hortonworks/cloudbreak

mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/test/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementServiceTest.java

Enable CDP_RAW_S3 by default in thunderhead mock.

CB-14107 Set CDP_RAW_S3 enabled locally

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/init.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_and_restore_dh.sh

Jira: https://jira.cloudera.com/browse/CDPSDX-3152
This is based off the work done by @Anupam-pandey, serving to add some easier methodology for the backup and restore functionalities on datahubs.
Specifically, I have added the script into Cloudbreak and connected it with Salt so that it will be copied over onto newly created clusters. I have tested the script on an existing datahub to ensure it works as desired.

CDPSDX-3152: Added salt script to facilitate database backup and restore on datahubs.

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProviderTest.java
template-manager-cmtemplate/src/test/resources/output/kafka-without-hdfs.bp

A new property 'hadoop.security.groups.cache.background.reload' was added to core_settings. If set to true, this enables a small threadpool of (default) 3 threads to fetch the security groups in the background, and this prevents the calling threads from blocking. Since this property is not present in the CSD, a safety valve was used.
The related test class is extended with Mockito to allow dependency injection in the provider that's needed for the unit tests.
Tested:
- Unit test
- Provisioned cluster
Note:
- A ticket was raised [OPSAPS-61614](https://jira.cloudera.com/browse/OPSAPS-61614) to add the property to the CSD. Once it's completed the safety valve can be removed.

CB-13938 Extend core_settings configuration provider with new property

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/BlackListedDownScaleRole.java

For NiFI scaling up:
if DATAHUB_FLOW_SCALING entitlement is not enabled (already done)
if runtime version is lower than 7.2.8 (already done)
For NiFI scaling down:
if DATAHUB_FLOW_SCALING entitlement is not enabled (already done)
if runtime version is lower than 7.2.11

CB-13522 Update scaling restrictions for NIFI template

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResourcesTest.java

User provides the encryption key url during creation of environment to enable disk encryption with CustomerManagedKey. The existence of key on Azure cloud is checked as part of this PR.
The getKey method in AzureClient either returns the keyBundle if the key exists or returns null.

CB-13810: Validate the existence of key url provided by user for Azure cmk

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpDiskResourceBuilder.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/multiaz/MultiAzCalculatorService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/multiaz/MultiAzValidator.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/InstanceMetaDataService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/instance/InstanceMetaDataServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/multiaz/MultiAzCalculatorServiceTest.java

- default to `CloudContext` based location if instance based not present
- when creating new instances during upscale, use the same logic to fill in zone data as during creation

CB-14026 Fix missing zone in GCP during FreeIPA upscale

---

ccm-connector/build.gradle
ccm-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/clusterconnectivitymanagementv2/ClusterConnectivityManagementV2Grpc.java
ccm-connector/src/generated/main/java/com/cloudera/thunderhead/service/clusterconnectivitymanagementv2/ClusterConnectivityManagementV2Proto.java
ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2JumpgateParameterSupplier.java
ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2ParameterSupplier.java
ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/InvertingProxyAndAgent.java
ccm-connector/src/main/proto/clusterconnectivitymanagementv2.proto
ccm-connector/src/test/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2JumpgateParameterSupplierTest.java
ccm-connector/src/test/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2ParameterSupplierTest.java
common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/CcmV2JumpgateParameters.java
common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/CcmV2ParameterConstants.java
common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultCcmV2JumpgateParameters.java
common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultCcmV2Parameters.java
common/src/test/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultCcmV2JumpgateParametersTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/userdata/UserDataService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/userdata/CcmUserDataServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/userdata/UserDataBuilderTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/userdata/UserDataBuilder.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/userdata/UserDataService.java
freeipa/src/main/resources/init/init.ftl
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/userdata/CcmUserDataServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/userdata/UserDataBuilderTest.java
freeipa/src/test/resources/azure-ccm-init.sh
freeipa/src/test/resources/azure-ccm-v2-init.sh
freeipa/src/test/resources/azure-ccm-v2-jumpgate-init.sh
freeipa/src/test/resources/azure-init.sh

For CCMv2 Jumpgate one-way TLS mode.
This is the priority mode, and is checked for validity first in the returned
values from InvertingProxy Agent registration (access key and secret key).
Then it falls back to the previous certificate + private key check.
User data script (init.ftl) got a new variable for all cases: environmentCrn,
and the 2 new variables for machine user access key+secret key for Jumpgate case.

CB-14123 Create logic to retrieve new machine user

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/recovery/bringup/DatalakeRecoveryBringupActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/recovery/bringup/DatalakeRecoveryBringupEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/recovery/bringup/DatalakeRecoveryBringupFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/recovery/bringup/DatalakeRecoveryBringupState.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/recovery/bringup/DatalakeRecoveryRestoreComponentsSuccess.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ImageComponentUpdaterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeRecoveryService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java
flow/src/main/java/com/sequenceiq/flow/cleanup/FlowCleanupJob.java
flow/src/main/java/com/sequenceiq/flow/repository/FlowChainLogRepository.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowChainLogService.java

Failures during upgrade might result in the following scenarios:
- neither the components nor the image are upgraded
- the components are upgraded but the image is not upgraded
Hence the first effective step of recovery process is to restore the original components from the original image.
That logic is in this commit.

CB-13541 - Restore components to before upgrade state

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/status/ExtendedHostStatuses.java
cluster-api/src/test/java/com/sequenceiq/cloudbreak/cluster/status/ExtendedHostStatusesTest.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java

- cert health check should be considered unhealthy only if CM reports `BAD` or `CONCERNING` state
- host health reason summary includes only the reason in case it's unhealthy
- cert check reason contains the original health summary from CM

CB-14143 Cert renewal pops up randomly

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeipaClientService.java
orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls

`/etc/ipa/default.conf` should always point to a valid FreeIPA server, so every `ipa` command would reach the same server
- during provisioning and when there is a change on FMS side the `default.conf` would be updated to a current server
- the choosing logic queries FMS for all instances and filters for ones in `CREATED` state and choose the first in alphabetical order
- if there is no instance in created choose the first one
- the file only edited if the FreeIPA join is successful and FMS is returning a response which is not 404

CB-14212 IPA server is not updated on CM nodes after FreeIPA repair

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java

If a node stuck in CREATED state, it does not have FQDN. It can cause the following:
New node(s) could not be added to the cluster. Reason Failed: Orchestrator component went failed in 60 min(s), message: com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: com.sequenceiq.cloudbreak.orchestrator.salt.domain.Pillar["json"]->java.util.Collections$SingletonMap["mount"]->java.util.HashMap["null"])

CB-14135 Filter out nodes without FQDN when composing pillars for mount

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/status/ExtendedHostStatuses.java
cluster-api/src/test/java/com/sequenceiq/cloudbreak/cluster/status/ExtendedHostStatusesTest.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java

- cert health check should be considered unhealthy only if CM reports `BAD` or `CONCERNING` state
- host health reason summary includes only the reason in case it's unhealthy
- cert check reason contains the original health summary from CMSee detailed description in the commit message.

Merge 2.48 to master

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java

The first step of the upgrade process is to deactivate and remove the unused parcels.
However, when the execution get's there we've already updated the database to use
the new image and new components including the CM server version. Due to this it
was incorrectly determined that the v45 API is available. As part of this PR I'm
reverting the change and always use the v31 API except when the post upgrade command
needs to be invoked.

CB-13844 only use the v45 client when the CM server is already upgraded

---

authorization-common/src/main/java/com/sequenceiq/authorization/service/RequestPropertyAuthorizationFactory.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceCrnAthorizationFactory.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceCrnListAuthorizationFactory.java
authorization-common/src/main/java/com/sequenceiq/authorization/utils/CrnAccountValidator.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/RequestPropertyAuthorizationFactoryTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/ResourceCrnAthorizationProviderTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/ResourceCrnListAuthorizationFactoryTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/utils/CrnAccountValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/service/integration/EnvironmentServiceIntegrationTest.java

Validate if the user's account is the same as the requested resources. If not throw an access denied exception. The exception intentionally doesn't contain information about the user crn or the resources crn since it can be a programming error and we don't want to leak resource crns to users in other accounts. When the account validation fails we log it on WARN level.

CB-14148 Validate user and resource account id in authz

---

core/src/main/resources/defaults/blueprints/7.1.0/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.0/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.1/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-sdx-micro.bp
core/src/main/resources/defaults/blueprints/7.2.13/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.13/cdp-sdx-micro.bp
core/src/main/resources/defaults/blueprints/7.2.13/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-sdx.bp

Adds the "atlas_ssl_exclude_protocols" : "TLSv1,TLSv1.1" setting to all SDX blueprints.
Tested via creating two datalakes (one 7.2.12, one 7.2.2) and verifying the service configuration
was set as expected, and the Atlas UI was accessible via Knox proxy.

CDPD-27965 Atlas is up but Knox throws service connectivity error trying to connect to Atlas

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterSecurityService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/certrotate/ClusterHostCertificatesRotationHandler.java

1. The following refactoring enables the cert renewal command to get the subAltName.
2. The interfaces must be refactored because the cluster-cm module does not have the ability to talk to the database.
3. A unit test is added to make sure that subAltName is indeed passed to the CM batch api call to rotate the certificate.

CB-14221 Cert renewal needs subAltName if it was set during provisioning

---

core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/ProfilerAdminConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/ProfilerMetricsConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/profilermanager/ProfilerAdminRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/profilermanager/ProfilerMetricsRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/profilermanager/ProfilerAdminRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/profilermanager/ProfilerMetricsRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/resources/input/profilermanager.bp

As Data catalog team is planning to add the Profiler Manager service into SDX blueprint. And it can be possible that the service can be part of GATEWAY/MASTER instance. We don't want to restrict it to the master node only. 
Testing:
1. I have done the testing by adding the profiler manager service into the GATEWAY instance of Medium DUTY SDX cluster, it worked.

CB-14213: Removed master group check in RDS config for ProfilerAdmin and ProfilerMetrics.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxSecurityTests.java

1. CB-14221 started passing the subAltName for the auto-tls renewal.
2. Though the certificate is not issued with the subAltName, the certificate is actually renewed successfully.
3. This means only Hue/Yarn to Oozie communication will fail if the certificates are renewed but they do not have subAltName. This scenario is only possible for DE HA clusters in 7.2.11.

CB-14120 Re-enabling certificate renewal tests for 7.2.12

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceMetaData.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java

If a PGW is unhealthy then we set another GW's status to unhealthy by mistake.

CB-14225 stopping primary GW node makes both of the GW nodes unhealthy

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxSecurityTests.java

This reverts commit 68442884f0851fb70f89de1dbe89ed83d1e4f9bc.

Revert "CB-14120 Re-enabling certificate renewal tests for 7.2.12"

---

structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/EnvironmentDetailsToCDPEnvironmentDetailsConverter.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/EnvironmentDetailsToCDPEnvironmentDetailsConverterTest.java
usage-collection/src/main/proto/usage.proto

CB-14274 Integrate with Telemetry solution for GCP CMEK
Adding a new property to CDPEnvironmentDetails, CDPEnvironmentGcpDetails which has entity bool resourceEncryptionEnabled, this is set only when encryptionKey is present.
As encryptionKey is present only when "CDP_CB_GCP_DISK_ENCRYPTION_WITH_CMEK" is enabled and encryptionKey is provided during environment creation, checking its presence is sufficient to know if user is using "GCP SSE with CMEK".
Thunderhead PR- https://github.infra.cloudera.com/thunderhead/thunderhead/pull/6016

CB-14274 Integrate with Telemetry solution for GCP CMEK

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterUpgradeInitHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterComponentUpdater.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterComponentUpdaterTest.java

Before this change when the upgrade flow started we removed the unused parcels from the CM server but those parcels are left in the database. This caused an inconsistent state because the Cloudbreak wanted to activate parcels which are not downloaded to the cluster.  
To solve this issue we need to remove those unused parcels from the clustercomponent table too.

CB-14234: Remove unnecessary components from the database in the begining of the upgrade

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/config/AwsConfig.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsTagValidatorTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/conf/AzureConfig.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/conf/GcpConfig.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpTagValidatorTest.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/config/OpenStackConfig.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/TagValidatorTest.java

Updated AWS, Azure, GCP and OpenStack tag specifications:
- Reflect the latest restrictions (see links in Jira)
- Fixed '-' issue where it was interpreted as a range
- Leading and trailing spaces are restricted

CB-14129 Update tag specifications

---

core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering.bp

[DISTX-705](https://jira.cloudera.com/browse/DISTX-705)
Fixes for CDPD-13652 in 7.2.12 introduced disk buffering for abfs streams. This also requires cleaning up the buffer directory as part of failed yarn jobs. Hence configuring following in 7.2.12 DE templates
fs.azure.buffer.dir=${env.LOCAL_DIRS:-${hadoop.tmp.dir}}/abfs
Testing done:
1. Have created a DE cluster using a modified 7.2.12 template that includes above mentioned config changes. Cluster creation was successful on Azure.
2. Mehakmeet ran a job and killed it mid-way, he noticed buffer dir was cleaned up correctly.

DISTX-705 Set Azure buffer dir to Yarn local dir

---

core/src/main/java/com/sequenceiq/cloudbreak/san/LoadBalancerSANProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/san/LoadBalancerSANProviderTest.java

1. Load balancer SAN needs to be generated only for CDH-7.2.11+/CM-7.4.3+ clusters which are created newly.
2. The only reliable mechanism for finding such clusters excluding the upgrade is to get the version number of CDH from the blueprint text.
3. This will avoid problems generated during the upgrade of older clusters to 7.2.11+/7.4.3+ where some features like case-insensitive DNS are handled correctly only in 7.2.11+/7.4.3+ and not all the hosts have this version.
4. This is how the Oozie HA feature setup is also done in LoadBalancerConfigService.

CB-14221 Consistently choose when to provide load-balancer SAN

---

template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/HostgroupView.java

**Background**
Follow-up to ENGESC-10576. According to https://jira.cloudera.com/browse/ENGESC-10576?focusedCommentId=4771478&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4771478 , there is an NPE in the `TreeSet` constructor. The complete code flow is:
* `RotateClusterCertificatesFlowEventChainFactory.createFlowTriggerEventQueue()` (core) -> `SaltUpdateFlowConfig` -> `SaltUpdateActions.uploadRecipesAction()` (core)
** The scenario encountered in ENGESC-10576  most probably involved the above code path.
** There are further irrelevant trigger procedures that can also lead to `UploadRecipesHandler` invocation in other places:
*** `ClusterCreationFlowConfig` -> `ClusterCreationActions.uploadRecipesAction()` (core)
*** `ClusterOperationService.updateSalt()` …

CB-14281 Eliminate NPE in HostgroupView constructor due to null FQDN

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterShape.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/MultiAzDecorator.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/MultiAzDecoratorTest.java

Enable multi-AZ only on HA Datalakes. It doesn't make sense to use multiple subnet on non-HA Datalakes as it perform worse and more expensive.
+ one more UT for @topolyai5 's gateway subnet selector logic 😄

CB-14257 enable multi-AZ only on HA Datalakes.

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/info/model/RightV4.java
authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
authorization-common/src/main/resources/legacyRights.json
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentOpDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/azure/UpdateAzureResourceEncryptionParametersRequest.java
environment-api/src/test/java/com/sequenceiq/environment/api/v1/environment/model/request/azure/UpdateAzureResourceEncryptionParametersRequestTest.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/UpdateAzureResourceEncryptionDto.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/ResourceEncryptionDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java
environment/src/test/java/com/sequenceiq/environment/environment/dto/UpdateAzureResourceEncryptionDtoTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentModificationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorServiceTest.java

CB-13134: Set encryption key for an existing env that does not yet have encryption enabled.
CB-9920 introduced the encryption of Azure Managed disks using Customer Managed Key. This feature is behind an entitlement "CDP_CB_AZURE_DISK_SSE_WITH_CMK" and can be used for new environments.
This PR allows to set the encryption key for existing environments such that the new disks launched as part of new Datahubs will be encrypted with Customer Managed Key. All the previously launched disks/resources would remain encrypted by Azure's platform managed key.
Thunderhead PR - https://github.com/hortonworks/cloudbreak/pull/11225 , Once CB changes are merged, will update the parent/pom.xml in thunderhead PR and open it for reviews.
Validated these changes with :
-  Existing environment
- Using wrong …

CB-13134: Set encryption key for an existing env that does not yet have encryption enabled 

---

.github/CODEOWNERS

Goal is for to team to be more involved in code review and provide better guidance for fellow developers.
- Raven team should review datalake and datalake-api modules
- Raven team should review datalake blueprint changes
- Raven team should review quartz and sync job related PRs
- Raven team should review how Controllers are authorized

CB-14299 adding experimental .CODEOWNERS for raven team. 

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentValidationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentFlowValidatorService.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyArnValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyArnValidatorTest.java

Reverts hortonworks/cloudbreak#11392
@satyabollineni this PR is being reverted because causing NPE on environment creation when environment request does not contain any `awsDiskEncryptionParameters` which is not a mandatory field. So this code would cause many environment creation issues
**Faulty object reference in `EncryptionKeyArnValidator`:**
`String encryptionKeyArn = parametersDto.getAwsParametersDto().getAwsDiskEncryptionParametersDto().getEncryptionKeyArn();`

Revert "CB-13464:Add validation to check if the mentioned Key exists in AWS"

---

README.md
orchestrator-salt/src/main/resources/salt/salt/nginx/conf/clouderamanager-ssl-user-facing.conf

> CB-14353 disable direct CM UI debug path in NGiNX configuration
It has been cherry-pick-ed from 2.49.0 line of Cloudbreak.

CB-14353 disable direct CM UI debug path in NGiNX configuration.

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeDiskSpaceValidationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/DiskSpaceValidationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/ParcelSizeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/ParcelUrlProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeDiskSpaceValidationHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/DiskSpaceValidationServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/ParcelSizeServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/ParcelUrlProviderTest.java

Problem
If you used a custom image catalog for your cluster the disk space validation tried to find the target image in the default image catalog.
Solution
The validation flow using the current image catalog to retrieve the target image.

CB-14327: Use the current image catalog to get the target image for disk space validation.

---

environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/FreeIpaResponse.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/FreeIpaConverter.java

in the case of SDX response, the related field is already there. For DH it is not relevant since the network setup implicitly tells that whether the cluster is deployed in a multi az way or not.
This pr is a stepping stone to extend the CLI responses as well

CB-12777 - add multiAz enablement for freeipa response in environment response

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/BootstrapMachineHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyServiceTest.java

**Changes:**
- re-register cluster into ClusterProxy after salt file update
- modify `BootstrapMachineHandler` to extends the new `ExceptionCatcherEventHandler`
- modify ClusterProxy endpoint registration for CM not to be based on CM direct access for no CCM(ClusterProxy only) and CCMv1, it uses the CCMv2 approach which registers the CM endpoint to port 9443 over mTLS if is applicable - this means that dependent libraries must not create any integration because the CM paths remain the same

CB-14473/CB-14474 modify ClusterProxy endpoint registration for CM

---

orchestrator-salt/src/main/resources/salt/salt/post-recipes/scripts/createuserhome.sh

Before my change:
```
ls -l /tmp/cloudbreak-webhdfs.cookies
-rw-r--r-- 1 root root 406 Oct 26 19:02 /tmp/cloudbreak-webhdfs.cookies
```
After my change:
```
ls -l /tmp/cloudbreak-webhdfs.cookies
-rw------- 1 root root 406 Nov  2 13:13 /tmp/cloudbreak-webhdfs.cookies
```

CB-14688: Remove world-readable permissions on cloudbreak webhdfs token

---

structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToClusterShapeConverter.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToStatusDetailsConverter.java
structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToClusterShapeConverterTest.java
structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToStatusDetailsConverterTest.java

Trimming stack and cluster status reason strings at 1500 chars and only including instance group detail json strings (definitionDetails) which are maximum of 3000 chars. This way the overall max length of an events stays around 8000 chars so it won't be separated by the log collecting pipeline.

CB-14753 Limit long string fields in telemetry events

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnVolumeConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmHostGroupRoleConfigProviderProcessorTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnVolumeConfigProviderTest.java

CB-14640: Fix yarn_nodemanager_log_dirs to be ephemeral volumes if present
If Instance has ephemeral volumes which are mounted, temporary data like `yarn_nodemanager_local_dirs` and `yarn_nodemanager_log_dirs` should use ephemeral volumes.

CB-14640: Fix yarn_nodemanager_log_dirs to be ephemeral volumes if present

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Jira: https://jira.cloudera.com/browse/CB-14692
Simply added the Knox keytab as a choice to the backup/restore scripts.
Verified that this enables successful database backups on Azure and AWS DataHubs.

CB-14692: Added knox keytab use to backup/restore scripts in order to resolve authentication issues on DataHubs

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/BasicEnvironmentVirtualGroupTest.java
integration-test/src/main/resources/application.yml

User groups are provider independent in L0 test cases. So I've moved these variables out from AWS provider related parameters.

CB-14740 Fix external test group variables for BasicEnvironmentVirtualGroupTest

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeFlowConfig.java

A common flow in both DL and DH upgrade had Datalake in its name.

CB-14681 DH upgrade retry event says "Upgrade Datalake cluster"

---

datalake-dr-connector/README.md
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxRecoveryController.java
datalake/src/main/java/com/sequenceiq/datalake/service/recovery/RecoveryService.java
datalake/src/main/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryService.java
datalake/src/test/java/com/sequenceiq/datalake/service/recovery/RecoveryServiceTest.java

Closes [CB-14398](https://jira.cloudera.com/browse/CB-14398).
Adds a RecoveryService which chooses one of Resize or Upgrade recovery.
Change the recovery controller to call into the Recovery Service.
This is small PR, additional changes are forthcoming, depending on results of design doc review.

CB-14398 - Add a RecoveryService to choose between Upgrade and Resize recoveries.

---

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/FreeIpaApi.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaModelDescriptions.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/describe/DescribeFreeIpaResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/configuration/EndpointConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverter.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverterTest.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/RedbeamsApi.java

* Add new property `DescribeFreeIpaResponse.tunnel` (`freeipa-api`). It is copied as-is from `Stack.tunnel` (`freeipa`).
* `freeipa` Swagger fixes:
* Add API description.
* Correct base path so that Swagger UI becomes usable.
* Add `ApiKeyAuthDefinition` to `FreeIpaApi` (`freeipa`) so that user authn information can be entered in Swagger UI. (Solution has been adapted from `redbeams`.) This extra header is currently only enabled for `FreeIpaV1Endpoint`.
* Fix spelling errors in several places.
* Testing:
* UT.
* `freeipa` Swagger UI in local CB.

CB-14572 Add TunnelType to FreeIPA response

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/service/AwsResourceNameService.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilderTest.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/context/ResourceBuilderContext.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/group/GroupResourceService.java
core/src/main/resources/schema/app/20211105113320_CB-14758_update_AWS_security_group_resources_to_have_instance_group_name_reference_based_on_resource_name.sql
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXCreateAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/FetchPreferredSubnetForInstanceNetworkIfMultiAzEnabledAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/distrox/AvailabilityZoneAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/DistroXTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDtoBase.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests-for-native.yaml

* native upgrade
* native repair
Some minor fixes the AWS_NATIVE resource builders.
Environment name check moved into the create action instead of the TestDto's valid method in the IT. This was neccessary because we cannot prepare properly the distrox object. In this case I wnat to use an existing env with name, but I cannot set because the env was required in prepare time instad of the execution

CB-14758 Added tests:

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/customimage/CustomImageCatalogV4CreateImageRequestToCustomImageConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/customimage/CustomImageCatalogV4UpdateImageRequestToCustomImageConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/DefaultImageCatalogService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/customimage/CustomImageCatalogV4CreateImageRequestToCustomImageConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/customimage/CustomImageCatalogV4UpdateImageRequestToCustomImageConverterTest.java

This task is the second step to refine the datalake and datahub operations based on the  CB-14390. This must be done in this order due to backward compatibility. Actually, in this step we should remove the business logic corresponding to the datahub/datalake enumerations, however, it is important that the proper enumeration values cannot be deleted.

CB-14464: Remove the obsoleted logic regarding to DATAHUB/DATALAKE image types

---

docker-autoscale/Dockerfile
docker-cloudbreak/Dockerfile

Java 11.0.5 have to be used as base docker image because of some TLS issues

Java 11.0.5 have to be used as base docker image because of some TLS issues

---

cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/testcontext/TestApplicationContext.java
common/src/main/java/com/sequenceiq/cloudbreak/altus/AltusDatabusConfiguration.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/DataBusEndpointProvider.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/TelemetryClusterDetails.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/common/TelemetryCommonConfigService.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigService.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigView.java
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/DataBusEndpointProviderTest.java
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/DiagnosticsFlowService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/TelemetryApiConverterTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/telemetry/TelemetryConfigService.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverterTest.java
orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/databus_metering.conf.j2
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/databus_monitoring.conf.j2
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/output_databus.conf.j2
orchestrator-salt/src/main/resources/salt-common/salt/nodestatus/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/telemetry/settings.sls

details:
- add new configuration (that should be passed in cloud-services-infra + dps-k8s) -> as thunderhad-sigmadbus is part of CSI, pass the s3 bucket name for dbus.
- use env region option for fluentd dbus plugin, if region is not used (or us-west-1 is passed), it will use the old dbus api, otherwise it will use the new /api/v1/dbus one
- update Uts

CB-11919. Support multi region CP for databus clients

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/dr/BackupRestoreV4RequestValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/BackupRestoreSaltConfigGenerator.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/dr/BackupRestoreV4RequestValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/BackupRestoreSaltConfigGeneratorTest.java

Jira: https://jira.cloudera.com/browse/CDPSDX-3158
Main objective of this change is to add GCP to the supported cloud providers for backup/restore. I also went ahead and changed some of the current logic for validating the URI scheme of the cloud platform to make it cleaner, albeit at the cost of a little worse performance so feel free to let me know if it's worth changing back. 
Thanks!

CDPSDX-3158: Added GCP to list of supported cloud providers for Datalake-DR.

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/config/RootCertRegisterService.java

If the CA cert fetching from FreeIPA fails this annotation would ensure to retry.
This effects the FreeIPA provision as well as CA cert fetching in case it hasn't been stored in the database yet.

CB-13376 Add `@Retryable` annotation for CA certificate registration

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/recovery/RecoveryStatus.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/recovery/RecoveryValidationV4Response.java
core-api/src/test/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/recovery/RecoveryValidationV4ResponseTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterRecoveryService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterRecoveryServiceTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxRecoveryEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/service/FreeipaService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/start/SdxStartService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/stop/SdxStopService.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/recovery/SdxUpgradeRecoveryService.java
datalake/src/test/java/com/sequenceiq/datalake/service/FreeipaServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/start/SdxStartServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/recovery/SdxUpgradeRecoveryServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxTests.java

This commit
- introduces FreeIPA validation during recovery() and validateRecoverable() calls on CB side
- refactors FreeIPA validation on SDX side

CB-13472 - Validate for stopped/unreachable FreeIPA

---

core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeServiceTest.java

For any call to `stackService.getByCrn` where subsequent code can handle the case that the returned
datalake is 'null', replace that call with `stackService.getByCrnOrElseNull`. This will eliminate
the errors deleting a datahub when the attached datalake cannot be found.
Tested with unit tests and by manually create a DL+DH, then removing the DL CRN from the database so
it could not be found. Verified the DH, DL, and env could all be successfully deleted.

CB-14558 Datalake deletion stuck, force delete does not work

---

integration-test/Makefile
integration-test/scripts/compress-results.sh

- to have longer test result retention time
- originally wanted this to be included as the last step of test execution but if we want to compress app logs, we need to wait for container stop, otherwise we'll get this:
```
tar: integcb/logs/cloudbreak/cloudbreak.log: file changed as we read it
make: *** [compress-results] Error 1
Build step 'Conditional steps (multiple)' marked build as failure
```

CB-14839 suites_log and integcb/logs should be compress to save space

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/cluster/DistroXUpgradeTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/search/KibanaSearchUrl.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/DistroXOSUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/cloudbreak/CloudbreakWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/datalake/DatalakeWaitObject.java
integration-test/src/main/resources/testsuites/e2e/l0promotion/distrox-os-upgrade-tests.yaml

Create new data hub (distrox) OS upgrade L0 test(s) at [Cloudbreak API test project](https://github.com/hortonworks/cloudbreak/tree/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion).
Test duration must be take into consideration:
- base (1:master, 1:compute, 3:workers) test takes more than 3 hours
- 50 workers test takes around 4 hours
- 200 workers test takes around 7 hours
So I was implemented the base case for the test project.
**NOTE:**
- We need to wait the [OPSAPS-62124](https://jira.cloudera.com/browse/OPSAPS-62124) to be resolved
- In the future if we would like to run this automated test on a daily basis, we need to create a separate `Longrunning` Jenkins job for this. This can be part of a follow up JIRA.

CB-14540 Base distrox OS upgrade L0 test

---

integration-test/src/main/resources/application.yml

HIVE Metastore install fails with 'Cannot allocate memory' error,
bumped instance size to 2xlarge, same as for other tests.

CB-13974 Same size instance types for ephemeral tests too

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpMetadataCollector.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/GCPLoadBalancerMetadataCollectorTest.java

one line change to set the LB name parameter plus testing

[CB-13177] missing resource identifier for GCP LB

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-datalake-backup-policy.json

Change BACKUP_BUCKET to BACKUP_LOCATION_BASE to be consistent with https://raw.githubusercontent.com/hortonworks/cloudbreak/master/cloud-aws-cloudformation/src/main/resources/definitions/aws-datalake-backup-policy.json
See https://jira.cloudera.com/browse/CB-14907

Update the DL backup policy

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/ephemeral/DistroXUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/action/ClouderaManagerClientActions.java

CM responds with a server error, when the test attempts to verify Yarn configs.
Putting the test on ignore, while this issue is fixed.
Added response body to error logs in the e2e CM client.

CB-14916 Ignore DataHub Upgrade test with ephemeral caching on

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/EnvironmentClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/FreeIpaClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/MicroserviceClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RedbeamsClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SdxClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UmsClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/ResourceAwait.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitOperationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/cloudbreak/CloudbreakWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/datalake/DatalakeWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/environment/EnvironmentWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/instance/FreeIpaInstanceWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/redbeams/RedbeamsWaitObject.java

The reason of the failure: when an instance is stopped on the cloudprovider and the CM is not reachable, then SDX syncer maps this to CLUSTER_UNREACHABLE. In the test this is a failure state, leading to an immediate termination of the test.
In this PR the await is further customized: it not only waits for a status, but the test writer can set up some tests to ignore some of the failure states. This is only fully implemented for SDX.

CB-14893 [e2e] The repair tests were failing, some of them constantly.

---

integration-test/src/main/resources/testsuites/e2e/azure-longrunning-e2e-tests.yaml

Disabling due to E2E run http://ci-cloudbreak.eng.hortonworks.com/job/api-longrunning-e2e-azure/1276/

CB-15109 - [e2e] AZURE SDX upgrade recovery test failure

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/EmbeddedDatabaseConfigProvider.java
orchestrator-salt/src/main/resources/salt/salt/postgresql/init.sls

CB-8981 We should move files like /var/log/init-services-db-executed to another place
Cluster creation:
* In case of external db:
** init-services-db-remote-executed file will be created in /opt/salt/scripts directory
* In case of embedded db on attached disk:
** pgsql_listen_address_configured, pgsql_max_connections_configured will be created in /dbfs/pgsql/scripts directory
** init-services-db-executed will be created in /dbfs/pgsql/scripts directory
* In case of embedded db on root disk:
** pgsql_listen_address_configured, pgsql_max_connections_configured will be created in /opts/salt/scripts directory
** init-services-db-executed will be created in /dbfs/pgsql/scripts directory
In case of old cluster upgrade (Salt update) the above mentioned files will be moved to the right place from …

CB-8981 We should move files like /var/log/init-services-db-executed to another place

---

core/src/main/resources/application.yml

CB-14899 Cannot upgrade the cluster because the root disk ran out of space
Turn on upgrade validation flow by default.

CB-14899 Cannot upgrade the cluster because the root disk ran out of space

---

core/src/main/resources/application.yml

Disk types for embedded DB will be changed to SSD on all cloudproviders.

CB-14874 Embedded DB runs on spinning disks

---

integration-test/scripts/compress-results.sh

- please check integration-test build results, it now has compressed logs and suite logs
- ~1 magnitude less disk space, so we can increase build result retention 10 fold, but we should start catious
- will apply same post build step to e2e tests
``` 
[0;92m+++ INTEGRATION TEST RESULTS COMPRESSED SUCCESSFULLY AND TOOK 41 SECONDS+++
```

CB-14839 test actual compress-results.sh

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResourcesTest.java

CB-14873: Environment provisioning for Azure CMK environments is failing without additional access policies 
Revert "CB-13810: Validate the existence of key url provided by user for Azure cmk"
This reverts commit c90356f966cb9737ff1373aafbc2311213ec88ca.
CB-13810 added a validation to check the existence of encryption key in KeyVault. It requires "get" access policy on the credential app which is used to create azure environment. If customer's keyVault is behind firewall the CDP_CIDRs needs to be whitelisted. As customer is not ok in whitelisting public-IPs to their firewalls, this changes is being reverted.

Revert "CB-13810: Validate the existence of key url provided by user for Azure cmk"

---

integration-test/src/main/resources/testsuites/e2e/azure-longrunning-e2e-tests.yaml

As the fix for E2E test (https://github.com/hortonworks/cloudbreak/pull/11815/commits/c972e293c9e5128882605399073c24432e66e3f3) is merged to master the test  can be re-enabled.
This reverts commit 82640202e726793bd8069fca27bc82a63dab541d.

Revert "CB-15109 - [e2e] AZURE SDX upgrade recovery test failure"

---

cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/loadbalancer/service/component/YarnLoadBalancerComponentFactoryService.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/loadbalancer/service/launch/YarnLoadBalancerLaunchService.java

1. The new image is built and published.
2. Once it is tested in mow-dev new image will be published which will be common for DE HA and other clusters like Datalake.
3. During that time the special handling of DE HA will be removed.
4. This is the fastest way to roll out this feature without disrupting the L0 and other testing that depends on this load-balancer.

CB-14833 Enable Oozie HA testing in YCloud

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelDecommissionService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelDecommissionServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelServiceTest.java

When we try to remove unused parcels from the CM server, the used components will be figured out from the blueprint. Therefore, if a custom parcel is not present in the blueprint, it will be deleted.
Based on the current image we're collecting the possible prewarm parcels. If a parcel in the CM server is not present in the prewarm parcel list we're skipping to remove it.

CB-15272: Skip custom parcels when removing unused parcels from Cloudera Manager

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/AbstractMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/EvaluatorExecutor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/CloudbreakCommunicator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandler.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java
autoscale/src/main/java/com/sequenceiq/periscope/utils/StackResponseUtils.java
autoscale/src/main/resources/logback.xml
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ScalingRequestTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/AutoscaleV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/base/ScalingStrategy.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/request/UpdateStackV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/HostGroupAdjustmentV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AutoscaleV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/StackCommonServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java

by Periscope / other components.
- Additionally fixes a few unit tests.
- Does not introduce an API for stop without an instanceId set.
- Temporary APIs continue to exist. To be cleaned up later.

CB-15138. Cleanup / define APIs for stop-start scaling which can be used

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerCloudStorageServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerCloudStorageServiceConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/StorageLocationView.java

If the default backup location is set for an environment, pass that to Ranger in the cloud_storage_paths
field as "BACKUP_LOCATION=\<backup location>". This information will be used to construct the RAZ
backup/restore data lake policy.
Tested via unit tests and in local CB.
I added this logic outside of the settings in the cm-cloud-storage-location-specification.json because there is no specific CM service setting associated with the backup location, so there is no reason to provide information about it outside of the property name and value.

CB-14974 Pass DL backup path to CM

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverterTest.java

Tested this with a custom template where encryption type is set to null and DH creation success.

CB-15245:Fix NPE in create-aws-cluster when encryption type set to null

---

datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachActions.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseService.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/DatabaseServerV4Endpoint.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/Notes.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/OperationDescriptions.java
redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java
redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java

**Behavior Observed:**
Database creation for new resized DL, never completed. It always timed out.
**Issue-1:**
One of the steps performed while detaching the data lake is updating the CRN of the cluster with the newly created CRN so that the new datalake that is being created can use the same CRN as the original one.
When this is done, the cluster CRN saved in DatabaseServerConfig should be updated otherwise, there will be issues while creating a new database using the same cluster CRN.
**Issue-2:**
When RedbeamsCreationService.launchDatabaseServer is invoked to create a new database while resizing, it returned an already existing database that was in a stopped state. Polling task that is created to poll the status of creation never completes as the database status would not change to …

CDPSDX-3198: resize data lake provisioning fails with external database

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/cruisecontrol/CruiseControlGoalConfigs.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/cruisecontrol/CruiseControlRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/cruisecontrol/CruiseControlRoleConfigProviderTest.java

Starting from CDH>=7.2.14 Cruise Control config provider will set the supported goals list too beside the other goal sets.
When Cruise Control csd is modified in the CM with new goal lists then the Cloudbreak's CC sometimes brake down since there are some missing goal list overrides in the CC config provider. After this change the CM modification won't take affect on the Cloudbreak's CC so the developers will be able to create separate PRs and they won't break any components by modifying another.
Tested:
- with unit tests,
- manually on a provisioned cluster.

CB-15334 Add missing goal lists to Cruise Control config provider

---

core-api/src/main/resources/definitions/exposed-services.json
core-api/src/test/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollectorTest.java
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_token.xml.j2

Starting from CDH>=7.2.14 Kafka Connect will be a part of Cloudbreak. This commit add the Kafka Connect endpoint to Knox.
Tested:
- with unit tests,
- manually on a provisioned cluster.

CB-14522 Add Kafka Connect endpoint to Knox

---

structuredevent-service-legacy/build.gradle
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToClusterShapeConverter.java
structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToClusterShapeConverterTest.java
usage-collection/src/main/proto/usage.proto

CB-13832: Add metrics on services installed on Datahub cluster
This PR adds cluster template details - services installed on datahub cluster - to CDPClusterShape to make it available to EDH metrics.

CB-13832: Add metrics on services installed on Datahub cluster

---

flow/src/main/java/com/sequenceiq/flow/converter/OperationDetailsPopulator.java
flow/src/test/java/com/sequenceiq/flow/converter/OperationDetailsPopulatorTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/operation/OperationService.java

details:
- if the operation is available in the flow stats table, it always overrides the step based progress with the time based progress.
- expectation: if the time based progress show higher value than the step based, use the step based

CB-15352. Fix date/step based progress calculation (that shows 99%).

---

common-model/src/main/java/com/sequenceiq/common/api/type/ImageType.java

No we can can remove the proper DATAHUB and DATALAKE enumeration values, instead of these the RUNTIME value has been provided previously. Follow up task of CB-14464.

CB-14466: Remove the obsoleted DATAHUB/DATALAKE enum values

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentWithCustomerManagedKeyTests.java
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml

CB-11741: Nigthly e2e Azure tests should use encryption
This PR adds the tests for Azure cloud SSE with CMK feature. 
Encryption key **https://cloud-jenkins-secrets.vault.azure.net/keys/key-azure-cmk-e2e/c1a1df3097f441b4a10cfcb7c8a3bcd9** is created in **cloud-daily** resource group, which needs to have access policy configured for the credential app used to create test environments. For details, Please refer - [Azure cmk permissions](https://docs.google.com/document/d/1DTIB2Wb-CX4HBFOjyWGnvHNteOwTx3TL3608LFUDxEc/edit#heading=h.s0bspwrofjfh) and
[Access policies required](https://docs.google.com/document/d/1DTIB2Wb-CX4HBFOjyWGnvHNteOwTx3TL3608LFUDxEc/edit#heading=h.fkbtsx9frdiu)

CB-11741: Nigthly e2e Azure tests should use encryption.

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterCommissionService.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterDecomissionService.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/exception/ClusterManagerCheckedException.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterCommissionService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecomissionService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerCommissioner.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerConnector.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/NoExceptionOnTimeoutClouderaManagerListenerTask.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/BaseClouderaManagerCommDecommTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterCommissionServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerCommissionerTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartds/StopStartDownscaleFlowService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/StopStartUpscaleCommissionViaCMHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java

- Moves temporary code from the decommissioner classes into commissioner
classes, with some improvements.
- Adds unit tests for the same.

CB-15376. Move CM commissioning into CMCommissioner classeses.

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxUpgradeRequest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/flow/SdxReactorFlowManagerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java

Jira: https://jira.cloudera.com/browse/CB-14924
Just added a new field in the request which is checked by the flow trigger. I also had to modify the tests, and did some slight cleanup of the classes I worked in.
This has not been tested, I will do that locally soon, but wanted eyes on the change.

CB-14924 : Added boolean option for skipping datalake backup during upgrade process.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentWithCustomerManagedKeyTests.java
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml

CB-11741: Nigthly e2e Azure tests should use encryption
This PR adds the tests for Azure cloud SSE with CMK feature.
Encryption key https://cloud-jenkins-secrets.vault.azure.net/keys/key-azure-cmk-e2e/c1a1df3097f441b4a10cfcb7c8a3bcd9 is created in cloud-daily resource group.

CB-11741: Nigthly e2e Azure tests should use encryption

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterUpscaleDownscaleTest.java
integration-test/src/main/resources/testsuites/v4/mock/longrunning-mock.yaml

Recently there was a production outage caused by large memory demand, that in turn was caused by DB queries with many (~3500) terminated instancemetadata (imd) entries. Terminated imds were left in place by downscale. Frequent scaling activities thus led to the accumulation of many imds, that increased the memory pressure. In production the cloudbreak container has ~2G of memory, and that is easily exhausted by a query with several 1000 imds.
This commit introduces a mock test with a large number of scaling, to test that cloudbreak will not run out of memory, even if more than 10.000 imd is accumulated for a cluster in cbdb imd table. Currently memory pressure is not measured, the test relies on the test environment maximizing cloudbreak memory in the same amount that is available on …

CB-14961 Have a mock test for a large cluster

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxBackupAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxBackupInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxRestoreInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxSyncAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxSyncInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java

Our [MOW-Dev API E2E projects](http://ci-cloudbreak.eng.hortonworks.com/job/mow-dev-e2e/) are failing, because of [CB-14825 Datalake backup flow has been finalized with failed status](https://jira.cloudera.com/browse/CB-14825).
While this issue is going to be investigated then fix, I'm increased the CM service wait timeout as a possible workaround. We had similar solution previously at [CB-13322 Data Lake database backup request failed: 409, Could not connect to Solr OR ATLAS_ENTITY_AUDIT_EVENTS_TABLE: HBase failure: Failed to take snapshot](https://jira.cloudera.com/browse/CB-13322)

CB-14825 Increase wait timeouts for SDX backup and restore

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxResizeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/ResourceAwait.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitService.java

**Root cause:** While performing DL resize there will be a brief period of time where there will not be any DL for a given environment.
This could result in a 404 error when the tests are polling for the status of the datalake for a sort interval.
Made necessary changes to test framework to perform retries when there are failures. Even these retries would be limited by the total timeout that is configured.

CB-15416: Fix the flaky DL resize tests.

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/RemoveReplicationAgreementsHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaTopologyService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/upgrade/UpgradeValidationService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaTopologyServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/upgrade/UpgradeValidationServiceTest.java

- modified validation to allow upgrade up to 3 instances
- refactored `FreeIpaTopologyService`
Tested upgrade for FreeIPA with 3 instances, and validated topology is fine when 4 instances are present. Also started DL after upgrade.

CB-15368 Enable FreeIPA HA upgrade

---

integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml

Temporarily disable the new e2e FreeIpaRebuildTests test because of
intermittent failures.

CB-15431: Temporarily disable FreeIpaRebuildTests

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxUpgradeRequest.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java

Jira: https://jira.cloudera.com/browse/CB-15467
Thunderhead was naming the field `backupSkipped` instead of `skipBackup` which would result in issues once a request was sent by Thunderhead to CB.
This should fix it.

CB-15467: Changed SdxUpgradeRequest field skipBackup to not have a isBackupSkipped field which was messing up Thunderhead generation.

---

config/idea/inspections.xml
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/E2ETestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/util/TagsUtil.java
integration-test/src/test/java/com/sequenceiq/it/util/TagsUtilTest.java

`test-name` tag value has been limited to 63 characters long in case of every tests. This is not appropriate, because of the Azure tags' keys are limited to 128 characters not 63 and the same is true for AWS as well. Tag key and value length limitation is only required for [GCP cloud labels](https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements).
One of our E2E test case name was too long: `testEnvironmentWithCustomerManagedKeyAndEncryptionKeyResourceGroupSpecified`, because of this the `test-name` tag validation is failing, because of splitting at 63 character.
So I've introduced a new IDE inspection rule for test method names. Furthermore I've refactored the [TagsUtil](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/ …

CB-15396 Fix TagsUtil applied length restrictions for Azure and AWS

---

config/idea/inspections.xml
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/E2ETestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/util/TagsUtil.java
integration-test/src/test/java/com/sequenceiq/it/util/TagsUtilTest.java

This reverts [92238c686e](https://github.com/hortonworks/cloudbreak/commit/92238c686e953bf8c3bd7f6021e075fa687ec3ab) and [335592b531](https://github.com/hortonworks/cloudbreak/commit/335592b531adb1603df4a17166d8a6e55e2a2230)

Revert "CB-15396 Fix TagsUtil applied length restrictions for Azure and AWS"

---

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverterTest.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StackDetails.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredSyncEventToCDPSyncDetailsConverter.java
structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredSyncEventToCDPSyncDetailsConverterTest.java
usage-collection/src/main/proto/usage.proto

Sync report is extended with database type in EDH report:
* new member in StackDetails: databaseType
* new member in usage proto: CDPSyncDetails.databaseType
* values: ON_ROOT_VOLUME, ON_ATTACHED_DISK, EXTERNAL_DB, UNKNOWN
* was tested on gcp, azure, aws; with root volume, attached disk and external db

CB-15359 Extend EDH sync report with database type

---

integration-test/scripts/check-results.sh

Our E2E tests are running in parallel by 8 threads (with the help of [TestNG parallel attribute](https://testng.org/doc/documentation-main.html#parallel-running)):
```
parallel="methods": TestNG will run all your test methods in separate threads. Dependent methods will also run in separate threads but they will respect the order that you specified.
```
This helps us to reduce the 'execution time' as tests are executed simultaneously in different threads.
Beyond this we applied a 100 minutes timeout for our test cases by default, on this way we can guarantees that none of the threads will block on a stuck test thread forever.
Unfortunately test case's thread is terminated if it takes longer than it's timeout setting. I found some similar issues at TestNG:
- [TestNg not generating reports …

CB-15495 TestNg reports are not generated for timed out test cases

---

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/InstanceGroupToInstanceGroupDetailsConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/converter/InstanceGroupToInstanceGroupDetailsConverterTest.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/InstanceGroupDetails.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToCDPClusterShapeConverter.java
structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToCDPClusterShapeConverterTest.java

… … a targeted reduction of data, in order to ensure that we can stay in the 12k size limit that is set today on fluentd.

CB-15503 Useful data is disappearing from EDH. With this commit we do

---

integration-test/scripts/check-results.sh

Our E2E tests are running in parallel by 8 threads (with the help of [TestNG parallel attribute](https://testng.org/doc/documentation-main.html#parallel-running)):
```
parallel="methods": TestNG will run all your test methods in separate threads. Dependent methods will also run in separate threads but they will respect the order that you specified.
```
This helps us to reduce the 'execution time' as tests are executed simultaneously in different threads.
Beyond this we applied a 100 minutes timeout for our test cases by default, on this way we can guarantees that none of the threads will block on a stuck test thread forever.
Unfortunately test case's thread is terminated if it takes longer than it's timeout setting. I found some similar issues at TestNG:
- [TestNg not generating reports …

CB-15495 TestNg E2E tiemout validation if INTEGRATIONTEST_TIMEOUT_E2E_CHECK set

---

core/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/7.2.13/cdp-flow-management-small.bp
core/src/main/resources/defaults/blueprints/7.2.13/cdp-flow-management.bp
core/src/main/resources/defaults/blueprints/7.2.14/cdp-flow-management-small.bp
core/src/main/resources/defaults/blueprints/7.2.14/cdp-flow-management.bp

Testing steps
- Create an environment with DataLake 7.2.12
- Create a DataHub cluster with Flow Management 7.2.12 blueprint.
- CDP_RUNTIME_UPGRADE_DATAHUB entitlement is turned off
- On the DataHub's upgrade tab the upgrade candidates should not be available
----
- Create an environment with DataLake 7.2.13
- Create a DataHub cluster with Flow Management 7.2.13 blueprint.
- CDP_RUNTIME_UPGRADE_DATAHUB entitlement is turned off
- On the DataHub's upgrade tab the upgrade candidates should be available

CB-15313: Enable patch upgrade for Flow Management templates from 7.2.13

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePreconditionService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperations.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/DistroXService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePreconditionServiceTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/StackOperationsTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperationsTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/DistroXServiceTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityServiceTest.java

Testing steps
- Create an environment with DataLake 7.2.9
- Create a DataHub with `7.2.9 - Data Mart with Apache Impala and Hue` template.
- In the DataHub's `upgrade` tab the available upgrades should be listed.
- Runtime upgrade to 7.2.10 should be successful

CB-13330: Allow Datahub upgrade when ephemeral storage based instances are used

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResourcesTest.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/ResourceEncryptionDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentModificationServiceTest.java

CB-15260: DES not deleted on Azure cloud if encryption key is wrong
This PR fixes following issues- 
1. Checks the existence of encryptionKeyUrl to delete the encryption resources. 
2. Saves azureEncryptionParameters correctly while adding the encryption resources for existing environments. "environmentService.save(environment)" was not able to save the encryptionKeyUrl as it is a secret. As a r
esult, saving it using AzureParameters entity.
3. Checks for the existence of keyVault before creating the disk encryption set. A check has been added before removing the disk encryption set's access policy from keyVault - to handle the case where keyVault is deleted/access changed but environment still exists. Without this existence check it would through an NPE.
Tests -
1. Updated the existing …

CB-15260: DES not deleted on Azure cloud if encryption key is wrong

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java

1. This bug got slipped through due to lack of enough unit testing.
2. Added a parameterized unit test to cover all three scenarios.

CB-15154 Fix a bug in validation for stop start scaling

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaAuthConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaConfigProviderUtils.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaConfigs.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDatahubConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDelegationTokenConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaMultiAzConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/schemaregistry/SchemaRegistryServiceConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/general/GeneralClusterConfigsProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDatahubConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaMultiAzConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/schemaregistry/SchemaRegistryServiceConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/model/GeneralClusterConfigs.java

To make the multi AZ feature working well we need to change a few
Kafka configs in datalakes where the multi AZ feature is enabled
and also in Data Hubs.
1) We will enable rack awareness by setting the
enable.rack.awareness CM config to true.
2) To make topics resilient we will set the default.replication.factor
to 3 to increase some topics' replication factor which are created
using the default replication factor. This will also make sure that
users by default create resilient topics.
The change will create a new config provider called
KafkaMultiAzConfigProvider that covers any config changes needed on
Kafka.
It will also introduce the multiAzEnabled field and isMultiAzEnabled
method to GeneralClusterConfigs so that the newly created config
provider is able to detect if it is needed to …

CB-15110 Adapt Kafka configs to multi AZ envs

---

cloud-azure/src/main/resources/templates/arm-v2.ftl
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java

When using a Standard SKU with the Azure load balancer, the publicIP of the instances being load
balanced must also have a Standard SKU, and the publicIPAllocationMethod must be "Static".
Previously the publicIP SKU was being set to match the load balancer SKU all instances, not just
the load balanced instances. This change adds a conditional to check if the instance is part
of the load balancer targets before setting the publicIP SKU.
Tested by creating a datalake with the change and verifying it was created successfully and that
the publicIP Standard SKU was only set for the target instances, and with a new unit test.

CB-15532 Azure load balancer Standard sku causing DL create failure

---

structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterUseCaseMapper.java

There was a change in cluster delete handling that moved the deletion of stopped clusters to a different flow chain. This flow chain was not handled in the mapping logic that maps flows to telemetry events. This commit adds the other flow chain to the mapping logic so it can start generating delete events again for stopped clusters. Tested by creating an environment, stopping, then deleting it and checking if the mapper logic correctly generated the expected DELETE_STARTED and DELETE_FINISHED events.

CB-15530 Fix missing delete telemetry events.

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/ArchivedInstanceMetaData.java
core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/converter/InstanceMetadataToArchivedInstanceMetadataConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/job/instancemetadata/ArchiveInstanceMetaDataConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/job/instancemetadata/ArchiveInstanceMetaDataJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/instancemetadata/ArchiveInstanceMetaDataJobAdapter.java
core/src/main/java/com/sequenceiq/cloudbreak/job/instancemetadata/ArchiveInstanceMetaDataJobInitializer.java
core/src/main/java/com/sequenceiq/cloudbreak/job/instancemetadata/ArchiveInstanceMetaDataJobService.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ArchivedInstanceMetaDataRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/archive/ArchiveInstanceMetaDataException.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/archive/ArchiveInstanceMetaDataService.java
core/src/main/resources/schema/app/20211206164956_CB-14959_Create_ArchivedInstanceMetaData_table.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/InstanceMetadataToArchivedInstanceMetadataConverterTest.java

Terminated InstanceMetaData blows up many DB queries, due to our adhoc
entity relationship designs. These relationships have to be properly
revisited later, however to remedy the issue until the solution arrives,
this commit introduces a scheduled job to archive old, terminated
InstanceMetaData.
- new entity/table, called ArchivedInstanceMetaData, this will
serve as a backup table for the imd
- scheduled job which runs daily, inserts all InstanceMetaData
which were terminated at least a week ago to the back up table

CB-14959 Add scheduled job to archive old, terminated InstanceMetaData

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDtoBase.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AwsEnvironmentWithCustomerManagedKeyTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AzureEnvironmentWithCustomerManagedKeyTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/FreeIpaInstanceUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/AwsCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/AmazonEC2Util.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/AzureCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml

We have hard-coded Azure disk encryption test parameters at [EnvironmentWithCustomerManagedKeyTests](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentWithCustomerManagedKeyTests.java#L30-L34). We can make this more secure. Furthermore can be troublesome if we'd like to change any of these parameter just for a Jenkins build.
Beyond this we already have external parameter for AWS at [application.yml](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/resources/application.yml#L103) as {{integrationtest.aws.diskEncryptionKey}}. However this was not introduced to [AwsCloudProvider](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/ …

CB-15425 Improve AWS Disk Encryption test with external parameters

---

core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java

1. It is difficult to rerun some failed test if there is a mix of Junit Tests.
2. Found a Junit 4 test case issue which was not testing the exception correctly.

CB-15154 Move to Junit 5 for StackOperationServiceTest

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/AmazonEC2Util.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java

[testEnvironmentWithCustomerManagedKey](http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-aws/3959/testngreports/com.sequenceiq.it.cloudbreak.testcase.e2e.environment/AwsEnvironmentWithCustomerManagedKeyTests/testEnvironmentWithCustomerManagedKey/) is failing, because of:
```
Attached volume IDs are [] for [i-05fc54266345c8719] EC2 instance 
Attached volume IDs are [] for [i-05fc54266345c8719] EC2 instance 
Attached volume IDs are [] for [i-05fc54266345c8719] EC2 instance 
Attached volume IDs are [] for [i-05fc54266345c8719] EC2 instance 
Attached volume IDs are [] for [i-05fc54266345c8719] EC2 instance 
...
java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:221)
at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.ja …
```

CB-15587 Cannot find attached volume Ids for FreeIPA

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/config/RootCertRegisterService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/config/RootCertRegisterServiceTest.java

During the environment creation, it's possible that we're trying to create and save the RootCert entity multiple times in the Freeipa management service, this can occur a ConstraintViolationException.
In this fix, we're trying to retrieve the current RootCert for the stack.
- If the RootCert is present with the new certificate not necessary to save it again.
- If the RootCert is present with an old certificate we're updating the entity.
- If the RootCert is not present, then we're creating a new entity and save to the database.

CB-15553: Fix constraint violation during root cert creation

---

config/idea/inspections.xml
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/E2ETestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/util/TagsUtil.java
integration-test/src/test/java/com/sequenceiq/it/util/TagsUtilTest.java

`test-name` tag value has been limited to 63 characters long in case of every tests. This is not appropriate, because of the Azure tags' keys are limited to 128 characters not 63 and the same is true for AWS as well. Tag key and value length limitation is only required for [GCP cloud labels](https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements).
One of our E2E test case name was too long: `testEnvironmentWithCustomerManagedKeyAndEncryptionKeyResourceGroupSpecified`, because of this the `test-name` tag validation is failing, because of splitting at 63 character.
So I've introduced a new IDE inspection rule for test method names. Furthermore I've refactored the [TagsUtil](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/ …

CB-15396 Fix TagsUtil validations

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/events/EventV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/internal/CloudbreakApiClientConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/EventV4Controller.java
datalake-api/build.gradle
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEventEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/EndpointConfig.java
datalake/src/main/java/com/sequenceiq/datalake/controller/SdxEventController.java
datalake/src/main/java/com/sequenceiq/datalake/repository/SdxClusterRepository.java
datalake/src/main/java/com/sequenceiq/datalake/service/SdxEventsService.java
datalake/src/test/java/com/sequenceiq/datalake/controller/SdxEventControllerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxEventsServiceTests.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/repository/CDPPagingStructuredEventRepository.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/filter/CDPStructuredEventFilter.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/CDPStructuredEventService.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/db/CDPStructuredEventDBService.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/controller/CDPStructuredEventV1ControllerTest.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/db/CDPStructuredEventDBServiceTest.java

The intent of the code is to add a controller in the datalake service that can provide all the events generated from datalake and cloud break services.
Functionality is added to fetch the notifications from the datalake service and cloudbreak service and perform necessary translations and sort them before serving the requests for notifications.

CB-13786: Implement controller to return all the data lake events.

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/VolumeBuilderUtil.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/VolumeBuilderUtilTest.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilder.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilderTest.java

… to have the accurate number of devices instead of creating only one

CB-14189 fix the AWS Native related ephemeral block device mapping creation

---

integration-test/src/main/resources/testsuites/e2e/azure-longrunning-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/l0promotion/azure-ephemeral-tests.yaml

- added it mow-dev test suite
- azure can't provide Standard_L8s_v2 instance type reliably

CB-15474 removed ephemeral disk tests from azure-longrunning-e2e-tests

---

environment/src/main/java/com/sequenceiq/environment/resourcepersister/Resource.java
environment/src/main/resources/schema/app/20220107151846_CB-15622_Increase_resourcereference_length.sql

* Change data type of `environmentdb.resource.resourcereference` from `VARCHAR(255)` to `TEXT`.
* Adjust entity `Resource` (`environment`):
* `resourceName` is not `nullable` (see the former create script
`20200930134106_CB-8867-Env_service_should_create_private_DNS_zone_privatelink.postgres.database.azure.com.sql`).
* `resourceReference` shall have the right `columnDefinition`.

CB-15622 Increase resourcereference length

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/model/ParcelOperationStatus.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelDecommissionService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelManagementService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ParcelCommand.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelDecommissionServiceTest.java

Before fixing the issue the class needed some refactor and extra unit test:
- getting rid of a bunch of code duplication by creating new parametrized methods under `ClouderaManagerParcelDecommissionService#removeUnusedParcelVersions`
- moving `getClouderaManagerParcelsByStatus` and `getClouderaManagerParcels` to `ClouderaManagerParcelManagementService` from `ClouderaManagerParcelDecommissionService` to make testing easier
- added unit test for `ClouderaManagerParcelDecommissionService#removeUnusedParcelVersions`

CB-15602 Refactor ClouderaManagerParcelDecommissionService

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaOperationDescriptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupToInstanceGroupResponseConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/events/FreeIpaCustomCrnOrNameProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/ChildEnvironmentRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ChildEnvironmentService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaDescribeService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/test/java/com/sequenceiq/freeipa/controller/FreeIpaV1ControllerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/events/FreeIpaCustomCrnOrNameProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/ChildEnvironmentServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaDescribeServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/StackServiceTest.java

Add new API to list all clusters including prior deleted clusters.
This is useful for obtaining a list of which CRN to use when
rebuilding FreeIPA clusters.
This was tested with unit tests and also with a local deployment of
cloudbreak.

CB-15397: Add FMS API for listing prior clusters

---

orchestrator-salt/src/main/resources/salt/salt/disks/service/scripts/mount-instance-storage.j2

Root disk was improperly detected by the service responsible for
mounting instance storage after cluster stop/start. Also
there was a semantic error in an if statement determining if the
device is already mounted or not.

CB-15619 Fix root disk detection logic in mount-instance-storage service

---

datalake/src/main/java/com/sequenceiq/datalake/service/SdxEventsService.java

When cloudbreakEventV4Response is translated to CDPStructuredEvent, resourceEvent is updated. This is needed by the Uluwatu.

CB-15635: ResourceEvent is missing in the CDPStructuredEvent

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaOperationDescriptions.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/operation/model/OperationType.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmOperationAcceptor.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaStartService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaStopService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaUpgradeCcmService.java
freeipa/src/test/java/com/sequenceiq/freeipa/controller/FreeIpaV1ControllerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmOperationAcceptorTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaUpgradeCcmServiceTest.java

* Add new operation `PUT` `/v1/freeipa/internal/upgrade_ccm` (nickname `internalUpgradeCcmByEnvironmentV1`) to `FreeIpaV1Endpoint`. This is an internal-only endpoint that triggers the CCM upgrade workflow for the FreeIPA cluster associated with a given environment. The stack must be `AVAILABLE` for the invocation to succeed.
* Returns an `OperationStatus`.
* The underlying `FreeIpaUpgradeCcmService` is only a skeleton; the actual flow trigger and stack status update will be added later (see [CB-14571](https://jira.cloudera.com/browse/CB-14571)).
* Testing:
* UT.
* `freeipa` service Swagger UI & `curl` in local CB.

CB-14570 New endpoint on FreeIPA service to trigger CCM upgrade flow

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AzureEnvironmentWithCustomerManagedKeyTests.java
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml

`AzureEnvironmentWithCustomerManagedKeyTests` has two test cases, `testWithEnvironmentResourceGroup` and `testWithEncryptionKeyResourceGroup`. There are hardly any green runs of this class, one of the methods fails most of the time. Disabling both test cases & removing the test class from `azure-e2e-tests.yaml` until they can be sufficiently stabilized.

CB-15638 Disable flaky AzureEnvironmentWithCustomerManagedKeyTests

---

orchestrator-salt/src/main/resources/salt/salt/disks/service/scripts/mount-instance-storage.j2

Added a check to skip the script, of all volumes are mounted already.
The mount-instance-storage scripts purpuse is to remount ephemeral volumes
after the cluster was stopped then started. However during cluster
deployment, the script ran, even when every disk was mounted and it could
happend that an ephemeral volume mounted /hadoopfs/fs1 also got mounted
on the next available path, eg. /haddopfs/fs3

CB-14883 mount-instance-storage service no longer mounts volumes twice

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/Crn.java
common/src/test/java/com/sequenceiq/cloudbreak/auth/crn/CrnTest.java

Adds gov cloud as a valid region in the Crn class.

CB-15684: Add usg-1 region to cloudbreak CRNs

---

core/src/main/java/com/sequenceiq/cloudbreak/service/multiaz/MultiAzCalculatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetadataServiceComponentTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/multiaz/MultiAzCalculatorService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/InstanceMetaDataService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/InstanceMetadataServiceComponentTest.java

If we have 3 subnets in az1 and 1 subnet in az2, we distributed the subnets in all of the subnets instead of the az. The distribution result was az1: 75% and az2: 25% of the subnets. Now we allocate in az1 50% and az2 50%

CB-14258 The az/subnet distribution was based on the subnetId. 

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/info/model/RightV4.java
authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentOpDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/aws/UpdateAwsDiskEncryptionParametersRequest.java
environment-api/src/test/java/com/sequenceiq/environment/api/v1/environment/model/request/aws/UpdateAwsDiskEncryptionParametersRequestTest.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/UpdateAwsDiskEncryptionParametersDto.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java
environment/src/test/java/com/sequenceiq/environment/environment/dto/UpdateAwsDiskEncryptionParametersDtoTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentModificationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorServiceTest.java
structuredevent-model/src/main/java/com/sequenceiq/environment/parameter/dto/AwsDiskEncryptionParametersDto.java

Tested this change by creating an environment without passing encryption paramater/CMK during creation and post creation ran the below CLI on the enviornment:
/Users/satyabolnedi/master/thunderhead/clients/cdpcli/cdp.sh environments update-aws-disk-encryption-parameters --environment satya-testabc2 --encryption-key-arn "dummykey"  --profile local
and verified that the encryption key arn is updated to DB in enviornment_parameters table and also post that created Datalake and Datahubs on the environment and verified that the respective disks and External RDS created post the updation are encrypted with the new key passed from CLI.
I will update the Thunderhead PR with the respective Cb build post merging this change. Thunderhead Draft PR created : …

CB-13205:Edit/Update the existing CMK on an environment

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientExceptionUtil.java
freeipa-client/src/test/java/com/sequenceiq/freeipa/client/FreeIpaClientExceptionUtilV1Test.java
freeipa/build.gradle
node-status-monitor-client/build.gradle

Previously not the full stack trace was check for `IOException`. With this commit the whole stack trace causes would be checked.
This is necessary as `JsonRpcHttpClient` does some wrapping.
Bumped up `JsonRpcHttpClient` version in some gradle files where it was missing.

CB-15709 Retry FreeIPA calls which fails with IOException

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/DistroXRepairTests.java
integration-test/src/main/resources/testsuites/e2e/l0promotion/azure-ephemeral-tests.yaml

MOW-Dev 2.52.0-b30 [mow-api-longrunning-azure DistroXRepairTests testEphemeralDistroXMasterRepairWithTerminatedEC2Instances](http://ci-cloudbreak.eng.hortonworks.com/job/mow-api-longrunning-azure/2/artifact/suites_log/DistroXRepairTests.testEphemeralDistroXMasterRepairWithTerminatedEC2Instances-20220116.log) is failing because of
```2022-01-16 16:50:50,578 [TestNG-test=azure-ephemeral-tests-1] INFO  c.s.i.c.u.c.c.ClouderaManagerClient [DistroXRepairTests.testEphemeralDistroXMasterRepairWithTerminatedEC2Instances] - Cloudera Manager Base Path: https://10.124.218.60/azure-test-a058/cdp-proxy-api/cm-api/v43
2022-01-16 16:50:53,838 [TestNG-test=azure-ephemeral-tests-1] ERROR c.s.i.c.u.c.a.ClouderaManagerClientActions [DistroXRepairTests.testEphemeralDistroXMasterRepairWithTerminatedEC2Instance …
```

CB-15695 Fix workloadUsername for testEphemeralDistroXMasterRepairWithTerminatedEC2Instances

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/AzureInstanceTemplateV4Parameters.java
core-api/src/test/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/AzureInstanceTemplateV4ParametersTest.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverterTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StackRequestManifesterTest.java

CB-15494: Store Azure CMK in DL/DH stack (in addition to the DES Resource ID)
This commit adds encryptionKeyUrl to the DL/DH stack

CB-15494: Store Azure CMK in DL/DH stack (in addition to the DES Resource ID)

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerHostStatusChecker.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/GrainPropertiesService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/HostAttributeDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/TargetedUpscaleCache.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/TargetedUpscaleSupportService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/main/java/com/sequenceiq/cloudbreak/util/StackUtil.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/GrainPropertiesServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/HostAttributeDecoratorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/TargetedUpscaleSupportServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/salt/response/FileExistsSaltResponse.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStates.java

CB-14421 Implement targeted salt highstate during Upscale operation
- during upscale we will execute highstate against only new nodes and gateway nodes (since several files should be updated on gateway nodes)
- host status checking should be done against only affected nodes
- node health validation is checking only nodes of affected hostgroup
- several logics have been separated in order to do targeted operations if operation is upscale
- targeted highstate operation depends on unbound elimination thus we are checking if unbound elimination is enabled and related conf is removed from all reachable nodes of the cluster
Tested locally:
- DH worker group upscale (before that, a compute node were killed on provider side)
- light duty DL master repair
- medium duty DL gateway repair

CB-14421 Implement targeted salt highstate during Upscale operation

---

core-model/src/test/java/com/sequenceiq/cloudbreak/domain/EntityTest.java
core/src/main/java/com/sequenceiq/cloudbreak/aspect/SecretAspects.java
core/src/main/java/com/sequenceiq/cloudbreak/service/customconfigs/CustomConfigurationsService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/customconfigs/CustomConfigurationsViewProvider.java
core/src/main/resources/schema/app/20211210124157_DISTX-683_Add_secretvalue_column_to_customconfiguration_properties_table.sql
core/src/test/java/com/sequenceiq/cloudbreak/aspect/SecretAspectsTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/customconfigs/CustomConfigurationsServiceTest.java
custom-configurations/build.gradle
custom-configurations/src/main/java/com/sequenceiq/cloudbreak/converter/CustomConfigurationPropertyConverter.java
custom-configurations/src/main/java/com/sequenceiq/cloudbreak/converter/CustomConfigurationsToCustomConfigurationsV4ResponseConverter.java
custom-configurations/src/main/java/com/sequenceiq/cloudbreak/converter/CustomConfigurationsV4RequestToCustomConfigurationsConverter.java
custom-configurations/src/main/java/com/sequenceiq/cloudbreak/domain/CustomConfigurationProperty.java
custom-configurations/src/main/java/com/sequenceiq/cloudbreak/repository/CustomConfigurationPropertyRepository.java
custom-configurations/src/main/java/com/sequenceiq/cloudbreak/repository/CustomConfigurationsRepository.java
custom-configurations/src/test/java/com/sequenceiq/cloudbreak/converter/CustomConfigurationPropertyConverterTest.java
custom-configurations/src/test/java/com/sequenceiq/cloudbreak/converter/CustomConfigurationsToCustomConfigurationsV4ResponseConverterTest.java
custom-configurations/src/test/java/com/sequenceiq/cloudbreak/converter/CustomConfigurationsV4RequestToCustomConfigurationsConverterTest.java

- Using the annotation `SecretValue`, Custom Configuration values are now being stored in the vault.
- This involves schema changes to make the `CustomConfigurationProperty` entity to be workspace aware.
- The changes are in line with 'Approach 2' as listed in the referenced one pager. 
- [DISTX 683 One Pager](https://docs.google.com/document/d/1cLtRwLWpXM-keDz_dR0yYTQSZqFTpr4PgWezbSiLRD4/edit?usp=sharing)
- [DISTX-683](jira.cloudera.com/browse/DISTX-683)
- [Design doc](https://docs.google.com/document/d/1jat_7jDNNRr5TagYEP7lG4r_UzBejHieCD-BEM9-jTE/edit?usp=sharing)

DISTX-683 Store secret custom configurations info in the vault

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/StackPatchType.java
core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJobService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/AbstractTelemetryPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/ExistingStackPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/LoggingAgentAutoRestartPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/MeteringAzureMetadataPatchService.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/MeteringAzureMetadataPatchServiceTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/TelemetryOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltTelemetryOrchestrator.java
orchestrator-salt/src/main/resources/salt/salt/metering/init.sls
orchestrator-salt/src/main/resources/salt/salt/metering/scripts/metering_package_manager.sh
orchestrator-salt/src/main/resources/salt/salt/metering/upgrade.sls
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltTelemetryOrchestratorTest.java

details:
- added new stack patcher implementation for fixing azure datahub nodes by upgrading old metering rpms
- stack patcher compares image creation dates in order to identify the stack that will need updates
- update logging auto restart stack patcher to update datahubs based on image timestamps as well (if those datahubs do not have a package version for cdp-logging-agent)
- added new metering_package_manager.sh script that can download/upgrade rpms (from 2 different places, first one can be provided by flags)
- script is used in upgrade.sls, init triggers that in failsafe mode, the stack patcher triggers that in fail hard mode
- add some refactoring & unit tests

CB-15700. Implement metering client auto updated via StackPatcher logic

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java

During the investigation of E2E test failures it turned out that all our E2E test on all environments are using the same cloud storage base location which is a dangerous practice and could be ended up with race condition in specific service when they would like to create the same subdirectory at the same time.
For example on Azure the main Datalake related service are configured to use the `abfs://autotesting@autotestingapi.dfs.core.windows.net/` cloud storage location which means that all the created Datalake's ranger services on different environments are writing to the `abfs://autotesting@autotestingapi.dfs.core.windows.net/ranger/audit/atlas` directory.
Relevant config from Ranger logs:
```
2022-01-15 02:40:11,910 INFO  - [main:] ~ AUDIT PROPERTY: …
```

CB-15712 Create separate cloud storage base location for every Azure E2E test

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AwsEnvironmentWithCustomerManagedKeyTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AzureEnvironmentWithCustomerManagedKeyTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/AwsCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/AzureCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java

CB-15688: [API E2E] Azure Customer Managed Key testWithEnvironmentResourceGroup creates resources as default settings
When I running [AzureEnvironmentWithCustomerManagedKeyTests suite testWithEnvironmentResourceGroup](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AzureEnvironmentWithCustomerManagedKeyTests.java#L86) test case I've realised the created [resourceGroupForTest](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AzureEnvironmentWithCustomerManagedKeyTests.java#L102) actually has not been used.
So the created resourceGroupForTest is empty and does not contain any resource during the entire test …

CB-15688: [API E2E] Azure Customer Managed Key testWithEnvironmentResourceGroup creates resources as default settings

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRetryService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxRetryServiceTest.java
flow/src/main/java/com/sequenceiq/cloudbreak/service/flowlog/FlowLogUtil.java
flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java

Currently, there is no retry mechanism for backup-restore flows when they fail.
Let's say datalake backup or restore flow failed in the resize flow chain, there is no way to trigger a retry of backup/restore flows again.
Retrying from the failed state does not work for backup restore flows so added implementation to retry the complete flow.
Made sure that retry for start/stop/backup/restore/create flows work.

CB-15715: Make backup-restore flows retryable.

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPermissionService.java

Adding 3 `System` permissions to `Host Enrollment` privilege is causing replication issues almost every time.
Sometimes the system can't get out of this and blocks every operation causing various issues during cluster operations.
The fix is simply to add the permissions in separate calls.

CB-15632 Mitigate FreeIPA System permission replication issue

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandler.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandlerTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidatorTest.java

1. To allow the clusters to stop we introduced a new state.
2. This state needs to be allowed in scale up via start mode.

CB-15341 Fix an end-to-end test during scale up

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/action/AzureCloudBlobClientActions.java

Azure E2E Build 1496--2.52.0-b59-AZURE (21-Jan-2022 03:01:21) [SdxRepairTests.testSDXRepairMasterAndIDBRokerWithStoppedEC2Instance](http://ci-cloudbreak.eng.hortonworks.com/job/api-longrunning-e2e-azure/1496/artifact/suites_log/SdxRepairTests.testSDXRepairMasterAndIDBRokerWithStoppedEC2Instance-20220121.log) is failing, because of:
```
2022-01-21 03:18:50,732 [TestNG-test=azure-longrunning-e2e-tests-8] ERROR c.s.i.cloudbreak.context.TestContext [SdxRepairTests.testSDXRepairMasterAndIDBRokerWithStoppedEC2Instance] - then [SdxRepairTests$$Lambda$1043/0x0000000800f1bc40] assertion is failed: begin 55, end 18, length 94, name: azure-test-c200430b
java.lang.StringIndexOutOfBoundsException: begin 55, end 18, length 94
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
at …
```

CB-15761 Fix java.lang.StringIndexOutOfBoundsException at AzureCloudBlobClientActions.getContainerName

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/repo/init.sls

7.1.0->7.2.13 upgrade fails with no external db setup due to the presence of package cloudera-manager-server-db-2.
This commit removes the condition to only remove this package in case of external RDS setup.
Tested with the following:
- 7.1.0 -> 7.2.13
- 7.1.0 -> 7.2.14
- 7.2.13 -> 7.2.14

CB-15751 - Remove CM DB during upgrade

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/ephemeral/DistroXUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/ClouderaManagerUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/action/ClouderaManagerClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/client/ClouderaManagerClient.java

REST calls towards CM did not work through knox in the case of
ephemeral upgrade e2e tests. Changed the test to utilize direct
connection, while we figure out why does knox respond with ssl
error, when the SDX is created through the public API for the test.

CB-14916 Use direct connection to CM in ephemeral upgrade test

---

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/orchestrator/TelemetrySaltRetryConfig.java
common/src/main/resources/common-config.yml
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackImageService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/ExistingStackPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/LoggingAgentAutoRestartPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/MeteringAzureMetadataPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/config/LoggingAgentAutoRestartPatchConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/config/MeteringAzureMetadataPatchConfig.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackImageServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/LoggingAgentAutoRestartPatchServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/MeteringAzureMetadataPatchServiceTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltTelemetryOrchestrator.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltTelemetryOrchestratorTest.java

details:
- create object for salt retry configs for salt telemetry orchestrator (remove contructor params)
- rename configs for stack patcher (with "-" separator as spring recommends that and does not allow to use upper case as name in @ConfigurationProperty) and move them to an object as well (so constructor params can be removed here as well)
- refactor: move stack based image operations from ExistingStackPatchService to StackImageService

CB-15745. Generalize some telemetry and stack pacher configs

---

integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupUtil.java

In case of an E2E Jenkins build has been aborted (by user or by Time-out strategy), the test project teardown won't be invoked furthermore the [api-cleanup-app](http://ci-cloudbreak.eng.hortonworks.com/job/api-cleanup-app/) related build won't delete all the created resources if a test case resource file could not be generated by the `afterInvocation` listener.

CB-15782 Cleanup every resources in case of Jenkins Abort

---

datalake/src/main/resources/schema/app/20210217140634_CB-11220_introduce_flowChainType_into_the_flowChainLog_table.sql
environment/src/main/resources/schema/app/20210217140634_CB-11220_introduce_flowChainType_into_the_flowChainLog_table.sql
flow/src/main/resources/schema/flow/20210217140634_CB-11220_introduce_flowChainType_into_the_flowChainLog_table.sql
flow/src/test/resources/schema/flow_test/20210818140529_CB-13731_add_flow_chain_type.sql
freeipa/src/main/resources/schema/app/20210217140634_CB-11220_introduce_flowChainType_into_the_flowChainLog_table.sql
redbeams/src/main/resources/schema/app/20210217140634_CB-11220_introduce_flowChainType_into_the_flowChainLog_table.sql

details:
- db migration can fail if flowchainlog does not exist at that time when this specific sql is running
- order of the migration scripts (per module) is decided based on the order of the SchemaLocationProvider implementations
- can differ for different projects + jdks -> can lead to migration failure

CB-15796. Move flow related migration scripts under flow module.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractSdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/CloudbreakTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/blueprint/BlueprintTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/clustertemplate/ClusterTemplateTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/credential/CredentialTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/customconfigs/CustomConfigurationsTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/imagecatalog/ImageCatalogTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/kerberos/KerberosTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ldap/LdapTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/recipe/RecipeTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxCustomTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/util/CheckResourceRightTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/util/CheckRightTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/ResourceAwait.java

- cleanup method is simplified now and using admin client from method parameter
- cleanup of affected classes regarding unused code

CB-15783 UMS mock tests should clean up resources correctly

---

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/clouderamanager-ssl-user-facing.conf
orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl-locations.d/knox.conf

**Describe the change you are making**
This PR adds two things to nginx config:
1. Generate a unique request id and pass it to Knox under `X-Request-Id` header
2. Log this request id in nginx access.log
**Why is this change needed**
This PR is a part of the effort to operationalize and instrument Knox (and other components). This is also part of OKR for Knox https://jira.cloudera.com/browse/CB-15417
**Side effects**
There should be no side effects. 
**Testing**
This was tested on a public cloud cluster by updating the `ssl-user-facing.conf` file. Following are the log snippets:
nginx log **before** the fix
```
10.19.15.62 - - [13/Jan/2022:19:40:04 +0000] "GET /dwx-o7p83q/cdp-proxy/atlas/js/templates/search/save/SaveSearchView_tmpl.html?bust=1640865545143 HTTP/1.1" 200 787 …
```

CB-15417 - Generate a request id in Nginx for all requests going to Knox and log it in access.log

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/ClouderaManagerUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/action/ClouderaManagerClientActions.java

Required CM services should be in running state (cluster start command should be issued) during cluster start.

CB-15759 Create test for cluster stop start with external database

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AzureEnvironmentWithCustomerManagedKeyTests.java

The recent changes of [CB-15688](https://jira.cloudera.com/browse/CB-15688) / [PR 12073](https://github.com/hortonworks/cloudbreak/pull/12073) override `AzureEnvironmentWithCustomerManagedKeyTests.tearDown()` in order to clean up Azure RG and tested resources.
The problem is, this method uses the:
```
onlyForGroups = { "withrg" }
```
condition and so it will not be invoked in case of `testWithEncryptionKeyResourceGroup` test case. So cluster resources are going to be left behind for this test.

CB-15837 Fix Azure encryption test single resource group test teardown

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/DiagnosticsFlowService.java
freeipa/build.gradle
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/AbstractDiagnosticsCollectionActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/DiagnosticsCollectionActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/DiagnosticsFlowService.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/event/DiagnosticsCollectionFailureEvent.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsCleanupHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsCollectionHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsEnsureMachineUserHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsInitHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsPreFlightCheckHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsSaltValidationHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsUpgradeTelemetryHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsUploadHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsVmPreFlightCheckHandler.java
usage-collection/src/main/proto/usage.proto

details:
- add usagecollection module to freeipa
- add usages around diagnostics steps (where it cannot be added - use UNSET types)
- update usage proto with case number (to be up to date, see: CB-15839)

CB-15847. Support freeipa diagnostics usage.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxResizeTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxResizeTests.java
integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/sdx-resize-tests.yaml

While running the e2e tests locally I have observed some issues before I was able to update the PR the earlier changes are merged. Please find the rebased changes.
I successfully ran the tests locally.

CB-13414: Add e2e tests for re-sizing of the datalake with fixes.

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

Bumping it up the try count from 60 to 300 so that the total retry interval is going to be 50 min.

CB-15788: Database backup/restore has only 10 minute timeout.

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/StackTerminationFlowConfig.java

When an error happens during on action, and it's not handled inside the action, then
`AbstractAction` would send the failure event configure in the flow's configuration.
If it's set to `noFailureEvent`, then this cause an unhandled failure in the flow.
These configurations are now replaced to avoid such situations.
Also other flows in FMS were check, but those have no `noFailureEvent` except the first transition.

CB-15762 Replace FreeIPA termination's `noFailureEvent`

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java

The recent changes of [CB-15688](https://jira.cloudera.com/browse/CB-15688) / [PR 12097](https://github.com/hortonworks/cloudbreak/pull/12097) override `DistroXEncryptedVolumeTest.tearDown()` in order to clean up Azure RG and tested resources.
The problem is, this method uses the:
```
onlyForGroups = { "azure_singlerg" }
```
condition and so it will not be invoked in case of AWS test case. Hence running that test class on AWS will likely leave behind cluster resources instead of cleaning them up.

CB-15837 Fix single resource group test teardown

---

core/src/main/resources/defaults/blueprints/7.2.14/cdp-streaming-small.bp
core/src/main/resources/defaults/blueprints/7.2.14/cdp-streaming.bp
core/src/main/resources/defaults/clustertemplates/7.2.14/aws/streaming.json
core/src/main/resources/defaults/clustertemplates/7.2.14/azure/streaming.json
core/src/main/resources/defaults/clustertemplates/7.2.14/gcp/streaming.json
core/src/main/resources/defaults/clustertemplates/7.2.14/yarn/streaming.json

This commit adds the Kafka Connect roletype to both the Heavy and Light Duty Streams Messaging templates.
Tested: Manually on provisioned cluster

CB-15248 Add Connect to DataHub templates (LD and HD) in Cloudbreak

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/healthcheckmodel/CheckResult.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaInstanceHealthDetailsService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaInstanceHealthDetailsServiceTest.java

Currently we store the whole freeipa healthcheck result in the statusreason field instead of storing the unhealthy part.
After the change only some main info and unhealthy checks would be present:
```
FreeIpa is AVAILABLE, node health check: {"status":"HEALTHY","host":"ipaserver0.mmolnar.xcu2-8y8x.wl.cloudera.site","checks":[],"pluginStats":[],"plugin_stat":[]}, node health check: {"status":"HEALTHY","host":"ipaserver1.mmolnar.xcu2-8y8x.wl.cloudera.site","checks":[],"pluginStats":[],"plugin_stat":[]}
```

CB-15820 Shorten FreeIPA statusReason field

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxResizeTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxResizeTests.java
integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/sdx-resize-tests.yaml

Reverts hortonworks/cloudbreak#12166

Revert "CB-13414: Add e2e tests for re-sizing of the datalake with fixes."

---

common/src/main/java/com/sequenceiq/cloudbreak/util/FreeIpaPasswordUtil.java
common/src/main/java/com/sequenceiq/cloudbreak/util/PasswordUtil.java
common/src/main/java/com/sequenceiq/cloudbreak/util/password/CharSet.java
common/src/main/java/com/sequenceiq/cloudbreak/util/password/DefaultPasswordGenerator.java
common/src/main/java/com/sequenceiq/cloudbreak/util/password/PasswordGenerator.java
common/src/main/java/com/sequenceiq/cloudbreak/util/password/PasswordPart.java
common/src/test/java/com/sequenceiq/cloudbreak/util/password/CharSetTest.java
common/src/test/java/com/sequenceiq/cloudbreak/util/password/PasswordGeneratorTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/TlsSecurityService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/TlsSecurityService.java

Created password generator which uses cryptographically strong random generator. The default password format is the same as in `FreeIpaPasswordUtil` but `PasswordGenerator` provides a builder to support different formats. The default implementation (based on SHA-512 based DRBG) requires 256 bit entropy from the operating system.
The password format is the following:
```
PREFIX | shuffle( MANDATORY_CHARACTERS | X1 | X2 | ... | Xn )
```
where:
- __PREFIX:__ optional n length prefix randomly chosen from a specified character set,
- __MANDATORY_CHARACTERS:__ optional characters which must be included in the password in random order,
- __X1, X2, ..., Xn:__ parts from different character sets with different length.
__Note:__ 
- not all ASCII characters could be used because various scripts, …

CB-15640 Use SHA2-512 for saltbootstrap password and salt password in cloudbreak-core and cloudbreak-freeipa

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/multiaz/MultiAzCalculatorService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/InstanceMetaDataService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/instance/InstanceMetaDataServiceTest.java

The following cURL has been created to test the upscale scenario of a FreeIPA cluster on Azure:
```
curl -X PUT -H "Content-Type: application/json" \
-H "x-cdp-actor-crn: crn:altus:iam:us-west-1:cloudera:user:t...@cloudera.com" \
-d '{"environmentCrn": "crn:cdp:environments:us-west-1:cloudera:environment:0...", "targetFormFactor": "HA"}' \
http://localhost:8090/freeipa/api/v1/freeipa/upscale
```
The previously problematic logic has been covered by UT and an AWS multi-AZ enabled FreeIPA cluster was also created as a sanity check of multi-AZ functionality.

CB-15800 calculate availability zone and subnet usage in FreeIPA only when availability zone data exists

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusServiceTest.java

There were some cases when the CM readRoles API call returned roled with null ApiRoleState and this caused a NullPointerException when we tried to convert the value of the ApiRoleState to an internal status.
This case has covered with an improvement to convert the null value into an ApiRoleState.UNKNOWN status.

CB-15119: Handle null ApiRoleState when trying to retrieve CM status

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/FreeIpaClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIpaDownscaleAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIpaUpscaleAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/FreeIpaTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/EnvironmentAware.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaDownscaleTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaUpscaleTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaScalingTests.java
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml

An e2e test is added for freeipa scaling: it scales NON_HA -> HA -> TWO_NODE_BASED -> HA. At each step it checks from instanceMetaData:
- are the correct node numbers present
- the primary gateway has not changed
The test is only run for AWS currently, and takes ~1 hour.

CB-15582 Freeipa upscale/downscale e2e test

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaGroupType.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/GroupAddOperation.java
freeipa-client/src/test/java/com/sequenceiq/freeipa/client/operation/GroupAddOperationTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncConstants.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncServiceTest.java

It is significantly faster to add group members to non-posix
groups than to posix groups. The cdp-usersync-internal group
is only used by usersync and does not need to be a posix group.
This commit changes usersync to create cdp-usersync-internal
as non-posix. This will only affect new environments and not
existing cdp-usersync-internal groups.

CB-15680. Make cdp-usersync-internal group non-posix

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandler.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandlerTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/DetailedStackStatus.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/Status.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/InstanceStatus.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceMetaData.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/InstanceMetaDataToCloudInstanceConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartds/StopStartDownscaleFlowService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartus/StopStartUpscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartus/StopStartUpscaleFlowService.java
core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/nodestatus/NodeStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartus/StopStartUpscaleActionsTest.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJobTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/StopStartUpscaleCommissionViaCMHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidatorTest.java

part of CB-14929 (before merge of the branch to master).
Also removes the STARTED InstanceStatus for now.
Impact on the CB-14929 stop-start based scaling is that all operations
will at least be attempted even if the cluster has STOPPED instances.
These will likely end up failing. Blocking specific operations is now
part of CB-15146, which mentions potential alternate mechanisms which
could be used to control these operations.

CB-15984. Remove additional Status, DetailedStackStatus introduced as

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxEnableRangerRazAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRangerRazEnabledTests.java

- Replaced `SdxInternalTestDto` with `SdxTestDto`
- Ran the E2E test to verify that prewarmed images were used.

CB-15924 Adjust SdxRangerRazEnabled E2E tests to use prewarmed images

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupServiceTest.java

This commit introduces consistent hostname generation and consistent primary gateway selection logic across multiple recoveries, meaning:
- it is guaranteed that
- the instanceId-s remain the same
- the privateId allocation remains the same
- primary gateways remain the same

CB-15730 - CM server moved during upgrade to another node

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java

More details could be found in the related JIRA item CB-15932 with a root cause analysis why the GCP based environment stop-start tests are failing.
A `TODO` has been added and this commit will be reverted with the permanent fix.

CB-15932 wait 2 mins before trigger start in Environment stop-start tests

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeServiceTest.java
orchestrator-salt/src/main/resources/salt/salt/metadata/settings.sls

- Instead of the mine.get the primary gateway's private IP is stored in `cloudera-manager:address` field in
`/cloudera-manager/settings.sls` pillar. This is available from all nodes.
- Removed condition which persisted CM related pillar only if it's a CM cluster based on blueprint.
As we do not support Ambari anymore, and every cluster is CM based, it doesn't make any sense.
- Adjusted unit test, and smaller refactor of gateway pillar code for readability.
Tested:
- DH and DL provision
- DH and DL upgrade, DL medium duty upgrade
- DH upscale
Example pillar file:
```
cat cloudera-manager/settings.sls 
#!json
{
"cloudera-manager": {
"address": "10.112.22.209",
"mgmt_service_directories": [
"/hadoopfs/fs1/cloudera-scm-headlamp",
"/hadoopfs/fs1/cloudera-scm-eventserver", …
```

CB-15991 Eliminate 'mine.get' from  metadata settings.sls

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/recover.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/init.sls

Shell will be set to /usr/sbin/nologin by default for postgres user for security reasons, so the /bin/bash shell should be set explicitly in each runuser command.

CB-15128 Set explicit shell for postgres user in runuser commands

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/ephemeral/DistroXUpgradeTests.java

- removed DL upgrade (~50min)
- removed ephemeral mount related validation after provision, as this is covered in other tests (~20min)
- removed DH stop-start as DL upgrade is removed (~15min)

CB-15821 [E2E] Optimize `DistroXUpgradeTests#testDistroXEphemeralUpgrade` to reduce runtime

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonClusterManagerProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
integration-test/src/main/resources/application.yml

See detailed description in the commit message.Today we have a single DistroX upgrade test for CDP upgrade http://ci-cloudbreak.eng.hortonworks.com/job/api-longrunning-e2e-aws/1389/testngreports/com.sequenceiq.it.cloudbreak.testcase.e2e.distrox/DistroXUpgradeTests/testDistroXUpgrade/ . We need to extend our testing to 3rd party image catalogs as well.
We should use the prod catalog for this purpose to avoid maintaining a new catalog. Prod catalog can be found here: https://cloudbreak-imagecatalog.s3.amazonaws.com/v3-prod-cb-image-catalog.json. Let's use this in the test with a random name and initiate an upgrade from any to any version using this catalog.
Jira link:
[https://jira.cloudera.com/browse/CB-15528](url)

Cb 15528 - E2E test for upgrade with custom catalog on Data Hub cluster

---

datalake/src/main/java/com/sequenceiq/datalake/repository/SdxClusterRepository.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
flow/src/main/java/com/sequenceiq/flow/core/ResourceIdProvider.java
flow/src/main/java/com/sequenceiq/flow/service/FlowService.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxResizeTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxResizeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/FlowUtil.java
integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml

Original PR was https://github.com/hortonworks/cloudbreak/pull/12011.
This change was reverted as it was flaky.
Summary of changes
1. As the datalake is detached, there will be a very small interval before resized Dl is created. During this interval, DL with the CRN will not be found. That is exactly what was happening. I have included some failures handling the flow until code to address this situation.
2. When the datalake is resized datalake ID will change. The current validation would fail. Made changes to skip the validation for resizing.

CB-15894: E2E SdxResizeTests.testSDXResize failed because the referenced flow didn't belong to the referenced resource

---

datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/flow/chain/DatalakeResizeFlowEventChainFactory.java

But the restore is not performed automatically when RAZ is enabled.
Made sure that Backup is triggered when resizing and upgrading RAZ-enabled datalake.

CB-16023: Support automatic backup of DL as part of upgrade and resize workflows on RAZ enabled environments.

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/DistroxService.java

When data lake in an environment with DH clusters is stopped, pooling internal to stop DH cluster is just 5-6 min which is short.
Especially this is not sufficient for DH clusters that have external databases.
Re-used the attempt count from DatahubPollerService.

CB-16102: Stopping the data lake is timing out when DH cluster are present.

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/LoadAlertConfigurationRequest.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/ClusterStatusMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/LoadMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/MonitorUpdateRate.java
autoscale/src/test/java/com/sequenceiq/periscope/domain/LoadAlertConfigurationTest.java

minute.
- The default continues to be 2 minutes.
- The ClusterStatusSyncMonitor now runs every minute at the 50s mark.

 CB-16060. Reduce the minimum cooldown configuration for AutoScale to 1

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/utils/StackResponseUtils.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/MockStackResponseGenerator.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/StackResponseUtilsTest.java

- Changes to exclude stopped nodes in clusterNodeCount if stopStart scaling is enabled
- Unit tests for StackResponseUtils, YarnLoadEvaluator

CB-15142 Fix cluster max size checks when making use of stop/start scaling

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java

- Extend the freeipa upgrade test with SDX cluster creation
- Ssh into SDX master node and test if kinit is working during the upgrade
- kinit should work, this would ensure KDC is available, and users are present
Something is not ok with https://github.com/hortonworks/cloudbreak/pull/12177 as during rebase every change is lost, so I created with a new branch with the changes.

CB-15292 Kinit tests during freeipa upgrade

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/VolumeSetAttributes.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/ResourceUtil.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
core-model/src/test/java/com/sequenceiq/cloudbreak/domain/stack/ResourceUtilTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/InstanceMetadataUpdater.java

This commit ensures, that even if there are multiple volumeSets for a given instance (e.g. through recovery) we would only use the latest one and no more.
Fixing the termination/recovery leaving the VolumeSets would be a much larger change that would make less sense to implement as we are already phasing out Multi RG setup.

CB-15963 - Handle dangling VolumeSets on Azure for MultiRG setup

---

cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartDownscaleStopInstancesHandler.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartUpscaleStartInstancesHandler.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartDownscaleStopInstancesHandlerTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartUpscaleStartInstancesHandlerTest.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartus/StopStartUpscaleFlowService.java

start (via the stopstart scaling mechanism).
- Increases the allowed time for both stop and start to 10 minutes. This
combined with the 10m for the CM operations means that a
scale-up/scale-down, if it were to fail, should fail within 20
minutes.
- If a timeout is hit, proceed with the nodes which we were able to
start.
- While determining which nodes to upscale, added an additional check
to get state from the cloud-provider as well.
- Reduces verbosity of one of the console error messages which was
otherwise logging CloudVmInstanceStatus for all nodes which were being
started.

CB-16194. Increase the allowed time-out while waiting for instances to

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/ephemeral/DistroXUpgradeTests.java

- removed DL upgrade (~50min)
- removed ephemeral mount related validation after provision, as this is covered in other tests (~20min)
- removed DH stop-start as DL upgrade is removed (~15min)
Bringing back the fix from [PR-12304](https://github.com/hortonworks/cloudbreak/pull/12304) to 2.52 line of CB.

CB-15821 [E2E] Optimize `DistroXUpgradeTests#testDistroXEphemeralUpgrade` to reduce runtime on 2.52 line

---

integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml

- until investigation is done on why it times out

CB-16208 datalake resize test need to be disabled 

---

flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java
flow/src/main/java/com/sequenceiq/flow/domain/FlowLogIdWithTypeAndTimestamp.java
flow/src/test/java/com/sequenceiq/flow/service/FlowNameFormatServiceTest.java
flow/src/test/java/com/sequenceiq/flow/service/TestFlowView.java
freeipa/build.gradle
freeipa/src/main/java/com/sequenceiq/freeipa/FreeIpaFlowInformation.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/cloud/PlatformParameterService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaFlowManager.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaParallelFlowValidator.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackTemplateService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaParallelFlowValidatorTest.java

…r creation or cleanup is running
As BindUserCreate and Cleanup flow could be started any time during an FreeIPA upgrade all upgrade related flow in the flowchain should be able to run in parallel.
Flow engine doesn't support fine grain restrictions regarding when a flow can start next to another one, it's either permitted or forbidden.
In this commit all flows used in `UpgradeFlowEventChainFactory` is added to the `PARALLEL_FLOWS` in `FreeIpaFlowInformation`
To ensure they cannot be started next to other flows, `FreeIpaParallelFlowValidator` was introduced and it's now hooked into `FreeIpaFlowManager` right
before triggering any flows.
This validator ensures that only BindUserCreate, Cleanup and Termination flows could be started next to other running flows, while the flowchain can …

CB-16066 Upgrade related flows should be able to start while bind use… 

---

core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJob.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/AbstractTelemetryPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/ExistingStackPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/LoggingAgentAutoRestartPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/MeteringAzureMetadataPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/StackPatchUsageReporterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/UnboundRestartPatchService.java
core/src/test/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJobTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/ExistingStackPatchServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/LoggingAgentAutoRestartPatchServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/MeteringAzureMetadataPatchServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/UnboundRestartPatchServiceTest.java

With monitoring in EDH and Datadog, stack patchers should only fail in unexpected cases. So when a stack is simply not in correct state for the patch to apply, no error should be reported.

CB-16164 Stack patcher error handling improvements

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/StackCommonServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidatorTest.java

- Added logic to detect compute like host groups
- Validation to ensure that the stop / start operations can be invoked only for the applicable host group
- UTs for stop / start hostGroup validation in UpdateNodeCountValidatorTest

CB-16109 Hostgroup check for stop / start instances API

---

datalake-api/src/main/java/com/sequenceiq/sdx/client/SdxClient.java
datalake-api/src/main/java/com/sequenceiq/sdx/client/SdxServiceApiKeyEndpoints.java
datalake-api/src/main/java/com/sequenceiq/sdx/client/SdxServiceCrnEndpoints.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SdxClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxGetAuditsAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxGetDatalakeEventsZipAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/util/SdxEventTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/SdxEventControllerAuthTest.java
integration-test/src/main/resources/testsuites/v4/mock/real-ums-mock-tests.yaml

Jira: https://jira.cloudera.com/browse/CB-15947
This is specifically meant to add automated testing of the new enforced roles for these methods defined in [#12231](https://github.com/hortonworks/cloudbreak/pull/12231).
To be completely honest, I don't really know what I'm doing or how to test this but this makes sense to me sort of. Please look over this and tell me if there is anything I need to change/how I can properly test this. Thank you.

CB-15947: Created a real UMS test for the SDX events API.

---

ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/ccmv2/CcmV2ManagementClient.java
ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/ccmv2/GrpcCcmV2Client.java
ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2JumpgateParameterSupplier.java
ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2ParameterSupplier.java
ccm-connector/src/test/java/com/sequenceiq/cloudbreak/ccmimpl/ccmv2/CcmV2ManagementClientTest.java
ccm-connector/src/test/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2JumpgateParameterSupplierTest.java
ccm-connector/src/test/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2ParameterSupplierTest.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/Crn.java
common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/CcmV2JumpgateParameters.java
common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/CcmV2Parameters.java
common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultCcmV2JumpgateParameters.java
common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultCcmV2Parameters.java
common/src/test/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultCcmV2JumpgateParametersTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/userdata/UserDataBuilderTest.java

There is an issue when trying to re-register an inverting proxy agent for the same cluster in the same environment, causing a unique constraint violation in the ccmv2 thunderhead service.
This is mitigated by first checking if an agent is already registered and if so, removing the registration.
The ccmv2 service was missing from the CRN enums, adding.

CB-16070 CCM Connector enhancements

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceStateChecker.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/GcpComputeResourceChecker.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceStateCheckerTest.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/scheduler/SyncPollingScheduler.java

The original logic only checked the state of the instances and try to convert it to InstanceStatus, but in some cases this result in a situation where the stop poller exited immediately as the instance state were still permanent when the poller has started.

CB-15932 refactor stop/start related GCP poller to be based on operations

---

orchestrator-salt/src/main/resources/salt-common/salt/fluent/cdp-logging-agent-init.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls

details:
- for ycloud, logging agents are not installed by default, this code installs rpm manually from s3
- this code is needed for tests, so just putting back as is, we will need to figure it out a better way for the upgrade

CB-13425.. Addendum: put back cdp-logging-agent manual install.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java

Additional waiter logic has been introduced between stop and start to let the VMs stop on GCP while the real fix hasn't  been implemented.
This PR is depends on [PR-12376](https://github.com/hortonworks/cloudbreak/pull/12376)

CB-15932 eliminate workaround from environment stop-start tests.

---

datalake/src/main/java/com/sequenceiq/datalake/repository/SdxClusterRepository.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java

Jira: https://jira.cloudera.com/browse/CB-16272
This is focused on fixing an issue noticed when trying to delete an environment (even with the force flag) which had live detached DLs. Specifically, authorization would fail since the detached DLs could not be found and matched.
This should fix this.

CB-16272: Fixed SDX authorization via env CRN for detached DLs in order to allow detached DLs to be deleted via environment deletion.

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterStopHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java

Allowing DH and DL to be stopped even if they have node-failures.

CB-16051 Can't stop the environment if DL has Node failure

---

docker-autoscale/Dockerfile
docker-autoscale/bootstrap/start_autoscale_app.sh
docker-cloudbreak/Dockerfile
docker-cloudbreak/bootstrap/start_cloudbreak_app.sh
docker-datalake/Dockerfile
docker-datalake/bootstrap/start_datalake_app.sh
docker-environment/Dockerfile
docker-environment/bootstrap/start_environment_app.sh
docker-freeipa/Dockerfile
docker-freeipa/bootstrap/start_freeipa_app.sh
docker-redbeams/Dockerfile
docker-redbeams/bootstrap/start_redbeams_app.sh
integration-test/test-image/Dockerfile
mock-infrastructure/Dockerfile
mock-thunderhead/Dockerfile

* Partially reverts cd86d83f2d069a76180e261975c6ca7c6bbabf70 / #12078.
* Changes to the following files have been untouched:
* `build.gradle`
* `integration-test/integcb/Profile_template`
* `integration-test/scripts/docker-compose.sh`

CB-16401 Temporarily revert UBI base image changes in CB Java services

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/network/NetworkResourcesCreationRequest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureNetworkConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/AzureNetworkV4Parameters.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AzureEnvironmentNetworkConverter.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/EnvironmentNetworkAzureParams.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzurePrivateEndpointValidator.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/AzureNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/service/NetworkCreationRequestFactory.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/AzureEnvironmentNetworkConverter.java
environment/src/main/resources/schema/app/20220214071457_CB-16106_Bring_Your_Own_Private_DNS_Zone_(BYODZ).sql
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/azure/AzurePrivateEndpointValidatorTest.java
structuredevent-model/src/main/java/com/sequenceiq/environment/network/dto/AzureParams.java

As the first commit of Bring Your Own DNS Zone feature, it introduces API changes to environment service:
- in the request a new Azure related field, privateDnsZoneId in network request is introduced, it takes a full azure resource id
- the id is then saved into the environment_network table
- the response returns an additional field privateDnsZoneId
However, the functionality should not yet change: if serviceEndpointCreation is set to enabledPrivateEndpoint, then the private DNS zone is still created in the single RG.

CB-16271 Bring your own DNS zone - environment API + DB changes

---

core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaConfigProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaConfigProviderTest.java
orchestrator-salt/src/main/resources/salt/salt/sssd/template/join_ipa.j2

- modified FreeIPA instance selection logic to prefer primary gateway
- `ipa-client-install` command now is using `--server` option to connect to the pgw if possible
Tested by creating a cluster and checking the rendered script on the host.

CB-15455 ipa client should prefer the primary gateway

---

datalake-dr-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/datalakedr/datalakeDRGrpc.java
datalake-dr-connector/src/generated/main/java/com/cloudera/thunderhead/service/datalakedr/datalakeDRProto.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/converter/GrpcStatusResponseToDatalakeBackupRestoreStatusResponseConverter.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/converter/OperationEnum.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/model/DatalakeBackupStatusResponse.java
datalake-dr-connector/src/main/proto/datalakedr.proto
datalake-dr-connector/src/test/java/com/sequenceiq/cloudbreak/datalakedr/converter/GrpcStatusResponseToDatalakeBackupStatusResponseConverterTest.java

This change updates the datalakedr.proto file and re-generates the associated Java classes.
When processing datalake backup/restore responses, extract the failure reason from the new
operationStates object instead of the old failureReason field. If the response indicates the
operation failed, each field in operationStates will be parsed to construct a single failure string
that combines the status of each operation. The failure string will include information about what 
operation each failure belonged to. Additionally, if all operations for a particular service (HBase
or Solr) have identical failure reasons, these will be condensed for readability.
If the operationStates object is not set, the old failureReason field will be used instead.
Tested with unit tests and on locally deployed …

CB-15355 Use new backup/restore status information in CB flows

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/dr/BackupRestoreStatusService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/dr/BackupRestoreStatusServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/handler/DatalakeDatabaseBackupWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/handler/DatalakeDatabaseRestoreWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreService.java
datalake/src/main/resources/schema/app/20220304194213_CB-8676_Datalake_database_backup_stderr_output_has_non-error_messages.sql
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Modifies the database backup and restore scripts to reduce the amount of non-error logging going to
stderr. The script changes are:
- Removes xtrace logging from backup_db.sh and restore_db.sh so less noise is in the stderr otuput.
- Adds a trap to both scripts so that output that was previously only going to the terminal is
being captured in the log file.
- Reduces the hdfs commands to log level ERROR, so lower level logs don't show up in stderr. This
has the result of hdfs generating less logging overall, but we should still see logging about any
error cases.
There is also new logic in BackupRestoreStatusService to strip any lines that are not related to
errors from the stderr output. The newly stripped down output is used as the failure reason in the
case of a database failure. The …

CB-8676 Datalake database backup stderr output has non-error messages

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/cloudbreak/CloudbreakInstanceWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/freeipa/FreeIpaInstanceWaitObject.java

Remove unhealthy instance status check, because of flaky E2E test results in the past few days.

CB-15862 Revert UNHEALTHY instance check

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/view/RdsConfigWithoutCluster.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/config/update/PillarConfigUpdateService.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/RdsConfigWithoutClusterRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/GatewayConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/TlsSecurityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterDBValidationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RdsConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RdsConfigWithoutClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/SharedServiceConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterDBValidationServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/RdsView.java
template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/views/RdsViewTest.java

The rds config fetch is too expensive because the hibernate fetch all of the attached clusters as references.

CB-16388 RDSConfig calculation take long time, refactor the RdsConfig select by clusterId

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/init.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_install.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_replica_install.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/templates/initial-ldap-conf.ldif

we identified issues were were were close to running out of database locks. There were some math formulas which suggested that we increase the locks significantly (e.g. 2M). But we found increasing it from 50k to 200k was effective.
To avoid LDAP server restart the change is added to the installation phase

CB-15451 Use 200k LDAP database locks in FreeIPA

---

core/src/main/resources/defaults/blueprints/7.2.14/cdp-dde.bp
core/src/main/resources/defaults/blueprints/7.2.15/cdp-dde.bp

When creating a data hub using the DDE template, machines in the gateway
instance group did not get the solr-gateway role. As a consequence of this, the
solrctl command did not work from these machines.

CB-15877: solrctl does not work on the gateway machines of the DDE template

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/Crn.java

The previous regex didn't allow for partitions with a 'hyphen' in it,
causing partition name 'cdp-us-gov' to fail. Also added Neil's
change to remove backtracking. This makes the regex used in cloudbreak
be the same as the one in thunderhead.
Reference:
- https://github.infra.cloudera.com/thunderhead/thunderhead/commit/e3c87608308d149c836f58d71ea8b49c2f65cbd7
- https://github.infra.cloudera.com/thunderhead/thunderhead/commit/6a771e0da29b7727bc6f10a5dc640583bef805c2

CDPCP-6171 update crn regex

---

orchestrator-salt/src/main/resources/salt/salt/post-recipes/scripts/createuserhome.sh
orchestrator-salt/src/main/resources/salt/salt/recipes/post-cluster-install.sls

As we are moving toward to have thousands of users some tweaks are necessary to handle it a bit better:
- instead of querying the whole user from now only the login is queried
- instead of running the script every minute it will run every 5 minute to ease the load on FreeIPA
- random delay is added to the script, between 0 and 179 sec, so the clusters won't start pulling data from FreeIPA at once
This is still a workaround, and the whole script should be removed.

CB-15452 Tune `createuserhome.sh` for larger number of users

---

datalake/src/main/java/com/sequenceiq/datalake/service/SdxEventsService.java

Jira: https://jira.cloudera.com/browse/CB-16451
Please look at the Jira description for the reason behind this bug and how I resolved it. Essentially, SDX events will run into an error if any of the environment's DLs are deleted, this being a result of additional error handling we added into 2.54.0.
This simply does nothing for the cloudbreak events if the DL is deleted, allowing for its SDX events to still be present, but not breaking the overall event retrieval.
I have tested this both via local UI and through both endpoint methods via Postman.

CB-16451: Fix issue when getting SDX events for environment with deleted datalakes.

---

core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJob.java

Stack.toString() throws an org.hibernate.LazyInitializationException if the stack resources are not queried, so the log was modified to only include the CRN.

CB-16444 Fix stack log of ExistingStackPatcherJob

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxBackupAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxBackupInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxRestoreInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxSyncAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxSyncInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/SdxBackupRestoreTest.java
integration-test/src/main/resources/testsuites/e2e/l0promotion/sdx-backup-tests.yaml

After [CB-16095: Wrong http for Solr service port in Knox topology. #12268](https://github.com/hortonworks/cloudbreak/pull/12268) has been merged, we can restore the related test case as well with name `SdxBackupRestoreTest`. Beyond this we can rewind the modified wait times in the related test actions as well.

CB-16352 Restore the SdxBackupRestoreTest after fixing wrong http for Solr service port

---

client-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/ClouderaManagerApiClientProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java

Add services through the host template feature (OPSAPS-60099) in the public cloud needs CM to store the host and host template mapping. Because in public cloud roles and services are added into the cluster by adding role config group to host template and then reapplying host template on all the associated hosts.
So we are storing host templates and host mapping by adding CM tag on the host. Tag name will be _cldr_cm_host_template_name and value will be template name for the host i.e -> (Tag name =_cldr_cm_host_template_name, value = template name, entity_id = hostid ).
These tags will be automatically added when performing an apply host template. For new installations, these tags will be added while setting up a cluster using import cluster template API(as it performs apply host template …

CB-14700 Add host template name as tag to hosts after upgrade

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java

Sometimes usersync can fail and leave users not fully available.
To avoid test failures caused by failing initial usersync, kinit test is only runs if last usersync is `COMPLETED`.See detailed description in the commit message.

CB-16518 Run kinit test only if usersync is COMPLETED

---

core/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/7.2.15/cdp-streaming-ha.bp
core/src/main/resources/defaults/clustertemplates/7.2.15/aws/streaming-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.15/azure/streaming-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.15/gcp/streaming-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.15/yarn/streaming-ha.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

This commit adds a new streaming template to enable high availability for Zookeeper and Schema Registry as well.
It is basically derived from the Heavy Duty template. The node layout is the following:
- master: 1 node that runs Cruise Control, Streams Messaging Manager and Cloudera Manager.
- core_zookeeper: 3 nodes running Zookeeper and Schema Registry
- core_broker: 3 nodes running the core Kafka brokers
- broker: nodes running scalable Kafka brokers
- srm: nodes running Streams Replication Manager
- connect: nodes running Kafka Connect

CB-15784: Streaming template for Zookeeper Multi AZ

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties

As the root cause was the auto-start configuration setup for Knox. Just starting the services would not work as the knox service is up even before the RDC refresh is performed.
Changing the logic from just starting the services to restarting the services.
Made sure that the issue is not observed in the local dev environment.

CB-16477: [In-Place Migration][7.2.12][AWS][mow-int] Restart of services with stale configurations is not issued for when starting OpsDB DH

---

common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/CcmConnectivityParameters.java
common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/CcmV2JumpgateParameters.java
common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/CcmV2Parameters.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/Stack.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaOrchestrationConfigService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/SaltConfigProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/userdata/UserDataService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/upgrade/ccm/CcmParametersConfigService.java
freeipa/src/main/resources/schema/app/20220321174423_CB-14578_add_ccmparameters.sql
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/SaltConfigProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/userdata/CcmUserDataServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/upgrade/ccm/CcmParametersConfigServiceTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

For the migration from earlier versions.
Store the parameters on FreeIPA Stack to persist them for the flow chain.
Prepare UserDataService and FreeIpaOrchestrationConfigService to accept CCM parameters
from Stack.

CB-14578 Make CCMv2 Jumpgate parameters serializable

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureSetup.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureStorageAccountBuilderService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtilsTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureStorageAccountBuilderServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/upscale/AzureUpscaleServiceTest.java

Azure policies blocking resource creation is a recurring issue for customers, so we should ease the identification of the policy, and include it in the error message.

CB-16512 Include Azure policy name in failure reason

---

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/CustomConfigurationsToCustomConfigurationsDetailsConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/converter/CustomConfigurationsToCustomConfigurationsDetailsConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverterTest.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/CustomConfigurationsDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StackDetails.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToCDPClusterShapeConverter.java
structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToCDPClusterShapeConverterTest.java
usage-collection/src/main/proto/usage.proto

- Added new column to `CDPClusterShape` to determine the services and roles of custom configurations that were used for the DH cluster
- New field `customConfigurations` in `StackDetails`
- UT for the relevant converters.

DISTX-731 Propagate telemetry metrics for custom configurations

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java

In the below scenario
1) have a DH (e.g. 7.2.12),
2) in the components table change the image back to an older version (mimicking the scenario where CM and CDH upgrade runs fine but image change is not done due to an error),
3) run a fresh upgrade (customer wants to finish the upgrade so that the image is changed)
the upgrade will fail in the cluster sync step of stack image change flow. The sync will fail with: Services installed but not running.
This commit makes sure that after the CDH upgrade all services are started.

CB-16573 Upgrade fails when CDH was upgraded separately

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/cloudbreak/CloudbreakInstanceWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/freeipa/FreeIpaInstanceWaitObject.java

Some of the E2E tests are failing, because of `java.lang.NullPointerException` from:
```
...
at com.sequenceiq.it.cloudbreak.util.wait.service.instance.cloudbreak.CloudbreakInstanceWaitObject.actualStatusReason(CloudbreakInstanceWaitObject.java:75)
at com.sequenceiq.it.cloudbreak.util.wait.service.instance.InstanceOperationChecker.handleTimeout(InstanceOperationChecker.java:55)
at com.sequenceiq.it.cloudbreak.util.wait.service.instance.InstanceOperationChecker.handleTimeout(InstanceOperationChecker.java:12)
at com.sequenceiq.it.cloudbreak.util.wait.service.WaitService.waitObject(WaitService.java:60)
...
```
and 
```
...
com.sequenceiq.it.cloudbreak.util.wait.service.instance.freeipa.FreeIpaInstanceWaitObject.actualStatusReason(FreeIpaInstanceWaitObject.java:68)
at …
```

CB-16555 instance status checker should never fail when status reason is not present

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/userdata/UserDataBuilder.java
core/src/main/resources/init/init.ftl
core/src/test/java/com/sequenceiq/cloudbreak/service/image/userdata/UserDataBuilderTest.java
core/src/test/resources/azure-gateway-init-authproxy.sh
core/src/test/resources/azure-gateway-init-noauthproxy.sh
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/userdata/UserDataBuilder.java
freeipa/src/main/resources/init/init.ftl
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/userdata/UserDataBuilderTest.java
freeipa/src/test/resources/azure-ccm-init.sh

It caused an issue when the user created a https proxy but the proxy URL was
assembled with fixed "http" protocol
Needs a fix in the cloudbreak-images repo too.

CB-16575 User data did not contain the proxy's protocol

---

datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/DatalakeDrClient.java
datalake/src/main/java/com/sequenceiq/datalake/service/recovery/RecoveryService.java
datalake/src/main/java/com/sequenceiq/datalake/service/recovery/SdxRecoverySelectorService.java
datalake/src/main/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreService.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/recovery/SdxUpgradeRecoveryService.java
datalake/src/test/java/com/sequenceiq/datalake/service/recovery/SdxRecoverySelectorServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/recovery/SdxUpgradeRecoveryServiceTest.java

This commit validates for an existing successful backup taken with the original runtime present before upgrade.
The Thunderhead change that includes the Runtime information for a given backup is, it is on "Stage" now:
https://github.infra.cloudera.com/thunderhead/thunderhead/commit/66e8a169fcb11e5f27d28843bb594bea9b88d981

CB-11052 - Validate existing backup for recovery

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceTypeProvider.java
freeipa/src/main/resources/application.yml

CB-16559 : Change FreeIPA default instance type to make it compatible for encryptionAtHost
This commit updates the default instance type for FreeIPA from "Standard_D3_v2" to "Standard_DS3_v2". Also, fixes a comment for AWS default instance type.

CB-16559 : Change FreeIPA default instance type to make it compatible for encryptionAtHost

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXScaleAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/distrox/DistroxScaleThresholdAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/DistroXTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXResilientScaleTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXScaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXScaleTestParameters.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXStopStartScaleTest.java
integration-test/src/main/resources/testsuites/e2e/distrox-resilientscale-tests.yaml

Based on the [CB-15971](https://jira.cloudera.com/browse/CB-15971) E2E test proposals to cover `usecase4` improvements regarding resilient scaling:
1. Start upscale on running cluster with percentage option with at least option
2. Provider only gives back above threshold
3. Upscale should complete

CB-16458 E2E tests for Resilient Scaling with percentage option

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/UpscaleClusterRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/UpscaleClusterHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/TlsSecurityService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterUpscaleServiceTest.java

Recommission decommissioned nodes during repair. This change fixes repair during stop/start scaling where we need to recommission nodes. It also fixes the cluster when the user decommissioned a node.

CB-16426 Recommission decommissioned nodes during repair

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/E2ETestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/AbstractE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java

We experienced malfunction at our API E2E project `Tear down context` in case of the Tag Validation is failing at [E2ETestContext](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/E2ETestContext.java#L28-L32):
```
@Override
public void cleanupTestContext() {
getResourceNames().values().forEach(value -> tagsUtil.verifyTags(value, this));
super.cleanupTestContext();
}
```
If the `tagsUtil.verifyTags` is failing, then the `super.cleanupTestContext()` wont be executed.
We should fix this part and force the cleanupTestContext even if the verifyTags is failing.

CB-16479 Move Tag Validation from TestContext Cleanup

---

datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/flow/chain/DatalakeResizeFlowEventChainFactory.java
datalake/src/main/java/com/sequenceiq/datalake/flow/chain/DatalakeResizeRecoveryFlowEventChainFactory.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachFlowConfig.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachRecoveryActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachRecoveryEvent.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachRecoveryFlowConfig.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachRecoveryState.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/event/DatalakeResizeRecoveryFlowChainStartEvent.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/event/SdxDetachRecoveryFailedEvent.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/event/SdxStartDetachEvent.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/event/SdxStartDetachRecoveryEvent.java
datalake/src/main/java/com/sequenceiq/datalake/flow/start/event/SdxStartStartEvent.java
datalake/src/main/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachDetachUtils.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/attach/SdxDetachService.java
datalake/src/test/java/com/sequenceiq/datalake/flow/chain/DatalakeResizeRecoveryFlowEventChainTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/attach/SdxDetachServiceTest.java
flow/src/main/java/com/sequenceiq/flow/reactor/eventbus/ConsumerCheckerEventBus.java
flow/src/test/java/com/sequenceiq/flow/core/AbstractActionTestSupport.java

Jira: https://jira.cloudera.com/browse/CB-14399
This change is focused on introducing a new flow chain for recovering from DL resize failures. In creating this change I also fixed existing bugs which caused recovery to fail due to the way in which the detach logic functioned.
**Recovery Flow**
1. Detach the DL to be deleted.
2. Delete the DL.
3. Re-attach the old DL that has to be recovered.
4. Start the DL
There are therefore three main parts to this change:
- Creation of the DL Resize Recovery flow chain
- Involves the new chain, new events, a trigger method, and a new flow within the existing SDX Detach flow (primarily in DetachActions)
- Modifying the SdxClusterStatusCheckerJob to work when a cluster's stack's CRN is modified (otherwise this would mark the cluster as failed during …

CB-14399 : Added a new flow chain for recovering from DL Resize failures.

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/RemoveReplicationAgreementsHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java

Sometimes adding a replica topology fails when upscaling FreeIPA.
After the investigation it seems this is caused by the way FreeIPA/389ds replication works, as it's eventual consistency.
If the new FreeIPA instance is in connection with an instance and the new topology command runs against another replica it might have not the information yet.
To avoid this issue until CB-15454 is implemented, a retry is added to give time for the replication to happen.
The chance for the issue to happen without this retry according to my test runs is about 5%, after the change I wasn't able to reproduce the issue.

CB-16547 Upscale failed during Post installing FreeIPA

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerModelBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/loadbalancer/AzureLoadBalancer.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/loadbalancer/AzureOutboundRule.java
cloud-azure/src/main/resources/templates/arm-v2.ftl
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerModelBuilderTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java
common-model/src/main/java/com/sequenceiq/common/api/type/LoadBalancerSku.java
common-model/src/main/java/com/sequenceiq/common/api/type/LoadBalancerType.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java

Adds a new load balancer type, OUTBOUND. An OUTBOUND load balancer is a public load balancer that
only does egress, and does not have any rules for routing ingress traffic. This is used in Azure
clusters when public IPs are disabled. With the Standard load balancer, any VMs behind a private LB
will not have a path for public egress. So in that scenario, an outbound only load balancer will
also be created solely to handle public egress.
This also changes the default Azure load balancer SKU from BASIC to STANDARD.
Tested by setting up a cluster with only the private LB and verifying the VMs behind it had no path
to the internet, and then setting up a cluster with a private LB and a second outbound only LB and
verifying the VMs could now do public egress over the internet.
This change is an …

CB-16504 Outbound only load balancer option

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerStatusListenerTask.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java

This commit contains the following:
- stopCluster check if CM is up and running
- if it is stopped then we do not attempt to stop it once again as it would result in an ApiException
- if not then the logic is as it used to be

CB-15848 - Cloudera Manager upgrade flow step is not restartable

---

core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ClouderaManagerProductTransformer.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ClouderaManagerProductTransformerTest.java

When we try to get the parcels from the image we can get a NPE when the image is a base image.
The reason for this exception is that there are no parcels on the image.
After this change, we're checking the image type and return an empty list if the image is not pre-warmed.

CB-16624: Do not transform the parcels from the image to ClouderaManagerProduct in case of base images.

---

orchestrator-salt/src/main/resources/salt-common/salt/telemetry/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/telemetry/template/proxy.env.j2
orchestrator-salt/src/main/resources/salt-common/salt/telemetry/upgrade.sls

details:
- at the moment repo usage is skipped if it is available
- possibly, with wrong paywall credentials - it's still can be available but you can get 403 errors
- to avoid authz/r issues, use a curl against the Rpm key, to see we can successfully download it, if we cannot, delete the repo file if it was created before and do not execute any upgrade commands
- in case of no desiredXXXVersion is set, skip the repo file generation (for the deletion, that will be handled)

CB-16361. Add extra tests against cdp-infra-tools repo.

---

autoscale/build.gradle
build.gradle
cloudera/docker_images.yaml

RE mentioned that we logging the success tests as well which is not required

CB-16724 Reduce the unit test output in builds

---

cloudera/docker_images.yaml

Backporting consumption service related build fix from master.

CRB-1916 disable consumption service related docker image from the build temporarily

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/converter/StackPatchStatusConverter.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/StackPatch.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/StackPatchStatus.java
core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJobInitializer.java
core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJobService.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackPatchRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/ExistingStackPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/MockPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/StackPatchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/StackPatchUsageReporterService.java
core/src/main/resources/schema/app/20220303125000_CB-16079_alter_stackpatch_table_add_status_columns.sql
core/src/test/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJobInitializerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJobTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/ExistingStackPatchServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/MockPatchServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/StackPatchServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/StackPatchUsageReporterServiceTest.java

Stack patcher should not schedule jobs for stacks that are either already finalized: either unsheduled, not affected or already fixed.

CB-16079 Do not schedule finalized stack patches

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/service/ClouderaManagerProductsProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/install/FinalizeClusterInstallHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/ImageReaderService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/ImageReaderServiceTest.java

This commit contains the following improvements:
- Removing unused parcels after cluster creation. This causes that only the activated parcels will be present on the CM and all prewarmed parcel (in downloaded) states will be removed.
- In the case of DataLake stack, we're not getting the required parcels by the ParcelFilterSercice instead only the CDH parcel will be used directly.

CB-16257: Remove phantom parcels from CM and DB which can cause stuck upgrades and upscales.

---

structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/EnvironmentDetailsToCDPNetworkDetailsConverter.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/EnvironmentDetailsToCDPNetworkDetailsConverterTest.java
usage-collection/src/main/proto/usage.proto

On Azure (and also on AWS) it is possible to create private endpoints to a select of cloud services. On Azure this requires the creation of a private DNS zone to resolve the service.
Up to now the DNS zone was created by CDP. A new feature, however, is to allow the customer to provide its own private DNS zone.
This commit enhances the EDH tracking of the private endpoint feature with specifying if the DNS zone was provided by the customer (aka Bring your own DNS zone) or is managed by CDP.

CB-16289 CB-16289 Bring your own DNS zone - EDH integration

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsVirtualGroupCreateService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UmsVirtualGroupCreateServiceTest.java

CB-16587 We should perform virtual group creation only for available stacks to avoid orphan workload administration groups in the UMS.

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_token.xml.j2

Fixed the OpDB Agent topology files. The service name in Knox is OPDB-AGENT and in CM it is called OPDB_AGENT.

CB-16609 Expose OpDB Agent service - correct CM and Knox service names

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java

Until CB-15454 is fixed we can't ensure the same instance receives the list and add/del requests. With the replication delay we can't ensure the assert returns valid result.

CB-15454 Disable DNSZone list assert in FreeIPA upgrade test

---

auth-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/usermanagement/UserManagementGrpc.java
auth-connector/src/generated/main/java/com/cloudera/thunderhead/service/common/options/Options.java
auth-connector/src/main/proto/options.proto
auth-connector/src/main/proto/usermanagement.proto

Update usermanagement.proto, rebuild and check in build artifacts.
We also need to include options.proto to define the "deprecated"
flag that's used in the usermanagement.proto.

CDPCP-6883. Update usermanagement.proto

---

datalake/src/main/java/com/sequenceiq/datalake/service/recovery/SdxRecoverySelectorService.java
datalake/src/test/java/com/sequenceiq/datalake/service/recovery/SdxRecoverySelectorServiceTest.java

Jira: https://jira.cloudera.com/browse/CB-16794
Please look at the Jira for an explanation on what this issue is and how it occurs.
Basically there is no reason to throw an exception here, an exception is thrown anyway if recovery validation is unsuccessful for all services.

CB-16794: Ignore exceptions during recovery validation to allow other recovery services to be used.

---

core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.14/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.15/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/clustertemplates/7.2.11/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.11/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.11/gcp/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.11/yarn/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.12/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.12/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.12/gcp/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.12/yarn/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.14/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.14/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.14/gcp/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.14/yarn/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.15/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.15/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.15/gcp/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.15/yarn/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.16/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.16/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.16/gcp/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.16/yarn/dataengineering-spark3.json

The Spark 3 template is missing the option to add gateway nodes and this has been requested by one of the customers. They would like to have this added to 7.2.11 and later templates.

CB-16440 Add gateway nodes to Spark3 DataHub template

---

core/src/main/java/com/sequenceiq/cloudbreak/san/LoadBalancerSANProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/FreeIPAEndpointManagementService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/GatewayPublicEndpointManagementService.java
core/src/test/java/com/sequenceiq/cloudbreak/san/LoadBalancerSANProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/publicendpoint/FreeIPAEndpointManagementServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/publicendpoint/GatewayPublicEndpointManagementServiceTest.java

Adds a condition to the logic to select a load balancer for DNS registration to never select an
OUTBOUND load balancer. Also renames the method to clarify what the selection is for.
This is the CB-2.55.0 branch version of the PR originally posted at https://github.com/hortonworks/cloudbreak/pull/12613

CB-16814 Outbound load balancer being selected for DNS registration

---

datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxRecoveryController.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java

Jira: https://jira.cloudera.com/browse/CB-16759
Essentially recovery used to only be doable on SDX clusters that were not detached due to the way in which it got the cluster via its name.
This change simply uses a new function on top of an already existing repository query.
Please note that I tested this by modifying the original `getByNameInAccount` method. I could not test these changes exactly as they are since I could not get the changes to the `SdxRecoveryController` to build locally for some reason. Not sure if it's always been the case that controller modifications require some extra work to rebuild locally.

CB-16759: Made it so recovery can be performed on an SDX cluster that is detached, allowing for more flexibility with resize recovery.

---

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java

Jira: [CB-16551](https://jira.cloudera.com/browse/CB-16551) Add Event History when the data lake is resized.
Add eventPublis to the Datalake resize trigger method. Add resource value to the message.properties. 
Tested by running locally and verifying:
- datalake resize trigger works and do what is expected.
- EventLog is created and published and contains the proper value from the properties.

CB-16551: add event publish to the trigger method

---

core/src/main/resources/defaults/clustertemplates/7.2.14/aws/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.14/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.14/aws/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.15/aws/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.15/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.15/aws/dataengineering.json

DISTX-681: Switch DE templates to use temporaryStorage as ephemeral volumes
This commit changes the instance type for compute and worker nodes of Data engineering cluster templates for AWS of 7.2.14 and 7.2.15.
Compute nodes are updated to use "r5d.2xlarge" and "r5d.4xlarge" for non-ha and ha templates respectively with ephemeral volume.
Worker nodes are updated to use "r5d.2xlarge" and "r5d.4xlarge" for non-ha and ha templates respectively with gp2/ebs volume.

DISTX-681: Switch DE templates to use temporaryStorage as ephemeral volumes

---

docker-autoscale/bootstrap/start_autoscale_app.sh
docker-cloudbreak/bootstrap/start_cloudbreak_app.sh
docker-consumption/bootstrap/start_consumption_app.sh
docker-datalake/bootstrap/start_datalake_app.sh
docker-environment/bootstrap/start_environment_app.sh
docker-freeipa/bootstrap/start_freeipa_app.sh
docker-redbeams/bootstrap/start_redbeams_app.sh

Use set -e in docker application start scripts to fail fast if cert import fails.

CB-16837 Use set -e in docker application start scripts to fail fast

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/distrox/DistroxScaleThresholdAssertions.java

Our [API AZURE E2E Build #3104--2.56.0-b28-AZURE (13-Apr-2022 11:51:44)](http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-azure/3104/) is failing, because of:
```
com.sequenceiq.it.cloudbreak.exception.TestFailException: Available Compute node count '1' is NOT match with the required (at least) scale percentage '90'.
Expected: a value equal to or greater than <9.0F>
but: <1.0F> was less than <9.0F> 
Resource Crn: crn:cdp:datahub:eu-1:qe-azure:cluster:9fbbb7dc-1a43-4521-be06-bdc9782b2bf2
```
Actually the referenced assertion did not get the right number of the scaled instances. So I fixed the related InstanceId getter for the assertion.

CB-16846 DistroX resilient scaling test failed with wrong number of new instances

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/ClusterRepairTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxInternalUpgradeAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxUpgradeTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxUpgradeTests.java

We would like to do DL OS upgrade in a rolling style:
Select one node from every hostgroup at once and do this until all
nodes are updated.
It is very important to select primary gateway in the first round.
It will result the HA Medium Duty being available in the upgrading process
because replication is > 2 for every service and we don't kill more
than 1 node from a host group. So the service on the other node(s) should
handle requests and it should work properly.

CB-16698 ZDU OS upgrade for DL

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/ums/BulkUmsUsersStateProvider.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/ums/BulkUmsUsersStateProviderTest.java

GRPC requests have a 1 minute timeout. The UMS bulk user sync state rpc
spends a long time decrypting credentials and may exceed the 1 minute timeout
when retrieving 2500+ actors.
A flag was added to the request to skip credentials retrieval in the bulk rpc.
This commit adds the flag to the GrpcUmsClient and modifies the
BulkUmsUsersStateProvider to retrieve the credentials separately.

CB-16497. Usersync retrieve credentials separately from bulk ums model

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsInstanceConnector.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/client/AmazonEc2Client.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/util/AwsInstanceStatusMapper.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsInstanceConnectorRetryingTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsInstanceConnectorTest.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterStatusService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerConnector.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/step/VmStatusCheckerConclusionStep.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderService.java
core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/RestartCmForLbHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/RestartClusterManagerServerHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/WaitingClusterServerHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterApiConnectors.java
core/src/test/java/com/sequenceiq/cloudbreak/conclusion/step/VmStatusCheckerConclusionStepTest.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJobTest.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusIntegrationTest.java

Improved StackStatusCheckerJob performance by:
- reducing CM connect/read timeouts,
- optimizing AWS instance status check by describing only the status and only describe the instance when the status is terminated (this is necessary because for terminated instances we gather additional information such as spot termination by the provider)

CB-16701 Improved StackStatusCheckerJob performance

---

core/src/main/java/com/sequenceiq/cloudbreak/service/recipe/UpdateRecipeService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/recipe/UpdateRecipeServiceTest.java

details:
- generated recipes entities are generated during cluster operations like deploy, upscale etc.
- in case of a recipe is detached and right after that is deleted, the next cluster operation that includes recipe operation will fail
- reason is, after recipe deletion, recipe is only set to archived, therefore cascading deletion is not used for the generated recipe, but for the quires, archived = true is skipped, so it can result an EntityNotFoundException, which can block upscales.

CB-16893. Prevent EntityNotFoundException when handling recipes.

---

cloudera/docker_images.yaml

- turning back cinsumption-service build to why it fails
- local build works
- `./gradlew :cloud-consumption:publishToMavenLocal` works
- since we lost the logs this is the only way to find out why the build failed on releng portal

CB-16668 Reenabling consumption service build

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java

Jira: https://jira.cloudera.com/browse/CB-16759
I recently made an initial change for this in: https://github.com/hortonworks/cloudbreak/pull/12585 thinking it was working as expected, but what I initially thought worked didn't.
Essentially, the resource authorization done by the Recovery API method calls an internal method which obtains the DL in a way that does not allow detached DLs. This makes recovery of detached DLs impossible.
This change makes it so the resource authorization is able to be done on detached DLs as well. I have tested this fully and in the correct manner this time.

CB-16759: Have resource authorization doable on detached DLs in order to enable recovery on detached DLs.

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/context/CloudContext.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceGroupMetadataProvider.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/detach/StackUpdateService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/AbstractStackTerminationAction.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackInstanceStatusChecker.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java
core/src/main/resources/schema/app/20220408210524_CDPSDX-3491:_Adding_original_name_field_to_stack.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverterTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachDetachUtils.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/attach/SdxDetachService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/attach/SdxDetachServiceTest.java

Jira: https://jira.cloudera.com/browse/CDPSDX-3491
Main issue here is that for certain cloud providers (specifically Azure and the Mock Cloud Provider), in some cases the stack name is used to define important resources.
For Azure this includes the name of the resource group created where the stack instances are located (this is only for cases where the environment is created without a pre-specified resource group).
It's very clear that after a detach, when the stack name is modified, these resources will no longer be able to be located resulting in errors.
Specifically, we see errors in two places:
- The `StackStatusCheckerJob` as it attempts to verify the health of the stack instances using an incorrect resource name
- The termination of the stack, where it attempts to terminate the …

CDPSDX-3491: Modified use of stack name for stack termination and status checking when the stack is detached to avoid multiple issues.

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/provision/ExternalDatabaseCreationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/provision/handler/CreateExternalDatabaseHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/start/ExternalDatabaseStartActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/start/handler/StartExternalDatabaseHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/stop/ExternalDatabaseStopActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/stop/handler/StopExternalDatabaseHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/terminate/ExternalDatabaseTerminationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/terminate/handler/TerminateExternalDatabaseHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/externaldatabase/CreateExternalDatabaseRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/externaldatabase/StartExternalDatabaseRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/externaldatabase/StopExternalDatabaseRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/externaldatabase/TerminateExternalDatabaseRequest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/EnforceEntityDenialInFlowPayloadTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/provision/handler/CreateExternalDatabaseHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/start/handler/StartExternalDatabaseHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/stop/handler/StopExternalDatabaseHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/terminate/handler/TerminateExternalDatabaseHandlerTest.java

I checked that removing the stack from these events is backward compatible, flows will be able to restart.

CB-16727 Remove stack from external database related flow payloads

---

datalake/src/test/java/com/sequenceiq/datalake/flow/SdxReactorFlowManagerTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/action/RedbeamsProvisionActions.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/event/allocate/AllocateDatabaseServerRequest.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/event/register/UpdateDatabaseServerRegistrationRequest.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/handler/AllocateDatabaseServerHandler.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/handler/UpdateDatabaseServerRegistrationHandler.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/action/RedbeamsTerminationActions.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/event/deregister/DeregisterDatabaseServerRequest.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/handler/DeregisterDatabaseServerHandler.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/EnforceEntityDenialInFlowPayloadTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/provision/action/RedbeamsProvisionActionsTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/provision/handler/AllocateDatabaseServerHandlerTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/provision/handler/UpdateDatabaseServerRegistrationHandlerTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/termination/handler/DeregisterDatabaseServerHandlerTest.java

Removed DBStack entity type from redbeams flow events. Fixed one datalake unit test which took 1 minute, now it takes 1 sec.

CB-16711 Removed DBStack entity type from redbeams flow events

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ProcessAutoRestartInjector.java

Enabled autorestart for OMID as OMID server getting crashed when the HBase service is stopped or having any issues. As a workaround we are enabling the autorestart.
**Tested on Local CB.**
1. Created an Operational Datahub cluster with the change and verified the auto restart in OMID config is enabled.

CB-16960: Enabled Autorestart for OMID in Datahub.

---

core/src/main/resources/defaults/clustertemplates/7.2.14/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.14/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.14/azure/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.15/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.15/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.15/azure/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.16/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.16/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.16/azure/dataengineering.json

DISTX-681: AZURE: Switch DE templates to use temporaryStorage: EPHEMERAL or temporaryStorage: COMBINED/EPHEMERAL_OR_ATTACHED
This commit changes 7.2.14, 7.2.15, 7.2.16 runtime versions of DE, DE-HA and DE spark3 templates.
- The master instance type for DE Spark3 template is changed from "Standard_D8_v3" to "Standard_D16_v3".
- The attached volume count for compute host group is changed to 0. So that only ephemeral/local volumes are used by default.
Compute nodes run YARN and require storage only for temporary data - this requirement is fulfilled by instance storage, so making the attached volumes count to 0 by default is better for customer w.r.t cost.

DISTX-681: AZURE: Switch DE templates to use temporaryStorage: EPHEMERAL or temporaryStorage: COMBINED/EPHEMERAL_OR_ATTACHED

---

common/src/main/java/com/sequenceiq/cloudbreak/quartz/JobDataMapProvider.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/configuration/JobAppVersionVerifier.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/configuration/QuartzConfig.java
common/src/main/java/com/sequenceiq/cloudbreak/util/VersionComparator.java
common/src/test/java/com/sequenceiq/cloudbreak/quartz/JobDataMapProviderTest.java
common/src/test/java/com/sequenceiq/cloudbreak/quartz/configuration/JobAppVersionVerifierTest.java
common/src/test/java/com/sequenceiq/cloudbreak/util/VersionComparatorTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceVersionSupport.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/SaltBootstrapVersionChecker.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateService.java
core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJobService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/filesystem/FileSystemSupportMatrixService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogVersionFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/PrefixMatcherService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/catalog/ImageCatalogService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/runtimes/SupportedRuntimes.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackStopRestrictionService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MountDisks.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentVersionComparator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/PermittedServicesForUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/MixedPackageVersionComparator.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/CDPConfigService.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxExternalDatabaseConfigurer.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreService.java
freeipa/src/main/java/com/sequenceiq/freeipa/util/AvailabilityChecker.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java

With rolling deployments it can be an issue that a quartz job is scheduled with the newer app version, but an older app tries to execute it and fails.
This is fixed by adding the app version to the job data map, and comparing it to the executing app's version.
Additionally, VersionComparator had to be moved to common module.

CB-16869 Veto job execution if it was scheduled with newer app version

---

orchestrator-salt/src/main/resources/salt-common/salt/monitoring/exporters.sls
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/scripts/noproxy_check.py
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/systemd/cdp-blackbox-exporter.service
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/systemd/cdp-vmagent.service.j2
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/template/blackbox.env.j2
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/template/prometheus.yml.j2
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/vmagent.sls

details:
- support vmagent to use proxy during remote write
- vmagent does not care with HTTPS_PROXY or NO_PROXY env variables, proxy can be set by a flag but no_proxy needs to be calculated, to workaround this problem, there will be a python script that will check the proxy can be bypassed or not.

CB-16945. Support https_proxy and no_proxy settings by cdp-vmagent

---

core/src/main/resources/defaults/clustertemplates/7.2.14/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.14/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.14/azure/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.15/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.15/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.15/azure/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.16/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.16/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.16/azure/dataengineering.json

Reverts hortonworks/cloudbreak#12672
Nightly test failed with validation:
http://ci-cloudbreak.eng.hortonworks.com/job/gui-e2e-azure/3101/allure/data/attachments/9953f2c0cc587312.png

Revert "DISTX-681: AZURE: Switch DE templates to use temporaryStorage: EPHEMERAL or temporaryStorage: COMBINED/EPHEMERAL_OR_ATTACHED"

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/dr/BackupRestoreStatusService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/dr/BackupRestoreStatusServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/DatalakeBackupActions.java

JIRA: CB-16642 remove, event log duplication, and the stack status update on the database backup finished status
tested locally:
- resize datalake
- datalake API triggered. 
All test result is passed.

JIRA: CB-16642 remove duplicated event logs

---

datalake/src/main/java/com/sequenceiq/datalake/service/SdxEventsService.java

Jira: https://jira.cloudera.com/browse/CB-16896
Basically we believe that there may be `NotFoundException`s that pop up due to DL creation when the DL does not have a stack yet. 
I decided to check for this and ignore exceptions when this is the case.
I am open to any feedback or comments on this as I believe this change to not be necessarily correct for the original issue.

CB-16896: Allowed for not found exceptions to not cause failure during DL event retrieval if stack not present.

---

template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidatorTest.java

Added two unit tests to CmTemplateValidatorTest to verify scaling enablement for upgraded Kafka clusters
- the blueprints under test are CDH 7.0.0
- but the actual CDH version is 7.2.11 / 7.2.12
Test verifies that its the actual CDH version that matters.

CDPD-35737 Test for scaling upgraded Kafka clusters

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProviderAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderAssertionProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProviderAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProviderAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProviderAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProviderAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProviderAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentNetworkTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java
integration-test/src/main/resources/application.yml

Currently e2e tests with private endpoints for Azure are not possible because cloudbreak tests are running in the peered network, using cloudera on-prem DNS servers. It seems that adding DNS forwarders for Azure DNS might take much time.
In this commit
1) we introduced network parameters for a second, private endpoint enabled network on Azure. If the service endpoints flag is turned on, then the private endpoint enabled network is used in the e2e tests. Also, if the databaseprivateDnsZone is filled in, then that will also be sent in the EnvRequest, and CDP will use that instead of creating its own.
2) we modified an already existing test tailored for azure single RG to use private endpoints

CB-16292 Bring your own DNS zone - e2e test

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverterTest.java

The expected behaviour from this PR is to remove the "do not encrypt" and "default encryption" options for datahubs. For environment we encrypt the freeipa,External RDS and Datalake with AWS managed key until and unless user passes a CMK during Env creation. We would like to have the same behaviour for Dtaahubs too. So as part of https://jira.cloudera.com/browse/CB-16943 UI change will be made to remove the options and this PR handles the backend behaviour for the same.
The new behaviour would be:
1. Datahubs would be encrypted with default AWS managed keys all the time when NO CMK is passed during Environment creation.
2. If User selects a different CMK from the one passed during env creation then Datahubs are encrypted by CMK2 and env by CMK1.
3. If a CMK is passed at Env level but NO …

CB-16623:Add backend changes for removing "do not encrypt" and default options from Datahubs

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProviderAssertion.java

The test testCreateDistroXWithEncryptedVolumesInSingleRG was equipped with a check that the service endpoint in the request and response do match. It, however, did not account for testparameter databsePrivateDnsZoneId to be not null but still an empty string. The present commit fixes this bug.

CB-17042 e2e: azure test with service endpoint fails

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncForStackService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/ums/UmsUsersStateProviderDispatcher.java
freeipa/src/main/resources/application.yml

Bulk ums usersync state retrieval falls back to the default ums
state retrieval on failure. The exception is now added to the logs
since it is otherwise swallowed.
Additionally, add a log message to indicate when how many large
groups are being synced to the environment.

Usersync. Improve logs

---

core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering.bp

The whitelist of Oozie NameNodes did not include the NameNodes
of the base cluster when the Oozie service was installed onto a
compute cluster, which lead to an error when an Oozie job was
submitted. This issue has been fixed in CM, so it is safe to remove
this safety valve setting.

[oozie] OPSAPS-62127 Remove Oozie NameNode whitelist setting.

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/dr/BackupRestoreStatusService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/dr/BackupRestoreStatusServiceTest.java

This is introduced with the changes done for CB-16642. Status was wrongly updated.

CDPSDX-3539: Resize datalake fails on Azure due to backup datalake failure.

---

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfigService.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfigView.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfiguration.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/NodeExporterConfiguration.java
common/src/main/resources/common-config.yml
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/exporters.sls
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/systemd/cdp-node-exporter.service.j2
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/template/prometheus.yml.j2

collectors:
- cpu
- cpufreq
- diskstats
- filefd
- filesystem
- loadavg
- meminfo
- netstat
- pressure
- processes
- stat
- systemd
- vmstat
- xfs
see more: https://github.com/prometheus/node_exporter/blob/master/README.md#collectors

CB-17045. Configure collector types for node-exporter.

---

common/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AccountMappingSubject.java

Added the streamsmsgmgr user to the mock id broker mappings. It is mapped to the Ranger identity. This is to follow up with CDPCP-6939 (add the SMM user is added to the default id broker mappings).
Testing: tested environment creation manually

CB-16838 Add SMM user to mock ID Broker mappings

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/PaywallCredentialPopulator.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/ClusterUpgradeImageValidationEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/ClusterUpgradeValidationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/config/ClusterUpgradeValidationEventToClusterUpgradeDiskSpaceValidationEventConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/event/ClusterUpgradeDiskSpaceValidationEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeDiskSpaceValidationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeImageValidationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ManifestRetrieverService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelAvailabilityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/DiskSpaceValidationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/ParcelSizeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/ParcelUrlProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/config/ClusterUpgradeValidationEventToClusterUpgradeDiskSpaceValidationEventConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeDiskSpaceValidationHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeImageValidationHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelAvailabilityServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/DiskSpaceValidationServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/ParcelSizeServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/ParcelUrlProviderTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/ImageCatalogMockServerSetup.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterCreationTest.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/controller/MockImageCatalogController.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/controller/MockParcelController.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/service/ImageCatalogMockService.java
mock-infrastructure/src/main/resources/mock-image-catalogs/catalog-with-for-upgrade.json
mock-infrastructure/src/main/resources/mock-image-catalogs/catalog-with-prewarmed.json

Add a new validator for the upgrade validation step to test the availability of the parcels.
The validator should check the following items:
- CDH parcel
- required non CDH parcels
- CM repo files
- CSD files
If the validation fails then the upgrade flow should not be started.

CB-15964: Validate the availability of the parcel before the upgrade

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/AwsCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/AzureCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java
integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml

CB-16009: Nightly e2e GCP tests should use encryption
This commit adds the e2e gcp tests for encryption key.

CB-16009: Nightly e2e GCP tests should use encryption

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/instance/AzureInstanceTemplate.java
cloud-azure/src/main/resources/templates/arm-v2-freeipa.ftl
cloud-azure/src/main/resources/templates/arm-v2.ftl
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/AzureEncryptionV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StackRequestManifesterTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/template/InstanceTemplateRequestToTemplateConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProvider.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/template/InstanceTemplateRequestToTemplateConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProviderTest.java

CB-16795: Allow encryption at host for FreeIPA and DataLake VM disks in Azure
If Encryption at Host is enabled for a VM, data stored on the VM host is encrypted at rest and flows encrypted to the Storage service.
This commit would ensure encryption at VM.
Customer needs to enable "encryptionAtHost" feature for all of their subscriptions to use this feature.

CB-16795: Allow encryption at host for FreeIPA and DataLake VM disks in Azure

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UmsClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/SetWorkloadPasswordAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/ums/ResourceRoleTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/ums/UserGroupTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/ums/VirtualGroupTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/log/Log.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/BasicEnvironmentVirtualGroupTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/DistroXRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/EnvironmentPrivilegedUserTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/EnvironmentUtil.java

Recently introduced [l0promotion.EnvironmentPrivilegedUserTest](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/EnvironmentPrivilegedUserTest.java) related `tearDownSpotValidateTags` is failing, because of:
```
Exception com.sequenceiq.it.cloudbreak.exception.TestFailException
Message: 
Default tag: [owner] value: [cb-qe-machine-envcreator-a] NOT equals [cloudbreak-qe@cloudera.com] acting user name!
Stacktrace:
at com.sequenceiq.it.util.TagsUtil.validateOwnerTag(TagsUtil.java:141)
at com.sequenceiq.it.util.TagsUtil.lambda$verifyTags$1(TagsUtil.java:90)
```
Furthermore [l0promotion.DistroXRepairTests](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/i …

CB-17073 Set workload password and UMS validation fixes

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_token.xml.j2

Knox introduced a more flexible way to map principals to groups than the existing `group.principal.mapping` mechanism in `CommonIdentityAssertionFilter`. You may check out [KNOX-2707](KNOX-2707) for further details.
This PR takes care of setting the `ENV_ASSIGNEES_####` group as virtual group mapping for anyone with at least one group.
This is required for some of our significant customers, such as Itau.
Please note this new config is not harmful to Knox in previous CDH versions; it's ignored.

CB-17079 Added Virtual Group related parameter into Knox's HadoopGroupProvider config

---

core/src/main/resources/defaults/clustertemplates/7.2.15/gcp/datamart.json
core/src/main/resources/defaults/clustertemplates/7.2.16/gcp/datamart.json

Mark featureState of GCP datamart templates as RELEASED since they're now considered GA.

CDPD-30884: Make datamart datahub template GA on GCP

---

environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentModificationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorServiceTest.java

CB-16012: Set encryption key for an existing env that does not yet have encryption enabled
This commit add the checks for GCP encryption key before updating the encryption resources for GCP.
Also, refactors the code and unit tests as per requirement.
Thunderhead PR - https://github.infra.cloudera.com/thunderhead/thunderhead/pull/7744

CB-16012: Set encryption key for an existing env that does not yet have encryption enabled

---

core/src/main/resources/defaults/blueprints/7.2.14/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.14/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.14/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.15/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.15/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.15/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering.bp

This commit adds below configs as default for DE, DE-HA and Spark3 templates for 7.2.14, 7.2.15 and 7.2.16.
hadoop.mapreduce.fileoutputcommitter.algorithm.version.v1.experimental.parallel.rename.recovery=true
hadoop.mapreduce.fileoutputcommitter.algorithm.version.v1.experimental.parallel.task.commit=true
hadoop.mapreduce.fileoutputcommitter.algorithm.version.v1.experimental.mv.threads=16

Compx 8551 - Default configs for parallel renames and rename resiliency

---

cloud-aws-common/src/main/resources/definitions/aws-cb-policy.json

https://jira.cloudera.com/browse/CB-17040
Adding ssm Permissions required when creating Kubernetes clusters that utilize SSM Parameters instead of explicit AMI.

CB-17040 Add ssm Permissions to Default Cross-Account Policy

---

core/src/main/java/com/sequenceiq/cloudbreak/job/nodestatus/NodeStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/node/status/NodeStatusService.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/chain/AbstractCommonChainAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/action/FreeIpaDownscaleActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/provision/action/FreeIpaProvisionActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/repair/changeprimarygw/action/ChangePrimaryGatewayActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/upscale/action/FreeIpaUpscaleActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/nodestatus/NodeStatusJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/nodestatus/NodeStatusJobAdapter.java
freeipa/src/main/java/com/sequenceiq/freeipa/nodestatus/NodeStatusJobConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/nodestatus/NodeStatusJobInitializer.java
freeipa/src/main/java/com/sequenceiq/freeipa/nodestatus/NodeStatusJobService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaDeletionService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaNodeStatusService.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaChecker.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaJobService.java
freeipa/src/main/resources/application.yml
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaDeletionServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeipaCheckerTest.java
node-status-monitor-client/src/main/java/com/sequenceiq/node/health/client/CdpNodeStatusMonitorClient.java
node-status-monitor-client/src/main/java/com/sequenceiq/node/health/client/model/CdpNodeStatusRequest.java

details:
- remove node status check from health check
- create new node status check job
- increase frequency from 2 min to 30 min
- do not map parsed string (json) to grpc object (no need for that anymore as metrics-consumer won't be used, we will have a different monitoring design)
- use (open/close) only 1 socket for multiple node status related http calls instead of n sockets for n calls

CB-17090. Optimize freeipa node status check.

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupServiceTest.java

After the runtime upgrade the instances are running with the old image.
While we're not performing a repair or an OS upgrade the image can be overwritten to the new image by a stop-start or an upscale flow.
This can cause that the cluster is still running with the old instances and we're not offering the OS upgrade.

CB-17085: The image in InstanceMetadata is overwritten after the runtime upgrade

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-cb-policy.json

Follow-up to #12759 / a18ec3661b5d85f172589d2f17c6f04e1465a8bd. Adds the same SSM permissions to the legacy CF-based policy as well for consistency.

CB-17040 Add SSM permissions to CF cross-account policy

---

cloud-consumption/src/main/java/com/sequenceiq/consumption/flow/ConsumptionFlowInformation.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/CloudbreakFlowInformation.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxFlowInformation.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/EnvironmentFlowInformation.java
flow/src/main/java/com/sequenceiq/flow/core/ApplicationFlowInformation.java
flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java
flow/src/test/java/com/sequenceiq/flow/component/ComponentTestConfig.java
flow/src/test/java/com/sequenceiq/flow/core/Flow2HandlerTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/FreeIpaFlowInformation.java
redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsFlowInformation.java

Restartable flows can be restarted after it was interrupted. So for example rolling upgrade on prod. There is no reason for a flow to be not restartable, so I remove the whole restartable concept. Retryable flows are not the same thing.

CB-17116 remove restartable logic (it is not the same as retryable!)

---

core/src/main/java/com/sequenceiq/cloudbreak/service/account/PreferencesService.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/PropertiesTest.java

It doesn't enable all the cloud providers and GOV cloud providers when an empty list is set up for the `cb.enabledplatforms` and `cb.enabledgovplatforms` config keys as value.
Also the default set of supported cloud providers has been upgraded to have all providers in our `core/src/main/resources/application.yml`.
This change has been built on top of [the necessary dps-k8s config changes](https://github.infra.cloudera.com/thunderhead/dps-k8s/pull/305) not to have empty list as config value explicitly for our testing environments. The CSI repo has also been checked and verified that we are using explicit set of providers on every supported manowar environment.

CB-17150 do not enable all the cloud providers and gov cloud providers whith empty list as config value

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-cb-policy.json
cloud-aws-common/src/main/resources/definitions/aws-cb-policy.json

Backporting the following to 2.56 of CB:
> https://jira.cloudera.com/browse/CB-17040
> 
> Adding ssm Permissions required when creating Kubernetes clusters that utilize SSM Parameters instead of explicit AMI.

CB-17040 Add ssm Permissions to Default Cross-Account Policy backport

---

cloud-consumption/src/main/java/com/sequenceiq/consumption/job/storage/StorageConsumptionConfig.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJob.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobAdapter.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobService.java

Implemented skeleton for quartz jobs. Jobs are running in 30 minutes interval. The scheduler will be called from Consumption service either with ID or JobResource. For now execution function just logs success message, however ,it will get credentials from environment service in later implementation.

CB-16673 Implement quartz jobs for cloud storage calculation

---

README.md

Removing `cb.enabledplatforms` config from the Cloudbreak/Core related section of the README.md as it has changed and unnecessary as the default values enabled all the supported cloud platorms.
https://github.com/hortonworks/cloudbreak/blob/CB-2.57.0/core/src/main/resources/application.yml#L111
Thanks @lturcsanyi for catching it!

CB-17150 remove unnecessary cb.enabledplatforms config from the README.md

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/RemoveReplicationAgreementsHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaTopologyService.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/RemoveReplicationAgreementsHandlerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaTopologyServiceTest.java

Add a retry when calling from `RemoveReplicationAgreementsHandler` as it caused issues during e2e tests.

CB-17132 Add retry when updating replication topology in FreeIPA

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/AbstractE2ETest.java

We have some failing tests because of: `tag validation is not possible, because of the tag value is empty or null!`
Actually the issue here is a `CREATE_FAILED` issue during test execution and the tag validation issue is just an effect of the creation failure on the resource.
So we need to skip the tag validation in case of test failure.

CB-17214 Tag validation is failing in case of error during resource creation

---

core/src/main/resources/defaults/blueprints/7.2.16/cdp-flink-heavy.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-flink-light.bp

The role `STREAMING_SQL_CONSOLE` got removed in CSA-DH-1.7.0.0. Removing it from the blueprints as well.

[CB-17231][datahub] Remove console role from cloudbreak blueprints

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpscaleFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/CmSyncTriggerEvent.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/ParcelGeneratorUtil.java

In this commit, we're adding the CM sync flow to the upscale flow chain.
With this extra flow, we can make sure that the runtime versions are correct.

CB-14321: Call the CM syncer before upscale

---

orchestrator-salt/src/main/resources/salt/pillar/top.sls

To support provisioning clusters with older (6.x) CM/CDH version without freeipa some additional pillars are excluded from top.sls when not present

CB-17219 Modify pillar top sls to exclude pillars if not present

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpscaleFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/CmSyncTriggerEvent.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/ParcelGeneratorUtil.java

Reverts hortonworks/cloudbreak#12734
It turned out this new sync fails during repair/upgrade operations more info in [this slack conversation](https://cloudera.slack.com/archives/CQ1R8L37D/p1653465770218649)

Revert "CB-14321: Call the CM syncer before upscale"

---

core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering.bp

As it turned out with a multi comp test run our previous cloudbreak commit needs to be reverted.
The commit was added due to a CM change which should handle namenode whitelist for Oozie but as testing pointed out it does not work for cloud buckets.
Reverts https://github.com/hortonworks/cloudbreak/pull/12708

Revert "[oozie] OPSAPS-62127 Remove Oozie NameNode whitelist setting."

---

datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/stop/SdxStopActions.java
datalake/src/main/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryService.java
datalake/src/test/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryServiceTest.java

Jira: https://jira.cloudera.com/browse/CB-16897
Objective of this change was to remove the use of flow logs for resize recovery validation since flow logs are not permanent.
This consisted of the following changes:
- Remove flow log usage from resize recovery validation
- Add validation for each status using existing knowledge:
- `PROVISIONING_FAILED` just checks if a _detached_ DL exists for the environment
- Restore failure also checks for a _detached_ DL
- DL stuck in detached state just checks if currently in `STOPPED` state and if current DL is detached
- DL in `STOPPED` state due to detach failure checks if **new** detach-related status reason is present
- DL in `STOP_FAILED` state checks if **new** resize-related status reason is present
I still need to test everything and deal …

CB-16897: Removed flow log use from resize recovery validation.

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/VolumeSetAttributes.java

Override `VolumeSetAttributes.Volume.toString()` for sake of improved logging and troubleshooting. All the fields are included since neither of them is sensitive.

CB-17211 Add toString() to VolumeSetAttributes.Volume for better logging

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/exception/CloudPlatformValidationWarningException.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureImageTermsSignerService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureImageFormatValidator.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureImageTermsSignerServiceTest.java
cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/setup/ValidationResult.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/ProvisionValidationHandler.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/ProvisionValidationHandlerTest.java
common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationActions.java

At the beginning of the cluster provision, we're validating that the Terms and Conditions are accepted for the Azure Marketplace image.
To perform this validation we need the Microsoft.MarketplaceOrdering/offertypes/publishers/offers/plans/agreements/read permission.
Sometimes the customers are not providing this permission. After this change, we're sending an error message to the customer to make sure that the Terms and Conditions are accepted.

CB-17162: Show warning message when we are unable to read details of the Azure Marketplace image.

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/flow/refresh/event/DatahubRefreshStartEvent.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/DistroxService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java

JIRA: https://jira.cloudera.com/browse/CB-16678
Refresh DataHub endpoint created. The endpoint can handle specific dataHub by name. If the data hub name is not provided, the API will refresh all datahubs. 
Tested:
DataHub refresh endpoint
DataLake resize flow.
All local tests passed.

CB-16678: Create refresh DataHub endpoint 

---

orchestrator-salt/src/main/resources/salt-common/salt/monitoring/systemd/cdp-node-exporter.service.j2

CB-17328. Node exporter should not collect its own metrics.

---

integration-test/scripts/check-results.sh
integration-test/scripts/docker-compose.sh
integration-test/scripts/download-cbd.sh

This fix is mandatory for Cloudbreak integration testing. The original commit for [CB-1543 check cbd start-wait result on service sanity check](https://jira.cloudera.com/browse/CB-1543) is https://github.com/hortonworks/cloudbreak/commit/fc56308f8d2c45ef4dbdaf682db628862c6d7c4f at 2.11.0. Unfortunately this is not working since October 2019, because of another commit where an additional command was introduced to the result check:
```
date
if [ $? -ne 0 ]; then
```
then another year later an additional command as well:
```
docker ps --format '{{.Image}}'
date
if [ $? -ne 0 ]; then
```
I think `docker ps -a -f status=exited -f status=dead -q` additional validation should be placed here to validate all the the CBD containers are running as expected before start integration testing.
Beyond …

CB-17345 Fix the validation of CBD start with all the required containers as service sanity check

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelDecommissionService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelDecommissionServiceTest.java

Small change to indicate the actual parcel operation in the error message and the logline, too
for method getParcelsInStatus().

CB-17338 - getParcelsInStatus() should indicate parcel status

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsAttachmentResourceBuilder.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsAttachmentResourceBuilderTest.java

It can happen if volume AwsAttachmentResourceBuilder call fails without response from AWS, but the attachment could be successful. It is a retryable method, and the next attachment will happen with the same params, but AWS will throw an error that volume are attached to an instance, because the previous attachment was successful. We will check if volumes are properly attached even if we think the api call failed.

CB-17353 check if volumes are successfully attached, even if attachment fails

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientCredentials.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientCredentialsTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientServiceTest.java

This commit introduces the following change:
- Azure regional endpoint for resource manager calls is used any time if CloudContext.Location.Region is not null
e.g. for West US region it is https://westus.management.azure.com/ instead of https://management.azure.com/
- global endpoint remains in use for all the other cases

CB-17220 - Azure regional endpoint

---

orchestrator-salt/src/main/resources/salt-common/salt/monitoring/exporters.sls
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/init.sls
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/systemd/cdp-node-exporter.service.j2
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/textfiles.sls
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/textfiles/salt-key-check.sh

details:
- add textfiles support for node exporter
- follow the same example for any custom metrics
- the simple example is: gathere salt keys, and put the output numbers for different types to a .prom file

CB-17399. Create simple custom metrics by nodexporter textfiles.

---

redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/DatabaseServerV4Endpoint.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/UpgradeDatabaseServerV4Request.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/Notes.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/OperationDescriptions.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ParamDescriptions.java
redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/UpgradeDatabaseServerV4RequestTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsUpgradeService.java
redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/stack/RedbeamsUpgradeServiceTest.java

The REST endpoint is introduced to perform a major upgrade in redbeams.
A new permission is also introduced, the thunderhead PR: https://github.infra.cloudera.com/thunderhead/thunderhead/pull/8438

CB-17307 Postgres 11 upgrade: REST endpoints in redbeams

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerApiCheckerTask.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/update/SaltUpdateActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/StartAmbariServicesRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/StartAmbariServicesHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/StartAmbariServicesHandlerTest.java

There are some customers for which salt update involves a CM restart for which we do not wait but progress to the actual upgrade that fails due to CM being inaccessible.
This commit introduces a waiter task to wait for the CM to be started up.

CB-17352 - Salt upgrade should wait for correct CM startup

---

datalake/src/main/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryService.java
datalake/src/test/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryServiceTest.java

Jira: https://jira.cloudera.com/browse/CDPSDX-3499
Main objective of this is to expand the cases for resize recovery validation. Essentially, if a detached DL is present, then we know that either resize is still in progress or it has failed (as the final step of resize is the deletion of the detached DL).
Therefore, I figure that it is perfectly acceptable to allow recovery in the case that a detached DL is present and the resized DL is in some failure state. 
This should expand the use case of recovery and lead to less escalations in the future.

CDPSDX-3499: Added additional failure states to resize recovery when detached DL present.

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilderTest.java

DeleteOnTermination default value is false for attached disks.
BUT if somebody sets DeleteOnTermination to true by mistake, then the repair will fail because it will delete the original instance with volumes.
This change sets the DeleteOnTermination flag to false with an explicit AWS call.

CB-15512 Set DeleteOnTermination to false on repair explicitly for AWS

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/audits/AuditEventV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/events/EventV4Endpoint.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEventEndpoint.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/SdxEventControllerAuthTest.java
structuredevent-api-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/endpoint/CDPEventV1Endpoint.java
structuredevent-api-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/endpoint/CDPStructuredEventV1Endpoint.java

Jira: https://jira.cloudera.com/browse/CB-16345
Essentially the REST API used here for the Zip endpoints expects an OCTET_STREAM response type on success but a JSON for failures. We were not defining this correctly in the endpoint classes so exceptions were not being parsed the right way, resulting in an automatic 500 internal server error for any exception.

CB-16345: Fixed EventEndpoint Zip exception handling for Jersey client.

---

core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/StackCommonServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/cmsync/SdxCmSyncActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/cmsync/SdxCmSyncEvent.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/cmsync/handler/SdxCmSyncWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/status/SdxStatusService.java
datalake/src/test/java/com/sequenceiq/datalake/cm/RangerCloudIdentityServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/database/DatabaseServiceTest.java

This commit:
- does not let roll forward happen in case there is a stopped node
- in case of unexpected failure, SDX roll forward flow was not restartable because of invalid line in SdxCmSyncEvent class, it is now removed

CB-17453 - CM syncer fails when there are unavailable nodes

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java

Set view parameter to 'FULL' in hostsResourceApi.readHosts call in order to return health summary in the response.

CB-17494 Selecting nodes to downscale ignores CM status

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/EmbeddedDatabaseConfigProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/EmbeddedDatabaseConfigProviderTest.java
orchestrator-salt/src/main/resources/salt/salt/postgresql/init.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/pg11.sls

If the `DistroXV1Request->externalDatabase` has the `databaseEngineVersion` set to `11` and `availabilityType1 set to `NONE` or `ON_ROOT_VOLUME`,
then use postgresql 11 version.
- this will stop the postgresql-10 service and disable it
- set the postgres related alternatives like `pgsql` to the `11` version binary
- relink `postgresql` service to `postgresql-11`
- relink `/var/lib/pgsql/data` to `/var/lib/pgsql/11/data`
None of these happens if remote database is configured.

CB-17407 Support postgres 11 on embedded database

---

core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java

CB-17486 Cluster status is still Available after detecting node failure

---

integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml

While testing [CB-17184](https://jira.cloudera.com/browse/CB-17184) for the [CB-16055](https://jira.cloudera.com/browse/CB-16055), I've realised one of our E2E test is constantly failing because of did not executed recipes after SDX repair at [InternalSdxRepairWithRecipeTest](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxRepairWithRecipeTest.java).
This is a special kind of E2E test, because of this has been executed only with [aws-sdx-recipe-tests](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/resources/testsuites/e2e/aws-sdx-recipe-tests.yaml) suite. This suite only applied at [PR time at AWS E2E check](https://github.com/hortonworks/cloudbreak-ansible-playboo …

CB-17440 Add InternalSdxRepairWithRecipeTest to the E2E suites

---

orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls

* the idea is coming from bugfixes for YARN platform (CB-1367 CB-5721)
* this way we can elliminate the DNS healthcheck issue in CM

CB-17542 In case of Java11, extend the resolv.conf with the current domain

---

integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml

[API E2E GCP Build #1525--2.60.0-b6-GCP (23-Jun-2022 18:09:02)](http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-gcp/1525/) is failing, because of [testSDXMultiRepairIDBRokerAndMasterWithRecipeFile](http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-gcp/1525/testngreports/com.sequenceiq.it.cloudbreak.testcase.e2e.sdx/InternalSdxRepairWithRecipeTest/testSDXMultiRepairIDBRokerAndMasterWithRecipeFile/). 
**This test case is not supported on GCP, because of GCP doesn't support stopping instances with ephemeral storage.**

CB-17440 Remove InternalSdxRepairWithRecipeTest from the GCP E2E suite

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/UpscaleClusterRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/recipe/UpscalePostRecipesRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/UpscaleClusterHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/recipe/UpscalePostRecipesHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/OrchestratorRecipeExecutor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/RecipeEngine.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterUpscaleServiceTest.java

details:
- as we can attach/detach recipes now, it's a possible use case that we have a new recipe that was originally not attached to a host group, but it has been attached later
- in that case a recipe has been attached after deployment, and a scale happens on that host group, the recipe will run on every node on that host group, not only against the scaled one
- without attach/detach recipe feature that did not happened, as recipes have been there already on the nodes, and could not be removed, so on an upscale, recipes only run against the new nodes (as they have been run already on the other nodes during deployment)

CB-17193. Recipes should run only on targeted hosts (during upscale).

---

datalake/build.gradle
datalake/src/main/java/com/sequenceiq/datalake/configuration/ConsumptionApiConfig.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/ConsumptionInternalClientConfiguration.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/ServiceEndpointConfig.java
datalake/src/main/java/com/sequenceiq/datalake/flow/create/handler/EnvWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/handler/RdsDeletionHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/consumption/ConsumptionClientService.java
datalake/src/main/java/com/sequenceiq/datalake/service/consumption/ConsumptionOperationFailedException.java
datalake/src/main/java/com/sequenceiq/datalake/service/consumption/ConsumptionService.java
datalake/src/main/resources/application.yml
datalake/src/test/java/com/sequenceiq/datalake/flow/create/handler/EnvWaitHandlerTest.java
datalake/src/test/java/com/sequenceiq/datalake/flow/delete/handler/RdsDeletionHandlerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/consumption/ConsumptionClientServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/consumption/ConsumptionServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/StorageConsumptionCollectionSchedulingHandlerTest.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/StorageConsumptionCollectionUnschedulingHandlerTest.java

* Add `cloud-consumption-api` as new compile dependency for `datalake` service.
* Integrate consumption schedule / unschedule invocations into datalake create & terminate flows.
* In order to meet the tight delivery schedule, it was decided that the initial implementation will re-use existing flow steps &
handlers. The proper refactoring to extract the logic into new flow steps (along with any new DL states and related notification messages) will be done later in [CB-17514](https://jira.cloudera.com/browse/CB-17514).
* For now, the consumption schedule invocation is placed right before the DL stack create step, at the end of `EnvWaitHandler`. Similarly, the consumption unschedule invocation is executed right after the DL stack terminate step, at the beginning of `RdsDeletionHandler`.
* …

CB-17217 Integrate `consumption` into `datalake` (create & terminate)

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxRepairWithRecipeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/PreconditionSdxE2ETest.java

[API E2E AWS Build #4407--2.60.0-b6-AWS (23-Jun-2022 17:39:23)](http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-aws/4407/) where [testSDXMultiRepairIDBRokerAndMasterWithRecipeFile](http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-aws/4407/testngreports/com.sequenceiq.it.cloudbreak.testcase.e2e.sdx/InternalSdxRepairWithRecipeTest/testSDXMultiRepairIDBRokerAndMasterWithRecipeFile/) test is failing, because of:
```
"Cluster instance replacement requested on entities could not start for nodes due to the following reason: Action is only supported if the image already contains Cloudera Manager and Cloudera Data Platform artifacts."
```
So in case of this test case we should introduce prewarmed image selection test step for SDX.

CB-17558 testSDXMultiRepairIDBRokerAndMasterWithRecipeFile E2E test failed because DL was created from base image

---

datalake/src/main/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryService.java
datalake/src/test/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryServiceTest.java

Jira: https://jira.cloudera.com/browse/CB-17535
Objective is to make it so the resize recovery service can handle all of the possible failure states which are already accepted by the validation process.
Changes consist of:
- Modifying the trigger method to simply invoke the resize recovery flow, with only variation for if 2 clusters are present (detached and new) or just one (old/detached)
- Note that this follows the assumption (which is currently true) that the trigger method is always called after validation has occurred, so we can assume that the present clusters are in an expected state
- Some changes to the existing tests to fit these modifications
With this, all of the states which are validated for should be properly handled. Note that the resize recovery flow requires no changes …

CB-17535: Fixed resize recovery triggering so that all possible failure states are handled properly.

---

orchestrator-salt/src/main/resources/salt/salt/sssd/template/join_ipa.j2

The problem is that if an A record is added and the SSHFP is also added, it is possible that two ldap add commands get run which can result in a conflict. The conflict resolution it to delete both records. The SSHFP uses nsupdate, so it is not guaranteed to be routed to the same instance of FreeIPA.
Thus we have a problem. We really only need to have the DNS A-record.
If unbound doesn't have the static records, then the flag can be safely used, as the A records would be created and the SSHFP records won't.
Without the unbound change, it would be possible that the A records won't be created.

CB-15453 Use --no-dns-sshfp flag during `ipa-client-install`

---

core/src/main/resources/defaults/vm-logs.json
orchestrator-salt/src/main/resources/salt/pillar/atlas/check_atlas_updated.sls
orchestrator-salt/src/main/resources/salt/pillar/top.sls
orchestrator-salt/src/main/resources/salt/salt/atlas/check_atlas_updated.sls
orchestrator-salt/src/main/resources/salt/salt/atlas/init.sls
orchestrator-salt/src/main/resources/salt/salt/atlas/scripts/check_atlas_updated.sh
orchestrator-salt/src/main/resources/salt/salt/top.sls

Jira: https://jira.cloudera.com/browse/CB-17112
Objective of this is to enable customers to run the appropriate salt commands to verify whether Atlas is up to date before initiating the resize process. In the future this will be used within a separate automatic flow within the resize process in order to fully automate and validate this before the core resize logic occurs.
I am opening this PR but have yet to finalize testing due to various issues. I would like eyes on it however since this is my first real Salt addition/change.

CB-17112: Added use of script for automatically verifying if Atlas is fully up to date to DL resize process.

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/ModelDescriptions.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxStopValidationResponse.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/stop/SdxStopService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/stop/SdxStopServiceTest.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentStopService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/sdx/SdxService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentStopServiceTest.java

Jira: https://jira.cloudera.com/browse/CDPSDX-3366
Objective is to not allow users to stop the datalake during a resize operation as this may result in difficulty in recovering the datalake. To be perfectly clear, our recovery process for resize is fairly exhaustive and should cover most cases, this is simply to ensure that nothing goes wrong during migration.
Changes consist of:
- Adding a validation check to the stop service which verifies if the datalake has any "unstoppable flow" currently running
- This is done at the beginning of each stop and simply throws an exception, which should stop the overall stop flow (whether for the environment or just the DL)

CDPSDX-3366: Added validation during Environment and SDX stop process so as to not perform stop during resize.

---

core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-spark3.bp

We need to add the Hue service in the default Spark3 template for 7.2.16 since Hue will be supporting SparkSQL from 7.2.16 release.
The fix was manually tested by creating a custom datahub cluster template and then provisioning the cluster with it, Hue service was coming up fine in the cluster.

CDPD-41195: Add Hue service in Spark3 default template

---

core/src/main/resources/defaults/vm-logs.json
orchestrator-salt/src/main/resources/salt/pillar/postgresql/upgrade.sls
orchestrator-salt/src/main/resources/salt/pillar/top.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/init.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/common_utils.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/upgrade/backup.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/upgrade/init.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/upgrade/restore.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/upgrade/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/upgrade/scripts/restore_db.sh

This commit contains 2 scripts and related salt states
- for dumping and restoring global DB objects
- for dumping and restoring data parallel
Tested via backing up and restoring into the same RDS instance via the following salt states:
`postgresql.upgrade.backup` and `postgresql.upgrade.restore`
These are needed as Azure does not support in place RDS upgrade
This logic is going to be wired in the near future as part of https://jira.cloudera.com/browse/CB-17316

CB-17323 - Implement dump and restore logic

---

environment/src/main/java/com/sequenceiq/environment/environment/domain/Environment.java
environment/src/main/java/com/sequenceiq/environment/environment/domain/EnvironmentTags.java
environment/src/main/java/com/sequenceiq/environment/environment/domain/EnvironmentView.java
environment/src/main/java/com/sequenceiq/environment/environment/domain/ExperimentalFeatures.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java
environment/src/test/java/com/sequenceiq/environment/environment/domain/EnvironmentTagsTest.java
environment/src/test/java/com/sequenceiq/environment/environment/domain/ExperimentalFeaturesTest.java
environment/src/test/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverterTest.java

* `com.sequenceiq.environment.environment.dto.EnvironmentDtoConverter`:
* Correct copy-paste errors in `environmentViewToViewDto()` and `environmentToDto()` so that the default SG also gets used from the respective source entities.
* Add extensive UT coverage in order to check every functionality of the class.
* Extract common logic from
`com.sequenceiq.environment.environment.domain.Environment.getEnvironmentTags()` and `com.sequenceiq.environment.environment.domain.EnvironmentView.getEnvironmentTags()` into the new package-private method `com.sequenceiq.environment.environment.domain.EnvironmentTags.fromJson()`.
* Some code cleanups:
* Naming corrections
* Remove unnecessary code
* Logic simplifications
* Testing:
* Manual testing in local CB.
* Added new UT and updated existing ones.

ENGESC-15269 Environment default SG gets ignored

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudCredential.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DatabaseServer.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/CertificatesRotationV4Request.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/test/java/com/sequenceiq/cloudbreak/FlowPayloadConstructorTest.java
datalake/src/main/java/com/sequenceiq/datalake/entity/SdxCluster.java
datalake/src/main/java/com/sequenceiq/datalake/entity/operation/SdxOperation.java
datalake/src/main/java/com/sequenceiq/datalake/settings/SdxRepairSettings.java
datalake/src/test/java/com/sequenceiq/datalake/FlowPayloadConstructorTest.java
environment/src/test/java/com/sequenceiq/environment/FlowPayloadConstructorTest.java
flow/src/test/java/com/sequenceiq/flow/helper/FlowPayloadConstructorChecker.java
freeipa/src/test/java/com/sequenceiq/freeipa/FlowPayloadConstructorTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/FlowPayloadConstructorTest.java

Moved it to a common place and used it from all other modules.
It checks for flow payload (implementing `Acceptable` interface) classes' constructors:
- if only the builder constructor exists
- if it has default constructor with no proper setters and no corresponding backing fields
- recursively checks constructor parameters' type for the same above

CB-17176 Add more sophisticated constructor checker

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java

Our latest [GOV-Dev AWS API E2E Build #13-dev-2.60.0-b15 (29-Jun-2022 23:44:25)](http://ci-cloudbreak.eng.hortonworks.com/view/e2e-test/job/gov-api-e2e-aws/13/) is failing, because of:
- GOV Cloud default `"tunnel" : "DIRECT"` is the cause of the issue. At the GOV Cloud `export ENVIRONMENT_JAVA_OPTS="...-Denvironment.tunnel.default"` is missing from CB config. So we should define the `Tunnel` in the `EnvironmentTestDto` as well.
- `"The selected image: 'Image{uuid='74a637d1-5c63-49a9-92a7-183d9ef148d0', os='centos7'}' doesn't contain virtual machine image for the selected platform`. Here is the `getLatestPreWarmedImageID` and `getLatestBaseImageID`last parameter `govCloud` is the root cause. So we should replace the `false` default value to `getGovCloud()` at `AwsCloudProvider`. 
Other …

CB-17596 Modify AWS E2E test cases for GOV Cloud testing

---

cloud-consumption/src/main/java/com/sequenceiq/consumption/endpoint/ConsumptionInternalV1Controller.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/service/ConsumptionService.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/endpoint/ConsumptionInternalV1ControllerTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/service/ConsumptionServiceTest.java

* Adapt `ConsumptionInternalV1Controller.scheduleStorageConsumptionCollection()` to silently proceed when invoked for the same input that has already been registered (instead of throwing a 400 error).
* Adapt `ConsumptionInternalV1Controller.unscheduleStorageConsumptionCollection()` to silently proceed when invoked for a location that was not registered (or has already been unscheduled).
* Testing:
* Manual testing in local CB.
* Added new UT and updated existing ones.

CB-17620 Consumption does not tolerate duplicate location & 404 errors

---

redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/UpgradeDatabaseServerV4Request.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/UpgradeTargetMajorVersion.java
redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/UpgradeDatabaseServerV4RequestTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java
redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java

The commit broke the API. To unblock other PRs, just the API part was separated into this commit and is targeted to the current prod branch.

CB-17310 Postgres upgrade framework - add the upgrade flow skeleton

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/handler/UpgradeCcmOnDatahubHandler.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/handler/UpgradeCcmOnDatahubHandlerTest.java

It is the unfortunate consequence of the empty collection .stream().anyMatch() is returning true in any case...
Needed to wrap around with `if`

CB-17633 If no DistroX then Upgrade CCM environment flow fails

---

environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java

Previously if the request contained CCMV2 then it was not changed to CCMv_JUMPGATE,
opposite like in the case of CCM.
Now Jumpgate is defaulted if entitled. Override is still possible

CB-17630 Make CCMV2_JUMPGATE default if entitled

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/polling/PollingService.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/polling/StatusCheckerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerDecommissionWarningListenerTask.java
common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties

Decommission could take very long in case of older clusters, this change will send a warning to the user after 90 minutes.

CB-16160 notify user if decommission took long

---

cloud-consumption/src/main/java/com/sequenceiq/consumption/configuration/api/EndpointConfig.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/endpoint/mapper/BadRequestExceptionMapper.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/endpoint/mapper/NotFoundExceptionMapper.java

Consumption service didn't have any ExceptionMapper as a result calling an endpoint from environment was giving HTTP 500 error as a response as default. Now it gives correct response(HTTP 404) in case you want call unscheduleStorageConsumptionCollection with wrong storage location. I also added BadReqestExceptionMapper so when you want to schedule consumption collection with empty storage location it gives HTTP 400. I have tested the solution by calling the endpoint in order to trigger the error.

CB-17311 Adding ExceptionMappers to Consumption Service

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterManagerUpgradeHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmServerQueryService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmVersionQueryService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/datalake/SdxUpgradeTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/mock/endpoint/ClouderaManagerEndpoints.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/ExecuteQueryToMockInfrastructure.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxUpgradeTests.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/controller/ConfigureController.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/service/ImageCatalogMockService.java

After the CM upgrade is finished (packages on the instances should have the new version) a validation is performed that this has really happened.
If not, then an exception is thrown to stop the upgrade process which can be retried after the issue is resolved.
`NA` status is handled as stopped when checking if stopping of the cluster services is necessary, as this was blocking retrying the upgrade.

CB-17521 Validate CM version after upgrade

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/UserAddOperation.java
freeipa-client/src/test/java/com/sequenceiq/freeipa/client/operation/BatchOperationTest.java
freeipa-client/src/test/java/com/sequenceiq/freeipa/client/operation/UserAddOperationTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncOperations.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/conversion/FmsUserConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/FmsUser.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncOperationsTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/conversion/FmsUserConverterTest.java

Each actor's CRN is stored in the title field of the FreeIPA user
as part of the metadata that is updated when credentials are set. This
process left a time gap between user creation and when the CRN was
added to the user.
This commit elimiates that time gap by setting the CRN in thte title
field upon user creation in FreeIPA.

CDPCP-7442. Usersync set crn in metadata on user_add

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserStateDifferenceCalculator.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncForStackService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncGroupAddMemberOperations.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncStateApplier.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/ums/BaseUmsUsersStateProvider.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncForStackServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncGroupAddMemberOperationsTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncStateApplierTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UsersStateDifferenceCalculatorTest.java

This commit adds more guardrails to usersync for handling groups with many members.
Any group that exceeds the large group threshold will not have it's members added
in batch operations. Empirically, we've observed that the batch operations is in
danger of exceeding some timeouts, e.g., in the inverting proxy. Timeouts indicate
that the FreeIPA server is starting to be overloaded and is unable to respond to
requests in a timely manner.
There are two known large groups that are needed in the system, but had been filtered out
of the UmsUsersState listing of groups that exceed the threshold/limits.
Filtering the groups that exceed the group size threshold/limit for allowed large group
names was moved out of the ums users state retrieval. This way we can include the allowed
large groups in …

CDPCP-7323. Don't batch group_add_member for large groups

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/Crn.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/CrnResourceDescriptor.java
common/src/test/java/com/sequenceiq/cloudbreak/auth/crn/CrnTestUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/service/recipe/RecipeServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/AuthorizationTestUtil.java

This reverts commit c7619845f55500c7d5015b299b1489d0cc41e3b4.

Revert "CB-17467 Recipe crn should not have datahub word in it"

---

cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilder.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/multiaz/MultiAzCalculatorService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/InstanceMetadataServiceComponentTest.java

With this fix and component test coverage the `com.sequenceiq.it.cloudbreak.testcase.e2e.freeipa.FreeIpaTests#testCreateStopStartRepairFreeIpaWithTwoInstances` test case ran successfully on `AWS_NATIVE_GOV` cloud platform variant:

CB-17634 fix FreeIPA repair on AWS_NATIVE variant, enhanced component tests and logs around it

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/loadbalancer/StackLoadBalancerUpdateActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/CreateCloudLoadBalancersRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/CreateCloudLoadBalancersSuccess.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/CreateLoadBalancerEntityRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/CreateLoadBalancerEntitySuccess.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/LoadBalancerMetadataRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/RegisterPublicDnsRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/RegisterPublicDnsSuccess.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/CreateCloudLoadBalancersHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/CreateLoadBalancerEntityHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/LoadBalancerMetadataHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/RegisterPublicDnsHandler.java

We don't need to send the entire stack entity as a payload in eventbus.

CB-17707 Remove stack entity from LoadBalancerUpdateRequest/Result

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/init.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/pg11.sls

Salt rendering preceeded postgresql 11 installation/configuration which could result in wrong data dir during the first highstate.
This could cause DB initialization issues.
With this change in case of postgres 11 the database data directory is set.
Also the state include is moved to a more proper place to eliminate extra conditions.

CB-17711 Explicitly set postgresql 11 unit file data directory

---

integration-test/src/main/resources/testsuites/e2e/gov/aws-gov-tests.yaml

**Changes:**
- Create separate test suite yaml for AWS gov related E2E tests.
- Remove incompatible NewNetworkWithNoInternetEnvironmentTests

CB-17634 create separate test suite yaml for AWS gov related E2E tests

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterHealthService.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/model/stopstart/DetailedCertHealthCheck.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/model/stopstart/DetailedHostHealthCheck.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/model/stopstart/DetailedServicesHealthCheck.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/model/stopstart/HostCommissionState.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/status/DetailedHostStatuses.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterHealthService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerConnector.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterHealthServiceTest.java

- Created new model to extract maintenanceMode status and hostCommission status from CM
- HOST, SERVICES and CERTIFICATE health will be inferred from CM API response

CB-17476 Collect more hostHealth info from CM APIs

---

integration-test/docker-compose_template.yml
integration-test/scripts/download-cbd.sh

Real AWS and AWS Native PR builds are failing, because of 
```
ERROR main:com.cloudera.cmf.crypto.LicenseLoaderImpl: Cannot load license from input stream
com.cloudera.cmf.crypto.LicenseReadingException: Error reading license.
...
INFO main:com.cloudera.cmf.crypto.LicenseLoaderImpl: The license state of the product is ERROR_DATA
```
So for these PR checks we need to introduce real CM license file.

CB-17634 add CM license from CM_LICENSE_FILE env variable for integration test container if it is not empty

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonCloudProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/telemetry/TelemetryTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/MonitoringTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/SshJUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/client/SshJClient.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/e2e/l0promotion/common-monitoring-tests.yaml

Common Monitoring related services will run on FreeIPA, Datalake and Datahub nodes. So we need to verify if those services are started properly and running on the nodes.

CB-17615 Add sanity test for compute monitoring on FreeIpa, SDX and Distrox nodes

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/migration/handler/service/SecurityGroupRecreatorService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/migration/handler/service/SecurityGroupRecreatorServiceTest.java

**Fixes:**
- allow AWS variant migration flow only from AWS to AWS_NATIVE platform variant
- AWS migration should handle when existing security group is configured for the workload

CB-17785 allow AWS variant migration flow only from AWS to AWS_NATIVE platform variant

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java

EDH reporting happens when the flow triggers.
If the stack status change happens only in the first flow step, the EDH event will contain the status from the previous flow, which could be almost anything.

CB-17635 EDH: scaling does not always report the exact node count

---

core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/SqlStreamBuilderAdminRdsConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/SqlStreamBuilderSnapperRdsConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ssb/SqlStreamBuilderAdminDatabaseConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ssb/SqlStreamBuilderMveDatabaseConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ssb/SqlStreamBuilderRoles.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ssb/SqlStreamBuilderAdminDatabaseConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ssb/SqlStreamBuilderMveDatabaseConfigProviderTest.java

Recently the architecture of `SQL_STREAM_BUILDER` changed and we are bringing this change to Public Cloud with the 7.2.16 release.
The relevant change is the `STREAMING_SQL_CONSOLE` role got removed from the product. Although the rest of the roles are intact. I pointed the Admin DB config condition to `STREAMING_SQL_ENGINE` instead, which will be backward compatible.
Open question is: I renamed the default users and databases for both SSB DB. Could that cause problems for existing environments? My guess was it would not bother already existing workloads and only applied to new cluster provisions, which should work. On our end, definitely but I am not a CB expert.

CB-17308 Adapt SSB DB setup to the new architecture

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/GcpInstanceTemplateV4Parameters.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverterTest.java

CB-17614: GCP VM Instance should have the property `gcp`
Adding a new field `encrpted` to `GcpInstanceTemplateV4Parameters`. This new param is set to true when encryption is set else is set to false. This would ensure that `InstanceGroup.template` will be not empty for gcp and UI can use this value to maintain cloud agnostic code.

CB-17614: GCP VM Instance should have the property `gcp`

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/CrnResourceDescriptor.java
common/src/test/java/com/sequenceiq/cloudbreak/auth/crn/CrnTestUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/service/recipe/RecipeServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/AuthorizationTestUtil.java

This reverts commit 5fafc7350da155f4690bde5daef7923f59fc02d6.

Revert "Revert "CB-17467 Recipe crn should not have datahub word in it""

---

common-model/src/main/java/com/sequenceiq/common/api/command/RemoteCommandsExecutionRequest.java
common-model/src/main/java/com/sequenceiq/common/api/command/RemoteCommandsExecutionResponse.java
common-model/src/main/java/com/sequenceiq/common/api/command/doc/RemoteCommandsExecutionDescription.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/UtilV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/RemoteExecutionService.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/RemoteExecutionServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/RestUrlParserTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/util/UtilV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/util/doc/UtilDescriptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/UtilV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/RemoteExecutionService.java
freeipa/src/main/resources/application.yml
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/RemoteExecutionServiceTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java

details:
- add remote_exec api to both core and freeipa
- disable feature by flag, that setting should be the default
- this featue should be only used for testing purposes in order to run specific commands on all or filtered hosts (filter by host or host group)

CB-17788. Add new remote_execution api for utils API.

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/rotatepassword/RotateSaltPasswordFlowConfig.java
flow/src/main/java/com/sequenceiq/flow/core/config/Flow2Config.java
flow/src/main/java/com/sequenceiq/flow/core/config/IgnoreFromRetryableFlowConfiguration.java
flow/src/main/java/com/sequenceiq/flow/service/FlowRetryService.java
flow/src/test/java/com/sequenceiq/flow/service/FlowRetryServiceTest.java

Some flows use events that should not interfere with restartable flows, like salt password rotation.
To achieve this, a new IgnoreFromRetryableFlowConfiguration interface was added to collect the events that should be ignored while checking for retryable flows.

CB-17889 Mark events as ignored from restartable flows

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/StorageConsumptionCollectionSchedulingHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/StorageConsumptionCollectionUnschedulingHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/service/consumption/ConsumptionClientService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/consumption/ConsumptionService.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/StorageConsumptionCollectionSchedulingHandlerTest.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/StorageConsumptionCollectionUnschedulingHandlerTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/consumption/ConsumptionClientServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/consumption/ConsumptionServiceTest.java

* Follow-up to [CB-17216](https://jira.cloudera.com/browse/CB-17216) / #12807.
* Rename the current `com.sequenceiq.environment.environment.service.consumption.ConsumptionService` to `ConsumptionClientService` (keeping the package unchanged), so that the latter new service only encapsulates the web service calls, nothing else.
* Extract all the consumption-related logic from `com.sequenceiq.environment.environment.flow.creation.handler.StorageConsumptionCollectionSchedulingHandler` and `com.sequenceiq.environment.environment.flow.deletion.handler.StorageConsumptionCollectionUnschedulingHandler` into `com.sequenceiq.environment.environment.service.consumption.ConsumptionService`. (This is the same service mentioned in the first bullet item.)
* Testing:
* Manual testing in local CB.
* Added …

CB-17581 Extract environment consumption logic from handlers into a separate service

---

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/recovery/DatalakeUpgradeRecoveryActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/loadbalancer/dns/UpdateLoadBalancerDNSActions.java
datalake/src/test/java/com/sequenceiq/datalake/flow/SdxReactorFlowManagerTest.java
datalake/src/test/java/com/sequenceiq/datalake/flow/datalake/recovery/DatalakeUpgradeRecoveryActionsTest.java
datalake/src/test/java/com/sequenceiq/datalake/flow/loadbalancer/dns/UpdateLoadBalancerDNSActionsTest.java

JIRA: https://jira.cloudera.com/browse/CB-16954
Add `eventLog` .eation to the recovery process started, and the recovery process finished state.
This is an improvement to make the track easier for the customer.
Tested:
-

CB-16954 Add eventLog creation to the recovery process started, and the recovery process finished state.

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/init.sls

The previous commit: https://github.com/hortonworks/cloudbreak/commit/3b68a8897479ba4c4bb2ab7f2a4d25056b8cd4b0
Fixed an issue where the symlink was deleted instead of the actual data. But running postgres 10 can cause issues when deleting data,
so postgres is stopped before deleted.
Tested with:
- AWS DH pg10 attached disk
- AWS DH pg10 root disk
- AWS DH pg11 attached disk
- AWS DH pg11 root disk
- ycloud sdx pg10
- ycloud sdx pg11

CB-17866 Stop postgres before initdb script

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/ccm/upgrade/UpgradeCcmService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ccm/DeregisterAgentHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ccm/HealthCheckHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ccm/PushSaltStateHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ccm/ReconfigureNginxHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ccm/RegisterClusterProxyHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ccm/RemoveAgentHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/ccm/upgrade/UpgradeCcmFlowIntegrationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ccm/DeregisterAgentHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ccm/HealthCheckHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ccm/PushSaltStateHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ccm/ReconfigureNginxHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ccm/RegisterClusterProxyHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ccm/RemoveAgentHandlerTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmService.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/handler/UpgradeCcmDeregisterMinaHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/handler/UpgradeCcmHealthCheckHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/handler/UpgradeCcmObtainAgentDataHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/handler/UpgradeCcmPushSaltStatesHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/handler/UpgradeCcmReconfigureNginxHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/handler/UpgradeCcmRegisterClusterProxyHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/handler/UpgradeCcmRemoveMinaHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/handler/UpgradeCcmUpgradeHandler.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/chain/UpgradeCcmFlowChainIntegrationTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmFlowIntegrationTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/handler/UpgradeCcmGenericHandlerTest.java

If the upgrade flow goes into a failed state, the tunnel type is
reverted to the original.
However, in the case of retries at several handlers,
the tunnel type should have been kept on CCMV2_JUMPGATE
(e.g. registering cluster proxy or obtaining inverting proxy data).
This must be corrected: the tunnel must be updated to the
CCMV2_JUMPGATE value at the beginning of each handler.
The second issue is with cluster proxy re-registration's health check.
In case of a failed health status, the cluster proxy registration
must be repeated with the original tunnel type to ensure further
cluster communication.
Also, the cluster proxy registration and health check is merged
because it is idempotent only this way.

CB-17930 Retrying failed CCM upgrade is impossible

---

structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterUseCaseMapper.java
usage-collection/src/main/proto/usage.proto

This commit:
* adds UPGRADE_PREPARE_STARTED/_FINISHED/_FAILED events to EDH,
* syncs the usage.proto file with the one in thunderhead,
* changes DATALAKE_RESIZE_START cluster status to DATALAKE_RESIZE_STARTED to follow naming conventions.

CB-17957 Add prepare upgrade operation tracking in EDH

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/init.sls

Changes in postgresql unit file was ignored when starting/restarting postgresql.
Adding daemon-reload after unit file change.
Start/restart is modified, init-db requirement removed, only daemon reload is required when on attached disk.

CB-17866 Reload systemd config files after changing unit files

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDtoBase.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXBigScaleTest.java
integration-test/src/main/resources/testsuites/e2e/distrox-bigscale-tests.yaml

This is related to [CB-17828 Support 800 node cluster size for datahubs](https://jira.cloudera.com/browse/CB-17828) epic.
We need to create a special  E2E DistroX scale test where we can add high node count for up and down scale along with the related test suite.

CB-17851 Create possibility to run high node count E2E tests

---

integration-test/scripts/check-results.sh
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/mock/endpoint/ClouderaManagerEndpoints.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterFaultTolerantUpscaleTest.java

The two test cases are:
1. Some of the nodes are not reachable, because they don't return their private IPs through Salt.
2. CM waiting for hosts, times out
In both cases the nodes go into ZOMBIE state.
The test cases don't check whether the ZOMBIE nodes get automatically cleaned up, after the upscale.

CB-17619 : Added integration tests for when not all of the new nodes are healthy after upscale

---

datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxUpgradeTests.java

JIRA: https://jira.cloudera.com/browse/CB-17712
We should have to check whether there is a backup before the configured days or not. 
We should not execute the backup process if we do not have a backup. 
Tested:
Locally, with manual backup and entitlement, the logic works with both states.

CB-17712: Check backup before resize

---

common/src/main/java/com/sequenceiq/cloudbreak/common/service/Clock.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/saltstatuschecker/SaltStatusCheckerConfig.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/saltstatuschecker/SaltStatusCheckerJobService.java
common/src/main/resources/common-config.yml
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/RotateSaltPasswordActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/event/RotateSaltPasswordReason.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/event/RotateSaltPasswordRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/orchestrator/RotateSaltPasswordService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/saltstatus/StackSaltStatusCheckerJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/saltstatus/StackSaltStatusCheckerJobAdapter.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/saltstatus/StackSaltStatusCheckerJobService.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/saltstatus/StackSaltStatusJobInitializer.java
freeipa/src/main/resources/application.yml
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/handler/RotateSaltPasswordHandlerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/orchestrator/RotateSaltPasswordServiceTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStateService.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java

A salt command querying the saltuser password expiry date is sent to all gateway instances of a stack:
- If the password expires sooner than a set threshold, a salt password rotation is started.
- If it responds with an unauthorized response, a salt password rotation is started.
- Other types of errors are only logged.

CB-17180 Detect and fix Freeipa saltuser password errors

---

common/src/main/java/com/sequenceiq/cloudbreak/common/database/MajorVersion.java
common/src/test/java/com/sequenceiq/cloudbreak/common/database/MajorVersionTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DatabaseServerConverter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DatabaseServerConverterTest.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/responses/DatabaseServerV4Response.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java
redbeams/src/main/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerConfigToDatabaseServerV4ResponseConverter.java
redbeams/src/main/java/com/sequenceiq/redbeams/domain/stack/DBStack.java
redbeams/src/test/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerConfigToDatabaseServerV4ResponseConverterTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/domain/stack/DBStackTest.java

This commit:
- parses Postgres server engine version from entity `databaseServer`
- returns the engine info in `DatabaseServerV4Response`

CB-17762 - Return RDS engine version via Redbeams API

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxResizeTests.java

Jira: https://jira.cloudera.com/browse/CB-18100
This should temporarily fix the existing e2e failures due to the e2e environment not running and enabling the DR service.
In the future I will revert this in order to have this validation occur.

CB-18100: Reverts the recent SDX resize E2E test changes which are causing failures.

---

core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java

Sometimes default blueprint loading fails because the key is already in the db. It's happening because concurrent loading but the process is too long for a transaction.

CB-17833 datalake provision failed

---

common/src/main/java/com/sequenceiq/cloudbreak/service/database/DatabaseDefaultVersionProvider.java
common/src/main/resources/common-config.yml
common/src/test/java/com/sequenceiq/cloudbreak/service/database/DatabaseDefaultVersionProviderTest.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxExternalDatabaseConfigurer.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxExternalDatabaseConfigurerTest.java

When the database engine version is not defined in the request, it would be overridden with the defined value if the runtime version is equal or higher than the deifned.
For now it is set to a not existing high veresion number so it doesn't effect anything.
Logic:
- engine version empty and runtime is older: engine version is null, current default behavior
- engine version empty and runtime is equal or new: engine version is overridden with defined version (currently 11)
- engine version is specified in the request: independently from runtime version it will be honored and won't be overridden

CB-18058 Ability to define Postgres version from runtime version X

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateComponentConfigProviderProcessor.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreRoles.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/StubDfsConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/StubDfsConfigProviderTest.java
template-manager-cmtemplate/src/test/resources/input/kafka-without-hdfs-cm-771.bp
template-manager-cmtemplate/src/test/resources/output/kafka-without-hdfs-cm-771.bp
template-manager-cmtemplate/src/test/resources/output/kafka-without-hdfs.bp

**Changes:**
-  elminiate unused roletypes list from the CM template processor addServiceConfigs
- StubDFS service needs to be added with storageoperations role from CM 7.7.1 and CoreSettings could not contain storageoperations role

Handle CoreSettings and StubDFS for CM 7.7.1+

---

core-model/src/main/java/com/sequenceiq/cloudbreak/dto/StackDto.java
core/src/main/java/com/sequenceiq/cloudbreak/job/salt/StackSaltStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/salt/StackSaltStatusCheckerJobAdapter.java
core/src/main/java/com/sequenceiq/cloudbreak/job/salt/StackSaltStatusCheckerJobInitializer.java
core/src/main/java/com/sequenceiq/cloudbreak/job/salt/StackSaltStatusCheckerJobService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/RotateSaltPasswordReason.java
core/src/main/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/StackCommonServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java

Works the same as in casse of FreeIPA: a salt command querying the saltuser password expiry date is sent to all gateway instances of a stack:
- If the password expires sooner than a set threshold, a salt password rotation is started.
- If it responds with an unauthorized response, a salt password rotation is started.
- Other types of errors are only logged.

CB-17180 Detect and fix Datahub saltuser password errors

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationStackUtil.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationStackUtilTest.java

group is actually a member of that group before assignment
note the previous dead parameter in getInstanceIdsForGroups

[CB-17903] check that that the instance being added to an AWS target

---

datalake/src/main/resources/duties/7.2.10/aws/light_duty.json
datalake/src/main/resources/duties/7.2.10/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.11/aws/light_duty.json
datalake/src/main/resources/duties/7.2.11/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.12/aws/light_duty.json
datalake/src/main/resources/duties/7.2.12/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.14/aws/cdp_data_lake_medium_duty_with_profiler/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.14/aws/light_duty.json
datalake/src/main/resources/duties/7.2.14/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.15/aws/cdp_data_lake_medium_duty_with_profiler/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.15/aws/light_duty.json
datalake/src/main/resources/duties/7.2.15/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.16/aws/cdp_data_lake_medium_duty_with_profiler/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.16/aws/light_duty.json
datalake/src/main/resources/duties/7.2.16/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.7/aws/light_duty.json
datalake/src/main/resources/duties/7.2.7/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.8/aws/light_duty.json
datalake/src/main/resources/duties/7.2.8/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.9/aws/light_duty.json
datalake/src/main/resources/duties/7.2.9/aws/medium_duty_ha.json

JIRA: CB-17751; Update datalake duties config for attached storage; 
- `AUXILIARY` - Reduced to 128GB
- `GATEWAY` - Reduced to 128GB
- `MASTER` - Reduced to 128GB
- `Core`: Increase it to 512GB
- `Light duty`: Increase it to 512GB
- change the `AWS` type to `GP2`;
Tested:
with CBD
* create a new medium-duty instance, Provider `AWS`; Run time version `7.2.16`
* result: the attached volume size is `512 GB` and the type is GP2
* resize micro duty to medium duty, Provider `AWS`; Run time version `7.2.16`
* result: the attached volume size is `512 GB` and the type is `GP2`

CB-17751; Change the volume size and type

---

integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeipaRotateSaltPasswordAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxRotateSaltPasswordAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXRotateSaltPasswordAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/DistroXTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/FreeIpaTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/saltpassword/RotateSaltPasswordE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshSaltPasswordActions.java
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/salt-password-rotation-tests.yaml

Verify the changed password and password expiry dates on FreeIPA, Datalake and Datahub clusters with the following steps:
- Set the password change date to a past date (on new clsuters that would be the current day by default)
- Get the saltuser line from the shadow file and save it as a reference
- Call the rotate salt password endpoint
- Verify that the saltuser's line in the shadow file was changed
- Verify that the saltuser's password change date is set to today

CB-17348 Create e2e test for saltuser password rotation

---

common/src/main/java/com/sequenceiq/cloudbreak/service/database/DatabaseDefaultVersionProvider.java
common/src/test/java/com/sequenceiq/cloudbreak/service/database/DatabaseDefaultVersionProviderTest.java

In some edge cases runtime version is not available to define the default db engine version.
In these cases we leave it as null and go with the default version.

CB-18191 Handle `null` runtime in `DatabaseDefaultVersionProvider`

---

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/rotatepassword/RotateSaltPasswordAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/rotatepassword/RotateSaltPasswordActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/rotatepassword/RotateSaltPasswordContext.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/update/SaltUpdateService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/RotateSaltPasswordRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/RotateSaltPasswordType.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/RotateSaltPasswordHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/RotateSaltPasswordHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java

Steps to rotate saltuser password on stacks with older salt-bootstrap version:
- Remove saltuser from gateways (proceed even if it fails, as the error message will give a hint to do this manually)
- Run the boostrap service on gateway nodes, this will recreate the saltuser with the new password

CB-17181 Fallback saltuser password rotation

---

datalake/src/main/resources/duties/7.2.10/azure/light_duty.json
datalake/src/main/resources/duties/7.2.10/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.11/azure/light_duty.json
datalake/src/main/resources/duties/7.2.11/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.12/azure/light_duty.json
datalake/src/main/resources/duties/7.2.12/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.14/azure/cdp_data_lake_medium_duty_with_profiler/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.14/azure/light_duty.json
datalake/src/main/resources/duties/7.2.14/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.15/azure/cdp_data_lake_medium_duty_with_profiler/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.15/azure/light_duty.json
datalake/src/main/resources/duties/7.2.15/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.16/azure/cdp_data_lake_medium_duty_with_profiler/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.16/azure/light_duty.json
datalake/src/main/resources/duties/7.2.16/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.7/azure/light_duty.json
datalake/src/main/resources/duties/7.2.7/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.8/azure/light_duty.json
datalake/src/main/resources/duties/7.2.8/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.9/azure/light_duty.json
datalake/src/main/resources/duties/7.2.9/azure/medium_duty_ha.json

JIRA: CB-17807: Change volume size of the datalake duties on Azure.
- new size: 
- AUXILIARY - Reduced to 128GB
- GATEWAY - Reduced to 128GB
- MASTER - Reduced to 128GB
- Core: Increase it to 512GB
- Light duty: Increase it to 512GB
Tested:
Locally with CBD & IDE:
- create a new datalake version `7.2.15`, and `medium duty`, the newly created nodes were the expected size. 
- create a new datalake version `7.2.15` with `light duty`, the newly created nodes were the expected size.

CB-17807: change volume size of the datalake duties on Azure

---

datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/cmsync/SdxCmSyncActions.java
datalake/src/main/java/com/sequenceiq/datalake/repository/SdxStatusRepository.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/status/SdxStatusService.java

The input parameter is the SDX id, not the SDX status id

CB-18241 Fix SdxStatusService.getActualStatusForSdx

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractSdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxCustomTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxSaasTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java

In case of [DistroXEncryptedVolumeTest](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java) and [DistroXRepairTests](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXRepairTests.java) teardown we've observed exception on the test console:
```
java.lang.IllegalStateException: Error happened, getCrn() is not implemented for TestDto: SdxCloudStorageTestDto[name: null]  at com.sequenceiq.it.cloudbreak.dto.CloudbreakTestDto.getCrn(CloudbreakTestDto.java:59)  at com.sequenceiq.it.cloudbreak.dto.AbstractTestDto.getClientForCleanup(AbstractTestDto.java:409)  at …
```

CB-18217 SDX E2E resource cleanup refactor

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/pg11-install.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/pg11.sls

To avoid double include which breaks salt rendering, postgres 11 install states has been moved to a separate state file, so it can be included with alternatives

CB-18255 Move postgres 11 install to separate state file

---

cloud-consumption/src/main/java/com/sequenceiq/consumption/configuration/repository/ConsumptionRepository.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/converter/metering/ConsumptionToStorageHeartbeatConverter.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/endpoint/ConsumptionInternalV1Controller.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/flow/consumption/storage/handler/StorageConsumptionCollectionHandler.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobInitializer.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobService.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/service/ConsumptionService.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/util/CloudStorageLocationUtil.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/converter/metering/ConsumptionToStorageHeartbeatConverterTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/endpoint/ConsumptionInternalV1ControllerTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/flow/consumption/storage/handler/StorageConsumptionCollectionHandlerTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobInitializerTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobServiceTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/service/ConsumptionServiceTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/util/CloudStorageLocationUtilTest.java

This commit implements S3 storage conusmption job aggregation. This means that for every environment CRN and bucket name pair only
one quartz job will run even if multiple storage consumptions are registered for the given pair.
Implementation details:
* To avoid changing the DB schema, as there might already be registered storage paths (referring to it as "consumption") in it, an
implementation is proposed that do not change how consumptions are registered and unregistered in the DB. All separate consumption
registrations will still be treated as a separate consumption from the DB standpoint.
* The "aggregation" logic is implemented not on the DB side but in the quartz job scheduling, unscheduling and initialization.
* When a new consumption is saved to the DB and quartz job scheduling …

CB-18043 Aggregate storage consumption collection jobs

---

autoscale/src/main/java/com/sequenceiq/periscope/config/DatabaseConfig.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/configuration/DatabaseConfig.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpHttpClientConfig.java
common/src/main/java/com/sequenceiq/cloudbreak/client/CertificateTrustManager.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/DatabaseConfig.java
docker-autoscale/Dockerfile
docker-autoscale/bootstrap/start_autoscale_app.sh
docker-cloudbreak/Dockerfile
docker-cloudbreak/bootstrap/start_cloudbreak_app.sh
docker-consumption/Dockerfile
docker-consumption/bootstrap/start_consumption_app.sh
docker-datalake/Dockerfile
docker-datalake/bootstrap/start_datalake_app.sh
docker-environment/Dockerfile
docker-environment/bootstrap/start_environment_app.sh
docker-freeipa/Dockerfile
docker-freeipa/bootstrap/start_freeipa_app.sh
docker-redbeams/Dockerfile
docker-redbeams/bootstrap/start_redbeams_app.sh
environment/src/main/java/com/sequenceiq/environment/configuration/DatabaseConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/configuration/DatabaseConfig.java
integration-test/docker-compose_template.yml
integration-test/test-image/Dockerfile
mock-infrastructure/Dockerfile
mock-thunderhead/Dockerfile
redbeams/src/main/java/com/sequenceiq/redbeams/configuration/DatabaseConfig.java

**Changes:**
-  Revert "CB-16401 Temporarily revert UBI base image changes in CB Java services"
- CB-16402 set ubi8/cldr-openjdk-11-runtime as default base image for Environment, FreeIPA, Redbeams, Datalake, Autoscale and Cloudbreak services.
- CB-16402 Introduce minor fixes to be able to start the mentioned services on FIPS enabled environments like use FIPS compatible `org.postgresql.ssl.DefaultJavaSSLFactory` as Postgres database client SSL factory, GCP client to use JRT default `KeyStore` instead of explicit `PKCS12`, use default `SSLContext` instead of a custom one that accepts everything...

CB-16402 set UBI8 base image for Java based docker images

---

core/src/main/resources/defaults/blueprints/7.2.16/cdp-streaming-ha.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-streaming-small.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-streaming.bp

The StorageOperations role will now be in StubDfs service, so existing templates that contain CoreSettings need to be updated. This commit updates the streams messaging templates.
Test:
- Manually on provisioned cluster (local)

CB-17557: Update blueprints for cdp 7.2.16 Streams Messaging clusters

---

cloud-consumption/src/main/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJob.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobTest.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/TracedQuartzJob.java
common/src/test/java/com/sequenceiq/cloudbreak/quartz/TracedQuartzJobTest.java
common/src/test/java/com/sequenceiq/cloudbreak/quartz/TracedQuartzJobTestClass.java
core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/altus/CloudbreakUMSCleanupJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/instancemetadata/ArchiveInstanceMetaDataJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/nodestatus/NodeStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJob.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/job/StructuredSynchronizerJob.java
datalake/src/main/java/com/sequenceiq/datalake/job/SdxClusterStatusCheckerJob.java
environment/src/main/java/com/sequenceiq/environment/environment/sync/EnvironmentStatusCheckerJob.java
flow/src/main/java/com/sequenceiq/flow/cleanup/FlowCleanupJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/altus/FreeIpaUMSCleanupJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/nodestatus/NodeStatusJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/saltstatus/StackSaltStatusCheckerJob.java
redbeams/src/main/java/com/sequenceiq/redbeams/sync/DBStackStatusSyncJob.java

In the flow quartz job, the null value is the accepted value. Now, it causes an error because the MdcContextBuilder has two object builders, and both are null we throw a validation error. If the return value is Optional.empty() it means the method implemented but no value

CB-18249 Change from object to Optional to handle the null value correctly in MdcContextBuilder

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/MonitoringTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java

This is the follow-up improvement for the [CB-17615 [API E2E] Add sanity test for compute monitoring on FreeIpa, SDX and Distrox nodes](https://jira.cloudera.com/browse/CB-17615) story.
For now we have finalized and upgraded images with the latest monitoring. So we can create some E2E tests to daily runs.
Currently the 
```
cdp-doctor monitoring status -m node_filesystem_free_bytes,cm_health_check_info --format json
```
command exit status '0' and result
```
{
"endpoint": {
"code": 401,
"proxy": "No",
"status": "OK",
"url": "https://receive-cdp-saas.api.monitoring.cdp.mow-dev.cloudera.com"
},
"metrics": {
"cm_health_check_info": "NOK",
"node_filesystem_free_bytes": "OK"
},
"request-signer": {
"error_count": 0,
"status": "OK",
"success_count": 34
},
"scrapping": {
"node-exporter": "OK", …
```

CB-18210 Improve and introduce E2E tests for compute monitoring on FreeIpa, SDX and Distrox nodes

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshCommandRunnerActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/client/SshJClient.java
integration-test/src/main/resources/commandrunner/qa-command-runner.py
integration-test/src/main/resources/commandrunner/sample-command.json

Currently we have integrated [SSHJClient](https://github.com/hierynomus/sshj) to connect VMs and execute commands there.
Instead of connect to VMs multiple times during test executions, we can use a simple combined command runner for checking results in one round.
Basically we should be able:
- execute commands on VMs remotely, like we do in case of diagnostics
- on SDX, Distrox, FreeIpa and their instances and hostrgroups
- then get the results (for example in JSON format):
- need to parse the JSON result

CB-18046 Introduce a command runner for Cloudbreak API Test project to multiple SSH

---

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/BlackboxExporterConfiguration.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfigService.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfigView.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfiguration.java
common/src/main/resources/common-config.yml
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfigServiceTest.java
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/template/prometheus.yml.j2

Create separate blackbox exporter configurations for internal and external url checks.
Add flag for checking urls only on master or on all nodes.
Add config parameters for defining scrape intervals for external/internal checks.
Fall back to old check if the package version is not high enough.

CB-17069 Separate internal and external blackbox exporter probes

---

common/src/main/resources/messages/messages.properties
core-model/src/main/java/com/sequenceiq/cloudbreak/view/StackView.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/rotatepassword/RotateSaltPasswordAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/rotatepassword/RotateSaltPasswordActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/rotatepassword/RotateSaltPasswordContext.java
core/src/main/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/salt/rotatepassword/RotateSaltPasswordTrackerActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/RotateSaltPasswordAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/RotateSaltPasswordActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/RotateSaltPasswordContext.java
freeipa/src/main/java/com/sequenceiq/freeipa/orchestrator/RotateSaltPasswordService.java
freeipa/src/test/java/com/sequenceiq/freeipa/orchestrator/RotateSaltPasswordServiceTest.java

Only check if the stack is not stopped instead of is it available
Save the starting status and re-aplly it after successful salt password rotation

CB-17890 Salt password rotation for non-available stacks

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/RotateSaltPasswordAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/RotateSaltPasswordActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/RotateSaltPasswordContext.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/RotateSaltPasswordType.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/event/RotateSaltPasswordRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/handler/RotateSaltPasswordHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/orchestrator/RotateSaltPasswordService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/BootstrapService.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/handler/RotateSaltPasswordHandlerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/orchestrator/RotateSaltPasswordServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/BootstrapServiceTest.java

Steps to rotate saltuser password on stacks with older salt-bootstrap version:
- Remove saltuser from gateways (proceed even if it fails, as the error message will give a hint to do this manually)
- Run the boostrap service on gateway nodes, this will recreate the saltuser with the new password

CB-17181 Fallback saltuser password rotation for FreeIPA

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/services.sls

Extend the 'after' regexp with start string character to avoid failures in case of [Service] exists in a comment as well (it was the case with RHEL8 and httpd.service).

CB-18328 Update service restart salt state after matcher to avoid failures

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxResizeRecoveryTests.java

Jira: https://jira.cloudera.com/browse/CB-18324
I was supposed to remove the DR checks before but it seems this one slipped through and is naturally causing e2e failures. I apologize for this.

CB-18324: Fix resize recovery e2e test by removing wait for backup state.

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActions.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActionsTest.java

There is a parameter  introduced in the application.yml to determine for
which cloud platform  backup and restore flow steps should be run or can be skipped.

CB-18030 - Run backup-restore flow steps only for Azure

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java

Because of the assumption that Impala always have a
dedicated coordinator, the Impala URLs were replaced with
the coordinator URLs.
In reality there are custom templates where no dedicated
Impala coordinator exists, thus the empty list should not be
placed as the Impala URL list.

CB-18345 Fix Impala URLs in Knox topology

---

core/src/main/resources/application.yml

details:
- for EU/AP - this stackpatcher constantly fails (every day)
- reason for the failing is  that their endpoints are not registered in cluster proxy
- stackpatcher can be disabled as it seems only happens with cloudera related accounts.

CB-18351. Disable 'disable-region-for-fluentd' existing stackpatcher.

---

common/src/main/resources/common-config.yml

details:
- use dashes instead of camel cases for properties
- in case on @ConfigurationProperties spring can tell you camelCases are not valid for using with objects
- both camel case + dashes can work on fields but won't work on classes - do not mix the 2 format, so just go with dashes (as it's true for most of telemetry + all monitoring related configs)

CB-18356. Do not use camel case for blackbox exporter configs.

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/operation/AwsRdsVersionOperations.java
cloud-aws-cloudformation/src/main/resources/definitions/aws-environment-minimal-policy.json
cloud-aws-common/src/main/resources/definitions/aws-environment-minimal-policy.json

This commit contains the following changes:
- Extend the AWS minimal policy definitions with the rds:DescribeDBEngineVersions permission because this is required for the RDS upgrade.
- Make the error message more user-friendly when this new policy is missing from the customer's policies.

CB-18301: Extend AWS minimal policy with a required policy for RDS upgrade

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/preparation/handler/ClusterUpgradeParcelSettingsPreparationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelAvailabilityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmServerQueryService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/ParcelUrlProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/preparation/handler/ClusterUpgradeParcelSettingsPreparationHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelAvailabilityServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmServerQueryServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/ParcelUrlProviderTest.java

The ParcelUrlProvider is returning all the required parcel URLs for a cluster. After implementing the upgrade-preparation flow, this logic is used multiple times. Therefore it can happen that the required parcels are already downloaded or distributed. In this case, we don't need to return those parcel URLs.

CB-18358: Improve ParcelUrlProvider logic to return only the requiredurls

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActions.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActionsTest.java

Fix to include the platform selection logic in the requests sent to the handlers and not only in `doExecute`.

CB-18030 - Run backup-restore flow steps only for Azure - fix

---

docker-autoscale/bootstrap/start_autoscale_app.sh
docker-cloudbreak/bootstrap/start_cloudbreak_app.sh
docker-consumption/bootstrap/start_consumption_app.sh
docker-datalake/bootstrap/start_datalake_app.sh
docker-environment/bootstrap/start_environment_app.sh
docker-freeipa/bootstrap/start_freeipa_app.sh
docker-redbeams/bootstrap/start_redbeams_app.sh

CB-16402 do import certs to the default keystore from a service specific directory also.
On Manowar K8S environments the database certs are mounted to a service specific directory like /SERVICENAME/certs/database.crt. The starter scripts of the docker containers need to use these directories to add database certs to the Java keystore.

CB-16402 do import certs to the default keystore from a service specific directory also

---

cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/CloudPlatformRequest.java

This promise is not used in later flow steps, only upon accepting
it for the first instance.

CB-18329 Edge case for insignificant Promise

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshCommandRunnerActions.java
integration-test/src/main/resources/commandrunner/qa-command-runner.py

Cb 18253 details:
- if qa-command-runner script fails it throws an exception by ssh java client
- instead of throwing an exception, add an extra layer to the script
- catch all the exception and return with a json + exit code + error message so won't cause java exceptions if the command fails
- use err for the error message as the same is used per node.
CB-18257 details:
- use hosts and host-groups options
- output will contain the hosts and host-group filter options
- if a node is unreachable that will be added to unreachable_nodes output
- if a node is filered out by hosts or host-groups filter, the host name will appear in the skipped field of the output.

Cb 18253 & CB-18257: [API E2E] QA Command Runner script - improvements (hosts/hostgroups) and add one more layer

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StartServicesHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StopServicesHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StartServicesHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StopServicesHandlerTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/restart.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/server-start.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/server-stop.sls
orchestrator-salt/src/main/resources/salt/salt/top.sls
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java

[CB-17763 Implement stop and start flow steps](https://github.com/hortonworks/cloudbreak/pull/13305/commits/9c822b6b399a88480e16bced343349268352228e) 
Stop steps:
- Stop the services using CM
- Stop the CM server on PrimaryGateway
- Stopall the CM agents on all hosts
Start steps:
- Start the CM server on PrimaryGateway
- Start all the CM agents on all hosts
- Start the services using CM

CB-17763 Implement stop and start flow steps

---

datalake/src/main/resources/duties/7.2.10/gcp/light_duty.json
datalake/src/main/resources/duties/7.2.10/gcp/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.11/gcp/light_duty.json
datalake/src/main/resources/duties/7.2.11/gcp/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.12/gcp/light_duty.json
datalake/src/main/resources/duties/7.2.12/gcp/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.14/gcp/cdp_data_lake_medium_duty_with_profiler/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.14/gcp/light_duty.json
datalake/src/main/resources/duties/7.2.14/gcp/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.15/gcp/cdp_data_lake_medium_duty_with_profiler/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.15/gcp/light_duty.json
datalake/src/main/resources/duties/7.2.15/gcp/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.16/gcp/cdp_data_lake_medium_duty_with_profiler/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.16/gcp/light_duty.json
datalake/src/main/resources/duties/7.2.16/gcp/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.7/gcp/light_duty.json
datalake/src/main/resources/duties/7.2.7/gcp/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.8/gcp/light_duty.json
datalake/src/main/resources/duties/7.2.8/gcp/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.9/gcp/light_duty.json
datalake/src/main/resources/duties/7.2.9/gcp/medium_duty_ha.json

JIRA: [CB-17805](https://jira.cloudera.com/browse/CB-17805)
Change datalake duty volume type and size at `GCP`.
Versions from: `7.2.7` to `7.2.16`
New medium duty size:
- AUXILIARY - Reduced to `128GB`
- GATEWAY - Reduced to `128GB`
- MASTER - Reduced to `128GB`
- CORE: Increase it to `512GB`
New light duty size:
- Light duty: Increase it to `512GB`
new core type: `ps-ssd`

CB-17805 change volume size and type GCP

---

cloud-consumption/src/test/java/com/sequenceiq/consumption/FlowStateEnumTest.java
core/src/test/java/com/sequenceiq/cloudbreak/FlowStateEnumTest.java
datalake/src/test/java/com/sequenceiq/datalake/FlowStateEnumTest.java
environment/src/test/java/com/sequenceiq/environment/FlowStateEnumTest.java
flow/src/test/java/com/sequenceiq/flow/helper/FlowStateEnumChecker.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmState.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/action/UpgradeCcmActions.java
freeipa/src/test/java/com/sequenceiq/freeipa/FlowStateEnumTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/FlowStateEnumTest.java

Add unit tests to check for all services this requirement.
FlowLog table has data (currentstate and variables) dependent on these classes being enums.
This needs a hotfix for 2.61 and the forward merge.

CB-18423 UpgradeCcmState FlowState implementation should be an enum

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshCommandRunnerActions.java
integration-test/src/main/resources/commandrunner/qa-command-runner.py
integration-test/src/main/resources/commandrunner/sample-command.json

This is a follow-up improvement for the [CB-18046 Introduce a command runner for Cloudbreak API Test project to multiple SSH #13252](https://github.com/hortonworks/cloudbreak/pull/13252) PR
We should introduce further improvements for the `integration-test/src/main/resources/commandrunner/qa-command-runner.py` script. Where we should be able to select the command(s) what we finally would like to run from commands Json file.

CB-18400 QA Command Runner script improvements with command selector

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/csd/csd-downloader.sh

In order to download the required CSD jars during the runtime upgrade, we need to use paywall access.
For some reason, the current script does not contain any authentication when trying to download the files.
In this commit, I added paywall authentication to the CURL command which is responsible to download the CSD files.
I also extended the CURL command with the --fail option because without this we saved the authentication failure response into the jar files.

ENGESC-16407: Missing paywall authentication from CSD downloader script

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/pg11-install.sls

To avoid yum reaching out to other repositories, `fromrepo` is added like it's done for upgrading CM.

CB-18466 Add `fromrepo` directive to postgres 11 install state

---

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/upgrade/RdsUpgradeV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/RdsUpgradeResponseType.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/upgrade/rds/DistroXRdsUpgradeV1Response.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/rds/DistroXRdsUpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeServiceTest.java

These fields are not used anymore because:
- successful responses do not have a reason
- error responses are returned via throwing an exception and are mapped as an exception mapper

CB-18471: Remove response type and reason fields from RDS upgrade response

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeSteps.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/operation/AwsRdsUpgradeOperations.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeStepsTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/operation/AwsRdsUpgradeOperationsTest.java

CB-18447 Distrox AWS external db is not ssl enforced after creation but will be after DB upgrade
RDS with enforced ssl only set for Datalake clusters. In case of Datahub clusters the 'enforced ssl' parameter is currently not set. The fix is that during DB upgrade the 'enforced ssl' parameter is only set for Datalake clusters.

CB-18447 Distrox AWS external db is not ssl enforced after creation but will be after DB upgrade

---

core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-mart.bp

As I saw in #13253, StubDFS will be added by CB automatically, so no need to rename this service in the bp.
This change has been tested on the pcqe mow-int tenant with a custom template and the deployment passed: https://quanta.infra.cloudera.com/#/runDetails?gtn=31503675
https://console.cdp.mow-int.cloudera.com/cloud/shared-resources/cluster-templates/details/7.2.16%20-%20Data%20Mart:%20Apache%20Impala,%20Hue%20No%20StorageOps
```
{
"cdhVersion": "7.2.16",
"displayName": "datamart",
"blueprintUpgradeOption": "GA",
"services": [
{
"refName": "hue",
"serviceType": "HUE",
"roleConfigGroups": [
{
"refName": "hue-HUE_SERVER-BASE",
"roleType": "HUE_SERVER",
"base": true
},
{
"refName": "hue-HUE_LOAD_BALANCER-BASE",
"roleType": "HUE_LOAD_BALANCER",
"base": true
}
]
},
{
"refName": "impala", …
```

CB-18269: Remove the CORE_SETTINGS service in the datamart blueprints

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java

Right now we have `stackAuthentication` method for every each cloud provider with different implementation to setting up SSH Public Key ID (AWS and MOCK) or Public Key (AZURE, GCP, YARN).
However these right now support only one stack authentication parameter set up.
Beyond these we have partially implemented solution for get Stack Authentication from SDX template. Right now this is only support setting up `publicKeyId` from template. So we need to improve this solution for the other two parameters as well.

CB-18514 Improve the E2E Stack Authentication for request parameters

---

freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaChecker.java

Do not append comma and space to status, unless there is a second part to be added.
Fixes statusReason to be returned as below:
`statusReason: "FreeIpa is UNREACHABLE, "`

CB-18495 Fix unfinished FreeIPA statuReason

---

structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterUseCaseMapper.java
usage-collection/src/main/proto/usage.proto

Adding EDH tracking for postgres upgrade feature. It starts with a validation (first step), and finished with the core upgrade flow. SDX upgrade is also tracked in core.

CB-18354 Postgres 11 upgrade: EDH tracking

---

datalake/src/main/java/com/sequenceiq/datalake/flow/upgrade/database/UpgradeDatabaseServerActions.java

When SDX postgres upgrade flow finishes, it sets status DATALAKE_UPGRADE_DATABASE_SERVER_FINISHED. However, DHs can only be started if the DL is in RUNNING state. That is, the DHs could not be started any more.
The present commit fixes this behavior by setting the RUNNING status.

CB-18566 SDX postgres upgrade flow sets wrong status upon finish

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateValidator.java
core/src/main/resources/application.yml
core/src/main/resources/defaults/clustertemplates/7.2.15/azure/datamart.json
core/src/main/resources/defaults/clustertemplates/7.2.16/azure/datamart.json
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateValidatorTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/impala/ImpalaVolumeConfigProvider.java

- We can stop the Real time data mart and data mart clusters in AWS, the error is resolved.
- Template changes for Data Mart cluster in Azure where the node count for attached volumes is changed to 0 and now in this case ephemeral volume from the instance would be used which is of comparable size of attached volumes.

CB-18330 Stop Error for Real Time Data Mart and Data Mart Clusters in AWS and Template changes for Data Mart Clusters in Azure

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/salt/SaltFunctionReport.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/salt/SaltHighstateReport.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/salt/SaltStateReport.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshSaltExecutionMetricsActions.java
integration-test/src/main/resources/salt/export_salt_metrics.sh

Added getSaltExecutionMetrics method to SshJClientActions, with which you can collect the salt highstate execution metrics in E2E test cases.
The collected metrics are sent back to the machine running CB from the salt master instance, and a json report is generated. The report contains data about:
- the instances a specific highstate affected
- which states ran on a specific instance
- how long a state took to run
- what salt functions were called during the application of a salt state (e.g. file.managed, cmd.run, etc.)
- details about specific function runs, such as duration, start time, return code, etc.
The generated reports could be collected as artifacts in the E2E test runs and be used to, for example, to identify salt states that took unusually long to complete.
(This PR contains …

CB-18222: Added ability to collect salt highstate execution metrics and generate json report from them

---

core/src/main/resources/defaults/blueprints/7.2.16/cdp-search-analytics.bp

The Search Analytics cluster template provides a minimal Solr cluster configuration using local file system. To use local filesystem instead of S3, Solr needs the core_defaultfs configuration to be set to empty string and have proper core-site.xml to be generated.
The core_defaultfs config used to be located inside the STORAGEOPERATIONS role, which was moved in 7.2.16 to the STUB_DFS service. In 7.2.16 the core_defaultfs config is a service level configuration in the CORE_SETTINGS service.
In this commit I moved the core_defaultfs config to service level and removed the STORAGEOPERATIONS from the template.

CDPD-44553: remove STORAGEOPERATIONS role from Search Analytics template

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/AltusMachineUserService.java

CB-18586. Setting access key type is missing for monitoring/databus

---

README.md
build.gradle
cloud-consumption/build.gradle

* `build.gradle` (root): Enable `application.properties` generation for `cloud-consumption` as well.
* `cloud-consumption/build.gradle`: Import AWS GovCloud environment variables when executing `bootRun`.
* `README.md` (root):
* Fix & add cloud-consumption details: DB, running in IDEA, running in CLI.
* Add Mock-Infrastructure running in CLI.
* Fix `LICENSE` file link.
* Document the various `*_SCHEMA_SCRIPTS_LOCATION` environment variables supported in `Profile`.
* Document AWS GovCloud environment variables.
* Document the complete list of service names supported in `CB_LOCAL_DEV_LIST`.
* Various spelling / wording / casing / formatting fixes.

CB-18151 `README` & build fixes for consumption

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/BackupOperationType.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/objectstorage/ObjectStorageValidateRequest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsObjectStorageConnector.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsIDBrokerMappedRolePermissionValidator.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsIDBrokerObjectStorageValidator.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsDataAccessRolePermissionValidatorTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsRangerAuditRolePermissionValidatorTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureObjectStorageConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidator.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureObjectStorageConnectorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidatorTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/ModelDescriptions.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxBackupLocationValidationRequest.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StorageValidationService.java
datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidator.java
datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxControllerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StorageValidationServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidatorTest.java
environment/src/main/java/com/sequenceiq/environment/environment/service/cloudstorage/CloudStorageValidator.java

Changes for CB-18406 had a bug causing NPE when the environment/datalake is created. 
This PR brings back changes done for CB-18406 and the necessary changes to fix the BUG it had.
Testing performed:
1. Made sure unit tests were passed.
2. Made sure the upgrade pre-checks were run through well.
3. Made sure the environment/datalake creation is good.
4. Made sure that permission pre-checks are not executed on environment/datalake creation.

Cb 18506:  Null pointer exception is caused by getBackupOperationType.

---

freeipa/src/main/resources/defaults/vm-logs.json
freeipa/src/main/resources/freeipa-salt/salt/freeipa/healthagent.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_healthagent_getcerts.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_healthagent_setup.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/httpd-crt-tracking.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/update_cnames.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/services/httpd-crt-change-tracker.service
freeipa/src/main/resources/freeipa-salt/salt/logrotate/conf/freeipa-healthagent-getcert
freeipa/src/main/resources/freeipa-salt/salt/logrotate/conf/freeipa-healthagent-setup
freeipa/src/main/resources/freeipa-salt/salt/logrotate/conf/httpd-crt-tracking
freeipa/src/main/resources/freeipa-salt/salt/logrotate/init.sls

On RHEL8, httpd is not using cert dbs by mod_nss anymore but uses crt files directly by mod_ssl. We should support pem generation for freeipa health agent directly from httpd crt file instead of using Server-Cert from cert db. We should track crt file changes similarly as Server-Cert was tracked in the cert db. We are using inotifywait 3rd party tool to track file changes, it triggers pem generation and freeipa healt agent restart.

CB-18332 Handle missing httpd Server-Cert

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/NameserverPillarDecorator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/NameserverPillarDecoratorTest.java

In this commit I added validation to prevent the nameserver settings in the service pillar from null values. Sometimes we set the nameserver address in the unbound config to null and this causes cluster creation failures. From now we're breaking the cluster install with a proper error message when the nameserver address is not present.

CB-18344: Add validation for nameserver settings during service pillar setup

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/Clue.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxCustomTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/AuditUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ErrorLogMessageProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/StructuredEventUtil.java

Add more investigation steps to the integration test module. After a failed test the framework:
- collects structured events for environment, freeipa, datalake resources,
- sorts the clues by checking if it contains issues so that developers don't need to scroll a lot to find the resource where the problem happened,
- presents the events in a nicely formatted human readable way.
The goal is to minimize the developer effort to find the root cause of the issue.
__Example output:__
Notice that now we don't just log huge jsons. We collect additional information and sort them by relevance. We can even see the exact stack trace from services which is present in structured events.
```
com.sequenceiq.it.cloudbreak.exception.TestFailException: All Exceptions that occurred during the test are …
```

CB-18570 Add more investigation steps to the integration test module

---

build.gradle
common/build.gradle
common/src/main/java/com/sequenceiq/cloudbreak/common/json/JsonUtil.java
common/src/main/java/com/sequenceiq/cloudbreak/common/json/TypedJsonUtil.java
flow/src/test/java/com/sequenceiq/flow/helper/FlowPayloadSerializabilityChecker.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/InstanceGroup.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/InstanceMetaData.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/SecurityGroup.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/SecurityRule.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/Stack.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/StackStatus.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/FreeIpaCleanupActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/event/cert/RevokeCertsRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/action/FreeIpaDownscaleActions.java

Annotating for Hibernate's circular references, also extend unit test with this. Adding Hibernate5 Jackson Module to skip lazy-loaded entities. Adding Time module to properly serialize Durations. Changing ObjectMapper configuration to prevent failure in case of self references (occuring mostly in exceptions).
Cleaning up RevokeCertsRequest.

CB-18601 Fixing multiple Jackson serialization issues

---

datalake/src/main/resources/application.yml

Sdx current timeout is 40 minutes, but there is anecdotal evidence that this might be too short (AWS HA upgrade). The upgrade timeout is thus increased to 120 min in this commit.

CB-18649 Datalake postgres upgrade timeout to 2 hours

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/instancegroup/DistroXInstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/instancegroup/DistroXInstanceGroupsBuilder.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/AbstractE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXAwsMigrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaRecipeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxCloudStorageTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRecipeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentChildTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/FreeIpaCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/FreeIpaRecipeDetachTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/RecipeUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/action/S3ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java
integration-test/src/main/resources/recipes/e2e-pre-termination.sh

PRE-Termination recipes are very hard to assert, because of the cluster is deleted after the recipes are executed. So we need to upload the result of recipe execution, for example: put a file into S3.
Furthermore this commit contains fixes:
- for the recently observed cascading delete mock test issue at [testDeleteChildAndParentEnvironment](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentChildTest.java#L164-L167) highlighted by @topolyai5 
- code style issues at changed classes

CB-18459 Create FreeIPA E2E test for pre-termination recipe

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorServiceTest.java

This commit introduces a fix to only perform `backup` and `restore` salt states on the primary gateway node.

CB-18648 - HA cluster's db upgrade fails

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmService.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmServiceTest.java

After upgrade, one or more of the nodes are terminated, and health check returns all nodes. The general status is that matters.
Added extra logging for debugging probable issues later.
This fix is a PROD blocker for CCM upgrade in 2.62.

CB-18637 FreeIPA health check was incorrect

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/StartFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/StopFlowEventChainFactory.java

External DB starts first and stops last.
Fixing this for customer issues.

CB-16314 Reorder Core Start/Stop flowchains for clean RDS start/stop

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java

Our latest AWS API E2E [Build #4638--2.63.0-b58-AWS (23-Sep-2022 11:52:18)](http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-aws/4638/) is failing, because of [testSDXPreClouderaManagerStartRecipe](http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-aws/4638/testngreports/com.sequenceiq.it.cloudbreak.testcase.e2e.sdx/SdxRecipeTests/testSDXPreClouderaManagerStartRecipe/) test `verifyPreTerminationRecipe` is failing.
The pre-termination recipe has not been added to the SDX POST request, as it should be the second recipe in a set.

CB-18681 E2E tests cannot introduce multiple recipes to SDX

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/polling/Poller.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPermissionService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPermissionServiceTest.java

To have a meaningful error message, `FreeIpaPermissionReplicatedPoller` is using `AttemptResults#continueFor` which expect an exception. If the poller is initialized with `stopIfException(true)`, this would cause a failure and stop polling. This prevents currently the polling after the first attempt. Poller adjusted to continue after an exception.

CB-18613 FreeIPA permission polling should not stop on exception

---

redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsUpgradeService.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/stack/RedbeamsUpgradeServiceTest.java

This commit does the following:
- if the upgrarde is triggered again when the upgrade is in progress, no exception is thrown, redbeams returns without triggering the upgrade flow
- if the DB is already at the target version, then upgrade flow is not be triggered

CB-18629 - Data Lake Postgres upgrade fails due to flow restart

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeManagementService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ClusterManagerUpgradeRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterManagerUpgradeHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeManagementServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeServiceTest.java

This commit contains the following improvements over the Cloudera Manager upgrade:
- Skip service stop if the runtime version is above 7.2.2.
- Skip the whole cluster manager upgrade if the target version is already installed
- Some improvements in the logging

CB-18110: Don't stop services before CM upgrade

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_healthagent_setup.sh

It is a workaround as cdp-freeipa-healthagent should not depend on a file what might missing (and it is missing on RHEL8). Final solution should be a fix in the healthagen. Instead of a string magic on top of the filename it should consume the service name form a different source in a failsafe way.

CB-18702 Fix cdp-freeipa-healthagent IndexError by creating the missing file on RHEL8

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/tags/upgrade/UpgradeV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePreconditionService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperations.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePreconditionServiceTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperationsTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/ModelDescriptions.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxUpgradeRequest.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeClusterConverter.java

In some cases we can't stop the Data Hub clusters, therefore we introduced a new option to enable the Data Hub to upgrade with running Data Hub clusters. The new option is called skipDataHubValidation.

CB-18421: Introduce a new flag to enable the Data Lake upgrade with running Data Hub clusters

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorService.java

The current retry counter of 20 is turned out to be not enough for some customers, as it takes ~4 minutes.
200 sounds like a better alternative.

CB-18774 - Backup/restore retry counter should be increased

---

core/src/main/java/com/sequenceiq/cloudbreak/service/datalake/SdxClientService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/CollectDbEngineVersionPatchService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/CollectDbEngineVersionPatchServiceTest.java

…in DL and core service
For old clusters it's possible the crn in the core and datalake service is different. In this case DL service returns with 404.
The solution is in this case, we list all datalakes for the environment and filter by name, and use it's crn for updating DB engine version.

CB-18780 COLLECT_DB_ENGINE_VERSION is failing where crn is different … 

---

datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxClusterConverterTest.java

added test to ensure that name translation doesn't introduce any potential NPE for conversion.

CB-18035 NPE in datalakeWaitObject

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/salt/SaltHighStateDurationAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshSaltExecutionMetricsActions.java

We should save the generated `Salt HighStates TotalDuration` report to disk. Major goal of this to keep the new report at Jenkins as test artifact along with others Salt reportsCB-18667 Save the Salt HighState Total Duration report as test artifact on Jenkins.

CB-18667 Save the Salt HighState Total Duration report as test artifact on Jenkins

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/salt/SaltHighStateDurationAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/salt/SaltFunctionReport.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/salt/SaltHighstateReport.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/salt/SaltStateReport.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshSaltExecutionMetricsActions.java

API E2E GCP [#1787--2.63.0-b91-GCP (04-Oct-2022 09:20:24)](http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-gcp/1787/) build is failing, because of [testCreateDistroXWithEncryptedVolumes](http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-gcp/1787/testngreports/com.sequenceiq.it.cloudbreak.testcase.e2e.distrox/DistroXEncryptedVolumeTest/testCreateDistroXWithEncryptedVolumes/) generating Salt report step throws `UnrecognizedPropertyException: Unrecognized field "_stamp"`.
So we should introduce a `@JsonIgnoreProperties(ignoreUnknown = true)` annotation at the related Salt util classes. Furthermore should manage the `getSaltExecutionMetrics` exceptions with warning and the case when the `List<SaltHighstateReport>` is empty.

CB-18800 [API E2E] Unrecognized field at SaltFunctionReport exception

---

core/src/main/resources/defaults/vm-logs.json
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/get_backup_data_sizes.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/init.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/get_backup_data_sizes.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Jira: https://jira.cloudera.com/browse/CB-18775
Please look at this [section in my design document](https://docs.google.com/document/d/17cNhj9gz-qoB_lnAXGMMwXIcA8jRYb0TuYhUq9v3s1s/edit#heading=h.5k4lj3wyor3) to understand what's happening in the script.
Overall the objective of this is just to enable functionality via Salt to obtain the sizes of all of the data in the DL to be backed up by the backup operation. This results in a flat JSON string like this:
```
{"database":{"hive":12153503,"ranger":18854559},"hbase":{"atlas_entity_audit_events":408,"atlas_janus":954200},"solr":{"edge_index":69,"fulltext_index":69,"ranger_audits":1663331,"vertex_index":496952}}
```
Tested this by creating a local DL, and running the Salt state using generic Salt commands from within the DL's primary gateway …

CB-18775: Added Salt script for determining the sizes of the DL data to be backed up.

---

environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentStatus.java
environment/src/main/java/com/sequenceiq/environment/environment/EnvironmentStatus.java
environment/src/main/java/com/sequenceiq/environment/environment/sync/EnvironmentSyncService.java
environment/src/test/java/com/sequenceiq/environment/environment/sync/EnvironmentSyncServiceTest.java

Add missing FreeIPA statuses as many cases the syncer function was returning AVAILABLE even if the FreeIPA was in failed/unreachable/unhealthy etc. state. New EnvironmentStatuses were needed too.

CB-18726 Fix environment status syncer

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentNetworkTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AzureMarketplaceImageTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java

We have implemented a special single resource group usage flag for AZURE: `SINGLE_WITH_DEDICATED_STORAGE_ACCOUNT`. This kind of single resource group usage will reduce the execution time of the tests and might add to stability.

CB-18626 Enable dedicated storage account for azure E2E with SINGLE_WITH_DEDICATED_STORAGE_ACCOUNT resource group usage

---

cloud-azure/src/main/resources/templates/arm-v2-freeipa.ftl
cloud-azure/src/main/resources/templates/arm-v2.ftl
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AzureMarketplaceImageTest.java

Jira - https://jira.cloudera.com/browse/CB-18599
Added tags to availabilitySets and PublicIPAddresses for load balancer, the only way that I could test if the resource has tags on it is to check if tags exist on the environment itself. I couldn't get the resources from the current way the environment is defined and changing that will take a lot more effort.

CB-18599 - Some Azure resources types are not tagged - fix arm templates

---

integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/client/GcpClient.java

We got several intermittent GCP list/query storage object, list/delete/stop instances ([CB-18678](https://jira.cloudera.com/browse/CB-18678), [CB-18788](https://jira.cloudera.com/browse/CB-18788)) issues during our E2E builds. Furthermore we had some deprecated components (JacksonFactory, GoogleCredential) on these GCP clients. So we should update the related libs and methods.

CB-18847 [API E2E] GCP Storage and Compute client need to be updated based on latest changes

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-cb-policy.json
cloud-aws-common/src/main/resources/definitions/aws-cb-policy.json

This commit allows chaning Log Retention Policy for Cloudwatch
logs. By default, cloudwatch log group has infinite log retention
policy, in DWX , we are making the default as 7 days and as such
we need this permission.

CB-18303: Allow changing LogRetentionPolicy for Cloudwatch Logs

---

common/src/main/java/com/sequenceiq/cloudbreak/quartz/TracedQuartzJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/instancemetadata/ArchiveInstanceMetaDataJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/nodestatus/NodeStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/salt/StackSaltStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJob.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/job/StructuredSynchronizerJob.java

Some quartz jobs still used the deprecated non typer-safe getMdcContextObject() instead of the type-safe getMdcContextConfigProvider() implementation. The legacy one could not resolve fields from Hibernate generated proxy view objects, so these were replaced in this commit. There are still some jobs using the legacy method, but those use types that can be resolved by MDCBuilder.buildMdcContext().

CB-18853 Fix MDC context of quartz jobs

---

core/src/main/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordServiceTest.java

Fallback implementation includes re-bootstrapping all nodes, so they have to be running. The lack of this validation caused start-stop autoscale enabled cluster failures.

CB-18858 Additional validation for fallback salt password rotation

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/InstanceMetaDataToCloudInstanceConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceGroupRepository.java

The JPQL query was wrong. If the reference projected instead of the join, the root object wasn't returned from DB"

CB-18666 Cannot convert InstanceMetaData to CloudInstance if the security group is null for the InstanceGroup. 

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java

CB-18503 Knox is not accessible after upgrade and stop-start
Set knox autorestart config parameter to true in all case of cluster start.

CB-18503 Knox is not accessible after upgrade and stop-start

---

cloud-consumption/src/main/java/com/sequenceiq/consumption/flow/ConsumptionFillInMemoryStateStoreRestartAction.java
common/src/main/java/com/sequenceiq/cloudbreak/logger/MDCBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/restart/DisableOnGCPRestartAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/restart/FillInMemoryStateStoreRestartAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/restart/InitializeMDCContextRestartAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/stop/StackStopRestartAction.java
datalake/src/main/java/com/sequenceiq/datalake/flow/FillInMemoryStateStoreRestartAction.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/EnvironmentFillInMemoryStateStoreRestartAction.java
flow/src/main/java/com/sequenceiq/cloudbreak/service/flowlog/FlowLogUtil.java
flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java
flow/src/main/java/com/sequenceiq/flow/core/RestartAction.java
flow/src/main/java/com/sequenceiq/flow/core/RestartContext.java
flow/src/main/java/com/sequenceiq/flow/core/config/AbstractFlowConfiguration.java
flow/src/main/java/com/sequenceiq/flow/core/restart/DefaultRestartAction.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java
flow/src/test/java/com/sequenceiq/flow/core/Flow2HandlerTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/FillInMemoryStateStoreRestartAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/InitializeMDCContextRestartAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/stop/StackStopRestartAction.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/common/FillInMemoryStateStoreRestartAction.java

Flow engine can't restart flow chain if the application stops right after the a flow is finished. This change fixes it be checking not only the last flow but the overall state of the flow chain as well.

CB-17686 The flowchain could get stuck between flows after pod restart/deployment.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DatalakeDatahubCreateAuthTest.java

In a recent E2E run, `DatalakeDatahubCreateAuthTest.testCreateEnvironment()` failed with: `You have tried to assign to SdxInternalTestDto, that hasn't been created and therefore has no Response object` cryptic error in the TestNG report. Upon closer inspection and digging up test logs, the root cause could be found much earlier: `Default error handler: Authorization failed due to user management service call timed out.` So basically the `SdxInternalEndpoint.create()` call failed due to an UMS timeout. The test case, however, kept running further.
Here need to break up the logic into multiple resource validation sections (e.g. one for `SdxInternalTestDto` followed by another one for `RenewDatalakeCertificateTestDto`). Each such section should conclude with an explicit `validate()` …

CB-18883 DatalakeDatahubCreateAuthTest needs to be refactored because the current logic may hide the actual failure cause

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerUpgradeService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerUpgradeServiceTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/InternalUpgradeSettings.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXUpgradeV1Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeManagementService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeDatalakeFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeDistroxFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/AbstractClusterUpgradeAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/ClusterUpgradeTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/DistroXUpgradeTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ClusterManagerUpgradeRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ClusterUpgradeRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterManagerUpgradeHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterUpgradeHandler.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXUpgradeV1Controller.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeManagementServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeDistroxFlowEventChainFactoryTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperationsTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java

In this commit I've extended the internal endpoint of the distrox upgrade with an additional rollingUpgradeEnabled request parameter. The effect of the rollingUpgradeEnabled parameter:
- We're not stopping the cluster services before the Cloudera Manager upgrade.
- Adding ApiCdhUpgradeArgs for the CDH upgrade command to indicate the rolling upgrade in cm
Small improvements:
- Skip Cloudera Manager upgrade when the target version is already installed.
- Minor logging improvements.

CB-18548 Trigger distrox runtime upgrade with rolling upgrade option

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/DiskSpaceValidationService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/DiskSpaceValidationServiceTest.java

The original error message was:
`There is not enough free space on the nodes to perform upgrade operation. The required free space by nodes: host1: 4.2 GB, host2: 5.8 GB`
The new message contains the available space for each nodes:
`There is not enough free space on the nodes to perform upgrade operation. The required and the available free space by nodes: host1: required free space is: 4.2 GB and the available free space: 890 MB, host2: required free space is: 5.8 GB and the available free space is: 1.6 GB`

CB-18934: Extend the disk space validation failure message with the available disk space

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/NifiUpgradeValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/NifiUpgradeValidatorTest.java

In this commit I've extended the error message of the NifiUpgradeValidator.
Original message:
`Nifi working directory validation failed. The current directory /var/etc is not eligible for upgrade.`
New message:
`Nifi working directory validation failed. The current directory /var/etc is not eligible for upgrade because it is located on the root disk. The Nifi working directory should be under the /hadoopfs/fs path. During upgrade or repair the Nifi directory would get deleted as the root disk is not kept during these operations.`

CB-17825: Extend Nifi working directory validation error message

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRepairService.java

Jira: https://jira.cloudera.com/browse/CB-18963
Directly after this logic, the finished state of `SdxRepairActions` runs:
`SdxCluster sdxCluster = sdxStatusService.setStatusForDatalakeAndNotify(DatalakeStatusEnum.RUNNING,
ResourceEvent.SDX_REPAIR_FINISHED, "Repair finished, Datalake is running", payload.getResourceId());`
So I have removed this status update to keep the event log clean.

CB-18963: SDX repair flow has duplicate event logs.

---

cloud-consumption/build.gradle
cloud-consumption/src/main/java/com/sequenceiq/consumption/configuration/api/EndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/StructuredEventFilterTest.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/EndpointConfig.java
environment/src/main/java/com/sequenceiq/environment/configuration/api/EndpointConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/configuration/EndpointConfig.java
redbeams/build.gradle
redbeams/src/main/java/com/sequenceiq/redbeams/configuration/DatabaseConfig.java
redbeams/src/main/java/com/sequenceiq/redbeams/configuration/EndpointConfig.java
redbeams/src/main/java/com/sequenceiq/redbeams/event/RedbeamsStructuredFlowEventFactory.java
redbeams/src/main/resources/application.yml
redbeams/src/main/resources/schema/app/20221013125607_CB-18959_include_structuredeven-service-cdp_in_the_redbeams_service.sql
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/CloudbreakEventService.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/cdp/redbeams/CDPRedbeamsStructuredFlowEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/cdp/redbeams/RedbeamsDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/filter/CDPJaxRsFilterPropertyKeys.java

**Changes:**
- CB-18959 enable strict audit filter in Consumption and Redbeams services
- CB-18426 register filters in an individual private method in endpoint configs - some cosmetics of filter registration that just verbally mentioned as a review item for the original PR

CB-18959 Configurable audit for Consumption and Redbeams services

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/MonitoringTests.java

Runtime 7.2.15+ pre-warmed images with Common Monitoring are available for now. So we can use default images where `smon-exporter`, `cm_health_check_info` and `request-signer's error_count` with `success_count` are working properly for now at metrics endpoints.
So we can add these test cases to the L0 Promotion suite on Jenkins MOW-Dev E2E.

CB-18885 [API E2E] Introduce new Monitoring L0 tests to the MOW-Dev Jenkins jobs

---

README.md

* Root README: Add JVM arg `consumption.cloudbreak.url` to Consumption service sections (IDEA and Command Line).

CB-19000 Update README with new JVM arg for consumption->core dependency

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperations.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperationsTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/ModelDescriptions.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxUpgradeRequest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/flow/chain/DatalakeUpgradeFlowEventChainFactory.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/DatalakeUpgradeActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/event/DatalakeUpgradeFlowChainStartEvent.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/event/DatalakeUpgradeStartEvent.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeService.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/flow/SdxReactorFlowManagerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java

The core of the rolling upgrade logic is implemented in the CB. In this commit I extended the Data Lake upgrade API with the rolling upgrade option and I extend the internal upgrade Cloudbreak API with the rolling upgrade parameter

CB-18938: Data Lake rolling runtime upgrade

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorService.java
datalake/src/main/resources/application.yml

A customer had a ~300GB, the backup and upload would have lasted more than the allotted 30 minutes of time. In the present commits we increase timeouts:
- backup and restore to ~1h 23min
- the whole upgrade process to 3h
As a side effect, if anything in PG upgrade would hang, the total timeout would be 3h.

CB-19031 Postgres backup timed out because of large DB

---

datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/DatalakeBackupActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/validation/DatalakeBackupValidationActions.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/status/SdxStatusService.java
datalake/src/test/java/com/sequenceiq/datalake/job/SdxClusterStatusCheckerJobTest.java

Jira: https://jira.cloudera.com/browse/CB-19023
Simply added a new method to the status service for accepting a message argument for the event sent with the other parameters.

CB-19023: Fix failure reason display in events generated by backup failures.

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilderTest.java

- Delete all volumes even if there is one or more already deleted
- Delete all volumes even if there is one or more already detached

CB-18446 COD operation leave old EBS volumes as orphan in AWS

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/BootstrapService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/BootstrapServiceTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltActionType.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltConnector.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/Cloud.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/Os.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/SaltAction.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/SaltMaster.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrap.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrapFactory.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStateService.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/utils/MinionUtil.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrapTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStateServiceTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/utils/MinionUtilTest.java

Simplified the rebootstrap step by refactoring it out from the bootstrap step - this way the salt states will not be uploaded, and only the gateway nodes have to be rebootstrapped.

CB-18993 Improve salt password rotation fallback implementation

---

core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ccm/StackCcmUpgradeService.java

Before it did not filter out TEMPLATEs
Also changed the logic to filter the inclusive upgradable tunnel types instead of the exclusive target tunnel type.

CB-19054 Fix Stack repository function "getNotUpgradedStackCount"

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxUpgradeDatabaseServerAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonClusterManagerProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxUpgradeDatabaseServerTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxUpgradeDatabaseServerTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-longrunning-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/gcp-longrunning-e2e-tests.yaml

CB-18416, CB-18417, CB-18418: E2E tests for Postgres Upgrade on AWS, Azure, GCP
E2E test steps:
- Create Datalake cluster with Postgres10 external database
- Upgrade the database to Postgres11
- Check the database version is updated to 11 in CB services
- Check the database server version is upgraded to 11 using psql "show server_version" command on the primary gateway node

CB-18416, CB-18417, CB-18418: E2E tests for Postgres Upgrade on AWS, Azure, GCP

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeDistroxFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/ClusterRepairTriggerEvent.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactoryTest.java

When we call rolling OS upgrade on Data Hub clusters is using the regular VM replacement but it should call the zero downtime upgrade to replace the VMs one by one. In this commit I modified the UpgradeDistroxFlowEventChainFactory to create a new ClusterRepairTriggerEvent with oneNodeFromEachHostGroupAtOnce flag based on the rolling upgrade option.

CB-19079: Data Hub rolling OS upgrade is using zero downtime upgrade

---

autoscale/src/main/java/com/sequenceiq/periscope/filter/AuditFilter.java
autoscale/src/main/java/com/sequenceiq/periscope/service/AuditService.java
autoscale/src/test/java/com/sequenceiq/periscope/filter/AuditFilterTest.java
autoscale/src/test/java/com/sequenceiq/periscope/service/AuditServiceTest.java
ccm-connector/src/test/java/com/sequenceiq/cloudbreak/ccmimpl/ccmv2/CcmV2ManagementClientTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/service/DatahubServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDatabusServiceTest.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/ThreadBasedUserCrnProvider.java
flow/src/test/java/com/sequenceiq/flow/core/AbstractActionTest.java

CB-19042 improve logging and sent parameters around Autoscale audit event sending
**Improvements:**
- send request method and request id with audit events
- proper log context setup for Autoscale's async audit event sender with request id, user crn, tenant to make the investigations easier
- modify ThreadBasedUserCrnProvider to update the MDC context too when user crn is updated on the thread local level

CB-19042 improve logging and sent parameters around Autoscale audit event sending

---

integration-test/src/main/resources/testsuites/e2e/gcp-longrunning-e2e-tests.yaml

CB-18418 fix gcp-longrunning-e2e-tests.yaml indentation

CB-18418 fix gcp-longrunning-e2e-tests.yaml indentation

---

flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java
flow/src/test/java/com/sequenceiq/flow/service/flowlog/FlowLogDBServiceTest.java

There are some cases when the FlowType is not set in the FlogLog table. In this commit, I added a null check to prevent the DB server deletion from NPE when the FlowType is null.

CB-19036: Fix DB server deletion when the FlowType is null

---

common-model/src/main/java/com/sequenceiq/common/api/backup/base/BackupBase.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeRdsFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/RdsUpgradeChainTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/rds/UpgradeRdsDataBackupRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/rds/UpgradeRdsTriggerRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/BackupRdsDataHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/BackupRestoreDBStateParamsProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActionsTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/BackupRdsDataHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/BackupRestoreDBStateParamsProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeServiceTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentBaseResponse.java
orchestrator-salt/src/main/resources/salt/salt/postgresql/upgrade/scripts/backup_db.sh

During postgres upgrade CDP creates a backup on Azure (on AWS and GCP the provider creates it automatically). The backup is then uploaded to cloud storage. The upload up to now used cdp-telemetry. At some customers, however, because of some unknown permission issue, the backup could not be uploaded. A PoC at these customers showed that with the attached msi azcopy is capable of copying the backup to the cloud storage without any issues. Also at the same customers freeipa backup also worked flawlessly with azcopy.
In the present commit thus cdp-telemetry is changed for azcopy.

CB-19033 Use azcopy instead of cdp-telemetry to upload Azure DB backup

---

cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/metadata/AwsNativeLbMetadataCollector.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/loadbalancer/AwsNativeLoadBalancerLaunchService.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/loadbalancer/AwsNativeLoadBalancerLaunchServiceTest.java

* Platform variant: `AWS_NATIVE`
* Handle the case when the stack has both an external and internal LB.
* Just like for the CF-based AWS variant, separate `loadbalancer`, `targetgroup` and `listener` ELB resources will be provisioned, depending on the scheme requested.
* The LB provisioning logic remains idempotent.
* Some code cleanup.
* Testing:
* Manual testing in local CB: Data Engineering HA, `AWS` and `AWS_NATIVE` variants.
* Added new UT and updated existing ones.

CB-18989 Fix provisioning of multiple LB per stack with native

---

integration-test/src/main/resources/testsuites/e2e/gcp-longrunning-e2e-tests.yaml

some test are not workig properly on gcp. disabling those and fixing them on master

CB-19142 testsuites/e2e/gcp-longrunning-e2e-tests.yaml was introduced

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeServiceTest.java

Embedded DB upgrade is executed via the pg_upgrade utility, and needs both pg 10 and 11 installed on the same image. To make sure that the customer has both, an OS upgrade is required as well. 
As a result embedded DB upgrade should not be allowed via the Database server upgrade API of distrox, it will not work.

CB-18968 Do not allow database upgrade via API for datahubs with embedded DB

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorService.java
datalake/src/main/resources/application.yml

In this commit, I updated the salt retry count from 500 to 2000 and the upgrade timeout from ~1h 23min to ~5h 30min

CB-19389: Extend salt timeout for database upgrade backup

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java

The internal endpoints had a validation, that only accepted USER-s, but not MACHINE_USER-s. This caused upgrade failures when DL service called to core.

CB-19116 Accept machine user on `StackV4Endpoint` db upgrade endpoints

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1ControllerTest.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterUseCaseMapper.java
usage-collection/src/main/proto/usage.proto

This commit adds a new endpoint to the DistroXV1 API that initiates Salt Update on a Datahub. This operation previously was only available on the StackV4 internal endpoint. EDH tracking for separate Salt Update operation is also added.

CB-19072 New DistroX endpoint for initiating Salt Update

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/info/model/RightV4.java

Right is required to be exposed to be used on UI.

CB-17460 Add CREATE_PROXY right to RightV4

---

integration-test/src/main/resources/application.yml

We have `currentRuntimeVersion: 7.2.0` [test parameter](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/resources/application.yml#L91) at `cloudbreak/integration-test/src/main/resources/application.yml`.
The GCP provider is not supported at `Runtime: 7.2.0`. Furthermore we should update to `7.2.7`.
**So the `currentRuntimeVersion` should be updated to `7.2.7` where the GCP provider is also supported.**

CB-19522 [API E2E] Set the Upgrade/Recovery tests default "currentRuntimeVersion" to 7.2.7

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/AuthorizationClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/PersonalResourceViewClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/config/UmsClientConfig.java

CB-19063 tracing should be configurable in ums clients in order to avoid tracing to block ums related requests in tests

---

integration-test/src/main/resources/testsuites/e2e/gcp-longrunning-e2e-tests.yaml

Previously we've removed following test suites from the GCP Longrunning YAML:
- com.sequenceiq.it.cloudbreak.testcase.e2e.sdx.SdxUpgradeRecoveryTests
- com.sequenceiq.it.cloudbreak.testcase.e2e.sdx.SdxRepairTests
- com.sequenceiq.it.cloudbreak.testcase.e2e.sdx.SdxUpgradeDatabaseServerTests 
We have done on the default `currentRuntimeVersion` to `7.2.7` task ([CB-19522](https://jira.cloudera.com/browse/CB-19522)) for 2.65.0-b33+. So we can set the above test suites back.

[API E2E] Rewind the GCP Longrunning test suite for Master

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidator.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/Scope.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidatorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/ScopeTest.java

Add /providers/Microsoft.Management/managementGroups/ scope prefix for management group support. Management group related scopes are not hierarchical, thus they can be matched on the static string above.

CB-19087 Azure storage validation should support management group

---

freeipa/src/main/resources/application.yml

Right now it's disabled  on Azure and GCP, but customers can have their own dnssec enabled nameservers which could cause failures.

CB-17695 Disable dnssec validation by default on freeipa in named.conf

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerRestartService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerRestartServiceTest.java

In this commit, I've added support for performing rolling patch upgrades.
- Extract CM service restart logic into a separate class.
- Call rolling restart instead of rolling upgrade instead of the regular restart command

CB-19045: Support rolling patch upgrade

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/UserV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UserOperationDescriptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/AbstractUserSyncTaskRunner.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PostUserSyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PreUserSyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/TimeoutTaskScheduler.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/AbstractUserSyncTaskRunnerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/PostUserSyncServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/PreUserSyncServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/TimeoutTaskSchedulerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncServiceTest.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/main/resources/application.yml

Exposing WAG creation with pre usersync API, and sudo rule creation as post usersync API  for WIAM. The new endpoint are internal only.
The actual logic is running async, so WIAM should check the operation to see if it's finished. Same operation type (USER_SYNC) is used during the new endpoints, so there shouldn't be conflicting usersyncs.
`CDP_ENVIRONMENT_PRIVILEGED_USER` is enabled in mock-thunderhead to enable testing.

CB-18795 Create pre and post usersync endpoint

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/chain/RepairFlowEventChainFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/chain/UpgradeFlowEventChainFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/upscale/action/FreeIpaUpscaleActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/upscale/event/UpscaleEvent.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/InstanceMetaDataService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/instance/InstanceMetaDataServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/InstanceMetadataServiceComponentTest.java

The subnet and AZ will be saved to the new instance metadata. The instances are grouped by the same group type and we create the same amount of instances with the same amount of AZs

CB-17129 Ensure FreeIPA instances are in different AZ after upgrade.

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/ExternalDatabaseService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsClientService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/ExternalDatabaseServiceTest.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v1/RedBeamsFlowEndpoint.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/client/RedbeamsApiKeyEndpoints.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/client/RedbeamsClient.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/client/RedbeamsServiceCrnEndpoints.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/client/internal/RedbeamsApiClientConfig.java

When only monitoring the stack status, there was an issue, where the upgrade failed, but the syncer detected the server as available, and updated the status before the core service could check it.
Now the upgrade endpoint returns a flow id, which we us to poll the redbeams service about the upgrade flow status. If there is no flow id in the response, that means the upgrade has already finished.

CB-19095 Monitor Redbeams upgrade flow status instead of stack status

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidatorTest.java

- Here we will be checking the health of the hosts on which the services will be dependent before the downscale operation

CB-19260 pre stopstart scaling checks - validate health of dependent services in downscale flow

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaModelDescriptions.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/image/ImageSettingsResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/image/ImageToImageEntityConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/image/ImageToImageSettingsResponseConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/ImageEntity.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java
freeipa/src/main/resources/schema/app/20221118110148_CB-18840_Add_ldapagentversion_column_to_image_table.sql
freeipa/src/test/java/com/sequenceiq/freeipa/converter/image/ImageToImageEntityConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/image/ImageToImageSettingsResponseConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageServiceTest.java

Store LDAP agent version to `ImageEntity` when creating FreeIPA. Also update it during upgrade. The version is exposed in `DescribeFreeIpaResponse#image` under `ldapAgentVersion` field.

CB-18840 Expose LDAP agent version on FMS API

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxFlowEndpoint.java
datalake-api/src/main/java/com/sequenceiq/sdx/client/internal/SdxApiClientConfig.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/EndpointConfig.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxFlowController.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/DatalakeMultipleFlowsResultEvaluator.java
environment/src/main/java/com/sequenceiq/environment/environment/poller/SdxPollerProvider.java
environment/src/main/java/com/sequenceiq/environment/environment/service/sdx/SdxPollerService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/sdx/SdxService.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/DatalakeMultipleFlowsResultEvaluatorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/poller/SdxPollerProviderTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/sdx/SdxPollerServiceTest.java

The environment poller shouldn't stop in case of exception, because the flow is still running on the datalake side.

CB-18563 Datalake failed to start but Environment had run to timeout

---

datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/converter/GrpcStatusResponseToDatalakeBackupRestoreStatusResponseConverter.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/converter/OperationEnum.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/model/DatalakeBackupStatusResponse.java
datalake-dr-connector/src/test/java/com/sequenceiq/cloudbreak/datalakedr/converter/GrpcStatusResponseToDatalakeBackupStatusResponseConverterTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/DatalakeBackupActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/DatalakeRestoreActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/validation/DatalakeBackupValidationActions.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreService.java

[CDPSDX-3783](https://jira.cloudera.com/browse/CDPSDX-3783): Update the `DatalakeDrResponseConvert` to handle the `VALIDATION_FAILED` state. 
[**IMPROVEMENT**]: Use the `isFailed` method rather than the `getState` and validate the `state` value.
[**Rasason**]: the upgrade and the resize flow do not handle the `VALIDATION_FAILED` state. Therefore, if something fails in the backup or restore process. The flow continues, which can cause data loss in the `Datalake`.
Test cases:
with `cbd`
**Upgrade** light duty dl with 7.2.12 to 7.2.16
* validation failed case - the upgrade failed. 
* validation success case - the upgrade run without any error.
**Resize** light duty dl to medium duty
* validation failed case - the resize failed.
* validation success case - the resize run without any error.

CDPSDX-3783: Update the DatalakeDrResponseConvert

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

During recipe execution we noticed the pillars returned by salt command (eg pillar.get) are stale while the files are up to date. After calling syncall command the pillars seems to be up to date. This has caused salt rendering issues during our e2e tests.

CB-18829 Add syncall salt call after uploading pillars

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/ResourceConnector.java
cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/ResourceConnectorTest.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsParameterGroupService.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsTerminateService.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsResourceConnector.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeService.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeSteps.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/operation/AwsRdsUpgradeOperations.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsParameterGroupServiceTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsTerminateServiceTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeServiceTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeStepsTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/operation/AwsRdsUpgradeOperationsTest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/client/AmazonRdsClient.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/client/AmazonRdsClientTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnectorTest.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockResourceConnector.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/upgrade/handler/UpgradeDatabaseServerHandler.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/upgrade/handler/UpgradeDatabaseServerHandlerTest.java

CB-19550 On Aws after Rds upgrade the newly created custom parameter group won't be deleted during cluster termination
The fix contains the following steps:
* During rds upgrade the new parameter group will be stored in the resource table in redbeams db
* After successfull rds upgrade the previous parameter group will be deleted from aws and from resource table in redbeams db
* During termination the stored parameter group will be deleted on AWS

CB-19550 On Aws after Rds upgrade the newly created custom parameter group won't be deleted during cluster termination

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/ProviderSpecificImageFilter.java

Image filter should have returned a mutable list implementation as it turned out there is a specific code path which tries to delete from the filtered image list:
```
if (!imageFilter.isBaseImageEnabled()) {
baseImages.clear();
}
```

CB-19811 - Image list could not be cleared during image selection

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCloudResourceService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceType.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCloudResourceServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnectorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceServiceTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/network/NetworkParameterAdder.java

All the Private Endpoint related cloud resources for the given RDS stack get deleted and re-created instead of marking them
`DETACHED` and re-attach them afterwards.
This prevents us from naming errors like in CB-19574, when subnet naming
convention change results in inconsistent naming of a Private Endpoint
resource.

CB-19563, CB-19672 - Private endpoints for old clusters should be handled properly

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsComputeResourceService.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleService.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/context/AwsContextBuilder.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNativeResourceConnectorTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureComputeResourceService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/context/AzureContextBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpCredentialConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpNetworkConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpResourceConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/context/GcpContextBuilder.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpCredentialConnectorTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpNetworkConnectorTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpResourceConnectorTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/context/GcpContextBuilderTest.java
cloud-template/build.gradle
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractInstanceConnector.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/ComputeResourceBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/ResourceContextBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceService.java
cloud-template/src/test/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/migration/handler/CreateResourcesHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/migration/handler/CreateResourcesHandlerTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/migration/handler/CreateResourcesHandler.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/migration/handler/CreateResourcesHandlerTest.java

If an instance and the related disk creation finished at the same time, then they will have the same resource name: https://github.com/hortonworks/cloudbreak/blob/39ad3cbd6e285cf6dc95028e0bad620e0c7f1a61/cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/GcpResourceNameService.java#L112
https://github.com/hortonworks/cloudbreak/blob/39ad3cbd6e285cf6dc95028e0bad620e0c7f1a61/cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/GcpResourceNameService.java#L49-L57
The stop logic tries to find instance resource by name here (I think the creator wanted to find the instance resource builder with this "creative" logic): https://github.com/hortonworks/cloudbreak/blob/115451c8a2c883967d1447f5695dae2bc9c3736e/cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud …

CB-19729 refactor GCP stop

---

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringUrlResolver.java
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringUrlResolverTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/TelemetryApiConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/telemetry/TelemetryConfigService.java

Implemented entitlement based controll on turning monitoring on. For freeipa monitoring is turned on during freeipa repair with REBUILD option. For datalake and datahub a simple stop/start is enough to turn on monitoring.
This feature is needed in 2.65 to enable saas team to turn on monitoring on production clusters.

CB-19716 Implemented entitlement based controll on turning monitoring on

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltConnector.java

The workaround is to add an additional "arg" with a dummy value, but besides the workaround I had to do a small refactor to satisfy CheckStyle's cyclomatic complexity criteria as well.

CB-19687: Added a quick workaround to support SaltStack 3005.1

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/util/AwsStackNameCommonUtil.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/util/AwsStackNameCommonUtilTest.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilder.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilderTest.java

The pattern will be stack-name-stackid-group-name. The created instances won't be affected but after a repair or OS Upgrade, the name will change

ENGESC-17409 Change the AWS Instance name to the CF template's format on AWS_NATIVE variant

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureNetworkConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformResources.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStackViewProvider.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureNetworkConnectorTest.java
common/src/main/java/com/sequenceiq/cloudbreak/constant/AzureConstants.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/AzureNetworkV4Parameters.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AzureEnvironmentNetworkConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4Converter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AzureEnvironmentNetworkConverterTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/EnvironmentNetworkAzureParams.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/AzureNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/AzureEnvironmentNetworkConverter.java
environment/src/main/resources/schema/app/20221114171700_CB-19610_Support_customer_provided_AKS_private_DNS_zones.sql
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverterTest.java
environment/src/test/java/com/sequenceiq/environment/network/v1/converter/AzureEnvironmentNetworkConverterTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/network/AzureNetworkParameters.java
structuredevent-model/src/main/java/com/sequenceiq/environment/network/dto/AzureParams.java

Liftie and AKS based CDP services allow the customer to specify a private DNS zone id for AKS. The zone should be provided during environment creation and is stored in environment service.
This commit adds code to POST, GET and store the private DNS zone id. The zone id can always be specified, irrespective of if private endpoints are used or not in the environment. There is no validation as of yet, will be added in a later commit.

CB-19610 AKS private DNS zone - post, get and store

---

sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/sdx/TargetPlatform.java

There was a bug in the past where DLs created with DH crns, this is why we need this.

CB-16771 return with PAAS TargetPlatform if the crn did not match to any crn we assume.

---

integration-test/README.md
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/AbstractE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java

Azure setup for E2E tests should consist of 2 Resource Groups:
- Volatile resource group with expensive and frequent deploys (can't have cloud cost ignore tag)
- Resource group for static resources (can have cloud cost ignore tag; eg.: storage accounts)

CB-19719 E2E test single resource group should not have cloud cost ignore

---

core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/upgrade/DistroXUpgradeV1Request.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXUpgradeV1Controller.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXUpgradeV1ControllerTest.java

In this commit I've added the rollingUpgradeEnabled parameter to the DistroXUpgradeV1Request. With this addition we can initiate the rolling upgrade from the public API as well.

CB-19852: Add rolling upgrade parameter for Data Hub upgrade public API

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsTerminateService.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeService.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeServiceTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/cloud/CloudResourcePersisterService.java

CB-19810 Redbeams CloudResourcePersisterService multiple deletion does not work properly
The fix is to use notification.getCloudResources() instead of getCloudResource() in redbeams CloudResourcePersisterService.delete() method.

CB-19810 Redbeams CloudResourcePersisterService multiple deletion does not work properly

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/AbstractE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaRebuildTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaRecipeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaScalingTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java

The commonly used `createDefaultEnvironment` method does not contains Telemetry related steps. So neither SDX, DistroX nor FreeIPA are created with Telemetry in these environments by default (expect if the Telemetry is defined directly for these resources in the related test). So we should introduce the well-known Telemetry related steps here by default to can get cluster-logs for FreeIPA, SDX and DistroX by default.
Where the Telemetry is applied along with the test steps and the `createDefaultEnvironment` is used, we should remove redundant Telemetry definition from test.

CB-19884 Introduce Telemetry for E2E createDefaultEnvironment method

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/ExternalDatabaseConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/ExternalDatabaseService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbCertificateProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/conf/ExternalDatabaseConfigTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/ExternalDatabaseServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbCertificateProviderTest.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/start.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/root-certs.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/settings.sls

* If applicable, configure the DH external DB with SSL enforcement.
* Prerequisites: AWS or Azure cloud platform, DH runtime >= 7.2.2, entitlement `CDP_CB_DATABASE_WIRE_ENCRYPTION_DATAHUB` (see #13824) granted for the tenant.
* When the external DB has SSL enforcement, configure DH CM Server to require SSL connections. Like for its DL counterpart, CM Server DB connections are initiated with `sslmode=verify-full`, i.e. using DB server certificate chain and host name verification.
* DB server root certs are deployed to the cluster in the following cases:
* Cluster is a DL and its external DB has SSL enforcement. The cert bundle will contain the DL DB root certs only.
* Cluster is a DH having an embedded DB, but the DL has an external DB with SSL enforcement. The cert bundle will contain the …

CB-19725 Enable DB SSL for DH CM

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java

GCP API Longrunning E2E Build #1677 is failing, because of `testSDXMultiRepairIDBRokerAndMasterWithTerminatedEC2Instances`. Here the Waiting for the `DELETED_ON_PROVIDER_SIDE` state of cluster is cancelled, because of `CLUSTER_UNREACHABLE` failed state. The root cause here is the `Update deprecated cluster status from: UNREACHABLE to: DELETED_ON_PROVIDER_SIDE` has been done 3 seconds after the final wait cycle was ended.
So we should wait longer in case of E2E tests (because of provider or CB can be slower in case of increased load). We can accomplish this with the help of `maxRetryCount` parameter.

CB-19914 Increase the maxRetryCount for E2E tests to extend the Waiting Limit

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/database/base/DatabaseType.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/ProfilerAdminRdsConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/ProfilerMetricsRdsConfigProvider.java

* `DatabaseType`: Add `@Deprecated` to the following constants: `DRUID`, `SUPERSET`, `AMBARI`, `CLOUDERA_MANAGER_MANAGEMENT_SERVICE_REPORTS_MANAGER`, `BEACON`.
* `ProfilerAdminConfigProvider` & `ProfilerMetricsConfigProvider`: Rename them by inserting `Rds` before `ConfigProvider`. Both are subclasses of `AbstractRdsConfigProvider`.

CB-10852 Fix DatabaseType deprecations Profiler RdsConfigProvider naming

---

environment/src/main/java/com/sequenceiq/environment/environment/EnvironmentStatus.java
environment/src/main/java/com/sequenceiq/environment/environment/repository/EnvironmentRepository.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java

If an env is in "FREEIPA_UNHEALTHY", then we don't schedule it on a pod restart because this list does not contain these statuses:
https://github.com/hortonworks/cloudbreak/blob/a6e0c4d027bdbbe46da6d4fe0a5d0faaa7d480bf/environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java#L424-L456
It should not work like this.
We should specify the disallowed statuses.

CB-19958 Environmentservice rescheduling missing envs in FREEIPA_UNREACHABLE, FREEIPA_UNHEALTHY status

---

flow-api/src/main/java/com/sequenceiq/flow/api/model/FlowCheckResponse.java
flow/src/main/java/com/sequenceiq/flow/core/FlowLogService.java
flow/src/main/java/com/sequenceiq/flow/domain/FlowLogWithoutPayload.java
flow/src/main/java/com/sequenceiq/flow/repository/FlowLogRepository.java
flow/src/main/java/com/sequenceiq/flow/service/FlowService.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java
flow/src/main/resources/schema/flow/20221201084526_CB-19881_add_index_to_flowlog_table.sql
flow/src/test/java/com/sequenceiq/flow/service/FlowServiceTest.java
flow/src/test/java/com/sequenceiq/flow/service/flowlog/FlowLogDBServiceTest.java

1. Added new method FlowLogRepository to get all flow related information using flowChainId.
2. Edited existing method in FlowLogRepository to return FlowLogWithoutPayload using flowChainId instead of flowLogId (checked to see where else this is being used and safely edited it).
3. Added login in FlowService to check if all flows in a chain is complete before adding an end time to FlowCheckResponse.

CB-19881 - add end time to flow check endpoint.

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java

We tested with 2.65.0-b62 salt version, so we only trust this version and we can make sure this version properly works. https://github.com/hortonworks/cloudbreak/commit/df926b9417a6f32ef00e6565002dc51d0cc7b917

CB-19968 add salt version check for monitoring enablement

---

core/src/main/java/com/sequenceiq/cloudbreak/service/account/PreferencesService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/account/PreferencesServiceTest.java

The original implementation returned all supported platforms based on cloud constants when it was not defined explicitly by 'cb.enabledplatforms'. Now we have gov platform support as well ('cb.enabledgovplatforms') so the default behaviour of 'supported platforms' should not take effect in case of existing gov platform.

CB-19903 Enabled platforms should take care about gov platforms

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/StartAmbariServicesHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterServiceRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/StartAmbariServicesHandlerTest.java

When doing upgrade recovery it can happen that the CM master node gets a new IP address and when starting to check the CM server startup via CM API the old IP is used for calling the API. This change maked sure that the metadata in cluster that contains the CM server IP is updated upon IP change.

CB-19909 Update CM IP in cluster object if it has changed

---

common/src/main/java/com/sequenceiq/cloudbreak/util/FreeIpaPasswordUtil.java
common/src/main/java/com/sequenceiq/cloudbreak/util/PasswordUtil.java
common/src/test/java/com/sequenceiq/cloudbreak/util/PasswordUtilTest.java

CB-15640 make our PasswordUtil FIPS compliant
**Changes:**
- refactor FreeIpaPasswordUtil to use our PasswordUtil
- use org.apache.commons.lang3.RandomStringUtils only in PasswordUtil
- configure org.apache.commons.lang3.RandomStringUtils with SecureRandom
- unit test to cover generations
- remove unnecessary hashing with MD5 and BigInteger's toString with Radix operations
- keep backward compatibility with 26 chars length

CB-15640 make our PasswordUtil FIPS compliant

---

flow/src/main/java/com/sequenceiq/cloudbreak/service/ha/HeartbeatService.java
flow/src/main/java/com/sequenceiq/flow/cleanup/FlowCleanupJob.java
flow/src/main/java/com/sequenceiq/flow/core/FlowRegister.java
flow/src/test/java/com/sequenceiq/cloudbreak/service/HeartbeatServiceTest.java

Heartbeatservice tries to check if any flow should be restarted; meanwhile, a flow can be in the finalization process. The flowLogService.findAllByCloudbreakNodeId returns the flow, but at the same time we removed the flow from the runningFlows. In this case, heartbeatservice will restart the flow, but it should not be restarted.

CB-20006 Edge case: Heartbeatservice restarts flow at the moment of flow finalizing

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/ums/EnvironmentAccessChecker.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/ums/EnvironmentAccessCheckerTest.java

`GrpcUmsClient` switched from throwing `StatusRuntimeException` to `UnauthorizedException` when the user/right is missing. This change was not handled on usersync side, causing usersync failures.

CB-20004 Failed usersync caused by authorization failure

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePrivateDnsZoneDescriptor.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePrivateDnsZoneRegistrationEnum.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePrivateDnsZoneServiceEnum.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/AzureExistingPrivateDnsZoneValidatorService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/AzurePrivateDnsZoneMatcherService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/AzurePrivateDnsZoneValidatorService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/AzureExistingPrivateDnsZoneValidatorServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/AzurePrivateDnsZoneMatcherServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/AzurePrivateDnsZoneValidatorServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/PrivateDnsZoneValidationTestConstants.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzureExistingPrivateDnsZonesService.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzurePrivateEndpointValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/azure/AzureExistingPrivateDnsZonesServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/azure/AzurePrivateEndpointValidatorTest.java

It is possible to register an Azure AKS private DNS zone to environment service. It is not used by cloudbreak, but environment services is used as the info source on the AKS private DNS zone. The current commit introduces some basic validations for the DNS zone:
- does it name match that of the AKS
- does it exist
- is it connected to the VNET passed to the environment
Note, that Azure AKS DNS zone names, unlike that of the Postgres, are variable:
- have a region in their name
- can have a subzone That is, instead of exact name matching, now a regex matching is used.

CB-19624 AKS private DNS zone - validations

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/action/S3ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/client/S3Client.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/action/AzureCloudBlobClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java

Audit dir creation sometimes flaky. The cause can be the same storage location for audit logs for all the test resources even if the test class contains more than one test cases.

CB-19889 Each test case should have own Cloud Storage Base Location

---

environment-api/src/main/java/com/sequenceiq/environment/api/v1/credential/model/parameters/azure/AzureCredentialRequestParameters.java
environment/src/main/java/com/sequenceiq/environment/credential/validation/aws/AzureCredentialValidator.java
environment/src/test/java/com/sequenceiq/environment/credential/validation/AzureCredentialValidatorTest.java

* Remove NotNull annotation from subscriptionId and tenantId field in AzureCredentialRequestParameters
* Remove required flag from ApiModelProperty on these fields
* Azure credential validation improvement: subscriptionId and tenantId are not required in case of certificate based credential.

CB-19971 Remove NotNull from subscriptionId and tenantId

---

environment/src/main/java/com/sequenceiq/environment/network/CloudNetworkService.java
environment/src/test/java/com/sequenceiq/environment/network/CloudNetworkServiceTest.java

Take into consideration if Endpoint Gateway Subnet IDs were empty or overlapped with the regular Subnet IDs

CB-20059 fix deployment restrictions output

---

core/src/main/java/com/sequenceiq/cloudbreak/service/datalake/DataLakeStatusCheckerService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/SdxConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/service/datalake/DataLakeStatusCheckerServiceTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/SdxConverterTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterStatusResponse.java
datalake/src/test/java/com/sequenceiq/sdx/api/model/SdxClusterStatusResponseTest.java
sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/sdx/PaasSdxService.java
sdx-connector/src/test/java/com/sequenceiq/cloudbreak/saas/sdx/PaasSdxServiceTest.java

Some data hub operations (Create/Start) were failing when the datalake backup was in progress. Since the backup should not interfere in this feature the block was removed. The datahub admin operations are allowed in running and backup in progress after this change.
Obs: stop and delete currently already work, so no change needed in these cases.
Tests:
Scenario 1:
Create a new DH when a backup is in progress without errors.
Backup created with `cdp datalake backup-datalake --datalake-name`
Scenario 2:
Start a DH when a backup is in progress without errors.
Scenario 3:
DH admin operations should be blocked when DL is restoring a backup.

CB-19967 - DH admin operations are allowed when data lake backup is in progress

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/SdxBackupRestoreTest.java

This change also adds a check on database backup folder - verified _hive_ and _ranger_ database backup files presence.
Tested locally on AWS datalake

[CB-19827] More checks on SdxBackupRestoreTest - database backup files

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXUpgradeV1Controller.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxUpgradeEndpoint.java
datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeControllerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/database/SdxDatabaseServerUpgradeServiceTest.java

Added validation to accept Datalake CRN or Cluster name only for datalake database upgrade
Also fixed DH end point to give correct error message if it is called with DL CRN

CB-18849 Commanding Datahub DB upgrade applied to the dataLake

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java

Adding two measurements when launching FreeIPA to be able to see which step could consume a lot of time in case of a failure.

CB-20081 Adding measurement to FreeIPA launch

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_replica_install.sh

Validation has been applied to avoid ntp config change in case of already installed ipa client.
https://github.com/freeipa/freeipa/commit/2fba5acc5245caf62ec9af8b8707c13f59bfcff4
FreeIPA related e2e tests are passed with centos7 image: http://ci-cloudbreak.eng.hortonworks.com/job/cloudbreak-pull-request-builder-aws-test/31166/testngreports/com.sequenceiq.it.cloudbreak.testcase.e2e.freeipa/
FreeIPA related e2e tests are passed with redhat8 image as well: http://ci-cloudbreak.eng.hortonworks.com/job/cloudbreak-pull-request-builder-aws-test/31170/testngreports/com.sequenceiq.it.cloudbreak.testcase.e2e.freeipa/

CB-20083 Removes no-ntp flag from ipa-replica-install

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/inifile/IniFile.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/inifile/IniFileFactory.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/inifile/IniFileSection.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/inifile/IniFileFactoryTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/inifile/IniFileSectionTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/inifile/IniFileTest.java
template-manager-cmtemplate/src/test/resources/input/clouderamanager-existing-conf.bp
template-manager-cmtemplate/src/test/resources/input/hue-ssl.bp
template-manager-cmtemplate/src/test/resources/output/hue-ssl.bp

* `HueConfigProvider`:
* Add DB SSL configs to Hue service safety valve if needed.
* Eliminate template variables. All settings are now set as regular name-value configs.
* `CmTemplateProcessor.chooseApiClusterTemplateConfig()`: Add support for merging INI file safety valve values.
* Fix various typos and other code clean-up.
* Testing:
* Manual test with a Data Engineering DH in a commercial AWS region.
* Added new UT & adapted existing ones.

CB-19951 Implement SSL for Hue DB

---

autoscale/src/main/java/com/sequenceiq/periscope/PeriscopeApplication.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/ConsumptionApplication.java
common/build.gradle
common/src/main/java/com/sequenceiq/cloudbreak/util/FipsOpenSSLLoaderUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/CloudbreakApplication.java
datalake/src/main/java/com/sequenceiq/datalake/DatalakeApplication.java
dependencies.gradle
docker-autoscale/Dockerfile
docker-cloudbreak/Dockerfile
docker-consumption/Dockerfile
docker-datalake/Dockerfile
docker-environment/Dockerfile
docker-freeipa/Dockerfile
docker-redbeams/Dockerfile
environment/src/main/java/com/sequenceiq/environment/EnvironmentApplication.java
freeipa/src/main/java/com/sequenceiq/freeipa/FreeIpaApplication.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/service/MockUmsService.java
redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsApplication.java

CB-18225 import Cloudera's openssl-provider library and configure it to be the most prior java security provider for FIPS
Changes:
- Register the com.cloudera.crypto.openssl-provider as default security provider for FIPS
- Register the new provider manually in our services application class, only for FIPS enabled environments
- Make stronger signer secret in mock-thunderhead to run in FIPS env
**The following log messages has been added and occurred during testing to indicates the working of the util on FIPS enabled and non-FIPS enabled environments:**
`2022-12-20 15:35:27,894 [main] registerOpenSSLJniProvider:26 INFO  c.s.c.u.FipsOpenSSLLoaderUtil - [type:springLog] [crn:] [name:] [flow:] [requestid:] [tenant:] [userCrn:] [environment:] [traceId:] [spanId:] Registering …

CB-18225 import Cloudera's openssl-provider library and configure it to be the most prior java security provider for FIPS

---

integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-native-tests.yaml

CB-16143 remove unnecessary .java extension from aws-long-running-e2e -native-tests.yaml

CB-16143 remove unnecessary .java extension from aws-long-running-e2e -native-tests.yaml

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/ResourceConnector.java
cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/ResourceConnectorTest.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsResourceConnector.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpdateService.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpdateServiceTest.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNativeResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpResourceConnector.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockResourceConnector.java
cloud-template/src/test/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnectorTest.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/userdata/UserDataUpdateActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/userdata/UserDataUpdateOnProviderRequest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeCcmFlowChainIntegrationTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/update/handler/UpdateUserDataOnProviderHandler.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/chain/UpgradeCcmFlowChainIntegrationTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/update/UpdateUserDataFlowIntegrationTest.java

The old implementation updated each Launch Template of AWS CF stacks with the gateway's userdata, now it updates each separately with it own userdata.

CB-20098 Update userdata of each Launch Template separately

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/datalakemetrics/datasizes/GetDatalakeDataSizesHandler.java
datalake-dr-connector/src/generated/main/java/com/cloudera/thunderhead/service/datalakedr/datalakeDRProto.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/converter/DatalakeDataInfoJsonToObjectConverter.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/converter/GrpcStatusResponseToDatalakeBackupRestoreStatusResponseConverter.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/converter/OperationEnum.java
datalake-dr-connector/src/main/proto/datalakedr.proto
datalake-dr-connector/src/test/java/com/sequenceiq/cloudbreak/datalakedr/converter/DatalakeDataInfoJsonToObjectConverterTest.java
orchestrator-salt/src/main/resources/salt/salt/datalake_metrics/get_free_space/get_free_space.sls

*Motivation:*
We want to prevent backups which will fail. One of the reasons backup can fail is a lack of temporary storage space on a database backup node. We want to send information about free available space on a node - we know which node performs database backup - to Thunderhead where it will be checked against required storage.
*Implementation*
Available space is collected by a Salt script using Linux _df_ command in POSIX compatibility mode (so higher chances output is uniform at different installations).
We reuse "determine datalake_data_sizes" call to feed this information into Thunderhead Datalake DR since it belongs to that process.
*Test approach:*
- Start database backup
```shell
cdp datalake backup-datalake --datalake-name sartyukh-045-dl-db-backup --debug`
```
"backupId": …

CB 19575 determine free space on a database backup node

---

core/src/main/java/com/sequenceiq/cloudbreak/service/loadbalancer/LoadBalancerConfigService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/loadbalancer/LoadBalancerConfigServiceTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/azure/AzureEnvironmentParameters.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/parameters/dao/domain/AzureParameters.java
environment/src/main/java/com/sequenceiq/environment/parameters/v1/converter/AzureEnvironmentParametersConverter.java
environment/src/main/resources/schema/app/20221206104600_CB-19623_add_no_outbound_load_balancer.sql
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/v1/converter/AzureEnvironmentParametersConverterTest.java
mock-thunderhead/src/main/resources/application.yml
structuredevent-model/src/main/java/com/sequenceiq/environment/parameter/dto/AzureParametersDto.java

Azure Option to disable the outbound load balancer creation that otherwise is created by default.
Testing:
Post to `/environmentservice/api/v1/env`
Condition:
When the Public endpoint gateway is disable and it's a private network and noOutboundLoadBalancer is true
Should create just the one load balancer (private)
When the noOutboundLoadBalancer is false
Should create two load balancers (private and outbound)
Example Json:
`{
"name": "rod-env-azure-05-001",
"credentialName": "rod-cred",
"regions": ["West US 2"],
"location": {
"name": "West US 2"
},
"network": {
"subnetIds": ["sdx-daily.internal.0.westus2"],
"serviceEndpointCreation": "ENABLED",
"publicEndpointAccessGateway": "DISABLED",
"azure": {
"networkId": "sdx-daily",
"resourceGroupName": "sdx-daily",
"noPublicIp": true
}
}, …

CB-19623 - Add option to disable outbound load balancer creation

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientExceptionUtil.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Permission.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Right.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/AbstractFreeIpaAddOperation.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/GroupAddMemberOperation.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/PermissionAddOperation.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/SetWlCredentialOperation.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/SudoCommandAddOperation.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/SudoRuleAddAllowCommandOperation.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/SudoRuleAddDenyCommandOperation.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/SudoRuleAddGroupOperation.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/SudoRuleAddOperation.java
freeipa-client/src/test/java/com/sequenceiq/freeipa/client/operation/AbstractFreeIpaAddOperationTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/binduser/UserSyncBindUserService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/binduser/UserSyncBindUserServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallServiceTest.java

As the ldapsync user need to modify the `admins` group membership, it doesn't make any sense to create fine grain permissions for it, as it would provide only some security through obscurity.
Get rid off the previous role memberhsip as admins don't need anything else.

CB-20127 Add ldapsync binduser to `admins` group on FreeIPA

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

https://jira.cloudera.com/browse/CB-14806
Before this change we could force the deletion of DL with attached DH in some cases. After this change, whenever DL has a DH attached, it won't be possible.
Test:
Before the change 
`cdp datalake delete-datalake --datalake-name rod-dl-21 --force` with the DH stopped. It worked.
After the change the same command returns an error
`An error occurred: The following Data Hub(s) cluster(s) must be terminated before SDX deleting: [dh-21]. (Status Code: 400; Error Code: INVALID_ARGUMENT; Service: datalake; Operation: deleteDatalake; Request ID: a55aa998-93ad-4b34-9bd2-b5e0e314d2bd;)`
Tested before/after the change
DL without DH can be deleted with/without force flag.

CB-14806 - Reject forced DL termination if there are any existing DH clusters

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCloudFormationClient.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsValidatorsTest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsClient.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/endpoint/AwsEndpointProvider.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/endpoint/AwsRegionEndpointProvider.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/endpoint/AwsServiceEndpointProvider.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsAuthenticatorTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsInstanceConnectorTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/endpoint/AwsEndpointProviderTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/endpoint/AwsRegionEndpointProviderTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/endpoint/AwsServiceEndpointProviderTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsStorageValidatorsTest.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNativeMetadataCollectorApiIntegrationTest.java

… enabled. aws.fips.use.endpoint mut be true to enable this logic. By default it must be supported by AWS sdk but because of a bug we need this workaround until we do not upgrade to aws sdk v2.

CRB-2367 FIPS for AWS

---

orchestrator-salt/src/main/resources/salt/salt/top.sls

This state should not be applied automatically, a separate state.apply call should be issues when needed

CB-20154 Remove 'modifyproxy' state from top.sls

---

flow/build.gradle
flow/src/main/java/com/sequenceiq/flow/cleanup/FlowCleanupConfig.java
flow/src/main/java/com/sequenceiq/flow/cleanup/FlowCleanupJob.java
flow/src/main/java/com/sequenceiq/flow/core/FlowLogService.java
flow/src/main/java/com/sequenceiq/flow/repository/FlowLogRepository.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java
flow/src/test/java/com/sequenceiq/flow/repository/FlowLogRepositoryTest.java
flow/src/test/java/com/sequenceiq/flow/repository/RepositoryTestConfig.java

- Added a configurable endTimeDuration to flow cleanup configs
- Propagate this param to the service layer and compute the endTimeUpperBound epoch ms
- Purge flow logs below computed upper bound
- Repository test for FlowLogRepository to verify correct behaviour

CB-19868 Retain flow information for atleast 24 hours after completion

---

freeipa/src/main/resources/freeipa-salt/salt/top.sls
orchestrator-salt/src/main/resources/salt-common/salt/faillock/init.sls
orchestrator-salt/src/main/resources/salt/salt/top.sls

When an instance is joining FreeIPA the SSSD and auth is reconfigured on RH8 so faillock has to be reenabled. The faillock configuration is part of the iamge.
Image related changes: https://github.com/hortonworks/cloudbreak-images/pull/755

CB-19579 CB-19578 Enable faillock for Redhat 8

---

common/src/main/java/com/sequenceiq/cloudbreak/constant/AzureConstants.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/AzureNetworkV4Parameters.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AzureEnvironmentNetworkConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/loadbalancer/LoadBalancerConfigService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4Converter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AzureEnvironmentNetworkConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/loadbalancer/LoadBalancerConfigServiceTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4ConverterTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/EnvironmentNetworkAzureParams.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/azure/AzureEnvironmentParameters.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/AzureNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/AzureEnvironmentNetworkConverter.java
environment/src/main/java/com/sequenceiq/environment/parameters/dao/domain/AzureParameters.java
environment/src/main/java/com/sequenceiq/environment/parameters/v1/converter/AzureEnvironmentParametersConverter.java
environment/src/main/resources/schema/app/20221222165000_CB-20153_move_no_outbound_load_balancer_to_network.sql
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverterTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/v1/converter/AzureEnvironmentParametersConverterTest.java
structuredevent-model/src/main/java/com/sequenceiq/environment/network/dto/AzureParams.java
structuredevent-model/src/main/java/com/sequenceiq/environment/parameter/dto/AzureParametersDto.java

Context: This [PR](https://github.com/hortonworks/cloudbreak/pull/13925) creates the noOutboundLoadBalancer field in the Azure Environment params but it should be in the Azure Network.
This PR fix it without any change in the feature.
Test:
Testing:
Post to /environmentservice/api/v1/env
Condition:
When the Public endpoint gateway is disabled and it's a private network and noOutboundLoadBalancer is true
Should create just one load balancer (private)
When the noOutboundLoadBalancer is false
Should create two load balancers (private and outbound)
Json:
noOutboundLoadBalancer inside the network.azure
`{
"name": "rod-env-no-outbound",
"credentialName": "rod-cred",
"regions": ["West US 2"],
"location": {
"name": "West US 2"
},
"network": {
"subnetIds": ["sdx-daily.internal.0.westus2"], …

CB-20153 - Move noOutboundLoadBalancer field from Azure Environment to Azure Network

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/init.sls

Package check that prevents unnecessary installation is only valid for CentOS 7, so added an additional check for RHEL8 as well.

CB-20216: Prevent CB from forcefully installing psycopg2 2.7.5 on RHEL8

---

core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelAvailabilityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelService.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelAvailabilityServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelServiceIntTest.java

During upgrade, We have seen cases where Parcel availability check fails but later it is successful. To reduce the failures, we are adding retry policy to check parcel availability.

CB-18161 Parcel Availability Checker should retry failed requests

---

orchestrator-salt/src/main/resources/salt/salt/datalake_metrics/get_database_sizes/scripts/get_database_sizes.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh

we want to estimate how big our database backup will be.
Previously used _pg_database_size_  gives us the size of a database on disk. This includes data not used during backup - indexes, dead entries before vacuum other support structures etc. 
The new estimator query only takes into account data from public tables which should give a better estimate.
In order to keep backup smaller the `-Z 9` option is added for compression. Smaller backup takes less time to write to temp location (disk) and then to a cloud bucket.
Short cycle:
- create LightDuty and login to _master_
- update salt (if not updated)
- perform backup and check database backup files successfully created in the cloud
- execute `/opt/salt/scripts/get_database_sizes.sh "" "" ""` to check sizes determined without errors
Full …

CDPSDX-3779 better estimation on database backup size

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/group/GcpInstanceGroupResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpBackendServiceResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/GcpResourceNameService.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/group/GcpInstanceGroupResourceBuilderTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpBackendServiceResourceBuilderTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/service/GcpResourceNameServiceTest.java

If we resize the DataLake we create new resources from a blueprint with the same names as in the old DataLake and this causes GCP to request creation requests due to name conflict.
Name strategy before: DATALAKE_NAME-templateName
we create an environment with LightDuty DL. DL blueprint is [datalake/src/main/resources/duties/7.2.15/gcp/light_duty.json](https://github.com/hortonworks/cloudbreak/blob/master/datalake/src/main/resources/duties/7.2.15/gcp/light_duty.json)
and datalake name is "butterfly". Among other things this will request an _idBroker_ instanceGroup (line 12) and create a cloud resource with the name "butterfly-idBroker"
Later on we decide to resize the DL to Medium Duty. This will use [datalake/src/main/resources/duties/7.2.15/gcp/medium_duty_ha.json](https://github.com/hort …

CB-20087 make GCP cloud resource names unique to a stack

---

common/src/main/java/com/sequenceiq/cloudbreak/util/FreeIpaPasswordUtil.java
common/src/main/java/com/sequenceiq/cloudbreak/util/PasswordUtil.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/cluster/ClusterV4Request.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/cluster/DistroXClusterV1Request.java

* `ClusterV4Request`, `DistroXClusterV1Request`: Fix validation error messages for `userName` and `password`.
* `FreeIpaPasswordUtil.generatePassword()`, `PasswordUtil.generatePassword()`: Use `SecureRandom` for the `Collections.shuffle()` call.
* `PasswordUtil`:
* `generatePassword()`: Change logic to an adaptation of `FreeIpaPasswordUtil.generatePassword()`. The generated password will always start with a 6-char prefix of letters, followed by a random mix of 10-10 numbers and letters, thus still giving a total of 26 characters. While the letter prefix is not a strict requirement for sake of validations in `ClusterV4Request` & `DistroXClusterV1Request`, it still makes sense to use a behavior consistent with the FreeIPA password.
* Remove unused `getRandomLettersAndNumbers()`.

CB-20208 Ensure password complexity is always satisfied

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/init.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/create_embeddeddb_certificate.sh

* Extend the postgres/init salt state with certificate generation when postgres ssl is enabled
* Create a rsa:2048 keypair using openssl
* Sign the certificate with freeipa
First the certificate generation and sign was planned to be implemented in FMS service via API, but for this
the postgres server host has to be registered in FreeIPA. The host registration is happening during salt highstate,
so it is not possible to sign the certificate before salt highstate has finished. This is the reason why we choose
the previously described solution for certificate generation.

CB-20174 Generate embedded PostgreSQL server cert using FMS

---

environment-common/build.gradle
environment-common/src/main/java/com/sequenceiq/cloudbreak/service/verticalscale/VerticalScaleInstanceProvider.java
environment-common/src/test/java/com/sequenceiq/cloudbreak/service/verticalscale/VerticalScaleInstanceProviderTest.java

* `VerticalScaleInstanceProvider.listInstanceTypes()`:
* Handle edge cases.
* Add additional logs.
* Minor code-cleanup / refactoring for a more expressive logic.
* Testing: Added new UT & adapted existing ones.

CB-20258 `NoSuchElementException` in `VerticalScaleInstanceProvider`

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCredentialConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/util/AzureAuthExceptionHandler.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/util/AzureExceptionExtractor.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/util/AzureExceptionExtractorTest.java

CB-18306 Azure error messages are quite ugly due to line breaks and json format
* AzureExceptionExtractor improvement: extract error and error_uri json parameters from the azure exception message next to the error_description.
* AzureAuthExceptionHandler will throw new ProviderAuthenticationFailedException with the extracted error message. No exception chain will be used, as the exception mapper send the root exception's message via the API
* AzureCredentialConnector.verify will throw new CloudConnectorException with the extracted error message as well
* The original exception will be logged before the extraction

CB-18306 Azure error messages are quite ugly due to line breaks and json format

---

integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java

Even we have ignored cleanup failures earlier the waiter still set the test to failed. With this change the failure is removed.
Also excluded `io.grpc` from `google-cloud-storage` dependency as it depends on a newer version which caused runtime issues.

CB-20157 CB-16966 Ignore cleanup failures during wait

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kudu/KuduMasterConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kudu/KuduMasterConfigProviderTest.java

Previously, the Kudu config provider didn't actually run when creating a cluster, because instead of extending AbstractRoleConfigProvider, it was implementing CmTemplateComponentConfigProvider. This patch fixes that.

CB-18996 Fix Kudu config provider

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/init.sls

This is basically the continuation of #14020 / #14032 for CentOS 7 (those were added for RHEL8 compatibility)

CB-20216: Added psycopg2 package check for CentOS7+Py3.8

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/action/S3ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/action/AzureCloudBlobClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java

MOW-Dev API GCP E2E are failing, because of `testSDXBackupRestoreCanBeSuccessful` is failing with `hive_backup has 0 sub-objects`. The path contains two file objects and not directory ones: `hive_backup` and `ranger_backup`. So here the GCP object listing and validation is needed to be updated, similar as is at AWS and AZURE.

CB-20304 GCP Sdx Backup and Restore is failing, hive_backup and ranger_backup is 0

---

autoscale/src/main/java/com/sequenceiq/periscope/config/ScalingActivityCleanupConfig.java
autoscale/src/main/java/com/sequenceiq/periscope/model/ScalingActivities.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/CleanupMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/ScalingActivityMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/context/ScalingActivitiesEvaluatorContext.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/cleanup/ActivityCleanupEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/executor/ExecutorServiceWithRegistry.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/ScalingActivityRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/RejectedThreadService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ScalingActivityService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ha/PeriscopeNodeService.java
autoscale/src/main/resources/application.yml
autoscale/src/test/java/com/sequenceiq/periscope/monitor/CleanupMonitorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/cleanup/ActivityCleanupEvaluatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/repository/ScalingActivityRepositoryTest.java
autoscale/src/test/java/com/sequenceiq/periscope/service/ha/PeriscopeNodeServiceTest.java

- Added a new monitor to run at a frequency of 10 min, which collects scalingActivityIds older than a set duration
- Corresponding evaluator will publish an event, whose handler will perform deletion of records.

CB-19650 Purge stale Scaling Activities from periscope

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java

Added the -cp option to indicate the cloud provider to CM server file.
The screenshot shared below is from the file /etc/default/cloudera-scm-server file 
Before the change:
After the change :
`CMF_SERVER_ARGS="-i /etc/cloudera-scm-server/cm.settings -cp  AWS -env PUBLIC_CLOUD"`
This change is applicable only If the CM version is greater than or equal to 7.6.2 as per the comment mentioned in the jira CB-16136. Screenshot of the same below

CB-16136:Set Cloud Type Variable in CM

---

structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/conf/StructuredEventSchemaLocationProvider.java
structuredevent-service-cdp/src/main/resources/schema/structuredevent/20230124110711_CB-20451_add_index_to_cdp_structered_event.sql

Cleanup from this table takes a long time as index was missing for the query. The SQL has been added to the module itself, to avoid copying it over to other services.

CB-20451 Add accountid-timestamp index to cdp_structured_event table

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseRestKnoxServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseRestKnoxServiceConfigProviderTest.java

[CDPSDX-3868](https://jira.cloudera.com/browse/CDPSDX-3868) Extend the Datalake wire encryption with Hbase RPC protection. The new default value is `privacy`. This change is controlled by the `SDX_CONFIGURATION_OPTIMIZATION` entitlement.

CDPSDX-3868 Extend the Datalake wire encription with Hbase rpc protection

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/setup-autotls.sh.j2

Adding this parameter has been requested by CM to make things compatible with RHEL 8. Details described in the ticket.

CB-20478: Added parameter to avoid invalid CA certs

---

common-model/src/main/java/com/sequenceiq/common/api/type/LoadBalancerType.java

A new LoadBalancerType is added and the Swagger Compatibility checker complains because of this.

CB-18948 Swagger compatibility fix - no shape change

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

Remove check which prevents backup/restore on GCP while doing upgrade and resize flows.
Backup/restore were not fully supported previously on GCP so flows exclude backup step for it. Now we have GCP backup/restore working and tested for a long time we can enable this functionality as part of the flow.
- set the `auth.mock.datalake.backup.on.upgrade.enable` property to `true` (default is `false`) in mock-thunderhead application.yaml file.
- start mock-thunderhead with this properties
- create a GCP environment with datalake version 7.2.15
- upgrade the environment to 7.2.16
- check backup has been created as part of the flow
- set the `auth.mock.datalake.backup.on.resize.enable` property to `true` (default is `false`) in mock-thunderhead application.yaml file.
- start mock-thunderhead with …

[CDPSDX-3334] Allow backup/restore for GCP. 

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/service/LoadAlertPolicyHostGroupInstanceInfo.java
autoscale/src/main/java/com/sequenceiq/periscope/service/RegularScalingAdjustmentService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/StopStartScalingAdjustmentService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/YarnBasedScalingAdjustmentService.java

wrong cluster (Load Based Scaling).
Changes the various LoadBasedAdjustmentServices to not use instance variables, which otherwise get clobbered by multiple threads dealing with different clusters.

CB-20679 Periscope can end up executing a scale operation against the

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/rotatepassword/RotateSaltPasswordActions.java
core/src/main/java/com/sequenceiq/cloudbreak/job/salt/StackSaltStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/RotateSaltPasswordHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/salt/RotateSaltPasswordService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/salt/RotateSaltPasswordTriggerService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/salt/RotateSaltPasswordValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/salt/SaltPasswordStatusService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/test/java/com/sequenceiq/cloudbreak/job/salt/StackSaltStatusCheckerJobTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/RotateSaltPasswordHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/SaltPasswordStatusServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/salt/RotateSaltPasswordTriggerServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/salt/RotateSaltPasswordValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/service/SdxDeleteService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/SdxDeleteServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

2 cases are handled:
```
lowLogsToListDiagnosticsCollectionResponseConverter (field private com.sequenceiq.flow.core.config.FlowProgressHolder com.sequenceiq.cloudbreak.converter.v4.diagnostics.FlowLogsToListDiagnosticsCollectionResponseConverter.flowProgressHolder)
┌─────┐
flowProgressHolder defined in URL [jar:file:/cloudbreak.jar!/BOOT-INF/lib/flow-2.67.0-b102.jar!/com/sequenceiq/flow/core/config/FlowProgressHolder.class]
↑ ↓
rotateSaltPasswordFlowConfig
↑ ↓
rotateSaltPasswordActions (field private com.sequenceiq.cloudbreak.service.RotateSaltPasswordService com.sequenceiq.cloudbreak.core.flow2.cluster.salt.rotatepassword.RotateSaltPasswordActions.rotateSaltPasswordService)
↑ ↓
rotateSaltPasswordService (field private com.sequenceiq.cloudbreak.core.flow2.service.ReactorFlowManager …
```

CB-20411 Remove more circular dependency

---

common-model/src/main/java/com/sequenceiq/common/api/type/InstanceGroupName.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperations.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeService.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/DatalakeUpgradeActions.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeService.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/OrderedOSUpgradeRequestProvider.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/OrderedOSUpgradeRequestProviderTest.java

There is a new API where you have to tell the order of the instances to be replaced with a new OS. In case of Rolling Upgrade

CB-20071: Use the Rolling OS API in case of Rolling Upgrade

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsPlatformResources.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsPlatformResourcesTest.java

When we do listkeys/list aliases AWS call we are ignoring the paginated results which is causing key not found exception when the particular AWS account have more than 50 keys and the key referred or used is at the end of the alphabetic ordered results retrieved i.e part of the later pages. In order to avoid this issue we should check if the results retrieved have more number of pages and If yes we should read all the keys from the paginated list. Checked this by creating 52 keys in an account and trying to create an Env with the last key in the list.

CB-19535:Handle Paginated AWS kms keys in list keys and list alias call

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/common-install.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/templates/ipa-ext.conf

On RH8 we have newer FreeIPA which has a different behavior and forbids requests from different networks by default. Issue explained https://access.redhat.com/solutions/5753431 and in jira
Solution is to restore the previous behavior by the solution suggested by RedHat portal.

CB-20678 Allow DNS request from different networks for FreeIPA on RH8

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerConfigService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/ClusterUpgradeValidationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/event/ClusterUpgradeServiceValidationEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeServiceValidationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/FlinkUpgradeValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/ServiceUpgradeValidationRequest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/ActiveCommandsValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/FlinkUpgradeValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/NifiUpgradeValidatorTest.java

In 7.2.16, there is no longer a STREAMING_SQL_CONSOLE role, its functionality is included in STREAMING_SQL_ENGINE. This role needs to be removed manually when upgrading a cluster with the Flink service to 7.2.16

CB-20669 Added upgrade validation for Flink

---

autoscale/src/main/java/com/sequenceiq/periscope/PeriscopeApplication.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/ConsumptionApplication.java
common/src/main/java/com/sequenceiq/cloudbreak/certificate/PkiUtil.java
common/src/main/java/com/sequenceiq/cloudbreak/util/OpenSSLLoaderUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/CloudbreakApplication.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java
datalake/src/main/java/com/sequenceiq/datalake/DatalakeApplication.java
docker-autoscale/Dockerfile
docker-cloudbreak/Dockerfile
docker-consumption/Dockerfile
docker-datalake/Dockerfile
docker-environment/Dockerfile
docker-freeipa/Dockerfile
docker-redbeams/Dockerfile
environment/src/main/java/com/sequenceiq/environment/EnvironmentApplication.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/KeystoreUtils.java
freeipa/src/main/java/com/sequenceiq/freeipa/FreeIpaApplication.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java
redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsApplication.java
redbeams/src/main/java/com/sequenceiq/redbeams/configuration/AppConfig.java

Move to OpenSSL provider on non gov/fips environment so our code and operation can behave the same.
On FIPS enabled envs OpenSSL is enforced, and the apps wouldn't start if cannot be loaded. On other envs if OpenSSL is not available then falling back to default JDK provider.

CB-20332 Remove bouncycastle as security provider

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java

Latest GOV-Dev API E2E tests are failing, because of FreeIpa deployment requests are only allowed with at least '2' instance(s) by group. The requested value was '1'. So we should assure GOV E2E tests are starting FreeIPA at least with 2 instances by group.

CB-20412 [API E2E GOV] FreeIpa deployment requests are only allowed with at least '2' instance(s) by group

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/util/AwsIamService.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/util/AwsIamServiceTest.java

JIRA: [CB-20813](https://jira.cloudera.com/browse/CB-20813) 
**Root cause:** The location passed in already ended with "/" and the template has a "/" as well, resulting in double slashes. 
**Solution:** For backup/restore, If the location passed in ends with "/", we will remove that "/". 
**Before:**
**After:** (The new line formatting issue will be handled by [CDPSDX-3700](https://jira.cloudera.com/browse/CDPSDX-3700) since the fix is in TH.

CB-20813 Fix the double slashes issue for permission precheck failure message

---

environment/build.gradle
environment/src/main/java/com/sequenceiq/environment/environment/flow/start/handler/SynchronizeUsersHandler.java
environment/src/main/resources/application.yml
environment/src/test/java/com/sequenceiq/environment/environment/flow/start/handler/SynchronizeUsersHandlerTest.java
freeipa/src/main/resources/application.yml
wiam-connector/src/main/java/com/sequenceiq/cloudbreak/wiam/client/GrpcWiamClient.java
wiam-connector/src/main/java/com/sequenceiq/cloudbreak/wiam/client/WiamClient.java

- when `WORKLOAD_IAM_USERSYNC_ROUTING` entitlement is enabled the usersync would be initiated through a WIAM call
- added WIAM client to env service
- set grpc timeout for WIAM client

CB-20429 Call WIAM for usersync on environment start

---

autoscale/src/main/java/com/sequenceiq/periscope/service/PeriscopeMetricService.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/configuration/metrics/ConsumptionMetricService.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobService.java
common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/AbstractMetricService.java
common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/CommonMetricService.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/JobSchedulerService.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/cleanup/service/UMSCleanupJobService.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/JobCountMetricConfigurator.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/JobMetricsListener.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/SchedulerMetricsListener.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/TriggerMetricsListener.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/saltstatuschecker/SaltStatusCheckerJobService.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/statuschecker/service/StatusCheckerJobService.java
core/src/main/java/com/sequenceiq/cloudbreak/job/instancemetadata/ArchiveInstanceMetaDataJobService.java
core/src/main/java/com/sequenceiq/cloudbreak/job/nodestatus/NodeStatusCheckerJobService.java
core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJobService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/metrics/CloudbreakMetricService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/job/StructuredSynchronizerJobService.java
datalake/src/main/java/com/sequenceiq/datalake/metric/SdxMetricService.java
environment/src/main/java/com/sequenceiq/environment/metrics/EnvironmentMetricService.java
environment/src/test/java/com/sequenceiq/environment/service/integration/CredentialExperienceTest.java
flow/src/main/java/com/sequenceiq/flow/cleanup/FlowCleanupJobService.java
flow/src/test/java/com/sequenceiq/flow/reactor/ContextClosedEventHandlerTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/metrics/FreeIpaMetricService.java
freeipa/src/main/java/com/sequenceiq/freeipa/nodestatus/NodeStatusJobService.java
redbeams/src/main/java/com/sequenceiq/redbeams/metrics/RedbeamsMetricService.java

The use of service specific prefixes makes it very cumbersome to handle metrics in Prometheus and Datadog.
- Common metric service added
- Prefixed metric services marked as @Primary to preserve the original behavior
- Quartz related metrics are handled by both  (prefixed and non-prefixed) metric services on a temporary basis until Prometheus rules and Datadog dashboards/monitors use the new metrics
- Fixed the quartz_job_count metric initalization

CB-20494 Create metrics without service specific prefixes

---

mock-thunderhead/src/main/resources/application.yml

This is to unblock E2E tests until the proper fix can be found for [CB-20838](https://jira.cloudera.com/browse/CB-20838).

CB-20838 Disable DB SSL entitlement in mock-thunderhead temporarily

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/AzureNetworkV4Parameters.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AzureEnvironmentNetworkConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/loadbalancer/LoadBalancerConfigService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4Converter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AzureEnvironmentNetworkConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/loadbalancer/LoadBalancerConfigServiceTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4ConverterTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/EnvironmentNetworkAzureParams.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/AzureNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/AzureEnvironmentNetworkConverter.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverterTest.java
structuredevent-model/src/main/java/com/sequenceiq/environment/network/dto/AzureParams.java

Context: Azure outbound load balancer should be created by default if the network is new and shouldn't be created if the network already exists. In both cases, the user can change this behavior.
Test:
Create new environments and check with CLI describe-datalake the number and types of the load balancer created.
Request with existing network:
`{
"name": "env-az-ex-net",
"credentialName": "rod-local-cred",
"regions": ["West US 2"],
"location": {
"name": "West US 2"
},
"network": {
"subnetIds": ["sdx-daily.internal.0.westus2"],
"serviceEndpointCreation": "ENABLED",
"publicEndpointAccessGateway": "DISABLED",
"azure": {
"networkId": "sdx-daily",
"resourceGroupName": "sdx-daily",
"noPublicIp": true
}
},
"telemetry": {
"logging": {
"storageLocation": …

CB-20718 Outbound Load Balancer is created by default on new networks only

---

mock-thunderhead/src/main/resources/application.yml
orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/create_embeddeddb_certificate.sh

* The embedded DB cert CSR has been changed as follows:
* The subject is the hostname.
* The FQDN is added as a SAN.
* The above change implies that clients connecting to the embedded DB using SSL must be able to interpret & consider the SAN correctly.
* Undo #14276 in order to re-enable `auth.mock.database.wire.encryption.enable` in `mock-thunderhead`. This basically enables entitlement `CDP_CB_DATABASE_WIRE_ENCRYPTION` that controls SSL for the DL DB (external & embedded).
* Testing: Manual test of embedded DB on DH with multiple cluster templates and different cluster name lengths, including the case when the cluster name is of maximal length (40 chars long).

CB-20838 Fix embedded DB cert subject for long FQDNs

---

core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJobTest.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusIntegrationTest.java
environment/build.gradle
flow/src/main/java/com/sequenceiq/flow/core/FlowLogService.java
flow/src/main/java/com/sequenceiq/flow/repository/FlowLogRepository.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java
integration-test/scripts/config-ums.sh
integration-test/scripts/create-cloudbreak-context.sh

When we do a status check, we will query the latest flow log end time, and if it is not older than 2 minutes, we will skip the status check. It will help in cases like the following: we did a CM management restart service, and the CM operation finished, but the services not properly started, and they need a few more seconds to start properly.

CB-20884 add a skip window for core statuschecker to avoid CM related issues

---

environment/src/main/java/com/sequenceiq/environment/EnvironmentHaApplication.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/repository/EnvironmentRepository.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentServiceTest.java

With the changes Environment service was able to pick up an abandoned flow:
```
select 
fl.id,
fl.finalized, 
fl.cloudbreaknodeid, 
fl.statestatus,
fl.currentstate,
fl.endtime,
fl.created
from flowlog fl where fl.flowid = 'bd43a6d4-93ac-41f5-8a2f-dbc4956f1a7e'
order by fl.created;
id  | finalized | cloudbreaknodeid | statestatus |                         currentstate                         |    endtime    |    created    
-----+-----------+------------------+-------------+--------------------------------------------------------------+---------------+---------------
204 | t         | 18e6237b-node1   | SUCCESSFUL  | INIT_STATE                                                   | 1676382403047 | 1676382402165
205 | t         | 18e6237b-node1   | SUCCESSFUL  | …
```

CB-20824 eliminate unnecessary DTO conversions from HeartbeatService related Environment service's calls

---

core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJobTest.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusIntegrationTest.java
environment/build.gradle
flow/src/main/java/com/sequenceiq/flow/core/FlowLogService.java
flow/src/main/java/com/sequenceiq/flow/repository/FlowLogRepository.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java
integration-test/scripts/config-ums.sh
integration-test/scripts/create-cloudbreak-context.sh

Reverts hortonworks/cloudbreak#14291
failed real-ums-test
```Replacing UMS_HOST in profile file
+ sed -i '/export UMS_HOST/d' ./integcb/Profile
+ sed -i '/export UMS_PORT/d' ./integcb/Profile
+ update-cb-profile
+ echo 'export UMS_HOST=usermanagement-internal.eu-1.cdp.mow-dev.cloudera.com'
+ echo 'export UMS_PORT=80'
+ sed -i '/^export CB_JAVA_OPTS/ s/$/ -Daltus.ums.rights.cache.seconds.ttl=5 -Drest.debug=true -Dmock.spi.endpoint=https\:\/\/test\:9443\//' Profile
sed: can't read Profile: No such file or directory
make: *** [config-ums] Error 2
Build step 'Execute shell' marked build as failure```

Revert "CB-20884 add a skip window for core statuschecker to avoid CM related issues"

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxNotificationService.java

Jira: https://jira.cloudera.com/browse/CB-20442
Simply modified the logic within the status checker job to use the SDX cluster's account ID for the status updates.
Note that this is not an issue our team introduced especially not in any period in the last few months. Seems to me like either something in CB changed or we modified how we track these exceptions making them more present. Note also that the basic functionality of the status checker job is still correct even with this issue. This is just ensuring that we do not throw an exception every time the updates are called.
Testing:
- Verify that issue exists without this fix by stopping a DL's nodes on the cloud provider so as to make the status checker job set it to unreachable
- Verify that the issue no longer exists with this fix by …

CB-20442: Fixed SDX status checker job status update issues.

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreService.java

Context: Permission denied on files were displayed and logged as "Flow is unknown state".
Tests:
Removed the `/etc/sssd/sssd.conf` file from CM master and turned the folder immutable (chattr +i /etc/sssd/s).
Start a datalake backup `cdp datalake backup-datalake --datalake-name rod-dl-aws-1`.

CB-20808 Improve log messages for unknown status and update failed

---

cloud-azure/src/main/resources/templates/arm-dbstack.ftl

We are seeing test case failures due to hard coded deployment name for "addAccessPolicy". Changed that to contain the dbservername so that every deployment will have a unique name and does not conflict when multiple environments were triggered at the same time. Screenwhot from azure console below:

CB-20479:Change the deployment name "addaccesspolicy" to unique name

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractMinimalTest.java

In case we want run an E2E test in IDEA with the IDEA Play option, we are getting error: `Acquiring key testlabel, but no result has found.` So as a workaround in this special case, I'm going to introduce the `testlabel` to Test Project's Test Parameter map as well.

CB-20895 Workaround for Mapped Diagnostic Context issue with IDEA E2E test run

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractMinimalTest.java

`TestParameter` class has been [moved to Util package](https://github.com/hortonworks/cloudbreak/pull/14298). So the out-of-date imports need to be updated.

CB-20895 TestParameter import update

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerFrontend.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerMetadataCollector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerModelBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureMetadataCollector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/resources/templates/arm-v2.ftl
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerMetadataCollectorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerModelBuilderTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureMetadataCollectorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtilsTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AzureEnvironmentNetworkConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/EnvironmentBaseNetworkConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/loadbalancer/LoadBalancerFqdnUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AzureEnvironmentNetworkConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/loadbalancer/LoadBalancerFqdnUtilTest.java
orchestrator-salt/src/main/resources/salt/salt/gateway/floating_ip_loadbalancer.sls
orchestrator-salt/src/main/resources/salt/salt/top.sls

In the case of Azure, if a secondary load balancer would be needed, just create the first and only private but add a secondary frontend IP configuration, using the targeted subnet from the environment request, and set the load balancing rules for both the two frontend IP configurations to enable Floating IP, also using the same frontend-backend port pair, backend pool and health probe.
VM OS level configuration is also needed for the loopback net interface

CB-18949 Targeting Subnets for Load Balancers in Azure

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/FreeIpaInstanceUtil.java

`testCreateDistroXWithEncryptedVolumes` is failing at the latest GOV API E2E with: `NullPointerException` at `FreeIpaInstanceUtil.getInstanceIds`, because of MASTER instance group contains 2 nodes with master0 name. So the related filter should be changed from `instanceGroup.getName().equals` to `instanceGroup.getName().contains`.

CB-20957 [API E2E] GOV E2E find MASTER InstanceIds is failing

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/RecipeUtil.java

`testCreateStopStartRepairFreeIpaWithTwoInstances` is failing at the latest GOV API E2E with: `The specified bucket does not exist`, because of the `cloudbreak-test` base location is for Cloudera AWS. However the Cloudera GOV AWS base location is: `cloudbreak-gov-dev-test`. So we should introduce `INTEGRATIONTEST_AWS_CLOUDSTORAGE_BASELOCATION` environment variable to the Pre Termination recipe script.

CB-20958 [API E2E] GOV E2E Pre Termination test recipe is failing at Cloud Storage Base Location

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/AvailabilityInfo.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/AvailabilityType.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/operation/model/OperationType.java
freeipa-api/src/test/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/AvailabilityTypeTest.java
freeipa-api/src/test/java/com/sequenceiq/freeipa/api/v1/operation/model/OperationTypeTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/upscale/action/FreeIpaUpscaleActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingValidationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/RepairInstancesService.java
freeipa/src/main/resources/application.yml
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingValidationServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/RepairInstancesServiceTest.java

During freeipa upgrade an error happened, because of which 4 nodes remained. Using downscale from 4 nodes was not possible, however, as mapping 4 nodes to AvailabilityType was not possible, as the 4 node state was meant to be temporary.
The present commit thus adds an error handling scenario: it introduces a new state, TEMPORARY_FOUR_NODE_BASED, for the case when the freeipa ends up having 4 nodes. It is now possible to downscale to HA. A downscale to TWO_NODE_BASED system is not allowed, as this is an error fixing scenario and let's allow only the smallests change to the system. Once the customer is back to HA, and also replication agreements are ok, he can separately decide to go downscale to 2 nodes.
The present commit also adds numerous log lines to repair.
See detailed description in …

CB-20500 Freeipa downscale failed from 4 nodes

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxDescribeInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentModifyProxyConfigAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/CBAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/proxy/ProxyConfigAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/proxy/ProxyConfigCmAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/proxy/ProxyConfigFileAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/proxy/ProxyConfigUserDataAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/EnvironmentTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/config/ProxyConfigProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/proxy/ProxyTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/DatalakeCcmUpgradeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/proxy/ModifyProxyConfigE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazoncf/action/CfClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/ClouderaManagerUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/action/ClouderaManagerClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshProxyActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshSaltPasswordActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/client/SshJClient.java
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/salt-password-rotation-tests.yaml

The test is ran as part of aws, azure and gcp testsuites. Test steps:
- Create an environment without proxy
- Add proxy
- Check proxy settings of FreeIpa nodes
- Create a Datalake
- Check proxy settings of Datalake nodes
- Modify to another proxy
- Check proxy settings of FreeIpa and Datalake nodes
- Create a Datahub
- Check proxy settings on Datahub
- Remove proxy
- Check proxy settings on Freeipa, Datalake and Datahub nodes
Proxy setting check steps:
- Check contents of /etc/cdp/proxy.env file on nodes
- Check proxy config in userdata in AWS CF stacks
- In case of Datalake/Datahub, check CM proxy settings
Additional changes:
- Helper methods to re-use existing clusters while testing locally to speed up development
- Unification of proxy and rotate salt password test suites
See detailed …

CB-18490 Modify proxy config e2e test

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/knoxsso.xml.j2

**Problem:**
Due to some changes in how Knox cookies are handled Public cloud UI have stopped working (7.2.17). This is the JIRA that contains the details [CB-20921](https://jira.cloudera.com/browse/CB-20921). In a nutshell `hadoop-jwt` cookie samesite property was changed from `None` to `Strict` to prevent Cross-Site Script Inclusion attacks [ENGESC-16602](https://jira.cloudera.com/browse/ENGESC-16602). This change breaks the SSO flow. 
**What is fixed:**
Here we are updating knoxsso topology to change the samesite property to `Lax`  using configuration `knoxsso.cookie.samesite`.
**How as this tested:**
This change was tested on a public cloud cluster. Runtime: 7.2.17-1.cdh7.2.17.p0.37723226  CB: 2.68.0-b108
// Edit to see if this triggers tests

CB-20921 - [Knox] Update samesite=lax for hadoop-jwt cookie

---

freeipa/src/main/resources/freeipa-salt/salt/nginx/conf/ssl.conf
orchestrator-salt/src/main/resources/salt/salt/nginx/conf/clouderamanager-ssl-user-facing.conf

In order to ease investigation of long requests, nginx should log how long did it take to process a request. Currently only the timestamp is logged when the response was sent to the client.
```
$request_time
request processing time in seconds with a milliseconds resolution; time elapsed between the first bytes were read from the client and the log write after the last bytes were sent to the client
```
From: http://nginx.org/en/docs/http/ngx_http_log_module.html

CB-21036 Add `request_time` to nginx access logging

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePrivateDnsZoneDescriptor.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePrivateDnsZoneRegistrationEnum.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePrivateDnsZoneServiceEnum.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/AzureExistingPrivateDnsZoneValidatorService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/AzurePrivateDnsZoneMatcherService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/AzurePrivateDnsZoneValidatorService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePrivateDnsZoneRegistrationEnumTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePrivateDnsZoneServiceEnumTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/AzureExistingPrivateDnsZoneValidatorServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/AzurePrivateDnsZoneMatcherServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/AzurePrivateDnsZoneValidatorServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/privatedns/PrivateDnsZoneValidationTestConstants.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzureExistingPrivateDnsZonesService.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzurePrivateEndpointValidator.java
environment/src/main/java/com/sequenceiq/environment/network/service/NetworkCreationRequestFactory.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/azure/AzureExistingPrivateDnsZonesServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/azure/AzurePrivateEndpointValidatorTest.java

It is possible to register an Azure AKS private DNS zone to environment service. It is not used by cloudbreak, but environment services is used as the info source on the AKS private DNS zone. The current commit introduces some basic validations for the DNS zone:
- does it name match that of the AKS
- does it exist
- is it connected to the VNET passed to the environment
Note, that some parts of an Azure AKS DNS zone name, unlike that of the Postgres, are variable:
- have a region in their name
- can have a subzone
That is, instead of exact name matching, now a regex matching is used. The original code was refactored accordingly. The regex for a subzone was compiled via testing the Azure UI. Testing was done via curl commands and adding unit tests.
Correction: the original implementation …

CB-19624 AKS private DNS zone - validations, corrected

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/InternalUpgradeSettings.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePreconditionService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperations.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePreconditionServiceTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperationsTest.java

When we initiate a rolling upgrade it should skip the Data Hub validation. This means that we don't need to stop the Data Hub clusters to upgrade the Data Lake.

CB-20836: Datalake rolling upgrade should skip the DataHub validation

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/modify/proxy/handler/EnvProxyModificationRevertAssociationHandler.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/modify/proxy/handler/EnvProxyModificationRevertAssociationHandlerTest.java
orchestrator-salt/src/main/resources/salt-common/salt/modifyproxy/init.sls

The /etc/jumpgate/config.toml file is only present on FreeIPA nodes, so the ccmv2_setup_jumpgate_proxy file.replace should be ignored if the file does not exist. Additionally, the proxy config revert failed if there was no previous proxy config so a null check was added.

CB-21058 Fix proxy config modification for CCMV2_JUMPGATE Data Lakes

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperations.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperationsTest.java

In this commit, I added an extra null check when we marked the prepared upgrade candidates.

CB-20995: Do not set prepared images when the upgrade candidates object is null

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilder.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilderTest.java

There is a serious issue on Azure. Bence Hegyi  found us today, and he noticed during an upscale that we randomly detached a disk from another machine in the group. At first, I looked at it incredulously, but I found the cause, and unfortunately, it's a real problem. Situation: someone starts a cluster with 5 workers. The following machines come up: stackname-w-0, stackname-w-1, stackname-w-2, stackname-w-3, stackname-w-4, and the following volume sets come up: stackname-w-3, stackname-w-1, stackname-w-4, stackname-w-0, stackname-w-2. I wrote this order because even though the private ID is in the disk name, we don't care what it is because we randomly attach it to the machines and then push the FQDN to the disk. So the stack is created, a week goes by, and the customer says they only …

CB-21074 Add timestamp to the hashed part of the volume name generation on Azure

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/das/DasConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/das/DasConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/RdsView.java
template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/views/RdsViewTest.java

* Add DB SSL configs to DAS and Query Processor service configs if needed.
* Prerequisite: CM >= 7.9.2.
* Fix various typos and other code clean-up.
* Testing:
* Manual test with a Data Engineering DH in a commercial AWS region.
* Added new UT & adapted existing ones.

CB-19948,CB-19955 Implement SSL for DAS and Query Processor DB

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java

A .withType() call from a CloudResource builder was accidentally removed. This needs an immediate fix as no GCP environment can be created as of now.

CB-21118 NPE in GcpAttachedDiskResourceBuilder

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxUpgradeRecoveryTests.java

Added `archive.cloudera.com` to the faked repository urls to handle the prod image catalog based tests.

CB-21126 - [E2E] Recovery test does not work with prod image catalog

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java

Added the -cp option to indicate the cloud provider to CM server file.
The screenshot shared below is from the file /etc/default/cloudera-scm-server file
Before the change:
After the change :
`CMF_SERVER_ARGS="-i /etc/cloudera-scm-server/cm.settings -cp  AWS -env PUBLIC_CLOUD"`

CB-16136:Add cloud provider type to cm settings

---

datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/converter/DatalakeDataInfoJsonToObjectConverter.java
datalake-dr-connector/src/test/java/com/sequenceiq/cloudbreak/datalakedr/converter/DatalakeDataInfoJsonToObjectConverterTest.java
orchestrator-salt/src/main/resources/salt/salt/datalake_metrics/get_free_space/get_free_space.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh

value returned by Salt script is in 1024-byte blocks, we should convert it to bytes to match the property name meaning.
Testing:
- manual run on the AWS instance - from the salt command specification: `/usr/bin/df --block-size=1024 --exclude-type=tmpfs  --exclude-type=devtmpfs -P -l|grep " /$"|sed 's/  */ /g'|cut -f 4 -d ' '|sed -E 's/(.*)/"freeSpace":\1/g'`
- run as part of the backup flow

CDPSDX-3919 Convert disk blocks to bytes while checking disk

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java

During upscale and repair when provisioning replicas, only a single instance should be installing freeipa replica. This is how it works during provisioning, so it makes sense to work the same way during repair and upscale. Also we have seen an issue where salt retry mechanism couldn't detect the failure of one instance as the other was still doing the installation for a long time.

CB-21051 Freeipa should upscale with 1 node at a time

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigServiceSSLSaltConfigTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigServiceTest.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/start.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/settings.sls

* When having a DB with SSL enforcement (embedded or external DB), use SSL JDBC options when creating CM DB schema in Salt.
* Prerequisites: CM >= 7.9.2 (specifically, at least 7.9.2-b98 / GBN 37940714 as stated in [OPSAPS-54579](https://jira.cloudera.com/browse/OPSAPS-54579)).
* When prerequisites are met, `scm_prepare_database.sh` will be invoked with 2 extra options: `-s` and `-j`. The latter will include the complete JDBC connection string including explicit SSL options. At the moment, this means `sslmode=verify-full` (i.e. DB server cert and host name verification) and `sslrootcert=/hadoopfs/fs1/database-cacerts/certs.pem` .
* Otherwise, `scm_prepare_database.sh` will be invoked as before, and `/etc/cloudera-scm-server/db.properties` will be still updated manually with the Hibernate …

CB-11269 SSL for CM schema creation

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java

During cleanup if find calls doesn't return every item it can miss cleaning up records in the LDAP.

CB-21176 Add unlimited flags to FreeIPA find calls

---

core/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-spark3-ha.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-rt-data-mart-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-data-engineering-spark3-ha.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-rt-data-mart-spark3.bp
core/src/main/resources/defaults/clustertemplates/7.2.16/aws/dataengineering-spark3-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.16/aws/rt-datamart-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.16/aws_gov/dataengineering-spark3-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.16/aws_gov/rt-datamart-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.16/azure/dataengineering-spark3-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.16/azure/rt-datamart-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.16/gcp/dataengineering-spark3-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.16/gcp/rt-datamart-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.16/yarn/dataengineering-spark3-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.16/yarn/rt-datamart-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.17/aws/dataengineering-spark3-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.17/aws/rt-datamart-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.17/aws_gov/dataengineering-spark3-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.17/aws_gov/rt-datamart-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.17/azure/dataengineering-spark3-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.17/azure/rt-datamart-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.17/gcp/dataengineering-spark3-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.17/gcp/rt-datamart-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.17/yarn/dataengineering-spark3-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.17/yarn/rt-datamart-spark3.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

Spark2 templates will be marked as deprecated in 7.2.17, all Spark3
templates have to be in sync with the Spark2 ones
Main changes:
Added these new templates:
7.2.17 - Data Engineering: HA: Apache Spark3, Apache Hive, Apache Oozie
7.2.17 - Real-time Data Mart: Apache Impala, Hue, Apache Kudu, Apache Spark3
7.2.16 - Data Engineering: HA: Apache Spark3, Apache Hive, Apache Oozie
7.2.16 - Real-time Data Mart: Apache Impala, Hue, Apache Kudu, Apache Spark3
Synced these templates:
7.2.17:  cdp-data-engineering-spark3.bp vs. cdp-data-engineering.bp (7.2.17 - Data Engineering Spark3)
7.2.16:  cdp-data-engineering-spark3.bp vs. cdp-data-engineering.bp (7.2.16 - Data Engineering Spark3)

CB-20852: Create all Spark3 datahub cluster templates which are necessary for Spark2 deprecation

---

cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/loadbalancer/service/component/YarnLoadBalancerComponentFactoryService.java

Jira: https://jira.cloudera.com/browse/CB-20899
Simply updates the image used for the Yarn LB. The old image for DEHA is fine as is for now, we are moreso focused on the DL. This is specifically to update it with recent changes I made to the image configuration to increase its timeouts and max connections.
We want this on 2.69 as that is where the current testing is being done and failing. This is of high priority for the QE team.
Let me know if any more info is needed.

CB-20899: Updating Yarn LB image to use new one with better timeout/connection handling.

---

environment/src/main/java/com/sequenceiq/environment/network/v1/converter/EnvironmentBaseNetworkConverter.java

setDefaultDeploymentRestrictionsForEndpointAccessGateway got a `null` value which has the root cause: the `endpointgatewaysubnetmeta` column in `environment_network` table contains the literal string "null" for older environments that is converted to a `null` map instead of an empty map.

CB-21266 Fix NPE in EnvironmentBaseNetworkConverter

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/SssdConfigProvider.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/SssdConfigProviderTest.java
orchestrator-salt/src/main/resources/salt/salt/sssd/template/sssd-ipa.j2

SSSD enumeration takes more time as the number of users/groups increases. At some point the sssd watchdog will assume that enumeration is stuck and kill the process. Enumeration will begin again, but will consistently be killed by the watchdog. The new value will be 60sec.
```
Options usable in SERVICE and DOMAIN sections
timeout (integer)
Timeout in seconds between heartbeats for this service. This is used to ensure that the process is alive and
capable of answering requests. Note that after three missed heartbeats the process will terminate itself.
Default: 10
```

CB-21204 Increase SSSD heartbeat timeout to support more users/groups

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/templates/initial-ldap-conf.ldif

Changing `nsslapd-db-deadlock-policy` to `6` which prefers writes against reads. We expect to see a more stable replication, as repliaction requires great number of writes. Config values available here: https://github.com/berkeleydb/libdb/blob/5b7b02ae052442626af54c176335b67ecc613a30/src/dbinc/db.in#L287-L300 
Default value is `9`

CB-21149 Change FreeIPA `nsslapd-db-deadlock-policy`

---

freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncServiceTest.java

In this commit, I introduced some changes to improve the performance of the StackRepository.findByAccountId query.
- I've created a new query for the PasswordService because it does not necessary to retrieve the whole Stack table.
- I've removed the joining of the instanceGroups and instanceMetaData table from the original query.
- Removed some unused queries from the StackRepository

CB-21196: Optimize FreeIPA StackRepository.findByAccountId query

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxDeleteCustomAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxDeleteInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/AbstractE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/java/ForceJavaVersionE2ETest.java

We have a [new validation](https://github.com/hortonworks/cloudbreak/commit/ac48224caeb53c929cac032bdb442c0be18b900f) in our API E2E test project for SafeLogic installation of created resources by [CB-21175](https://jira.cloudera.com/browse/CB-21175).
Unfortunately this test does not take in account some cases where:
1. testCreateDistroXWithEncryptedVolumes where DistroX Delete is part of the test (in case of AWS and GCP)
2. testClusterProvisionWithForcedJavaVersion (test presents only for AWS) `/usr/lib/jvm/java/jre/lib/ext/: No such file or directory`
The validation should be enhanced or skipped for these cases, because of the E2E 2.70.0-b73 is failing. So this is a quick fix for the issue.

CB-21290 Introduce skip logic for SafeLogic Validation in the E2E tests

---

cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/loadbalancer/service/component/YarnLoadBalancerComponentFactoryService.java

Reverts hortonworks/cloudbreak#14494

Revert "CB-20899: Updating Yarn LB image to use new one with better timeout/connection handling."

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java

Context: e2e test for Azure doesn't work without the outbound load balancer. The default for an existing network will be not to create the outbound load balancer and most of the tests are using an existing network. The purpose of this change is to create the outbound LB for default in e2e tests.
Tests:
Run the com.sequenceiq.it.cloudbreak.testcase.e2e.sdx.SdxImagesTests#testSDXWithPrewarmedImageCanBeCreatedSuccessfully for Azure provider.
com.sequenceiq.it.cloudbreak.testcase.e2e.sdx.SdxUpgradeTests#testSDXHAUpgrade
com.sequenceiq.it.cloudbreak.testcase.e2e.sdx.SdxUpgradeTests#testSDXUpgrade
The nooutboundloadbalancer from the environment_network table should be false.
The `cdp datalake describe-datalake --datalake-name` should return the outbound LB.

CB-21302 Azure Outbound Load Balancer created by default for e2e tests

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsCloudWatchService.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchService.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleService.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsCloudWatchServiceTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleServiceTest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsTaggingService.java

Jira: https://jira.cloudera.com/browse/CB-21280
Objective: We want to add all user-defined tags, which are already added to other AWS resources, to the Cloudwatch alarms generated. This will enable us to manage and maintain all of our resources.
I simply added the tags to the cloudwatch generation request.
I was unable to test this locally due to issues with generating environments in master, however the change is very simple. I figured it would be okay to move forward with the PR and we can figure out testing later.

CB-21280: Added tags to cloudwatch alarms when they're provisioned.

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsPlatformResources.java

In this commit I've removed the following objects from the PlatformSecurityGroupResponse
- description
- ipPermissions
- ipPermissionsEgress
The ipPermissions and ipPermissionsEgress are using a non-serializable Class from AWS SDK v2. Then I removed them from the response because we're not using these properties anywhere.

CB-21323: Remove unnecessary response objects from PlatformSecurityGroupResponse

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/BootstrapParams.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java

Configure salt master worker threads during. The motivation is to add more threads to salt master for better performance on bigger instances. This takes effect during cluster creation or during node repair when the user repairs the node where salt master is running.

CB-21089 Configure salt master worker threads

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/model/PackageInfo.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/model/PackageInfoValidationResult.java
common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmServerQueryService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmVersionQueryService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmVersionQueryServiceTest.java

This commit contains the following CM package version sync enhancements:
- indicating the unreachable nodes in the event history
- removing the invalid package versions from the result set

CB-21293 - Better error reporting in CM package version sync

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureInstanceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtilsTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXStopStartScaleTest.java

- start/stopWithLimitedRetry are versions of instance start/stop where it limits the retries that the operation may perform normally.
- If the instances are not started/stopped in the given time than we update the instance state as unknown.

CB-18055 Implement start/StopWithLimitedRetry for Azure

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxExternalDatabaseConfigurer.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxExternalDatabaseConfigurerTest.java
redbeams/src/main/resources/application.yml

In this commit I set the default database engine version to 11 and modified the database config provider to use the database engine version and the availability type from the internal database request if present

CB-21242: Sdx external database configuration provider should use the internal database request as well

---

cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/loadbalancer/service/component/YarnLoadBalancerComponentFactoryService.java

Jira: https://jira.cloudera.com/browse/CB-20899
This is the updated image which has already been manually tested on YCloud clusters by the QE team. Previously this was on 2.69 but was reverted due to issues with the YCloud docker version. For now I am pointing this at 2.70.

CB-20899: Updating Yarn LB image to use new one with better timeout/connection handling. Updating version to fixed image.

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleService.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleServiceTest.java

We described 2 instances, both were terminated long time ago, but somehow the describe threw exception for 1 instance only. So we tried to terminate the other instance that was not in the exception message, but the termination fails because the instance were removed a long time ago and the instance ID was not known by AWS.

CB-21337 try to terminate instances in multiple rounds on AWS if InvalidInstanceID.NotFound received from AWS

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaOperationDescriptions.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/AvailabilityInfo.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/scale/DownscaleRequest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/scale/ScaleRequestBase.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/scale/UpscaleRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingValidationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeipaDownscaleNodeCalculatorService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingValidationServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeipaDownscaleNodeCalculatorServiceTest.java

Currently freeipa resize takes an AVAILABILITY_TYPE as argument. Downscale will then arbitrarily choose a node id. However, sometimes, in troublehooting scenarios it would be great if the user could choose the node to downscale.
The present commit thus adds support to remove exactly the nodes specified in a request.

CB-20662 Downscale should be able to take exact instance id

---

common/src/main/java/com/sequenceiq/cloudbreak/vm/VirtualMachineConfiguration.java
common/src/main/resources/common-config.yml
common/src/test/java/com/sequenceiq/cloudbreak/vm/VirtualMachineConfigurationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/JavaVersionValidatorTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

We can not pass list values from dps-k8s so the property format was changed to a comma separated list that is parsed in the VirtualMachineConfiguration class.

CB-21320 Change vm.supportedJavaVersions property format

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxDescribeInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentModifyProxyConfigAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/CBAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/proxy/ProxyConfigAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/proxy/ProxyConfigCmAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/proxy/ProxyConfigFileAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/proxy/ProxyConfigUserDataAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/EnvironmentTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/config/ProxyConfigProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/proxy/ProxyTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/DatalakeCcmUpgradeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/proxy/ModifyProxyConfigE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazoncf/action/CfClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/ClouderaManagerUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/action/ClouderaManagerClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshProxyActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/client/SshJClient.java
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/salt-password-rotation-tests.yaml

This reverts commit f119772bbc633b9e823d678f504e542da03b74a0.
This commit does not contain changes to the e2e test, but new parameters were added to the test runs that will hopefully fix the original issue: 
- https://github.com/hortonworks/cloudbreak-ansible-playbooks/commit/30a3f1655c2df4b77feb8e1772d9742eaee130ff
- https://github.com/hortonworks/cloudbreak-ansible-playbooks/commit/31409ccc50c695632a145bd3cb9e18aca3e32e26

Revert "Revert "CB-18490 Modify proxy config e2e test""

---

common/src/main/java/com/sequenceiq/cloudbreak/validation/ContentSizeProvider.java
common/src/main/java/com/sequenceiq/cloudbreak/validation/DefaultContentSizeProvider.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/HttpContentSizeValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ImageCatalogValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidHttpContentSize.java
core-api/src/test/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ImageCatalogV4BaseTest.java
core-api/src/test/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ValidatorTestHelper.java
core-api/src/test/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ValidatorTestHelperConfiguration.java
core-api/src/test/java/com/sequenceiq/cloudbreak/validation/HttpContentSizeValidatorTest.java
core/src/main/resources/application.yml

The image catalogs are reaching the original 5 MB limit of our validators. Refactored the limit to an environment variable and increased it to 6 MB.

CB-21403 Content size validation limit increase

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToTemplatePreparationObjectConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackV4RequestToTemplatePreparationObjectConverterTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/Spark3OnYarnRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/general/GeneralClusterConfigsProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/Spark3OnYarnRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/general/GeneralClusterConfigsProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java
template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObjectTest.java

* Partially reverts 79215c7b434115564660b61d73700fd7c818d726 / #14667.
* `GeneralClusterConfigs.variant` is restored to its former meaning, i.e. cluster manager variant.
* Introduce `TemplatePreparationObject.platformVariant`.
* Populated in the respective converters.
* Utilized in config providers when invoking `CMRepositoryVersionUtil.isS3SslChannelModeSupported()`.
* Testing: Added new UT & adapted existing ones, migrating all JUnit 4 ones to JUnit 5.

CB-21417 Fix `GeneralClusterConfigs.variant`

---

autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/PeriscopeMetricService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ha/LeaderElectionService.java
autoscale/src/main/java/com/sequenceiq/periscope/utils/MetricUtils.java
autoscale/src/test/java/com/sequenceiq/periscope/component/MetricTest.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/MetricUtilsTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsValidatorsTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsLaunchTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsRepairTest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsClient.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/metrics/AwsMetricPublisher.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/metrics/AwsMetricTag.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsAuthenticatorTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsInstanceConnectorTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/metrics/AwsMetricPublisherTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsStorageValidatorsTest.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNativeMetadataCollectorApiIntegrationTest.java
common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/AbstractMetricService.java
common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/MetricService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
flow/src/main/java/com/sequenceiq/flow/core/AbstractAction.java
flow/src/main/java/com/sequenceiq/flow/core/FlowRegister.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/service/SecretService.java
secret-engine/src/test/java/com/sequenceiq/cloudbreak/service/secret/service/SecretServiceTest.java

Metrics: aws_api_call_duration_,aws_service_call_duration_, aws_api_call_failed_total, aws_retry_count_total, aws_max_concurrency_total, aws_leased_concurrency_total, aws_pending_concurrency_acquires_total

CB-20513 Create metrics for provider API calls - AWS

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateValidatorAndUpdater.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateValidatorTest.java

CDPSDX-4058; update the template validation to allow the SDX COMPUTE host to does not have  attached volumes.
Some of the additional host groups added with this shape do not need local storage, so we removed the attached disks. This has resulted in validation failure. This change updates the validation to skip certain host groups.

CDPSDX-4058; update the template validation to allow the SDX COMPUTE host

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterShape.java

Jira: https://jira.cloudera.com/browse/CDPSDX-4057
This is meant to modify the name of the new DL shape without breaking the backwards compatibility tests ran on these enum classes. This is why this is pointed at the prod branch.

CDPSDX-4057: Changing the scalable shape enum from SCALABLE to ENTERPRISE. This change only affects the enum.

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandler.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandlerTest.java

This caused a Timeout exception in the promise as the flow progressed towards the next flow step but the same Selector was sent again. This is fixed.

CB-21450 FreeIpaCreationHandler is sending the next step event twice

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/exception/CloudPlatformValidationWarningException.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureImageTermStatus.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureImageTermsSignerService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureImageFormatValidator.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureImageTermsSignerServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureImageFormatValidatorTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/ProvisionValidationHandlerTest.java

This commit validates for the following 3 unhappy cases, marked with "!!":
```
if (CDP_AZURE_IMAGE_MARKETPLACE_ONLY)
if (non-auto)
if (non-accepted)
!!failhard
elif (unknown)
!!warn
else
proceed
if (auto)
if (non-accepted|unknown)
accept
else
proceed
elif (CDP_AZURE_IMAGE_MARKETPLACE)
if (non-auto)
if (non-accepted)
!!fallback to vhd --> warn
elif (unknown)
proceed and fallback if error
else
proceed
if (auto)
if (non-accepted|unknown)
accept
else
proceed
```
Fallback clause does not work due to an independent bug: [CB-21442](https://jira.cloudera.com/browse/CB-21442)

CB-19860,CB-14228 - Validation of terms and permissions at launch

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/scale/DownscaleResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingServiceTest.java

The previous commit with the same id made it possible to specify which freeipa nodes to downscale. The response, however should contain which nodes were then in fact removed. The current commit thus adds the field to the response which nodes were deleted during the downscale.

CB-20662 Downscale should be able to take exact instance id - extension

---

core/src/main/resources/defaults/blueprints/7.2.17/cdp-sdx-enterprise.bp

CB-21467 add Ranger to the Gateway Host group to make sure that the topology.xml will be populated with the Ranger URL.
We will also explore ways to have separate topology.xml defined for the new shape. This will be a separate PR.

CB-21467 add Ranger to the Gatway Host group in enterprise DL

---

common/src/main/java/com/sequenceiq/cloudbreak/common/orchestration/OrchestratorAware.java
core-model/src/main/java/com/sequenceiq/cloudbreak/dto/StackDto.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cmdiagnostics/CmDiagnosticsFlowService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/orchestrator/OrchestratorService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cmdiagnostics/CmDiagnosticsFlowServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/orchestrator/RotateSaltPasswordService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/orchestrator/OrchestratorService.java
freeipa/src/test/java/com/sequenceiq/freeipa/orchestrator/RotateSaltPasswordServiceTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java

Situation:
We have 2 terminated nodes:
hostname=ascend-dev-master1, instance_id=i-0e61aa448ef41d3bb, fqdn=ascend-dev-master1.ascend-d.a8du-8mgv.cloudera.site, domain=ascend-d.a8du-8mgv.cloudera.site, public_address=false, custom_domain=true, instance_type=m5.xlarge hostname=ascend-dev-idbroker1, instance_id=i-0d1d4a9eaba612185, fqdn=ascend-dev-idbroker1.ascend-d.a8du-8mgv.cloudera.site, domain=ascend-d.a8du-8mgv.cloudera.site, public_address=false, custom_domain=true, instance_type=t3.medium We try to repair ascend-dev-master1, but it got the same IP address from Azure as the previous ascend-dev-idbroker instance IP address.
Solution:
When collecting nodes for the orchestrator we will skip nodes which are deleted on provider, so we will not push these hosts' infos in pillar.

CB-21342 Error occurred during salt minion tear down java.lang.IllegalStateException: Duplicate key 10.28.216.147

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleService.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/repair/RepairInstancesRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaStackHealthDetailsService.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java
freeipa/src/test/java/com/sequenceiq/freeipa/sync/StackStatusTest.java

An instance is unusable if it's missing FQDN or private IP, as this is a bare minimum to have a functional instance. If the instance:
- has instance ID, but lack any of FQDN or IP then the state is set to `FAILED`, FreeIPA will be `UNHEALTHY`
- has no instance ID, no FQDN or IP then it's set to TERMINATED, and if everything else is fine FreeIPA will be `HEALTHY`
The `FAILED` isntance is removable with the repair functionality by providing the instance id. To handle the edge case where the instance id is malformed, this error is handled the same way during downscale as if the instance is non existing on AWS side.
Added filtering to `RepairInstancesRequest` to filter out blank instance IDs, as during testing CLI sent in one empty string in the list.
See detailed description in the commit …

CB-21393 FMS status syncer modifications for unusable instances

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsEnsureMachineUserHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/telemetry/TelemetryConfigService.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsEnsureMachineUserHandlerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/telemetry/TelemetryConfigServiceTest.java

"We should make the key type selection based on which type of deployment we have.
On gov environments we can only allow ECDSA.
On commercial clouds we can only support RSA since some components(e.g. telemetry-publisher) can't accept ECDSA.
We should remove the entitlement and substitute it with either a deployment config or we could also check on the crn partition to decide if we are on a gov deployment or not. Or any reliable way to tell if it's a gov env or not will suffice."

CB-21385 We can allow ECDSA only on GOV envs

---

mock-infrastructure/src/main/java/com/sequenceiq/mock/salt/response/JobsLookupJidSaltResponse.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltJobIdTracker.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltEmptyResponseException.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStateService.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStateServiceTest.java

**JIRA:** [CDPSDX-3995](https://jira.cloudera.com/browse/CDPSDX-3995) & [CDPD-50759](https://jira.cloudera.com/browse/CDPD-50759)
**ISSUE:** When we backup a large set of DB data, we dump those data to the local disk. When there's no space in the disk to store that data we should return the backup as failed but we get a successful status. This is caused by salt is not working well when there's no enough space and then it returns an empty response, since the response is empty, we assume there's no error, so we mark it as successful.
**SOLUTION:**  When jobs.lookup_jid  returns an empty response, throws an error, because jobs.lookup_jid should always return something. **[Latest Updates]** However, after we catch the jid empty response exception, we will just mark this job as in progress …

CDPSDX-3995 Throw errors when jobs.lookup_jid returns empty response

---

common-model/src/main/java/com/sequenceiq/common/api/type/InstanceGroupName.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/OrderedOSUpgradeRequestProvider.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/OrderedOSUpgradeRequestProviderTest.java

Context: Enterprise DL has service host groups that should be added to the OS upgrade request when they are present in the stack.
The order of upgrade for these services will be a group of 1 service of each type (SOLRHG, STORAGEHG, KAFKAHG, RAZHG, ATLASHG, HMSHG) at a time.
Test:
Enterprise shape only exists in 7.2.17, to test the upgrade I had to change the checkUpgrade code to force the return of the same image as a candidate to upgrade the OS. 
The service instances were upgraded following the described order.

CB-21356 Handle OS Upgrade Order for Enterprise DL

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupServiceTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/util/BlueprintUtilsTest.java

[CDPSDX-3896](https://jira.cloudera.com/browse/CDPSDX-3896) Move CM MGMT services to AUXILIARY host in case of Enterprise DL. These changes are required to remove the overallocation of the Gateway host groups. This action is harmless based on the CM MGMT services are backend services that will not be hit directly by the services. In other words: the CM and the CM MGMT decouple is harmless because we do not move the CM; therefore, the CM has the required load balancer (s). Tested locally by Enterprise Datalake. The CM MGMT services were deployed to the AUXILIARY host group. The CM was reachable. Also, the SMON and HMON metrics were shown on CM UI. Sidenote: CM and the CM MGMT are not HA. Therefore we do not lose HA capability by this action. Also, this action is not on their roadmap, date: …

CDPSDX-3896 move CM MGMT services to AUXILIARY host in case of Enterprise DL

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderService.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterStartHandlerTest.java
sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/sdx/PaasSdxService.java
sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/sdx/SaasSdxService.java
sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/sdx/SdxService.java

CDPD-43642, increase CM memory threshold on all hosts to 95% in the case of Medium duty Datalake and the EDL.
Our current datalakes have warnings about the memory settings. The default CM memory threshold is 80%. This means if we allocate more than 80% of the available resource. We cannot handle the basic datalake resource. Therefore we pump up the memory threshold to 95%.

CDPD-43642, increase CM memory threshold on all host

---

structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StackDetailsToCDPImageDetailsConverter.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StackDetailsToCDPImageDetailsConverterTest.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToCDPImageDetailsConverter.java
structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToCDPImageDetailsConverterTest.java
usage-collection/src/main/proto/usage.proto

Here is a sample value set of the `imageName`, based on which it can be easily determined if a given cluster is launched with a VHD or an Azure Marketplace image:

CB-21444 - Implement EDH tracking of image name

---

datalake/src/main/resources/duties/7.2.17/aws/enterprise.json
datalake/src/main/resources/duties/7.2.18/aws/enterprise.json

[CB-4086](https://jira.cloudera.com/browse/CB-4086) change the attached volume types to `gp3` from `gp2` in case of enterprise datalake (`EDL`); modified runtimes: `7.2.17`; `7.2.18`

CB-4086 change the attached volume types to gp3 from gp2

---

core/src/main/resources/defaults/blueprints/7.2.17/cdp-sdx-enterprise.bp
core/src/main/resources/defaults/blueprints/7.2.18/cdp-sdx-enterprise.bp

Changed the blueprint for enterprise data lake to hold ranger audits for last 30 days.

CB-21346: Change the TTL for ranger audits to 30 days.

---

gradle.properties

Gradle build is called from the make file therefore we need this to be present in a central place rather than individually providing arguments to each ./gradlew call.

Fix disappearing Gradle daemon with gradle settings

---

integration-test/scripts/docker-compose.sh

From now on nssdb-init-svc will certainly exit before all other service containers, so it must be excluded from the list we check for.

CB-18277 Fix exited containers check in integration test.

---

datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java

The current code restricted rolling upgrade to Mediumduty datalake.

CB-21727: Rolling upgrade is not allowed for Enterprise shape.

---

flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java
flow/src/main/java/com/sequenceiq/flow/core/chain/FlowChains.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowChainLogService.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java

JIRA: [CDPSDX-4064](https://jira.cloudera.com/browse/CDPSDX-4064)
**ISSUE:** We got database backup timeout error on mow-dev -- this only happens a few times. From the dev log in Kibana we can tell the issue is the backup is finished, but the flowchain is still active because the `chainJackson` column in `flowChainLog` is not empty (but it should be empty when backup is done). However we don't know why that column is not empty and what is in there since we don't have enough logging and we can not reproduce this error locally. Therefore, we are adding some logging there which could help us debug next time the issue happens on mow-dev. Also, it would be helpful for future debugging about flow and flowchain handling with logs.
Some log examples (using local test):
`Removing LastTriggerEvent …

CDPSDX-4064 Add logging for flowChain handling

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/datalake/RecipeTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/proxy/ProxyConfigCmAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/ephemeral/DistroXRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/ephemeral/DistroXStopStartTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/ephemeral/DistroXUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/DistroXRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/EnvironmentPrivilegedUserTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/InternalSdxSshAndCmAccessTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxRepairWithRecipeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRecipeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/ClouderaManagerUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/action/ClouderaManagerClientActions.java

Right now we have several classes where we implemented the CM access with the help of `MOCK_UMS_PASSWORD` or getWorkloadPassword:
- DistroXStopStartTest
- DistroXUpgradeTests
- DistroXRepairTests
- AwsYcloudHybridCloudTest
- EnvironmentStopStartTests
and with `getWorkloadUserName`:
- InternalSdxSshAndCmAccessTest
- DistroXRepairTests
in the test project next to the `TextContext`.
So we should collect these classes and move the related implementation to a common place...etc.

CB-21551 API E2E Refactor the MOCK_UMS_PASSWORD with getWorkloadPassword and getWorkloadUserName in the test project

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/util/AwsIamService.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/util/AwsIamServiceTest.java

Reverts https://github.com/hortonworks/cloudbreak/pull/14243
JIRA: https://jira.cloudera.com/browse/CDPSDX-4103
ISSUE: In [CDPSDX-3700](https://jira.cloudera.com/browse/CDPSDX-3700) (PR https://github.com/hortonworks/cloudbreak/pull/14243), to fix the double slash format issue, we introduced the code to always remove the slash at the end of the backup location. If the backup location set up by the user is just "s3://bucket" or "s3://bucket/", the aws-datalake-restore-policy will always have resources "bucket/" and "bucket", without the slash because we remove it, which introduces a bug - when the user only sets up resources in their policy with "bucket/" and "bucket/", they may fail at storage validation because the role has no authorization to "bucket", because the program is using …

Revert "CB-20813 Fix the double slashes issue for permission precheck failure message"

---

orchestrator-salt/src/main/resources/salt/salt/kerberos/config/krb5.conf-existing

The max total time = NUMBER_OF_KDCS x max_retries x kdc_timeout.
Default kdc_timeout is 3 sec.

CB-13850  setup krb5.conf max_retrires=1

---

environment/src/main/java/com/sequenceiq/environment/exception/mapper/JsonParseExceptionMapper.java

The error on prod was about the jackson's own JsonParseException which couldn't be returned in SearchCauseExceptionMapper:41 as BaseExceptionMapper (CastException was thrown).

CB-15423 adding exception mapper to json parse exception which has stronger priority than the mapper of jackson

---

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerMemoryAdjuster.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerMemoryAdjusterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleServiceTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/Memory.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/MemoryInfo.java
orchestrator-api/src/test/java/com/sequenceiq/cloudbreak/orchestrator/model/MemoryTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStateService.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStateServiceTest.java

Adjust Cloudera Manager jvm memory in case of data hub clusters based on the cluster size.
The logic works as follows:
- We get the current memory from /etc/default/cloudera-scm/server config.
- Calculate the required value based on the node count.
- If more memory is needed than the current value then we check the available memory with salt status.meminfo.
- We set CM's memory to min(available memory * 0.25, requiredMemory).
- If the required memory is less than the 25% of the available memory than we send a warning to the user to recommend a vertical scale on master host group.
- If the memory is changed than we restart CM and wait for it to become available.
Data lake clusters are not touched. CM's default 4GB memory starts to cause issues after 400+ node clusters which is not the case …

CB-21447 Adjust Cloudera Manager jvm memory in case of data hub clusters based on the cluster size

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/setup-autotls.sh.j2

In FIPS mode the pkcs11 provider is not configured by default, so it has to be passed as an argument to keytool

CB-21564 Set providerclass for keytool in setup-autotls

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/clusterproxy/reregister/ClusterProxyReRegistrationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/clusterproxy/reregister/ClusterProxyReRegistrationConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/clusterproxy/reregister/ClusterProxyReRegistrationContext.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/clusterproxy/reregister/ClusterProxyReRegistrationEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/clusterproxy/reregister/ClusterProxyReRegistrationState.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/clusterproxy/ClusterProxyReRegistrationTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachActions.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachDetachUtils.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/attach/SdxDetachService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachServiceTest.java

Jira: https://jira.cloudera.com/browse/CDPSDX-4024
We determined that the reason for this failure was that the proxy service was not having its config updated, resulting in it using stale keys (the instance IDs of the medium duty DL which was deleted). 
This change reformats some logic but the main change which solves the issue is that we now run the proxy re registration twice for CCMv1, once with the logic used to remap the MinaSSHd tunneling keys for CCMv1, and the second time for the full re-registration of the proxy service configs.
Due to local issues with CCMv1 port forwarding, I am and will be unable to test this locally. However due to the importance of this fix, and the fact that the issue is causing L0 promotion test failures, I believe we can move forward with the change and …

CDPSDX-4024: Fixed faulty resize recovery for CCMv1 sdx clusters due to missing proxy service config reset.

---

core/src/main/resources/defaults/clustertemplates/7.2.10/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.11/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.12/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.14/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.15/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.16/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.16/aws_gov/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.17/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.17/aws_gov/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.18/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.18/aws_gov/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.8/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.9/aws/dataengineering-spark3.json

This configuration has been already set for Spark2 in 2021 which should fix the HMS OOM memory issues in case of non HA AWS environments

CB-21854: Set m5.4xlarge for the Spark3 AWS master host

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/init.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/update_cnames.sh

Cert are located at a different place on RHEL8 in a file instead of a cert db fot HTTPD. The script has been modified to depend on this file when fetching the cert requiest id on RHEL8.

CB-21868 Add FreeIPA Subject Alt Name On RHEL 8

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpHttpClientConfig.java

This fix is intended to solve the manowar-gov-dev deployment issues of CB services.

CB-21883 load GCP related keystore from google.jks instead of google.p12 to avoid the usage of PBEWithSHA1AndRC2_40 algorithm

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/HostGroupType.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/InstanceCountParameter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractSdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/InstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java
integration-test/src/main/resources/testsuites/e2e/sdx-repair-tests.yaml

Jira: https://jira.cloudera.com/browse/CB-21803
The tests were failing since the default QE image catalog does not have 7.2.17 on it. This change attempts to fix this by specifying a specific image catalog URL to be used for the SDX cluster which does have 7.2.17.

CB-21803: Fixed failing enterprise e2e tests which require specific 7.2.17 image catalog.

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_healthagent_getcerts.sh

It's not needed to use httpd or freeipa server cert and passwd to generate a new certificate, simple self signed certificate is enought the establish connection. 
This way it's not needed to take care about different OSs and cloud providers.

CB-21815 Generate self signed certificate for freeipa-healthagent

---

core/src/main/resources/defaults/blueprints/7.2.17/cdp-sdx-enterprise.bp
core/src/main/resources/defaults/blueprints/7.2.18/cdp-sdx-enterprise.bp

CDPSDX-4027; update the extra host groups, with service-specific, memory allocation
We have to update the memory allocation of the services because the CM rule engine will not update the memory allocation of the extra host group, therefore the default memory options will apply, which means the services run with the minimum memories. That cause that state where the instance has lots of unused memory. 
In some cases, we properly set the memory value of the service in the BP. these values will not be applied to the extra host group because the extra host groups have different configRoleGroup.

CDPSDX-4027; update the extrahostgroups, with service specific, memory

---

core-model/src/main/java/com/sequenceiq/cloudbreak/dto/StackDto.java
core-model/src/test/java/com/sequenceiq/cloudbreak/dto/StackDtoTest.java

I extended the getAllFunctioningNodes with a function which will only return one node for one ip address, even if we have multiple nodes with the same ip address in the database. With this implementation I would like to avoid the situation where a ZOMBIE node is deleted on provider, but a new upscaled node has the same IP address. Without this implementation the getAllFunctioningNodes would return both nodes, which can cause issues at hosts pillar save, because the key is the private IP address and there would be duplicated key.
**IT IS A CHERRY-PICK FROM MASTER**

CB-21796 saveHostsPillar should use getNotDeletedInstanceMetaData instead of getAllFunctioningNodes

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStackViewProvider.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureImageFormatValidator.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnectorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStackViewProviderTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/template/AzureTemplateDeploymentServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureImageFormatValidatorTest.java

CB-21834 Azure datalake upgrade E2E test fails on master with bad request from Azure related to image creation
In case of marketplace -> vhd upgrade without vm replacement, the original marketplace image is stored in instance metadata, but the image in stack will be replaced with the new vhd one.
The fix: In AzureStackViewProvider.getCustomImageNamePerInstance() we will check if the image is marketplace on instance level when we collect instance image names not boased on image name stored in stack.
The fix was tested with marketplace -> vhd upgrade without vm replacement, after it vertical scale, repair, os upgrade is worked, na azure exception has thrown.

CB-21834 Azure datalake upgrade E2E test fails on master with bad request from Azure related to image creation

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/clusterproxy/reregister/ClusterProxyReRegistrationConfig.java

Jira: https://jira.cloudera.com/browse/CB-21952
Flow creation for this process was failing due to the flow manager not being able to find the flow for the event. This was due to me not setting the init event correctly in the config file for the flow. This is a simple change which fixes this.
As for why I did not see this before, I have been unable to test CCMv1 changes locally for a while now, and decided to leave the verification for mow-dev. This is still something I am okay with as long as we move forward quickly and do not block anything.

CB-21952: Added flow initialization event for CCMv1 key remapping to its flow config.

---

redbeams/src/main/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverter.java
redbeams/src/main/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverter.java
redbeams/src/main/java/com/sequenceiq/redbeams/domain/stack/DBStack.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/action/RedbeamsTerminationActions.java
redbeams/src/main/java/com/sequenceiq/redbeams/repository/NetworkRepository.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/network/NetworkBuilderService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/network/NetworkService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsTerminationService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsUpgradeService.java
redbeams/src/main/resources/schema/app/20230515125404_CB-21842_Remove_'network_id_idx'_as_it_duplicates_pkey_index.sql
redbeams/src/test/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverterTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverterTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/domain/stack/DBStackTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/network/NetworkBuilderServiceTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/stack/RedbeamsUpgradeServiceTest.java

Remove entity level connection between `DBStack` and `Network` to avoid join during fetching `DBStack`. This involves:
- using the id from `DBStack` to fetch and delete `Network`
- store the id instead of the entity (this makes the change backward compatible as it is the current state at db level)
- separate saving Network from DBStack
- during termination create a transaction for deleting the 2 together to simulate `orphanRemoval = true`
Also removed unnecessary unique index for primary key.

CB-21842 Do not fetch network for Redbeams DBStack

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/HostGroupType.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java

Jira: https://jira.cloudera.com/browse/CB-21906
A recent change to the EDL logic exposed an issue in the way the cluster is set up in the E2E environment. This change fixes that issue by ensuring the host groups have the correct amount of instances associated with them.
I have verified this locally by recreating the original issue with the E2E, and then ensuring the test passes after making the change.

CB-21906: Fixed failing E2E tests for EDL creation.

---

core/src/main/resources/defaults/blueprints/7.2.17/cdp-sdx-enterprise.bp
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/atlas/AtlasKnoxRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/atlas/AtlasKnoxRoleConfigProviderTest.java

CDPSDX-4126; disable atlas entity differential where the runtime is higher than 7.2.16, reason: this value is default with the newer runtimes. Change the ranger  audit ttl to 30, reason: this value already exists, but the name has typo.

CDPSDX-4126; disable atlas entity differential 

---

cloud-gcp/src/main/resources/definitions/gcp-credential.json
environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/CredentialToCredentialV1ResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/gcp/GcpCredentialV1ParametersToGcpCredentialAttributesConverter.java
environment/src/test/java/com/sequenceiq/environment/credential/v1/converter/gcp/GcpCredentialV1ParametersToGcpCredentialAttributesConverterTest.java

GCP secret structure was not reflected in the resource definitions as the `projectId` is a top level attribute. The converter had to be altered accordingly, to fill up this field with the raw value from the credential JSON. Previously the `projectId` was embedded under the `gcp` attribute.

CB-21993 ProjectId is not returned from GCP credentials

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/setup-autotls.sh.j2

On commercial we also have Java 11 which does not have the specified providerclass, and it only has to be specified for GOV as it has different java security providers.

CB-22015 Only specify providerclass and providerarg for keytool on GOV

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/backup.sls

**JIRA:** [CDPSDX-4157](https://jira.cloudera.com/browse/CDPSDX-4157) The root cause of the restore fails is the database backup failed but it shows successful. This PR is aimed to fix the issue of the database backup failure because it is urgent. We need to have another PR to fix the issue on why it shows successful rather than failed (jira created and assigned to myself to fix that: [CDPSDX-4160](https://jira.cloudera.com/browse/CDPSDX-4160))
**ISSUE:** Get this error when running DB backup (this error is in the Kibana log): [{"outputter":"highstate","data":{"dl-9go86ufc7i-master0.sdx-quas.xcu2-8y8x.dev.cldr.work":["Rendering SLS 'base:postgresql.disaster_recovery.backup' failed: Jinja variable 'remote_admin' is undefined"]}}]}
**FIX:** Renamed pg_username (which is never used in …

CDPSDX-4157 Fixed "remote_admin is undefined" error on database backup

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2

**Proposed changes:**
Change Ranger UI and API configs, specifically update stickysession and nofallback properties to prevent case where Ranger UI becomes unresponsive in case of HA failover. This is because Ranger UI calls Ranger API which does not fallback when there is an error.
**Testing**
Testing for these configs was done on a QE cluster.

CB-22019 - Update Ranger sticky session and LB configs

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTerminationHelperService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/loadbalancer/AzureLoadBalancer.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTerminationHelperServiceTest.java

Bug: When an error occurs in the upscale operation, it downscales back. When it tries to delete the public IP associated with the load balancer, as it is in use, the operation fails.
Test:
Created light duty datalake, then create a data engineering HA data hub.
Throw an exception before the save resources in the upscale operation.
The public IP of the LB is skipped.

CB-22098 Hotfix - Load balancer public IP should not be delete in downscale operation

---

core/src/main/resources/defaults/blueprints/7.2.17/cdp-sdx-enterprise.bp
core/src/main/resources/defaults/blueprints/7.2.18/cdp-sdx-enterprise.bp

Change the message size to 10% of the available memory. This modification will remove the warning message on the CM UI. This configuration refers to the max size of a thrift message being sent back to the client. This change is done to address the warning thrown by CM.

CB-21969 Update EDL HMS configuration.

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/CandidateImageAwareMixedPackageVersionService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/MixedPackageNotificationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/TargetImageAwareMixedPackageVersionService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/CandidateImageAwareMixedPackageVersionServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/MixedPackageNotificationServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/TargetImageAwareMixedPackageVersionServiceTest.java

When an upgrade fails, the roll-forward is called automatically to sync versions from CM to CDP DB. It, however, uses the UPDATE_IN_PROGRESS notification type.
This is because the roll-forward can be used:
automatically during upgrade failure - UPGRADE_FAILED voluntarily by the customer - UPDATE_IN_PROGRESS

CB-16526: Mixed package warings should use UPGRADE_FAILED status when upgrade failed

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceServiceTest.java

When the redbeams service restarted in ALLOCATE_DATABASE_SERVER_STATE we sent the database server ARM template again to the azure. In this commit, I've added an extra check to validate the existence of the template on the Azure side.

CB-11157: Azure database server creation should be idempotent

---

freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmFlowIntegrationTest.java

CB-22030 raising UpgradeCcmFlowIntegrationTest test in freeipa timeout beforce the flow finishes

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmProductChooserService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmProductChooserServiceTest.java

In this commit I've fixed the handling of the case gracefully when one parcel present in CB metadata is missing from CM (e.g. customer deleted it) but there is a newer version of that parcel already installed and activated.

CB-20488: Roll forward should detect and not fail on newer parcel version

---

core/src/main/resources/defaults/blueprints/7.2.17/cdp-sdx-enterprise.bp
core/src/main/resources/defaults/blueprints/7.2.18/cdp-sdx-enterprise.bp
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_token.xml.j2

CB-21467 extends the topology to populate ranger and ranger UI URLs when the ranger is running on the master node. In the case of EDL, we moved the Ranger from the GATEWAY node to the MASTER node. But the salt searched it in the GATEWAY host, which means it's not loading the ranger URLs into the cdp-proxy topology;
To unblock EDL promotion we added Ranger in Gateway along with Master node as well. This PR fixes it correctly.
Tested.
The Datalake Ranger UI loaded.
The Ranger API call was successful.
The content of  `/var/lib/knox/gateway/data/deployments/cdp-proxy.topo.18795723142/META-INF/topology.xml`
```
<service>
<role>RANGER</role>
<url>https://irokolya-env-04-18-001-gateway0.irokolya.xcu2-8y8x.wl.cloudera.site:6182</url>
<url>https://irokolya-env-04-18-001-gateway1.irokolya.xcu2-8y8x. …
```

CB-21467 extends the topology to populate ranger and ranger UI URLs

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/CustomParcelFilterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmInstalledComponentFinderService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/CustomParcelFilterServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmInstalledComponentFinderServiceTest.java

In this commit, I've improved the handling of the custom parcels during CM parcel sync. When we've retrieved the active parcels from the CM we're filtering out those parcels that are not present in our image catalog.

CB-14443: Handle custom parcels during CM parcel sync

---

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/FreeIpaImageRequest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/FreeIpaImageResponse.java
environment/src/main/java/com/sequenceiq/environment/environment/domain/Environment.java
environment/src/main/java/com/sequenceiq/environment/environment/domain/EnvironmentView.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDto.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/FreeIpaConverter.java
environment/src/main/resources/schema/app/20230612074641_CB-22114_Create_new_image_os_field.sql
structuredevent-model/src/main/java/com/sequenceiq/environment/environment/dto/FreeIpaCreationDto.java

This PR exposes an already existing backend feature to select
an image based on the [O]perating [S]ystem. As part of the
environment request now you'll be able to do this
```
"image": {
"os": "redhat8"
},
```
to select the latest RedHat8 based FreeIPA image. Later this
functionality can be exposed to the UI. You can achieve the
same thing by specifying the image by direct ID like
```
"image": {
"catalog": "https://cloudbreak-imagecatalog.s3.amazonaws.com/v3-test-freeipa-image-catalog.json",
"id": "ef46a6e8-1cc3-40f4-a33f-606b42ad3772",
},
```
but it simplifies the testing by not caring about the image
id just the OS type.

CB-22114 Create an 'os' option for FreeIPA creation

---

flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowChainLogService.java
flow/src/test/java/com/sequenceiq/flow/service/flowlog/FlowChainLogServiceTest.java

**JIRA:** [ENGESC-20632](https://jira.cloudera.com/browse/ENGESC-20632) & [CDPSDX-4064](https://jira.cloudera.com/browse/CDPSDX-4064) **(we need it to be a hotfix to 2.72 since many customers are experiencing this issue)** This PR had already been approved in there https://github.com/hortonworks/cloudbreak/pull/15029, creating this new one to merge it into CB2.72.
**CONTEXT:** We recently introduced code in BackupDatalakeDatabaseFlowEventChainFactory that would skip salt_update if salt_update_event has been run, that would left the flowchain only have database_backup_event, which would let the flowchainlog be saved into the database in a very short time (detail is under the code in removeLastTriggerEvent), causing the column created to have the same value in some rare cases.
**ISSUE:** …

CDPSDX-4064 Change getCreated to getId when getting lastFlowChain

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/DiskSpaceValidationService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/DiskSpaceValidationServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/CheckResult.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/ConnectivityCheckResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmService.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/handler/UpgradeCcmCheckPrerequisitesHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/orchestrator/OrchestratorParamsProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/proxy/ModifyProxyConfigOrchestratorService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/upgrade/ccm/UpgradeCcmOrchestratorService.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/chain/UpgradeCcmFlowChainIntegrationTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmFlowIntegrationTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/handler/UpgradeCcmCheckPrerequisitesHandlerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/orchestrator/OrchestratorParamsProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/proxy/ModifyProxyConfigOrchestratorServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/upgrade/ccm/UpgradeCcmOrchestratorServiceTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/OrchestratorRunParams.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

Added call to a connectivity checker script in case of CCM upgrade from CCMv1 in order to fail fast if no CCMv2 connection is available from the FreeIPA nodes.
Refactored orchestrator shell command runner to be more generic.
See https://github.com/hortonworks/cloudbreak-images/pull/828

CB-22006 Validate CCMv2 Server connectivity

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/CleanupFreeIpaHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaCleanupService.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/CleanupFreeIpaHandlerTest.java

Increase the timeout to one hour on CB side.
In case of failure/timeout do not proceed with the upscale/provision. If the issue is intermittent, retry would work for these cases too.

CB-22251 CB core doesn't wait for FreeIPA cleanup

---

cloud-azure/src/main/resources/templates/arm-flexible-dbstack.ftl

In case if WIRE_ENCRYPTION entitlement is disabled we will turn off ssl for flexible server

CB-21576 SSL setup for flexible server based on the provided parameters

---

core-model/src/main/java/com/sequenceiq/cloudbreak/dto/StackDto.java
core-model/src/main/java/com/sequenceiq/cloudbreak/dto/StackDtoDelegate.java
core-model/src/main/java/com/sequenceiq/cloudbreak/util/DatabaseParameterFallbackUtil.java
core-model/src/test/java/com/sequenceiq/cloudbreak/dto/StackDtoTest.java
core-model/src/test/java/com/sequenceiq/cloudbreak/util/DatabaseParameterFallbackUtilTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackToStackV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackDtoRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/DatabaseSslService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/EmbeddedDatabaseService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackDtoService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/UpgradeEmbeddedDBPreparationStateParamsProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/UpgradeEmbeddedDBStateParamsProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/DatabaseSslServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/EmbeddedDatabaseServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/consumption/ConsumptionServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/TargetedUpscaleSupportServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/UpgradeEmbeddedDBPreparationStateParamsProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/UpgradeEmbeddedDBStateParamsProviderTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseParameterFallbackUtil.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/database/DatabaseParameterFallbackUtilTest.java

CB-22198 Fix create external db in 2.73 -> upgrade on 2.72 -> back to 2.73: upgrade is needed again
The issue:
* In case of external database creation is happening on 2.73, the new Database entity will be created in cbdb.
* If we upgrade this database on 2.72 branch, the database entity won't be updated, the upgrade will be successful
* If we switch back to 2.73, cloudbreak will check the database entity, but it won't contain the right version
The fix:
If the db version is set in stack and database entity as well and they are not equal, the db version will be from stack
This fix is needed because of backward compatibiltiy and will be removed with this 2 jira ticket: CB-21369, CB-22002

CB-22198 Fix create external db in 2.73 -> upgrade on 2.72 -> back to 2.73: upgrade is needed again

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryRoleConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/BlueprintView.java

* [CFM-3228](https://jira.cloudera.com/browse/CFM-3228) made some improvements to NiFi Registry so that it employs a more up-to-date PostgreSQL JDBC driver; see CFM 2.2.6.200 (for CDH 7.2.16.p200) and 2.2.7.0 (for CDH 7.2.17.p0). This commit fixes the behavior of earlier NiFi Registry versions that do not contain the aforementioned change.
* CFM parcel versions < 2.2.6.200: Use `sslmode=require`.
* CFM parcel versions >= 2.2.6.200: No change, keep using `sslmode=verify-full`.
* Applicable to all cloud providers, external and embedded DB servers.
* Some code cleanup.
* Testing:
* Manual test with DH using multiple runtimes: 7.2.15.p100, 7.2.16.p200, 7.2.17.p0.
* Added new UT & adapted existing ones.

CB-22187 Fix DB SSL for old NiFi Registry versions

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/LoadBalancerMetadataHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupServiceTest.java

Context: Metadata wasn't being validated in the create stack workflow. Validation moved to Metadata service to ensure the data will be validated before persists for all cases.
Test:
An exception was thrown during metadata collection and the load balancer wasn't created with inconsistent data.
Tested with public/private/gateway_private/outbound LB

CB-22257 Load balancer metadata validation before persist

---

core/src/main/java/com/sequenceiq/cloudbreak/rotation/executor/CMUserRotationExecutor.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/executor/ClusterProxyRotationExecutor.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/executor/RedbeamsPollerRotationExecutor.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/executor/SaltPillarRotationExecutor.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/executor/SaltPillarRotationExecutorTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/rotation/CloudbreakPollerRotationExecutor.java
datalake/src/main/java/com/sequenceiq/datalake/service/rotation/RedbeamsPollerRotationExecutor.java
redbeams/src/main/java/com/sequenceiq/redbeams/rotation/RootPasswordRotationExecutor.java
redbeams/src/test/java/com/sequenceiq/redbeams/rotation/context/provider/RootPasswordRotationExecutorTest.java

- Skip throwing an exception in Redbeams during rollback when secrets are not in rotation state (it can happen when root password rotation fails before the Vault step)
- Remove unnecessary logs and resourceCrn from log messages, because MDC context should hold the related resourceCrn

CB-21683 RDS root password rotation improvements

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/VmTypeMeta.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureDisk.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformResources.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilder.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformResourcesTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilderTest.java

cloud-azure module should be enhanced to fetch and populate Availability zones for cloud resources
Added AzureDisk DTO to populate information needed for creating the disk. It is needed because 7 attributes for disk were being passed as argument to the method. AZ cannot be added as another argument since maximum number of allowed arguments are  7. 
Equals and hashCode has been overridden to only use diskName since diskName is unique and disk should be treated equal if diskname is same. Also, Overriding equals and hashCode is only needed for unit tests to pass since unit tests are using as part of verification.

CB-22077 cloud-azure module should be enhanced to fetch and populate Availability zones for cloud resources

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/init.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/pg14.sls

This commit includes the support for embedded Postgres 14
- turning off PG10 and PG11 services
- configuring the `PGDATA` and `Alias=postgresql.service`
- configuring the alternatives
- installing PG14 if it does not exist yet

CB-22309 - Embedded PG14 support

---

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/GatewayPublicEndpointManagementService.java

Tests:
Thrown an exception in DNS Registration.

CB-21998 DNS registration failures trigger an event

---

core/src/main/java/com/sequenceiq/cloudbreak/rotation/ExitCriteriaProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/provider/CMDBPasswordRotationContextProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/provider/CMServiceDBPasswordRotationContextProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/provider/UserKeyPairSaltStateRunRotationContextGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/executor/SaltPillarRotationExecutor.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/context/provider/CMDBPasswordRotationContextProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/context/provider/CMServiceDBPasswordRotationContextProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/context/provider/UserKeyPairSaltStateRunRotationContextGeneratorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/executor/SaltPillarRotationExecutorTest.java

- after pod restart we need to update memory state again regarding polling group in order to be able to properly poll salt related operations

CB-21512 improve exit criteria for salt related rotations

---

common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/usage/SecretRotationUsageProcessor.java
flow/src/main/java/com/sequenceiq/flow/rotation/SecretRotationActions.java
flow/src/main/java/com/sequenceiq/flow/rotation/handler/ExecuteRotationHandler.java
flow/src/main/java/com/sequenceiq/flow/rotation/handler/FinalizeRotationHandler.java
flow/src/main/java/com/sequenceiq/flow/rotation/handler/RollbackRotationHandler.java
flow/src/test/java/com/sequenceiq/flow/rotation/handler/ExecuteRotationHandlerTest.java
flow/src/test/java/com/sequenceiq/flow/rotation/handler/FinalizeRotationHandlerTest.java
flow/src/test/java/com/sequenceiq/flow/rotation/handler/RollbackRotationHandlerTest.java
usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/UsageReportProcessor.java
usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/UsageReporter.java
usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/service/SecretRotationUsageService.java
usage-collection/src/main/proto/usage.proto
usage-collection/src/test/java/com/sequenceiq/cloudbreak/usage/service/SecretRotationUsageServiceTest.java

Only first-level secretTypes will be sent to EDH, where the execution type is null (secret types from polling are not included). SecretRotationUsageProcessor is injected as an optional service, to avoid using usage-collection as a flow module depencency.

CB-21882 Send secret rotation events to EDH

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Image.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/instance/InstanceMetaDataResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/image/ImageToImageEntityConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/image/ImageToImageSettingsResponseConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/InstanceMetaDataToInstanceMetaDataResponseConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/InstanceMetaData.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/chain/UpgradeFlowEventChainFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/upgrade/UpgradeEvent.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/action/RebootActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/FreeipaPlatformStringTransformer.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/InstanceMetaDataService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/MetadataSetupService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/upgrade/UpgradeService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/upgrade/UpgradeValidationService.java
freeipa/src/main/resources/schema/app/20230531134016_CB-20506_alter_instancemetadata_table_add_image_column.sql
freeipa/src/test/java/com/sequenceiq/freeipa/converter/image/ImageToImageEntityConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/image/ImageToImageSettingsResponseConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/InstanceMetaDataToInstanceMetaDataResponseConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/chain/UpgradeFlowEventChainFactoryTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/FreeipaPlatformStringTransformerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/instance/InstanceMetaDataServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/InstanceMetadataServiceComponentTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/upgrade/UpgradeServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/upgrade/UpgradeValidationServiceTest.java

- save image info with instancemetadata when created
- publish image info on the API
- alter upgrade logic, so it's possible to upgrade when there is instance with old image
- alter upgrade logic, that instances with current image are not upgraded

CB-20506 Add image info to FMS instancemetadata

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/general/GeneralClusterConfigsProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/model/GeneralClusterConfigs.java

Currently only the primary gateway host have been put to the knox_proxyhosts, but now it will be the other available gateway hosts as well.

CB-22268 adding other gateways as well as the primary gateway to the knox_proxyhosts ServiceConfig

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/Clue.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxCustomTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ErrorLogMessageProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/action/S3ClientActions.java

Lookup of logs should not involve any manual digging just a simple click on the test page.

CB-22353 Introduce Kibana Query and S3 Cluster Logs URLs to the Jenkins TestNG Reports page

---

freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KeytabCleanupService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientRetryService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/host/HostDeletionService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/host/HostDeletionServiceTest.java

Added internal retries where the exception wouldn't propagate as issues are collected. This prevented for intermittent issues to be retried and caused unnecessary cleanup failures.

CB-22345 Improve FMS CleanupService retry logic

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXMarketplaceImageTests.java

The runtime version for e2e tests was raised to 7.2.17. However there is no marketplace image in the production image catalog as of now. Hard coding in 7.2.15 for the marketplace e2e test for the meanwhile.

CB-22402 Temporarly lock runtime version for the Marketplace e2e test to 7.2.15

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/SdxWithCcmResizeRecoveryTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/SdxWithCcmResizeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/EnvironmentUtil.java
integration-test/src/main/resources/testsuites/e2e/l0promotion/ccm-sdx-tests.yaml

We have failing MOW-Dev L0 Promotion test cases, because of `cluster-proxy.proxy.timeout::failed because of akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(10 seconds) expired`.
After we've upgraded to CCMv2, the issue vanished.

CB-22390 Replace CCMv1 with CCMv2 in the L0 Promotion test cases

---

common/build.gradle
common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/AbstractMetricService.java
common/src/main/java/com/sequenceiq/cloudbreak/jvm/DiagnosticCommandRunner.java
common/src/main/java/com/sequenceiq/cloudbreak/jvm/JvmInfoProvider.java
common/src/main/java/com/sequenceiq/cloudbreak/jvm/JvmMetricTag.java
common/src/main/java/com/sequenceiq/cloudbreak/jvm/JvmMetricType.java
common/src/main/java/com/sequenceiq/cloudbreak/jvm/MemoryCategory.java
common/src/main/java/com/sequenceiq/cloudbreak/jvm/NativeMemoryMetricConfigurator.java
common/src/main/java/com/sequenceiq/cloudbreak/jvm/NativeMemoryParser.java
common/src/main/java/com/sequenceiq/cloudbreak/jvm/VmFlagsParser.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/JobCountMetricConfigurator.java
common/src/test/java/com/sequenceiq/cloudbreak/jvm/NativeMemoryParserTest.java
common/src/test/java/com/sequenceiq/cloudbreak/jvm/VmFlagsParserTest.java
dependencies.gradle

- Add native memory metrics based on the -XX:NativeMemoryTracking=summary jvm flag and jmx
- Add 'real' memory metrics from procfs '/proc/self/status'
- Print vmFlags content on startup
- Add new properties: vm.info.vmflags.enabled (default true), vm.info.nativeMemory.enabled (default true), vm.info.nativeMemory.delay (default 60 sec)
- Fix gauge metrics related bug where gauge uses multiple tags as dimensions (xxx_flow_step)

CB-22416 Setup native memory tracking

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/action/AzureCloudBlobClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java

In case of separate resource's TestDTO path generation base location fallback should be introduced to the getLoggingUrl method.

CB-22392 Improve AZURE and GCP get Cluster Logs URL methods

---

orchestrator-salt/src/main/resources/salt/salt/datalake_metrics/get_database_sizes/scripts/get_database_sizes.sh

If database size cannot be obtained via more precise method we can use raw database size instead.

CB-22380 Try to calculate the database size using an alternative method

---

datalake/src/main/java/com/sequenceiq/datalake/entity/DatalakeInstanceGroupScalingDetails.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxHorizontalScalingService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxHorizontalScalingServiceTest.java

CB-22003 Extends the Datalake horizontal scaling flow with the node status validation. We cannot execute the horizontal scaling if the CM is not reachable. Validations: check, the stack status, Stack has to be available. Check the CM status, CM has to be reachable. The target host group is scalable. Do not allow the downscale for Solr, Kafka, and storage add-on host groups. Validate the desired count does not hurt the minimum EDL setup

CB-22003 Extend datalake horizontal scale validation

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/upgrade/FreeIpaUpgradeV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/upgrade/model/FreeIpaUpgradeRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaUpgradeV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/dto/ImageWrapper.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/provision/handler/ImageFallbackHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/CoreImageProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/FreeIpaImageFilter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/FreeIpaImageFilterSettings.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/FreeIpaImageProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/upgrade/UpgradeImageService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/upgrade/UpgradeService.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/CoreImageProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/FreeIpaImageFilterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/FreeIpaImageProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageCatalogProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/upgrade/UpgradeImageServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/upgrade/UpgradeServiceTest.java
freeipa/src/test/resources/com/sequenceiq/freeipa/service/image/freeipa-catalog-1.json

This commit contains the following changes:
- Introduce FreeIpaImageFilterSettings class to encapsulate all the upgrade required parameters
- Added allowMajorOsUpgrade parameter to FreeIpaUpgradeRequest
- Added allowMajorOsUpgrade request parameter to FreeIpaUpgradeV1Endpoint.getFreeIpaUpgradeOptions

CB-22264: Introduce allowMajorOsUpgrade parameter for FreeIpa upgrade to enable the upgrade for different OS
