hortonworks/cloudbreak

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRetryService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxRetryServiceTest.java
flow/src/main/java/com/sequenceiq/cloudbreak/service/flowlog/FlowLogUtil.java
flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java

rebased CB-16028 to 2.52 without resizeRecoveryService

[CB-16152] SDX retry broken when no flow log

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/AuthorizationClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/PersonalResourceViewClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/config/UmsClientConfig.java
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClientTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRetryService.java
datalake/src/test/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxRetryServiceTest.java
flow/src/main/java/com/sequenceiq/cloudbreak/service/flowlog/FlowLogUtil.java
flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java
grpc-common/src/main/java/com/sequenceiq/cloudbreak/grpc/util/GrpcUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UmsClient.java

merges fix for CB-16152 to master and includes changes needed for for CB-16028

Merge 2.52 to master

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java

Full forced usersync is invoked and the operation result is checked.

CB-15295 Add usersync to FreeIPA upgrade availability tests

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java

CB-15863 making sure that only gcp labels are used for user specified tags

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackStopRestrictionService.java

CB-14728 Fix no session error in StackStopRestrictionService

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/AuthorizationClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/PersonalResourceViewClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/config/UmsClientConfig.java

CB-16138 use short timeout only for right checks

---

core/src/main/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/ImageReaderService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/ImageReaderServiceTest.java

Merge 2.52 to 2.53

---

autoscale/src/main/resources/application.yml
core/src/main/resources/application.yml
datalake/src/main/resources/application.yml
environment/src/main/resources/application.yml
freeipa/src/main/resources/application.yml
redbeams/src/main/resources/application.yml

Set timeout-per-shutdown-phase to 60 sec instead of 60 ms

CB-15891 Investigate Graceful Shutdown Failure on kill signals

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

[CB-16205] don't use improperly escaped characters for SDXService error

---

core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJob.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/StackPatchUsageReporterService.java
core/src/test/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJobTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/StackPatchUsageReporterServiceTest.java
usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/UsageReportProcessor.java
usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/UsageReporter.java
usage-collection/src/main/proto/usage.proto

CB-16076 Report stack patcher usages to EDH

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java

- creating DL cluster without external database
- removed DL upgrade
- removed DH cluster stop-start before the upgrade

CB-16207: Optimise DistroXUpgradeTests.testDistroXUpgrade E2E test to reduce execution time

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java

CB-14728 Fix ephemeral stoppability detection in repair service

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterDetailResponse.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterResponse.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxDatabaseRequest.java
datalake-api/src/test/java/com/sequenceiq/sdx/api/model/SdxClusterDetailResponseTest.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxClusterConverter.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/entity/SdxCluster.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxExternalDatabaseConfigurer.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/AwsDatabaseServerParameterSetter.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/AzureDatabaseServerParameterSetter.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseServerParameterSetter.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/GcpDatabaseServerParameterSetter.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/MockDatabaseServerParameterSetter.java
datalake/src/main/resources/schema/app/20220201083304_CB-15832_Store_Database_engine_version.sql
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/database/AwsDatabaseServerParameterSetterTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/database/AzureDatabaseServerParameterSetterTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/database/DatabaseServiceTest.java

CB-15832 Database engine version configurable from API for datalakes

---

cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartDownscaleStopInstancesHandler.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartUpscaleStartInstancesHandler.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartDownscaleStopInstancesHandlerTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartUpscaleStartInstancesHandlerTest.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartus/StopStartUpscaleFlowService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java
flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java
flow/src/main/java/com/sequenceiq/flow/domain/FlowLogIdWithTypeAndTimestamp.java
flow/src/test/java/com/sequenceiq/flow/service/FlowNameFormatServiceTest.java
flow/src/test/java/com/sequenceiq/flow/service/TestFlowView.java
freeipa/build.gradle
freeipa/src/main/java/com/sequenceiq/freeipa/FreeIpaFlowInformation.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/cloud/PlatformParameterService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaFlowManager.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaParallelFlowValidator.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackTemplateService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaParallelFlowValidatorTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java

2.53 to master

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
orchestrator-salt/src/main/resources/salt/salt/nginx/conf/openssl.cnf
orchestrator-salt/src/main/resources/salt/salt/nginx/conf/server_cert_ext.cnf
orchestrator-salt/src/main/resources/salt/salt/nginx/init.sls
orchestrator-salt/src/main/resources/salt/salt/nginx/scripts/create-user-facing-cert.sh

CB-15642 Genereta user facing cert with openssl instead of certm

---

integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-longrunning-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/gcp-longrunning-e2e-tests.yaml

CB-15505 Enable FreeIPA upgrade tests

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java

CB-15292 Fix of logging failure.

CB-15292 Fix of logging failure.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java

Jira:
https://jira.cloudera.com/browse/CB-15293
Call the generateServiceKeytab endpoint to generate keytab for a service

CB-15293 E2E test for get-keytab for a service principal

---

datalake/src/main/java/com/sequenceiq/datalake/entity/SdxClusterView.java
datalake/src/main/java/com/sequenceiq/datalake/repository/SdxClusterRepository.java
datalake/src/main/java/com/sequenceiq/datalake/repository/SdxClusterViewRepository.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/EnvironmentService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/EnvironmentServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/ChangeImageCatalogTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DataStewardTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DatalakeDatahubCreateAuthTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/AuthorizationTestUtil.java

CB-15947 enable authz by environment crn in datalake service

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxDefaultTemplateResponse.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

CB-16169 Create default template API in datalake

CB-16169 Create default template API in datalake

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterRequestBase.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxInstanceGroupRequest.java

CB-16282 Extend datalake API with instance type

---

core/src/main/java/com/sequenceiq/cloudbreak/service/multiaz/MultiAzCalculatorService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/multiaz/MultiAzCalculatorServiceTest.java

Merge252into253

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureObjectStorageConnector.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureObjectStorageConnectorTest.java

CB-16171 handle Azure CloudException during object storage validation

---

datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/test/java/com/sequenceiq/datalake/flow/SdxReactorFlowManagerTest.java

Jira: https://jira.cloudera.com/browse/CB-16322
Simple change focused on adding more logging to this so we can know exactly why backups are skipped.

CB-16322: Add logging for backup being skipped for upgrade/resize

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityService.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityServiceTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java

CB-15994 Enable patch upgrade for Ranger RAZ clusters for 7.2.7 or newer

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java

Jira:
[https://jira.cloudera.com/browse/CB-15297?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel](url)
DNS lookups should always work, as every FreeIPA instance has nameserver running and we configure all cluster with all FreeIPA as nameserver

CB-15297 E2E test for DNS lookups

---

core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXRemoveInstanceAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXScaleTest.java

CB-14421 distrox scale test should poll instance deletion by flow

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterRequestBase.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxInstanceGroupRequest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxCustomTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxTests.java

CB-16283 Implement service logic for instance type selection in datalake

---

environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java

CB-16053 Fix the wrong parameter type

---

core/src/main/java/com/sequenceiq/cloudbreak/service/environment/credential/CredentialClientService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeService.java
datalake/src/main/java/com/sequenceiq/datalake/service/CredentialService.java

CB-16328 added missing resource property provider for authz

---

datalake/src/main/java/com/sequenceiq/datalake/service/SdxEventsService.java

Jira: https://jira.cloudera.com/browse/CB-16131
This specifically serves to introduce actual error throwing for the SdxEventsService. Before we were just returning an empty list and not logging or throwing anything.
This issue is of particular importance due to a difficult experience had during the release of 2.52.0, more info here: https://jira.cloudera.com/browse/CB-15944.
I have simply opted to throw exceptions in the various places where the errors can occur, allowing for them to be received and interpreted.

CB-16131: Added proper error handling to SdxEventsService

---

core/src/main/resources/schema/app/20220304081639_CB-16263_rename_opdb_templates.sql

CB-16263 7.2.14 OpDb templates are still referenced in DB renaming that.

---

core/src/main/resources/defaults/blueprints/7.2.15/cdp-streaming-small.bp
core/src/main/resources/defaults/blueprints/7.2.15/cdp-streaming.bp

Streaming template include SRM Gateway role config group so that auto-TLS is generated for the GATEWAY role.
Tested: manual cluster installation

CB-16162 Streaming blueprints: generate auto-TSL config for SRM Gateway

---

orchestrator-salt/src/main/resources/salt-common/salt/filecollector/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/filecollector/template/filecollector.yaml.j2

CB-16386. Add hostname and cluster name fields for diagnostic bundles.

---

usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/strategy/HttpUsageProcessingStrategy.java
usage-collection/src/test/java/com/sequenceiq/cloudbreak/usage/strategy/HttpUsageProcessingStrategyTest.java

CB-15999. Addendum - use additional fields for http usage.

---

datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/cert/CertRenewalService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/cert/CertRotationService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/diagnostics/DiagnosticsService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/cert/CertRenewalServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/cert/CertRotationServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreServiceTest.java

[CDPSDX-3373]  add sdx name to error message

---

mock-thunderhead/src/main/resources/application.yml

CB-16416 Enable backup on upgrade entitlement in UMS mock

---

common/src/main/resources/common-config.yml

this will increase the timeout to 10 min

CB-16453. Increase telemetry upgrade timeout.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXScaleTest.java

CB-14421 distrox scale test should validate dto

---

common/src/main/java/com/sequenceiq/cloudbreak/common/dal/ResourceBasicView.java
common/src/main/java/com/sequenceiq/cloudbreak/common/dal/repository/AccountAwareResourceRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/repository/SdxClusterRepository.java
environment/src/main/java/com/sequenceiq/environment/environment/repository/EnvironmentRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/repository/CDPStructuredEventRepository.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/filter/RepositoryBasedDataCollector.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/filter/DataCollectorComponentTest.java

Added some queries to the AccountAwareService to fetch the resourceCrn, name and id only from the entities

CB-16359 Change the stack projection during Datahub list

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/handler/DiagnosticsSaltPillarUpdateHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/handler/DiagnosticsSaltStateUpdateHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/handler/DiagnosticsUpgradeTelemetryHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/handler/DiagnosticsSaltPillarUpdateHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/handler/DiagnosticsSaltStateUpdateHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/handler/DiagnosticsUpgradeTelemetryHandlerTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsSaltPillarUpdateHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsSaltStateUpdateHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsUpgradeTelemetryHandler.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsSaltPillarUpdateHandlerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsSaltStateUpdateHandlerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsUpgradeTelemetryHandlerTest.java
usage-collection/src/main/proto/usage.proto

CB-16484. Add new diagnostics failure types.

---

cloud-azure/src/main/resources/templates/arm-storageaccount.ftl

CB-16511 Specify minimumTlsVersion in storage account ARM template

---

core/src/main/java/com/sequenceiq/cloudbreak/service/idbroker/IdBrokerService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/idbroker/IdBrokerServiceTest.java

CB-16381 Fix the IdBroker sign keys generation during the recovery

---

core/src/test/java/com/sequenceiq/cloudbreak/orchestrator/SimpleOrchestratorBootstrapRunnerTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/Pillar.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/PillarSave.java
orchestrator-yarn/src/main/java/com/sequenceiq/cloudbreak/orchestrator/yarn/poller/YarnAppBootstrap.java

CB-16533 Add toString() to OrchestratorBootstrap implementations

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidator.java

CB-16541 Enable scaling when the cluster is in NODE_FAILURE state

---

common-model/src/main/java/com/sequenceiq/common/api/type/LoadBalancerCreation.java
common/src/main/java/com/sequenceiq/cloudbreak/converter/LoadBalancerCreationConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/base/EnvironmentNetworkBase.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentNetworkResponse.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/BaseNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/EnvironmentBaseNetworkConverter.java
environment/src/main/resources/schema/app/20220321161846_CB-15814_Option_to_create_without_load_balancer.sql
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverterTest.java
structuredevent-model/src/main/java/com/sequenceiq/environment/network/dto/NetworkDto.java

N.B. this is intended for internal testing purposes only to recreate the
configuration of old datalakes/enviroments created prior to the release
of loadbalancers it is not intented to be exposed to customers

[CB-15814] introduce option to disable loadbalancer for environments

---

datalake/src/main/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryService.java
datalake/src/test/java/com/sequenceiq/datalake/service/resize/recovery/ResizeRecoveryServiceTest.java

Expands on work done in CB-14399 needs to plan action based on current detached status

CB-16446 add in recovery option for detach

---

cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtilsTest.java

DOCS-12746 Add test for documented hash generation

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltConnector.java

Send requests with the exact json the signature was generated from, and also log salt endpoint calls in SaltConnector.

CB-16534 Fix salt endpoint signature generation

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaOperationDescriptions.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/create/FreeIpaRecommendationResponse.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/create/VmTypeMetaJson.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/create/VmTypeResponse.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/create/VolumeParameterConfigResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/VmTypeToVmTypeResponseConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/CredentialService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaRecommendationService.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/VmTypeToVmTypeResponseConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaRecommendationServiceTest.java

Returns:
- default instance type (based on appliaction.yaml config)
- available vm types from cloud provider (CPU and memory size should be at least the default instance type)

CB-16413 Cretate recommendation API in FreeIPA

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/PaywallCredentialPopulator.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/cache/common/ParcelMetadataCache.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ManifestRetrieverService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ManifestRetrieverServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterServiceTest.java

This change contains the following improvements:
- Added cache for parcel metadata retrieval
- Added 5 sec timeout for getting the metadata xml
- Improved ParcelFilterService to not get all parcels manifest if the required parcels are found.

CB-16316: Improve the performance of the retrieval of the required parcels

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ccm/StackCcmUpgradeService.java

CB-14584 triggering ccm upgrade flow through internal call

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ccm/StackCcmUpgradeService.java

Reverts hortonworks/cloudbreak#12488

Revert "CB-14584 triggering ccm upgrade flow through internal call"

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/environment/credential/CredentialConverter.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/credential/model/response/CredentialResponse.java

CB-16569 adding the missing jsonignore property to CredentialResponse

---

core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/dns/AllHostPublicDnsEntryService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/publicendpoint/dns/AllHostPublicDnsEntryServiceTest.java

CB-16548 DNS resolution for nodes is faulty on mow-int/ mow-stage

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ccm/StackCcmUpgradeService.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/chain/UpgradeCcmFlowChainIntegrationTest.java

Revert cb 14584 rdoktorics

---

freeipa/src/test/java/com/sequenceiq/freeipa/flow/chain/UpgradeCcmFlowChainIntegrationTest.java

@Ignore annotation is for JUnit4, @Disabled is for JUnit5

---

environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/CredentialViewConverter.java
environment/src/test/java/com/sequenceiq/environment/credential/v1/converter/CredentialViewConverterTest.java

CB-16604 Missing govCloud flag from CredentialViewResponse converter

---

common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/AbstractMetricService.java
common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/MetricService.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/configuration/SchedulerFactoryConfig.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/QuartzMetricType.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/SchedulerMetricsListener.java

- actual job count by job group
- scheduled trigger count by trigger group
- scheduler error count

CB-16384 Introduce quartz scheduler metrics

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterResponse.java

CB-16597 Ignore unknown properties on SdxClusterResponse

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/StackV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/StackViewV4Response.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/EnvironmentServiceDecorator.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/EnvironmentServiceDecoratorTest.java

CB-16611 adding govcloud flag to distrox responses

---

core-api/src/main/resources/definitions/exposed-services.json
core-api/src/test/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollectorTest.java
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_token.xml.j2

CB-16609 Expose OpDB Agent service

---

template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.2.15.json

[CB-16460] Bump CSA/SSB version to 1.6.1

---

common-model/src/main/java/com/sequenceiq/common/api/type/LoadBalancerType.java

CB-16504 Adding OUTBOUND LoadBalancerType to 2.53

---

common-model/src/main/java/com/sequenceiq/common/api/type/LoadBalancerType.java

Merge for the new enum in case of loadbalancers

---

common/src/main/java/com/sequenceiq/cloudbreak/quartz/configuration/SchedulerFactoryConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/EventBusMetricConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/ScheduleConfig.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/EventBusMetricConfig.java
environment/src/main/java/com/sequenceiq/environment/configuration/metrics/EventBusMetricConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/configuration/EventBusMetricConfig.java
redbeams/src/main/java/com/sequenceiq/redbeams/configuration/EventBusMetricConfig.java

- quartz executor
- scheduler executor
- reactor executor (event bus)

CB-16142 Introduce live metrics for thread pools of our services

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterStartHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterServiceRunnerTest.java

CB 16620  Lazy init exception occurred on rds config listing

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterServiceRunnerTest.java

Merge 2.54 into master

---

core-api/src/main/java/com/sequenceiq/cloudbreak/validation/StackNameLengthValidator.java
core-api/src/test/java/com/sequenceiq/cloudbreak/validation/StackNameLengthValidatorTest.java

and added the unit test for it

CB-16167 Fixed NPE in StackNameLengthValidator 

---

freeipa/src/main/java/com/sequenceiq/freeipa/client/AbstractFreeIpaHttpClientFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaHealthCheckClientFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaNodeStatusClientFactory.java
node-status-monitor-client/src/main/java/com/sequenceiq/node/health/client/CdpNodeStatusMonitorClient.java

- renamed `FreeIpaClientFactory` to `AbstractFreeIpaHttpClientFactory`
- added some logs
- removed unnecessary lines

CB-12317 Rename FreeIpaClientFactory as there is another one already

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsVirtualGroupRight.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/VirtualGroupService.java
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/VirtualGroupServiceTest.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/RangerVirtualGroupService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentInitHandler.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentInitHandlerTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsVirtualGroupCreateService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UmsVirtualGroupCreateServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/BasicEnvironmentVirtualGroupTest.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockGroupManagementService.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseServiceConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/NifiConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerUserSyncRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/zeppelin/ZeppelinRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProviderTest.java

CB-16587 Create virtual groups for existing environments as a part of user sync

---

autoscale/src/test/java/com/sequenceiq/periscope/endpointtests/DistroXAutoScaleClusterV1EndpointTest.java
common/src/main/java/com/sequenceiq/cloudbreak/common/service/LockNumber.java
common/src/main/java/com/sequenceiq/cloudbreak/common/service/LockService.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/configuration/QuartzJobInitializer.java
common/src/test/java/com/sequenceiq/cloudbreak/common/service/LockServiceTest.java
environment/src/test/java/com/sequenceiq/environment/service/integration/AuditCredentialAuthorizationIntegrationTest.java
environment/src/test/java/com/sequenceiq/environment/service/integration/CredentialAuthorizationIntegrationTest.java
environment/src/test/java/com/sequenceiq/environment/service/integration/EnvironmentServiceIntegrationTest.java

CB-16378 quartz init should run by one pod at a time

---

autoscale/build.gradle
autoscale/src/test/java/com/sequenceiq/periscope/endpointtests/DistroXAutoScaleClusterV1EndpointTest.java
build.gradle
cloudera/docker_images.yaml
common/src/main/java/com/sequenceiq/cloudbreak/common/service/LockNumber.java
common/src/main/java/com/sequenceiq/cloudbreak/common/service/LockService.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/configuration/QuartzJobInitializer.java
common/src/test/java/com/sequenceiq/cloudbreak/common/service/LockServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/RoutingDataSource.java
core/src/test/java/com/sequenceiq/cloudbreak/conf/RoutingDataSourceTest.java
environment/src/test/java/com/sequenceiq/environment/service/integration/AuditCredentialAuthorizationIntegrationTest.java
environment/src/test/java/com/sequenceiq/environment/service/integration/CredentialAuthorizationIntegrationTest.java
environment/src/test/java/com/sequenceiq/environment/service/integration/EnvironmentServiceIntegrationTest.java

Changes that has been merged to 2.55 line of CB but not on the related branch

---

common/src/main/java/com/sequenceiq/cloudbreak/common/controller/BinderControllerAdvice.java

CVE-2022-22965 quickfix

---

datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/DatalakeBackupActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/handler/DatalakeFullBackupWaitHandler.java

Thunderhead timeout is currently 10 hours

[CB-16643] Backup status poller timeout doesn't match backup timeout

---

structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/FreeIpaUseCaseMapper.java
usage-collection/src/main/proto/usage.proto

CB-15441 Add FreeIPA upgrade flow support for usage collection

---

common/src/main/java/com/sequenceiq/cloudbreak/common/controller/BinderControllerAdvice.java
orchestrator-salt/src/main/resources/salt-common/salt/telemetry/scripts/cdp-telemetry-deployer.sh

2.54 to 2.55

---

flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java
flow/src/test/java/com/sequenceiq/flow/service/flowlog/FlowLogDBServiceTest.java

Revert gson error

---

core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackIdViewImpl.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupServiceTest.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java
flow/src/test/java/com/sequenceiq/flow/service/flowlog/FlowLogDBServiceTest.java

Merge255intomaster

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java

CB-16765 FreeIPA upgrade test should use cluster-proxy

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachDetachUtils.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/attach/SdxDetachServiceTest.java

Jira: https://jira.cloudera.com/browse/CB-16720
Main objective of this is to not fail the updating of a stack or external DB if they are not found, instead choosing to just skip the step while logging the occurrence appropriately.
This is primarily meant to allow for more flexibility from resize recovery, for instance in the following scenario:
- Resize fails at the beginning of DL creation for the resized DL
- Resized DL therefore has no stack or DB or really anything but the SDX Cluster object
- Detach of resized DL, which occurs at the beginning of resize recovery, should be successful despite these missing

CB-16720: Skip detach of stack and DB if not present instead of throwing errors, allowing for more flexible resize recovery.

---

cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureStorageAccountBuilderServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/upscale/AzureUpscaleServiceTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpBaseResourceCheckerTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/setup/GcpBucketRegisterServiceTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/setup/GcpImageRegisterServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/start/SdxStartServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/stop/SdxStopServiceTest.java
gradle.properties
integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/ImageCatalogMockServerSetup.java

CB-16783 eliminate CVE-2022-22965 vulnerability

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/FlowUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceAwait.java

[MOW-Dev API E2E GCP Build #3-dev-2.55.0-b79-GCP (03-Apr-2022 16:34:47)](http://ci-cloudbreak.eng.hortonworks.com/job/mow-api-e2e-gcp/3/) is failing, because of the `TestFailException: Test timed out, flow did not finish in time.`. Unfortunately the waiting cycle did not stop here, even keep continue till the test case timeout (150 minutes).

CB-16707 SdxBackupRestoreTest waiting for flow timed out, test does not failed

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/database/base/DatabaseType.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/externaldatabase/SupportedDatabaseProvider.java
core-api/src/main/resources/definitions/exposed-services.json
core-api/src/test/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollectorTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/QueryProcessorRdsConfigProvider.java
core/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/7.2.15/cdp-data-engineering.bp
custom-configurations/src/main/java/com/sequenceiq/cloudbreak/validation/AllServiceTypes.java
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryStoreRoles.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProviderTest.java
template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/views/GatewayViewTest.java

Testing: I have done end-to-end testing and found that it's working as expected.

[Hue] - CDPD-32891 - Cloud Break Template change for QP

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java

Reverts hortonworks/cloudbreak#12617

Revert "ENGESC-14092 Increase CB hikari pool size to mitigate prod periodic o…"

---

docker-consumption/Dockerfile

CB-16716 fixing the jar url

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterStopStartTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXStartStopTestParameters.java

Since the related [CB-7294](https://jira.cloudera.com/browse/CB-7294) FlowChain issue has been resolved we can set back this scaling test case.

CB-16780 Set back DistroX Stop Start then Scale test

---

mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java

CB-16851 extend mock with DbusUploader role

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsVirtualGroupRight.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/VirtualGroupService.java
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/VirtualGroupServiceTest.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/RangerVirtualGroupService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/SudoRuleService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/SudoRuleServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/BasicEnvironmentVirtualGroupTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseServiceConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/NifiConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerUserSyncRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/zeppelin/ZeppelinRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerUserSyncRoleConfigProviderTest.java

CB-16887 virtual group rights can depend on entitlement

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsVirtualGroupRight.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/VirtualGroupService.java
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/VirtualGroupServiceTest.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/RangerVirtualGroupService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/SudoRuleService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/SudoRuleServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/BasicEnvironmentVirtualGroupTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseServiceConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/NifiConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerUserSyncRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/zeppelin/ZeppelinRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerUserSyncRoleConfigProviderTest.java

2.56 to master

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/archive/ArchiveInstanceMetaDataService.java

Removed active flow checks from ArchiveInstanceMetaData job, as they are not interfereing with removing old instancemetadata.

CB-16836 Remove active flow checks from ArchiveInstanceMetaData job

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/archive/ArchiveInstanceMetaDataService.java

Merge 2.55.0 into 2.56.0

---

common/src/main/java/com/sequenceiq/cloudbreak/quartz/TracedQuartzJob.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/JobMetricsListener.java

Log warning when quartz takes long time. Categorize it to >30s, 15s-30s, 5s-15s.

CB-16828 Log warning when quartz takes long time.

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/cache/UmsResourceRolesCache.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java

CB-16851 fix paging and caching of UMS role/resource role query

---

core/src/main/java/com/sequenceiq/cloudbreak/filter/WorkspaceConfiguratorFilter.java
core/src/test/java/com/sequenceiq/cloudbreak/filter/WorkspaceConfiguratorFilterTest.java

to find out if CB user getOrCreate or SpringSecurityContext gives back wrong user

CB-16391 added even more logs WorkspaceConfiguratorFilter

---

core/src/test/java/com/sequenceiq/cloudbreak/service/stack/archive/ArchiveInstanceMetaDataServiceTest.java

CB-14959  ArchiveInstanceMetaDataService covered with unit tests

---

core/src/main/resources/defaults/clustertemplates/7.2.14/gcp/dde.json
core/src/main/resources/defaults/clustertemplates/7.2.15/gcp/dde.json
core/src/main/resources/defaults/clustertemplates/7.2.16/gcp/dde.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

For feature parity with AWS and Azure, and to complete DH features for CDP on GCP, add data discovery template on GCP.

CDPD-30883 Support Data discovery Datahub template on GCP

---

common/src/main/java/com/sequenceiq/cloudbreak/util/Benchmark.java
core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java

Log CM call durations in status checker job. This will help us setting correct timeout values in the future.

CB-16701 Log CM call durations in status checker job

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java

CB-16510 Fix custom configurations runtime version issue

---

usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/http/UsageHttpRecordWorker.java

CB-16929. Do not log payload for usage if no logging strategy is set

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/DeregisterServicesHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/DeregisterServicesHandlerTest.java

Merge 2.56 to master

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java

Until CB-15454 is fixed to reduce test flakiness the first test failure is ignored.
The chance of happening right now is pretty small, but for long runnig stuff lik cleanup or usersync it can happen.
It's possible the customer would observe the same issue, but a retry would help them to recover from such an issue.

CB-16966 Ignore first test failuire for FreeIPA upgrade

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-zone-coordinates.json
cloud-aws-common/src/main/resources/definitions/aws-zone-coordinates.json

CB-16935 enable K8S support flag from AWS US GOV regions

---

core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterCommonServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

Prevent the followings:
- Autotls cert rotation
- Upgrade

CB-15146 prevent some action if there are stopped nodes in the cluster

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentStartStopTest.java

CB-16931 ignore related flaky test until it gets fixed

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/projection/StackInstanceCount.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperations.java

Theoretically it shouldn't be null and the fields shouldn't be null neither.

CB-16996 Add log and null check to instance count validation for upgrade

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRecommendationService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxRecommendationServiceTest.java

CB-17089 Skip SDX instance type validation on YCLOUD

---

freeipa/src/main/java/com/sequenceiq/freeipa/repository/ResourceRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/cloud/CloudResourceRetrieverService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/resource/ResourceService.java

Fix missing resource implementation which causing downscale failure in case of `AWS_NATIVE` variant

CB-17091 FreeIPA upgrade support from Native to Native variant

---

datalake/src/main/java/com/sequenceiq/datalake/flow/chain/DatalakeResizeFlowEventChainFactory.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/DistroxService.java
datalake/src/test/java/com/sequenceiq/datalake/flow/chain/DatalakeResizeFlowEventChainTest.java

CB-17100: Trigger restore on datalake resize when RAZ is enabled.

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/aws/FreeIpaAwsNetworkProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/cloud/CloudResourceRetrieverService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-native-tests.yaml

- adjust FreeIPA creation to support multi az/AWS_NATIVE
- add freeipa upgrade to native long running tests
- implement method in `CloudResourceRetrieverService

CB-17091 Add native e2e test for freeipa upgrade

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupServiceTest.java

After the runtime upgrade the instances are running with the old image.
While we're not performing a repair or an OS upgrade the image can be overwritten to the new image by a stop-start or an upscale flow.
This can cause that the cluster is still running with the old instances and we're not offering the OS upgrade.

CB-17085: The image in InstanceMetadata is overwritten after the runime upgrade

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/database/base/DatabaseType.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/externaldatabase/SupportedDatabaseProvider.java
core-api/src/main/resources/definitions/exposed-services.json
core-api/src/test/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollectorTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/QueryProcessorRdsConfigProvider.java
core/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/7.2.15/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.15/cdp-data-engineering.bp
custom-configurations/src/main/java/com/sequenceiq/cloudbreak/validation/AllServiceTypes.java
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryStoreRoles.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProviderTest.java
template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/views/GatewayViewTest.java

Testing: I have done end-to-end testing and found that it's working as expected.

[Hue] - CDPD-32891 - Cloudbreak Template change for QP

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

CB-17155: DL resize should not allowed for GCP.

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-cb-policy.json
cloud-aws-common/src/main/resources/definitions/aws-cb-policy.json

Merge 256 into 257

---

authorization-common/src/test/java/com/sequenceiq/authorization/EnforcePropertyProviderTestUtil.java

CB-16328 authz enforce logic should handle repeatable annotations too

---

datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/DatalakeBackupActions.java

JIRA: https://jira.cloudera.com/browse/CDPSDX-3537
Remove misleading status updates from, database backup.
Tested locally:
- resize test passed
- backup test passed

CDPSDX-3537: remove invalid state update from database backup

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/security/authentication/AuthenticatedUserService.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/security/authentication/AuthenticationService.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/security/authentication/DisabledAuthenticationService.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/security/authentication/UmsAuthenticationService.java
autoscale/src/main/java/com/sequenceiq/periscope/config/SecurityConfig.java
autoscale/src/main/java/com/sequenceiq/periscope/filter/AuditFilter.java
autoscale/src/main/java/com/sequenceiq/periscope/filter/CloudbreakUserConfiguratorFilter.java
autoscale/src/test/java/com/sequenceiq/periscope/filter/AuditFilterTest.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/configuration/security/SecurityConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/filter/CloudbreakUserConfiguratorFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/filter/WorkspaceConfiguratorFilter.java
core/src/test/java/com/sequenceiq/cloudbreak/filter/WorkspaceConfiguratorFilterTest.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/SecurityConfig.java
environment/src/main/java/com/sequenceiq/environment/configuration/security/SecurityConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/configuration/SecurityConfig.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/config/SecurityConfig.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/config/SecurityConfig.java
redbeams/src/main/java/com/sequenceiq/redbeams/configuration/SecurityConfig.java

CB-16391 do not use spring security context to get cloudbreakuser

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/service/RoleCrnGenerator.java
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/service/RoleCrnGeneratorTest.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/OwnerAssignmentService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/AltusMachineUserService.java
autoscale/src/test/java/com/sequenceiq/periscope/service/AltusMachineUserServiceTest.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentServiceTest.java

2.58 to master

---

common/src/main/resources/common-config.yml

CB-16443. Use public cdp-infra-tools link for rpm repo

---

core/src/main/resources/defaults/blueprints/7.2.16/cdp-sdx-medium-ha-profiler.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-sdx-micro.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-sdx.bp

CDPD-34041: Standardise compaction configuration across all form factors

CDPD-34515: SDX/DataLake compaction configs update

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/polling/StatusCheckerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerApiCheckerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerStartupListenerTask.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerStartupListenerTaskTest.java

CB-17326 improve cm echo api timeout message

---

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfigView.java

CB-17044. Addendum - fix broken vmagent disk usage setting.

---

core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering.bp

CDPD-34041: Standardize compaction configuration across all form factors

CDPD-34514: DataHub compaction configs update

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/ModelDescriptions.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxRepairRequest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRepairService.java
datalake/src/main/java/com/sequenceiq/datalake/settings/SdxRepairSettings.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxRepairServiceTest.java

CB-17223 deleteVolumes flag should be introduced for SDX repair

---

environment/src/main/resources/application.yml

CB-17165 Remove anonymization of principals from logs

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java

The counterpart permission is added to thunderhead repo in
https://github.infra.cloudera.com/thunderhead/thunderhead/commit/70158ff19302191eb06058b990baee1eebde7097

CB-14648 New upgradeCCM permission

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackImageService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackImageServiceTest.java

CB-17388 Fix infinite loop in case of custom image not found and disable change catalog for custom image catalog

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/recipe/UploadUpscaleRecipesHandler.java

CB-17423. Recipes are not re-uploaded on master repair

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java

See
https://github.infra.cloudera.com/thunderhead/thunderhead/pull/8553#pullrequestreview-162767

CB-14648 Harrison Sheinblatt did not like the naming

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-enabled-availability-zones.json
cloud-aws-cloudformation/src/main/resources/definitions/aws-zone-coordinates.json
cloud-aws-cloudformation/src/main/resources/definitions/aws-zone-displaynames.json
cloud-aws-cloudformation/src/main/resources/definitions/zones.json
cloud-aws-common/src/main/resources/definitions/aws-enabled-availability-zones.json
cloud-aws-common/src/main/resources/definitions/aws-zone-coordinates.json
cloud-aws-common/src/main/resources/definitions/aws-zone-displaynames.json
cloud-aws-common/src/main/resources/definitions/zones.json

Merge 2.58.0 into master

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpscaleFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/CmSyncTriggerEvent.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/ParcelGeneratorUtil.java

Reverts hortonworks/cloudbreak#12860

Revert "CB-14321: Call the CM syncer before upscale"

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

ENGESC-14953 Recipe addition failure in datalake - user not found

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/StartStackHandler.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/StopStackHandler.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceService.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceStopStartCallable.java

CB-17483 Improve logging during the stack start/stop on GCP

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilderTest.java

Reverts hortonworks/cloudbreak#12853

Revert "CB-15512 Set DeleteOnTermination to false on repair explicitly for AWS"

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/datalake/RecipeTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/freeipa/RecipeTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/NewNetworkWithNoInternetEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/DistroXRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/InternalSdxSshAndCmAccessTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxRepairWithRecipeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/PreconditionSdxE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRecipeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRecoveryTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxSecurityTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/FreeIpaCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RecipeClusterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/RecipeUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/SshJUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java

Extending already existing FreeIPA provisioning E2E test cases with recipe related steps and validations.

CB-17184 Extend already existing FreeIPA provisioning testcase with recipes

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceType.java
environment/src/main/java/com/sequenceiq/environment/authorization/ProxyFiltering.java
environment/src/main/java/com/sequenceiq/environment/proxy/repository/ProxyConfigRepository.java
environment/src/main/java/com/sequenceiq/environment/proxy/service/ProxyConfigService.java
environment/src/main/java/com/sequenceiq/environment/proxy/v1/controller/ProxyController.java
environment/src/test/java/com/sequenceiq/environment/proxy/v1/ProxyTestSource.java
environment/src/test/java/com/sequenceiq/environment/proxy/v1/service/ProxyConfigServiceTest.java
environment/src/test/java/com/sequenceiq/environment/service/integration/EnvironmentServiceIntegrationTest.java
integration-test/README.md
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/proxy/ProxyConfigListAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/ProxyTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/proxy/ProxyTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ums/UmsTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/ProxyTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ProxyConfigTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/AuthorizationTestUtil.java
integration-test/src/main/resources/testsuites/v4/mock/real-ums-mock-tests.yaml

CB-12878 EnvironmentCreator should be able to create and delete ProxyConfigurations

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/setup/GcpProvisionSetup.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/setup/GcpProvisionSetupTest.java

We fetch all image but the Google respond with the first 500. If the image was not in the list we copied even if the image already exists. Now we try to fetch by image name and project id

CB-17454 The GCP image discover was not work properly. 

---

core-common/src/main/java/com/sequenceiq/cloudbreak/recipe/RecipeCrnListProviderService.java
core-common/src/test/java/com/sequenceiq/cloudbreak/recipe/RecipeCrnListProviderServiceTest.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/recipe/EnvironmentRecipeService.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/recipe/FreeIpaRecipeService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/recipe/FreeIpaRecipeServiceTest.java

CB-17498 Validate if all recipes exists on environment post request

---

core-api/src/main/java/com/sequenceiq/cloudbreak/doc/Notes.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/doc/DistroXOpDescription.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1EventEndpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1EventController.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1EventControllerTest.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/CloudbreakEventService.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredEventType.java

CB-16228 Created notification endpoint for data hubs.

---

common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/Telemetry.java
common/src/main/java/com/sequenceiq/cloudbreak/message/CloudbreakMessagesService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/job/nodestatus/NodeStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/node/status/NodeStatusService.java
core/src/test/java/com/sequenceiq/cloudbreak/job/nodestatus/NodeStatusCheckerJobTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/Stack.java
freeipa/src/main/java/com/sequenceiq/freeipa/nodestatus/NodeStatusJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaNodeStatusService.java
freeipa/src/test/java/com/sequenceiq/freeipa/entity/StackTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/nodestatus/NodeStatusJobTest.java
node-status-monitor-client/src/main/java/com/sequenceiq/node/health/client/CdpNodeStatusMonitorClient.java
node-status-monitor-client/src/main/java/com/sequenceiq/node/health/client/model/CdpNodeStatusRequest.java

CB-17443 Changed node status checker jobs to get only the network metrics if common monitoring is enabled.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxCustomTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/gov/BasicDistroXTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/gov/BasicEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/gov/BasicFreeIpaTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/gov/BasicSdxTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/gov/GovUserKeys.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/gov/PreconditionGovTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudbreakUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/cloudbreak/CloudbreakWaitObject.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/e2e/gov/aws-gov-tests.yaml

Upgrade existing API test project to GOV-Cloud testing. Furthermore a new GOV-Cloud Sanity test suite has been introduced.

CB-17097 Create new test cases and upgrade test project for GOV Dev testing

---

core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCommonService.java

CB-17493 Enable downscale when cluster is in NODE_FAILURE state

---

freeipa/src/main/java/com/sequenceiq/freeipa/util/AvailabilityChecker.java
freeipa/src/test/java/com/sequenceiq/freeipa/util/AvailabilityCheckerTest.java

CB-16706 Handle ImageNotFoundException when checking package version

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/FlowChainTriggers.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeCcmFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/ccm/upgrade/UpgradeCcmService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/userdata/AbstractUserDataUpdateAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/userdata/UpdateUserDataEvents.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/userdata/UpdateUserDataFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/userdata/UpdateUserDataState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/userdata/UserDataUpdateActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/userdata/UserDataUpdateFailureHandlerAction.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ccm/AbstractUpgradeCcmEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ccm/UpgradeCcmFlowChainTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ccm/UpgradeCcmTriggerRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/userdata/UserDataUpdateFailed.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/userdata/UserDataUpdateOnProviderRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/userdata/UserDataUpdateOnProviderResult.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/userdata/UserDataUpdateRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/userdata/UserDataUpdateSuccess.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/userdata/UpdateUserDataHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/userdata/UpdateUserDataOnProviderHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/userdata/UserDataService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeCcmFlowChainIntegrationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/userdata/FlowIntegrationTestConfig.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/userdata/UpdateUserDataFlowIntegrationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/userdata/UserDataServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ccm/StackCcmUpgradeServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/userdata/UserDataService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/userdata/UserDataServiceTest.java

CB-14594 Create Flow chain and implement userdata update flow

---

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/clouderamanager-ssl-user-facing.conf

ENGESC-15134 add X-Forwarded-For to nginx config

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidator.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidatorTest.java

Fix of the storage validation bug on Azure. Added the filesystem to the scopes to check,

CB-17487 [Azure] Permissions check on environment creation.

---

datalake/src/main/java/com/sequenceiq/datalake/entity/SdxCluster.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxEventParameterFactory.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/loadbalancer/dns/UpdateLoadBalancerDNSActions.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxNotificationService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/cert/CertRenewalService.java
datalake/src/main/resources/schema/app/20220623171204_CB-17551_Deprecate_initiatorusercrn.sql
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifesterTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/ProvisionerServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxRecoveryServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxRepairServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/attach/SdxAttachServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/cert/CertRenewalServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/flowcheck/CloudbreakFlowServiceTest.java

CB-17551 Deprecate initiatorusercrn field and do not use it

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/userdata/UserDataUpdateActions.java

CB-14594 fixing userdata finishing state create request

---

environment/src/main/java/com/sequenceiq/environment/environment/domain/Environment.java
environment/src/main/java/com/sequenceiq/environment/environment/domain/EnvironmentTags.java
environment/src/main/java/com/sequenceiq/environment/environment/domain/EnvironmentView.java
environment/src/main/java/com/sequenceiq/environment/environment/domain/ExperimentalFeatures.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java
environment/src/test/java/com/sequenceiq/environment/environment/domain/EnvironmentTagsTest.java
environment/src/test/java/com/sequenceiq/environment/environment/domain/ExperimentalFeaturesTest.java
environment/src/test/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverterTest.java

Merge 259 to master

---

orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltTelemetryOrchestratorTest.java

Increased unit test coverage of SaltTelemetryOrchestrator from ~10% to ~80%

CB-17585 - Increase SaltTelemetryOrchestrator unit test coverage

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/Crn.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/CrnResourceDescriptor.java
common/src/test/java/com/sequenceiq/cloudbreak/auth/crn/CrnTestUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/service/recipe/RecipeServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/AuthorizationTestUtil.java

CB-17467 Recipe crn should not have datahub word in it

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ccm/StackCcmUpgradeService.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentOpDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentInternalEndpoint.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentInternalV1Controller.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/EnvironmentInternalV1ControllerTest.java

Its result will be used in the Environment service to decide whether the notification
should be displayed to the end user on the UI

CB-17598 Query Non CCM-upgraded stack count

---

common/src/main/java/com/sequenceiq/cloudbreak/cache/common/AbstractNoTtlCacheDefinition.java
common/src/main/java/com/sequenceiq/cloudbreak/common/domain/IdAware.java
common/src/main/java/com/sequenceiq/cloudbreak/monitoring/MonitoringEnablementCache.java
common/src/main/java/com/sequenceiq/cloudbreak/monitoring/MonitoringEnablementService.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJobTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/Stack.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/StackServiceTest.java
metrics-client/src/main/java/com/sequenceiq/cloudbreak/metrics/MetricsClient.java
metrics-client/src/test/java/com/sequenceiq/cloudbreak/metrics/MetricsClientTest.java

CB-17546 Extends cb_cluster_state metric with compute monitoring setting

---

core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelAvailabilityService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelAvailabilityServiceTest.java

CB-17411 When CM server rpm is not accessible show a different message

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/endpoint/ConsumptionInternalV1Controller.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/endpoint/ConsumptionInternalV1ControllerTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentOpDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/EnvironmentControllerTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/AuthDistributorService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/AuthDistributorServiceTest.java

Merge 2.59 to master

---

README.md

CB-16677 Extend Cloudbreak README with Consumption service setup

---

integration-test/scripts/analyse_postgres_stat.jsh
integration-test/scripts/check-results.sh

CB-17715 Improve postgres network traffic output message in IT

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/Crn.java

CB-17734 Recipe error when creating an environment

---

environment/src/main/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaServiceTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/RotateSaltPasswordActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/RotateSaltPasswordEvent.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/RotateSaltPasswordFlowConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/RotateSaltPasswordState.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/event/RotateSaltPasswordFailureResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/event/RotateSaltPasswordRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/event/RotateSaltPasswordSuccessResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/handler/RotateSaltPasswordHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/orchestrator/RotateSaltPasswordService.java
freeipa/src/test/java/com/sequenceiq/freeipa/controller/FreeIpaV1ControllerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/salt/rotatepassword/handler/RotateSaltPasswordHandlerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/orchestrator/RotateSaltPasswordServiceTest.java

Environment proxy call is no longer needed, so it was removed.

CB-17515 Rotate freeipa saltuser password in a flow

---

structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterUseCaseMapper.java
usage-collection/src/main/proto/usage.proto

JIRA: https://jira.cloudera.com/browse/CB-16641
Add telemetry data collection to the datalake resize flow.

JIRA: CB-16641 ; Add telemetry data collection to the datalake resize flow

---

core/src/main/java/com/sequenceiq/cloudbreak/repository/cluster/ClusterRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxBlueprintLoadTests.java

CB-17779 Cannot update databusCredential because IllegalStateException was occurred

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java

CB-17783 Create a datahub in an existing environment during the test

---

core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderServiceTest.java

CB-17782 Resource fetch is disabled in Azure

---

core-model/src/main/java/com/sequenceiq/cloudbreak/dto/StackDto.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackDtoService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderServiceTest.java

CB-17787 Cannot update Cluster becuase grain append was unsuccessful

---

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfiguration.java
common/src/main/resources/common-config.yml
metrics-client/src/main/java/com/sequenceiq/cloudbreak/metrics/processor/MetricsProcessorConfiguration.java

CB-17786. Add internal remote write endpoint for compute monitoring.

---

integration-test/scripts/check-results.sh

Merge 2.60.0 into master

---

core/src/main/resources/application.yml

CB-17616 Disable PEM related stackpatcher by default

---

cloud-consumption-api/src/main/java/com/sequenceiq/consumption/api/v1/consumption/endpoint/ConsumptionInternalEndpoint.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/endpoint/ConsumptionInternalV1Controller.java

CB-17812 Enable machine_user as the user for consumption operations

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/instancegroup/InstanceGroupV4RequestToInstanceGroupConverter.java

CB-17724 Forbid scale of gateway group

---

core/src/main/java/com/sequenceiq/cloudbreak/service/AbstractWorkspaceAwareResourceService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeipaClientService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/recipe/RecipeService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/AbstractWorkspaceAwareResourceServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/recipe/RecipeServiceTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiEndpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/internal/FreeIpaApiClientConfig.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/util/UtilV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/util/doc/UtilDescriptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/UtilV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/FreeIpaStackRecipeRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/recipe/FreeIpaRecipeService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/recipe/FreeIpaRecipeServiceTest.java

CB-17499 Prevent recipe deletion if it is used for a freeipa

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java

CB-17655 Fix integration test to not wait for host group if exception happened.

---

cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/poller/PollerUtilTest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/poller/PollerUtil.java

CB-17749 better error message if the operation timed out on AWS

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/catalog/model/ImageCatalogPlatform.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ImageFilterParamsFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ImageFilterParams.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/CloudPlatformBasedUpgradeImageFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/CmAndStackVersionUpgradeImageFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/EntitlementDrivenPackageLocationFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/IgnoredCmVersionUpgradeImageFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/ImageCreationBasedUpgradeImageFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/ImageNameUpgradeImageFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/NonCmUpgradeImageFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/OsVersionBasedUpgradeImageFilter.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ImageFilterParamsFactoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePermissionProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/BlueprintBasedUpgradeValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/CsdLocationFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/PreWarmParcelLocationFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/CloudPlatformBasedUpgradeImageFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/CmAndStackVersionUpgradeImageFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/CurrentImageUpgradeImageFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/ImageCreationBasedUpgradeImageFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/ImageNameUpgradeImageFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/OsVersionBasedUpgradeImageFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/UpgradeImageFilterConfigTest.java

CB-17731 Filter upgrade candidate images by image name availability.

---

orchestrator-salt/src/main/resources/salt-common/salt/monitoring/scripts.sls
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/scripts/instanceid_retriever.py
orchestrator-salt/src/main/resources/salt-common/salt/monitoring/template/prometheus.yml.j2

CB-17769. Use instance id/name instead of hostnames for metrics.

---

common/src/main/java/com/sequenceiq/cloudbreak/quartz/statuschecker/StatusCheckerConfig.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/statuschecker/service/StatusCheckerJobService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/PackageName.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/RecipeEngine.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ccm/StackCcmUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmVersionQueryService.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ccm/StackCcmUpgradeServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/component/CmVersionQueryServiceTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStateService.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStateServiceTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/exception/DatabaseStartFailedException.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/start/handler/StartDatabaseServerHandler.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/start/handler/StartDatabaseServerHandlerTest.java

Merge260tomaster

---

metrics-client/src/main/java/com/sequenceiq/cloudbreak/metrics/MetricsClient.java
metrics-client/src/test/java/com/sequenceiq/cloudbreak/metrics/MetricsClientTest.java

CB-17901. Labels for prometheus remote write needs to be ordered.

---

orchestrator-salt/src/main/resources/salt-common/salt/monitoring/stop.sls

CB-17816. Added salt stop state for monitoring salt states.

---

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/SdxDeleteActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/refresh/DatahubRefreshActions.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowChainLogService.java
flow/src/test/java/com/sequenceiq/flow/service/flowlog/FlowChainLogServiceTest.java

CB-17735: Generate event when resize is complete.

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStateService.java

CB-17771 Fix targeting of targeted reachability salt check

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/OperationV4Controller.java

Probably was a copy-paste error.

CB-17683 : Fixed Data Hub's getOperation endpoint using Data Lake permission check

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidator.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidatorTest.java
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/fluent/cloud/AdlsGen2ConfigGeneratorTest.java

Tests performed:
1. In the local development environment, I made sure that permissions in on backup location are also validated when the environment is created.
2. Validated both success and failure cases
3. Validated to make sure that there are no regressions introduced on existing validations.

CB-17434: [Azure][pre-check] Backup/restore permissions on environment creation.

---

.github/CODEOWNERS

Duck team code ownership for freeipa and redbeams modules

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/recovery/bringup/DatalakeRecoveryBringupActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeActions.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ImageComponentUpdaterService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ImageComponentUpdaterServiceTest.java

Reverts hortonworks/cloudbreak#13156

Revert "Revert "CB-17896 After a failed and fixed upgrade component versions are not …""

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/PlatformStringTransformer.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/PlatformStringTransformerTest.java

https://github.com/hortonworks/cloudbreak/pull/13029

Cherry pick CB-17732 to avoid alerts on mowint

---

core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java

CB-17740 Change the load balancer enabled entitlement check.
We have to check the `loadBalancerEnabled` entitlement for all cloud providers

CB-17740; change the load balancer enabled entitlement check

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsObjectStorageConnector.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsIDBrokerMappedRolePermissionValidator.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsIDBrokerObjectStorageValidator.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsLogRolePermissionValidator.java
common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxBackupLocationValidationRequest.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StorageValidationService.java
datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidator.java
datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxControllerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StorageValidationServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidatorTest.java
datalake/src/test/resources/stackRequest.json
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentBaseResponse.java
mock-thunderhead/src/main/resources/application.yml

Testing Performed:
1. Made sure that validations are performed on the creation of environment and datalake.
2. Made sure that permissions validations are performed on the backup location when the appropriate datalake API is triggered.

CB-17232: [pre-check] Implement new data lake API to trigger permission validation backup location.

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/InternalUpgradeSettings.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperations.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/StackUpgradeOperationsTest.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeController.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeControllerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java

CB-17956 Remove Datahub validation from Datalake upgrade preparation

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/polling/PollingService.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/polling/StatusCheckerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerApiCheckerTask.java

 CB-17935 "Service Unavailable" from CM APIs should likely use an exponential backoff retry policy

---

datalake/src/main/java/com/sequenceiq/datalake/events/EventSenderService.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/recovery/DatalakeUpgradeRecoveryActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/SdxDeleteActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/DatalakeBackupActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/DatalakeRestoreActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/loadbalancer/dns/UpdateLoadBalancerDNSActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/refresh/DatahubRefreshActions.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StorageValidationService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/stop/SdxStopService.java
datalake/src/test/java/com/sequenceiq/datalake/flow/SdxReactorFlowManagerTest.java
datalake/src/test/java/com/sequenceiq/datalake/flow/datalake/recovery/DatalakeUpgradeRecoveryActionsTest.java
datalake/src/test/java/com/sequenceiq/datalake/flow/loadbalancer/dns/UpdateLoadBalancerDNSActionsTest.java

CB-17955 Cleanup unused usercrn parameter from EventSenderService in DL service

---

cloud-consumption/src/main/java/com/sequenceiq/consumption/ConsumptionApplication.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/configuration/api/EndpointConfig.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/swagger/SwaggerGenerator.java
integration-test/scripts/build-swagger.sh
integration-test/scripts/swagger-check.sh
scripts/build-dev.sh

CB-17306 Add consumption-api checks to CI swagger-compatibility-test

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/cluster/gateway/GatewayV4Response.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/gateway/GatewayToGatewayV4ResponseConverter.java

CB-16834 adding the knox signing key to gateway response

---

orchestrator-salt/src/main/resources/salt-common/salt/monitoring/template/cdp-request-signer.yaml.j2

CB-18028. Use resource crn and instance header for request signer.

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserStateDifferenceCalculator.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UsersStateDifferenceCalculatorTest.java

CB-18056 calculateUsersToAdd fail if two user has the same email prefix

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureObjectStorageConnector.java

CB-18042 Fixed AzureObjectStorageConnector to anonymize request and not log the secret key.

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/RestUrlParserTest.java

CB-16568 missing path on imagecatalog endpoint

---

freeipa/src/main/java/com/sequenceiq/freeipa/nodestatus/NodeStatusJob.java

CB-18077. System metrics are not logged properly by Node status job.

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/Cluster.java
core-model/src/main/java/com/sequenceiq/cloudbreak/view/ClusterView.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ClusterToClusterV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterDtoRepository.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/cluster/ClusterToClusterV4ResponseConverterTest.java

CB-18044 modifing the removed logic from the refactor.

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/recipes/RecipeV4Base.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/recipes/requests/RecipeV4Type.java

CB-17189 Add two new enums to avoid swagger compatibility check problems

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/service/ScalingException.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core-model/src/main/java/com/sequenceiq/cloudbreak/dto/StackDto.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/UpscaleClusterHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandlerTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterFaultTolerantUpscaleTest.java

CB-17934 Failed scale up left hosts in INSTANCE_CREATED state, and the cluster moved to "RUNNING" state

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/recipes/RecipeV4Base.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/recipes/requests/RecipeV4Type.java
freeipa/src/main/java/com/sequenceiq/freeipa/nodestatus/NodeStatusJob.java

2.60 merge

---

core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java

CB-17189 modify recipe type description to more common

---

core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/EnvironmentReactorFlowManager.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentDeletionService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaPollerService.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/EnvironmentReactorFlowManagerTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentDeletionServiceTest.java

Cb 2.60.0 merge

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/view/InstanceMetaDataView.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/RestUrlParserTest.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java
environment/src/test/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentModificationServiceTest.java

CB-17983 , CB-18036 Several fix from the backlog

---

core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetadataServiceComponentTest.java

CB-17939 In this PR, the privateId generation is optimized

---

core-model/src/main/java/com/sequenceiq/cloudbreak/view/StackView.java

CB-18135 Stack and StackView isStartInProgress are mismatch

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
datalake/src/main/java/com/sequenceiq/datalake/entity/SdxCluster.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxEventParameterFactory.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/cert/CertRenewalService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/cert/CertRenewalServiceTest.java

Should be merged when 2.60 is branched

CB-17552 Remove initiatorusercrn field from sdx service sdxcluster entity

---

datalake/src/main/java/com/sequenceiq/datalake/service/SdxEventsService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxEventsServiceTests.java

2.61 to master

---

datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxUpgradeTests.java

CB-17712 Check the backup before the resize

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetaDataCollectorTest.java

Merge 260 to 261

---

common/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AccountMappingSubject.java

More details: https://jira.cloudera.com/browse/CDPCP-7335

CB-18172 Add "ssb" to the IDBroker data admin role mappings

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetaDataCollectorTest.java

Merge 2.61 to master

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtTelemetryService.java

details:
- set prometheus_adapter_enabled property in case of Cm/CDH version is at least 7.2.16
- covered in UT, but it's not validated the line is called or not, for achieving that, some refactoring will be required later.

CB-18199. Enable CM Prometheus adapter in SaaS.

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/poller/DatabasePollerService.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/poller/GcpDatabasePollerProvider.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpDatabaseBaseResourceChecker.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/AbstractGcpDatabaseServerStartStopService.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerBaseService.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerCheckService.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerLaunchService.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerStartService.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerStopService.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerTerminateService.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerUpgradeService.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerBaseServiceTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerLaunchServiceTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerUpgradeServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java

CB-17554 Postgres upgrade implementation for GCP provider

CB-17554 Postgres upgrade implementation for GCP provider

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4Controller.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4ControllerTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knox-of-0.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knox-of-2.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knoxes-of-0-0.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knoxes-of-0-2.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knoxes-of-1-1-2.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knoxes-of-1-2-3.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knoxes-of-1-2.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knoxes-of-2-2.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-with-knox.bp

Please be sure to use Merge commit instead of Rebase!

CB-18195 merge to 2.61

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4Controller.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4ControllerTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knox-of-0.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knox-of-2.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knoxes-of-0-0.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knoxes-of-0-2.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knoxes-of-1-1-2.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knoxes-of-1-2-3.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knoxes-of-1-2.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker-with-knoxes-of-2-2.bp
template-manager-cmtemplate/src/test/resources/input/namenode-ha-with-knox.bp

Please be sure to use a Merge commit, instead of Rebase!

CB-18195 merge to master

---

core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterServiceTest.java

The logic were we trying to determine the required parcels for the cluster and was not handling the base images properly.
This fix contains that when we using base image then we'll mark every parcel in the request as required because we're unable to determine which parcel is custom.

CB-18089: Fix the parcel filter when the cluster is using base image.

---

structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/FreeIpaUseCaseMapper.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterUseCaseMapper.java
usage-collection/src/main/proto/usage.proto

CB-18143 CB-18144 add ccm flows to edh

---

core/src/main/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorServiceTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java

CB-17631 Remove allNodes member from OrchestratorStateParams

CB-17631 Remove allNodes member from OrchestratorStateParams

---

cloud-consumption/src/main/java/com/sequenceiq/consumption/configuration/repository/ConsumptionRepository.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/converter/metering/ConsumptionToStorageHeartbeatConverter.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/endpoint/ConsumptionInternalV1Controller.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/flow/consumption/storage/handler/StorageConsumptionCollectionHandler.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobInitializer.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobService.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/service/ConsumptionService.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/util/CloudStorageLocationUtil.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/converter/metering/ConsumptionToStorageHeartbeatConverterTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/endpoint/ConsumptionInternalV1ControllerTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/flow/consumption/storage/handler/StorageConsumptionCollectionHandlerTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobInitializerTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobServiceTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/service/ConsumptionServiceTest.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/util/CloudStorageLocationUtilTest.java

CB-26.1.0 merge to master

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/BlueprintUtilV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4ControllerTest.java

CB-18208 Create an environment based recommendation endpoint

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/filesystem/CloudAdlsGen2View.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/filesystem/CloudAdlsView.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/filesystem/CloudEfsView.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/filesystem/CloudGcsView.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/filesystem/CloudS3View.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/filesystem/CloudWasbView.java
common-model/src/main/java/com/sequenceiq/common/model/diagnostics/CloudStorageDiagnosticsParameters.java

Missed Interface subtypes deserialization

CB-18251 Even more Jackson fix

---

datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxNotificationService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/status/SdxStatusService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/status/SdxStatusServiceTest.java

Jira: https://jira.cloudera.com/browse/CB-18176
Objective of this was to simply use the method in the `EventSenderService` instead of what we were using before.

CB-18176: Added use of the eventSenderService's sendEventAndNotification method in the SdxStatusService instead of just the send notification method.

---

core/src/main/java/com/sequenceiq/cloudbreak/service/StackUpdater.java

See detailed description in the commit message.CB-17631 Fix DB version upgrade in CB DB.

CB-17631 Fix DB version upgrade in CB DB.

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-enabled-availability-zones.json
cloud-aws-cloudformation/src/main/resources/definitions/aws-zone-coordinates.json
cloud-aws-cloudformation/src/main/resources/definitions/aws-zone-displaynames.json
cloud-aws-cloudformation/src/main/resources/definitions/zones.json
cloud-aws-common/src/main/resources/definitions/aws-enabled-availability-zones.json
cloud-aws-common/src/main/resources/definitions/aws-zone-coordinates.json
cloud-aws-common/src/main/resources/definitions/aws-zone-displaynames.json
cloud-aws-common/src/main/resources/definitions/zones.json
cloud-consumption/src/main/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJob.java
cloud-consumption/src/test/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobTest.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/TracedQuartzJob.java
common/src/test/java/com/sequenceiq/cloudbreak/quartz/TracedQuartzJobTest.java
common/src/test/java/com/sequenceiq/cloudbreak/quartz/TracedQuartzJobTestClass.java
core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/altus/CloudbreakUMSCleanupJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/instancemetadata/ArchiveInstanceMetaDataJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/nodestatus/NodeStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/salt/StackSaltStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJob.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/job/StructuredSynchronizerJob.java
datalake/src/main/java/com/sequenceiq/datalake/job/SdxClusterStatusCheckerJob.java
environment/src/main/java/com/sequenceiq/environment/environment/sync/EnvironmentStatusCheckerJob.java
flow/src/main/java/com/sequenceiq/flow/cleanup/FlowCleanupJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/altus/FreeIpaUMSCleanupJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/nodestatus/NodeStatusJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/saltstatus/StackSaltStatusCheckerJob.java
redbeams/src/main/java/com/sequenceiq/redbeams/sync/DBStackStatusSyncJob.java

Merge CB-2.61.0 into master

---

integration-test/scripts/check-results.sh

CB-18305 Increase the postgres traffic value for temporary unblock Pr's

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/Cluster.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/AwsNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/AzureNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/BaseNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/GcpNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/MockNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/YarnNetwork.java
environment/src/main/java/com/sequenceiq/environment/parameters/dao/domain/AwsParameters.java
environment/src/main/java/com/sequenceiq/environment/parameters/dao/domain/AzureParameters.java
environment/src/main/java/com/sequenceiq/environment/parameters/dao/domain/BaseParameters.java
environment/src/main/java/com/sequenceiq/environment/parameters/dao/domain/GcpParameters.java

Missed Interface subtypes deserialization

CB-18315 Abstract classes Jackson fix

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/BlueprintUtilV4Endpoint.java

annotations added to Endpoint too

CB-18208 Create an environment based recommendation endpoint - fix

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiEndpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiKeyEndpoints.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiUserCrnEndpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaClient.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/internal/FreeIpaApiClientConfig.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/recipe/RecipeV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/recipe/doc/RecipeDescription.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/recipe/model/RecipeAttachDetachRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/configuration/EndpointConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/RecipeV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/handler/ExecutePreTerminationRecipesHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/FreeIpaStackRecipeRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/recipe/FreeIpaRecipeService.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/termination/handler/ExecutePreTerminationRecipesHandlerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/recipe/FreeIpaRecipeServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIpaAttachRecipeAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIpaDetachRecipeAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/FreeIpaTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/BaseImageValidatorE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/FreeIpaCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/FreeIpaRecipeDetachTest.java

CB-18207 freeipa recipe attach / detach feature

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

CB-18309 Modify grain command should not retry 180 times

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/common-install.sls

CB-18325 Removes hadcoded python version from ipaserver path.

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverterTest.java

Merge 261 to master

---

freeipa/src/main/resources/freeipa-salt/salt/top.sls
orchestrator-salt/src/main/resources/salt-common/salt/sshd/init.sls
orchestrator-salt/src/main/resources/salt/salt/top.sls

CB-18227: Added salt state to fix the ClientAliveInterval config of SSHD

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/pg11-install.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/repo/pg11.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/repo/postgres11-el7.repo

CB-18321 Use archive.cloudera.com to install Pg11

---

README.md

CB-17679 : Added section about running the mock-infrastructure in IDEA

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/freeipa/RecipeTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/recipe/RecipeTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaRecipeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/SshJUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/freeipa-recipe-tests.yaml
integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml

Create new test with the steps to attach and detach FreeIPA recipes. In the end validate the attached and detached recipes on FreeIPA.

CB-18304 Create or append existing e2e tests for freeipa attach, detach recipes

---

core/src/main/resources/defaults/clustertemplates/7.2.14/gcp/dde.json
core/src/main/resources/defaults/clustertemplates/7.2.15/gcp/dde.json
core/src/main/resources/defaults/clustertemplates/7.2.16/gcp/dde.json
core/src/main/resources/schema/app/20220831083250_CB-18120_rename_dde_templates_in_case_of_google.sql

CB-18120 rename dde template to be consistent on Google Cloud

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateServiceTest.java

CB-18366 fixing os upgrade in case of aws gov

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/ccm/upgrade/UpgradeCcmActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/ccm/upgrade/UpgradeCcmService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeCcmFlowChainIntegrationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/ccm/upgrade/UpgradeCcmFlowIntegrationTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/upgrade/ccm/UpgradeCcmService.java

CB-18363 FreeIPA Status Reason is extended for Upgrade CCM errrors

---

environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentEditRequest.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentEditDto.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverterTest.java
environment/src/test/java/com/sequenceiq/environment/network/NetworkServiceTest.java

For now just throw a NotImplementedException when proxy config is changed. The actual proxy config changing will be done under the subsequent tickets from epic "CB-18431 Edit environment proxy configuration".

CB-18432 Extend environment edit request with proxy config

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerApiCheckerTask.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerApiCheckerTaskTest.java

CB-18411 fix CM API checker task tolerated error message

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/BackupOperationType.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/objectstorage/ObjectStorageValidateRequest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsObjectStorageConnector.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsIDBrokerMappedRolePermissionValidator.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsIDBrokerObjectStorageValidator.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsDataAccessRolePermissionValidatorTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsRangerAuditRolePermissionValidatorTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureObjectStorageConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidator.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureObjectStorageConnectorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidatorTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/ModelDescriptions.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxBackupLocationValidationRequest.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StorageValidationService.java
datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidator.java
datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxControllerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StorageValidationServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidatorTest.java

CB-18406: Optimize the permission validation on backup location

---

core-model/src/main/java/com/sequenceiq/cloudbreak/view/ClusterView.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterDtoRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/customconfigs/CustomConfigurationsService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverterTest.java

The customConfigurations' projection missed in the ClusterView and the configurations relation is LAZY fetched, we need to fetch again.

CB-18457 Custom datahub creation with cluster template override not working

---

core-model/src/main/java/com/sequenceiq/cloudbreak/view/ClusterView.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterDtoRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/customconfigs/CustomConfigurationsService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverterTest.java

Merge261into262

---

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/databus/DatabusConfigService.java

CB-18505. Typo in databus pillar key name.

---

common/src/main/resources/common-config.yml

CB-18512. Disable cb_cluster_state metrics processing.

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Recipe.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/recipe/RecipeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/recipe/UpdateRecipeService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/recipe/RecipeServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/recipe/UpdateRecipeServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverterTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/recipe/FreeIpaRecipeService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/recipe/FreeIpaRecipeServiceTest.java
usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/UsageReportProcessor.java
usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/UsageReporter.java
usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/service/RecipeUsageService.java
usage-collection/src/main/proto/usage.proto
usage-collection/src/test/java/com/sequenceiq/cloudbreak/usage/service/RecipeUsageServiceTest.java

CB-18275 recipe usage feature tracking

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/util/poller/upgrade/UpgradeStartPoller.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/TestConfig.java
cloud-common/build.gradle
cloud-common/src/main/java/com/sequenceiq/cloudbreak/polling/Poller.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Privilege.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPermissionReplicatedPoller.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPermissionService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java
freeipa/src/main/resources/application.yml
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPermissionReplicatedPollerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPermissionServiceTest.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/freeipa/FreeipaController.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/freeipa/response/PrivilegeShowResponse.java

CB-18460 Poll permission replication for Host Enrollment privilege

---

integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-longrunning-e2e-tests.yaml

Jira: https://jira.cloudera.com/browse/CB-18478
I have verified that the test is working locally at the very least and am sure that the original issue faced during testing is resolved.

CB-18478: Re-enable the SDX resize recovery e2e tests.

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeService.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/operation/AwsRdsUpgradeValidatorService.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeServiceTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/operation/AwsRdsUpgradeValidatorServiceTest.java
common/src/main/java/com/sequenceiq/cloudbreak/client/RestClientUtil.java

Merge 2.62 to master

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/csd/csd-downloader.sh

The CSD downloader script is using a CURL command to download the required files. In order to access their files behind the paywall, we added an authentication flag for the CURL command. However, there are some internal repos that do not accept this auth header and the response will be a HTTP 400. In this command I improved the script to use the auth header only in case of archive.cloudera.com URL's.

CB-18515 CSD downloader should not use authentication in case of internal repos

---

core-model/src/test/java/com/sequenceiq/cloudbreak/clustertemplate/ClusterTemplateTestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/clustertemplate/ClusterTemplateV4RequestToClusterTemplateConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/clustertemplate/ClusterTemplateV4RequestToClusterTemplateConverterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/clustertemplate/DistroXTemplateTestDto.java

CB-18528 adding cluster template validation regarding group types

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/migration/handler/AwsMigrationUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/migration/handler/AwsMigrationUtilTest.java

The AWS API responds with an HTTP 404 error instead of an empty response. In this PR I have added the error handling and if the CF stack doesn't exist return with an empty response

CB-18498 Cannot process the AWS migration because cannot describe the deleted CF stack.

---

datalake/src/main/java/com/sequenceiq/datalake/flow/upgrade/database/UpgradeDatabaseServerActions.java

Merge 262 to master

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXBigScaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AzureMarketplaceImageTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/BasicEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/NewNetworkWithNoInternetEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/gov/BasicEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/gov/PreconditionGovTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/MonitoringTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentTest.java

CB-18577 use 1 freeipa node for not HA e2e tests

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java

CB-18234 make a separated right for vertical scaling

---

usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/service/RecipeUsageService.java
usage-collection/src/main/proto/usage.proto
usage-collection/src/test/java/com/sequenceiq/cloudbreak/usage/service/RecipeUsageServiceTest.java

CB-18275 recipe usage feature tracking - add account id to recipe events

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshSaltExecutionMetricsActions.java

This makes it possible to work with the Salt highstate reports, without having to parse them from the generated JSONs.
You can still write the reports to files by using the `writeSaltHighstateReportsToFiles` method.

CB-18587 Made writing Salt highstate reports to files a separate method, and cleaned the up code

---

datalake/src/main/resources/schema/app/20220630110836_CB-17527_remove_initiatorusercrn.sql

CB-17552 Remove initiatorusercrn field from sdx service sdxcluster table

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsPlatformResources.java
config/checkstyle/checkstyle-suppressions.xml
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/BlueprintUtilV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/template/ClusterTemplateService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4ControllerTest.java

Reverts hortonworks/cloudbreak#13411

Revert "CB-18536 Gateway recommendation: If available use cluster definition'…"

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/info/model/RightV4.java

Expose EDIT_ENVIRONMENT to UI via RightsV4 as ENV_EDIT.

CB-18614 Add EDIT_ENVIRONMENT right to RightV4

---

cloud-consumption-api/src/main/java/com/sequenceiq/consumption/api/doc/ConsumptionModelDescription.java
cloud-consumption-api/src/main/java/com/sequenceiq/consumption/api/doc/ConsumptionOpDescription.java
cloud-consumption-api/src/main/java/com/sequenceiq/consumption/api/v1/consumption/endpoint/ConsumptionInternalEndpoint.java
cloud-consumption-api/src/main/java/com/sequenceiq/consumption/api/v1/consumption/model/common/ConsumptionType.java
cloud-consumption-api/src/main/java/com/sequenceiq/consumption/api/v1/consumption/model/request/CloudResourceConsumptionRequest.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/endpoint/ConsumptionInternalV1Controller.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/endpoint/converter/ConsumptionApiConverter.java

Endpoints have been created for general consumption collection. New `CloudResourceConsumptionRequest` has been added for new endpoint. Now we can handle all type of consumption requests depending on the `ConsumptionType`

CB-17875 Add schedule and unschedule endpoint for ebs consumption

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/recipe/FreeIpaRecipeService.java
freeipa/src/main/java/com/sequenceiq/freeipa/util/RecipeAttachmentChecker.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/recipe/FreeIpaRecipeServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/util/RecipeAttachmentCheckerTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltService.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltConnector.java

Steps
1) Check if freeipa has recipes -> it supports recipes
2) Check if it was started with newer version than 2.59.0-b21 -> we have the necessary salt states
3) If none of the above, then we check if the necessary state is on the cluster

CB-18533 Validate recipe attachment on freeipa

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsPlatformResources.java
config/checkstyle/checkstyle-suppressions.xml
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/BlueprintUtilV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/template/ClusterTemplateService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4ControllerTest.java

Reverts hortonworks/cloudbreak#13446

Revert "Revert "CB-18536 Gateway recommendation: If available use cluster definition'…""

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/datalake/DatalakeWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/environment/EnvironmentWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaUserSyncWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/cloudbreak/CloudbreakInstanceWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/freeipa/FreeIpaInstanceWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/redbeams/RedbeamsWaitObject.java

CB-18679 [e2e] NPE during FreeIpaWaitObject with UMS tests

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_healthagent_getcerts.sh

CB-18332 Typo fix in privateKey.pem generation in case of RHEL8

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResourcesTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceServiceTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverter.java
redbeams/src/test/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverterTest.java

CB-18149: [E2E] Azure deployment failed with The maximum number of access policy entries is 1024
This commit removes the vault access policy for the postgreSql.

CB-18149: [E2E] Azure deployment failed with The maximum number of access policy entries is 1024

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/service/ClusterComponentConfigProvider.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterComponentHistoryRepository.java
cluster-api/src/test/java/com/sequenceiq/cloudbreak/cluster/service/clustercomponent/ClusterComponentConfigProviderTestBase.java
common/src/main/java/com/sequenceiq/cloudbreak/common/anonymizer/AnonymizerUtil.java
common/src/test/java/com/sequenceiq/cloudbreak/common/anonymizer/AnonymizerUtilTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/InstanceMetaDataToCloudInstanceConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/cluster/ClusterRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/FinalizationCleanUpService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java
core/src/test/java/com/sequenceiq/cloudbreak/JpaTest.java
core/src/test/java/com/sequenceiq/cloudbreak/SqlStatementInspector.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/FinalizationCleanUpServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/database/SdxDatabaseServerUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/database/SdxDatabaseServerUpgradeServiceTest.java

2.62 to master

---

audit-connector/src/main/java/com/sequenceiq/cloudbreak/audit/AuditClient.java
audit-connector/src/main/java/com/sequenceiq/cloudbreak/audit/config/AuditConfig.java
ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/altus/GrpcMinaSshdManagementClient.java
ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/altus/config/MinaSshdManagementConfig.java
ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/ccmv2/GrpcCcmV2Client.java
ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/ccmv2/config/GrpcCcmV2Config.java
cluster-dns-connector/src/main/java/com/sequenceiq/cloudbreak/client/ClusterDnsConfig.java
cluster-dns-connector/src/main/java/com/sequenceiq/cloudbreak/client/GrpcClusterDnsClient.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/DatalakeDrClient.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/config/DatalakeDrConfig.java
idbmms-connector/src/main/java/com/sequenceiq/cloudbreak/idbmms/GrpcIdbmmsClient.java
idbmms-connector/src/main/java/com/sequenceiq/cloudbreak/idbmms/config/IdbmmsConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SdxSaasItClient.java
sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/client/sdx/GrpcSdxSaasClient.java
sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/client/sdx/GrpcServiceDiscoveryClient.java
sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/client/sdx/config/SdxSaasChannelConfig.java
sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/client/sdx/config/ServiceDiscoveryChannelConfig.java

Reverts hortonworks/cloudbreak#13480

Revert "CB-15442: Made all usages of ManagedChannelWrapper avoid creating new instances unnecessarily"

---

environment/src/main/java/com/sequenceiq/environment/experience/common/CommonExperienceConnectorService.java
environment/src/test/java/com/sequenceiq/environment/experience/common/CommonExperienceConnectorServiceTest.java

CB-18705 - extend logging and rephrase error message upon xp deletion issue

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/info/model/RightV4.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/CommonPermissionCheckingUtilsTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/UmsAccountAuthorizationServiceTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/UtilAuthorizationServiceTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/defaults/AccountAuthorizationServiceTest.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXInternalV1Controller.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/CheckRightRawTest.java

CB-18124 Remove legacy rights from backend 

---

datalake/src/main/java/com/sequenceiq/datalake/events/EventSenderService.java
datalake/src/main/java/com/sequenceiq/datalake/flow/verticalscale/DatalakeVerticalScaleActions.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/VerticalScaleService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/status/SdxStatusService.java

CB-18023 Add log to Data lake vertical scaling and a method was renamed

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/info/model/RightV4.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/CommonPermissionCheckingUtilsTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/UmsAccountAuthorizationServiceTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/UtilAuthorizationServiceTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/defaults/AccountAuthorizationServiceTest.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXInternalV1Controller.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/CheckRightRawTest.java

2.61 to 2.62

---

freeipa/src/main/resources/freeipa-salt/salt/monitoring/scripts/cipa.py

CB-18691 : [RHEL8] Upgrade Py3.6 to Py3.8 | MAIN_PATCHED_SCRIPT_PATH

---

freeipa/src/main/resources/application.yml

CB-18744 Enables redhat8 linux type

---

core-api/src/main/resources/definitions/exposed-services.json

[CB-18753] Rename Streaming SQL Engine to Streamin SQL Console

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java

API GCP E2E builds are failing, because of:
```
Exception java.lang.IllegalStateException
Message: There is no 'DELETED_ON_PROVIDER_SIDE' instance to wait!Stacktrace:
at com.sequenceiq.it.cloudbreak.dto.distrox.DistroXTestDto.awaitForActionedInstances(DistroXTestDto.java:198)
at com.sequenceiq.it.cloudbreak.testcase.e2e.distrox.DistroXScaleTest.testCreateAndScaleDistroX(DistroXScaleTest.java:85)
```
We need to update the API test project GCP Client related actions to conform the latest changes.

CB-18678 GCP E2E DELETED_ON_PROVIDER is not available for resilient upscale tests

---

common/src/main/java/com/sequenceiq/cloudbreak/util/DatabaseCommandFormatter.java
common/src/main/java/com/sequenceiq/cloudbreak/util/TimeUtil.java
common/src/test/java/com/sequenceiq/cloudbreak/util/DatabaseCommandFormatterTest.java
common/src/test/java/com/sequenceiq/cloudbreak/util/TimeUtilTest.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/LegacyStructuredEventDBService.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/action/TerminationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cleanup/StructuredEventCleanupService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/termination/action/TerminationServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/cleanup/StructuredEventCleanupServiceTest.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/repository/CDPStructuredEventRepository.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/db/CDPStructuredEventDBService.java

CB-18125 - cleanup structured events upon deletion for FreeIpa service

---

core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleServiceTest.java

- CM hosts status checker returns null as failed instance ids if CM call fails before initializing that variable
- in this case error message contains the null, which should be hidden
- if failedInstanceIds is null, it means there were some issue with CM until timeout, thus message will either print the actual exception instead of instance ids, or in worst case it will ask user to check CM logs

CB-18725 'Null' in statusreason after failed upscale during e2e

---

environment/build.gradle
environment/src/main/java/com/sequenceiq/environment/environment/flow/modify/proxy/action/AbstractEnvProxyModificationAction.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/modify/proxy/action/ProxyConfigModificationFailedStateAction.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/modify/proxy/action/ProxyConfigModificationFinishedStateAction.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/modify/proxy/event/EnvProxyModificationDefaultEvent.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/modify/proxy/event/EnvProxyModificationFailedEvent.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/modify/proxy/event/ProxyConfigModificationEvent.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/modify/proxy/handler/EnvProxyModificationSaveAssociationHandler.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/modify/proxy/action/AbstractEnvProxyModificationActionTest.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/modify/proxy/action/ProxyConfigModificationFailedStateActionTest.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/modify/proxy/action/ProxyConfigModificationFinishedStateActionTest.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/modify/proxy/handler/EnvProxyModificationSaveAssociationHandlerTest.java
usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/UsageReportProcessor.java
usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/UsageReporter.java
usage-collection/src/main/proto/usage.proto

CB-18489 Track proxy edit feature usage

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/info/model/RightV4.java

CB-18850 adding vertical scale right to the ui right response

---

flow-api/src/main/java/com/sequenceiq/flow/api/model/FlowLogResponse.java
flow/src/main/java/com/sequenceiq/flow/converter/FlowLogConverter.java
flow/src/main/java/com/sequenceiq/flow/domain/FlowLog.java
flow/src/main/java/com/sequenceiq/flow/repository/FlowLogRepository.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java
flow/src/main/resources/schema/flow/20221005170000_CB-18654_add_endtime_to_flowlog.sql
flow/src/test/java/com/sequenceiq/flow/service/flowlog/FlowLogDBServiceTest.java
flow/src/test/resources/schema/flow_test/20221005170000_CB-18654_add_endtime_to_flowlog.sql

Jira - https://jira.cloudera.com/browse/CB-18654
Added new column to flowlog table which will be updated when the status of the flow is being updated.

CB-18654 - Update flowlog table to add flow end time

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java

2.62 to 2.63

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java

2.63 to master

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/InstanceMetaDataToCloudInstanceConverter.java

CB-18666 add more log to print the existed instance groups for stack

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/InstanceMetaDataToCloudInstanceConverter.java

263intomaster

---

cloud-gcp/build.gradle

CB-18898 Upgrade google-oauth-client 1.31.5 to 1.33.3

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java

 CB-18915 setup cm credentials for monitoring correctly in case of enitlement

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Jira: https://jira.cloudera.com/browse/CDPSDX-3735
This is a fix for a promotion blocker for 2.63.0 on mow-int.
Explanation of changes:
- I first determined that the issue is only present when upgrade calls the backup process, hinting at the fact that the issue was due to how the Upgrade process differs (it sends a subset of database names to be backed up as a single string)
- I then replicated this issue within the gateway node of the DL by inserting a similar string into the pillar file and running the backup, observing that the script immediately failed due to the arguments being incorrect (this also skipping the creation of the log file)
- I then fixed the issue by modifying how the script determines if the inputs are valid (accepting more than 7 inputs to account for multiple …

CDPSDX-3735: Fixed backup during upgrade failing due to passing of database name set to internal Salt script.

---

common/src/main/java/com/sequenceiq/cloudbreak/quartz/TracedQuartzJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/instancemetadata/ArchiveInstanceMetaDataJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/nodestatus/NodeStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/salt/StackSaltStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/stackpatcher/ExistingStackPatcherJob.java
core/src/main/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/job/StructuredSynchronizerJob.java
core/src/test/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordServiceTest.java

Merge CB-2.63 to master

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java

GCP API E2E `listBucketSelectedObject` validation is intermittently failing at Jenkins, because of:
- MOW-Dev API E2E GCP `testSDXBackupRestoreCanBeSuccessful`
- QA Cloud API E2E GCP `testCreateDistroXWithEncryptedVolumes`
So GCP Client Action's `listBucketSelectedObject` method needs to be revisited and fixed.

CB-18920 [API E2E] GCP list objects validation is failing because of GCS object has 0 sub-objects!

---

autoscale/build.gradle

Remove jetty-server and jetty-http vulnerabilities.

CB-18903 CB-18904 Upgrade ehcache

---

common/build.gradle

CB-18902 Upgrade kotlin-stdlib and jaeger tracing client

---

gradle.properties

CB-18900 Upgrade aws-java-sdk-s3 1.11.952 to 1.12.261

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StartServicesHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StopServicesHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActionsTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StartServicesHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StopServicesHandlerTest.java

CB-18969 Stop/start cm during rds upgrade even if CDP_POSTGRES_UPGRADE_SKIP_SERVICE_STOP entitlement is enabled

CB-18969 Stop/start cm during rds upgrade even if CDP_POSTGRES_UPGRADE_SKIP_SERVICE_STOP entitlement is enabled

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/DistroXVerticalScaleV1Request.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StartServicesHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StopServicesHandler.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXVerticalScaleV1RequestToStackVerticalScaleV4RequestConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActionsTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StartServicesHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StopServicesHandlerTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/VerticalScaleService.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java
environment/src/main/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaService.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java

Cb 2.62.0 merge r1

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/DistroXVerticalScaleV1Request.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StartServicesHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StopServicesHandler.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXVerticalScaleV1RequestToStackVerticalScaleV4RequestConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActionsTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StartServicesHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/StopServicesHandlerTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/VerticalScaleService.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java
environment/src/main/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaService.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java

Cb 2.63.0 2

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java

Mergeback 2.62

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java

Merge263dr1

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java

ENGESC-17176 Set GCP VM canIpForward to FALSE

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java

Merge262 2

---

datalake-dr-connector/src/generated/main/java/com/cloudera/thunderhead/service/datalakedr/datalakeDRProto.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/model/DatalakeBackupStatusResponse.java
datalake-dr-connector/src/main/proto/datalakedr.proto
usage-collection/src/main/proto/usage.proto

Jira: https://jira.cloudera.com/browse/CDPSDX-3751
Failure was introduced due to the proto files in CB not being updated to match the Thunderhead ones. This caused the error seen of the enum missing.
Testing done: Locally built and ran CB-2.63.0 and reproduced the issue, then used the code in this PR to run the same Upgrade preparation process and confirmed that the issue is no longer present.

CDPSDX-3751: Fix upgrade failure due to backup validation error.

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/CloudbreakCommunicator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/AutoscaleV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AutoscaleV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java

CB-18655 AutoscaleV4Apis should return FlowIdentifier

---

core/src/main/resources/schema/app/20221004110836_CB-18697_remove_creator.sql

CB-18697 remove creator column from blueprint, customimage, vmimage

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

Pg upgrade stop services role remove

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoleConfigProvider.java

CDPSDX-3684; add new values to the HDFS node
`dfs.client.block.write.replace-datanode-on-failure.policy` set as `NEVER`
`dfs.client.block.write.replace-datanode-on-failure.enable`  set as `FALSE`

CDPSDX-3684; add new values to the HDFS node

---

integration-test/scripts/create-cloudbreak-context.sh

CB-18881 Expose UMS short timeout

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/NameserverPillarDecorator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/NameserverPillarDecoratorTest.java

In this commit I added validation to prevent the nameserver settings in the service pillar from null values. Sometimes we set the nameserver address in the unbound config to null and this causes cluster creation failures.

CB-18344: Extend nameserver ip validation with null check

---

core/src/main/java/com/sequenceiq/cloudbreak/job/salt/StackSaltStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackDtoService.java
core/src/test/java/com/sequenceiq/cloudbreak/job/salt/StackSaltStatusCheckerJobTest.java

CB-18984 Handle terminated stacks in StackSaltStatusCheckerJob

---

cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockNetworkConnector.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockPlatformResources.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockResourceConnector.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/NetworkCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/MockEnvironmentNetworkConverter.java
freeipa/src/main/resources/application.yml
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/FullVerticalScaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxResizeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RedbeamsDatabaseServerTest.java
integration-test/src/main/resources/application.yml

CB-18799 Add mock vertical scaling test, the network was implemented for Environment against Mock provider

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParameters.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParametersConsts.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformParameters.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/service/CloudParameterCache.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnPlatformParameters.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/VerticalScalingValidatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/EmbeddedDatabaseService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/StackDecorator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/StackCommonServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/EmbeddedDatabaseServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/StackDecoratorTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverter.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/network/NetworkBuilderService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsUpgradeService.java
redbeams/src/test/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverterTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/network/NetworkBuilderServiceTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/stack/RedbeamsUpgradeServiceTest.java

CB-18976 Changing network causes failure in PG upgrade
In case of azure we will update the database subnets before executing the database upgrade in redbeams.

CB-18976 Changing network causes failure in PG upgrade

---

gradle.properties

CB-19076 Upgrade commons-text 1.9 to 1.10

---

redbeams/build.gradle
redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/validation/RedBeamsTagValidator.java
redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/validation/RedBeamsTagValidatorTest.java

I  have added new service for validating tags depending on the cloud platform. UT has been added for corresponding class.

CB-17959 Fixed Tag  validation not applying in redbeams API issue.

---

core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionChecker.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionCheckerFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionCheckerService.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionCheckerType.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionResult.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionStepNode.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionStepNodeFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/step/ConclusionMessage.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stop/ClusterStopActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/ClusterStopFailedRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterDownscaleFailedConclusionHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterStopFailedHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterUpscaleFailedConclusionHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterUpgradeFailedHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/conclusion/ConclusionCheckerServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterStopFailedHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterUpgradeFailedHandlerTest.java

CB-19007 Include conclusion checker into cluster stop flow

---

autoscale-api/build.gradle
autoscale/build.gradle
build.gradle
cloud-api/build.gradle
cloud-azure/build.gradle
cloud-common/build.gradle
cluster-proxy/build.gradle
common-model/build.gradle
common/build.gradle
core-api/build.gradle
core/build.gradle
environment/build.gradle
flow-api/build.gradle
freeipa-client/build.gradle
freeipa/build.gradle
gradle.properties
integration-test/build.gradle
node-status-monitor-client/build.gradle
orchestrator-api/build.gradle
orchestrator-salt/build.gradle
redbeams-api/build.gradle
secret-engine/build.gradle
structuredevent-model/build.gradle

This version is only for the particular component. General Jackson is still 2.13.4

CB-19077 Upgrade Jackson Databind to 2.13.4.2

---

core/src/main/java/com/sequenceiq/cloudbreak/repository/StackDtoRepository.java

CB-18534 Do not fetch terminated cluster when checking for upgrade

---

core/src/main/java/com/sequenceiq/cloudbreak/service/diagnostics/DiagnosticsService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/diagnostics/DiagnosticsService.java
flow/src/main/java/com/sequenceiq/flow/repository/FlowLogRepository.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/diagnostics/DiagnosticsService.java

CB-19086 Filter out finished flow logs from diagnostic related query.

---

cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilder.java

ENGESC-17409 adding instancegroup tag to each and every ec2 machine.

---

core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionCheckerFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionStepTreeFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/start/ClusterStartActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/ClusterStartFailedRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterStartFailedHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/conclusion/ConclusionStepTreeFactoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterStartFailedHandlerTest.java

CB-19007 Include conclusion checker into cluster start flow

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProviderTest.java

Adding missing escape character and [^/]

[KNOX] - CDPD-45349 - Modify default whitelist regexp

---

orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/databus_metering.conf.j2

set follow_inodes true in metering config.

CB-18639 fixing new clusters/finishing up Oliver's work, 

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/backup.sls

 CB-19021 Remove extra spaces from backup.sls

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java

We've the capability to use cdp-telemetry module to upload logs and backups to Cloud storage configured for the cluster.
Make sure that we have an assertion that the upload actually happens at all the providers.

CB-19009 Make sure telemetry publisher can upload to cloud storage

---

cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/metadata/AwsNativeLbMetadataCollector.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/loadbalancer/AwsNativeLoadBalancerLaunchService.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/loadbalancer/AwsNativeLoadBalancerLaunchServiceTest.java
common-model/src/main/java/com/sequenceiq/common/api/backup/base/BackupBase.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeRdsFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/RdsUpgradeChainTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/rds/UpgradeRdsDataBackupRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/rds/UpgradeRdsTriggerRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/BackupRdsDataHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/BackupRestoreDBStateParamsProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActionsTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/BackupRdsDataHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/BackupRestoreDBStateParamsProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeServiceTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentBaseResponse.java
orchestrator-salt/src/main/resources/salt/salt/postgresql/upgrade/scripts/backup_db.sh

CB-18989 263 264 merge

---

cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/metadata/AwsNativeLbMetadataCollector.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/loadbalancer/AwsNativeLoadBalancerLaunchService.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/loadbalancer/AwsNativeLoadBalancerLaunchServiceTest.java
common-model/src/main/java/com/sequenceiq/common/api/backup/base/BackupBase.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeRdsFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/RdsUpgradeChainTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/rds/UpgradeRdsDataBackupRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/rds/UpgradeRdsTriggerRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/BackupRdsDataHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/BackupRestoreDBStateParamsProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsActionsTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/rds/BackupRdsDataHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/BackupRestoreDBStateParamsProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeServiceTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentBaseResponse.java
orchestrator-salt/src/main/resources/salt/salt/postgresql/upgrade/scripts/backup_db.sh

CB-18989 264 master merge

---

integration-test/src/main/resources/testsuites/e2e/gcp-longrunning-e2e-tests.yaml

Merge to264 gcp

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java

not only the current directory objects.

CB-19139 GCP e2e fix - list every object (recursively) on path, 

---

integration-test/src/main/resources/testsuites/e2e/gcp-longrunning-e2e-tests.yaml

CB-18418 Put back rds upgrade test to gcp-lomgrunning suite

---

environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyArnValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyArnValidatorTest.java

CB-19535: AWS deployment errors with encryption key not found
This commit improves logging around the encryption key not found error for AWS CMK.

CB-19535: AWS deployment errors with encryption key not found

---

build.gradle

CB-19099 upgrading spotbug plugin because of CVE

---

common/src/main/java/com/sequenceiq/cloudbreak/filter/MinimalHardwareFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/VerticalScalingValidatorService.java
environment-common/src/main/java/com/sequenceiq/cloudbreak/service/verticalscale/VerticalScaleInstanceProvider.java
environment-common/src/test/java/com/sequenceiq/cloudbreak/service/verticalscale/VerticalScaleInstanceProviderTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/VerticalScalingValidatorService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/VerticalScalingValidatorServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/FullVerticalScaleTest.java

65mergerrdoktorics

---

core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java

CB-19114:Add validation for custom templates to ensure correct knox placement
This commit adds a validation that knox can't be in a hostgroup where type!=GATEWAY
-     nginx is configured only on host group with type=GATEWAY
-     LB is configured with all the nodes where knox is installed
-     If knox is deployed on 2 hostgroups, but only one hostgroup will have type=GATEWAY and only that node will have nginx
So the ask is, to add a validation that knox can't be in a hostgroup where type!=GATEWAY

CB-19114:Add validation for custom templates to ensure correct knox placement

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/LdapAgentConfigProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/LdapAgentConfigView.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/SaltConfigProvider.java
freeipa/src/main/resources/defaults/vm-logs.json
freeipa/src/main/resources/freeipa-salt/pillar/top.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/ldapagent.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/templates/ldapagent_config.yaml.j2
freeipa/src/main/resources/freeipa-salt/salt/nginx/conf/ssl-locations.d/ldapagent.conf
freeipa/src/main/resources/freeipa-salt/salt/nginx/init.sls
freeipa/src/main/resources/freeipa-salt/salt/top.sls
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/config/LdapAgentConfigProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/SaltConfigProviderTest.java

CB-18829 Setup FreeIPA LDAP agent

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2

CB-19710 Increase gateway timeouts for SSB-SSE-UI

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/upscale/AzureVerticalScaleService.java
integration-test/src/main/resources/application.yml

CB-19690 CB-19691 disable azure and gcp vertical scale test

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh

JIRA: https://jira.cloudera.com/browse/CDPSDX-3767 
ISSUE: Temp local files are not cleaned up if backup fails and that may result in customer having full disk due to these obsolete files. 
FIX: Force remove the temp directory when having an error and before exit the program.
Even if we have a failed backup (I gave a wrong bucket name to make it a failed backup, same way to reproduce the issue above):
No temp files left and the log (test updated at Nov 16 5:25PM EST):

CDPSDX-3767 Fix Temporary DB Backup Data Is Not Deleted When Backup Fails

---

datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/converter/GrpcStatusResponseToDatalakeBackupRestoreStatusResponseConverter.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/converter/OperationEnum.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/model/DatalakeBackupStatusResponse.java
datalake-dr-connector/src/test/java/com/sequenceiq/cloudbreak/datalakedr/converter/GrpcStatusResponseToDatalakeBackupStatusResponseConverterTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/DatalakeBackupActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/DatalakeRestoreActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/validation/DatalakeBackupValidationActions.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreService.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/adls/AdlsGen2ConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/adls/AdlsGen2ConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProviderTest.java

Merge 2.65 to master

---

flow/README.md

CB-19012 Updated flow module's README.md. Removed reactor related parts.

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/ResourceConnector.java
cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/ResourceConnectorTest.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsParameterGroupService.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsTerminateService.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsResourceConnector.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeService.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeSteps.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/operation/AwsRdsUpgradeOperations.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsParameterGroupServiceTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsTerminateServiceTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeServiceTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/AwsRdsUpgradeStepsTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/upgrade/operation/AwsRdsUpgradeOperationsTest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/client/AmazonRdsClient.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/client/AmazonRdsClientTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnectorTest.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockResourceConnector.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/upgrade/handler/UpgradeDatabaseServerHandler.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/upgrade/handler/UpgradeDatabaseServerHandlerTest.java

Merge 265 to master

---

integration-test/scripts/check-results.sh

DistroXUpgradeTests.testDistroXOsUpgradeByUpgradeSets

CB-19819 increase pg network output to 4.6 because a new test was added

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleService.java

CB-19729 fix added log line in getAllowedInstanceStates

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCloudResourceService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceType.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCloudResourceServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnectorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceServiceTest.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringUrlResolver.java
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringUrlResolverTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/TelemetryApiConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/telemetry/TelemetryConfigService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/network/NetworkParameterAdder.java

Merge265tomaster

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh

ISSUE: Temp local files not cleaned up if backup fails.
FIX: Force remove the temp directory when having an error and before exit the program.
Hi @sodre90 , this is the same PR of this one (https://github.com/hortonworks/cloudbreak/pull/13780) that you reverted. I updated the commit message. Please let me know if it looks good. Thank you so much!

CDPSDX-3767 Fix Temp DB Backup Data Not Deleted When Backup Fails

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/environment/EnvironmentNetworkTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/constants/NetworkConstants.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentWithPublicEndpointAccessGatewayTests.java

CB-18953 - E2e tests for Targeting Subnets for Load Balancers Feature

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-environment-minimal-policy.json
cloud-aws-common/src/main/resources/definitions/aws-environment-minimal-policy.json

CB-19688 adding rds:RebootDBInstance to minimal policy

---

environment/src/main/java/com/sequenceiq/environment/configuration/AppConfig.java
environment/src/main/java/com/sequenceiq/environment/credential/attributes/azure/AppBasedAttributes.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDto.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/credential/AwsCredentialDetailsConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/credential/AzureCredentialDetailsConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/credential/CloudPlatformAwareCredentialDetailsConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/credential/CredentialDetailsConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/credential/GcpCredentialDetailsConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/credential/MockCredentialDetailsConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/credential/YarnCredentialDetailsConverter.java
environment/src/test/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/dto/credential/AwsCredentialDetailsConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/dto/credential/AzureCredentialDetailsConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/dto/credential/CredentialDetailsConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/dto/credential/GcpCredentialDetailsConverterTest.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/cdp/environment/EnvironmentDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/cdp/environment/credential/CredentialDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/cdp/environment/credential/CredentialType.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/EnvironmentDetailsToCDPEnvironmentDetailsConverter.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/EnvironmentDetailsToCDPEnvironmentDetailsConverterTest.java
usage-collection/src/main/proto/usage.proto

CB-19655 EDH tracking for credential type of environments

CB-19655 EDH tracking for credential type of environments

---

redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/common/RedbeamsEvent.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/start/RedbeamsStartEvent.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/start/RedbeamsStartFlowConfing.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/start/RedbeamsStartState.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/start/actions/CertRotateInRedbeamsAction.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/start/actions/StartDatabaseServerFinishedAction.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/start/event/CertRotateInRedbeamsRequest.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/start/event/CertRotateInRedbeamsSuccess.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/start/handler/CertRotateInRedbeamsHandler.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/start/actions/CertRotateInRedbeamsActionTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/start/actions/StartDatabaseServerFinishedActionTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/start/handler/CertRotateInRedbeamsHandlerTest.java

CB-19609 Create a new flow step in the External DB start flow. Create the skeleton of the CERT rotation step in External DB flow.

---

freeipa/src/main/java/com/sequenceiq/freeipa/repository/ImageRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/UsedImagesProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/UsedImagesProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/StackServiceTest.java

CB-15822 Refactor used image collection

---

.gitconfig
Makefile
README.md
scripts/hooks/pre-push

CB-19904 Adding pre commit hook testing

---

freeipa/src/main/java/com/sequenceiq/freeipa/FreeIpaFlowInformation.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/binduser/BindUserCreateService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupService.java
freeipa/src/main/java/com/sequenceiq/freeipa/util/FreeIpaStatusValidator.java
freeipa/src/test/java/com/sequenceiq/freeipa/FreeIpaFlowInformationTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/binduser/BindUserCreateServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaParallelFlowValidatorTest.java

…ke 5 mins for EC2 to successfully describe instance created by ASG.See detailed description in the commit message.

CB-19917 Make new FMS flows parallel

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/Cluster.java
core-model/src/main/java/com/sequenceiq/cloudbreak/view/ClusterView.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterDbCertRotationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterDtoRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/cluster/ClusterRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/resources/schema/app/20221128111150_CB-19615_add_db_ssl_cert_to_cluster.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/cluster/ClusterRequestToClusterConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterDbCertRotationHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java

Update the db root ssl cert for the cluster entity during the cluster start. The cert rotation on the VM will be done in the next task

CB-19615 Update the cert on the Cluster

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetaDataCollectorTest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/client/AmazonEc2Client.java
common/src/main/java/com/sequenceiq/cloudbreak/service/Retry.java
common/src/main/java/com/sequenceiq/cloudbreak/service/RetryService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/CloudbreakFlowInformation.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/StartAmbariServicesHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterServiceRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/StartAmbariServicesHandlerTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxFlowInformation.java
flow/src/test/java/com/sequenceiq/cloudbreak/service/HeartbeatServiceTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/Status.java
freeipa-api/src/test/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/StatusTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/FreeIpaFlowInformation.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/binduser/BindUserCreateService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupService.java
freeipa/src/main/java/com/sequenceiq/freeipa/util/FreeIpaStatusValidator.java
freeipa/src/test/java/com/sequenceiq/freeipa/FreeIpaFlowInformationTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/binduser/BindUserCreateServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaParallelFlowValidatorTest.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/model/common/Status.java
redbeams/src/test/java/com/sequenceiq/redbeams/RedbeamsFlowInformationTest.java

266 to master 2

---

datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java

The rolling runtime upgrade command is only available for HA clusters in Cloudera Manager. Therefore we need validation for the Data Lake cluster before we start the upgrade.

CB-19883: Create validation for Data Lake rolling runtime upgrade

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxDescribeInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonClusterManagerProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeNativeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxNativeMigrationTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/AwsCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazoncf/action/CfClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/AmazonEC2Util.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/AzureCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java
integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-native-tests.yaml

CB-17135 cloudformation to native migration tests for sdx and freeipa

---

autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterPertainRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java
autoscale/src/test/java/com/sequenceiq/periscope/endpointtests/DistroXAutoScaleClusterV1EndpointTest.java

Merge 2.66 to master

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/StackScaleV4Request.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/DistroXScaleV1Request.java

Improve error message to show desiredCount field name if it was null.

CB-18254 Improve error message to show desiredCount field name

---

autoscale/src/main/java/com/sequenceiq/periscope/PeriscopeApplication.java
cloud-consumption/src/main/java/com/sequenceiq/consumption/ConsumptionApplication.java
common/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/CloudbreakApplication.java
datalake/src/main/java/com/sequenceiq/datalake/DatalakeApplication.java
dependencies.gradle
docker-autoscale/Dockerfile
docker-cloudbreak/Dockerfile
docker-consumption/Dockerfile
docker-datalake/Dockerfile
docker-environment/Dockerfile
docker-freeipa/Dockerfile
docker-redbeams/Dockerfile
environment/src/main/java/com/sequenceiq/environment/EnvironmentApplication.java
freeipa/src/main/java/com/sequenceiq/freeipa/FreeIpaApplication.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/service/MockUmsService.java
redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsApplication.java

Reverts hortonworks/cloudbreak#13802

Revert "CB-18225 import Cloudera's openssl-provider library and configure it to be the most prior java security provider for FIPS"

---

flow/src/main/java/com/sequenceiq/flow/core/chain/FlowChains.java

CB-20150 add Lazy annotation for temp fix

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/upscale/failure/UpscaleStackResultToUpscaleFailureEventConverter.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/upscale/failure/UpscaleStackResultToUpscaleFailureEventConverterTest.java

code changes to capture reason of failure as additonal failure details

CB-18474 FREEIPA - AWS quota issue is hidden, hard to investigate e2e test results

---

integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-native-tests.yaml

CB-20159 remove migration until it is not stabilized

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java

CB-20130 NPE upon logging when VirtualMachine object gets null

---

environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java

remove unnecessary comment from credential change method

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidatorTest.java

CB-19937 CM Status validation in upscaleStartInstances requires all type=GATEWAY roles to be HEALTHY

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/cert/CertRenewalService.java

CB-17146 redeployGatewayCertificate should init pillars

---

cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceService.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceDeletionCallable.java
cloud-template/src/test/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceServiceTest.java

Make sure resource deletion throws error if cloud connector exception happens during individual resource deletion.

CB-19997 Make sure resource deletion throws error

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ClusterProxyService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/ClusterProxyServiceTest.java

CB-20109 Pass environment CRN for FreeIPA cluster proxy registration

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureAttachmentResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java

Throw preserve resource exception instead of interrupted exception.

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserStateDifferenceCalculator.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UsersStateDifferenceCalculatorTest.java

There is a new user created in IPA for use by LDAP usersync. Usersync previously would remove this user from the admins group, which removes the ability for this user to make changes in IPA.
This commit updates usersync so that it only removes group memberships for users that are in the cdp-usersync-internal group.

CB-20198. Usersync filters users

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsPlatformParameters.java
cloud-aws-common/src/main/resources/definitions/aws-gov-cb-policy.json

CB-20200 adding the fix for pi service which does not exist in govcloud

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerParcelListenerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerSingleParcelActivationListenerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerUpgradeParcelDistributeListenerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerUpgradeParcelDownloadListenerTask.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerParcelListenerTaskTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerSingleParcelActivationListenerTaskTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerUpgradeParcelDistributeListenerTaskTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerUpgradeParcelDownloadListenerTaskTest.java

CB-20158 Handle parcel download errors in poller

---

common/src/main/java/com/sequenceiq/cloudbreak/util/FreeIpaPasswordUtil.java
common/src/main/java/com/sequenceiq/cloudbreak/util/PasswordUtil.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/cluster/ClusterV4Request.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/cluster/DistroXClusterV1Request.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/TargetedUpscaleSupportService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/TargetedUpscaleSupportServiceTest.java

2.67 to master

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-enabled-availability-zones.json
cloud-aws-cloudformation/src/main/resources/definitions/aws-zone-coordinates.json
cloud-aws-cloudformation/src/main/resources/definitions/aws-zone-displaynames.json
cloud-aws-cloudformation/src/main/resources/definitions/zones.json
cloud-aws-common/src/main/resources/definitions/aws-enabled-availability-zones.json
cloud-aws-common/src/main/resources/definitions/aws-zone-coordinates.json
cloud-aws-common/src/main/resources/definitions/aws-zone-displaynames.json
cloud-aws-common/src/main/resources/definitions/zones.json

CB-20176 adding Spain as supported region

---

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/ClusterToClusterDetailsConverter.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/ClusterDetails.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToCDPClusterDetailsConverter.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredFlowEventToCDPDatalakeRequestedConverter.java
structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToCDPClusterDetailsConverterTest.java
usage-collection/src/main/proto/usage.proto

CB-10760 - Send events for audit & EDH about DB SSL usage

---

flow/src/main/resources/schema/flow/20230109112161_CB-18783_drop_old_payload_fields.sql

The new Jackson serialized fields are proven to work, these columns are the last remaining pieces that are not in use anymore.

CB-18783 Drop old payload fields

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandler.java
autoscale/src/main/java/com/sequenceiq/periscope/utils/StackResponseUtils.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandlerTest.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/MockStackResponseGenerator.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/StackResponseUtilsTest.java

CB-20171 Refactor periscope cluster status sync

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/blueprint/BlueprintV4RequestToBlueprintConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePreconditionService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityService.java
core/src/main/resources/schema/app/20221221111150_CB-18190_update_custom_blueprint_upgrade_option.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/blueprint/BlueprintV4RequestToBlueprintConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePreconditionServiceTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityServiceTest.java
core/src/test/resources/test/defaults/blueprints/blueprint-with-upgrade-option.bp
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/utils/BlueprintUtils.java

This saves Blueprint Upgrade Options from custom builds in the database.

CB-18190 This saves Blueprint Upgrade Options from custom builds in the database.

---

core/src/main/resources/defaults/blueprints/7.2.10/cdp-rt-data-mart.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-rt-data-mart.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-rt-data-mart.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-rt-data-mart.bp
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kudu/KuduConfigs.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kudu/KuduServiceConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kudu/KuduVolumeConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kudu/KuduServiceConfigProviderTest.java

Merge CB-18996

---

build.gradle
config/spotbugs/excludeFilter.xml
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbCertificateProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbServerConfigurer.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/UpgradeRdsBackupRestoreStateParamsProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/HueRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/KnoxGatewayServiceRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/NifiRegistryRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/OozieRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/ProfilerAdminRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/ProfilerMetricsRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/RangerRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbCertificateProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbServerConfigurerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/SqlStreamBuilderAdminRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/SqlStreamBuilderSnapperRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/StreamsMessagingManagerRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/UpgradeRdsBackupRestoreStateParamsProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverterTest.java
orchestrator-salt/src/main/resources/salt/salt/postgresql/root-certs.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/settings.sls

CB-19614 adding cert rotation flow when the cluster starts.

---

environment-common/build.gradle
environment-common/src/main/java/com/sequenceiq/cloudbreak/service/verticalscale/VerticalScaleInstanceProvider.java
environment-common/src/test/java/com/sequenceiq/cloudbreak/service/verticalscale/VerticalScaleInstanceProviderTest.java

CB-20258 merge to master

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/PrewarmImageValidatorE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/MonitoringTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxRepairWithRecipeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxImagesTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxResizeRecoveryTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxResizeTests.java

CB-20156 Added telemetry to tests using SdxInternalTestDto

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PricingCache.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/configuration/PricingConfig.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/cost/AwsPricingCache.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/cost/AwsPricingCacheTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/cost/AzurePricingCache.java
common/src/main/java/com/sequenceiq/cloudbreak/common/cost/EnvironmentRealTimeCost.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cost/ClusterCostService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cost/InstanceTypeCollectorService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cost/ClusterCostServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cost/InstanceTypeCollectorServiceTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentRealTimeCostRequest.java
environment/src/main/java/com/sequenceiq/environment/environment/service/cost/EnvironmentCostService.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/cost/EnvironmentCostController.java
freeipa/src/main/java/com/sequenceiq/freeipa/cost/FreeIpaCostService.java
freeipa/src/main/java/com/sequenceiq/freeipa/cost/FreeIpaInstanceTypeCollectorService.java
freeipa/src/test/java/com/sequenceiq/freeipa/cost/FreeIpaCostServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/cost/FreeIpaInstanceTypeCollectorServiceTest.java

- provider based cached pricing services are implementing a common interface to simplify calculation logic

CB-20233 refactor, fixes for cost calculation

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureSetup.java

Adding exception message to Azure Setup thrown error message.
Jira: https://jira.cloudera.com/browse/CB-17590

CB-17590 - To add to exception message when Image Copy error is thrown.

---

docker-autoscale/Dockerfile
docker-cloudbreak/Dockerfile
docker-consumption/Dockerfile
docker-datalake/Dockerfile
docker-environment/Dockerfile
docker-freeipa/Dockerfile
docker-redbeams/Dockerfile
integration-test/docker-compose_template.yml
integration-test/test-image/Dockerfile
mock-infrastructure/Dockerfile
mock-thunderhead/Dockerfile

CB-20314 update java base images to reduce vulnerabilities

---

core/src/main/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/RotateSaltPasswordServiceTest.java

Validate that the status after rotation is OK, otherwise fail and do not save the generated password.

CB-20284 Check password status after salt password rotation

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/cost/ClusterCostV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/cost/requests/ClusterCostV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/Notes.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/doc/DistroXOpDescription.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXCostV1Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ClusterCostV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackDtoRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cost/ClusterCostService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackDtoService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXCostV1Controller.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cost/ClusterCostServiceTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxCostEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/EndpointConfig.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxCostController.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxCostService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxCostServiceTest.java
environment/src/main/java/com/sequenceiq/environment/environment/service/cost/EnvironmentCostService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/cost/EnvironmentCostServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/cost/FreeIpaCostService.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/test/java/com/sequenceiq/freeipa/cost/FreeIpaCostServiceTest.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/main/resources/application.yml

depends on: https://github.com/hortonworks/cloudbreak/pull/14051

CB-20260 CB-20281 Environment cost should return attached resources' cost as well, different DL and DH cost APIs for UI

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxNativeMigrationTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazoncf/action/CfClientActions.java

Merge cb20159 4

---

common-model/src/main/java/com/sequenceiq/common/api/type/LoadBalancerType.java

Merge266 2

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/config/AwsCostCache.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/cost/AwsPricingCache.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/conf/AzureCostCache.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/cost/AzurePricingCache.java

CB-20281 improve caching of cost calculation logic

---

docker-autoscale/Dockerfile
docker-cloudbreak/Dockerfile
docker-consumption/Dockerfile
docker-datalake/Dockerfile
docker-environment/Dockerfile
docker-freeipa/Dockerfile
docker-redbeams/Dockerfile
integration-test/docker-compose_template.yml
integration-test/test-image/Dockerfile
mock-infrastructure/Dockerfile
mock-thunderhead/Dockerfile

CB-20420 update base image to decrease vulnerabilities on the base image

---

environment/src/test/java/com/sequenceiq/environment/environment/flow/EnvironmentReactorFlowManagerTest.java

Resolve merge conflict in unit test

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazoncf/action/CfClientActions.java

CB-20440 fixing bad assertion in FreeipaNativeMigrationTest

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazoncf/action/CfClientActions.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateComponentConfigProviderProcessor.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxServiceConfigProvider.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/RdsView.java

Merge cb20440

---

common-model/src/main/java/com/sequenceiq/common/api/type/LoadBalancerType.java

This reverts commit 6060045f66d938f6d389a70eeadff6f2f459e1b7.

Revert "CB-18948 Swagger compatibility fix"

---

common/src/main/java/com/sequenceiq/cloudbreak/common/cost/RealTimeCost.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cost/ClusterCostService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/cost/EnvironmentCostServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/cost/FreeIpaCostService.java

CB-20457 Return crn of Data Lake in EnvironmentRealTimeCost

---

README.md

CB-18493 add Readme section about importing mock-infrastructure cert to your trust store and why/when it is needed

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java

Reverts hortonworks/cloudbreak#13961

Revert "CB-16136:Set Cloud Type Variable in CM"

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/StackV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/StackV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/DistroXV1Request.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/StackToStackV4ResponseConverterTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/ModelDescriptions.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterRequestBase.java

We are changing the API first so we can work in parallel on implementing the feature both in CB and CDP CLI

CB-20462 CB API changes to support java version opt-in parameter

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/endpoint/AwsEndpointProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaBackupConfigView.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigService.java
freeipa/src/main/resources/freeipa-salt/pillar/freeipa/init.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup
freeipa/src/main/resources/freeipa-salt/salt/freeipa/settings.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/templates/freeipa_backup.conf.j2
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigServiceTest.java

CB-20471 Use S3 fipsed endpoint for freeipa backup on govcloud

---

common/src/main/java/com/sequenceiq/cloudbreak/config/DataBusS3EndpointPattern.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/DataBusEndpointProvider.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/converter/DiagnosticsDataToParameterConverter.java
common/src/main/resources/common-config.yml
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/DataBusEndpointProviderTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/DiagnosticsFlowService.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/telemetry/TelemetryConfigService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/telemetry/TelemetryConfigServiceTest.java

Use S3 fipsed endpoint for logcollection on govcloud

CB-20470 Use S3 fipsed endpoint for logcollection on govcloud

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/service/LoadAlertPolicyHostGroupInstanceInfo.java
autoscale/src/main/java/com/sequenceiq/periscope/service/RegularScalingAdjustmentService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/StopStartScalingAdjustmentService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/YarnBasedScalingAdjustmentService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeNativeTests.java

Merge 2.67 to master

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java

CB-20677 Single AZ native enablement - fix checkstyle

---

autoscale-api/src/test/java/com/sequenceiq/periscope/api/endpoint/validator/DistroXAutoscaleRequestValidatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/controller/AutoscaleClusterCommonServiceTest.java
autoscale/src/test/java/com/sequenceiq/periscope/controller/HistoryControllerTest.java
autoscale/src/test/java/com/sequenceiq/periscope/converter/LoadAlertRequestConverterTest.java
autoscale/src/test/java/com/sequenceiq/periscope/converter/LoadAlertResponseConverterTest.java
autoscale/src/test/java/com/sequenceiq/periscope/converter/TimeAlertRequestConverterTest.java
autoscale/src/test/java/com/sequenceiq/periscope/converter/TimeAlertResponseConverterTest.java
autoscale/src/test/java/com/sequenceiq/periscope/domain/LoadAlertConfigurationTest.java
autoscale/src/test/java/com/sequenceiq/periscope/endpointtests/DistroXAutoScaleClusterV1EndpointTest.java
autoscale/src/test/java/com/sequenceiq/periscope/filter/AuditFilterTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/AbstractMonitorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/RejectedThreadMonitorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/CronTimeEvaluatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/EvaluatorExecutorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/ScalingPolicyTargetCalculatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/executor/EvaluatorExecutorRegistryTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/executor/ExecutorServiceWithRegistryTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ScalingHandlerTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandlerTest.java
autoscale/src/test/java/com/sequenceiq/periscope/service/AuditServiceTest.java
autoscale/src/test/java/com/sequenceiq/periscope/service/DateServiceTest.java
autoscale/src/test/java/com/sequenceiq/periscope/service/RejectedThreadServiceTest.java
autoscale/src/test/java/com/sequenceiq/periscope/service/UsageReportingServiceTest.java
autoscale/src/test/java/com/sequenceiq/periscope/service/security/TenantBasedPermissionEvaluatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/swagger/SwaggerGenerator.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/ClusterUtilsTest.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/CronTest.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/LoggingUtilsTest.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/MetricUtilsTest.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/ModelTest.java

CB-20676 Migrate the majority of autoscale from junit4 to junit5

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java

Will add the -cp option to CM settings only incase of supported values which are AWS,AZURE,GCP and NONE.

CB-20508:Fix Cloudprovider check for Yarn cloud

---

core/src/main/resources/application.yml

CRB-2407 Support Azure E*ds_v4 and E*s_v4 instances for Data Hub

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsPlatformResources.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsPlatformResourcesTest.java

PR merged to master : https://github.com/hortonworks/cloudbreak/pull/13922/files

CB-19535:Handle Paginated AWS kms keys in list keys and list alias call

---

environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyArnValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyArnValidatorTest.java

PR created for master : https://github.com/hortonworks/cloudbreak/pull/14182/files

CB-20135:Turn off KMS validations / allows keys in remote AWS account

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java

This reverts commit 302ada1871a6f420485b0d6e7e1627097ce6747b.

Revert "CB-20508:Fix Cloudprovider check for Yarn cloud"

---

autoscale/src/main/java/com/sequenceiq/periscope/domain/ScalingActivity.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/ScalingActivityRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ScalingActivityService.java
autoscale/src/main/resources/schema/app/20230131191556_CB-20727_Refactor_ScalingActivity_entity's_activityCrn_field_to_operationId.sql
autoscale/src/test/java/com/sequenceiq/periscope/repository/ScalingActivityRepositoryTest.java
autoscale/src/test/java/com/sequenceiq/periscope/service/ScalingActivityServiceTest.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/Crn.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/CrnResourceDescriptor.java

CB-20727 Refactor ScalingActivity entity's activityCrn field to an operation ID

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxCustomClusterRequest.java
datalake-api/src/test/java/com/sequenceiq/sdx/api/ApiFormatTest.java
datalake-api/src/test/java/com/sequenceiq/sdx/api/model/SdxCustomClusterRequestTest.java

Add recipes to the custom image request object.

CB-20774 [CLI] [API] Recipes are not attached if custom image is used

---

flow-api/src/main/java/com/sequenceiq/flow/api/FlowEndpoint.java
flow/src/main/java/com/sequenceiq/flow/controller/FlowController.java
flow/src/test/java/com/sequenceiq/flow/controller/FlowControllerTest.java

CB-20775 Modify the bulk flow APIs to return a list instead of a page

---

common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/AbstractMetricService.java
common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/MetricService.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/JobMetricsListener.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/QuartzMetricTag.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/QuartzMetricType.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/QuartzMetricUtil.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/SchedulerMetricsListener.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/TriggerMetricsListener.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/model/JobResource.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/model/JobResourceAdapter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
environment/src/main/java/com/sequenceiq/environment/environment/repository/EnvironmentRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
redbeams/src/main/java/com/sequenceiq/redbeams/repository/DBStackRepository.java

- Include provider as a tag in quartz related metrics where it is possible
- Remove unused and duplicated metrics

CB-20512 Create quartz metrics by provider

---

core/src/main/resources/defaults/blueprints/7.2.17/cdp-flow-management-small.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-flow-management.bp

CFM-3204: parameter name is changed in csd service descriptor

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsPlatformResources.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerConfigService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/ClusterUpgradeValidationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/event/ClusterUpgradeServiceValidationEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeServiceValidationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/FlinkUpgradeValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/ServiceUpgradeValidationRequest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/ActiveCommandsValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/FlinkUpgradeValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/NifiUpgradeValidatorTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxCustomClusterRequest.java
datalake-api/src/test/java/com/sequenceiq/sdx/api/ApiFormatTest.java
datalake-api/src/test/java/com/sequenceiq/sdx/api/model/SdxCustomClusterRequestTest.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyArnValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyArnValidatorTest.java
flow-api/src/main/java/com/sequenceiq/flow/api/FlowEndpoint.java
flow/src/main/java/com/sequenceiq/flow/controller/FlowController.java
flow/src/test/java/com/sequenceiq/flow/controller/FlowControllerTest.java

Merge CB-2.68.0 to master

---

client-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/ClouderaManagerApiClientProvider.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterDecomissionService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecommissionService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecommissionServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissionerTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/StopCmServicesOnHostsInsteadOfDecommissionHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/resource/DecommissionRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/resource/StopCmServicesOnHostsRequest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleActionsTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/StopCmServicesOnHostsInsteadOfDecommissionHandlerTest.java
dependencies.gradle
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java

CB-19851 Integrate with hostsStopRoles CM command for ZDU upgrade

---

flow/src/main/java/com/sequenceiq/cloudbreak/service/flowlog/FlowLogUtil.java

CB-20682 Fix logging issue in FlowLogUtil when the returned entity is a projection.

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverterTest.java

2.67 to 2.68

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverterTest.java

2.68 to master

---

core/src/main/java/com/sequenceiq/cloudbreak/service/operation/OperationService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/operation/OperationServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/operation/OperationService.java
environment/src/main/java/com/sequenceiq/environment/operation/service/OperationService.java
flow/src/main/java/com/sequenceiq/flow/core/stats/FlowOperationStatisticsService.java
flow/src/main/java/com/sequenceiq/flow/service/FlowService.java
flow/src/test/java/com/sequenceiq/flow/core/stats/FlowOperationStatisticsServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/operation/FlowOperationService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/operation/FlowOperationServiceTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/operation/OperationService.java

CB-20411 remove FlowOperationStatisticsService from FlowService

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/PersistRejectedThreadExecutionHandler.java
autoscale/src/main/java/com/sequenceiq/periscope/utils/FileReaderUtils.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpHttpClientConfig.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfigService.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfigView.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/nodestatus/NodeStatusConfigView.java
common/src/main/java/com/sequenceiq/cloudbreak/util/PasswordUtil.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/UserGeneratorService.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/UserGeneratorServiceTest.java

CRB-2413 fortify fixes for reduce the current issuenumbers.

---

idbmms-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/idbrokermappingmanagement/IdBrokerMappingManagementGrpc.java
idbmms-connector/src/generated/main/java/com/cloudera/thunderhead/service/idbrokermappingmanagement/IdBrokerMappingManagementProto.java
idbmms-connector/src/main/proto/idbrokermappingmanagement.proto

We need to update the IDBroker Mappings PROTO to can set IDBMMS mappings to RAZ enabled SDX as well.

CB-20861 Update idbrokermappingmanagement PROTO

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/ClusterTemplate.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/clustertemplate/ClusterTemplateToClusterTemplateV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/clustertemplate/ClusterTemplateV4RequestToClusterTemplateConverter.java
core/src/main/resources/schema/app/20230110074614_DISTX-739_Fix_EnableLoadBalancer_set_to_false_irrespective_of_true_in_custom_cluster_definition.sql

DISTX-739 Fix EnableLoadBalancer set to false irrespective of true in custom cluster definition

---

datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StackRequestManifesterTest.java

CB-20677 cover SDX single AZ AWS native enforcement with UT

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java

Fix ResourceNotFound error during private dns check during Azure env creation

CB-20883 Fix ResourceNotFound error during private dns check during Azure env creation

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/endpoint/AwsEndpointProvider.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/DataBusEndpointProvider.java

CB-20890 modify the environment variable name from fips.use to use.fips

---

environment/src/main/java/com/sequenceiq/environment/EnvironmentHaApplication.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/repository/EnvironmentRepository.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentServiceTest.java

Merge 268 into master

---

freeipa/src/main/resources/application.yml

CB-20863 Modify the current n1-standard-2 to e2-standard-2

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureHttpClientConfigurer.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureUrlMetricTagMapper.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureUrlMetricTagMapperTest.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpServiceFactory.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/metric/CompositeHttpExecuteInterceptor.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/metric/GcpMetricTag.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/metric/GcpMetricType.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/metric/MetricLoggerInterceptor.java

CB-20513 Create metrics for provider API calls (Azure, GCP)

---

environment/src/main/java/com/sequenceiq/environment/network/v1/converter/EnvironmentBaseNetworkConverter.java
environment/src/test/java/com/sequenceiq/environment/network/v1/converter/AwsEnvironmentNetworkConverterTest.java

In case of previously created environments, the subnet metadata that is stored in the database, naturally do not have the deployment restrictions set.
To overcome this, a logic is provided that tries to guess the restrictions. Unfortunately this was applied to the subnets where this data is present, actually.

CB-20903 Wrong deployment restrictions

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeImageInfo.java

Merge268tomaster

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh

Jira: https://jira.cloudera.com/browse/CDPSDX-3934
Simple change which will fix slowness experienced during large DB backups in prod.

CDPSDX-3934: Removed compress flag from DB backup script to remove slowness issues from customers.

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseRestKnoxServiceConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoleConfigProviderTest.java

CDPSDX-3528; fix configuration conditions to enable new sdx optimization config values.

CDPSDX-3528; fix configuration conditions to enable new sdx optimization config values

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

CB-20987 Empty java version should not override stack's java version

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java

Give better error message when we couldn't find an instance from AWS which was either not registered by existing volumes or was recognised by existing volumes.

CB-20316 Give better error message when we couldn't find an instance

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh

Merge 2.68 to master

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleServiceTest.java

After an unsuccessful upscale phase of a repair, the volumes were successfully attached to some of the nodes, but some failed because of some reason. In this case, we are just handling the instance deletion on the provider side, but the volumes will be in CREATED status and the saved instance ID for the volume resource will be the new node's id which is removed and is not updated to the original one.
For a workaround, we will set every volume to DETACHED at the end of the downscale phase which has the same FQDN as the nodes FQDN we are repairing.
It would be set to DETACHED at the instance deletion phase, but the instance ID is wrong because it is the newer node's one (which was deleted because of the rollback).

CB-21004 Always set volumes to detached at repair

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/OSUpgradeByUpgradeSetsFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/OSUpgradeByUpgradeSetsFlowEventChainFactoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/AvailabilityInfo.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/AvailabilityType.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/operation/model/OperationType.java
freeipa-api/src/test/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/AvailabilityTypeTest.java
freeipa-api/src/test/java/com/sequenceiq/freeipa/api/v1/operation/model/OperationTypeTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/upscale/action/FreeIpaUpscaleActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingValidationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/RepairInstancesService.java
freeipa/src/main/resources/application.yml
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingValidationServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/RepairInstancesServiceTest.java

Merge 268 to master

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PricingCache.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsLaunchTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsRepairTest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsClient.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/client/AmazonPricingClient.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/cost/AwsPricingCache.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/cost/model/OfferTerm.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/cost/model/PriceDimension.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/cost/model/PriceListElement.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/cost/model/PricePerUnit.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/cost/model/Terms.java
cloud-aws-common/src/main/resources/definitions/aws-cb-policy.json
cloud-aws-common/src/main/resources/definitions/aws-gov-cb-policy.json
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/cost/AwsPricingCacheTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/cost/AzurePricingCache.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/cost/AzurePricingCacheTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cost/ClusterCostService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cost/InstanceTypeCollectorService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cost/ClusterCostServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cost/InstanceTypeCollectorServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/cost/FreeIpaCostService.java
freeipa/src/main/java/com/sequenceiq/freeipa/cost/FreeIpaInstanceTypeCollectorService.java
freeipa/src/test/java/com/sequenceiq/freeipa/cost/FreeIpaCostServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/cost/FreeIpaInstanceTypeCollectorServiceTest.java

CB-20856 Made cost calculation pricing caches more fault tolerant

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-audit-policy.json
cloud-aws-common/src/main/resources/definitions/aws-audit-policy.json

CB-20964 - The "Audit" service policy returned by credential prerequisites is incorrect

---

integration-test/scripts/download-cbd.sh

CB-21043 build CBD with Go 1.20

---

docker-autoscale/Dockerfile
docker-cloudbreak/Dockerfile
docker-consumption/Dockerfile
docker-datalake/Dockerfile
docker-environment/Dockerfile
docker-freeipa/Dockerfile
docker-redbeams/Dockerfile
integration-test/docker-compose_template.yml
integration-test/test-image/Dockerfile
mock-infrastructure/Dockerfile
mock-thunderhead/Dockerfile

CRB-2402 updating the base image

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java

CB-21012 CM apply host template request with empty host list fails

---

common/src/main/java/com/sequenceiq/cloudbreak/common/exception/WebApplicationExceptionMessageExtractor.java
common/src/test/java/com/sequenceiq/cloudbreak/common/exception/WebApplicationExceptionMessageExtractorTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/ProvisionerService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/ProvisionerServiceTest.java

CB-21016 Show real error message during Datalake creation

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissionerTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterUpscaleService.java

CB-20916 Integrate with hostsStartRoles CM command for ZDU upgrade

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazBaseConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazBaseConfigProviderTest.java

CB-20990 Populate raz service account property for raz enabled GCP Datalake

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/AwsCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/AmazonEC2Util.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/AzureCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java
integration-test/src/main/resources/application.yml

CB-19768  new vertical scaling end to end test

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java

CB-19768 Fix compile error

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureNetworkConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpNetworkConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformResources.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpForwardingRuleResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/view/GcpDatabaseNetworkView.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpForwardingRuleResourceBuilderTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtilTest.java
common/src/main/java/com/sequenceiq/cloudbreak/constant/AzureConstants.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/AzureNetworkV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/GcpNetworkV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/MockNetworkV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/OpenStackNetworkV4Parameters.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/network/NetworkToNetworkV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/GcpEnvironmentNetworkConverter.java
environment/src/test/java/com/sequenceiq/environment/network/v1/converter/GcpEnvironmentNetworkConverterTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/network/AwsNetworkParameters.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/network/AzureNetworkParameters.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/network/GcpNetworkParameters.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/network/MockNetworkParameters.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/network/OpenStackNetworkParameters.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/aws/AwsNetworkV4Parameters.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/network/NetworkParameterAdder.java

This PR conains 2 commits, the first is a little code cleanup (consolidation). 
Please review it separately.

CB-20318 Targeting Load Balancer with GCP

---

integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml

CB-20821 [API E2E] E2E test(s) need to be added to support RAZ on GCP

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java

CB-21131 vertical scaling test failing with unusable error message

---

orchestrator-salt/src/main/resources/salt/salt/java/init.sls
orchestrator-salt/src/main/resources/salt/salt/java/scripts/set_default_java_version.sh
orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls

CB-20962 Elliminate the depencency on dhclient-enter-hooks

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java

CB-21035 Fix NPE when VirtualMachine is null during instance delete

---

cloud-aws-common/src/main/resources/definitions/aws-audit-policy.json

CB-21110 credential-pre-requisite have consistent response for bucket placeholder

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

CB-21032 Add topologies for EFM UI and API

---

core/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/7.2.17/cdp-edge-flow-management-small.bp
core/src/main/resources/defaults/clustertemplates/7.2.17/aws/edge-flow-management-small.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java
template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.2.17.json
template-manager-cmtemplate/src/main/resources/cloudera-manager-template/service-definitions-minimal.json

CB-21030 EFM Templates and Blueprint

---

docker-autoscale/Dockerfile
docker-cloudbreak/Dockerfile
docker-consumption/Dockerfile
docker-datalake/Dockerfile
docker-environment/Dockerfile
docker-freeipa/Dockerfile
docker-redbeams/Dockerfile
integration-test/test-image/Dockerfile
mock-infrastructure/Dockerfile
mock-thunderhead/Dockerfile

Automated Pull request to update the base image and reduce CVEs

Base image update for the latest RELENG image

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxNativeMigrationTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazoncf/action/CfClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java

CB-21153 filtering StackStatuses instead of string values

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsCredentialConnector.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsPlatformParameters.java
cloud-aws-common/src/main/resources/definitions/cdp/aws-cdp-ranger-raz-s3-policy.json
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsCredentialConnectorTest.java

CB-21109 get-credential-prerequisites should support ranger raz role

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/java/ForceJavaVersionE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJavaVersionActions.java
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml

CB-20483 E2E test to validate Java11

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRangerRazEnabledTests.java
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml

Disbled test caused failure, so it will be removed from the test suit

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java

Merge 269 to master

---

dependencies.gradle

Reverts hortonworks/cloudbreak#14474

Revert "CB-20503 reverting the crypto lib version increase because it causein…"

---

core/src/main/resources/defaults/clustertemplates/7.2.17/azure/edge-flow-management-small.json
core/src/main/resources/defaults/clustertemplates/7.2.17/gcp/edge-flow-management-small.json
core/src/main/resources/defaults/clustertemplates/7.2.17/yarn/edge-flow-management-small.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

CB 21191 remaining cloud providers

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AzureEnvironmentNetworkConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/loadbalancer/LoadBalancerConfigService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4Converter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AzureEnvironmentNetworkConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/loadbalancer/LoadBalancerConfigServiceTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/EnvironmentNetworkAzureParams.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverter.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverterTest.java

Reverts hortonworks/cloudbreak#14370
More explanation could be found [in the relevant ticket](https://jira.cloudera.com/browse/CDPSDX-3910?focusedCommentId=5843351&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-5843351)

Revert "CB-20718 Outbound Load Balancer is created by default on new networks only"

---

flow/src/main/java/com/sequenceiq/flow/reactor/config/EventBusConfig.java
flow/src/test/java/com/sequenceiq/flow/reactor/config/EventBusConfigTest.java

CB-21252 Close flow even if an exception happens during failed flow handling.

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsSessionCredentialClient.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsSessionCredentialClientTest.java

CB-21256 remove explicit AWS endpoint override of STS client creation when using FIPS mode

CB-21256 remove explicit AWS endpoint override of STS client creation when using FIPS mode

---

orchestrator-salt/src/main/resources/salt/salt/java/init.sls
orchestrator-salt/src/main/resources/salt/salt/java/templates/java.policy
orchestrator-salt/src/main/resources/salt/salt/java/templates/java_security_providers.j2

Depends on https://github.com/hortonworks/cloudbreak/pull/14449

CB-21070 Use FIPS validated crypto modules on gov cloud

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/network/MultiAzValidator.java

CB-21238 fix AWS Gov related typo in multi-AZ enabled cloud platform variants for Datahubs

CB-21238 fix AWS Gov related typo in multi-AZ enabled cloud platform variants for Datahubs

---

autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java
autoscale/src/main/java/com/sequenceiq/periscope/controller/DistroXAutoScaleClusterV1Controller.java
autoscale/src/main/java/com/sequenceiq/periscope/controller/validation/AlertValidator.java
autoscale/src/test/java/com/sequenceiq/periscope/controller/validation/AlertValidatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/endpointtests/DistroXAutoScaleClusterV1EndpointTest.java

CB-20926 Set useStopStartMechanism in the periscope backend based on entitlement checks

---

core/src/main/resources/defaults/blueprints/7.2.14/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.14/cdp-sdx-micro.bp
core/src/main/resources/defaults/blueprints/7.2.14/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.15/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.15/cdp-sdx-micro.bp
core/src/main/resources/defaults/blueprints/7.2.15/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-sdx-micro.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-sdx-micro.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-sdx.bp
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProviderTest.java
template-manager-cmtemplate/src/test/resources/input/clouderamanager-variables.bp
template-manager-cmtemplate/src/test/resources/output/clouderamanager-variables.bp
template-manager-cmtemplate/src/test/resources/output/clouderamanager-without-hosts.bp
template-manager-cmtemplate/src/test/resources/output/clouderamanager.bp

CDPSDX-3936 add hive direct sql configatrion to the blueprints

CDPSDX-3936 add hive direct sql configatrion to the blueprints

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandlerTest.java

CB-21253 Call removeHosts after stopping agents too

---

cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/loadbalancer/service/component/YarnLoadBalancerComponentFactoryService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/ServiceStatusCheckerLogLocationDecorator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/ServiceStatusCheckerLogLocationDecoratorTest.java

Merge 2.69.0 to master

---

gradle.properties

RELENG-20767: Trying to fix CB gradle daemon crash

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/efm/EfmVolumeConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/efm/EfmVolumeConfigProviderTest.java

CB-21292 Log to persistent volume

---

core/src/main/resources/defaults/blueprints/7.2.15/cdp-rt-data-mart.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-rt-data-mart-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-rt-data-mart.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-rt-data-mart-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-rt-data-mart.bp

CB-21341: Add yarn-GATEWAY-BASE role to the coordinator node

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientFactory.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/configuration/SchedulerFactoryConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleServiceTest.java

2.69 to 2.70

---

dependencies.gradle

CB-21348 updating aws sdk for the latest one

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/update/SaltUpdateActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/kerberos/KeytabConfigurationRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/kerberos/CmServiceKeytabRequestFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/kerberos/KeytabConfigurationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/kerberos/KeytabProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/kerberos/CmServiceKeytabRequestFactoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/kerberos/KeytabConfigurationHandlerTest.java

Tested scenarios before repair:
- remove privilege from ipa role
- remove member service (CM) from ipa role
- remove role

CB-21013 Repair should regenerate Kerberos credentials

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ClusterUpgradeFailedEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ClusterUpgradeFailedRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ClusterUpgradeRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterUpgradeFailedHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterUpgradeFailedHandlerTest.java
dependencies.gradle
gradle.properties

Merge 270 to master

---

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/TelemetryFeatureService.java
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/TelemetryFeatureServiceTest.java

CB-21355 Fix ECDSA requirement check to allow key type if package is not present.

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/rest/AzureRestOperationsService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/rest/AzureRestTemplateFactory.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureRestOperationServiceTest.java
cloud-common/build.gradle
secret-engine/build.gradle

CB-21339 spring-vault-core upgrade from 2.1.0 to 2.3.3 (Aquasec cve)

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientFactory.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureHttpClientConfigurer.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureQuartzRetryUtils.java

CB-21340 remove azure related ok http client retry too in case of quartz

---

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/TelemetryFeatureService.java
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/TelemetryFeatureServiceTest.java

2.70 merge to master

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParametersConsts.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnectorTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/environment/marketplace/AzureMarketplaceTermsClientService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/environment/marketplace/AzureMarketplaceTermsClientServiceTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/marketplace/MarketplaceDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/marketplace/endpoint/AzureMarketplaceTermsEndpoint.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/marketplace/model/AzureMarketplaceTermsRequest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/marketplace/model/AzureMarketplaceTermsResponse.java
environment-api/src/main/java/com/sequenceiq/environment/client/internal/EnvironmentApiClientConfig.java
environment/src/main/java/com/sequenceiq/environment/marketplace/domain/Terms.java
environment/src/main/java/com/sequenceiq/environment/marketplace/repository/TermsRepository.java
environment/src/main/java/com/sequenceiq/environment/marketplace/service/AzureMarketplaceTermsService.java
environment/src/main/java/com/sequenceiq/environment/marketplace/v1/controller/AzureMarketplaceTermsController.java
environment/src/main/resources/schema/app/20230310154102_CB-12577_Table_to_store_account_level_setting_to_image_terms_auto_acceptance.sql

CB-12577 Azure Marketplace image automatic terms acceptance setting

---

orchestrator-salt/src/main/resources/salt/salt/java/init.sls
orchestrator-salt/src/main/resources/salt/salt/java/scripts/set_default_java_version.sh
orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls

CB-21362 Revert changes are brake down ycloud cluster provision

---

core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-spark3-ha.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.16/cdp-rt-data-mart-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-data-engineering-spark3-ha.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.17/cdp-rt-data-mart-spark3.bp
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/Spark3OnYarnRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/Spark3OnYarnRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnConfigProviderTest.java

Remove openssl configs from template and populate them only for AWS

CB-21312 Disable openssl for RAZ GCP cluster

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleService.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleServiceTest.java

269 to 270

---

core/src/main/java/com/sequenceiq/cloudbreak/service/environment/marketplace/AzureMarketplaceTermsClientService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/environment/marketplace/AzureMarketplaceTermsClientServiceTest.java
integration-test/scripts/check-results.sh

CB-21396 Handle terms setting not found as set to false

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleService.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleServiceTest.java

270 to master

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollector.java
core-api/src/main/resources/definitions/exposed-services.json
core-api/src/test/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollectorTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_token.xml.j2
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatahubConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatalakeConfigProvider.java

Expose Ranger Raz via knox proxy

CB-21119 Ranger RAZ - get metrics api via knox proxy

---

common/src/main/java/com/sequenceiq/cloudbreak/vm/VirtualMachineConfiguration.java
common/src/main/resources/common-config.yml
common/src/test/java/com/sequenceiq/cloudbreak/vm/VirtualMachineConfigurationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/JavaVersionValidatorTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

Merge 2.70 into master

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java

CB-20071 fix duplicate swagger nickname definition

---

common/src/main/java/com/sequenceiq/cloudbreak/validation/ContentSizeProvider.java
common/src/main/java/com/sequenceiq/cloudbreak/validation/DefaultContentSizeProvider.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/HttpContentSizeValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ImageCatalogValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidHttpContentSize.java
core-api/src/test/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ImageCatalogV4BaseTest.java
core-api/src/test/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ValidatorTestHelper.java
core-api/src/test/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ValidatorTestHelperConfiguration.java
core-api/src/test/java/com/sequenceiq/cloudbreak/validation/HttpContentSizeValidatorTest.java
core/src/main/resources/application.yml

Merge from 2.69.0

---

core/src/main/resources/defaults/blueprints/7.2.16/cdp-data-engineering-spark3-ha.bp

typo in 7.2.16 Spark3 HA blueprint

CB-21463 typo in 7.2.16 Spark3 HA blueprint

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudInstance.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCloudResourceService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureMetadataCollector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureInstanceView.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCloudResourceServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureMetadataCollectorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStackViewProviderTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverterTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/cloud/StackToCloudStackConverter.java

This reverts commit e8de6f05038caff8fd06b36a1bcbc99174fc4286.

Revert "CB-21088 add 8 digit hash to the end of the vm names on Azure"

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureImageTerms.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureImageTermsSignerService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/rest/AzureRestOperationsService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureImageTermsSignerServiceTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/marketplace/model/AzureMarketplaceTermsRequest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/marketplace/model/AzureMarketplaceTermsResponse.java
environment-api/src/main/java/com/sequenceiq/environment/client/EnvironmentClient.java
environment-api/src/main/java/com/sequenceiq/environment/client/EnvironmentServiceApiKeyEndpoints.java
environment-api/src/main/java/com/sequenceiq/environment/client/EnvironmentServiceCrnEndpoints.java
environment/src/main/java/com/sequenceiq/environment/configuration/api/EndpointConfig.java
environment/src/main/java/com/sequenceiq/environment/marketplace/domain/Terms.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/cloud/StackToCloudStackConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/client/AzureMarketplaceTermsClientService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/terms/TermsGetAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/terms/TermsPutAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/AzureMarketplaceTermsClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/TermsPolicyDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/microservice/EnvironmentClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXMarketplaceImageTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AzureMarketplaceImageTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxMarketplaceImageTests.java
integration-test/src/main/resources/catalog/v3-marketplace-image-catalog.json
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml

CB-19604 E2E Marketplace image tests for datalake and datahub

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/proxy/ProxyConfigCmAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java

CB-21538 Handle real ums in ProxyConfigCmAssertions

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cost/InstanceTypeCollectorService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cost/InstanceTypeCollectorServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/cost/FreeIpaInstanceTypeCollectorService.java
freeipa/src/test/java/com/sequenceiq/freeipa/cost/FreeIpaInstanceTypeCollectorServiceTest.java

CB-21548 Fix CloudCredential govCloud flag

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/ResourceDiskPropertyCalculator.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/template/ResourceDiskPropertyCalculatorTest.java

CB-21465 avoiding null pointer exception with an explicit check

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/FlinkUpgradeValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/FlinkUpgradeValidatorTest.java

CB-21363 Added missing Component annotation and changed service name

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/Spark3OnYarnRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/Spark3OnYarnRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnRoleConfigProviderTest.java

Duplicate key hive_service_config_safety_valve

CB-21569 Duplicate key hive_service_config_safety_valve

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/FlinkUpgradeValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/service/FlinkUpgradeValidatorTest.java
environment/src/main/java/com/sequenceiq/environment/experience/ResponseReaderUtility.java
environment/src/test/java/com/sequenceiq/environment/experience/ResponseReaderUtilityTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/Spark3OnYarnRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/Spark3OnYarnRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnRoleConfigProviderTest.java

Merge 2.70 to master

---

core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/StackDecorator.java

when the availability is not filled then would have happened that the availability zone set later on which would have been different than the subnet (and instances) availability zone (causing errors in gcp)

getAvailabilityZoneFromEnv will fill the availability zone in case of the environment has prefered subnet with those subnets availability zone

---

common-model/src/main/java/com/sequenceiq/common/api/type/InstanceGroupName.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/OrderedOSUpgradeRequestProvider.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/OrderedOSUpgradeRequestProviderTest.java

Reverts hortonworks/cloudbreak#14724

Revert "CB-21356 Handle OS Upgrade Order for Enterprise DL"

---

freeipa/src/main/java/com/sequenceiq/freeipa/sync/ProviderChecker.java

CB-20509 Log instance ID and FQDN when updating status during sync

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationStackUtil.java

ENGESC-20104 adding more logs to the cloudformationstackutil

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerCloudStorageServiceConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazBaseConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatalakeConfigProviderTest.java

Minimum version for RAZ on GCP should be changed to 7.2.17

CB-21663 Minimum version for RAZ on GCP should be changed to 7.2.17

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureQuartzRetryUtils.java

CB-21340 Set max client quartz retry to 0

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterSecurityService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityServiceTest.java
common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/PostRotationAction.java
common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/RotationContext.java
common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/RotationContextProvider.java
common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/RotationExecutor.java
common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/SecretLocationType.java
common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/SecretRotationConfig.java
common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/SecretRotationException.java
common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/SecretType.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/cm/CMUserRotationExecutor.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/provider/CBCMAdminPasswordRotationContextProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/provider/MgmtCMAdminPasswordRotationContextProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/provider/ServicesDBPasswordsRotationContextProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/cm/CMUserRotationExecutorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/context/provider/CBCMAdminPasswordRotationContextProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/context/provider/MgmtCMAdminPasswordRotationContextProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/context/provider/ServicesDBPasswordsRotationContextProviderTest.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/SecretEngine.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/service/SecretService.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/service/rotation/VaultRotationExecutor.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/vault/VaultKvV1Engine.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/vault/VaultKvV2Engine.java
secret-engine/src/test/java/com/sequenceiq/cloudbreak/service/secret/service/SecretServiceTest.java
secret-engine/src/test/java/com/sequenceiq/cloudbreak/service/secret/service/rotation/VaultRotationExecutorTest.java

- generating context for secret rotation
- executing rotation based on type of secret
- WIP: error handling, rollback strategy, DB secret rotations
- added rotations: CM admin password, CM mgmt password
- not wired into any API or automatism yet

CB-21512 basic framework for secret rotation

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/action/ClouderaManagerClientActions.java

Add Retryable to CM config calls to reduce test flakiness

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationStackUtil.java

Merge 2.70.0 to master

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudInstance.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCloudResourceService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureMetadataCollector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureInstanceView.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCloudResourceServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureMetadataCollectorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStackViewProviderTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverterTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/cloud/StackToCloudStackConverter.java

CB-21088 add 8 digit hash to the end of the vm names on Azure

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/AbstractEnvironmentCreationAction.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/EnvCreationActions.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/AbstractEnvClustersDeleteAction.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/AbstractEnvDeleteAction.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/EnvClustersDeleteActions.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/EnvDeleteActions.java

CB-11565 Extract inner Action classes

---

cloud-gcp/build.gradle

Reverts hortonworks/cloudbreak#14808

Revert "Bump com.google.apis:google-api-services-iam from v1-rev20230406-2.0.0 to v1-rev20230420-2.0.0"

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageFilter.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageFilterTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageServiceTest.java

CB-20698 Image filtering logic should only prefer Azure Marketplace images when the entitlement is granted

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageFilter.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageFilterTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageServiceTest.java

Merge from 2.70.0

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-enabled-availability-zones.json
cloud-aws-cloudformation/src/main/resources/definitions/aws-zone-coordinates.json
cloud-aws-cloudformation/src/main/resources/definitions/aws-zone-displaynames.json
cloud-aws-cloudformation/src/main/resources/definitions/zones.json
cloud-aws-common/src/main/resources/definitions/aws-enabled-availability-zones.json
cloud-aws-common/src/main/resources/definitions/aws-zone-coordinates.json
cloud-aws-common/src/main/resources/definitions/aws-zone-displaynames.json
cloud-aws-common/src/main/resources/definitions/zones.json

CB-21673 adding UAE regions and coordinates to the CB code

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupServiceTest.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceMetaData.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/network/MultiAzValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/multiaz/DataLakeMultiAzCalculatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/multiaz/MultiAzCalculatorService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/StackCreatorServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/multiaz/DataLakeMultiAzCalculatorServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/multiaz/MultiAzCalculatorServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetadataServiceComponentTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/utils/BlueprintUtils.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/util/BlueprintUtilsTest.java

This is not a final change. Still need additional unit tests and final testing.
I intent of the PR is to seek feedback on the solution approach.
**Solution approach:**
We would like to make sure the nodes in Gateway and Auxillary are treated as one group when AZ placement is performed so that services shared across these host groups are properly distributed.

CB-21122 - Define the Multi AZ node placement for enterprise dl.

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java

CB-21518 Disable google-analytics in CM when we deploy a cloud cluster

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java

Jira: https://jira.cloudera.com/browse/CDPSDX-3985
Simply added new enterprise shape to repair E2E test.

CDPSDX-3985: Added E2E tests for new Scalable SDX shape.

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/CleanupMonitor.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/CleanupMonitorTest.java

CB-21498 Limit the number of scaling events for cleanup monitor

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerFedRAMPService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerFedRAMPServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupServiceTest.java

CB-21553 Implement CM policy configuration to be Fips compliant

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageServiceTest.java

CB-20698 Select the default region for image on ycloud platform

---

client-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/ClouderaManagerApiClientProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
dependencies.gradle

CB-20093 Add argument runAutoConfig for applyHostTemplate call to CM

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/DistroxEnabledInstanceTypes.java
common/src/main/resources/cost/cloudera-price.json
core/src/main/resources/application.yml
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidatorTest.java
structuredevent-model/src/main/java/com/sequenceiq/environment/environment/domain/Region.java

CB-21520 include the Azure region in error message which is about nonexistent subnets

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerHostStatusChecker.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/view/ClusterComponentView.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartds/StopStartDownscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartActions.java
core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/StopStartUpscaleCommissionViaCMHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/TlsSecurityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/start/action/StackStartActions.java

CB-20874 Fixing log messages containing partial entity views

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java

CDPSDX-3985 disable E2E tests for new Scalable/Enterprise SDX shape

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageServiceTest.java

CB-20698 Select the default region for image on mock platform

---

client-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/ClouderaManagerApiClientProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
dependencies.gradle

Reverts hortonworks/cloudbreak#14706

Revert "CB-20093 Add argument runAutoConfig for applyHostTemplate call to CM"

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/atlas/AtlasKnoxRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseRestKnoxServiceConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoleConfigProvider.java

CDPSDX-4002 Disable Wire encription configuration in case of YCloud

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageInfo.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageInfoService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/util/CustomVMImageNameProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageServiceTest.java

Merge 2.71.0 into master

---

client-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/ClouderaManagerApiClientProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
dependencies.gradle
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java

Reverts hortonworks/cloudbreak#14852

Revert "Revert "CB-20093 Add argument runAutoConfig for applyHostTemplate call to CM""

---

secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/SecretEngine.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/domain/RotationSecret.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/service/SecretService.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/vault/VaultKvV1Engine.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/vault/VaultKvV2Engine.java
secret-engine/src/test/java/com/sequenceiq/cloudbreak/service/secret/vault/VaultKvV2EngineTest.java

CB-21743 Vault handling in secret rotation

---

integration-test/src/main/resources/application.yml

CB-21818 set distroXUpgrade3rdPartyTargetVersion: 7.2.16

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/ActivityStatus.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/MetricType.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/CleanupMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/client/YarnMetricsClient.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/cleanup/ActivityCleanupEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/FreeIpaCommunicator.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/ScalingActivityRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/PeriscopeMetricService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ScalingActivityService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/YarnBasedScalingAdjustmentService.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/cleanup/ActivityCleanupEvaluatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/repository/ScalingActivityRepositoryTest.java
autoscale/src/test/java/com/sequenceiq/periscope/service/ScalingActivityServiceTest.java
autoscale/src/test/java/com/sequenceiq/periscope/service/YarnBasedScalingAdjustmentServiceTest.java

CB-20947 Additional metrics for periscope to Prometheus

---

environment/src/main/java/com/sequenceiq/environment/network/v1/converter/AwsEnvironmentNetworkConverter.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/AzureEnvironmentNetworkConverter.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/EnvironmentBaseNetworkConverter.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/GcpEnvironmentNetworkConverter.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/MockEnvironmentNetworkConverter.java
environment/src/test/java/com/sequenceiq/environment/network/v1/converter/AwsEnvironmentNetworkConverterTest.java
environment/src/test/java/com/sequenceiq/environment/network/v1/converter/AzureEnvironmentNetworkConverterTest.java

270 fw r04

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupServiceTest.java

CDPSDX-3896; change condition to move the CM MGMT in case of Enterprise DLse DL. Reason: Enterprise DL name changes should be followed

CDPSDX-3896; change condition to move the CM MGMT in case of Enterprise DL

---

integration-test/src/main/resources/application.yml

Reverts hortonworks/cloudbreak#14873

Revert "CB-21818 setting current version to 7.2.15 from 7.2.7 in order to upg…"

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetaDataCollectorTest.java

CB-21850 Do not perform describe instances on auto scaling group where there is no existing instances during AWS metadata collect

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/PythonVersionBasedRuntimeVersionValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/validation/PythonVersionBasedRuntimeVersionValidatorTest.java

In this commit I've extended the existing validation what we introduced in CB-21567.

CB-21804: Extend the upgrade validations to require the Python 3.8 dependency when upgrading Data Lake cluster to 7.2.17+ runtime version

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilderTest.java

During the cluster deletion we're calling the AmazonEc2Client.describeVolumes endpoint to get the status of the volumes. The problem was that we called this endpoint for the deleted volumes with null volume ID and the AWS send back this error message: `software.amazon.awssdk.services.ec2.model.Ec2Exception: The request must contain the parameter volumes (Service: Ec2, Status Code: 400, Request ID: eef3faf6-d9c1-4e79-b86b-ba719c391da3) `
In this fix I set the status of the volume to deleted if the volume ID is null.

CB-21764: Do not call AWS describe volumes when the volume ids are null.

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetaDataCollectorTest.java

Merge CB-2.71.0 into master

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java

CB-21906 Disable SdxRepairTests.testSDXEnterpriseRepair (E2E failure)

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/CloudbreakUserCache.java

Fedramp E2E tests are failing, because of malformatted V3 secret keys in test project. So a simple formatting has been introduced for secret keys with `SHA512withECDSA` algorithm.

CB-21938 [GOV-DEV E2E] BlueprintListAction is failing: Illegal base64 character 5c

---

auth-internal-api/src/main/java/com/sequenceiq/cloudbreak/auth/security/internal/AccountIdValidator.java
common-model/src/main/java/com/sequenceiq/common/api/telemetry/validation/LoggingRequestValidator.java
common-model/src/main/java/com/sequenceiq/common/api/util/ValidatorUtil.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/DatalakeCrnValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/EnvironmentCrnValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/HttpContentSizeValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ImageCatalogValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/UpgradeRequestValidator.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/upgrade/DistroXUpgradeRequestValidator.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/validation/RootVolumeSizeValidator.java
datalake-api/src/main/java/com/sequenceiq/sdx/validation/UpgradeRequestValidator.java

Merge origin/CB-2.71.0 into branch CB-2.72.0

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/generic/DynamicModel.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsAttachmentResourceBuilder.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilderTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureAttachmentResourceBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpDiskResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java
cloud-template/src/test/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnectorTest.java

Merge 271 to 272

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java

CB-21987 Relax custom configs runtime check

---

auth-internal-api/src/main/java/com/sequenceiq/cloudbreak/auth/security/internal/AccountIdValidator.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/generic/DynamicModel.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsAttachmentResourceBuilder.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilderTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureAttachmentResourceBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpDiskResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java
cloud-template/src/test/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnectorTest.java
common-model/src/main/java/com/sequenceiq/common/api/telemetry/validation/LoggingRequestValidator.java
common-model/src/main/java/com/sequenceiq/common/api/util/ValidatorUtil.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/DatalakeCrnValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/EnvironmentCrnValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/HttpContentSizeValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ImageCatalogValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/UpgradeRequestValidator.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/upgrade/DistroXUpgradeRequestValidator.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/validation/RootVolumeSizeValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/clusterproxy/reregister/ClusterProxyReRegistrationConfig.java
datalake-api/src/main/java/com/sequenceiq/sdx/validation/UpgradeRequestValidator.java

Merge 272 to master

---

orchestrator-salt/src/main/resources/salt/salt/java/init.sls
orchestrator-salt/src/main/resources/salt/salt/java/scripts/set_default_java_version.sh
orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls

CB-20962 Elliminate the dependency on dhclient-enter-hooks

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java

Merge 2.71 to 2.72

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/cloudbreak/CloudbreakInstanceWaitObject.java

Jira: https://jira.cloudera.com/browse/CB-21155
We have observed cases where the instance waiting logic in the E2E tests fails, but is not clear about how it failed, making it hard to diagnose and debug the issue. I have modified the error logging and throwing to also display the stack's status and status reason which will contain more information about why the failure occurred.

CB-21155: Added logging of stack status and status reason to instance wait object upon failure for E2E tests.

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/InstanceStatus.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsInstanceConnector.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/util/AwsInstanceStatusMapper.java

CB-17033 AWSConnector stop/start API enhancements

---

common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/SecretRotationStep.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/DatabaseRootPasswordSaltPillarGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/SaltPillarRotationContext.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/executor/SaltPillarRotationExecutor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/salt/SaltStateParamsService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorService.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/context/DatabaseRootPasswordSaltPillarGeneratorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/executor/SaltPillarRotationExecutorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/rds/RdsUpgradeOrchestratorServiceTest.java

Cb 21683 Salt pillar rotation executor

---

common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/SecretRotationStep.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/rotation/SaltStateApplyRotationContext.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/rotation/SaltStateApplyRotationExecutor.java
orchestrator-api/src/test/java/com/sequenceiq/cloudbreak/orchestrator/rotation/SaltStateApplyRotationExecutorTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

CB-21684 implement salt state apply executor for secret rotation

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/acceptor/AutoscalingInstancesInServiceAcceptor.java

CB-21996 ASG creation waiter is not prepared for empty list in response

---

autoscale/src/test/java/com/sequenceiq/periscope/utils/MetricUtilsTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupServiceTest.java
config/checkstyle/checkstyle.xml
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackToStackV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackDtoService.java
core/src/test/java/com/sequenceiq/cloudbreak/DefaultEnumConverterCompatibilityTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentServiceExperienceFetchTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/RepoConfigValidationTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RepoConfigValidationTest.java
integration-test/src/main/java/com/sequenceiq/it/util/TestParameter.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/srm/StreamsReplicationManagerConfigProviderTest.java
template-manager-recipe/src/test/java/com/sequenceiq/cloudbreak/recipe/moduletest/RecipeModulTestModelProvider.java

- based on common agreement we would like to avoid usage of var in CB codebase

deny usage of var

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCloudFormationClient.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsValidatorsTest.java
cloud-aws-common/build.gradle
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsClient.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsSessionCredentialClient.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/client/AwsApacheClient.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsAuthenticatorTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsInstanceConnectorTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsSessionCredentialClientTest.java
cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsStorageValidatorsTest.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNativeMetadataCollectorApiIntegrationTest.java

Merge 271 to 272 2

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterSecurityService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityServiceTest.java
common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/SecretRotationStep.java
common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/type/CloudbreakSecretType.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/Cluster.java
core-model/src/main/java/com/sequenceiq/cloudbreak/view/ClusterView.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterDtoRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/CMUserRotationContext.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/ClusterProxyRotationContext.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/provider/CBCMAdminPasswordRotationContextProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/provider/CMUserRotationContextProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/provider/MgmtCMAdminPasswordRotationContextProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/executor/CMUserRotationExecutor.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/executor/ClusterProxyRotationExecutor.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/context/provider/CBCMAdminPasswordRotationContextProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/context/provider/CMUserRotationContextProviderTestUtils.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/context/provider/MgmtCMAdminPasswordRotationContextProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/executor/CMUserRotationExecutorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/executor/ClusterProxyRotationExecutorTest.java
flow/src/test/java/com/sequenceiq/flow/rotation/service/SecretRotationServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXRotateSecretAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/DistroXTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXSecretRotationTest.java

CB-21539 CM admin password rotation

---

cloudera/docker_images.yaml

SREOPS-11974 adding the java init container to the release artifacts

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2

adding NAMENODE service rule to topology.xml

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AutoscaleV4Controller.java

2.71 to 2.72

---

common/src/main/java/com/sequenceiq/cloudbreak/rotation/secret/README.md

CB-21851 Readme for secret rotation framework

---

integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml

CB-21539 adding CM admin password rotation E2E to AWS suite

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2

CB-21848 adding NAMENODE to the topology

---

.github/CODEOWNERS

CB-22047 Add Armadillo team as owner of datalake dependencies

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceServiceTest.java

Reverts hortonworks/cloudbreak#14987

Revert "CB-11157: Azure database server creation should be idempotent"

---

core/src/main/java/com/sequenceiq/cloudbreak/service/datalake/DataLakeStatusCheckerService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/datalake/DataLakeStatusCheckerServiceTest.java

This user facing error message was very confusing, so I've extended it to avoid misunderstanding.

CB-22122 Clarify error message in DataLakeStatusCheckerService

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXMarketplaceImageTests.java

Removed runtime from sdx request in Azure Marketplace E2E test and switched to use prod image catalog to use up-to-date Azure MP images to test.

CB-22144 Remove runtime property from MP e2e test

---

integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml

CB-22175 remove from testsuite postgres10 upgrade test

---

integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml

272 to master

---

cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/CloudFailureHandler.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceService.java

CB-22183 If disk attach fails, the rollback logic does not remove disks and instance

---

core-api/src/main/java/com/sequenceiq/cloudbreak/rotation/CloudbreakSecretRotationStep.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/context/SaltStateApplyRotationContext.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/executor/SaltStateApplyRotationExecutor.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/executor/SaltStateApplyRotationExecutorTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/rotation/OrchestratorSecretRotationStep.java

CB-21682 fix salt state executor injection issue

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java

CB-18921 Decrease FreeIPA upgrade flakiness

---

orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/logging-agent.conf.j2

CB-22142 CDP logging agent can write hug log files

---

core/src/main/java/com/sequenceiq/cloudbreak/rotation/executor/ClusterProxyRotationExecutor.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/executor/SaltStateApplyRotationExecutor.java
flow/src/main/java/com/sequenceiq/flow/rotation/SecretRotationActions.java
flow/src/main/java/com/sequenceiq/flow/rotation/service/SecretRotationService.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/service/rotation/VaultRotationExecutor.java

CB-21512 Secret rotation - add more logging

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformResources.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
common/src/main/java/com/sequenceiq/cloudbreak/common/network/NetworkConstants.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackToPlacementSettingsV4ResponseConverter.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/EnvironmentNetworkGcpParams.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/gcp/FreeIpaGcpNetworkProvider.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/gcp/GcpEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/NetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/network/CloudNetworkService.java
environment/src/main/java/com/sequenceiq/environment/network/NetworkService.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/GcpNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/GcpEnvironmentNetworkConverter.java
environment/src/main/resources/schema/app/20230608154440_CB-22147_introduce_zonemetas_text_field_for_availability_zones_on_environment_network_table.sql
environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/gcp/FreeIpaGcpNetworkProviderTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/gcp/GcpEnvironmentNetworkValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/NetworkValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/network/CloudNetworkServiceTest.java
environment/src/test/java/com/sequenceiq/environment/network/NetworkServiceTest.java
environment/src/test/java/com/sequenceiq/environment/network/v1/converter/GcpEnvironmentNetworkConverterTest.java
structuredevent-model/src/main/java/com/sequenceiq/environment/network/dto/GcpParams.java

CB-22147 introduce configurable availabilty zone for GCP environments

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/image/ImageSettingsV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/image/StackImageV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/image/DistroXImageV1Request.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXImageToImageSettingsConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/DistroXService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceDefaultNotFoundTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXImageToImageSettingsConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/DistroXServiceTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/ModelDescriptions.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterRequest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceCreateSdxTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorServiceTest.java

Additional fixes:
- Validation was also added to FreeIpa to not accept when both image id and os are set.
- SdxServiceCreateSdxTest was extracted from SdxServiceTest as it became too long (2000+ lines)

CB-21136 Add image os parameter to create DL/DH APIs

---

dependencies.gradle

CB-22260 Update springBootVersion from 2.7.2 to 2.7.12 to avoid a cve

---

core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderService.java
sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/sdx/PaasSdxService.java
sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/sdx/SaasSdxService.java
sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/sdx/SdxService.java

CDPD-43642 abstract sdx classes should not contain paas specific imports

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/EmbeddedDatabaseService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/EmbeddedDatabaseServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/database/DatabaseServiceTest.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/main/resources/application.yml
mock-thunderhead/src/test/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementServiceTest.java

CB-22189 	Remove CDP_CB_DATABASE_WIRE_ENCRYPTION check on backend side

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/services.sls

CB-22306 Modify certmonger systemctl service file to ensure it's started after kdc server is available

CB-22306 Modify certmonger systemctl service file to ensure it's started after kdc server is available

---

datalake/src/main/java/com/sequenceiq/datalake/service/rotation/SdxRotationService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXSecretRotationTest.java

CB-21684 change order of secret rotations in e2e tests

---

integration-test/scripts/download-cbd.sh

CB-22159 modifying the deployer url to private github

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudStack.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/loadbalancer/AwsNativeLoadBalancerLaunchServiceTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilder.java
cloud-azure/src/main/resources/templates/arm-v2-freeipa.ftl
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/cloud/StackToCloudStackConverter.java

FreeIPA Service ARM template changes to support multi AZ configuration

CB-22063 FreeIPA Service ARM template changes to support multi AZ configuration

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java

CB-22354 exposing DL secret rotate API on swagger

---

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/EnvironmentNetworkAzureParams.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/AzureNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/AzureEnvironmentNetworkConverter.java
environment/src/main/resources/application.yml
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverterTest.java
environment/src/test/java/com/sequenceiq/environment/network/v1/converter/AzureEnvironmentNetworkConverterTest.java
structuredevent-model/src/main/java/com/sequenceiq/environment/network/dto/AzureParams.java

Environment Service changes to persist and fetch Azure AZ information

CB-22060 Environment Service changes to persist and fetch Azure AZ information

---

datalake/src/main/resources/application.yml
integration-test/src/main/resources/application.yml

CB-22355 change the default Runtime version to 7.2.17

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/ResourceConnector.java
cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/ResourceConnectorTest.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsResourceConnector.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpdateService.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpdateServiceTest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsAttachmentResourceBuilder.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsEfsResourceBuilder.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AbstractAwsNativeComputeBuilder.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AbstractAzureComputeBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/upscale/AzureVerticalScaleService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/upscale/AzureVerticalScaleServiceTest.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/AbstractGcpComputeBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockResourceConnector.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/UpdateImageHandler.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/testcontext/TestApplicationContext.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/ComputeResourceBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceService.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceUpdateCallable.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceUpdateCallablePayload.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/CoreVerticalScaleHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/verticalscale/FreeIpaVerticalScaleService.java

CB-22348 vertical scale must run only on the targeted group

---

environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/NetworkTestUtils.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidatorTest.java

Environment Service should validate the requested AZs as part of environment creation

CB-22059 Environment Service should validate the requested AZs as part of environment creation

---

core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java
scripts/hooks/pre-push

also corrected the pre-commit hook to accept \s after the ticket id and Reverts

CB-22354 exposing distroxApi for cdpcli

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXMarketplaceImageTests.java

CB-22402 Added logic to only select image ids with MP image for MP e2e test

---

core/src/main/resources/defaults/vm-logs.json
orchestrator-salt/src/main/resources/salt/salt/disks/format-and-mount.sls
orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/find-device-and-format.j2
orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/format-and-mount-common.sh
orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/format-and-mount-initialize.sh
orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/get-uuid-list.j2
orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/mount-disks.j2

CB-22377 Fixed syntax error in disk mount script

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/ResourceConnector.java
cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/ResourceConnectorTest.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsResourceConnector.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpdateService.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpdateServiceTest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsAttachmentResourceBuilder.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsEfsResourceBuilder.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AbstractAwsNativeComputeBuilder.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AbstractAzureComputeBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/upscale/AzureVerticalScaleService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/upscale/AzureVerticalScaleServiceTest.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/AbstractGcpComputeBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockResourceConnector.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/UpdateImageHandler.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/testcontext/TestApplicationContext.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/ComputeResourceBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceService.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceUpdateCallable.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceUpdateCallablePayload.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/CoreVerticalScaleHandler.java
core/src/test/resources/cdp-sdx-enterprise.bp
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/verticalscale/FreeIpaVerticalScaleService.java

Forward merge 273 to master

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/ExternalDatabaseService.java
core/src/main/java/com/sequenceiq/cloudbreak/rotation/executor/RedbeamsPollerRotationExecutor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsClientService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/ExternalDatabaseServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/rotation/executor/RedbeamsPollerRotationExecutorTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/rotation/CloudbreakPollerRotationExecutor.java
datalake/src/main/java/com/sequenceiq/datalake/service/rotation/RedbeamsPollerRotationExecutor.java
datalake/src/main/java/com/sequenceiq/datalake/service/rotation/SdxRotationService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/flowcheck/AbstractFlowService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/flowcheck/CloudbreakFlowService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/flowcheck/RedbeamsFlowService.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxUpgradeValidationResultProvider.java
datalake/src/test/java/com/sequenceiq/datalake/service/rotation/CloudbreakPollerRotationExecutorTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/rotation/RedbeamsPollerRotationExecutorTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/rotation/SdxRotationServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxUpgradeValidationResultProviderTest.java

CB-21838 Implement preValidation steps for poller executors

---

integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml

This reverts commit e6beffeb48b55639e9388a6e0f8d8aa3cb30e94b.

Revert "CB-21539 adding CM admin password rotation E2E to AWS suite"

---

core/src/main/resources/defaults/vm-logs.json
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KeytabCleanupService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientRetryService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/host/HostDeletionService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/host/HostDeletionServiceTest.java
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
orchestrator-salt/src/main/resources/salt/salt/disks/format-and-mount.sls
orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/find-device-and-format.j2
orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/format-and-mount-common.sh
orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/format-and-mount-initialize.sh
orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/get-uuid-list.j2
orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/mount-disks.j2

Merge 2.73.0 into master

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXMarketplaceImageTests.java

CB-22402 Marketplace image id was fetched from the wrong image catalog

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/certrenew/ClusterCertificateRenewTriggerCondition.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/certrenew/ClusterCertificateReissueHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/GatewayPublicEndpointManagementService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/publicendpoint/GatewayPublicEndpointManagementServiceTest.java

CB-22408 remove PEM calls from transaction

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/describe/DescribeFreeIpaResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverter.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverterTest.java

FreeIPA Service API must be able to get AZ configuration and should expose it

CB-22064 FreeIPA Service API must be able to get AZ configuration and should expose it

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/lifetime/ScheduledLifetimeChecker.java

Merge 273 to master

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/image/ImageSettingsV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/image/StackImageV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/image/DistroXImageV1Request.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXImageToImageSettingsConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/DistroXService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceDefaultNotFoundTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXImageToImageSettingsConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/DistroXServiceTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/ModelDescriptions.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterRequest.java
datalake/src/main/java/com/sequenceiq/datalake/service/imagecatalog/ImageCatalogService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/imagecatalog/ImageCatalogServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceCreateSdxTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceValidateRuntimeAndImageTest.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorServiceTest.java

CB-22446 Backport DL/DH os selection to 2.73

---

.github/CODEOWNERS

add raven as codeowner to sdx-connector module
