shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/ClusterCommands.java

CLOUD-57392 cb-shell cluster node needs proper success message

---

core/src/main/resources/defaults/blueprints/hdp-etl-edw.bp
core/src/main/resources/defaults/blueprints/hdp-small-default.bp
core/src/main/resources/defaults/blueprints/hdp-spark-cluster.bp
core/src/main/resources/defaults/blueprints/hdp-streaming-cluster.bp
core/src/main/resources/defaults/blueprints/hdp25-data-science.bp
core/src/main/resources/defaults/blueprints/hdp25-edw-analytics.bp
core/src/main/resources/defaults/blueprints/hdp25-etl-edw-spark2.bp
core/src/main/resources/defaults/blueprints/hdp25-etl-edw.bp

CLOUD-63870 update blueprints to 2.5

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Component.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ComponentRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ComponentConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/HostMetadataSetup.java

CLOUD-64895 fix MARATHON cluster installation

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/OrchestratorBase.java

CLOUD-64528 remove invalid swagger required field

---

integration-test/src/main/resources/testsuites/openstack/credandsmoke/osspark-clustercreate.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/osstreaming-clustercreate.yaml

CLOUD-63869 new tests with spark and streaming bps

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Credential.java

CLOUD-65123 fixed namedquery on credential

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderService.java

@doktoric @biharitomi please review

CLOUD-65082 - AccountId is invalid telemetry e-mail format

---

scripts/build-rc-patch.sh
scripts/build-rc.sh

CLOUD-61470 small modifications in build-scripts

---

scripts/build-rc-patch.sh

CLOUD-61470 put back uploadArchives goal

---

CHANGELOG.md
integration-test/integcb/Profile_template

Synchronize changelog with code base

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ImageJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverterTest.java

CLOUD-65216 echo back Ambari and HDP version in stack response

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnectorTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/NetworkJson.java

Calculatesubnet

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/HdpInfoSearchService.java

CLOUD-61480 - use greatest and latest from image catalog for dev versions

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverterTest.java

CLOUD-64895 fixed region convert for mesos/marathon

---

cloud-arm/src/main/resources/templates/arm-v2.ftl

CLOUD--65419 Cannot create bigger than 999GB size volumes on azure

---

core/src/main/java/com/sequenceiq/cloudbreak/VersionedApplication.java
core/src/main/java/com/sequenceiq/cloudbreak/service/TlsSecurityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sssdconfig/SssdConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/usages/StackUsageGenerator.java

CLOUD-61408 Eliminate criticals by Sonar

---

cloud-arm/src/main/resources/templates/arm-v2.ftl
cloud-arm/src/test/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateBuilderTest.java

CLOUD-55526 Validate ARM template as JSON

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpMetadataCollector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/group/GcpFirewallInResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpFirewallInternalResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpReservedIpResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/NetworkJson.java
web/app/static/messages.properties
web/app/static/tags/network/gcpnetworkform.tag

CLOUD-65287 GCP existing VPC improvements

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/GcpCommands.java

CLOUD-65287 GCP existing VPC improvements, extend shell with new options

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/task/ASGroupStatusCheckerTask.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/task/ASGroupStatusCheckerTaskTest.java

@akanto or @keyki 
This reverts commit fdc464fb9484ebcb5642c912c434a702ee703188.

Consider auto scaling activities in auto scaling group status checker

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/RecipeCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/completion/PluginExecutionType.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommandsTest.java

CLOUD-65660 Sync recipe create command with current behavior

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterTerminationService.java
core/src/main/resources/schema/app/20160920113118_CLOUD-66091_Terminated_clusters_Hive_Metastore_items_cannot_be_deleted.sql

CLOUD-66091 Terminated clusters Hive Metastore items cannot be deleted

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java
core/src/main/resources/defaults/blueprints/hdp-etl-edw.bp

CLOUD-65838 ambari request just with required parameters

---

scripts/build-rc-patch.sh

repackage the jar to avoid esoteric beanwire issue

---

scripts/build-rc-patch.sh

add debug to build script

---

scripts/build-rc-patch.sh

move repackage after release

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/HdpInfoSearchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/HdpInfoSearchServiceTest.java
core/src/test/resources/image/cb-image-catalog.json

- exact dev version support
- prefiltering based on cloud provider and hdp version among ambari blocks
@akanto or @martonsereg pls review

CLOUD-66362 Image catalog improvement

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Blueprint.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/BlueprintInputParameters.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/BlueprintParameter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/BlueprintToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderService.java
core/src/main/resources/schema/app/20160928135412_CLOUD-66496_convert_blueprints_parameters_collection_to_a_json_field.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToBlueprintConverterTest.java

Change input parameters element collection to a json field in Blueprint

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml

CLOUD-66343 New images for reserve ports

---

orchestrator-salt/src/main/resources/salt/salt/ambari/agent.sls

CLOUD-66437 Temporarily turning off parallel command execution in ambari-agents

---

CHANGELOG.md

CLOUD-65865 added changelog for 1.6

---

integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-existing-subnet-in-existing-vpc.yaml
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-new-subnet-in-existing-vpc.yaml
integration-test/src/main/resources/testsuites/azurerm/credandsmoke/azurerm-clustercreate-existing-vpc-subnet.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-existing-legacy-network.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-existing-subnet-existing-network.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-new-subnet-existing-vpc.yaml
integration-test/src/main/resources/testsuites/mock/mock-clustercreate-consul-failed.yaml
integration-test/src/main/resources/testsuites/mock/mock-clustercreate-salt-failed.yaml
integration-test/src/main/resources/testsuites/mock/mock-clustercreate-salt.yaml
integration-test/src/main/resources/testsuites/mock/mock-clustercreate-swarm.yaml
integration-test/src/main/resources/testsuites/mock/mock-scaling-salt.yaml

CLOUD-61480 - use unique names in testsuites

---

core/src/main/resources/init/init.ftl
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh

CLOUD-64886 Fix salt-boostrap on AWS

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParameters.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/VmSpecification.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/VmType.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmPlatformParameters.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java
cloud-aws/src/main/resources/definitions/aws-vm.json
cloud-byos/src/main/java/com/sequenceiq/cloudbreak/cloud/byos/BYOSPlatformParameters.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformParameters.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockPlatformParameters.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackParameters.java
cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/platform/GetVirtualMachineTypesRequest.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/GetVirtualMachineTypesHandler.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ConnectorEndpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/PlatformParameterController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudParameterService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilderTest.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java

CLOUD-66630 added possibility to to filter the vmtype list

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/client/RsaKeyUtil.java

CLOUD-64886 Cache signature parameters

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderService.java

@martonsereg @biharitomi pls review

CLOUD-61483 - remove telemetry mail sending

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
cloud-common/src/main/resources/application.yml

@martonsereg or @akanto  pls review

CLOUD-66888 enable access for cloudbreak to the clusters on aws.

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/SmartSenseConfigProvider.java

Add hst server component to NameNode's hostgroup

---

core/src/main/java/com/sequenceiq/cloudbreak/init/DefaultSubscriptionService.java

CLOUD-67162 ability to set default subscription address in cb

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/RDSConfigJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/RDSDatabase.java

CLOUD-65655 Missing validation on RDSConfigJson connectionURL field

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
cloud-common/src/main/resources/application.yml

CLOUD-67182 inbound access for cloudbreak's secgroup to the clusters

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-common/src/main/resources/application.yml

Secgroup vpc

---

autoscale/src/main/resources/logback.xml
core/src/main/resources/logback.xml

CLOUD-67368 - Remove cloudbreak log highlighting

---

autoscale-api/build.gradle
autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/AlertEndpoint.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/ClusterEndpoint.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/ConfigurationEndpoint.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/HistoryEndpoint.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/PolicyEndpoint.java
autoscale/build.gradle
autoscale/src/main/java/com/sequenceiq/periscope/PeriscopeApplication.java
autoscale/src/main/java/com/sequenceiq/periscope/config/CombinedSwaggerResourcesProvider.java
autoscale/src/main/java/com/sequenceiq/periscope/config/SecurityConfig.java
autoscale/src/main/java/com/sequenceiq/periscope/rest/EndpointConfig.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/BlueprintEndpoint.java

CLOUD-65425 autoscale api with swagger 2

---

autoscale/src/main/java/com/sequenceiq/periscope/rest/EndpointConfig.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/AccountPreferencesEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/BlueprintEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ClusterEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ClusterTemplateEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ConnectorEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ConstraintTemplateEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/CredentialEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/EventEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/LdapConfigEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/NetworkEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/RdsConfigEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/RecipeEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SecurityGroupEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SettingsEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SssdConfigEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/StackEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SubscriptionEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/TemplateEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/TopologyEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UsageEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UserEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UtilEndpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java

CLOUD-64902 fixed swagger invalid fields

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/TemplateBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/TemplateRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/TemplateResponse.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/TemplateController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToTemplateConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/TemplateDecorator.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AwsCommands.java
web/app/static/js/controllers/templateController.js
web/app/static/tags/template/awsform.tag
web/app/static/tags/template/awslist.tag

CLOUD-60209 Calculate ephemeral disk properties on the backend

---

web/app/static/js/controllers/templateController.js
web/app/static/tags/template/awsform.tag

CLOUD-67768 Fix uluwatu missing template volume type in some cases

---

auth/main.js

CLOUD-67911 Fix Sultans base path calculation

---

cloud-common/src/main/resources/application.yml

CLOUD-67989 fix smtp related indentations in application.yml

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/BlueprintBase.java

In case of blueprint creation from url this field can be null
@keyki

CLOUD-67785 fixed bp creation from url

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/UpdateClusterJson.java

CLOUD-67916 Fix reinstall json parsing

---

auth/templates/confirmation-email.jade
auth/templates/invite-email.jade
auth/templates/reset-password-email.jade
core/src/main/resources/templates/cluster-installer-mail-fail.ftl
core/src/main/resources/templates/cluster-installer-mail-success.ftl

CLOUD-68245 updated mails

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java

CLOUD-68113 no transaction for cluster update

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsInstanceProfileView.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderTest.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AwsCommands.java
web/app/static/js/controllers/clusterController.js
web/app/static/messages.properties
web/app/static/tags/stack/configurehostgroups.tag

CLOUD-4859 renamed s3role to instanceprofile

---

web/app/static/js/controllers/recipeController.js
web/app/static/tags/recipe/recipelist.tag

CLOUD-68177 avoid alphabetical order of recipes by filename

---

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/task/interactivelogin/PrincipalCreator.java

CLOUD-67597 - retryable principal creation

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java

CLOUD-65480 spot instance check fix

---

.gitignore
web/app/static/js/controllers/notificationController.js
web/app/static/tags/stack/activecluster.tag

CLOUD-68481 Update node counts as well on Uluwatu

---

cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/Acceptable.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow2Handler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/DownscaleFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ProvisionFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ResetFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/StartFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/StopFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/SyncFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpscaleFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/ClusterScaleTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/StackSyncTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ErrorHandlerAwareFlowEventFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/FlowEventFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/StackEvent.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow/ReactorFlowManagerTest.java

CLOUD-59179 One flow per stack

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow2Handler.java

CLOUD-59179 Fix synchronization scope in flow handler

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/ClusterCommands.java

CLOUD-59179 Fix shell sync commands error handling

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/OfflineStateGenerator.java

CLOUD-58082 Add cluster creation flow to dot generator

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java

CLOUD-68726 return ambari public ip in cluster response

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java

CLOUD-68726 return ambari public ip if the gateway instance has public ip

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java

CLOUD-68726 Only return ambari ip, when ambari is available

---

auth/main.js

@biharitomi @doktoric pls review

CLOUD-68858 Return error if user has multiple accounts

---

core/src/main/java/com/sequenceiq/cloudbreak/service/usages/UsageService.java

CLOUD-67379 fix usage close when status is STOPPED

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakITContextConstants.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTestSuiteInitializer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/startstop/ClusterAndStackStopTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/startstop/ClusterStartTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/startstop/ClusterStopTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/startstop/StackAndClusterStartTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/startstop/StackStartTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/startstop/StackStopTest.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-startstop.yaml

CLOUD-69008 Start / stop e2e api tests improvement

---

web/app/static/js/controllers/securityGroupController.js

Secuirty group duplication cause exception on ui

---

autoscale/src/main/java/com/sequenceiq/periscope/domain/Subscription.java
autoscale/src/main/java/com/sequenceiq/periscope/init/DefaultSubscriptionService.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java
autoscale/src/main/java/com/sequenceiq/periscope/notification/HttpNotificationSender.java
autoscale/src/main/java/com/sequenceiq/periscope/notification/Notification.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/SubscriptionRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/HistoryService.java
autoscale/src/main/java/com/sequenceiq/periscope/subscription/SubscriptionAlreadyExistException.java
autoscale/src/main/java/com/sequenceiq/periscope/subscription/SubscriptionService.java
autoscale/src/main/resources/schema/app/20161115104306_CLOUD-68586_Autoscaling_History_does_not_auto-refresh.sql
web/app/static/js/controllers/notificationController.js
web/app/static/js/controllers/periscopeController.js
web/server.js

CLOUD-68586 Autoscaling History does not auto-refresh

---

core/src/main/java/com/sequenceiq/cloudbreak/service/credential/PublicKeyReaderUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/RsaPublicKeyValidator.java

CLOUD-68600 change invalid ssh key message

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/ShellContext.java

```
cloudbreak-shell>network show --id 8
FIELD            VALUE
---------------  -----------
subnetCIDR       10.0.0.0/8
id               8
name             asdf-public
cloudPlatform    OPENSTACK
publicInAccount  true
cloudbreak-shell>network delete --id 8
Command failed java.lang.RuntimeException
```

CLOUD-69985. RuntimeException after deleting network

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/AmbariJson.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/ClusterState.java
autoscale-api/src/main/java/com/sequenceiq/periscope/doc/ApiDescription.java
autoscale/src/main/java/com/sequenceiq/periscope/model/ClusterCreationEvaluatorContext.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/AmbariAgentHealthMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/ClusterMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/MonitorUpdateRate.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/AmbariAgentHealthEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ClusterCreationEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandler.java
autoscale/src/main/java/com/sequenceiq/periscope/rest/controller/ClusterController.java
autoscale/src/main/java/com/sequenceiq/periscope/service/AlertService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/HistoryService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ScalingService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/security/ClusterSecurityService.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/StackEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackController.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java

Modify periscope to sync new cluster from cb and monitor agents health for recovery

---

integration-test/README.md
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakITContextConstants.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTestSuiteInitializer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RDSConfigTest.java
integration-test/src/main/java/com/sequenceiq/it/util/CleanupService.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-rds.yaml

CLOUD-69586 Create new test suite for RDS configurations

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariDecommissioner.java

CLOUD-67249 host metadata deletion during decomission from ambari

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudInstance.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmResourceConnector.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/view/ArmInstanceView.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/view/ArmStackView.java
cloud-arm/src/main/resources/templates/arm-v2.ftl
cloud-arm/src/test/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateBuilderTest.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/InstanceMetaData.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java

I am testing this patch just wait a bit with merge

Same host names are used on Azure for every cluster

---

autoscale/src/main/java/com/sequenceiq/periscope/model/ClusterCreationEvaluatorContext.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/ClusterMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ClusterCreationEvaluator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/StackEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/AutoscaleStackResponse.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackController.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToAutoscaleStackResponseJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java

CLOUD-67248 making autoscaling stack synchronization more lightweight

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java

CLOUD-67249 remove manual repair notification

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/HostGroupBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Cluster.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/HostGroup.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/HostGroupToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToClusterConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToHostGroupConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java
core/src/main/resources/schema/app/20161212161403_CLOUD-70099_Recoverymode_flag_is_moved_from_cluster_to_hostgroup_level.sql
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/ClusterCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/HostGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/InstanceGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/HostgroupEntry.java

@martonsereg or @biharitomi pls review

CLOUD-70099 Hostgroup based recory_mode for the clusters

---

core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakClient.java

@akanto or @biharitomi pls review
Was tested with 1min token validity time and 1000sec token cache expration duration and worked well. In case of unauth exception, the token was refreshed.

CLOUD-70379 Refresh cloudbreak client auth token if unauthorized exception is thrown during rest call

---

integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-updown-updown.yaml

CLOUD-70202 Create Upscale-Downscale-Upscale E2E flow

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ClusterCreationEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java

CLOUD-70379 ClusterCreationEvaluator has to use the cluster update without permission check.

---

core/src/main/resources/defaults/blueprints/hdp26-druid-bi.bp

In effort to avoid all the unused setting and fix the derby path.

[BUG-71117]use default setting for derby and remove unused properties

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/PortDefinition.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/SecurityRule.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/view/ArmSecurityView.java
cloud-arm/src/test/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateBuilderTest.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderTest.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/group/GcpFirewallInResourceBuilder.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/group/OpenStackSecurityGroupResourceBuilder.java
cloud-openstack/src/main/resources/templates/openstack-heat.ftl
cloud-openstack/src/test/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/HeatTemplateBuilderTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/ParameterGenerator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/SecurityRuleBase.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
web/app/static/js/controllers/securityGroupController.js

@sodre90 please create a cluster on azure before merge

CLOUD-69156 added ability to define port ranges

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/LdapConfigBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/LdapConfig.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToLdapConfigConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/LdapConfigToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverter.java
core/src/main/resources/schema/app/20170102192111_CLOUD-71449_added_stack_tags.sql
core/src/main/resources/schema/app/20170103142952_CLOUD-71449_added_userSearchAttribute_to_ldapconfig.sql
core/src/main/resources/schema/app/20170104093824_CLOUD-71449_added_domain_to_ldapconfig.sql
core/src/test/resources/com/sequenceiq/cloudbreak/converter/stack/ldap_config.json

CLOUD-71449 added domain changes for shared services

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeScript.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/AbstractFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/gcs/GcsFileSystemConfigurator.java
core/src/main/resources/scripts/gcs-connector-hdfs.sh
core/src/main/resources/scripts/gcs-connector-local.sh
orchestrator-salt/src/main/resources/salt/salt/ambari/agent.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/hadoop-classpath.sh
orchestrator-salt/src/main/resources/salt/salt/ambari/server.sls

CLOUD-70291 gcs connector recipe fix: hdfs part only run on one node

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToCredentialConverter.java
core/src/main/resources/schema/app/20170111085207_CLOUD-72055_use_cloudbreak_user_by_default.sql

OpenStack will be fixed under a different Jira, since it requires image burning etc.

CLOUD-72055 Cloudbreak does not work with CentOS on AWS

---

core/src/main/resources/defaults/blueprints/hdp26-etl-edw.bp

This PR adds missing common properties and node type.

BUG-71237 add common pros and other nodes

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudStack.java
cloud-arm/src/test/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateBuilderTest.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsTagPreparationService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnectorTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsTagPreparationServiceTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderTest.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackResourceConnector.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/ParameterGenerator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackBase.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java

CLOUD-70679 Support user-specified tags for AWS resources

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/StackEndpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackController.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/DependecyDeletionService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackForceTerminationAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationFailureAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationFinishedAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/TerminationEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/service/account/ScheduledAccountPreferencesValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow/ReactorFlowManagerTest.java
integration-test/src/main/java/com/sequenceiq/it/util/CleanupService.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/marathon/MarathonCommands.java

CLOUD-72266 delete cluster dependencies after termination

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AwsCheckSpotInstance.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AwsTemplateCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakITContextConstants.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/StackCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/scaling/ClusterAndStackDownscaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/scaling/ScalingUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/scaling/StackAndClusterUpscaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/scaling/StackScalingTest.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-spot.yaml

CLOUD-70659 Create new API automated test suite for Spot Instances

---

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateBuilder.java
cloud-arm/src/main/resources/templates/arm-v2.ftl
cloud-arm/src/test/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateBuilderTest.java

CLOUD-72768 Support user-specified tags for Azure resources

---

cloud-aws/src/main/resources/definitions/aws-vm.json

CLOUD-71038 added r4 instances

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Cluster.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecorator.java
core/src/main/resources/schema/app/20170123093709_added_validation_to_cluster.sql
gradle.properties

CLOUD-72005 topology validation added to cluster object

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ClusterCreationEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java

CLOUD-71006 fix cluster state updater mechanism of recovery

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpDiskResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackAttachedDiskResourceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackFloatingIPBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackInstanceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackPortBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/ComputeResourceBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceService.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceCreateThread.java

CLOUD-73107 Support user-specified tags for GCP resources

---

cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/HeatTemplateBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackResourceConnector.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackInstanceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/view/NovaInstanceView.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/view/OpenStackGroupView.java

CLOUD-73317 Support user-specified tags for OpenStack resources

---

core/src/main/resources/defaults/blueprints/hdp26-data-science-spark2.bp

CLOUD-72005 added new datascience bp

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackParameterService.java

CLOUD-73714 fixed parameter validation if credentialid null

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AwsCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AzureCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/GcpCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/OpenStackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/util/TagParser.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/util/TagParserTest.java

CLOUD-70679 Support user-specified tags for AWS resources, shell support

---

CHANGELOG.md
cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/RdsType.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Cluster.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/RDSConfig.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/RdsConfigRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/RDSConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecorator.java
core/src/main/resources/schema/app/20170130125235_CLOUD-73592_ability_to_specify_more_rdsconfig.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToClusterConverterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/ClusterCommands.java

CLOUD-73592 ability to define more metastore

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterRequest.java

CLOUD-73592 rds json setter for more rdsconfig

---

core/src/main/resources/defaults/blueprints/hdp26-etl-edw-shared.bp

CLOUD-74224 fixed druid components in shared service bp

---

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmPlatformParameters.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParametersConsts.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformParameters.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackParameters.java
core/src/main/java/com/sequenceiq/cloudbreak/service/account/AccountPreferencesValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/account/ScheduledAccountPreferencesValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/lifetime/ScheduledLifetimeChecker.java
web/app/static/js/controllers/clusterController.js
web/app/static/messages.properties
web/app/static/tags/stack/configurecluster.tag

CLOUD-72993 Pre-configurable cluster lifetime

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/start/ClusterStartService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stop/ClusterStopService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upgrade/ClusterUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleFlowService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartStopService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariViewProvider.java

CLOUD-74310 show ambari pulbic ip instead of private ip if it's available

---

cloud-common/src/main/resources/application.yml

CLOUD-74882 Update HDP and Ambari versions to match HDC

---

integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recovery/AbstractAutoRecoveryTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recovery/AbstractManualRecoveryTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recovery/AwsAutoRecoveryTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recovery/AwsManualRecoveryTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recovery/OpenstackAutoRecoveryTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recovery/OpenstackManualRecoveryTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recovery/RecoveryUtil.java
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-autorecovery.yaml
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-manualrecovery.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-autorecovery.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-manualrecovery.yaml

CLOUD-71221 Create new API test suite for Node Recovery

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/RecipeCommands.java

CLOUD-75652 Unable to delete recipe via shell

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/RecipeCommands.java

CLOUD-75652 recipe show command fix

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recovery/AwsAutoRecoveryTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recovery/AwsManualRecoveryTest.java

CLOUD-71221 region parameter fix

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ExposedService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/DruidSupersetConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/network/NetworkUtils.java
core/src/main/resources/defaults/blueprints/hdp26-druid-bi.bp
core/src/main/resources/defaults/blueprints/hdp26-etl-edw-shared.bp

In This PR i have added superset UI as part of the druid bi cluster.
Also since it is a master need to be present on the ETL cluster otherwise install can fail.
Injecting email, admin user name and password. The idea is to use the same password and user name for ambari.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sequenceiq/cloudbreak/2250)

[BUG-73456] adding superset and move broker to master group

---

autoscale/src/main/resources/alerts/prometheus/namenode_capacity_threshold_exceeded.ftl

@zoltanzseli please check the fix

Fix namenode capacity threshold exceded template's description

---

autoscale/build.gradle
autoscale/src/main/java/com/sequenceiq/periscope/config/DatabaseConfig.java
cloud-common/build.gradle
cloud-common/src/main/java/com/sequenceiq/cloudbreak/util/DatabaseUtil.java
cloud-common/src/main/resources/application.yml
core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java
integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java

@martonsereg or @mhmxs pls review

CLOUD-75962 ability for cloudbreak and periscope to use schemas inside the postgres databases

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UtilEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/LdapTestResult.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/UtilController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/ldapconfig/LdapConfigValidator.java

CLOUD-76661 added enpoint for ldap connection test

---

web/app/static/messages.properties

CLOUD-76738 Update message on Finish tab in credential creation wizard

---

cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackInstanceBuilder.java
integration-test/src/main/java/com/sequenceiq/it/util/CleanupService.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java

CLOUD-76828 Cloudbreak shell startup fix

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java

CLOUD-75991 using gateway publicip in cluster response

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/Msg.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationService.java
core/src/main/resources/messages/messages.properties

CLOUD-76529 Credential create previous failure message still remains

---

core/src/main/resources/defaults/blueprints/hdp26-druid-bi.bp
core/src/main/resources/defaults/blueprints/hdp26-etl-edw-shared.bp
core/src/main/resources/defaults/blueprints/hdp26-etl-edw.bp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sequenceiq/cloudbreak/2324)

[BUG-76973][BUG-76455] fix missing properties of superset

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/AbstractMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/AmbariAgentHealthMonitor.java

Do not switch off autorecovery when autoscaling disabled manually

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageNameUtil.java
core/src/main/resources/defaults/blueprints/hdp26-data-science-shared.bp
core/src/main/resources/defaults/blueprints/hdp26-data-science-spark2-shared.bp
core/src/main/resources/defaults/blueprints/hdp26-druid-bi-shared.bp
core/src/main/resources/defaults/blueprints/hdp26-edw-analytics-shared.bp
core/src/main/resources/defaults/blueprints/hdp26-etl-edw-spark2-shared.bp
core/src/main/resources/defaults/blueprints/hdp26-shared-services.bp

1. Set hive warehouse dir to S3
2. Enabled ranger hive plugin for hive2

CLOUD-76213 Enable ranger hive plugin for hive2

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/AccountPreferencesEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/BlueprintEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ClusterEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ClusterTemplateEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ConnectorEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ConstraintTemplateEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/CredentialEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/EventEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/LdapConfigEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/NetworkEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/RdsConfigEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/RecipeEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SecurityGroupEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SettingsEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SssdConfigEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/StackEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SubscriptionEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/TemplateEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/TopologyEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UsageEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UserEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UtilEndpoint.java

CLOUD-77535 fixed swagger operationids

---

orchestrator-salt/src/main/resources/salt/salt/ambari/agent.sls

CLOUD-77567 extend SPARK_CLASSPATH only in case of gcp cloud provider

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/CloudbreakUsage.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/usages/UsageGeneratorService.java
core/src/main/resources/schema/app/20170322090940_CLOUD-76685_UUID_should_be_assigned_to_Cluster_and_Stack_domain_objects.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToCloudbreakUsageConverterTest.java

CLOUD-76685 UUID should be assigned to Cluster and Stack domain objects

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/LdapConfigBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/LdapConfigRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/LdapConfigToJsonConverter.java

CLOUD-74241 ldap response fix

---

core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecorator.java

CLOUD-74241 fixed ldap cluster request

---

cloud-common/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/hdp24-etl-edw.bp
core/src/main/resources/defaults/blueprints/hdp25-data-science.bp
core/src/main/resources/defaults/blueprints/hdp25-edw-analytics.bp
core/src/main/resources/defaults/blueprints/hdp25-etl-edw-spark2.bp
core/src/main/resources/defaults/blueprints/hdp25-etl-edw.bp
core/src/main/resources/defaults/blueprints/hdp26-data-science-spark2.bp
core/src/main/resources/defaults/blueprints/hdp26-druid-bi.bp
core/src/main/resources/defaults/blueprints/hdp26-etl-edw.bp

CLOUD-78056 updated bps

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/ResourceType.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverter.java

CLOUD-78078 added vpcid and subnet id to stack response

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java

CLOUD-78087 added vpc and subnet in case if both exist

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java

CLOUD-75554 security config for daily flex usage endpoint

---

autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java

CLOUD-77736 fix nullpointer in validation of cluster uniqueness

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UsageEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/CloudbreakUsageController.java
core/src/main/java/com/sequenceiq/cloudbreak/facade/DefaultCloudbreakUsagesFacade.java

Use java.time.LocalDate instead of Calendar as simplification.

CLOUD-75554 new endpoint for flex usages on the given day

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToClusterConverter.java

CLOUD-78627 Default value is used for enableGateway if its value is null in cluster request

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltConnector.java

CLOUD-78751 Close saltconnector.upload jersey responses properly

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/ldapconfig/LdapConfigValidator.java

CLOUD-78811 added ldap connection timeout

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverter.java

CLOUD-78426 optimistic lock fix

---

core/src/main/resources/defaults/blueprints/hdp26-shared-services.bp

CLOUD-76506 removed hive metastore

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/JacksonBlueprintProcessor.java

CLOUD-78970 fixed settings generation

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/JacksonBlueprintProcessor.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/JacksonBlueprintProcessorTest.java
core/src/test/resources/blueprints/bp-with-settings-array.bp
core/src/test/resources/blueprints/bp-without-settings-array.bp
core/src/test/resources/blueprints/settings-bp-result.bp
core/src/test/resources/blueprints/with-settings-bp-result.bp

CLOUD-78970 added tests to settings generation

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/ClusterAttributes.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToClusterConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/config/ContainerConfigBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ContainerConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariViewProvider.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/ContainerConfig.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestratorTest.java
orchestrator-yarn/src/main/java/com/sequenceiq/cloudbreak/orchestrator/yarn/handler/ApplicationSubmissionHandler.java
orchestrator-yarn/src/main/java/com/sequenceiq/cloudbreak/orchestrator/yarn/model/request/CreateApplicationRequest.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/ClusterCommands.java
web/app/static/js/controllers/clusterController.js
web/app/static/js/services.js
web/app/static/messages.properties
web/app/static/tags/stack/configurecluster.tag

CLOUD-55600 configurable yarn queue

---

integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AutoscaleTestSuiteInitializer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakITContextConstants.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/autoscaling/AutoScalingPrometheusTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/autoscaling/AutoscalingUtil.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-autoscale.yaml

CLOUD-76686 Create new E2E API tests for auto scaling

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DefaultHDPInfo.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DefaultHDPInfos.java
cloud-common/src/main/resources/application.yml
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintUtils.java

CLOUD-79430 fixed hdp and ambari version

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java

CLOUD-76776 fix flex subscription delete

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/FlexSubscriptionEndpoint.java

CLOUD-75554 fix private flex subscription deletion's nickname

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UtilEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/RDSBuildRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/RdsBuildResult.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/UtilController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/rds/RdsConnectionBuilder.java

CLOUD-78287 added database creation endpoint

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/AmbariDatabaseDetailsToAmbariDatabaseJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java

CLOUD-79860 added ambari database to cluster response

---

autoscale/src/main/resources/application.yml
cloud-common/src/main/resources/application.yml

CLOUD-80097 updated hdp and ambari version

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/UtilController.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/UtilControllerTest.java

CLOUD-80251 database can not contains special characters

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/SmartSenseConfigProvider.java
core/src/main/resources/defaults/blueprints/hdp26-shared-services.bp

CLOUD-80474 fixed HST_SERVER addition

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UtilEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/UtilController.java

CLOUD-80509 added ldap connection check by id

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseTemplateCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/ShellContext.java

EAR-5997 template nullpointer fix

---

autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java

Periscope NullPointerException fix

---

core/src/main/java/com/sequenceiq/cloudbreak/service/flex/FlexSubscriptionService.java

@mhmxs using 'name' everywhere...

CLOUD-80519 Fix Flex use and set method, fix set

---

autoscale/src/main/java/com/sequenceiq/periscope/domain/Ambari.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/BaseAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/Cluster.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/History.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/Notification.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/ScalingPolicy.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/SecurityConfig.java
autoscale/src/main/resources/schema/app/20170525111458_CLOUD-81663_Fix_periscope_sequences.sql

@keyki or @mhmxs or @akanto pls review

CLOUD-81663 Periscope db sequence fixes

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderTest.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpResourceConnector.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/OpenStackNativeResourceConnector.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/service/CloudbreakResourceNameService.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java

CLOUD-80482 Handle EIPs on gateway repair

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl

CLOUD-80482 Remove '_' from eip resources in cfn template

---

orchestrator-salt/src/main/resources/salt/salt/ambari/agent.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/settings.sls
orchestrator-salt/src/main/resources/salt/salt/unbound/config/00-cluster.conf

CLOUD-82116 kerberos fix

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsGroupView.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl

CLOUD-81295 gateways are deployed into different subnets on aws in case of existing vpc existing subnets

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java

CLOUD-81295 Using different subnets only if multiple gateway is used

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterTerminationService.java

CLOUD-81338 fixed ldap termination

---

core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/template/BlueprintTemplateProcessor.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/BlueprintTemplateProcessorTest.java
core/src/test/resources/blueprints/bp-mustache-test.bp

CLOUD-82510 fixed templating engine

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariDecommissioner.java

I'm not sure how it works on HDC with compute nodes. I suspect you cannot downscale compute nodes.
Update: it works there, because there is a NM in the compute group

CLOUD-82519 don't check DN decommission if there is no DN

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandler.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/InstanceMetaDataJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/MetaDataToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterComponentConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java

CLOUD-81393 Periscope detects ambariserver failure and reports it to cloudbreak

---

gradle.properties

CLOUD-82601 Ambari operation progress fix

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSetup.java

CLOUD-82793 fixed opt in error

---

core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/AmbariClusterUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/OrchestratorRecipeExecutor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostRecipeExecutor.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

CLOUD-82696 upload recipes to the gateway nodes during gateway recover

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow2Handler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/repair/ChangePrimaryGatewayService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/Msg.java
core/src/main/resources/messages/messages.properties
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

CLOUD-78517 Change primary gateway flow can be restartable

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseInstanceGroupCommands.java

CLOUD-80499 Allow multi gw setup with CB Shell

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/json/EncryptedJsonToString.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariViewProvider.java

CLOUD-83682 fixed decryption logic

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ExecutorType.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Cluster.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToClusterConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/ContainerExecutorConfigProvider.java
core/src/main/resources/defaults/blueprints/hdp26-infra-pool.bp
core/src/main/resources/schema/app/20170607154539_Add_executor_type_to_cluster_object.sql
core/src/main/resources/scripts/configure-container-executor.sh
orchestrator-salt/src/main/resources/salt/pillar/docker/init.sls
orchestrator-salt/src/main/resources/salt/pillar/top.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/agent.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/setup_container_executor_agent.sh
orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/setup_container_executor_server.sh
orchestrator-salt/src/main/resources/salt/salt/ambari/server.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/settings.sls
orchestrator-salt/src/main/resources/salt/salt/docker/init.sls
orchestrator-salt/src/main/resources/salt/salt/top.sls
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/ClusterCommands.java
web/app/static/js/controllers/clusterController.js
web/app/static/js/services.js
web/app/static/messages.properties
web/app/static/tags/stack/configurecluster.tag

CLOUD-83298 added container executor

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java

CLOUD-83682 provide view definition fixed

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/Status.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariViewProvider.java

CLOUD-83682 do not call view definition on stopped clusters

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParameters.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformParameters.java
cloud-byos/src/main/java/com/sequenceiq/cloudbreak/cloud/byos/BYOSPlatformParameters.java
cloud-common/src/main/resources/application.yml
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformParameters.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockPlatformParameters.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackParameters.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilderTest.java

CLOUD-83908 fixed platform defaults

---

integration-test/scripts/download-cbd.sh

CLOUD-83982 fixed build issue

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/resources/schema/app/20170713112316_CLOUD-84189_ambari_database_migrate_to_cluster.sql

CLOUD-84189 fixed components table

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/EventEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/StackEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UtilEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/LdapValidationRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackValidationRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/CloudbreakEventController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/UtilController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/ldapconfig/LdapConfigValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackValidationConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackRequestToStackValidationRequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/facade/CloudbreakEventsFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/facade/DefaultCloudbreakEventsFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/CloudbreakEventRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/responseprovider/StackResponseEventProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/events/CloudbreakEventService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java

cluster and stack request in the same json

---

orchestrator-yarn/src/main/java/com/sequenceiq/cloudbreak/orchestrator/yarn/model/core/Container.java

The YARN Native Services API has been updated and includes several additional fields in the application detail response.

CLOUD-84740 Add fields to the application detail response for the YARN Orchestrator

---

cloud-aws/aws-images.tmpl
cloud-azure/azure-images.tmpl
cloud-gcp/gcp-images.tmpl
cloud-openstack/os-images.tmpl

CLOUD-84095 use new atlas artifacts

---

core/src/main/java/com/sequenceiq/cloudbreak/logger/ControllerLogContextAspects.java

CLOUD-84172 LogContext Nullpointer fix if no user given

---

autoscale-api/src/main/java/com/sequenceiq/periscope/client/AutoscaleClient.java
autoscale/src/main/java/com/sequenceiq/periscope/config/AppConfig.java
autoscale/src/main/java/com/sequenceiq/periscope/config/RemoteTokenConfig.java
autoscale/src/main/java/com/sequenceiq/periscope/notification/HttpNotificationSender.java
autoscale/src/main/resources/application.yml
cloud-common/src/main/java/com/sequenceiq/cloudbreak/client/ConfigKey.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/client/IdentityClient.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/client/RestClientUtil.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/service/token/CachedRemoteTokenService.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/service/user/CachedUserDetailsService.java
cloud-common/src/main/resources/application.yml
core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/RemoteTokenConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/notification/HttpNotificationSender.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AutoscaleTestSuiteInitializer.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

CLOUD-85581 configurable https service between cb and identity

---

integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-startstop.yaml

CLOUD-85639 change instance type in start/stop aws tests

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/GcsFileSystemConfiguration.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/AbstractFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/FileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/adls/AdlsFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/gcs/GcsFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasb/WasbFileSystemConfigurator.java
orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/hadoop-classpath.sh
web/app/static/js/controllers/clusterController.js

CLOUD-86039 hadoop-classpath.sh does not run properly, GCS connector missing from HADOOP_CLASSPATH

CLOUD-85884 [Cloudbreak] Cannot create cluster with GCS fs

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/AccountPreferencesJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/AccountPreferences.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/AccountPreferencesToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToAccountPreferencesConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/main/resources/schema/app/20170808124521_CLOUD-85571_Ability_to_specify_default_tags_for_a_user.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverterTest.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/AccountPreferencesCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseAccountPreferencesCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/configuration/CommandDefinition.java
web/app/static/js/controllers/clusterController.js

CLOUD-85571 Ability to specify default tags for a user

---

autoscale/src/main/java/com/sequenceiq/periscope/log/ControllerLogContextAspects.java
autoscale/src/main/java/com/sequenceiq/periscope/log/MDCBuilder.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/AbstractMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/AmbariAgentHealthMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/AmbariAgentHealthEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ClusterCreationEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/CronTimeEvaluator.java

@biharitomi or @keyki pls review

CLOUD--84173 Log context cleanup in Periscope

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/AbstractAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/restart/DefaultRestartAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ErrorHandlerAwareFlowEventFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/FlowEventFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/logger/LogContextAspects.java
core/src/main/java/com/sequenceiq/cloudbreak/logger/MDCBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackParameterService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow/ReactorFlowManagerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/AbstractActionTest.java

CLOUD-84172 logcontext cleanup fixes

---

core/src/main/java/com/sequenceiq/cloudbreak/logger/ControllerLogContextAspects.java

CLOUD-84172 NullPointerException fix during logcontext creation

---

integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudProviderParamsInitializer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakITContextConstants.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SshUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/filesystem/FilesystemConfigureTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/filesystem/FilesystemTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/filesystem/FilesystemUtil.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/azure/credandsmoke/azure-clustercreate-adls.yaml
integration-test/src/main/resources/testsuites/azure/credandsmoke/azure-clustercreate-wasb.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-gcs.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-autorecovery.yaml

BUG-63867 Extend Cloudbreak API E2E testcases

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DiskTypes.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/PlatformDisks.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureDiskType.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformParameters.java
cloud-byos/src/main/java/com/sequenceiq/cloudbreak/cloud/byos/BYOSPlatformParameters.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformParameters.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockPlatformParameters.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackParameters.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/GetDiskTypesHandler.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ConnectorEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/PlatformDisksJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/PlatformParameterController.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/CloudNetworksToPlatformNetworksResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/CloudSecurityGroupsToPlatformSecurityGroupsResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/CloudSshKeysToPlatformSshKeysResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/PlatformDiskTypesToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/util/PlatformConverterUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilderTest.java

CLOUD-87361 added displaynames to api responses

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/StackTags.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/main/resources/schema/app/20170905181325_updated_tags_on_stack_table.sql
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/StackCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/tags/TagsUtil.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java

CLOUD-87519 unified tag handling

---

performance-test/conf/gatling-akka.conf
performance-test/conf/gatling.conf
performance-test/conf/logback.xml
performance-test/conf/recorder.conf
performance-test/perftest.sh
performance-test/user-files/simulations/cloudbreak/BlueprintRequests.scala
performance-test/user-files/simulations/cloudbreak/CloudbreakSimulation.scala
performance-test/user-files/simulations/cloudbreak/CredentialRequests.scala
performance-test/user-files/simulations/cloudbreak/Feeders.scala
performance-test/user-files/simulations/cloudbreak/HttpHeaders.scala
performance-test/user-files/simulations/cloudbreak/NetworkRequests.scala
performance-test/user-files/simulations/cloudbreak/SecurityGroupRequests.scala
performance-test/user-files/simulations/cloudbreak/StackRequests.scala
performance-test/user-files/simulations/cloudbreak/TemplateRequests.scala
performance-test/user-files/simulations/cloudbreak/Utils.scala
performance-test/user-files/simulations/cloudbreak/resources/create-blueprint.json
performance-test/user-files/simulations/cloudbreak/resources/create-cluster-azure.json
performance-test/user-files/simulations/cloudbreak/resources/create-stack-azure.json

@sodre90 plz check, it's working with azure (not mock)

CLOUD-87983 Create perftest POC with gatling

---

cloud-api/build.gradle
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParameters.java
cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/PlatformParametersTest.java

CLOUD-87594 fixed platform parameters

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/service/user/CachedUserDetailsService.java

account = StringUtils.isEmpty(account) ? userId : account;

CLOUD-88220 use the user id if there is no account scope

---

structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/InstanceGroupDetails.java

CLOUD-87419 remove comments

---

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/StructuredFlowEventFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/BlueprintToBlueprintDetailsConverter.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/BlueprintDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/ClusterDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/FlowDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/InstanceGroupDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/OperationDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/SecurityGroupDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/SecurityRuleDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StackDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredFlowErrorEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredFlowEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/json/Base64Deserializer.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/json/Base64Serializer.java

CLOUD-87423 base64 encoding can be used for text fields

---

core/src/main/resources/schema/app/20170924095147_CLOUD-87449_new_members_of_structuredevent_table_to_be_used_for_storing_notifications.sql
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/BlueprintDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/ClusterDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/FlowDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/InstanceGroupDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/NotificationDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/OperationDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/SecurityGroupDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/SecurityRuleDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StackDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredFlowErrorEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredNotificationEvent.java

CLOUD-87449 migration script fix

---

core/src/main/resources/schema/app/20170924095147_CLOUD-87449_new_members_of_structuredevent_table_to_be_used_for_storing_notifications.sql

CLOUD-87449 migration script fix part 2.

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/AbstractAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow2Handler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/FlowAdapter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/FlowStructuredEventHandler.java

CLOUD-88329 structured event about flow cancellation

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recovery/AutoRecoveryTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recovery/ManualRecoveryTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recovery/RecoveryUtil.java

CLOUD-88161 Eliminate goto from Cloudbreak code base

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SshUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/filesystem/FilesystemTest.java
integration-test/src/main/resources/testsuites/azure/credandsmoke/azure-clustercreate-adls.yaml
integration-test/src/main/resources/testsuites/azure/credandsmoke/azure-clustercreate-wasb.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-gcs.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-autoscale.yaml

CLOUD-87462 Extend filesystem tests

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/kerberos/KerberosTypeResolver.java
integration-test/src/main/resources/testsuites/openstack/credandsmoke/oskerb-clustercreate-startstop-updown.yaml

EAR-7009 kdc-type default value is mit-kdc insteadof null

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java
integration-test/src/main/resources/testsuites/openstack/credandsmoke/oskerb-clustercreate-startstop-updown.yaml

EAR-7009 Fix kerberos e2e test

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToClusterConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackRequestToStackValidationRequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/template/BlueprintTemplateProcessor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecorator.java

Cluster creation doesn't work without these fixes

CLOUD-89509 Fix resources by name in stack request

---

structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/OperationDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredFlowErrorEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredNotificationEvent.java

BUG-89835 Getters and setters for structured event classes

---

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/ClusterToClusterDetailsConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverter.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/ClusterDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StackDetails.java

BUG-89835 structured event model improvements and fixes

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformResources.java

BUG-89399 fixed azure recommendation

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/UserProfile.java
core/src/main/resources/schema/app/20171013125421_CLOUD-90147_add_contraint_to_userprofile.sql

CLOUD-90147 Userprofile with UniqueConstraint

---

.gitignore
cloud-aws/src/main/resources/aws-images.yml
cloud-azure/src/main/resources/azure-images.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilder.java
core/src/main/resources/init/init.ftl
core/src/test/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilderTest.java
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh

fix ssh key and upgrading salt

---

.gitignore
cloud-aws/src/main/resources/aws-images.yml
cloud-azure/src/main/resources/azure-images.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilder.java
core/src/main/resources/init/init.ftl
core/src/test/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilderTest.java
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh

Reverts hortonworks/cloudbreak#2812

Revert "fix ssh key and upgrading salt"

---

.gitignore
cloud-aws/src/main/resources/aws-images.yml
cloud-azure/src/main/resources/azure-images.yml
cloud-common/src/main/resources/application.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackInstanceConnector.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackAttachedDiskResourceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackInstanceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/view/NovaInstanceView.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/view/OpenStackGroupView.java
cloud-openstack/src/main/resources/os-images.yml
cloud-openstack/src/main/resources/templates/openstack-heat.ftl
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/main/resources/init/init.ftl
core/src/test/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilderTest.java
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh

ssh key problem on amazon when using sshkeyid
- Salt upgrade
- pass loginUser to heattemplate
- we are able to start cluster from amazon ssh key id
- removed to pass pubkey to startup script

CLOUD-90057 ssh key problem on amazon when using sshkeyid

---

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/StructuredEventFilter.java

CLOUD-87422 nullpointer fix

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/MetricType.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/AbstractAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/FlowRegister.java

Expose the number of active flows to see how many flows each node is running.

CLOUD-88948 expose the number of active flows

---

core/src/main/java/com/sequenceiq/cloudbreak/filter/MDCContextFilter.java

CLOUD-90528 set ownerid in MDCContextFilter

---

core-api/build.gradle
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v1/EventEndpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/CloudbreakEventController.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/StructuredEventService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/StructuredEventDBService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/converter/StructuredEventEntityToStructuredEventConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/StructuredEventFilter.java

CLOUD-90694 Downloadable structured events for a specific stack

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariOperationsStatusCheckerTask.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ImageStatusCheckerTask.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/StructuredFlowEventFactory.java
core/src/main/resources/schema/app/20171031115527_CLOUD-91043_extend_stack_with_display_name.sql

CLOUD-91043 extend Stack with displayName field

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureSetup.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceCreateThread.java

CLOUD-91218 catch Exception insteadof RuntimeException in ResourceCreateThread

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformResources.java

Retrieve Azure VM's memory size in gigs instead of MBs.

CLOUD-91588 retreive Azure VM's memory in GB

---

core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/BlueprintLoaderService.java
core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/DefaultBlueprintCache.java
core/src/main/resources/defaults/blueprints/hdp26-data-science-shared.bp
core/src/main/resources/defaults/blueprints/hdp26-data-science-spark2-shared.bp
core/src/main/resources/defaults/blueprints/hdp26-data-science-spark2.bp
core/src/main/resources/defaults/blueprints/hdp26-data-science.bp
core/src/main/resources/defaults/blueprints/hdp26-druid-bi-shared.bp
core/src/main/resources/defaults/blueprints/hdp26-druid-bi.bp
core/src/main/resources/defaults/blueprints/hdp26-edw-analytics-shared.bp
core/src/main/resources/defaults/blueprints/hdp26-edw-analytics.bp
core/src/main/resources/defaults/blueprints/hdp26-etl-edw-shared.bp
core/src/main/resources/defaults/blueprints/hdp26-etl-edw-spark2.bp
core/src/main/resources/defaults/blueprints/hdp26-etl-edw.bp

https://hortonworks.jira.com/browse/BUG-91981 we should update the description on the default blueprints as well

CLOUD-91981 Update default blueprint descriptions

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackValidationRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackValidationConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackRequestToStackValidationRequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/BlueprintRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecorator.java

4 calls have been reduced to 1

CLOUD-92129 reduce the blueprint repo calls on v2 API

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/StackSensitiveDataPropagator.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackValidationConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackRequestToStackValidationRequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToStackResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/RecipeRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/HostGroupDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/StackDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/recipe/RecipeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackParameterService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverterTest.java

CredentialRepo findByName was called 6 times for 1 stack request

CLOUD-92129 reduce the credential repo calls on v2 API

---

cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnConnector.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnConstants.java

CLOUD-91577 introducing YCloudConstant class

---

README.md

Opensource projects are analysed for free of charge: https://codeclimate.com/github/hortonworks/cloudbreak/maintainability

Add fancy maintainibility analysis from codeclimate

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/LdapConfigBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/LdapConfig.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToLdapConfigConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/LdapConfigToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
core/src/main/resources/schema/app/20171130102238_DPAAS-83_added_ambari_admin_group_for_ldap_config.sql
core/src/test/resources/com/sequenceiq/cloudbreak/converter/stack/ldap_config.json
orchestrator-salt/src/main/resources/salt/pillar/top.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/setup-ldap.sh
orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/sync-ldap.sh
orchestrator-salt/src/main/resources/salt/salt/ambari/server.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/settings.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/sync-ldap.sls
orchestrator-salt/src/main/resources/salt/salt/top.sls

For user and group sync a running Ambari is required so it has been triggered with the POST_AMBARI_START recipe hook.

auto configure ldap for ambari if it's specified

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/EphemeralClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stop/ClusterStopService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/sync/StackSyncActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleService.java

@schfeca75 plz check
Closes BUG-91669

CLOUD-91669 ui shows ambari failure as 'green'

---

core/src/main/resources/defaults/blueprints/hdp26-etl-edw.bp

From template the INSTALL_ONLY action removed, so the cluster won't be in unhealthy state.

CLOUD-91077 Druid services INSTALL_ONLY removed

---

gradle.properties

CLOUD-92658 blueprint configuration improvement: don't override existing config params

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParameters.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParametersConsts.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnInstanceConnector.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnPlatformParameters.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackV2Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudParameterCache.java

CLOUD-91577 Scaling, start/stop are currently unsupported on ycloud

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformResources.java

Response should have the same structure as for other providers

CLOUD-92603 GCP security group response refactor

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ImageCatalogBase.java
core-api/src/test/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ImageCatalogBaseTest.java

@akanto plz check
Closes CLOUD-93025

CLOUD-93025 ImageCatalog URL is not validated on the API

---

cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnConstants.java

CLOUD-91577 platform enable fix

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
orchestrator-salt/src/main/resources/salt/salt/ambari/server.sls

However, it still does not work with "Enterprise Admins" nor "enterprise admins"

DPAAS-83 fix auto configuration of LDAP when there are no recipes added

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/service/user/CachedUserDetailsService.java

@akanto only
We can use the john@acme1.com email and acme1.com as the account.

CLOUD-92165 use the domain as account in case of jwt token

---

autoscale/src/main/java/com/sequenceiq/periscope/config/DatabaseConfig.java
autoscale/src/main/java/com/sequenceiq/periscope/config/ServiceEndpointConfig.java
autoscale/src/main/resources/application.yml

solving https://hortonworks.jira.com/browse/BUG-93253
the db configuration is now following the same scheme as cloudbreak
@keyki

CLOUD-93253 support ssl for periscope db

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariRepositoryVersionService.java
gradle.properties
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockClusterCreationWithSaltSuccessTest.java
integration-test/src/main/java/com/sequenceiq/it/spark/ambari/AmbariVersionDefinitionResponse.java

CLOUD-93033 version definition posted only once to ambari

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/StackRepoDetails.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariRepositoryVersionService.java

CLOUD-93528 cloning StackRepoDetails before the modification

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
orchestrator-salt/src/main/resources/salt/pillar/metadata/init.sls
orchestrator-salt/src/main/resources/salt/pillar/top.sls
orchestrator-salt/src/main/resources/salt/salt/metadata/settings.sls

CLOUD-93783 store clustername in /opt/metadata/cluster.json

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformResources.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudAccessConfig.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudAccessConfigs.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResources.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResourcesTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformResources.java
cloud-common/src/main/resources/application.yml
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformResources.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockPlatformResources.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackPlatformResources.java
cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/platform/GetPlatformCloudAccessConfigsRequest.java
cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/platform/GetPlatformCloudAccessConfigsResult.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/GetPlatformAccessConfigsHandler.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnPlatformResources.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v1/ConnectorV1Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/AccessConfigJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/PlatformAccessConfigsResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ResourceQueryStatus.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/PlatformParameterV1Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/CloudAccessConfigsToPlatformAccessConfigsResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudParameterService.java

this pr helps to query the existing instanceprofiles from AWS

RMP-10206 Ability to set Instance Profile on AWS cluster EC2 instances

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/PlatformIpPoolsResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTestSuiteInitializer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/OpenStackCredentialCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/scaling/ScalingUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/CloudbreakV2Constants.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/ExistingSshKeySelectionTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/ImageSelectionTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/InstanceGroupV2PreparationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/IpPoolSelectionTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/OpenstackStackCreationV2Test.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/StackScalingV2Test.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/StackStartV2Test.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/StackStopV2Test.java
integration-test/src/main/resources/testsuites/v2/openstack/v2-os-stackcreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/v2/openstack/v2-os-stackcreate-startstop.yaml
integration-test/src/main/resources/testsuites/v2/openstack/v2-os-stackcreate.yaml

@afarsang or @biharitomi pls review...

CLOUD-93506 Cloudbreak-Api-v2 e2e tests

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureSetup.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorage.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java

Azure resource group and storage account does not applied the user defined tags so fixed that.

DPAA-198 Investigate why cost tagging does not work

---

cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollResourcesStateTask.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/kerberos/KerberosDetailService.java

Current solution skips kerberos related salt actions based on krb5_conf. manage_krb5_conf property. New solution based on kerberos-env. install_packages

RMP-10381 Skip kerberos related salt action based on install_packages

---

cloud-common/src/main/resources/application.yml
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

CLOUD-93929 HDF repo update, mandatory 'NiFi' instancegroup naming removal

---

README.md

Documentation of determining correct version based on git repository

CLOUD-87281 Unspecified version handling - documentation

---

integration-test/integcb/Profile_template
integration-test/it-application.yml
integration-test/src/main/java/com/sequenceiq/it/MockSuiteInitializer.java
integration-test/src/main/resources/application.yml

CLOUD-93453 put mock params into inttest's application.yml

---

integration-test/it-application.yml
integration-test/src/main/java/com/sequenceiq/it/MockSuiteInitializer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java
integration-test/src/main/resources/application.yml

RMP-10331 Fix kerberos request in cluster request

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/RDSConfigRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/ClusterV2Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/CustomDomainSettings.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/GeneralSettings.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/ImageSettings.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/PlacementSettings.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/RdsConfigs.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/StackV2Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/Tags.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/ClusterV2RequestToClusterRequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackV2RequestToStackRequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/cli/ClusterToClusterV2RequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/cli/StackToStackV2RequestConverter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/AbstractStackCreationV2Test.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/MockScalingTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/MockStackCreationV2Test.java

@zoltanzseli plz check and merge after fixing the UI

CLOUD-94880 Stack v2 api usability refactor

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/PlatformGatewaysResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/PlatformNetworksResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/PlatformSecurityGroupsResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/PlatformSshKeysResponse.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/ExistingSshKeySelectionTest.java

CLOUD-95534 fixed missing default constructor

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceDefaultNotFoundTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceDefaultTest.java
core/src/test/resources/com/sequenceiq/cloudbreak/service/image/default-base-imagecatalog.json
core/src/test/resources/com/sequenceiq/cloudbreak/service/image/default-hdf-imagecatalog.json
core/src/test/resources/com/sequenceiq/cloudbreak/service/image/default-hdp-imagecatalog.json
core/src/test/resources/com/sequenceiq/cloudbreak/service/image/no-default-imagecatalog.json
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-startstop.yaml

CLOUD-95050 Select prewarmed image if no imageid is provided in ClusterRequest

---

core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/BlueprintLoaderService.java
core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/DefaultBlueprintCache.java

@doktoric or @keyki pls review

CLOUD-94792 default blueprints will be cloned before db store

---

integration-test/src/main/java/com/sequenceiq/it/spark/MockSparkServer.java
performance-test/user-files/simulations/cloudbreak/CloudbreakSimulation.scala
performance-test/user-files/simulations/cloudbreak/ImageCatalogRequests.scala
performance-test/user-files/simulations/cloudbreak/InfoRequests.scala
performance-test/user-files/simulations/cloudbreak/StackRequests.scala
performance-test/user-files/simulations/cloudbreak/resources/create-imagecatalog-mock.json
performance-test/user-files/simulations/cloudbreak/resources/create-stack-v2-mock.json

CLOUD-95544 Update performance tests for modified v2 api

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/RecipeBase.java

CLOUD-91677 Recipe’s name minimum length is not consistent UI/CLI

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTestFactory.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UpgradeTestFactory.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackPostStrategy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/TestParameter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/priority/Priority.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/priority/PriorityMethodInterceptor.java
integration-test/src/main/resources/testsuites/clustertestset-wo-factory.yaml
integration-test/src/main/resources/testsuites/clustertestset.yaml
integration-test/src/main/resources/testsuites/upgradetestset.yaml

modifying api tests to use V2 api

CLOUD-95537 api v2 smoke cluster tests

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/v1/AlertEndpoint.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/TimeAlertValidationRequest.java
autoscale-api/src/main/java/com/sequenceiq/periscope/doc/ApiDescription.java
autoscale/build.gradle
autoscale/src/main/java/com/sequenceiq/periscope/controller/AlertController.java
autoscale/src/main/java/com/sequenceiq/periscope/utils/DateUtils.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/CronTest.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/DateUtilsTest.java

this is only the first part of the issues

CLOUD-94963 [Autoscale] Cannot create alert for day of the week

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakTest.java

api v2 tests fix

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/SecurityGroupV2RequestToSecurityGroupRequestConverter.java

CLOUD-95845 NPE while creating cluster from cb cli

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/BlueprintTests.java

@afarsang Please review
I've changed the test names based on your suggestions.

BUG-95616 fixing Blueprints test cases

---

cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackResourceConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationService.java

CLOUD-95602 in case of os provider network don't wait for network creation

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/AbstractAlertJson.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/ScalingPolicyBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/AutoscaleStackResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ConstraintTemplateBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/CredentialBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/NetworkRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/RecipeBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/SecurityGroupRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/TemplateRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/TopologyBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ImageCatalogBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/AmbariV2Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/GeneralSettings.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/PlacementSettings.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/StackV2Request.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackRequestToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackV2RequestToStackRequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/CredentialRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserProfileService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/StackRequestToStackConverterTest.java

BUG-96588 [CLI] Eliminate NPEs during cluster create
BUG-96589 [CLI] Java and Go regex validation give different results
@keyki plz check

BUG-96588 [CLI] Eliminate NPEs during cluster create

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java

BUG-96592 scaling and status update only executable if stack and cluster are valid

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/StackV2Request.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackV2RequestToStackRequestConverter.java

BUG-96566 Cannot use CLI json skeleton generated by the UI

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Log.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackPostStrategy.java

add stack request response to the report
Closes BUG-96794

BUG-96794 add verbose log message to test report

---

integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/GherkinTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Stack.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackOperation.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackPostStrategy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/log/Log.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/log/ReportListener.java

There is an issue in the ambari availability check of api e2e tests, this PR is going to fix that.
Also contains more reporting in gherkin syntax
Closes BUG-96891 fix ambari health check in api e2e tests

BUG-96891 fix ambari health check in api e2e tests

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/BlueprintTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CredentialProviderSpecTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CredentialTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RecipeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Credential.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CredentialAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/credentialtests.yaml

@afarsang please review new API E2E credential tests

BUG-95630 Introduce new credential test cases

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v1/UtilEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/VersionCheckResult.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/UtilController.java
core/src/main/java/com/sequenceiq/cloudbreak/util/ClientVersionUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/util/ClientVersionUtilTest.java

Version check infrastructure for checking cli client versions
@mhmxs plz check

BUG-96897 Unable to create clusters using dockerized cb-cli

---

.circleci/config.yml
integration-test/it-application.yml
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/BlueprintTests.java

Adding new tests to the mock integration test phase
Closes  BUG-97065

BUG-97065 tests to the mock integration phase

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/BlueprintTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CredentialProviderSpecTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CredentialTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/BlueprintAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CredentialAction.java
integration-test/src/main/java/com/sequenceiq/it/util/LongStringGeneratorUtil.java

@afarsang Introduced step descriptions and logging for new Blueprints and Credentials test cases. please review.

BUG-95616 BUG-95630 Introduce log comments and descriptions

---

core/src/main/resources/schema/app/20180222131946_BUG-96715_remove_default_2.5_blueprints.sql

BUG-96715 Remove default blueprints for hdp 2.5

---

mock/cloudbreak/api/swagger.yaml
mock/cloudbreak/controllers/V1connectors.js
mock/cloudbreak/controllers/V1credentials.js
mock/cloudbreak/controllers/V1imagecatalogs.js
mock/cloudbreak/controllers/V1imagecatalogsService.js
mock/cloudbreak/controllers/V1repositoryconfigs.js
mock/cloudbreak/controllers/V1repositoryconfigsService.js
mock/cloudbreak/controllers/V1stacks.js
mock/cloudbreak/controllers/V1templates.js
mock/cloudbreak/controllers/V1util.js
mock/cloudbreak/controllers/V1utilService.js

refreshing cloudbreak mock with the api changes including version check to the cli

BUG-96897 mock support for version check

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CredentialTests.java

Removing unnecessary credential clean up

BUG-97394 removing unnecessary credential clean up

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ImageCatalogTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RecipeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ImageCatalog.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ImageCatalogAction.java
integration-test/src/main/resources/testsuites/imagecatalogtests.yaml

BUG-96990 Add imagecatalog test cases

---

cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java

BUG-97207 Set yarn application status in case of deletion

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartStopService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/stop/StackStopActions.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java

BUG-97083 Proper handling of failed aws start/stop operations

---

mock/cloudbreak/api/swagger.yaml

Fix wrong reference in a stack operation
Closes BUG-97461

BUG-97461 fix cbmock reference

---

orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/setup-ldap.sh

DPAAS-275 Ambari prompts for custom truststore when setting up ldaps

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java
integration-test/src/main/resources/testsuites/upgradetestset.yaml

adding credential names as parameters
adding these parameters to the upgrade test set

BUG-48033 adding credential names as parameters

---

cloud-gcp/build.gradle
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpCredentialConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/context/InvalidGcpContextException.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpCredentialConnectorTest.java

fix for the bug which cause that the user has been able to create a new credential with an invalid service account id and/or project id

BUG-97296 GCP credential creation validate

---

core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RepositoryConfigsTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RepositoryConfigs.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RepositoryConfigsAction.java
integration-test/src/main/resources/testsuites/repoconfigstests.yaml

BUG-97402 Add RepoConfigsValidate test cases

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/recipes/RecipeCreationTest.java

Fix assert typo

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/PlatformVmtypesResponse.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RegionProviderSpecTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RegionTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/VmTypeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Region.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RegionAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/VmType.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/VmTypeAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/VmTypeEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java
integration-test/src/main/resources/testsuites/regiontests.yaml
integration-test/src/main/resources/testsuites/vmtypetests.yaml

@afarsang Please review new API tests for VM Types Service.

BUG-97056 Introduce VMTypes test cases and support classes

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/DiskTypeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/DiskTypes.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/DiskTypesAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/DiskTypesEntity.java
integration-test/src/main/resources/testsuites/disktypetests.yaml

BUG-97945 Introduce new test suite for Connectors V1 DiskTypes

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/DiskTypeTests.java

@afarsang based on our discussion I've changed the test class

BUG-97945 Changes for Connectors V1 DiskTypes

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/NetworksProviderSpecificTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/NetworksTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Networks.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/NetworksAction.java
integration-test/src/main/resources/testsuites/networkstests.yaml

BUG-97678 Add V1 Connectors Networks test cases

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RecommendationsTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Recommendation.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RecommendationAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RecommendationEntity.java
integration-test/src/main/resources/templates/diskResponses.json
integration-test/src/main/resources/testsuites/recommendationstests.yaml

@mhmxs or @mhalmy In the absence of @afarsang could you review these new tests for V1 Connectors Recommendations?

BUG-98151 Introduce new test suite for Connectors V1 Recommendations

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/IpPoolTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/NetworksTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/IpPool.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/IpPoolAction.java
integration-test/src/main/resources/testsuites/ippooltests.yaml

BUG-98154 Add V1 Connectors Ippools test cases

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/GatewayTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Gateway.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/GatewayAction.java
integration-test/src/main/resources/testsuites/gatewaystests.yaml

BUG-98243 Add Gateways test cases

---

integration-test/src/main/resources/testsuites/clustertestset.yaml

@topolyai5 Fixing CI issues because of credential names

Introduce custom credential names for Cluster tests

---

blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/BlueprintTextProcessor.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/nifi/HdfConfigProvider.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/nifi/HdfConfigs.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/template/BlueprintTemplateModelContextBuilder.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/template/BlueprintTemplateProcessor.java
blueprint-manager/src/main/resources/blueprints/configurations/nifi/global.handlebars
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/moduletest/BlueprintModelProvider.java
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/nifi/HdfConfigProviderTest.java
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/nifi/HdfConfigsTest.java
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/BlueprintTemplateProcessorTest.java
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/BlueprintTextProcessorTest.java
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/ConfigTemplateTest.java
blueprint-manager/src/test/resources/handlebar/configurations/nifi/global-with-hdf-full.json
blueprint-manager/src/test/resources/handlebar/configurations/nifi/global-with-hdf-nifitargets.json
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackToBlueprintPreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/InstanceGroupMetadataCollector.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ambari/InstanceGroupMetadataCollectorTest.java

@doktoric or @biharitomi pls review

BUG-98439 Set nifi proxy parameter using the public ips

---

mock/cloudbreak/api/swagger.yaml
mock/cloudbreak/controllers/V1connectorsService.js
mock/cloudbreak/controllers/V1proxyconfigs.js
mock/cloudbreak/controllers/V1proxyconfigsService.js
mock/cloudbreak/responses/connectors/networks.json
mock/cloudbreak/responses/connectors/sshkeys.json
mock/cloudbreak/responses/imagecatalogs/qa-images.json

Update the mock with proxy service

BUG-98968 mock update

---

core-api/src/test/java/com/sequenceiq/cloudbreak/api/model/v2/StackV2RequestCompatibilityTest.java
core-api/src/test/resources/api-compatibility/StackV2Request_v2.4.0.json
core-api/src/test/resources/api-compatibility/StackV2Request_v2.5.0-rc.1.json

@akanto, @schfeca75  plz check

testing stackv2 api validation with v2.4.0 json

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/BlueprintTests.java

@afarsang Please review:
1. Special characters are allowed for blueprints name (in 1 to 100 character long range)
2. Somehow the "@#$%|:&*;" blueprint name is exist in the qa-cloud DB.

BUG-95607 Updating Blueprints tests for special characters

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/LdapConfigTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RdsConfigTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/LdapConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/LdapConfigAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/LdapConfigEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/LdapTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/LdapTestEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RdsConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RdsConfigAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RdsConfigEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RdsTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RdsTestEntity.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/ldapconfigtests.yaml
integration-test/src/main/resources/testsuites/rdsconfigtests.yaml

BUG-98845 Extend E2E api tests: RDS, LDAP

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ldap/LDAPTestRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/rds/RDSTestRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/LdapController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/RdsConfigController.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ldapconfig/LdapConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RdsConfigService.java

BUG-99417 Rds and LDAP test request should work based on resource name

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/LdapConfigTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ProxyConfigTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/LdapConfigAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ProxyConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ProxyConfigAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ProxyConfigEntity.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/proxyconfigtests.yaml

BUG-99326 add proxy config e2e api tests

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RdsConfigTests.java

BUG-99529 fix rds config validation tests

---

integration-test/apidefinitions/api-2.4.json
integration-test/apidefinitions/api-2.5.json
integration-test/docker-compose_template.yml
integration-test/scripts/docker-compose.sh

API compatibility check against 2.4 GA and 2.5 TP - first version is just for info level; won't break the build, just to monitor the changes.
It runs on integration test phase, and uses swagger-diff
Closes BUG-99619

BUG-99619 introducing api compatibility check

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/LdapClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ProxyClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RdsClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Cluster.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java
integration-test/src/main/resources/testsuites/ldapclustertests.yaml
integration-test/src/main/resources/testsuites/proxyclustertests.yaml
integration-test/src/main/resources/testsuites/rdsclustertests.yaml

BUG-99615 External resources attached with cluster

---

orchestrator-salt/src/main/resources/salt/pillar/jdbc/connectors.sls
orchestrator-salt/src/main/resources/salt/salt/jdbc/connectors.sls

@keyki or @topolyai5 pls review

BUG-98856 jdbc connector fix: do nothing if connector properties are not provided

---

orchestrator-salt/src/main/resources/salt/salt/ambari/server.sls

BUG-98847 ambari vendor fix

---

blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/BlueprintTextProcessor.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpCredentialConnector.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/SharedServiceRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/ClusterV2Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackRequestToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/ClusterV2RequestToClusterRequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackV2RequestToStackRequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/AmbariDecommissioner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/StackDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/SharedServiceConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/smartsense/SmartSenseSubscriptionService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/StackRequestToStackConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/ClusterV2RequestToClusterRequestConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackV2RequestToStackRequestConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecoratorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/StackDecoratorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/sharedservice/SharedServiceConfigProviderTest.java

Shared service implementations supported with unit tests

DO NOT MERGE

---

core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackV2RequestToStackRequestConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecoratorTest.java

the changed mockito version caused some malfunction with some unit test, in this branch these tests has fixed

unit test corrections for shared service due to mockito version change

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/StackRepoDetails.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/StackType.java
cloud-common/src/main/resources/application.yml
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/AmbariStackDetailsJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ManagementPackEntry.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/StackDetailsJson.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/AmbariStackDetailsJsonToStackRepoDetailsConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/ImagesToImagesResponseJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackRepoDetailsToAmbariStackDetailsResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java

BUG-99294 mpack extension for imagecatalog endpoint

---

mock/cloudbreak/api/swagger.yaml
mock/cloudbreak/controllers/Info.js
mock/cloudbreak/controllers/InfoService.js
mock/periscope/api/swagger.yaml
mock/periscope/controllers/Health.js
mock/periscope/controllers/HealthService.js
mock/periscope/controllers/V1clustersService.js
mock/periscope/controllers/V2clustersService.js

BUG-100624 Update Cloudbreak Mock

---

mock/cloudbreak/controllers/V1imagecatalogsService.js
mock/cloudbreak/controllers/V1ldapService.js
mock/cloudbreak/controllers/V1proxyconfigsService.js
mock/cloudbreak/controllers/V1rdsconfigsService.js
mock/cloudbreak/responses/imagecatalogs/cloudbreak-default.json
mock/cloudbreak/responses/ldapconfig/default-ldap.json
mock/cloudbreak/responses/proxyconfig/default-proxy.json
mock/cloudbreak/responses/rdsconfig/default-rds.json

BUG-100624 Upgrade Cloudbreak Mock

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/NetworkClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Network.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/NetworkAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/NetworkEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Stack.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java
integration-test/src/main/resources/testsuites/clusternetworktest.yaml

@afarsang please review and merge.

BUG-99980 Introduce new AWS tests for create cluster with custom network

---

blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/moduletest/CentralBlueprintUpdaterRollingtest.java
blueprint-manager/src/test/resources/module-test/outputs/hdp26-shared-services.bp
blueprint-manager/src/test/resources/module-test/outputs/ldap-with-rds-ranger.bp
blueprint-manager/src/test/resources/module-test/outputs/oozie.bp
blueprint-manager/src/test/resources/module-test/outputs/smartsense-when-no-hst-server.bp
blueprint-manager/src/test/resources/module-test/outputs/smartsense.bp
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/AmbariClusterTemplateService.java
gradle.properties

The ambari cluster creation template was not logged if the create cluster request failed.
This commit fixes the issue.
Closes #3285

BUG-100311# Logging ambari cluster template before sending request

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/rds/RDSConfigJson.java

BUG-98852 [CLI] Implement mysql/oracle functionality into the CLI

---

blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/template/GatewayDisabledHelper.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/template/HandlebarUtils.java
blueprint-manager/src/main/resources/blueprints/configurations/hive/ldap.handlebars

BUG-100712 LLAP is configured with LDAP when GW is enabled

---

mock/cloudbreak/api/swagger.yaml
mock/cloudbreak/controllers/V1accountpreferencesService.js
mock/cloudbreak/controllers/V1imagecatalogsService.js
mock/cloudbreak/controllers/V1stacksService.js
mock/cloudbreak/controllers/V1util.js
mock/cloudbreak/controllers/V1utilService.js
mock/cloudbreak/controllers/V2stacksService.js
mock/cloudbreak/responses/accountpreferences/accountpreferences.json

BUG-100759 Update Cloudbreak Mock with latest changes

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v1/ManagementPackEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/mpack/ManagementPackBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/mpack/ManagementPackDetails.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/mpack/ManagementPackRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ManagementPackResourceValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ResourceGroup.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidManagementPack.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/mpack/ManagementPackValidator.java

BUG-99294 Mpack validation improvement

---

orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/install-mpack.sh

BUG-99294 parameter substitution in install mpack script

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CredentialAction.java

parallel credential creation fix in integrationtest

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CredentialTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java

Integration test credential creation test fix

---

integration-test/src/main/resources/testsuites/clustertestset.yaml

@afarsang please review: BUG-101213 Update NiFi blueprint name in API E2E suite files
@schfeca75 and @keyki FYI

BUG-101213 Update NiFi blueprint name in API E2E

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackDescriptor.java
core/src/main/generated/com/sequenceiq/cloudbreak/converter/mapper/StackInfoMapperImpl.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/mapper/StackInfoMapper.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackMatrixService.java

BUG-101213 extend stackmatrix with mpacks

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/LdapClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ProxyClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RdsClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RecipeClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SshService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Stack.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java
integration-test/src/main/resources/testsuites/recipeclustertests.yaml

BUG-100513 add cluster recipe tests

---

blueprint-manager/src/main/resources/hdp/service-config.json
blueprint-manager/src/test/resources/module-test/outputs/atlas-with-ldap.bp
blueprint-manager/src/test/resources/module-test/outputs/atlas-without-ldap.bp
blueprint-manager/src/test/resources/module-test/outputs/execution-type-container.bp
blueprint-manager/src/test/resources/module-test/outputs/hbase-master-in-all-host.bp
blueprint-manager/src/test/resources/module-test/outputs/hbase.bp
blueprint-manager/src/test/resources/module-test/outputs/kerberos.bp
blueprint-manager/src/test/resources/module-test/outputs/ldap-with-ranger-hadoop.bp
blueprint-manager/src/test/resources/module-test/outputs/ldap-with-rds-druid.bp
blueprint-manager/src/test/resources/module-test/outputs/ldap-with-rds-ranger.bp
blueprint-manager/src/test/resources/module-test/outputs/llap.bp
blueprint-manager/src/test/resources/module-test/outputs/one-hbase-master-one-client-in-different-host.bp
blueprint-manager/src/test/resources/module-test/outputs/oozie.bp
blueprint-manager/src/test/resources/module-test/outputs/rds-with-druid.bp
blueprint-manager/src/test/resources/module-test/outputs/rds-with-hive-metastore.bp
blueprint-manager/src/test/resources/module-test/outputs/rds-with-ranger.bp
blueprint-manager/src/test/resources/module-test/outputs/smartsense-when-no-hst-server.bp
blueprint-manager/src/test/resources/module-test/outputs/smartsense.bp
blueprint-manager/src/test/resources/module-test/outputs/zeppelin-2-5.bp
blueprint-manager/src/test/resources/module-test/outputs/zeppelin-2-6.bp

 BUG-100998 change default temp S3 directory

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/StartAmbariServicesHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/ComponentLocatorService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/ComponentLocatorServiceTest.java

BUG-101469 Remove @Transactional from long running method: ClusterHostServiceRunner.runAmbariServices

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RdsConfigService.java

BUG-101833 read cluster with lists

---

autoscale/build.gradle
autoscale/src/main/java/com/sequenceiq/periscope/controller/AlertController.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/Cluster.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/AbstractMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/MonitorUpdateRate.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/AmbariAgentHealthEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ClusterCreationEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/CronTimeEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/MetricEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingHandler.java
autoscale/src/main/java/com/sequenceiq/periscope/service/AlertService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/AmbariClientProvider.java
autoscale/src/main/java/com/sequenceiq/periscope/service/DateService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/DateTimeService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ha/LeaderElectionService.java
autoscale/src/main/java/com/sequenceiq/periscope/utils/ClusterUtils.java
autoscale/src/main/java/com/sequenceiq/periscope/utils/TimeUtil.java
autoscale/src/main/resources/schema/app/20180427090338_RMP-11205_Periscope_cluster_last_evailation.sql
autoscale/src/test/java/com/sequenceiq/periscope/service/DateServiceTest.java
autoscale/src/test/java/com/sequenceiq/periscope/service/ha/LeaderElectionServiceTest.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/CronTest.java

On case of an Periscope node crash there is a time period when triggers may run, so need to rewind the time and check all the missing triggers in all second till `now`.

RMP-11205 Back to the future

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/BootstrapParams.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/Cloud.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/SaltAction.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrap.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrapTest.java

BUG-101494 set the cloud type for the salt-bootstrap for rc-1.16

---

orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/ambari-server-init.sh
orchestrator-salt/src/main/resources/salt/salt/ambari/server.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/yum/MariaDB.repo
orchestrator-salt/src/main/resources/salt/salt/jdbc/connectors.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/postgres-install.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/conf_pgsql_listen_address.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/init_db.sh

Changes:
- fix MySQL based Ambari RDS
- remove unnecessary fany name jinja variables from the Ambari server initialization script
- refactor Postgres initialization salt states to only applied once
- configure Postgres' listen_addresses not to bind on network interface that is only reachable locally

Ambari rds

---

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl-user-facing.conf
orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl.conf
orchestrator-salt/src/main/resources/salt/salt/nginx/datalake.sls
orchestrator-salt/src/main/resources/salt/salt/nginx/init.sls
orchestrator-salt/src/main/resources/salt/salt/nginx/scripts/create-user-facing-cert.sh
orchestrator-salt/src/main/resources/salt/salt/top.sls

- separate configs for the two ssl certs (443 and 9443) for ambari
- script added to generate new cert for the user facing port (443) for ambari
Closes #BUG-101501

BUG-101501 new certificate generated for ambari on master node with public ip as host

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRequestValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateRequestValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRequestValidatorTest.java

instancegroup-hostgroup mapping is checked in request time.
Closes #BUG-101026

BUG-101026 InstaceGroup - HostGroup mapping changed in request time

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/ValidationResult.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/Validator.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRequestValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateRequestValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/ValidationResultTest.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRequestValidatorTest.java
integration-test/docker-compose_template.yml

BUG-101026 InstaceGroup - HostGroup mapping checked in request time for rc-2.6
(cherry picked from commit 0ccc891, and partly from 43201b9)
(added 81e9f62 for integration test fix)

Hostgroup instancegroup mapping check rc26

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ImageResponse.java

Please do not merge it. If there is no UI related PR for this it will break lots of image related tests. Only @tamasfoldi and @zoltanzseli can merge it.

BUG-101526 rename default json field to defaultImage

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/AmbariStackDetailsJsonToStackRepoDetailsConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCreationSetupService.java

BUG-102760 stack repo details fix

---

core-api/build.gradle
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/stack/cluster/ClusterRequest.java
core-api/src/test/java/com/sequenceiq/cloudbreak/api/model/ClusterRequestTest.java
core-api/src/test/java/com/sequenceiq/cloudbreak/externaldatabase/RdsRequestValidatorTest.java

making the cluster's ambari password more secure

BUG-100515 - more strict for ambari password

---

integration-test/Makefile

ability to save swagger definition in integration test phase

BUG-102525 saving swagger definition

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/stack/cluster/ClusterRequest.java

removed positive lookahead from the ClusterRequest's password field's regex

removed positive lookahead from password regex

---

core/src/main/resources/schema/app/20180518082538_rollback_shared_service_related_changes.sql

RMP-11224 add back the deleted columns

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java

recommendation for root volume size

RMP-11135 recommendation for root volume size

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/service/DefaultCostTaggingService.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/DefaultApplicationTag.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/service/Clock.java
cloud-common/src/test/java/com/sequenceiq/cloudbreak/common/service/DefaultCostTaggingServiceTest.java

+ new tags for all resources:
+ creation unix timestamp
+ creation human readable timestamp

BUG-103101 unix and human readable timestamp added to defaultTags

---

orchestrator-salt/src/main/resources/salt/salt/ambari/setup-sso.sls

Hopefully it fixes the api tests

fixing jinja error in ambari/setup-sso.sls

---

orchestrator-salt/src/main/resources/salt/salt/nginx/init.sls

- when knox gateway is enabled, port 443 for nginx is not configured, so ambari is available only through knox.
- when knox gateway is disabled, port 443 for nginx is configured so ambari is available through nginx.

BUG-102745 nginx for 443 is disabled when knox gateway is enabled

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/stack/cluster/gateway/GatewayToGatewayJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/cli/ClusterToAmbariV2RequestRequestConverter.java

@akanto, @biharitomi , @doktoric  plz check

BUG-103942 Showcli does not contain gateway

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackPostStrategy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/log/ReportListener.java

Add create cluster response to the test report when it is failing
Closes BUG-104104

BUG-104104 Add stack response to the test report in failing case

---

blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/views/GatewayViewTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/stack/cluster/gateway/SSOType.java
core-api/src/test/resources/api-compatibility/StackV2Request_v2.4.0.json
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/gateway/Gateway.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/util/GatewayConvertUtil.java
core/src/main/resources/schema/app/20180530105603_BUG-104115_ssotype-proxy-rename.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/cluster/gateway/ClusterRequestToGatewayConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/cluster/gateway/GatewayToGatewayJsonConverterTest.java
orchestrator-salt/src/main/resources/salt/salt/ambari/setup-sso.sls
orchestrator-salt/src/main/resources/salt/salt/gateway/config/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/init.sls

SSOType enum values renamed according to Jira ticket description

BUG-104115 SSOType enum values renamed

---

integration-test/src/main/resources/testsuites/clusterawstestset.yaml
integration-test/src/main/resources/testsuites/clusterazuretestset.yaml
integration-test/src/main/resources/testsuites/clustergcptestset.yaml
integration-test/src/main/resources/testsuites/clusteropenstacktestset.yaml

Closes BUG-104107 
Split cluster tests into more test suite for readablity

BUG-104107 split test yaml based on providers

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/cluster/gateway/GatewayJsonValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/stack/cluster/gateway/ClusterRequestToGatewayConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/stack/cluster/gateway/GatewayToGatewayJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/util/GatewayConvertUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackV2RequestToGatewayConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/cluster/gateway/GatewayJsonValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/cluster/gateway/ClusterRequestToGatewayConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/cluster/gateway/TestConfig.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/util/GatewayConvertUtilTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackV2RequestToGatewayConverterTest.java

some additional tests and validations for gateway

BUG-103932 some additional tests and validations for gateway

---

orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/OrchestratorBootstrapRunner.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

BUG-101476 errorcount can be turned off

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/ImageSettings.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ImageSettings.java
integration-test/src/main/resources/testsuites/clusterostestset.yaml

@keyki or @afarsang pls review

BUG-103753 extend e2e tests with suse and ubuntu cases

---

README.md
docs/spi.md

fixed link for additional info section

fixed link for additional info

---

blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/BlueprintPreparationObject.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/template/views/BlueprintView.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/filesystem/CloudS3View.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/filesystem/CloudWasbView.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/StorageLocationBase.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/StorageLocation.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackToBlueprintPreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/StorageLocationRequestToStorageLocationConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/StorageLocationToStorageLocationResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/S3FileSystemToCloudS3ViewConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/WasbCloudStorageParametersToCloudWasbViewConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToBlueprintPreparationObjectConverterTest.java

**For the following converters:**
- StackToBlueprintPreparationObjectConverter
- WasbCloudStorageParametersToCloudWasbViewConverter
- S3FileSystemToCloudS3ViewConverter
- StorageLocationToStorageLocationResponseConverter
- StorageLocationRequestToStorageLocationConverter

few converter unit test

---

blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/template/views/LdapView.java
blueprint-manager/src/main/resources/blueprints/basics/zeppelin/shiro_ini_content.handlebars
blueprint-manager/src/main/resources/blueprints/configurations/ranger/ldap.handlebars

BUG-104372 [LDAP] introduce userDnPattern to LDAP domain, added dn pattern to handlebars

---

blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/BlueprintTextProcessor.java
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/BlueprintTextProcessorTest.java
blueprint-manager/src/test/resources/blueprints-jackson/bp-config-properties.bp
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ExposedService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/UtilController.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/stack/cluster/ClusterToClusterResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/BlueprintPortConfigCollector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/AmbariHaComponentFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ServiceEndpointCollector.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/cluster/ClusterToClusterResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/BlueprintPortConfigCollectorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/AmbariHaComponentFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/ServiceEndpointCollectorTest.java
core/src/test/resources/com/sequenceiq/cloudbreak/core/bootstrap/service/host/test-blueprint-no-config.json
core/src/test/resources/com/sequenceiq/cloudbreak/service/ha-components.bp
core/src/test/resources/defaults/blueprints/hdp26-data-science-spark2-text.bp

BUG-104121 - HA services are not listed in knox services.

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltJobIdTracker.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltJobIdTrackerTest.java

BUG-103644 show salt jinja failure on UI + tests + minor refactor

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpAuthenticator.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpCredentialConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
cloud-gcp/src/main/resources/definitions/gcp-credential.json
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderCredentialAdapter.java
core/src/test/resources/com/sequenceiq/cloudbreak/converter/credential/gcp-credential.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/GcpCloudProvider.java

BUG-103749 Support json based GCP credentials

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/stack/cluster/gateway/GatewayJson.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/cluster/gateway/GatewayJsonValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/stack/cluster/gateway/ClusterRequestToGatewayConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/stack/cluster/gateway/GatewayTopologyJsonToExposedServicesConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/util/GatewayConvertUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecorator.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/cluster/gateway/GatewayJsonValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/cluster/gateway/ClusterRequestToGatewayConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecoratorTest.java
core/src/test/resources/com/sequenceiq/cloudbreak/service/decorator/ha-components.bp
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/AbstractStackCreationV2Test.java

Also fixed that removing HA services from exposed services JSON of topologies.

BUG-104544 - corrected gateway backward compatibility

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Group.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Subnet.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackRequestToBlueprintPreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackV2RequestToGatewayConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackRequestToBlueprintPreparationObjectConverterTest.java

**Unit tests for:**
- StackToCloudStackConverter
- StackRequestToBlueprintPreparationObjectConverter

unit tests for remaining converters

---

blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/BlueprintPreparationObject.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/BlueprintViewProvider.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/CentralBlueprintUpdater.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/smartsense/SmartSenseConfigProvider.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/template/BlueprintTemplateModelContextBuilder.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/template/BlueprintTemplateProcessor.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/template/views/GatewayView.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/template/views/LdapView.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/template/views/SmartSenseSubscriptionView.java
blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/utils/StackInfoService.java
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/CentralBlueprintUpdaterTest.java
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/hadoop/HadoopConfigurationServiceTest.java
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/moduletest/BlueprintModulTest.java
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/moduletest/BlueprintModulTestModelProvider.java
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/HandlebarTemplateTest.java
blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/utils/StackInfoServiceTest.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/gateway/Gateway.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackRequestToBlueprintPreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackToBlueprintPreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackRequestToBlueprintPreparationObjectConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToBlueprintPreparationObjectConverterTest.java

minor refacts mainly for BlueprintPreparation and ContextBuilder with some additional refact

BUG-104312 – blueprint related refacts

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/GherkinTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Kerberos.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackPostStrategy.java

e2e os tests will create kerberized clusters

---

orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/GenericResponse.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltConnector.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/PillarSave.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrap.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltUpload.java

BUG-101476 Salt error log message improvement

---

core/src/main/java/com/sequenceiq/cloudbreak/init/CloudbreakCleanupService.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/CredentialRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialMigrationService.java

BUG-104758 Add selector attribute for old gcp credentails

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/conf/AwsConfig.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/conf/AzureConfig.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/conf/GcpConfig.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/config/OpenStackConfig.java

Reverts hortonworks/cloudbreak#3553

Revert "BUG-104696 – fix for passing tag key with only space value"

---

core/src/main/resources/defaults/blueprints/hdp26-shared-services.bp

BUG-104886 Remove unnecessary hostgroups from datalake bluprint

---

core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RdsConfigService.java

BUG-104774 – rds warning now shows both name of the RDS config – instead of ID – and the related cluster's name if user tries to delete it while it's still used in a cluster

BUG-104774 – rds warning with resource name and related cluster name

---

core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialService.java
core/src/main/resources/messages/messages.properties
core/src/test/java/com/sequenceiq/cloudbreak/service/credential/CredentialServiceTest.java

BUG-104784 – Credential creation notification text should be more polite
inserted missing CloudbreakMessagesService to resolve message code and extract the related content from the messages.properties

BUG-104784 – fixed notification for CredentialService

---

core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RdsConfigService.java

the exception when the rds is going to be deleted but it is used by an active cluster now returns two different message, depending on the amount of clusters which uses it.

BUG-104774 – extended exception message for rds deletion

---

core/src/main/java/com/sequenceiq/cloudbreak/service/ldapconfig/LdapConfigService.java

related to the BUG-104769 ticket

BUG-104769 – extended delete message on ldap

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/CommonResourceType.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/ResourceType.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleService.java

BUG-104790 Stack status is set to failed in case of heat template failure during upscale

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/generator/OfflineStateGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceGroupRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/network/NetworkService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/proxy/ProxyConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/recipe/RecipeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/securitygroup/SecurityGroupService.java

The following resources have to list all the related clusters which use the it:
- ProxyConfig
- Recipe
- Network
- Blueprint
- SecurityGroup

BUG-105054 – change warning message from id to name and cluster list on resource deletion

---

cloud-common/src/main/resources/application.yml
orchestrator-salt/src/main/resources/salt/salt/ambari/agent.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/server-install.sls
orchestrator-salt/src/main/resources/salt/salt/gateway/init.sls

BUG-105073 Ignore GPG keys on Ubuntu16/Debian9

---

orchestrator-salt/src/main/resources/salt/salt/gateway/init.sls

BUG-105073 Fix jinja issue

---

core-api/src/main/java/com/sequenceiq/cloudbreak/validation/AdlsCloudStorageParametersValidator.java

BUG-105177 - removed validation for tenantID for adls file system attach since it's extracted from the credential later

BUG-105177 - removed validation for tenantID for adls file system attach

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/CredentialBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/exception/ProxyMethodInvocationException.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/BeforeAfterMessagingProxyExecutor.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/EndpointExecutionException.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/GenericProxyExecutor.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ProxyCloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ProxyHandler.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ProxyInstanceCreator.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackPostStrategy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/log/Log.java

dynamic proxy for endpoint calls

dynamic proxy for newway endpoint calls

---

core/src/main/java/com/sequenceiq/cloudbreak/service/DefaultAmbariRepoService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/DefaultAmbariRepoServiceTest.java

BUG-104541 ImageResponse fix: collect proper ostypes

---

cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/auth/OpenStackClient.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/view/KeystoneCredentialView.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/CredentialRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/type/OpenStackCredentialRequestKeys.java
core-api/src/main/java/com/sequenceiq/cloudbreak/type/OpenStackCredentialV3ScopeConstants.java
core-api/src/main/java/com/sequenceiq/cloudbreak/type/OpenStackCredentialVersionConstants.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/CredentialRequestValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidCredentialRequest.java
core-api/src/test/java/com/sequenceiq/cloudbreak/validation/CredentialRequestValidatorTest.java

BUG-75209 openstack credential validation + tests

BUG-75209 OpenStack credential validation scaffolding

---

core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java

@lacikaaa or @daszabo pls review

BUG-105926 LazyInitException fix on StackRepository.findAliveOnes method

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/generator/OfflineStateGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/CredentialRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/NetworkRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/TemplateRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/topology/TopologyService.java

This PR is related to the BUG-105054 but it's extension/addition, and the following [PR](https://github.com/hortonworks/cloudbreak/pull/3566)

BUG-105054 extended message for topology and credential delete

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/filesystem/S3CloudStorageParameters.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SharedServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Cluster.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/HiveRdsConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/LdapConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/LdapConfigAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/LdapConfigRequestDataCollector.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/MissingExpectedParameterException.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ProxyHandler.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RDSConfigRequestDataCollector.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RangerRdsConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RdsConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RdsConfigAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RdsConfigs.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackPostStrategy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/TestParameter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/HostGroupType.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/Provider.java
integration-test/src/main/resources/testsuites/datalake-cluster-aws.yaml

basic shared service integration test for aws

basic shared service integration test for aws

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SharedServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/LdapConfigRequestDataCollector.java
integration-test/src/main/resources/testsuites/datalake-cluster-aws.yaml

BUG-105464 – basic shared service integration test for aws

BUG-105464 – basic shared service integration test for aws

---

cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
web/app/static/tags/network/awsnetworkform.tag
web/app/static/tags/securitygroup/securitygroupform.tag

@zoltanzseli it should fix this EAR-8714
Could you check if any other modification on the UI should be added?

BUG-97390 Support longer resource ID-s on AWS

---

cloud-common/src/main/resources/application.yml

RMP-11667 Update Ambari to 2.6.2.2 in Cloudbreak

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java

Openstack test will not use volume

BUG-106743 volume count is 0 for openstack

---

cloud-openstack/build.gradle
integration-test/build.gradle

BUG-107162 openstack4j library update: using jersey 2.26

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/cache/common/CloudResourceRegionCache.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/cache/common/CloudResourceVmTypeCache.java
core/src/main/java/com/sequenceiq/cloudbreak/cache/ResourceDefinitionCache.java

some of our cache dont use eviction

BUG-107482 adding ttl to every cache

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRequestValidator.java

BUG-107235 – fix for inapropriate validation logic

BUG-107235 – fix for inapropriate validation logic

---

cloud-aws/src/main/resources/definitions/aws-zone-displaynames.json
cloud-aws/src/main/resources/definitions/aws-zone-vm.json
cloud-aws/src/main/resources/definitions/aws-zone.json

This change adds the missing information required for AWS GovCloud.

Add missing AWS GovCloud zone info.

---

orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/CommandExecutionResponse.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/PackageVersionResponse.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/PackageVersionsResponse.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStates.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStatesTest.java

BUG-107405 extend salt commands: pkg.version, cmd.run

---

cloud-common/src/main/resources/application.yml
core/src/main/java/com/sequenceiq/cloudbreak/reactor/ClusterSyncHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/InstanceMetadataUpdater.java

@lacikaaa or @keyki pls review

BUG-107405 Update instances' package versions during cluster sync

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/InstanceMetadataUpdater.java
core/src/main/resources/messages/messages.properties

@lacikaaa or @keyki pls review

BUG-107405 Notification about package version differences on hosts

---

integration-test/src/main/resources/testsuites/clusterawstestset.yaml
integration-test/src/main/resources/testsuites/clusterostestset.yaml
integration-test/src/main/resources/testsuites/clustertestset.yaml

Moving api test to other region where is the rds
Closes BUG-107868

BUG-107868 moving aws api tests to region with rds

---

integration-test/src/main/resources/testsuites/clusteropenstacktestset.yaml

update openstack test yaml thread count to 4
Closes 107947

BUG-107947 update openstack test yaml thread count to 4

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/EncryptedClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/TestParameter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/HostGroupType.java
integration-test/src/main/resources/testsuites/clusterawstestset.yaml

Run one/some e2e test with EBS encrypted disc(s)

BUG-106768 – Run nightly tests with encrypted disks by default

---

core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/AmbariClusterUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/recipe/UpscalePostRecipesHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/OrchestratorRecipeExecutor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/RecipeEngine.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/RecipeExecutionFailureCollector.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/RecipeExecutionFailureCollectorTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/ScalingMock.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/StackCreationMock.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

BUG-108064 fixing wrong recipe error message :
- only executing highstate for recipes when there is recipe added for the given state
- filtering the error response from salt api is corrected

BUG-108064 fixing wrong recipe error message

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRequestValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackEncryptionValidatorTest.java

BUG-107949 – API should validate encrption key before cluster creation start

BUG-107949 – API should validate encrption key before cluster creation start

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v1/OrganizationEndpoint.java

PUT method is more pragmatic for modification of the resource

BUG-108475 - org modifications are PUT

---

orchestrator-salt/src/main/resources/salt/salt/kerberos/scripts/principals.sh

- activating virtualenv before executing salt-cp command

BUG-108538 Kerberos salt state fails if salt installed in virtualenv

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v1/ImageCatalogV1Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/Notes.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ImageCatalogV1Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/StackImageFilterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/StackImageFilterServiceTest.java

BUG-107573 filter images valid for cluster upgrade

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTests.java

api e2e test support for multiple hdp version and image selection
Closes BUG-108873

BUG-108873 api e2e test support for multiple hdp version

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RecoveryTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RepairNodeStrategy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Stack.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/UnhealthyNodeStrategy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/HostGroupType.java
integration-test/src/main/resources/testsuites/clusterrecoverytestset.yaml

auto and manual recovery test without periscope
Closes BUG-107981

BUG-107981 Create recovery test for CB

---

integration-test/src/main/resources/testsuites/clusterawstestset.yaml
integration-test/src/main/resources/testsuites/clusteropenstacktestset.yaml

BUG-109137 blueprint name typo

---

.gitignore
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformResources.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/TemplateToTemplateResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/cli/TemplateToTemplateV2RequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/template/ParametersToGcpTemplateParametersConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/template/ParametersToGcpTemplateParametersConverterTest.java

Blocks: https://github.com/hortonworks/hortonworks-cloud/pull/963

BUG-108315 Show encryption info on hardware panel

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/GeneralRecipeClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/NetworkClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SshService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Stack.java
integration-test/src/main/resources/testsuites/generalrecipeclustertests.yaml

BUG-108343 – Tests for support python shebangs in recipe

BUG-108343 – Tests for support python shebangs in recipe

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/EncryptedClusterTests.java

remove duplicated code in encryption test
Closes BUG-109259

BUG-109259 Encryption test refactor

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v3/RdsConfigV3Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/RdsConfigV3Controller.java

These two additional endpoints are needed by UI

BUG-108475 RDS Configs V3 - add more V3 endpoints for UI

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CredentialTests.java

@afarsang or @doktoric pls review

RMP-10615 Change exception type in the tests in case of name duplication

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/credential/CredentialValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/CredentialRequestToCredentialConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/CredentialToCredentialResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/cli/CredentialToCredentialRequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialService.java

BUG-109461 – fix for NPE when cloudPlatform is unidentified on credential creation with curl

BUG-109461 – fix for NPE when cloudPlatform is unidentified on credential creation with curl

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/CredentialResponse.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/CredentialToCredentialResponseConverter.java

added OrganizationResourceResponse to CredentialResponse and related converter

added OrganizationResourceResponse to CredentialResponse

---

core/src/main/java/com/sequenceiq/cloudbreak/service/audit/AuditEventService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/StructuredEventRepository.java
core/src/test/java/com/sequenceiq/cloudbreak/service/audit/AuditEventServiceTest.java

BUG-109585 – Audit describe fails - Internal server error: No converter found...

BUG-109585 – Audit describe fails

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v3/ConnectorV3Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ControllerDescription.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/PlatformParameterV3Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/PlatformResourceRequestJsonToPlatformResourceRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/platform/PlatformParameterService.java

BUG-109584 – ConnectorV3Endpoint

BUG-109584 – ConnectorV3Endpoint

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/CredentialController.java

BUG-109690 fix for creating invalid credential

BUG-109690 fix for creating invalid credential

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CredentialTests.java

@mhmxs or @doktoric pls review

BUG-109690 Credential test fix

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v3/StackV3Endpoint.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/organization/Organization.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/BlueprintController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/BlueprintV3Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackV3Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/BlueprintLoaderService.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/BlueprintRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/organization/OrganizationService.java
core/src/main/resources/schema/app/20180823095801_BUG-108475_adding_constraints_to_org.sql
core/src/test/java/com/sequenceiq/cloudbreak/security/StackServiceSecurityComponentTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackServiceTest.java

BUG-109662 - default blueprints are created for every org
- and StackV3 getByNameInOrganization entries fixed
- and proper error message when org cannot be created because name is occupied
- and added stricter constraints to organization

BUG-109662 - default blueprints created for every org

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/repository/BaseRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/organization/OrganizationResourceRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/StackImageFilterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/StackImageFilterServiceTest.java
orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/init_db.sh

@mhmxs or @attilapalfi92 pls reivew

BUG-108475 JPA transaction fixes, lazy init fixes

---

autoscale/src/test/java/com/sequenceiq/periscope/modul/rejected/StackCollectorServiceModulTest.java

Fixed one of the errors.
The other one I could not reproduce.

BUG-109750 fixing unstable periscope test

---

core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserProfileService.java

BUG-109759 – unable to change default credential

BUG-109759 – unable to change default credential

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/CredentialController.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/credential/CredentialServiceTest.java

BUG-109872 – Credential on deletion should also tells which resource uses it
_and some unit test_

BUG-109872 – Credential on deletion should also tells which resource uses it

---

core/src/main/java/com/sequenceiq/cloudbreak/service/organization/OrganizationDeleteVerifierService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/organization/OrganizationDeleteVerifierServiceTest.java

BUG-109859 – grammar fix for org deletion message

BUG-109859 – grammar fix for org deletion message

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/BlueprintRequest.java
core-api/src/test/java/com/sequenceiq/cloudbreak/BlueprintRequestTest.java

BUG-109957 – Blueprint name validation is not strict enough

BUG-109957 – Blueprint name validation is not strict enough

---

core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/credential/CredentialServiceTest.java

BUG-110022 – Update resource events with the organization stuff (Credential)

BUG-110022 – Update resource events with the organization stuff (Credential)

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/BlueprintTests.java

@gregito or @afarsang pls review

BUG-109957 Negative e2e test for blueprint names with illegal characters

---

docs/common/retrieve_oauth_token.md

Added python example to oauth token retrieval doc

Added python example to oauth token retrieval doc

---

cloud-common/src/main/resources/application.yml
orchestrator-salt/src/main/resources/salt/salt/gateway/config/topology.xml.j2

BUG-110383 ambari websocket fix with knox

---

cloud-common/src/main/resources/application.yml
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java
cloud-yarn/src/test/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnectorTest.java

BUG-110392 Include the name of the owner in the Yarn applications on ycloud

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/UserProfile.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/CredentialV3Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/UserProfileRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserProfileHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserProfileService.java

- deleted old default credential field from userprofile entity (still exists in db)
- added missing notifications
- when user creates his/her first credential, that will be the default (this was an existing feature, but deleted accidentally)
- when user deletes a default credential, it will be removed from userprofile (this was an existing feature, but deleted accidentally)

BUG-110016 fix default credential creation and deletion

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleServiceTest.java

BUG-107772 – Downscale notification text error

BUG-107772 – Downscale notification text error

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/BlueprintRequest.java
core-api/src/test/java/com/sequenceiq/cloudbreak/BlueprintRequestTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/BlueprintTests.java

BUG-109957 – additional character is banned from blueprint name

BUG-109957 – additional character is banned from blueprint name

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakClusterTestConfiguration.java

api tests are terminating clusters unexpectedly
Closes BUG-110764

BUG-110764 api tests are terminating clusters

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/stack/cluster/ClusterRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/AmbariV2Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/ClusterV2RequestToClusterRequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCreationSetupService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java

BUG-109191 Deeper ambari and stack repository check during cluster creation

---

integration-test/src/main/resources/testsuites/generalrecipeclustertests.yaml

BUG-110819 – [TEST] Recipe tests should skip additional tests if stack creation fails

BUG-110819 – [TEST] Recipe tests should skip additional tests if stack creation fails

---

.circleci/config.yml
build.gradle
core/build.gradle

introduced codeclimate testcoverage

---

core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/stack/StackValidationRequestToStackValidationConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/StackValidationRequestToStackValidationConverterTest.java

Default blueprints are now populated on stack creation.

BUG-110143 Blueprint validation now creates workspace blueprints if needed

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/GeneralRecipeClusterTests.java
integration-test/src/main/resources/testsuites/generalrecipeclustertests.yaml

BUG-110819 – [TEST] Recipe tests should skip additional tests if stack creation fails – V2

BUG-110819 – [TEST] Recipe tests should skip additional tests if stack creation fails – V2

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakClusterTestConfiguration.java

@keyki or @afarsang pls review

BUG-111030 Handle forbidden exception during e2e test cleanup

---

integration-test/README.md
integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java

Added quick-start guide for integration tests. Did minor clarifications on the guide itself.

Integration test README.me quickstart added

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/RecipeEngine.java

BUG-111190 fix checkstyle

---

core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCreationSetupService.java

BUG-111269 enable-gpl-repo flag not working

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AzureAbfsClusterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Stack.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureAbfsResourceHelper.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureCloudProvider.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/clustertest-azure-abfs.yaml

BUG-111162 Create E2E API tests for Abfs

---

core-api/src/main/java/com/sequenceiq/cloudbreak/validation/RDSConfigJsonValidator.java
core-api/src/test/java/com/sequenceiq/cloudbreak/validation/RDSConfigJsonValidatorTest.java

BUG-112054 Cloudbreak JDBC connection string should allow get parameters

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RegionProviderSpecTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RegionTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/Retry.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Region.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/v3/RegionV3Action.java
integration-test/src/main/resources/testsuites/regiontests.yaml

retry utility for test purposes. first test for regions

retry utility for test purposes

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java

@mhalmy please review then merge if it is OK for you.

BUG-111268 Modify Field OpenStack Credentials

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/GeneralRecipeClusterTests.java

@mhalmy or @gregito please review and merge if it is fine for you.

BUG-111268 Change defaultPrivateKeyFile reference in Recipe Tests

---

integration-test/src/main/resources/testsuites/clustertest-azure-abfs.yaml

BUG-112429 Fix typo in AdlsGen2 test

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureAdlsGen2ResourceHelper.java

BUG-112523 Not setting locations in AdlsGen2 test

---

orchestrator-salt/src/main/resources/salt/salt/gateway/init.sls
orchestrator-salt/src/main/resources/salt/salt/gateway/scripts/generate-repo-for-os-from-vdf.sh.j2

wget caused Salt timeouts since it's default value is 900 seconds.

EAR-9343 vdf xml now can be fetched through proxy

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/stack/StackViewResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/view/StackApiView.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/stack/StackApiViewToStackViewResponseConverter.java

BUG-112250 extend stacks with environment in the list API call

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RecipeTests.java

How is this test running green?

change the recipe url to be a valid one

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v3/StackV3Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/annotations/MutuallyExclusiveNotNull.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/stack/cluster/ClusterRepairNodesRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/stack/cluster/ClusterRepairRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ResourceRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java

Switch manual repair logic based on request, if it was supplied with
host groups or node IDs.
Add necessary unit tests.

BUG-113190 Add node Id repair logic

---

autoscale/src/test/java/com/sequenceiq/periscope/modul/rejected/AmbariAgentHealthMonitorModulTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureSubnetValidator.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ImageCatalogTests.java

BUG-113200 Remove subnet validation on existing azure subnets

---

core/src/main/java/com/sequenceiq/cloudbreak/util/ConverterUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/util/ConverterUtilTest.java

There was a bug in Stream creation from Iterable.
Covering with unit tests.

BUG-113348 Cluster was not stopping completely

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/CredentialBase.java

BUG-113779 Remove credential sensitive information from log

---

cloud-common/src/main/resources/application.yml

@doktoric or @afarsang pls review

BUG-114708: Add hdp 3.0 blueprints as internals

---

cloud-aws/src/main/resources/definitions/aws-vm-recommendation.json

BUG-114819 Aws recommendation fix: m5.xlarge with MAGNETIC discs

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ImageCatalogTests.java

Put back the imagecatalog cleanUp fix, which was removed accidentally

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Environment.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/EnvironmentAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/EnvironmentEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentTest.java

BUG-114654 API Mock tests for Delete Environment

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SecurityRulesTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/assertion/MockVerification.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/KerberosTest.java

- newway mock integration tests broke silently. This fixes the already broken, unstable testcases.
- Next PR will contain the Circle reporting fix.

Fix broken mock integration tests

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackRequestToTemplatePreparationObjectConverter.java

BUG-115127 get credential from environment if it is given in request

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Environment.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentTest.java

BUG-114648 API Mock tests for Attach/Detach Resources to Environment

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilder.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/ResourceToCloudResourceConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/AmbariDecommissioner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MountDisks.java
core/src/main/java/com/sequenceiq/cloudbreak/util/StackUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariDecommissionerTest.java

Removed provider specific code from provider independent areas, and refactored json to domain class conversion code from multiple places to a single method.

BUG-115357 Removed provider specific code from provider independent areas

---

cloud-common/src/main/resources/application.yml
core-api/src/main/java/com/sequenceiq/cloudbreak/authorization/WorkspaceResource.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/DatalakeResources.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/ServiceDescriptor.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/ServiceDescriptorDefinition.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackRequestToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/AmbariClusterCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/cluster/DatalakeResourcesRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/cluster/ServiceDescriptorRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/ServiceDescriptorDefinitionProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/SharedServiceConfigProvider.java
core/src/main/resources/schema/app/20181205130345_datalake_resources_related_new_entities.sql

@keyki pls review and merge it!

BUG-115613 Datalake service discovery refactor

---

cloud-cumulus-yarn/src/main/resources/definitions/cumulus-yarn-credential.json
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClientProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialPrerequisiteService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/ServiceDescriptorDefinitionProvider.java
gradle.properties
template-manager-blueprint/src/test/resources/module-test/outputs/smartsense-when-no-hst-server.bp
template-manager-blueprint/src/test/resources/module-test/outputs/smartsense.bp

RMP-12943 Cumulus credential modifcation: extend with ambari endpoint

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/GeneralRecipeClusterTests.java

fix e2e recipe test because hdfs home recipe is removed
Closes BUG-115955

BUG-115955 recipe test fix

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v3/EnvironmentV3Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/environment/request/RegisterDatalakeRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/environment/response/DatalakeResourcesResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/environment/response/DetailedEnvironmentResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/environment/response/SimpleEnvironmentResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/environment/Environment.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/DatalakeResources.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/view/EnvironmentView.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EnvironmentV3Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/environment/EnvironmentToDetailedEnvironmentResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/environment/EnvironmentViewToSimpleEnvironmentResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/environment/EnvironmentService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeConfigProvider.java
core/src/main/resources/schema/app/20181212130821_RMP-12943_Datalake_API_related_DB_changes.sql
core/src/test/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeConfigProviderTest.java

RMP-12943 External datalake registration

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/environment/request/RegisterDatalakeRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/environment/EnvironmentService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeConfigProvider.java

RMP-12943 Extend RegisterDatalakeRequest with ranger admin password

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/AbstractCloudbreakEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Credential.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Environment.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/LdapConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ProxyConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RdsConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentClusterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentTest.java
integration-test/src/main/resources/testsuites/v2/mock/clustermocktestset.yaml

Please review it.
Test cases are described here:
https://hortonworks.jira.com/browse/BUG-114651

BUG-114651 API Mock tests for Create Cluster in Environment

---

cloud-cumulus-yarn/src/main/resources/definitions/cumulus-yarn-credential.json

RMP-12943 cumulus credential yarn endpoint set to optional

---

core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeConfigProvider.java

RMP-12943 Fix datalakeresources.save exception

---

template-manager-blueprint/src/main/resources/definitions/cloud-storage-location-specification.json

Initial location. Will be finalized as part of https://hortonworks.jira.com/browse/BUG-114429.

RMP-12457 Add cloud location for LogFeeder

---

core/src/main/java/com/sequenceiq/cloudbreak/service/environment/EnvironmentService.java

RMP-12943 store ambari fqdn in datalakeresources.ambariFqdn field instead of the ambari url

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/KerberosConfigToKerberosResponseConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/KerberosConfigToKerberosResponseConverterTest.java

BUG-116100 – Kerberos response doesn't contain verifyKdcTrust field value properly

BUG-116100 – Kerberos response doesn't contains verifyKdcTrust field value properly

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Environment.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/EnvironmentEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentClusterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentTest.java

BUG-115557 API Mock tests for Environment Credential change

---

core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/IntegrationTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTestSuiteInitializer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RecoveryTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ProxyCloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/UnhealthyNodeStrategy.java

Reverts hortonworks/cloudbreak#4350
@attilapalfi92 Reverted, master build failed because of this commit:
https://circleci.com/gh/hortonworks/cloudbreak/46133

Revert "BUG-115951 using identity token for an autoscale endpoint in manual recovery test"

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Kerberos.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AwsKerberos.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/v3/KerberosV3Action.java
integration-test/src/main/resources/testsuites/clusterawstestset.yaml
integration-test/src/main/resources/testsuites/clusteropenstacktestset.yaml

add kerberos in order to test hdf
Closes BUG-115954

BUG-115954 HDF tests

---

core-api/src/main/java/com/sequenceiq/cloudbreak/validation/externaldatabase/SupportedDatabaseProvider.java

BUG-116460 Hive DAS is missing from the supported external db

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/util/JsonUtil.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/audit/AuditEvent.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/audit/StructuredEventResponse.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/kafka/KafkaStructuredEventHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/kafka/KafkaStructuredEventHandlerTest.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/rest/RestCallDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/rest/RestRequestDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/rest/RestResponseDetails.java

- original implementation was causing errors multiple places
- new sanitization is localized to the KafkaEventHandler class, where should happen sanitization

RMP-12945 Removing @Jsonfilter annotation as it was to fragile

---

cloud-common/src/main/resources/application.yml
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/environment/request/RegisterDatalakeRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/environment/response/DetailedEnvironmentResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/environment/response/EnvironmentBaseResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/environment/Environment.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/DatalakeResources.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/ServiceDescriptor.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/view/EnvironmentView.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/environment/ClusterCreationEnvironmentValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/environment/EnvironmentToDetailedEnvironmentResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/environment/EnvironmentViewToSimpleEnvironmentResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/cluster/DatalakeResourcesRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/datalake/DatalakeResourcesService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/environment/EnvironmentService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/SharedServiceConfigProvider.java
core/src/main/resources/schema/app/20190106224300_multiple_datalakeresources_per_environment.sql
core/src/test/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeConfigProviderTest.java
gradle.properties

@lacikaaa or @keyki pls review

BUG-116111 Register datalake validation improvement

---

orchestrator-salt/src/main/resources/salt/salt/kerberos/config/krb5.conf
orchestrator-salt/src/main/resources/salt/salt/kerberos/config/krb5.conf-existing

BUG-116283 - parse multi-host kdc

BUG-116283 - parse multi-host kdc

---

cloud-common/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/hdf33-flow-management.bp
core/src/main/resources/defaults/blueprints/hdf33-messaging-kafka-registry.bp
core/src/main/resources/defaults/blueprints/hdf33-messaging-kafka.bp
core/src/main/resources/defaults/blueprints/hdp31-data-science-spark2.bp
core/src/main/resources/defaults/blueprints/hdp31-edw-analytics.bp
core/src/main/resources/defaults/blueprints/hdp31-shared-services.bp
orchestrator-salt/src/main/resources/salt/salt/gateway/init.sls

- added package repositories
- added blueprints for HDF and HDP
- fix missing directory for knox gateway-site.xml

RMP-12142 Upgrade to Ambari 2.7.3, HDP 3.1 and HDF 3.3.1

---

integration-test/src/main/resources/testsuites/clusterawstestset.yaml

test yaml was messed up
Closes 116721

BUG-116721 invalid test yaml

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/credentials/CredentialV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/credentials/filter/AuthCodeGrantFlowFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/CredentialV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialService.java
core/src/main/java/com/sequenceiq/cloudbreak/util/ConverterUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Credential.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CredentialEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/v4/CredentialV4Action.java

code cleanup vol. 2

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTests.java

remove ambariversion selection in order ot match with cb logic
Closes 116801

BUG-116801 wrong image selected for base image tests

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/credentials/CredentialToCredentialV4RequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/credentials/CredentialToCredentialV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/credentials/CredentialV4RequestToCredentialConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/credentials/MapToAwsCredentialV4ParametersConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/credentials/MapToAzureCredentialV4ParametersConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/credentials/MapToCumulusYarnCredentialV4ParametersConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/credentials/MapToGcpCredentialV4ParametersConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/credentials/MapToMockCredentialV4ParametersConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/credentials/MapToOpenstackCredentialV4ParametersConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/credentials/MapToYarnCredentialV4ParametersConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/CredentialRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialParameterSetterUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/CredentialV4RequestToCredentialConverterTest.java

renames and repository method deletion

renames and repository method deletion

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/responses/GeneralSetV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/user/UserV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/user/responses/UserV4Responses.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakClient.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakIdentityClient.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ControllerDescription.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/Notes.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UserV4Controller.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakTest.java

BUG-116392 – User endpoint has returned as V4

BUG-116392 – User endpoint has returned as V4

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/UtilV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ControllerDescription.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java

Cleaning up Operation- and ControllerDescriptions

Cleaning up Operation- and ControllerDescriptions

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/user/UserV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/user/responses/UserEvictV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/userprofile/UserProfileV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/userprofile/responses/UserProfileV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/UtilV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/responses/StackMatrixV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UserProfileV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UserV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/userprofiles/UserProfileToUserProfileV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/userprofiles/UserToUserEvictV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/DefaultAmbariRepoService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackMatrixService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserProfileService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserService.java
core/src/main/resources/schema/app/20190116142923_BUG-116392_removing_credential_and_imagecatalog_from_userprofile.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/userprofiles/UserProfileToUserProfileV4ResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/ClusterCreationSetupServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/DefaultAmbariRepoServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/StackMatrixServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakTest.java

userprofile-refactor

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakClusterTestConfiguration.java

Test cleanup breaks upgrade tests therefore cleanup is optional now
Closes 116900

BUG-116900 tests cleanup breaks upgrade tests

---

core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/StructuredEventFilterTest.java

fix checkstyle problem from merge

---

cloud-gcp/build.gradle
core/build.gradle

- gradle now runs the junit5 units tests

Added useJUnitPlatform for junit5 test so gradle can detect them

---

cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilderTest.java

- due to enabling test with gradle this test was failing

Fix failing Junit5 test

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/mappable/CloudPlatform.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/mappable/Mappable.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/mappable/ParameterMapToClassConverterUtil.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/mappable/ProviderParameterCalculator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/credentials/CredentialV4Base.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/credentials/parameters/CredentialV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/credentials/parameters/aws/AwsCredentialV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/credentials/parameters/azure/AppBased.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/credentials/parameters/azure/AzureCredentialV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/credentials/parameters/azure/RoleBased.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/credentials/parameters/azure/RoleType.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/credentials/parameters/gcp/GcpCredentialV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/InstanceTemplateV4Base.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/AwsNetworkParametersV4.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/GeneralSettingsValidator.java

fix for mainly azure cred params

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AzureAdlsGen2ClusterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureCloudProvider.java
integration-test/src/main/resources/testsuites/clustertest-azure-abfs.yaml

removing hard coded reference for hdp version
Closes 117010

BUG-117010 azure adlsgen2 test fix

---

cloud-gcp/build.gradle
core/build.gradle
core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/StackDecoratorTest.java

Added JUnit vintage engine dependency and included the engine to the test goal to run JUnit 4 tests along with JUnit 5 tests.
Fixed StackDecorator unit tests.

BUG-117154 Unit test goal includes both JUnit 4 and 5 tests

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/mappable/CloudPlatform.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/mappable/Mappable.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/connector/ConnectorV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/AwsNetworkV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/GcpNetworkV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/MockNetworkV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/OpenStackNetworkV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/storage/WasbCloudStorageV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/StackV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/authentication/StackAuthenticationV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/StackV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/authentication/StackAuthenticationV4Response.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackToStackV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cli/StackAuthenticationToStackAuthenticationV4RequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cli/StackToStackV4RequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/stackauthentication/StackAuthenticationToStackAuthenticationV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/stackauthentication/StackAuthenticationV4RequestToStackAuthenticationConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/StackToStackResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/StackV4RequestToStackConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackV4RequestToStackConverterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/StackCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/entity/StackAuthenticationEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/entity/StackV4EntityBase.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/AbstractStackCreationV2Test.java

Contents:
* CheckStyle bugs in `core-api`
* Dependent files in `core` and `integration-test`

Fix core-api CS (+ deps in core and integration-test)

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/instancegroup/AzureInstanceGroupV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/instancegroup/GcpInstanceGroupV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/AwsNetworkV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/AzureNetworkV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/GcpNetworkV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/MockNetworkV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/OpenStackNetworkV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/stack/AzureStackV4Parameters.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackV4RequestValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackTagsToTagsV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/gateway/topology/GatewayTopologyToGatewayTopologyV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/environment/StackToEnvironmentSettingsV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/instancegroup/securitygroup/SecurityGroupToSecurityGroupResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecorator.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackAwsEncryptionValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackV4RequestValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/SecurityGroupToSecurityGroupResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/TemplateToInstanceTemplateV4ResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackTagsToTagsV4ResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/gateway/topology/GatewayTopologyToGatewayTopologyV4ResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/environment/StackToEnvironmentSettingsV4ResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/StackDecoratorTest.java

Contents:
* CheckStyle error fixes: `core`, `core-api`
* SpotBugs error fixes: `core`
* Fix unused variables / missing assignments or returns (all in `core`): `GatewayTopologyToGatewayTopologyV4ResponseConverter`, `StackToEnvironmentSettingsV4ResponseConverter`, `StackTagsToTagsV4ResponseConverter`
* New UT (all in `core`): `GatewayTopologyToGatewayTopologyV4ResponseConverterTest`, `StackToEnvironmentSettingsV4ResponseConverterTest`, `StackTagsToTagsV4ResponseConverterTest`

Fix CS in core & core-api; SB in core; some converters in core; add UT to core

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/ResourceHelper.java
template-manager-blueprint/src/main/resources/definitions/cloud-storage-location-specification.json
template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/filesystem/query/FileSystemConfigQueryServiceTest.java

BUG-116913 fix storage location parameters

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/repair/ChangePrimaryGatewayService.java

BUG-116914 Fix ambariserver flag after primary gateway recovery

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ambari/AmbariRepoDetailsToAmbariRepositoryV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ambari/AmbariRepoToAmbariRepositoryV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ambari/AmbariRepositoryV4ResponseToAmbariRepoConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/ClusterV4RequestToClusterConverterTest.java

converter type fix

---

integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-existing-legacy-network.yaml

BUG-117513 Invalid test yaml

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/StackViewV4Responses.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/Environment.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/EnvironmentAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/EnvironmentEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/assertion/CheckEnvironmentCredential.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentTest.java

BUG-117327 Environment tests

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/events/responses/CloudbreakEventBaseV4.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/events/responses/CloudbreakEventV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/UtilV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/notification/HttpNotificationSender.java
core/src/main/java/com/sequenceiq/cloudbreak/service/notification/NotificationSender.java

New V4 utils endpoint to validate notification system/chain

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/mpacks/ManagementPackComponentToManagementPackDetailsV4ResponseConverter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/entity/InstanceGroupEntity.java

CB-106 - Update Kerberos v4 related integration tests

CB-106 - Update kerberos v4 related integration tests

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackToStatusConverter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/AbstractCloudbreakEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/StackEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/assertion/AssertStatusReasonMessage.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/entity/CloudbreakEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/AmbariSetupTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/ClusterStopTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/ClusterTemplateTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentClusterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/KerberosTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/RecipeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/RecoveryItTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/SharedServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/StackCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/TerminationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/UpscaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/WorkspaceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/wait/WaitUtilForMultipleStatuses.java

WaitUtil.await() fix in integration-test

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/RecipeTest.java

CB-308 – Update RecipeTest

---

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/AutoscaleGlobalRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/AutoscaleStackResourceRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4CredentialResourceEventRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4EventRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ExistingResourceEventRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ExistingResourceIdRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ExistingResourceRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4GlobalEventRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4GlobalRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4WorkspaceEventRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4WorkspaceNameRestUrlParser.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/RestUrlParserTest.java

Squashed commits:
Enforce parser impl naming convention; enable testing of GET requests
Assert resource type expected value; unify some event parsers
Assert resource event expected value
CheckStyle fix

CB-299 Fix REST URL parsers

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ClusterToClusterV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecorator.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/cluster/ClusterToClusterV4ResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecoratorTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/AbstractCloudbreakEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/BlueprintEntity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/SharedServiceTest.java

SharedServiceTest fixes

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/views/ClusterViewV4Response.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/view/ClusterApiViewToClusterViewV4ResponseConverter.java

CB-355 – Add kerberos name to ClusterViewV4Response

CB-355 – Add kerberos name to ClusterViewV4Response

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackToStackV4ResponseConverter.java

CB-356 – Add recipes to Stackv4Response

CB-356 – Add recipes to Stackv4Response

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/mappable/ProviderParametersBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/StackV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/StackViewV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/environment/EnvironmentSettingsV4Response.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/view/StackApiViewToStackViewV4ResponseConverter.java

CB-357 – Inconsistent environment on stack responses

CB-357 – Inconsistent environment on stack responses

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentClusterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentDatalakeClusterTest.java

BUG-114652 API Mock tests for create datalake in environment

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/mappable/Mappable.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/StackV4Request.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/mpack/ManagementPackValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackV4RequestValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ambari/StackRepositoryV4RequestToStackRepoDetailsConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/instancegroup/template/InstanceTemplateV4RequestToTemplateConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/StackDecorator.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackAwsEncryptionValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackV4RequestValidatorTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentClusterTest.java

CB-404 – Yarn based cluster request throws null pointer because no placement defined

CB-404 – Yarn based cluster request throws null pointer because no placement defined

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/cluster/ClusterV4Request.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cli/ClusterToClusterV4RequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ClusterV4RequestToClusterConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cli/ClusterToClusterV4RequestConverterTest.java
template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/GeneralClusterConfigsProvider.java

CB-475 – Invalid Executor type: CONTAINER

CB-475 – Invalid Executor type: CONTAINER

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/assertion/MockVerification.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/AbstractClouderaManagerTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/AmbariSetupTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/BlueprintTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/ClusterStopTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/ClusterTemplateTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/DatabaseTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentClusterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentDatalakeClusterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/EnvironmentTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/KerberizedScaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/KerberizedStackCreation.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/KerberosTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/MaintenanceModeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/ProxyConfigTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/RecipeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/RecoveryItTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/SharedServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/StackCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/TerminationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/UpscaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/WorkspaceTest.java
integration-test/src/main/resources/testsuites/v2/mock/all-in-mock-package.yaml

add back integration tests, and failing one's are fixed.
Closes nothing

CB-424 give back all integration test

---

datalake/build.gradle
datalake/src/main/java/com/sequenceiq/datalake/configuration/DatabaseConfig.java
datalake/src/main/java/com/sequenceiq/datalake/util/DatabaseUtil.java

cloud-common imposed some security constraints on the actuator endpoints, effectively blocking them.

CB-3 Removed cloud-common dependency from Datalake

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/OrchestratorRecipeExecutor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/RecipeExecutionFailureCollector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/RecipeExecutionFailureCollectorTest.java

- Using regular expression for parsing Salt message
- directly fetch InstanceMetadata for Clusters

BUG-117764 cleanup of salt recipe error parsing

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/mock/CredentialTest.java

CB-459 - Credential v4 related integration test minor refactor

CB-459 - Credential v4 related integration test minor refactor

---

core/src/main/java/com/sequenceiq/cloudbreak/service/ServiceEndpointCollector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/clusterdefinition/ClusterDefinitionTextProcessorFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/service/clusterdefinition/ClusterDefinitionTextProcessorUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java
core/src/test/java/com/sequenceiq/cloudbreak/service/ServiceEndpointCollectorTest.java
template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/clusterdefinition/AmbariBlueprintProcessorFactory.java
template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/clusterdefinition/template/AmbariBlueprintTextProcessorTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/processor/AmbariBlueprintTextProcessor.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/processor/ClusterDefinitionTextProcessor.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/processor/ClusterManagerType.java

CB-508 Host group - instance type recommendation for CM

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/action/imagecatalog/ImageCatalogGetImagesByNameAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/mock/ImageCatalogMockServerSetup.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/mock/ImageCatalogTest.java
integration-test/src/main/java/com/sequenceiq/it/spark/ITResponse.java
integration-test/src/main/resources/mockresponse/imagecatalog/catalog-with-prewarmed.json
integration-test/src/main/resources/mockresponse/imagecatalog/catalog.json

An issue was discovered during the new test implementations and that test could be enabled again if we will have finished the fix.

CB-365 new ImageCatalog tests for get images for an existing stack

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/environment/EnvironmentViewToEnvironmentSettingsV4ResponseConverter.java

CB-656 – Stack v4 missing fields

CB-656 – Stack v4 missing fields

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/RandomNameCreator.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/parameter/CommonCloudParameters.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/provider/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/wait/WaitUtilForMultipleStatuses.java
integration-test/src/main/resources/application.yml

CB-535 default parameters' fixes

---

cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderTest.java

CB-618 – Unit test for root volume on AWS

CB-618 – Unit test for root volume on AWS

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/parameter/AwsParameters.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/parameter/AzureParameters.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/parameter/YarnParameters.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/provider/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/provider/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/provider/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/provider/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/provider/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/provider/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/provider/YarnCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/entity/InstanceTemplateV4Entity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/entity/NetworkV2Entity.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/entity/StackV4EntityBase.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/smoke/YarnSmokeTest.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/smoke/yarn-smoke-tests.yaml

@attilapalfi92 please review! If it is Ok for you, please merge.
This is the first part of the Yarn E2E Smoke Testing sub-project.

CB-584 Create minimal test run that is part of deployment pipeline

---

cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnectorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilderTest.java

CB-617 – Unit test for root volume on Azure

CB-617 – Unit test for root volume on Azure

---

cluster-ambari/src/main/java/com/sequenceiq/cloudbreak/ambari/AmbariClusterSecurityService.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterSecurityService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/ldap/LdapSSOConfigurationHandler.java
orchestrator-salt/src/main/resources/salt/salt/recipes/post-cluster-install.sls

CB-348 LDAP/AD support for CM

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/ClouderaManagerClientProvider.java

CB-772 Multiple CM-ApiClient have to be used for the clusters instead of the default one

---

orchestrator-salt/src/main/resources/salt/salt/recipes/post-cluster-install.sls

CB-348 cm restart fix

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/ClouderaManagerClientFactory.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapServiceTest.java

CB-348 Avoid package scope methods just because of unittests

---

cloud-common/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/cdh6-data-science.bp
core/src/main/resources/schema/app/20190322104752_CB-99_CDH_clusterdefinition_name_fix.sql
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/volume/AbstractVolumeConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/volume/YarnVolumeConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/volume/YarnVolumeConfigProviderTest.java

CB-99 Multiple volume configs in cm clusterdefiniton

---

orchestrator-salt/src/main/resources/salt/pillar/top.sls
orchestrator-salt/src/main/resources/salt/salt/recipes/post-cluster-install.sls

CB-348 cmserver restart fix

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/generator/OfflineStateGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/RdsConfigRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/workspace/WorkspaceResourceRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/AbstractWorkspaceAwareResourceService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/workspace/WorkspaceAwareResourceService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/StructuredEventRepository.java
core/src/test/java/com/sequenceiq/cloudbreak/service/AbstractWorkspaceAwareResourceServiceTest.java

NotFoundExceptions are reported for all missing resources as opposed to
the first resource that was not found.

CB-751. Add NotFoundExceptions for multiple missing resources.

---

.circleci/config.yml

Ignore master builds on CircleCI

---

core/src/main/resources/defaults/blueprints/cdh6-shared-services.bp

CB-99 CM datalake cluster definition uses multiple volumes

---

.circleci/config.yml
README.md
autoscale/build.gradle
autoscale/src/main/java/com/sequenceiq/periscope/service/MetricService.java
build.gradle
cloud-common/build.gradle
cloud-common/src/main/java/com/sequenceiq/cloudbreak/cache/common/AbstractCacheDefinition.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/AbstractComponentTest.java
config/spotbugs/excludeFilter.xml
core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/PackageVersionChecker.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/metrics/MetricService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/credential/RsaPublicKeyValidatorTest.java
docker-autoscale/Dockerfile
docker-cloudbreak/Dockerfile
gradle.properties
gradle/wrapper/gradle-wrapper.properties
integration-test/build.gradle
integration-test/docker-compose_template.yml
integration-test/scripts/create-image.sh
integration-test/scripts/docker-build.sh
integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/priority/PriorityMethodInterceptor.java
integration-test/test-image/Dockerfile

Java 11 is now supported in Cloudbreak. This additionally modifies
several docker images to user openjdk 11 instead of openjdk 10.

CB-25. Java 11 support.

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java

CB-836 – SHOW CLI COMMAND stopped working

CB-836 – SHOW CLI COMMAND stopped working

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/dto/InstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/e2e/gcp/GcpEncryptionTests.java

gcp prewarm image datascience with disc encryption
Closes CB-555

CB-555 gcp prewarm image datascience with disc encryption

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResources.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/StopRestrictionReason.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
core-model/src/test/java/com/sequenceiq/cloudbreak/domain/StackTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/connectors/CloudNetworksToPlatformNetworksV4ResponseConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterHostServiceTypeTest.java

Do not merge pls until the UI merged

CB-527 Add name to VPC, Subnet dropdown

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/assertion/storage/azure/AdlsGen2TestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/azure/AzureParameters.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/context/Description.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/e2e/AbstractE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/e2e/aws/AwsBaseImageTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/e2e/azure/AzureAdlsGen2Tests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/util/storagelocation/AzureTestStorageLocation.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/util/storagelocation/StorageComponent.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/util/storagelocation/TestStorageLocation.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/wait/WaitUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/wait/WaitUtilForMultipleStatuses.java

B-554 – azure cluster test with adlsgen2

CB-554 – azure cluster test with adlsgen2

---

cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderTest.java

CloudFormationTemplateBuilderTest now covers inclusion of Spot price
in templates. The test was also slightly refactored.

CB-469 Add unit test for Spot instance in CF template

---

core/scripts/security/enable_tls_ambari.sh

Added recipe to enable TLS on Ambari

RMP-10590 - Cloudbreak support with SSL enabled Ambari

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/json/EncryptedJsonToString.java
core/src/main/java/com/sequenceiq/cloudbreak/init/CloudbreakCleanupService.java

Log if columns could not be decrypted and shutdown if migration could not performed without errors.

Failed decryption log messages

---

cloud-common/build.gradle
cloud-common/src/main/java/com/sequenceiq/cloudbreak/util/FixedSizePreloadCache.java
cloud-common/src/test/java/com/sequenceiq/cloudbreak/util/FixedSizePreloadCacheTest.java

- master build was failing on jenkins occasionally, but always this test. Probably related to threading, I rather removed cause I found no way to make it deterministic

CB-706 unit test is unstable

---

core/src/main/java/com/sequenceiq/cloudbreak/init/CloudbreakCleanupService.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/cluster/ClusterRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/status/ClusterStatusUpdater.java
core/src/main/java/com/sequenceiq/cloudbreak/service/environment/EnvironmentService.java

This commit will help stuck environment start. It may not fix the cluster state.

CB-1132 Cluster stuck in WAIT_FOR_SYNC after environment is archived

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapServiceTest.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/ldap/ldap.settings
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/settings.sls
orchestrator-salt/src/main/resources/salt/salt/recipes/post-cluster-install.sls

CB-348 CM Ldap configuration without cm-server restart

---

core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/AbstractWorkspaceAwareResourceServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/credential/CredentialServiceTest.java

Multiple credentials can now be deleted properly.

CB-1167. Fix deletion of multiple credentials.

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClientTest.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/cache/common/UmsAccountCache.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/model/user/CloudbreakUser.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/service/token/CachedRemoteTokenService.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/service/TransactionService.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/service/security/AuthUserService.java
cloud-common/src/test/java/com/sequenceiq/cloudbreak/common/service/DefaultCostTaggingServiceTest.java
cloud-common/src/test/java/com/sequenceiq/cloudbreak/common/service/token/CachedRemoteTokenServiceTest.java
cluster-ambari/src/test/java/com/sequenceiq/cloudbreak/ambari/TestUtil.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapServiceTest.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/workspace/User.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/CloudbreakRestRequestThreadLocalService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/StructuredEventFilter.java
core/src/main/resources/schema/app/20190411012200_CB-783_add_crn_to_users.sql
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateActionsTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/clusterdefinition/ClusterDefinitionLoaderServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/environment/EnvironmentServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/StackImageFilterServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/kerberos/KerberosServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/user/UserProfileHandlerTest.java
orchestrator-salt/src/main/resources/salt/pillar/top.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/license.txt

Cloudera Manager licenses can be retrieved from UMS and applied to
Cloudera Manager during bootstrapping.

CB-783. License Cloudera Manager using UMS.

---

Makefile
docker-redbeams/Dockerfile
docker-redbeams/Makefile
docker-redbeams/bootstrap/start_redbeams_app.sh
docker-redbeams/bootstrap/wait_for_redbeams_api.sh
docker-redbeams/deploy.sh

The files for creating a Docker image for the new Redbeams service are
in place.

CB-1095 Add docker-redbeams

---

cluster-cm/build.gradle
integration-test/build.gradle
template-manager-cmtemplate/build.gradle

@akanto the private maven repo has been fixed

RELENG-5121 use the proper swagger CM lib

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosServiceTest.java
orchestrator-salt/src/main/resources/salt/salt/kerberos/config/krb5.conf-existing
orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls
orchestrator-salt/src/main/resources/salt/salt/sssd/settings.sls
orchestrator-salt/src/main/resources/salt/salt/sssd/template/generate_cm_keytab.j2
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java

[*] Enable FreeIpa on CM as it's disabled by default
[*] Added krb5.conf line for dns lookup
[*] Generate cmf.keytab to create the principals
[*] Sed changes to fixx all the CM script errors

CB-1035 enable FreeIpa on CM

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/volume/AbstractVolumeConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/volume/HdfsVolumeConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/volume/HiveServer2ConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/volume/YarnVolumeConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/volume/HiveServer2ConfigProviderTest.java
template-manager-cmtemplate/src/test/resources/input/clouderamanager-no-hs2.bp

CB-964 Setup 'hive.server2.wm.namespace' param in cm clusterdefinition for hiveserver2

---

README.md

CB-1207 updating readme with UMS and grpc related info.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/mock/ClouderaManagerDownscaleTest.java

Disable ClouderaManager downscale test

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/dto/AbstractCloudbreakTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/mock/ClouderaManagerDownscaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/wait/WaitUtilForMultipleStatuses.java

Downscale test fix

---

core/src/main/java/com/sequenceiq/cloudbreak/repository/StackApiViewRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/UserProfileRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/environment/EnvironmentViewRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/workspace/UserRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/workspace/WorkspaceRepository.java

CB-1250 Sql query tunning on stack and env lists

---

core/src/main/java/com/sequenceiq/cloudbreak/authorization/UmsAuthorizationService.java
core/src/test/java/com/sequenceiq/cloudbreak/authorization/UmsAuthorizationServiceTest.java

CB-1268 error message contains correct information

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering.bp

Testing Done:
Created this blueprint in manowar-dev and used it to create a cluster

CRB-728 Add a built in template for data engineering

---

freeipa/src/main/java/com/sequenceiq/freeipa/api/model/users/SynchronizeUsersRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/api/model/users/SynchronizeUsersResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/api/model/users/SynchronizeUsersStatus.java
freeipa/src/main/java/com/sequenceiq/freeipa/api/model/users/UsersyncEndpoint.java
freeipa/src/main/java/com/sequenceiq/freeipa/configuration/EndpointConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/UsersyncController.java

A separate endpoint and controller is added to the freeipa service
for handling usersync.

DISTX-103. Add usersync API skeleton to freeipa service

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtSetupService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java

CB-1338 Cluster install flow step with CM is now restartabl

---

config/checkstyle/checkstyle.xml
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/database/DatabaseV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/DatabaseV4Endpoint.java
redbeams/.gitignore
redbeams/build.gradle
redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/database/DatabaseV4Controller.java

Dummy redbeams CRUD endpoints have been added.

CB-863. Add dummy redbeams CRUD endpoints.

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/BlueprintUtilV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/BlueprintV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/v4/RecommendationV4Action.java

move blueprint recommendation to blueprint-util api. existing integration tests are fixed too.
Closes CB-1375

CB-1375 move blueprint recommendation to blueprint-util api

---

environment-api/build.gradle
environment-api/src/main/java/com/sequenceiq/environment/client/EnvironmentClient.java
environment-api/src/main/java/com/sequenceiq/environment/client/EnvironmentClientBuilder.java
environment-api/src/main/java/com/sequenceiq/environment/client/EnvironmentUserCrnClient.java
environment-api/src/main/java/com/sequenceiq/environment/client/UserCrnConfigKey.java
environment-api/src/main/java/com/sequenceiq/environment/client/UserCrnToken.java
environment-api/src/main/java/com/sequenceiq/environment/client/WebToken.java

environment-api client module
Closes CB-1354

CB-1354 Environment-api client module

---

integration-test/Makefile

CB-1360 cb build needs to be triggered

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/BlueprintUtilV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/BlueprintV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakClient.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakIdentityClient.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakUserCrnClient.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4EventRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ExistingResourceRestUrlParser.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/v4/RecommendationV4Action.java

separating blueprintutil controller from blueprint controller in order to locate on the right path
Closes CB-1375

CB-1375 blueprintUtil endpoint was out of order

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/CommonCloudProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/dto/ClouderaManagerProductTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/dto/ClouderaManagerRepositoryTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/e2e/aws/AwsBasicStackTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/smoke/YarnSmokeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/util/ClouderaManagerUtil.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/recipes/create-cm-user.sh

CB-1376 Update E2E test projects based on latest changes

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha.bp
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoleConfigConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoles.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/VolumeUtils.java
template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/VolumeUtilsTest.java

Replace hard-coded JournalNode directory with volume-based path calculated at cluster creation time.
Deployed HA cluster.  Added unit test.

[DISTX-127] Dynamically configure JournalNode directory

---

freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaController.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/Stack.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java
freeipa/src/main/resources/schema/app/20190516151400_add_tenant_to_stack.sql

Added column for tenant (customer id) in stack table. 
`BUILD SUCCESSFUL in 42s
348 actionable tasks: 15 executed, 333 up-to-date`
@keyki @lacikaaa @handavid

Tenant col add

---

freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaController.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/Stack.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaDeletionService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/main/resources/schema/app/20190520140000_add_account_id_to_stack.sql

This isto replace tenant -> accountid column 
`BUILD SUCCESSFUL in 4m 15s
361 actionable tasks: 44 executed, 317 up-to-date`
@handavid @keyki @lacikaaa

Add accountid col

---

cloud-common/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/cdp-data-mart.bp
core/src/main/resources/schema/app/20190520161304_CB-1334_remove_old_templates_without_hue.sql
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java

Adding new services to default Data Science template

Add Hue and its dependency, Oozie to Data Science CDP template

---

cloud-common/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/cdp-data-science.bp
core/src/main/resources/schema/app/20190522102701_CB-1334_revert_data_science.sql
integration-test/src/main/resources/application.yml

reverting Data Science rename
a new Data Mart will be created after this.

Revert renaming Data Science to Data Mart

---

cloud-common/src/main/resources/application.yml
cluster-ambari/src/main/java/com/sequenceiq/cloudbreak/ambari/AmbariClusterSetupService.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterSetupService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/ClouderaManagerClientFactory.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/ClouderaManagerClientProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/ClouderaManagerDatalakeConfigProvider.java
core/src/main/resources/defaults/blueprints/cdh6-data-science.bp
core/src/main/resources/defaults/blueprints/cdp-data-science.bp
integration-test/src/main/resources/application.yml
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdater.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java

DatalakeResources collection missing for CM.

CB-1034 Shared Data context support in Cloudbreak

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/BootstrapService.java

Reverts hortonworks/cloudbreak#5054, there is no issue ID in commit.

Revert "Remved hard coded os type"

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/kubernetes/KubernetesV4Base.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/kubernetes/KubernetesV4Endpoint.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/KubernetesConfig.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/environment/Environment.java
core-model/src/test/java/com/sequenceiq/cloudbreak/domain/environment/EnvironmentTest.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/KubernetesV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/environment/EnvironmentCreationValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/EnvironmentToDetailedEnvironmentV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/kuberneteses/KubernetesConfigToKubetnetesV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/KubernetesConfigRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/KubernetesConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/environment/EnvironmentService.java
core/src/main/resources/schema/app/20190522093845_remove_env_key_in_k8s_domain.sql
core/src/test/java/com/sequenceiq/cloudbreak/service/KubernetesConfigServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/kubernetes/KubernetesListAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/kubernetes/KubernetesTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v4/KubernetesAction.java

We need UI modification as well

CB-1508 removed k8s env connection

---

freeipa/src/main/java/com/sequenceiq/freeipa/aspect/SecretAspects.java
freeipa/src/main/resources/application.yml

I modified the aspect according to the documentation. Could you check if this the right way?

CB-1489 Fix Freeipa secret hhandling

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/BootstrapService.java

DISTX-135 Removed Hard Coded ostype and getting it from db 
`BUILD SUCCESSFUL in 12m 37s
362 actionable tasks: 286 executed, 76 up-to-date`
Closes DISTX-135
@keyki @handavid @lacikaaa

DISTX-135 Removed Hard Coded ostype and getting it from db

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/conf/CachingConfig.java
environment-api/build.gradle
environment/src/main/java/com/sequenceiq/environment/configuration/EndpointConfig.java
environment/src/main/java/com/sequenceiq/environment/credential/validation/definition/CredentialDefinitionService.java
environment/src/main/java/com/sequenceiq/environment/exception/MissingParameterException.java
environment/src/main/java/com/sequenceiq/environment/exception/mapper/ConstraintViolationExceptionMapper.java
environment/src/main/java/com/sequenceiq/environment/exception/mapper/DefaultExceptionMapper.java
environment/src/main/java/com/sequenceiq/environment/exception/mapper/WebApplicaitonExceptionMapper.java
environment/src/main/resources/banner.txt

CB-1210 - constraint violation mapper in env service

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCommonService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterCommonServiceTest.java

Add inventory hosts generation for stack endpoint

CB-1552. Add ansible hosts file generation

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/BlueprintUtilV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/responses/BlueprintServicesV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/responses/SupportedServiceV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/clustertemplate/SupportedServicesToBlueprintServicesV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/clustertemplate/SupportedVersionsToSupportedVersionsV4ResponseConverter.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateGeneratorService.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/generator/configuration/CmTemplateGeneratorConfigurationResolver.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/generator/configuration/domain/StackVersion.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/generator/configuration/domain/versionmatrix/CdhService.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/generator/configuration/domain/versionmatrix/ServiceList.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/generator/support/DeclaredVersionService.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/generator/support/SupportedVersionService.java
template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/6.1.json
template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.json
template-manager-cmtemplate/src/main/resources/cloudera-manager-template/service-definitions-minimal.json
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/generator/configuration/CmTemplateGeneratorConfigurationResolverTest.java

CB-1564 Get service list with version for a specific blueprint

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/impala/ImpalaLdapConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/impala/ImpalaRoles.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/impala/ImpalaLdapConfigProviderTest.java

CB-1006 Add LDAP support for Impala using CM

---

environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/EnvCreationActions.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/config/EnvCreationFlowConfig.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/FreeipaCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/NetworkCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/RdbmsCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java
flow/src/main/java/com/sequenceiq/flow/reactor/api/handler/EventSenderAwareHandler.java

CB-1477 – list, describe, persist flow step

CB-1477 – list, describe, persist flow step

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering.bp

Remove zeppelin-GATEWAY-BASE from DE blueprint

CDPD-1062: Remove zeppelin-GATEWAY-BASE from DE blueprint

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerLdapConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoles.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerLdapConfigProviderTest.java

CB-1006 Add LDAP support for Ranger using CM

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/client/ThreadLocalUserCrnWebTargetBuilder.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/client/UserCrnClientRequestFilter.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/client/WebTargetEndpointFactory.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/ThreadBaseUserCrnProvider.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/filter/AuthFilterConfiguration.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/filter/CrnFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateActionsTest.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
flow/src/main/java/com/sequenceiq/flow/core/AbstractAction.java
flow/src/main/java/com/sequenceiq/flow/reactor/FlowParametersAspects.java
flow/src/test/java/com/sequenceiq/flow/core/AbstractActionTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiClientConfig.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiClientParams.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiUserCrnClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/util/UserCrnService.java

@attilapalfi92 or @keyki pls review

CB-1555 client endpoint refactor to setup usercrn automatically

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaModelDescriptions.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/CreateUsersRequest.java

Minor update to maintain consistency with the freeipa create request

DISTX-112. Use common model description for environment

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java

CB-1652 If no usercrn in threadlocal during flow trigger fallback to stackcreator's usercrn

---

core/src/main/resources/defaults/blueprints/cdh6-data-science.bp
core/src/main/resources/defaults/blueprints/cdh6-shared-services.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/cdp-data-science.bp

Add default cardinality to existing templates.  Verified on UI (shared resources / blueprints).

CB-1393. No host group cardinality for CM templates

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/ThreadBasedUserCrnProvider.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentOpDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java
environment/build.gradle
environment/src/main/java/com/sequenceiq/environment/credential/service/AbstractCredentialService.java
environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialDeleteService.java
environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialService.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/CredentialV1Controller.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java
environment/src/main/resources/application.yml
environment/src/test/java/com/sequenceiq/environment/credential/service/CredentialDeleteServiceTest.java
notification-sender/src/main/java/com/sequenceiq/notification/NotificationController.java

CB-1478 multiple delete for env and cred

CB-1478 multiple delete for env and cred

---

core/src/main/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupServiceTest.java

If the cluster request has no explicit `cm.products` information (CDH version and repo URL), use the default one corresponding to `cdhVersion` specified in the blueprint.  The same information is already used to find a compatible CM version (if not specified), but has been so far ignored for finding the default CDH version.
Deployed clusters with and without `products` information.

CB-1560. Wrong default CDH version for CDH 6.2 template

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXClusterToClusterConverter.java

CB-1568 fix for proxy filling on conversion

CB-1568 fix for proxy filling on conversion

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerStopManagementServiceListenerTask.java

Use correct listener task when stopping MGMT service.

CB-681. Wrong listener on MGMT stop

---

cluster-cm/build.gradle
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtSetupServiceTest.java

* Run JUnit 4 tests, which are currently ignored in the `cluster-cm` project.
* Fix broken tests.

CB-331. vintage tests not run

---

cloud-common/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/cdp-data-mart.bp

It contains Hive on MR initially as Hive on Tez is not recognizable
by Hue as of now.

Add DataMart blueprint

---

integration-test/scripts/docker-compose.sh

CB-1543 check cbd start-wait result on service sanity check

CB-1543 check cbd start-wait result on service sanity check

---

common/src/main/java/com/sequenceiq/cloudbreak/util/NullUtil.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/CloudStorageConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/CloudStorageV1ToCloudStorageV4Converter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/ClouderaManagerProductV1ToClouderaManagerProductV4Converter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/ClouderaManagerRepositoryV1ToClouderaManagerRepositoryV4Converter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/ClouderaManagerV1ToClouderaManagerV4Converter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXAuthenticationToStaAuthenticationConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXClusterToClusterConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXEnvironmentV1ToEnvironmentSettingsConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXImageToImageSettingsConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXParameterConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/GatewayV1ToGatewayV4Converter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceGroupParameterConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceGroupV1ToInstanceGroupV4Converter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateV1ToInstanceTemplateV4Converter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/LocationV4ToLocationV1Converter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4Converter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/VolumeConverter.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/AwsCredentialV1ParametersToAwsCredentialAttributesConverter.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/AzureCredentialV1ParametersToAzureCredentialAttributesConverter.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/CredentialToCredentialV1ResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/CredentialV1RequestToCredentialConverter.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/GcpCredentialV1ParametersToGcpCredentialAttributesConverter.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/OpenStackCredentialV1ParametersToOpenStackCredentialAttributesConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentApiConverter.java

- ifNotNull -> doIfNotNull: do smtgh if not null
- ifNotNullF -> getIfNotNull: do smtgh if not null and get the result or null

Distrox request

---

environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialService.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/CredentialV1Controller.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentChangeCredentialDto.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentApiConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java

CB-1483 env edit

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentOpDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/EnvironmentNetworkAzureParams.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentResourceService.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentApiConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java
environment/src/main/java/com/sequenceiq/environment/network/NetworkService.java
environment/src/main/java/com/sequenceiq/environment/network/repository/BaseNetworkRepository.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/EnvironmentBaseNetworkConverter.java

CB-1415 env create with existing network fix

CB-1415 env create with existing network fix

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha.bp

Add Hive-on-Tez and Tez to Data Engineering HA template.
Tested deployment.

DISTX-182. Add Hive-on-Tez to Data Engineering HA template

---

cloud-common/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/cdp-data-engineering.bp
core/src/main/resources/schema/app/20190606084601_update_DE_blueprint_name.sql
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java

Testing Done:
Created the same blueprint in manowar-dev to make sure it works.

Add Hive on Tez and remove Hue from DE template

---

environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java
environment/src/main/java/com/sequenceiq/environment/network/NetworkService.java
environment/src/main/java/com/sequenceiq/environment/network/domain/BaseNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/dto/NetworkDto.java
environment/src/main/java/com/sequenceiq/environment/network/repository/BaseNetworkRepository.java

CB-1415 env network edit fix

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ConfigUtils.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreCloudStorageRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerCloudStorageServiceConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnCloudStorageServiceConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnRoles.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnCloudStorageRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/zeppelin/ZeppelinCloudStorageRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/zeppelin/ZeppelinRoles.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/zeppelin/ZeppelinS3CloudStorageRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreCloudStorageRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerCloudStorageServiceConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnCloudStorageServiceConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnCloudStorageRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/zeppelin/ZeppelinCloudStorageRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/zeppelin/ZeppelinS3CloudStorageRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/resources/input/clouderamanager-ds.bp

DisX-137 Cloud Storage CM Wiring for HMS, Ranger and Yarn

DisX-137 Cloud Storage CM Wiring

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxInternalEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/EndpointConfig.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxInternalController.java

- UI uses a lot of common modules that expect name in the response.

CDPUI-30 sdxname to name

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterResponse.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxClusterConverter.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxInternalController.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxControllerTest.java

CDPUI-30 sdxname to name again

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackV4RequestValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackToStackV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackValidationV4RequestToStackValidationConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/view/StackApiViewToStackViewV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/StackDecorator.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXEnvironmentV1ToEnvironmentSettingsConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/environment/ClusterCreationEnvironmentValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackAwsEncryptionValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/StackToStackV4ResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/StackValidationRequestToStackValidationConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackV4RequestToTemplatePreparationObjectConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/StackDecoratorTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/DetailedEnvironmentResponse.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentBaseResponse.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentApiConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentToDetailedEnvironmentResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentToSimpleEnvironmentResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentViewToSimpleEnvironmentResponseConverter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/environment/EnvironmentTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java

instead of plain Credential name

CB-1727 Include CredentialRequest in DetailedEnvironmentResponse

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/telemetry/logging/LoggingV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/LoggingV4RequestValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidLoggingV4Request.java
core-api/src/test/java/com/sequenceiq/cloudbreak/validation/LoggingV4RequestValidatorTest.java

Add s3 bucket + base path validations for logging request

DISTX-196. Validate Logging inputs during stack request processing

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/ThreadBasedUserCrnProvider.java

CB-1555 store usercrn in a stack in threadlocal to handle multiple add-remove on one thread

---

orchestrator-salt/src/main/resources/salt/salt/fluent/template/td-agent.conf.j2

Added fluentd support for Solr / Atlas / Ranger

DISTX-198. Support uploading Solr/Ranger/Atlas application logs by fluentd to cloud storage

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/delete/handler/freeipa/FreeIpaDeleteRetrievalTask.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/delete/handler/freeipa/FreeipaDeleteHandler.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/Status.java

CB-1839 env flow does not wait for freeipa delete end

CB-1839 env flow does not wait for freeipa delete end

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/delete/config/EnvDeleteFlowChainFactory.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/delete/config/EnvDeleteFlowConfig.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/delete/handler/NetworkDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/delete/handler/RdbmsDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/delete/handler/freeipa/FreeipaDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentResourceDeletionService.java

CB-1840 reorder env delete flow steps
current order is:
1. freeipa
2. rdbms
3. network

CB-1840 reorder env delete flow steps

---

cloud-aws/src/main/resources/definitions/aws-cb-policy.json

This PR added DWX required permissions to the AWS policy JSON file.

Merged in DWX permissions

---

orchestrator-salt/src/main/resources/salt/salt/fluent/init.sls

Install dbus fluentd plugin (only if it's not there already on the image)

DISTX-200. Install fluentd dbus plugin on DistroX/SDX clusters.

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/UserV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UserOperationDescriptions.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeAllUsersRequest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeAllUsersResponse.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeUserRequest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeUserResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/user/FreeIpaUsersStateProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/user/PasswordService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/user/UmsUsersStateProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/user/UserService.java
freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java

The User API has been modified to support separate APIs for single user
and multi-user sync. Single-user sync syncs the caller while multi-user
sync syncs all users in the account.

DISTX-142. Add single-user sync

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/EnvCreationActions.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/delete/EnvDeleteActions.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/delete/handler/NetworkDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/delete/handler/RdbmsDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/delete/handler/freeipa/FreeipaDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java

@doktoric The environment creation and deletion is now working again, the deletion flow start during the creation flow repair will be handled in a separate PR.

CB-1908 fix transient issues on environment and it's related network

---

environment/src/main/java/com/sequenceiq/environment/proxy/v1/converter/ProxyConfigToProxyRequestConverter.java
environment/src/test/java/com/sequenceiq/environment/credential/service/CredentialDeleteServiceTest.java
environment/src/test/java/com/sequenceiq/environment/proxy/v1/ProxyTestSource.java
environment/src/test/java/com/sequenceiq/environment/proxy/v1/converter/ProxyConfigToProxyRequestConverterTest.java
environment/src/test/java/com/sequenceiq/environment/proxy/v1/converter/ProxyConfigToProxyResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/proxy/v1/converter/ProxyRequestToProxyConfigConverterTest.java
environment/src/test/java/com/sequenceiq/environment/proxy/v1/service/ProxyConfigServiceTest.java

unit tests for proxy config services and converters
Closes CB-1913

CB-1913 Create unit tests for Proxy config related services/validators

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/ExposedService.java
orchestrator-salt/src/main/resources/salt/salt/gateway/cm.sls
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_ui.xml.j2
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/atlas/AtlasKnoxRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseKnoxRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseKnoxServiceConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseRoles.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoles.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveRoles.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueRoles.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerKnoxRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoles.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerUserSyncRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnRoles.java

Contains the following:
- Additional service and role configs
- Separation of UA and API topologies

CB-1955 - Enable trusted proxy for all services
