build.gradle
The ability to gather the dependency (transient as well) license files running the `./gradlew dependencyLicenseReport` task. 
Will generate an index.html in `build/reports/dependency-license` will license information.
=> Ability to generate licence

src/main/java/com/sequenceiq/cloudbreak/converter/StackConverter.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsConnector.java
please review @keyki or @martonsereg or @doktoric
/stacks/{id}/status response is extended with cluster status. It is needed for integration tests.
=> CLOUD-311: stack status response extended with clusterstatus

src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/AmbariRoleAllocator.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/ConsulHostCheckerTask.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/ConsulUtils.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/handler/StackUpdateSuccessHandler.java
`Problem1`: During decommission we remove nodes from the consul cluster, but they remain with a failed state so consul can keep trying to reach them. In case if we add new nodes to the cluster with the same IP address which we just removed during decommission, but with different hostname consul will return the wrong PTR record during reverse lookup (it returns to name of the node with the failed state). YARN RM maintains an exclusion list which will contain this hostname, thus the new nodes with the same IP but different hostname cannot join to the Hadoop cluster.
`Solution1`: During stack termination we force the removed nodes to leave the consul cluster, so their state become `left`. In this way consul will resolve properly the newly added hosts.
`Problem2`: Result of Problem1. In case …
=> CLOUD-455 remove nodes from consul and deal with alive members only

build.gradle, config/checkstyle/checkstyle-suppressions.xml, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureStackUtil.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/AzureSimpleInstanceResourceBuilder.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/AzureResourceBuilderInit.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/instance/AzureVirtualMachineResourceBuilder.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/network/AzureNetworkResourceBuilder.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/model/AzureProvisionContextObject.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/model/AzureStartStopContextObject.java, src/test/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureStackUtilTest.java
`Problem`: The way we currently allocate IP addresses in the VPC on Azure is wrong. 
`Solution`: Every instance builder tries to find a valid IP, by starting from the first available IP in the subnet and incrementing the address until they find an available one. All resource builders share a context object which got extended with a volatile Set IP pool to avoid allocating the same IP to multiple instances. If a builder finds a free IP it writes it to the pool so others will see that it is already taken. It means multiple threads try to read and write the same pool concurrently so synchronization is a crucial point. On upscale a set of IP is already provided, by the running instances. 
@martonsereg @doktoric
=> CLOUD-449 avoid IP collision in Azure VPC

src/main/java/com/sequenceiq/cloudbreak/domain/InstanceMetaData.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/filter/AmbariServerFilter.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/filter/AppMasterFilter.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/filter/ConsulServerFilter.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/filter/HostFilter.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/filter/HostFilterService.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/filter/NameNodeFilter.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/AmbariRoleAllocator.java, src/test/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterServiceTest.java
`Problem`: During downscale there is a high chance we remove a host which acts as a consul server thus the cluster becomes unreliable.
`Solution`: We keep track of the consul servers and exclude them from the decommission candidates as reserved instances.
@martonsereg
=> CLOUD-457 Do not delete consul servers during downscale

src/main/java/com/sequenceiq/cloudbreak/controller/json/FailurePolicyJson.java, src/main/java/com/sequenceiq/cloudbreak/controller/json/StackJson.java, src/main/java/com/sequenceiq/cloudbreak/converter/StackConverter.java, src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/UserDataBuilder.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/ConsulUtils.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/ProvisionContext.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/handler/UpdateInstancesRequestHandler.java, src/main/resources/azure-init.sh, src/main/resources/ec2-init.sh, src/main/resources/gcc-init.sh, src/main/resources/openstack-init.sh, src/test/java/com/sequenceiq/cloudbreak/service/stack/connector/UserDataBuilderTest.java, src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/ProvisionContextTest.java, src/test/resources/azure-init-test-expected.sh, src/test/resources/ec2-init-test-expected.sh, src/test/resources/gcc-init-test-expected.sh, src/test/resources/openstack-init-test-expected.sh
@biharitomi @martonsereg 
It is possible now to configure how many consul servers should CB launch. If it's not provided the defaults are used.
DB change required, changeset added to liquibase.
=> CLOUD-401 configurable consul server count with defaults

src/main/java/com/sequenceiq/cloudbreak/controller/ExceptionControllerAdvice.java, src/main/java/com/sequenceiq/cloudbreak/controller/json/StackJson.java, src/main/java/com/sequenceiq/cloudbreak/controller/validation/ParametersRegexValidator.java, src/main/java/com/sequenceiq/cloudbreak/controller/validation/StackJsonValidator.java, src/main/java/com/sequenceiq/cloudbreak/controller/validation/StackParam.java, src/main/java/com/sequenceiq/cloudbreak/controller/validation/ValidStackRequest.java, src/main/java/com/sequenceiq/cloudbreak/converter/StackConverter.java, src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsConnector.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsMetadataSetup.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/CloudFormationStackStatusChecker.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/CloudFormationTemplateBuilder.java, src/main/resources/templates/aws-cf-stack.ftl, src/test/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/CloudFormationTemplateBuilderTest.java
@doktoric 
Ability to create stacks in an existing VPC on AWS. VPCId, internetGatewayId and subnetCIDR parameters only make sense on AWS stacks so these are not part of the main Stack domain object, I've rather introduced stack parameters that is an unstructured set of params.
VPC ids and subnet overlappings are not validated before stack creation, so these will only turn out when the CloudFormation stack is creating.
UI and Shell changes are not yet done, this `curl` can be used to test this PR:
```
curl -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json"  -d '{"name":"almasd","userName":"admin","password":"admin","credentialId":"50","region":"US_WEST_2","instanceGroups":[{"templateId":52, "nodeCount":1, "group":"master"},{"templateId":52, "nodeCount":3, …
```
=> CLOUD-470 stacks can be created in an existing VPC on AWS

src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsConnector.java
@biharitomi 
Public DNS names must be enabled on the VPC on AWS that is not possible when deploying to an existing one, but we can use the ip addresses as well (and we do use them when creating a stack). This PR fixes that we are using them when restarting a cluster as well.
=> CLOUD-470 use ip address instead of dns name when restarting instances

src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/openstack/HeatTemplateBuilder.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/openstack/OpenStackConnector.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/openstack/OpenStackInstance.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/openstack/OpenStackMetadataSetup.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/openstack/OpenStackUtil.java, src/main/resources/templates/openstack-heat.ftl
@doktoric please review
Scaling without AS group is not that easy. We have to generate the whole template on each update like we would do it for the first time. Previously the resource generation was:
node_1
node_2
node_3
.. The host group didn't matter. With scaling it causes problems so it's changed to:
node_slave1_0
node_slave1_1
node_slave1_2
node_slave2_0
node_slave2_1
node_master_0
Each resource has its own private ID within the host group. In case of downscale now we can say that not to generate the node_slave1_1 when generating the whole template again.
The instance id looks like the following uuid_slave1_1 to be able to identify the host group and private id later.
=> CLOUD-491 scaling on Openstack

src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java, src/main/java/com/sequenceiq/cloudbreak/controller/StackController.java, src/main/java/com/sequenceiq/cloudbreak/controller/json/StackValidationRequest.java, src/main/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/BlueprintServiceComponent.java, src/main/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/BlueprintValidator.java, src/main/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/StackServiceComponentDescriptor.java, src/main/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/StackServiceComponentDescriptorMapFactory.java, src/main/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/StackServiceComponentDescriptors.java, src/main/java/com/sequenceiq/cloudbreak/converter/BlueprintConverter.java, src/main/java/com/sequenceiq/cloudbreak/converter/ClusterConverter.java, src/main/java/com/sequenceiq/cloudbreak/converter/InstanceGroupConverter.java, src/main/java/com/sequenceiq/cloudbreak/converter/StackValidationConverter.java, src/main/java/com/sequenceiq/cloudbreak/domain/StackValidation.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/DefaultStackService.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, src/main/resources/hdp/hdp-services.json, src/test/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/BlueprintValidatorTest.java, src/test/java/com/sequenceiq/cloudbreak/converter/BlueprintConverterTest.java, src/test/java/com/sequenceiq/cloudbreak/converter/ClusterConverterTest.java
@keyki pls review
**Notes**
* validate hostgroup and instancegroup name matching
* validate hostgroup and instancegroup count matching
* validate hostgroup cardinality based on it’s master components’ max cardinality
* validate master components’ max cardinality in more than one host groups 
* if validation fails cluster creation request will throw BadRequestException
* introducing new stack validation request: stacks/validate
**Tested with**
* hdp-multinode-default
* lambda-architecture: starts only if master and slave_1 node count was 1, slave_1 with more than one nodes start will fail because of snamenode. with new validation slave_1 nodecount can be only 1 because it contains master components with 1 cardinality: example snamenode, storm_ui_server
* multi-node-hdfs-yarn
* …
=> CLOUD-269: Blueprint validation improvement

build.gradle, gradle/wrapper/gradle-wrapper.properties, integrationtest/build.gradle, integrationtest/gradle/wrapper/gradle-wrapper.properties
@doktoric 
- upgraded gradle version to 2.3
- remove unused systemProperties (this field also not supported in version 2.3)
- jacoco test properties cannot be set at sonarRunner -> relocate into test task
- checkstyle -> guava classes missing -> force to use guava 16.0.1
=> CLOUD-468 upgrade gradle version to 2.3

src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java
@doktoric or @martonsereg 
db (cloudbreak) migration is needed
=> CLOUD-479 removed stack unique name constraint

src/main/java/com/sequenceiq/cloudbreak/controller/ExceptionControllerAdvice.java, src/main/java/com/sequenceiq/cloudbreak/controller/json/ClusterRequest.java, src/main/java/com/sequenceiq/cloudbreak/controller/json/ClusterResponse.java, src/main/java/com/sequenceiq/cloudbreak/controller/json/HostGroupJson.java, src/main/java/com/sequenceiq/cloudbreak/controller/json/RecipeJson.java, src/main/java/com/sequenceiq/cloudbreak/controller/validation/TrustedPluginValidator.java, src/main/java/com/sequenceiq/cloudbreak/converter/ClusterConverter.java, src/main/java/com/sequenceiq/cloudbreak/domain/Cluster.java, src/main/java/com/sequenceiq/cloudbreak/domain/HostGroup.java, src/main/java/com/sequenceiq/cloudbreak/domain/HostMetadata.java, src/main/java/com/sequenceiq/cloudbreak/domain/PluginExecutionType.java, src/main/java/com/sequenceiq/cloudbreak/domain/Recipe.java, src/main/java/com/sequenceiq/cloudbreak/repository/ClusterRepository.java, src/main/java/com/sequenceiq/cloudbreak/repository/HostGroupRepository.java, src/main/java/com/sequenceiq/cloudbreak/repository/HostMetadataRepository.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ConsulKVCheckerTask.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ConsulPluginManager.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/PluginManager.java, src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java, src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java, src/main/java/com/sequenceiq/cloudbreak/service/recipe/SimpleRecipeService.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/handler/StackDeleteCompleteHandler.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/handler/StackStatusUpdateHandler.java
@doktoric 
- Recipes are associated with host groups instead of the cluster itself. Also one host group can contain multiple recipes (e.g.: spark and GCS connector). 
- Recipe plugins now have an execution type - `one-node` or `all-nodes`. If `one-node` is set, the plugin will only be installed on one of the nodes in the host group. It can be used for example to run HDFS commands in the plugin.
- Only the newly added hosts run the recipes on upscale 
DB migrations submitted
Rest-client changes: sequenceiq/cloudbreak-rest-client#46
Shell changes: sequenceiq/cloudbreak-shell#63
=> Recipe improvements

src/main/resources/azure-init.sh, src/main/resources/ec2-init.sh, src/main/resources/gcc-init.sh, src/main/resources/openstack-init.sh
@keyki 
-Dcb.azure.image.uri=http://102589fae040d8westeurope.blob.core.windows.net/images/packer-cloudbreak-2015-03-10-centos6_2015-March-10_17-15-os-2015-03-10.vhd
-Dcb.gcp.source.image.path=sequenceiqimage/sequenceiq-ambari17-consul-centos-2015-03-10-1449.image.tar.gz
-Dcb.aws.ami.map=ap-northeast-1:ami-c528c3c5,ap-southeast-2:ami-e7c3b2dd,sa-east-1:ami-c5e55dd8,ap-southeast-1:ami-42c3f510,eu-west-1:ami-bb35a7cc,us-west-1:ami-4b20c70f,us-west-2:ami-eb1f3ddb,us-east-1:ami-00391e68
-Dcb.openstack.image=packer-cloudbreak-centos-2015-03-11
=>  CLOUD-496 separate postgres

src/test/java/com/sequenceiq/cloudbreak/service/usages/IntervalInstanceUsageGeneratorTest.java
@keyki or @doktoric or @lpuskas please take a look!
Set dates to a specified date on January in IntervalInstanceUsageGeneratorTest, because the forthcoming time changing related to summer time causes assertion errors.
=> Set Calendars to a specified date in tests to solve assertion errors

src/test/java/com/sequenceiq/cloudbreak/service/usages/IntervalInstanceUsageGeneratorTest.java
@keyki 
Set date to avoid time changing related to summer time in IntervalInstanceUsageGeneratorTest.
=> CLOUD-542 fix test date

src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ConsulPluginManager.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/DiskAttachUtils.java, src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/openstack/HeatTemplateBuilder.java, src/main/resources/azure-gateway-init.sh, src/main/resources/azure-hostgroup-init.sh, src/main/resources/ec2-gateway-init.sh, src/main/resources/ec2-hostgroup-init.sh, src/main/resources/gcc-gateway-init.sh, src/main/resources/gcc-hostgroup-init.sh, src/main/resources/openstack-gateway-init.sh, src/main/resources/openstack-hostgroup-init.sh
CLOUD-549: Move consul-watch and plugn into a separated container, CLOUD-546 fix: mounting attached disks under hadoopfs dir instead of mnt
=> CLOUD-549: Move consul-watch and plugn into a separated container, CLOUD-546 fix: mounting attached disks under hadoopfs dir instead of mnt

src/main/java/com/sequenceiq/cloudbreak/controller/validation/AWSCredentialParam.java, src/main/java/com/sequenceiq/cloudbreak/controller/validation/CredentialParametersValidator.java, src/main/java/com/sequenceiq/cloudbreak/domain/AwsCredential.java, src/main/java/com/sequenceiq/cloudbreak/domain/Credential.java, src/main/java/com/sequenceiq/cloudbreak/repository/CredentialRepository.java, src/main/java/com/sequenceiq/cloudbreak/service/credential/SimpleCredentialService.java, src/main/java/com/sequenceiq/cloudbreak/service/credential/aws/AwsCredentialHandler.java
@doktoric 
This change allows an IAM role to be exposed as public (it is already handled like that now - stored in db as plain text, exposed on UI as plain text, etc..).
The IAM role cannot be reused outside of Cloudbreak, because it is configured to trust only the Cloudbreak deployer account, but it can be reused in Cloudbreak itself if it is captured by an attacker. This change restricts the usage to only one account (but multiple users inside), so it won't be reusable in Cloudbreak either.
=> CLOUD-666 RoleArn can only be used from 1 account

core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/json/ClusterRequest.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/json/UpdateClusterJson.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecorator.java
@biharitomi @schfeca75 
This PR adds the ability to bypass the blueprint validation. By default it is turned on, otherwise it should be specified in the JSON both when creating the cluster and we re-creating it.
=> CLOUD-708 bypass blueprint validation

orcestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orcestrator/swarm/SwarmContainerOrchestrator.java, orcestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orcestrator/swarm/containers/AmbariServerBootstrap.java, orcestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orcestrator/swarm/containers/AmbariServerDatabaseBootstrap.java
The IP address of the ambari db may change after restart and the server won't be able to connect to it. There are 2 solutions:
* launch with net=host this is what i just did
* let registrator register the db and modify the ambari-server start script to get the db IP from consul
=> CLOUD-576 start ambari db with net=host

core/src/main/resources/init/init.sh, orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java
@akanto or @martonsereg pls review
* increasing munchausen timeout to 360
* using lazy_itable_init mkfs parameter to speed up the disk formatting
* was tested on azure with teragen / terasort / teravalidate on hadoop cluster with 12 nodes
* was tested on aws, azure and gcp with TestDFSIO read / write
=> CLOUD-738: Timeout can be too short when multiple large volumes are attached

core/build.gradle, core/src/main/java/com/sequenceiq/cloudbreak/controller/json/TemplateRequest.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow/ClusterBootstrapper.java, core/src/main/java/com/sequenceiq/cloudbreak/domain/AwsInstanceType.java, core/src/main/java/com/sequenceiq/cloudbreak/domain/CloudPlatform.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsConnector.java, core/src/main/resources/init/init.ftl, core/src/main/resources/templates/aws-cf-stack.ftl, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/CloudFormationTemplateBuilderTest.java, core/src/test/resources/azure-core-init.sh, core/src/test/resources/azure-gateway-init.sh, orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java
@schfeca75 please review
added support for d2 type instances:
- d2xlarge, d22xlarge, d24xlarge instances work as expected
- d28xlarge instances cannot be started (even with our base ami), so those won't be available on the UI
- increased timeout for Munchausen wait and cluster bootstrapping, because if the gateway doesn't have any large volumes attached its Docker API will be available much faster than on the other instances with lots of large volumes (e.g: 12 2TB instance store volumes for d24xlarge).
- fixed bug with volume labels (labels were converted from the hex value to ascii characters)
- aws volume labeling now starts from "b"
=> support for d2 instances

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariOperationsStatusCheckerTask.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AddInstancesOperation.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureConnector.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureOperation.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/BuildStackOperation.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/DeleteStackOperation.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/RemoveInstancesOperation.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/RollbackOperation.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/StartStopOperation.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/UpdateAllowedSubnetsOperation.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/AzureResourceStatusCheckerTask.java
AzureConnector refactor:
* azureConnector operations which belong to the same subscription cannot be executed parallel
* if an operation is in progress and an another should be started, notification will be sent about the waiting.
* all the azure operations are executed in this way
* the execution mode can be controlled with the "queued" parameter
* no state change to pending
* no retry mechanism in case of conflict error: if there are running operations started outside from the current cloudbreak conflicts with inner operations
Known bugs:
* if stack creation is in progress and the cluster will be terminated: ongoing pollings will be cancelled but termination can be failed because of conflict on azure operations. Solution: waiting for the pollings to be finsished before starting the …
=> CLOUD-682: Azure can't process more than one network operations simultaneously

core/build.gradle, core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunner.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ContainerOrchestratorResolver.java, orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/ContainerOrchestrator.java, orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/ContainerOrchestratorTool.java, orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/SimpleContainerOrchestrator.java, orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java
@martonsereg please check
- core has only runtime dependency on swarm
- eliminate the ContainerOrchestratorTool enum to make the plugin mechanism more dynamic
- delete code duplication by introducing ContainerOrchestratorResolver
- some code formatting
=> CLOUD-811 Eliminate swarm compile time dependency from core

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/AbstractFlowHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow/FlowCancelledException.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow/context/StackStatusUpdateContext.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow/handlers/ClusterStartHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleFlowFacade.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleStackFacade.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/StackStartService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/StackStopService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/PollingResult.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariHealthCheckerTask.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariHostsJoinStatusCheckerTask.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackFailureHandlerService.java
@doktoric please check this
Main goal was to separate logic in cluster and stack layers. 
When starting a cluster, checking the Ambari server and starting the agents are part of the cluster layer. When stopping a cluster, stopping the agents are again part of the cluster layer.
I've also cleaned up the code in some classes.
=> cleaned up stack and cluster layers in start/stop implementation

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureProvisionSetup.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/AzureResourcePollerObject.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/AzureResourceStatusCheckerTask.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/instance/AzureCloudServiceResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/instance/AzureServiceCertificateResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/instance/AzureVirtualMachineResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/network/AzureAffinityGroupResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/network/AzureNetworkResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/network/AzureReservedIpResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/network/AzureStorageAccountResourceBuilder.java, core/src/main/resources/logback.xml
@martonsereg 
Log messages like this: 
ce022217551f] [type:STACK] [id:1103] [name:marciteszt3] Response code: 200; found handler: org.codehaus.groovy.runtime.MethodClosure@13cc99e3
came from the Azure rest client due to its debug logging, but it's useless so I turned it off.
=> CLOUD-835 cleaned Azure logging

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
@martonsereg please take a look!
- Optimistic locking exception should not be occurred when cluster and stack stops are requested at almost the same time
- Integration tests are checked and no modification is required
- Tested with stop requests at the same time and requests in a row when stopping of cluster is in progress and after it has been finished.
=> CLOUD-870 remove stack status update to avoid optimistic locking exceptions

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/AbstractFlowHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow/CloudbreakErrorHandler.java
* exceptions thrown from handlers are logged with the stacktrace
* the logging "logic" is moved to the CloudbreakErrorHandler
* cleaned some other log messages
@akanto please check this out
=> CLOUD-873 Exceptions logged properly, with the stacktrace

core/src/main/java/com/sequenceiq/cloudbreak/service/network/ExposedService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/network/NetworkUtils.java, core/src/main/java/com/sequenceiq/cloudbreak/service/securitygroup/DefaultSecurityGroupCreator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java, core/src/main/resources/schema/20150623133213_CLOUD-872_create_default_security_groups_and_rules.sql
@keyki or @martonsereg please review it!
Changes:
- detach security group form stack at termination
- update default security groups description
- create a migration script that creates default security groups and rules for existing stacks (it is tested on a production like database)
=> CLOUD-872 fix default security rules and groups description and migration scripts

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/HostMetadata.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/StackStartService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/StackStopService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/CloudPlatformConnector.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/ParallelCloudResourceManager.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsConnector.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureConnector.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureResourceException.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/StartStopOperation.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/gcp/GcpConnector.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/openstack/OpenStackConnector.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/ResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/AzureSimpleInstanceResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/AzureSimpleNetworkResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/instance/AzureVirtualMachineResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/GcpSimpleInstanceResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/GcpSimpleNetworkResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/builders/instance/GcpInstanceResourceBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/builders/network/GcpNetworkResourceBuilder.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/dummy/instance/DummyAttachedDiskResourceBuilder.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/dummy/instance/DummyExVirtualMachineResourceBuilder.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/dummy/instance/DummyVirtualMachineResourceBuilder.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/dummy/network/DummyExNetworkResourceBuilder.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/dummy/network/DummyNetworkResourceBuilder.java
@doktoric 
removed boolean return values from start-stop related calls, because we should keep the error context as well to provide some information on failures. When something fails, an exception is thrown like in other cases.
=> DEV-45 propagate exceptions on start-stop

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/ProvisioningSetupService.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/StackUpdater.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureProvisionSetup.java
* optimistic locking exception avoided by not saving the stack after (azure) provisioning setup
* events are published about the image copy status (azure)
* copy status check interval increased from 5 sec to 30 (azure)
@doktoric please review it
=> CLOUD-880 removed superfluous saving of stack during provisioning setup

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsConnector.java
cloud formation generated roles can have name easily longer than 70 chars, which causes createstack call to fail
moreover relearn should be kept as a secret
=> DEV-41 Replace stackowner ec2 tag value from relearn to email

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleStackFacade.java
=> CLOUD-938: moving stack status update to AVAILABLE from bootstrapNewNodes to extendConsulMetadata

core/src/main/resources/templates/aws-cf-stack.ftl
@biharitomi 
An earlier fix broke the feature to deploy clusters in an existing vpc on AWS.
=> CLOUD-898 fixed cf template for existing vpcs

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariHostsLeaveStatusCheckerTask.java
Stop the ambari agents before deleting them during downscale. Unfortunately it does not solve the dead node issue.
@biharitomi @akanto @doktoric
=> CLOUD-959 stop Ambari agents before deleting them

core/src/main/resources/init/init.ftl, core/src/test/resources/azure-core-init.sh, core/src/test/resources/azure-gateway-init.sh
@akanto pls review
Was tested:
- aws, after create, after stop/start
- gcp, after create, after stop/start
- azure, after create
not tested:
- openstack
- azure stop/start
=> CLOUD-663: workaround for aws/azure, without this the /etc/sysctl.conf parameters have no effect after stop/start

build.gradle
@keyki 
If rc changes are merged back to master but there were no other changes on master after the first RC, then the commits on the rc branch will be the same as the commits on master and will have both the rc tags and the new dev tags (e.g.: `0.8.0-dev.1 and 0.7.0-rc.2`), so the release (`0.7.0`) will fail if precedence is enforced (`0.7.0` cannot be preceded by `0.8.0-dev.1`).
=> CLOUD-932 do not enforce precedence of versions

build.gradle
@akanto please take a look
Instead of the latest RC tag, the latest pre release tag was used in most cases. But dev tags are also pre-release tags, and that caused some complications if dev tags appeared on the rc branch when rc patches were merged back to master.
The `1.1.0-rc.1` tag should be removed from the remote repo before merging this PR, because it will cause failures when the real `1.1.0-rc.1` should be released later
=> CLOUD-932 always work with latest rc tag when scope is rc

conf/README.md
It looks like /conf was an accidentally created dupe of /config (the commit refers to a file that does not exist)? Assuming it's a dupe, this deletes it.
=> Removed conf directory which appears to be a duplicate of /config

cloud-openstack/src/test/java/com/sequenceiq/cloudbreak/cloud/conf/EventBusConfig.java, cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/config/CloudReactorConfiguration.java, cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/reactor/config/EventBusConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/conf/AsyncConfig.java
Added some thread names to help give us a better idea of what's going on when we take thread dumps, use monitoring tools, debug, etc. I used the camelCase naming convention since it was used on a few other threadpools in cloudbreak.
=> Add thread names

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AzureRmCredentialCreationTest.java
=> CLOUD-42308: integration test fix: ssh key have to be base64 encoded when creating azure rm credential

core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java
Please review @schfeca75 !
Makes Cloudbreak handle new read-only scopes on resources' endpoints and try to validate all possible URL patterns with scopes.
=> CLOUD-42526 add read only scopes of resources to security config

core/src/main/resources/messages/messages.properties
A single quote escaped all the parameter placeholders in some messages.
=> CLOUD-43441 Fix error messages

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
There is a bug in 2.1.1 which prevents using the attached disks
=> CLOUD-43945 downgrade to Ambari 2.1.0

core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/ExceptionControllerAdvice.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToFileSystemConverter.java
@biharitomi 
FileSystemConfigs were mapped from JSON in a previous PR, but validation must be called explicitly for them.
=> CLOUD-42393 validate fs properties for real this time

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/dash/DashFileSystemConfiguration.java, core/src/main/resources/scripts/dash-hdfs.sh, core/src/main/resources/scripts/dash-local.sh
@biharitomi 
validate account name/ account key with regex,
change dash storage jars in local mapreduce.tar.gz as well because it is recopied to hdfs when some services are restarted
find mapreduce hdfs directory based on hdp version parsed from local filesystem, because the previous solution failed when a dash storage was used with another hdp version pre-installed
=> CLOUD-42393 some dash fs changes

core/src/main/java/com/sequenceiq/cloudbreak/service/PollingResult.java, core/src/main/java/com/sequenceiq/cloudbreak/service/PollingService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/SimpleStatusCheckerTask.java, core/src/main/java/com/sequenceiq/cloudbreak/service/StatusCheckerTask.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariOperationsStatusCheckerTask.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasbintegrated/StorageAccountStatusCheckerTask.java, core/src/main/resources/messages/messages.properties, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnectorTest.java
@biharitomi 
If MR Smoke test fails, it should not cause a failure in the cloudbreak cluster creation, it sends a Warning event instead.
=> CLOUD-44576 smoke test failure sends warning

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
@akanto @martonsereg 
In docker-ambari I moved Zeppelin to the base image so the newly created cloud images will have this change, but I'm lazy to rebuild it for now.
=> CLOUD-45185 since there is no warmup we can use that image which has Zeppelin in it

core/src/main/resources/scripts/dash-hdfs.sh, core/src/main/resources/scripts/dash-local.sh, core/src/main/resources/scripts/gcs-connector.sh, core/src/main/resources/scripts/gcs-p12.sh, core/src/main/resources/scripts/hdfs-home.sh
@keyki 
If some recipes fail but this script runs first and creates the directories it will fail after a cluster reinstall when all the recipes run again.
Also do not truncate the consul-handler log file with `exec &>` in the scripts
=> CLOUD-48869 ability to run hdfs-home multiple times successfully

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpMetadataCollector.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java
@akanto 
Due to resource name change we cannot determine the instances instance group thus we rely on the existing information. In case of GCP every instance will come back from the metadata collection as gw node, but that's incorrect so we use the original one.
=> CLOUD-46378 GCP stop/start after CB update from 1.0.x

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/AbstractFileSystemConfigurator.java, core/src/main/resources/init/init.ftl, core/src/main/resources/scripts/dash-hdfs.sh, core/src/main/resources/scripts/dash-local.sh, core/src/test/resources/azure-core-init.sh, core/src/test/resources/azure-gateway-init.sh
@keyki 
- tez.tar.gz contains an azure-storage jar as well, I've modified the dash scripts to change it there as well
- the `oozie.service.HadoopAccessorService.supported.filesystems` configuration's default value is `hdfs` so if it's not set then wasb is not working with oozie
- oozie server must be restarted after the azure jars are changed
- /hadoopfs/fs directories' permission is set to 777 so default ssh user is able to scp files there
- oozie sharelib creation on hdfs is not done via cloudbreak, it is the responsibility of the oozie user by executing `oozie-setup.sh sharelib create -fs <fs.defaultFs>`
=> Dash enhancements

core/src/main/resources/scripts/dash-local.sh
@keyki 
otherwise the next 'stop service' operation from Ambari will fail because it won't be able to access the pid file created by 'root' user
=> Restart as oozie user just like in ambari

gradle.properties, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTestSuiteInitializer.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SecurityGroupCreationTest.java, integration-test/src/main/resources/testsuites/aws/smoke/aws-clustercreate-startstop-updown.yaml, integration-test/src/main/resources/testsuites/azurerm/smoke/azurerm-clustercreate-startstop-updown.yaml, integration-test/src/main/resources/testsuites/gcp/smoke/gcp-clustercreate-startstop-updown.yaml, integration-test/src/main/resources/testsuites/nativeos/smoke/nativeos-clustercreate-startstop-updown.yaml, integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate-startstop-updown.yaml
@schfeca75 
Let's test the clusters using a restricted security group. 8080 is open as the IT itself tries to communicate with Ambari, 443 should be enough for that, but it requires 2-way-ssl connection and we don't have the client cert.
=> CLOUD-46100 create a restricted security group for each cluster

core/build.gradle
@schfeca75 
sshj 0.15.0-rc.1 is manually built and uploaded to maven.sequenceiq.com. It will be used until the 0.15.0 sshj release is out.
=> CLOUD-48384 new sshj version fixes ecdsa fingerprint issue

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java, shell/src/main/java/com/sequenceiq/cloudbreak/shell/transformer/ResponseTransformer.java
@doktoric or @keyki plz review
Fixes:
BUG-51703 SHELL: Remained "EC2" references should be replaced with "AWS"
BUG-52211 SHELL: AWS 'template show' throws "java.lang.RuntimeException"
=> CLOUD-51703 CLOUD-52211 Fix SHELL template problems

build.gradle, gradle.properties, shell/build.gradle
with this PR applied:
```
$ gradle :cloud-common:build
Parallel execution with configuration on demand is an incubating feature.
:cloud-common:compileJava UP-TO-DATE
:cloud-common:processResources UP-TO-DATE
:cloud-common:classes UP-TO-DATE
:cloud-common:jar UP-TO-DATE
:cloud-common:assemble UP-TO-DATE
:cloud-common:checkstyleMain UP-TO-DATE
:cloud-common:compileTestJava UP-TO-DATE
:cloud-common:processTestResources UP-TO-DATE
:cloud-common:testClasses UP-TO-DATE
:cloud-common:checkstyleTest UP-TO-DATE
:cloud-common:test UP-TO-DATE
:cloud-common:check UP-TO-DATE
:cloud-common:build UP-TO-DATE
BUILD SUCCESSFUL
Total time: 0.835 secs
```
=> get the gradle build sub-second

cloud-common/src/main/resources/application.yml
This default value can be used as "fixed" on all environments. On cbd deployments docker takes, care, For local dev, you can:
- configure `/etc/hots`file
- configure `/etc/resolver/service.consul `
use the `docker-machine ip` or `boot2docker ip` for actual ip
```
192.168.59.103 consul.service.consul
```
use the `docker-machine ip` or `boot2docker ip` for actual ip
```
cat >  /etc/resolver/service.consul <<EOF
nameserver 192.168.59.103
EOF
```
=> CLOUD-52281: Add sensible default hostname

cloud-common/src/main/resources/application.yml
@akanto,@keyki pls
We should avoid keeping 2 yaml (one in cloudbreak,  one in cloudbreak-images) to list docker images we need on the cloud-images.
cloudbreak-image should use application.yml from cloud-common, and remoce vars-docker-images.yml
=> CLOUD-52916: add reference to all images, so cloudbreak-images can use this a "source of truth"

core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToCredentialConverter.java
@akanto when you create a new azure credential the json contains accessKey and secretKey like in case of aws which cause that the login username will be ec2-user on azure.
=> CLOUD-53668 fixed ssh username

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java, core/src/main/resources/hdp/hive-kerberos-descriptor.json
@akanto in secure cluster if stack advisor used we extend the bp with a kerberos descriptor if there is no user specified
=> CLOUD-53432 workaround for missing hive keytab

web/app/static/partials/dashboard.html
@mhmxs 
isWriteScope takes a while to finish while the page renders in the background and tries to hook a click event on the cluster-create button, but it's not there yet because of the isWriteScope hasn't finished yet
this PR changes that even if you don't have write permission the button is still visible but you cannot click it
=> CLOUD-49027 fix onclick event

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java
=> CLOUD-56572: stack create command doesn't work: 'region' parameter is missing

cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
@biharitomi 
When deleting the CF stack, the delete of the DetachGateway resource can start while the AutoScalingGroup is still being deleted. Probably this was causing problems when it happened before the instances in the group still had mapped public addresses.
With this fix the route tables and gateway attachments will only be deleted after the ASG is deleted.
=> CLOUD-55843 fix dependencies between ASG and IGW

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToStatusConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java, shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java, shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/ClusterCommands.java, shell/src/main/java/com/sequenceiq/cloudbreak/shell/util/CloudbreakShellUtil.java
@doktoric 
If something fails when --wait=yes is set, cloudbreak shell will show the status reason, not only a generic failure message.
=> CLOUD-56733 show status reason in shell on failure

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ConstraintTemplateBase.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/ConstraintTemplate.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/ConstraintTemplateToJsonConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToConstraintTemplateConverter.java, core/src/main/resources/schema/app/20160602190114_Add_orchestratorType_to_constrainttemplate.sql, web/app/static/js/controllers/templateController.js, web/app/static/js/services.js, web/app/static/tags/templatepanel.tag
@martonsereg - Please review as time permits. 
This PR adds the orchestratorType field to the constraint domain to enable multiple different orchestrators under the BYOS cloud platform. This allows for controlling UI elements based on the type of orchestrator defined.
=> Add orchestratorType to the constraint domain

core/src/main/resources/schema/app/20160602190114_Add_orchestratorType_to_constrainttemplate.sql
@martonsereg - Here is the PR that fixes the db migration when the constrainttemplate table already exists.
=> set a default for orchestratortype for existing rows

cloud-arm/src/main/resources/arm-images.yml, cloud-aws/src/main/resources/aws-images.yml, cloud-gcp/src/main/resources/gcp-images.yml, cloud-openstack/src/main/resources/os-images.yml
- RM does not work with kerberos
- The Ambari is more memory hungry: 4GB is not enough
=>  CLOUD-58099 Update to Ambari 2.4.0.0-660

cloud-aws/src/main/resources/definitions/aws-vm.json
- For high memory uses such as Spark & LLAP
- https://aws.amazon.com/ec2/instance-types/x1/
=> FIX BUG-60182: Add x1.32xlarge AWS EC2 instance type to CloudBreak

core/src/main/java/com/sequenceiq/cloudbreak/service/notification/HttpNotificationSender.java
@doktoric 
cloudbreak doesn't handle responses to notification messages just sends the http requests out so it doesn't matter if the target is untrusted.
=> send notifications to untrusted https as well

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/OpenStackNetworkCreationTest.java, integration-test/src/main/resources/application.yml, integration-test/src/main/resources/testsuites/aws/smoke/aws-clustercreate-startstop-updown.yaml, integration-test/src/main/resources/testsuites/aws/smoke/aws-clustercreate-startstop.yaml, integration-test/src/main/resources/testsuites/aws/smoke/aws-clustercreate-updown.yaml, integration-test/src/main/resources/testsuites/aws/smoke/aws-clustercreate.yaml, integration-test/src/main/resources/testsuites/azurerm/smoke/azurerm-clustercreate-startstop-updown.yaml, integration-test/src/main/resources/testsuites/azurerm/smoke/azurerm-clustercreate-startstop.yaml, integration-test/src/main/resources/testsuites/azurerm/smoke/azurerm-clustercreate-updown.yaml, integration-test/src/main/resources/testsuites/azurerm/smoke/azurerm-clustercreate.yaml, integration-test/src/main/resources/testsuites/gcp/kerberos/gcp-clustercreate-startstop-updown.yaml, integration-test/src/main/resources/testsuites/gcp/recipe/gcp-clustercreate-up.yaml, integration-test/src/main/resources/testsuites/gcp/smoke/gcp-clustercreate-startstop-updown.yaml, integration-test/src/main/resources/testsuites/gcp/smoke/gcp-clustercreate-startstop.yaml, integration-test/src/main/resources/testsuites/gcp/smoke/gcp-clustercreate-updown.yaml, integration-test/src/main/resources/testsuites/gcp/smoke/gcp-clustercreate.yaml, integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate-startstop-updown.yaml, integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate-startstop.yaml, integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate-updown.yaml, integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate.yaml, integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-startstop-updown.yaml, integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-startstop.yaml, integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-updown.yaml, integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate.yaml, integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate-startstop-updown.yaml, integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate-startstop.yaml, integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate-startstopX10.yaml, integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate-updown.yaml, integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate.yaml
@sodre90 pls review
Openstack integrationtest improvement to be able to run them on hwx jenkins:
- publicnetid can be application level parameter
- publicnetid can be empty
- default blueprint is empty in application.yml
=> openstack integrationtest fixes

core/src/main/resources/defaults/blueprints/hdp25-etl-edw-spark2.bp
The workaround that was applied with Ambari build 660 is not needed in 2.4.0.0-680 and above.
=> Removed Spark1 components, not needed with newer build of Ambari

core/src/main/resources/defaults/blueprints/hdp-spark-cluster.bp
Remove Zeppelin from 1.3 release as it's not supported in HDP 2.4.3.
=> removed zeppelin as it's not in hdp 2.4.3

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTestSuiteInitializer.java
=> CLOUD-56745 itest fix, networkid have to be string in context

autoscale/src/main/java/com/sequenceiq/periscope/service/security/ClusterSecurityService.java, web/app/static/js/controllers/periscopeController.js
@keyki @akanto 
Two fixes have been cherry picked for [issue](https://hortonworks.jira.com/browse/BUG-62364):
- autoscale is able to work on cluster with different user who created it (within the account)
- avoid alert duplication on autoscaling view
=> Autoscale user fix

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
@biharitomi @martonsereg @doktoric 
If you're launching a non-warmed up image on ARM, since we're installing Ambari on-the-fly it exceeds the 10 minutes threshold so I raised it to 15 minutes.
=> CLOUD-62537 increase poll timeout for ARM

cloud-aws/src/main/resources/definitions/aws-vm.json
Added support for c4 instance types, with following observations:
- C4 supports only EBS storage volumes - so set Ephemeral storage to 0.
- It supports General purpose SSD, Provisioned SSD and Magnetic - so set Throughput optimized HDD (st1) to 0. We don't seem to support Provisioned SSD (io1) - maybe for a reason, so didn't add it.
Verified that the new instance types show up in the template creation options in UI. Created a cluster with a template of C4 instances and saw that the instance was created properly. Please let me know if this looks fine.
=> CLOUD-50679 - Add support for c4 instance types in AWS

core-model/build.gradle, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/StopRestrictionReason.java, core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java, core-model/src/test/java/com/sequenceiq/cloudbreak/domain/StackTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterHostServiceTypeTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/DefaultStackHostServiceTypeTest.java
For the stop flow, added a check for instances being of type Spot and throwing a BadRequestException in that case. This is similar to how we check for ephemeral volumes before stopping.
Couple of things to call out:
- Have replaced the method Stack.isInfrastructuralEphemeral with Stack.isInfrastructureStoppable, primarily to just have one iteration on the instance groups. If this seems unclear, can retain the original method and add a new one and call both from callers.
- Have used the presence of spotPrice in the Template.attributes JSON to determine if this is a spot instance. Please let me know if this is assumption is ok, or should we do something better?
- This fix only adds backend checks. So, front-end will still show a stop button, but stop fails with an error message. I noticed …
=> CLOUD-63639: Added check for spot instances to disallow stop flow

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSetup.java
@doktoric 
This validation will run in the first phase of the stack creation flow, but only after the stack is already created in the db. It means that the cluster will appear on the UI, but it will fail instantly and the user will need to terminate it if they didn't opt-in to the marketplace product.
=> CLOUD-64834 validate marketplace opt-in

orchestrator-salt/src/main/resources/salt/salt/ambari/agent.sls, orchestrator-salt/src/main/resources/salt/salt/ambari/server.sls, orchestrator-salt/src/main/resources/salt/salt/ambari/upstart/ambari-agent.override, orchestrator-salt/src/main/resources/salt/salt/ambari/upstart/ambari-server.override, orchestrator-salt/src/main/resources/salt/salt/kernel/init.sls, orchestrator-salt/src/main/resources/salt/salt/top.sls
@schfeca75, @keyki 
Proper handling of upstart config to avoid concurrency between sysv and upstart. Code is also aligned with rh_service.py: https://github.com/saltstack/salt/blob/develop/salt/modules/rh_service.py
=> CLOUD-65291 Proper handling of upstart config to avoid concurrency

core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
Main issue was that TERMINATED instances were filtered out by instanceGroup.getInstanceMetaData()
=> CLOUD-EAR-4599 avoid duplicated privateids

Makefile, cloud-aws/src/main/resources/aws-images.yml, cloud-gcp/src/main/resources/gcp-images.yml, cloud-openstack/os-images.tmpl, cloud-openstack/src/main/resources/os-images.yml
Although this fix is not strictly related to HDC AWS, but our GCP tests are failing on this branch
=> CLOUD-EAR-4658 missing files from gcp images

core/src/main/resources/defaults/blueprints/hdp26-etl-edw-shared.bp, core/src/main/resources/defaults/blueprints/hdp26-etl-edw.bp
part of [RMP-8002] this PR adds a blue prints for 2.6 stack in order to include druid.
the new BP is a copy and past from 2.5 stack plus the druid spec/properties.
=> [RMP-8002] adding druid to the stack 2.6

cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/InstancePayload.java, cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/resource/RemoveInstanceRequest.java, cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/resource/RemoveInstanceResult.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/InstanceTerminationTriggerEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/AbstractInstanceTerminationAction.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationAction.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationContext.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationService.java
This enhancement allows multiple instances to be deleted in the backend InstanceTerminationFlow. The flow involves termination from the cloud provider and Ambari. Multiple instance termination from cloud provider is already supported in the API (due to downscale).
This enhancement will help in ongoing work to recover from multiple faulty slave nodes in the cluster. So, while there is no front end exposure to this capability right now, it will be used with development of that feature.
Could you please review this and let me know if it can be merged, or any other feedback to address.
=> CLOUD-68246: Allow deleting multiple instances in a stack in the backend

shell/src/main/java/com/sequenceiq/cloudbreak/shell/support/TableRenderer.java, shell/src/main/java/com/sequenceiq/cloudbreak/shell/transformer/OutputTransformer.java, shell/src/test/java/com/sequenceiq/cloudbreak/shell/transformer/OutputTransformerTest.java
`OutputTransformer.render` only checks the first value when deciding how to render the `map`.  If the first value happens to be `null`, the `else` branch is executed, resulting in the following exception:
```
java.lang.NullPointerException
at org.springframework.shell.support.table.Table.calculateColumnWidths(Table.java:85)
at com.sequenceiq.cloudbreak.shell.support.TableRenderer.format(TableRenderer.java:174)
at com.sequenceiq.cloudbreak.shell.support.TableRenderer.renderObjectValueMap(TableRenderer.java:120)
```
This may happen in real life eg. with the `network show` command:
```
cloudbreak-shell>network show --id 63
Command failed java.lang.RuntimeException
```
This particular network had `subnetCIDR=null`, which was the first item in the `HashMap` (at least on this JVM):
``` …
```
=> NPE in OutputTransformer.render if first value in map is null

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/view/ArmInstanceView.java
Reduce host name length on Azure in order to be sure that the fully qualified hostname is under 64 chars
The Azure-created DNS suffix cannot be modified as this document states:
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances
Unfortunately no any proper fix exist for this issue, since the fully qualified domain name has a fixed pattern:
```
<hostname>.<hash>.<network zone>.internal.cloudapp.net
where:
hash: is the id (hash) of an Azure virtual network, its 26 chars long
network zone: describes a network zone inside the specific Azure datacenter, where the VM is allocated, it is 2 chars long
```
https://blogs.msdn.microsoft.com/igorpag/2016/07/24/my-personal-azure-faq-on-azure-networking-and-arm/ …
=> CLOUD-69681 reduce host name length on Azure

shell/build.gradle
With Spring Shell 1.1.0 it is [not possible to get completion for a command that is a prefix of another command](https://jira.spring.io/browse/SHL-183).
Example:
```
cloudbreak-shell>network create --AWS --NEW --name asdf --sub[press TAB]
network create --AWS --NEW           network create --AWS --NEW_SUBNET
cloudbreak-shell>network create --AWS --NEW
```
This is [fixed in Spring Shell 1.2.0](https://github.com/spring-projects/spring-shell/commit/e693a7da9cfcc8fd7526c8f25dad4d8f4c8a916d):
```
cloudbreak-shell>network create --AWS --NEW --name asdf --sub[press TAB]
cloudbreak-shell>network create --AWS --NEW --name asdf --subnet
```
Similarly, detailed help is not available with 1.1.0 for prefix commands:
```
cloudbreak-shell>help 'network create --AWS --NEW'
* network create --AWS --NEW - …
```
=> Upgrade Spring Shell to 1.2.0.RELEASE

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java
`stack node --ADD` and `stack node --REMOVE` commands are available without selecting a stack first.  Of course they don't work:
```
Welcome to Cloudbreak Shell. For command and param completion press TAB, for assistance type 'hint'.
cloudbreak-shell>stack node --ADD --adjustment 1 --instanceGroup host_group_slave_1
Command failed java.lang.RuntimeException: null
```
With the fix:
```
Welcome to Cloudbreak Shell. For command and param completion press TAB, for assistance type 'hint'.
cloudbreak-shell>stack node --ADD --adjustment 1 --instanceGroup host_group_slave_1
Command 'stack node --ADD --adjustment 1 --instanceGroup host_group_slave_1' was found but is not currently available (type 'help' then ENTER to learn about this command)
cloudbreak-shell>stack select --id 1
Stack selected, …
```
=> Stack scale commands should not be available without selected stack

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java, shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/ClusterCommands.java, shell/src/main/java/com/sequenceiq/cloudbreak/shell/configuration/CommandDefinition.java, shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/common/ClusterCommandsTest.java
Add `--wait` option to the following commands:
* `stack node --ADD`
* `stack node --REMOVE`
* `cluster node --ADD`
* `cluster node --REMOVE`
Defaults to `false`, for consistency with other wait-enabled operations, and also for backwards compatibility.
This allows writing scripts involving multiple scaling operations without the need to wait outside of Cloudbreak Shell.
=> Optionally wait for stack/cluster up/downscale

orchestrator-salt/src/main/resources/salt/salt/ambari/agent.sls
=> CLOUD-71995 Extend SPARK_CLASSPATH with '/usr/lib/hadoop/lib/*' to work with gcs filesystem

core/src/main/resources/defaults/blueprints/hdp26-etl-edw-shared.bp
On ephemeral clusters that connect to shared services cluster,
1. Replaced ranger service with ranger plugin configuration
2. Exposed missing ldap confs for hadoop conf
Tested by replacing blueprinttext in blueprint table
=> CLOUD-72731 Enhance shared services blueprint for Ranger

core/src/main/resources/hdp/service-config.json
If HDP 2.6 is released we should consider using the fs.s3a.fast.upload option, because in that case it writes directly from memory to s3.
=> CLOUD-74238 set the s3a buffer dir to the attached disk

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnectorTest.java
For those who dare to look :-|
Problem:
Cloudbreak tries to figure out the subnet CIDR if it's not provided, by doing a describe-vpc to check which one is the first available. If you start multiple clusters at almost the same time with the same network setup there is a high chance that the same subnet CIDR will be determined for multiple clusters. This is because it takes some time to create the subnet on AWS to make it occupied. 
Fix:
Based on the cluster name we'll determine the first subnet CIDR to check if it's available or not. Multiple clusters with different names will start from a different point. Example:
VPC: 10.0.0.0/16
Cluster name: AA will start looking for subnet from 10.0.130.0/24 - 10.0.255.0/24
Cluster name: AB will start from 10.0.131.0/24  - 10.0.255.0/24
Cluster name: …
=> CLOUD-76934 reduce the likelihood of subnet cidr collision

autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/ScalingStatus.java, autoscale/src/main/java/com/sequenceiq/periscope/domain/History.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/ClusterMonitor.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ClusterCreationEvaluator.java, autoscale/src/main/java/com/sequenceiq/periscope/rest/controller/ClusterController.java, autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java, autoscale/src/main/java/com/sequenceiq/periscope/service/HistoryService.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/AutoscaleStackResponse.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToAutoscaleStackResponseJsonConverter.java
@keyki 
Changes:
- Enable autoscaling only if the cluster is in AVAILABLE state in Cloudbreak too
- Create history and notification when enabling and disabling autoscaling on a cluster
- usage of Inject annotation instead of Autowired
=> Enable autoscaling only if the cluster is in AVAILABLE state in Cloudbreak too

orchestrator-salt/src/main/resources/salt/salt/gateway/yum/hdp.repo
I don't think it ever worked on amazonlinux besides HDC. osmajorrelease returns 2016 or 2017 on amazonlinux. Also I'm not sure how it supposed to work on CB UI if I enable knox in the topology file there are no UI's exposed. I guess the UI just didn't send the required services to expose?
=> CLOUD-78236 use redhat6 repo on amazonlinux

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/HadoopConfigurationService.java
The following exception occurs when using the yarn orchestrator as the template is null within the instance group.
```
2017-04-25 13:19:52,432 [reactorDispatcher-66] buildAmbariCluster:329 ERROR c.s.c.s.c.f.AmbariClusterConnector - [owner:spring] [type:springLog] [id:] [name:] Error while building the Ambari cluster. Message null, throwable: {}
java.lang.NullPointerException: null
at com.sequenceiq.cloudbreak.service.cluster.HadoopConfigurationService.getHostGroupConfiguration(HadoopConfigurationService.java:123)
at com.sequenceiq.cloudbreak.service.cluster.flow.AmbariClusterConnector.addBlueprint(AmbariClusterConnector.java:750)
at com.sequenceiq.cloudbreak.service.cluster.flow.AmbariClusterConnector.buildAmbariCluster(AmbariClusterConnector.java:286)
at …
```
=> CLOUD-79673 Null check instance group templates for orchestrators

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java, core/src/main/resources/init/host/tls-setup.sh
also SCP server.pem directly from /etc/certs instead of copying it to /tmp
/tmp is still used elsewhere but I wanted to send this fix asap
=> CLOUD-85817 explicitly set permissions of private key

autoscale/build.gradle, core/build.gradle
Spring boot doesn't recive JVM arguments from Gradle. With this change can use bootRun tasks:
`./gradlew :autoscale:bootRun -PjvmArgs="-D... -D..."`
`./gradlew :core:bootRun -PjvmArgs="-D... -D..."`
=> CLOUD-56645 Pass JVM args to bootRun

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/MetricType.java, config/checkstyle/checkstyle-suppressions.xml, core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/AbstractAction.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/start/ClusterStartActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stop/ClusterStopActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/stop/StackStopActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationAction.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationFailureAction.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleActions.java, core/src/main/java/com/sequenceiq/cloudbreak/service/ha/HeartbeatService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/metrics/MetricService.java
org_springframework_metrics_response_value{type="gauge",value="api.v1.stacks.646",} 65.0
org_springframework_metrics_response_value{type="gauge",value="api.v1.stacks.645",} 113.0
org_springframework_metrics_response_value{type="gauge",value="api.v1.stacks.user",} 2008.0
org_springframework_metrics_response_value{type="gauge",value="api.v1.stacks.645.cluster",} 1631.0
org_springframework_metrics_response_value{type="gauge",value="api.v1.stacks.validate",} 53.0
org_springframework_metrics_response_value{type="gauge",value="api.v1.stacks.646.cluster",} 1448.0
org_springframework_boot_endpoint_sensitive{name="consulEndpoint",} 0.0
org_springframework_boot_endpoint_sensitive{name="infoEndpoint",} 0.0
org_springframework_boot_endpoint_sensitive{name="healthEndpoint",} 0.0 …
=> CLOUD-88948 implement basic metrics

core/src/main/resources/defaults/blueprints/hdp26-edw-analytics.bp
This won't fix BUG-89127 so I'm reverting it.
=> Revert "CLOUD-89127 EDW-Analytics: Apache Hive 2 LLAP cluster doesn't have th…"

core/build.gradle, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/template/BlueprintTemplateProcessor.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/BlueprintTemplateProcessorTest.java, core/src/test/resources/blueprints/bp-mustache-test.bp
@martonsereg and @doktoric please take a look
Changes:
- backport templating fix, change mustache java to handlebars
- adding expressions that could be occurred in exported blueprints to the test
- configure handlebar to avoid syntax error on exported blueprint's special expressions
- calculates and logs also the template processing time
=> Blueprint templating fix

autoscale/build.gradle, build.gradle, cloud-common/build.gradle, cloud-common/src/main/resources/application.yml, core/src/main/java/com/sequenceiq/cloudbreak/CloudbreakApplication.java
For some reason spring-cloud enabled the class proxying and if we remove it it will fall back to interface proxying and cannot inject services.
=> CLOUD-91578 remove spring consul and enable class proxying

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/AmbariStackDetailsResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterResponse.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/StackRepoDetailsToAmbariStackDetailsJsonConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterComponentConfigProvider.java
Sending back the stackdetails in the cluster response because that is missing previously.
RMP-9129
=> Display configured Ambari and HDP repos on cluster details

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Image.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/catalog/Image.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/StackRepoDetails.java, cloud-common/src/main/resources/application.yml, core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/AmbariStackDetailsJson.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ImageResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterCreationSetupService.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/ImagesToImagesResponseJsonConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToHDPRepoConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariServiceException.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterTemplateService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariRepositoryVersionService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java, core/src/test/java/com/sequenceiq/cloudbreak/domain/json/JsonTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnectorTest.java, gradle.properties, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockClusterCreationWithSaltSuccessTest.java
Backward compatible support of Ambari's repository version related API changes:
- In case of newer Ambari API from version 2.6.0.0 uses the VDF files to set repositories to be installed
- New "os-type" field integrated to the image catalog domain as it is available in our image catalogs
=> Backward compatible support of Ambari's repository version related API changes

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Group.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Network.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResources.java
Backend should return meaningful response for AWS networks and sec. group requests even if they are empty. E.g: {"eu-west-1":[]}
BUG-92769 should be fixed in UI for sec. groups to be usable in AWS
=> CLOUD-92453 Cluster fails when using existing security groups on AWS

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformResources.java
Backend should return meaningful response for Azure networks and sec. group requests even if they are empty. E.g: {"eu-west-1":[]}
=> CLOUD-92453 Cluster fails when using existing security groups on Azure

autoscale/src/main/java/com/sequenceiq/periscope/service/security/OwnerBasedPermissionEvaluator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/security/OwnerBasedPermissionEvaluator.java, core/src/test/java/com/sequenceiq/cloudbreak/conf/OwnerBasedPermissionEvaluatorTest.java
@mhmxs plz check
The hasPermission method shouldn't throw NotFoundException if targetDomainObject is null. The documentation of the interface' method: _the domain object for which permissions should be checked. May be null in which case implementations should return false, as the null condition can be checked explicitly in the expression_
This working could lead to information leakage because an attacker could use the API to identify existing credentials/resources.
Closes BUG-92881
=> CLOUD-92881 PermissionEvaluator shouldn't throw exception

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
With this fix I no longer get optimistic lock exceptions, but might be scenarios when we'll get LazyInitializationException (lets hope not :))
This PR prevents any users to get info about a stack that they dont have permission to.
=> do not open transaction to avoid optimistic lock exception

core/build.gradle
To get this feature working, one has to set "core:buildInfo" Gradle task as Before launch action in Idea Run Configurations.
=> CLOUD-87281 Unspecified version handling

cloud-common/src/main/resources/application.yml
First I was thinking of completely remove this feature since I was not able to reproduce the mysql hostname issue anymore, but after that, I decided to keep at least for the next release and if nobody complains then we can remove this config parameter.
=> DPAAS-180 increase default hostname length

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/KerberosRequest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/KerberosConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToClusterConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/kerberos/KerberosBlueprintService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/kerberos/KerberosDetailService.java, core/src/main/resources/schema/app/20180108121930_RMP-10343_Separate_kdc_server_and_admin_host.sql, gradle.properties, orchestrator-salt/src/main/resources/salt/salt/kerberos/config/krb5.conf-existing, orchestrator-salt/src/main/resources/salt/salt/kerberos/settings.sls
Previous version supported only one url for both kdc and admin server. Now it supports both separatly.
=> RMP-10343 Support Kerberos admin host

integration-test/it-application.yml, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockClusterCreationWithSaltSuccessTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockKerberizedClusterCreationTest.java, integration-test/src/main/resources/testsuites/mock/mock-kerberized-clustercreate-salt.yaml
@mhmxs the mock integration test has been extended with a new test run that tries to create a kerberized cluster and also validate:
- kerberos role was assigned in the salt orchestration
- Ambari cluster creation template contains the necessary kerberos related fields
=> CLOUD-10329 mock tests for kerberized cluster creation

core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterCreationSetupService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariRepositoryVersionService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariRepositoryVersionServiceTest.java
Please take a look after it's become green!
Fix for wrong Ambari API version checking that has been committed by @topolyai5 and broke all of the e2e tests on QA.
=> CLOUD-92223 fix Ambari version checking logic and tests

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToStackResponseConverter.java
The previous logic selected the mpack field from stack repo details and tried to parse the HDF version from there.
=> CLOUD-91823 fix hdp/hdf version in stack response

autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ClusterCreationEvaluator.java, autoscale/src/main/java/com/sequenceiq/periscope/rest/controller/ClusterController.java
PR is dedicated to avoid automatic switch on of autoscaling by recovery's poller mechanism and only create history entries when the cluster's status should be updated according to the request.
=> EAR-7655 avoid automatic enabling of autoscale by recovery functionality

core/src/main/java/com/sequenceiq/cloudbreak/controller/SmartSenseSubscriptionController.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/SmartSenseSubscriptionRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/smartsense/SmartSenseSubscriptionService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/smartsense/SmartSenseSubscriptionServiceTest.java
Fix the default subscription generation logic that fails due to the OwnerBasedPermissionEvaluator behavior had been changed and not throwing the NotFoundException anymore when the annotated repository calls return with null.
=> CLOUD-95729 fix default SmartSense subscription generator logic

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AwsCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AzureCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/GcpCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java
api e2e tests are caused null pointer exception when send a cluster request (v2) without availability zone in case of openstack - this commit would not close the original jira issue, only just enable the test's run
=> BUG-96599 api e2e test send availability zone in case of openstack

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/TestParameter.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java
-giving openstack cluster request floating pool attribute
-handling environment variable as property
=> BUG-96598 handling environment variable as property at new api tests

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePremiumValidatorService.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePremiumInstanceTest.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtilsTest.java
based on new azure documentation:
Premium Storage supports DS-series, DSv2-series, GS-series, Ls-series, Fs-series VMs. You can use standard and premium storage disks with these VM types. You cannot use premium storage disks with VM series that are not Premium Storage-compatible.
=> BUG-96777 premium storage validation

core/src/main/java/com/sequenceiq/cloudbreak/reactor/CollectDownscaleCandidatesHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/NotEnoughNodeException.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/AmbariDecommissioner.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackDownscaleValidatorService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariDecommissionerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackDownscaleValidatorServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackServiceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/instanceterm/MockInstanceTerminationTest.java
The user had the ability on the UI (with the little bin icon) to terminate that node which maintains the Ambari server what led to the total malfunction of the cluster. With this fix when the user tries to do the same operation, the UI brings up a warning message telling him/her that this operation is not allowed.
This bug recorded with the following ticket id: BUG-98907
=> BUG-98907 - fix to prevent the user from terminating the Ambari server node

cloud-common/src/main/resources/application.yml, core/src/main/resources/defaults/blueprints/hdf31-messaging-kafka.bp
Added blueprint for HDF31 Messaging management. It included kafka, zookeeper and ambari metrics. No additional changes were needed on cloudbreak side as blueprint just worked out of the box.
=> Added HDF31 Messaging management blueprint containing kafka

orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/OrchestratorBootstrapRunner.java
Added handling of thread interruption in OrchestratorBootstrapRunner before/during sleeping.
Closes #BUG-100796
=> BUG-100796 added handling of interrupted status of thread

blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/kerberos/KerberosBlueprintService.java, blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/kerberos/KerberosDetailService.java, blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/kerberos/KerberosDetailServiceTest.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/KerberosRequestToKerberosConfigConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
Fixes a bug when the user sends an empty value (or only spaces) as the kerberos admin host, and this empty and/or invalid data stored in the kerberos config file by the salt, which would cause malfunction
=> BUG-101237 – fix for sending empty kerberos admin host bug

orchestrator-salt/src/main/resources/salt/salt/consul/scripts/consul_cleanup.sh
Enhance Consul cleanup to force leave only nodes which are not alive or not left.
Issue:
For a cluster which performs lot of upscale/downscale, consul dead members can accumulate quickly.
For a Cluster which had more than 500 "left" consul member nodes,
Cloudbreak 2.4 started failing to add nodes to Ambari cluster as consul cleanup would not complete in ambari server -Consul cleanup was not completing within the 90 attempts that Cloudbreak would do to get the status of Consul cleanup.
Consul cleanup was attempting to perform force-leave on any member which is not alive.
Performing a force-leave on a node which has already left will not benefit consul/cloudbreak.
Fix:
Patched consul_cleanup to force leave only nodes which are not alive and not left.
This would make consul_cleanup to …
=> Force leave nodes which are (Not alive(1) and Not left(3))

cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackImageVerifier.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackSetup.java, cloud-openstack/src/test/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackImageVerifierTest.java
- fallback to V1 API added when V2 list images request fails in OpenStackImageVerifier
- OpenStackImageVerifier getStatus does not return nulls anymore
Closes #BUG-102296
=> BUG-102296 - fallback to V1 API added when V2 list images request fails

cloud-common/src/main/resources/application.yml, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpDiskResourceBuilder.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/AbstractStackCreationV2Test.java
Root volume size can be set in the create cluster request's template part for GCP too:
~~~~
"template": {
"parameters": {
"encrypted": false
},
"instanceType": "n1-standard-8",
"volumeType": "pd-standard",
"volumeCount": 1,
"volumeSize": 100,
"rootVolumeSize": 65
}
~~~~
Note: this feature is already implemented for AWS and Azure. 
For OpenStack, the root disc cannot be configured directly. The user must choose a flavor which satisfies her/his needs.
Closes #RMP-11135
Closes #BUG-101027
=> RMP-11135 root volume size configuration enabled for GCP

orchestrator-salt/src/main/resources/salt/salt/gateway/init.sls, orchestrator-salt/src/main/resources/salt/salt/gateway/repo.debian.sls, orchestrator-salt/src/main/resources/salt/salt/gateway/repo.sls, orchestrator-salt/src/main/resources/salt/salt/gateway/yum/scripts/extract-repo-url-from-vdf.sh
1. In case of gateway setup I split the repo.sls file in two, because the pkgrepo works in different ways based on OS type. (Further improvement could be to rename the yum directory to something OS independent. package-management)
2. Added a script which if the salt pillar property `hdp.stack.vdf-url` is provided, will download the vdf xml, parses out the 2 repository HDP and HDP-UTIL, using xpath. These values are stored in tmp files for the pkgrepo to use.
3. Common salt states were moved to the init.sls
=> BUG-102974 Added vdf xml parsing for package repositories

blueprint-manager/src/main/java/com/sequenceiq/cloudbreak/blueprint/template/views/GatewayView.java, blueprint-manager/src/main/resources/blueprints/configurations/atlas/gateway.handlebars, blueprint-manager/src/main/resources/blueprints/configurations/beacon/gateway.handlebars, blueprint-manager/src/main/resources/blueprints/configurations/ranger/gateway.handlebars, blueprint-manager/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/views/GatewayViewTest.java
Removed old code for escaping the cert. 
The certWithoutHeader is used in ranger, atlas, beacon handlebars.
=> BUG-102975 Gateway handlebars now will use the CertWithoutHeader

README.md, docs/common/retrieve_oauth_token.md, docs/spi.md
Most of the contents of [this site](https://hortonworks.github.io/cloudbreak-documentation/latest/dev/index.html) has moved to this repo to make its management easier
=> extended cloudbreak dev. documentations

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/RepositoryConfigValidationService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/RepositoryConfigValidationServiceTest.java
Fix the validation issue that appeared when the Ambari, Stack or HDP Utils repo base url was invalid, the new implementation supports the deb repositories for Ubuntu and Debian.
The validation always threw a warning when the Ambari/HDP version required the 1.1.0.21 version of HDP-UTILS.
=> BUG-104241 fix the validation of yum and deb repos availibility

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/listener/CheckedListener.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/listener/FirstLastTestExecutionBehaviour.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/listener/GatekeeperBehaviour.java
Listeners run for suite where they are defined.
Closes 104482
=> BUG-104482 custom listener to test suite

cloud-aws/src/main/resources/definitions/aws-vm.json
The i3 series comes with ephemeral disks. I added the meta data for that.
No testing provided as I'm not in the CloudBreak team nor a developer, so you'll need to test that these are the exact correct sizes.
=> add EPHEMERAL volumes to the EC2 i3 series

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/conf/AwsConfig.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/conf/AzureConfig.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/conf/GcpConfig.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/config/OpenStackConfig.java
BUG-104696 – fix for passing tag key with only space value which caused cluster creation failure
=> BUG-104696 – fix for passing tag key with only space value

core/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/ldapconfig/LdapConfigService.java
BUG-104769 – ldap warning now shows both name of ldap config – instead of ID – and the related cluster's name if user tries to delete it while it's still used in a cluster
=> BUG-104769 – ldap warning on delete now shows both ldap config name and related cluster's name

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl-user-facing.conf
Adding configuration changes to nginx to support websocket proxying
=> BUG-104109 websocket connection fails on cloudbreak launched cluster

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/conf/GcpConfig.java
BUG-105170 – fix for scenario when the user can't create a gcp cluster due to the misconfigured regex for the tag value which fails to check some autogenerated values such as the owner
=> BUG-105170 – fix misconfigured gcp tag value regex

core/src/main/java/com/sequenceiq/cloudbreak/converter/FileSystemRequestToFileSystemConverter.java
BUG-105203 – fix for the NullPointerException which comes when the user sends a CloudStorageRequest with a null (or missig, which is the same in this case) locations parameter. The exception has came from a conversion (between filesystemrequest and filesystem) when we did a foreach on this null 'value'. Now it checks for it's existence and the quantity of it's elements.
=> BUG-105203 – fix for NPE when there is no storage location in request

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/common/StackEndpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v1/StackV1Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v2/StackV2Endpoint.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCommonService.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/StackV1Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/StackV2Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/DownscaleFlowEventChainFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/ClusterAndStackDownscaleTriggerEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/ClusterDownscaleDetails.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/ClusterDownscaleTriggerEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/Msg.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/CollectDownscaleCandidatesHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/resource/CollectDownscaleCandidatesRequest.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/resource/DecommissionRequest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, core/src/main/resources/messages/messages.properties, core/src/test/java/com/sequenceiq/cloudbreak/core/flow/ReactorFlowManagerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/reactor/CollectDownscaleCandidatesHandlerTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/instanceterm/MockInstanceTerminationReplicationErrorTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/instanceterm/MockInstanceTerminationReplicationTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/instanceterm/MockInstanceTerminationTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/instanceterm/MockInstanceTerminationUnknownTest.java
- Added option to forcefully terminate an instance. (Skip ambari check)
- Added custom "forcefully terminated message" to events.
- Added unit integration test for flow.
Initial idea was to use a custom state for forcefully terminating an instance, but got pretty complicated pretty soon, so that's why I used the additional ClusterDownScale details.
=> BUG-104948 Added forced option to instance termination.

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ProxyHandler.java
BUG-105888 – NPE on proxy method invocation when null parameter passed
=> BUG-105888 – NPE on proxy method invocation when null parameter passed

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/ProxyHandler.java
log shows the called method's args only when it fails
=> log shows the called method's args only when it fails

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/catalog/CloudbreakVersion.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/catalog/Image.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/CachedImageCatalogProvider.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogVersionFilter.java, core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceDefaultNotFoundTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceDefaultTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogVersionFilterTest.java
- Added logging for image filtering with info level. Based on discussion logs should probably be debug logs,but we agreed on info. every log message start with: "Filtering images by " and lists what got filtered.
- Also did a little refactor on ImageCatalogService, and extracted version related filtering.
Unit tests for Version Filtering on the way.
=> BUG-105901 Better logging for ImageCatalog filtering.

core-api/src/main/java/com/sequenceiq/cloudbreak/validation/RDSConfigJsonValidator.java, core-api/src/test/java/com/sequenceiq/cloudbreak/validation/RDSConfigJsonValidatorTest.java
BUG-106346 – unable to create rds when a name contains hyphen
A user was unable to create an rds when the url contains a hyphen in the database's name which could easily happen in real life:
For example:
jdbc:postgresql://37.191.55.32:5432/my-db
or
jdbc:postgresql://37.191.55.32:5432/ranger-audit-db
=> BUG-106346 – unable to create rds when a name contains hyphen

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/OpenstackCloudProvider.java
If we start OpenStack tests with volumes there is a good chance we can not delete the stack.
Closes 106743
=> BUG-106743 volume count is 0 for openstack

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java, integration-test/src/main/resources/testsuites/clusterawstestset.yaml, integration-test/src/main/resources/testsuites/clusteropenstacktestset.yaml
Backport NodeCount in tests to CB 2.7
Closes BUG-106742
=> BUG-105325 instance count is modifiable in cluster tests

cloud-aws/src/main/resources/definitions/aws-vm.json
BUG-105997 max disk size changed to AWS allowed max of 16384
Updated all instance types with st1 disk parameters.
=> BUG-105997 AWS: updated instance types with storage st1

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRequestValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterRepository.java
**Description:**
Now the user can create an attached cluster (through direct API call) when the related datalake cluster has failed on creation which is undesirable because this cluster's creation would take several minutes but will fail unavoidably.
The API should validate that the desired shared cluster exists and it is available.
**Note for the commit:**
I did a double check so not just checking the stack's availability but it's cluster's status to be more sure about the readiness for attaching.
=> BUG-107235 – Prevent user from creating an attached cluster when the related datalake cluster has failed

integration-test/src/main/resources/testsuites/clusterawstestset.yaml, integration-test/src/main/resources/testsuites/clusteropenstacktestset.yaml
Run end to end test on parallel with thread count 10.
Closes 107662
=> BUG-107662 update e2e api tests thread count to higher

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/users/OrganizationResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/v2/OrganizationStatus.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/security/Organization.java, core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/OrganizationController.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/users/OrganizationRequestToOrganizationConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/users/OrganizationToOrganizationResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/generator/OfflineStateGenerator.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/security/OrganizationRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/organization/OrganizationDeleteVerifierService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/organization/OrganizationService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserService.java, core/src/main/resources/schema/app/20180802114825_BUG-108486_Improve_org_delete_experience.sql, core/src/test/java/com/sequenceiq/cloudbreak/service/organization/OrganizationDeleteVerifierServiceTest.java
This pr fixing BUG-108486:
- you can not delete the default org
- you can not delete org when it has cluster
- migration script for adding org status and termination date
- namedquery modifications based on active org
=> BUG-108486 Improve org delete experience

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackServiceTest.java
BUG-108475 – NullPointerException when termination was triggered on non-existing cluster name
=> BUG-108475 – NullPointerException when termination was triggered on non-existing cluster name

core/src/main/java/com/sequenceiq/cloudbreak/converter/CredentialToCredentialResponseConverter.java
BUG-109912 – Cannot edit AWS credential
changing those values to Boolean type in the parameters which has to be that type (instead of String), to help the UI to identify whether the credential is in a AWS GovCloud or not.
=> BUG-109912 – Cannot edit AWS credential

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java
The fix has been tested with:
- new cluster creation
- cluster upscale
- Datalake HA "gateway" instance group's manual recovery
=> BUG-110246 prevent marking more instances as Ambari server

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AwsCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/CloudProviderHelper.java, integration-test/src/main/resources/application.yml
until ambari 2.7.1 is not released, we can use custom ambari repo for hdf aws base image tests
=> BUG-111255 [E2E] Can't create hdf flow management on AWS

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/annotations/IgnorePojoValidation.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/annotations/MutuallyExclusiveNotNull.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/stack/cluster/ClusterRepairNodeRequest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/stack/cluster/ClusterRepairRequest.java, core-api/src/test/java/com/sequenceiq/cloudbreak/api/model/annotations/MutuallyExclusiveNotNullValidatorTest.java, core-api/src/test/java/com/sequenceiq/cloudbreak/utils/ModelTest.java
As the repair request can be used for 1. host group repair 2. individual node repair but these 2 lists are mutually exclusive, the validation had to be altered.
Also, made the node ID list mandatory, e.g. not null and not emtpy.
Added test cases for the validator.
=> BUG-112926 Add mutually exclusive non-null check to repair request

docs/spi.md
The header titles were missing a space after the `#` marks.
=> Fix markdown for SPI documentation

integration-test/scripts/check-results.sh
check-result.sh was updated. Not the same reporting system was used for new integration testcases, and failures were only found if there were skipped testcases aswell, which are rare in case of new testcases. 
As a first stage this PR should fail with KerberosTest and Circle report should be in line with the test results.
=> Fix failure detection for circleCI

core-api/src/main/java/com/sequenceiq/cloudbreak/client/RestClientUtil.java
Should not have a performance impact, since the rest logging is off by default except if somebody sets -Drest.debug
=> BUG-115283 increase log level when rest debugging is enabled.

template-manager-blueprint/src/main/resources/definitions/cloud-storage-location-specification.json, template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/filesystem/query/FileSystemConfigQueryServiceTest.java
Initial installment of Cloudbreak UI settings for additional cloud storage locations. At the moment, the following services are covered:
- YARN NM app logs
- YARN ATS
- SHS
- AMS
More changes are expected to come. In particular:
- Locations for LogSearch and Zeppelin are still missing
- `requiredForAttachedCluster` and `relatedService` settings need to be double-checked
- Extra `clusterName` suffix might need to be removed in certain cases
- Better wording for descriptions or more appropriate paths
Open issues (to be covered in a separate PR):
- Adding location inheritance to Cloudbreak (attached WL inheriting certain locations from the DL)
- Finetuning `defaultPath` expansion so that it does not necessarily contain any clusterName (or if it does, it contains the name of the DL in case of …
=> Bug 114428 configure additional cloud storage locations during dl setup   step 1

structuredevent-model/build.gradle
-We plan to reuse structured event models for Spark queries, sadly Smartsense datalake is running on java 8, so we enforce source+target compatibility in gradle.
- Verified bytecode with `javap -verbose` and returned
major version: 52
=> RMP-12797 setting source and target compatibility for structuredevents

template-manager-blueprint/src/main/resources/blueprints/configurations/metrics_monitor/services.json, template-manager-blueprint/src/main/resources/blueprints/configurations/metrics_monitor/shared_service.handlebars, template-manager-blueprint/src/main/resources/blueprints/configurations/yarn_client/services.json, template-manager-blueprint/src/main/resources/blueprints/configurations/yarn_client/shared_service.handlebars, template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/BlueprintSegmentReaderTest.java, template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/HandlebarTemplateTest.java, template-manager-blueprint/src/test/resources/handlebar/configurations/metrics_monitor/metrics-monitor.json, template-manager-blueprint/src/test/resources/handlebar/configurations/yarn_client/yarn-client.json
RMP-12456 : Wire Up WL Cluster to send metrics to DL
- Configured Blueprint Shared Services template to wire up METRICS_MONITOR and YARN_CLIENT in WL Clusters.
=> RMP-12456 : Wire Up WL Cluster to send metrics to DL

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/CloudbreakClusterTestConfiguration.java
Get all blueprints for workspace before cluster tests in order to insert blueprints in a fresh db
Closes BUG-114664
Closes BUG-98037
=> BUG-114664 get all blueprints before cluster tests

template-manager-blueprint/src/main/resources/blueprints/configurations/yarn_client/shared_service.handlebars, template-manager-blueprint/src/test/resources/handlebar/configurations/yarn_client/yarn-client.json
Changes to fix below issues.
BUG-115806 : Yarn log server URL wiring is missing the protocol
BUG-114296 : CloudBreak needs to configure a unique cluster Id for each workload cluster
Closes #BUG-115806
Closes #BUG-114296
=> BUG-115806 Yarn log server URL and BUG-114296  CloudBreak needs to configure a unique cluster Id 

integration-test/src/main/resources/testsuites/clusterawstestset.yaml
add back aws hdp3 tests (base and prewarm)
Closes BUG-109353
=> BUG-109353 Re-enable HDP 3.0 tests

template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/kerberos/KerberosBlueprintService.java, template-manager-blueprint/src/test/resources/blueprints-jackson/bp-kerberized-test.bp, template-manager-blueprint/src/test/resources/blueprints-jackson/bp-not-kerberized-existing-expected.bp, template-manager-blueprint/src/test/resources/module-test/outputs/kerberos.bp
Tested this on a local deploy. The auth_to_local rules are generated properly with the change.
=> BUG-116076 Set additional kerberos-env configs to generate auth_to_local

cloud-common/src/main/resources/application.yml, core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/SharedServiceConfigProvider.java, template-manager-blueprint/src/main/resources/blueprints/configurations/hive_server/shared_service.handlebars, template-manager-blueprint/src/main/resources/blueprints/configurations/hive_server_interactive/shared_service.handlebars, template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/HandlebarTemplateTest.java, template-manager-blueprint/src/test/resources/handlebar/configurations/hive_server/shared-service-atlas-attached.json, template-manager-blueprint/src/test/resources/handlebar/configurations/hive_server/shared-service-attached.json, template-manager-blueprint/src/test/resources/handlebar/configurations/hive_server_interactive/shared-service-atlas-attached.json, template-manager-blueprint/src/test/resources/handlebar/configurations/hive_server_interactive/shared-service-attached.json
Tested via a local deployment. Also noticed that CB seems to pick up DL properties from it's DB, rather than querying the DL cluster. Creating an improvement request for that.
=> BUG-115160. Set additional Atlas settings when attaching to a kerberized cluser. BUG-115662. Enable ranger audit logging to solr

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/task/AwsInstanceTerminatedStatusCheckerTask.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/task/AwsPollTaskFactory.java
Sometimes instance termination takes a very long time on AWS. Cloudbreak before stepped to the next flow step right after it sent the termination request to AWS. In the event of slow instance termination, flow execution reached the disk reattach step, but the disks were still attached to the instance under termination, which caused an error.
Implemented a poller, which waits for the instance to be terminated, before moving forward. The downside of this, is it makes flows, which include instance termination slower, depending on AWS performance.
=> BUG-116567 Wait for instances to be terminated

cloud-common/src/main/resources/application.yml
HDP & Ambari versions are increased to use new hdp3 blueprints
HDP 3.0.100.0-171
Ambari 2.7.100.0-255
Closes 116321
=> BUG-116321 adjust Ambari and HDP versions in order to use blueprints

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTests.java
HDF kerberos test is failing due to test could not check ambari availability with default credentials
Closes 116615
=> BUG-116615 Kerberos e2e test can't check ambari availability

template-manager-blueprint/src/main/resources/blueprints/configurations/kafka_broker/shared_service.handlebars, template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/HandlebarTemplateTest.java, template-manager-blueprint/src/test/resources/handlebar/configurations/kafka_broker/shared-service-attached.json
Initialize ranger properties while attaching Kafka cluster to Ranger in DL.
Closes #BUG-115743
=> BUG-115743: Set properties while attaching kafka cluster to Ranger in DL

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterTests.java, integration-test/src/main/resources/testsuites/clusterawstestset.yaml
E2e tests could not check ambari status without credential for the kerberized cluster
Closes 116668
=> BUG-116668 e2e test can't check ambari when cluster is kerberized

integration-test/src/main/resources/testsuites/clusterawstestset.yaml, integration-test/src/main/resources/testsuites/clusterazuretestset.yaml, integration-test/src/main/resources/testsuites/clustergcptestset.yaml, integration-test/src/main/resources/testsuites/clusteropenstacktestset.yaml, integration-test/src/main/resources/testsuites/clusterostestset.yaml, integration-test/src/main/resources/testsuites/clusterrecoverytestset.yaml, integration-test/src/main/resources/testsuites/clustertest-azure-abfs.yaml, integration-test/src/main/resources/testsuites/credentialmodifyclustertests.yaml
fixing blueprint names - some tests have been using older blueprints.
Closes 116785
=> BUG-116785 fix blueprints

.gitignore
Different 3rd parties for bash are supporting to load environment variables per directory, and all of them are support `.env` file. Would be nice to ignore them.
=> BUG-105449 Git ignore .env file

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/StructuredEventFilter.java, core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/StructuredEventFilterTest.java
When trying to parse resourceId from non JSON responses like BadRequestResponses various Exception have appeared in logsearch.
- com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input in field name
- com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'createInWorkspace': was expecting ('true', 'false' or 'null')
- now we'll log cases when there is a valid JSON but without an ID. Also in those cases we does not provide RESOURCE_ID as emptyString
=> BUG-115316 handle plain text responses with no warning

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java, integration-test/src/main/resources/application.yml
Merge removed pollingIntervall from application.yml (integration-test)
Closes 116969
=> BUG-116969 after merge 2.9tests are failing

web/Dockerfile
Upgrade NodeJS and NPM version to avoid the following syntax error in Uluwatu:
```/uluwatu/node_modules/express/node_modules/debug/src/node.js:120
exports.inspectOpts = Object.keys(process.env).filter(key => {
^
SyntaxError: Unexpected token >
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/uluwatu/node_modules/express/node_modules/debug/src/index.js:9:19)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)```
=> upgrade NodeJS to avoid syntax error in web container

auth/Dockerfile
Fix to avoid SyntaxError in Sultans:
```
sultans/node_modules/request/node_modules/tough-cookie/node_modules/ip-regex/index.js:3
const word = '[a-fA-F\\d:]';
^^^^^
SyntaxError: Use of const in strict mode.
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/sultans/node_modules/request/node_modules/tough-cookie/lib/cookie.js:34:15)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
```
=> upgrade NodeJS to avoid syntax error in sultans

config/checkstyle/checkstyle-suppressions.xml, integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/config/SparkServer.java
- wait with timeout and logs for waiting spark service to shutdown. 
- if spark can't be released, port won't be freed up. 
- Threads should be taken care by `System.exit()`  at the end of SpringApp run.
=> await with 30 second timeout for spark service shutdown

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/OrchestratorRecipeExecutor.java
These 2 lines were excluded during the cherry pick resulting in persisting null's to the databases, when a cluster was launched with recipes. The issue was only visible on the UI once the recipes got generated. sodre's PR only fixed the View part.
Sadly we can't remove that fix for now, as these are alredy persisted to the database. 
Effect is probably the recipes didn't run at all.
=> BUG-117886 generated recipes are not saved

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/ClouderaManagerRepo.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/AmbariDefaultStackRepoDetails.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/ClouderaManagerDefaultStackRepoDetails.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/DefaultCDHEntries.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/DefaultCDHInfo.java, cloud-common/src/main/resources/application.yml, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/responses/AmbariStackRepoDetailsV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/responses/ClouderaManagerStackRepoDetailsV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/responses/StackDetailsV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/cluster/clouderamanager/ClouderaManagerRepositoryV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/responses/AmbariStackDescriptorV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/responses/ClouderaManagerInfoV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/responses/ClouderaManagerStackDescriptorV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/responses/StackMatrixV4Response.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/imagecatalog/ImagesToImagesV4ResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/clouderamanager/RepoDetailsToClouderaManagerRepositoryV4ResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/clouderamanager/RepositoryInfoToClouderaManagerInfoV4ResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/clouderamanager/StackInfoToClouderaManagerStackDescriptorV4ResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/gateway/StackInfoToAmbariStackDescriptorV4ResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCreationSetupService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/DefaultAmbariRepoService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/DefaultClouderaManagerRepoService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/StackMatrixService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/ClusterCreationSetupServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/DefaultAmbariRepoServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/DefaultClouderaManagerRepoServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/StackMatrixServiceTest.java
The stack matrix response is extended with the following section:
```
"cdh": {
"6.1.0": {
"version": "6.1.0-1.cdh6.1.0.p0.770702",
"minCM": "6.1",
"repository": {
"stack": {
"repoid": "CDH",
"redhat7": "https://archive.cloudera.com/cdh6/{latest_supported}/parcels/"
}
},
"clouderaManager": {
"version": "6.1.0",
"repository": {
"redhat7": {
"baseUrl": "https://archive.cloudera.com/cm6/6.1.0/redhat7/yum/",
"gpgKeyUrl": "https://archive.cloudera.com/cm6/6.1.0/redhat7/yum/RPM-GPG-KEY-cloudera"
}
}
}
}
}
```
The actual values are not in use on the backend as the repo info is part of the cluster definition which we will need to extend. This is the min requirement to make the CM work with the stack matrix.
=> CB-574 support CM anc CDH in stack matrix

cloud-common/src/main/resources/application.yml, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackV4RequestValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/init/clusterdefinition/ClusterDefinitionLoaderService.java, core/src/main/java/com/sequenceiq/cloudbreak/init/clusterdefinition/DefaulClusterDefinitionCache.java, core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/StackDecorator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/SharedServiceValidator.java, core/src/main/resources/defaults/blueprints/cdh6-shared-services.bp, core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackV4RequestValidatorTest.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/init/clusterdefinition/DefaulClusterDefinitionCacheTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/clusterdefinition/ClusterDefinitionLoaderServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/SharedServiceValidatorTest.java
This PR allows to launch a CDH based simple data lake with a default template (HMS) (which contains more services than it should, but this can be polished later). It also allows to attach a simple WL cluster by connecting the HMS databases. No Ldap, Kerberos, Cloud storage support. Also in case of CM there is no data lake resource collection (basically we do not collect any config from CM, but we might never need to if the shared data context will be implemented).
=> CB-150 add default CM DL template with HMS

cloud-common/src/main/java/com/sequenceiq/cloudbreak/json/ValidationResult.java, cloud-common/src/test/java/com/sequenceiq/cloudbreak/json/ValidationResultTest.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/mapper/ConstraintViolationExceptionMapper.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/mock/ClusterTemplateTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/mock/CredentialTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/mock/DatabaseTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/mock/ImageCatalogTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/mock/KubernetesTest.java
The core ConstraintViolationExceptionMapper class was returning a plain
string as a response, but to be valid for JSON-producing endpoints, it
should return JSON. It now does, in a manner identical to the same
mapper in periscope.
=> CB-438 Send JSON response for constraint violations

core/src/test/java/com/sequenceiq/cloudbreak/converter/InstanceTemplateV4RequestToTemplateConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverterTest.java
This PR adds tests when we convert the requests to entities and entities to dtos. Gcp side of the encryption is already covered: https://github.com/hortonworks/cloudbreak/blob/master/cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java#L326-L358
=> CB-484 unit tests for gcp/aws encryption

orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/init.sls
In the following command `>=2.5.4` is treated as output redirection instead of the intended version constraint for `pip`:
https://github.com/hortonworks/cloudbreak/blob/98c5c269d2a14122f616326d8d969a9d0bde5a43/orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/init.sls#L11
The result:
```
$ cat /root/\=2.5.4
Collecting psycopg2
Downloading https://files.pythonhosted.org/packages/51/89/7490c48abf2ea89b65140c3c77023f7ea623031389a8e0cd0788c1625b06/psycopg2-2.7.7-cp27-cp27mu-manylinux1_x86_64.whl (2.7MB)
Installing collected packages: psycopg2
Found existing installation: psycopg2 2.5.1
Uninstalling psycopg2-2.5.1:
Successfully uninstalled psycopg2-2.5.1
Successfully installed psycopg2-2.7.7
```
Ran `pip install --upgrade "psycopg2>=2.5.4"` manually to verify that `pip` gets the …
=> avoid output redirection for pip install

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/clusterdefinition/ClusterDefinitionV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/clusterdefinition/responses/ClusterDefinitionV4Responses.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ClusterDefinitionV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/service/AbstractWorkspaceAwareResourceService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/workspace/WorkspaceAwareResourceService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/AbstractWorkspaceAwareResourceServiceTest.java
WorkspaceAwareResourceService and its abstract implementation now
support deleting multiple resources at a time. Resources, or the names
of them, are provided in sets, so deletion order is not specified.
A new unit test for AbstractWorkspaceAwareResourceService tests out
the delete and multi-delete methods.
The v4 cluster definition API is updated to make use of this new support
and features a new endpoint for deleting multiple cluster definitions at
once. The endpoint is called with a DELETE HTTP method, and the body of
the method is a JSON list of the names of the cluster definitions to
delete.
=> CB-28 Define multi-delete API for cluster defs

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/recipes/RecipeV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/recipes/responses/RecipeViewV4Responses.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/RecipesV4Controller.java
The v4 recipe API is updated with a new endpoint for deleting multiple
recipes at once. The endpoint is called with a DELETE HTTP method, and
the body of the method is a JSON list of the names of the recipes to
delete.
The existing RecipeV4Responses class is reworked to store a collection
of RecipeV4Response objects, and the new RecipeViewV4Responses class
takes its place.
=> CB-29 Implement multi-delete API for recipes

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow2Handler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/flowlog/FlowLogService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/Flow2HandlerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/flowlog/FlowLogServiceTest.java
The IMAGE_CHECK_STATE is a repeatable event. For every repetition the flow handler created a new flow log entry with the same nextState value. This prevented postgres to make use of indexes on the table because of the multiple identical records.
From now on, the flow handler will check if the last flow log has the same state as the next one, and if it does, then it will only update its payload and variable columns.
=> CB-722 Prevent creating multiple flow logs for the same state

integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/wait/WaitUtilForMultipleStatuses.java
- disabling parallel execution for integration tests
- increasing timeout for e2e tests
=> int test and e2e test fixes

README.md
Additions have been made to the README.md to clarify some things
necessary specific to Linux development.
Note: This is pretty minor -- a lot of the changes made recently have made it nicer to work on Linux, since the Mac experience and the Linux experience are closer together.
=> CB-688. README additions for Linux development.

README.md
The most recent version of cbd now properly maps the database to
localhost instead of the Docker bridge, so this caveat is no longer
necessary.
=> CB-688. Remove references to docker bridge IP address from README.md.

cloud-common/src/main/resources/application.yml
Reverts hortonworks/cloudbreak#4751 because blueprints are not working
=> Revert "CB-770 - fixed ambari version"

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/projection/AutoscaleStack.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/stack/AutoscaleStackToAutoscaleStackResponseJsonConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/generator/OfflineStateGenerator.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/GatewayConfigService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackServiceTest.java
Hibernate was slow to hydrate entities. Simplified the query to select only the necessary columns and records and created a projection interface for ease of use.
=> CB-723 Simplify get stacks for autoscale query

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, cloud-common/src/main/java/com/sequenceiq/cloudbreak/cache/common/UmsUserCache.java
- remote UMS was slow, user should be cacheable.
- same as caas user before
=> CB-716 make Ums user cacheable

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/CrnTokenExtractor.java, auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/CrnTokenExtractorTest.java
- in some versions of DPS gateway there was an email address in the CRN header, we don't want to extract that
=> CB-716 make sure only extract valid CRN from CRN header.

cluster-ambari/src/main/java/com/sequenceiq/cloudbreak/ambari/AmbariClusterModificationService.java
Fix NPE, which occurs at `AmbariClusterModificationService#getStatus` during cluster sync.
=> NPE at AmbariClusterModificationService.getStatus

.circleci/config.yml
CircleCI `unit-test` tries to upload coverage to Code Climate.
https://github.com/hortonworks/cloudbreak/blob/41f5c96f5e9f9832f2fc7baf3f81902ae638056e/.circleci/config.yml#L149-L152
For PRs opened from forks this results in the following error due to empty `CC_TEST_REPORTER_ID`:
```
./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
Error: flag needs an argument: 'r' in -r
```
=> Skip upload to Code Climate for forked PRs

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudInstance.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudVmInstanceStatus.java, cloud-cumulus-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/cumulus/yarn/CumulusYarnInstanceConnector.java, cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/InstanceStateHandler.java, cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/InstanceStateHandlerTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java
Mark instance state as `UNKNOWN` if a cloud provider does not support instance state check, instead of failing the whole flow chain.  The goal is to allow the chain to proceed to cluster manager sync.
Tested sync on a cluster deployed to Yarn.  CB synced with Ambari fine after reporting that it couldn't sync with some instances.  Tested both with Ambari running and stopped.
=> [CB-997] Cluster sync prevented by unsupported instance sync

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/e2e/openstack/OpenStackTests.java
CB-945 – OpenStackTests dataprovider reusing same TestContext for multiple tests
=> CB-945 – OpenStackTests dataprovider reusing same TestContext for multiple tests

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/clustertemplate/ClusterTemplateV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/clustertemplate/responses/ClusterTemplateV4Responses.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/credentials/CredentialV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/database/DatabaseV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/kerberos/KerberosConfigV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/kerberos/responses/KerberosV4Responses.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/kubernetes/KubernetesV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/ldaps/LdapConfigV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/mpacks/ManagementPackV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/proxies/ProxyV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ClusterTemplateV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/CredentialV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/DatabaseV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/KerberosConfigV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/KubernetesV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/LdapV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ManagementPackV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ProxyV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
Credentials, image catalog, Kerberos configurations, Kubernetes
configurations, proxy configurations, cluster templates, authentication,
database configurations, and management packs all have the ability to
delete multiple resources.
Note: I verified that the new endpoints show up in swagger.json, but I need to work on testing them more thoroughly.
=> CB-750. Multiple deletion for various resources.

cluster-ambari/src/main/java/com/sequenceiq/cloudbreak/ambari/AmbariAdapter.java, cluster-ambari/src/main/java/com/sequenceiq/cloudbreak/ambari/AmbariClusterModificationService.java, cluster-ambari/src/main/java/com/sequenceiq/cloudbreak/ambari/AmbariClusterSetupService.java, cluster-ambari/src/main/java/com/sequenceiq/cloudbreak/ambari/AmbariClusterStatusFactory.java, cluster-ambari/src/main/java/com/sequenceiq/cloudbreak/ambari/status/AmbariClusterStatusService.java, cluster-ambari/src/test/java/com/sequenceiq/cloudbreak/ambari/AmbariAdapterTest.java, cluster-ambari/src/test/java/com/sequenceiq/cloudbreak/ambari/status/AmbariClusterStatusFactoryTest.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterStatusService.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/status/ClusterStatus.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/status/ClusterStatusResult.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/ClouderaManagerClientFactory.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusServiceTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/status/ClusterStatusUpdater.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/repair/CandidateUnhealthyInstanceSelector.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/status/ClusterStatusUpdaterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/repair/CandidateUnhealthyInstancesSelectorTest.java
Implement cluster sync for Cloudera Manager:
* cluster status calculation based on service and role state
* host status based on the host health check `HOST_SCM_HEALTH`
Notable changes:
* Move the method `getStatus` from `ClusterModificationService` to `ClusterStatusService`
* Eliminate mutable state (`statusReasonArg`) from the `enum ClusterStatus` by reusing `ClusterStatusResult` for this purpose (moved to `cluster-api`)
* Refactor stream processing in `CandidateUnhealthyInstanceSelector` (trying to avoid mutating external state in `foreach`)
Note:
* Health checks apparently require Cloudera Management Service
* `CandidateUnhealthyInstanceSelector` has Ambari-specific status code that will need to account for corresponding status from CM
Tested "sync" on CDH cluster after install …
=> [CB-984] Sync CM with CB

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ClusterTemplateV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/service/template/ClusterTemplateService.java
The multi-delete code for cluster templates now also deletes the stack
temmplate resident inside each template, to avoid API conversion
problems later.
=> CB-1168 Fix cluster template multi-delete

template-manager-blueprint/src/main/resources/definitions/cloud-storage-location-specification.json
Cloud storage location property hive.metastore.warehouse.external.dir was duplicated in generated blueprint
Closes CB-1169
=> CB-1169 hive.metastore.warehouse.external.dir was duplicated

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/filesystem/FileSystemType.java
When cluster is configured to use cloud storage on Azure, ADSL gen2 location was incorrect. dfs.core.windows.net instead of blob.core.windows.net
Closes CB-1169
=> CB-1169 Hive metastore storage location is invalid for ADLS gen2

build.gradle, orchestrator-salt/src/main/resources/salt/pillar/top.sls, orchestrator-salt/src/main/resources/salt/salt/sssd/ipa-leave.sls, orchestrator-salt/src/main/resources/salt/salt/sssd/settings.sls, orchestrator-salt/src/main/resources/salt/salt/sssd/template/generate_cm_keytab.j2, orchestrator-salt/src/main/resources/salt/salt/sssd/template/remove_cm_sa.j2
CB needs to generate a keytab for CM so CM can create the principals for the different services. However, using the same global service account makes the already generated keytabs invalid. To avoid such errors we need to generate a SA per cluster and once the cluster is terminated remove the corresponding SA as well from IPA.
=> CB-1193 generate IPA service account per cluster

cloud-aws/src/main/resources/definitions/aws-zone-coordinates.json, cloud-azure/src/main/resources/definitions/azure-zone-coordinates.json, cloud-cumulus-yarn/src/main/resources/definitions/cumulus-yarn-zone-coordinates.json, cloud-mock/src/main/resources/definitions/mock-zone-coordinates.json, cloud-openstack/src/main/resources/definitions/openstack-zone-coordinates.json, cloud-yarn/src/main/resources/definitions/yarn-zone-coordinates.json
Fix the location of some US West zones:
* Oregon: [old](https://www.openstreetmap.org/#map=8/43.676/-70.249) -> [new](https://www.openstreetmap.org/#map=8/45.543/-122.654)
* Washington: [old](https://www.openstreetmap.org/#map=7/38.891/-77.014) -> [new](https://www.openstreetmap.org/#map=7/47.608/-122.342)
=> CB-1272. Wrong location for some US West zones

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityService.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/cluster/ClusterV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ClusterToClusterV4ResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ClusterV4RequestToClusterConverter.java
Create a shared CM management user. I didn't rename the Entity fields, just the Response fileds, because in DB we still save all user/pass entries under cloudbreakAmbariUser etc..
=> CB-1286 create CM management user for shared access

core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/instance/InstanceMetaDataToInstanceMetaDataJsonConverterTest.java, template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/TemplateProcessorTest.java, template-manager-blueprint/src/test/resources/blueprints-jackson/bp-mustache-test.bp, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java, template-manager-cmtemplate/src/test/resources/input/clouderamanager-fixparam.bp, template-manager-cmtemplate/src/test/resources/output/clouderamanager-fixparam.bp, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/FormatJoinHelper.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/HandleBarModelKey.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/HandlebarUtils.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplateModelContextBuilder.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplateProcessor.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/HostgroupView.java, template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/FormatJoinHelperTest.java
Introduce support for generic host group substitution in Cloudbreak templates.
1. Hosts that belong to a host group are available using `{{{ host_group.<host_group> }}}`.  For example `{{{ host_group.master }}}` is replaced with `master1,master2` if this host group contains the hosts `master1` and `master2`.
2. To accomodate the need to add some protocol and port for each host, a new custom Handlebars.java helper is implemented.  For example
```
{{{format-join host_group.master format="thrift://%s:9083"}}}
```
is replaced with
```
thrift://master1:9083,thrift://master2:9083
```
Separator can be changed, too, but defaults to `,`.
Adjusted existing unit tests for template processing, and added a new one for the custom helper.
=> [CB-1321] Support host group substitution

redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/DatabaseServerV4Endpoint.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/base/DatabaseServerV4Base.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/DatabaseServerV4Request.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/responses/DatabaseServerV4Response.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java, redbeams-model/src/main/java/com/sequenceiq/redbeams/domain/DatabaseServerConfig.java, redbeams-model/src/test/java/com/sequenceiq/redbeams/domain/DatabaseServerConfigTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/repository/DatabaseServerConfigRepository.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/main/resources/schema/app/20190508131601_CB-1174_database_server_config_env.sql
A database server entity in redbeams is now associated with one or more
environment IDs. The list API is connected up properly so that the
environment ID query parameter matters.
Other useful changes:
- The query for finding all database server entities is expanded to
include the environment ID as a criterion. The query is not fully tested
yet to see what happens if no environment ID is specified.
- The database vendor property for database server API models is
refactored into the base model class.
- The databaseserverconfig table gets a new constraint pertaining to
archiving.
- Many commented-out lines, left tentatively in place, are cleaned up.
(There are still plenty more in redbeams to dispose of later.)
=> CB-1174 Add environments to database servers, and more

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLicenseService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtSetupService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/ClouderaManagerClientFactory.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapServiceTest.java
CM/CDH cluster creation fails in certain test environments due to using test license.  The change here is to start the trial period if Management Service is being setup.  The logic is extracted from LDAP setup service.
Tested actual cluster deployment.  Also tested that duplicate "begin trial" requests are handled (to account for multiple independent services that require the trial).
=> CB-1353. Need trial license for Management Service

orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/init.sls, orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/start.sls, orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls, orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/start.sls, orchestrator-salt/src/main/resources/salt/salt/top.sls
Extract `start` step from `cloudera.manager` and `cloudera.agent` salt scripts.  Run these after `pre-ambari-start` step.
Plus:
* fix `server_host` value in `unless` condition of `replace_server_host`
* fix marker file for `init-cloudera-manager-db`
Deployed a simple ZK cluster with 2 host groups.  Verified that pre-ambari-start recipe is executed after CM install, but before CM start, both on the server host and on agent-only hosts.
=> [CB-1388] CM started before pre-ambari-start recipe

freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java
One line change for setting image from request and removal of hard-coded image id. 
Until there is a plan to have Images 
`"image": {
"catalog": "string", 
"id": "ami-0a21cab39fdfb6b1a", 
"os": "string"
}, `
`BUILD SUCCESSFUL in 14m 4s
390 actionable tasks: 388 executed, 2 up-to-date`
@keyki @lacikaaa @handavid
=> Image id can be taken from the request

redbeams-api/build.gradle, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/DatabaseServerV4Endpoint.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/responses/DatabaseServerV4Response.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/OperationDescriptions.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/responses/DatabaseServerV4ResponseTest.java, redbeams-model/build.gradle, redbeams-model/src/main/java/com/sequenceiq/redbeams/domain/DatabaseServerConfig.java, redbeams/build.gradle, redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsApplication.java, redbeams/src/main/java/com/sequenceiq/redbeams/aspect/SecretAspects.java, redbeams/src/main/java/com/sequenceiq/redbeams/configuration/DatabaseConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/mapper/NotFoundExceptionMapper.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/StringToSecretResponseConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerConfigToDatabaseServerV4RequestConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerConfigToDatabaseServerV4ResponseConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerV4RequestToDatabaseServerConfigConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/repository/DatabaseServerConfigRepository.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/DummyMetricService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/main/resources/application.yml, redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerConfigToDatabaseServerV4RequestConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerConfigToDatabaseServerV4ResponseConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerV4RequestToDatabaseServerConfigConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigServiceTest.java
The redbeams service now supports the following operations on existing
database servers:
* registration (creation)
* deregistration (deletion)
* multiple deregistration
* retrieval
* listing
The two primary pieces of work to enable this, beyond the business logic
to perform the operations:
* Several converters are added for converting between the internal
DatabaseServerConfig model class and corresponding request and
response objects at the API level. Additionally,
StringToSecretV4ResponseConverter is brought in, since it is needed
for converting to database server API response objects.
* The SecretAspects aspect is copied in to enable redbeams to access
the vault service, where database server connection usernames and
passwords are kept.
The API response converters are also needed for …
=> CB-1174 Implement redbeams existing database server API

cloud-common/src/main/resources/application.yml, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha.bp
Add a flavor of the Data Engineering template configured for HA (for components that already support it).
Some limitations/workarounds:
* checkpoint dir needs to be specified due to CM config bug, although Secondary NameNode is not deployed in HA setup
* Hive Metastore Canary health check disabled due to not HA-specific CM bug
* redaction policy needs to be disabled due to some classpath issue that prevents JournalNode startup
=> DISTX-122. Create HA Data Engineering template

core-api/build.gradle, core-api/src/main/java/com/sequenceiq/cloudbreak/validation/DatabaseVendorValidator.java, core-api/src/main/java/com/sequenceiq/cloudbreak/validation/UrlValidator.java, core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidDatabaseVendor.java, core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidUrl.java, core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidatorUtil.java, core-api/src/test/java/com/sequenceiq/cloudbreak/validation/DatabaseVendorValidatorTest.java, core-api/src/test/java/com/sequenceiq/cloudbreak/validation/UrlValidatorTest.java, gradle.properties, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/base/DatabaseServerV4Base.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/DatabaseServerV4Request.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/mapper/ConstraintViolationExceptionMapper.java
Bean validation for the JSON representation of database server data is
expanded to cover the database vendor and connector JAR URL fields,
through the application of two new validators: DatabaseVendorValidator
and UrlValidator. Constraint violations that arise from validation
failures are now properly mapped to API responses.
=> CB-1365 Expand bean validation on DatabaseServerV4Base

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/AbstractRoleConfigConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ConfigUtils.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoleConfigConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoles.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveRoles.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveServer2RoleConfigConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/oozie/OozieRoleConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/oozie/OozieRoles.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoles.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnRoleConfigConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnRoles.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/generator/configuration/CmTemplateGeneratorConfigurationResolver.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/generator/dependencies/ServiceDependencyMatrixService.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/generator/support/SupportedVersionService.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/generator/template/GeneratedCmTemplateService.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/ClusterTemplateGeneratorServiceTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsVolumeConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveServer2ConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/oozie/OozieRoleConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnVolumeConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/generator/configuration/CmTemplateGeneratorConfigurationResolverTest.java, template-manager-cmtemplate/src/test/resources/output/clouderamanager-without-hosts.bp, template-manager-cmtemplate/src/test/resources/output/clouderamanager.bp
Refactor config providers a bit:
* eliminate indirection (`name` -> `variable` -> `value`) since it seems unnecessary for generated templates
* extract service and role names to constants
* less verbose config item creation (`config` utility function)
Plus:
* remove unused `ResourceLoader` from `CmTemplateGeneratorConfigurationResolver`
* rename `serviceInformations` to `serviceConfigs` to be consistent with the type `ServiceConfig`
Adjusted unit tests.
Deployed workload and data lake clusters.
=> Simplify CM template configuration

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/cluster/ClusterV4Request.java, core-api/src/test/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/cluster/ClusterV4RequestTest.java, core-api/src/test/resources/api-compatibility/StackV4Request_v2.10.0.json, core/src/main/resources/defaults/blueprints/cdp-sdx.bp, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java, template-manager-cmtemplate/src/test/resources/input/clouderamanager.bp, template-manager-cmtemplate/src/test/resources/output/clouderamanager.bp
Use master password in SDX template instead of hard-coded one.
Adjusted unit test.  Still have to test actual cluster deployment.
=> CB-1433. Remove hard-coded password from SDX template

README.md
The main README.md now describes how to run Redbeams locally. Many
other areas of the document were lightly edited for grammar,
capitalization, and updated URLs.
=> CB-1417. Add Redbeams to README along with light editing

cloud-common/src/main/resources/application.yml
SDX cluster (which has Ranger and Atlas) cannot be installed with this build nor kerberos enabled cluster.
=> CB-99 update CM version

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java, template-manager-cmtemplate/src/test/resources/input/clouderamanager-existing-conf.bp
Prefer configuration defined in cluster template (blueprint) over configuration generated by code.
Adjusted unit test.  Deployed cluster with custom `dfs_datanode_failed_volumes_tolerated` setting.
=> CB-1452. Let existing config in template take precedence

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToTemplatePreparationObjectConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintViewProvider.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackV4RequestToTemplatePreparationObjectConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintViewProviderTest.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/BlueprintView.java
Leftover `AmbariBlueprintViewProvider` caused `BlueprintView` created for CM template to have no components.
=> CB-1494. Stack converter creates Ambari blueprint view

core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/ComponentLocatorService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/ComponentLocatorServiceTest.java, template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/AmbariBlueprintTextProcessor.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/model/ServiceComponent.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/processor/BlueprintTextProcessor.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/BlueprintView.java
Implement some missing component-related functions for CM templates.  This is needed to streamline HA template logic.
Unit tests.
=> CB-1518. Implement component-related logic for CM templates

core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha.bp, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoleConfigConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsVolumeConfigProviderTest.java, template-manager-cmtemplate/src/test/resources/input/namenode-ha.bp
Move properties required for NameNode HA to the config provider from the template.  The goal is to avoid having to specify them in all HA templates.  `autofailover_enabled` should always be `true`.  The name for nameservice and journal are sensible defaults, but can be overridden in the template if needed.  The properties are injected only for HA template (more than one NameNode).
Deployed both non-HA and HA clusters.
Unit test.
=> DISTX-138. Provide default values for HA-related configs

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiClient.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiUserCrnClient.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/UserV1Endpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UserModelDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UsersyncOperationDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SetPasswordRequest.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SetPasswordResponse.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeUsersRequest.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/User.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa/src/main/java/com/sequenceiq/freeipa/configuration/EndpointConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/user/event/FreeIpaClientRequest.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/user/event/FreeIpaClientResult.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/user/event/SetPasswordRequest.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/user/event/SetPasswordResult.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/user/handler/SetPasswordHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/PasswordService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/UserService.java
This commit adds an endpoint that sets a user's password in the
freeipa server. The API call is currently wired directly to the
service implementation and executed synchronously. The actual
set password activities will take time and will be executed
through the EventBus.
As part of this change, the API path for usersync has been changed
/v1/freeipa/user/sync -- performs usersync
/v1/freeipa/user/{username}/password -- sets password for user
A getAllByAccountId method was added to the StackService to retrieve all stacks for a
given accountId because we want to set the password in all environments.
=> CDPCP-146. Add API to set user password in FreeIPA

core/src/main/resources/defaults/blueprints/cdh6-data-science.bp
Remove leftover Hive Metastore DB variables from CDH 6.2 template.  They are no longer assigned any value since #4996.  The problem is that the variable references are not overwritten by generated config values since #5030.
Deployed CDH 6.2 cluster.
=> CB-1557. CDH 6.2 cluster creation fails on Hive metastore config

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/AbstractRoleConfigConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ConfigUtils.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ConfigTestUtil.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/impala/ImpalaLdapConfigProviderTest.java
* Rename `AbstractRoleConfigConfigProvider.getVariables()` to `getRoleConfigVariable()`
* Named by analogy of its counterpart `getRoleConfig()`
* Extend `ConfigUtils` with two additional convenience factory methods: `configVar()` and `variable()`
* Will come handy when setting configs as variables as opposed to direct values
* Extract `Map` building logic from `ImpalaLdapConfigProviderTest` into the new `ConfigTestUtil`
* Encourages code-reuse among similar unit tests
Adjusted unit tests.
=> CB-1006 Small enhancements for CM conf provider var handling & testing

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaOperationDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/service/api/doc/ContentType.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/model/Ca.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaRootCertificateService.java, freeipa/src/test/java/com/sequenceiq/freeipa/controller/FreeIpaV1ControllerTest.java
/v1/freeipa/ca.crt?{environmentCrn} endpoint added to FreeIpaV1Endpoint.
This endpoint uses the FreeIpaClient to retrieve the root certificate
from the IPA server. The certificate is returned Base64 encoded. This
code re-formats the certificate into PEM format before returning it to
the caller.
=> CB-1521. Retrieve root certificate from ipa server

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/test/ClientTestV1Endpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/UserV1Endpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UserModelDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UserNotes.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UserOperationDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UsersyncOperationDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/CreateUsersRequest.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/CreateUsersResponse.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizationStatus.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeUsersRequest.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeUsersResponse.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/PasswordService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/UserService.java, freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java
The existing user sync API has been moved to "create". This will
be left in place until the user sync API work is completed.
The user sync API has been changed to accept an optional set of
environments and users in anticipation of retrieving users from
the UMS instead of passing them in through the API. The environments
and users in the request will be used to narrow the scope of the
sync. e.g., if we want to sync only one environment or one user.
Minor improvements were made to API documentation and testing.
=> DISTX-112. Update user sync API

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdater.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateConfigInjector.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateConfigInjectors.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ProcessAutoRestartInjector.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoles.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java, template-manager-cmtemplate/src/test/resources/output/namenode-ha-injected.bp
Automatically inject `process_auto_restart: true` into configs for all roles which are currently tested with this feature.
(The framework can also be used for example to "globally" override log directory thresholds to percentage values.)
Added unit test.  Deployed clusters using Data Engineering HA, Data Science and SDX templates.
=> CB-1612. Enable process auto-restart by default

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdater.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java, template-manager-cmtemplate/src/test/resources/input/clouderamanager-custom_cluster_name.bp, template-manager-cmtemplate/src/test/resources/input/clouderamanager-variables.bp, template-manager-cmtemplate/src/test/resources/output/clouderamanager-variables.bp
Remove configurations that reference undefined variables before further processing the cluster template.  This way leftover references are handled gracefully, while ensuring that users can define variables and reference them.
Added unit test.  Deployed cluster with both kind of variables (valid and invalid).
=> CB-1616. Handle undefined cluster template variables

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/generator/OfflineStateGenerator.java, core/src/main/java/com/sequenceiq/cloudbreak/init/CloudbreakCleanupService.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/VolumeTemplateRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, core/src/main/java/com/sequenceiq/cloudbreak/startup/MissingVolumeTemplatesMigrator.java
This is needed for environments where the wrong volume template SQL has already been executed before the fix (like on QA). 
Later we can delete it, but it was easier to do this with Java migration.
=> CB-1339 missing volume templates migrator

core/src/main/resources/defaults/blueprints/cdp-sdx.bp
Incorporate changes made to SDX blueprint by @kkalvagadda in #5154 and:
1. Keep `cdp-sdx.bp` instead of re-adding it as `cdp-sdx-dev.bp` (to avoid breaking defaults)
2. Replace hard-coded secrets with "master" password
3. Move to a branch in the `hortonworks/cloudbreak` repo, because unfortunately CI is not working for PRs from forks
I have kept the author of the commit (9ea8371a705ba2f49940f1432becbffc0f9edcfa) the same as the original (1f036ce31877bfc73acef4641862f58268c0fdee).
Deployed a data lake cluster based on this blueprint.
=> CB-1604. Update the blueprint for SDX cluster

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/GatewayRecommendation.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/InstanceCount.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/PlatformRecommendation.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/responses/RecommendationV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/connector/responses/GatewayRecommendationV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/connector/responses/InstanceCountV4Response.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/clustertemplate/PlatformRecommendationToPlatformRecommendationV4ResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java, template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/AmbariBlueprintTextProcessor.java, template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/AmbariBlueprintTextProcessorTest.java, template-manager-blueprint/src/test/resources/blueprints-jackson/test-bp-cardinality.bp, template-manager-blueprint/src/test/resources/blueprints-jackson/test-bp-gateway.bp, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java, template-manager-cmtemplate/src/test/resources/input/namenode-ha-no-gateway.bp, template-manager-cmtemplate/src/test/resources/input/namenode-ha-single-worker.bp, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/processor/BlueprintTextProcessor.java
Add two new structures to the response of `/blueprints_util/recommendation` V4 endpoint:
1. `instanceCounts`: minimum and maximum number of hosts for each host group
2. `gatewayRecommendation`: set of host groups where the cluster manager server should be installed
Example:
```
{
...
"instanceCounts": {
"compute": {
"minimumCount": 0,
"maximumCount": 2147483647
},
"gateway": {
"minimumCount": 1,
"maximumCount": 1
},
"master": {
"minimumCount": 2,
"maximumCount": 2
},
"quorum": {
"minimumCount": 3,
"maximumCount": 2147483647
},
"worker": {
"minimumCount": 1,
"maximumCount": 2147483647
}
},
"gatewayRecommendation": {
"hostGroups": [
"gateway"
]
}
}
```
These are filled based on the following:
1. Ambari: the following types of cardinality specification are handled in blueprints:
* `N` …
=> CB-1536. Recommend default instance counts and cluster manager group

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/blueprint/BlueprintV4RequestToBlueprintConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/blueprint/BlueprintV4RequestToBlueprintConverterTest.java, template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/utils/BlueprintUtils.java, template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/utils/AmbariBlueprintUtilsTest.java, template-manager-blueprint/src/test/resources/defaults/blueprints/cdp.bp
[Default blueprints](https://github.com/hortonworks/cloudbreak/tree/master/core/src/main/resources/defaults/blueprints) have an additional layer of data on top of the content accepted for user-managed blueprints.  This causes confusion when trying to submit customised built-in blueprints, especially given the not too helpful error message:
```
ERROR: status code: 400, message: null
```
This change lets users submit both raw regular and built-in blueprints.  The latter is accepted if the embedded `"blueprint": { ... }` structure is valid as Ambari or CM blueprint.
Tags, description and any other data from the external structure are ignored and still need to be set "manually" in the request.
Added unit test.  Tested creation of valid and invalid blueprints via CLI.  Checked created valid …
=> CB-1458. Accept built-in blueprint in request

redbeams/src/main/java/com/sequenceiq/redbeams/converter/database/DatabaseConfigToDatabaseV4ResponseConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigService.java, redbeams/src/main/resources/schema/app/20190530170044_CB-1653_Adjust_database_CRN_storage.sql, redbeams/src/test/java/com/sequenceiq/redbeams/converter/database/DatabaseConfigToDatabaseV4ResponseConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigServiceTest.java
Redbeams now stores the account ID from database CRNs in a separate,
indexed column. The existing "crn" column is migrated to a TEXT type to
ensure enough space to store an entire CRN.
=> CB-1653 Add account ID to database, expand CRN column

cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtSetupServiceTest.java
Fix:
```
> Task :cluster-cm:compileTestJava FAILED
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtSetupServiceTest.java:15: error: cannot find symbol
import com.sequenceiq.cloudbreak.validation.DatabaseCommon;
```
=> CB-1394. Fix compile error in ClouderaManagerMgmtSetupServiceTest

common/src/main/java/com/sequenceiq/cloudbreak/common/database/DatabaseCommon.java, common/src/test/java/com/sequenceiq/cloudbreak/util/DatabaseCommonTest.java
PostgreSQL always requires a database as part of a JDBC connection URL.
So, the general connection URL for PostgreSQL database servers is now
defined as the URL for the "postgres" database that should always exist.
This allows connection to PostgreSQL for server-level operations, such
as database creation and deletion.
=> CB-1395 Fix connection URL for Postgres server

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/UserV1Endpoint.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/PasswordService.java, freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java
This change removes the username from the set password endpoint.
Instead, the calling user crn will be used to retrieve the
user id from the UMS so users can only set their own password.
=> CDPCP-300. Set password for user from crn

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerTemplateInstallChecker.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerTemplateInstallCheckerTest.java
Improve the message shown when cluster install fails for the following cases.
Sometimes the error message is in the top-level command's result.  Current code ignores it, and looks for message only in children.
```
{
"name" : "ClusterTemplateImport",
"success" : false,
"resultMessage" : "java.lang.IllegalArgumentException: Unknown configuration attribute 'process_auto_restart'.",
"children" : {
"items" : [ {
"name" : "DeployParcels",
"success" : true,
"resultMessage" : "The Following parcels successfully activated : ..."
} ]
}
}
```
Old:
```
com.sequenceiq.cloudbreak.cm.ClouderaManagerOperationFailedException: Cluster template install failed: []
```
New:
```
com.sequenceiq.cloudbreak.cm.ClouderaManagerOperationFailedException: Cluster template install failed: [Command …
```
=> CB-761. Give detailed message on CM cluster template failure

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/config/UmsClientConfig.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/Group.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/User.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/model/Group.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/model/User.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/ClientTestV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/FreeIpaUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/UmsUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/UserService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/model/UsersState.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/model/UsersStateDifference.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/user/FreeIpaUsersStateProviderTest.java
This is the first cut at syncing users and groups from the UMS to
the IPA server. This includes the following changes:
- The UMS client was updated to list all users and retrieve rights
- The FMS retrieves the user and group state from the UMS
- The FMS retrieves the user and group state from the IPA
- The FMS calculates the difference between the state retrieved from
the UMS compared to the IPA
- The FMS adds groups and users that exist in the UMS to the IPA.
The sync is currently run synchronously with the API call and the
API response is not yet populated.
=> DISTX-126. Sync users from UMS to IPA

core/src/main/resources/defaults/blueprints/cdp-sdx-ha.bp
We need to have an SDX blueprint for HA deployment. Scope of this Jira to get an initial version and make improvements as we go.
Made sure that cloudbreak is able to set up a CM cluster using the blueprint.
=> CB-1713: Add SDX ha blueprint to CB.

redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/DatabaseV4Endpoint.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/base/DatabaseV4Identifiers.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/request/DatabaseTestV4Request.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/DatabaseServerV4Endpoint.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/base/DatabaseServerV4Identifiers.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/DatabaseServerTestV4Request.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/database/base/DatabaseV4BaseTest.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/database/base/DatabaseV4IdentifiersTest.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/database/request/DatabaseTestV4RequestTest.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/base/DatabaseServerV4IdentifiersTest.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/DatabaseServerTestV4RequestTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/database/DatabaseV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/repository/DatabaseConfigRepository.java, redbeams/src/main/java/com/sequenceiq/redbeams/repository/DatabaseServerConfigRepository.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigServiceTest.java
All redbeams API calls pertaining to databases and database servers now
require an environment ID, which may be either a CRN or name. Calls
where the environment ID is not passed as a JSON field get it from an
API query parameter, such that these resources are now scoped by
environment in the API.
Other changes:
* DatabaseConfigRepository.findByEnvironmentId now returns a set.
* DatabaseConfigService.list is renamed to findAll.
* DatabaseConfigService.get is implemented; this refactors delete logic
and forms the basis for the upcoming get API endpoint.
* DatabaseConfigService.delete for multiple databases now returns the
deleted entities, not the originally found ones.
* DatabaseV4BaseTest is introduced.
* Listing of database servers now include all of them, not just
USER_MANAGED ones.
=> CB-1654 Include environment ID fully in redbeams API

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProvider.java
Use the cluster password if gateway is not enabled, but Knox GW role is present in the blueprint.
=> CB-1500 set password for Knox even if gateway is not enabled

redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/ResourceStatus.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/database/DatabaseV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/database/DatabaseV4RequestToDatabaseConfigConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerV4RequestToDatabaseServerConfigConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseServerConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/exception/RedbeamsException.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/main/resources/schema/app/20190604193436_CB-1395_Link_databases_and_database_servers.sql, redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/database/DatabaseV4ControllerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/database/DatabaseConfigToDatabaseV4ResponseConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/database/DatabaseV4RequestToDatabaseConfigConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerV4RequestToDatabaseServerConfigConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/model/DatabaseServerConfigTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigServiceTest.java
Redbeams now has the ability to delete databases existing on PostgreSQL
database servers, as long as redbeams itself created it in the first
place.
Redbeams uses a new ResourceStatus enum to more clearly mark databases
as either service-managed (created by redbeams) or user-managed (created
outside redbeams). Handling of this status field for databases is
updated, so that it is set properly depending on the provenance of a new
database.
Implementing this requires the establishment of a one-to-many
relationship between databases and the servers they run on. Only
databases created by redbeams have this linkage in place.
As a bonus, the database get operation is now available in the API.
=> CB-1395 Implement database deletion on server

redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsApplication.java, redbeams/src/main/java/com/sequenceiq/redbeams/repository/DatabaseConfigRepository.java, redbeams/src/main/java/com/sequenceiq/redbeams/repository/DatabaseServerConfigRepository.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/crn/CrnService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/crn/CrnServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigServiceTest.java
Two changes:
* The account ID present in the authenticated user's CRN is used when
constructing new CRNs for databases and database servers.
* API calls which specify the "name" of a database or database server
may use either the name itself or the CRN.
=> CB-1676 Update redbeams CRN handling

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
If during cluster install, cleanup task can fail through creating cluster modification bean (as CM client cannot be created yet)
that is just a quick fix , a cluster related cleanup is not a fatal one, so just catching and logging the error.
With a longer term solution (not too long term ... I mean like next week) is to create an another interface for ClusterApi that can be called without creating CM client or just call the cleanup if a specific cluster state is satisfied
=> DISTX-39. Fix cleanup failure if delete happens too early.

cloud-common/src/test/java/com/sequenceiq/cloudbreak/util/FixedSizePreloadCacheTest.java
Increase timeout, trying to avoid intermittent failure of `FixedSizePreloadCacheTest.testPopWhenReplacementNeeded` (failed 2 out of 20 times recently).
=> CB-706. Increase timeout of testPopWhenReplacementNeeded

core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha.bp
Add Oozie to the Data Engineering HA template.  Oozie supports HA, but CM requires a load balancer to be manually set up for that. The load balancer will be added later, so Oozie is not HA yet in this template.
Deployed HA cluster using the template.
=> DISTX-192. Add Oozie to Data Engineering HA template

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/InstanceCount.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/host/HostGroup.java, core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintValidatorFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecorator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterHostServiceTypeTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecoratorTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentDatalakeClusterTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/KerberosConfigTest.java, template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/utils/BlueprintUtils.java, template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/validation/AmbariBlueprintValidator.java, template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/validation/AmbariBlueprintValidatorTest.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidator.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidatorTest.java, template-manager-cmtemplate/src/test/resources/input/cdp-data-mart-no-cardinality.bp, template-manager-cmtemplate/src/test/resources/input/cdp-data-mart.bp, template-manager-core/build.gradle, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/validation/BlueprintValidator.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/validation/BlueprintValidatorUtil.java, template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/validation/BlueprintValidatorUtilTest.java
Validate host groups in cluster creation request for CM.
* no missing groups: all host groups in the template should be present in the request
* no unknown groups: all host groups in the request should be defined in the template
* cardinality: nodes requested for each host group should be within the range recommended based on cardinality of the template
Validation can be turned off by setting `.cluster.validateBlueprint` to `false` in the request.  However CLI has a bug that makes it impossible to turn off validation since version 964.
UI always turns off validation, cluster with invalid cardinality can still be created through it.
Validation for scaling requests is not implemented yet.
Tested that cluster creation requests invalid due to the above restrictions are rejected with the …
=> CB-1761. Validate node counts in CM cluster request

core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha.bp, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProvider.java, template-manager-cmtemplate/src/test/resources/output/clouderamanager-variables.bp, template-manager-cmtemplate/src/test/resources/output/clouderamanager-without-hosts.bp, template-manager-cmtemplate/src/test/resources/output/clouderamanager.bp
Temporarily disable Hive Metastore Canary health check until it is fixed.
Adjusted unit tests.  Deployed built-in SDX data lake, verified check is disabled.
=> CB-1660. Workaround for Metastore Canary failure

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/ModifyGrainBase.java
Implemented a quick and dirty retry logic inside the `ModifyGrainBase` because passing a RetryTemplate would have been a too large modification.
=> CB-1715 - added retry logic to modify grain runner

redbeams/src/main/java/com/sequenceiq/redbeams/aspect/CheckPermissionsAspects.java, redbeams/src/main/java/com/sequenceiq/redbeams/authorization/CheckPermissionsByReturnValue.java, redbeams/src/main/java/com/sequenceiq/redbeams/authorization/CheckPermissionsByTarget.java, redbeams/src/main/java/com/sequenceiq/redbeams/authorization/CrnResource.java, redbeams/src/main/java/com/sequenceiq/redbeams/authorization/DisableCheckPermissions.java, redbeams/src/main/java/com/sequenceiq/redbeams/authorization/DisabledPermissionChecker.java, redbeams/src/main/java/com/sequenceiq/redbeams/authorization/PermissionChecker.java, redbeams/src/main/java/com/sequenceiq/redbeams/authorization/PermissionCheckerService.java, redbeams/src/main/java/com/sequenceiq/redbeams/authorization/PermissionCheckingUtils.java, redbeams/src/main/java/com/sequenceiq/redbeams/authorization/ResourceAction.java, redbeams/src/main/java/com/sequenceiq/redbeams/authorization/ReturnValuePermissionChecker.java, redbeams/src/main/java/com/sequenceiq/redbeams/authorization/TargetPermissionChecker.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseServerConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/repository/DatabaseConfigRepository.java, redbeams/src/main/java/com/sequenceiq/redbeams/repository/DatabaseServerConfigRepository.java, redbeams/src/test/java/com/sequenceiq/redbeams/authorization/DisabledPermissionCheckerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/authorization/PermissionCheckerServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/authorization/PermissionCheckingUtilsTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/authorization/ReturnValuePermissionCheckerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/authorization/TargetPermissionCheckerTest.java
The repository classes in redbeams now enforce READ permission checks on
database and database server entities. The permission framework is
implemented in a similar fashion to other Cloudbreak services (core and
environment, in particular), but uniquely enough to merit doing its own
thing.
Only the following three permission checks are supported, reduced from
those currently defined in core:
* disabled
* on return value
* on method argument ("target")
Each permission checker is composed of an annotation and corresponding
class containing the checking logic. Unlike the permission framework in
core, redbeams allows repository methods to have no annotation, which
means there is no permission check. Multiple annotations are still
prohibited.
CheckPermissionsAspects intercepts calls to the …
=> CB-1676 Implement UMS-based permission checks in redbeams

common/src/main/java/com/sequenceiq/cloudbreak/common/database/DatabaseCommon.java, common/src/test/java/com/sequenceiq/cloudbreak/util/DatabaseCommonTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseServerConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/test/java/com/sequenceiq/redbeams/model/DatabaseServerConfigTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigServiceTest.java
When creating a new database on a server, redbeams now also creates a
new user with all privileges to the server. Likewise, when deleting a
database on a server, redbeams also deletes the corresponding user.
(Database commands are only tested on PostgreSQL for now.)
The user for a new database gets a random ten-character alphabetic
username and a random UUID for a password. (Future work could do a
better job of username generation, to ensure that an existing user
isn't reused by chance.) If, somehow, the user for a database is the
same as the root user for the server, redbeams does not remove the user
account from the server along with the database.
Transaction processing for these operations in redbeams has been
adjusted, so that only the SQL commands for database and user handling
occur …
=> CB-1695 Create db-specific users in redbeams

core/src/main/resources/defaults/blueprints/cdp-sdx-ha.bp, core/src/main/resources/defaults/blueprints/cdp-sdx.bp, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxRoles.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProviderTest.java
Inject gateway password (or cluster password if gateway is not enabled) as `idbroker_master_secret` in Knox role configs, similar to how `gateway_master_secret` is injected.
Added unit test.  Deployed SDX clusters of various flavors.
=> CB-1804. Inject `idbroker_master_secret`

cloud-common/src/main/resources/application.yml, core/src/main/resources/defaults/blueprints/cdp-data-mart-ha.bp
Add a flavor of the Data Mart template configured for HA for components that already support it.
Note: Oozie supports HA, but CM requires a load balancer to be manually set up for that.  The load balancer will be added later, so Oozie is not HA yet in this template.
Deployed cluster.
=> DISTX-128. Create HA Data Mart cluster template

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Logging.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/LoggingAttributesHolder.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/WorkloadAnalytics.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/WorkloadAnalyticsAttributesHolder.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/logging/CommonLoggingAttributes.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/logging/S3LoggingAttributes.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtTelemetryService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtTelemetryServiceTest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/LoggingV4Base.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/WorkloadAnalyticsV4Base.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/telemetry/TelemetryComponentParams.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java, orchestrator-salt/src/main/resources/salt/pillar/fluent/init.sls, orchestrator-salt/src/main/resources/salt/salt/fluent/init.sls, orchestrator-salt/src/main/resources/salt/salt/fluent/settings.sls, orchestrator-salt/src/main/resources/salt/salt/fluent/template/td-agent.conf.j2
Use objects instead of dynamic attributes for log settings:
that: 
```json
"attributes" : {
"xxx",
"yyy"
}
```
will look like this:
```json
"output": "s3",
"attributes" : {
"s3": {
"xxx",
"yyy"
}
}
```
Also adding some cleanups:
- extend decorator a bit to handle situations when bucket or basePath is defined with s3, s3a or s3n scheme
- install td-agent on the nodes in case of missing from the image (it is installed by default in cloudbreak-images, but that can be useful if the package is missing)
- do not skip cluster cleanup on any errors, it can be skipped if cluster IP was calculated (before)
- add some more UTs
=> DISTX-39. Use objects for telemetry attributes

core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha.bp, core/src/main/resources/defaults/blueprints/cdp-sdx.bp
We need to have an SDX blueprint for HA deployment to handle the medium load. Idea is to have three blueprints for SDX
1. SDX Lite Duty
2. SDX Lite Duty -HA
3. SDX Medium Duty -HA
Scope of this Jira to get an initial version and make improvements as we go.
Made sure that cloudbreak is able to set up a CM cluster using the blueprint.
=> CB-1778: Create SDX blueprint to handle medium scale

core/src/main/java/com/sequenceiq/cloudbreak/service/TlsSecurityService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperErrorHandlerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/PreTerminationStateExecutorTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/TlsSecurityService.java, orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/GatewayConfig.java, orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java, orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrapTest.java
With these changes, the provider-specific instance id has been
propagated to the gateway config, in preparation for its use as a unique identifier by the CCM registration/lookup process.
=> CB-1814. add instance id to gateway config.

core/src/main/resources/defaults/blueprints/cdp-data-mart.bp
1. Replace `mr` execution engine with `spark` in Data Mart template, because HiveServer2 fails to start due to: `IllegalArgumentException: mr execution engine is not supported`.
2. Specify `cardinality`.
Deployed cluster, verified HiveServer2 is up and running.
=> CDPD-1220. Hive on MR does not start

core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha.bp
The blueprint should use the hostgroup cardinality to attain HA for the service. Jira has additional details.
Made sure that cluster is properly set up using Manowar.
Please refer below sheet for more details
https://docs.google.com/spreadsheets/d/105k_ilyLqQbzOA-GUxmrtbPm_ZMfJfVf13i6KR8VePQ/edit?usp=sharing
=> CB-1869: Update the SDX Medium HA BP using hostgroup Cardinality

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DatabaseEngine.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DatabaseServer.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DatabaseStack.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/common/type/ResourceType.java
Additions to cloud-api lay the groundwork for database server creation
in cloud providers via template.  The new DatabaseStack class
corresponds to the existing CloudStack class, but is intended to
represent the resources for a database server and supporting resources.
=> CB-1837 Augment cloud-api with database support

redbeams/src/main/java/com/sequenceiq/redbeams/authorization/PermissionCheckingUtils.java, redbeams/src/main/java/com/sequenceiq/redbeams/configuration/AppConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/filter/RequestIdFilter.java, redbeams/src/main/java/com/sequenceiq/redbeams/filter/RequestIdGeneratingFilter.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/ThreadBasedRequestIdProvider.java, redbeams/src/test/java/com/sequenceiq/redbeams/authorization/PermissionCheckingUtilsTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/filter/RequestIdFilterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/filter/RequestIdGeneratingFilterTest.java
Two new web filters in redbeams deal with request IDs.
* RequestIdGeneratingFilter looks for an x-cdp-request-id header in an
incoming request and, if absent, generates one with a random UUID for
a value. This ensures that every request has a request ID.
* RequestIdFilter saves the request ID in the x-cdp-request-id header in
a thread-local variable hosted by ThreadBasedRequestIdProvider. This
makes the request ID available to business logic.
PermissionCheckingUtils gets the request ID from the thread-local
provider to pass in UMS calls, instead of the former stub value.
The redbeams AppConfig class registers the two new web filters. The
generating filter is ordered first, so that the other filter can see
the request ID it might generate.
Unlike other services, this request ID handling is …
=> CB-1772 Handle and generate request ID in redbeams

redbeams/src/main/java/com/sequenceiq/redbeams/domain/stack/DBStack.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/stack/DatabaseServer.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/stack/Network.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/stack/SecurityGroup.java, redbeams/src/main/resources/schema/app/20190614194213_CB-1837_Add_redbeams_stack_entities.sql, redbeams/src/test/java/com/sequenceiq/redbeams/domain/DatabaseServerConfigTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/domain/stack/DBStackTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/domain/stack/DatabaseServerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/domain/stack/NetworkTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/domain/stack/SecurityGroupTest.java
New entity classes represent the creation of a new database server. The
top-level DBStack object represents one creation request. It is
comprised of a network description, a database server description, and
general top-level information. The lower-level Network, DatabaseServer,
and Security entities store more detailed information. Network and
Security are based on similar entity classes in the core Cloudbreak
service. All of the entities might end up with more fields in the near
future as the logic for performing database creation develops.
A database migration for establishing the entities in the redbeams
database is included.
=> CB-1837 Add redbeams DBStack and associated entities

common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/AbstractServiceFamily.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/BaseServiceEndpoint.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/DirectServiceEndpointFinder.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/HostEndpoint.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/HttpsServiceEndpoint.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/KnownServiceIdentifier.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/ServiceEndpoint.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/ServiceEndpointFinder.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/ServiceEndpointLookupException.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/ServiceEndpointRequest.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/ServiceFamilies.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/ServiceFamily.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/endpoint/TargetInstance.java, orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/GatewayConfig.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
With these changes, CB has classes representing the various
CCM domain objects and finder functionality.
Additionally, the gateway config and salt orchestrator have
been modified to use a service endpoint finder instead of
always connecting directly to the nginx server on the gateway
node.
=> CB-1816. Add CCM endpoint infrastructure.

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/ResourceConnector.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DatabaseServer.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsResourceConnector.java, cloud-aws/src/main/resources/templates/aws-cf-dbstack.ftl, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java, cloud-common/src/main/resources/application.yml, cloud-cumulus-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/cumulus/yarn/CumulusYarnResourceConnector.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpResourceConnector.java, cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockResourceConnector.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackResourceConnector.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/OpenStackNativeResourceConnector.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java, cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java, environment/src/main/resources/application.yml, freeipa/src/main/resources/application.yml, redbeams/src/main/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverter.java, redbeams/src/main/resources/application.yml, redbeams/src/test/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverterTest.java
The ResourceConnector cloud-api interface gains two new methods:
launchDatabaseServer for launching a new database server in a cloud
provider, and getDBStackTemplate for getting the Freemarker template to
be used to build an RDS instance. The methods are mostly stubbed out in
ResourceConnector implementations, except for AwsResourceConnector. In
that implementation, the template contents are loaded from a file as
expected, but the launch method is still stubbed out, for now.
The contents of that Freemarker template for creation of an RDS instance
and associated DB subnet are now available. The template is much simpler
than the existing one for clusters, and is driven by a somewhat large
number of parameters.
The new DBStackToDatabaseStackConverter class converts from the redbeams
DBStack …
=> CB-1837 Augment cloud-api for db servers; add RDS CFT

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateComponentConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateComponentConfigProviderProcessor.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ConfigUtils.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoleConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerCloudStorageServiceConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerCloudStorageServiceConfigProviderTest.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java
This change improves the default Ranger audit location for HDFS to make it work in NameNode HA setup.
Also:
* since `/ranger/audit` is appended by CM, we don't need to include it in the default value
* use FQDN of NameNode, since it may be assigned to a host other than the one with CM
* port can be omitted, CM will read from configs
Deployed clusters HA and non-HA clusters with:
* default settings
```
Successfully created HDFS directory hdfs://ns1/ranger/audit/hdfs.
Successfully created HDFS directory hdfs://example.com/ranger/audit/hdfs.
```
* custom audit location (specified in `ranger_plugin_hdfs_audit_url` in the blueprint)
```
Successfully created HDFS directory hdfs://ns1/customdir/ranger/audit/hdfs.
Successfully created HDFS directory …
```
=> CB-1959. Default Ranger audit location is not HA-compatible

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelper.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsLaunchService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsResourceConnector.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsNetworkView.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsRdsDbSubnetGroupView.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsRdsInstanceView.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelperTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderDBTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/TestConstants.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsNetworkViewTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsRdsDbSubnetGroupViewTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsRdsInstanceViewTest.java, cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/CloudbreakResourceType.java, cloud-common/src/test/java/com/sequenceiq/cloudbreak/common/service/DefaultCostTaggingServiceTest.java
The cloud-aws module is augmented with most of the logic needed for
creating RDS instances. The core classes that have been modified or
added are:
* AwsResourceConnector - now delegates to the new AwsRdsLaunchService
to create an RDS instance
* AwsRdsLaunchService - performs the RDS instance launch process:
uses the following classes to create a CloudFormation template and
creation request, then sends the request to AWS and polls for
completion and outputs
* CloudFormationTemplateBuilder - builds the body of a CloudFormation
template for a new RDS instance and DB subnet group from a context
* AwsStackRequestHelper - creates a CloudFormation stack creation
request from a database stack, including setting the necessary
template parameters
The actual CloudFormation template for new RDS …
=> CB-1837 Add RDS instance creation to cloud-aws

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/ResourceConnector.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsResourceConnector.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java, cloud-cumulus-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/cumulus/yarn/CumulusYarnResourceConnector.java, cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockResourceConnector.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackResourceConnector.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java, cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java
The ResourceConnector cloud-api interface gains a new methods,
terminateDatabaseServer for terminating a previously allocated database
server in a cloud provider. The methods are stubbed out in
ResourceConnector implementations.
=> CB-1248 Augment cloud-api for db server termination

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/config/UmsClientConfig.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/User.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/FreeIpaPostInstallService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/FreeIpaUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/PasswordService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/UmsUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/UserService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/model/SyncStatusDetail.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/model/UmsState.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/model/UsersState.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/user/model/UsersStateDifference.java, freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/user/FreeIpaUsersStateProviderTest.java, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java
User sync behavior has changed in the following ways:
- All groups are retrieved from UMS instead of only those that
users are members of
- All users are added to IPA instead of only those that are members
of a group
- Users are retrieved a single time from the UMS instead of
repeatedly for each environment
- A user filter was implemented to allow sync of specified users
- Group membership is calculated and compared between UMS and IPA
- Users are added to groups in IPA
Other minor changes were:
- account and actor crn are retrieved in the controller layer
and passed in to the UserService rather than retrieved in
the UmsUsersStateProvider
This commit does not remove or deactivate users, nor does it
remove users from groups.
=> DISTX-186. Improve user sync behavior

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsLaunchService.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/AllocateDatabaseServerV4Request.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/AwsNetworkV4Parameters.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/DatabaseServerV4Base.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/DatabaseServerV4Request.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/NetworkV4Base.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/SecurityGroupV4Request.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/AwsNetworkV4ParametersTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerV4RequestToDatabaseServerConfigConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/stack/DBStack.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/AbstractRedbeamsProvisionAction.java, redbeams/src/main/java/com/sequenceiq/redbeams/repository/DatabaseServerConfigRepository.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsCreationService.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverterTest.java
* Dropped VPC ID and IGW ID from AwsNetworkV4Parameters
* AwsRdsLaunchService no longer looks for VPC in request
* Added Redbeams ModelDescriptions for all the things
* Added name generation to DBStack conversion
* Added logging of DBStack in RedbeamsCreationService
* Added MDCBuilder context building to provision action
* Added account ID getter to DBStack for MDCBuilder to find
* Implemented stack tags in conversion to DBStack
* Set username in CloudContext so StackOwner parameter works
=> CB-1837 Fix some lingering items in redbeams

core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/rds/RdsConfigValidator.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/rds/RdsConfigValidatorTest.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackV4RequestToTemplatePreparationObjectConverterTest.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/AbstractRdsRoleConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ConfigUtils.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/oozie/OozieRoleConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/AbstractRdsRoleConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProviderTest.java, template-manager-cmtemplate/src/test/resources/output/clouderamanager-variables.bp, template-manager-cmtemplate/src/test/resources/output/clouderamanager-without-hosts.bp, template-manager-cmtemplate/src/test/resources/output/clouderamanager.bp, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java
RDS configs in the stack request are already validated, rejecting requests with multiple database of the same type.  This change adds some unit test for the validator.
Since duplicates are rejected, we can collect `RDSConfig`s into a map by type, and eliminate `getFirstRDSConfigOptional`, which had two problems:
1. it returned "some" config of the given database type (didn't fail on duplicates)
2. used linear search
Also extracted a common base class for DB-related config providers to get rid of some code duplication.
Added unit test, deployed various clusters.
=> CB-1427. Only one DB per type is allowed

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudResource.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DatabaseServer.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/common/type/ResourceType.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelper.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsLaunchService.java, cloud-aws/src/main/resources/templates/aws-cf-dbstack.ftl, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderDBTest.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/DatabaseServerV4Base.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/stack/DatabaseServer.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/common/RedbeamsContext.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/AbstractRedbeamsProvisionAction.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/action/RedbeamsProvisionActions.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/event/register/RegisterDatabaseServerRequest.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/handler/RegisterDatabaseServerHandler.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/AbstractRedbeamsTerminationAction.java, redbeams/src/main/resources/schema/app/20190624144438_CB-1837_add_accountid_and_port_to_databaseserver.sql, redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/common/RedbeamsContextTest.java
Databases are now registered after creation, which will allow further
manipulation via redbeams existing mechanisms. Additionally, the ability
to specify a port has been added to redbeams, and the account ID has
been added to the database server entity.
One thing to note: the response from the create endpoint is still empty.
After this, the ability to query redbeams for the provisioning status of
a database will be added, and an identifier associated with this will be
given via the create endpoint. For now, this is not hooked up.
=> CB-1837. Register created databases.

core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering.bp
Now that dependency issues are resolved, add Hue to DE template, both HA and non-HA.
Deployed clusters.
=> DISTX-181. Add Hue to Data Engineering template

core/src/main/java/com/sequenceiq/cloudbreak/converter/util/TelemetryMergerUtil.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/util/TelemetryMergerUtilTest.java, environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/base/CommonTelemetryFields.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/base/LoggingBase.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/base/WorkloadAnalyticsBase.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentEditRequest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentRequest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/LoggingRequest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/TelemetryRequest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/WorkloadAnalyticsRequest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/DetailedEnvironmentResponse.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentBaseResponse.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/LoggingResponse.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/SimpleEnvironmentResponse.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/TelemetryResponse.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/WorkloadAnalyticsResponse.java, environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/TelemetryApiConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/domain/Environment.java, environment/src/main/java/com/sequenceiq/environment/environment/domain/EnvironmentView.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentCreationDto.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDto.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentEditDto.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentApiConverter.java, environment/src/main/java/com/sequenceiq/environment/network/v1/converter/EnvironmentBaseNetworkConverter.java, environment/src/main/resources/schema/app/20190626141237_DISTX-197_add_telemetry.sql
- added telemetry request / response on env side
- save global telemetry settings on env side (nullable - dynamic)
- merge global env telemetry settings with the stack level one
UI changes should be added in the future for the env API
No request validation yet (will be added in another PR) - overall every new field is nullsafe right now, should not broke anything
I will be out until next Thursday so no hurry with merging this
=> DISTX-197. Implement telemetry on env side

core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackApiViewService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperation.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java, environment/build.gradle, environment/src/main/java/com/sequenceiq/environment/configuration/CloudbreakApiClientConfig.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/delete/handler/NetworkDeleteHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentResourceDeletionService.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java
**Changes:**
- validate the existence of workload cluster at environment deletion
**Two additional changes to the desired test could be validated:**
- modify DistroX API to list by environment name instead of CRN
- handle null network in environment deletion handler
=> Env delete with workload cluster

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeipaCreationHandler.java, freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_install.sh
- enable overlapping DNS zone for FreeIPA installation
- change `cdp.site` domain name to `cloudera.site`
=> CB-2088 changing FreeIPA domain from cdp.site to cloudera.site

redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseServerConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/AbstractRedbeamsTerminationAction.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/action/RedbeamsTerminationActions.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/event/deregister/DeregisterDatabaseServerFailed.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/event/deregister/DeregisterDatabaseServerRequest.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/handler/DeregisterDatabaseServerHandler.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/DBStackService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsCreationService.java, redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/termination/AbstractRedbeamsTerminationActionTest.java
Databases are now deregistered during RDS termination.
Note: Need to do a bit more testing, but overall this looks good.
I had to change the DatabaseServerConfig to make the databases field not lazy, as I was running into a LazyInitializationError otherwise.
=> CB-1248. Deregister databases.

freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/user/handler/SetPasswordHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java
This changes the exception handling and logging for the set password
api. The FreeIpaClientBuilder throws an exception on failure to
connect instead of logging then throwing. The PasswordService logs
the exceptions when it swallows it and collates failure messages
for the response object. Exceptions are not wrapped in OperationException
in waitSetPassword() since they are just unwrapped again in setPassword().
=> DISTX-234. Improve exception handling for set password

orchestrator-salt/src/main/resources/salt/salt/fluent/init.sls, orchestrator-salt/src/main/resources/salt/salt/fluent/settings.sls
fluent databus plugin is available from cloudera public gem repo, so using that to installing it instead of using curl
the repo is not configurable yet so it's passed as a constant
=> CB-2140. Use cloudera public gem repo for install fluent-plugin-databus.

freeipa/src/main/resources/freeipa-salt/salt/freeipa/init.sls, freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/getkeytab.py
Add the get_keytab API to the FreeIPA API servier. The API was added
to the FreeIPA API server as a plugin.
This was manually tested by logging into to the FreeIPA server and
using the the ipa command line utility to call the get_keytab API.
Closes CDPSDX-518
=> CDPSDX-518 - Add the get_keytab API to the FreeIPA API server

core/src/main/resources/defaults/blueprints/cdp-de-llap.bp, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ConfigUtils.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveRoles.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnResourceManagerRoleConfigProvider.java
Implementation contains addition of valve configs to YARN needed for LLAP and addition of DE blueprint with LLAP.
That blueprint have not added to default ones yet, but we can add it later.
During cluster creation we need to use base image and override CM version and baseUrl:
`version: 7.x.0-1220014, baseurl: http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1220014/cm7/7.x.0/redhat7/yum/`
Configs should be added to YARN if blueprint contains LLAP, so this should be OK for now and anyone can test this following these step:
1. Create blueprint added in this PR as custom blueprint
2. During cluster creation override CM versions and using base image
=> DISTX-191 DE template to have LLAP

freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/model/Keytab.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/getkeytab.py, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtV1ServiceTest.java
Added the ability to create and retrieve keytabs. When creating a
keytab, the host and service principal are added. If they already
exist, the operation will proceed without an error.
If a keytab is created for the same service principal more than once,
only the latest keytab is usable. Prior keytabs are invalidated. The
retrieve operation can be used to retrieve an existing keytab without
invalidating the prior keytabs.
The result from the get_keytab API on the FreeIPA server was updated
to be structured similar to other FreeIPA APIs. This enables the
FreeIPA client to be used on the FreeIPA management service.
Unit tests were updated and the changes were manually tested using
the REST API on the FreeIPA management service. The keytabs were
validated against the FreeIPA server. …
=> CDPSDX-584: Add the implementation to create and retrieve keytabs

core/src/main/resources/defaults/blueprints/cdp-data-mart-ha.bp, core/src/main/resources/defaults/blueprints/cdp-data-mart.bp
Hive is still required for Hue, but at least we can remove Spark.
=> DISTX-195. Replace Hive-on-Spark with Hive-on-Tez in Data Mart

redbeams/src/main/resources/application.yml
redbeams now uses /redbeams/shared as its vault path instead of
/cb/shared.
Note: Verified that secret fields in the database show up as the new vault path.
```
15 | dbsvr-3a376221-2320-4e08-9944-6861dcd3577c |             | db.m3.medium | POSTGRES       |          40 | {"enginePath":"secret","engineClass":"com.sequenceiq.cloudbreak.service.secret.vault.VaultKvV2Engine","path":"redbeams/shared/databaseserver/rootusername/a502f36b-f639-41be-a6ec-dfaf2b7fa1a3-16bbaa1e62c"} | {"enginePath":"secret","engineClass":"com.sequenceiq.cloudbreak.service.secret.vault.VaultKvV2Engine","path":"redbeams/shared/databaseserver/rootpassword/c6d44782-1a34-4232-b2e1-b790cc838473-16bbaa1e6a2"} |               15 | {"engineVersion":"10.6","cloudPlatform":"AWS","backupRetentionPeriod":1} | cloudera  | 55432 …
```
=> CB-1812. Use /redbeams/shared vault path.

redbeams/src/main/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigServiceTest.java
Database and database server registration now test the connection as
part of the registration.
Note: My initial thought was that I was able to register databases with bad credentials because bad credentials passed the test connection. However, on further inspection, it looks like database registration didn't test the credentials at all, so this has been added.
Unit tests and manual tests have been run.
=> CB-1691. Test connection as part of database registration.

common/src/main/java/com/sequenceiq/cloudbreak/common/database/DatabaseCommon.java, common/src/test/java/com/sequenceiq/cloudbreak/util/DatabaseCommonTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigServiceTest.java
Redbeams no longer wraps the statements for creating a database and
associated user, or deleting them, in a transaction. The previous code
erroneously used a transaction on the redbeams database server, and not
on the target database server where the database resides; this ended up
having no practical effect.
PostgreSQL, the only database vendor currently supported by redbeams,
does not permit database creation in a transaction. Therefore, no
transaction is used for creation, or deletion. If some other vendors
allow transactions for these operations, then redbeams should be updated
to use them, just for those vendors, when support is added.
=> CB-1895. Remove transaction around db creation / deletion

core/src/main/resources/defaults/blueprints/cdp-sdx-ha.bp
Used cardinality to create lite SDX HA cluster following the lines of blueprint for medium SDX HA.
Verified the changed by creating an SDX cluster in Manowar-int using it.
This is a continuation of https://github.com/hortonworks/cloudbreak/pull/5354. It took a while to get back to it. This pull request address the comment you had there.
=> CB-1926: Update blueprint for SDX-HA lite using cardinality.

redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsApplication.java, redbeams/src/main/java/com/sequenceiq/redbeams/aspect/ControllerLogContextAspects.java, redbeams/src/main/java/com/sequenceiq/redbeams/configuration/AppConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/filter/MDCFilter.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/AbstractRedbeamsTerminationAction.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsCreationService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsTerminationService.java, redbeams/src/main/resources/logback.xml, redbeams/src/test/java/com/sequenceiq/redbeams/aspect/ControllerLogContextAspectsTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/filter/MDCFilterTest.java
Redbeams logging is improved in several ways. First, a new MDCFilter
inserts the request ID and user CRN associated with every request into
the MDC. Second, the new ControllerLogContextAspects aspect intercepts
calls to redbeams controllers and updates the MDC based on method
arguments. It is worth noting that the corresponding aspect in other
services also stores the request ID, but that is in fact redundant with
the filter.
The logback.xml file for redbeams is updated to match those of other
services. It pulls out expected values from the MDC, and so makes
log entries much more useful and relevant.
Additional logging has been added to AbstractRedbeamsTerminationAction
and RedbeamsTerminationService, to bring them in line with corresponding
logging during the creation flow.
=> CB-1818 Update redbeams logging

autoscale/src/main/resources/schema/app/20190709065638_CB-1859_set_crn_to_stack.sql
CB-1898 remove stack crn uq constraint from periscope history table
=> CB-1898 remove stack crn uq constraint from periscope history table

redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DBStackToDatabaseServerStatusV4ResponseConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DBStackToDatabaseServerTerminationOutcomeV4ResponseConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/stack/DBStack.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/handler/RegisterDatabaseServerHandler.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/crn/CrnService.java, redbeams/src/main/resources/schema/app/20190711232220_CB-2365_add_resource_crn_to_dbstack.sql, redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java
When creating a redbeams managed database, the CRN is generated up front
and passed to the user as part of the status response. Similarly, the
CRN is now passed to the user as part of the termination response as
well.
Notes:
```
mike@mikework  ~/src/launchpad/cli   DIR9076  curl -k -H "Content-Type: application/json" -H "x-cdp-actor-crn: crn:altus:iam:us-west-1:cloudera:user:mike.wilson@cloudera.com" -d @/home/mike/createexternaldb.json http://localhost:8087/redbeams/api/v4/databaseservers/managed 
{"environmentId":"crn:altus:environments:us-west-1:cloudera:environment:b6b81d4f-c889-48a0-8168-ded330517a48","name":"mw-cb-alloc15","resourceCrn":"crn:altus:redbeams:us-west-1:cloudera:databaseServer:5047d12e-2ed7-4b08-96a9-bda7ddc87e2d","status":"REQUESTED","statusReason":""}% 
```
Also …
=> CB-2365. Allocate CRN prior to external database creation.

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/ServiceKeytabResponse.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/model/Keytab.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/getkeytab.py, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtV1ServiceTest.java
This backports the keytab changes into the 2.10 branch so that the DWX team can use them before the 2.11 sprint is complete.
Since this is a new feature being added to the RC branch, I want to call out that I have a deployment locally. The FreeIPA server was created successfully but the SDX cluster failed to provision with the reason "RuntimeException: Can not start provisioning, client error happened on Cloudbreak side: HTTP 400 Bad Request". The same error message is present when I locally deploy without this change.
=> Backport the kerberos keytab functionality to 2.10.

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DatabaseServer.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelper.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderDBTest.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/base/DatabaseV4Base.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/base/DatabaseServerV4Base.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/DatabaseServerV4Base.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/database/base/DatabaseV4BaseTest.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/base/DatabaseServerV4BaseTest.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/DatabaseServerV4BaseTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/database/DatabaseV4RequestToDatabaseConfigConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerV4RequestToDatabaseServerConfigConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/stack/DatabaseServer.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/handler/RegisterDatabaseServerHandler.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsCreationService.java, redbeams/src/main/resources/schema/app/20190712171448_CB-2366_Add_connection_driver_and_jar_to_stack_db_server.sql, redbeams/src/test/java/com/sequenceiq/redbeams/converter/database/DatabaseV4RequestToDatabaseConfigConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/v4/databaseserver/DatabaseServerV4RequestToDatabaseServerConfigConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/domain/DatabaseServerConfigTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/domain/stack/DatabaseServerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigServiceTest.java
The following kinds of redbeams API requests now fully support the
caller specifying the class name of the required JDBC driver and a
URL for a JAR from which the driver can be loaded.
* existing database (driver class name added)
* existing database server (driver class name added)
* new database server allocation (both added)
The various object converters used in these API calls are updated so
that they pass these values along. Notably, the database stack's
database server object lacked space for them, so columns were added.
RegisterDatabaseServerHandler, which registers newly created database
servers, now gets the values from the stack instead of just skipping
them.
Business logic is now responsible for explicitly filling in the class
name of the connection driver when it is missing …
=> CB-2366 Normalize redbeams treatment of connection information

freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserService.java
User the 'random' option to allow the ipa server to set a random password
for new users instead of generating a random password in the FMS.
=> DISTX-201. Use 'random' option when adding users to ipa

freeipa/src/main/java/com/sequenceiq/freeipa/entity/SyncOperation.java
This change ensures that the value contained in the Json successList
and failureList is never null by persisting an empty list onCreate
and when set to null.
=> CB-2182. Fix SyncOperation conversion

client-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/ClouderaManagerClientProvider.java
Raised the HttpClient timeout values of Cloudera Manager to 1 minute from the default, 10 seconds.
=> CB-1668 Raise timeout values of CM client to 1 min

redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/request/DatabaseV4Request.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/DatabaseServerV4Request.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/DatabaseServerV4Request.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/util/DatabaseVendorUtil.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/validation/ConnectorJarUrlForDatabaseVendorValidator.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/validation/DatabaseVendorAndServiceValidator.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/validation/ValidConnectorJarUrlForDatabaseVendor.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/util/DatabaseVendorUtilTest.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/validation/ConnectorJarUrlForDatabaseVendorValidatorTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/database/DatabaseV4RequestToDatabaseConfigConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/drivers/DriverFunctions.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/database/DatabaseV4RequestToDatabaseConfigConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/drivers/DriverFunctionsTest.java
Redbeams once again validates the connector JAR URL passed in requests
to register databases and database servers and to allocate new database
servers. The URL is required in a request unless PostgreSQL is being
used.
=> CB-2366 Restore validation of connector JAR URL

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizationStatus.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/exception/SyncOperationAlreadyRunningException.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/mapper/SyncOperationAlreadyRunningExceptionMapper.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/freeipa/user/SyncOperationToSyncOperationStatus.java, freeipa/src/main/java/com/sequenceiq/freeipa/entity/SyncOperation.java, freeipa/src/main/java/com/sequenceiq/freeipa/entity/util/ListFailureDetailsToString.java, freeipa/src/main/java/com/sequenceiq/freeipa/entity/util/ListStringToString.java, freeipa/src/main/java/com/sequenceiq/freeipa/entity/util/ListSuccessDetailsToString.java, freeipa/src/main/java/com/sequenceiq/freeipa/entity/util/ListToString.java, freeipa/src/main/java/com/sequenceiq/freeipa/repository/SyncOperationRepository.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/AcceptResult.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/CleanupSyncOperation.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/SetPasswordAcceptor.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/SyncOperationAcceptor.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/SyncOperationStatusService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncAcceptor.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/SyncStatusDetail.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UmsState.java, freeipa/src/main/resources/schema/app/20190715135810_add_version_and_filters_to_syncoperation.sql, freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/converter/freeipa/user/SyncOperationToSyncOperationStatusTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/entity/util/ListToStringTest.java
The FMS was enhanced to better track SyncOperations and reject
concurrent requests.
The syncoperation table was modified
to add the environmentList and userList columns to represent
the scope of the sync operation. The SyncOperation entity was
modified to use new AttributeConverters to hide the conversion
to/from Json.
When requested, the FMS will store the SyncOperation in the db
then check whether to accept the request or not based on other
active requests in the db.
The SyncOperationAlreadyRunningException was created and mapped
to 409 CONFLICT.
=> DISTX-266. Reject concurrent user sync requests

environment/src/main/java/com/sequenceiq/environment/environment/dto/telemetry/EnvironmentTelemetry.java
Although Telemetry stored in environment, we did . not get the response because of missing json creator
=> Missing Json Creator for EnvironmentTelemetry

cluster-ambari/src/main/java/com/sequenceiq/cloudbreak/ambari/AmbariClusterSetupService.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterSetupService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDatabusService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtSetupService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtTelemetryService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDatabusServiceTest.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtTelemetryServiceTest.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderService.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterDetailResponse.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterResponse.java, datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxClusterConverter.java, datalake/src/main/java/com/sequenceiq/datalake/entity/SdxCluster.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/ProvisionerService.java, datalake/src/main/resources/schema/mybatis/20190718101135_add_sdx_crn.sql, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java, mock-caas/src/main/java/com/sequenceiq/caas/util/IniUtil.java, mock-caas/src/main/resources/application.yml, mock-caas/src/test/java/com/sequenceiq/caas/grpc/service/MockUserManagementServiceTest.java, mock-caas/src/test/java/com/sequenceiq/caas/util/IniUtilTest.java
Contains a few changes:
- move altus credential reading to auth mock side (so from that point you will be able to provide your altus secret / access keypair for auth app - so the mock will send that back if you will try to create a keypair )
- use sdx STACK crn tp gather sdx id for telemetry publisher (also store sdx crn on stack side - nullable)
- installing telemetry publisher feature can be enabled by default without providing in the request (of course using in the request can install it even if it is disabled...it makes sense as this way as you can install TP manually anyway if you go to CM UI)
=> DISTX-258. Workload analytics installation improvements.

core/src/main/java/com/sequenceiq/cloudbreak/service/ServiceEndpointCollector.java
Simple change to change the generated url from `?host=<host>?port=<port>` to `?host=<host>&port=<port>`. The initial page will load from this URL, but subsequent traversals on the proxied UI will break.
=> CB-2581 Fix typo in HBaseUI gateway proxy URL

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCommonService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperation.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterCommonServiceTest.java
use plain text response for generate inventory hosts.
this way that can be used in cb-cli (swagger has problems with attachment response types for go)
=> Use string return type (plan/text) for inventory generation

redbeams/src/main/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverter.java
Redbeams can once again begin allocating a new database server when the
allocation request specifies network parameters.
In addition, a redundant call to the environment service made during a
data conversion is eliminated.
=> CB-2582 Fix redbeams server allocation when no network specified

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DatabaseServer.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelper.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelperTest.java
The following parameters for redbeams database server allocation are
now fully optional: allocated storage, backup retention period, engine
version. The server port also remains optional, as before.
Additionally, a type error in the cloud model's DatabaseServer object
is fixed, so that null allocated storage sizes may pass fully through
the necessary data conversions.
=> CB-2418 Make more redbeams db server parameters optional

redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/DatabaseServerV4Endpoint.java
swagger generate client -f http://localhost:8087/redbeams/api/swagger.json -c client -m model -t dataplane/api-redbeams
2019/07/23 14:45:51 validating spec http://localhost:8087/redbeams/api/swagger.json
The swagger spec at "http://localhost:8087/redbeams/api/swagger.json" is invalid against swagger specification 2.0. see errors :
- path param "environmentCrn" is not present in path "/v4/databaseservers/managed/status/name/{name}"
make: *** [generate-swagger-redbeams] Error 1
=> CB-2148 invalid api path variable

core/src/main/java/com/sequenceiq/cloudbreak/init/clustertemplate/ClusterTemplateLoaderService.java, core/src/main/java/com/sequenceiq/cloudbreak/init/clustertemplate/DefaultClusterTemplateCache.java
When the Cloudbreak run in a container, the cluster template is not found on the classpath.
=> CB-2533 Cluster definitions not visible in manowar

redbeams-api/src/main/java/com/sequenceiq/redbeams/api/RedbeamsApi.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/DatabaseV4Endpoint.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/DatabaseServerV4Endpoint.java, redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsApplication.java, redbeams/src/main/java/com/sequenceiq/redbeams/configuration/EndpointConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/configuration/SecurityConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/configuration/SwaggerConfig.java
Swagger configuration in redbeams is split out from general endpoint
configuration. The base path for the configuration is fixed so that it
includes the "/redbeams" context path for the service as a whole.
The API now documents the need for the x-cdp-actor-crn header for
authorization. Not only is this simply more accurate, but it causes the
Swagger UI to offer the option to set the header. Along with the
corrected base path, this makes the UI usable for performing redbeams
calls from a browser.
Unfortunately, the Swagger API documentation available at /v2/api-docs
is not working. My guess is that it's because the API controllers use
JAX-RS, and not Spring, for their annotations. This issue is already
overcome for other Swagger artifacts.
=> CB-2684. Improve Swagger docs for redbeams API

common/build.gradle, common/src/main/java/com/sequenceiq/cloudbreak/logger/MaskingPatternLayout.java, common/src/main/java/com/sequenceiq/cloudbreak/logger/format/CustomJsonLayout.java, common/src/main/java/com/sequenceiq/cloudbreak/logger/format/JsonLayoutFormat.java, common/src/main/java/com/sequenceiq/cloudbreak/logger/format/LayoutFormat.java, common/src/main/java/com/sequenceiq/cloudbreak/logger/format/LayoutFormatFactory.java, common/src/main/java/com/sequenceiq/cloudbreak/logger/format/SimpleLayoutFormat.java, core-api/src/main/java/com/sequenceiq/cloudbreak/logger/MaskingPatternLayout.java, gradle.properties
support JSON log output (based on property logger.format.json.enabled , or LOGGER_FORMAT_JSON_ENABLED env variable)
Can be considered as a POC. Idea is the propagate the log formatting into an interface which is created at startup (before spring bootstrap so im using System. calls to get env or properrty)
By default without enabling JSON output, it works as it worked before.
also added prefix options, so you can define how the fields from MDC map should look like (e.g.: userCrn -> cloudbreal.userCrn ...note, now we can use "." in prefix instead of "_" as i was problematic for fluend regex filter)
=> Support formatted JSON log output for cb components

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToTemplatePreparationObjectConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackV4RequestToTemplatePreparationObjectConverterTest.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxIdBrokerConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxIdBrokerConfigProviderTest.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java
This change injects mock user/group-to-role IDB mappings from `TemplatePreparationObject` (provided by #5664 as mock settings) in a new `KnoxIdBrokerConfigProvider`. Limitations:
* Could not be tested E2E with scenario "datalake & cloud storage locations" due to some blocker issues, but IDB mappings were correctly reflected in both CM and `/var/run/cloudera-scm-agent/process/14-knox-IDBROKER/conf/gateway-reloadable.xml`.
=> CB-2434 Add settings for AWS mappings

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ProcessAutoRestartInjector.java
Set `process_auto_restart: true` for Kafka and Knox, too.
Deployed SDX cluster, verified config sent to CM.
=> CB-2566. Enable process auto-restart for all SDX services

common/src/main/java/com/sequenceiq/cloudbreak/logger/format/CustomJsonLayout.java, common/src/main/java/com/sequenceiq/cloudbreak/logger/format/JsonLayoutFormat.java, common/src/main/java/com/sequenceiq/cloudbreak/logger/format/LayoutFormatFactory.java
remove fields that are not needed (throwable part is appended to the formatted message anyway + the simple log message is not that useful to include)
+ instead of a using mdc fields with prefix, we can embed that in a json (ES?Kibana can handle that)
also use timestamp without '@' as on fluentd side we are using the docker timestamp anyway for that (so it can be a different field as the origin)
=> Cleanup Json log formatter

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveOnTezServiceConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveRoles.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/tez/TezRoleConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/tez/TezRoles.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveOnTezServiceConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/tez/TezRoleConfigProviderTest.java, template-manager-cmtemplate/src/test/resources/input/clouderamanager-ds.bp
Derive tez.history.logging.proto-base-dir and hive.hook.proto.base-directory property values from hive.metastore.warehouse.external.dir for Hive/HMS Inserts to work with cloud storage
Closes #CB-2723
=> CB-2723 Derive tez.history.logging.proto-base-dir and hive.hook.proto.base-directory property values from hive.metastore.warehouse.external.dir

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyService.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/recipe/ClusterProxyDeregisterHandler.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyServiceTest.java
This change is to start using the Stack CRN as identifier when registering a cluster with Cluster Proxy service. We were using Cluster Id as the identifier previously, and there are consumers of Cluster Proxy service that depend on Cluster Id. Therefore to maintain backwards compatibility, we are registering with both the Cluster Id as well as the Stack CRN. We will remove the Cluster Id once all consumers switch to using Stack CRN.
=> CDPAM-129 | Cluster proxy registration with Stack CRN and Cluster Id

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/impala/ImpalaVolumeConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/VolumeConfigProviderTestHelper.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/impala/ImpalaVolumeConfigProviderTest.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/VolumeUtils.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/HostgroupView.java
CB-2695 :  Expose volume configuration templates to role config providers.
CB-2766 :  Initialize Impala Volume Configurations.
Closes #CB-2695
Closes #CB-2766
=> CB-2695, CB-2766 : Initialize Impala Volume Configurations

core/src/main/resources/defaults/blueprints/cdp-data-engineering.bp, core/src/main/resources/defaults/blueprints/cdp-de-llap.bp
Add Hue Load Balancer to the non-HA Data Engineering blueprint (and its LLAP version).  While there is only one Hue Server, Load Balancer is still required because Knox topology generator does not handle standalone Server (adb229cd86e8cad05bece04cf3ee36398df3703c).
Deployed data hub cluster with this blueprint.
=> DISTX-296. Hue Load Balancer missing from DE blueprint

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/AuthorizationClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java, grpc-common/src/main/java/com/sequenceiq/cloudbreak/grpc/altus/AltusMetadataInterceptor.java, idbmms-connector/build.gradle, idbmms-connector/src/main/java/com/sequenceiq/cloudbreak/idbmms/GrpcIdbmmsClient.java, idbmms-connector/src/main/java/com/sequenceiq/cloudbreak/idbmms/IdbmmsClient.java, idbmms-connector/src/main/java/com/sequenceiq/cloudbreak/idbmms/config/IdbmmsConfig.java, idbmms-connector/src/main/java/com/sequenceiq/cloudbreak/idbmms/exception/IdbmmsOperationException.java, idbmms-connector/src/main/java/com/sequenceiq/cloudbreak/idbmms/model/MappingsConfig.java, idbmms-connector/src/test/java/com/sequenceiq/cloudbreak/idbmms/config/IdbmmsConfigTest.java
Follow-up to  #5818. Wiring into Datalake service will come in a later PR.
Notes:
* `IdbmmsClient` cannot be unit tested because `IdBrokerMappingManagementGrpc.IdBrokerMappingManagementBlockingStub` is a `final` class (hence cannot be mocked easily).
* While `GrpcIdbmmsClient` could theoretically be unit tested, that would need the mocking of `makeWrapper()` and `makeClient()` via some nested factory classes. Even then `getMappingsConfig()` has a pretty trivial logic that is deemed not worth testing in its current form.
* `MappingsConfig` is an immutable POJO so it does not need to be unit tested.
=> CB-2719 Create IDBMMS gRPC client for fetching mappings

core/src/main/resources/defaults/blueprints/cdp-sdx-ha.bp, core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha.bp, core/src/main/resources/defaults/blueprints/cdp-sdx.bp
This pull requests addresses CDPSDX-693 - we wanted to chang the GUI label from "Hive" to "Hive Metastore".  i have deployed a cluster to verify the change.
Closes #CDPSDX-693
Closes #xxx
=> CDPSDX-693 - added display name for HMS in hive section.

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/altus/AltusIAMService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java
Nullpointer can happen as during cluster cleanup, machine user deletion happens outside of telemetry context (as it was moved out in a more common module)
=> Fix telemetry cleanup

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/KerberosMgmtV1Endpoint.java
The following APIs were fixed so that the response message contains
the exceptions error message when an exception is thrown:
/v1/kerberosmgmt/cleanupClusterSecrets (HTTP delete)
/v1/kerberosmgmt/host (HTTP delete)
/v1/kerberosmgmt/serviceprincipal (HTTP delete)
Closes #CDPSDX-726
=> CDPSDX-726 - Fix error messages for keytab management (rc-2.12)

core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-ha-700.json
Fix problems with HA cluster definitions:
* correct instance count for `master` and `quorum`
* make `gateway` the `GATEWAY` (the one with CM) instead of `master`, and change exposed ports accordingly
=> CB-2844. HA deployment fails due to invalid node counts

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java
for cloud storage logging, cluster folder generated as <cluster name>-<uuid from crn>, but as uuid contains "-", it's not clear where cluster name ends and uuid starts. So use "_" instead
=> Cloud storage logging: use "_ " instead of "-" between cluster name and UUID

core/src/main/resources/defaults/blueprints/cdp-sdx.bp
CDPSDX-699 - remove HDFS NFS Gateway from DataLake blueprints
tested via deployment of blueprint into datalake via cli.
Closes #CDPSDX-699
=> CDPSDX-699 - removed hdfs-nfs-gateway from datalake blueprint.

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
Storage location missing from SDX telemetry request
=> CB-2937. Storage location parameter is missing for S3 for SDX

datalake/src/main/resources/sdx/aws/cluster-light-duty-template.json, datalake/src/main/resources/sdx/aws/cluster-medium-duty-ha-template.json, datalake/src/main/resources/sdx/azure/cluster-light-duty-template.json, datalake/src/main/resources/sdx/azure/cluster-medium-duty-ha-template.json
- increased disk sizes according to tickets
- corrected root disk size for Azure templates as it was defaulting to 30gb
=> CB-2921 Root disk and attached disk size increased

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerExternalAccountService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerExternalAccountServiceTest.java
if cm cluster install flow step re-runs for some reason, it will try to re-create altus external account with the same name as it was created, so that api call can fail
can be solved easily just create an account with an additional uuid string
=> CB-2970. Telemetry publisher install fails with: account already exists error message

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/DatabaseService.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/AllocateDatabaseServerV4Request.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/DatabaseServerV4StackBase.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/DatabaseServerV4StackRequest.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/NetworkV4StackBase.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/NetworkV4StackRequest.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/SecurityGroupV4StackRequest.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/AllocateDatabaseServerV4RequestTest.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/DatabaseServerV4StackBaseTest.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/NetworkV4StackBaseTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverter.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverterTest.java
Some classes in the redbeams API model are renamed to avoid name
conflicts with other classes in the API model. This ensures that API
client code generated by Swagger is correct and complete.
=> CB-2935 Rename redbeams API model classes to avoid name conflicts

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java
make sure until we are not using enums for telemetry + generate new UI objects, WA enabled by default (if enabled globally), so would not run issues, until those changes are done
=> Enable WA by default until CB-2903 is not merged and wired on the UI

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UserModelDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/FailureDetails.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SetPasswordRequest.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SuccessDetails.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SyncOperationStatus.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeAllUsersRequest.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeOperationRequestBase.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeUserRequest.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/user/handler/SetPasswordHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/SyncOperationStatusService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/FmsGroup.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/FmsUser.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UmsState.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersState.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersStateDifference.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java, freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProviderTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserServiceTest.java, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java
This commit makes the various user sync apis behave more similarly.
The environment crn filter was pulled out into a base class for all
the requests (set password, sync all, single user sync). The User
and Group models were removed from freeipa-api since they are now
only used internally to the FMS. They have also been renamed to
FmsUser and FmsGroup to make it easier to distinguish from UMS
users/groups and IPA users/groups.
All APIs can handle machine users as well as users. Sync code paths
were consolidated internally to use a single method for entry to the
UserService. Parameters are assumed (and validated) to be non-null
to simplify the code and the user controller was updated to adhere
to this change.
Retrieving stacks matching an environment crn filter has been moved
into the …
=> DISTX-212. Cleanup inconsistencies in FMS user sync

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtTelemetryService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtTelemetryServiceTest.java
- need to use sdx type for WXM which is now datalake
- also add UT
=> DISTX-305. Telemetry publisher: update cluster type to DATALAKE instead of DISTROX

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
Less likely, but it is possible after user creation, UMS could answer with not found status (for an already existing user) - as we cannot use the crn from create machine user response (as if the user already exists, it throws an exception, possible on cluster install retries), we need to query it after the creation
=> CB-3023. Machine user could be not found by the UMS client, right after creation

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
actor is not a machine user so CRN, so it cannot get machine user details by itself. (copied that from a few lines below, but that is invalid for dbus user)
=> CB-3054. Invalid Machine user Crn during Machine user creation.

core/src/main/resources/defaults/blueprints/cdp-sdx.bp
CDPSDX-716 - suppress warning for single zookeeper
2nd attempt for zookeeper config change to suppress.  previous pull request was denied due to changes in the 2 HA blueprints.  this pull request only includes changes to the NON-HA blueprint.
Closes #CDPSDX-716
=> CDPSDX-716 - suppress warning for single zookeeper

core/src/main/resources/defaults/blueprints/cdp-sdx-ha.bp, core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha.bp, core/src/main/resources/defaults/blueprints/cdp-sdx.bp
Notes:
Please take a moment to review this code change.  The change is a single property to enable delegation tokens in kafka.  (for all 3 blueprints)
Testing:
1. set value in CM ui, then exported blueprint to verify that the location and value for the config in the blueprint.
2. provisioned a datalake with the cdp-sdx.bp + this 1 change.
3. logged into provisioned cluster and verified key was configured with the expected value.
Closes #OPSAPS-51980
=> OPSAPS-51980 - enable delegation tokens in Kafka

core/src/main/resources/defaults/blueprints/cdp-sdx-ha.bp, core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha.bp, core/src/main/resources/defaults/blueprints/cdp-sdx.bp
CDPD-2339 - Disable ability to create local users in Atlas
simple config addition to atlas to disable local users.  
{
"name": "atlas_authentication_method_file",
"value": "false"
},
Closes #CDPD-2339
=> CDPD-2339 - Disable ability to create local users in Atlas

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifester.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifesterTest.java
creating cloud storage request behavior for SDX with internal SDX stack request:
- if cloud storage data is filled in sdx request use that
- if cloud storage data is not filled in sdx request but sdx internal request has, use that
- if logging is enabled, enrich cloud request with that, if none of the above 2 is enabled, create a new cloud request with logging
- if any from the above 3 is enabled, enrich with s3 guard dynamo table (if it has not set already in sdx internal request and it is enabled)
added a lot of logging as well
added new UTs
=> CB-3041. Consider SDX internal request for cloud storage request manifester

redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/DatabaseServerV4Endpoint.java
The Swagger @Api annotation for DatabaseServerV4Endpoint once again
describes the use of the user CRN header for authorization. Its presence
was causing problems for implementing the Cloudbreak (dp) CLI commands
for redbeams, but I found that simply passing a null value for the
authorization information to the generated client worked. This means
that both the Cloudbreak CLI and the Swagger UI console function for
redbeams.
---
I tested this by successfully using the CLI, with regenerated client code, on both my local Cloudbreak and on manowar-dev. In the CLI, I just pass `nil` for the authorization information, and there's no problem.
I will put up a separate PR up for the CLI modifications, including the regenerated redbeams client, in the hortonworks/cb-cli repository.
=> CB-2909 Restore Swagger authorization annotation for redbeams

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java
calculate sdx id from sdxcluster crn (not from stack crn of the sdx cluster),
as datalake api was introduced on distrox side, that can be done during request processing.
Workload analytics has attributes that can override CM service component settings, so using that if SDX response is available.
(if not available, will work as is it worked before - will try to use stack crn, if that also not available, will generate a random uuid)
=> CB-3001. Use sdxcluster crn instead of stack crn of SDX for telemetry publisher

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentClusterType.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigService.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/cloud/CloudStorageConfigGenerator.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/cloud/CloudStorageFolderResolverService.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/cloud/S3ConfigGenerator.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/cloud/WasbConfig.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/cloud/WasbConfigGenerator.java, common/src/test/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigServiceTest.java, common/src/test/java/com/sequenceiq/cloudbreak/telemetry/fluent/cloud/CloudStorageFolderResolverServiceTest.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java
as it was requested, we are storing the full path of the log locations on the stack side (so that can be gathered by the api, detailed responses will contain the generated full path), enrich the env based telemetry location with cluster details,
so for example, env response:
```
"telemetry": {
"logging": {
"s3": {
"instanceProfile": "arn:aws:iam::980678866538:instance-profile/oszabo-s3-access"
},
"storageLocation": "s3://oszabo"
}
}
```
stack response:
```
"telemetry": {
"logging": {
"s3": {
"instanceProfile": "arn:aws:iam::980678866538:instance-profile/oszabo-s3-access"
},
"storageLocation": "s3://oszabo/cluster-logs/datahub/oszabo-distrox-1_0fc69cab-c421-4948-bbdd-b86b6ba178b3"
}
}
```
also make enum from some built-in constants
=> CB-2959. Telemetry: Store full cloud storage log path in DB (do not only set/generate for Salt pillars).

core-api/src/main/java/com/sequenceiq/cloudbreak/validation/CrnValidator.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/base/DatabaseV4Base.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/DatabaseServerV4Endpoint.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/database/DatabaseV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java, redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java
The database and database server test API endpoints for redbeams are
disabled, to eliminate the possibility of an outside, compromised
database server gaining access to redbeams or its hosting compute
resource. The endpoints may come back later once it's certain that they
can be implemented safely.
While testing, I found that CrnValidator was too strict and rejecting
null CRN values, which are valid in some cases. The validator now
permits nulls, and I added the @NotNull validation annotation in places
where the CRN really shouldn't be null.
=> CB-2687 Disable redbeams dbserver test endpoint

orchestrator-salt/src/main/resources/salt/salt/fluent/template/output.conf.j2
seems like fluentd can auto create bucket or containers by default, we should not do that so i will disable that behavior
=> DISTX-310. Fluentd should not auto create S3 bucket or WASB container.

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
User sync sets the login shell for ipa users to /bin/bash when adding
new users to IPA. This does not affect existing users.
=> CB-3039. Set user shell to bash

core/src/main/resources/defaults/blueprints/cdp-sdx-ha.bp, core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha.bp, core/src/main/resources/defaults/blueprints/cdp-sdx.bp
This change will suppress the 3 kafka warnings that were showing up in the datalake, based on the light duty blueprint.
Notes:
including all 3 blueprint changes, but only tested the lite-duty version. (HA is not supported in GA, but adding the configs now to avoid technical debt that must be done after GA for 1.1.
Tests performed: (only "cdp-sdx.bp")
deployed cluster in mow-dev, verified via CM API that these 3 configuration values are available in the current supported CM version.
deploy via CLI with configuration changes to verify that there were no provision errors when including the 3 values in the blueprint.
Closes #CDPSDX-715
=> CDPSDX-715 - suppress kafka warnings

core/src/main/resources/defaults/blueprints/cdp-data-engineering.bp
In the Data engineering blueprint CapacityScheduler should be the default, and hive the default acl for yarn.
Tested on Manowar.
Closes #xxx
Closes #xxx
=> CB-3080 Set CapacityScheduler as default scheduler for YARN in the Data Engineering blueprint

redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/database/DatabaseV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/database/DatabaseV4ControllerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigServiceTest.java
Redbeams no longer verifies connectivity for databases and database
servers before registration, because it relies on open JDBC access to
do so. Verification should be restored once redbeams uses salt / remote
access for database operations.
=> CB-2687 Disable db and db server verification upon registration

common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
Replaced SDX and SDX_CLUSTER by DATALAKE, marked unused Crn related enums as deprecated. @horadla23 @sodre90 @doktoric please review.
=> CB-2917 Datalake CRN uses sdx and sdxcluster instead of datalake

core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering.bp, core/src/main/resources/defaults/blueprints/cdp-data-science.bp, core/src/main/resources/defaults/blueprints/cdp-de-llap.bp
Adding HTTP mode to the default blueprints
=> CB-2878 - Hive Needs to be in HTTP Mode for Knox to Proxy J/ODBC Access

cloud-common/src/main/resources/application.yml, core/src/main/resources/defaults/blueprints/cdp-opdb-custom.bp, core/src/main/resources/defaults/clustertemplates/aws/aws-opdb-700.json
Two blueprints now: one for the cluster template, optimized for
the instance types in that template. A second with no configuration
optimizations.
=> CDPD-3127 Update OpDB blueprints and add first cluster template

freeipa/src/main/java/com/sequenceiq/freeipa/repository/SyncOperationRepository.java
The syncoperation table is used to track the set password and user sync
operations. environments/write permissions should not be required for
writing to this table. We should be able to check other rights instead,
e.g., environments/setPassword.
This commit loosens the rights check on saving to the syncoperation table
to environments/read to enable non-admin users to set their passwords.
DISTX-317 will follow up this change with a more meaningful treatment of
rights for sync operations.
=> CDPCP-578. Loosen rights check on the syncoperation table

core/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AwsMockAccountMappingService.java
=> CDPCP-540 Add user dpprofiler to mock ID Broker mappings

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/DatabaseService.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/DatabaseServerV4Endpoint.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/Notes.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/OperationDescriptions.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java
The redbeams API endpoints for getting the status of service-managed
database servers are eliminated, because the status information is now
available through the ordinary database server description endpoints.
DatabaseService in the datalake service is updated to use the general
database server description endpoint, with some glue code to translate
the description into a status response as before. It would be better for
the datalake service to transition completely to the general response,
but that is too extensive a change for me to be comfortable doing right
now.
=> CB-3148 Remove redbeams database server status API endpoints

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProviderTest.java
- because our config overrides the original values
=> CDPB-3228 Hue needs full blacklist 

cloud-aws/src/main/resources/templates/aws-cf-dbstack.ftl, common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java, common/src/test/java/com/sequenceiq/cloudbreak/auth/altus/CrnTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/AbstractRedbeamsProvisionAction.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/AbstractRedbeamsTerminationAction.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/crn/CrnService.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/provision/AbstractRedbeamsProvisionActionTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/termination/AbstractRedbeamsTerminationActionTest.java
The new Crn::getUserId method retrieves the correct value of the user ID
in a user CRN. For "type 0" CRNs, the user ID is the value after the
first slash character in the resource ID. Otherwise ("type 1"), the user
ID is the entire resource ID.
Redbeams now uses this interpretation of user ID. Specifically, user
names and IDs attached to stacks and used as the value fo resource tags
are now derived from the proper user ID of the owner CRN.
In addition, the maximum length of the "StackOwner" parameter in the
AWS database stack CloudFormation template is changed from 50 to a more
generous 200.
=> CB-3169 Fix redbeams handling of user ID in CRN

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClientTest.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/UmsAuthorizationService.java, authorization-common/src/test/java/com/sequenceiq/authorization/service/UmsAuthorizationServiceTest.java
!Letting all read rights checks through by skipping UMS call if the right ends with /read!
=> CB-3196 allow all read operations

core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/FileSystemConverter.java
Validation is now in place to prevent posting incomplete cloud storage identities, however those clusters, which were deployed before the validation are failing, because of null values. This change should enable the termination of those clusters.
=> CB-3145 Null check on cloud storage identity conversion

freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/CleanupService.java
CDPSDX-606 Cleanup the CM keytabs secrets
Delete the CM keytab secrets when deleting a cluster with CM. Add
kerberosmgmt delete APIs that use query parameters rather than the
entity body so that Jersey can validate the args. This fixes the
error "Entity must be null for http method DELETE" when using Jersey
clients.
Tested manually using a local cloudbreak deployment.
This pull request is for master so that it makes it into 2.13 rather than 2.12.
Closes #CDPSDX-606
=> CDPSDX-606 Cleanup the CM keytabs secrets

cloud-common/src/main/resources/application.yml, core/src/main/resources/schema/app/20190822084041_CB-3203_remove_CM_6_2_version_from_distrox.sql
Removed CM 6.2 templates and set it to default_deleted in database. @horadla23 @akanto please review.
=> CB-3203 remove CM 6.2 version from distrox UI

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelper.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsRdsInstanceView.java, cloud-aws/src/main/resources/templates/aws-cf-dbstack.ftl, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelperTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsRdsInstanceViewTest.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/aws/AwsDatabaseServerV4Parameters.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/aws/AwsDatabaseServerV4ParametersTest.java
Redbeams now supports parameterized choices for whether to deploy a
multi-AZ RDS instance (default is true) and for the storage type of the
instance. Because of a bug in the Go implementation of Swagger, the
multiAZ property must be a string instead of a Boolean, or else Go
clients will never sent a false value for the property.
=> CB-3166 Add multiAZ and storageType RDS options

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsTerminateService.java
When AwsRdsTerminateService fails to locate the CF template for a
database server to terminate, rather than fail, it now assumes that the
template has been properly deleted, and returns successfully (without
itself issuing a termination request). This prevents this likely common
occurrence from causing termination failures.
If a redbeams server is already in a DELETE_FAILED status because of
some earlier termination failure, it turns out you can issue another
termination and redbeams will try again. This provides an escape hatch
for failed terminations, by manually getting rid of the CF template and
then rerunning termination.
---
This is currently targeted at rc-2.12, but won't be merged without approval.
=> CB-3211 Skip RDS termination if CF template is missing

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/KerberosMgmtV1Endpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/doc/KeytabOperationsDescription.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/action/TerminationService.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/VaultPathBuilder.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/VaultPathBuilderV1Test.java
CDPSDX-800 Fix cleanup of kerberos secrets when deleting an env
Delete all vault secrets that are associated with an environment when
that environment is deleted. This prevents the secrets from remaining
in the control plane after the environment has been deleted.
Manually tested using a local development version of cloudbreak.
Closes #CDPSDX-800
=> CDPSDX-800 Fix cleanup of kerberos secrets when deleting an env

redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/DatabaseV4Endpoint.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/request/CreateDatabaseV4Request.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/Notes.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/OperationDescriptions.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ParamDescriptions.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/database/DatabaseV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseServerConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/handler/DeregisterDatabaseServerHandler.java, redbeams/src/main/java/com/sequenceiq/redbeams/repository/DatabaseConfigRepository.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/database/DatabaseV4ControllerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/domain/DatabaseServerConfigTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigServiceTest.java
The following improvements are in place for the redbeams database API:
* Redbeams now supports API endpoints for getting and deleting databases
by CRN. The paths of the existing corresponding endpoints that work by
environment CRN and name have been altered to include "name/", so that
the CRN-based endpoints are now primary.
* A database description may now be supplied in a database creation
request. If one is not present, then the description of the hosting
database server is used, as before.
* The multi-delete API operation now uses CRNs instead of names.
* Additional unit tests are uncommented / created.
* Some unnecessary code injections are removed.
=> CB-2480 Improve redbeams database API

core/src/main/resources/defaults/blueprints/cdp-sdx-ha.bp, core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha.bp, core/src/main/resources/defaults/blueprints/cdp-sdx.bp, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/config/ServerUtil.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/BasicSdxTests.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDelegationTokenConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDelegationTokenConfigProviderTest.java
**Changes**:
- Dynamic configuration of delegation token for Kafka. Some of our tests tries to create clusters with env without freeipa/kerberos, but the mentioned `delegation.token.enable` property with `true` value works only with kerberos enabled clusters.
- Make the mock/e2e tests runnable on localhost, avoid enhancing the usage of HTTPS on local deployments.
=> Dynamic configuration of delegation token for Kafka

orchestrator-salt/src/main/resources/salt/salt/fluent/template/databus_metering.conf.j2
applying fix to rc-2.12 (in order to test metering on mow dev on this week)
also will apply https://github.com/hortonworks/cloudbreak/pull/6082 as well but only after CDPCP-628 is fixed
=> CDPCP-606. Metering consumer failed to convert payload to MeteringEvent entity

secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/vault/VaultKvV2Engine.java
Deleting the vault kv version 2 secrets was fixed so that the key and
all values are fully deleted. Version 2 allows the secrets to be
versioned and keys can be undeleted. Version 2 also supports a
destroy which cleans up the data for a specific version so undelete
is not possible for that version. But if all versions are destroyed,
the key still remains stored without any versions of the value. The
key and all versions can be fully destroyed by deleting the metadata
for the secret. The delete operation was updated to delete the
metadata.
This was tested manually on a local build of cloudbreak. The vault
UI was checked to ensure the secret was actually deleted.
Closes #CB-3230
=> CB-3230 Fix deleting vault kv version 2 secrets

freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/VaultPathBuilder.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/VaultPathBuilderV1Test.java, secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/service/SecretService.java
CRN handling is cleaned up to use the Crn class to get the resource
rather than just using everything after the last ":".
NOTE: cluster-ambari/src/main/java/com/sequenceiq/cloudbreak/ambari/AmbariBlueprintPortConfigCollector.java still uses the last ":" rather than the using the CRN class. I didn't update this because I don't know how to test it and I think it may be deprecated. If this assumption is wrong, please let me know and I will change it there too.
Closes #CB-3243
=> CB-3243 Cleanup CRN handling from CB-2907

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/metering/MeteringConfigService.java, common/src/test/java/com/sequenceiq/cloudbreak/telemetry/metering/MeteringConfigServiceTest.java
seems like during a refactor, making uppercase value from metering service type  (that is used as a value in salt config) was removed at some point, adding uppercase stuff to metering config generator level
without uppercase DATAHUB value, metering application fails on it cannot use datahub as an enum on python level
=> Fix metering settings with lowercase service type

core/build.gradle, orchestrator-salt/src/main/resources/salt/salt/postgresql/init.sls, orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/conf_pgsql_max_connections.sh
Configure embedded postgres via Salt to allow 500 connections.
@akanto please review.
=> CB-2971 Increase DB max_connections from 100 to 500

README.md
Contains the following fixes:
* Formatting for IDEA menu labels, env vars, config settings, java class names, file names etc.
* Minor wording corrections, including improvements to some section headers
* Adding details for `freeipadb` (migration topic) and `auth-mock` (for testing changes for mock-UMS)
* Some leftover items for https://github.com/hortonworks/cloudbreak-deployer/pull/605 (access to container logs for new services); the rest was added in #6113
=> README fixes: formatting, wording, add auth-mock & freeipadb

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/KerberosMgmtV1Endpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/doc/KeytabModelDescription.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/doc/KeytabModelNotes.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/doc/KeytabOperationsDescription.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/HostKeytabRequest.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/HostKeytabResponse.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Host.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/VaultPathBuilder.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtV1ServiceTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/VaultPathBuilderV1Test.java
Adds keytab creation and retrieval for host principals to support CML
which needs to use the host principals to manage service principals.
The host principals have the ability to be created with privileges
such as service principal management by using a role.
The deletion operations for host, cleanupClusterSecrets, and
cleanupEnvironmentSecrets were updated to also delete the host
principal secrets.
Unit tests were added and it was also tested on a local cloudbreak
build.
Closes #CDPSDX-519
=> CDPSDX-519 Add keytab retrieval for host principals to support CML

core/src/main/resources/defaults/blueprints/cdp-data-engineering.bp
The Telemetry Publisher component in Cloudera Manager runs as the HDFS user in this context and needs to have permission to view all jobs in order to collect the YARN logs from S3 when cloud storage is enabled.
=> CB-3306. Add HDFS user to Yarn admin ACL

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDatabusServiceTest.java
query against machine user only if it exists or the response does not contain the machine user crn. if user already exists that means that is in the UMS index so we can safely send a get query. therefore we can avoid eventual consistency issues for machine user creation
edit: validated
=> CB-3298. Query machine user for crn only if user already exist during user creation.

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilder.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java, cloud-azure/src/main/resources/templates/arm-dbstack.ftl, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/azure/AzureNetworkV4Parameters.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/azure/AzureNetworkV4ParametersTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/network/NetworkParameterAdder.java
The "virtualNetwork" parameter in the redbeams AzureNetworkV4Parameters
class and the "vnets" parameter in the Azure connector's database stack
ARM template are renamed to "subnets", to reflect precisely what their
values need to be.
Bonus changes:
* Azure database server termination now continues without a failure if
the expected resource group to delete is missing.
* A missing implementation of NetworkParameterAdder::getVpcId for Azure
is filled in. Without this, database creation fails to start.
=> CB-3379 Rename dbserver virtual network parameters to subnets

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/doc/KeytabModelNotes.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/HostRequest.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/ServicePrincipalRequest.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Role.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/freeipa/RoleAddResponse.java
An optional way to delete roles was added to the kerberos management
delete host and delete service principal APIs. An attempt is made to
ensure the role is not in use, although the verification has a race
condition, the check will handle most common use cases and it is
better than nothing.
This was tested manually using a local deployment of cloudbreak.
Closes #CDPSDX-839
=> CDPSDX-839 Allow a role to be deleted when deleting a host or service

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/DatabaseServerV4StackBase.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/azure/AzureDatabaseServerV4Parameters.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/azure/AzureDatabaseServerV4ParametersTest.java
Redbeams now validates the following for Azure PostgreSQL allocation
requests:
* port number (true for AWS as well)
* backup retention days
* database version, pattern match only
* SKU capacity minimum
* SKU tier
In addition:
* The boolean parameters in AzureDatabaseServerV4Parameters are now
Boolean object types, so that omitted values can be represented
accurately.
* Error logging for ARM template deployment failure is much improved,
so that it's less necessary to go look in the Azure Portal for
details.
=> CB-3380 Add more validation to Azure PostgreSQL allocation requests

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelper.java, cloud-aws/src/main/resources/templates/aws-cf-stack.ftl, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelperTest.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/CcmParameterConstants.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/CcmParameters.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultCcmParameters.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultInstanceParameters.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultServerParameters.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultTunnelParameters.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/InstanceParameters.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/ServerParameters.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/TunnelParameters.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilder.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, core/src/main/resources/init/init.ftl, core/src/test/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilderTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackServiceTest.java, core/src/test/resources/azure-core-init.sh, core/src/test/resources/azure-gateway-init.sh, freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/image/UserDataBuilder.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java, freeipa/src/main/resources/init/init.ftl
With these changes, all the plumbing has been done for communicating
CCM parameters down through the freemarker templates to the cloud-init
user data script.
Specific changes include:
1. New model objects for CCM parameters, including server parameters
that represent information required to contact CCM, instance
parameters required to identify the instance to CCM, and tunnel
parameters which represent the tunnels to be registered with CCM.
2. The ability to pass the CCM parameters from the stack service
through the image service to the user data builder. Note that
with this commit, the CCM parameters are always absent. They
will be populated from communication with the mina management
service in a subsequent commit.
3. Updates to the freemarker templates for the cloud-init user data …
=> CB-2187. Add CCM tunnel registration to cloud-init.

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/ExposedService.java, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
Profiler admin and Profiler Metrics services need to expose API in Knox.
E.g
> https://10.97.81.21:8443/sumishra-env3/cdp-proxy/profiler-metrics/asset/metrics/repo?eventType=audit
>https://10.97.81.21:8443/sumishra-env3/cdp-proxy/profiler-admin/profilers/
SSO is not supported. No UI for these services. Currently, API is supported. Above API's would be used by DSS-APP
I could test this by launching an SDX cluster from local cloudbreak code and checked the file 
"/var/lib/knox/gateway/conf/topologies/cdp-proxy.xml" which contained the PROFILER_ADMIN and    PROFILER_METRICS service entries.
=> CB-3375: Added DataCatalog Profiler Services to expose services in Knox

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kudu/KuduRoles.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kudu/KuduVolumeConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kudu/KuduVolumeConfigProviderTest.java, template-manager-cmtemplate/src/test/resources/input/cdp-data-mart.bp, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/VolumeUtils.java
Initialize Kudu Volume Configs.
Based on discussions with @akanto  since CB does not provide Mount Paths associated with specific type of attched volumes like SSD, Magnetic Disk  to ConfigProviders,  the kudu volume configs are initialized based on default mount paths similar to all other Volume Initializations.
Closes #CB-3347
=> CB-3347 Kudu Volume Config Initialization

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java
AzureDatabaseResourceService now supports forcing termination of
database servers. Essentially, failure to delete the server's resource
group does not cause termination failure if the force flag is set.
=> CB-3390 Implement forced termination for Azure database servers

environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentApiConverter.java
Subnet IDs passed in the network portion of an environment creation API
request are once again carried forward into the converted network DTO by
EnvironmentApiConverter.
=> CB-3453 Preserve subnets in environment creation API request

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/CloudStorageDecorator.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/CloudStorageDecoratorTest.java
if you are setting `identities` field in cloud storage request (in distrox cluster template) to `null`, then log identity is not added to the identity list (not causing any issues with the UI or default flows with cb cli) -> main problem with this is if identities field is missing , generated go client will fill that as null (workaround is to set identities as empty [])
=> CB-3463. Log identity is not filled if identity is set to null manually for distrox template

orchestrator-salt/src/main/resources/salt/salt/metering/template/generate_heartbeats.ini.j2
metering log size is too small, so rotation happens really often, like in every 2 minutes. so increase the size setting to 10 MB
=> Increase default metering log size to 10 MB

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudSubnet.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsNetworkView.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsNetworkViewTest.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilder.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureNetworkView.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureNetworkViewTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/dto/Credential.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/CredentialService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/network/NetworkParameterAdder.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/network/SubnetChooserService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/network/SubnetListerService.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/cloud/CredentialToCloudCredentialConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/dto/CredentialTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/CredentialServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/network/NetworkParameterAdderTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/network/SubnetChooserServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/network/SubnetListerServiceTest.java
The task of listing subnets in an environment is refactored out of
AllocateDatabaseServerV4RequestToDBStackConverter into the new
SubnetListerService class. For AWS, the class behaves as the previous
code, simply listing all the subnets by their IDs. For Azure, the class
modifies each subnet, expanding out its ID into the complete Azure
resource ID. Some of the necessary information is already available in
the environment response, but the subscription ID must be retrieved from
the credential associated with the environment.
SubnetChooserService is still in use, but it is now aware of the cloud
platform and supports Azure. Since there are no AZ restrictons in Azure,
it just chooses all of the subnets.
Other changes:
* The new CloudSubnet::withId method makes it easy to create a new
subnet …
=> CB-3382 Support Azure environment subnets for redbeams

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
I think this was broken in commit fbbf20e9a5. Deployments now fail with:
Name: /var/lib/knox/cloudbreak_resources//topologies/cdp-proxy.xml
Comment: Unable to manage file: Jinja syntax error: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.; line 488
---
[...]
{% for hostloc in salt['pillar.get']('gateway:location')['PROFILER_SCHEDULER_AGENT'] -%}
<url>{{ protocol }}://{{ hostloc }}:{{ ports['PROFILER-SCHEDULER-API'] }}</url>
{%- endfor %}
</service>
{%- endif %}
{%- endif %}    <======================
</topology>
=> Fix missing endif from topology.xml.j2

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/ExposedService.java, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
Generate NiFi REST API service and provider param into cdp-proxy-api.xml
Closes #CB-3477
=> CB-3477 Make NiFi REST API accessible through cdp-proxy-api topology

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilder.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureDatabaseServerView.java, cloud-azure/src/main/resources/templates/arm-dbstack.ftl
The following parameters for Azure PostgreSQL database server creation
are now optional.
* skuCapacity - no default
* storageSize - defaults to 10 GB
* dbVersion - defaults to 10
* skuFamily - defaults to Gen5
* skuTier - defaults to GeneralPurpose
Azure PostgreSQL does not allow selecting a non-default port. Therefore,
the Azure connector now warns when the port is present, but otherwise
ignores what it is set to, if anything.
The default for geoRedundantBackup is changed from false to true, for
availability in case of a region-wide failure.
=> CB-3491 Allow more defaults for Azure database server allocation

environment-api/src/main/java/com/sequenceiq/environment/api/v1/credential/endpoint/CredentialEndpoint.java
verifyCredentialByName is duplicated - because of that swagger cannot generate the go client model from the swagger definition
=> Fix operation id duplication (swagger) - verify credential by name/crn

autoscale/src/main/java/com/sequenceiq/periscope/domain/FailedNode.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ClusterManagerHostHealthEvaluator.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/cm/ClouderaManagerHostHealthEvaluator.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandler.java, autoscale/src/main/java/com/sequenceiq/periscope/repository/FailedNodeRepository.java, autoscale/src/main/resources/schema/app/20190910083831_CB-3291_periscope_should_restore_instance_state_automatically.sql, autoscale/src/test/java/com/sequenceiq/periscope/modul/rejected/ClusterManagerHostHealthMonitorModuleTest.java, autoscale/src/test/java/com/sequenceiq/periscope/modul/rejected/RejectedThreadContext.java, autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/ClusterManagerHostHealthEvaluatorTest.java, autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/cm/ClouderaManagerClusterCreationEvaluatorTest.java, autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandlerTest.java, autoscale/src/test/java/com/sequenceiq/periscope/utils/ModelTest.java, common/src/main/resources/messages/messages.properties, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/AutoscaleV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/request/ChangedNodesReportV4Request.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/Notes.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AutoscaleV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java, core/src/main/resources/messages/messages.properties, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java
The issue was that, when no failed nodes detected then periscope didn't notify cloudbreak about that, so previous failed nodes didn't go into healthy state.
In the current solution periscope stores records about failed nodes and notifies cloudbreak when change happens in that. I also add more unit tests.
=> CB-3291 Periscope should restore the instance state automatically

datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageLocationValidator.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/cloudstorage/CloudStorageLocationValidator.java
there is a fluent call against logging in cloud storage validator, so it assumes logging could not be null, but on object level it could be as that fields (telemetry or logging) is optional.
=> Make cloud storage validator nullsafe (telemetry)

auth-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/usermanagement/UserManagementGrpc.java, auth-connector/src/generated/main/java/com/cloudera/thunderhead/service/common/options/Options.java, auth-connector/src/main/proto/options.proto, auth-connector/src/main/proto/usermanagement.proto, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java
The first commit updates the options and usermanagement proto files from thunderhead and regenerates the code. There are no manual changes in that commit.
The second commit modifies usersync to retrieve the workloadAdministrationGroupNames from the getRights response.
NOTE: I've only tested this with the mock ums so far. I intend to test this with the real ums tomorrow morning. I'll leave a comment here when I'm done with that.
=> CDPCP-743. Usersync adds workload administration groups

cloud-common/src/main/resources/application.yml, core/src/main/resources/defaults/blueprints/cdp-op-data-mart-710.bp, orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls, orchestrator-salt/src/main/resources/salt/salt/sssd/ntp/sysconfig_ntpd, orchestrator-salt/src/main/resources/salt/salt/sssd/template/ntp_conf.j2
This commit introduces a new blueprint which I've called the "active data
mart". The name is a reference to Active Data Warehouse, a term we often use
to describe a data warehouse that leverages Kudu for additional real-time
storage and query capabilities. The blueprint is based on the existing data
mart template, complete with custom Impala performance tuning. Besides the
obvious inclusion of Kudu, I've also added Spark (and a dependent YARN) for
eventual Kudu BDR support.
The topology itself consists of three masters (for HA) and four tablet
servers (for 3-4-3 replication). To minimize the effect of a failure, each
master and tablet server runs on its own node, which makes the minimal
cluster size seven nodes. The worker nodes are partitioned into a singleton
"coordinator" group running …
=> Initial commit of data mart blueprint with support for Kudu

orchestrator-salt/src/main/resources/salt/salt/fluent/template/output.conf.j2
s3 plugin has a pre-check against credentials (api key or instance profile), and if it fails it re-runs the input configuration setup.
basically, this mechanism stop any other plugins to work properly, so if the instance profile is wrong for s3, databus plugin won't work (for metering)
=> CDPCP-751. Metering for DataHub clusters is not working if S3 td-agent output is misconfigured.

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/CleanupService.java
Issue description found in JIRA. We need to make the cleanup process pollable and remove the underlying kerberos and ldap entities. This is a temporary solution to unblock everyone in the 1.1 release.
=> CB-3581 temporarily disable bind user deletion in IPA

cloud-common/src/main/java/com/sequenceiq/cloudbreak/message/Msg.java, common/src/main/java/com/sequenceiq/cloudbreak/message/Msg.java, common/src/main/resources/messages/messages.properties, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/FlowChainTriggers.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ConfigRegistrationRequest.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleFlowConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleFlowService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleState.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/ClusterProxyReRegistrationFailed.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/ClusterProxyReRegistrationRequest.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/ClusterProxyReRegistrationResult.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/ClusterProxyReRegistrationHandler.java, core/src/main/resources/messages/messages.properties
Introduced a new state in ClusterUpscaleFlowConfig that re-registers proxy configuration with cluster proxy service - only if the host groups is of type gateway. This is done because the private ip may change on repair.
On re-registration with cluster proxy, the existing public key certificate that knox token topology was configured with is returned. The assumption here is that we don't need to re-configure knox topology as part of repair flow. 
Have done some local testing on my machine. Needs to be tested on mow-dev.
=> CB-3388 | Re-registering with cluster proxy on cluster repair

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
Fix NiFi Knox role name in cdp-proxy-api topology jinja template.
Closes #CB-3477
=> CB-3477 Fix NiFi Knox role name in cdp-proxy-api topology

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformResources.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/nosql/CloudNoSqlTable.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/nosql/CloudNoSqlTables.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResources.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResourcesTest.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformResources.java, cloud-cumulus-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/cumulus/yarn/CumulusYarnPlatformResources.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformResources.java, cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockPlatformResources.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackPlatformResources.java, cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/platform/GetPlatformNoSqlTablesRequest.java, cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/platform/GetPlatformNoSqlTablesResult.java, cloud-reactor/build.gradle, cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/GetPlatformNoSqlTablesHandler.java, cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/service/CloudParameterService.java, cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/GetPlatformNoSqlTablesHandlerTest.java, cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/service/CloudParameterServiceTest.java, cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnPlatformResources.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/PlatformResourceEndpoint.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/PlatformResourceModelDescription.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/model/PlatformNoSqlTableResponse.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/model/PlatformNoSqlTablesResponse.java, environment/src/main/java/com/sequenceiq/environment/platformresource/PlatformParameterService.java, environment/src/main/java/com/sequenceiq/environment/platformresource/v1/PlatformResourceController.java, environment/src/main/java/com/sequenceiq/environment/platformresource/v1/converter/CloudNoSqlTablesToPlatformNoSqlTablesV1ResponseConverter.java, environment/src/test/java/com/sequenceiq/environment/platformresource/PlatformParameterServiceTest.java, environment/src/test/java/com/sequenceiq/environment/platformresource/v1/PlatformResourceControllerTest.java, environment/src/test/java/com/sequenceiq/environment/platformresource/v1/converter/CloudNoSqlTablesToPlatformNoSqlTablesV1ResponseConverterTest.java
Remove DynamoDB table after environment cleanup.
Only do so if the table did not exist before AND if no other environments are referencing it.
=> CB-3003 Add NoSQL tables listing to environment platform service

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/config/CloudbreakServer.java
test framework validates parameters with wrong parameter name
Closes CB-3628
=> CB-3628 test framework validates parameters with wrong parameter name

orchestrator-salt/src/main/resources/salt/bootstrapnodes/mount-disks.sh
=> CB-3578 ephemeral disk list is not parsed correctly

redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseServerConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/handler/DeregisterDatabaseServerHandler.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/test/java/com/sequenceiq/redbeams/domain/DatabaseServerConfigTest.java
Deletion (actually archival) of service-managed database servers by
redbeams now includes setting a correct deletion timestamp. This allows
database server names in an environment to be reused as expected.
This change temporarily removes one useful feature: archival of
databases in a database server when that server is deleted. However,
this will be restored by work in CB-3638.
=> CB-3639 Correct service-managed database server deletion

redbeams/src/main/java/com/sequenceiq/redbeams/service/network/SubnetChooserService.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/network/SubnetChooserServiceTest.java
Rather than selecting exactly two subnets from different AZs for an RDS
instance's DB subnet group, redbeams now selects all available subnets,
while still verifying that the subnets are spread across at least two
AZs.
=> CB-3441 Select all subnets for RDS DB subnet group

common/src/main/java/com/sequenceiq/cloudbreak/logger/MDCBuilder.java, usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/LoggingUsageReporter.java
cloudbreak_log_message is not used anymore for fluentd, we are producing json output on manowar, message field is used only for the full message.
usage collection requires only the message part of the log message in binary format, so im putting this to mdc context in a dynamic way (that is processed as a context field in EK index), so the new output would be like this for usage events:
logger: CDP_BINARY_USAGE_EVENT
context.requestId: \<request id\>
context.binaryUsageEvent: \<binary event\>
=> CB-3699. Add cdp binary usage event to mdc context

cluster-dns-connector/src/main/java/com/sequenceiq/cloudbreak/certificate/service/CertificateCreationService.java, cluster-dns-connector/src/test/java/com/sequenceiq/cloudbreak/component/CreateCertificationTest.java, common/src/main/java/com/sequenceiq/cloudbreak/certificate/PkiUtil.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/repair/master/ha/ChangePrimaryGatewayService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationService.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/recipe/ClusterProxyDeregisterHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/gateway/GatewayPublicEndpointManagementService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java
Changes:
- SAN support in CSR generation, which is now disabled as PEM doesn't support SANs
- Separate the PEM service related logic into an individual service in core and call the `cluster-dns-connector` module from there
- Move the new service to be wired after host metadata setup to internal FQDNs be available
The only refactor that needs to be done is to create a new flow step for this logic.
=> Refactor of Public Endpoint Management service related logic

redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/responses/DatabaseV4Response.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/database/responses/DatabaseV4ResponseTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/database/DatabaseConfigToDatabaseV4ResponseConverter.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseServerConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigService.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/database/DatabaseConfigToDatabaseV4ResponseConverterTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/domain/DatabaseConfigTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/domain/DatabaseServerConfigTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbconfig/DatabaseConfigServiceTest.java, redbeams/src/test/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigServiceTest.java
When a service-managed database server is deleted (as part of
deregistration after termination), the databases that were created by
redbeams on it are deleted first. Otherwise, deletion, which is actually
archival, happens as before.
Both DatabaseConfig and DatabaseServerConfig now have implementations of
the unsetRelationsToEntitiesToBeDeleted which clear out relations from
those entities to each other as part of the deletion (archival) process.
For simplicity, the DatabaseConfigService::deleteOne method is renamed
to simply delete, overriding but calling to its superclass
implementation. The full implementation of the method accepts a
skipDeletionOnServer flag, so that database deletion due to a database
server deletion does not try to contact the deleted server; at that
point, the …
=> CB-3638 Delete service-managed dbs when server deleted

freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/VaultPathBuilder.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/VaultPathBuilderV1Test.java
If a cluster CRN which was formatted in an invalid way was provided
to the cleanup cluster secrets API, previously all secrets for the
entire environment would be deleted. This fix throws exceptions when
and invalid CRN is provided.
Testing was performed manually using a local deployment of cloudbreak
and unit tests were added.
In https://github.com/hortonworks/cloudbreak/pull/6093, there was a discussion about whether or not we should throw exceptions for invalid CRNs. At the time, the thought was to require a valid CRN for the environment since it must match and to ignore invalid cluster CRNs since it was optional. The problem with ignoring the invalid CRN is that recursive deletes will now delete a vault path which does not have the CRN so it will delete the secrets from all CRNs. …
=> CDPSDX-935 Fix invalid cluster CRNs from deleting wrong vault secrets

cloud-common/src/main/java/com/sequenceiq/cloudbreak/polling/PollingService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtSetupService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerRoleRefreshService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerApplyHostTemplateListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerDecommissionHostListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerDeployClientConfigListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerGenerateCredentialsListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerHostStatusChecker.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerKerberosConfigureListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerParcelActivationListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerParcelRepositoryRefreshChecker.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerRefreshServiceConfigsListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerRestartServicesListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerServiceStartListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerStartManagementServiceListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerStartupListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerStopListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerStopManagementServiceListenerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerTemplateInstallationChecker.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosServiceTest.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerRoleRefreshServiceTest.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerTemplateInstallationCheckerTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/TlsSetupService.java
This change is necessary for two reasons:
- Task is a unit of work that can be passed to an executor to execute it. Therefore a task must be instantiable and should be able to store state. The executor in our case is the PollingService.
- For this task: https://jira.cloudera.com/browse/CB-3749
=> CB-3734 - Instantiating CM tasks instead of using them as services

core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ImageCatalogValidator.java, core-api/src/test/java/com/sequenceiq/cloudbreak/api/model/imagecatalog/ImageCatalogV4BaseTest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/credential/model/request/CredentialRequest.java, integration-test/src/main/java/com/sequenceiq/it/TestParameter.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/PurgeGarbageService.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/ImageCatalogMockServerSetup.java
This changeset contains the following minor improvements to integration
testing.
* CredentialRequest now has a toString method.
* ImageCatalogValidator now includes the URL that failed validation in
its constraint violation message.
* ImageCatalogMockServerSetup now logs when it has started the
"prewarmed" URL, as it does for other URLs.
* Spelling is fixed in various log lines and variables.
=> Make small improvements to integration testing

integration-test/src/main/java/com/sequenceiq/it/config/IntegrationTestConfiguration.java
When loading Spring configuration properties,
IntegrationTestConfiguration now conforms to the defined Spring Boot
priority order for property sources. If a lower-priority source has a
value for a property, it no longer replaces one from a higher-priority
source.
=> CB-3757 Honor Spring Boot property loading in IT config

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/UtilV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/responses/ResourceEventResponse.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UtilV4Controller.java
CB-3780 – wrap ResourceEvent enum on postNotificationTest
=> CB-3780 – wrap ResourceEvent enum on postNotificationTest

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserService.java, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java
- Since we get all groups from UMS, therefore we should get all groups from FreeIPA. This way, diff for groups is always based on all groups.
- Getting only those users those are passed in as an argument. Sync will be performed only for those users.
- If none of the users is provided, we still go and fetch all users and sync all eligible users for the given environment.
Closes DISTX-327
@handavid @keyki @lacikaaa
=> DISTX-327 changes for set of user sync:

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/DeletableEnvironmentTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/DeletableTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/EnvironmentSettingsV4TestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/blueprint/BlueprintTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/clustertemplate/ClusterTemplateTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/clustertemplate/DistroXTemplateTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/credential/CredentialTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/database/DatabaseTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/database/DatabaseTestTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDtoBase.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIPATestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/imagecatalog/ImageCatalogTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/kerberos/KerberosTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/kubernetes/KubernetesTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ldap/LdapTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/mpack/MPackTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/proxy/ProxyTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/recipe/RecipeTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxRepairTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTemplateTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDtoBase.java
* In TestContext, the spelling of the "handleExceptionsDuringTest"
method is fixed.
* In AbstractTestDto, the spelling of the method
"resourcePropertyProvider" is fixed.
=> CB-1692 Fix some spelling / grammar in integration tests

orchestrator-salt/src/main/resources/salt/salt/ntp/init.sls, orchestrator-salt/src/main/resources/salt/salt/top.sls
The time synchronization status quo as of commit 909127e is that
provisioned VMs will use their out-of-the-box time service and
configuration as-is. For CDP CentOS 7 VMs, this means using chronyd to sync
with public NTP pool servers on the Internet.
Not all deployments will have Internet access, however. In fact, we've seen
some sporadic instances[1] where the NTP port appears to be blocked. To fix
this, let's reconfigure the VMs to incorporate whatever time sync service is
prescribed by the relevant cloud provider. Given our exclusive use of
CentOS 7 VMs I only bothered to do so for chronyd.
Note: I've only tested AWS deployments. Azure is especially frustrating
since the recommendation is to forgo NTP-based sync in favor of their Linux
Integration Services, so I've held off on that.
=> Configure VMs with cloud provider NTP servers

common-model/src/main/java/com/sequenceiq/common/api/telemetry/base/FeaturesBase.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/base/TelemetryBase.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/doc/TelemetryModelDescription.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/Features.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/Telemetry.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/request/FeaturesRequest.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/request/TelemetryRequest.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/response/FeaturesResponse.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/response/TelemetryResponse.java, common-model/src/main/java/com/sequenceiq/common/api/type/FeatureSetting.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/telemetry/EnvironmentFeatures.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/telemetry/EnvironmentLogging.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/telemetry/EnvironmentTelemetry.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/telemetry/EnvironmentWorkloadAnalytics.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/TelemetryApiConverter.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/TelemetryApiConverterTest.java
that is for 2.13
idea:
- support new fields in saved json and in objects
-> on the follow up  change (after that is deployed already) , if an older request will be persisted, it will persist things like metering in the new features object, so that can be processed by that actual or new cb/env pod as well
cluster deployment testing is done - i have tried out to use an old model for telemetry json + create a new one, which persisting features object as well - deployment did not stack on telemetry parsing + s3 logs where generated (+ contained metering data)
=> CB-3210. Update telemetry model (v2) - less strict JSON as first step

environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EnvironmentCreationValidator.java
CB-3849 – upon env creation with new VPC an alert comes
brief expl.: based on how the ui sends the new env. request, if the network CIDR has not set, we take it as a new network creation request on our side
=> CB-3849 – upon env creation with new VPC an alert comes

freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtV1ServiceTest.java
The APIs to get service principal and host principal keytabs have a
role request in them because they reuse the same request type as the
post operation which sets the roles. The get operations no longer
allow the role request to be provided (it used to just silently
ignore it).
This was tested in a stand alone deployment of cloudbreak and by
using unit tests.
Closes #CDPSDX-995
=> CDPSDX-995 Require the role request to be empty for keytab retrieval

auth-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/usermanagement/UserManagementGrpc.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java, auth-connector/src/main/proto/usermanagement.proto, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/CleanupSyncOperation.java, freeipa/src/main/resources/application.yml, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java, mock-caas/src/main/resources/application.yml
These commits update the usermanagement.proto, regenerate the code, and update the MockUserManagementService. As part of this update, a fix to the MockUserManagementService is included that uses the specified accountId when retrieving users or machine users.
There is a small unrelated change in a separate commit to make the syncoperation cleanup schedule configurable.
=> CDPCP-721 part1

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersState.java
In case, if the set of users are passed and the call is not for "user sync all" then, if one of the pre-existing user's access is being changed in CDP, (removed user from env), then handleUser method will filter-out that user and the user will not be removed in IPA.
Currently, we are adding a new map in UserState but later we should have something like "UserSyncRequestContext" and all needed state should be composite in that including user state, ipa state, and additional information.
Closes DISTX-327
=> DISTX-327 - This change is for left out users.

template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/GeneralClusterConfigsProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/smm/StreamsMessagingManagerServiceConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/smm/StreamsMessagingManagerServiceConfigProviderTest.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/model/GeneralClusterConfigs.java
Initialize SMM Config With CM FQDN instead of CM IP Address.
Closes #CB-2682
=> CB-2682 Initialize SMM Config With CM FQDN

orchestrator-salt/src/main/resources/salt/salt/fluent/template/input.conf.j2
Add config changes to have fluentd pick-up autossh logs from
/var/log/autossh-*.log
=> Have fluentd pick-up autossh logs

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserServiceTest.java
This is a minor fix to retrieve the full user state from ipa instead of the filtered user state when performing a full user sync.
=> CDPCP-854. Retrieve full ipa user state for full user sync

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactoryTest.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxRepairRequest.java, datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRepairService.java
- Previously datalake only allowed one host to repair now, it can handle multiple hosts as well.
- Previously during multi host repair when a gateway and a core node were unhealthy the core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java would have generate an incorrect flow where it adds a cluster downscale event to the flow for thee idbroker host. This is problematic because during this process the master might not be available so that the salt's tearDown wont work.
=> CB-3804 Allow multiple host repair.

core-api/src/main/java/com/sequenceiq/cloudbreak/validation/CrnValidator.java, integration-test/build.gradle, integration-test/docker-compose_template.yml, integration-test/integcb/Profile_template, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RedBeamsTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RedbeamsClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/database/RedbeamsDatabaseCreateAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/database/RedbeamsDatabaseCreateIfNotExistsAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/database/RedbeamsDatabaseDeleteAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/database/RedbeamsDatabaseListAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/database/RedbeamsDatabaseTestAssertion.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/RedbeamsDatabaseTestClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/config/CliProfileReaderService.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/config/RedbeamsServer.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/config/ServerUtil.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractRedbeamsTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/DeletableRedbeamsTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/database/RedbeamsDatabaseTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RedbeamsDatabaseTest.java, integration-test/src/main/resources/application.yml, redbeams-api/build.gradle, redbeams-api/src/main/java/com/sequenceiq/redbeams/client/RedbeamsApiKeyClient.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/client/RedbeamsApiKeyEndpoints.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/validation/DatabaseVendorAndServiceValidator.java, redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/database/request/DatabaseV4RequestValidationTest.java
RedbeamsDatabaseTest is the first integration test for the redbeams
service. It tests database registration, like the older DatabaseTest
does for the core cloudbreak service.
There are many ancillary classes introduced in order to make the
integration test possible.
* RedbeamsApiKeyEndpoints and RedbeamsApiKeyClient: These objects make
it feasible for integration tests, or other code, to call redbeams
passing in the necessary Altus API key headers for redbeams calls.
* RedbeamsDatabaseTestDto: This holds the request and response for
database registration tests.
* DeletableRedbeamsTestDto and AbstractRedbeamsTestDto: These are common
base classes for all redbeams integration test DTOs, including
RedbeamsDatabaseTestDto.
* RedbeamsDatabaseTestAssertion: This class is a factory for functions …
=> CB-1692 Create first redbeams integration test

core/src/main/resources/defaults/blueprints/cdp-opdb-702.bp
Increase `hbase.hstore.blockingStoreFiles` configuration value to 50 for HBase RegionServers.
=> CDPD-4781 Increase HBase max blocking store files

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilder.java, cloud-azure/src/main/resources/templates/arm-dbstack.ftl, core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProvider.java, core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbServerConfigurer.java, core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProviderTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbServerConfigurerTest.java, datalake/src/main/java/com/sequenceiq/datalake/configuration/AppConfig.java, datalake/src/main/java/com/sequenceiq/datalake/flow/create/handler/RdsWaitHandler.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/DatabaseConfigKey.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/DatabaseService.java, datalake/src/main/resources/sdx/azure/database-custom-template.json, datalake/src/main/resources/sdx/azure/database-light-duty-template.json, datalake/src/main/resources/sdx/azure/database-medium-duty-ha-template.json, datalake/src/main/resources/sdx/mock/database-custom-template.json, datalake/src/main/resources/sdx/mock/database-light-duty-template.json, datalake/src/main/resources/sdx/mock/database-medium-duty-ha-template.json, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/DatabaseConfigKeyTest.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/DatabaseServiceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterCreationTest.java, orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/init_db.sh, orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/init_db_remote.sh
A datalake / SDX cluster may now be created in an Azure environment,
although not with an external database server, yet.
First, the subnet checks in RdsWaitHandler now only apply to AWS. They
are unnecessary for Azure. With this change alone, it is possible to
create an Azure datalake without having redbeams create an external
database server.
SDX templates are introduced for Azure, to go along with the existing
ones for AWS. Currently, the templates are identical, each calling for a
GP_Gen5_2 instance for the database server. The map of templates in
DatabaseService was keyed only by SDX cluster shape, but is now keyed by
both cluster shape and cloud platform.
TLS is disabled for new Azure database servers. This is done because the
Cloudera Manager code which is responsible for creating …
=> CB-3791 Begin enabling Azure datalakes (no external db servers yet)

datalake/src/main/resources/sdx/azure/cluster-light-duty-template.json
Removed override of topology name and SSO type. 
I don't know how to test this currently, but wanted to open a PR to get some reviews.
=> CB-3975 Azure - Don't override topology name and SSO type

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
NiFi needs to have the useTwoWalSsl parameter in order to authenticate Knox to NiFi. Added to NiFi Registry as well since they use a similar authentication mechanism. If NiFi is not configured for TLS, then this should have no affect since HTTP client won't send the client certificate.
=> CB-3856 Knox - NiFi service needs useTwoWaySsl parameter

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/security/InternalCrnBuilder.java, auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/security/CrnUserDetailsServiceTest.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/doc/DistroXOpDescription.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXInternalV1Endpoint.java, core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/StackApiViewRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackApiViewService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperation.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXInternalV1Controller.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/EnvironmentServiceDecorator.java, core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/RestUrlParserTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/StackOperationTest.java
Requirement:
- have an ability to get some stack details (env crn/name, stack crn/name, stack create/terminate timestamp) based on a crn for an internal user 
Solution:
- added **internal** distrox endpoint (similar as sdx internal) - that is for internal usage inside Control Plane, so that is the name right now, that can be changed in another commit if that needs to be changed (like support by a query param like tenantUnawere or something . else)
- use INTERNAL role for the operation (that can be re-used) - map to AUTOSCALE role only for autoscale (as that is internal from CB perspective)
edit: use only default iam internal actor
testing is in progress ...
manual tests looked ok
=> CB-3842. Add get DistroX api endpoint for internal CB user

freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtRoleComponent.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtRoleComponentV1Test.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtV1ServiceTest.java
When adding a role for creating host keytabs and service principal
keytabs. The permissions were not checked to ensure they exist. This
check has been added and the roles are only created if the
permissions already exist.
Although there is a slight race condition, if a permission is removed
concurrently while creating one of the roles, it is possible that the
role is created and the permission does not exist. It is better to
have the check even if it is not perfect.
Closes #CDPSDX-994
=> CDPSDX-994 Add validation that permissions exist when creating roles

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
Currently in logs password also gets leaked. As a temp fix, we can remove param map from logs. 
Closes CDPCP-871
=> CDPCP-871 - removing parameter map since it leaks password

freeipa/src/main/java/com/sequenceiq/freeipa/entity/UserSyncStatus.java, freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java, freeipa/src/main/java/com/sequenceiq/freeipa/repository/UserSyncStatusRepository.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsEventGenerationIdsProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncStatusService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UsersyncPoller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UmsEventGenerationIds.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java, freeipa/src/main/resources/application.yml, freeipa/src/main/resources/schema/app/20191015100823_CDPCP-721_create_usersync_status.sql, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UmsEventGenerationIdsProviderTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UsersyncPollerTest.java
This commit supports the automatic user sync feature by polling the UMS
for changes in each account. The UMS now provides an API for retrieving
event generation ids.
A UserSyncStatus model is added to the database to hold the event generation
ids for the last successful full user sync for each environment. A poller
class is added that runs on a configurable interval. The poller retrieves
the event generation ids from the UMS, compares them to the stored event
generation ids, and triggers the user sync if the ids do not match.
=> CDPCP-721. Trigger user sync through polling event generation ids

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/knoxsso.xml.j2, orchestrator-salt/src/main/resources/salt/salt/gateway/config/knoxsso.xml.j2
The KnoxSSO topology TTL should be limited to a duration instead of -1. This sets the duration to 24hrs in milliseconds. After this ttl expires, the user will need to login again.
=> CB-4039 KnoxSSO - JWT Tokens Are Valid for Extremely Long Duration

core/src/main/resources/defaults/blueprints/cdp-data-mart-702.bp, core/src/main/resources/defaults/blueprints/cdp-op-data-mart-702.bp
Impala was enhanced in CDH-79188 to set a more optimal default block size for Parquet files on object stores.
Now that the Impala default has been fixed we no longer need the explicit fs.s3a.block.size config setting in the Datamart template.
=> CB-4037 Remove explicit setting of fs.s3a.block.size in Datamart template

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/kerberos/CmServiceKeytabRequestFactory.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtVaultComponent.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/VaultPathBuilder.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/VaultPathBuilderV1Test.java
Due to [this issue](https://jira.cloudera.com/browse/CB-3758) we tried to find a way to reduce the size of the paths in Vault. The original Vault path builder generated the cluster id if it hasn't been provided previously as concatenating the account and environment ids, but they are already part of the path, so with @keyki we think it is better not to have such a long part in the paths. I think the cleanup of Vault should not be affected by this change.
Also the cluster id is set from CB side to decrease the cases where cluster id is not specified for service keytab generation.
@jamisonbennett Could you please take a look and validate our approach?
=> CB-3758 do not generate cluster id into Vault path in FreeIpa

core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
- adding resource crn to get By crn endpoint (only !!! that - following calls will be needed to be validated)
validating is in progress with real cluster ...
not deleting internal endpoint yet, in order to deploy this first to mow-dev, until internal usage is not deleted from metering service
=> CB-4019. Add ResourceCrn annotation for DistroX get by CRN Api endpoint

environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java
I missed that internal actor handling feature is used by the credential env api, not by the env api itself., I got a PR with Integration tests, but as that is a larger one, im sending this PR with only that part
=> CB-4019. Add resource crn annotation for get env by crn call

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/start.sls, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/RdsView.java, template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/views/RdsViewTest.java
One change in the prior commit for CB-3791 was having Cloudbreak
configure Cloudera Manager with only the bare usernames for database
connections, instead of the "full" username@short-hostname format needed
for connections to Azure-managed databases. This change undoes that
work, so that once again the entire username is configured in Cloudera
Manager.
This still does not allow Cloudera Manager to support clusters backed
by Azure databases, because of OPSAPS-53099. However, once that CM work
is done, Hive metastore table creation should succeed, and perhaps
overall cluster creation will as well.
Other previous changes in CB-3791 to username handling are preserved.
This change only affects how Cloudera Manager is configured.
=> CB-3791 Revert to passing full db usernames to CM

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/clouderamanager-ssl-user-facing.conf
Add config for Nginx to enable websockets when proxying Knox/Zeppelin
=> CB-4167 Enable Nginx websockets proxying for Knox/Zeppelin

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProvider.java
Hive metastore - hive.server2.authentication.kerberos.* shouldn't be set by CB anymore. This should be set by CM automatically.
=> CB-4192 Hive metastore - hive.server2.authentication.kerberos.* shouldn't be set by CB anymore

ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/altus/config/MinaSshdManagementConfig.java
In k8 the ccm service is exposed in port 80, this updates the default
port to be the same.
=> Change default MinaSshdManagementConfig.port to 80

core/src/test/java/com/sequenceiq/general/RepositoryRestrictionTest.java, environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialDeleteService.java, environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialService.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java, environment/src/test/java/com/sequenceiq/environment/RepositoryRestrictionTest.java, environment/src/test/java/com/sequenceiq/environment/credential/service/CredentialDeleteServiceTest.java, environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentModificationServiceTest.java
Since environment service uses both annotation and constructor dependency injection, the related unit test had to be changed
=> CB-1097 – modifying environmnet service check due to different type(s) of dep.inj. usages

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLicenseService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLicenseServiceTest.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java, core/src/main/java/com/sequenceiq/cloudbreak/service/gateway/GatewayPublicEndpointManagementService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserProfileDecorator.java, environment/src/main/java/com/sequenceiq/environment/credential/validation/CredentialValidator.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaServerRequestProvider.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java, environment/src/test/java/com/sequenceiq/environment/credential/validation/CredentialValidatorTest.java, environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaServerRequestProviderTest.java, environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java, environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentTestData.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UsersyncPoller.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UsersyncPollerTest.java, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java
The UmsClient and EntitlementService were modified to accept an accountId
in addition to an actorCrn. This change is needed to support calling
with an internal actor crn.
The UsersyncPoller was modified to check the CDP_AUTOMATIC_USERSYNC_POLLER
entitlement for each account.
=> CDPCP-1017. Entitle automatic usersync poller

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserService.java, freeipa/src/main/resources/application.yml, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserServiceTest.java
The FreeIpaClient returns a null response object when the cluster-proxy request times out. The first commit null-checks the response and throws an exception. The second commit partitions the known potentially long-running requests into smaller chunks of work.
=> CDPCP-1023. 

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/provision/handler/ClusterProxyRegistrationHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/handler/ClusterProxyDeregistrationHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/config/FmsClusterProxyEnablement.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ClusterProxyService.java
Cluster proxy integration for FMS now also requires an
entitlement. This will allow us to continue testing in
mow-dev while keeping it disabled for other users. Note
that since we've moved the check into ClusterProxyService,
this will also affect the register/deregister api.
=> CB-4524. Enable cluster proxy for FMS through entitlements

common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java
This allows the "ml" service to use its CRN as the cluster CRN for the
kerberos management APIs.
This was manully tested with the following CRN:
crn:cdp:ml:us-west-1:9d74eee4-1cad-45d7-b645-7ccf9edbb73d:workspace:
e4ef2cc9-904f-4d5a-80cb-929e76f9d288
Closes #CB-4286
=> CB-4286 Add "ml" as a valid service CRN

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/knoxsso.xml.j2
If a user facing fqdn is defined, Knox will use that to set the domain for the redirect whitelist regex.
=> CB-4040 KnoxSSO - Improve knoxsso.redirect.whitelist.regex

README.md
The readme instructions for running the environment from the command
line were fixed.
The instructions were tested using a local deployment of cloudbreak
with the environment service running from the command line.
=> Fix the readme instructions for running the environment

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ProcessAutoRestartInjector.java
Auto restart should be on for Hive on Tez by default.
=> CB-4290 Enable auto restart for Hive on Tez

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
Using the CLI and submitting a non exsisting sdx anme the ResponseWriter was not able to write error messages resulting in 500 InternalServerError
`{"timestamp":"2019-11-06T15:05:56.051+0000","status":500,"error":"Internal Server Error","message":"HTTP 500 Internal Server Error","path":"/dl/api/sdx/lnardai/upgrade"}
ERROR: status code: 500, message: HTTP 500 Internal Server Error
DEBUG: status code: 500, message: HTTP 500 Internal Server Error
INFO:  Upgrade sdx cluster by name took 329.350702ms
DEBUG: status code: 500, message: HTTP 500 Internal Server Error`
=> CB-3905 fixed 500 error response when we responded with bad request

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaAuthConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaAuthConfigProviderTest.java
Description:
- Renamed  KafkaLdapConfigProvider to KafkaAuthConfigProvider
- Changed the logic so that PAM authentication will be used as of CDH 7.1.0. Previous logic for CDH between 7.02 and 7.1.0 is kept.
Tests:
- Rewrote unit tests: KafkaAuthConfigProviderTests
- Tested the following cases manually: CM 7.02 - CDH 7.0.2, CM 7.10 - CDH 7.02, CM 7.1.0 - CDH 7.1.0
Closes CB 4250
=> CB 4250 - Enable PAM Authentication for Kafka from CHD Version 7.1.0

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/knoxsso.xml.j2
Currently the KnoxSSO whitelist checks both port and path. The port and path should both be optional. Added two non capturing optional groups around the port and path.
=> CB-4423 KnoxSSO whitelist - make port and path optional

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, environment/src/main/java/com/sequenceiq/environment/cache/CredentialCloudPlatformCache.java, environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialService.java, environment/src/main/java/com/sequenceiq/environment/credential/validation/CredentialValidator.java, environment/src/test/java/com/sequenceiq/environment/credential/service/CredentialServiceTest.java, environment/src/test/java/com/sequenceiq/environment/credential/validation/CredentialValidatorTest.java, environment/src/test/java/com/sequenceiq/environment/service/integration/EnvironmentServiceIntegrationTest.java
* `CredentialService.listAvailablesByAccountId()` (called by `CredentialV1Controller.list()`): Filter out all credentials whose cloud platform is not entitled for the target account (besides the former check for being enabled globally in EnvSvc)
* `GrpcUmsClient.getAccountDetails()`: Fix `@Cacheable` key (was likely omitted during a recent method parameter name change).
Tests:
* Unit
* Integration (existing `EnvironmentServiceIntegrationTest`)
* Manual using cbd & IDEA
=> CB-4300 Fix credential list for missing Azure entitlement

freeipa/src/main/java/com/sequenceiq/freeipa/client/ClusterProxyError.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/ClusterProxyErrorRpcListener.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/test/java/com/sequenceiq/freeipa/client/ClusterProxyErrorRpcListenerTest.java
The JSON RPC client we use for FMS returns a null when there
is an HTTP error and the error response body doesn't conform
to json rpc standards. This is not ideal behavior because the
cluster proxy may return an HTTP error that has valid json
body but not valid json rpc format.
To surface cluster proxy errors, we now throw an error if the
json in the RPC response matches what we expect the cluster
proxy errors to look like.
=> CDPCP-1028. Throw exception on cluster proxy error in FMS

cloud-common/build.gradle, cloud-common/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AccountMappingSubject.java, cloud-common/src/test/java/com/sequenceiq/cloudbreak/service/identitymapping/AccountMappingSubjectTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AwsMockAccountMappingService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AzureMockAccountMappingService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/identitymapping/AwsMockAccountMappingServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/identitymapping/AzureMockAccountMappingServiceTest.java
Contents:
* Extract Data Access and Ranger Audit service user sets into the new utility class `AccountMappingSubject`
* Located in module `cloud-common` so that it becomes available to `AwsIDBrokerObjectStorageValidator` of #6639
* Matches the corresponding collections of IDBMMS
* Replace field injection with constructor injection in `AwsMockAccountMappingService`
* Eliminate superfluous injected dependencies in `AzureMockAccountMappingService`
* Construct mappings in `AwsMockAccountMappingService` and `AzureMockAccountMappingService` using the user set of `AccountMappingSubject`
* Add JUnit 5 support to module `cloud-common`, while keeping JUnit 4 dependencies as well for legacy tests
* Add JUnit 5 unit tests for all classes involved
=> CB-4438 Realistic mock IDBroker mapping service user list

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/TelemetryApiConverter.java
in telemetry api converter, one of the field setting is passed, if features are filled -> cause nullpointer
in telemetry converter there is a similar method, it does not cause anything but removing the request object from there as well
=> CB-3210. Fix telemetry conversion after refactor

datalake/src/main/java/com/sequenceiq/datalake/configuration/AppConfig.java, datalake/src/main/java/com/sequenceiq/datalake/configuration/PlatformConfig.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
- from a Datalake perspective cb.enabled platform is not equivalent of the supported databases towards redbeams so created a new parameter for that
- tried to preserve the cli compatibility, so now Azure external Db can be forced from CLI but won't be started by default
-  should not have any more classpath read exceptions during sdx startup
=> CB-4491 Fixed various issues where database was created for certain platforms

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsIDBrokerMappedRolePermissionValidator.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsDataAccessRolePermissionValidatorTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsIDBrokerMappedRolePermissionValidatorTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsRangerAuditRolePermissionValidatorTest.java
When no DynamoDB table is specified, IDBroker mapping validation should not fail.
=> CB-4524 IDBroker mapping validation - handle case of no DynamoDB table

core/src/main/java/com/sequenceiq/cloudbreak/service/template/ClusterTemplateCloudPlatformValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/template/ClusterTemplateService.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/ClusterTemplateV4ControllerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/template/ClusterTemplateCloudPlatformValidatorTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/template/ClusterTemplateServiceFilterTest.java
* Change to cluster definitions `list()` (GET https://localhost/cloudbreak/v4/0/cluster_templates)
* Hide Azure cluster definitions when Azure entitlement is missing
* Hide cluster definitions associated with a disabled / invalid cloud platform
* Add unit tests
=> CB-4488 Hide Azure cluster definitions when Azure entitlement is missing

common/src/main/java/com/sequenceiq/cloudbreak/validation/ValidationResult.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/ValidationResultTest.java
Using the `ValidationResultBuilder` should not have duplicate errors. This changes the internal representation from an `ArrayList` to `TreeSet`
=> CB-4525 ValidationResult should not have duplicate errors

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/BasicSdxTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsSdxCloudStorageTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsSdxTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/azure/AzureSdxCloudStorageTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterCreationTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterStopStartTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxTests.java
@lnardai or @sodre90 please review then merge if it is OK for you.
Based on the latest SDX response:
```
{
...
"clusterShape": "LIGHT_DUTY",
"status": "RUNNING",
"statusReason": "Datalake is running",
...
"stackV4Response": {
...
"status": "AVAILABLE",
...
"instanceGroups": [
{
"nodeCount": 1,
"name": "master",
"type": "CORE",
...
"metadata": [
{
...
"instanceGroup": "master",
"instanceStatus": "SERVICES_HEALTHY",
"instanceType": "GATEWAY_PRIMARY",
"state": "HEALTHY",
"mountedVolumes": []
}
],
...
},
{
"nodeCount": 1,
"name": "idbroker",
"type": "CORE",
...
"metadata": [
{
...
"instanceGroup": "idbroker",
"instanceStatus": "SERVICES_HEALTHY",
"instanceType": "CORE",
"state": "HEALTHY",
"mountedVolumes": []
}
],
...
],
```
=> CB-3329 Fix Instance Status for SDX tests

environment/src/main/resources/schema/app/20191120150142_CB-2902_managed_publickey.sql
Set the 'managedkey' flag to false for records inserted by older
codebase
=> CB-2902 datafix for managed publickey

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/knoxsso.xml.j2
Right now the KnoxSSO cookie is scoped across the domain of the Knox host. Since multiple clusters share that domain with different Knox signing keys, this causes cookie scoping issues. The short term fix is to scope the cookie to the Knox host since only the Knox host reads this cookie right now.
We only want this to happen when a user facing domain is generated to prevent any issues with testing.
=> CB-4598 KnoxSSO cookie should be scoped to the Knox host only

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSessionCredentialClient.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSessionCredentialProvider.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSessionCredentials.java
Use credential provider with aws client builders instead of deprecated client creation -> clients always accessing credentials through credential providers (with depricated client -> it creates a static credential provider without refresh function, and that is used there)
Solution 1
Pros:
- we can refresh the token more often (based on our custom cache), even if expiration time is close (can be configurable)
- log expiration time for role arn
Cons:
- custom credential provider
(note, not tested too well yet + if it will be acceptable, i will change the base branch to rc-2.15 if it's needed)
solution 2:  https://github.com/hortonworks/cloudbreak/pull/6772
=> CB-4444 Fix token expiration issue (version 1)

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProviderTest.java
OPSAPS-53430 starting in CM 7.1.0 gbn://1643975 or
higher removed the need to set the HS2 kerberos
authentication safety valve settings. This change
checks if the CM version is >=7.1.0 and if so
doesn't set the HS2 kerberos authentication configs.
Adds a test to verify behavior.
This follows the pattern from CB-4250 to detect CM 
version.
=> CB-4194 Remove HiveServer2 kerberos authentication safety valve setting

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/VirtualGroupService.java
- without proper logging i have no idea which call get stucked. 
https://github.com/hortonworks/cloudbreak/blob/master/environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/EnvironmentUMSResourceDeleteHandler.java#L71
based on the logs the problematic flow never reached the catch part or the code below that, also on next run it went through to finished state
=> Add logging for UMS resource deletion (notify resource deletion & virtual group cleanup)

build.gradle
Adds an eclipse specific fixup function to the root gradle.build file that removes the erronous  eclipse classpath entries for protobuf generated code, and adds the correct classpath entries.
The function is only ever run by the eclipse project setup gradle plugin, so it should have minimal risk.
testing done:
run './gradlew eclipse', import the project into eclipse. 
Eclipse does not have dependency problems with the fix.
run './gradlew build'
check that the build completes.
Closes #CB-4683
=> CB-4683 Fix gradle Eclipse IDE project generation

Makefile, scripts/build-rc-patch.sh, scripts/create-rc-version-tag.sh
Separate version tag creation from build.
__Note:__
This branch should not be merged until CB related jobs in https://github.com/hortonworks/RE-Jenkins are modifie to use the new scripts based on the project version.
=> DO NOT MERGE CB-4685 Use swagger generator tests in rc pipeline

environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java
i got the following error during cb-cli swagger generation:
```bash
2019/11/29 16:45:40 validating spec /Users/oliverszabo/GoProjects/src/github.com/hortonworks/cb-cli/build/swagger.json
The swagger spec at "/Users/oliverszabo/GoProjects/src/github.com/hortonworks/cb-cli/build/swagger.json" is invalid against swagger specification 2.0. see errors :
- path param "{name}" has no parameter definition
make: *** [generate-swagger-environment-docker] Error 1
```
so i added the path param to this endpoint
=> Add '@PathParam' to crnByName endpoint

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/NifiKnoxRoleConfigProvider.java
Missing `return` keyword, logs are added
=> CB-4676 Nifi knox does not populated in the CM template

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialVerifier.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/cache/AwsCredentialCachingConfig.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/client/AmazonIdentityManagementRetryClient.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialVerifierTest.java, common/src/main/java/com/sequenceiq/cloudbreak/service/Retry.java, common/src/main/java/com/sequenceiq/cloudbreak/service/RetryService.java, flow/src/test/java/com/sequenceiq/cloudbreak/service/HeartbeatServiceTest.java
- creating 5 second cache for verification (in order to not use aws client too often, especially problematic in parallel scenarios - like creating multiple credentials for e2e tests )
- also adding retry around request exceeded calls -> that can avoid throttling errors if an another application uses the same aws account for iam operations -> added 1 sec / 5 times retry as well as the issue happened during create credential actions (2 sec delay with 15 times will be too large there)
=> CB-4625. Fix AWS throttling errors during credential verification

cluster-ambari/src/main/java/com/sequenceiq/cloudbreak/ambari/status/AmbariClusterStatusService.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterStatusService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
1. Check CM accessibility, before checking hosts, during sync flow. If CM is not available, set its state to unhealthy and send notification
2. Aggregated host saves and notification sending for multiple hosts for optimization
=> CB-4709 Fix for Sync, when CM is not available

README.md, core/build.gradle, environment/build.gradle, freeipa/build.gradle, redbeams/build.gradle
Add the AWS variables in  bootRun in the subprojects that set the same in cbd dockerfiles.
Add instructions to set the AWS variables in README
Add instructions to use --no-daemon in  README
Testing done:
./gradlew build succeeds
Cloudbreak can actually be successfully run from CLI with these instructions.
I did not test the IDEA settings, or the other services, just mechanically copied the changes.
Closes #CB-4710
=> CB-4710 Update README.md for current AWS authentication

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaAuthConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaAuthConfigProviderTest.java
PR to disable Kafka auth config provider for datalake clusters. There are two reasons to do this:
1. It is not needed for data lakes, only workload clusters
2. It prevents a breaking config change to be rolled out.
Testing:
- Rewrote KafkaAuthConfigProviderTest
=> CB-4653 disable Kafka auth config for datalake

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/Status.java, freeipa/src/main/java/com/sequenceiq/freeipa/configuration/UsersyncConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UsersyncPoller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java, freeipa/src/main/resources/application.yml, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UsersyncPollerTest.java
A separate threadpool is configured for use by the UserService and PasswordService.
Minor related configuration improvements are included:
- UsersyncPoller bean is conditionally created instead of checking the enabled flag
- application.yml is updated to move relevant configuration properties under freeipa.usersync
=> CDPCP-1015. Usersync uses separate threadpool

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsIDBrokerMappedRolePermissionValidator.java
Reenables IDBroker role mapping validation since it is correct. The issue is IDBMMS changing from instance profile to role behind the scenes.
=> CB-4670 Reenable IDBroker role mapping validation

orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls
removed `--server` parameter so the cluster would use autodiscovery to connect to freeipa server.
tested on AWS and AZURE
=> CB-4602 join FreeIPA with autodiscovery

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
Remove copy/paste typo. This is only on master. I checked rc-2.15 and rc-2.16. Looks like it came in as part of https://github.com/hortonworks/cloudbreak/commit/c1de8da699d7e678279011a5706741ba3f89e0ac by mistake.
=> Fix typo in topology.xml.j2

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDatahubConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDatahubConfigProviderTest.java
Adds `"ranger_plugin_kafka_service_name" = "{{GENERATED_RANGER_SERVICE_NAME}}"` to the datahub clusters' Kafka service level config.
Testing:
- Reworked `KafkaDatahubConfigProviderTest` 
- Tested DataHub cluster installation manually.
Closes CB-4576
=> CB-4576 Config provider for Ranger service generation for Kafka

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/service/AltusIAMService.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/base/FeaturesBase.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/doc/TelemetryModelDescription.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/Telemetry.java, common/src/main/java/com/sequenceiq/cloudbreak/altus/AltusDatabusConfiguration.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/TelemetryConfiguration.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserService.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserServiceTest.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/telemetry/EnvironmentFeatures.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/TelemetryApiConverter.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/TelemetryApiConverterTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/handler/MachineUserRemoveHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/AltusMachineUserService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaInstallService.java, freeipa/src/test/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverterTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsApplication.java
- add global config to enable to use a common altus credential for all cb cluster (that should be enabled for e2e environments)
- the shared altus credential is only used if that is set in telemetry request (as a feature setting) - if the global config is disabled, you cannot enable that feature
- access / secret key can be set in the configuration (use char array for the secret key)
- as many configurations passed to the converters, create config objects instead of extending the parameters (Telemetry + Altus config object)
=> CB-4749. Add global databus secret/access keys to skip machine user generation

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/clouderamanager-ssl-user-facing.conf
Nginx config client_max_body_size defaults to
1MB which is too small when proxying large
file uploads. Setting client_max_body_size to
0 will not have Nginx check the "Content-Length"
request header. Chunked transfers are enabled
by default so this shouldn't load the entire
upload into memory.
=> CB-4848 Unable to upload huge file to HDFS through Nginx

auth-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/usermanagement/UserManagementGrpc.java, auth-connector/src/main/proto/usermanagement.proto, config/checkstyle/checkstyle.xml, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UmsUsersState.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersState.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/WorkloadCredential.java, freeipa/src/test/java/com/sequenceiq/freeipa/client/FreeIpaClientTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserServiceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/freeipa/UserFindResponse.java, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java
The UMS now provides a password expiration time along with the
workload credentials. This value is epoch millis. User sync has
been updated to set this expiration time when setting the hashed
password. The userMod request was refactored, moving the param
map creation into the FreeIpaClient to match the pattern used by
other FreeIpaClient methods.
The UsersState was slightly refactored to split out the UMS-specific
information into a UmsUsersState because the UsersState model is
also used to represent the ipa state.
The Mock user management service has been modified to return an
expiration time that is different from the max expiration time
that the FMS uses.
=> CDPCP-1212 Update password expiration for hashed password codepath

core/src/main/resources/defaults/clustertemplates/aws/aws-streaming-702.json, core/src/main/resources/defaults/clustertemplates/aws/aws-streaming-small-702.json, core/src/main/resources/defaults/clustertemplates/azure/azure-streaming-702.json, core/src/main/resources/defaults/clustertemplates/azure/azure-streaming-small-702.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.1.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.2.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.1.json
- Added "PREVIEW" label to the streaming clusters
- Fixed SMM (1.0.0 -> 2.1.0)and SR (4.0.0 -> 0.8.1) versions, from 
Testing:
Checked out the changes manually on the UI.
Closes CSP-803
=> CSP-803, Streaming is preview,fix sersion for SMM,SR

README.md
This patch updates the README so that developers will know the
correct port to use depending on whether cloudbreak was started
in a container or from IntelliJ/Command line.
To test, I've run various services in dev and container mode and ensured basic functions work.
=> CB-4863: README doesn't account for cloudbreak service port changes

freeipa/src/main/resources/freeipa-salt/salt/fluent/template/input.conf.j2, orchestrator-salt/src/main/resources/salt-common/salt/fluent/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/databus_metering.conf.j2, orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/output.conf.j2, orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/output_databus.conf.j2, orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/td-agent.conf.j2, orchestrator-salt/src/main/resources/salt/salt/fluent/template/input.conf.j2
Use multiple workers for fluentd
there can be situations when s3 or abfs output or policies are misconfigured in a way that can cause fatal issues for fluentd (regarding buffers for example), but that can cause that the databus part of fluentd won't work because of that kind of errors. (that means metering can stop because of some specific cloud storage issues) - or same is true for OOM errors
solution for that:
- run fluentd in different processes for different outputs
see more: https://docs.fluentd.org/deployment/multi-process-workers
workers needs to be indexed (from 0...n), and also to number of workers needs to match the configurations, so adding a small logic to `fluent/settings.sls`  to calculate the number of workers + use the right indexes (any of output can be disabled, so we …
=> CB-4871. Use different fluentd workers for different outputs.

template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.1.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.2.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.1.json
Fix for Nifi and Nifi Registry version display on Cloudbreak UI.
Nifi version is changed from 0.7.0 to 1.10.0
Nifi Registry version is changed from 0.4.0 to 0.5.0
Testing: checked manually on UI.
Closes CB-4867
=> CB-4867 fix Nifi versions

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/user/event/SetPasswordRequest.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/user/handler/SetPasswordHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberos/v1/KerberosConfigV1Service.java, freeipa/src/main/java/com/sequenceiq/freeipa/ldap/v1/LdapConfigV1Service.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UmsUsersState.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersState.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordServiceTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserServiceTest.java, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java, mock-caas/src/test/java/com/sequenceiq/caas/grpc/service/MockUserManagementServiceTest.java
The password expiration time is not included as part of the set password
request. The PasswordService retrieves the password policy from the UMS and
calculates the expiration Instant. The SetPasswordHandler calls the FreeIpaClient
with the expiration Instant when setting the password.
=> CDPCP-1212. Password expiration set in set password api workflow

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaAuthConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaConfigProviderUtils.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDatahubConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaAuthConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaConfigProviderUtilsTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDatahubConfigProviderTest.java
Adjusted Kafka Config providers for the 7.0.3 release. Although this release has higher version number than 7.0.2.2 it yet contains older code and accepts the same configuration as the 7.0.2 version.
Changed `KafkaAuthConfigProvider` and `KafkaDatahubConfigProvider`.
Testing: 
* adjusted Kafka config provider tests.
* tested manual cluster installation with 7.0.2.2 and 7.0.2.
Closes CB-4874
=> CB-4874 Kafka config providers adjusted for CDH 7.0.3

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
Increase the connection/read timeout from 20s to 5m for Impala Hiveserver2
=> CB-4942 Knox - Increase connection and read timeout values for Impala

cloud-aws/src/main/resources/definitions/cdp/aws-cdp-dynamodb-policy.json
CB-3513 mistakenly removed the CreateTable
permission from the DynamoDB policy. This
puts back the missing permission so S3Guard
works as expected to create the table.
=> CB-4951 CreateTable is missing from DynamoDB policy

core/src/main/resources/defaults/blueprints/cdp-opdb-702.bp
reduce memory allocations to conform to the (overly conservative) CM limit in worker node
Testing done:
use modified blueprint to build DatHub cluster
check that CM doesn't display a warning
Closes #CB-4899
=> CB-4899 OpDB 7.0.2 blueprint overcommits memory

freeipa/build.gradle, freeipa/src/test/java/com/sequenceiq/freeipa/FreeipaJinjaTester.java, gradle.properties, orchestrator-salt/build.gradle, orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/CbJinjaTester.java
- should check all sls files in cb and freeipa modules
Error message example:
`java.lang.AssertionError: Jinja validation failed for sls file: .../orchestrator-salt/out/production/resources/salt/salt/docker/init.sls
TemplateError{severity=FATAL, reason=SYNTAX_ERROR, item=OTHER, message='Syntax error in '{% easdasdndif %}': Unknown tag: easdasdndif', fieldName='easdasdndif', lineno=13, startPosition=1, scopeDepth=1, category=UNKNOWN, categoryErrors=null}TemplateError{severity=FATAL, reason=SYNTAX_ERROR, item=OTHER, message='Syntax error in '{% if salt['pillar.get']('docker:enableContainerExecutor') %}': Missing end tag: endif for tag defined as: {% if salt['pillar.get']('docker:enableContainerExecutor') %}', fieldName='{% if salt['pillar.get']('docker:enableContainerExecutor') %}', …
=> CB-4967 added 2 unit tests for cb and freeipa to verify all salt files

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsDefaultZoneProvider.java
This reverts commit bf0fd882324bc61fe174db775bee888fe54c63a6.
**Changes:**
- Set `us-east-1` as default region for AWS clients
- Workaround for cross-origin behaviour of AWS S3 client: https://github.com/aws/aws-sdk-java/issues/1451#issuecomment-360281381
=> CB-4915 update AWS default zone provider defaults to Virginia us-east-1

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/UpgradeOptionV4Response.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeServiceTest.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeService.java
Return reason when upgrade is allowed after datahub cluster stop.
__Note:__
Frontend change is necessary for this change to work properly.
=> CB-4957 Can't perform Data Lake OS Upgrade if Data Hub added to the environment

core/src/main/resources/defaults/blueprints/cdp-data-mart-702.bp
Removed HDFS from Data Mart blueprint
Testing done:
* Provisioned Data Mart cluster with modified blueprint and verified:
- No provisioning errors and no errors/alerts reported by CM
- HDFS service not configured (as expected)
- All relevant S3 and S3guard configurations properly set in Core and Impala configs
- Able to create/insert/select/drop table in S3 using Impala
=> CDPD-5915 - Update Data Mart template to remove HDFS service

orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls
compression is supported from 0.2.x, so updating the azure storage plugin version for that
testingdone
=> CB-4946. Update fluentd azure storage plugin version

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxRepairAction.java
Unfortunately there was an issue with String.format usage in the repair integration test. This commit fixes it.
=> Fix string format usage since it caused the repair test failure

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/TopologySegment.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/TopologySuffix.java, freeipa/build.gradle, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaInstallService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaTopologyService.java, freeipa/src/main/resources/freeipa-salt/pillar/freeipa/init.sls, freeipa/src/main/resources/freeipa-salt/salt/freeipa/common-install.sls, freeipa/src/main/resources/freeipa-salt/salt/freeipa/init.sls, freeipa/src/main/resources/freeipa-salt/salt/freeipa/primary-install.sls, freeipa/src/main/resources/freeipa-salt/salt/freeipa/replica-install.sls, freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_replica_install.sh, freeipa/src/main/resources/freeipa-salt/salt/top.sls, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaTopologyServiceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/freeipa/TopologySegmentFindResponse.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/freeipa/TopologySuffixFindResponse.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/KerberosConfigTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RecipeClusterTest.java, orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
This adds support to the FreeIPA management service to support
provisioning multiple instances, but this does not change the
environment service which is hardcoded to 1 instance.
The primary gateway is chosen as the CA master, the CRL master, the
node for configuring the FreeIPA servers, and the first FreeIPA node
to be installed.
All the other FreeIPA nodes are installed next as a part of the
FreeIPA install step. During the FreeIPA post install, the network
topology is updated to be a more complete mesh with a maximum of 4
replication agreements.
This was tested manually by setting the MASTER_NODE_COUNT in
FreeIpaCreationHandler.java (which is not included in this change).
=> CB-1141 Add the ability of the FMS to provision multiple FreeIPA nodes

core/src/main/resources/application.yml, core/src/main/resources/defaults/blueprints/cdp-opdb-710.bp, core/src/main/resources/defaults/clustertemplates/aws/aws-opdb-710.json, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/service-definitions-minimal.json
* add the PQS service to opdb blueprint
* set the hbase_regionserver_wal_codec property
* add the other configs  that Phoenix needs to Hbase client and service safety valve
* set hbase.use.dynamic.jars to false via HBase safety valve
* add Phoenix to service-definitions-minimal.json
Testing done:
built cloudbreak successfully
Built an opdb cluster with the change
Checked that the cluster works
checked that the local phoenix-sqlline client works
checked that phoenix-thin-client (and consequently PQS) works
Closes #CB-4551
=> CB-4551 add phoenix service and configuration opdb blueprint

orchestrator-salt/src/main/resources/salt/salt/fluent/template/input.conf.j2
add the following missing components to monitor for fluentd:
- SMM
- Schema registry
- kafka-broker
- hbase regionserver
- hbase server
- hbase thriftserver
=> CB-5077. Add missing Kafka/HBase logs (to monitor by fluentd)

template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.1.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.2.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.1.json
also add Phoenix to compinent version list for CDH 7.1
Updates the descriptors that specify the component versions to display.
Adds Phoenix to 7.1 descriptor
I have used the versions from the POM, even though they may not be accurate. I left the HBase version in 7.1 alone, because while it does not match the POM version, it matches reality.
Test:
Start modified CB
Check that the UI displays the new versions on DataHub creation screen
Check that the UI display Phoenix with logo and correct version on DataHub creation screen
Closes #CB-4802
=> CB-4802 Update displayed component versions for OpDB components

core/src/main/resources/defaults/clustertemplates/azure/azure-opdb-702.json
This reverts commit b0eb36743b07060ad0b293aeecd94ae85253930c.
Instance type Standard_DS4_v2 is not supported by product.
see: CB-4012
followup:
CB-5197
=> Revert "CB-4917 Change instance type and disk in OpDB DataHub"

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/TelemetryApiConverterTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverter.java
altus shared credential is not set on the API for every use case
- fix converters on the right place
- add some UT changes
=> CB-5174. Use shared altus credential is not always set if enabled

freeipa/src/main/resources/freeipa-salt/salt/fluent/template/input.conf.j2, orchestrator-salt/src/main/resources/salt/salt/fluent/template/input.conf.j2
collect nginx access and error logs, based on a freeipa cluster, the logs are the following:
- /var/log/nginx/access.log
- /var/log/nginx/error.log
=> CB-5250. Add nginx logs to log collection

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/User.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProvider.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProviderTest.java
Users with empty groups would cause a NullPointerException when
constructing the FreeIPA users state model. Failure constructing this
model will prevent usersync from progressing on that environment.
This commit adds a null-check and logs a warning if we see a user that
is not a member of any groups. We generally don't expect to see this
condition because all users are part of the ipausers group by default.
However, it is possible for someone to modify a user directly in ipa
and we need to protect the usersync process against this case.
=> CDPCP-1359. Usersync handles users with empty groups

core/src/main/resources/application.yml, core/src/test/java/com/sequenceiq/cloudbreak/util/ParcelAccessibilityTest.java
- e2e test was failing because the parcels got removed due to CM build artifact policy
- we should statically check for the presented URL's so Base images will select the correct urls.
=> CB-5150 added parcel manifest checks

integration-test/scripts/analyse_postgres_stat.jsh, integration-test/scripts/check-results.sh, integration-test/scripts/docker-compose.sh, integration-test/src/main/resources/pg_stats/pg_query_stat_template.html
__DB network traffic check__
Configurable check to limit the overall network traffic between cloudbreak and postgres. If the overall traffic is higher than `INTEGRATIONTEST_MAX_PG_NETWORK_OUTPUT (default="16GB")` 
the integration test will fail. The current usage is around 14.4 GB but over time we can bring down the limit with jenkins config.
__Html database query statistics__
Other than that the integration test exports postgres query statistics and stores it as a html artifact so that developers can analyse database usage.
=> CB-5215 Add postgres traffic check to integration test

orchestrator-salt/src/main/resources/salt/salt/metering/init.sls, orchestrator-salt/src/main/resources/salt/salt/metering/template/metering-heartbeat-application.service.j2
override default heartbeat monitoring application service definition (will be fixed later on thunderhead side) as metering stops after reboot with the current definition
=> CB-5296. No metering heartbeats after reboot

freeipa/src/main/java/com/sequenceiq/freeipa/controller/OperationV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/FreeIpaCleanupActions.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/poller/UserSyncPoller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/operation/OperationService.java, freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java
This commit renames the existing OperationStatusService to OperationService.
Entity conversion into API models has been moved to the controllers so
that all internal code works with the Operation entity instead.
An account id must always be specified when retrieving an operation from
the database. The controller for the getSyncOperationStatus api gets the
account id from the caller (i.e., from the x-cdp-actor header). This ensures
that no actor can retrieve operation status for any account other than its
own account. Since the request does not include an account
parameter, there is no way for an internal actor to request status of
an operation in a different account.
=> CDPCP-624. Prevent cross-account queries for operation status

common-model/src/main/java/com/sequenceiq/common/api/telemetry/base/FeaturesBase.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/Features.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/response/FeaturesResponse.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/telemetry/EnvironmentFeatures.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/TelemetryApiConverter.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/TelemetryApiConverterTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverter.java, freeipa/src/test/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverterTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/telemetry/TelemetryTestDto.java
- remove use shared credential from the API
Right now, it's not enough to set use altus credential globally in order to use a shared altus credential instead of communicate with UMS, you also need to provide this "ask" in the request. 
That works fine for e2e tests but not for the GUI test, as that option should be always hidden.
So make sense to remove from the API - at least the request part. (respone is kept so we can see on the API if that is used)
also refactor features object to set wrapper objects more easily
=> CB-5371. Feature refactor & (E2E) remove use shared credential from the API (request)

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/CleanupEvent.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/FreeIpaCleanupActions.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/event/AbstractCleanupEvent.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/operation/OperationService.java
This commit removes the OperationService method that retrieves
Operations by operation id only. An accountId is now always required.
This is a follow-on to PR https://github.com/hortonworks/cloudbreak/pull/7160
=> CDPCP-624. Require accountId when retrieving Operation

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Service.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtRoleComponent.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupService.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtRoleComponentV1Test.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtV1ServiceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/freeipa/ServiceFindResponse.java
refector keytab generation:
- don't try to create services/hosts if already exists, so we can reduce error logs
- use krbcanonicalname instead of krbprincipalname
=> CB-5207 Refactor keytab generation

orchestrator-salt/src/main/resources/salt-common/salt/fluent/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/override.conf.j2
we are setting ulimit for open files for fluentd at startup, but if you are restarting td-agent manually or after a system reboot, it wont use that dynamically set values (by salt), we can make it persistent by adding an override.conf to /etc/systemd/system/td-agent.d/override.conf: 
tested, output for fluentd agter calling fluent.init salt state:
```bash
cat /proc/<td_agent_pid>/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0 …
```
=> CB-5236. Increase number of open files for td-agent (make it persistent after restart)

freeipa/src/main/resources/freeipa-salt/salt/freeipa/init.sls
The FreeIPA installation starts krb5kdc with the argument "-w 100",
which starts 100 worker processes. The previous value of 2 worker
processes were insufficient for the CDP clusters and it results in
errors that weren't easily diagnosed from the types of issues that
occurred when Kerberos was under a load.
Each worker process consumes about 0.26 MB of memory, so this
increases memory usage by 26MB.
This was tested by creating an environment, logging into the FreeIPA
instance, and checking the number of krb5kdc processes.
Closes #CDPSDX-1379
=> CDPSDX-1379 Use 100 worker krb5kdc processes for FreeIPA

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/recipe/StackPreTerminationHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/telemetry/TelemetryAgentService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/telemetry/TelemetryAgentServiceTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/StackTerminationEvent.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/StackTerminationFlowConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/StackTerminationState.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/action/StopTelemetryAgentAction.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/event/telemetry/StopTelemetryAgentFinished.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/event/telemetry/StopTelemetryAgentRequest.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/handler/StopTelemetryAgentHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/orchestrator/StackBasedExitCriteriaModel.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/TelemetryAgentService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/TelemetryAgentServiceTest.java, orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/StateAllRunner.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStates.java
Shutdown in some cases are too agressive or too fast (like for AWS) and the shutdown scripts are not finishing for td-agent on the nodes.
Solution for that is to run fluent.agent-stop.sls salt script on the nodes before termination
- Add as an action for freeipa
- Add as an another task for core code (to pre stack termination)
If command fails, that should not be considered as an error, so put the salt execution in try catch block and just log the errors 
tested manually
=> CB-5303. Add stop telemetry agents action before termination.

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaOperationDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/health/HealthDetailsFreeIpaResponse.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/health/NodeHealthDetails.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthDetailsService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthServiceTest.java
This patch adds the ability to get a detailed status
from FreeIPA servers.  This information will be used
by the CLI and UI to provide detailed status information
for the FreeIPA node. This will also fix CB-5333
Ran additional unit tests.  Validated manually against FreeIPA instance.
=> CB-5094: Add connection check for FreeIPA MS to FreeIPA server

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/kafka/KafkaStructuredEventHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/CleanupEvent.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/FreeIpaCleanupActions.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/event/AbstractCleanupEvent.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/handler/UserRemoveHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupServiceTest.java
In case of child environment the created clusters FreeIPA related resources haven't been cleaned up correctly, the entities were queried for the parent environment and archived in case of cluster termination. This behaviour caused that the clusters recreation have been failed with the same name, due to the existing/not-archived FreeIPA entities the necessary Kerberos/Ldap roles were not propagated to the FreeIPA instance.
The main issue was that the entity cleanup of the two mentioned resources were based on the environment CRN of the parent environment's FreeIPA stack.
=> CB-5122 FreeIPA's LdapConfig and KerbConfig entity cleanup in case of child environment

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/AwsBackoffSyncPollingScheduler.java
1. In PR #7227 we reduced the throttling and request limit exceeded issues for describe images.
2. In this PR, we are fixing the next two offenders, those are describe CF stacks and events.
3. All these were already nicely wrapped in a backoff scheduler with reset.
4. In this PR increased the time lag between resets, added a jitter and made the code to be more tolerant of request limit exceeded errors.
./gradlew clean build
=> SRE-5408 Small steps toward allowing large number of AWS SDX cluster creations happen in parallel.

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsIDBrokerAssumeRoleValidator.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsIDBrokerAssumeRoleValidatorTest.java
Previously was trying to simulate each role independently when it wasn't necessary. This is still disabled until CB-4886 is complete, but its a step in the right direction.
=> CB-4808 AWS - Reduce number of IAM calls in AwsIDBrokerAssumeRoleValidator

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/UpdateStackRequestV2ToUpdateStackRequestConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperErrorHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleActions.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceGroupRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceGroupService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperErrorHandlerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupServiceTest.java
The number of calls are different because I didn't wait the entire cluster delete [here](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterStopStartTest.java#L56) . But the number of rows returned clearly show the improvement.
__Before:__
<table>
<tr>
<th>userid
</th>
<th>dbid
</th>
<th>queryid
</th>
<th>query
</th>
<th>calls
</th>
<th>total_time
</th>
<th>min_time
</th>
<th>max_time
</th>
<th>mean_time
</th>
<th>stddev_time
</th>
<th>rows
</th>
<th>shared_blks_hit
</th>
<th>shared_blks_read
</th>
<th>shared_blks_dirtied
</th>
<th>shared_blks_written
</th>
<th>local_blks_hit
</th>
<th>local_blks_read
</th>
<th>local_blks_dirtied
</th>
<th>local_blks_written
</th>
<th>temp_blks_read
</th> …
=> CB-5515 Select only the instance group in MetadataSetupService

common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java
The CRN validation now allows "dex" service type.
Closes #CB-5533
=> CB-5533 Add dex to the CRN service types

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/clouderamanager/CMUpscaleWithHttp500ResponsesTest.java
fix intermittent issue for upscale tests
Failed Tests: 2 (+2)
mock-tests / newway mock testcases
com.sequenceiq.it.cloudbreak.testcase.mock.clouderamanager.CMStartStopWithHttp500ResponsesTest.testCreateStartStopWithHttp500ErrorsForEachApiCallForTheFirstTime
com.sequenceiq.it.cloudbreak.testcase.mock.clouderamanager.CMUpscaleWithHttp500ResponsesTest.testUpscale
=> Fix intermittent IT Upscale issue

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/service/AltusIAMService.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/AnonymizationRule.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigService.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigView.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/altus/AltusAnonymizationRulesService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/AltusAnonymizationRulesService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaInstallService.java, orchestrator-salt/src/main/resources/salt-common/pillar/fluent/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/filter.conf.j2
Anonymization rules skeleton if the anonymization rules is defined on UMS account side (that part gives back null)
Notes:
- UMS is not supporting this option yet, so the method always gives back null
- As anonymization rules field is empty it will be missing from the salt config, so technicallly this change won't do anything until UMS side is not implemented (but i have tried out this by manually set the objects and set it through salt)
- If UMS side is done, only change here will be to transform the UMS response to our object format (that can be done in UMS client, as it was done for Altus credential - if that happens, maybe the model can be moved to auth-connector...but for know it's good at its actual place as that is related with telemetry)
- maybe later makes sense to persist the …
=> CB-5408. Apply anonymization rules on td-agent configs (by Salt)

core/src/main/resources/defaults/blueprints/cdp-opdb-702.bp, core/src/main/resources/defaults/blueprints/cdp-opdb-710.bp
**Summary**
Add hbase-GATEWAY-BASE and hdfs-GATEWAY-BASE roles to Leader node for OpDB blueprints.
**Testing**
Added custom template to mow-dev environment and created an OpDB cluster from it. Logged in to the leader node and executed a couple of HBase commands from the shell.
=> CDPD-7598 Add gateway roles to Leader

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/clouderamanager-ssl-user-facing.conf
Changes the user facing Nginx conf to accept "Expect" header. This is helpful in uploading in large files. Currently it does not allow the header to pass through and Knox fails the request.
> Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity.
>         at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:226)
>         at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
=> CSP-879: Knox proxy errors while uploading jar files

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigView.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StackRequestManifesterTest.java, orchestrator-salt/src/main/resources/salt-common/pillar/fluent/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/output.conf.j2
Pass idbroker identity for fluentd configs (not the log identity one), technically multiple identities should be assigned, but as we are not doing that just use the idbroker one
- UTs added
- few permission fixes (databus credentials)
cluster testing is in progress
=> CB-5636. E2E tests: ABFS logs are missing from idbroker host.

freeipa/src/main/java/com/sequenceiq/freeipa/kerberos/v1/KerberosConfigV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/ldap/v1/LdapConfigV1Controller.java
As part of HBase Autoscaling initiative we came across a bug in Periscope: LDAP and Kerberos services haven't been prepared to accept Internal CRNs which is a must for Periscope to work properly.
This patch enables the required endpoint for Internal usage.
No tests added yet, but recommendations are welcome.
Closes CB-5643
=> CB-5643 Periscope is unable to call FreeIPA endpoints with internal CRN (2.18)

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ResourcePropertyProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDtoBase.java
=> CB-5604 Distrox E2E creation fails in case of long stackname and 7.1.0 template

core/src/main/resources/defaults/clustertemplates/azure/azure-opdb-710.json
The new clustertemplate was created from an outdated version.
=> CB-5275 Use Standard_D8_v3 instance type for OpDB Master node on Azure

README.md
1. manager is misspelled in the example URL.
2. Added a note about significance of trailing slash in the URL.
=> Fix a type error in the README.md

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/StackAuthenticationV4Base.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/StackV4Request.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/security/StackAuthenticationBase.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/create/CreateFreeIpaRequest.java
Added length validation for StackAuthenticationRequest. The max length for publicKey is 2048, for publicKeyId it is 255 and for loginUserName it is 32.
=> CB-5562 Add length validation for StackAuthenticationRequest

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/action/AzureCloudBlobClientActions.java
blob with content length can be valid, creating a blob and append + flush are different steps against abfs api (see: https://docs.microsoft.com/en-gb/rest/api/storageservices/datalakestoragegen2/path), so it can be a state (if flush fails, there are like 5 sec retries after that) where the content is not appended yet
solution:
add toleration for this error, it should be rare, so if it occurs often, that can be a valid issue.
testing is in progress (not sure the default value will work)
update: seems like setting the value + the default is working as expected
=> CB-5711. Add zero byte toleration for e2e tests.

orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/output.conf.j2
main change is to set the retry timeout (+ if it reaches the 2h limit, drop the backups as well from tmp) + set a total buffer limit (1-2 GB)
retry timeout: 
Default: 72h
The maximum seconds to retry to flush while failing, until plugin discards buffer chunks
- change it to 2h
disable_chunk_backup:
Default: false
Instead of storing unrecoverable chunks in the backup directory, just discard them
- enable this, will only impact /tmp folder
overflow_action
drop_oldest_chunk: drop/purge oldest chunk to accept newly incoming chunk
(default is throw exception)
total_limit_size
Once the total size of stored buffer reached this threshold, all append operations will fail with error (and data will be lost)
- set 1G for CM agent commands and 2G for service logs
=> CB-5750. Drop oldest fluentd chunks - avoid buffer overflow

cloud-aws/src/main/resources/definitions/cdp/aws-cdp-log-policy.json
The policy linked from the documentation is missing `ListBucket`
https://docs.cloudera.com/management-console/cloud/environments/topics/mc-idbroker-minimum-setup.html
=> CB-5668 aws-cdp-log-policy.json missing ListBucket for LOGS_LOCATION_BASE resource

template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/6.1.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/6.2.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.1.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.2.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.1.json
CDH 7.1.0 = Livy 0.6.0
CDH <7.1.0 = Livy 0.5.0
=> CB-5826 Blueprint version for Livy 2.4.0 is wrong and should be 0.6.0

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
Enabled HA proxying for Schema Registry in the Knox topology template.
Tested manually (installed a cluster with 2 Schema Registry instances, checked UI and API with either of the instances down)
Closes CB-5588
=> CB-5588 Enable Knox HA proxy for Schema Registry

core/src/main/resources/application.yml, core/src/main/resources/defaults/blueprints/cdp-streaming-710.bp, core/src/main/resources/defaults/blueprints/cdp-streaming-small-710.bp, core/src/main/resources/defaults/clustertemplates/aws/aws-streaming-710.json, core/src/main/resources/defaults/clustertemplates/aws/aws-streaming-small-710.json, core/src/main/resources/defaults/clustertemplates/azure/azure-streaming-710.json, core/src/main/resources/defaults/clustertemplates/azure/azure-streaming-small-710.json, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java
Ported the 7.0.2 streaming templates to 7.1.0.
Testing: tested manually on AWS and Azure. Both the light duty and the heavy duty template installed successfully.
Closes CB-5764
=> CB-5764 Port streaming templates to 710

core/src/main/resources/defaults/clustertemplates/azure/azure-rt-datamart-710.json
When commit 0f3e5b69e2 added 7.1.0 variants of all of the cluster
definitions, it didn't incorporate the fix from commit 3badaf2e50 into the
RT-DM cluster def.
This commit rectifies that omission.
=> CB-5104: ephemeral volumes not supported by Azure (take two)

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java, datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidator.java, environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/base/CloudStorageValidation.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentEditRequest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentRequest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/DetailedEnvironmentResponse.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentBaseResponse.java, environment/src/main/java/com/sequenceiq/environment/environment/domain/ExperimentalFeatures.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentEditDto.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentApiConverter.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
Adds a feature flag for cloud storage validation which includes the IDBroker mapping validation. It is disabled by default. The validation is enabled by modifying the environment creation request. CB-5768 is for switching to enabled by default.
=> CB-4886 Add feature flag for IDBroker mapping validation

core-api/src/main/resources/definitions/exposed-services.json, core-api/src/test/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollectorTest.java, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
Add Phoenix Query Server to the list of services that CB pre-configures in Knox
Testing done on a local rc-2.19 CB instance
* Created environment
* Created OpDB DataHub with latest CM and CDH
* Checked that /var/lib/knox/gateway/conf/topologies/cdp-proxy-api.xml contains the correct URLs for the PQS instances
* Exported the Knox certificate to local machine
* Connected from DBeaver with the Phoenix Thin client driver JAR with the following JDBC URL:
jdbc:phoenix:thin:url=https://10.97.84.213/stoty-local-opdb/cdp-proxy-api/avatica;serialization=PROTOBUF;authentication=BASIC;truststore=/Users/stoty/x/gateway.truststore;truststore_password=bububu;avatica_user=stoty;avatica_password=redacted
* Checked that I can issue SQL commands successfully
Closes CB-4760
=> CB-4760 Add Phoenix Query Server to Knox configuration

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
Right now, any user may access the Kudu web UI; we need to ensure that Knox
enforces its access control mechanisms appropriately.
Even though commit 9e33314bf99 added all endpoints en masse, the Kudu web UI
endpoint was added two weeks prior in commit 409a0cf8c9, so it's conceivable
that the first commit missed the second.
=> CB-3857: add Kudu web UI to list of access-controlled Knox endpoints

core/src/main/resources/application.yml, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-702.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-710.bp, core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-ha-702.json, core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-ha-710.json, core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-702.json, core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-710.json, core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-ha-702.json, core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-ha-710.json, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java
1. Design : https://docs.google.com/document/d/1oN8l9p74gKNps1aeG2NCjdh1_6yRo5YZA4eTolS9dVw/edit
2. Added all the templates in preview mode as noted in the design.
3. The requirement was to use smaller instance type for quorum nodes. At the moment not possible because, a unit test fails with m5.xlarge for quorum nodes. To compensate, moved to Standard_D8_v3 for all the DE template masters.
4. Tested that cluster definitions and blueprints came up fine in UI via moonlander private stack https://gk1-console.cdp-priv.mow-dev.cloudera.com/cloud/environments/list.
=> DISTX-397 Create data engineering HA template

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/freeipa/FreeIpaDeletionHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/repository/EnvironmentRepository.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java, environment/src/main/java/com/sequenceiq/environment/network/dao/domain/YarnNetwork.java, environment/src/main/java/com/sequenceiq/environment/network/v1/converter/YarnEnvironmentNetworkConverter.java, environment/src/main/resources/application.yml, environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandlerTest.java, environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/freeipa/FreeIpaDeletionHandlerTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/freeipa/DnsZoneAddResponse.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/freeipa/DnsZoneDelResponse.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentChildTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/FreeIpaCreationTest.java, integration-test/src/main/resources/application.yml
CB-5725
Child environment detach should remove reverse DNS zone from FreeIPA
Depends on https://github.com/hortonworks/cloudbreak/pull/7312
=> CB-5725 Child environment detach should remove reverse DNS zone from FreeIPA

README.md, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/validation/CreateFreeIpaRequestValidator.java, freeipa/src/test/java/com/sequenceiq/freeipa/controller/validation/CreateFreeIpaRequestValidatorTest.java, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java, mock-caas/src/main/resources/application.yml
Check the CDP_FREEIPA_HA entitlement when creating FreeIPA HA
clusters.
Fixed the readme for the running the mock-caas.
Closes #CB-5896
=> CB-5896: Add CDP_FREEIPA_HA entitlement check.

core/src/main/resources/application.yml, core/src/main/resources/defaults/clustertemplates/aws/aws-opdb-710.json, core/src/main/resources/defaults/clustertemplates/azure/azure-opdb-710.json, core/src/main/resources/schema/app/20200228140101_CB-5752_rename_template.sql
for both the AWS and Azure definitions:
* change the name of the definition
* set featureState to RELEASED
*set bluePrintName to match the name of the 7.1.0 blueprint
removed old duplicate 7.1.0 references from application.yml
testing done:
Started local cloudbreak
created environment
checked that the 7.1.0 AWS definition appears with the correct name
built the OpDB cluster
checked that uses the intended blueprint (with Phoenix)
Closes #CB-5752
=> CB-5752 OpDB 7.1.0 cluster definitions out of sync for AWS and Azure

freeipa/src/main/java/com/sequenceiq/freeipa/controller/validation/CreateFreeIpaRequestValidator.java
Fix the CDP_FREEIPA_HA entitlement check to use the IAM service as the
internal actor's service. The UMS requires the internal actor to be
IAM.
This was tested locally with the mock-caas.
Closes #CB-5896
=> CB-5896: Use the IAM service for the CDP_FREEIPA_HA entitlement

cloud-common/src/main/java/com/sequenceiq/cloudbreak/concurrent/ActorCrnTaskDecorator.java, cloud-common/src/main/java/com/sequenceiq/cloudbreak/concurrent/CompositeTaskDecorator.java, cloud-common/src/test/java/com/sequenceiq/cloudbreak/concurrent/ActorCrnTaskDecoratorTest.java, cloud-common/src/test/java/com/sequenceiq/cloudbreak/concurrent/CompositeTaskDecoratorTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/configuration/UsersyncConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/repository/UserSyncStatusRepository.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/operation/OperationAcceptor.java, freeipa/src/test/java/com/sequenceiq/freeipa/configuration/UsersyncConfigTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncServiceTest.java
This PR contains two commits to address the behavior exhibited in CDPCP-1549.
CDPCP-1549. Run user sync internals as internal user
An authorization mismatch between the Operation db and the UserSyncStatus
db resulted in a bug where a user sync operation can be accepted, but
will fail when saving the user sync status. This commit changes the
authorization behavior so that authoriation is only performed on acceptance
of the sync operation. All the user sync internals are run as the internal
user.
CDPCP-1549. Catch and fail user sync operation
There was a gap where exceptions could cause user sync to fail but
not be recorded in the Operation database. This would prevent another
user sync from being accepted even though the current user sync was
not actually running. Eventually, the operation …
=> CDPCP-1549. Fix issue where user sync failure is not recorded

freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthDetailsService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthServiceTest.java
This patch adds an issue entry when the node is UNREACHABLE.  This is to provide better end user messaging with the health check.
Updated and ran unit tests as well as verified with local freeipa against AWS instance.
=> CB-5520: Health check provide a message in instance issues when the node is UNREACHABLE

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParametersConsts.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsCloudWatchService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsTerminateService.java, cloud-aws/src/main/resources/definitions/aws-cb-policy.json, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsTerminateServiceIntegrationTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsTerminateServiceTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/cloud/StackToCloudStackConverter.java
This change adds an automatic cloudwatch alarm during
the instance creation for AWS and removes it during
termination. This is only necessary for AWS as Azure
enables this by default. This enables an instance to
automatically recover when the underlying hardware,
owned by AWS, is faulty.
This was tested manually and verified that only FreeIPA instances receive the cloudwatch alarm.
=> CB-5099: FreeIPA changes to support AWS instance recovery

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
This removes cors.enabled=true from the topology.xml. I am working on testing this on some real clusters.
=> CB-6066 - Remove WebAppSec cors.enabled from topology.xml.j2

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProviderTest.java
As part of CDP DC, Knox is doing CM discovery of topologies which was previously disabled. However this should be disabled for CDP public cloud. This sets the config to back to false for CDP public cloud only.
=> CB-6094 Disable Knox CM auto discovery

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxBaseImageTests.java
Ignore SdxBaseImageTests temporarily
=> CB-6101 SdxBaseImageTests.testSDXWithBaseImageCanBeCreatedSuccessfully failed

core/src/main/resources/defaults/blueprints/cdp-opdb-710.bp
* YARN Service added to OpDB template
* Disable HDFS DataNode cache
* Reduce HBase RegionServer heap to 7GB
* Reduce HBase BucketCache to 6.5GB
Testing: Added custom blueprint to mow-dev and created a cluster. Verified Yarn service is present on the right instances, memory allocation is set accordingly and CM does not show memory overallocation for any of the hosts.
=> CDPD-8316 Add YARN to OpDB

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java, datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidator.java, datalake/src/test/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidatorTest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentRequest.java, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java, mock-caas/src/main/resources/application.yml
Adds IDBroker mapping validation as an entitlement and defaults the feature flag of environment request to true for IDBroker mapping validation. This lays the way to enable this per tenant in CDP in case there are issues with SimulatePrincipalPolicy due to IAM limits or other AWS issues (altus found that SimulatePrincipalPolicy is not always accurate).
=> CB-5768 Add entitlement and enable feature flag for IDBroker mapping validation

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaModelDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/FreeIpaServerResponse.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/config/FreeIpaDomainUtils.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/config/KerberosConfigRegisterService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/config/LdapConfigRegisterService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/DnsLoadBalanceSetupService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java, freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverterTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/config/KerberosConfigRegisterServiceTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/config/LdapConfigRegisterServiceTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/DnsLoadBalanceSetupServiceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/freeipa/DnsRecordAddResponse.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/freeipa/DnsRecordShowResponse.java
The kerberos configuration and ldap configuration will use a DNS load
balanced entry. This will allow a failed client to reconnect to a
different server.
Some of the unit tests were updated and it was manually tested with an
LDAP client. The LDAP client tries the first DNS entry and on failure,
it can retry. FreeIPA returns the entries in a random order, so it
will eventually try a working node. Java can be configured to cache
good and bad nodes.
Closes #CB-5904
=> CB-5904: Use CA DNS name for Kerberos and LDAP

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
The DNSName is now encoded correctly as:
{
"__dns_name__": "value_goes_here"
}
Previously it was encoded as:
"value_goes_here"
I think this was only working because the server was compatible with a
very old version of the FreeIPA API which supported the old version.
The FreeIpaClient implementation was not compatible with the API
version it claimed to use.
This was manually tested to ensure it works with a local deployment of
cloudbreak.
Closes #CB-6147
=> CB-6147: Fixed FreeIpaClient to properly encode DNSName

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/model/AdvertisedRuntime.java, datalake/src/main/java/com/sequenceiq/datalake/configuration/CDPConfigService.java, datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/main/resources/runtime/7.0.2/aws/light_duty.json, datalake/src/main/resources/runtime/7.0.2/aws/medium_duty_ha.json, datalake/src/main/resources/runtime/7.0.2/azure/light_duty.json, datalake/src/main/resources/runtime/7.0.2/azure/medium_duty_ha.json, datalake/src/main/resources/runtime/7.0.2/mock/light_duty.json, datalake/src/main/resources/runtime/7.0.2/yarn/light_duty.json, datalake/src/main/resources/runtime/7.0.2/yarn/medium_duty_ha.json, datalake/src/test/java/com/sequenceiq/datalake/configuration/CDPConfigTest.java
This is not going to have any effect on Mow Dev -> Prod, although it will help us to execute the upgrade tests easier in local dev.
Just set up -Ddatalake.supported.runtime=  in datalake. If you enable it, unfortunately, you need to be sure that you use the runtime dropdown on the UI because the 7.0.2 is selected as default. It is going to be solved with some UI changes in the near future.
=> Re-enable 7.0.2 for upgrade

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientException.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/auth/InvalidPasswordException.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/auth/InvalidUserOrRealmException.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/auth/PasswordExpiredException.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/GatewayConfigService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/TlsSecurityService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactoryTest.java
This change adds an automatic retry on the FreeIpaClientFactory
getFreeIpaClient* methods.  These methods perform a login.
Manually verified by blocking http/https ports.  This is necessary
in FreeIPA HA environments where there might be a failover and
the client should retry.
=> CB-6035: FMS should relogin on failures

integration-test/build.gradle
spring boot jetty server was kind of incompatible with spark server usage of sslcontext. it has been downgraded just in integration tests
Closes 6238
=> CB-6238 downgrading spring boot for integration test

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaCapabilities.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Config.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/user/event/SetPasswordRequest.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/user/handler/SetPasswordHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsCredentialProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java, freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/user/handler/SetPasswordHandlerTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UmsCredentialProviderTest.java
The setPassword call now uses the password hash and keys from UMS
when possible. Note that we plan to deprecate / remove this endpoint
soon, but for now the UI is still calling it and this behavior
will keep the UMS keys consistent with the keys in FreeIPA, which
is desirable for user keytab generation.
=> CDPCP-1601. set-password now uses credentials from control plane

core/src/main/resources/application.yml, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/imagecatalog/ImageCatalogTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
We do not have to delete image validation source catalog aftet test, thus I added a logic to skip cleanup in this case
=> CB-5317 Skip cleanup in case of image validation catalog

orchestrator-salt/src/main/resources/salt-common/salt/monitoring/init.sls, orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/init.sls
Currently when pip is first invoked, the pip cache
is populated by reaching out to the internet. Using
--no-index will avoid this call out to pypi and
prevent the call out to the internet.
This is an optimization only. If pypi access is
blocked, then this won't fail even without using
--no-index. This prevents the call from happening
at all.
=> CB-6307 Use pip list --no-index to avoid calls out to the internet

freeipa/src/main/java/com/sequenceiq/freeipa/entity/UserSyncStatus.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/poller/CooldownChecker.java, freeipa/src/main/resources/schema/app/20200313110708_CDPCP-1533_store_operations_in_user_sync_status.sql, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/poller/CooldownCheckerTest.java
First part to the rolling update of the freeipa database schema
for tracking user sync status.
This commit adds the requested and successful operations to the
usersync status. The new lastrequestedoperation field is preferred
but lastsyncstarttime field is still used as a
fallback when calculating whether a stack is "cool" for the purposes
of automatic user sync polling.
=> CDPCP-1533. Add operations to usersyncstatus

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup
This changes the command to upload the backups to the cloud provider
to be a simple copy instead of a sync to that a ListBucket permission
is not needed.
Closes #CB-6333
=> CB-6333 Remove dependency on ListBucket (List Objects)

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup
This removes an extra slash that was causing a blank directory
to be created on S3 for the FreeIPA backup.
Closes #CB-6351
=> CB-6351 Remove extra blank dir from S3 path for FreeIPA backup

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java, freeipa/src/main/java/com/sequenceiq/freeipa/entity/Stack.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthDetailsService.java, freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaChecker.java, freeipa/src/test/java/com/sequenceiq/freeipa/client/FreeIpaClientTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthServiceTest.java
This patch changes the health check to return individual
health of all HA nodes. The cn of the server_conncheck API
must be the host that the client is connected to. So we
exposed the connected hostname to use as the first parameter
of the API call.
Updated unit test.
Manually validated against 3 node FreeIPA and various levels of failure.
Also fixes:
CB-6226
=> CB-6225: health check not returning status of all hosts.

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaBackupConfigView.java
This adds the azure_instance_msi to the pillar that was missing.
Closes #CB-6376
=> CB-6376 azure_instance_msi missing from backup configuration for FreeIPA

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java, freeipa-client/build.gradle, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientException.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientExceptionUtil.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientExceptionWrapper.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/RetryableFreeIpaClientException.java, freeipa-client/src/test/java/com/sequenceiq/freeipa/client/FreeIpaClientExceptionUtilV1Test.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/RetryableFreeIpaClientService.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/DnsV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/AbstractFreeIpaCleanupAction.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberos/v1/KerberosConfigV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtRoleComponent.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java, freeipa/src/main/java/com/sequenceiq/freeipa/ldap/v1/LdapConfigV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/dns/DnsZoneService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaTopologyService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/host/HostDeletionService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaRootCertificateService.java, freeipa/src/main/resources/application.yml, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaTopologyServiceTest.java
When an instance of FreeIPA fails, the FreeIPA management service will
retry with a delay. When cluster proxy mode is used with FreeIPA HA,
the delay will allow cluster proxy to switch over to a working
instance of FreeIPA.
Retries are performed on the FreeIPA management service APIs, but not
flows nor user sync.
Retries are only performed with certain errors occur that have a
reasonable chance of succeeding on a retry.
Closes #CB-6043
=> CB-6043: FreeIPA management service should retry FreeIPA APIs

orchestrator-salt/src/main/resources/salt/salt/cloudera/repo/cloudera-manager.list, orchestrator-salt/src/main/resources/salt/salt/cloudera/repo/init.sls
I am working on CFM-889 to implement ubuntu16 base image. During testing we discover, that repo init is not working for ubuntu16 and this change is necessary for that.
=> [CFM-889] Modify repo init to work for ubuntu16 as well

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaModelDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/describe/DescribeFreeIpaResponse.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/usersync/UserSyncStatusResponse.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/usersync/UserSyncStatusToUserSyncStatusResponseConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsEventGenerationIdsProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncStatusService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaDescribeService.java, freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverterTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/converter/usersync/UserSyncStatusToUserSyncStatusResponseConverterTest.java
The last started and last successful operation ids are exposed through
the describe freeipa api. Also included are the event generation ids
for the last successful full sync. This information can be user to
determine whether an environment is up-to-date by comparing with the
event generation ids from the UMS.
=> CDPCP-1534. Expose UserSyncStatus through describe freeipa api

core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-702.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-710.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-711.bp, core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-ha-702.json, core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-ha-710.json, core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-ha-711.json, core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-ha-702.json, core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-ha-710.json, core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-ha-711.json
1. CB-5660 added the ability to have JN across node groups.
2. Tested the template and the fix for CB-5660 works for the DE HA template in a private stack.
=> DISTX-397 DE HA template co-locate JN and ZK nodes to masters and manager

freeipa/src/main/java/com/sequenceiq/freeipa/controller/exception/UnsupportedException.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/mapper/UnsupportedExceptionMapper.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/UserKeytabService.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/UserKeytabServiceTest.java
The user keytabs we generate are only valid on FreeIPAs that have password
hash support. This change returns an appropriate error based on this.
=> CDPCP-1735. Error message when getting user keytab on older FreeIPA

autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/v1/AlertEndpoint.java, autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/v1/DistroXAutoScaleClusterV1Endpoint.java, autoscale/src/main/java/com/sequenceiq/periscope/controller/AlertController.java, autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java, autoscale/src/main/java/com/sequenceiq/periscope/controller/DistroXAutoScaleClusterV1Controller.java, autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterRepository.java, autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java, autoscale/src/test/java/com/sequenceiq/periscope/controller/AlertControllerTest.java
CB-5734 Additional Validations
1. Load Based Scaling Enabled only for clusters with cluster-proxy tunnel.
2. Additional Validation for invalid crn or name.
=> CB-5734 Additional Validations for DistroX Autoscale API

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup, freeipa/src/main/resources/freeipa-salt/salt/freeipa/templates/freeipa_backup_hourly.j2, freeipa/src/main/resources/freeipa-salt/salt/freeipa/templates/freeipa_backup_monthly.j2
This change enables the backup script to report a single
line status. This enables easier parsing of the last
backup status for the health checks.
Local deployment and validation.
=> CB-6494: Update FreeIPA backup scripts to provide status

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java, core/src/main/resources/schema/app/20200408152731_CB-6380_Do_not_persist_telemetry_for_stack_template.sql
- do not add telemetry component for stacks with type 'TEMPLATE'
- remove already existing ones from DB
tested against dtahub deployments with default cluster definitions + custom ones
=> CB-6380. Do not persist telemetry component for stack with template type

core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-ha-702.json, core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-ha-710.json, core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-ha-711.json, core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-ha-720.json, core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-ha-702.json, core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-ha-710.json, core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-ha-711.json, core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-ha-720.json
1. From 2.20 there is support for the external database via CLI or cluster definition.
2. Adding the external database to be of type HA. We do not have multi-az clusters in the HA template, still choosing HA type because the NON_HA database in a HA cluster sounds odd.
3. This does not work in the private stack, it looks like this feature is undergoing modification in 2.20 itself CB-6137.
make
=> DISTX-397 For DE HA template use HA external database

freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/UserKeytabService.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/UserKeytabServiceTest.java
If the actor does not have any credential keys in UMS it indicates they have not set their workload password. A proper error message is now propagated in this situation.
=> CDPCP-1848. Better error message on missing keys for getKeytab

freeipa/src/main/resources/freeipa-salt/salt/freeipa/common-install.sls, freeipa/src/main/resources/freeipa-salt/salt/freeipa/templates/ipa-rewrite.conf.j2
The httpd rules were updated to allow the DNS load balanced domain
names to be used for connecting to FreeIPA directly without using the
nginx interface.
This was tested manually to ensure clients were not rejected with a
301 error.
Closes #CB-6558
=> CB-6558: Fix FreeIPA refer URL so the DNS load balanced names work

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigService.java, common/src/test/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigServiceTest.java, environment/src/main/java/com/sequenceiq/environment/telemetry/service/AccountTelemetryService.java, environment/src/test/java/com/sequenceiq/environment/telemetry/service/AccountTelemetryServiceTest.java
- encode default anonymization rules (no validation yet for inputs)
- decode anonymization rules during salt config generation
- updated tests
=> CB-6569. Encode (base64) regex input for anonymization rules (log collection)

orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls
When we query IPA from a lot of instances in parallel, some cases the IPA server gives a DNS Zone not found error:
```
{
"error": {
"code": 4001,
"data": {
"reason": "krisz-en.xcu2-8y8x.wl.cloudera.site.: DNS zone not found"
},
"message": "krisz-en.xcu2-8y8x.wl.cloudera.site.: DNS zone not found",
"name": "NotFound"
},
"id": 0,
"principal": "HTTP/ipaserver0.krisz-en.xcu2-8y8x.wl.cloudera.site@KRISZ-EN.XCU2-8Y8X.WL.CLOUDERA.SITE",
"result": null,
"version": "4.6.5"
}
```
This is not a timeout in the cli, but an actual IPA server response. To avoid this we shouldn't actually query IPA all the time. + it save a lot of time durring highstate
=> CB-6544 do not check dns records in every highstate

template-manager-tag/src/main/java/com/sequenceiq/cloudbreak/tag/DefaultCostTaggingService.java, template-manager-tag/src/test/java/com/sequenceiq/cloudbreak/DefaultCostTaggingServiceTest.java
=> CB-6526. Allow cluster/env luanch to specify a tag key already specified at the account level as long as the value is identical.

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/listener/VerboseLogReporter.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/log/Log.java
@afarsang and @lnardai please review
Unfortunately the `org.testng.internal.InvokeMethodRunnable$TestNGRuntimeException` cannot be removed or workaround.
=> CB-6464 Restore Test Failure message for Test Reports

environment-api/src/main/java/com/sequenceiq/environment/api/v1/telemetry/endpoint/AccountTelemetryEndpoint.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/telemetry/model/request/TestAnonymizationRuleRequest.java, environment/src/main/java/com/sequenceiq/environment/telemetry/service/AccountTelemetryService.java, environment/src/main/java/com/sequenceiq/environment/telemetry/v1/controller/AccountTelemetryController.java, environment/src/test/java/com/sequenceiq/environment/telemetry/service/AccountTelemetryServiceTest.java
Add validation before creation (not by validation classes - it's easier like this as pattern validation already used in the service)
+ removed no-match test
+ Use a list of patterns instead one pattern for test anonymization pattern api
+ Add Valid annotation (to make sure anonymization rule contains a value)
+ updated ITs
=> CB-6647. Validate anonymization rules regex before creation.

core/src/main/resources/defaults/blueprints/cdp-opdb-710.bp
Yarn stores the application logs on the local filesystem due to OPSAPS-54760. As a workaround to store these logs on the object store the config needs to be set as empty.
Testing: Created cluster from custom blueprint and executed a CompactionTool MapReduce job. The container logs were available on S3 filesystem.
=> CDPD-10146 [opdb] Store Yarn app logs on object store

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/RecipeExecutionPhase.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/KerberosConfigTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RecipeClusterTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/clouderamanager/CMUpscaleWithHttp500ResponsesTest.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java, orchestrator-salt/src/main/resources/salt/salt/sssd/ipa-leave.sls
1. In this commit, we optimize the salt execution times by removing the `high state apply` after each phase of recipe execution.
2. There is only one high state apply in all the nodes after a scale-up.
3. We could still optimize the individual scripts like metering which always removes and adds the same package in all the nodes of the cluster for every scale-up.
4. This is the first time modifying something in salt, so I will focus on further optimization after getting initial feedback.
5. Also removed the deprecated pre/post-execution phases. Made sure that there are no existing salt scripts for such phases.
./gradlew build && test scale-up in a private stack to see the time getting reduced from 5 mins to 4 mins.
=> DISTX-415 Reduce the amount of time it takes to add new nodes

core/src/main/resources/defaults/blueprints/cdp-data-engineering-711.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-720.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-711.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-720.bp
The normal 7.1.1 blueprint was tested on manowar-dev and resulted in a successful cluster deployment which included Queue Manager.
=> CB-3958 Add Queue Manager service to all Data Engineering blueprints for 7.1.1 and 7.2.0

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentOpDescription.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentApiConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java, environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentModificationServiceTest.java
add "change_telemetry_features" by env crn and env name
use in a similar way as credential is used.
problem with edit request. if in telemetry, something is null, its not clear that should be deleted or changed.
by adding new endpoints for feature:
- if feature is missing from the input, that is not changed
- if feature is filled, that is updated
also on UI or on public API side, it's a bit problematic to update one feature as we need to send the exact same telemetry request back with the changed properties. That means on UI/Public API we need to make sure to iterate through on the request, put everything in the response (we cannot miss anything, so it needs more maintenance)
=> CB-6245. Add change environment level telemetry features endpoints (by env crn/name)

core-api/src/main/resources/definitions/exposed-services.json
Remove trailing slash from HBase UI link to workaround a Knox bug
Testing done: Checked from Firefox that the 
https://psomogyi-opdb-gateway3.psomogyi.xcu2-8y8x.dev.cldr.work/psomogyi-opdb/cdp-proxy/hbase/webui/master?host=psomogyi-opdb-master4.psomogyi.xcu2-8y8x.dev.cldr.work&port=16010 URL works.
The trailing slash was removed after hbase/webui/master
=> CDPD-10605 HBase UI link incorrect redirection

cloud-aws/src/main/resources/definitions/aws-cb-policy.json
This patch just adds the privileges to be able to run the
aws command to retrieve the cloudwatch alarm.  The actual
check will be included as part of the RPM for the health
agent.
=> CB-5958: Add cloudwatch check to health check

core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceGroupRepository.java
Finding instacegroups without terminated metadata query does not return those instanceGroups that has no instance metadata at all
Solution
-> check if instancemetadata is null  (i have tried with is null and is empty together, but with is null it resulted the same)
after the change,  resize window looks like this (without gateway and compute nodes):
do not merge yet (only after @daszabo reviewed this, just to make sure getting back instanceGroups are fine if no instanceMetadata is totally fine)
=> CB-6730. Instance groups are not listed in stack response if instancence metadata is attached to it

freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java
As per design a user should be able to get a keytab for themselves
without needing any rights. The authorization done through the
annotation has been removed to get this working as expected.
=> CDPCP-1887. Remove environment read requirement for getUserKeytab

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxNotificationService.java
- this needs to be enabled since the UI get's the status update from DL through Notifications
// This is disabled since it causes confusion in the event log, because they are not persisted
It's designed that way not to store those updates in the event log
=> CB-6675 reenable notificaiton sending from Datalake

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaHostNotAvailableException.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaChecker.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactoryTest.java
Fixes the health check so that it is able to run when the stack is
unavailable.
Fixes the stack status so that when it is unavailable it doesn't
bounce between unavailable and unhealthy every minute, but rather it
remains unavailable until it should actually change.
Fixes some exception handling so that it checks the exceptions that
are wrapped inside a FreeIpaClientException.
In addition to updating the tests, this was validated on a cluster
that was stuck in the unavailable status to ensure it became
available after the problem was fixed.
Closes #CB-6745
=> CB-6745: Allow FreeIPA health check when the stack is unavailable

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaHostNotAvailableException.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java, freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaChecker.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactoryTest.java
Fix the status reported when FreeIPA is unreachable and cluster proxy
is being used. The status should be unreachable rather than unhealthy.
This fixes the unavailable status when using cluster proxy so that it
reports the same status as direct mode.
This was tested manually by blocking the network to FreeIPA and
checking the status.
Closes #CB-6769
=> CB-6769: Fix FreeIPA unavailable status when using cluster proxy

core-api/src/main/resources/definitions/exposed-services.json, core-api/src/test/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollectorTest.java, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
Fixed the Atlas cdp-proxy-api url to point to the correct base path.
=> CB-6687 Atlas cdp-proxy-api URL is not correct in CB UI

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidator.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidatorTest.java
AzureIDBrokerObjectStorageValidator compared uuid style id's (principal id's) with path style id's (fully qualified resource id's). Fix compares principal id's with principal id's during validation.
Tests:
- Updated AzureIDBrokerObjectStorageValidatorTest
- Tested Azure datalake creation manually.
Closes CB-6782
=> CB-6782 Fix Azure Id Broker role assigmnent validation

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigView.java, freeipa/src/main/resources/freeipa-salt/salt/fluent/template/input.conf.j2, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/telemetry/TelemetryTestDto.java, orchestrator-salt/src/main/resources/salt-common/pillar/fluent/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls, orchestrator-salt/src/main/resources/salt/salt/fluent/template/input.conf.j2
add new fluent attribute: dbusIncludeSaltLogs (if we want this to be extended to the UI in the future, that can be moved out from here, and put into AccountTelemetry as a real boolean flag)
- do not enable processing of salt logs by default for cluster deployment logs collection
- enable this option for e2e tests
=> CB-6800. Log collection: make salt logs processing configurable (dbus -> disable by default)

orchestrator-salt/src/main/resources/salt/salt/metering/init.sls
it was needed as in older images, the rpm name changed in the same version mow CB version (with different build - it means the new rpm was not installed, but old one used the same files as the new one, so first, it was required to remove that). now it's not required anymore to remove the old one
also it includes to mode <-> file_mode fixes
=> CB-6808. Removing old metering rpm is not required anymore.

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncAcceptor.java
When changes are applied to a single user (like setting credential,
or deleting user) we would like to immediatly sync them instead
of needing to wait for potentially long full sync to finish first.
This change lets single user sync operations to always be accepted
even when full syncs are running.
=> CDPCP-1561. Always accept single user sync operation

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UserModelDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeAllUsersRequest.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java, freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncServiceTest.java
Previously the accountId to sync was inferred from the calling
user, which doesn't work when the calling user is the internal
actor. This is fixed by including accountId as an optional
parameter to the user sync request.
=> CDPCP-1561. Allow internal actor to call user sync endpoint

orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/check_fluent_plugins.sh.j2
it is required to avoid this situation:
- older Cluster (like 2.19)
- newer image (as some changes were required for 2.20, as we are building images from master -> for a newer 2.19, probably we will upgrade some binaries/plugins there)
- when applying 2.19 salt script -> in the newer image, it's possible there are newer plugins, this check plugins script will delete those plugins and will re-install the old versions.
(of course that will be fixed from CB 2.20...just described that problem with a 2.19 example)
=> CB-6816. Do not downgrade fluent plugins on newer images.

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup, freeipa/src/main/resources/freeipa-salt/salt/freeipa/templates/freeipa_backup_hourly.j2, freeipa/src/main/resources/freeipa-salt/salt/freeipa/templates/freeipa_backup_monthly.j2
This adds a new status file to record the last status
for the monthly and hourly backups.
Deployed to AWS, waited for hourly backup to complete.  Manually ran monthly backup from cron entry.
=> CB-4378: Add backup status for monthly and hourly

redbeams/src/main/java/com/sequenceiq/redbeams/sync/DBStackStatusSyncService.java, redbeams/src/test/java/com/sequenceiq/redbeams/sync/DBStackStatusSyncServiceTest.java
CB-6791 Null status should not be set on DB Stack.
=> CB-6791 Null status should not be set on DB Stack.

freeipa/src/main/resources/freeipa-salt/salt/freeipa/backups.sls
This prevents the monthly backup from running, when enabled, until the next month after the initial install.  This is the first step to fixing CB-6717 across multiple FreeIPA HA nodes.
Closes #CB-6879
=> CB-6879: Redundant full backup created on Azure FreeIPA HA hosts

cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterProxyConfiguration.java, cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterProxyRegistrationClient.java, cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterServiceConfig.java, cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterServiceHealthCheck.java, cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ReadConfigEndpoint.java, cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ReadConfigRequest.java, cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ReadConfigResponse.java, cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ReadConfigService.java, core/src/main/resources/application.yml, freeipa/src/main/java/com/sequenceiq/freeipa/client/CookieAndStickyId.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/provision/handler/ClusterProxyUpdateRegistrationHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/polling/clusterproxy/ServiceEndpointHealthListenerTask.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/polling/clusterproxy/ServiceEndpointHealthPollerObject.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ClusterProxyService.java, freeipa/src/main/resources/application.yml
DEPENDS ON: https://github.com/hortonworks/cloudbreak-deployer/pull/657
Use cluster proxy HA for FreeIPA connections. Configure cluster proxy
to monitor the FreeIPA health using the login page. A better health
check is being developed, but the login will at least allow cluster
proxy to determine if FreeIPA is reachable.
Use a sticky session to maintain the connection to a specific FreeIPA
instance.
When provisioning, wait for the HA endpoint provide a good status
before continuing to provision.
This was tested manually, by stopping nginx on one node and performing
FreeIPA management service requests to FreeIPA. Then the first node
was brought back up and the same thing was done after bringing the
second node down.
Closes #CB-4377
=> CB-4377: Use cluster proxy HA for FreeIPA connections

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProviderTest.java, template-manager-cmtemplate/src/test/resources/input/cb6720.bp
In CM 7.2 and above, ranger db configs moved from
role to service level. Update the cm template to
address for this.
Added unit-tests to verify that correct service templates
are generated.
Closes CB-6720
=> CB-6720: Update Ranger configs for CM 7.2+

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigView.java, freeipa/src/main/resources/application.yml, freeipa/src/main/resources/freeipa-salt/pillar/freeipa/init.sls, freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_install.sh, freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_replica_install.sh, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigServiceTest.java
This forces the dnssec.validation of the FreeIPA DNS server to be
disabled for Azure deployments. It allows for the config to set the
DNSSEC validation based on the Cloud Platform deployment that the stack
is being deployed to.
This uses the freeipa.platform.dnssec.validation.<PLATFORM> config property
to set this on a per Cloud Platform basis.
Closes #CB-6948
=> CB-6948: Force disable DNSSEC for Azure environments.

orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/check_fluent_plugins.sh.j2
in case of fluent plugin version should be upgraded without internet connection (like old image is used for newer CB), it's better if the user will read the right error message instead of td-agent start failed.
=> CB-6920. Use proper error message in case of fluent version incompatibility (No network)

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaChecks.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa-client/src/test/java/com/sequenceiq/freeipa/client/FreeIpaChecksTest.java, freeipa-client/src/test/java/com/sequenceiq/freeipa/client/FreeIpaClientTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncConstants.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/FmsGroup.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/FmsUser.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UmsUsersState.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersStateDifference.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProviderTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncServiceTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersStateDifferenceTest.java
Groups that do not exist in the control plane at all can be safely removed
from IPA. The UmsUsersState has modified to include all WAGs so we can make
this determination.
Some protections were added to the FreeIPA client to prevent adding/removing
certain users that user sync should not touch. e.g., this prevents accidentally
removing the admin user or the admins group.
Added unit tests for new behavior
Tested manually by adding a group and running user sync
=> CDPCP-2043. Remove groups that don't exist in control plane from IPA

common-model/src/main/java/com/sequenceiq/common/api/telemetry/base/FeaturesBase.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/doc/TelemetryModelDescription.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/Telemetry.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigService.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigView.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserService.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/telemetry/EnvironmentFeatures.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/TelemetryApiConverter.java, environment/src/main/java/com/sequenceiq/environment/telemetry/service/AccountTelemetryService.java, environment/src/main/java/com/sequenceiq/environment/telemetry/v1/converter/AccountTelemetryConverter.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/TelemetryApiConverterTest.java, orchestrator-salt/src/main/resources/salt-common/pillar/fluent/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/databus_monitoring.conf.j2, orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/td-agent.conf.j2
skipping freeipa metrics (as those are not done yat). so only included core + env converters (not the freeipa one)
=> CB-6833. Send node metrics to CdpVmMetrics kinesis stream (by fluentd).

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltConnector.java, orchestrator-salt/src/main/resources/salt/salt/metadata/settings.sls
Old images with 2017.7.5 and 2017.7.7 will continue to work as both param is present. 
```
Changed in version 2017.7.0: The expr_form argument has been renamed to tgt_type, earlier releases must use expr_form.
```
https://docs.saltstack.com/en/latest/topics/releases/2017.7.0.html#expr-form-deprecation
=> CB-7024 Salt change: deprecated expr_form to tgt_type to support Salt 3000+

orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/backup_db.sh, orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/restore_db.sh
Create bash scripts to run PostgreSQL dump and restore against `hive` and `ranger` databases.
* Add `backup_db.sh`
* Add `restore_db.sh`
Scripts accept:
1. Cloud Provider (azure | aws)
2. PostgreSQL host name.
3. PostgreSQL port.
4. Object Storage Service url to save backups.
5. PostgreSQL user name.
6. PostgreSQL password.
The backup script stores backups in the Cloud Object storage under a Date String prefix, e.g. `s3://backup-bucket/2020-04-28T18:12:53Z`.
Storage service URLs are different when doing backup versus restore. The parent folder is specified for backup, while the particular date folder should be specified for restore.
* Backup to `s3://backup-bucket`
* Restore from `s3://backup-bucket/2020-04-28T18:12:53Z`
The backup script:
1. Runs `pg_dump`, outputting to a local file
2. …
=> Add backup and restore scripts for DL postgres db.

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProviderTest.java, template-manager-cmtemplate/src/test/resources/input/cb6720.bp
In CM 7.2.1 and above, ranger db configs moved from
role to service level. Update the cm template to
address for this.
Closes CB-6720
=> CB-6720: Update Ranger configs for CM 7.2.1+

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/backup/cloud/AdlsGen2BackupConfigGenerator.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/backup/cloud/AdlsGen2BackupConfigGeneratorTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/backup/cloud/CloudBackupFolderResolverServiceTest.java
This changes the backup location for FreeIPA backups to the older blob.core.windows.net to the same location that is used by telemetry (dfs.core.windows.net)  so we have the same dns url to be used with things like Private Link.
Closes #CB-7048
=> CB-7048: Change FreeIPA ASDL backup location from older .blob. to .dfs

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestErrorLog.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/mock/HttpMock.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/log/Log.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java
when tests are could not be fixed, instead of removing or skipping the whole test ,developer can use skipWhenFail() or validate() at the end of the test code. skipWhenFail() let the test run as usual do all the reporting, but skip if exceptions were collected during the run.
If the test or functionality fixed skipWhenFail() easily may swap with validate().
=> CB-7063 tests could be skipped if developer find it flaky

core/src/main/resources/defaults/blueprints/cdp-data-engineering-702.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-710.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-720.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-702.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-710.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-710.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-720.bp
1. CB-6547 identified a parity between normal template and HA templates.
2. There is not much difference between the templates but when one exists it takes a lot of time to figure out the parity.
3. To ease parity identification, as a first step sorting and indenting the DE templates.
4. To ease code review, this change does not contain any other modification than sort order and indentation.
5. The algorithm is `jq  '.blueprint.services|=sort_by(.refName)|.blueprint.services[].roleConfigGroups|=sort_by(.refName)|.blueprint.hostTemplates|=sort_by(.refName)|.blueprint.hostTemplates[].roleConfigGroupsRefNames|=sort'`.
6. Spot checked the difference between non ha and ha for couple of versions.
=> DISTX-445 Indent and sort DE templates for checking parity

freeipa/src/main/resources/freeipa-salt/salt/freeipa/backups.sls, freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup
This adds locks to the backup scripts so that only one backup
job can run at any one time on a host.
As well it reorders the deployment of the corn jobs until after the
running of the initial backup.
Closes #CB-7089
=> CB-7089: Prevent FreeIPA backup script parallel runs

auth-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/usermanagement/UserManagementGrpc.java, auth-connector/src/main/proto/usermanagement.proto, common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientExceptionUtil.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/user/handler/SetPasswordHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/WorkloadCredentialService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsCredentialProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/SyncStatusDetail.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/WorkloadCredential.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/WorkloadCredentialServiceTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncServiceTest.java, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java, mock-caas/src/main/resources/application.yml, mock-caas/src/test/java/com/sequenceiq/caas/grpc/service/MockUserManagementServiceTest.java
Ssh public keys are retrieved for each user as part of the UMS
GetActorWorkloadCredentials API. The user sync code to set workload
passwords in FreeIPA has been refactored to sync both the hashed
password and the public keys.
FreeIPA may return an 4202 error code during the user-mod call that can
be safely ignored. This error indicates that the mod list is empty and
may occur if the user does not have a hashed password set in the UMS and
does not have any ssh public keys. Exception handling in the user sync
code has been improved to also ignore similar exceptions for user and
group addition and removal as well as group membership changes.
Non-ignorable exceptions are now propagated to the sync operation status.
Environments with these exceptions are now put in the "failure" list
instead …
=> CDPCP-808 Sync SSH keys to IPA

orchestrator-salt/src/main/resources/salt/salt/kerberos/config/krb5.conf-existing
The current configuration of the krb5.conf does not handle FreeIPA HA well.  It is dependent on using Round Robin DNS entries to failover Kerberos KDC connections.  This does not allow for retrying connections and moving to the failover FreeIPA node.
For ipa based configs, the krb5.conf needs to be as close as possible to the configuration laid down by the ipa-client-install. This allows the KDC and admin service to be looked up via DNS and Kerberos understands that when there are multiple hostnames pulled from the DNS service record that it is supposed to retry and failover to those hostnames.
Closes #CB-7115
=> CB-7115: Updated krb5.conf configuration to better handled FreeIPA HA

core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-710.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-720.bp
There's also some conflicts in the 711 templates. However - afaik - those are not used and should just be deleted. Will create a jira and second PR to remove those.
=> Fix Data Engineering templates post merge

cloud-azure/build.gradle, gradle.properties, integration-test/build.gradle, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxCloudStorageTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudFunctionality.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/AwsCloudFunctionality.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/AzureCloudFunctionality.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/AzureCloudBlobUtil.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java
I noticed that azure storage assert in e2e tests is checking all blobs in the given container which is time consuming and unnecessary, so I changed to check only the cluster and freeipa of the given test
=> CB-7073 azure storage assert should check only the clusters of the test

cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterServiceConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/polling/clusterproxy/ServiceEndpointHealthListenerTask.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ClusterProxyService.java
FreeIPA provisioning using CCM was fixed. When provisioning, cluster
proxy registration occurred with bootstrapping information followed by
additional connections. The second registration used gateway
config's port which had been updated to refer to cluster proxy's port.
This was fixed so that it always refers to NGINX.
The FreeIPA client builder was fixed so that very old clusters which
were provisioned before the stack's port was saved will still work.
Reregistering FreeIPA with cluster proxy was fixed so that it works
with CCM clusters which were originally provisioned prior to
cloudbreak 2.21.0. Previously the gateway's configuration was not
included in the reregistration with cluster proxy.
The accountId, tunnels, useTunnel, and tlsStrictCheck were cleaned up
from the cluster service …
=> CB-7132: Fix FreeIPA provisioning when using CCM

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaBackupConfigView.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigService.java, freeipa/src/main/resources/freeipa-salt/pillar/freeipa/init.sls, freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup, freeipa/src/main/resources/freeipa-salt/salt/freeipa/settings.sls, freeipa/src/main/resources/freeipa-salt/salt/freeipa/templates/freeipa_backup.conf.j2
This adds support to the AWS FreeIPA backup S3 uploader to set the region
to allow for the backup to use a regional endpoint.  It uses the region
defined for the stack.
This will result in upload url of s3.<region>.amazonaws.com instead of
s3.amazonaws.com as talked about in the documentation:
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html
Closes #CB-7162
=> CB-7162: FreeIPA AWS backup CLI command should use the regional endpoint

autoscale/src/main/java/com/sequenceiq/periscope/controller/AlertController.java, autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java, autoscale/src/main/java/com/sequenceiq/periscope/filter/CloudbreakUserConfiguratorFilter.java, autoscale/src/main/java/com/sequenceiq/periscope/filter/FilterConfiguration.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ScalingConstants.java, autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterPertainRepository.java, autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterRepository.java, autoscale/src/main/java/com/sequenceiq/periscope/service/AutoscaleRestRequestThreadLocalService.java, autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterPertainService.java, autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java, autoscale/src/test/java/com/sequenceiq/periscope/controller/AlertControllerTest.java
With UMS Authorization, all authorized users with DataHub permission can configure cluster autoscaling. Hence Cluster RetrievalByName,ID, CRN is associated with workspace (CB currently associates each tenant with a workspace). Also clusterNames are unique within a tenant and hence workspace.
Even though Cluster Retrieval ByCRN, ByID doesn't require workspace association, it is associated for additional security incase of leaked CRN or guessed clusterId.
=> DISTX-442 Associate Cluster Retrieval with workspace.

core/src/main/resources/application.yml, core/src/main/resources/defaults/clustertemplates/azure/azure-datamart-702.json, core/src/main/resources/defaults/clustertemplates/azure/azure-datamart-720.json
Fix instance types in datamart template on Azure:
Master:  D16_v3 -> E8_v3
Impala coordinator and executors:  D8_v3 -> E16_v3
Use less expensive instance type for master (but same memory size)
Increase size of coordinator and executor instances to match sizes used by Datamart on AWS and DWX
=> CB-5908 - Fix datamart instance types on Azure

common-model/src/main/java/com/sequenceiq/common/api/telemetry/doc/TelemetryModelDescription.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/Telemetry.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/response/TelemetryResponse.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigService.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaInstallService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java
why?
to see what anonymization rules were used for the cluster during deployment, even after the rules changed
manual testing is in progress (freeipa looks good)
=> CB-7110. Persist anonymization rules on cluster side (freeipa/datalake/datahub)

autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/validator/DistroXAutoscaleRequestValidator.java, autoscale-api/src/main/java/com/sequenceiq/periscope/client/AutoscaleUserCrnClient.java, autoscale-api/src/test/java/com/sequenceiq/periscope/api/endpoint/validator/DistroXAutoscaleRequestValidatorTest.java, autoscale/build.gradle, autoscale/src/main/java/com/sequenceiq/periscope/PeriscopeApplication.java, autoscale/src/main/java/com/sequenceiq/periscope/cache/AccountEntitlementCache.java, autoscale/src/main/java/com/sequenceiq/periscope/config/DatabaseConfig.java, autoscale/src/main/java/com/sequenceiq/periscope/controller/AlertController.java, autoscale/src/main/java/com/sequenceiq/periscope/controller/EndpointConfig.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/SuspendedClusterMonitor.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ClusterStateEvaluator.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandler.java, autoscale/src/main/java/com/sequenceiq/periscope/service/EntitlementValidationService.java, autoscale/src/main/resources/application-test.yml, autoscale/src/test/java/com/sequenceiq/periscope/controller/AlertControllerTest.java, autoscale/src/test/java/com/sequenceiq/periscope/endpointtests/DistroXAutoScaleClusterV1EndpointTest.java, autoscale/src/test/java/com/sequenceiq/periscope/modul/rejected/RejectedThreadContext.java, autoscale/src/test/java/com/sequenceiq/periscope/modul/rejected/StackCollectorContext.java, autoscale/src/test/java/com/sequenceiq/periscope/service/EntitlementValidationServiceTest.java, autoscale/src/test/java/com/sequenceiq/periscope/testcontext/EndpointTestContext.java
1. Introduce Entitlement Validations
2. Introduce SuspendedClusterMonitor which monitors suspended clusters and purges them if they are deleted in CB
3. Disable AlertEndpoint
4. Introduce DistroXAutoscaleEndpointTests which runs endpoint tests against embedded tomcat and embedded db.
Closes #DISTX-471
=> DISTX-471 Periscope Entitlement Service Integration

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncAcceptor.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncAcceptorTest.java
I noticed sync operations with a single user were still gettting rejected when there were other operations running. This is due to a bug in my earlier commit. Fixed now.
=> CDPCP-1561. Fix single user sync operation

core/src/main/resources/defaults/clustertemplates/aws/aws-streaming-720.json, core/src/main/resources/defaults/clustertemplates/aws/aws-streaming-small-720.json, core/src/main/resources/defaults/clustertemplates/azure/azure-streaming-720.json, core/src/main/resources/defaults/clustertemplates/azure/azure-streaming-small-720.json, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDatahubConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/schemaregistry/SchemaRegistryServiceConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/schemaregistry/SchemaRegistryServiceConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/smm/StreamsMessagingManagerServiceConfigProviderTest.java, template-manager-cmtemplate/src/test/resources/input/cdp-streaming.bp
This PR contains the remaining requirements for GA 7.2.0 streaming clusters.
- Config provider for Schema Registry Ranger repo
- Custom Knox proxy setting for SCHEMA_REGISTRY:  replayBufferSize=512
- Final blueprints and cluster definitions
Testing:
- Tested manual cluster installation for all combinations (AWS / Azure, Light Duty / Heavy Duty)
- Wrote new unit tests for config providers
Closes:
CB-6996
CB-7153
CB-7208
=> CB-6996 - Streaming GA requirements: Ranger pluging cfg.provider, blueprints, proxy settings

core/src/main/resources/defaults/blueprints/cdp-data-engineering-720.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp
set hive.txn.acid.dir.cache.duration=0 in hive safety valve
until https://issues.apache.org/jira/browse/HIVE-23551 is fixed
Testing done:
I created custom template from 7.2.0 DE & DE HA templates with tuned hive config in mow-dev. And launched clusters couple of times. There were no issues. Noticed changes were applied.
Closes #CDPD-12838
=> CDPD-12838:

autoscale/src/main/java/com/sequenceiq/periscope/monitor/RemovableClusterMonitor.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandler.java, autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterRepository.java, autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java, autoscale/src/main/resources/application.yml, autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandlerTest.java
1. Disable ClusterManagerHostHealthEvaluator.
2. Including autoscaling disabled clusters for removable check.
Closes CB-5738
=> CB-5738 Disable ClusterManagerHostHealthEvaluator

core-api/src/main/resources/definitions/exposed-services.json, core-api/src/test/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollectorTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/OpdbServiceEndpointCollectorTest.java, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
New unit test which demonstrates failure prior to correcting the
visibleForDatalake/visibleForDatahub both being false, and then passing
upon fixing exposed-services.json.
Copied the relevant text from other sections in topology_api.xml.j2,
but I'm not sure if there's some way to validate these changes are
correct prior to getting a deploy in dev.
Should cherry-pick cleanly to rc-2.21, if this change is acceptable. Would like to see this get deployed to validate it once and for all :)
=> CB-7259 Ensure HBASEJARS is listed as an ExposedService

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProviderTest.java
This is a workaround fix for a CM bug which introduces case-sensitivity for ranger_database_type. Tested with unit-tests.
=> CB-6720 Fix a case-sensitivity bug in Ranger configs

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProviderTest.java
This fixes an red error warning in CM about HDFS health and suppresses a  yellow warning error.  This needs to go into 2.20 and 2.21.
=> CB-7306 setting HDFS replication to 1 and suppressing health check.

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsCloudWatchService.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsCloudWatchServiceTest.java
Batch cloudwatch alarm deletions into batches of 100. Before deleting
an alarm, check that it exists. If the deletion fails, then throw an
exception rather than ignoring the error.
This was tested with the unit tests and the skipping of already
deleted alarms was tested with cloudbreak on AWS.
This uses the AWS permissions cloudwatch:DescribeAlarms which was
added to the CDP permissions request in cloudbreak 2.21.0. The initial
cloudwatch alarms permissions cloudwatch:PutMetricAlarm and
cloudwatch:DeleteAlarms were added in cloudbreak 2.20.0.
Closes #CB-734
=> CB-7340: Delete cloudwatch alerts in batches of 100

orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/output.conf.j2
config changes to avoid usage of getObject calls
if object is not checked, we cannot know any number index of the files, that is needed also for multi part uploads
if no index in the filename -> uploaded files are overwritten. solutions for these:
- use a hex random in every buffer (4 digit - that is not unique, but the chance is really low you will generate the same random in the same minute for 2 different file - also it creates the same filename with the right minute timestamp if the log is grows larger than 16MB in the same minute -> there is a `uuid_flush` as well which is unique, but that's a long string, hex random looks better)
- decrease chunk limit from 60MB (default: 256MB) to 16MB in order to - most likely - avoid multi part uploads (so we do not need AbortMultipartUpload …
=> CB-7346. FluentD - get rid of s3 getObject requirement.

README.md
Cloudbreak core and FreeIPA management service build instructions were
missing the cb.image.catalog.url configuration property. This was
added.
The command line instructions were manually tested.
Closes #CB-7375
=> CB-7375: Fix command line build instructions for image catalog error

core/src/main/resources/defaults/blueprints/cdp-opdb-720.bp
Hue talks to HBase via the Thriftserver and can be used to view/modify data.
This change adds Hue to the opdb blueprint and enables thriftserver.
Testing: Created cluster from custom blueprint and verified that Hue turns up.
Tried CRUD operations on a sample table from the Hue UI.
=> CB-7343 [opdb] Add Hue in the opdb blueprint

orchestrator-salt/src/main/resources/salt/pillar/postgresql/disaster_recovery.sls, orchestrator-salt/src/main/resources/salt/pillar/top.sls, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/.pgpass, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/backup.sls, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/init.sls, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/restore.sls, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh
Invoke PostgreSQL backup and restore salt scripts.
* Add Salt States for:
* Copying scripts to master node
* Copying .pgpass for credentials
* Running backup and restore scripts
* Move PostgreSQL scripts to `disaster_recovery` directory.
* Add Pillar value for backup location
Closes CB-7217
=> CB-7217 Add necessary salt stack changes to invoke the database backup restore scripts.

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/KerberosConfigTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RecipeClusterTest.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/HighStateAllRunner.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStates.java, orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java, orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/HighStateAllRunnerTest.java, orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStatesTest.java
This is for branch CB-2.23.0.
When FreeIPA HA installed, the primary FreeIPA instance was updating
certificates and restarting services at the same time as the replicas
were installing. This caused the replica installation to fail.
The salt high state was updated to be able to target specific nodes.
This prevents salt from updating the primary node when the replicas
are being installed.
This was tested using the tests and also it was manually tested a few
times.
Closes #CB-7335
=> CB-7335: Fix intermittent FreeIPA replica installation failure

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncServiceTest.java
User sync changes in CDPCP-808 introduced a potential null pointer
exception when removing all users from a group. FreeIPA will return
null for the Group member_user field. The new check for whether the
group member removal works did not null-check this field.
The UserSyncService is updated to not fail when this field is null.
=> CDPCP-2294. Fix NullPointer in user sync

freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/entity/InstanceGroup.java, freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverterTest.java
I am targeting this for 2.23 so that when FreeIPA basic HA is enabled, the database will contain the information needed in order for the repair to work when full HA is available.
The FreeIPA instance group database table's node count was set to
null. This sets the value for newly provisioned FreeIPA clusters.
This was tested using the unit tests and also by checking the database
table values when provisioning a cluster.
Closes #CB-7391
=> CB-7391: Fix FreeIPA instance group database table's node count

autoscale/src/main/resources/schema/app/20200611115912_DISTX-494_Purge_existing_Periscope_Cluster_Data.sql
Periscope database contains Cluster data where in each cluster creator is stored as a duplicate row in clusterpertain table. This mapping has been fixed to associate all clusters created by single user with a single entry in ClusterPertain.
Existing cluster table data needs to be purged to honour this new mapping.
Closes #DISTX-494
=> DISTX-494-PurgeExistingPeriscopeClusterData

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_replica_install.sh
This does an ipa-server-uninstall to clean up any possible bad server install
components in case of a retry of the replica install.  As well it adds a
--force-join option to the replica install in case the client has already
been installed and registered on the main server.  This effectively makes
the replica install idempotent.
Closes #CB-7405
=> CB-7405: Add a force uninstall and force-join option to FreeIPA replica install

autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/cm/ClouderaManagerClusterCreationEvaluator.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/CloudbreakCommunicator.java, autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java, autoscale/src/main/java/com/sequenceiq/periscope/service/ha/LeaderElectionService.java, autoscale/src/main/java/com/sequenceiq/periscope/service/security/SecurityConfigService.java, autoscale/src/main/java/com/sequenceiq/periscope/service/security/TlsHttpClientConfigurationService.java, autoscale/src/test/java/com/sequenceiq/periscope/controller/AutoscaleClusterCommonServiceTest.java, autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/cm/ClouderaManagerClusterCreationEvaluatorTest.java, autoscale/src/test/java/com/sequenceiq/periscope/service/ha/LeaderElectionServiceTest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/AutoscaleV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/AutoscaleStackV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AutoscaleV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/stack/AutoscaleStackToAutoscaleStackResponseJsonConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackToAutoscaleStackV4ResponseConverter.java
1. Introducing CB-Periscope Cluster Sync on-demand instead of polling all CB Clusters every 30 seconds to avoid unnecessary CB DB Load and  periscope processing already synced clusters.
2. Persicope CM Communication is defaulted to use cluster-proxy which is the recommended mechanism for all Cluster Communication since CM IP would not be reachable in all scenarios.
This was tested on private stack for periscope-cb cluster sync and autoscaling scaleup\scaledown actions.
Closes #CB-6619
=> CB-6619-Optimize-CB-ClusterSync

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceGroup.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceGroupRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceGroupService.java
- on resize, if you have downscaled all the nodes for an instance groups you cannot get back the instance group itself with 0 instance metadata (if ALL terminated)
- removed left join fetch query
- get instance groups by stack and filter in java on the non-terminated instance metadata
- condition (not terminated) should go into the right side of the join -> BUT you cannot include any with/on-clause if you are using fetch
- without using fetch, we end up to using many queries (around 8)
- with the actual (removed) query, we still load stack anyway in the objects, so it contains all instance groups/instance metadata -> in terms of space/load query only the instance group with all metadata should not cause larger heap space
=> CB-6730. List instance groups even if all metadata are terminated.

core/src/main/resources/defaults/blueprints/cdp-data-engineering-720.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-721.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-721.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-720.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-721.bp
[DISTX-493](https://jira.cloudera.com/browse/DISTX-493)
1. Disabled erasure encoding
2. Enabled S3AFileSystem to use openssl for hive & spark
3. Removed hive.server2.tez.sessions.per.default.queue=4 from hive safety valve
Testing done:
- I created custom template from DE, DE Spark3 templates with tuned values in mow-dev. And launched clusters couple of times. There were no issues. Noticed changes were applied.
- For openssl related changes verified via async profiler output that openssl & wildfly related are being used.
Closes #DISTX-493
=> fix for DISTX-493

auth-connector/build.gradle, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java, auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementServiceTest.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/encryption/EncryptedImageCopyService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/encryption/EncryptedSnapshotService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilder.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceCreateThread.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StackRequestManifesterTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/template/InstanceTemplateRequestToTemplateConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProvider.java, freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverterTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/template/InstanceTemplateRequestToTemplateConverterTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProviderTest.java, mock-caas/build.gradle, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java, mock-caas/src/main/resources/application.yml, mock-caas/src/test/java/com/sequenceiq/caas/grpc/service/MockUserManagementServiceTest.java
As per one-pager [design doc](https://docs.google.com/document/d/1OK6COfHosg3EA6IQxuV4o1AczzBLAqk2SNgyafJ-x0w/edit) linked to [CB-4925](https://jira.cloudera.com/browse/CB-4925), this PR unconditionally enables the encryption of EBS volumes for FreeIPA and DL clusters (but note the exception below for the latter). Notes:
* This applies to root (always EBS) as well as EBS data volumes. (There is no way to define encryption settings separately in `cloud-api`; they apply to all the volumes of the whole host group when given.)
* The current logic always uses the region-default EBS encryption key. The handling of customer-provided KMS CMK is out of scope here and will be covered in a follow-up JIRA & PR.
* No change to service APIs; settings are currently hard-wired into the service logic. Any …
=> CB-4925 Enable EBS encryption for FreeIPA and DL

cloud-aws/src/main/resources/definitions/cdp/aws-cdp-log-policy.json
This changes the example logging policy so that the FreeIPA backups can
not be read.  It only allows writing to that location.
Closes #CB-7506
=> CB-7506: Update example logging IAM policy to block FreeIPA backup access

core/src/main/resources/defaults/blueprints/cdp-data-engineering-720.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp
Set hive.optimize.sort.dynamic.partition.threshold=0 as a workaround JIRA [CDPD-13636](https://jira.cloudera.com/browse/CDPD-13636)
For now this needs to be merged for CB 2.20 only.
Testing done:
I created custom template from DE & DE HA templates with tuned values in mow-dev. And launched clusters couple of times. There were no issues. Noticed changes were applied.
=> Workaround for CDPD-13636

core/src/main/resources/defaults/blueprints/cdp-opdb-721.bp
CB-7343 was used to track addition of Hue to 7.2.0 blueprint. This change applies the same addition to 7.2.1 blueprint.
Testing: Created cluster from custom blueprint and verified that Hue turns up.
Tried CRUD operations on a sample table from the Hue UI.
=> CB-7514 [opdb] Add Hue in the opdb blueprint 7.2.1

mock-caas/src/main/resources/application.yml
It's a possible trap for all developers who just want to setup an environment. For most devs encryption is not needed and they won't even know that it's enabled and slowing their work down. Who needs encryption, already knows this feature exists and can set the value to true in their dev env.
=> CB-4925 - Setting auth.mock.freeipadlebsencryption.enable=false by default

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/AutoscaleV4Endpoint.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AutoscaleV4Controller.java
1. Autoscale needs a recommendation endpoint for UI.
2. This API is similar to the one exposed recently for the periscope, so no further testing is done.
=> DISTX-421 Separate endpoint for autoscale recommendation

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/RemoveHostsHandler.java, freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/RemoveHostsHandlerTest.java
When an upscale operation fails before the hostname is collected, the
subsequent repair operation used to fail because the hostnames to
remove from the orchestrater was empty. This was fixed.
A unit test was added and it was tested manually on a local deployment
of cloudbreak.
Closes #CB-7534
=> CB-7534: Fix downscale when deleting host without a hostname

common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java
Update the CRN service name for DEX to match with the thunderhead
service name (defined in Crn.java in the thunderhead repo).
Refer: https://github.infra.cloudera.com/thunderhead/thunderhead/blob/master/services/libs/protocols/src/main/java/com/cloudera/thunderhead/service/common/crn/Crn.java
=> CB-7479: Update the service name for DEX

environment/src/main/java/com/sequenceiq/environment/telemetry/service/AccountTelemetryService.java, environment/src/test/java/com/sequenceiq/environment/telemetry/service/AccountTelemetryServiceTest.java
seems like we should not log freeipa pwd in e2e test clusters (which appears in salt minion log) so adding a default anonymization rule for that
on long term, maybe we should create a static json that contains the default rules that is read at CB startup
=> CB-7556. Anonyimize freeipa pwd by default (Dbus->Kibana)

freeipa/src/main/resources/freeipa-salt/salt/fluent/template/input.conf.j2
In order to better diagnose install issues and track installs
from repairs the FreeIPA install and uninstall logs should
be uploaded to fluent
added logs
/var/log/ipaclient-install.log
/var/log/ipaserver-install.log
/var/log/ipaclient-uninstall.log
/var/log/ipareplica-install.log
/var/log/ipaserver-uninstall.log
Closes #7599
=> CB-7558: Add FreeIPA install and uninstall logs to fluentd.

authorization-common/src/main/java/com/sequenceiq/authorization/service/PermissionCheckService.java
The PermissionCheckerService will double proceed when called with an
internal actor. This is fixed by returning the results of the first
proceed call.
=> Fix permission check for internal actors

freeipa/src/main/resources/application.yml
When FreeIPA HA has 3 out of 4 failed instances, there were several
issues that occurred such as CB-6842, CB-7523, CDPSDX-1793, and
CDPSDX-1869. These issues do not occur when 2 out of 3 nodes have
failed. So the maximum number of instances of FreeIPA is being capped
at 3 nodes.
Closes #CB-7576
=> CB-7576: Reduce the max nodes of FreeIPA to 3

autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/v1/HistoryEndpoint.java, autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/AutoscaleClusterHistoryActivity.java, autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/AutoscaleClusterHistoryResponse.java, autoscale-api/src/main/java/com/sequenceiq/periscope/doc/ApiDescription.java, autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java, autoscale/src/main/java/com/sequenceiq/periscope/controller/DistroXAutoScaleClusterV1Controller.java, autoscale/src/main/java/com/sequenceiq/periscope/controller/EndpointConfig.java, autoscale/src/main/java/com/sequenceiq/periscope/controller/HistoryController.java, autoscale/src/main/java/com/sequenceiq/periscope/converter/HistoryConverter.java, autoscale/src/main/java/com/sequenceiq/periscope/domain/History.java, autoscale/src/main/java/com/sequenceiq/periscope/domain/LoadAlertConfiguration.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/cm/ClouderaManagerClusterCreationEvaluator.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java, autoscale/src/main/java/com/sequenceiq/periscope/repository/HistoryRepository.java, autoscale/src/main/java/com/sequenceiq/periscope/service/HistoryService.java, autoscale/src/test/java/com/sequenceiq/periscope/controller/HistoryControllerTest.java, autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/cm/ClouderaManagerClusterCreationEvaluatorTest.java
1. Enable Autoscaling History Endpoint to retrieve Autoscaling Events
2. Capture history events for autoscaling.
3. Downscaling should not validate node count since downscaling to 0 nodes for a hostgroup is supported.
Closes #DISTX-478
Closes #DISTX-413
Closed #DISTX-501
=> DISTX-478-Enable Autoscaling History

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/InstanceTemplate.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/instance/AwsInstanceTemplate.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsInstanceView.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/encryption/EncryptedImageCopyServiceTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsInstanceViewTest.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/GcpDiskEncryptionService.java, cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/AwsInstanceTemplateV4Parameters.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/GcpInstanceTemplateV4Parameters.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/InstanceTemplateV4RequestToTemplateConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/template/InstanceTemplateRequestToTemplateConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProvider.java, freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/template/InstanceTemplateRequestToTemplateConverterTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProviderTest.java
* Extract AWS magic strings as constants in the new class `AwsInstanceTemplate` in `cloud-api`
* The similar magic strings used for Azure & GCP encryption scenarios have not been touched. The only exceptions are the strings `"type"` and `"key"` that are common to AWS & GCP (and might be used later for Azure as well for customer-managed encryption keys); these have been added as constants to the superclass `InstanceTemplate`.
* Replace raw strings (`"NONE"`, `"DEFAULT"`, `"CUSTOM"`) with `EncryptionType` enum constant names
=> CB-7365 Extract magic string literals in AwsInstanceView

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup
This modifies the FreeIPA backup script to be write-only
by taking out the file length check that does a read
of the file in order to verify the upload.
Closes #CB-7601
=> CB-7601: Modify the FreeIPA backup script to work write only.

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/UserSyncState.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/EnvironmentUserSyncStateCalculator.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/EnvironmentUserSyncStateCalculatorTest.java
The environment sync state is calculated from the last started
user sync operation. This commit adds a SYNC_FAILED state and
updates the state calculations to explicitly call out when the
sync failed instead of just marking the environment STALE.
=> CDPCP-2435. Add user sync failed state

core/src/main/resources/defaults/blueprints/cdp-data-engineering-720.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-721.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-721.bp
1. CDPD-12283 added s3a and adls as a supported filesystem for CDPD oozie in **7.2.0**.
2. Still, it does not work because only the namenode of the cluster is whitelisted by default in oozie.
3. Oozie team thinks that it is bad to whitelist everything.
4. CDP-PC datahub clusters need to work with any s3a or adls filesystem.
5. So removing the whitelisting by overriding it with an empty value.
6. Tested this in a cluster. I was getting the below error which went away after the safety valve setting.
```
{"errorMessage":"E0307: Runtime error [Could not check whether file [s3a://gk1priv-cdp-bucket/oozie/hive/workflow.xml] exists on HDFS. Error message: E0901: NameNode [gk1priv-cdp-bucket] not allowed, not in Oozie's whitelist. Allowed values are: …
```
=> DISTX-451 Oozie: Add s3a and adls to the supported filesystems

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup
This modifies the FreeIPA backup script to check if the backup location 
host is valid. This is for azure only because the storage location 
is a customer provided hostname based on the storage account being used.
Closes #8365
=> CB-7608: Modify FreeIPA backup to check if azure backup location host resolves

orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/output.conf.j2
- added write_only option for azure plugin
- use upload timestamp instead of index in the filename (format: 'HHSSmmff')
- set buffer chunk size to 4MB (as you need to upload in multiple parts per abfs blocks, the block size is 4MB, and as during upload knowing the position is required we cannot continue the uploading if for some reason the app is stopped and we cannot gather the blob properties through a head operation)
edit: also add an update to s3 path to use hms_slice instead of hex random
edit2: it's possible freeipa backup will need read anyway, if that's the case, maybe this fix is not a must
=> CB-7626. Update Azure storage plugin version for VM nodes (support write only mode)

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/action/FreeIpaDownscaleActions.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/repair/changeprimarygw/action/ChangePrimaryGatewayActions.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/upscale/action/FreeIpaUpscaleActions.java
The chained FreeIPA repair flow was fixed so that if one of the flows
fails, subsequent chained flows do not run.
This was tested manually on a local deployment of cloudbreak by
injecting failures in each of the chained flows for FreeIPA repair and
ensuring that subsequent flows are not executed.
Closes #CB-7667
=> CB-7667: Fix failed FreeIPA repair flows to not run chained flows

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazConfigProviderTest.java
Bunch of raz fixes went into 7.2.1, so raz should only be enabled past that.
=> CB-7641 changing minimum CM version for Raz to 7.2.1

freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthDetailsService.java
If an instance of FreeIPA does not have an assigned FQDN, then the
reboot and repair operation which are not forced can throw a null
pointer exception.
Closes #CB-7673
=> CB-7673: Fix NPE when rebooting or repairing FreeIPA without FQDN

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java, auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementServiceTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/RepairInstancesService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/RepairInstancesServiceTest.java, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/auth/MockUserManagementService.java, mock-caas/src/main/resources/application.yml
Check the CDP_FREEIPA_HA_REPAIR entitlement when repairing FreeIPA HA.
This was tested manually with a local deployment of cloudbreak.
Closes #CB-7707
=> CB-7707: Add CDP_FREEIPA_HA_REPAIR entitlement check

core/src/main/resources/defaults/blueprints/cdp-opdb-720.bp
Addition of hue to opdb template depends upon CM 7.2.1 version hence removing this change from the 7.2.0 blueprint. 
This reverts commit 1ef188066b2427e61c12cdf1d566bf18ca851d7e.
Testing: Created cluster from custom blueprint and verified that dh cluster turns up.
=> CB-7704 [opdb] Revert "CB-7343 [opdb] Add Hue in the opdb blueprint"

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup
This fixes the FreeIPA backup script for some quoting issues via
over-zealous shellcheck compliance.  As well this  sets the AWS
upload check to better handle failing return codes.
Closes #8435
=> CB-7727: Fix FreeIPA backup script for quoting issues and ret code

audit-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/audit/AuditGrpc.java, audit-connector/src/generated/main/java/com/cloudera/thunderhead/service/audit/AuditProto.java, audit-connector/src/main/java/com/sequenceiq/cloudbreak/audit/AuditClient.java, audit-connector/src/main/proto/audit.proto
I removed the unused codes from the audit client. I think we should not maintenance unused codes.
=> CB-7617 Refresh audit.proto from thunderhead repo

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java, auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementServiceTest.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/instance/AwsInstanceTemplate.java, cloud-aws/build.gradle, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/encryption/EncryptedImageCopyService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilder.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsGroupView.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsInstanceView.java, cloud-aws/src/main/resources/templates/aws-cf-dbstack.ftl, cloud-aws/src/main/resources/templates/aws-cf-stack-freeipa.ftl, cloud-aws/src/main/resources/templates/aws-cf-stack.ftl, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderDBTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/encryption/EncryptedImageCopyServiceTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilderTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsInstanceViewTest.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/instancegroup/template/InstanceTemplateV4RequestToTemplateConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/InstanceTemplateV4RequestToTemplateConverterTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/template/InstanceTemplateRequestToTemplateConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProvider.java, freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/template/InstanceTemplateRequestToTemplateConverterTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProviderTest.java, mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/auth/MockUserManagementService.java, mock-caas/src/main/resources/application.yml, mock-caas/src/test/java/com/sequenceiq/caas/grpc/service/auth/MockUserManagementServiceTest.java
This PR adds the ability to provision clusters with encrypted EBS in a fast way, avoiding unnecessary resource creations. Notes:
* Applies to FreeIPA & DL (#7833) as well as DH clusters.
* Affects root (always EBS) as well as EBS data / attached volumes.
* No change to service APIs; the flag controlling the fast logic is included as a new dynamic parameter in `InstanceTemplate`. The parameter key has been added to `AwsInstanceTemplate` introduced earlier in #8340.
* The fast logic is guarded by the new entitlement `CDP_CB_FAST_EBS_ENCRYPTION`. This entitlement gets checked by both FreeIPA and Cloudbreak / Core Svc; the absence of the entitlement grant will result in the legacy behavior.
* When testing with local CB, `mock-caas` defaults to presenting `CDP_FREEIPA_DL_EBS_ENCRYPTION` …
=> CB-7360 Speed up handling of encrypted EBS

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java
1. The built-in DE HA template uses the manager host group for hosting CM.
2. Usually, workflow for folks to create HA template is to copy from the built-in.
3. Since the recommendation of 1 host, plus the name of the host group to be manager or services does not match the default template, the CM gets automatically placed in the compute host group whose default size is 0.
4. To prevent users from shooting themselves in the foot, adding manager as a recommended host group.
=> DISTX-428 Add a recommendation for manager host group to be one of the right places for hosting CM service.

orchestrator-salt/src/main/resources/salt-common/salt/fluent/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls, orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/check_fluent_plugins.sh.j2
in case of old images with newer CB, for limited network, it should be possible to use proxy for gem/curl based installs
=> CB-7758. Add proxy support to fluentd plugin installations.

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/clouderamanager-ssl-user-facing.conf
The changes are to nginx component. 
With this change unauthenticated favicon.ico requests (automatic requests by browser) to UIs will be denied (with 403 response). Favicon requests will only be allowed when the UI is authenticated i.e. hadoop-jwt cookie is present. This only affects requests going in via Knox and does not affect CM requests. 
**Why is this change needed**
More details can be found in [CB-7246](jira.cloudera.com/browse/CB-7246). In a nutshell this is what is happening (in Chrome browser):
1. Request is made to a UI page (Atlas, CM, Ranger etc.) from CP.
2. In case where there is no authentication KnoxSSO flow is triggered.
3. Before the previous KnoxSSO flow is completed Chrome requests favicon.ico at the root of the server (this is the nginx host).
4. This favicon.ico …
=> CB-7246 - Prevent favicon.ico requests for unauthenticated UIs

cloud-api/build.gradle, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Group.java, cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/model/GroupTest.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSetup.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/encryption/EncryptedImageCopyService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/encryption/EncryptedSnapshotService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilder.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilder.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilderTest.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpDiskResourceBuilder.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackFlavorVerifier.java, cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java, cloud-yarn/src/test/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnectorTest.java
* Add a new convenience method `getReferenceInstanceTemplate()` to `Group` (`cloud-api`) returning `getReferenceInstanceConfiguration().getTemplate()`.
* Replace all occurrences of the expression `getReferenceInstanceConfiguration().getTemplate()` in various classes with invocations of `getReferenceInstanceTemplate()`.
* Eliminate some superfluous local variables in said classes as part of the refactoring.
=> CB-7792 Introduce Group.getReferenceInstanceTemplate()

freeipa/src/main/java/com/sequenceiq/freeipa/util/ClusterProxyServiceAvailabilityChecker.java, freeipa/src/test/java/com/sequenceiq/freeipa/util/ClusterProxyServiceAvailabilityCheckerTest.java
If the appversion is not filled out in the database, then a null
pointer exception will happen when
ClusterProxyServiceAvailabilityChecker is used.
Unit tests were added.
Closes #CB-7830
=> CB-7830: Fix NullPointerException when appversion is not present

core/src/main/resources/defaults/blueprints/cdp-data-engineering-721.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-721.bp, core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-721.bp, core/src/main/resources/defaults/blueprints/cdp-flink-ha-721.bp, integration-test/src/main/resources/blueprint/clouderamanager.bp, template-manager-cmtemplate/src/test/resources/input/de-ha.bp
YARN UI2 fetches logs from MR HistoryServer LogsServlet which runs as mapred
user. Currently, mapred user accesses the RM and NM to get job details and job
logs details respectively. This requires mapred user to have access on viewing
all the jobs.
=> COMPX-3063. Add mapred user as YARN admin

core/src/main/resources/defaults/clustertemplates/azure/azure-flink-light-ha-721.json, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java
Adds a default Azure template based on the one for [AWS](https://github.com/hortonworks/cloudbreak/blob/master/core/src/main/resources/defaults/clustertemplates/aws/aws-flink-light-ha-721.json)
=> CB-7816 Add default Azure template for Flink

environment/src/main/java/com/sequenceiq/environment/proxy/v1/controller/ProxyController.java
Somehow annotations (responsible to make account id usage possible with internal actor) were accidentally removed
=> CB-7861 Proxy config internal call fix

core/src/main/resources/defaults/blueprints/cdp-sdx-721.bp
Manually tested the changed by spinning up a datalake with Runtime 7.2.1 and made sure that the "solr_https_port" is set to 8985 and also made sure that Solr HTTP service is reachable.
=> CB-7831: Connections to Solr are failing with a 500 on 7.2.1 clusters

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/operation/model/OperationType.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/RebootInstanceEvent.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/RebootOperationAcceptor.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/action/AbstractRebootAction.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/action/RebootActions.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/RepairInstancesService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/RepairInstancesServiceTest.java
The reboot API in FreeIPA Management Service was updated to return an
operation ID instead of void. This makes the reboot API consistent
with the repair API and it allows the client to know when the reboot
operation is complete.
This tested by with unit tests and manually checking the return
value in a local deployment of cloudbreak.
NOTE: This does not wait for the reboot flow to ensure the nodes have come back online, which will be handled by a separate pull request.
Closes #CB-7860
=> CB-7860: Return operation ID with FreeIPA reboot

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/spot/SpotRetryUtil.java, integration-test/src/main/resources/application.yml, integration-test/src/test/java/com/sequenceiq/it/cloudbreak/util/spot/SpotRetryUtilTest.java
This change is already on master, but we need it for 2.25 too
=> CB-7803 Disable retry of failed test cases on spot instances

autoscale/src/main/resources/schema/app/20200708120655_DISTX-494_Purge_Old_Cluster_Data.sql
1. Persicope old cluster data was not initialized with newly added columns like stacktype, cloudplatform..
2. Purging old data so that periscope auto-syncs new cluster data.
=> DISTX-494-Purge Old Periscope Cluster Data

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java, core/src/main/resources/application.yml, orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/kerberos/KerberosDetailService.java, template-manager-recipe/src/test/java/com/sequenceiq/cloudbreak/recipe/moduletest/CentralRecipeContext.java
During upgrade/repair it's possible that unbound would return the old IP as the TTL in FreeIPA by default is 1200 sec (unbound honors this value)
Unfortunately FreeIPA doesn't support setting default TTL for DNS zones. See:
https://www.redhat.com/archives/freeipa-users/2013-October/msg00122.html
This leaves us with 2 option:
- add DNS record with TTL (this is the current implementation)
- create a plugin which enables LDAP level editing for DNS zones
After some investigation we are going with 30 sec as:
- it is a very short period, won't cause any disruption
- 0 is an invalid value for TTL
- many DNS servers don't honor values under 30, which could cause they would fall back to their default value
=> CB-7715 Set cluster DNS entries TTL to 30 sec

README.md
Changes:
* Follow-up to #8489.
* Replace `auth-mock` with `thunderhead-mock` in `CB_LOCAL_DEV_LIST` description and related comments, to bring it in sync with https://github.com/hortonworks/cloudbreak-deployer/pull/677 .
* Similarly, replace `Auth Mock` with `Thunderhead Mock`.
* Correct capitalization of `THUNDERHEAD API` to `Thunderhead API` as per internal docs.
Note: The config keys of `mock-thunderhead` still begin with the prefix `auth.`, so `auth.config.dir` is left untouched.
=> CB-7612 Fix thunderhead-mock name in CB_LOCAL_DEV_LIST

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ClusterV4RequestToClusterConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/BootstrapMachineHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/HostMetadataSetupHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/TlsSecurityService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java, core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusIntegrationTest.java
Sometimes in edge cases syncer put an instancemetadata from TERMINATED to some other status which is wrong. Example scenario:
1) stop master instance
2) call repair on master node
3) syncer try to call CM, but it is down and connection times out for several times
4) in the meantime repair was started, downscale was successful
5) after some retry to CM syncer starts to check if VMs are available or not
6) VM is down because dowscale was successful -> syncer puts master node to DELETED_IN_PROVIDER_SIDE
master instance status is TERMINATED at this point, but it will be  DELETED_IN_PROVIDER_SIDE which is wrong. It results there will be 2 primary gateway.
Solution: syncer should not update instance status from TERMINATED state
=> CB-7745 syncer shouldn't overwrite TERMINATED status

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/Clue.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/Investigable.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/AuditUtil.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ErrorLogMessageProvider.java
Test failure reports will now contain if there were spot terminations, and also the relevant api responses to ease the troubleshooting.
=> CB-7804 Extend test failure report with spot info

autoscale/src/main/resources/schema/app/20200709061507_DISTX-516_Optimize_Periscope_DB_Columns.sql
1. Purge legacy periscope data and enforce null constraints.
2. Introduce not null checks for fields which are mandatory for DH autoscaling to work.
3. Introduce indexes for frequently used field.
=> DISTX-516-Optimize Periscope DB Columns.

auth-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/usermanagement/UserManagementGrpc.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java, auth-connector/src/main/proto/usermanagement.proto, auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementServiceTest.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SetRangerCloudIdentityMappingRequest.java, datalake/build.gradle, datalake/src/main/java/com/sequenceiq/datalake/cm/ClouderaManagerProxiedClientFactory.java, datalake/src/main/java/com/sequenceiq/datalake/cm/ClouderaManagerRangerUtil.java, datalake/src/main/java/com/sequenceiq/datalake/cm/RangerCloudIdentityService.java, datalake/src/main/java/com/sequenceiq/datalake/controller/exception/RangerCloudIdentitySyncException.java, datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/main/resources/application.yml, datalake/src/test/java/com/sequenceiq/datalake/cm/ClouderaManagerRangerUtilTest.java, datalake/src/test/java/com/sequenceiq/datalake/cm/RangerCloudIdentityServiceTest.java, freeipa/build.gradle, freeipa/src/main/java/com/sequenceiq/freeipa/configuration/SdxApiConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/configuration/ServiceEndpointConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/CloudIdentitySyncService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UmsUsersState.java, freeipa/src/main/resources/application.yml, mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java, mock-thunderhead/src/main/resources/application.yml
Azure cloud identity information (Azure OID mapping) are now synced from
UMS into all appropriate datalake instances. At high level the
implementation is:
- SDX service has a new endpoint that allows setting azure ranger
configs (azure user and group mappings). The SDX service will make the
necessary CM api call (through cluster proxy) to set the config and
trigger a role refresh.
- The FMS user sync service will pull the Azure Object IDs (cloud
identity mapping) from UMS and call the new SDX endpoint to set the
configs.
Follow on work items include:
- Poll the status of the refresh after triggering it
- Individual user level and group level sync of OIDs
- Moving some of the CM logic into cluster-cm and client-cm
=> CDPCP-1941. Sync Azure OID Mappings as part of user sync

orchestrator-salt/src/main/resources/salt/salt/metering/init.sls, orchestrator-salt/src/main/resources/salt/salt/metering/template/metering-heartbeat-application.service.j2
metering application is burned on both datahub and datalake image, by default it tries to restart itself, but on datalake cluster we are not configuring that in the right way (generate_heartbeats.ini) and we do not even need metering application there yet. 
(only needed for DataHub)
solution:
- rewrite service descriptor on datalake cluster -> it wont restart the service and won't be started at startup (after salt highstate)
=> CDPCP-2566. Do not try to start metering application on DataLake cluster (every 5 sec)
