cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePremiumValidatorService.java

CB-2004 Fix premium storage support for Standard_E64is_v3 virtual machines

---

cloud-common/src/main/resources/application.yml

Also append CM build number to the version displayed in CB UI.

CB-2047. Update CM and CDH versions

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java
common/src/main/java/com/sequenceiq/cloudbreak/util/NullUtil.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/BlueprintV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/dto/BlueprintAccessDto.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/responses/BlueprintV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Blueprint.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/blueprint/BlueprintToBlueprintV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/BlueprintLoaderService.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/BlueprintRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ExistingResourceByCrnOrNameRestUrlParser.java
core/src/main/resources/schema/app/20190623082338_CB-1859_set_crn_to_blueprint.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/blueprint/BlueprintToBlueprintV4ResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/blueprint/BlueprintV4RequestToBlueprintConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTestSuiteInitializer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/blueprint/BlueprintCreateAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/blueprint/BlueprintDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/blueprint/BlueprintGetAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/AuditTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/BlueprintTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CleanupService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v4/BlueprintV4Action.java

CB-1898 set crn for blueprint

---

core/src/main/resources/schema/app/20190619095712_CB-1859_set_crn_to_image_catalog.sql

CB-1898 fix update sql for imagecatalog crn

CB-1898 fix update sql for imagecatalog crn

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/ExposedService.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ClusterToClusterV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ServiceEndpointCollector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/ComponentLocatorService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/ServiceEndpointCollectorTest.java
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_ui.xml.j2
template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/AmbariBlueprintTextProcessor.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/atlas/AtlasKnoxRoleConfigProvider.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/processor/BlueprintTextProcessor.java

The PR contains the following:
- exposed services are shown in UI
- SOLR service is introduced
- Atlas Knox related config corrected

CB-1982 - Exposedservices are not shown in UI

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java

CB-2049 Turn off default rollback onfailure strategy

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiEndpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiUserCrnEndpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/KerberosMgmtV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/doc/KeytabModelDescription.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/doc/KeytabModelNotes.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/doc/KeytabOperationsDescription.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/HostRequest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/ServiceKeytabRequest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/ServiceKeytabResponse.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/ServicePrincipalRequest.java
freeipa-api/src/main/java/com/sequenceiq/service/api/doc/ModelDescriptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/configuration/EndpointConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java

I manually tested the API's by sending requests from the client to make sure that the corresponding API is invoked.
There was another pull request that I created for this change from my forked repo
https://github.com/hortonworks/cloudbreak/pull/5410.
I have addressed the comments on that pull request.

CDPSDX-511: keytab and service principal internal control plane APIs.

---

integration-test/src/main/resources/application.yml

@sodre90 please review and merge if it is Ok for you!
This is the fix for Jenkins builds.

CB-1585 Fix Test Application.yml for SDX testing

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/UserV1Endpoint.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java

The previous DISTX-142 commit changed the sync endpoint to syncAll. This commit changes the status endpoint to match

DISTX-142. Fix syncAll status endpoint to match syncAll endpoint

---

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/AttachedFreeIpaRequest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentRequest.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentApiConverter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java

CB-2124 unable to create env without freeipa from cli

CB-2124 unable to create env without freeipa from cli

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/recipes/RecipeV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/recipes/dto/RecipeAccessDto.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/recipes/responses/RecipeV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Recipe.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/RecipesV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/recipes/RecipeToRecipeV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/RecipeRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/recipe/RecipeService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ExistingResourceByCrnOrNameRestUrlParser.java
core/src/main/resources/schema/app/20190617130945_CB-1859_set_crn_to_recipe.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/recipes/RecipeBaseToRecipeV4ConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/recipe/RecipeServiceTest.java
core/src/test/resources/com/sequenceiq/cloudbreak/converter/v4/recipes/recipe.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/recipe/RecipeCreateAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/recipe/RecipeDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/recipe/RecipeGetAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/recipe/RecipeTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/AuditTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CleanupService.java

CB-1896 set crn for recipe

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxCloudStorageRequest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterRequest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/ProvisionerService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/ProvisionerServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

- Cloudstorage now accepted as optional parameter on SDX API

CB-1867 CloudStorage request on SDX api

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtTelemetryService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtTelemetryServiceTest.java

Update telemetry altus url (custom) to use global CM config instead of telemetry role configuration
Updated UTs for it as well

Use custom altus url for TP as global CM config

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/user/model/UmsState.java
mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java

This is a workaround until we figure out how to map users to roles.

CB-877 give admin privilege to all users for now

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SetPasswordRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java
freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java

Added environment parameter for set password api
@handavid @keyki

Cdpcp 387 envparam

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/ExposedService.java
datalake/src/main/resources/sdx/cluster-template.json
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_ui.xml.j2

This PR contains the following:
- SDX launches with Knox by default
- CM UI is open by default

CB-1924 - SDX should configure knox as CM proxy for every service through knox

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/ModifyGrainBase.java
orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls
orchestrator-salt/src/main/resources/salt/salt/sssd/ycloud/dns_hack.sh

- delete all DNS entries once on join (ycloud only)
- call sync_all on salt if grains modification retry is needed

CB-1779 cleanup DNS for ycloud

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java
orchestrator-salt/src/main/resources/salt/pillar/fluent/init.sls
orchestrator-salt/src/main/resources/salt/salt/fluent/init.sls
orchestrator-salt/src/main/resources/salt/salt/fluent/settings.sls

- Install CLDR specific azurestorage plugin from CLDR rubygem repository
- specify plugin version in a constant
- pass platform variable directly to fluent. (do not gather from discovery)

DISTX-40. Install CLDR fluent azurestorage plugin for Azure cluster

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/KerberosMgmtV1Endpoint.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/model/Keytab.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/exception/KeytabCreationException.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java
freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtV1ServiceTest.java

Changes include below
1. Implementing API's to add host, service and get the keytab. It also implements API's to fetch existing keytab.
2. Define Apis in FreeIpaClient.
I have tested this change in the local development environment and also added unit tests cases to verify them.

CDPSDX-580: Implement service APi's to get the keytab.

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilder.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsGroupView.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
cloud-common/src/main/java/com/sequenceiq/cloudbreak/util/DeviceNameGenerator.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java

@daszabo or @horadla23 pls review

CB-2076 ephemeral disk attachment fix on aws

---

cloud-common/src/main/resources/application.yml

Knox with CM is still bad, but the rest of the things seems working

CB-2253 Update CM and CDP to the latest good build

---

core-api/src/main/java/com/sequenceiq/cloudbreak/validation/CrnValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidCrn.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/repository/SdxClusterRepository.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/resources/schema/mybatis/20190705141821_add_idx_crn.sql
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

some units test might be needed

CB-1863 findBy EnvCrn and findBy sdxCrn

---

environment/src/main/java/com/sequenceiq/environment/credential/service/ResourceDefinitionService.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/CredentialToCredentialV1ResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/credential/validation/CredentialValidator.java
environment/src/main/java/com/sequenceiq/environment/credential/validation/definition/CredentialDefinitionService.java
environment/src/main/java/com/sequenceiq/environment/util/ResourceDefinitionRequestFactory.java
environment/src/test/java/com/sequenceiq/environment/credential/service/CredentialServiceTest.java
environment/src/test/java/com/sequenceiq/environment/credential/service/ResourceDefinitionServiceTest.java
environment/src/test/java/com/sequenceiq/environment/credential/validation/CredentialValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/credential/validation/definition/CredentialDefinitionServiceTest.java

Create unit tests for Credential related services/validators

CB-1914 Create unit tests for Credential related services/validators

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java

CB-985 check single node cm server recovery support only if it is necessary

---

environment/src/test/java/com/sequenceiq/environment/credential/service/CredentialServiceTest.java

Create additional unit tests for Credential related services validators
Closes CB-1914

CB-1914 Create unit tests for Credential related services validators

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonCloudProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/resources/application.yml

- internal and normal clustershape was the same

CB-1988 fix broken e2e due to cluster shape

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/impala/ImpalaLdapConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/impala/ImpalaRoles.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/impala/ImpalaLdapConfigProviderTest.java

CB-1006 Add temporary LDAP support for Impala using CM (rc-2.10)

---

environment/build.gradle
environment/src/main/java/com/sequenceiq/environment/environment/domain/Environment.java
environment/src/main/java/com/sequenceiq/environment/environment/domain/EnvironmentView.java
environment/src/main/java/com/sequenceiq/environment/environment/domain/RegionSetTypeReference.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentResourceService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentModificationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentResourceDeletionServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentResourceServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentTestData.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentViewServiceTest.java

Create unit tests for Environment related services/validators
Closes CB-1915

CB-1915 Create unit tests for Environment related services/validators

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/task/AwsInstanceTerminatedStatusCheckerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecomissionService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecommisionerTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterKerberosService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/PreTerminationStateExecutor.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterKerberosServiceTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

cm recover

---

orchestrator-salt/src/main/resources/salt/salt/fluent/init.sls
orchestrator-salt/src/main/resources/salt/salt/fluent/settings.sls

- update fluentd databus plugin version (install only if not installed already on the node)

DISTX-271. Update fluent dbus plugin version to 1.0.2 for CB images.

---

orchestrator-salt/src/main/resources/salt/salt/fluent/template/td-agent.conf.j2

add knox gateway logs for td-agent config

Logging: monitor KNOX service logs (gateway)

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/kerberos/KeytabConfigurationHandler.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/ServiceKeytabResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java
freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtV1ServiceTest.java

There is no functional change in this patch. I fixed a typo. I have not added any tests for this change.

CDPSDX-660: Fix the typo in ServiceKeytabResponse.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentNetworkTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/yarn/YarnSdxTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/smoke/YarnSmokeTest.java
integration-test/src/main/resources/testsuites/e2e/yarn-sdx-tests.yaml

@sodre90 or @lnardai please review then merge if it is Ok for you.

CB-2165 SDX E2E test for YARN

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/KerberosMgmtV1Endpoint.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/RPCMessage.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/RPCResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java

Added API's to delete host and service.

CDPSDX-581: Implement service API's to delete service principal and host

---

cloud-azure/src/main/resources/templates/arm-dbstack.ftl

This is the single server deployment of postgres (is HA).
Template for server group is still to be checked if needed, but will come later. 
I provide some readings for the template I created:
arm template for postgres:
https://docs.microsoft.com/en-us/azure/templates/microsoft.dbforpostgresql/2017-12-01/servers
service endpoints: vnet to postgres connection without adding the postgres a public ip:
https://docs.microsoft.com/en-us/azure/postgresql/howto-manage-vnet-using-portal

CB-2567 arm template for db stack creation

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/smoke/YarnSmokeTest.java

@sodre90 or @lnardai please review

CB-2635 Upgrade YARN smoke test based on latest changes

---

core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreCloudStorageServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProviderTest.java

Enable S3Guard and configure S3Guard authoritative mode for HMS warehouse directory

CB-2589: Enable S3Guard

---

core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/network/AwsNetworkV1Parameters.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/network/AzureNetworkV1Parameters.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4Converter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/SdxConverter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4ConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/SdxConverterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java

CB-2709 network inheritance is different in distrox

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/hdfs/hdfs-dir-create-fix.settings.j2
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls

Has been verified with the following builds:
* CM: 1294992
* CDH: 1287733

CB-2668 Add SCM workaround settings for OPSAPS-51681

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/CloudConnector.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/IdentityService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsIdentityService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/util/Arn.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/util/ArnTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AwsIdentityMappingService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AwsMockIdentityMappingService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/base/IdBrokerMappingSource.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentEditRequest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentRequest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/DetailedEnvironmentResponse.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentBaseResponse.java
environment/src/main/java/com/sequenceiq/environment/environment/domain/Environment.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentCreationDto.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDto.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentEditDto.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentApiConverter.java
environment/src/main/resources/schema/app/20190719094401_CB-2455_idbroker_mapping.sql
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java

CB-2455 Add mock IDBroker mapping for AWS

---

cloud-common/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/cdp-sdx.bp

CB-2402 Bump repo versions and revert "CB-2402 Temporary disable IDBroker because of start issues"

---

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/UtilV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UtilV4Controller.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/flow/create/SdxCreateActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/SdxDeleteActions.java
environment/src/main/java/com/sequenceiq/environment/credential/reactor/handler/InteractiveCredentialCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/credential/reactor/handler/InteractiveCredentialCreationStatusHandler.java
environment/src/main/java/com/sequenceiq/environment/credential/service/AbstractCredentialService.java
environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialDeleteService.java
environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialService.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/CredentialV1Controller.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/EnvCreationActions.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/network/NetworkCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/EnvDeleteActions.java
environment/src/main/java/com/sequenceiq/environment/proxy/v1/controller/ProxyController.java
environment/src/main/java/com/sequenceiq/environment/user/UserPreferencesRepository.java
environment/src/main/resources/application.yml
notification-sender/src/main/java/com/sequenceiq/notification/HttpNotificationSenderService.java
notification-sender/src/main/java/com/sequenceiq/notification/NotificationAssemblingService.java
notification-sender/src/main/java/com/sequenceiq/notification/NotificationController.java
notification-sender/src/main/java/com/sequenceiq/notification/NotificationService.java

notification fix pack

---

autoscale/src/main/java/com/sequenceiq/periscope/config/SecurityConfig.java
autoscale/src/main/resources/application.yml

- tested with some API's seems to be working
- need to refactor the API to work based on CRN's and check the CRN of the user

CB-2342 changing Security Config for Periscope.

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceGroupV1ToInstanceGroupV4Converter.java
core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-700.json
core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-ha-700.json
core/src/main/resources/defaults/clustertemplates/aws/aws-datamart-700.json
core/src/main/resources/defaults/clustertemplates/aws/aws-datamart-ha-700.json
core/src/main/resources/defaults/clustertemplates/aws/aws-datascience-700.json
core/src/main/resources/schema/app/20190729182226_CB-2764_distrox_ui_hangs.sql
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceGroupV1ToInstanceGroupV4ConverterTest.java

CB-2764 DistroX UI is frozen on Mow

CB-2764 DistroX UI is frozen on Mow

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4Converter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4ConverterTest.java

CB-2793 NPE when distrox json does not contains a network

CB-2793 NPE when distrox json does not contains a network

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/KerberosMgmtV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/doc/KeytabModelNotes.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/doc/KeytabOperationsDescription.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/HostRequest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/ServiceKeytabRequest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/model/VaultCleanupRequest.java
freeipa-api/src/main/java/com/sequenceiq/service/api/doc/ModelDescriptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/exception/DeleteException.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/SecretEngine.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/service/SecretService.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/vault/VaultKvV1Engine.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/vault/VaultKvV2Engine.java

Made sue that changes are working in the local development environment. The missing piece in this patch is the cleanup cluster delete. It all depends on cluster CRN. Cluster CRN should be passed by the consumers of the API. It is an optional parameter for now.

CDPSDX-623: Cleanup keytab data put in the vault.

---

environment/src/main/java/com/sequenceiq/environment/parameters/service/ParametersService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentModificationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/service/ParametersServiceTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/v1/converter/AwsEnvironmentParametersConverterTest.java

CB-1447 add test cases

---

common-model/src/main/java/com/sequenceiq/common/api/cloudstorage/AccountMappingBase.java
common-model/src/main/java/com/sequenceiq/common/api/cloudstorage/CloudStorageBase.java
common-model/src/main/java/com/sequenceiq/common/api/cloudstorage/doc/CloudStorageModelDescription.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/cloudstorage/AccountMapping.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/cloudstorage/CloudStorage.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/CloudStorageConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AwsMockAccountMappingService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackV4RequestToTemplatePreparationObjectConverterTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxIdBrokerConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxIdBrokerConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/AccountMappingView.java

Has been verified using local CB (core & datalake apps) and custom CB CLI.

CB-2715 Add ID Broker mappings params to API

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureDatabaseServerView.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureDatabaseServerViewTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/handler/RegisterDatabaseServerHandler.java

Azure database termination has now been implemented.
Note: Successfully deleted Azure databases.

CB-1678. Terminate Azure databases.

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/altus/AltusIAMService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java
orchestrator-salt/src/main/resources/salt/salt/metering/init.sls

few issues:
- always the same machine user was created
- only RSA access key is generated
small addition:
use uuid from clustern crn for generating logging folder

DISTX-294. Databus credential & metering fixes

---

template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/FileSystemConfigurationProvider.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/FileSystemConfigurationsViewProvider.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/s3/S3FileSystemConfigurationsView.java
template-manager-recipe/src/test/resources/module-test/inputs/MultiCloudStorageInsertion.recipe
template-manager-recipe/src/test/resources/module-test/inputs/SingleCloudStorageInsertion.recipe
template-manager-recipe/src/test/resources/module-test/outputs/MultiAbfsCloudStorageInsertion.recipe
template-manager-recipe/src/test/resources/module-test/outputs/MultiAdlsCloudStorageInsertion.recipe
template-manager-recipe/src/test/resources/module-test/outputs/MultiGcsCloudStorageInsertion.recipe
template-manager-recipe/src/test/resources/module-test/outputs/MultiS3CloudStorageInsertion.recipe
template-manager-recipe/src/test/resources/module-test/outputs/MultiWasbCloudStorageInsertion.recipe
template-manager-recipe/src/test/resources/module-test/outputs/SingleAbfsCloudStorageInsertion.recipe
template-manager-recipe/src/test/resources/module-test/outputs/SingleAdlsCloudStorageInsertion.recipe
template-manager-recipe/src/test/resources/module-test/outputs/SingleGcsCloudStorageInsertion.recipe
template-manager-recipe/src/test/resources/module-test/outputs/SingleS3CloudStorageInsertion.recipe
template-manager-recipe/src/test/resources/module-test/outputs/SingleWasbCloudStorageInsertion.recipe

Also fixing another issue in the same class: identity is no longer set in `BaseFileSystemConfigurationsView`

CB-2884 - Fixed NPE in FileSystemConfigurationsViewProvider

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/openstack/OpenStackCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxCloudStorageTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsSdxCloudStorageTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazons3/AmazonS3Util.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazons3/action/S3ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazons3/client/S3Client.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/e2e/aws-sdx-cloudstorage-tests.yaml

@lnardai or @sodre90 please review

CB-2166 SDX E2E add Cloudstorage options to SdxClusterTest

---

redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/DatabaseV4Endpoint.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/base/DatabaseV4Base.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/base/DatabaseV4Identifiers.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/database/request/CreateDatabaseV4Request.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/DatabaseServerV4Endpoint.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/base/DatabaseServerV4Base.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/AllocateDatabaseServerV4Request.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/DatabaseServerTestV4Request.java
redbeams/src/main/java/com/sequenceiq/redbeams/controller/mapper/CrnParseExceptionMapper.java

This commit adds in the ValidCrn annotation to all CRN instances in
redbeams.
Note: This has now been verified -- I was missing the @Validated annotation -- and CRNs are validated as expected.

CB-2452. Validate redbeams CRNs.

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java

(∩｀-´)⊃━☆ﾟ.*･｡ﾟ cli needs this

CB-2809 forgot sdx name based endpoint for repair

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/InternalCrnBuilder.java
datalake/build.gradle
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/main/resources/application.yml
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StackRequestManifesterTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/base/IdBrokerMappingSource.java
idbmms-connector/src/main/java/com/sequenceiq/cloudbreak/idbmms/GrpcIdbmmsClient.java

Relies on the client established in #5608.

CB-2863 Wire IDBMMS into Datalake Svc

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerHostStatusChecker.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/SetupCmScalingMock.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/model/ClouderaManagerMock.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClouderaManagerUpscaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RecipeClusterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtilForMultipleStatuses.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/generate_agent_tokens.sh
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/setup-autotls.sh

@keyki or @lacikaaa or @daszabo pls review

CB-2808 Single node recovery with Auto-TLS

---

core/src/main/resources/defaults/blueprints/cdp-sdx-ha.bp
core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/cdp-sdx.bp

Reverts hortonworks/cloudbreak#5886
Does not work with our default CM version. @jasonwmcswain

Revert "CDPD-2339, CDPSDX-716, CDPSDX-715 - updated configs with warnings sup…"

---

orchestrator-salt/src/main/resources/salt/salt/metering/init.sls

Update metrics package: from this point if it will be installed, it won't depends on different pip packages.
technically that code should be only run if cb image does not contain metering package + metering is enabled.
tested against on metering disabled/enabled clusters
right now it will be used by altus team for testing by updating salt configs manually

Use binary package for metering instead of installing pip packages with rpm

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ConfigUtils.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/impala/ImpalaVolumeConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkRoles.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/zeppelin/ZeppelinS3CloudStorageRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/spark/SparkOnYarnRoleConfigProviderTest.java

Initialize spark client configs with cloud storage base paths.
Closes #CB-2890

CB-2890 : Initialize spark client configs with cloud storage

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/openstack/OpenStackCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentNetworkTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/resources/application.yml

@lnardai or @sodre90 please review then merge if it is OK for you!
This is the API part of E2E test updates for [CB-2781](https://jira.cloudera.com/browse/CB-2781) and the fix for caused [CB-2997](https://jira.cloudera.com/browse/CB-2997) issue.
FYI: @keyki

CB-2997 Introduce set of subnet IDs for E2E Environment Create

---

idbmms-connector/src/generated/main/java/com/cloudera/thunderhead/service/idbrokermappingmanagement/IdBrokerMappingManagementProto.java
idbmms-connector/src/main/proto/idbrokermappingmanagement.proto

Updates the IDBroker Mapping Management Service ProtoBuf definition & associated generated Java SDK. Follow-up to #CB-2718.

CB-2718 Update IDBMMS ProtoBuf Java SDK

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UmsState.java

@handavid  - internal PR for adding machine user to grp map.

Cdpcp 496 env usersync refactoring on rc2.12 apurohit

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StackRequestManifesterTest.java

CB-2863 Clarify log messages around IDBroker account mapping population

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java

if you try to install datahub cluster from the UI, if you click on Cluster definitions, it won't install tp, (but if you go with custom with exactly the same blueprint, it will install),it was not the case for cli, only happens can happen if stack template call does not have any telemetry component (so for older DBs on the UI ...but actually it's valid, that older templates does not have component for telemetry), so change the converter to lookup telemetry options in the following order:
- check stack template has telemetry data, use that if if has
- if it has not, and you have env crn, check environment for it
- if environment has no WA telemetry configured, use the defaults from telemetry converter

DISTX-304. Telemetry Publisher not always configured with Data Hub cluster (UI setup)

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java

one of the PRs (CB-3001) was not rebased before merging a code changed (without having any conflict), that causes an error
sdx cluster response needs to be passed to the converter, so including that

CB-3001. Fix broken converter because of not rebased branch

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java

- we'll skip checkRight for internalCrn's as advised by the UMS team
- tested with remote UMS configured

CB-2409 allow everything for internal services

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/DatabaseService.java

- redbeams response changed
- statusReason contains redbeams related error

CB-3073 redbeams response changed. 

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/blueprint/BlueprintV4RequestToBlueprintConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/blueprint/BlueprintV4RequestToBlueprintConverterTest.java
template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/CentralBlueprintParameterQueryService.java
template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/CentralBlueprintUpdater.java
template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/kerberos/KerberosBlueprintService.java
template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/utils/StackInfoService.java
template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/CentralBlueprintUpdaterTest.java
template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/utils/StackInfoServiceTest.java

related to:
https://github.com/hortonworks/cb-cli/pull/616

CB-2874 - changing blueprint to cluster template in error messages

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java
common/src/test/java/com/sequenceiq/cloudbreak/auth/altus/CrnTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/recipe/RecipeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/template/ClusterTemplateService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/recipe/RecipeServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackServiceTest.java

Changed CRN for Blueprint, Image Catalog, Recipe, Cluster resources. @horadla23 @doktoric please review.

CB-3038 CRNs for Recipe, Blueprint, Image Catalog, Cluster definition should use official names

---

orchestrator-salt/src/main/resources/salt/salt/post-recipes/scripts/createuserhome.sh

OPSAPS-52161. Kinit only as needed, and also fixes mkdirs to happen in one go

---

common/src/main/java/com/sequenceiq/cloudbreak/common/database/DatabaseCommon.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/cluster/ClusterV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/ServiceEndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbServerConfigurer.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbServerConfigurerTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/model/ClouderaManagerMock.java

- some typos
- usage of database common

CB-2148 small refactors advised by bill

---

environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentRequest.java
environment-api/src/test/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentRequestNameLengthValidationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ResourcePropertyProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java

I open this as a Draft because only tomorrow could be merged into rc-2.12.

CB-3064 limit the max length of the environment's name to 28 chars

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProvider.java

Awaiting further input on parameters

CB-2878 - Hive Needs to be in HTTP Mode for Knox to Proxy J/ODBC Access

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/AbstractAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/ContextKeys.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow2Handler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/FlowAdapter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/FlowFinalizeAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/FlowChainHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/FlowChains.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/generator/OfflineStateGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/AbstractStackDownscaleAction.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/Flow2HandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/config/AbstractFlowConfigurationTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

CB-3016 The same instances will be deleted on the provider side as from Ambari

---

common-model/src/main/java/com/sequenceiq/common/model/CloudStorageCdpService.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseRoles.java
template-manager-cmtemplate/src/main/resources/definitions/cm-cloud-storage-location-specification.json
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/cloudstorage/CmCloudStorageConfigDetailsTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProviderTest.java

Configure cloud storage location for hbase root directory on DataHub clusters.
Closes #DISTX-303

DISTX-303 Datahub Cluster configure Hbase Cloud Storage

---

cloud-common/src/main/resources/application.yml

updating
waiting for local to build with Default image.

CB-3102 updated version of CM and CDH for default images

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/hdfs/hdfs-dir-create-fix.settings.j2
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls

CB-2982 Restore workaround for OPSAPS-49716

---

cloud-common/src/main/resources/application.yml

again
WAIT for AWS image creation at least

CB-3102 new round of (updated version of CM and CDH for default images)

---

orchestrator-salt/src/main/resources/salt/salt/sssd/template/sssd-ipa.j2

moving memcache_timeout to nss as that is the right place where this config should be

CB-3104: move memcache_timeout to nss

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

- First I'll add the safety test, then in another PR I'll try to fix the UI and the API

CB-3135 enable/recreate cluster template list test

---

datalake/src/main/java/com/sequenceiq/datalake/configuration/AppConfig.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/DatabaseConfig.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/DatabaseService.java
datalake/src/main/resources/sdx/aws/database-custom-template.json
datalake/src/main/resources/sdx/aws/database-light-duty-template.json
datalake/src/main/resources/sdx/aws/database-medium-duty-ha-template.json
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/DatabaseServiceTest.java

Extracted database setup configs into templates. @horadla23 please review.

CB-3103 Configure external database of SDX based on cluster shape with template

---

orchestrator-salt/src/main/resources/salt/salt/post-recipes/scripts/createuserhome.sh

This fixes the createuserhome.sh script (which is invoked once a minute
by cron) so that it no longer uses the default krb5 ticket cache
location. Instead it uses a cloudbreak-specific one. That means that it
won't interfere with any end user who might be trying to kinit on that
same node. This should fix some of our test cases which were doing that
same thing.
Along the way I noted that the existing 'chown' path was quite slow --
it took about 17 minutes to perform the chowns for 623 users (each one
takes about 2 seconds, sometimes slower). In contrast, using curl to
invoke webhdfs takes about 10ms per operation. The full sync for 623
users took 10 seconds.

OPSAPS-52161. Avoid overwriting root krb5 ccache, speed up chown

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java
common/src/test/java/com/sequenceiq/cloudbreak/auth/altus/CrnTest.java

CB-3202 fix machineUser getUserId for qaas

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java

- make retry around the whole create machine user operation - with that we will generate a new request id for the call
- add retry annotation for generate keys as well (as create machine user is called through that)
- double the retries

CB-3023. Improve create machine user retry logic

---

orchestrator-salt/src/main/resources/salt/salt/fluent/template/input.conf.j2

update knox gateway log location (idbroker log location changed before, it happened with gateway as well)

Update knox gateway log location

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/resources/sdx/aws/cluster-light-duty-template.json
datalake/src/main/resources/sdx/aws/cluster-medium-duty-ha-template.json
datalake/src/main/resources/sdx/azure/cluster-light-duty-template.json
datalake/src/main/resources/sdx/azure/cluster-medium-duty-ha-template.json
datalake/src/main/resources/sdx/mock/cluster-light-duty-template.json

Moved security group config from template to code. @horadla23 please review.

CB-2328 remove securityGroups from sdx template jsons, add ports programmatically by "type" (GATEWAY,CORE)

---

README.md
cloud-common/src/main/resources/application.yml
freeipa/src/main/resources/application.yml
secret-engine/README.md
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/conf/VaultConfig.java

- add localhost as default value to vault.addr
- add running freeipa from IDEA to README.md

CB-3206 Doc improvement and add default value to vault.addr proeprty

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering.bp
core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-700.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/HostGroupType.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClouderaManagerDownscaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClouderaManagerUpscaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/KerberizedStackCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RecipeClusterTest.java

CDPD-3348 Increase DE Blueprint workers cardinality

CB-3200 Increase DE Blueprint Worker Node Count to 3

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLicenseService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtSetupService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLicenseServiceTest.java
integration-test/docker-compose_template.yml
mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java
mock-caas/src/test/java/com/sequenceiq/caas/grpc/service/MockUserManagementServiceTest.java
mock-caas/src/test/resources/etc/license.txt

- Throw exception if license file is not present during mock startup
- Add dummy license for integration test and remove CM begin trial logic
@akanto please review.

CB-3238 Mandatory CM license

---

mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java

Required for IDBMMS (see https://github.com/hortonworks/cloudbreak-deployer/pull/605) to work correctly, since it verifies the validity of the returned role response.
IDBMMS gRPC log before this fix:
```
c.c.t.s.common.grpc.GrpcInterceptors: usermanagement.UserManagement/GetRights: response: roleAssignment { role { crn: \"PowerUser\" } } groupCrn: \"crn:cdp:iam:us-west-1:default:group:d5509d61-8ba3-4bff-80a2-d70b1435ad51\"
```
or pretty-printed:
```
roleAssignment {
role {
crn: \"PowerUser\"
}
}
groupCrn: \"crn:cdp:iam:us-west-1:default:group:d5509d61-8ba3-4bff-80a2-d70b1435ad51\"
```
The output changes as follows after the fix:
```
c.c.t.s.common.grpc.GrpcInterceptors: usermanagement.UserManagement/GetRights: response: roleAssignment { role { crn: …
```

CB-2717 Fix mock-UMS GetRights: valid CRN and policy

---

orchestrator-salt/src/main/resources/salt/salt/metering/init.sls

- remove systemd config file check.
- remove old package manually (because of possible conflicts)

Update metering package - use long term location

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/ContextKeys.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/generator/OfflineStateGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/AbstractStackDownscaleAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationActions.java
flow/src/main/java/com/sequenceiq/flow/core/AbstractAction.java
flow/src/main/java/com/sequenceiq/flow/core/Flow.java
flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java
flow/src/main/java/com/sequenceiq/flow/core/FlowAdapter.java
flow/src/main/java/com/sequenceiq/flow/core/FlowConstants.java
flow/src/main/java/com/sequenceiq/flow/core/FlowFinalizeAction.java
flow/src/main/java/com/sequenceiq/flow/core/chain/FlowChainHandler.java
flow/src/main/java/com/sequenceiq/flow/core/chain/FlowChains.java
flow/src/test/java/com/sequenceiq/flow/core/AbstractActionTest.java
flow/src/test/java/com/sequenceiq/flow/core/Flow2HandlerTest.java
flow/src/test/java/com/sequenceiq/flow/core/config/AbstractFlowConfigurationTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

CB-3016 context passing between flowchain's flows

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackV4RequestValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderService.java
core/src/main/java/com/sequenceiq/cloudbreak/ldap/LdapConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/ldap/LdapSSOConfigurationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/RecipeEngine.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/SharedServiceValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackV4RequestToTemplatePreparationObjectConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/SharedServiceValidatorTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/dns/DnsV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/dns/doc/DnsOperationDescriptions.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaOperationDescriptions.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/ldap/LdapConfigV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/ldap/doc/LdapConfigOpDescription.java
freeipa/src/main/java/com/sequenceiq/freeipa/ldap/LdapConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/ldap/LdapConfigRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/ldap/LdapConfigService.java
freeipa/src/main/java/com/sequenceiq/freeipa/ldap/v1/LdapConfigV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/ldap/v1/LdapConfigV1Service.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/FreeIpaRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/config/LdapConfigRegisterService.java
freeipa/src/main/resources/schema/app/20190826111559_CB-2488_add_clustername_to_ldapconfig.sql
freeipa/src/test/java/com/sequenceiq/freeipa/ldap/LdapConfigServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/config/LdapConfigRegisterServiceTest.java

includes some API description/documentation fix

CB-2488 Create service account for LDAP bind integration

---

README.md

Describe additional services added in https://github.com/hortonworks/cloudbreak-deployer/pull/605 that can be included in `CB_LOCAL_DEV_LIST`.

CB-2717 README update for cbd IDBMMS and Environments2 API Svc

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToTemplatePreparationObjectConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackV4RequestToTemplatePreparationObjectConverterTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/PlacementView.java

As getBucketLocation call from AWS SDK returns "US" for region us-east-1
we must supply this property explicitly.

CB-3264 Add S3guard Dynamo Table region property

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/objectstorage/ObjectStorageMetadataResponse.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsObjectStorageConnector.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsObjectStorageConnectorTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageLocationValidator.java
datalake/src/test/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageLocationValidatorTest.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/cloudstorage/CloudStorageLocationValidator.java

See comments in AwsObjectStorageConnector class

CB-3287 Shadow Access Denied response on AWS getBucketLocation call

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/start.sls

Hide username and password from cm's db setup.
@akanto @sodre90 please review.

CB-3235 DB init failure logs RDS user/password

---

autoscale/src/main/java/com/sequenceiq/periscope/domain/Cluster.java

CB-3325 - Increase default cluster max size
Please review @lacikaaa a @pdarvasi

CB-3325 Increase default cluster max size

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java

Simple change related to enabling user sync while env launch.
Closes CDPCP-591
@keyki @lacikaaa @handavid

CDPCP-591 re-enable user sync while env launch

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperation.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/stack/StackTestAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/stack/StackSyncAction.java

Created two endpoints in datalake to support sync by name and crn.
@sodre90, @lnardai please review.

CB-3284 Manual sync endpoint on SDX API

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/database/base/DatabaseType.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/externaldatabase/SupportedDatabaseProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/SchemaRegistryServerRdsConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/StreamsMessagingManagerRdsConfigProvider.java
template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/GeneralClusterConfigsProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/schemaregistry/SchemaRegistryRdsRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/schemaregistry/SchemaRegistryRoles.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/smm/StreamsMessagingManagerRoles.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/smm/StreamsMessagingManagerServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/schemaregistry/SchemaRegistryRdsRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/smm/StreamsMessagingManagerServiceConfigProviderTest.java
template-manager-cmtemplate/src/test/resources/input/cdp-streaming.bp
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/model/GeneralClusterConfigs.java

Configure Providers for Schema Registry Server and Streams Messaging Manager.
1. Configure RDS Providers for Schema Registry Server and SMM.
2. Configure Local CM Admin and Password for SMM
Closes #CB-2681
Closes #CB-2682

CB-2681-CB-2682 Configure Providers for Schema Registry and SMM

---

integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupClientUtil.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupUtil.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupWaitUtil.java
integration-test/src/main/resources/application.yml

Please review and let me know where can I improve or refactor this if it is needed.

CB-3077 GUI E2E teardown solution for Jenkins builds

---

integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupUtil.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupWaitUtil.java

@afarsang please review, based on our discussion and brainstorming session on this...

 CB-3077 Some improvements for stabilizing Cleanup Wait Util

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/DetailedStackStatus.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java

Set stack state to UPDATE_IN_PROGRESS when repair starts.

CB-3361 Set initial repair state initiated when triggering repair

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserServiceConstants.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersStateDifference.java

changes related to users, groups, group memberships update and deletion.
Closes CDPCP-674
@handavid @lacikaaa @keyki
Related to https://github.com/hortonworks/cloudbreak/pull/6175

CDPCP-679 - user and groups delete and update

---

integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupWaitUtil.java

CB-3077 Fixes Cleanup Wait Util

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/EnvironmentView.java

Default Policy Groups Name for ranger initialized to cdp_<environment>
Closes #CB-3438

CB-3438-Initialize default policy group name for ranger

---

core-api/src/main/java/com/sequenceiq/cloudbreak/validation/externaldatabase/SupportedDatabaseProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/DasRdsConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/das/DasConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/das/DasRoles.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/das/DasConfigProviderTest.java

Add DAS service config to configure RDS instance for DAS.
Closes CDPD-3641

CDPD-3641 - Configure RDS instance for DAS.

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/StackScaleRequestV2ToUpdateClusterRequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/AmbariClusterUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/recipe/StackPreTerminationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/recipe/UploadRecipesHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/HostGroupRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/HostMetadataRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/AmbariClusterSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/AmbariDecommissioner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/hostgroup/HostGroupService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterHostServiceTypeTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariDecommissionerTest.java
integration-test/README.MD
integration-test/src/main/java/com/sequenceiq/it/spark/salt/SaltApiRunPostResponse.java

CB-3330 Remove expensive 'join fetch' clauses from host group related queries

---

cluster-dns-connector/src/main/java/com/sequenceiq/cloudbreak/certificate/service/CertificateCreationService.java
cluster-dns-connector/src/main/java/com/sequenceiq/cloudbreak/certificate/service/DnsManagementService.java
cluster-dns-connector/src/test/java/com/sequenceiq/cloudbreak/component/DnsManagementServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/repair/master/ha/ChangePrimaryGatewayService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/util/StackUtil.java

I have rebased this branch, please @topolyai5 confirm that this could be merged into rc-2.13

The user manager IP should be changed from IP to FQDN in DistroX response

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtRoleComponent.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtUtil.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtVaultComponent.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/VaultPathBuilder.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java
freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtRoleComponentV1Test.java
freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtUtilV1Test.java
freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtV1ServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtVaultComponentV1Test.java
freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/VaultPathBuilderV1Test.java

The kerberos management service was refactored to support better
testing. Unit tests were added and the existing unit tests were fixed.
Closes #CB-3420

CB-3420 Add kerberos management unit tests and refactor for tests

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/SdxDeleteActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/event/RdsDeletionWaitRequest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/event/SdxDeleteStartEvent.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/event/StackDeletionSuccessEvent.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/event/StackDeletionWaitRequest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/handler/RdsDeletionHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/handler/StackDeletionHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/DatabaseService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/ProvisionerService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/flow/create/handler/StackDeletionHandlerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/ProvisionerServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxDeleteInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupUtil.java

Datalake from now sends an optional _forced_ parameter from cloudbreak.

CB-3434 SDX should have a force delete options

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberos/v1/KerberosConfigV1Service.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPermissionService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java

CB-3511 extend kerbbind user's privileges with the right permissions on existing envs

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/projection/StackInstanceCount.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/stack/StackApiViewToStackViewResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackApiViewRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackApiViewService.java

Quick and safe performance upgrade for stack listing.

CB-3330 Small stack list performance fix

---

core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/StackCreatorServiceRecipeValidationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/StackCreatorServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RecipeClusterTest.java

CB-3482 validation for recipe exist

CB-3482 validation for recipe exist

---

integration-test/application.yml

CB-3372 Update CM and CDH versions in end to end tests

CB-3372 Update CM and CDH versions in end to end tests

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandler.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandlerTest.java

Delete failed nodes before deleting cluster.

CB-3584 Delete failed nodes before deleting cluster

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProviderTest.java

Initialize Ranger Default Policy Groups for CM Version >= 7.0.1
Closes #CB-3438

CB-3438  Initialize Ranger Default Policy Groups

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/StackCreatorServiceRecipeValidationTest.java

CB-3612 npe fix for recipe exist

CB-3612 npe fix for recipe exist validation

---

cloud-aws/src/main/resources/templates/aws-cf-network.ftl
cloud-aws/src/test/resources/json/aws-cf-network-private-subnet.json
cloud-aws/src/test/resources/json/aws-cf-network.json
cloud-aws/src/test/resources/templates/aws-cf-stack-1.16.1.ftl
cloud-aws/src/test/resources/templates/aws-cf-stack-1.16.4.ftl
cloud-aws/src/test/resources/templates/aws-cf-stack-1.16.5.ftl

CB-3423 fix description for cf

CB-3423 fix description for cf

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClouderaManagerDownscaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RecipeClusterTest.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/ParcelGeneratorUtil.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/ParcelMockActivatorUtil.java

CB-3589 – fix integration test

CB-3589 – fix integration test

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxDescribeInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxRefreshAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxRepairAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxSyncAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/InstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxRepairTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/BasicSdxTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsSdxCloudStorageTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsSdxTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazonec2/AmazonEC2Util.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazonec2/action/EC2ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazonec2/client/EC2Client.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazons3/action/S3ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazons3/client/S3Client.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtil.java

@afarsang and @sodre90 please review.

CB-3481 Upgrade AWS SDX E2E tests based on latest SDX API changes

---

cloud-common/src/main/resources/application.yml

new cm and cdh build

---

integration-test/application.yml
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterCreationTest.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/e2e/aws-distrox-tests.yaml

Tests fail because test framework sent mock network parameter
Closes 3626

CB-3626 Tests fail because test framework sent mock network parameter

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java

CB-3647 detach instances in groups with max size of 20

---

core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/CBAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/AmbariBlueprintTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/BlueprintTestBase.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/CmTemplateBlueprintTest.java
template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/AmbariBlueprintTextProcessor.java
template-manager-blueprint/src/test/java/com/sequenceiq/cloudbreak/blueprint/template/AmbariBlueprintTextProcessorTest.java
template-manager-blueprint/src/test/resources/blueprints-jackson/test-bp-non-unique-host-group-name.bp
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java
template-manager-cmtemplate/src/test/resources/input/cdp-invalid-multi-host-template-name.bp
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/processor/BlueprintTextProcessor.java

CB-3617 validation for unique host template name

CB-3617 validation for unique host template name

---

orchestrator-salt/src/main/resources/salt/salt/metering/template/generate_heartbeats.ini.j2

(this will improve metering db performance)

CB-3741. Increase metering event heartbeat interval to 5 min (from 1 min).

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClientRetryer.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/AmbariConfigurationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/AmbariDecommissioner.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariDecommissionerTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/TerminationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/MockScalingTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/ScalingMock.java

Ambari decomissioner retry

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/mock/DefaultModel.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/mock/model/AmbariMock.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/testcase/TerminationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/MockScalingTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/v2/mock/ScalingMock.java
integration-test/src/main/java/com/sequenceiq/it/spark/MockSparkServer.java
integration-test/src/main/java/com/sequenceiq/it/spark/ambari/AmbariClusterHostDeleteRequestsResponse.java
integration-test/src/main/java/com/sequenceiq/it/spark/ambari/AmbariClustersHostsResponse.java
integration-test/src/main/java/com/sequenceiq/it/spark/ambari/AmbariClustersHostsResponseW.java
integration-test/src/main/java/com/sequenceiq/it/spark/ambari/v2/AmbariCategorizedHostComponentStateResponse.java

CB-3662 Integration test fixes for downscale tests

---

cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockInstanceConnector.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXScaleAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXStartAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXStopAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/DistroXTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/DefaultModel.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockModel.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/model/ClouderaManagerMock.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/model/SPIMock.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterStopStartTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXStartStopTestParameters.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/FreeIpaStartStopTest.java
integration-test/src/main/resources/testsuites/v2/mock/onebigcluster.yaml
integration-test/src/main/resources/testsuites/v4/mock/distroxmethod.yaml
integration-test/src/main/resources/testsuites/v4/mock/distroxstopstart.yaml
integration-test/src/main/resources/testsuites/v4/mock/freeipa.yaml

Cover masssive scaling and stop start with mock 
currently added with low numbers
Closes 3664

CB-3664 Cover masssive scaling and stop start with mock

---

autoscale/src/main/java/com/sequenceiq/periscope/domain/FailedNode.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/AmbariAgentHealthEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/CloudbreakCommunicator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandler.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/FailedNodeRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java
autoscale/src/main/resources/schema/app/20190910083831_CB-3291_periscope_should_restore_instance_state_automatically.sql
autoscale/src/test/java/com/sequenceiq/periscope/modul/rejected/AmbariAgentHealthMonitorModulTest.java
autoscale/src/test/java/com/sequenceiq/periscope/modul/rejected/RejectedThreadContext.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/AmbariAgentHealthEvaluatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandlerTest.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/ModelTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/autoscale/AutoscaleEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ChangedNodesReport.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/Notes.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/AutoscaleController.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/resources/messages/messages.properties

Periscope detects new healthy and new failed nodes.

CB-3725 Port back 'Periscope should restore the instance state automatically' to 2.9

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/DefaultModel.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterStopStartTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXStartStopTestParameters.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtil.java
integration-test/src/main/resources/testsuites/v4/mock/distroxstopstart.yaml

improving test's await with flow check
Closes CB-3816
Closes CB-3664

CB-3816 improving test's await with flow check

---

core/src/main/resources/defaults/clustertemplates/aws/aws-op-datamart-710.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

This PR adds a cluster definition for the Operations Data Mart blueprint. The definition should most certainly be considered a work in progress as it hasn't received any performance testing at all.

Cluster definition for operations data mart

---

integration-test/it-application.yml
integration-test/scripts/build-cb.sh
integration-test/scripts/check-results.sh
integration-test/scripts/create-cloudbreak-context.sh
integration-test/scripts/create-image.sh
integration-test/scripts/docker-build.sh
integration-test/scripts/docker-compose.sh
integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java

run mock tests parallel
Closes cb-3767

CB-3767 run mock tests parallel

---

integration-test/it-application.yml
integration-test/scripts/build-cb.sh
integration-test/scripts/check-results.sh
integration-test/scripts/create-cloudbreak-context.sh
integration-test/scripts/create-image.sh
integration-test/scripts/docker-build.sh
integration-test/scripts/docker-compose.sh
integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java

Reverts hortonworks/cloudbreak#6412

Revert "CB-3767 run mock tests parallel"

---

template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/GeneralClusterConfigsProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/smm/StreamsMessagingManagerServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/smm/StreamsMessagingManagerServiceConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/model/GeneralClusterConfigs.java

Porting https://github.com/hortonworks/cloudbreak/pull/6414 to rc-2.14 so that it should be deployed to Mow Dev.
Testing: run build + unit tests, it completed without errors.

CB-2682 Initialize SMM with CM FQDN

---

template-manager-blueprint/src/main/java/com/sequenceiq/cloudbreak/blueprint/GeneralClusterConfigsProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/model/GeneralClusterConfigs.java

Configure Hue knox_proxyhosts with external domain if available

---

gradle.properties

CB-3869 improve pull request builds
Closes CB-3869

build cache for gradle

---

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/StructuredFlowEventFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/ClusterToClusterDetailsConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/StructuredFlowEventFactoryTest.java

- was not able to reproduce the issue, fix is based on stacktrace and unit tests

CB-3713 structured event can't be created if freeipa is terminated

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/smm/StreamsMessagingManagerServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/smm/StreamsMessagingManagerServiceConfigProviderTest.java

Initialize SMM Instance Discovery FQDN.
Closes #CB-2682

CB-2682-Initialize SMM Discovery FQDN

---

cluster-proxy/build.gradle
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterProxyException.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterProxyRegistrationClient.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterProxyRegistrationServiceConfig.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterServiceConfig.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterServiceCredential.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ConfigDeleteRequest.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ConfigRegistrationRequest.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ConfigRegistrationResponse.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ConfigUpdateRequest.java
core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/ClusterProxyRegistrationHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterProxyRegistrationClientTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyServiceTest.java
freeipa/src/main/resources/application.yml
settings.gradle

These two commits pull cluster-proxy client code out from the core module so that it can be re-used by the freeipa module.

CDPSDX-515 (part 1)

---

core/src/main/java/com/sequenceiq/cloudbreak/service/ServiceEndpointCollector.java

We cannot really determine if the cert is valid or not that Let's Encrypt generates, because it's env dependent which endpoint is used for the Let's Encrypt service. So this will remove the trust store from the URL even if we get an invalid cert.

CB-3759 do not show truststore in Hive URL with Let's Encrypt cert

---

core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/DistroXV1Request.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/cluster/DistroXClusterV1Request.java
core/src/main/java/com/sequenceiq/cloudbreak/service/template/ClusterTemplateService.java
core/src/main/resources/schema/app/20191015092316_CB-3962_–_create_validation_for_missing_blueprint_on_cluster_definition_create.sql
core/src/test/java/com/sequenceiq/cloudbreak/service/template/ClusterTemplateServiceCreationValidationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/clustertemplate/DistroXTemplateTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

CB-3962 – extend cluster definition cleanup for missing blueprint

CB-3962 – extend cluster definition cleanup for missing blueprint

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/ExposedService.java
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2

Adding DAS service to knox proxy config.
Closes #CB-3986

CB-3986 - Add DAS to knox proxy config.

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/MetricAlertRequest.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/MetricAlertResponse.java
autoscale-api/src/main/java/com/sequenceiq/periscope/doc/ApiDescription.java
autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java
autoscale/src/main/java/com/sequenceiq/periscope/converter/MetricAlertRequestConverter.java
autoscale/src/main/java/com/sequenceiq/periscope/converter/MetricAlertResponseConverter.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/MetricAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/init/AutoscaleStartupService.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/AmbariAgentHealthEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/CronTimeEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/EvaluatorExecutor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/MetricEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/executor/EvaluatorExecutorRegistry.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/MetricAlertRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/TimeAlertRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/AlertService.java
autoscale/src/main/resources/schema/app/20190918113956_CB-3586_indicies_and_unique_constraints_for_alert_entities.sql
autoscale/src/main/resources/schema/app/20191010103826_CB-3586_new_column_in_metricalert_table:_definition_label.sql
autoscale/src/test/java/com/sequenceiq/periscope/modul/rejected/AmbariAgentHealthMonitorModulTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/AmbariAgentHealthEvaluatorTest.java
gradle.properties

CB-3586 Autoscale optimization refactor

---

template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.0.2.json

Add DAS service to list of discoverable services in 7.0.2 release.
Closes CB-3979

CB-3979 - Add DAS service to list of discoverable services in 7.0.2 release.

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java

User sync lists all users and machineUsers then gets the rights for
each. It's possible for a user or machineUser to be deleted between
listing and getting rights, which results in an exception from the
get rights request. This commit catches and logs these errors and
treats NOT_FOUND users as if they have no rights to the environment.

CDPCP-906. Handle users deleted during user sync

---

core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-710.json
core/src/main/resources/defaults/clustertemplates/azure/azure-datamart-710.json
core/src/main/resources/defaults/clustertemplates/azure/azure-opdb-710.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

CB-3988 – create default cluster definition(s) for azure

CB-3988 – create default cluster definition(s) for azure

---

common/src/main/resources/messages/messages.properties
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/resources/messages/messages.properties
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java

CB-3942 Start sync when primary gateway detected as unhealthy

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/knoxsso.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/knoxsso.xml.j2

Cherry pick of PR #6503 to the rc-2.14 branch

CB-4039 KnoxSSO - JWT Tokens Are Valid for Extremely Long Duration

---

environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java

CB-3542 Use virtual groups for DataLake and DataHub admin groups

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaLdapConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaLdapConfigProviderTest.java

This reverts commit dcce9b3f73c4712a1e7ae3ae5605d8b516a25a45.

[DO NOT MERGE YET] Revert "CB-3981 Revert"

---

core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/cluster/DistroXClusterV1Request.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXClusterToClusterConverter.java

CB-4075 – remove notnull annotation for username and password in DistroXClusterV1Request

CB-4075 – remove notnull annotation for username and password in DistroXClusterV1Request

---

freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtUtil.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Service.java

@lacikaaa or @keyki pls review

CB-4086 fix freeipa errorcode handling

---

core/src/main/resources/defaults/clustertemplates/azure/azure-op-datamart-702.json

CB-4066 Create 1.2 cluster templates for Azure

CB-4066 Create 1.2 cluster templates for Azure

---

mock-caas/build.gradle
mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java
mock-caas/src/main/resources/mock-responses/ums/get-workload-credentials.json
mock-caas/src/test/java/com/sequenceiq/caas/grpc/service/MockUserManagementServiceTest.java

Added code in mock service to generate hash password. 
FYI: This is not tested with FreeIPA. 
@keyki @lacikaaa 
Closes: CDPCP-951

CDPCP-951 added hashed password for Password123

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveLLAPServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveLLAPServiceConfigProviderTest.java

CB-4087 Initialize Cloud Storage Locations for Hive LLAP Proto Base Dir 
Closes #6542

CB-4087 Initialize Cloud Storage Locations for Hive LLAP Proto Base Dir

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/ExposedService.java
core/src/main/resources/defaults/blueprints/cdp-data-engineering-702.bp
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProvider.java

Reverts hortonworks/cloudbreak#6548

Revert "Cdpd 3643"

---

cloud-aws/src/main/resources/definitions/aws-credential.json
environment-api/src/main/java/com/sequenceiq/environment/api/doc/credential/CredentialModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/credential/model/parameters/aws/RoleBasedParameters.java

Reverts hortonworks/cloudbreak#6530

Revert "CB-2321 Cannot determine the ARN associated with a role credential"

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

Increase the connection/read timeout from 20s to 5m for Hive

CB-4160 Knox - Increase connection and read timeout values for Hive

---

cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterServiceConfig.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/Tunnel.java
config/checkstyle/checkstyle-suppressions.xml
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ClusterProxyService.java

When CCM is enabled we now register FreeIPA server with the necessary
tunnelling configs to cluster proxy.

CDPSDX-1080. Register FreeIPA servers to cluster proxy with tunnelling

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProviderTest.java

Uses the configured LDAP admin group to set the `gateway.knox.admin.groups` property for both Knox and IDBroker.
Follows a similar pattern to what was done for Zeppelin in CB-3094

CB-4166 Knox - gateway.knox.admin.groups should be configured to the admin group

---

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/FlowStructuredEventHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/StructuredFlowEventFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/ClusterToClusterDetailsConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/StructuredFlowEventFactoryTest.java

- Removed freeipa call because it was invoked with every transition during flow and with missing freeipa it was preventing termination for certain clusters

CB-3713 reverted previous solution, removed freeipa fetch from structured event

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProviderTest.java

Remove HDFS hadoop.http.filter.initializers safety valve config since it is set by CM automatically

CB-4197 Remove HDFS hadoop.http.filter.initializers safety valve config

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnConfigProviderTest.java

Remove YARN hadoop.proxyuser.knox.* safety valve configs since these are set by CM already

CB-4201 Remove YARN hadoop.proxyuser.knox.* safety valve configs

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/audit/AuditEventService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackTemplateService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/StructuredEventDBService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/audit/AuditEventServiceTest.java
core/src/test/java/com/sequenceiq/general/RepositoryRestrictionTest.java
environment/src/test/java/com/sequenceiq/environment/RepositoryRestrictionTest.java

only for the core and environment module(s)

CB-1097 – prevent developer from accessing repository interfaces directly

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UsersyncPoller.java

The entitlement check was moved out of the forEach into a stream filter
to be more streamy and get back one level of indentation.
This commit is in response to @giladwolff 's comment on https://github.com/hortonworks/cloudbreak/pull/6602

CDPCP-1017. Usersync poller filters based on entitlement

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/ExposedService.java
core/src/main/resources/defaults/blueprints/cdp-data-engineering-702.bp
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/das/DasConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/das/DasConfigProviderTest.java

- Adding DAS in DE template.
- Fix DAS service name in ExposedServices.
- Fix Tez proto base directory in DE template.
Closes #6548 
Closes #CDPD-3643

CDPD-3643 - Configure DAS in DE template.

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/start.sls

Reverts hortonworks/cloudbreak#6611

Revert "CB-837 increase agent token check attempt to 20"

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackValidationV4RequestToStackValidationConverter.java

CB-4303 – missing optional check for network exist on conversion

CB-4303 – missing optional check for network exist on conversion

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/newway/cloud/v2/MockCloudProvider.java
integration-test/src/main/resources/testsuites/clusterawstestset.yaml
integration-test/src/main/resources/testsuites/clusterostestset.yaml
integration-test/src/main/resources/testsuites/clusterrecoverytestset.yaml
integration-test/src/main/resources/testsuites/clustertestset.yaml

@lnardai or @sodre90 please review then merge if it is OK for you.

CB-4085 Move all the E2E tests to the new AWS account

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/responses/ImageCatalogV4Response.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/ImageCatalog.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/imagecatalog/ImageCatalogToImageCatalogV4ResponseConverter.java
core/src/main/resources/schema/app/20191018132252_CB-4047_image_catalog_created_field.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/imagecatalog/ImageCatalogToImageCatalogV4ResponseConverterTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/credential/CredentialModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/credential/model/response/CredentialResponse.java
environment/src/main/java/com/sequenceiq/environment/credential/domain/Credential.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/CredentialToCredentialV1ResponseConverter.java
environment/src/main/resources/schema/app/20191018132342_CB-4047_credential_created_field.sql
environment/src/test/java/com/sequenceiq/environment/credential/v1/converter/CredentialToCredentialV1ResponseConverterTest.java

backend development from created on column
Closes CB-4047

CB-4047 backend development from created on column

---

orchestrator-salt/src/main/resources/salt/salt/gateway/cm.sls

Remove world writable privileges for the Knox files

CB-4289 Knox files should not be world writable

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/cdp-token.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/knoxsso.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/manager.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

* Remove `;maxRetryAttempts=300;retrySleep=1000` since it has no effect after KNOX-1093
* Remove explicit `:443` from https url
* Remove unnecessary `<uri>` section

CB-4336 Knox - Misc topologies cleanup

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java

CB-4054 Force termination cleanup merge

---

integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxRepairInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxRepairTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDtoBase.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/BasicSdxTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsSdxCloudStorageTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsSdxTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazonec2/AmazonEC2Util.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazonec2/action/EC2ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/SshJUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/client/SshJClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtil.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/e2e/aws-sdx-recipe-tests.yaml
integration-test/src/main/resources/testsuites/v4/mock/mock-sdx-tests.yaml

@lnardai, @sodre90, @foldik Please review and merge if it is OK for you.

CB-3804 E2E test repair whole cluster

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/Investigable.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/AuditUtil.java

Audit events about clusters in failed tests
Closes CB-4005

CB-4005 Audit events about clusters in failed tests

---

datalake/src/main/resources/sdx/azure/cluster-light-duty-template.json
datalake/src/main/resources/sdx/azure/cluster-medium-duty-ha-template.json

Update Azure datalake templates:
* Instance sizes based on the "Data Lake Technical Specification" wiki
* Storage volume sizes based on the corresponding AWS templates

CB-4154 Update SDX Azure instance types & storage

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java

With these changes, gateway nodes with Knox are configured to register
a CCM tunnel to the nginx fronting Knox on port 443.

CB-4367. Add CCM tunnel for Knox.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazonec2/action/EC2ClientActions.java

There was a merge issue... @lnardai or @sodre90 please review and merge if it is OK for you.

CB-3804 Fix getHostGroupVolumeIds for SDX Multi Repair

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/ImageInfoV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/UpgradeOptionV4Response.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceDefaultNotFoundTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceDefaultTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/upgrade/handler/SdxChangeImageWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeService.java

Upgrade looks for new images with the same parcel and package versions

Cb 4329 Strict validation for OS upgrade for SDX

---

cloud-common/src/main/resources/application.yml
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/ExposedService.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/ClusterProxyError.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/ClusterProxyErrorRpcListener.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java
freeipa/src/test/java/com/sequenceiq/freeipa/client/ClusterProxyErrorRpcListenerTest.java

Merging rc-2.15 to master, conflicts resolved in:
cloud-common/application.yml,
ExposedService.java

Merge rc.2.15 to master

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
environment/src/main/java/com/sequenceiq/environment/cache/CredentialCloudPlatformCache.java
environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialService.java
environment/src/main/java/com/sequenceiq/environment/credential/validation/CredentialValidator.java
environment/src/test/java/com/sequenceiq/environment/credential/service/CredentialServiceTest.java
environment/src/test/java/com/sequenceiq/environment/credential/validation/CredentialValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/service/integration/EnvironmentServiceIntegrationTest.java

CB-4487 Backport CB-4300 to rc-2.15

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/openstack/OpenStackCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/credential/CredentialTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxCloudStorageTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/telemetry/TelemetryTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsSdxCloudStorageTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/azure/AzureAdlsGen2Tests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/azure/AzureSdxCloudStorageTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazons3/AmazonS3Util.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/amazons3/action/S3ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azurecloudblob/AzureCloudBlobUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azurecloudblob/action/AzureCloudBlobClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azurecloudblob/client/AzureCloudBlobClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/storagelocation/AzureTestStorageLocation.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/storagelocation/StorageComponent.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/storagelocation/TestStorageLocation.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/e2e/azure-sdx-cloudstorage-tests.yaml

Please review then merge if it is OK for you.

CB-4145 Create Azure E2E test for SDX

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/securityrule/SecurityRuleService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceGroupV1ToInstanceGroupV4Converter.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverterTest.java
core/src/test/resources/com/sequenceiq/cloudbreak/converter/v4/stacks/stack-with-instancegroups.json
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/CreateFreeIpaRequestToStackConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProvider.java
freeipa/src/main/resources/application.yml

CB-4041 extend cluster's security rules to nginx with control plane cidrs

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/task/AMICopyStatusCheckerTask.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/task/AMICopyStatusCheckerTaskTest.java

Add better logging in the image copy polling process.

CB-4512 Add logging to image copy process

---

cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/scheduler/SyncPollingScheduler.java

Increase delay between polling

Cb 4516 Increase delay between polling

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/CreateFreeIpaRequestToStackConverter.java

CB-4041 only extend security group if rules are given

---

integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml

Fixing support files for the api-e2e-newway-azure Jenkins job.

CB-4145 Fixing E2E test YAML files for AZURE

---

datalake/src/main/java/com/sequenceiq/datalake/configuration/PlatformConfig.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxExternalDatabaseConfigurer.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxExternalDatabaseConfigurerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

now it honors if the flag is set to false. Problem was only for AWS.

CB-4491 Always created database in case of AWS

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsObjectStorageConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/util/AwsIamService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsIDBrokerAssumeRoleValidator.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsIDBrokerMappedRolePermissionValidator.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsIDBrokerObjectStorageValidator.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsInstanceProfileEC2TrustValidator.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsLogRolePermissionValidator.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsRangerAuditRolePermissionValidator.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/util/AwsIamServiceTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsDataAccessRolePermissionValidatorTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsIDBrokerAssumeRoleValidatorTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsIDBrokerMappedRolePermissionValidatorTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsInstanceProfileEC2TrustValidatorTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsRangerAuditRolePermissionValidatorTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cloudprovider/CloudProviderService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidator.java

@lnardai pointed out that I had missing IntelliJ configs which caused code formatting issues. This PR addresses only those code formatting items after fixing IntelliJ configs.

Fix formatting from missing IntelliJ configs

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java

CB-4041 Open 443 port from controlplane on clusters' gateway

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/Cluster.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/DatalakeResources.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceMetaData.java
core/src/main/resources/schema/app/20191114152446_CB-1358_Rename_every_Ambari_related_DB_column_to_generic_one.sql

CB-1358 - Rename every Ambari related DB column to generic one

CB-1358 - Rename every Ambari related DB column to generic one

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/CloudStorageConverter.java

When converting from a `CloudStorageRequest` to a `CloudFileSystemView` make sure to attached the DynamoDB table.

CB-4526 IDBroker mapping validation - Ensure dynamodb checked

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/init.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls

Add failhard option to salt states
Closes cb-4534

CB-4534 Add failhard option to salt states

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java

add sdxtestdto to structured event logger
Closes cb-4005

CB-4005 add sdxtestdto to structured event logger

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXStartStopTestParameters.java

Increase the nodecount on the big cluster test
Closes CB-4456

CB-4456 Increase the nodecount on the big cluster test

---

core/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/cdp-data-engineering-hueha-702.bp
core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-hueha-702.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

Add Hue HA template for DE template to support customer's new request
Closes #CDPD-5755

[CDPD-5755] Add default DE Hue HA template to support Customer request

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/search/KibanaSearchUrl.java

Kibana url fixes.
Closes CB-4004

CB-4004 Kibana url fix

---

datalake/src/main/java/com/sequenceiq/datalake/flow/start/handler/SdxSyncHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/CloudbreakFlowService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/ProvisionerService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRepairService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/CloudbreakFlowServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/ProvisionerServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxRepairServiceTest.java

- on behalf of foldik
- need some additional testing

CB-4139 CB polling during sdx delete

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/User.java
freeipa/src/main/java/com/sequenceiq/freeipa/init/ModifyAdminPassordExpiration.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/freeipa/UserFindResponse.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/freeipa/UserModResponse.java

- set admin password expiration on creation
- to update existing we run a modification for admin password expiration on application startup which can be dropped later when all env is updated

CDPCP-1140 Set FreeIPA admin password expiration

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/PublicKeyDeleteHandler.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/PublicKeyDeleteHandlerTest.java

and the public key id stays null

Fix NPE on Public Key deletion in case the Environment create failed

---

cloud-openstack/build.gradle
gradle.properties
integration-test/build.gradle

Basic cluster creation, upscale, downscale and termination scenarios tested.

CB-4609 Update openstack4j-connectors dependency

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/objectstorage/ObjectStorageValidateRequest.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsIDBrokerMappedRolePermissionValidator.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsIDBrokerObjectStorageValidator.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsLogRolePermissionValidator.java
common/src/main/java/com/sequenceiq/cloudbreak/common/json/JsonUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/CloudProviderServicesV4Controller.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidator.java

Added extra logs to figure out why log storage validation fails on mow dev. It cannot be reproduced in local.

CB-4670 extra logs and disabling the faulty part of the validation

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/EnvironmentClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/FreeIPAClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/MicroserviceClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RedbeamsClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SdxClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/Actor.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/CloudbreakUser.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/PurgeGarbageService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/RunningParameter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MultiThreadTenantTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/WorkspaceTest.java

multitenant test in order to catch threadlocal bug in crn handling
Closes CB-4648

CB-4648 multi tenant integration test

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
integration-test/scripts/create-image.sh

-should return 400 BadRequest with detailed information

CB-4678 If error happens during Image selection from img catalog

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxIdBrokerConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxIdBrokerConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/BaseFileSystemConfigurationsView.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/FileSystemConfigurationsViewProvider.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/adls/AdlsFileSystemConfigurationsView.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/adlsgen2/AdlsGen2FileSystemConfigurationsView.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/gcs/GcsFileSystemConfigurationsView.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/s3/S3FileSystemConfigurationsView.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/wasb/WasbFileSystemConfigurationsView.java
template-manager-recipe/src/test/java/com/sequenceiq/cloudbreak/recipe/moduletest/RecipeModulTestModelProvider.java

CANNOT BE MERGED until new CM version is released containing the required parameter

CB-4269 - Propogate assumer identity property to IDBroker config

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureContextService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureAttachmentResourceBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/upscale/AzureUpscaleService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilderTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/upscale/AzureUpscaleServiceTest.java

@keyki or @daszabo or @gergopapi2 pls review

CB-4392 upscale attach fix during cloudbreak restart

---

README.md

Added the missing step to the readme of this project.

CB-4694 added missing step to readme

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/UpgradeOptionV4Response.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeServiceTest.java

Reject upgrade/repair requests for clusters created from base image.

CB-4691 Reject upgrade/repair requests for clusters created from base image

---

core/src/main/java/com/sequenceiq/cloudbreak/util/UsageLoggingUtil.java
usage-collection/src/generated/main/java/com/cloudera/thunderhead/service/common/usage/UsageProto.java
usage-collection/src/main/proto/usage.proto

…ters
1. Update usage.proto
2. Add clusterDefinitionName as the blueprint name
3. This is used to track the number of datamart and dataengineering datahub clusters.
4. In future usage of different flavours of datalake clusters.
./gradlew clean build

Usage reporting enhacement

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonCloudProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/openstack/OpenStackCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ImageSettingsTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/image/DistroXImageTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/BasicStackTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsDistroXBaseImageTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsSdxBaseImageTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsSdxUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtil.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/e2e/aws-distrox-baseimage-tests.yaml
integration-test/src/main/resources/testsuites/e2e/aws-sdx-baseimage-tests.yaml
integration-test/src/main/resources/testsuites/e2e/aws-sdx-upgrade-tests.yaml

CB-4706 Introduce new SDX and Distrox create test cases with Base Image

---

common/src/main/java/com/sequenceiq/cloudbreak/util/JaxRSUtil.java

Is this new error message acceptable:
`Status: 502 Bad Gateway Response: {"status":502,"code":"cluster-proxy.ccs.mina-mgmt-unavailable","message":"Unable to discover an instance of MinaSSHdService for accountId cloudera."}`

CB-4777 Improve salt logging when unexpected error is received

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsSdxTests.java

CB-4717 Re-introduce SDX repair test cases for IDBroker and Master

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/service/ClusterComponentConfigProvider.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Component.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/ClusterComponent.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceMetaData.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ComponentConfigProviderService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/userdata/UserDataService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/main/resources/application.yml
core/src/main/resources/schema/app/20191209154124_CB-4299_Increase_instance_metadata_id_seq_step.sql
core/src/main/resources/schema/app/20191209164124_CB-4299_Increase_component_id_seq_step.sql
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackServiceTest.java

Reverts hortonworks/cloudbreak#6910

DO NOT MERGE Revert "Revert "CB-4299 Batching entity saves, bumping sequence steps""

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentDeleteForcedAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/EnvironmentTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/BasicEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsBasicEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/azure/AzureBasicEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/yarn/YarnBasicEnvironmentTests.java

CB-4718 Create test case for environment delete and force delete as well

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/StartFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/StopFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/start/ClusterStartService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartStopService.java

CB-3845 Remove sync flow from start / stop flow chains, update instance states during start/stop

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/ManualClusterRepairMode.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/RdsConfigRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/model/HostGroupName.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/model/RepairValidation.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/model/Result.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RdsConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/RdsConfigServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeServiceTest.java

Extract repair cluster functionality into separate class, unify repair validation.

CB-4739 Refactor cluster repair

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/ProvisionerService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/start/SdxStartService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/stop/SdxStopService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/ProvisionerServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/start/SdxStartServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/stop/SdxStopServiceTest.java

Add flow API polling to SDX-CB polling

CB-4781 SDX should use FLOW api in every CB poller

---

datalake/src/main/java/com/sequenceiq/datalake/configuration/PlatformConfig.java
datalake/src/main/java/com/sequenceiq/datalake/flow/create/handler/RdsWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/handler/RdsDeletionHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/AwsDatabaseServerParameterSetter.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/AzureDatabaseServerParameterSetter.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseConfig.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseConfigKey.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseServerParameterSetter.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/MockDatabaseServerParameterSetter.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/DatabaseConfigKeyTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/DatabaseServiceTest.java

A refactoring step before making external rds the default on azure.

CB-4876 Sdx on azure: refactor redbeams parametrizing

---

orchestrator-salt/src/main/resources/salt-common/salt/fluent/init.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/check_fluent_plugins.sh.j2
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/output.conf.j2

- added auto-upgrade script from master branch (just a small change to include auzrestorage_gen2 plugin)
- add new azurestorage gen2 plugin
tested manually

CB-4774. Fluentd process in master node of DL/DW is leaking memory

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/executor/EvaluatorExecutorRegistry.java

@akanto or @sodre90 pls review

CB-4552 Increase executor registry timeout to 5min

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxCheckForUpgradeAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxUpgradeAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/aws/AwsSdxUpgradeTests.java

@sodre90 and/or @horadla23 please review. If it is Ok for you, please merge.

CB-3805 Create new AWS E2E tests for SDX Image Upgrade

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProviderTest.java

If TLS is enabled, then whitelist should be strict HTTPS only.

CB-4908 Ensure strict HTTPS whitelist if TLS enabled

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java

CB-4902 - fill environment crn on stack request in internal datalake creation if it does not exists

CB-4902 - fill environment crn on stack request in internal datalake creation

---

core/src/main/resources/application.yml

- used the parcels from the latest base image
- please double check if all URL updates are correct

CB-4446 updating parcel URLS for the latest prewarmed versions

---

core/src/main/resources/application.yml

- will do some base image test locally

CB-4446 fixing schemaregistry version

---

core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/test/java/com/sequenceiq/cloudbreak/JpaTest.java
core/src/test/java/com/sequenceiq/cloudbreak/SqlStatementInspector.java
environment/src/test/java/com/sequenceiq/environment/service/integration/SqlStatementInspector.java

test to check hibernate queries how many sql statement generates
Closes CB-4979

CB-4979 test to check hibernate queries how many sql statement generates

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/cm/ClouderaManagerClusterCreationEvaluator.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/cm/ClouderaManagerClusterCreationEvaluatorTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/GrainPropertiesService.java

Grains were uploaded in wrong order during repair.

Fix SDX multiple repair

---

core/src/main/resources/schema/app/20200109144610_CB-5016_-_error_message_on_pre-remove-ambari_clusters.sql

CB-5016 - error message on pre-remove-ambari clusters

CB-5016 - error message on pre-remove-ambari clusters

---

README.md

CB-5015 - unable to restart flow after single node cloudbreak restart

CB-5015 - unable to restart flow after single node cloudbreak restart

---

README.md

Nothing specific, just a small correction.

Remove duplicated word

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls

CB-4838 cm.settings file only created once

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java

Now the test gathers all required volumes.

Fix volume id comparison in multi node repair test

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtilForMultipleStatuses.java

Decrease wait time in integration tests when cloudProvider is MOCK

CB-5119 [Kaizen] integration test improvement

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/doc/CredentialPrerequisiteModelDescription.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/response/AzureCredentialPrerequisites.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCredentialConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformParameters.java
cloud-azure/src/main/resources/definitions/azure-role-def.json
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCredentialConnectorTest.java

Add azure role definition template.

CB-5062 Azure AppId required permissions on the UI

---

core/src/main/resources/schema/app/20200116132808_CB-4600_rename_deprected_blueprints.sql

CB-4600 rename deprected to stackversion

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-702.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-hueha-702.bp
core/src/main/resources/defaults/blueprints/cdp-de-llap.bp
core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-702.json
core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-hueha-702.json
core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-702.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/HostGroupType.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/InstanceCountParameter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/InstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/instancegroup/DistroXInstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/instancegroup/DistroXInstanceGroupsBuilder.java
integration-test/src/main/resources/blueprint/clouderamanager.bp

Introduce Optional Gateway HostGroup in Default DE Templates.
Closes #DISTX-367

DISTX-367-Introduce optional gateway HostGroup in DE Templates

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsCredentialViewProvider.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnectorTest.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/CredentialVerificationHandler.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/credential/model/parameters/aws/AwsCredentialParameters.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/credential/model/parameters/aws/RoleBasedParameters.java

CB-5133 - credential validation error ignored in case of aws

CB-5133 - credential validation error ignored in case of aws

---

core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserProfileService.java

Please somebody with a good eye for multithreading have a look at it.

CB-5004 Fix race condition issue on UserProfile save

---

orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/output.conf.j2

add enable retry + retry settings for fluentd outputs (abfs)

CB-5180. Fluentd abfs upload: add retry logic for handling intermittent operation errors

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxForceDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxForceDeleteInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXForceDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentForceDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/stack/StackForceDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/DistroXTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/EnvironmentTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/StackTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/BasicEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupUtil.java

@lnardai or @sodre90 please review.

CB-5069 Environment delete should be force delete when auto clenaup happens

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackDownscaleValidatorService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackDownscaleValidatorServiceTest.java

CB-4031 - Failed to delete Data Lake master host :: message fix

CB-4031 - Failed to delete Data Lake master host :: message fix

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/BasicEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/stack/BasicStackTests.java
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/aws-image-validation-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-image-validation-tests.yaml

BasicStackTests, BasicEnvironmentTest and aws image validation test suite have succeeded on AWS locally for me

CB-5206 E2E AWS Api test running took too long on master (QA)

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureNetworkConnector.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureNetworkConnectorTest.java

CDPUI-377 - Azure Envs are stuck in deletion error

CDPUI-377 - Azure Envs are stuck in deletion error

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxCloudStorageTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/AwsCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/AmazonS3Util.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/action/S3ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/AzureCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/AzureCloudBlobUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/action/AzureCloudBlobClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java

@lnardai please review and merge if it is OK for you.

CB-5176 Create new test case(s) for validate S3 FreeIPA, DataLake and DataHub logs are created

---

environment-api/src/main/java/com/sequenceiq/environment/api/v1/credential/model/parameters/yarn/YarnParameters.java
environment/src/main/java/com/sequenceiq/environment/credential/attributes/yarn/YarnCredentialAttributes.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/YarnCredentialV1ParametersToAwsYarnAttributesConverter.java

Reverts hortonworks/cloudbreak#7170

Revert "CB-5330 Remove ambari username from yarn credential"

---

environment-api/src/main/java/com/sequenceiq/environment/api/v1/credential/model/parameters/yarn/YarnParameters.java
environment/src/main/java/com/sequenceiq/environment/credential/attributes/yarn/YarnCredentialAttributes.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/converter/YarnCredentialV1ParametersToAwsYarnAttributesConverter.java

Reverts hortonworks/cloudbreak#7175

Revert "Revert "CB-5330 Remove ambari username from yarn credential""

---

common-model/src/main/java/com/sequenceiq/common/api/telemetry/base/FeaturesBase.java
common-model/src/main/java/com/sequenceiq/common/api/telemetry/doc/TelemetryModelDescription.java
common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/Telemetry.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/TelemetryConfiguration.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigService.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigView.java
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigServiceTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/telemetry/EnvironmentFeatures.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/TelemetryApiConverter.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/TelemetryApiConverterTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/handler/MachineUserRemoveHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaInstallService.java
freeipa/src/main/resources/freeipa-salt/salt/fluent/template/input.conf.j2
freeipa/src/test/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/telemetry/TelemetryTestDto.java
orchestrator-salt/src/main/resources/salt-common/pillar/fluent/init.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/init.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/output_databus.conf.j2
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/td-agent.conf.j2
orchestrator-salt/src/main/resources/salt/salt/fluent/template/input.conf.j2

CB-5244. Rename clusterDeploymentLogsReport to clusterLogsCollection

---

integration-test/src/main/resources/application.yml

@lnardai or @doktoric please review, then merge if it is OK for you.

CB-5394 West US region is not enabled in environment. Enabled regions westus

---

cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackInstanceConnector.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollInstancesStateTask.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollTaskFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/AmbariStartupListenerTask.java
integration-test/docker-compose_template.yml
integration-test/test-image/Dockerfile

CB-5160 Waiting for instances to be started / stopped on openstack

---

orchestrator-salt/src/main/resources/salt-common/salt/fluent/init.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/check_fluent_plugins.sh.j2

install reduction plugin (if not provided in the image)

CB-5405. Install fluent-plugin-reduction gem for td-agent.

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-702.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-hueha-702.bp
core/src/main/resources/defaults/blueprints/cdp-de-llap.bp
core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-702.json
core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-hueha-702.json
core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-702.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/HostGroupType.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/InstanceCountParameter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/InstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/instancegroup/DistroXInstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/instancegroup/DistroXInstanceGroupsBuilder.java
integration-test/src/main/resources/blueprint/clouderamanager.bp

Reverts the DISTX-367 DE Template changes which introduced optional gateway since there are concerns of breaking backward compatibility with existing custom launch templates.
Closes #DISTX-404

Revert "DISTX-367-Introduce optional Gateway HostGroup in DE Templates"

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsRight.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/NifiConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/NifiRegistryConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/NifiRegistryVolumeConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/NifiVolumeConfigProvider.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/VolumeUtils.java
template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/VolumeUtilsTest.java

CB-5019, CB-5020: Extend Nifi configproviders with certain config properties

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/kerberos/KeytabConfigurationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaCleanupService.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/kerberos/KeytabConfigurationHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaCleanupServiceTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/kerberos/KerberosDetailService.java
template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/kerberos/KerberosDetailServiceTest.java

CB-5395 Update keytabs in case of YARN as a child environment.

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResources.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResourcesTest.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/GetPlatformAccessConfigsHandler.java

CB-5483 - paging for role fetching from aws

CB-5483 - paging for role fetching from aws

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MockedTestContext.java

First delete stack and other things then stop spark server

CB-5527 Fix integration test context cleanup

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/health/NodeHealthDetails.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthDetailsService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthServiceTest.java

Adding instance ID to the health check response.
Updated unit tests initialization.  Additionally ran manual tests.

CB 5486: Add Instance ID to health check response.

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxRepairRequest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRepairService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxRepairServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxRepairTestDto.java

hostGroupName should not be used anymore

CB-5556 removed unused hostGroup param from RepairRequest

---

integration-test/scripts/docker-compose.sh

@foldik or @lnardai please review and merge if it is OK for you.

CB-5290 set -ex for Integration Test docker-compose script

---

environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentDeletionService.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/ChildEnvironmentRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ChildEnvironmentService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaDeletionService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaDeletionServiceTest.java

CB-5531 Validate Freeipa delete request

CB-5531 Validate Freeipa delete request

---

integration-test/docker-compose_template.yml
integration-test/scripts/docker-compose.sh

CB-5581 docker-compose up times out with UnixHTTPConnectionPool

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/search/KibanaSearchUrl.java

fixing kibana url link in test report
Closes 5186

CB-5186 kibana url fix

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/describe/DescribeFreeIpaResponse.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/list/ListFreeIpaResponse.java
freeipa-api/src/main/java/com/sequenceiq/service/api/doc/ModelDescriptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/FreeIpaToListFreeIpaResponseConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/ChildEnvironment.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/Stack.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/ChildEnvironmentRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/FreeIpaRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ChildEnvironmentService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/FreeIpaToListFreeIpaResponseConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/ChildEnvironmentServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/StackServiceTest.java

CB-5122 Remove eager fetching of child environments

CB-5122 Remove eager fetching of child environments

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/freeipa/FreeIpaDeletionHandler.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/freeipa/FreeIpaDeletionHandlerTest.java

CB-5395 Fix FreeIpa delete/detach conditions

CB-5395 Fix FreeIpa delete/detach conditions

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-702.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-710.bp
core/src/main/resources/defaults/clustertemplates/aws/aws-dataengineering-702.json
core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-702.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/HostGroupType.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/InstanceCountParameter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/InstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/instancegroup/DistroXInstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/instancegroup/DistroXInstanceGroupsBuilder.java
integration-test/src/main/resources/blueprint/clouderamanager.bp

Reintroduce gateway nodes in cdp 702 and 710 templates.
Closes #DISTX-367

Distx 367 gatewaynodes

---

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigView.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StackRequestManifesterTest.java
orchestrator-salt/src/main/resources/salt-common/pillar/fluent/init.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/init.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/output.conf.j2

same as https://github.com/hortonworks/cloudbreak/pull/7332 but for rc-2.17

CB-5636. ABFS logs are missing from idbroker host.

---

core/src/main/resources/application.yml
template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.1.json

CB-5647 - Update NiFi Version in Services Preview after selecting the nifi template

CB-5647 - Update NiFi Version in Services Preview after selecting the nifi template

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java

CLOUD-5695 Ports are not opened to customer provided CIDR

---

common/src/main/java/com/sequenceiq/cloudbreak/util/NullUtil.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentValidationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/repository/EnvironmentRepository.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentResourceService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/AwsEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/AzureEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/EnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/MockEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/YarnEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EnvironmentNetworkProviderValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/NetworkCreationValidator.java
environment/src/main/java/com/sequenceiq/environment/network/CloudNetworkService.java
environment/src/main/java/com/sequenceiq/environment/network/NetworkService.java
environment/src/main/java/com/sequenceiq/environment/network/dto/NetworkDto.java
environment/src/main/java/com/sequenceiq/environment/platformresource/v1/converter/CloudAccessConfigsToPlatformAccessConfigsV1ResponseConverter.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/AwsEnvironmentNetworkValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/AzureEnvironmentNetworkValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/NetworkTestUtils.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/YarnEnvironmentNetworkValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/NetworkCreationValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/network/CloudNetworkServiceTest.java
environment/src/test/java/com/sequenceiq/environment/network/NetworkServiceTest.java

CB-5298 – Azure environment creation: result of subnet fetch not fully checked

---

datalake/build.gradle
freeipa/src/test/java/com/sequenceiq/freeipa/kerberos/KerberosConfigServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/kerberos/v1/CreateKerberosConfigRequestToKerberosConfigConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/ldap/LdapConfigServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/ldap/LdapConfigValidatorTest.java

- followup PR where the disabled unit tests are fixex and rewritten in junit5

CB-5659 re-enabling testcase skipped. Also making the Junit5 testcases.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/CloudbreakTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/mock/HttpMock.java

Adds support to the integration test framework to specify cloud platform at run-time when creating a TestDTO.

CB-5123 Adds support to change cloud platform at run-time

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdater.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java

CB-4912 Include Cluster type and origin tags in CM Cluster Templates

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/action/S3ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/action/AzureCloudBlobClientActions.java

CB-5708 Remove cloud storage object listing from suite logs

---

core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserProfileService.java

CB-5733 Ignore ConstraintViolationException during userprofile creation

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSetup.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelper.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/util/AwsInstanceStatusMapper.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AuthenticatedContextView.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsAuthenticatorTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceConnectorTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetaDataCollectorTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelperTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsLaunchTest.java

awsInstanceConnector refactor and integrationtest
Closes 5619

CB-5619 cloud-aws instanceConnector and authenticator test

---

cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsValidatorsTest.java

aws validators tests
Closes CB-5626

CB-5626 aws validators tests

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformResources.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/AzureEnvironmentNetworkValidator.java

Unit tests will be submitted to master .

Npe fix azure get network

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/encryption/EncryptedSnapshotService.java

1. Found that this is the only place where we use sync polling scheduler.
2. I see that this class is used in few flows.
3. The top offenders are describe images, ASGs and stacks, but those are already using backoff scheduler.

SRE-5408 Reduce DescribeVolumes AWS call volume.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIPATestDto.java

CB-5782 Cleanup freeipa after IT run

CB-5782 Cleanup freeipa after IT run

---

environment/src/main/java/com/sequenceiq/environment/environment/validation/network/AzureEnvironmentNetworkValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/AzureEnvironmentNetworkValidatorTest.java

CB-5795 Azure subnet validation improvement: given subnets must exist on azure side

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/UpgradeOptionV4Response.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeServiceTest.java

- better logging in code for UpgradeOption Results
- added extra reasoning to different clauses

CB-5809 returning a reasoning in the datalake repair not finished case

---

freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java

Lookup stacks for user sync and password setup by child environment crn as well.

CB-5901 Lookup stacks by child environment crn as well

---

template-manager-tag/src/main/java/com/sequenceiq/cloudbreak/tag/DefaultCostTaggingService.java
template-manager-tag/src/test/java/com/sequenceiq/cloudbreak/DefaultCostTaggingServiceTest.java

CB-5938 Empty tag value breaks environment creation

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsTerminateService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsTerminateServiceIntegrationTest.java

aws terminate service refactor
Closes CB-5897

CB-5897 aws terminate service refact and modification

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtil.java

@biharitomi or @afarsang pls review

CB-5875 E2e tests won't be executed if test init failed

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandler.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandlerTest.java

CB-5872 - NPE check on freeipa creation

CB-5872 - NPE check on freeipa creation

---

environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentTest.java

Add permission checks by resource

CB-5584 Make environment accessible for creator only

---

cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnPlatformParameters.java

CB-5963 Enable auto TLS support on YARN platform

CB-5963 Enable auto TLS support on YARN platform

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/concurrent/ActorCrnTaskDecorator.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/concurrent/CompositeTaskDecorator.java
cloud-common/src/test/java/com/sequenceiq/cloudbreak/concurrent/ActorCrnTaskDecoratorTest.java
cloud-common/src/test/java/com/sequenceiq/cloudbreak/concurrent/CompositeTaskDecoratorTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/configuration/UsersyncConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/UserSyncStatusRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/operation/OperationAcceptor.java
freeipa/src/test/java/com/sequenceiq/freeipa/configuration/UsersyncConfigTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncServiceTest.java

Fixed compile error introduced when  #7428 was merged into rc-2.19

CDPCP-1549

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtil.java

@lacikaaa or @daszabo pls review

Merge rc18 to rc219

---

auth-connector/src/main/proto/usermanagement.proto
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/KerberosMgmtV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/doc/KeytabModelNotes.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/doc/KeytabOperationsDescription.java
freeipa/build.gradle
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/UserKeytabGenerator.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/UserKeytabService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/kerberos/KrbKeySetEncoder.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/kerberos/UserKeytabGenerator.java
freeipa/src/test/java/com/sequenceiq/freeipa/controller/KerberosMgmtV1ControllerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/UserKeytabGeneratorTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/UserKeytabServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/kerberos/KrbKeySetEncoderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/kerberos/UserKeytabGeneratorTest.java

This updates FreeIPA service to include a new endpoint that allows retrieving a keytab for a user or machine user under a provided environment.

CDPCP-1291. Add support for retrieving a keytab in FMS

---

client-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/retry/ClouderaManagerApiFactory.java
client-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/retry/CmClientConfig.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtSetupService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/AbstractCmConfigService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/CmConfigService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtServiceConfigLocationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtServiceLogConfigService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtYarnConfigService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/config/CmConfigServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtServiceConfigLocationServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtServiceLogConfigServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtYarnConfigServiceTest.java

CB-5726
Solve CM swapping warnings
CB-5727
Solve CM clock offset issues

CB-5726 Suppress CM swapping warnings

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/instance/InstanceGroupRequest.java

Added log message for FreeIPA InstanceGroupRequest's inherited
properties.

Improve log message for FreeIPA InstanceGroupRequest

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/status/AzureInstanceStatus.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxRepairInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/sdx-repair-tests.yaml

Please review. If it is OK for you, please merge.

CB-5992 Introduce SDX Repair E2E tests to Azure suite

---

cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnPlatformParameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/cluster/cm/ClouderaManagerV4Request.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/environment/ClusterCreationEnvironmentValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecorator.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/environment/ClusterCreationEnvironmentValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/ClusterCreationSetupServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/ClusterDecoratorTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/DetailedEnvironmentResponse.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentBaseResponse.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDto.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentApiConverter.java

CB-6037 Retrieve auto tls settings by parent environment cloud platform

CB-6037 Parent environment platform based AutoTLS

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/status/ClusterStatusUpdater.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/StructuredEventDBService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/ProvisionerService.java

Update stack and cluster status after install in the same transaction

CB-6050 [FAILED AZURE E2E] SDX polling failed when stack is available and cluster is requested

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/database/RedbeamsDatabaseServerCreateAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/database/RedbeamsDatabaseServerDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/datalake/SdxUpgradeTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/RedbeamsDatabaseServerTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractRedbeamsTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ClusterTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/DeletableRedbeamsTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/database/RedbeamsDatabaseServerTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/database/RedbeamsDatabaseTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/ITResponse.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/ImageCatalogMockServerSetup.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RedbeamsDatabaseServerTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtil.java
integration-test/src/main/resources/mockresponse/imagecatalog/catalog-with-for-upgrade.json

- Redbeams needs additional mock provider to allow a mocked flow test in redbeams, that will be a separate PR

CB-5927 adding upgrade mock test for sdx

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtil.java

Refactor wait util logic in instance group status wait

CB-6106 Clean up instance status wait logic

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/NifiConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/NifiRegistryConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/RangerAutoCompleteConfigProvider.java

CB-5324 Enabling Ranger autocomplete of NiFi and NiFi Registry resources

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/InstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/InstanceTemplateV4TestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDtoBase.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java
integration-test/src/main/resources/application.yml

CB-5546 Use SDX cluster instead of a DistroX one for hybrid e2e test

CB-5546 Use SDX cluster instead of a DistroX one for hybrid e2e test

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java

@keyki or @horadla23 pls review

CB-6125 creator of an environment will automaticly get enviromentAdmin

---

common/src/main/java/com/sequenceiq/cloudbreak/util/NullUtil.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentValidationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/NetworkCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentResourceService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/AwsEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/AzureEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/EnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/MockEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/YarnEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EnvironmentNetworkProviderValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/NetworkCreationValidator.java
environment/src/main/java/com/sequenceiq/environment/network/CloudNetworkService.java
environment/src/main/java/com/sequenceiq/environment/network/NetworkService.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/RegistrationType.java
environment/src/main/java/com/sequenceiq/environment/network/dto/NetworkDto.java
environment/src/main/java/com/sequenceiq/environment/platformresource/v1/converter/CloudAccessConfigsToPlatformAccessConfigsV1ResponseConverter.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/AwsEnvironmentNetworkValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/AzureEnvironmentNetworkValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/NetworkTestUtils.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/YarnEnvironmentNetworkValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/NetworkCreationValidatorTest.java
environment/src/test/java/com/sequenceiq/environment/network/CloudNetworkServiceTest.java
environment/src/test/java/com/sequenceiq/environment/network/NetworkServiceTest.java

removed the problematic part what has caused some issues earlier  ¯\_(ツ)_/¯

[RE::] CB-5298 - Azure environment creation: result of subnet fetch not fully checked

---

common/src/main/java/com/sequenceiq/cloudbreak/validation/SubnetType.java
common/src/main/java/com/sequenceiq/cloudbreak/validation/SubnetValidator.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/base/EnvironmentNetworkBase.java
environment-api/src/test/java/com/sequenceiq/environment/api/v1/environment/validator/NetworkCidrValidatorTest.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EnvironmentNetworkProviderValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/EnvironmentNetworkProviderValidatorTest.java

validation has been moved into request time, and only for new network
Closes 6195

CB-6195 rfc compliancy check is not needed in case of existing network

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/NetworkCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/network/service/SubnetIdProvider.java
environment/src/test/java/com/sequenceiq/environment/network/service/SubnetIdProviderTest.java

CB-6215 Parent network overwrite should happen in case of the same cloud platform

CB-6215 Parent network overwrite should happen in case of the same cloud platform

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJobTest.java

Handle stack states in stack status checker

CB-5954 SETUP_STATE retry fails with NPE

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/NifiKnoxRoleConfigProvider.java

Adds all the Knox topology names to the `nifi.web.proxy.context.path`

CB-6206 nifi.web.proxy.context.path needs to include all Knox topology names

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java

CB-5124 Fix Hybrid cloud e2e test.
Further investigation needed why it is failing on parent environment deletion (CB says there is a child environment - meanwhile it got deleted before) when the framework tries to clean up the context.

CB-5124 Fix Hybrid cloud e2e test.

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceConnector.java

This change adjusts the reboot to properly reboot only started instances and
to call start on stopped instances. Because of AWS lifecycle
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html
other statuses cannot be started or rebooted.
Manually tested against 3 node FreeIPA with instances in various states, including
started, stopped, terminated.

CB-6251: Could not reboot stopped FreeIPA

---

freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/UserKeytabService.java
freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/UserKeytabServiceTest.java

Currently it's possible for the user to provide a user that isn't
present (hasn't been synced) into an environment. In this case we
throw an appropriate exception.

CDPCP-1669. Verify user exists in an environment before getting keytab

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollector.java
core-api/src/main/resources/definitions/exposed-services.json

CB-5487 - Knox - Oozie API doesn't show in gateway tab

CB-5487 - Knox - Oozie API doesn't show in gateway tab

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifi/NifiVolumeConfigProvider.java

This fix is introduced to enable cluster creation with CFM-1.0.0.0 and CFM-1.0.1.0 which is required by the DiM sustaining team.

CFM-913 Fix CFM-1.0.1.0 cluster creation

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxDistroxTest.java

CB-6370 Restore the validate ExternalDatabaseHostname step to Distrox tests

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxImagesTests.java

CB-6408 Result checker reports skipped testcase

---

orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls

CB-6411 Fix ipa client install on YARN cloud platform

CB-6411 Fix ipa client install on YARN cloud platform

---

integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java
integration-test/src/main/resources/application.yml

CB-6217 Intorduce test case timeout for all the E2E test cases

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterKerberosService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/OrchestratorRecipeExecutor.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterKerberosServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/OrchestratorRecipeExecutorTest.java

Fix termination with stopped nodes.

CB-6311 DistroX termination hangs if cluster is STOPPED

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/config/EnvCreationFlowConfig.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentValidationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/NetworkCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/PublicKeyCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandler.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/PublicKeyCreationHandlerTest.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandlerTest.java

EnvironmentService validation fails when it has validation error
Closes 6394

CB-6394 EnvironmentService validation fails when it has validation error

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxDatabaseAvailabilityType.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxDatabaseRequest.java
datalake/src/main/java/com/sequenceiq/datalake/entity/SdxCluster.java
datalake/src/main/java/com/sequenceiq/datalake/flow/create/handler/RdsWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/handler/RdsDeletionHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxExternalDatabaseConfigurer.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/AwsDatabaseServerParameterSetter.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/AzureDatabaseServerParameterSetter.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseServerParameterSetter.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/MockDatabaseServerParameterSetter.java
datalake/src/main/resources/schema/app/20200403103701_CB-6110_Update_DL_API_with_external_rds_options.sql
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/DatabaseServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxExternalDatabaseConfigurerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/database/AwsDatabaseServerParameterSetterTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/database/AzureDatabaseServerParameterSetterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxDistroxTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterCreationTest.java

Support HA, not HA as external database and embedded database.

CB-6110 Update DL API with external rds options

---

core/src/main/resources/application.yml

we agreed with the Nifi team we can leave their parcels out until further notice

CB-6461 readding cdh parcels without nifi for base images to work

---

core/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/cdp-flow-management-710.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-720.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-small-710.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-small-720.bp
core/src/main/resources/defaults/clustertemplates/aws/aws-flow-management-710.json
core/src/main/resources/defaults/clustertemplates/aws/aws-flow-management-720.json
core/src/main/resources/defaults/clustertemplates/aws/aws-flow-management-small-710.json
core/src/main/resources/defaults/clustertemplates/aws/aws-flow-management-small-720.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flow-management-710.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flow-management-720.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flow-management-small-710.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flow-management-small-720.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

CB-6450 Add CFM template and definitions for 7.2.0 runtime versions

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/listener/ReportListener.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/log/Log.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtil.java

@afarsang thank you for your help on this!
@afarsang or @lnardai please review then merge if it is OK for you!

CB-6464 Fixing OnTestFailure ReportListener NullPointerException

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtil.java

The template variable 'flowId' has no value happened probably because the flowid was empty.
Closes CB-6372

CB-6372 checking flowid

---

core/src/main/resources/schema/app/20200408144422_CB-6513_Change_monitoring_user_pwd_type.sql

change type to text, as varchar(255) could be not enough
tested locally

CB-6513. Change monitoring user/pwd DB type from varchar(255) to TEXT.

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsElasticIpService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsTerminateService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsTerminateServiceIntegrationTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsTerminateServiceTest.java

AWS_RESERVE_IP resource it is not created anymore
Closes 5950

CB-5950 AWS_RESERVE_IP resource it is not created anymore

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsRight.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseServiceConfigProvider.java

CB-5287 Create virtualGroups in CB for datahub/adminHBase

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ClusterV4RequestToClusterConverter.java
core/src/main/resources/schema/app/20200414115903_CB-6509_removing_credentials_from_clusters_in_case_of_template.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/cluster/ClusterRequestToClusterConverterTest.java

Clustertemplates should not persist username and passwords.
Also stored credentials are removed in case of clustertemplate
Closes CB-6509

CB-6509 Clustertemplates should not persist username and passwords

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/EnvDeleteActions.java
environment/src/main/resources/schema/app/20200415125953_CB-6594_proxyconfig_id_have_to_be_null_for_archived_environemnts.sql

@keyki or @doktoric pls review

CB-6594 After environment deletion attached proxy config can be deleted

---

integration-test/src/main/resources/application.yml

Move YARN E2E tests to infrastructure-services queue

Move YARN E2E tests to infrastructure-services queue

---

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl-user-facing.conf

@biharitomi or @pdarvasi pls review

CB-6421 nginx userfacing location fix: the path will be cut after the first 'ambari' part

---

environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialService.java
environment/src/test/java/com/sequenceiq/environment/credential/service/CredentialServiceTest.java

CB-5584 Remove credential role assignment to avoid mow issues caused by entitlement

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/task/AzurePollTaskFactory.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/task/networkinterface/NetworkInterfaceDetachChecker.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/task/networkinterface/NetworkInterfaceDetachCheckerContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CredentialProviderSpecTests.java

@sodre90 @gergopapi2 @pdarvasi pls review

ENGESC-1873 Wait for detaching networkinterface from VM before delete it on azure

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/PaywallCredentialValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java

@keyki or @tiborpopovics pls review

CB-6695 Filter out paywall protected blueprints when no paywall credential provided

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureSetup.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java

CB-6746 Create storage account for images with only https traffic

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java

ENGESC-1984 Create azure storage account with only https traffic

---

core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/ComponentLocatorService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/ComponentLocatorServiceTest.java

caused by sneaky bug in ComponentLocatorService

CB-6626 - fixed unexplained component multiplication in exposed service response

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java

Test against mow-dev
```
before
users: 1305
total groups: 2000 <- we're already missing user groups
wl groups: 1946
```
```
after
users: 1305
total groups: 437
wl groups: 48 (1 env 8 groups)
```
The original WAG list and the user member of group list is fetched at a different time
so they can be different as they can launch environments in between
(probably we need to filter there as well), but the `listWorkloadAdministrationGroupsForMember`
only returns the name of the group so there is nothing to filter on.
Locally it's much slower to connect to UMS than from mow-dev so this will not be that different there
Crn handling needed: Error during UMS operation: 'cdpp is not a valid partition value'
There are also weird WAGs
```
Not adding to filter: _c_wag_testers_34ef5c69 crn: null
Not …
```

CB-6605 only sync env related WAGs

---

redbeams/src/main/java/com/sequenceiq/redbeams/sync/DBStackJobService.java
redbeams/src/main/java/com/sequenceiq/redbeams/sync/DBStackStatusSyncService.java
redbeams/src/test/java/com/sequenceiq/redbeams/sync/DBStackJobServiceTest.java

CB-6791 autosync should not run on Azure

CB-6791 autosync should not run on Azure

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDatahubConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/schemaregistry/SchemaRegistryServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDatahubConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/schemaregistry/SchemaRegistryServiceConfigProviderTest.java

schema registry also needs config updates (same as SMM)
seems like the kafka part handles the CM / stack version differences
testing is in progress

 CB-5952. Fix schema registry configs for 7.1.0

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerParcelsApiListenerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerStartupListenerTask.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/image/ImageInfoV4Response.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeOptionsResponseFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeService.java

CB-6287 - Wait for ParcelUpdateService to complete before downloading… …
CB-6797 - ImageV4 response should return readable creation date

CB-6287 - Wait for ParcelUpdateService to complete before downloading

---

cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java
core/src/main/resources/application.yml
environment/src/main/resources/application-test.yml
environment/src/main/resources/application.yml
redbeams/src/main/resources/application.yml

CB-6699 Update YCloud default lifetime

CB-6699 Update YCloud default lifetime

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXImagesTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxRepairWithRecipeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxCloudStorageTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxImagesTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/WaitUtilForMultipleStatuses.java

@afarsang, @lnardai and @topolyai5 please review

CB-6338 Refactor wait for instance states at WaitUtil

---

integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml

-fix repair related issues followup(CB-6861)

CB-6381 disabling repair tests until we switch to 7.2.0 

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxUpgradeResponse.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeController.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/DatalakeUpgradeActions.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeService.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeControllerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java
mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java
mock-caas/src/main/resources/application.yml

https://github.infra.cloudera.com/thunderhead/thunderhead/pull/130

CB-6854 introduce CDP_RUNTIME_UPGRADE entitlement to prevent unattended upgrade

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmHostGroupRoleConfigProviderProcessor.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmHostGroupRoleConfigProviderProcessorTest.java

Generated template: 
```
"services": [
{
"refName": "zookeeper",
"serviceType": "ZOOKEEPER",
"roleConfigGroups": [
{
"refName": "zookeeper-SERVER-BASE",
"roleType": "SERVER",
"base": true,
"configs": [
{
"name": "dataDir",
"value": "/hadoopfs/fs1/zookeeper"
},
{
"name": "dataLogDir",
"value": "/hadoopfs/fs1/zookeeper"
}
]
}
]
},..
```
I have tested with bp of https://jira.cloudera.com/browse/CB-5660 and here is the template part:
```
{
"refName": "zookeeper",
"serviceType": "ZOOKEEPER",
"serviceConfigs": null,
"roleConfigGroups": [
{
"refName": "zookeeper-SERVER-BASE",
"roleType": "SERVER",
"base": true,
"displayName": null,
"configs": [
{
"name": "dataDir",
"value": "/hadoopfs/fs1/zookeeper",
"ref": null,
"variable": null,
"autoConfig": null
},
{
"name": "dataLogDir",
"value": …
```

CB-6862 Zookeeper is not configured with external volume

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/PlatformConfig.java
datalake/src/main/java/com/sequenceiq/datalake/flow/start/handler/RdsStartHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/stop/handler/RdsStopHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/pause/DatabasePauseSupportService.java
datalake/src/test/java/com/sequenceiq/datalake/flow/start/handler/RdsStartHandlerTest.java
datalake/src/test/java/com/sequenceiq/datalake/flow/stop/handler/RdsStopHandlerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/pause/DatabasePauseSupportServiceTest.java

CB-6719 Disable start stop functionality on Azure

CB-6719 Disable start stop functionality on Azure

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceType.java
authorization-common/README.md
authorization-common/src/main/java/com/sequenceiq/authorization/service/CommonPermissionCheckingUtils.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/CrnsByCategory.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/DefaultResourceChecker.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/CommonPermissionCheckingUtilsBulkTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/CommonPermissionCheckingUtilsTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/requests/UpdateImageCatalogV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/responses/ImageCatalogV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/responses/ImageCatalogV4Responses.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/ImageCatalog.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ImageCatalogRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/DefaultImageChecker.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/DefaultImageCheckerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/imagecatalog/ImageCatalogSetAsDefaultAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ImageCatalogPrewarmedTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ImageCatalogTest.java

Add default resource checker for authorization. Add authorization to image catalog.

[WIP] CB-6583 Allow ManagementConsoleUser's to use our default provided image catalog

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java

Use userCrn when get image in stack creator service

CB-6915 [E2E] Unknown error happened when determining image from image catalog:java.lang.IllegalStateException: Crn is not set!

---

environment/src/main/java/com/sequenceiq/environment/credential/service/ServiceProviderCredentialAdapter.java
environment/src/test/java/com/sequenceiq/environment/credential/service/ServiceProviderCredentialAdapterTest.java

Return failed to verify message on credential verification

CB-6858 Make simulate credential policy discreet again

---

redbeams/src/main/java/com/sequenceiq/redbeams/domain/stack/DBStackStatus.java
redbeams/src/main/java/com/sequenceiq/redbeams/repository/converter/DetailedDBStackStatusConverter.java
redbeams/src/test/java/com/sequenceiq/redbeams/repository/converter/DetailedDBStackStatusConverterTest.java

CB-6971 Handle backward incompatible DetailedDBStackStatus values

CB-6971 Handle backward incompatible DetailedDBStackStatus values

---

environment-common/src/main/java/com/sequenceiq/cloudbreak/service/proxy/ProxyConfigDtoService.java
environment-common/src/test/java/com/sequenceiq/cloudbreak/service/proxy/ProxyConfigDtoServiceTest.java
environment/src/main/java/com/sequenceiq/environment/proxy/v1/converter/ProxyRequestToProxyConfigConverter.java
environment/src/test/java/com/sequenceiq/environment/proxy/v1/converter/ProxyRequestToProxyConfigConverterTest.java

@keyki or @lacikaaa pls review

CB-6969 CB should ignore the username and password fields when empty string is set

---

cloudera/docker_images.yaml

List docker images for metadata generation

Update docker images list for metadata generation

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/InstanceStatusConverter.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceMetaData.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/view/InstanceMetaDataView.java
core-model/src/test/java/com/sequenceiq/cloudbreak/domain/InstanceStatusConverterTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/repository/converter/DetailedDBStackStatusConverter.java

CB-6972 Handle backward incompatible InstanceStatus values

CB-6972 Handle backward incompatible InstanceStatus values

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterCommandRepository.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/ClusterCommand.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/ClusterCommandType.java
core/src/main/resources/schema/app/20200505104000_CB-6036_save_cm_command_id.sql

Add cluster command repository

CB-6036 CM commands should be retryable

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIPATestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/Await.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/ExceptionChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/Result.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/StatusChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/TimeoutChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitResult.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/environment/EnvironmentAwait.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/environment/EnvironmentOperationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/environment/EnvironmentTerminationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/environment/EnvironmentWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaAwait.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaOperationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaTerminationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaWaitObject.java
integration-test/src/main/resources/testsuites/v4/mock/wait.yaml

This is the first part of a sequent.
The goal is to retire the old API Test Project Wait Util. The new Wait Service.

CB-6751 Environment and FreeIPA WaitUtil and WaitForMultipleStatuses overall refactor

---

common/src/main/java/com/sequenceiq/cloudbreak/util/SanitizerUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java
mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/MockUserManagementService.java

- this only fixes the username issue when doing an ssh login with usernames that contain @company.com endings

Fix e2e ssh assert for email like usernames

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/ExternalDatabaseStatus.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsStatusLookupService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsStatusLookupServiceTest.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/model/common/Status.java
redbeams/src/main/java/com/sequenceiq/redbeams/sync/DBStackStatusSyncService.java
redbeams/src/test/java/com/sequenceiq/redbeams/sync/DBStackStatusSyncServiceTest.java

CB-6970 Adds delete in progress and deleted to external database statuses

CB-6970 Adds delete in progress and deleted to external database statuses

---

redbeams/src/main/java/com/sequenceiq/redbeams/domain/stack/DBStackStatus.java
redbeams/src/main/resources/schema/app/20200505103700_CB-6886_db_stack_status_shoud_not_be_null.sql

CB-6886 Set DB stack status non null

CB-6886 Set DB stack status non null

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentServiceTest.java

__Note:__
Should be merged after https://github.com/hortonworks/cloudbreak/pull/8045

Cb 7006 Use resource Owner assignment feature in UMS

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java

CB-7031 removing workaround in hybrid usecase

---

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/DetailedStackStatus.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/Status.java
core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterStatusResponse.java
datalake/src/main/java/com/sequenceiq/datalake/entity/DatalakeStatusEnum.java
datalake/src/main/java/com/sequenceiq/datalake/job/SdxClusterStatusCheckerJob.java

CB-6916 Adds new status to indicate the case where cluster instances are deleted on provider side

CB-6916 Adds new status to indicate the case where cluster instances are deleted on provider side

---

orchestrator-salt/src/main/resources/salt-common/salt/fluent/init.sls
orchestrator-salt/src/main/resources/salt/salt/metering/init.sls

Backport file_mode change to support Salt 3000.2

Use 'mode' instead of 'file_mode' in fluent salt script

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/DetailedStackStatusConverter.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/StatusConverter.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/StackStatus.java
core-model/src/test/java/com/sequenceiq/cloudbreak/domain/DetailedStackStatusConverterTest.java
core-model/src/test/java/com/sequenceiq/cloudbreak/domain/StatusConverterTest.java
datalake/src/main/java/com/sequenceiq/datalake/converter/DatalakeStatusEnumConverter.java
datalake/src/main/java/com/sequenceiq/datalake/entity/SdxStatusEntity.java
datalake/src/test/java/com/sequenceiq/datalake/converter/DatalakeStatusEnumConverterTest.java

CB-7604 Handle backward incompatible enum values

CB-7604 Handle backward incompatible enum values

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-702.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp

1. Rename hive to hive_on_tez, this is just cosmetic.
2. Add few hive service configs that were missing for hive_on_tez.

DISTX-445 Correct the parity between normal DE template and HA template.

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/scheduler/StatusToPollGroupConverter.java

CB-7111 Mark the new deleted on provider side status pollable

CB-7111 Mark the new deleted on provider side status pollable

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java

CB-7151 Update cluster status in line with stack status in case of deleted on provider side

CB-7151 Update cluster status in line with stack status in case of deleted on provider side

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/converter/StatusConverter.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/Cluster.java
core-model/src/test/java/com/sequenceiq/cloudbreak/domain/converter/StatusConverterTest.java

CB-7166 Handle backward incompatible cluster Status values

CB-7166 Handle backward incompatible cluster Status values

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AccountMappingSubject.java

No unit tests need to be updated.

CB-7160 Add missing users to mock IDBroker mappings

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java

Simple fix for resolving clouderaManagerIp for general configs (recipe) without touching anything on flow side.
Value is only filled if it does not exist already in the general configs (same for PrimaryGatewayInstanceDiscoveryFQDN)
As generating these configs are called from multiple places, it's not always needed
added unit tests as well
workaround without the fix, adding these to recipe scripts:
```bash
server_host=$(cat /etc/cloudera-scm-agent/config.ini | grep server_host | cut -d'=' -f2)
server_ip=`dig +short $server_host`
```

ENGESC-2389. general.clusterManagerIp parameter is not resolved as parameter is not resolved as part of a recipe

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/distrox/DistroXExternalDatabaseAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java

CB-7143 - DistroX should be validated with DB but not in imagevalidator test

CB-7143 - DistroX should validated with DB but not in imagevalidator test

---

integration-test/.gitignore
integration-test/Makefile
integration-test/scripts/fetch-secrets.sh
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/Actor.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/CloudbreakUser.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CredentialCreateTest.java
integration-test/src/main/resources/testsuites/v4/mock/all-authz-mock-package.yaml
integration-test/src/main/resources/testsuites/v4/mock/minimal-authz.yaml

- First draft that can be run locally if CB is configured properly

CB-7106 added tests with real UMS for manual runs only

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java

- minor error improvement since it was quite hard to find which template we were looking for from kibana

CB-7291 we should log what BP we can't find.

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentStatus.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/environment/EnvironmentOperationChecker.java

CB-6016 SDX creation should fail in case of the environment is in delete in progress phase

CB-6016 SDX creation should fail in case of the environment is in delete in progress phase

---

template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.2.json

CB-7290 - No services listed for 7.2.0 Datahub blueprints

CB-7290 - No services listed for 7.2.0 Datahub blueprints

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/AutoscaleRecommendation.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/PlatformRecommendation.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/ResizeRecommendation.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/responses/RecommendationV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/connector/responses/AutoscaleRecommendationV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/connector/responses/ResizeRecommendationV4Response.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/clustertemplate/PlatformRecommendationToPlatformRecommendationV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/BlackListedDownScaleRole.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/BlackListedLoadBasedAutoscaleRole.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/BlackListedTimeBasedAutoscaleRole.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java
template-manager-cmtemplate/src/test/resources/input/de-ha.bp
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/processor/BlueprintTextProcessor.java

1. Added recommendations for auto-scalability and manual scalability.
2. Implemented both CM service based recommendations and fallback recommendations.

DISTX-421 DISTX-427 Recommendation for host groups' scalability

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentNetworkTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/NewNetworkWithNoInternetEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml

CB-5976 Test for 'no network' cluster installation

---

core/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/cdp-sdx-721.bp
core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha-721.bp
datalake/src/main/resources/application.yml
datalake/src/main/resources/runtime/7.2.1/aws/light_duty.json
datalake/src/main/resources/runtime/7.2.1/aws/medium_duty_ha.json
datalake/src/main/resources/runtime/7.2.1/azure/light_duty.json
datalake/src/main/resources/runtime/7.2.1/azure/medium_duty_ha.json
datalake/src/main/resources/runtime/7.2.1/mock/light_duty.json
datalake/src/main/resources/runtime/7.2.1/yarn/light_duty.json
datalake/src/main/resources/runtime/7.2.1/yarn/medium_duty_ha.json

https://cloudera.atlassian.net/wiki/spaces/ENG/pages/596149312/How+to+introduce+a+new+Cloudera+Runtime+version

CB-7352 Introduce 7.2.1 SDX templates

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

testListClusterTemplate test description was different what the test actually is doing 
Closes 7354

CB-7354 fixing test description

---

freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/CreateFreeIpaRequestToStackConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/AuthUserKeys.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CredentialCreateTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvironmentCreateTest.java

- mock tests (with real UMS) for Freeipa
- possibility to create freeipa with machineuser

CB-7104 Add resource based Auth for Freeipa api - tests

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/Cluster.java
core-model/src/test/java/com/sequenceiq/cloudbreak/domain/stack/cluster/ClusterTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/resources/schema/app/20200608105123_CB-7326_extend_Cluster_entity_with_keystore_and_truststore_pwd_fields.sql

CB-7326 Keystore and truststore passwords are the same on a CDP Datahub deployment

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/StackDecorator.java
redbeams/src/main/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverter.java

CB-7247 - External DB status lookup failed. javax.ws.rs.NotFoundException on RDS deletion

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ExistingResourceByCrnOrNameRestUrlParser.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/ProvisionerService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/ProvisionerServiceTest.java

CB-7008 Sdx got attached to long ago terminated cb cluster

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/AutoscaleV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AutoscaleV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/clustertemplate/AutoscaleRecommendationToAutoscaleRecommendationV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java

1. Autoscale needs a recommendation endpoint for the backend verification in periscope.
2. Tested by changing the auth and setting the workspace and blueprint manually. 
Depends on PR #8100 so sent to that PRs branch instead of master.

DISTX-421 Separate endpoint for autoscale recommendation

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitService.java

CB-7402 WaitService fails to throw exception when FAILED status too fast

---

integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupWaitUtil.java

CB-7452 Fix API Cleanup App in case of resource has been removed

---

integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java

CB-7451 Fix API Cleanup App Exit in case of exception

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/environment/EnvironmentTerminationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaTerminationChecker.java

@Bajzathd and @afarsang please review

CB-7277 PR test fails intermittently with 404 when waiting for archived

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/ExternalDatabaseService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/DatabaseServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/database/RedbeamsDatabaseServerTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RedbeamsDatabaseServerTest.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/AllocateDatabaseServerV4Request.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java
redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java
redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseServerConfig.java
redbeams/src/main/java/com/sequenceiq/redbeams/repository/DatabaseServerConfigRepository.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsCreationService.java
redbeams/src/main/resources/schema/app/20200610094900_CB-6774_Add_cluster_crn_to_database_server_config.sql
redbeams/src/test/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4ControllerTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/stack/RedbeamsCreationServiceTest.java

CB-6774 Make redbeams database creation idempotent

CB-6774 Make redbeams database creation idempotent

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/authorization/UtilAuthorizationService.java

For new authorization we will return true for old permissions, possibly more changes will come later in this util endpoint.

CB-7463 Show/Hide logic refactor for new Rights

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentStartStopTest.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupWaitUtil.java

CB-7452 Fix API Cleanup App in case of checking DELETE_FAILED

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java

CB-7182 Fix Environment Await with Polling

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup

CB-7496 don't use http_proxy for cloud storages

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/v1/AlertEndpoint.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/validator/DistroXAutoscaleRequestValidator.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/AlertType.java
autoscale-api/src/main/java/com/sequenceiq/periscope/common/MessageCode.java
autoscale-api/src/main/resources/messages/messages.properties
autoscale-api/src/test/java/com/sequenceiq/periscope/api/endpoint/validator/DistroXAutoscaleRequestValidatorTest.java
autoscale/src/main/java/com/sequenceiq/periscope/cache/AutoscaleRecommendationCache.java
autoscale/src/main/java/com/sequenceiq/periscope/controller/AlertController.java
autoscale/src/main/java/com/sequenceiq/periscope/model/yarn/YarnScalingServiceV1Response.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/CloudbreakCommunicator.java
autoscale/src/main/java/com/sequenceiq/periscope/service/AutoscaleRecommendationService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java
autoscale/src/test/java/com/sequenceiq/periscope/controller/AlertControllerTest.java
autoscale/src/test/java/com/sequenceiq/periscope/endpointtests/DistroXAutoScaleClusterV1EndpointTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluatorTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/connector/responses/AutoscaleRecommendationV4Response.java

Integrate with autoscale hostgroup recommendations.
Integrate with MessageSource messages.
Optimize Yarn Response Unmarshalling
Closes #DISTX-480
Closes #DISTX-496
Closes #DISTX-498

DISTX-480 Integrate with autoscale hostgroup recommendations

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ProcessAutoRestartInjector.java

CB-7502 auto-restart Yarn queue manager

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/ScaleRecommendation.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/BlueprintUtilV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/connector/responses/ScaleRecommendationV4Response.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/clustertemplate/ScaleRecommendationToScaleRecommendationV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java

1. Platform recommendation endpoint has lots of details.
2. So creating a new api endpoint just to deal with scaling recommendations.

DISTX-421 Separate endpoint for autoscale and resize recommendation

---

flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java
flow/src/main/java/com/sequenceiq/flow/core/chain/FlowChains.java
flow/src/test/java/com/sequenceiq/flow/core/Flow2HandlerTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RecipeClusterTest.java

Revert "CB-7294 FlowChain ends before next flow actually executed"

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/stack/YarnStackV4Parameters.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/YarnDistroXV1Parameters.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXParameterConverter.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/EnvironmentNetworkYarnParams.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/YarnEnvironmentNetworkValidator.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/YarnNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/dto/YarnParams.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/YarnEnvironmentNetworkConverter.java
environment/src/main/resources/schema/app/20200618095432_CB-6756_add_yarn_lifetime.sql
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/YarnEnvironmentNetworkValidatorTest.java

CB-6756 Configurable lifetime for ycloud deployments

CB-6756 Configurable lifetime for ycloud deployments

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/AlertType.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/TimeAlertRequest.java
autoscale-api/src/main/resources/messages/messages.properties
autoscale/src/main/java/com/sequenceiq/periscope/domain/BaseAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/ScalingPolicy.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/CronTimeEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/service/DateService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/security/SecurityConfigService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/security/TlsHttpClientConfigurationService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/security/TlsSecurityService.java
autoscale/src/main/resources/logback.xml

Optimize Logging Messages, Log Levels and Validations
Closes #DISTX-496

DISTX-496-OptimizeLoggingMessages

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java

In case of freeipa usersync and setPassword, environments list should not be empty.
Need to wait for UI and CLI change.

CB-7225 Usersync and setpassword APIs should authorized in case of empty list too

---

core/src/main/java/com/sequenceiq/cloudbreak/service/ServiceEndpointCollector.java
core/src/test/java/com/sequenceiq/cloudbreak/service/OpdbServiceEndpointCollectorTest.java

Add `-api` to HBASEJARS URL. Modify unit tests to verify /hbase/jars and /avatica endpoints.

CB-7553 Change HBASEJARS to use cdp-proxy-api

---

core/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/cdp-flink-ha-721.bp
core/src/main/resources/defaults/clustertemplates/aws/aws-flink-light-ha-721.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

CB-7587 Add Flink default cluster templates

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParametersConsts.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCloudResourceService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTerminationHelperService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureComputeResourceService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureAttachmentResourceBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/service/AzureResourceNameService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnectorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilderTest.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/LaunchStackHandler.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/service/CloudbreakResourceNameService.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverterTest.java

CB-6013 Azure cluster creation fails due to interruption during subscription

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh

Add an if/else branch to attempt an S3 upload using `aws:kms` instead of `AES` encryption.
Tested two ways. One test was uploading to a standard S3 bucket, which used the AES encrypted s3 upload.
To test KMS encryption, I created a new bucket and applied the following policy:
```yml
{
"Version": "2012-10-17",
"Id": "PutObjPolicy",
"Statement": [
{
"Sid": "DenySSE-S3",
"Effect": "Deny",
"Principal": "*",
"Action": "s3:PutObject",
"Resource": "arn:aws:s3:::bderriso-test-aws-kms-upload/*",
"Condition": {
"StringEquals": {
"s3:x-amz-server-side-encryption": "AES256"
}
}
}
]
}
```
Then confirmed upload works and logs contain ouput indicating that upload fell back to `aws:kms`.
Salt output:
```
stdout:
Logs at /var/log/dl_postgres_backup.log
try to upload with aws:kms encryption
try to upload …
```

CB-7508 Attempt to use KMS for SSE when AES fails.

---

core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/service/template/ClusterTemplateService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/AbstractFreeIPAAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIPAStartAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIPAStopAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXCreateAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXScaleAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXStartAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXStopAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/AbstractEnvironmentAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentCreateAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentDeleteByNameAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentStartAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentStopAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/stack/StackCreateAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/stack/StackScalePostAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractEnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractFreeIPATestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterStopStartTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RecipeClusterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/clouderamanager/CMDownscaleWithHttp500ResponsesTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/clouderamanager/CMStartStopWithHttp500ResponsesTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/clouderamanager/CMUpscaleWithHttp500ResponsesTest.java

CB-7182 IT fails intermittently

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureVirtualMachineService.java

- The CloudExceptions from Azure SDK were swallowed by our logic and the affected instances were put into UNKNOWN state. A new debug log has been introduced there for easier debug from the logs in the future.
- Also the VirtualMachine state updater logic needed to be fixed, not to mark the instances as terminated when previous logic marked them UNKNOWN.

CB-7483 do not swallow exceptions from Azure SDK during vm list

---

core/src/main/java/com/sequenceiq/cloudbreak/service/environment/tag/AccountTagClientService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/environment/telemetry/AccountTelemetryClientService.java
environment-common/src/main/java/com/sequenceiq/cloudbreak/service/proxy/ProxyConfigDtoService.java
environment/src/main/java/com/sequenceiq/environment/tags/service/AccountTagService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/userdata/UserDataService.java
integration-test/Makefile
integration-test/scripts/config-ums.sh
integration-test/scripts/create-cloudbreak-context.sh
integration-test/scripts/docker-compose.sh
integration-test/scripts/fetch-secrets.sh
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DatalakeDatahubCreateAuthTest.java
integration-test/src/main/resources/pg_stats/pg_query_stat_template.html
integration-test/src/main/resources/testsuites/v4/mock/all-authz-mock-package.yaml
integration-test/src/main/resources/testsuites/v4/mock/minimal-authz.yaml
redbeams/src/main/java/com/sequenceiq/redbeams/service/AccountTagService.java

- job to test the added behaviour:
http://ci-cloudbreak.eng.hortonworks.com/job/cloudbreak-real-ums-test
- less test output on generating docker stats
- later on might add a label similar to aws-e2e, but now the job is manual

CB-7106 making ums test job possible, less logging in test job output

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchService.java

increase throttle retries for cloudformation calls
Closes 7614

CB-7614 increase throttle retries for cloudformation calls

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazConfigProviderTest.java

Moving RAZ deployment to main node
Closes https://jira.cloudera.com/browse/CB-7635

[CB-7635] Moving RAZ deployment to main node

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/start/handler/StartFreeIpaHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/stop/handler/StopFreeIpaHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaService.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/start/handler/StartFreeIpaHandlerTest.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/stop/handler/StopFreeIpaHandlerTest.java

CB-7464 - Env is startable/stoppable but it does not exists on provider side

CB-7464 - Env is startable/stoppable but it does not exists on provider side

---

environment/src/main/java/com/sequenceiq/environment/proxy/v1/controller/ProxyController.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvironmentCreateTest.java

CB-7636 test action name changed, ProxyController changed to tenantAware

---

core/src/main/java/com/sequenceiq/cloudbreak/service/environment/telemetry/AccountTelemetryClientService.java
environment-common/src/main/java/com/sequenceiq/cloudbreak/service/proxy/ProxyConfigDtoService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/AccountTagService.java

- we are reverting every internalAPI calls
- it was spread around multiple commit, hence the half assed reverts

CB-7698 Internal call revert

---

integration-test/src/main/resources/application.yml

@lnardai or @akanto please review.

CB-7227 Move Azure E2E to the new network

---

integration-test/src/main/resources/application.yml

@akanto or @lnardai please review

Merge rc-2.20 to CB-2.24.0

---

core/src/main/resources/defaults/blueprints/cdp-sdx-721.bp

Modified lite duty blueprints to suppress service level warnings
Closes https://jira.cloudera.com/browse/CB-7630

[CB-7630] Modified lite duty blueprints to suppress service level warnings

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java

enable retry on all aws client
previously was only on cloudformation client
Closes cb-7614

CB-7614 enable retry on all aws client

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java

1. We might be releasing autoscale recommendation from either 7.2.0 or 7.2.1
2. This is a placeholder RFC for that.
3. We can discuss on exact version here or by other means.

DISTX-421 Add a version checker for autoscale recommendation

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageComparator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/LatestDefaultImageUuidProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceDefaultTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageComparatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/LatestDefaultImageUuidProviderTest.java

CB-4910 Identify latest CDH/CM images for a given CB version.

CB-4910 Identify latest CDH/CM images for a given CB version

---

environment/src/main/java/com/sequenceiq/environment/parameters/validation/validators/parameter/AzureParameterValidator.java
environment/src/test/java/com/sequenceiq/environment/parameters/validation/validators/AzureParameterValidatorTest.java
integration-test/src/main/java/com/sequenceiq/it/TestParameter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ResourceGroupTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/config/azure/ResourceGroupProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/resources/application.yml

With this change the single RG parameters are introduced but it should not change anything yet.

CB-6588 [ASRG] e2e test

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/TimeMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java

Time Monitor should only monitor clusters which have timeAlerts defined.
Closes #DISTX-504

DISTX-504 Optimize Schedule Based Autoscaling

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/v1/HistoryEndpoint.java
autoscale-api/src/main/java/com/sequenceiq/periscope/common/MessageCode.java
autoscale-api/src/main/java/com/sequenceiq/periscope/doc/ApiDescription.java
autoscale-api/src/main/resources/messages/messages.properties
autoscale/src/main/java/com/sequenceiq/periscope/controller/HistoryController.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/History.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/HistoryRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/HistoryService.java
autoscale/src/test/java/com/sequenceiq/periscope/controller/HistoryControllerTest.java

1. Support autoscale history retrieval by cluster name.
2. Support autoscale history count for limiting number of records.
Closes #DISTX-478

DISTX-478-Enhancements

---

core/src/main/java/com/sequenceiq/cloudbreak/service/audit/AuditEventService.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/StructuredEventRepository.java

Customer is not able to download audit events zip from UI (timeout after 2 mins). I introduced a parameter to limit the max returned structured events.

ENGESC-2904 limit returned audit events to 10000

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Print to stderr when there are problems.
Capture log output by redirecting to the LOGFILE.
Tested by running backup/restore procedure on a Data Lake.
When restoring, I did not stop the running hive services, so PostgreSQL fails the `drop` statement.
Got Salt output that looks like the following:
```
ID: restore_postgresql_db
Function: cmd.run
Name: /opt/salt/scripts/restore_db.sh AWS s3://eng-sdx-daily-datalake/bderriso-cranston/data/backup1 dbsvr-a40ba31f-6ff5-4323-8ef2-d758d8129ace.czhkrnzwtcwb.us-west-2.rds.amazonaws.com 5432 ucklnfysen
Result: False
Comment: Command "/opt/salt/scripts/restore_db.sh AWS s3://eng-sdx-daily-datalake/bderriso-cranston/data/backup1 dbsvr-a40ba31f-6ff5-4323-8ef2-d758d8129ace.czhkrnzwtcwb.us-west-2.rds.amazonaws.com 5432 ucklnfysen" run
Started: …
```

CB-7701: Capture failures and log them when dropping and creating database for restore.

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/image/ImageInfoV4Response.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentVersionProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeOptionsResponseFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeOptionsResponseFactoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeServiceTest.java

CB-7378: add component versions for os upgrade response

---

autoscale/src/main/java/com/sequenceiq/periscope/domain/BaseAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/MetricAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/ScalingPolicy.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/MetricEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/service/AlertService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ScalingService.java

@keyki or @biharitomi pls review

ENGESC-3007 Logging improvement for alert and scalingpolicy add / remove operations

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java
environment/src/main/java/com/sequenceiq/environment/proxy/service/ProxyConfigService.java

@oleewere or @keyki pls review

CB-7774 using proxyConfig crn resourcetype for proxies

---

core/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/cdp-flink-light-721.bp
core/src/main/resources/defaults/clustertemplates/aws/aws-flink-light-721.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flink-light-721.json

CB-7920 Fix Flink blueprint and template naming

---

mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/audit/MockAuditLogService.java
mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/auth/MockAuthorizationService.java
mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/auth/MockCrnService.java
mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/auth/MockGroupManagementService.java
mock-caas/src/main/java/com/sequenceiq/caas/grpc/service/auth/MockUserManagementService.java

We got timeouts on service side and we need more logs for debugging

CB-7867 add some more log to mock

---

core/src/main/resources/defaults/blueprints/cdp-opdb-721.bp
core/src/test/java/com/sequenceiq/cloudbreak/service/OpdbServiceEndpointCollectorTest.java
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2

Add HBase REST to OpDB blueprint
Remove WEBHBASE from cdp-proxy topology
Extend OpdbServiceEndpointCollectorTest with HBASEREST

DISTX-453 Expose HBase REST API in the OpDB DataHub

---

common-model/src/main/java/com/sequenceiq/common/model/CloudStorageCdpService.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/flink/FlinkConstants.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/flink/FlinkRoleConfigProvider.java
template-manager-cmtemplate/src/main/resources/definitions/cm-cloud-storage-location-specification.json
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/flink/FlinkCloudStorageConfigProviderTest.java
template-manager-cmtemplate/src/test/resources/input/flink.bp

Flink Cloud Storage Integration
Closes #CB-7773

CB-7773 Flink Cloud Storage Integration

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResources.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResourcesTest.java
cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/platform/GetPlatformEncryptionKeysRequest.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/GetPlatformEncryptionKeysHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRequestValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudParameterService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackAwsEncryptionValidatorTest.java

[This is a fix also for ENGESC-2931](https://jira.cloudera.com/browse/ENGESC-2931)

CB-7819 eliminate listing all the encryption keys at cluster creation validation

---

environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentRequest.java

CB-7807 added back the deprecated regions field

---

datalake/src/test/java/com/sequenceiq/datalake/service/sdx/dr/SdxDatabaseDrServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidatorTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltConnector.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltFileUpload.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltUploadWithPermission.java
orchestrator-salt/src/main/resources/salt/salt/recipes/post-cloudera-manager-start.sls
orchestrator-salt/src/main/resources/salt/salt/recipes/post-cluster-install.sls
orchestrator-salt/src/main/resources/salt/salt/recipes/pre-cloudera-manager-start.sls
orchestrator-salt/src/main/resources/salt/salt/recipes/pre-termination.sls

recipes access rights only for root group in /salt/srv as well in /opt/

CB-7853 Too broad access rights to recipes

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/validator/DistroXAutoscaleRequestValidator.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/ScalingStatus.java
autoscale-api/src/main/java/com/sequenceiq/periscope/common/MessageCode.java
autoscale-api/src/main/resources/messages/messages.properties
autoscale-api/src/test/java/com/sequenceiq/periscope/api/endpoint/validator/DistroXAutoscaleRequestValidatorTest.java
autoscale/src/main/java/com/sequenceiq/periscope/controller/DistroXAutoScaleClusterV1Controller.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/CronTimeEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingHandler.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java
autoscale/src/main/java/com/sequenceiq/periscope/service/DateService.java
autoscale/src/main/resources/logback.xml
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ScalingHandlerTest.java
autoscale/src/test/java/com/sequenceiq/periscope/service/DateServiceTest.java

Introduce History Event for Cluster Autoscale Config Change.
Introduce History Event for Schedule-Based Autoscaling.
Additonal Validations for Autoscaling Requests.

DISTX-478-Introduce Config Change History Event

---

cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnPlatformResources.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java

CB-7958 disable location based region validation for YARN envs

---

template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/GeneralClusterConfigsView.java

CB-7952 Add cmUserName and cmPassword to the recipe template parameters

---

datalake/src/main/java/com/sequenceiq/datalake/cm/ClouderaManagerRangerUtil.java
datalake/src/test/java/com/sequenceiq/datalake/cm/ClouderaManagerRangerUtilTest.java

After setting role configs related to identity mapping, we no
longer trigger refresh when the values haven't changed (by
checking whether CM reports whether a refresh is required).

CDPCP-1941. Only trigger user sync role refresh when needed

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java

Add logs around the major user sync tasks so that we can
easily determine duration of these tasks from the logs.

CDPCP-2598 Add logs around major user sync tasks

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceActionModel.java
authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceActionType.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/UmsAccountAuthorizationService.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/UmsResourceAuthorizationService.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/UmsRightProvider.java
authorization-common/src/main/resources/actions.json
authorization-common/src/test/java/com/sequenceiq/authorization/service/UmsAccountAuthorizationServiceTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/UmsResourceAuthorizationServiceTest.java

CB-7985 Remove resource dependent/independent logic from authz framework

---

authorization-common/README.md

CB-7985 update authz readme

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/datahub/DataHubClusterDeletionHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/freeipa/FreeIpaDeletionHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/sdx/DataLakeClustersDeleteHandler.java

We would like to make sure that the force does not cause problem in our services until CB-8013 and CB-8017 are not implented

CB-8017 Remove force deletion in case of DL/FreeIPA/DH

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/dns/model/AddDnsZoneForSubnetsResponse.java

CB-8041 fixing the broken swagger diff

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/dns/model/AddDnsZoneForSubnetsResponse.java

Fixing the broken swagger diff

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

Added code changes to have a separate configuration to control the number of retries on failure while performing database backup/restore operations.
Made code change in local development environment and tested them.

CB-7742: Reduce retry for backup/restore operations

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeImageFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentBuildNumberComparator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePermissionProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeImageFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentBuildNumberComparatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePermissionProviderTest.java

CB-7741: Allow upgrade with same runtime and different GBN

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXShowBlueprintAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/DistroXTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterCreationTest.java

CB-7770 added test for show blueprint

---

redbeams/src/main/java/com/sequenceiq/redbeams/aspect/ControllerLogContextAspects.java

CB-7777 Fix redbeams controller logging

---

cloud-azure/src/main/resources/definitions/azure-enabled-regions.json
cloud-azure/src/test/resources/json/azure-regions-test.json

CB-7875: remove UAE Central from azure region list

---

auth-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/usermanagement/UserManagementGrpc.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/config/UmsClientConfig.java
auth-connector/src/main/proto/usermanagement.proto
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClientTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java

CDPCP-2663

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java

CB-7836: Configure Azure client to create V2 type storage account

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/EnvDeleteActions.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/ClusterDefinitionDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/IdBrokerMappingsDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/NetworkDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/PrerequisitesDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/PublicKeyDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/RdbmsDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/S3GuardTableDeleteHandler.java
flow/src/main/java/com/sequenceiq/flow/core/AbstractAction.java

Correct payload in EnvDeleteActions for failure.
Side fix: logging strings in deletion handlers

CB-7994 Add warn log for empty payload in AbstractAction

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/InternalCrnBuilder.java

CB-8072 user sync apis don't work with internal actor

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/ScalingHandlerUtil.java

CB-7923 add logs and sync block to cooldown's calculation

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformResources.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/resourcegroup/CloudResourceGroup.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/resourcegroup/CloudResourceGroups.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResources.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformResources.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformResources.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockPlatformResources.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackPlatformResources.java
cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/platform/GetPlatformResourceGroupsRequest.java
cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/platform/GetPlatformResourceGroupsResult.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/GetPlatformResourceGroupsHandler.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/service/CloudParameterService.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnPlatformResources.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/PlatformResourceEndpoint.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/PlatformResourceModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/model/PlatformResourceGroupResponse.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/model/PlatformResourceGroupsResponse.java
environment/src/main/java/com/sequenceiq/environment/platformresource/PlatformParameterService.java
environment/src/main/java/com/sequenceiq/environment/platformresource/v1/PlatformResourceController.java

A new endpoint is introduced to get Resource groups list from Azure.
In case of other providers it will produce an empty list.

CB-8065 create endpoint to get all resource groups for UI

---

core/src/main/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelServiceTest.java
template-manager-cmtemplate/src/main/resources/cloudera-manager-template/service-definitions-minimal.json

Added flink component the service definition now flink is also checked. Also added a safety feature which is if we dont find the component in the json then we dont filter parcels because we should know that the given components owned by which parcel

Parcel validation enhancement

---

integration-test/Makefile
integration-test/scripts/swagger-check.sh

CB-8057 adding a swagger placeholder

---

common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/AbstractMetricService.java
common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/type/MetricTag.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/CheckImageAction.java
core/src/main/java/com/sequenceiq/cloudbreak/service/metrics/CloudbreakMetricService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/metrics/MetricType.java

CB-7782 Create image copy performance and metrics and alerts

---

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentOpDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java

CB-7930 Verify credential on environment level

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResources.java
cloud-aws/src/main/resources/definitions/aws-enabled-availability-zones.json
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResourcesTest.java
cloud-azure/src/main/resources/definitions/azure-enabled-regions.json

CB-7784 Remove Switzerland West from Azure region list
CB-7784 Unify AWS and Azure region/az region filtering: Change AWS region and availability zone deny list to allow list, similar to how Azure works.

CB-7784 Remove Switzerland West from Azure region list

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackV4RequestValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/environment/PlatformResourceClientService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackAwsEncryptionValidatorTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/PlatformResourceEndpoint.java
environment/src/main/java/com/sequenceiq/environment/platformresource/PlatformParameterService.java
environment/src/main/java/com/sequenceiq/environment/platformresource/v1/PlatformResourceController.java
environment/src/test/java/com/sequenceiq/environment/platformresource/PlatformParameterServiceTest.java
environment/src/test/java/com/sequenceiq/environment/platformresource/v1/PlatformResourceControllerTest.java

CB-7777 PlatformResources should authorized on environment

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java

Even if redbeams template deployment fails some resources may have been created (e.g. network service endpoint fails after successful db server deploy). However, in case of failure no resources are saved into redbeams db, hence no resource is deleted from azure cloud provider during termination, leading to resource leakage when using single resource group for azure.
Tested with 3 scenarios: 1) happy path, 2) when only dbserver was created and 3) no resource was created in cloud.

CB-8168 [ASRG] resource leakage when redbeams provisioning error

---

authorization-common/README.md

CB-8136 add note to authz readme

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/cache/UmsAuthorizationEntitlementRegisteredCache.java

mow-dev and mow-int are very slow... this can be a cause

CB-8201 Missing cache for GrpcUmsClient.isAuthorizationEntitlementRegistered

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/diagnostics/DiagnosticsCollectionValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/diagnostics/DiagnosticsCollectionValidatorTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/validation/diagnostics/DiagnosticsCollectionValidator.java
datalake/src/test/java/com/sequenceiq/datalake/service/validation/diagnostics/DiagnosticsCollectionValidatorTest.java

CB-8199 - added unit tests for DiagnosticsCollectionValidators

---

core/src/main/resources/application.yml

CB-7604 Approve/enable the D8s v3 instance type

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ClusterTemplateV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/RecipesV4Controller.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/CredentialV1Controller.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java
environment/src/test/java/com/sequenceiq/environment/service/integration/CredentialAuthorizationIntegrationTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java
redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/database/DatabaseV4Controller.java
redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java

CB-8046 Remove filtering based on permissions

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/RemoveHostsHandler.java

Fix the case where the FreeIPA management service database has the
instancemetadata.discoveryfqdn null for the node which is being
repaired.
This was tested on a local deployment of cloudbreak.

CB-8234: Fix downscale repair when FQDN is missing

---

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverter.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverterTest.java

remove preferedSubnetId because that can causee performance problems and we would like to avoid that.

CB-8232 remove preferedSubnetId in case of env list

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/StackRepoDetails.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeImageFilter.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeImageFilterTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/main/resources/application.yml
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java
integration-test/src/main/resources/application.yml
scripts/build-dev.sh

merge 2.27 to master

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleServiceTest.java

- the issue is sporadic
- it is a concurrency issue, since even when we start debug CB the issue goes away
The solution is to reorganise the Amazon API calls, to detach and terminate the instances first and change the size of the ASG after that.

CB-8222 After detach instances AWS fails to update desired count of ASG

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/config/UmsConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UmsClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/AssignResourceRequest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/AssignUmsRoleAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/Actor.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/CloudbreakUser.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/CloudbreakUserCache.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assign/Assignable.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/EnvironmentTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractEnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ums/UmsTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CreateDhWithDatahubCreator.java

- added example of assigning resource roles
- will add more testcases and datahub creation usecase

CB-7930 adding UMSClient to tests so we can assign resourceRoles

---

core/src/main/java/com/sequenceiq/cloudbreak/service/metrics/CloudbreakMetricService.java

CB-8306 Registering the same metric with different set of tags

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToTemplatePreparationObjectConverter.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazBaseConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatahubConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatalakeConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatahubConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatalakeConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/DatalakeView.java

CB-7963 CB work for deploying RAZ to Datahub cluster

---

datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeControllerTest.java

CB-8340 fixed broken master

---

client-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/retry/ApiExceptionRetryPolicy.java

CM took too much time processing a request which caused gateway
timeout.
This timeout showed up as socket timeout on java side and the request
wasn't retried. Additional logs are added in this commit to help us
figure out why is there no retry and we can handle those also.

CB-8341 Enrich `ApiExceptionRetryPolicy` with log

---

core/src/main/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ManifestStatus.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelServiceTest.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/generate_agent_tokens.sh.j2

Merge 227 (pull has been created for IT MOCK test only)

---

datalake/src/main/java/com/sequenceiq/datalake/configuration/CDPConfigService.java
datalake/src/test/java/com/sequenceiq/datalake/configuration/CDPConfigTest.java

CB-8273 Reverse the order of runtimes

---

cloud-azure/src/main/resources/definitions/azure-credential.json

CB-8322 - make sure credential response contains azure app id

CB-8322 - make sure credential response contains azure app id

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackToStackV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/SharedServiceConfigProvider.java

CB-8302 - Add additional logging around DH - DL attaching

CB-8302 - Add additional logging around DH - DL attaching

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/LoadAlertResponse.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/TimeAlertResponse.java
autoscale-api/src/main/java/com/sequenceiq/periscope/doc/ApiDescription.java
autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java
autoscale/src/main/java/com/sequenceiq/periscope/converter/LoadAlertResponseConverter.java
autoscale/src/main/java/com/sequenceiq/periscope/converter/TimeAlertResponseConverter.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/BaseAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/service/AlertService.java
autoscale/src/main/resources/schema/app/20200807074304_DISTX-526_crn_for_alerts.sql
common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java

Introduce CRN for Autoscaling Config

DISTX-526 Crn for Autoscaling Config

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/main/java/com/sequenceiq/cloudbreak/util/NotAllowedStatusUpdate.java

CB-8387 Improve error message when datahub/datalake stop is not possible

---

core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/NifiRegistryRdsConfigProvider.java

CB-8029 adding back the missing RDS provider for nifi registry

---

environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/chain/EnvDeleteClustersFlowEventChainFactory.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentDeletionService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentDeleteByNameAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentDeleteMultipleByNamesAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/EnvironmentTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentChildTest.java

- Extend environment cascading delete to delete child environments
- Set environment delete cascade flag to false by default

CB-7957 Delete child envs when deleting parent with cascade

---

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/ClusterToClusterDetailsConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/RdsConfigToRdsDetailsConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/LegacyStructuredEventDBService.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/converter/RdsConfigToRdsDetailsConverterTest.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/BlueprintDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/ClusterDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/FlowDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/InstanceGroupDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/LdapDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/LdapNotificationDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/NotificationDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/OperationDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/RdsDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/RdsNotificationDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/SecurityGroupDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/SecurityRuleDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StackDetails.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredEventContainer.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredFlowEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredNotificationEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredRestCallEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/VolumeDetails.java

Fixed version inconsistencies, deleted ambari references, added tunnel type field to show if CCM is used or not, fixed database type always showing "embedded" and added more detailed information about the used databases.

CB-7799 Fix missing information in Structured Events

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/BackupRestoreSaltConfigGenerator.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/BackupRestoreSaltConfigGeneratorTest.java
orchestrator-salt/src/main/resources/salt/pillar/postgresql/disaster_recovery.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/backup.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/restore.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Closes [CB-8278](https://jira.cloudera.com/browse/CB-8278)
* Restore db using HDFS cli to transfer backups. Fix styling.
* Hack together a fix for embedded database backups.
* Adjust url construction and region passing to account for HDFS cli usage.
* Fix style issues.
Tested by triggering backup and restore using HTTP requests and against external and embedded database.
**Ranger admin group changes were merged in as well** after which I retested by triggering via HTTP requests.

CB-8278: Backup using hdfs cli

---

integration-test/Makefile
integration-test/docker-compose_template.yml
integration-test/scripts/check-results.sh
integration-test/scripts/docker-build.sh
integration-test/scripts/download-cbd.sh
integration-test/src/main/resources/gen/generate-mock-keystore.sh
performance-test/perftest.sh

CB-8465 update thirdparty images to use the private registry

---

autoscale-api/src/main/java/com/sequenceiq/periscope/common/MessageCode.java
autoscale-api/src/main/resources/messages/messages.properties
autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java
autoscale/src/main/java/com/sequenceiq/periscope/controller/DistroXAutoScaleClusterV1Controller.java
autoscale/src/main/java/com/sequenceiq/periscope/init/DefaultSubscriptionService.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java
autoscale/src/main/java/com/sequenceiq/periscope/notification/HttpNotificationSender.java
autoscale/src/main/java/com/sequenceiq/periscope/notification/Notification.java
autoscale/src/main/java/com/sequenceiq/periscope/notification/NotificationType.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/SubscriptionRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/subscription/SubscriptionService.java
autoscale/src/main/resources/application-test.yml
autoscale/src/main/resources/application.yml
autoscale/src/test/java/com/sequenceiq/periscope/subscription/SubscriptionServiceTest.java

Periscope should send Autoscaling Config Update\History Event update notifications to UI app.

DISTX-529 Autoscaling Notification

---

environment/src/main/resources/schema/app/20200714110940_CB-7523_add_credential_type.sql
environment/src/main/resources/schema/app/20200814084920_CB-8421_missing_default_value_for_credential_type.sql

CB-8421 missing default value for credential type

---

core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbServerConfigurer.java

CB-8029 fixed the missing connection driver issue

---

core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha-722.bp

Added a custom template to shared resources with an additional ranger service to the gateway node.

[CB-8335] Added ranger to medium duty blueprint gateway

---

core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbServerConfigurer.java

Merge cb 2.28.0 2

---

core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbServerConfigurer.java

Merge master 1

---

environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialService.java
environment/src/main/java/com/sequenceiq/environment/platformresource/PlatformParameterService.java
environment/src/test/java/com/sequenceiq/environment/platformresource/PlatformParameterServiceTest.java

Audit credential does not work with the new Authz changes. This PR fixing the logic.

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java

CB-6775 - Disable repair for not fixed hostnames

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/instance/AzureInstanceGroupParameters.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformParameters.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/CreateFreeIpaRequestToStackConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProvider.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProviderTest.java

Create Availability Sets for FreeIPA instances with reasonable defaults

CB-8161 - FreeIPA instances are not in Availability Set on Azure

---

datalake/src/main/java/com/sequenceiq/datalake/cm/ClouderaManagerRangerUtil.java
datalake/src/test/java/com/sequenceiq/datalake/cm/ClouderaManagerRangerUtilTest.java

The previous behavior for syncing azure oids into CM was to only
trigger role refresh if CM reported the configs to be stale. This
does not always work as expected because the staleness status that
CM reports is eventually consistent.
To fix this, instead of relying on staleness check we only set
the configs if they are different than the existing configs. Under
rare circumstances we still need to fallback on checking staleness
status (as explained in the code comment).

CDPCP-2673. Fix role refresh on cloud identity sync

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryVolumeConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryRoleConfigProviderTest.java

CB-8498 Nifi registry DB must be role level config and not service level

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsAutoScalingService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/BackoffCancellablePollingStrategy.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/BackoffDelayStrategy.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/CustomAmazonWaiterProvider.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsLaunchTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsRepairTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsAutoScalingServiceTest.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterUpscaleDownscaleTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryVolumeConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/nifiregistry/NifiRegistryRoleConfigProviderTest.java

Merge 227 rdoktorics 1

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/security/internal/InitiatorUserCrn.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/PermissionCheckService.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/PermissionCheckServiceTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4EventRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ExistingResourceEventRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ExistingResourceRestUrlParser.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4RestUrlParser.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/RestUrlParserTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/ProvisionerService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRepairService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxDatabaseDrService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/start/SdxStartService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/stop/SdxStopService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/ProvisionerServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxRepairServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/start/SdxStartServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/stop/SdxStopServiceTest.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/sdx/SdxDeleteService.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/sdx/SdxDeleteServiceTest.java

CB-8480 internal calls broke tags and audit

---

core/src/main/resources/defaults/blueprints/cdp-flow-management-710.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-720.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-721.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-722.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-small-710.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-small-720.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-small-721.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-small-722.bp

CFM-1427 DH NiFi template - use zookeeper instead of zookeeper-BASE

---

environment/src/main/java/com/sequenceiq/environment/environment/validation/cloudstorage/EnvironmentLogStorageLocationValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/cloudstorage/EnvironmentLogStorageLocationValidatorTest.java

CB-8474. Allow Telemetry with no cloud storage logging object.

---

cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/logger/LogContextAspects.java

ENGESC-3681 fix CRN field in AWS module's MDC log context

---

core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-ha-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-dataengineering-spark3-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-datamart-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-dde-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flink-light-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flow-management-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flow-management-small-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-opdb-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-rt-datamart-722.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

CB-8528 Add missing 7.2.2 datahub templates for Azure

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsAutoScalingService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsAutoScalingServiceTest.java

CB-8513 skip check of last activity when hostgroup has 0 as cardinality

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerLdapService.java
core/src/main/resources/application.yml

CB-8357 - added global ROLE_LIMITED_CLUSTER_ADMIN for CM users

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-722.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-722.bp

CB-8535 Adding Sqoop to the Data Engineering template
Evidence: https://cloudera.cdp.mow-int.cloudera.com/cloud/workloads/details/fdanielsqoopv3/events
Sqoop got successfully installed: https://fdanielsqoopv3-master1.oozie-p3.svbr-nqvp.int.cldr.work/cmf/services/1546334077/instances

CB-8535 Adding Sqoop to the Data Engineering template

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ClusterUpgradeRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterUpgradeHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeServiceTest.java

CB-8331: Allow cluster upgrade when only the GBN differs

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/context/CloudContext.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudNetworks.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Location.java
cloud-gcp/build.gradle
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpNetworkConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpObjectStorageConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformResources.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/GcpSubnetSelectorService.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/platform/GetPlatformNetworksResult.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/GetPlatformNetworksHandler.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/base/EnvironmentNetworkBase.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/telemetry/EnvironmentLogging.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/cloudstorage/CloudStorageLocationValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EnvironmentNetworkProviderValidator.java
environment/src/main/java/com/sequenceiq/environment/network/CloudNetworkService.java
environment/src/main/java/com/sequenceiq/environment/network/dto/GcpParams.java
environment/src/main/java/com/sequenceiq/environment/network/dto/NetworkDto.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/GcpEnvironmentNetworkConverter.java
environment/src/main/resources/schema/app/20200817121630_CB-3252_enable_google_cloud_in_environment_service.sql
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverterTest.java
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_install.sh
template-manager-tag/src/main/java/com/sequenceiq/cloudbreak/tag/DefaultCostTaggingService.java
template-manager-tag/src/test/java/com/sequenceiq/cloudbreak/DefaultCostTaggingServiceTest.java

Salient points,
1. The availability zone selection logic is different.
2. Tagging for CRN is different. Instead of cutting off at 63, I tried to select the last part for the CRN.
3. Fetching the network CIDR from GCP.
4. Added request/response conversations for GCP requests.
5. Started adding support for telemetry logging to cloud storage.
6. Have pulled in a change from the master that is currently breaking the installation in google cloud.
The compilation is failing because my patches are from both gcp-and-os-support and master. I will try to fix them. This is just to give a picture of what I am working.

Support for bringing up GCP freeipa environment

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorage.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageSetupService.java

CB-8510: Fixing NPE when azure getCopyStatus returns with null value

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsContextService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsContextServiceTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorage.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageSetupService.java

Merge 2.27 into 2.28

---

datalake/src/main/java/com/sequenceiq/datalake/flow/create/handler/StackCreationHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/ProvisionerService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/flow/create/handler/StackCreationHandlerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/ProvisionerServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeServiceTest.java

We will update runtimeversion in StackCreationHandler after stack was provisioned successfully. Reused the runtime version updater code from sdx upgrade flow.

CB-8276 set runtimeVersion if sdx was created through internal API

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsContextService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsContextServiceTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorage.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentBuildNumberComparator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentBuildNumberComparatorTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/create/handler/StackCreationHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/ProvisionerService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/flow/create/handler/StackCreationHandlerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/ProvisionerServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeServiceTest.java

Merge 2.29 branch into master

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/NewNetworkWithNoInternetEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxDistroxTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxRepairWithRecipeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxImagesTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsSdxSpotInstanceTest.java

Revert CB-8303

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/FreeIpaServerResponse.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/instance/InstanceGroupBase.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/instance/InstanceGroupResponse.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/instance/InstanceTemplateRequest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/instance/InstanceTemplateResponse.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/instance/VolumeBase.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/security/SecurityGroupResponse.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SetPasswordRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/CreateFreeIpaRequestToStackConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/start/action/AbstractStackStartAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberos/v1/KerberosConfigV1Service.java
freeipa/src/main/java/com/sequenceiq/freeipa/ldap/v1/LdapConfigV1Service.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/dns/DnsRecordService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/dns/DnsZoneService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/operation/OperationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ChildEnvironmentService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ClusterProxyService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaDeletionService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaDescribeService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthDetailsService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaRootCertificateService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaStopService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/dns/DnsRecordServiceTest.java

We have missed setting the `MDCContext` in many places. This commit
tries to fix those cases.

CB-8586 Check and fill FMS log context

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/NewNetworkWithNoInternetEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxDistroxTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxRepairWithRecipeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxImagesTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsSdxSpotInstanceTest.java

CB-8582 Apply cloud storage validation in case of non internal sdx create

CB-8582 Apply cloud storage validation in case of non internal sdx create

---

core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha-722.bp
datalake/src/main/resources/runtime/7.2.2/aws/medium_duty_ha.json
datalake/src/main/resources/runtime/7.2.2/azure/medium_duty_ha.json
datalake/src/main/resources/runtime/7.2.2/yarn/medium_duty_ha.json

- change the idbroker node count to 1
- assign gateway roles on all nodes (including master)

[CB-8618] Modified the medium duty template

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
authorization-common/build.gradle
authorization-common/src/main/java/com/sequenceiq/authorization/service/CommonPermissionCheckingUtils.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceBasedCrnProvider.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceCrnPermissionChecker.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceNamePermissionChecker.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceObjectPermissionChecker.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourcePermissionChecker.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/UmsResourceAuthorizationService.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/ResourceCrnPermissionCheckerTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/ResourceNamePermissionCheckerTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/ResourceObjectPermissionCheckerTest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/kerberos/KeytabProvider.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java
environment/src/test/java/com/sequenceiq/environment/service/integration/CredentialAuthorizationIntegrationTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/kerberosmgmt/KerberosMgmtV1Endpoint.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java

CB-7976 Modify framework for dual Right checking

---

datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java

CB-8628 make datalake describe endpoints internal ready

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CreateDhWithDatahubCreator.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CredentialCreateTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DatalakeDatahubCreateAuthTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvironmentCreateTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/RecipeTest.java

CB-7976 Fix Real UMS integration tests

---

authorization-common/src/main/java/com/sequenceiq/authorization/service/UmsResourceAuthorizationService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CreateDhWithDatahubCreator.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CredentialCreateTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DatalakeDatahubCreateAuthTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvironmentCreateTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/RecipeTest.java

CB-7976 print needed permissions if access is denied

---

integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupUtil.java

API Cleanup App error message is not correct:
```
Caused by: java.lang.RuntimeException: End To End cleanup have been failed, because of credential(s) '[aws-test-bd84fafad3c24769bf327e633d69d47, yarn-test-4f08108497dd4abe9d8dd47382aef9]' found left behind!
```
However there is also:
```
environmentName:aws-test-9061250527914a019dc will be deleted!
credentialName:aws-test-bd84fafad3c24769bf327e633d69d47 will be deleted!
credentialName:yarn-test-4f08108497dd4abe9d8dd47382aef9 will be deleted!
```
Need to collect the correct list of deleted resources for the final error message.

CB-8667 Add all the deleted resources to the error message

---

common/src/main/java/com/sequenceiq/cloudbreak/service/Retry.java
common/src/main/java/com/sequenceiq/cloudbreak/service/RetryService.java
flow/src/test/java/com/sequenceiq/cloudbreak/service/HeartbeatServiceTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java

CB-8682 remove @Retryable annotation from private method

---

core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha-722.bp

CB-8674 Removing duplicate Kafta gateway from master.  This fixes the

---

authorization-common/src/main/java/com/sequenceiq/authorization/service/CommonPermissionCheckingUtils.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxDetailedDescribeInternalAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DatalakeDatahubCreateAuthTest.java

CB-8720 dual right check for DL

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java

CB-7800 Stack remains in REPAIR_IN_PROGRESS if every node healthy

---

authorization-common/src/main/java/com/sequenceiq/authorization/service/CommonPermissionCheckingUtils.java

CB-7976 fix default resource handling during dual authz check

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/UtilV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/base/ResourceRightsV4.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/base/RightV4.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/requests/CheckResourceRightsV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/responses/CheckResourceRightV4SingleResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/responses/CheckResourceRightsV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/authorization/UtilAuthorizationService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/authorization/UtilAuthorizationServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/util/CheckResourceRightAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/util/CheckRightAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CheckResourceRightFalseAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CheckResourceRightTrueAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CheckRightFalseAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CheckRightTrueAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/UtilTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/util/CheckResourceRightTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/util/CheckRightTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CreateDhWithDatahubCreator.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DatalakeDatahubCreateAuthTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvironmentCreateTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/AuthorizationTestUtil.java

CB-8684 update checkRight API method on Util backend API

---

README.md

CB-8737 Bump memory and CPU recommendations in README

---

core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaCleanupService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaCleanupServiceTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaOperationDescriptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java

CB-8731 Freeipa Cleanup context fails with DhCreator role

---

core/src/main/java/com/sequenceiq/cloudbreak/service/authorization/UtilAuthorizationService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/authorization/UtilAuthorizationServiceTest.java

CB-8635 util checkright should go to UMS always

---

orchestrator-salt/src/main/resources/salt/salt/metering/template/generate_heartbeats.ini.j2

CDPCP-2987. Metering ServiceType should be enum instead of string

---

orchestrator-salt/src/main/resources/salt/salt/idbroker/init.sls

CB-8752 setting up IdBroker salt pillar only if it should exist.

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/diagnostics/DiagnosticsV4Endpoint.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/DiagnosticsEndpoint.java

just find out in sdx diagnostics branch, one of my change was missing
on diagnostics api call, it causes an error as that is redefined in the diagnostics controller call

CB-8611. Missing @Valid annotiation from DiagnosticsEndpoints

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/base/RightV4.java

CB-8635 Add new values for UI to checkRight enum

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceGroupMetadataProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/AbstractE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXImagesTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXScaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/ImageValidatorE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/PreconditionSdxE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsDistroXSpotInstanceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsSdxSpotInstanceTest.java

@keyki or @gergopapi2 please review.

Merge CB-2.30.0 to master

---

structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/LegacyStructuredEventFilter.java

The stream type is BufferedInputStream and mark() method call in LegacyStructuredEventFilter.logInboundEntity method
has a parameter readlimit which is set to 64K and if stream reading goes beyond this limit, the mark position is invalidated.
In the next line IOUtils.toString(stream, charset) was called which indeed reads the whole stream to the end and possibly passing the 64K readlimit thus invalidating the mark and throwing an exception when stream.reset is called.
This is fixed by explicitly reading into a pre-determined size byte buffer.

CB-8755 Fix stream mark error

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/database/DatabaseConfigV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/database/responses/DbConnectionParamsV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/internal/CloudbreakApiClientConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/DatabaseConfigV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/RdsConfigRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RdsConfigService.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/DatabaseConfigEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/EndpointConfig.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/DatabaseConfigController.java
datalake/src/main/java/com/sequenceiq/datalake/repository/SdxClusterRepository.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java

CB-8049 Request for API method for Hive DB user/pass vault path

---

structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/LegacyStructuredEventFilter.java

Merge CB-2.29.0 to CB-2.30.0

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/service/AltusIAMService.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/service/SharedAltusCredentialProvider.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/security/authentication/UmsAuthenticationService.java
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/security/authentication/UmsAuthenticationServiceTest.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDatabusService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDatabusServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/AltusMachineUserService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java

- enhanced ThreadBasedUserCrnProvier so internal calls can function well

CB-8313 making createMachineUser an internalCall, 

---

cloud-aws/src/main/resources/templates/aws-cf-stack-freeipa.ftl

CB-8816 fixing the freeipa provision error

---

core/src/main/resources/defaults/blueprints/cdp-flow-management-710.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-720.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-721.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-722.bp
core/src/main/resources/defaults/blueprints/cdp-flow-management-723.bp
core/src/main/resources/defaults/clustertemplates/aws/aws-flow-management-710.json
core/src/main/resources/defaults/clustertemplates/aws/aws-flow-management-720.json
core/src/main/resources/defaults/clustertemplates/aws/aws-flow-management-721.json
core/src/main/resources/defaults/clustertemplates/aws/aws-flow-management-722.json
core/src/main/resources/defaults/clustertemplates/aws/aws-flow-management-723.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flow-management-710.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flow-management-720.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flow-management-721.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flow-management-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flow-management-723.json

CB-8811 Flow Management Template Installation Fails

---

datalake/src/main/java/com/sequenceiq/datalake/flow/stop/handler/SdxStopAllDatahubHandler.java
datalake/src/test/java/com/sequenceiq/datalake/flow/stop/handler/SdxStopAllDatahubHandlerTest.java

CB-8386 SdxStopAllDatahubHandler should handle BadRequestException or any other Exception properly

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-702.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-722.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-702.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-722.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-722.bp

Revert ee32eb0b 766ff1e0f

---

core/src/main/resources/defaults/clustertemplates/aws/aws-flink-heavy-721.json
core/src/main/resources/defaults/clustertemplates/aws/aws-flink-heavy-722.json
core/src/main/resources/defaults/clustertemplates/aws/aws-flink-heavy-723.json
core/src/main/resources/defaults/clustertemplates/aws/aws-flink-light-721.json
core/src/main/resources/defaults/clustertemplates/aws/aws-flink-light-722.json
core/src/main/resources/defaults/clustertemplates/aws/aws-flink-light-723.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flink-heavy-721.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flink-heavy-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flink-heavy-723.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flink-light-721.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flink-light-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-flink-light-723.json

We aim to release the Streaming Analytics with Apache Flink templates via the 2.30 release. Please accept this pull request and also merge the commit back to the master branch. Thanks!

CB-8835 Release Streaming Analytics with Apache Flink

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDto.java

npe check in sdxinternalTestDto investigate 
beforehand it had nullpointer exception(only in test log)

CB-8822 npe check in sdxinternaltestdto investigate

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDtoBase.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java

CB-8758 Add ssh key to ycloud in hybrid e2e tests

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ClusterTemplateV4Controller.java

CB-8783 Do not attempt to get environment name is env crn is empty

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/CredentialConnector.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/credential/CredentialVerificationContext.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsConfusedDeputyException.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSessionCredentialClient.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnectorTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCredentialConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpCredentialConnector.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpCredentialConnectorTest.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockCredentialConnector.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/auth/OpenStackCredentialConnector.java
cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/credential/CredentialVerificationRequest.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/CredentialVerificationHandler.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/auth/YarnCredentialConnector.java
environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialService.java
environment/src/main/java/com/sequenceiq/environment/credential/service/RequestProvider.java
environment/src/main/java/com/sequenceiq/environment/credential/service/ServiceProviderCredentialAdapter.java
environment/src/test/java/com/sequenceiq/environment/credential/service/CredentialServiceTest.java
environment/src/test/java/com/sequenceiq/environment/credential/service/ServiceProviderCredentialAdapterTest.java
environment/src/test/java/com/sequenceiq/environment/service/integration/AuditCredentialAuthorizationIntegrationTest.java
environment/src/test/java/com/sequenceiq/environment/service/integration/CredentialAuthorizationIntegrationTest.java
environment/src/test/java/com/sequenceiq/environment/service/integration/EnvironmentServiceIntegrationTest.java

CB-8809 verify that AWS credentials' role is assumable without external Id

---

cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockResourceConnector.java
common/src/main/java/com/sequenceiq/cloudbreak/certificate/PkiUtil.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Resource.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/eventbus/CloudResourcePersisterService.java
core/src/main/resources/schema/app/20200911091600_CB-8659_add_index_to_resource_table.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
datalake/src/main/java/com/sequenceiq/datalake/entity/DatalakeStatusEnum.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/status/SdxStatusService.java
integration-test/docker-compose_template.yml
integration-test/scripts/docker-compose.sh
integration-test/scripts/stop-containers.sh
integration-test/scripts/swagger-check.sh
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/FileSystemConfigurationProvider.java

CB-8700 optimizations for IT test

---

environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/network/service/NetworkCreationRequestFactory.java
environment/src/main/java/com/sequenceiq/environment/network/service/NetworkTagProvider.java
environment/src/test/java/com/sequenceiq/environment/network/service/NetworkCreationRequestFactoryTest.java
environment/src/test/java/com/sequenceiq/environment/network/service/NetworkTagProviderTest.java

CB-8562 Fix environment and new network owner tags

---

environment/src/main/java/com/sequenceiq/environment/configuration/api/EndpointConfig.java
structuredevent-api-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/endpoint/CDPStructuredEventOperationDescriptions.java
structuredevent-api-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/endpoint/CDPStructuredEventV1Endpoint.java

CB-8892 missing structured_event endpoint from swagger json

---

common/src/main/java/com/sequenceiq/cloudbreak/certificate/PkiUtil.java

CB-8700 revert PkiUtil

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/mapper/CommonNotFoundExceptionMapper.java

CB-8912 not found exception with missing mapper was implemented

---

core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/ComponentLocatorService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/DefaultModel.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/model/SPIMock.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxTests.java

CB-8824 Can't repair SDX if both hostgroup is stopped

---

common-model/src/main/java/com/sequenceiq/common/api/telemetry/base/LoggingBase.java
common-model/src/main/java/com/sequenceiq/common/api/telemetry/doc/TelemetryModelDescription.java
common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/Logging.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifester.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifesterTest.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/TelemetryApiConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverter.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverterTest.java

1. This is required for creating CDP cli for environment creation.
2. The actual logging is yet to be done.

CB-8681 CB-3257 Adding GCS support for telemetry Logging

---

structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/CDPRestCommonService.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/filter/CDPStructuredEventFilter.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/filter/LoggingStream.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/filter/RepositoryBasedDataCollector.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/filter/RestEventFilterRelatedObjectFactory.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/filter/StructuredEventFilterUtil.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/filter/DataCollectorComponentTest.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/filter/StructuredEventFilterUtilTest.java

Cb 8777 refactor structured filter

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNetworkConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/client/AmazonCloudFormationRetryClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsLaunchService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/WaiterRunner.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/util/AwsCloudFormationErrorMessageProvider.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/util/AwsCloudFormationErrorMessageProviderTest.java

CB-8810 Get error reason from failed AWS CF stacks

---

environment/src/main/java/com/sequenceiq/environment/events/EnvironmentStructuredFlowEventFactory.java
environment/src/main/java/com/sequenceiq/environment/events/EventSenderService.java
freeipa/src/main/java/com/sequenceiq/freeipa/events/FreeipaStructuredFlowEventFactory.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/credential/CredentialTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/environment/EnvironmentListStructuredEventAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/freeipa/FreeIpaListStructuredEventAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/kerberos/KerberosConfigListStructuredEventAssertions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/ldap/LdapListStructuredEventAssertions.java
structuredevent-api-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/endpoint/CDPStructuredEventV1Endpoint.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/cdp/CDPStructuredEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/cdp/CDPStructuredFlowEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/cdp/CDPStructuredNotificationEvent.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/cdp/CDPStructuredRestCallEvent.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/repository/CDPStructuredEventRepository.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/controller/CDPStructuredEventV1Controller.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/filter/StructuredEventFilterUtil.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/CDPStructuredEventService.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/db/CDPStructuredEventDBService.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/converter/CDPStructuredEventEntityToCDPStructuredEventConverterTest.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/db/CDPStructuredEventDBServiceTest.java

CB-8947-filter-structured-event

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentStatus.java

CB-8655 Verify env is not failed before creating SDX

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/base/RightV4.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/util/CheckRightRawAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/UtilTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/RawCloudbreakTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/CheckRightRawTest.java

CB-9000 checkright util api should fall back to a default value for right enum in case of error

---

cloud-aws/build.gradle
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/tracing/AwsSpanDecorator.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/tracing/AwsTracingRequestHandler.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/tracing/AzureOkHttp3TracingInterceptor.java
common/src/main/java/com/sequenceiq/cloudbreak/tracing/TracingConfiguration.java
common/src/main/java/com/sequenceiq/cloudbreak/tracing/TracingUtil.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/DatalakeDrClient.java
flow/src/main/java/com/sequenceiq/flow/core/FlowTracingUtil.java
grpc-common/src/main/java/com/sequenceiq/cloudbreak/grpc/util/GrpcUtil.java

Prefixes for:
Azure
AWS
gRPC
flow

CB-8954 - added prefixes for trace operation names to improve readability

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/base/RightV4.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/util/CheckRightRawAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/UtilTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/RawCloudbreakTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/CheckRightRawTest.java

merge 2.29 into 2.31

---

authorization-common/README.md

CB-6671 update authz readme

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDiagnosticsService.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/base/RightV4.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/diagnostics/DiagnosticsCollectionValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/CmDiagnosticsCollectionActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/handler/CmDiagnosticsCleanupHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/handler/CmDiagnosticsInitHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/handler/CmDiagnosticsUploadHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/diagnostics/DiagnosticsService.java
datalake/src/main/java/com/sequenceiq/datalake/service/validation/diagnostics/DiagnosticsCollectionValidator.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/util/CheckRightRawAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/UtilTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/RawCloudbreakTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/CheckRightRawTest.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls

2.31 to master

---

core/src/main/resources/defaults/clustertemplates/gcp/gcp-dataengineering-723.json
core/src/main/resources/defaults/clustertemplates/gcp/gcp-flow-management-723.json
core/src/main/resources/defaults/clustertemplates/gcp/gcp-flow-management-small-723.json
core/src/main/resources/defaults/clustertemplates/gcp/gcp-streaming-723.json
core/src/main/resources/defaults/clustertemplates/gcp/gcp-streaming-small-723.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

CB-8931 Introduce Gcloud template as a first drop

---

environment/src/main/java/com/sequenceiq/environment/tags/service/DefaultInternalAccountTagService.java
environment/src/test/java/com/sequenceiq/environment/tags/service/DefaultInternalAccountTagServiceTest.java
template-manager-tag/src/main/java/com/sequenceiq/cloudbreak/tag/HandleBarModelKey.java

CB-9061 Accounttag validation should check existing expressions

---

common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/type/MetricType.java
flow/src/main/java/com/sequenceiq/cloudbreak/service/ha/HeartbeatService.java

as it was missing and not traceable

CB-9044 Add heartbeat success logging

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidator.java

CB-9058 remove datahub/write permission checks from service layer

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/ClusterRepairV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpscaleFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleContext.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/ClusterScaleTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/StackAndClusterUpscaleTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/UpscaleClusterRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/ClusterRepairTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/UpscaleClusterHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/RemoveHostsHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterUpscaleServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusIntegrationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxEventParameterFactory.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRepairService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/status/SdxStatusService.java

CB-8659 restart services after repair

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/handler/MachineUserRemoveHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaInstallService.java

and therefore the machine user get's created with creatorCrn not internal

CB-8313 FreeIpa is not using the same service as in CB 

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementServiceTest.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/main/resources/application.yml
mock-thunderhead/src/test/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementServiceTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProviderTest.java

Cherry-pick the commit at master to 2.31.0 branch. https://github.com/hortonworks/cloudbreak/commit/b1f5b8a9ccb2c2b8b7e78c99fa52d640917faade

CB-9055: Put HBase Cloud Storage feature under entitlement

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerRoleRefreshService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerApiCheckerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerCommandCheckerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerCommandListCheckerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ApiCommandUtil.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerCommandCheckerTaskTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ApiCommandUtilTest.java

CB-8943 Can't repair datahub with stopped compute and worker nodes

---

structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/db/CDPStructuredEventDBService.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/db/CDPStructuredEventDBServiceTest.java

CB-9129 We want to save the structured event if the resource crn is null

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
authorization-common/src/main/resources/legacyRights.json
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/base/RightV4.java

CB-9066 Add listAssignedResourceRoles to Rights

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
authorization-common-api/src/main/java/com/sequenceiq/authorization/annotation/ResourceObjectField.java
authorization-common-api/src/main/java/com/sequenceiq/authorization/annotation/ResourceObjectFieldHolder.java
authorization-common/README.md
authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceObjectPermissionChecker.java
authorization-common/src/test/java/com/sequenceiq/authorization/EnforceAuthorizationLogicsUtil.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/ResourceObjectPermissionCheckerTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/cluster/ClusterV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/image/ImageSettingsV4Request.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/DistroXV1Request.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/cluster/DistroXClusterV1Request.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/image/DistroXImageV1Request.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/instancegroup/InstanceGroupV1Request.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxInternalController.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UmsClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CreateDhWithDatahubCreator.java

CB-9124 AuthZ is not checked for DistroX recipes/templates/imagecatalogs

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/NetworkDeleteHandler.java
structuredevent-api-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/endpoint/CDPStructuredEventV1Endpoint.java

CB-9155 and CB-9147

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/base/RightV4.java

Added DH_REPAIR, DH_RESIZE, DH_RETRY, SDX_REPAIR, SDX_RETRY and ENV_DESCRIBE to RightV4 
Required to authorize UI elements

CB-9166 Make additional rights available for UI

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/poller/DatabasePollerService.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/poller/GcpDatabasePollerProvider.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerLaunchService.java

CB-9171 Associate private network and root user for GCP RDS instances

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/service/AltusIAMService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDatabusService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDatabusServiceTest.java
common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/DataBusCredential.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/Cluster.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserService.java
core/src/main/resources/schema/app/20200930130154_CB-9056_add_dbus_secrets.sql
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserServiceTest.java

Merge 231 to master

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrap.java

CB-9064 don't restart minions more than once

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerLaunchService.java

CB-9171 store GCP database instane's private ip as RDS hostname

---

authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceObjectPermissionChecker.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/ResourceObjectPermissionCheckerTest.java

CB-9124 Request object authz logic shouldn't traverse null objects

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonCloudProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/ImageValidatorE2ETest.java

CB-8687 Validate image uuid in case of the expected one is provided.

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/UpgradeMatrixConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentVersionComparator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePermissionProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/CmAndStackVersionFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/matrix/Runtime.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/matrix/RuntimeUpgradeMatrix.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/matrix/UpgradeMatrixDefinition.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/matrix/UpgradeMatrixDefinitionProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/matrix/UpgradeMatrixService.java
core/src/main/resources/definitions/upgrade-matrix-definition.json
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentVersionComparatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePermissionProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/matrix/RuntimeUpgradeMatrixDefinitionProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/matrix/UpgradeMatrixServiceTest.java
core/src/test/resources/upgrade/upgrade-matrix-definition.json

CB-8228: Implement the mechanics to specify the upgrade matrix

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpIdentityService.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/cloudstorage/CloudIdentity.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/cloudstorage/GcsIdentity.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/FileSystemConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/CloudStorageConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/GcpMockAccountMappingService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java

CB-9250 addede idbmms mock mapping to handle gcloud scenario

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/ImageValidatorE2ETest.java

CB-8687 Apply image validation before env creation to fail fast.

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/AuthorizationClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java

This client was skipped by accident when tracing was added to the other grpc clients.

CB-9272 - Added tracing config to authorzation grpc calls.

---

authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceCrnPermissionChecker.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceNamePermissionChecker.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceObjectPermissionChecker.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/ResourceCrnPermissionCheckerTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/ResourceNamePermissionCheckerTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/ResourceObjectPermissionCheckerTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/AuthUserKeys.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/legacy/authorization/EnvironmentGetTest.java
integration-test/src/main/resources/testsuites/v4/mock/legacy-authz-mock-package.yaml

CB-9328 Dual right check should be performed only if authz entitlement disabled

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbCertificateProvider.java
orchestrator-salt/src/main/resources/salt/pillar/postgresql/root-certs.sls
orchestrator-salt/src/main/resources/salt/pillar/top.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/root-certs.sls
orchestrator-salt/src/main/resources/salt/salt/top.sls
redbeams/src/main/resources/schema/app/20201013110628_CB-9289_ssl_certificate_added_to_db_stack.sql

CB-8114 Gather root certs for Redbeams database instances and save it to  a file on every node of the clusters

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverterTest.java

Reverts hortonworks/cloudbreak#9193

Revert "CB-9227 - unable to get cluster definition on a stopped environment"

---

core/src/main/resources/definitions/upgrade-matrix-definition.json

CB-9383: Extend upgrade matrix to enable upgrades to 7.2.3

---

authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceNamePermissionChecker.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceObjectPermissionChecker.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/BlueprintRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java

- make sure getResourceCrnByResourceName for BlueprintService is not returning null and framework also responds with 404 if resourceCrn cannot be found

CB-9382 make sure getResourceCrnByResourceName not returns null

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/UserV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UserOperationDescriptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java

CB-9100 Resource authorized new user sync operation status endpoint

---

common/src/main/java/com/sequenceiq/cloudbreak/validation/SubnetType.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/DnsRecord.java

Fixed a build warning due to unmappable UTF-8 characters.

CB-9406: Fix unmappable UTF-8 characters for spot bugs warning

---

mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java

CB-9380. Update user management mock (using create workload user call)

---

authorization-common/build.gradle
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/InstanceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureInstanceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureVirtualMachineService.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/InstanceStateQuery.java
common/build.gradle
common/src/main/java/com/sequenceiq/cloudbreak/quartz/statuschecker/service/StatusCheckerJobService.java
common/src/test/java/com/sequenceiq/cloudbreak/quartz/EnforceStatusCheckerAnnotationUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackInstanceStatusChecker.java
core/src/test/java/com/sequenceiq/cloudbreak/job/EnforceStatusCheckerAnnotationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackInstanceStatusCheckerTest.java
datalake/src/main/java/com/sequenceiq/datalake/job/SdxClusterStatusCheckerJob.java
datalake/src/test/java/com/sequenceiq/datalake/job/EnforceStatusCheckerAnnotationTest.java
environment/src/main/java/com/sequenceiq/environment/environment/sync/EnvironmentStatusCheckerJob.java
environment/src/test/java/com/sequenceiq/environment/environment/sync/EnforceStatusCheckerAnnotationTest.java
flow/build.gradle
freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackInstanceProviderChecker.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java
freeipa/src/test/java/com/sequenceiq/freeipa/sync/EnforceStatusCheckerAnnotationTest.java
integration-test/build.gradle
redbeams-model/build.gradle
redbeams/src/main/java/com/sequenceiq/redbeams/sync/DBStackStatusSyncJob.java
redbeams/src/test/java/com/sequenceiq/redbeams/sync/EnforceStatusCheckerAnnotationTest.java

CB-9305 Optimize syncer Thread usage

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java

CB-9391: Do not restart all the services in CM during upgrade-repair

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/BaseImageValidatorE2ETest.java

CB-9037 Fix image id lookup at the end of the test case

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/base/RightV4.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CheckResourceRightFalseAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CheckResourceRightTrueAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CheckRightFalseAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CheckRightTrueAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvironmentCreateTest.java

CB-9309 Util API (used by UI to authorize UI components) uses wrong right for checking permission of datahub creation

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpNetworkConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformResources.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/group/GcpFirewallInResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtilTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/base/RightV4.java
core/src/main/resources/defaults/blueprints/7.2.2/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.3/cdp-sdx-medium-ha.bp
datalake/src/main/resources/duties/7.2.2/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.2/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.2/yarn/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.3/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.3/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.3/yarn/medium_duty_ha.json
environment/src/main/java/com/sequenceiq/environment/network/EnvironmentNetworkService.java
environment/src/main/java/com/sequenceiq/environment/network/NetworkConnectorNotFoundException.java
environment/src/main/java/com/sequenceiq/environment/network/NetworkService.java
environment/src/test/java/com/sequenceiq/environment/network/EnvironmentNetworkServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CheckResourceRightFalseAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CheckResourceRightTrueAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CheckRightFalseAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CheckRightTrueAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvironmentCreateTest.java

2.32 to master

---

common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/RequestHeaderMetricFilter.java
common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/type/MetricTag.java
common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/type/MetricType.java
common/src/main/java/com/sequenceiq/cloudbreak/filter/CommonFilterConfiguration.java

Added common filter, which applies in all services. The filter
increments a metric counter based on the caller id in the header.

CB-9195 Request caller id metrics
