hortonworks/cloudbreak

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java

CLOUD-865 added event when can not deregester from ambari

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Credential.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/SimpleCredentialService.java
core/src/main/resources/schema/20150622105546_CLOUD-840_new_column_for_keeping_deleted_credentials.sql

* Credentials marked as archived during deletion
* credential names appended with a uuid to avoid constraint violation
* migration scripts added
@biharitomi  please review it

CLOUD-840 credentials kept for further reference

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/UserController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/RemoteUserDetailsService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserDetailsService.java

CLOUD-444 add: delete user operation

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/DefaultStackService.java

CLOUD-868 fixed nullpointer

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/UserController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/RemoteUserDetailsService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/UserDetailsService.java

CLOUD-444 check user resources instead of user deletion

---

integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakITContextConstants.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTestSuiteInitializer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/StackCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/config/ITProps.java
integration-test/src/main/resources/application.yml

@schfeca75 please review it!
Add the new resources to the integration tests.

CLOUD-872 integrate security group and rule resources

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/MetadataSetup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsMetadataSetup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureMetadataSetup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/gcp/GcpMetadataSetup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/openstack/OpenStackMetadataSetup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java

DEV-45 remove/add resources as well after stack sync

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/ApiDocConfig.java

CLOUD-872 add security group endpoints to swagger patterns

---

integration-test/src/main/resources/testsuites/azure/smoke/azure-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/azure/smoke/azure-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/azure/smoke/azure-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/azure/smoke/azure-clustercreate.yaml

Try to eliminate azure instance type combination exception during integration test

---

core/src/main/java/com/sequenceiq/cloudbreak/service/credential/aws/AwsCredentialHandler.java

previously, a misleading "Couldn't assume role" message was sent

DEV-41 In case of missing AWS credentials provide correct error message

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Blueprint.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Template.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/BlueprintController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/TemplateController.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToAwsTemplateConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToAzureTemplateConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToBlueprintConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToGcpTemplateConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToOpenStackTemplateConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/BlueprintRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/TemplateRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/DefaultBlueprintLoaderService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/DefaultBlueprintService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/template/SimpleTemplateLoaderService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/template/SimpleTemplateService.java
core/src/main/resources/schema/20150625111518_CLOUD-881_default_resources.sql

@biharitomi @doktoric 
Template and blueprint default resources are handled the same way as networks and security groups. Once you delete a default one it won't bring back after a page refresh.

CLOUD-881 handle default resource deletions

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/SecurityConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/CertificateResponse.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/SecurityConfigRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/DefaultStackService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java

@keyki 
Added a new endpoint that returns the certificate of a stack if the caller has the cloudbreak.autoscale scope. Will be used by Periscope.

CLOUD-885 endpoint for returning certificate of cluster

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java
core/src/main/resources/init/init.ftl
core/src/test/resources/azure-gateway-init.sh

@keyki or @martonsereg or @biharitomi

CLOUD-891 fixed tmp ssh remove

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsMetadataSetup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureMetadataSetup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/openstack/OpenStackMetadataSetup.java

@martonsereg please review it!

CLOUD-878 fix instance sync states creation in case of Azure and OpenStack

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Resource.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperErrorHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ResourceRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/InstanceTerminationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java
core/src/main/resources/schema/20150626160502_CLOUD-890_unique_contraint_for_resource_table,_delete_old_duplicated_resources.sql

CLOUD-890 get rid of NonUniqueResultExceptions of resources

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperErrorHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/InstanceTerminationHandler.java

CLOUD-000 fix broken annotations

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/CloudbreakResourceNameService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/ResourceNameService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/AzureResourceNameService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/AzureSimpleInstanceResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/instance/AzureCloudServiceResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/instance/AzureServiceCertificateResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/instance/AzureVirtualMachineResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/network/AzureNetworkResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/network/AzureReservedIpResourceBuilder.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/resource/AzureResourceNameServiceTest.java

Azure resource names have the form:
network resource:
clustername-20150626152730
cloud resource:
cbgateway-0-clustername-20150626152752
master-1-clustername-20150626152915
vm name:
cbgateway-0-clustername-20150626152752
master-1-clustername-20150626152915
slave1-2-clustername-20150626153016
@akanto  @doktoric please review

CLOUD-883 Resource names generated with the resource name service

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Cluster.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/status/AmbariClusterStatusUpdater.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java

CLOUD-892 modify sync to not ruin stacks in stopped state

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunner.java

CLOUD-893 handle empty ambari docker container environment variables

---

core/config/checkstyle/checkstyle-suppressions.xml
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperErrorHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ContainerOrchestratorResolver.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/CloudbreakUsageSpecifications.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackUpdater.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureProvisionSetup.java
core/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/CancelledMockContainerOrchestrator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ContainerOrchestratorResolverTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/FailedMockContainerOrchestrator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/MockContainerOrchestrator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/StackDeletionBasedExitCriteriaTest.java
core/src/test/java/com/sequenceiq/cloudbreak/facade/DefaultCloudbreakEventsFacadeTest.java
core/src/test/java/com/sequenceiq/cloudbreak/facade/DefaultCloudbreakUsagesFacadeTest.java
core/src/test/java/com/sequenceiq/cloudbreak/logger/MDCBuilderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/repository/StackUpdaterTest.java

CLOUD-895 added more test in bootstrap phase

---

core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/CloudPlatformConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/gcp/GcpConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/gcp/GcpConsoleOutputCheckerTask.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/openstack/ConsoleOutputCheckerTask.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/openstack/OpenStackConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/FingerprintParserUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/VerboseHostKeyVerifier.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/builders/instance/GcpDiskResourceBuilder.java
core/src/main/resources/init/init.ftl
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/FingerprintParserUtilTest.java
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh
core/src/test/resources/com/sequenceiq/cloudbreak/service/stack/flow/gcp-console.txt
core/src/test/resources/com/sequenceiq/cloudbreak/service/stack/flow/openstack-console.txt
orchestrator-swarm/build.gradle
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java

- Upgrade to Centos 7
- Fingerprint validation is disabled on AWS, since neither Centos7 nor RHEL7 does not provide fingerprint ( https://forums.aws.amazon.com/thread.jspa?threadID=190043 )
Note: there is a mistake in the AWS thread, because the Centos 7 also does not provide the consol output 
- No tar.gz image is used on GCP

Centos 7 upgrade

---

core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/BaywatchClientBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/BaywatchServerBootstrap.java

!!!important: merge this after new images are burned already. (baywatch version already updated in cloudbreak-images)

BAY-7 update baywatch elasticsearch data path

---

core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunner.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/MockContainerOrchestrator.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/ContainerOrchestrator.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/DockerContainer.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/LogrotateBootsrap.java

!!! important note: merge this after new images are built

CLOUD-672 added logrotate container (bootstrap)

---

core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperErrorHandlerTest.java
orchestrator-api/build.gradle
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/DockerClientUtil.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariAgentBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariServerBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariServerDatabaseBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/BaywatchClientBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/BaywatchServerBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/ConsulWatchBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/LogrotateBootsrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/MunchausenBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/RegistratorBootstrap.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/DockerClientUtilTest.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestratorTest.java

Unit tests

---

core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java

CLOUD-899: Using image created only with packer for gcp

---

core/src/main/resources/hdp/hdp-services.json

@schfeca75 
new services introduced in HDP 2.3

CLOUD-936 new services introduced to check before provisioning

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Status.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariHostsStatusCheckerTask.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/status/AmbariClusterStatusUpdater.java

CLOUD-943 fixed ambari host health checks

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/CloudbreakResourceNameService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/AzureResourceNameService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/AzureSimpleInstanceResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/network/AzureNetworkResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/network/AzureReservedIpResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/GcpResourceNameService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/GcpSimpleNetworkResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/builders/instance/GcpAttachedDiskResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/builders/instance/GcpDiskResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/builders/instance/GcpInstanceResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/builders/network/GcpFireWallInResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/builders/network/GcpFireWallInternalResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/builders/network/GcpNetworkResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/builders/network/GcpReservedIpResourceBuilder.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/GcpResourceNameServiceTest.java

Added resource name generation to the GCP
@akanto please review

CLOUD-906 gcp resource names are generated with the dedicated service

---

core/src/main/resources/templates/aws-cf-stack.ftl

CLOUD-878 fix dependency between cf resources

---

core-model/build.gradle
core/build.gradle

CLOUD-943 added exclude patterns

---

integration-test/src/main/resources/testsuites/aws/smoke/aws-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/aws/smoke/aws-clustercreate-startstop.yaml

change ephemaral volumes to ssd in case of stop-start smoketests

---

core/src/main/resources/hdp/service-config.json

CLOUD-859 Ambari 2.0 does not create the dir automatically

---

core/config/checkstyle/checkstyle-suppressions.xml
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

@keyki pls review
We need to restart the services before downscale

CLOUD-48 restart services before decommission

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/OpenStackTemplateParam.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/TemplateParametersValidatorTest.java

CLOUD-951 eliminate non existing field from OpenStack template validation

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java

CLOUD-907 get host names only once

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/json/ClusterRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java

CLOUD-945 remove password validation

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/AwsTemplate.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/DefaultStackService.java
core/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/DefaultStackServiceTest.java

CLOUD-949 aws stop disabled when ephemeral volumetype

---

core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/builder/BindsBuilder.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/builder/HostConfigBuilder.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariAgentBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariServerBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariServerDatabaseBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/BaywatchClientBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/BaywatchServerBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/ConsulWatchBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/LogrotateBootsrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/MunchausenBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/RegistratorBootstrap.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestratorTest.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/ConsulWatchBootstrapTest.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/LogrotateBootstrapTest.java

@keyki , @schfeca75 please take a look
- Updating the swarm and munchausen version
- Eliminate deprecated api calls
- Fix issue with volume mounting

Swarm update

---

core/src/main/resources/defaults/templates/minviable-azure.tmpl
core/src/main/resources/defaults/templates/minviable-gcp.tmpl
core/src/main/resources/schema/20150712112355_default_template_vmtype_changes.sql

CLOUD-955 default template changes

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java

CLOUD-946 fixed upscale with sync

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakITContextConstants.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ScalingTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/StatusUpdateTest.java

CLOUD-945: Update integration test to use the given ambari user/pwd not the default ones

---

core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
core/src/main/resources/init/init.ftl
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh

CLOUD-663: Setting up CentOS host according to best practices

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariHostsCheckerContext.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariHostsJoinStatusCheckerTask.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariHostsStatusCheckerTask.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnectorTest.java

CLOUD-962 fixed hostchecking

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/StackDeletionBasedExitCriteria.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/DefaultStackService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/StackDeletionBasedExitCriteriaTest.java

CLOUD-975 reduce db access and object size

---

core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/ASGroupStatusCheckerTask.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsProvisionSetup.java

CLOUD-965 spot request configuration

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/InstanceMetaDataJson.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/MetaDataToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackScalingService.java

CLOUD-907 added instance status and updated instance removing

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/SshCheckerTask.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/SshCheckerTaskContext.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java

CLOUD-978 check ssh is available before setup

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

CLOUD-878 fixed persisting problem on host data part

---

core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java

CLOUD-663: New image for openstack

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

CLOUD-984 fixed hostcount check under upscale

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/TlsSecurityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/HadoopConfigurationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/VolumeUtils.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/openstack/HeatTemplateBuilder.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/CancelledMockContainerOrchestrator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperErrorHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/FailedMockContainerOrchestrator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/MockContainerOrchestrator.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/ContainerOrchestrator.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/GatewayConfig.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/LogVolumePath.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/builder/BindsBuilder.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariAgentBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariServerBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariServerDatabaseBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/BaywatchClientBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/ConsulWatchBootstrap.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/OrchestratorTestUtil.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestratorTest.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AbstractContainerBootstrapTest.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariAgentBoostrapTest.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariServerBootstrapTest.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariServerDatabaseBootstrapTest.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/BaywatchClientBootstrapTest.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/ConsulWatchBootstrapTest.java

CLOUD-908 refactored log volume handling

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackScalingService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/gcp/builders/GcpResourceBuilderInit.java

CLOUD-986: Using the original resources stored in the db for deletion

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterSecurityService.java
core/src/main/java/com/sequenceiq/cloudbreak/util/AmbariClientExceptionUtil.java

CLOUD-980 expand the error message from groovy HttpResponseException

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java

CLOUD-973 added global bc provider

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/DefaultStackService.java

CLOUD-991: First check the existance of the instancegroup

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

Catch and log exceptions during rollback of upscale when try to delete ambari hosts

---

docs/index.md

CLOUD-878 fixed contribution urls

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/StackDeletionBasedExitCriteria.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/ContainerBootstrapRunner.java

CLOUD-996 do not exit polling if the cluster is not created yet

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

@keyki 
!! try it before merge it

CLOUD-992 start hdfs/hbase services if needed

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleFlowFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java

CLOUD-994 trigger recipes on upscale

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariOperationsStatusCheckerTask.java

CLOUD-970 fixed nullpointer after ambari SSL error

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ConsulPluginManager.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/PluginManager.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java

CLOUD-997 handle ONE_NODE type of recipes during upscale

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

CLOUD-992 set sequence between hdfs and hbase services

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

CLOUD-999 fixing rollback in case of upscale

---

core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java

CLOUD-985 image update to start docker daemon after cloud init

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperErrorHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleFlowFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleStackFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackUpdater.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/InstanceTerminationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/events/CloudbreakEventHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/messages/CloudbreakMessagesService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/messages/MessagesConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/notification/Notification.java
core/src/main/java/com/sequenceiq/cloudbreak/service/notification/NotificationAssemblingService.java
core/src/main/resources/messages/messages.properties
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperErrorHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/repository/StackUpdaterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/messages/CloudbreakMessagesServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/messages/TestConfig.java

- added service implementation to deal with cb messages sent to users
- stack and cluster flow messages extracted into a message bundle
- event creation moved to facades (removed from the stack updater)
- hunglish messages rewritten
More messages are to be extracted (those hidden in various services)
@akanto please have a look

Cloud 967 - Improved messaging

---

core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleStackFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java

@akanto 
reenabled fingerprint validation on AWS with new RHEL images with proper serial console setup in grub
run some smoke tests (cluster installs) on EC2, Google and Azure

Re-enabled fingerprint validation on EC2

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/status/AmbariClusterStatusUpdater.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/DefaultStackService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackScalingService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java
core/src/main/resources/messages/messages.properties
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/status/AmbariClusterStatusUpdaterTest.java

- more messages extracted into the bundle
@akanto please review

CLOUD-967 more messages extracted

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/azure/builders/network/AzureStorageAccountResourceBuilder.java

CLOUD-1003 fixed lazy initialization exception

---

.gitignore
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackFailureHandlerService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/ProvisionUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/callable/ProvisionContextCallable.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/handler/ScalingFailureHandlerService.java

Rollback fix all resource

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java
core/src/main/resources/init/tls-setup.sh

CLOUD-41900: Refactor tls-setup.sh script

---

core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/ServiceEndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/registry/DNSServiceAddressResolver.java
core/src/main/java/com/sequenceiq/cloudbreak/service/registry/RetryingServiceAddressResolver.java
core/src/main/java/com/sequenceiq/cloudbreak/service/registry/ServiceAddressResolver.java
core/src/main/java/com/sequenceiq/cloudbreak/service/registry/ServiceAddressResolvingException.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/RemoteUserDetailsService.java

CLOUD-41906: use dns for service address resolving

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Blueprint.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java

BUG-42385 Instance metadata is not set to TERMINATED

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/ServiceEndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/registry/RetryingServiceAddressResolver.java

CLOUD-41906: address resolving timeout can be set via envvar

---

core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/ClusterRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterSecurityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ConsulPluginEvent.java
core/src/main/resources/init/init.ftl
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/MockContainerOrchestrator.java
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh
gradle.properties
integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/ContainerOrchestrator.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/security/KerberosConfiguration.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/AmbariServerBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/KerberosServerBootstrap.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestratorTest.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/KerberosServerBootstrapTest.java

CLOUD-41495 Kerberos support

---

core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/ConsoleOutputCheckerTask.java

CLOUD-42445 update AWS SDK and aws console output poller

---

gradle.properties

CLOUD-41495 Update CB client version

---

gradle.properties

CLOUD-41495 Update CB client version again

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/ClusterRequest.java

@keyki plz review it. Unfortunately @RequestParam, built in validations and custom validations are not friends together, too complicated to implement (not impossible), so i choose this stupid simple solution

CLOUD-41495 Kerberos related request params validation

---

docs/index.md

CLOUD-41495 Readme update with Kerberos hints

---

docs/index.md

CLOUD-41495 Kerberos related read update

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/gcp/kerberos/gcp-clustercreate-startstop-updown.yaml

CLOUD-41495 Kerberos integration test

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/context/CloudContext.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/logger/LogContext.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/task/FetchTask.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollTask.java
cloud-openstack/src/test/java/com/sequenceiq/cloudbreak/ReactorApplication.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollInstanceConsoleOutputTask.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollInstancesStateTask.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollResourcesStateTask.java
core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/logger/LogContextAspects.java
core/src/main/java/com/sequenceiq/cloudbreak/logger/MDCBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderAdapter.java
gradle.properties

@keyki or @akanto please review!

Declarative MDC context builder is required

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunner.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/CancelledMockContainerOrchestrator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/FailedMockContainerOrchestrator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/MockContainerOrchestrator.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/ContainerOrchestrator.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestratorTest.java
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/mantest/BootstrapManTest.java

@akanto build success, it success, plz review

CLOUD-42473 Eliminate code duplication

---

core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/BaywatchClientBootstrap.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/KerberosServerBootstrap.java

Do not merge till openstack image is not available and updated

Krb baywatch

---

integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTestSuiteInitializer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/NetworkDeleteByNameTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/OpenStackCredentialCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/OpenStackNetworkCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/OpenStackTemplateCreationTest.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/openstack-resourcetests.yaml
integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate.yaml

CLOUD-42448: Add OpenStack into Integration test

---

cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/GetSSHFingerprintsHandler.java

CLOUD-42390 fixed azure try-catch

---

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmResourceConnector.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollBooleanTerminationTask.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollTaskConfig.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollTaskFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/AbstractFlowHandler.java

CLOUD-42390 arm cancel was not working because of custom polltasks

---

cloud-openstack/src/main/resources/templates/openstack-heat.ftl

CLOUD-42639: Using block_device_mapping instead of VolumeAttachment

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudResource.java
cloud-arm/build.gradle
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmInstanceConnector.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmMetadataCollector.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmResourceConnector.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmSetup.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateUtils.java
cloud-arm/src/main/resources/logback.xml
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/OpenStackMetadataCollector.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/OpenStackResourceConnector.java
config/checkstyle/checkstyle.xml
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/ResourceToCloudResourceConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/azurerm/AzureRmCredentialHandler.java
docs/index.md

@keyki or @akanto pls check this modification

CLOUD-42308 azure rm fixes

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AzureRmCredentialCreationTest.java
integration-test/src/main/resources/testsuites/resourcetests.yaml

CLOUD-42308 it fix

---

core/src/main/java/com/sequenceiq/cloudbreak/repository/StackUpdater.java

CLOUD-42390 fixed delete npe

---

core/src/main/resources/messages/messages.properties

CLOUD-43517 fix broken Ambari ip pattern

---

gradle.properties

CLOUD-43362 Update amber client version

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java

CLOUD-43501 added frankfurt

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java

CLOUD-42844 Update images

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/ResourceConnector.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/resource/LaunchStackRequest.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/notification/PersistenceNotifier.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmResourceConnector.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/OpenStackResourceConnector.java
cloud-reactor/build.gradle
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/LaunchStackHandler.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/UpdateStackHandler.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/UpscaleStackHandler.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/init/CloudPlatformConnectors.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/notification/AllocationNotifier.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/AbstractComponentTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/CollectMetadataComponentTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/DownscaleStackComponentTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/GetSSHFingerprintsComponentTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/InstanceStateComponentTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/LaunchStackComponentTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/ParameterGenerator.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/StartStackComponentTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/StopStackComponentTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/TerminateStackComponentTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/UpdateStackComponentTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/UpscaleStackComponentTest.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/testcontext/TestApplicationContext.java

Create basic test framework for component test.

Testframework

---

core/src/main/java/com/sequenceiq/cloudbreak/service/account/SimpleAccountPreferencesService.java

CLOUD-42526 avoid account preferences' unique constraint violation

---

cloud-api/build.gradle
cloud-arm/build.gradle
cloud-common/build.gradle
cloud-openstack/build.gradle
cloud-reactor/build.gradle

@akanto or @schfeca75 
Noticed that there were some hardcoded versions in some submodules, I think it wasn't on purpose.

CLOUD-43335 removed hardcoded versions in some submodules

---

docs/index.md

CLOUD-42308 reverted arm doc

---

build.gradle

@akanto 
it's getting complicated...:)

CLOUD-43335 create rc from nearest any if scope is not patch

---

docs/index.md

CLOUD-42308 added arm docs

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/RecipeController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/RecipeBase.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/RecipeResponse.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/PluginValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/ValidPlugin.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToRecipeConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
core/src/main/resources/schema/20150902144124_CLOUD-43504_load_recipe_from_consul.sql
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/PluginValidatorTest.java

@martonsereg plz review. Burned images are missing!

CLOUD-43504 Strore recipe in Consul

---

cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/StartStackHandler.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/StopStackHandler.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollInstancesStateTask.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollTaskConfig.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/task/PollTaskFactory.java
integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate-startstop-updown.yaml

CLOUD-44058: waiting for STOPPED,FAILED in StopStackHandler, waiting for STARTED,FAILED in StartStackHandler

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/context/CloudContext.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmClient.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmResourceConnector.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmSetup.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateBuilder.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateUtils.java
cloud-arm/src/test/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateBuilderTest.java
cloud-arm/src/test/java/com/sequenceiq/cloudbreak/cloud/arm/TestUtil.java

CLOUD-44147 one storage for every resourcegroup

---

core/src/main/resources/defaults/blueprints/datadev-default.bp
core/src/main/resources/defaults/blueprints/datascientist-default.bp
core/src/main/resources/defaults/blueprints/operations-default.bp
core/src/main/resources/defaults/blueprints/streaming-default.bp

CLOUD-42526 more blueprint added

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java

CLOUD-42393 fixed long object comparison

---

core/src/main/resources/defaults/blueprints/datadev-default.bp
core/src/main/resources/defaults/blueprints/datascientist-default.bp
core/src/main/resources/defaults/blueprints/operations-default.bp
core/src/main/resources/defaults/blueprints/streaming-default.bp

CLOUD-43133 blueprint fixes

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/JacksonBlueprintProcessor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/FileSystemType.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/gcs/GcsFileSystemConfiguration.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/gcs/GcsFileSystemConfigurator.java
core/src/main/resources/scripts/gcs-connector.sh
core/src/main/resources/scripts/gcs-p12.sh
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/JacksonBlueprintProcessorTest.java
core/src/test/resources/blueprints/test-bp-with-core-site-properties-defaultfs.bp
core/src/test/resources/blueprints/test-bp-with-core-site-properties.bp

CLOUD-42393 gcs filesystem implementation

---

core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/StackDecorator.java

CLOUD-44354 fixed separation

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/PluginValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/ConsulHostCheckerTask.java
gradle.properties
integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakITContextConstants.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTestSuiteInitializer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CountRecipeResultsTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RecipeCreationTest.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/gcp/recipe/gcp-clustercreate-up.yaml

@martonsereg @schfeca75 plz review

CLOUD-42848 Recipe integration test

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/RecipeResponse.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToRecipeConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/RecipeToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/CloudbreakRecipeSetupException.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ConsulPluginManager.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/PluginManager.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/HostGroupDecorator.java

CLOUD-42849 Ability to restart pre-install/post-install phases

---

docs/index.md

@matyix plz review, and correct if necessary.

CLOUD-42845 Recipe documentation

---

core/src/main/resources/templates/launch-cluster-installer-mail-fail.ftl
core/src/main/resources/templates/launch-cluster-installer-mail-success.ftl
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderServiceTest.java

CLOUD-44527 added launch email templates

---

cloud-api/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
cloud-arm/src/test/java/com/sequenceiq/cloudbreak/cloud/arm/TestUtil.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/ReactorTestUtil.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/CloudbreakEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/CloudbreakEventsJson.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/StackResponse.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/CloudbreakEventToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToCloudbreakEventConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/notification/Notification.java
core/src/main/java/com/sequenceiq/cloudbreak/service/notification/NotificationAssemblingService.java
core/src/main/resources/schema/20150916144124_CLOUD-42849_ability_to_restart_recipes.sql
core/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/test/resources/com/sequenceiq/cloudbreak/converter/event/cloudbreak-event.json

CLOUD-42849 Missing cluster status at events

---

core/src/main/java/com/sequenceiq/cloudbreak/service/credential/SimpleCredentialService.java

CLOUD-44396 OpenStack credential cannot be deleted

---

integration-test/src/main/resources/testsuites/gcp/kerberos/gcp-clustercreate-startstop-updown.yaml

CLOUD-44698 Fix Kerberos integration test downscale

---

core/src/main/resources/init/init.ftl
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh

@akanto @biharitomi 
Should we open an issue in Docker?

CLOUD-44414 release udev cookies/semaphores if the udev-worker got killed

---

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmSetup.java

CLOUD-44707 use locally redundant storage accounts

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CountRecipeResultsTest.java

CLOUD-42848 Log missing cert file

---

docs/index.md

CLOUD-47753 dash documentation

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailMimeMessagePreparator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderServiceTest.java
core/src/test/resources/mail/provisioning-failure-email
core/src/test/resources/mail/provisioning-success-email
core/src/test/resources/mail/termination-failure-email
core/src/test/resources/mail/termination-success-email

@mhmxs please review
fixed email sending when termination success on new email template
launch-cluster-installer-mail-success
new tests are created:
testSendTerminationSuccessEmail
testSendTerminationFailureEmail
testSendProvisioningFailureEmail
testSendProvisioningSuccessEmail

CLOUD-44583 fixed email sending when termination success

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/json/BlueprintResponse.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/RecipeBase.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/RecipeResponse.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/RecipeToJsonConverter.java

@martonsereg There was a missing property in the API

CLOUD-42850 Make the recipe function available in Uluwatu

---

core/src/main/resources/schema/20150921144124_CLOUD-43504_load_recipe_from_consul.sql

@martonsereg Attila accepted this solution

CLOUD-43504 Remove obsolete recipe plugin primary key

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java

CLOUD-44323 added ability to define scopes

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackController.java
core/src/main/java/com/sequenceiq/cloudbreak/service/account/AccountPreferencesValidator.java

CLOUD-42525 fix validation of Peri scaling requests

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/GcpCredentialToJsonConverter.java

CLOUD-47755 return public key + service account key for gcp creds

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsConnector.java

@doktoric 
needed for EAR-2323

if asg could not be created do not resume scaling policies on delete

---

gradle.properties
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/StackCreationTest.java
integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate-native.yaml

CLOUD-43947: Native OpenStack integrationtest

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/FileSystemType.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasb/WasbFileSystemConfiguration.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasb/WasbFileSystemConfigurator.java

@keyki 
simple WASB filesystem without dash - can be useful for small test clusters and PoCs

CLOUD-47753 simple wasb fs implementation

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/BlueprintProcessor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/JacksonBlueprintProcessor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/AbstractFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/FileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/dash/DashFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/gcs/GcsFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasb/WasbFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasbintegrated/WasbIntegratedFileSystemConfigurator.java
core/src/main/resources/defaults/blueprints/datadeveloper.bp
core/src/main/resources/defaults/blueprints/datascientist.bp
core/src/main/resources/defaults/blueprints/operations.bp
core/src/main/resources/defaults/blueprints/streaming.bp
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/JacksonBlueprintProcessorTest.java

CLOUD-45188 re-configure HBase with default FS

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/FileSystemConfiguration.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/dash/DashFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasb/WasbFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasbintegrated/WasbIntegratedFileSystemConfigurator.java

CLOUD-45390 create new storage container for every cluster

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleStackFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderService.java
core/src/main/resources/templates/launch-cluster-installer-mail-success.ftl
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderServiceTest.java
core/src/test/resources/mail/provisioning-success-email
core/src/test/resources/mail/termination-failure-email
core/src/test/resources/mail/termination-success-email

CLOUD-44583 add cluster name to notification email and fix it's messages

---

cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceDeleteThread.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/network/NetworkResourceService.java

CLOUD-45457: Deletes only CloudResources with CREATED states

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/AbstractFileSystemConfigurator.java

CLOUD-45398 set data folder for non-HDFS filesystems

---

docs/index.md

CLOUD-44393 fixed eclipse formatter url

---

core/src/main/java/com/sequenceiq/cloudbreak/service/securitygroup/DefaultSecurityGroupCreator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/securitygroup/SimpleSecurityGroupService.java

@doktoric or @biharitomi pls review

CLOUD-45144: securitygroup save fix

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/InstanceTemplate.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/notification/PersistenceNotifier.java
cloud-aws/build.gradle
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/cache/CachingConfig.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsCredentialView.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClientTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/TestContext.java
cloud-aws/src/test/resources/templates/aws-cf-stack.ftl
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/notification/ResourceNotifier.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/CredentialController.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/aws/AwsCredentialHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/CredentialDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderCredentialAdapter.java
core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/CredentialDecoratorTest.java

CLOUD-45388 aws module, credential handling

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/SecurityGroup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/securitygroup/SimpleSecurityGroupService.java

@akanto or @biharitomi pls review

CLOUD-45144: CascadeType.Persist added to SecurityGroup.securityRules member

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/notification/model/ResourceNotification.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/notification/ResourceNotifier.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/reactor/config/CloudReactorInitializer.java
core/src/main/java/com/sequenceiq/cloudbreak/logger/LogContextAspects.java
core/src/main/java/com/sequenceiq/cloudbreak/service/eventbus/CloudResourcePersisterService.java

@biharitomi or @akanto pls review

CLOUD-45304: ResourcePersistenceHandler's log aspect added

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/context/CloudContext.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudCredential.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmUtils.java
cloud-arm/src/test/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateBuilderTest.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
cloud-openstack/src/test/java/com/sequenceiq/cloudbreak/ReactorApplication.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/ParameterGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/CredentialToCloudCredentialConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderConnectorAdapter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderMetadataAdapter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderSetupAdapter.java

@akanto plz review. ArmUtils.119 and  GcpStackUtil.65 are the important parts

CLOUD-45450 Cleanup CloudContext

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/json/SecurityGroupJson.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/SecurityRuleJson.java

CLOUD-45516: server side security rule validation

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java

CLOUD-43945 update to Ambari 2.1.2

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/AbstractFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/FileSystemConfiguration.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/FileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/dash/DashFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/gcs/GcsFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasb/WasbFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasbintegrated/WasbIntegratedFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java

CLOUD-45604 modify integrated WASB filesystem to delete storage accounts at termination

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/BlueprintProcessor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/JacksonBlueprintProcessor.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/JacksonBlueprintProcessorTest.java
gradle.properties

CLOUD-45463 instantiate default views

---

core/src/main/resources/scripts/gcs-connector.sh

CLOUD-45389 fixed connector file name

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java

CLOUD-45604 fix filesystem resource  deletion in case of termination

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/aws/AwsMetadataSetup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureMetadataSetup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/CoreInstanceMetaData.java

CLOUD-45815 Duplicate InstanceMetadata entries on aws after start

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/resources/scripts/hdfs-home.sh

CLOUD-45462 create admin user home dir on HDFS

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleFlowFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java

CLOUD-45817 NonUniqueResultException: result returns more than one elements during upscale

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/InstanceStatus.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/InstanceMetaDataToCloudInstanceConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetadataService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java

CLOUD-42470 Cluster sync fails when containers hasn't started on newly provisioned VM(s)

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/AzureVmType.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToAzureTemplateConverter.java

CLOUD-45976 introduce V2 instance types for Azure

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/InstanceMetaData.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java

CLOUD-42470 Handle CREATED status during upscale

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/InstanceMetaData.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackScalingService.java

CLOUD-42470 Handle CREATED status during downscale

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java

CLOUD-46114 refactored key importing on aws

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpReservedIpResourceBuilder.java

CLOUD-46111 GCP global Address no longer accepts region as parameter

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DynamicModel.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/service/GcpResourceNameServiceTest.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackResourceConnector.java
cloud-reactor/src/test/resources/logback-test.xml
core/src/test/resources/logback-test.xml
orchestrator-swarm/src/test/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestratorTest.java

BUG-46096 Cleanup build warnings

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
config/checkstyle/checkstyle-suppressions.xml
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/azure/AzureStackUtil.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/ContainerOrchestrator.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java

CLOUD-46117 some supressions cleaned up

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/FixedDefaultConfigProvider.java

CLOUD-46191 increase ZK connection retry for HBase

---

cloud-api/build.gradle
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/service/CloudbreakResourceNameService.java
cloud-arm/build.gradle
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmUtils.java
cloud-aws/build.gradle
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationStackUtil.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/ResourceType.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/GcpResourceNameService.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/service/GcpResourceNameServiceTest.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/HeatTemplateBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/service/OpenStackResourceNameService.java
cloud-reactor/build.gradle

CLOUD-44977 new function for trimming the resource name, environment variables and unit tests updated

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java

@doktoric i found one more place where need to handle created status. Plz review

CLOUD-42470 Handle created status during sync

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/context/GcpContextBuilder.java

CLOUD-46246: if no location given in cloudcontext, region will be null

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSessionCredentialClient.java

CLOUD-46247 Invalid AWS credential cacheing

---

core/src/main/resources/init/init.ftl
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh

CLOUD-46097 Remove unnecessary touch

---

cloud-api/build.gradle
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudStack.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/DynamicModel.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Group.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Image.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/InstanceTemplate.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Network.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Security.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Subnet.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackResourceConnector.java
cloud-openstack/src/test/java/com/sequenceiq/cloudbreak/ReactorApplication.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/ParameterGenerator.java
cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/testcontext/TestApplicationContext.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/CloudFailureHandler.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceService.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java

@schfeca75, @akanto @doktoric @keyki plz review

CLOUD-46124 Openstack doesn't remove instance during downscale

---

core/src/main/resources/init/init.ftl
core/src/main/resources/init/tls-setup.sh
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh

CLOUD-46097 Bump MAX_RETRIES if docker relocating is active

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Cluster.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/core/init/CloudbreakInitStates.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java

CLOUD-46107 Wait for sync on UPDATE_REQUESTED status

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceConnector.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/ResourceType.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpFirewallInResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpFirewallInternalResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpNetworkResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpReservedIpResourceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/context/OpenStackContext.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/network/AbstractOpenStackNetworkResourceBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractInstanceConnector.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/ComputeResourceBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/NetworkResourceBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/OrderedBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/ResourceChecker.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/ResourceContextBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/network/NetworkResourceService.java

CLOUD-46413 SPI resource builder documentation

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/AzureRmCredentialToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/OpenSshPublicKeyValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderCredentialAdapter.java

Make SPI credential management to handle password based authentication

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetadataService.java

@keyki plz review
During upscale CB updated all CREATED status to UNREGISTERED instead of update only upscale candidates

CLOUD-42470

---

core/src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java

CLOUD-46477 fixed termination problem

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/ProvisioningSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/PollingService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ConsulPluginManager.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasbintegrated/WasbIntegratedFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/ConsulMetadataSetup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackScalingService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnectorTest.java

CLOUD-46696: poll with fault tolerance in case of image copy status check

---

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmResourceConnector.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmSetup.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateBuilder.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmUtils.java
cloud-arm/src/main/resources/templates/arm-v2.ftl

CLOUD-45139 separated storage for attached disks

---

cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/resource/UpscaleStackResult.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderConnectorAdapter.java

CLOUD-46802: start with the validation of the spi upscale result in ServiceProviderAdapter.addInstances()

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/MailSenderConfig.java

CLOUD-46740 configurable mail sending

---

core/src/main/resources/scripts/dash-local.sh

@keyki 
spark works out-of-the-box even in yarn-cluster mode with dash with this change

CLOUD-46418 add azure jars to SPARK_CLASSPATH

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariOperationsStatusCheckerTask.java

CLOUD-47009 added ambari progress

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java

@keyki pls review, do not merge until all the azure image upload jobs are finished in jenkins.

CLOUD-46700: new cloud provider images with fix kernel and systemd versions and docker 1.8.3

---

core/src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java

CLOUD-46477 null check for Cloudbreak events

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/network/ExposedService.java

@biharitomi 
It doesn't make sense to return those service endpoints that doesn't have a UI.

Do not show services on uluwatu that doesn't have a UI

---

core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/DefaultBlueprintLoaderService.java

CLOUD-47022 create default blueprints for every user

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java

CLOUD-47138 AmbariOperationFailedException during upscale is not handled

---

build.gradle

@doktoric 
further complication of the release strategy....

release failed on master when master is ff-merged to rc

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java

CLOUD-47424 Avoid IllegalFormatConversionException

---

orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java

CLOUD-47602 use private IP for consul join

---

integration-test/src/main/java/com/sequenceiq/it/util/RestUtil.java

CLOUD-43757 apply changes that are required by upgrading UAA to 2.7.1

---

core/src/main/resources/init/init.ftl

CLOUD47694 Run ssh alias creation

---

core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh

CLOUD47694 Run ssh alias creation - test fix

---

cloud-openstack/build.gradle
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/auth/OpenStackClient.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/view/KeystoneCredentialView.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/OpenStackCredential.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/CredentialParametersValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/OpenStackCredentialParam.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToOpenStackCredentialConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/OpenStackCredentialToJsonConverter.java
core/src/main/resources/schema/20151027185309_schema_changes_for_keystone_v3.sql
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/CredentialParametersValidatorTest.java

Keystone v3 support for credential management (implemented by vivekpm)

---

core/src/main/java/com/sequenceiq/cloudbreak/service/user/RemoteUserDetailsService.java

CLOUD-47693 fixed user delete

---

gradle.properties

CLOUD-47608 Update ambari rest client

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java

@schfeca75 
```yaml
aws:
ap-northeast-1: ami-4ea78120
ap-southeast-1: ami-babd7bd9
ap-southeast-2: ami-9188d6f2
eu-central-1: ami-1cedfe70
eu-west-1: ami-24a47c57
sa-east-1: ami-6408b308
us-east-1: ami-2393ed49
us-west-1: ami-4af49b2a
us-west-2: ami-203c2a41
```

CLOUD-45609 add aws images built by packer

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/MailSenderConfig.java

CLOUD-46704 boolean type convertion fix

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SecurityGroupCreationTest.java

CLOUD-46100: Open resourcemanager port in restricted secgroup because of downscale

---

config/checkstyle/checkstyle-suppressions.xml
core/src/main/java/com/sequenceiq/cloudbreak/concurrent/ConcurrentMethodExecutionAspect.java
core/src/main/java/com/sequenceiq/cloudbreak/concurrent/GuardedMethod.java
core/src/main/java/com/sequenceiq/cloudbreak/concurrent/LockedMethod.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleFlowFacade.java

CLOUD-46808: introducing guarded/locked method execution

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/MailSenderConfig.java

CLOUD-46704 configurable smtp type

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleStackFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java

@akanto or @biharitomi pls review

CLOUD-48044: during upscale sync doesn't change the stack status

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/SecurityGroupCreationTest.java
integration-test/src/main/resources/testsuites/aws/smoke/aws-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/azurerm/smoke/azurerm-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/gcp/smoke/gcp-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/nativeos/smoke/nativeos-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/openstack/smoke/openstack-clustercreate-startstop-updown.yaml

CLOUD-47925 set connetcion timeout to 3 secs

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/CloudbreakUsageToJsonConverter.java

CLOUD-48185 fixed usage generation when user deleted

---

core/src/main/resources/defaults/templates/minviable-aws.tmpl
core/src/main/resources/defaults/templates/minviable-gcp.tmpl

CLOUD-47850 Refactor disk types, fix default templates

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleStackFacade.java

CLOUD-48284 fix infrastructure start failed message

---

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/view/ArmInstanceView.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsInstanceView.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/util/JsonUtil.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/view/NovaInstanceView.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/json/Json.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/JsonHelper.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/StackServiceComponentDescriptorMapFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToBlueprintConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/HadoopConfigurationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/filter/AppMasterFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/JacksonBlueprintProcessor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/template/SimpleTemplateLoaderService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/RemoteUserDetailsService.java
core/src/main/java/com/sequenceiq/cloudbreak/util/AmbariClientExceptionUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/AbstractJsonConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToBlueprintConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/JacksonBlueprintProcessorTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RecipeCreationTest.java

CLOUD-46397 JsonUtil for ObjectMapper

---

build.gradle

@doktoric @lalyos @akanto @biharitomi @schfeca75 @martonsereg @matyix 
mavenLocal() would be nice by default

CLOUD-47781 Maven local repo to build.gradle

---

integration-test/src/main/resources/testsuites/resourcetests.yaml

CLOUD-47850 Refactor disk types, fix resource tests in integration test

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/credential/CredentialVerificationException.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/CredentialVerificationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderCredentialAdapter.java

CLOUD-46247 Invalid AWS credential cacheing, improve error message

---

core/build.gradle

CLOUD-48384 sshj 0.15 is released

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariOperationsStatusCheckerTask.java

CLOUD-48441 NullPointer during Ambari operation status check

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleFlowFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleStackFacade.java
core/src/main/resources/messages/messages.properties

CLOUD-45111 Uluwatu Cloud stack description doesn't refresh

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTestSuiteInitializer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ScalingTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/StackCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/StatusUpdateTest.java

CLOUD-48614: itest fix for cluster scaling

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackAttachedDiskResourceBuilder.java

CLOUD-42393: using synced list during attached disks creation.

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/resources/messages/messages.properties

CLOUD-45683 restart Ambari agents during cluster reset

---

integration-test/src/main/resources/testsuites/azurerm/smoke/azurerm-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/azurerm/smoke/azurerm-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/azurerm/smoke/azurerm-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/azurerm/smoke/azurerm-clustercreate.yaml

Change azure itest region because of quota limit

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/HostGroup.java

CLOUD-49049 Wrong JPA relation between HostGroup and InstanceGroup

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java

CLOUD-48935 fixed arm buckets

---

gradle.properties

CLOUD-48916 update cb client version due to template API change

---

core/src/main/java/com/sequenceiq/cloudbreak/core/init/CloudbreakInitStates.java

CLOUD-49205 Handle DELETE_IN_PROGRESS status during Cloudbreak start

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/BlueprintValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/StackServiceComponentDescriptor.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/StackServiceComponentDescriptorMapFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/BlueprintValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverterTest.java

@schfeca75 plz review
- fixed blueprint validation tests
- validate node and component counts during scale

CLOUD-48805 Validate blueprint during up and downscale

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/TemplateBase.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/TemplateRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/ValidTemplate.java

CLOUD-49029 generic validator based on platform variants for template

---

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmPlatformParameters.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackParameters.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/TemplateBase.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateValidator.java

CLOUD-49029 fix the validation of generic templates

---

gradle.properties
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/OpenStackCredentialCreationTest.java

CLOUD-48917 increase rest client version

---

core/src/main/resources/defaults/blueprints/hdp-multinode-default.bp
core/src/main/resources/defaults/blueprints/multi-node-hdfs-yarn.bp
core/src/test/resources/blueprints/test-bp-invalid.bp
core/src/test/resources/blueprints/test-bp-with-core-site-properties-defaultfs.bp
core/src/test/resources/blueprints/test-bp-with-core-site-properties.bp
core/src/test/resources/blueprints/test-bp-with-core-site.bp
core/src/test/resources/blueprints/test-bp-with-empty-config-block.bp
core/src/test/resources/blueprints/test-bp-without-config-block.bp
core/src/test/resources/com/sequenceiq/cloudbreak/converter/stack/ambari-blueprint.json
core/src/test/resources/com/sequenceiq/cloudbreak/converter/stack/blueprint.json
integration-test/src/main/resources/blueprint/hdp-multinode-default.bp
integration-test/src/main/resources/blueprint/multi-node-hdfs-yarn.bp

CLOUD-49480 Update stack version in blueprints

---

.gitignore
cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-common/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml
core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageNameUtil.java

CLOUD-46419 cloud images are separated

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderService.java

CLOUD-49681 Typo in the 'Cloudbreak Cluster Downscale Success' email

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseMigrationConfig.java

CLOUD-48457 modify database migration to run pending scripts too

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AzureRmCredentialCreationTest.java

CLOUD-48917 integationtest fix: remove base64 encode from the test

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java

CLOUD-50579 NullPointerException during termination and a missing flow transition

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/APIResourceType.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Topology.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/TopologyRecord.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/ApiDocConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/TopologyController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/doc/ControllerDescription.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/doc/Notes.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/TopologyBase.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/TopologyRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/TopologyResponse.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToTopologyConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/TopologyToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/TopologyRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/topology/SimpleTopologyService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/topology/TopologyService.java
core/src/main/resources/schema/20151216134710_CLOUD-49844_Ability_to_store_Cloud_Platform_topology_in_Cloudbreak.sql

CLOUD-49844 Ability to store Cloud Platform topology in Cloudbreak

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/AccountPreferences.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/AccountPreferencesController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/json/AccountPreferencesJson.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/AccountPreferencesToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToAccountPreferencesConverter.java
core/src/main/resources/schema/20160107154621_CLOUD-49847_Show_only_one_type_of_platform.sql

CLOUD-49847 Show only one type of platform

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow2Handler.java

CLOUD-50969 Fix NPE at Flow2Handler.accept()

---

core/src/main/java/com/sequenceiq/cloudbreak/service/TlsSecurityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java

CLOUd-50690 Fix cert file path in services

---

core-api/build.gradle
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ClusterEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/CredentialEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/NetworkEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/RecipeEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SecurityGroupEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/StackEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SubscriptionEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/TemplateEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UserEndpoint.java

@akanto pls review
The validation on the request objects missing this pr fixing the problem.

CLOUD-46290 fixed validation

---

autoscale/src/main/java/com/sequenceiq/periscope/config/DatabaseMigrationConfig.java

Fix periscope database migrations script default location in source code

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/InstanceMetaData.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
gradle.properties

CLOUD-49845 Send rack infor to Ambari

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java

CLOUD-50855 fix IT for status check

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariOperationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariOperations.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariOperationsRequestCheckerTask.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnectorTest.java

CLOUD-50855 upscale cluster w/ blueprint request

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverterTest.java

CLOUD-51200 remove nagios and ganglia operations

---

integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/logback.xml

@bbihari or @biharitomi pls review

CLOUD-50744 TestNG output directory can be set by environment variable

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AzureTemplateCreationTest.java

CLOUD-51308 itest used wrong cloudplatform

---

autoscale/build.gradle
cloud-arm/build.gradle
cloud-aws/build.gradle
cloud-gcp/build.gradle
cloud-reactor/build.gradle
cloud-template/build.gradle
core-api/build.gradle
core/build.gradle
gradle.properties
integration-test/build.gradle

CLOUD-51308 remove jee dependencies

---

core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakClient.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/IdentityClient.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/RestClient.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/config/ConfigKey.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/security/CertificateTrustManager.java
integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTestSuiteInitializer.java
integration-test/src/main/resources/logback.xml

@schfeca75 replacing cache loader with homegrown cache

CLOUD-51308 replace cache loader

---

core-api/build.gradle
core-api/src/main/java/com/sequenceiq/cloudbreak/client/RestClient.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/security/CertificateTrustManager.java

@schfeca75 
apache http client config for proper ssl handling. tested with
- plain http
- valid certificate (with and without security)
- invalid certificate  (with and without security)

CLOUD-51308 use apache http client instead of HTTPS url connection

---

config/checkstyle/checkstyle-suppressions.xml
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/BlueprintCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/SecurityGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ShellConfiguration.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/OutPutType.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/util/CloudbreakUtil.java

CLOUD-51472 added metadata show

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudInstanceMetaData.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpMetadataCollector.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/GetSSHFingerprintsHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/StackCreationEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java

CLOUD-49291 NullPointerException during collect metadata on gcp

---

cloud-arm/src/main/resources/templates/arm-v2.ftl
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderConnectorAdapter.java

CLOUD-46890 enable boot diagnostics log on Azure vms

---

gradle.properties
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java

CLOUD-51632 added ssh key as raw string parameter

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java

CLOUD-51562 remove invalid AWS regions

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/BlueprintCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/HostGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/InstanceGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/SecurityGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/transformer/ExceptionTransformer.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/BlueprintCommandsTest.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommandsTest.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommandsTest.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommandsTest.java

CLOUD-51636 fixed shell execution states

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java

BUG-51692 fixed azure credential creation

---

.gitignore

CLOUD-51700 Gitignore filters out every test folder

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/CloudbreakContext.java

CLOUD-51702 fixed stack creation command

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderConnectorAdapter.java

CLOUD-0000 remove unsude code

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/TopologyEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakClient.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/TopologyController.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToTopologyConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/topology/TopologyService.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TopologyCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/util/TopologyUtil.java

CLOUD-51620 Implement topology feature in cb shell

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java

CLOUD-51754 fixed cluster create command

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/SshCheckerTask.java

CLOUD-51757 Update to Docker 1.9.1 and overlay fs

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpFirewallInResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpFirewallInternalResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpNetworkResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpReservedIpResourceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackConstants.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackUtils.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/HeatTemplateBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackResourceConnector.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/network/OpenStackNetworkResourceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/network/OpenStackRouterResourceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/network/OpenStackSecurityGroupResourceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/network/OpenStackSubnetResourceBuilder.java
cloud-openstack/src/main/resources/templates/openstack-heat.ftl
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/NetworkResourceBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/network/NetworkResourceService.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java

@akanto 
Required parameters for custom network:
* networkId
* routerId

Allow custom network for openstack

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CleanupService.java

CLOUD-51750 prevent parallel cleanups

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CleanupService.java

CLOUD-51750 cleanup run only once

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TopologyCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/Hints.java

CLOUD-51768 SHELL: 'topology' related hints are missing

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java

CLOUD-43617 re-use existing subnet on AWS with subnetId param

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/StackCommandsTest.java

CLOUD-51935 added wait for stack termination

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/AbstractGcpResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpFirewallInResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpFirewallInternalResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpNetworkResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/network/GcpReservedIpResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackUtils.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/network/AbstractOpenStackNetworkResourceBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/NetworkResourceBuilder.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/network/NetworkResourceService.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java

CLOUD-43941 gcp allow custom network

---

cloud-aws/src/main/resources/aws-images.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml

WIP: waiting for azure to finish copy ...

CLOUD-50462 use cloudbreak images built on base image

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Topology.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToTopologyConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/TopologyToJsonConverter.java
core/src/main/resources/schema/20160203101357_CLOUD-52010_Remove_endpoint_field_from_topology.sql

CLOUD-52010 Remove endpoint field from topology

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java

CLOUD-51940 fixed credential create command

---

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateBuilder.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmUtils.java
cloud-arm/src/main/resources/templates/arm-v2.ftl
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java

CLOUD-43617 re-use existing network and subnet for Azure

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ShellConfiguration.java

CLOUD-52131 remove 'shell.' prefix from the message

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java

CLOUD-43617 fix ARM custom network shell command

---

cloud-arm/src/main/resources/templates/arm-v2.ftl

CLOUD-43617 do not create security group in case of existing subnet

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TopologyCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/util/TopologyUtil.java

CLOUD-52114 SHELL: Rename 'topology' to 'platform' conform to GUI

---

cloud-arm/src/main/resources/templates/arm-v2.ftl

Revert "CLOUD-43617 do not create security group in case of existing subnet"

---

cloud-common/src/main/resources/application.yml
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/template/DefaultTemplateLoaderService.java

CLOUD-52267 Typo problem around cb.template.defaults variable

---

config/checkstyle/checkstyle-suppressions.xml
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/util/CloudbreakShellUtil.java

CLOUD-52270 wait result should throw exception when poller failed

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceConnector.java
cloud-common/src/main/resources/application.yml
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/VerboseHostKeyVerifier.java

CLOUD-52336 configurable host key verification on AWS

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnectorTest.java

CLOUD-52262 log generated blueprint

---

cloud-aws/build.gradle
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceType.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java
cloud-aws/src/main/resources/aws-images.yml

CLOUD-51691 Uluwatu: 'Seoul' is missing from AWS regions

---

cloud-common/src/main/resources/application.yml
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunner.java

CLOUD-48264 Set default LDAP user to ambari-qa

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java

CLOUD-52269 fixed command return message

---

autoscale/src/main/java/com/sequenceiq/periscope/config/AppConfig.java
autoscale/src/main/java/com/sequenceiq/periscope/service/security/RemoteUserDetailsService.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/IdentityClient.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/RestClient.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/filter/AppMasterFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/notification/HttpNotificationSender.java
core/src/main/java/com/sequenceiq/cloudbreak/service/user/RemoteUserDetailsService.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ShellConfiguration.java

CLOUD-51844 Replace RestTemplate to Jersey client

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java

CLOUD-52282 capability to load images from /etc/cloudbreak

---

cloud-common/src/main/resources/application.yml
core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ContainerConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/network/ExposedService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/network/NetworkUtils.java
core/src/main/java/com/sequenceiq/cloudbreak/service/securitygroup/DefaultSecurityGroupCreator.java
core/src/main/resources/schema/20160209141039_CLOUD-52199_7070_added_to_open_ports.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverterTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/containers/DockerContainer.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/ContainerConstraint.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/ContainerName.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/SwarmContainerOrchestrator.java
orchestrator-swarm/src/main/java/com/sequenceiq/cloudbreak/orchestrator/swarm/containers/SwarmContainerBootstrap.java

@akanto 
This pr contains two new container which running on the cbgateway. Read more about shipyard here: https://shipyard-project.com/

CLOUD-52199 added shipyard to gateway instance

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java

CLOUD-52274 fixed stack show command

---

autoscale/src/main/java/com/sequenceiq/periscope/config/AppConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java

CLOUD-52519 fixed identity url

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CleanupService.java

CLOUD-51750 recipe cleanup added

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsAuthenticator.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsCredentialView.java
cloud-aws/src/main/resources/definitions/aws-credential.json
core/src/main/resources/schema/20160212070234_CLOUD-52524_include_selector_in_aws_credentials.sql
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AwsCredentialCreationTest.java
integration-test/src/main/resources/application.yml
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java

@akanto @schfeca75 @doktoric 
UI change is ready as well

CLOUD-52524 support access and secret based authentication on AWS

---

cloud-common/src/main/resources/application.yml
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/SssdConfigBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/SssdSchemaType.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/SssdTlsReqcert.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/SssdConfig.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToSssdConfigConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/SssdConfigToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sssdconfig/SssdConfigService.java
core/src/main/resources/schema/20160211094219_CLOUD-48264_more_ssssd_options.sql
core/src/test/resources/com/sequenceiq/cloudbreak/converter/stack/sssd_config.json
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/SssdConfigCommands.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/SssdConfigCommandsTest.java

CLOUD-48264 More SSSD options

---

cloud-common/src/main/resources/application.yml

CLOUD-48264 fix ambari reset

---

cloud-common/src/main/resources/application.yml
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/SssdConfigBase.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/resources/schema/20160212094219_CLOUD-48264_unlock_ssd_config_stict_nulls.sql
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/SssdConfigCommands.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/SssdConfigCommandsTest.java

@keyki plz review
contains ability to upload SSSD config file via shell, and stores in Consul during start

CLOUD-48264 Upload SSSD config

---

cloud-common/src/main/resources/application.yml
core/src/main/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilder.java
core/src/main/resources/init/init.ftl
core/src/test/java/com/sequenceiq/cloudbreak/service/image/UserDataBuilderTest.java
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh

add modified application.yml to ./config dir
you probably need a `-v ./config:/config` for the cloudbreak container

CLOUD-45292: make user-data script configurable, without code change

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/SssdConfigBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/SssdProviderType.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/SssdConfigCommands.java

CLOUD-48264 Some validation and a new provider type

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunner.java

CLOUD-52680 mount /hadoopfs instead of individual folders

---

core/build.gradle
gradle.properties
integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CountRecipeResultsTest.java
integration-test/src/main/resources/application.yml

CLOUD-52738 Fix connection timeout

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/SssdConfigBase.java

CLOUD-48264 Fix SSSD config validation

---

gradle.properties

CLOUD-50248 if security block is defined only change the type

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SettingsEndpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/SettingsController.java

CLOUD-52775 Enum options API endpoint

---

core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/BlueprintValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/HostGroupToJsonEntityConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToClusterConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToHostGroupConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunnerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ContainerOrchestratorResolverTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/DummyContainerOrchestrator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow/ReactorFlowManagerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnectorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventServiceTest.java
core/src/test/resources/com/sequenceiq/cloudbreak/converter/stack/host-group.json
core/src/test/resources/com/sequenceiq/cloudbreak/converter/stack/stack.json
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/HostGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/InstanceGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/CloudbreakContext.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/HostgroupEntry.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/support/TableRenderer.java

CLOUD-52752 fixed shell and unit tests

---

cloud-common/src/main/resources/application.yml

CLOUD-48264 Update consul watch container

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/SssdConfigBase.java

CLOUD-52775 Remove size limitation of SSSD config

---

cloud-common/src/main/resources/application.yml

CLOUD-52680 ambari 2.2.1.1 build 29

---

cloud-common/build.gradle

CLOUD-52900 duplicated Consul client on the classpath

---

.gitignore
auth/Makefile

CLOUD-52969 Add makefile to auth to trigger docker image building on dockerhub

---

core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakClient.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/BlueprintCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/HostGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/InstanceGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/MarathonCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/SecurityGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TopologyCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/completion/ConstraintName.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ConverterConfiguration.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/converter/ConstraintNameConverter.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/CloudbreakContext.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/Focus.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/FocusType.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/Hints.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/HostgroupEntry.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/MarathonContext.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/BlueprintCommandsTest.java

CLOUD-52971 added support for mesos into cloudbreak shell

---

web/Makefile

CLOUD-53134 docker build for cloudbreak-web

---

core/src/main/java/com/sequenceiq/cloudbreak/service/subscription/SubscriptionService.java

CLOUD-53131 Replace SubscriptionAlreadyExistException to logging

---

cloud-common/src/main/resources/application.yml
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpInstanceConnector.java

Please review it @akanto or @schfeca75 !

CLOUD-53136 make host key verification be configurable in case of GCP

---

cloud-aws/src/main/resources/aws-images.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml

CLOUD-53136 update images with pre-pulled containers

---

cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/GetSSHFingerprintsHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/CloudPlatformResponseToFlowFailureConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/StackCreationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/StackCreationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationFailureAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationService.java

CLOUD-53143 metadata and ssh fingerprint collection errorhandling fix on the flow

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/aws-images.tmpl
cloud-openstack/src/main/resources/os-images.yml

CLOUD-52916: update images

---

core/src/main/java/com/sequenceiq/cloudbreak/service/notification/HttpNotificationSender.java

CLOUD-53144 add content-type header to notification posts

---

core/src/main/java/com/sequenceiq/cloudbreak/service/notification/HttpNotificationSender.java

CLOUD-53144  use media type for application/json

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariDecommissioner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RSDecommissionStatusCheckerTask.java
gradle.properties

CLOUD-53068 wait for HBase decommission request

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

CLOUD-53287 fixed stopped services

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/AbstractAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationFailureAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/sync/StackSyncFailedAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationFailureAction.java

CLOUD-53143 exception logging in flow

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-common/src/main/resources/application.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml

CLOUD-52680 ambari 2.2.1.1 build 48

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/util/JsonUtil.java
cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/platform/ResourceDefinitionResult.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

@doktoric 
instead of printing in the log this:
```
{
"values": [
{
"name": "userName",
"type": "String",
"encrypted": true
},
{
"name": "password",
"type": "String",
"encrypted": true
},
{
"name": "endpoint",
"type": "String"
},
{
"name": "keystoneVersion",
"type": "String"
}
],
"selectors": [
{
"name": "cb-keystone-v2",
"values": [
{
"name": "tenantName",
"type": "String"
}
]
},
{
"name": "cb-keystone-v3",
"values": [
{
"name": "userDomain",
"type": "String"
},
{
"name": "keystoneAuthScope",
"type": "String"
}
]
},
{
"name": "cb-keystone-v3-default-scope",
"parent": "cb-keystone-v3",
"values": []
},
{
"name": "cb-keystone-v3-domain-scope",
"parent": "cb-keystone-v3",
"values": [
{
"name": "domainName",
"type": "String"
}
]
},
{
"name": "cb-keystone-v3-project-scope",
"parent": …
```

CLOUD-52524 minify json log

---

web/app/static/css/Admin.min.css
web/app/static/css/Cloudbreak.min.css

CLOUD-51772 Platform button bottom border fix

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

CLOUD-53287 fixed start services

---

cloud-common/build.gradle

@keyki 
releasing build of https://github.com/sequenceiq/spring-cloud-consul/commit/abc1a177663c140fec03eb1d48b755798b1018d2 into s3 as `M6-v2`

CLOUD-52281: fixing https://github.com/spring-cloud/spring-cloud-consul/issues/137

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-common/src/main/resources/application.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml

fixed functions

---

Makefile
auth/Gruntfile.js
auth/app/confirm.html
auth/app/dashboard.html
auth/app/login.html
auth/app/regacc.html
auth/app/register.html
auth/app/reset.html
auth/build.gradle
auth/format.sh
auth/mailer.js
auth/main.js
auth/package.json
auth/public/css/style.css
auth/public/js/app.js
config/jsbeautifyrc
web/Gruntfile.js
web/app/static/css/Admin.min.css
web/app/static/css/Cloudbreak.min.css
web/app/static/css/cloudbreak-custom.css
web/app/static/css/roboto.css
web/app/static/js/controllers/clusterController.js
web/app/static/tags/stack/configuresecuritygroup.tag
web/build.gradle
web/format.sh
web/package.json

Beatifying

---

web/app/static/js/controllers/clusterController.js
web/app/static/js/controllers/notificationController.js
web/app/static/tags/stack/activecluster.tag
web/app/static/tags/stack/clusterlistpanel.tag

CLOUD-53440 Enable to click on Cluster when termination in progress

---

cloud-arm/src/main/resources/arm-images.yml

@lalyos these are the links of the uploaded images

CLOUD-52680 azure images

---

cloud-arm/src/main/resources/arm-images.yml

Reverts sequenceiq/cloudbreak#1365

Revert "CLOUD-52680 azure images"

---

integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate.yaml
integration-test/src/main/resources/testsuites/azurerm/credandsmoke/azurerm-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/azurerm/credandsmoke/azurerm-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/azurerm/credandsmoke/azurerm-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/azurerm/credandsmoke/azurerm-clustercreate.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate.yaml
integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate.yaml

CLOUD-52766 shorten stack and cluster names

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/CloudbreakEventsJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/CloudbreakEvent.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/CloudbreakEventToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToCloudbreakEventConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariOperationsStatusCheckerTask.java
core/src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/notification/Notification.java
core/src/main/java/com/sequenceiq/cloudbreak/service/notification/NotificationAssemblingService.java
core/src/main/java/com/sequenceiq/cloudbreak/websocket/UptimeNotifier.java
core/src/main/resources/schema/app/20160229100932_CLOUD-53353_evenpanel_fix.sql
core/src/test/resources/com/sequenceiq/cloudbreak/converter/event/cloudbreak-event.json
web/app/static/js/controllers/clusterController.js

CLOUD-53353 fixed events on ui

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariDecommissioner.java

@doktoric @biharitomi 
If few nodes are dead it's not possible to start the service.

CLOUD-52922 failing service start in case of dead nodes

---

web/app/static/js/controllers/clusterController.js

CLOUD-50403 fixed hostmetadata state filter

---

web/app/static/js/controllers/clusterController.js

CLOUD-50403 beautify js

---

web/app/static/tags/templatepanel.tag

@biharitomi I did not create a separated record for delete label in case of constraint because the meaning of the label is same as template deletion.

CLOUD-53587 fixed label in template deletion

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToCredentialConverter.java

CLOUD-48917 fix login user name in key based ec2 credential

---

Makefile

CLOUD-53594 added js beautify deps

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ContainerConstraintFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ContainerService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunnerTest.java
orchestrator-marathon/src/main/java/com/sequenceiq/cloudbreak/orchestrator/marathon/MarathonContainerOrchestrator.java

@keyki or @doktoric 
Changes:
- refactor container constraint creation into an individual class from ClusterContainerRunner.java
- black list mesos slaves where an ambari agent has already been deployed

Marathon constraints

---

orchestrator-marathon/src/main/java/com/sequenceiq/cloudbreak/orchestrator/marathon/MarathonContainerOrchestrator.java

CLOUD-53510 black list used mesos slaves for upscale

---

orchestrator-marathon/src/main/java/com/sequenceiq/cloudbreak/orchestrator/marathon/MarathonContainerOrchestrator.java

Reverts sequenceiq/cloudbreak#1379
@doktoric

Revert "CLOUD-53510 black list used mesos slaves for upscale"

---

web/app/static/js/console.UI.js
web/app/static/js/controllers/notificationController.js

CLOUD-53665 fixed carousel on ui

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunner.java

CLOUD-53670 check the cancellation of pollers at bootstrap

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java

CLOUD-45825 add config strategy to shell

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/BlueprintCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/HostGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/MarathonCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/SecurityGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/SssdConfigCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TopologyCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/HostgroupEntry.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/MarathonContext.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/MarathonHostgroupEntry.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/NodeCountEntry.java

@biharitomi plz review. it contains two commits, the 25418d5 is the most important.

Secgroup msg fix

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/SimpleFlowFacade.java

CLOUD-53519 consider cancellation of Ambari health check poller

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-common/src/main/resources/application.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml

Upgrade to rc1 images (Ambari dev build 2.2.1.1-66)

---

web/app/static/js/controllers.js
web/app/static/js/controllers/accountuserController.js
web/app/static/partials/dashboard.html
web/app/static/tags/blueprintpanel.tag
web/app/static/tags/credentialpanel.tag
web/app/static/tags/networkpanel.tag
web/app/static/tags/recipepanel.tag
web/app/static/tags/securitygrouppanel.tag
web/app/static/tags/templatepanel.tag

CLOUD-49027 Fix Uluwatu buttons depends on write permissions

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

CLOUD-53898 ignore ambari start plugin failures

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java

CLOUD-53670 added delete method to cluster commands

---

auth/schema/app/20150918124357_add_new_read_scopes.sql
auth/schema/app/20150921115156_add_read_scope_to_clients.sql
auth/schema/app/20151208111111_add_new_write_scopes.sql
auth/schema/app/20160306145372_add_sssdconfig_scopes.sql

CLOUD-52739 Disable old uaa migration scripts

---

auth/main.js
auth/schema/app/20160307125817_add_scope_to_platform.sql
web/app/static/js/controllers/accountuserController.js
web/app/static/tags/accountpanel.tag
web/app/static/tags/topologypanel.tag
web/app/static/tags/userspanel.tag

CLOUD-51506 Add write capabilities to topology/platform

---

cloud-arm/arm-images.tmpl
cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-common/src/main/resources/application.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml

upgrade to ambari buld 67 @keyki

Upgrade to ambari build 67

---

cloud-arm/arm-images.tmpl

CLOUD-53828 fixed azure rm image link in template

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/InstanceTemplate.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmDiskType.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmPlatformParameters.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmResourceConnector.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmSetup.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmStorage.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/view/ArmInstanceView.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/view/ArmStackView.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/view/ArmStorageView.java
cloud-arm/src/main/resources/templates/arm-v2.ftl
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
core/src/main/resources/defaults/templates/minviable-azure.tmpl
core/src/main/resources/schema/app/20160307151014_CLOUD-53847_update_azure_disk_type_to_Standard_LRS.sql
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AzureTemplateCreationTest.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/TemplateCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/completion/AzureVolumeType.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ConverterConfiguration.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/converter/AzureVolumeTypeConverter.java
web/app/static/config/displaynames.json
web/app/static/js/controllers/templateController.js
web/app/static/tags/template/azureform.tag
web/app/static/tags/template/azurelist.tag

CLOUD-53847 introduce storage types for ARM

---

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmDiskType.java

CLOUD-53847 remove premium storage for now

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ConstraintTemplateBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ConstraintTemplateResponse.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/ConstraintTemplate.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackController.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/MarathonCommands.java

CLOUD-50403 make ConstraintTemplate consistent with other resources

---

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmDiskType.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmPlatformParameters.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmResourceConnector.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmUtils.java

CLOUD-53847 introduce DS instance types with premium storage

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml

updated v13 images

---

web/app/static/css/Admin.min.css
web/app/static/css/Cloudbreak.min.css

CLOUD-54046 Fixing Uluwatu cluster create button layout

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/BlueprintController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/NetworkController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/SecurityGroupController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/TemplateController.java

CLOUD-53990 default resources fix

---

cloud-arm/src/main/resources/arm-images.yml

@doktoric @biharitomi 
relocate changed to `docker load`

CLOUD-53847 use docker load when relocating docker images

---

web/app/static/tags/stack/activecluster.tag

@doktoric plz review
Tested in latest Safari, Firefox, Chrome

CLOUD-54114 Fix Uluwatu instance termination button layout

---

integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate.yaml

CLOUD-53990 network id fix in openstack tests

---

cloud-arm/src/main/resources/arm-images.yml

CLOUD-54126 fix invalid mount order on Azure

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/StatusUpdateTest.java

CLOUD-54118 remove duplicate stack stop req in itest

---

web/app/static/js/controllers.js
web/app/static/js/controllers/clusterController.js
web/app/static/js/controllers/notificationController.js
web/app/static/partials/dashboard.html

CLOUD-54047 Fix cluster termination event closes cluster creation form

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ScalingTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/StatusUpdateTest.java

CLOUD-54161 itest fix for rest error handling

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/mapper/WebApplicaitonExceptionMapper.java

Avoid wrapping of JAX-RS WebApplicationException to internal server error

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/ClusterCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/util/CloudbreakShellUtil.java

CLOUD-54161 Improve error handling in shell on stack/cluster upscale/downscale and start/stop

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-common/src/main/resources/application.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml

updated images

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-common/src/main/resources/application.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml

Update for ambari v15

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java

CLOUD-54477 fix transaction during stack update

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/DefaultStackServiceTest.java

CLOUD-54477 fix lazy exception caused by missing transaction

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommandsTest.java

CLOUD-54472 NetworkCommandsTest created

---

shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/RecipeCommandsTest.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/SssdConfigCommandsTest.java

@keyki plz review, i cleaned up some test based on my experience with NetworkCommandsTest

CLOUD-54472 Polish some tests

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackParameterService.java

@doktoric or @keyki or @martonsereg

CLOUD-54565 fix credential validation in case of Mesos/Marathon

---

core/src/main/java/com/sequenceiq/cloudbreak/service/network/DefaultNetworkCreator.java

CLOUD-54680 added azure default network

---

cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/auth/OpenStackClient.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackConstants.java
cloud-openstack/src/main/resources/definitions/openstack-credential.json
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/definition/credential/CredentialDefinitionService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/resource/definition/credential/Value.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/CredentialCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/completion/OpenStackFacing.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ConverterConfiguration.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/converter/OpenStackFacingConverter.java
web/app/static/js/controllers/credentialController.js
web/app/static/messages.properties
web/app/static/tags/credential/openstackform.tag

CLOUD-54633 Openstack API facing option added

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/AccountPreferencesEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/BlueprintEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ClusterEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ConstraintTemplateEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/CredentialEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/EventEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/NetworkEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/RecipeEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SecurityGroupEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/StackEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/SubscriptionEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/TemplateEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/TopologyEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UsageEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UserEndpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java
web/app/static/js/services.js

CLOUD-52205 path configuration changes

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/AbstractFlowConfiguration.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/StackCreationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/stop/StackStopFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/sync/StackSyncFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationFlowConfig.java

Simlify flow

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/AbstractFlowConfiguration.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/StackCreationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/stop/StackStopFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/sync/StackSyncFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationFlowConfig.java

CLOUD-55042 Simplify flow initialization

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/AbstractFlowConfiguration.java

CLOUD-55324 Fix flow state machine invalid state error message

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java

CLOUD-55500 fix gcp disk type

---

web/app/static/js/controllers.js
web/app/static/tags/credentialpanel.tag
web/app/static/tags/networkpanel.tag
web/app/static/tags/templatepanel.tag
web/app/static/tags/topologypanel.tag

@doktoric  plz review
There was problems with platform borders, because `.btn-segmented-control .btn-group:last-child .btn` didn't matched

CLOUD-51772 Fix Uluwatu platform borders

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/TerminateClusterHandler.java

CLOUD-55577 Fix failed cluster termination events

---

cloud-common/src/main/resources/application.yml

CLOUD-55564 fixed install fail

---

web/app/static/js/controllers/templateController.js
web/app/static/messages.properties
web/app/static/tags/template/awsform.tag
web/app/static/tags/template/azureform.tag
web/app/static/tags/template/gcpform.tag
web/app/static/tags/template/openstackform.tag

CLOUD-55567 ephemeral disks are displayed correctly on the UI

---

core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/AbstractActionTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/Flow2HandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/StateConverterAdapterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/config/AbstractFlowConfigurationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/config/Flow2ConfigTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/config/Flow2InitializerTest.java

CLOUD-50458 Flow2 configuration tests

---

Makefile
config/checkstyle/checkstyle-suppressions.xml
core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/OfflineStateGenerator.java

@bbihari or @biharitomi plz review. This is a very basic prototype of flow state generator. It generates transitions in text mode via `make generate-flow-transitions` command.

CLOUD-55044 Flow state generator prototype

---

core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/AbstractActionTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/Flow2HandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/StateConverterAdapterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/config/AbstractFlowConfigurationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/config/Flow2ConfigTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/config/Flow2InitializerTest.java

Flow test fix

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/AbstractFlowConfiguration.java

CLOUD-55044 Eliminate redundancy at flow state confugarion

---

Makefile
config/checkstyle/checkstyle-suppressions.xml
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/OfflineStateGenerator.java

@bbihari plz review. The final solution is we generate standard [dot files](https://en.wikipedia.org/wiki/DOT_(graph_description_language)), and we leave clients to choose visualization tool. That tool could be an IDE plugin, or some JS lib, or what ever.

Flow state graph dot

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationFailureAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationFinishedAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationFlowService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationFailureAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationFinishedAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationFailureAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationFinishedAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationService.java

CLOUD-55041 Reusable flow actions, cleanup services

---

auth/build.gradle
web/build.gradle

@doktoric or @keyki please check

Make build temporarily independent from jsbeautifier

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtilTest.java

CLOUD-55924 added support for older gcp projectids

---

web/app/static/messages.properties

CLOUD-55849 Alert field validations messages fix

---

cloud-gcp/src/main/resources/gcp-images.yml

@martonsereg 
Please check it, you can use this for performance testing

CLOUD-55973 Mounted disks are not visible in containers

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/transformer/ExceptionTransformer.java

CLOUD-47839 fixed show the real error

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/transformer/ExceptionTransformer.java

CLOUD-55981 fixed validation error show

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/AppConfig.java

CLOUD-55986 validate HA blueprint

---

web/app/static/js/app.js

@bbihari 
This patch should fix the main page load errors that happen sometimes when first loading the UI.

Deleted unnecessary explicit method calls

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSetup.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsNetworkView.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/InstanceMetaData.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/MetaDataToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ConsulPluginManager.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/ConsulMetadataSetup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackScalingService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperErrorHandlerTest.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/NetworkCommands.java
web/app/static/js/controllers/networkController.js
web/app/static/tags/network/awsnetworkform.tag

CLOUD-56078 ability to create cluster without public ip

---

cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/instance/StartInstancesResult.java
cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/instance/StopInstancesResult.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/FlowState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/AbstractFlowConfiguration.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/StackCreationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/stop/StackStopFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/stop/StackStopState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/sync/StackSyncFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/sync/StackSyncState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationState.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/AbstractActionTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/config/AbstractFlowConfigurationTest.java

CLOUD-55042 Flow simplification, config builder

---

web/app/static/messages.properties

CLOUD-55849 fixed alert message

---

web/app/static/tags/stack/activecluster.tag

CLOUD-56053 - Autoscaling window create panels close icons

---

cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackMetadataCollector.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/OpenStackNativeMetaDataCollector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariHostsStatusCheckerTask.java

@schfeca75 or @keyki please review!

OpenStack metadata collection handles manually terminated instances

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Chainable.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow2Handler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stackandcluster/provision/StackAndClusterCreationFlowConfig.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/Flow2HandlerTest.java

CLOUD-55042 Fix some class casting

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateValidator.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/OpenStackCommands.java
web/app/static/tags/template/gcpform.tag

CLOUD-56573 os template with hdd disk type

---

web/app/static/js/controllers/periscopeController.js
web/app/static/tags/stack/activecluster.tag

CLOUD-56471 [GUI] Autoscaling throws script error on stopped cluster

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/OpenStackCommands.java

CLOUD-56573 os volumesize can not be smaller than 1

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/FlowLog.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow2Handler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/AbstractFlowConfiguration.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/Flow2Config.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/Flow2Initializer.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/FlowConfiguration.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/OfflineStateGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/StackCreationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stackandcluster/provision/StackAndClusterCreationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/init/CloudbreakCleanupAction.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/FlowLogRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/flowlog/FlowLogService.java
core/src/main/resources/schema/app/20160419083635_CLOUD-56259_save_stackid_to_flowlog.sql
core/src/test/java/com/sequenceiq/cloudbreak/core/flow/ReactorFlowManagerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/Flow2HandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/config/Flow2ConfigTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/config/Flow2InitializerTest.java

CLOUD-56259 Flow cancellation during termination

---

core/build.gradle

CLOUD-56645 Pass JVM args to bootRun

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsEnvironmentVariableChecker.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSessionCredentialClient.java

CLOUD-56489 Assume role without adding the keys into cbd Profile

---

web/app/static/messages.properties

CLOUD-56052 - adjustment type camel case fix

---

web/app/static/tags/topologypanel.tag

CLOUD-56657 Fixing manage platforms close button

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow/service/AmbariClusterFacade.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/HostServiceConfig.java
orchestrator-onhost/src/main/java/com/sequenceiq/cloudbreak/orchestrator/onhost/OnHostOrchestrator.java
orchestrator-onhost/src/main/java/com/sequenceiq/cloudbreak/orchestrator/onhost/client/OnHostClient.java
orchestrator-onhost/src/main/java/com/sequenceiq/cloudbreak/orchestrator/onhost/poller/ConsulConfigDistributeBootstrap.java
orchestrator-onhost/src/main/java/com/sequenceiq/cloudbreak/orchestrator/onhost/poller/ConsulRunUpscale.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/ShellContext.java

Upscalewodocker

---

config/checkstyle/checkstyle-suppressions.xml
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/AbstractAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/FlowState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/AbstractFlowConfiguration.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/OfflineStateGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/StackCreationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/StackCreationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/stop/StackStopFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/stop/StackStopState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/sync/StackSyncFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/sync/StackSyncState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationState.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/AbstractActionTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/config/AbstractFlowConfigurationTest.java

Flow simplification

---

cloud-arm/src/main/resources/arm-images.yml
core/src/main/resources/init/init.ftl
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh

CLOUD-56481 Fix of slow lazy format on azure

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceConnector.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Resource.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ResourceRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java

sync handles manually terminated vms

---

cloud-openstack/src/main/resources/os-images.yml
core/src/main/resources/init/init.ftl

added new os image and simplified userdata

---

core/src/main/resources/schema/app/20160505090528_CLOUD-57201_change_default_gateway_port_to_9443.sql

CLOUD-57201 migration sql fix

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java
core/src/main/resources/messages/messages.properties

@bbihari or @keyki 
please @schfeca75 only you check pr-s these days...

CLOUD-56370 check and fix sync related notifications

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java

CLOUD-57107 Fix instance metadata status during cluster sync

---

core/src/main/java/com/sequenceiq/cloudbreak/CloudbreakApplication.java
core/src/main/java/com/sequenceiq/cloudbreak/core/init/CloudbreakCleanupAction.java

@akanto or @schfeca75 or @mhmxs please review

CLOUD-56374 sync starts automatically at startup

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TlsSetupService.java

CLOUD-56725 fix zip salt dir from classpath within jar

---

build.gradle
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java

CLOUD-56733 added custom tag to CF stack created by cloudbreak

---

orchestrator-salt/src/main/resources/salt/salt/consul/init.sls
orchestrator-salt/src/main/resources/salt/salt/consul/scripts/consul
orchestrator-salt/src/main/resources/salt/salt/consul/stop.sls
orchestrator-salt/src/main/resources/salt/salt/consul/systemd/consul.service
orchestrator-salt/src/main/resources/salt/salt/consul/systemd/stop.sh

CLOUD-56725 systemd will wait for consul status

---

web/app/static/js/controllers/clusterController.js
web/app/static/tags/stack/ambarirepositoryconfig.tag

CLOUD-57266 Fix HDP repo verification vs cluster create on Uluwatu

---

web/app/static/js/controllers/clusterController.js

CLOUD-57266 Extra protection for .cluster.ambariStackDetails.verify

---

core-api/build.gradle
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/NetworkJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/SubnetValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidSubnet.java
core-api/src/test/java/com/sequenceiq/cloudbreak/controller/validation/AbstractValidatorTest.java
core-api/src/test/java/com/sequenceiq/cloudbreak/controller/validation/PluginValidatorTest.java
core-api/src/test/java/com/sequenceiq/cloudbreak/controller/validation/SubnetValidatorTest.java
core/build.gradle
web/app/static/js/app.js
web/app/static/messages.properties
web/app/static/tags/network/awsnetworkform.tag
web/app/static/tags/network/azurenetworkform.tag
web/app/static/tags/network/gcpnetworkform.tag
web/app/static/tags/network/openstacknetworkform.tag

CLOUD-57265 Custom CIDR validator for subnet

---

autoscale-api/build.gradle
cloud-api/build.gradle
cloud-arm/build.gradle
cloud-arm/src/main/resources/arm-images.yml
cloud-aws/build.gradle
cloud-aws/src/main/resources/aws-images.yml
cloud-byos/build.gradle
cloud-common/build.gradle
cloud-gcp/build.gradle
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/build.gradle
cloud-openstack/src/main/resources/os-images.yml
cloud-reactor-api/build.gradle
cloud-reactor/build.gradle
cloud-template/build.gradle
core-api/build.gradle
core-model/build.gradle
core/src/main/resources/init/host/nginx.conf
core/src/main/resources/init/init.ftl
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh
orchestrator-api/build.gradle
orchestrator-marathon/build.gradle
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltEndpoint.java
orchestrator-swarm/build.gradle

@keyki images include jce for kerberos, use saltboot instead of cbboot, salt-bootstrap waits for cloudinit, waagent, gcp-init

CLOUD-57108 use salt bootstrap instead of cloudbreak bootstrap

---

cloud-aws/src/main/resources/templates/aws-cf-stack.ftl

CLOUD-56078 map public ips to vms in case of existing vpc

---

core/src/main/resources/schema/app/20160426091942_CLOUD-56183_remove_docker.sql

CLOUD-57108 fixed migration script

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltJobIdTracker.java

CLOUD-56725 extend logging with job id

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl

@martonsereg or @doktoric please review

CLOUD-57542 elastic ips are managed by CloudFormation

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/SaltBootResponse.java

CLOUD-57108 fixed response json from salt bootstrap

---

build.gradle

CLOUD-57787 fixed gradle version file

---

orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/OrchestratorBootstrapRunner.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

CLOUD-56725 configurable poller max retry

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml
core/src/main/resources/init/init.ftl
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/OrchestratorBootstrapRunner.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/JobId.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/RunningJobsResponse.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/BaseSaltJobRunner.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrap.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltCommandTracker.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltJobIdTracker.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/ConsulChecker.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/HighStateChecker.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/SimpleAddRoleChecker.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/SyncGrainsChecker.java

@doktoric  this is only the first part, there are a lot of to do regarding logging

CLOUD-57785 basic logging improvement with  simplified vm images

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStates.java

CLOUD-57785 extend logging with job info

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSetup.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsInstanceProfileView.java
cloud-aws/src/main/resources/definitions/aws-zone.json
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/InstanceProfileStrategy.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AwsCommands.java
web/app/static/config/displaynames.json
web/app/static/js/controllers/clusterController.js
web/app/static/messages.properties
web/app/static/tags/stack/configurehostgroups.tag

need to document this feature.
@martonsereg pls review

CLOUD-56490 seamless s3 connection

---

auth/main.js

CLOUD-57206 fixed login when password contains special characters

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSetup.java
cloud-aws/src/main/resources/definitions/aws-credential.json

CLOUD-57544 AWS cluster creation with existing key pair

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsTagPreparationService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsTagPreparationServiceTest.java

CLOUD-57988 added cf tagging feature

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AwsCommands.java

AWS existing SSH key pair could be configured by credential command

---

cloud-aws/src/main/resources/templates/aws-cf-stack.ftl

CLOUD-57070 new description and output for CFN stack

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParameters.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/StringTypesCompare.java
cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmPlatformParameters.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformParameters.java
config/checkstyle/checkstyle-suppressions.xml
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/PlatformParameterController.java

CLOUD-58083 fixed ordering

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/StatusUpdateTest.java

CLOUD-56704 - status update test fix

---

cloud-arm/src/main/java/com/sequenceiq/cloudbreak/cloud/arm/ArmPlatformParameters.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformParameters.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackParameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterRequest.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/ClusterCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/GcpCommands.java
web/app/static/js/controllers/clusterController.js

BUG-58076 removed container option

---

cloud-aws/src/main/resources/aws-images.yml
core/src/main/resources/init/init.ftl
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh

CLOUD-56717 switch to Amazon Linux

---

build.gradle
cloud-mock/build.gradle
core/src/main/resources/logback.xml
gradle.properties
integration-test/src/main/resources/logback.xml

CLOUD-57130 spring update and logback config correction

---

cloud-arm/build.gradle

CLOUD-57130 add groovy-all 2.4.6 to cloud-arm module

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationService.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/OrchestratorBootstrapRunner.java

CLOUD-58082: Logging Nullpointer fix

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-common/src/main/resources/application.yml

CLOUD-56717 enable spot price instances

---

integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AwsCreateExistingVpcNetworkTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AwsDeleteVpcTest.java
integration-test/src/main/resources/cloudformation/public_vpc.json
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-on-vpc.yaml

CLOUD-58081 Integration test for existing VPC

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java

show reason of failed commands when using the shell with --cmdfile

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java

CLOUD-56717 enable spot price instances, fix null

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/OpenStackCommands.java

CLOUD-58086: Openstack network shell command improvement for the new network types

---

integration-test/Makefile
integration-test/integcb/Profile

CLOUD-57130 makefile download latest cbd

---

core/src/main/resources/init/init.ftl

note: might need to remove > /var/log/user-data.log from line 25

log to user-data.log & console

---

core/src/main/java/com/sequenceiq/cloudbreak/service/network/NetworkUtils.java
core/src/main/resources/schema/app/20160524102332_CLOUD-57310_update_hbase_ports_to_new_versions.sql

CLOUD-57310 Follow HBase port changes

---

core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AwsCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AzureCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/GcpCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/OpenStackCommands.java

just @schfeca75 pls.
I also changed the default failure action as we talked.
Pls also review the updated tests...

CLOUD-58513 network separation

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AzureCommands.java
web/app/static/tags/stack/configurecluster.tag
web/app/static/tags/stack/configurefilesystem.tag

CLOUD-58094 docker properties removed on ui

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java

CLOUD-58682 remove circular dependencies

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverter.java

CLOUD-58813 added creation time to stack response

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java

BUG-58820 default views not needed any more

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/TlsSecurityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariDecommissioner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/HostMetadataSetup.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterContainerRunnerTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/GatewayConfig.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/PillarSave.java
orchestrator-salt/src/main/resources/salt/salt/top.sls
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltConnectorTest.java

@keyki @schfeca75 
Also solves the CLOUD-58093

CLoudbreak does not start without DNS on OpenStack

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/BlueprintValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/HostGroupDecorator.java
core/src/main/resources/hdp/hdp-services.json
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverterTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/InstanceGroupCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/ShellContext.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/InstanceGroupCommandsTest.java

CLOUD-58087 ability to select where to put ambari server to

---

cloud-openstack/src/main/resources/templates/openstack-heat.ftl

CLOUD-58086 always use ports even there is no floating ip assigned

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockClusterCreationWithSaltSuccessTest.java

CLOUD-58820 remove verify views from integration test

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/RunnerInfoObject.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/JidInfoResponseTransformer.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStates.java

CLOUD-58877 fix JID response NPE

---

cloud-aws/src/main/resources/aws-images.yml
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackController.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageNameUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AwsCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AzureCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/GcpCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/OpenStackCommands.java

CLOUD-58111 support image selection

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/PillarSave.java
orchestrator-salt/src/main/resources/salt/pillar/nodes/hosts.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/agent.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/public_hostname.sh
orchestrator-salt/src/main/resources/salt/salt/nodes/settings.sls

CLOUD-57779 Using private address if only private address is available

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/BlueprintValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/blueprint/BlueprintValidatorTest.java

CLOUD-58087 fix bp validator

---

orchestrator-salt/src/main/resources/salt/salt/kernel/init.sls
orchestrator-salt/src/main/resources/salt/salt/top.sls

CLOUD-56980 echo kernel version on each platform

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockClusterCreationWithSaltFailTest.java
integration-test/src/main/java/com/sequenceiq/it/spark/salt/SaltApiRunPostResponse.java
integration-test/src/main/resources/mockresponse/saltapi/lookup_jid_fail_response.json
integration-test/src/main/resources/testsuites/mock/mock-clustercreate-salt-failed.yaml
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/JobState.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/RunnerInfoObject.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltJobIdTracker.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/JidInfoResponseTransformer.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStates.java

BUG-58678 Salt polling with meaningful error response

---

core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java
orchestrator-salt/src/main/resources/salt/salt/kerberos/server.sls

Sporadic kadmin failure

---

cloud-common/src/main/resources/application.yml
core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/BlueprintConfigurationEntry.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/BlueprintProcessingException.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/BlueprintProcessor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/DefaultConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/FixedDefaultConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/JacksonBlueprintProcessor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/SmartSenseConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/AbstractFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/FileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/dash/DashFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/gcs/GcsFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasb/WasbFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasbintegrated/WasbIntegratedFileSystemConfigurator.java
core/src/main/resources/defaults/blueprints/hdp-ephemeral.bp
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnectorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/JacksonBlueprintProcessorTest.java
gradle.properties
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/resources/salt/salt/smartsense/gateway-init.sls
orchestrator-salt/src/main/resources/salt/salt/smartsense/gateway/hst-gateway.ini
orchestrator-salt/src/main/resources/salt/salt/smartsense/init.sls
orchestrator-salt/src/main/resources/salt/salt/smartsense/scripts/security.py.diff
orchestrator-salt/src/main/resources/salt/salt/smartsense/scripts/smartsense-agent-patch.sh
orchestrator-salt/src/main/resources/salt/salt/top.sls

Configurable default SmartSense configuration and installation

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AwsCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AzureCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/GcpCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/OpenStackCommands.java

CLOUD-58927 shell help messages with common provider names

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ConfigStrategy.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/resources/init/init.ftl
core/src/test/resources/azure-core-init.sh
core/src/test/resources/azure-gateway-init.sh
orchestrator-salt/src/main/resources/salt/pillar/ambari/repo.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/ambari-server-init.sh
web/app/static/js/controllers/clusterController.js

@biharitomi 
Upgrade to Ambari 2.4.0.0-622, SmartSense needs to be checked

Upgrade to Ambari 2.4.0.0-622

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockClusterCreationWithSaltSuccessTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockStackCreationWithSaltSuccessTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/BaseSaltJobRunner.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/ConsulChecker.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/HighStateChecker.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/SimpleAddRoleChecker.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/SyncGrainsChecker.java

CLOUD-59041 call network.interface_ip function zero times

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/resources/salt/salt/top.sls

CLOUD-58091 patch smartsense on every node

---

integration-test/Makefile
integration-test/integcb/Profile

@schfeca75 @biharitomi pls review

CLOUD-58884 print cloudbreak container log into a log file

---

core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/MetaDataToJsonConverterTest.java

CLOUD-59029 fixed ig metadata generation

---

web/app/static/tags/stack/configurefilesystem.tag

CLOUD-59104 remove GCS from UI temporarily

---

cloud-aws/src/main/resources/aws-images.yml

CLOUD-58111 update warmup images on Amazon for HDP 2.4.3

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/BaseSaltJobRunner.java

CLOUD-59081 Infinite polling fix

---

web/app/static/js/console.UI.js
web/app/static/js/controllers/clusterController.js
web/app/static/messages.properties
web/app/static/tags/stack/configurereview.tag

Cluster wizzard

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverterTest.java
web/app/static/js/controllers/periscopeController.js
web/app/static/js/services.js

CLOUD-59329 add missing gateway port to stack response

---

web/app/static/js/controllers/clusterController.js
web/app/static/messages.properties

CLOUD-58087 allow single node clusters

---

gradle.properties

CLOUD-59052 add extra logging to Ambari client

---

gradle.properties
orchestrator-salt/build.gradle
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/BaseSaltJobRunnerTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/PillarSaveTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrapTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltCommandTrackerTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltJobIdTrackerTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/HighStateCheckerTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/SimpleAddRoleCheckerTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/SyncGrainsCheckerTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStatesTest.java
orchestrator-salt/src/test/resources/jid_response.json
orchestrator-salt/src/test/resources/jid_simple_response.json

CLOUD-59542 create unit tests for salt orchestrator

---

web/app/static/js/controllers/clusterController.js

@biharitomi @doktoric plz check

CLOUD-59440 [GUI] Script error on Cluster Details tab

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/status/AmbariClusterStatusUpdater.java
web/app/static/js/controllers/clusterController.js
web/app/static/messages.properties
web/app/static/tags/stack/activecluster.tag
web/app/static/tags/stack/configurereview.tag

Remove cbgateway references

---

cloud-common/src/main/resources/application.yml
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/SmartSenseConfigProvider.java

Handle aws account id as String during smartsense id generation

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/APIResourceType.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/ClusterTemplateEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterTemplateBase.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterTemplateRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterTemplateResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterTemplateType.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/ClusterTemplate.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterTemplateController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterTemplateToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToClusterTemplateConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterTemplateRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/clustertemplate/ClusterTemplateService.java
core/src/main/resources/schema/app/20160607135120_CLOUD-57781_added_clustertemplate.sql

CLOUD-59648 added clustertemplate table

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/BlueprintBase.java
core/src/main/java/com/sequenceiq/cloudbreak/service/clustertemplate/ClusterTemplateService.java
web/app/static/tags/blueprint/bpform.tag
web/app/static/tags/network/azurenetworkform.tag

Cl template

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterRequest.java
orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/ambari-server-init.sh

OpenJDK + update to ambari 2.4.0.0-648

CLOUD-58099 Use OpenJDK instead of Oracle JDK

---

core/src/main/java/com/sequenceiq/cloudbreak/service/network/NetworkUtils.java
core/src/main/java/com/sequenceiq/cloudbreak/service/securitygroup/DefaultSecurityGroupCreator.java
core/src/main/resources/init/host/nginx.conf
core/src/main/resources/schema/app/20160609101056_CLOUD-56730_security_rule_update.sql
web/app/static/tags/stack/activecluster.tag

CLOUD-56730 reverse proxy for UI components

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/BlueprintProcessor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/JacksonBlueprintProcessor.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/JacksonBlueprintProcessorTest.java

CLOUD-59766 added stackversion to blueprint

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ImageJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/ImageToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverterTest.java

CLOUD-59774 added image to cluster response

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/AbstractAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/Flow2Handler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/DownscaleFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/StartFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpscaleFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/ClusterAndStackDownscaleTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/StackAndClusterUpscaleTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/AbstractStackUpscaleAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/event/ClusterUserNamePasswordUpdateRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetadataService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/Flow2HandlerTest.java

@schfeca75 and/or @bbihari plz review

CLOUD-59030 Some flow code cleanup

---

cloud-common/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/hdp-etl-edw.bp

@biharitomi @doktoric nearly final etl-edw bp

CLOUD-58088 add etl-edw default bp

---

core/src/main/resources/init/host/nginx.conf

CLOUD-56730 - rewrite url if ambari sessionid appears in cookies

---

cloud-aws/src/main/resources/templates/aws-cf-stack.ftl

CLOUD-59566 added group name to AWS instance Name tags

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSetup.java

iam:createRole is enough for cloudbreak, iam:* not needed

---

orchestrator-salt/src/main/resources/salt/salt/dns/init.sls
orchestrator-salt/src/main/resources/salt/salt/top.sls

CLOUD-59942 Set DNS TTL for AWS clients to <= 60s

---

core/src/main/resources/scripts/hdfs-home.sh
orchestrator-salt/src/main/resources/salt/salt/top.sls
orchestrator-salt/src/main/resources/salt/salt/users/init.sls

CLOUD-56630 create admin user for Ambari views

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java

CLOUD-59184 modified connector matcher

---

core/src/main/resources/defaults/blueprints/hdp25-data-science.bp
core/src/main/resources/defaults/blueprints/hdp25-edw-analytics.bp
core/src/main/resources/defaults/blueprints/hdp25-etl-edw-tp.bp
core/src/main/resources/defaults/blueprints/hdp25-etl-edw.bp

- these are currently placeholders requested by Attila
- most will not work at this time since HDP25 isn't ready.

placeholder blueprint files BUG-58088

---

cloud-common/src/main/resources/application.yml
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderServiceTest.java
core/src/test/resources/defaults/blueprints/testloader.bp

CLOUD-60178 modification in bp loader service

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
core/src/main/resources/scripts/smartsense-capture-schedule.sh

CLOUD-58092 set SmartSense capture schedule on hosts by recipe

---

core/src/main/resources/init/host/nginx.conf

CLOUD-56730 spark reverse proxy settings

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/generic/DynamicModel.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSmartSenseIdGenerator.java
core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/SmartSenseConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/CredentialService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderCredentialAdapter.java

CLOUD-58092 generate SmartSense id as credential attribute

---

core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java
web/server.js

fixed subscriptions url pattern

---

auth/app/confirm.html
auth/app/dashboard.html
auth/app/login.html
auth/app/regacc.html
auth/app/register.html
auth/app/reset.html
auth/main.js
auth/public/js/app.js

@akanto email functions are working as well

CLOUD-41893: sultans: use /identity url prefix behind proxy

---

integration-test/Makefile
web/app/static/messages.properties
web/app/static/tags/blueprint/bpform.tag

CLOUD-60075 Update Blueprint Name field validation message

---

cloud-aws/src/main/resources/definitions/aws-credential.json

CLOUD-58092 added smartsenseid to response

---

auth/main.js

@doktoric 
proxy change accidentaly removed this password encode

CLOUD-57206 fixed password encode - again

---

cloud-aws/src/main/resources/templates/aws-cf-stack.ftl

stack output to show https ambari address

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/client/CertificateTrustManager.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/client/RestClientUtil.java

CLOUD-41893 Add a permissive HostnameVerifier

---

core/src/main/resources/init/host/nginx.conf

CLOUD-56730 spark jobhistory server nginx config

---

cloud-common/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/hdp25-etl-edw-spark2-hive2.bp
core/src/main/resources/defaults/blueprints/hdp25-etl-edw-spark2.bp

rename blueprint: hdp-etl-edw-tp to hdp-etl-edw-spark2-hive2

---

auth/main.js

Make sultans base path configurable with '/auth' as default value

---

cloud-aws/src/main/resources/definitions/aws-vm.json

CLOUD-59813 fixed missing cpu and memory

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java

CLOUD-60279 Fixed NPE during invalid command in command file

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/SmartSenseConfigProvider.java

Add SmartSense server to a single noded hostgroup if possible

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/VmTypeMeta.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/VolumeParameterType.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformParameters.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsGroupView.java
cloud-aws/src/main/resources/definitions/aws-vm.json
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
web/app/static/config/displaynames.json

@akanto or @doktoric pls reivew

CLOUD-60244 new supported volume type on aws: ST1

---

core/src/main/resources/init/host/nginx.conf

CLOUD-56730 remove spark and zeppelin nginx proxy settings

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/PlatformVirtualMachineTypesToJsonConverter.java

CLOUD-60244 st1 added to json

---

integration-test/src/main/resources/testsuites/nativeos/smoke/nativeos-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/nativeos/smoke/nativeos-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/nativeos/smoke/nativeos-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/nativeos/smoke/nativeos-clustercreate.yaml
integration-test/src/main/resources/testsuites/openstack-resourcetests.yaml

@biharitomi or @sodre90 pls review

Remove pulbicNetId parameters from the tests

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/AbstractFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/FileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/FileSystemScriptConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/dash/DashFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/gcs/GcsFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasb/WasbFileSystemConfigurator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/filesystem/wasbintegrated/WasbIntegratedFileSystemConfigurator.java
core/src/main/resources/scripts/gcs-connector.sh
core/src/main/resources/scripts/gcs-p12.sh
orchestrator-salt/src/main/resources/salt/salt/ambari/agent.sls

CLOUD-58976 google connector with salt orchestrator

---

core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/service/flowlog/FlowLogService.java

do not save payload because it can cause stackoverflow

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/CloudbreakShell.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ShellConfiguration.java

CLOUD-60634 use only cloudbreak address to connect cloudbreak

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/UtilEndpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/RdsTestResult.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ControllerDescription.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/UtilController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/rds/RdsConnectionValidator.java

CLOUD-56715 test rds connection

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/resources/os-images.yml

CLOUD-58099 Update Ambari to 2.4.0.0-683

---

orchestrator-salt/src/main/resources/salt/salt/top.sls
orchestrator-salt/src/main/resources/salt/salt/users/add-to-group.sls
orchestrator-salt/src/main/resources/salt/salt/users/init.sls

Add admin user to hadoop and hdfs groups after ambari install

---

auth/public/js/app.js

Fix sultans base path

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudCredential.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailMimeMessagePreparator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/SmartSenseConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderCredentialAdapter.java

CLOUD-59082 telemetry email sending

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java

CLOUD-60890 fixd incorrect string compare

---

autoscale/src/main/java/com/sequenceiq/periscope/service/security/ClusterSecurityService.java

CLOUD-60729 Fix ClusterSecurityService.hasAccess()

---

web/app/static/js/controllers/clusterController.js

CLOUD-60727 Fix uluwatu active cluster cloudPlatform variable

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java

CLOUD-58976 gcp connector fix

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java

CLOUD-60927 Fix ambari server ip selection on AWS

---

core/src/main/resources/defaults/blueprints/hdp25-edw-analytics.bp

Also removed workaround for BUG-60040

Enabled HSI and LLAP services

---

orchestrator-salt/src/main/resources/salt/salt/smartsense/init.sls

CLOUD-61156 fix conflicting salt execute-patch IDs

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/CloudbreakUsageJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/CloudbreakUsage.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/HostGroup.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/CloudbreakUsageToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToCloudbreakUsageConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/usages/DefaultCloudbreakUsageGeneratorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/usages/IntervalStackUsageGenerator.java
core/src/main/resources/schema/app/20160628084931_CLOUD-61094_extend_cloudbreak_usage_with_blueprintid_and_blueprintname.sql
core/src/main/resources/schema/app/20160628142654_CLOUD-59100_remove_service_componenttype.sql
core/src/test/java/com/sequenceiq/cloudbreak/service/usages/DefaultCloudbreakUsageGeneratorHostServiceTypeTest.java
core/src/test/resources/com/sequenceiq/cloudbreak/converter/usage/cloudbreak-usage.json

CLOUD-61094 Extend cloudbreak usage with blueprint id and blueprint name

---

cloud-arm/arm-images.tmpl
cloud-arm/src/main/resources/arm-images.yml
cloud-arm/src/main/resources/definitions/arm-zone.json

@sodre90 or @keyki Canada is comming

CLOUD-61245 added canada region to azure

---

integration-test/Makefile
integration-test/fill_public_ip.sh
integration-test/integcb/Environment
integration-test/integcb/Profile_template

@schfeca75 @doktoric review please

CLOUD-61285 Use cbd start-wait instead of wait_for_cloudbreak_api.sh

---

core/src/main/resources/init/container/tls-setup.sh
core/src/main/resources/init/host/nginx.conf
core/src/main/resources/init/host/tls-setup.sh

@doktoric @akanto please review

CLOUD-60625 Refactor certification generation and naming

---

core/src/main/resources/scripts/dash-hdfs.sh
core/src/main/resources/scripts/dash-local.sh

CLODU-61407 dash-hdfs.sh and dash-local.sh changed to be idempotent

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/BlueprintResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/BlueprintToJsonConverter.java

CLOUD-61427 add blueprint status to response

---

cloud-common/src/main/resources/application.yml
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Cluster.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/AmbariClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/RecipeEngine.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/SmartSenseConfigProvider.java
core/src/test/resources/com/sequenceiq/cloudbreak/converter/stack/stack.json
web/app/static/js/controllers/clusterController.js
web/app/static/tags/stack/activecluster.tag

CLOUD-61093 getting Mesos/Marathon to work

---

cloud-arm/src/main/resources/arm-images.yml
cloud-aws/src/main/resources/aws-images.yml
cloud-gcp/src/main/resources/gcp-images.yml
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/OpenStackSmartSenseIdGenerator.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/auth/OpenStackCredentialConnector.java
cloud-openstack/src/main/resources/os-images.yml
integration-test/src/main/resources/testsuites/nativeos/smoke/nativeos-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/nativeos/smoke/nativeos-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/nativeos/smoke/nativeos-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/nativeos/smoke/nativeos-clustercreate.yaml

@akanto or @biharitomi pls review

Smartsense 1.3

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/CbUser.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/SecurityConfig.java

CLOUD-60785 Fix security config for users endpoint

---

web/app/static/js/services.js
web/server.js

CLOUD-61408 Fix possibly rest errors in uluwatu

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderService.java

CLOUD-61641 more info in telemetry mail

---

shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseNetworkCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/ShellContext.java
shell/src/test/java/com/sequenceiq/cloudbreak/shell/commands/BaseNetworkCommandsTest.java

@schfeca75 fixed shell command problem in shell

CLOUD-61481 network name is used instead of platfrom

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/AbstractAction.java

CLOUD-61514 measure each flow step

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/AbstractAction.java

CLOUD-61514 fix flow measure: some of the work is done in doExec

---

core/src/main/resources/schema/app/20160628125127_CLOUD-61260_add_plugin_table.sql

CLOUD-61260 missing drop from undo

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockClusterCreationWithSaltSuccessTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockStackCreationWithSaltSuccessTest.java

move salt mappings and verifications from stack creation to cluster creation (salt bootstrap was removed from stack creation)
@akanto @schfeca75 pls review

CLOUD-61481 mock-integration-test

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
orchestrator-salt/src/main/resources/salt/salt/ambari/agent.sls

Parallel1.4

---

core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToBlueprintConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintUtils.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToBlueprintConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderServiceTest.java

CLOUD-61490 automatic blueprint update in startup

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/mapper/CloudbreakApiExceptionMapper.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/HdpInfoSearchService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/HdpInfoSearchServiceTest.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/StackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/base/BaseStackCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AwsCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/AzureCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/GcpCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/OpenStackCommands.java

@keyki 
```
stack create --OPENSTACK --name zzamb2825 --region local  --ambariVersion 2.8 --hdpVersion 2.5 --imageCatalog https://s3-eu-west-1.amazonaws.com/cloudbreak-info/dev-cb-image-catalog.json
```

CLOUD-62273 Configurable image catalog

---

core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/InstanceGroupToJsonConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/MetaDataToJsonConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java

CLOUD-62555 - ClusterBootstrapperTest randomly fails

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java

CLOUD-62383 fix sync to avoid node count corruption of instance groups

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Cluster.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/JsonToClusterConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/reset/ClusterResetService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/start/ClusterStartService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stop/ClusterStopService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationFlowService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleFlowService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartStopService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailMimeMessagePreparator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderService.java
core/src/main/resources/schema/app/20160718123439_CLOUD-62544_mail_to_field_added_to_cluster.sql
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderHostServiceTypeTest.java
core/src/test/resources/com/sequenceiq/cloudbreak/converter/stack/cluster-with-ambari-stack-details.json
core/src/test/resources/com/sequenceiq/cloudbreak/converter/stack/cluster-with-file-system.json
core/src/test/resources/com/sequenceiq/cloudbreak/converter/stack/cluster.json

CLOUD-62544 mail notification for custom address

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/task/ASGroupStatusCheckerTask.java

@doktoric @martonsereg @biharitomi

CLOUD-62711 remove invalid auto scaling group history check

---

integration-test/build.gradle
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AwsCreateVpcNetworkTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AzureDeleteVpcTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/AzureUseAnExistingSubnetInAnExistingVpcNetworkTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/GcpCreateVirtualNetworkTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/GcpDeleteVpcTest.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/cloudformation/public_vpc_with_subnet.json
integration-test/src/main/resources/cloudformation/public_vpc_without_subnet.json
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-existing-subnet-in-existing-vpc.yaml
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-new-subnet-in-existing-vpc.yaml
integration-test/src/main/resources/testsuites/azurerm/credandsmoke/azurerm-clustercreate-existing-vpc-subnet.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-existing-legacy-network.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-existing-subnet-existing-network.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-new-subnet-existing-vpc.yaml

@doktoric @schfeca75 @akanto pls review

BUG-62014 - aws, azure and gcs existing vpc TCs

---

core/src/main/resources/schema/app/20160721133313_remove_old_recipes.sql

CLOUD-62860 delete old recipes

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/AmbariDatabase.java
cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/ComponentType.java
cloud-common/src/main/resources/application.yml
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/AmbariDatabaseDetailsJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/DatabaseVendor.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/AmbariDatabaseDetailsJsonToAmbariDatabaseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ComponentConfigProvider.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/RunnerInfoObject.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/JidInfoResponseTransformer.java
orchestrator-salt/src/main/resources/salt/pillar/top.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/ambari-server-init.sh
orchestrator-salt/src/main/resources/salt/salt/ambari/server.sls
orchestrator-salt/src/main/resources/salt/salt/ambari/settings.sls
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/ClusterCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/DatabaseCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/completion/DatabaseVendor.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/configuration/CommandDefinition.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/configuration/ConverterConfiguration.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/converter/DatabaseVendorConverter.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/model/ShellContext.java

@doktoric @keyki @martonsereg plz review. Only ambari-server-init-sh changed since https://github.com/sequenceiq/cloudbreak/pull/1803

Ambari database

---

core/src/main/resources/schema/app/20160721133313_remove_old_recipes.sql

CLOUD-62860 delete old recipes fix

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Image.java

CLOUD-61497 Duplicated HDP repo impementation, fix json annotation

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java
web/app/static/tags/stack/activecluster.tag

CLOUD-63067 Fix Ambari password change form validation

---

CHANGELOG.md

Add changelog to Cloudbreak

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderService.java
core/src/main/resources/templates/cluster-installer-mail-fail.ftl
core/src/main/resources/templates/cluster-installer-mail-success.ftl
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/EmailSenderHostServiceTypeTest.java

CLOUD-63076 email template modifications

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariDecommissioner.java

@akanto
This PR allows every hg which does not have a DATANODE to scale down to 1 node.

CLOUD-63074 only consider DATANODE when counting the replication factor

---

CHANGELOG.md
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/CloudbreakDetailsJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/StackResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/CloudbreakDetailsToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/StackToJsonConverterTest.java
web/app/static/js/controllers/clusterController.js
web/app/static/tags/stack/activecluster.tag

@doktoric or @schfeca75 or @keyki or @mhmxs

Add Cloudbreak details to stack response and fix Ambari address of older clusters

---

circle.yml

CLOUD-48030 added circle build

---

CHANGELOG.md
core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/DatabaseVendor.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/DatabaseCommands.java
web/app/static/messages.properties
web/app/static/tags/stack/ambaridatabaseconfig.tag

CLOUD-61927 Ability to configure any type of database for Ambari

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/PillarSave.java
orchestrator-salt/src/main/resources/salt/salt/discovery/init.sls
orchestrator-salt/src/main/resources/salt/salt/top.sls
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/PillarSaveTest.java

@schfeca75 @akanto 
Now you can set custom domain for every platform.

CLOUD-63239 ability to use custom domain on every platform

---

cloud-openstack/build.gradle
cloud-openstack/src/test/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/HeatTemplateBuilderTest.java

CLOUD-55526 Implement heatTemplateBuilder tests

---

cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackUtils.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackMetadataCollector.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackResourceConnector.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/AbstractOpenStackComputeResourceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackAttachedDiskResourceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/context/OpenStackContextBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/network/OpenStackRouterResourceBuilder.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/view/KeystoneCredentialView.java

CLOUD-63502 put stack id to stack name on OpenStack

---

cloud-arm/build.gradle
cloud-arm/src/test/java/com/sequenceiq/cloudbreak/cloud/arm/ArmTemplateBuilderTest.java

CLOUD-55526 Implement armTemplateBuilder tests

---

Makefile
scripts/build-dev.sh
scripts/build-rc-patch.sh
scripts/build-rc.sh
scripts/build-release.sh
scripts/build.sh

CLOUD-48030 added make scripts

---

cloud-gcp/build.gradle
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/GcpTemplateCreationTest.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/provider/GcpCommands.java
web/app/static/messages.properties
web/app/static/tags/template/gcpform.tag
web/app/static/tags/template/gcplist.tag

CLOUD-51841 Implement preemtible instances for GCP

---

cloud-aws/build.gradle
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderTest.java

CLOUD-55526 Implement cloudFormationTemplateBuilder tests

---

circle.yml
integration-test/Makefile

@doktoric @biharitomi pls review

CLOUD-63682 - Pull request: move mock integration test to Circle CI

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/ResourceType.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockResourceConnector.java
integration-test/it-application.yml
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakITContextConstants.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockClusterCreationWithSaltFailTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockClusterCreationWithSaltSuccessTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockClusterCreationWithSwarmSuccessTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockClusterScalingTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/MockStackCreationWithSaltSuccessTest.java
integration-test/src/main/java/com/sequenceiq/it/spark/ambari/AmbariBlueprintsResponse.java
integration-test/src/main/java/com/sequenceiq/it/spark/ambari/AmbariClusterResponse.java
integration-test/src/main/java/com/sequenceiq/it/spark/ambari/AmbariClustersHostsResponse.java
integration-test/src/main/java/com/sequenceiq/it/spark/ambari/AmbariHostsResponse.java
integration-test/src/main/java/com/sequenceiq/it/spark/ambari/AmbariServiceConfigResponse.java
integration-test/src/main/java/com/sequenceiq/it/spark/ambari/model/Hosts.java
integration-test/src/main/java/com/sequenceiq/it/spark/salt/SaltApiRunPostResponse.java
integration-test/src/main/java/com/sequenceiq/it/spark/spi/CloudMetaDataStatuses.java
integration-test/src/main/java/com/sequenceiq/it/util/ServerAddressGenerator.java
integration-test/src/main/resources/mockresponse/blueprint/hdp-small-default.bp
integration-test/src/main/resources/testsuites/mock/mock-scaling-salt.yaml

@schfeca75 @doktoric pls review

CLOUD-63588 - Mock integration test for upscale and downscale

---

cloud-common/src/main/resources/application.yml

@aszegedi @schfeca75  update ambari

BUG-61477 Update Ambari to build 980

---

circle.yml
integration-test/Makefile
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcpkerb-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/oskerb-clustercreate-startstop-updown.yaml

using hdp-small-default blueprint and create credential
@doktoric pls review

CLOUD-63863 kerberos test improvement

---

web/app/static/tags/stack/activecluster.tag

Add cloudbreak details to active cluster panel as a hidden field

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/RDSConfigJson.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/ClusterController.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/RdsConfigController.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/ClusterCommands.java
shell/src/main/java/com/sequenceiq/cloudbreak/shell/commands/common/RdsConfigCommands.java

CLOUD-63975 Ability to create the metastore if the validation fails

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/ClusterResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Cluster.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariViewProvider.java
core/src/main/resources/schema/app/20160809093634_CLOUD-63600_attributes_added_to_cluster.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/JsonToClusterConverterTest.java
gradle.properties

CLOUD-63600 added view info to cluster response

---

scripts/build-dev.sh

save version for dev versions

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariViewProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverterTest.java

CLOUD-63600 added view exist check

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ClusterCreationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/TemplateAdditionHelper.java
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-on-vpc.yaml
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/aws/credandsmoke/aws-clustercreate.yaml
integration-test/src/main/resources/testsuites/azurerm/credandsmoke/azurerm-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/azurerm/credandsmoke/azurerm-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/azurerm/credandsmoke/azurerm-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/azurerm/credandsmoke/azurerm-clustercreate.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcp-clustercreate.yaml
integration-test/src/main/resources/testsuites/gcp/credandsmoke/gcpkerb-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/nativeos/credandsmoke/nativeos-clustercreate.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-startstop-updown.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-startstop.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate-updown.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/openstack-clustercreate.yaml
integration-test/src/main/resources/testsuites/openstack/credandsmoke/oskerb-clustercreate-startstop-updown.yaml

CLOUD-63871 remove cbgateway instances from itests

---

scripts/build-dev.sh
scripts/build-rc-patch.sh
scripts/build-rc.sh

CLOUD-61470 minor changes in build scripts

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/ClusterToJsonConverter.java

CLOUD-63600 view check when ambari available

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSetup.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsNetworkView.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
web/app/static/messages.properties
web/app/static/tags/network/awsnetworkform.tag

CLOUD-64312 Ability to specify multiple subnets for the same VPC on AWS

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariClusterConnector.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/AutoRecoveryConfigProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/BlueprintProcessor.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/blueprint/JacksonBlueprintProcessor.java

CLOUD_64330 Auto restart HDP services on failure

---

gradle.properties

CLOUD-64325 OpenStack topology mapping error

---

auth/Makefile
web/Makefile

CLOUD-61470 version can come from env variable

---

autoscale/src/main/java/com/sequenceiq/periscope/config/ApiDocConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/ApiDocConfig.java

BUG-64534 Add proper API version to swagger

---

core/src/main/java/com/sequenceiq/cloudbreak/service/sssdconfig/SssdConfigService.java

CLOUD-61408 Fix SssdConfigService.getDefaultSssdConfig() locking object

---

cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackSetup.java

CLOUD-60780 - list all openstack images instead of first page
