core/src/main/resources/defaults/blueprints/cdp-opdb-720.bp
core/src/main/resources/defaults/blueprints/cdp-opdb-721.bp

Disable Erasure Coding for opdb templates. 7.2.0 enables EC by default. However, since HDFS is used as temporary storage on public cloud clusters, EC and corresponding health checks need to be disabled.
Testing: Made the changes to a custom blueprint and created a cluster with the blueprint. Verified that the EC test fail message is not shown up.

DISTX-488 [opdb] Disable Erasure Coding for OpDB templates

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/StackType.java
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/responseprovider/StackResponseEventProvider.java
core/src/main/resources/schema/app/20200708143948_CB-7808_set_from_datahub,_datalake_stack_type_to_stacks_in_structured_events.sql
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/CloudbreakEventService.java

We filtered the structured events to datalake and datahub only but before 2.25 the CB stored as stacks. The legacy resource type added

Cb-7808 Flow events are missing from Structuctured events

---

common-model/src/main/java/com/sequenceiq/common/api/tag/response/MapToTaggedResponseAdapter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CloudProviderSideTagAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/database/RedbeamsDatabaseTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/AwsCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/AmazonEC2Util.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/AzureCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/util/TagsUtil.java

Extend tag verification so that it does not jut verify tags on CB side, but actually query the cloud provider that resources have the needed tags. Supported cloud providers are Aws and Azure.

CB-7706 Verify tags on cloud provider side

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/LoadAlertConfigurationRequest.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/LoadAlertConfiguration.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ScalingConstants.java

LoadAlertConfigurationRequest::coolDownMinutes is made not mandatory and initialized with default value of 2 mins.
.

DISTX-475-NotMandatoryCoolDownMins

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SetRangerCloudIdentityMappingRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/CloudIdentitySyncService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/CloudIdentitySyncServiceTest.java

CloudIdentitySyncService was filtering by the identity domain, but
this field may be null. This is fixed by filtering based on cloud
identity name instead. This commit also adds unit tests for
CloudIdentitySyncService.

CDPCP-1941. Fix cloud identity sync filter

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/SaltBootstrapFingerprintVersionChecker.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/PackageVersionChecker.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCommonService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/SaltBootstrapFingerprintVersionCheckerTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/BootstrapService.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/BootstrapParams.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/FingerprintsResponse.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/Minion.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrap.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/AcceptAllFpMatcher.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/DummyFingerprintCollector.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/EqualMinionFpMatcher.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/FingerprintCollector.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/FingerprintFromSbCollector.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionAcceptor.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionFingerprintMatcher.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/FingerprintFromSbCollectorTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionAcceptorTest.java

When a cluster is started with old salt-bootstrap it will have auto join in salt master configuration. Every minion will be able to join.
During cluster upgrade we replace the master first. Master will not have the auto join configured
but we can't collect the fingerprints from the old salt-bootstrap.
In this change we will check if every instance has a new salt-bootstrap (greater or equal to 0.13.2).
If any instance has old one, we will replace the FingerprintCollector with a dummy implementation which won't collect the fingerprints as it would fail anyway.
The fingerprint matching has been refactored into a separate class. If there is an old salt-bootstrap between the instances we will use `AcceptAllFpMatcher`.
It will return with all fingerprints are matching, so every minion will be …

CB-7929 OS upgrade should work with non-auto joinable master

---

core/src/main/resources/defaults/blueprints/cdp-sdx-721.bp

Adds the "-Dsolr.hdfs.allow.location.override=true" to the Solr java opts on
the 7.2.1 datalake. This option is used with some recent Solr change to allow
the datalake disaster recovery service to export Solr backups to cloud storage.
See also CDPSDX-1707 and CDPSDX-2121.

CB-7901 Enable Solr backup location override java opt on datalake

---

common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/CcmParameters.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/userdata/UserDataBuilder.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/userdata/UserDataBuilderTest.java
core/src/test/resources/azure-core-ccm-init.sh
core/src/test/resources/azure-gateway-ccm-init.sh
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/userdata/UserDataBuilder.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/userdata/UserDataBuilderTest.java
freeipa/src/test/resources/azure-ccm-init.sh
freeipa/src/test/resources/azure-init.sh

Due to a missing filter we're configuring the reverse SSH tunnel
on every single instance. This is unnecessary as we're only
communicating with the master instance. With this change only the
instances with GATEWAY type will create the tunnel. FMS has only
1 type of instances.

CB-7940 do not create reverse SSH tunnel on CORE type of instances

---

common/src/main/java/com/sequenceiq/cloudbreak/common/exception/NotFoundException.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxFlowInformation.java
datalake/src/main/java/com/sequenceiq/datalake/flow/create/SdxCreateActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/SdxDeleteActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/handler/RdsDeletionHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/status/SdxStatusService.java
flow/src/main/java/com/sequenceiq/flow/core/AbstractAction.java
flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java

On prod I realized lot of flows are running and most of them are very old. These flows stuck, in SdxCreateActions and SdxDeleteActions the failure handlers could throw exception if sdx cluster is terminated at status save. This problem now handled and I introduced some improvement

CB-7933 Do not fail on sdx status update in Create and Delete action failurehandler

---

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/CloudbreakFlowInformation.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/config/update/PillarConfigUpdateActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/config/update/PillarConfigUpdateFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/config/update/PillarConfigUpdateService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/config/update/PillarConfigUpdateState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/config/update/PillarConfigurationUpdateEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/config/update/event/PillarConfigUpdateFailed.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/config/update/event/PillarConfigUpdateRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/config/update/event/PillarConfigUpdateSuccess.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/config/update/handler/PillarConfigUpdateHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java

This commit adds support for a flow and API call that updates
the salt config on a cluster and then runs the high state to
apply the config.  Primarily this is to allow for the DNS
server IPs to be updated when they change with a FreeIPA node
change.  Since those IPs are pulled from the FreeIPA service
dynamically when a salt config is created it was felt that a
general salt config update flow and API call would allow for
any change the affects the salt config to be updated and
configured on a cluster.
Closes #CB-6364

CB-6364: Create CB core api and flow which updates salt config

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java

`SimpleStatusCheckerTask#handleException` converts errors to `CloudbreakServiceException`
This was not handled in `DecommissionHandler` when running cleanup against FreeIPA causing downscale to fail.
Solution is to catch `CloudbreakServiceException` also.

CB-8001 Downscale failed with a FreeIpaCleanup

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/cluster/clouderamanager/ClouderaManagerProductV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/cluster/clouderamanager/ClouderaManagerV4Response.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/DatalakeUpgradeActions.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxUpgradeServiceTest.java

During upgrade we might change the runtime version. For example
we can upgrade from 7.2.0 to 7.2.1. This version is used on the
UI to offer Data Hubs to create. If it's not updated then the
UI will offer the old runtime version of 7.2.0 which might not
be compatible with the upgraded version of 7.2.1.

CB-8018 update the SDX runtime version after upgrade

---

core/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/ImageBasedDefaultCDHEntries.java
core/src/test/java/com/sequenceiq/cloudbreak/cloud/model/component/ImageBasedDefaultCDHEntriesTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/StackMatrixServiceTest.java

CB-7646 Cloud platform should fall back to AWS in case of missing CDH images

CB-7646 Cloud platform should fall back to AWS in case of missing CDH images

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/.pgpass
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/backup.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/restore.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Closes [CB-7578](https://jira.cloudera.com/browse/CB-7578).
* Make the `.pgpass` file empty if we're using an embedded db
* Pass empty string parameters `""` to the backup and restore script for host url, port, and username
* `psql` cli tools will default to `localhost:5432` and `postgres` as the host, port, and user if none are provided -- this matches up with the embedded db case.
* Provide a configurable location for log output.
The embedded PostgreSQL DB listens at `localhost:5432` and allows connections from the `postgres` system user without credentials.
The normal `/var/logs` directory is not accessible to the `postgres` user without further changes to the system. It was easier to provide configurable logging location.
Tested by copying the salt states over to a Data Lake master …

CB-7578: Run backup and restore against an embedded PostgreSQL database.

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerCloudStorageServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerCloudStorageServiceConfigProviderTest.java

This adds in passing in the cloud paths to Ranger during CM template
construction for SDX.  This is only on 7.2.2 and Azure for now.

CB-7744 passing in cloud paths to SDX.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java

Now you can specify your own sshPublicKey when starting an e2e test locally.

CB-7971 [IT] value of integrationtest.sshPublicKey is not honored

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxUpgradeRequest.java

This removes an unused and incorrectly generated swagger parameter "empty" in request SdxUpgradeRequest.java
`    "SdxUpgradeRequest" : {
"type" : "object",
"properties" : {
"imageId" : {
"type" : "string"
},
"runtime" : {
"type" : "string"
},
"lockComponents" : {
"type" : "boolean"
},
"dryRun" : {
"type" : "boolean"
},
"empty" : {
"type" : "boolean"
}
}
},`

CB-6795 - Remove incorrectly generated swagger field

---

environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialDeleteService.java
environment/src/test/java/com/sequenceiq/environment/credential/service/CredentialDeleteServiceTest.java

Credential deletion can fail so if user initiate multiple delete then we will try to delete the next element as well

CB-7425 If I try to delete in batch, should not fail on the first error

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_install.sh

If FreeIPA installation fails it couldn't be rerun as it would fail
with `FreeIPA already installed`.
In this commit uninstall is added prior install as the installation
script shouldn't run if there was a successful installation.
Only when FreeIPA isn't installed, or the installation failed would
run. This is ensured with the state and not in the script.

CB-8060 Make FreeIPA install retryable

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

**Describe the change you are making here!**
This PR will add Ranger authorizer plugin to Knox topologies [CB-5949](https://jira.cloudera.com/browse/CB-5949). What this means is that ranger policies will be applied to  all the requests flowing through Knox. This should not break any functionality as Ranger side will have policy that will allow all access going though Knox see [OPSAPS-55862](https://jira.cloudera.com/browse/OPSAPS-55862).
**Why is this change needed**
Currently Knox and Ranger are disconnected, there is no way for Ranger to enforce policies on Knox without modifying Knox configs (and Ranger policies). This PR will enable Ranger plugin for Knox so users can update Ranger policies for Knox in on place  (Ranger)
**What the patch does:**
This patch updates the salt files to …

CB-5949 Ranger authorizer support for cdp-proxy and cdp-proxy-api topologies

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/ScalingHandlerUtil.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/MetricEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/event/ScalingEvent.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingHandler.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/ScalingHandlerUtilTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ScalingHandlerTest.java

The periscope starts the alerts one by one. If the first alert finishes before then the last alert starts, the last alert will be skipped because the cooldown is calculated from the last activity field. So, we should send the alerts in batch and iterate after the cooldown check.

CB-7923 MetricEvaluator should send alerts in batch

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterDecomissionService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecomissionService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java

1. The underlying CM API call is generic and it is not tied to any deleting host per se.
2. Saves time during large scale decommission with minimal change in behavior.
3. One of the lower hanging fruits identified at PR #8604

CB-6359 CB-6845 During decommission delete the unused credentials at last.

---

cloud-aws/src/main/resources/templates/aws-cf-dbstack.ftl

Tags of an RDS should be copied to the created snapshots.

CB-8077 AWS RDS: enable CopyTagsToSnapshot

---

cloud-aws/src/main/resources/templates/aws-cf-dbstack.ftl
core/src/main/java/com/sequenceiq/cloudbreak/service/externaldatabase/AwsDatabaseServerParameterDecorator.java
core/src/main/java/com/sequenceiq/cloudbreak/service/externaldatabase/AzureDatabaseServerParameterDecorator.java
core/src/main/resources/application.yml
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/AwsDatabaseServerParameterSetter.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/AzureDatabaseServerParameterSetter.java
datalake/src/main/resources/application.yml
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/database/AwsDatabaseServerParameterSetterTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/database/AzureDatabaseServerParameterSetterTest.java

BackupRetentionPeriod is handled differently between AWS and azure, as well as between SDX and Distrox. All of them should have a meaningful value and set to 30 days for HA and a different value for non-HA scenarios.

RDS: BackupRetentionPeriod should be unified to 30

---

environment/src/main/java/com/sequenceiq/environment/parameters/validation/validators/parameter/AzureParameterValidator.java
environment/src/test/java/com/sequenceiq/environment/parameters/validation/validators/AzureParameterValidatorTest.java

In case the user tries to create an env with single RG but the feature is turned off from entitlement then an error message comes up. It was too technical. Also, if a RG name is specified along with single RG name then another error message comes, it was also too technical.

CB-8098 [ASRG] error message when missing entitlement is not clear

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/client/YarnMetricsClient.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/CronTimeEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ScalingConstants.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/ScalingPolicyTargetCalculator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnResponseUtils.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/event/ScalingEvent.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingHandler.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/TimeAlertRepository.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/CronTimeEvaluatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/ScalingPolicyTargetCalculatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ScalingHandlerTest.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/MockStackResponseGenerator.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/StackResponseUtilsTest.java
autoscale/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Periscope Downscaling Candidates selection is integrated with Yarn Response.
Yarn Scaling Response refactored to be reused between Schedule-Based and Load-Based Autoscaling.

CB-8088 Periscope Downscaling should use YARN downscale recommendation

---

audit-connector/src/main/java/com/sequenceiq/cloudbreak/audit/config/AuditConfig.java
audit-connector/src/test/java/com/sequenceiq/cloudbreak/audit/config/AuditConfigTest.java
integration-test/src/main/java/com/sequenceiq/it/config/AuditBeanConfig.java
integration-test/src/main/resources/application.yml

This configuration item has no default value and it was not asserted before.
Upon audit service call, the endpoint and port was always used and in case it was null, an NPE
was raised by the GRPC client library

CB-8126 Hard fail if audit endpoint configuration is missing

---

core/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/ImageBasedDefaultCDHEntries.java
core/src/test/java/com/sequenceiq/cloudbreak/cloud/model/component/ImageBasedDefaultCDHEntriesTest.java

CB-8131 Image catalog lookup should not fail on multiple default images for the same CDH version. The generated DefaultCDHInfo should be the same so it does not matter which one is used.

CB-8131 Fix image catalog lookup

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/generate_agent_tokens.sh.j2

During salt highstate agent token generation will run only on new nodes.
For this the script will check, that the token has already been generated for the cluster instances and only generates and copies tokens for the newly created ones.

CB-7880 cm_generate_agent_tokens script might not need to be run on every highstate

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

This PR will add Ranger authorizer plugin to Knox topologies CB-5949. What this means is that ranger policies will be applied to all the requests flowing through Knox. This should not break any functionality as Ranger side will have policy that will allow all access going though Knox see OPSAPS-55862.
The changes will be ignored for releases < 7.2.0
Why is this change needed
Currently Knox and Ranger are disconnected, there is no way for Ranger to enforce policies on Knox without modifying Knox configs (and Ranger policies). This PR will enable Ranger plugin for Knox so users can update Ranger policies for Knox in on place (Ranger)
What the patch does:
This patch updates the salt files to add Knox composite authorization that uses ACL and Ranger …

Ranger authorizer support for cdp-proxy and cdp-proxy-api topologies

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/JsonCMLicense.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java
core/src/test/resources/cm-license-empty.txt
core/src/test/resources/cm-license-nojson.txt
core/src/test/resources/cm-license.txt
orchestrator-salt/src/main/resources/salt/salt/cloudera/repo/clustermanager.repo
orchestrator-salt/src/main/resources/salt/salt/cloudera/repo/init.sls

Whenever a cluster is installed from https://archive.cloudera.com
a basic credential must be provided. This credential can be generated
from the CM license file that is provided by UMS. The test credential
can be used to authenticate to this paywall however, in production
each customer gets its own license file. The username is the uuid field
and the password is generated from sha256(name + uuid) and the first 12
characters.

CB-8135 configure paywall credentials to CM yum repo file

---

core/src/main/resources/application.yml

cloudbreak tries to remove node from domain, however the node is missing and salt command is running for 5 minutes and repeats for 10 times without success. Datalake will mark the deletion with failure (because of time out after 60 minutes), but after a while cloudbreak is finishing with the datalake stack deletion (redbeams remains as it was).
I decreased the repeat time to 5 (~25 minutes).
closing cb-5469

CB-5469 datalake shutdown hangs where idbroker node is missing

---

core/src/main/resources/application.yml
datalake/src/main/resources/application.yml

Set to localhost:8982 as it is the default mock grpc service endpoint.
Since a41b1c64157fd30a49ee845c78f83a068e2d6391 the applications will stop with an exception on startup if the default value is not provided.
Now it is set within application.yml

CB-8157 Set default value for audit endpoint

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/client/YarnMetricsClient.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnResponseUtils.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/CronTimeEvaluatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluatorTest.java

Forced Downscale should pass DOWNSCALE_FACTOR_IN_NODE_COUNT as QueryParam and not HeaderParam.
Forced Downscale should be limited to MandatoryDownscale NodeCount

CB-8158-ForcedDownscale

---

orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls

Run 'ipa-client-install --unattended --uninstall' before running the
normal `ipa-client-install` installation and ignore the errors. This
enables a retry after failure to succeed.

CB-8164 Make ipa-client-install idempotent so that a retry can succeed

---

scripts/build-dev.sh

this change was requested by the RE team because it is hard to debug build issues so shrinking down the gradle log level

CB-8170 reduce the logs in the build process

---

README.md

Providing introductory content for the readme for those who would like to contribute to the Cloudbreak project.
The body contains some technical guidelines but in the majority, it points to the formal guidelines of opening a proper pull request.

CB-7826 - Improve CB repository readme with Contribution pipeline

---

orchestrator-salt/src/main/resources/salt-common/salt/fluent/init.sls

As old images can be built but I could not make a good deployment, in order to not fail on this check -> fail on this silently and hope there won't be any hard failure after that ("possibly" not: most likely things won't work with proxies or for ADLSv2, it won't be any log output if Storage contributor is used). With this way, connection problem is logged but won't be any failure, so if in the end we will have a td-agent start issue, there is a log about the connection issue. If there will be network available, plugins will update fine, so that why running the script anyway.

CB-8093. Fail check_fluent_plugins silently

---

environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialService.java
environment/src/test/java/com/sequenceiq/environment/credential/service/CredentialServiceTest.java

- Remove long running credential verification code from the transactional block to avoid long transacition duration
- With verification removal the UserPreferencesService.getExternalId() will be removed from the transactional block. This method call in the transaction was the main reason of the duplicate key error
- Remove notification sending from the transactional block

CB-7490 avoid duplicate key value violates unique constraint "uk_user_crn" error during credential creation

---

environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/PlatformResourceEndpoint.java

the current endpoint using required name parameter so it means if you specify the crn that is not enough. removing the required flag because that is not necessary

CB-8200 getResourceGroups API call using required name parameter

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_promote_replica_to_master.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/update_cnames.sh
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/setup-autotls.sh.j2
orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls
orchestrator-salt/src/main/resources/salt/salt/sssd/template/add_dns_record.j2
orchestrator-salt/src/main/resources/salt/salt/sssd/template/generate_cm_keytab.j2
orchestrator-salt/src/main/resources/salt/salt/sssd/template/join_ipa.j2
orchestrator-salt/src/main/resources/salt/salt/sssd/template/remove_cm_sa.j2
orchestrator-salt/src/main/resources/salt/salt/sssd/template/remove_dns.j2
orchestrator-salt/src/main/resources/salt/salt/sssd/template/reverse_dns.j2
orchestrator-salt/src/main/resources/salt/salt/sssd/ycloud/dns_cleanup.sh

Fix the cloudbreak core DNS A record and reverse registration to
always have a 30 second TTL and to be able to regsister both the
A record and reverse record with salt retries in the case of an
intermittent failure.
More Details:
Cloudbreak core had a fix put in to address scale with CB-6544. But
it turns out this does not always work. When ipa-client-install is
run, it sometimes (but for some reason it does not always) registers
the DNS and reverse DNS. If the ipa-client-install registers DNS
entries then the add_dns_record rule is not run because the unless
clause causes it to be skipped. This presents a few problems.
1. The flag file /var/log/dnsrecord-add-executed is never created. So
every time a salt high state is run the unless clauses which in turn
checks FreeIPA to see if the DNS …

CB-8144: Fix Cloudbreak Core DNS registration and TTL

---

core/src/main/java/com/sequenceiq/cloudbreak/service/metrics/CloudbreakMetricService.java

Ycloud does not have a region so the region metric was throwing a
NullPointerException. This was fixed to only include the region metric
if the value is non-null.
This was tested by deploying a ycloud datalake.

CB-8205: Fix NullPointerException in ycloud metric for region

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxUpgradeRequest.java

The default value of replaceVms was set to DISABLED. This means whenever
an upgrade request is sent without specifying this parameter we didn't
actually replace the VM on the Cloud Provider. This must have been introduced
as VM replacement doesn't work with Runtime upgrade yet. However, OS upgrade
doesn't do anything without VM replacement, hence removing the default value
of this parameter. The SdxRuntimeUpgradeService has a condition to properly
set this value based on the type of the upgrade. As of now the logic says:
isOsUpgrade(request) ? SdxUpgradeReplaceVms.ENABLED : SdxUpgradeReplaceVms.DISABLED.

CB-8215 OS upgrade should automatically replace the VM on Cloud Provider

---

autoscale-api/src/main/java/com/sequenceiq/periscope/common/MessageCode.java
autoscale-api/src/main/resources/messages/messages.properties
autoscale/src/main/java/com/sequenceiq/periscope/controller/AlertController.java
autoscale/src/main/java/com/sequenceiq/periscope/controller/DistroXAutoScaleClusterV1Controller.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandler.java
autoscale/src/test/java/com/sequenceiq/periscope/controller/AlertControllerTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandlerTest.java

Removed user validation for clusterproxy since it is not User Controlled Configuration and duplicate validations.
Update periscope cluster status based on both CB Stack and Cluster Status.

CB-5742-EnhanceErrorHandling

---

autoscale-api/src/main/java/com/sequenceiq/periscope/common/MessageCode.java
autoscale-api/src/main/resources/messages/messages.properties
autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java
autoscale/src/main/java/com/sequenceiq/periscope/controller/DistroXAutoScaleClusterV1Controller.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/BaseAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/LoadAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/MetricAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/PrometheusAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/TimeAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/CronTimeEvaluator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingHandler.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ScalingHandlerTest.java

Standardize single line history format and content for displaying in UI.
The new standardized event text is as below:
Autoscaling has been disabled.
Autoscaling has been enabled.
'LOAD-BASED' Autoscaling Configuration updated; HostGroup(s) 'compute'.
'LOAD-BASED' Autoscaling triggered for Host Group 'compute' from '2' to '0'.
'LOAD-BASED' Autoscaling triggered for Host Group 'compute' from '0' to '2'.
'SCHEDULE-BASED' Autoscaling Configuration updated; HostGroup(s) 'compute'.
'SCHEDULE-BASED' Autoscaling triggered for Host Group 'compute' from '1' to '3'.
'SCHEDULE-BASED' Autoscaling not required for config 'up2'; Host Group  'compute' node count is '3'.
'SCHEDULE-BASED' Autoscaling Configuration 'up3' not triggered, overlaps with 'up2'.
'SCHEDULE-BASED' Autoscaling triggered for Host …

DISTX-413 Single Line Autoscaling History

---

common-model/src/main/java/com/sequenceiq/common/api/telemetry/validation/LoggingRequestValidator.java
common-model/src/main/java/com/sequenceiq/common/api/telemetry/validation/ValidLoggingRequest.java
common-model/src/main/java/com/sequenceiq/common/model/UpgradeShowAvailableImages.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/tags/upgrade/UpgradeV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/UpgradeRequestValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidUpgradeRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeImageFilter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxUpgradeRequest.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxUpgradeShowAvailableImages.java
datalake-api/src/main/java/com/sequenceiq/sdx/validation/UpgradeRequestValidator.java
datalake-api/src/main/java/com/sequenceiq/sdx/validation/ValidUpgradeRequest.java
datalake-api/src/test/java/com/sequenceiq/sdx/validation/UpgradeRequestValidatorTest.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeClusterConverter.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeController.java
datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRepairService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxControllerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/datalake/SdxUpgradeTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxUpgradeTests.java

The commit contains fixes for the following jira tickets:
- CB-8119 - Introduce --show-available-images and --show-latest-available-image-per-runtime
- CB-8120 - --dry-run should return at most one image candidate
The DP CLI counterpart of the effort can be tracked here: https://github.com/hortonworks/cb-cli/pull/763
The documentation will be refreshed here: https://cloudera.atlassian.net/wiki/spaces/ENG/pages/488638097/SDX+upgrade

CB-8119 - Introduce --show-available-images

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/tags/upgrade/UpgradeV4Request.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxUpgradeRequest.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeClusterConverterTest.java

This has the following enhancements:
- unit test for enum value set comparison
- some extra logging
- == instead of .equals for enum comparison

CB-8119 - Introduce --show-available-images - PR follow-ups

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupUtil.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupWaitUtil.java

@lnardai or @Bajzathd please review.
AwsYcloudHybridCloudTest.testCreateSdxOnChildEnvironment is continuously failing, because of the cascading delete is not available right now for environments. Until the backend change is getting ready we need to introduce additional test steps to can deal with deletion of child environment.
I can see:
```
.given(CHILD_ENVIRONMENT_KEY, EnvironmentTestDto.class, CHILD_CLOUD_PLATFORM)
.when(environmentTestClient.forceDelete(), RunningParameter.key(CHILD_ENVIRONMENT_KEY))
.await(EnvironmentStatus.ARCHIVED, RunningParameter.key(CHILD_ENVIRONMENT_KEY))
.validate();
```
However somehow it seems cannot working correctly. May would be worthy to move these steps to an AfterMethod.

CB-8239 Introduce delete child environment steps to the AwsYcloudHybridCloudTest

---

authorization-common/src/main/java/com/sequenceiq/authorization/service/PermissionCheckService.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/PermissionCheckServiceTest.java

When an API that is annotated with InternalOnly is called by a non-
internal actor, it should report "You have no access to this resource"
rather than null.
This was tested by calling an InternalOnly API on a local deployment
of cloudbreak. Unitests were added.

CB-8246: Fix NullPointerException for InternalOnly API access

---

core/src/main/resources/defaults/clustertemplates/azure/azure-streaming-720.json
core/src/main/resources/defaults/clustertemplates/azure/azure-streaming-722.json
core/src/main/resources/defaults/clustertemplates/azure/azure-streaming-small-722.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

This PR enables premium SSD for Kafka brokers in Azure streaming templates. Also adds Azure templates for 7.2.2 (AWS templates already exist)
Testing: tested manual cluster installation on 7.2.0 / 7.2.1 / 7.2.2
Closes: CB-7605

CB-7605 Enable premium SSD in Azure for Kafka, add 7.2.2 Streaming templates for Azure

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/RebootService.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/action/RebootActions.java

Fixed the FreeIPA status so that it didn't get stuck in the "Update
Requested" status after a reboot type repair was issued. The flow now
updates the status each step and sets the final status to a completed
or failed state.

CB-8165: Fix FreeIPA reboot to update the FreeIPA status

---

integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/CloudbreakTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/blueprint/BlueprintTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/credential/CredentialTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/database/RedbeamsDatabaseTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDtoBase.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/image/DistroXImageTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/imagecatalog/ImageCatalogTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ldap/LdapTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/mock/HttpMock.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/proxy/ProxyTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/recipe/RecipeTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDtoBase.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/listener/TestInvocationListener.java

This is a part of [CB-7876 [E2E Environment] Cleanup collision on E2E builds](https://jira.cloudera.com/browse/CB-7876):
>We had issues because of, the previous E2E cleanup build is still ongoing when the new E2E build has been started on the same environment with same provider and user.
>
>So we need to prevent this with introducing the list of created resources (for example list of names of all the created distroxes, sdxes, environments and credentials) for cleanup job.
Preparation of the new Cleanup solution, we need to introduce a solution to collect the deletable resources for Cleanup job. This should be same in format as generating from GUI E2E project. This is mandatory, because of the common usage purposes.
After this was merged, we need to change the API Cleanup App based on …

CB-7876 Save deletable TestContext resource names for API Cleanup

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsTerminateService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsTerminateServiceTest.java

CB-8013 Forced database termination 
* is expected to clean up the database 
* is not expected to fail the environment/sdx deletion flow 
In case of any exception while calling cloud providers' API.

CB-8013 Fix the error handling in case of forced database termination

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/freeipa/FreeIpaDeletionHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaService.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/freeipa/FreeIpaDeletionHandlerTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/action/StackTerminationAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaDeletionService.java
freeipa/src/test/java/com/sequenceiq/freeipa/controller/FreeIpaV1ControllerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaDeletionServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIpaDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java

CB-8014: implement freeipa force delete
- introducing new flag on FreeIpaV1Endpoint.delete() in freeipa microservice: boolean forced
- During environment deletion the forcedelete flag of environmentDeleteRequest will be passed to the freeipe deletion request
- in case of force delete the freeipa service will delete the freeipa related entities even if error occured during the deletion process

CB-8014: implement freeipa force delete

---

flow/src/main/java/com/sequenceiq/flow/reactor/api/handler/ExceptionCatcherEventHandler.java
flow/src/test/java/com/sequenceiq/cloudbreak/reactor/api/handler/ExceptionCatcherEventHandlerTest.java
flow/src/test/java/com/sequenceiq/cloudbreak/reactor/api/handler/ExceptionCatcherEventHandlerTestHelper.java

Fix ExceptionCatcherEventHandler to use the defaultFailureEvent's for
the event's data.
Added unit test.

CB-8261: Fix ExceptionCatcherEventHandler to set the event's data

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentCascadingDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/EnvironmentTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/BasicEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupUtil.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupWaitUtil.java

@biharitomi or @lnardai please review.
This PR relates to [CB-8239 Introduce delete child environment steps to the AwsYcloudHybridCloudTest](https://github.com/hortonworks/cloudbreak/pull/8682).
Unfortunately AwsYcloudHybridCloudTest.testCreateSdxOnChildEnvironment is still failing, because of wait for child environment delete was not implemented along with the previous change. So I'm fixing this missing feature with this commit.

CB-8239 Fix delete child environments at API Cleanup App

---

environment-api/src/main/java/com/sequenceiq/environment/api/v1/credential/endpoint/AuditCredentialEndpoint.java
environment/src/main/java/com/sequenceiq/environment/credential/v1/AuditCredentialV1Controller.java

added /name/{name} endpoint to audit controller. Audit config service - also the CLI - using the name to identify audit credential. To make UI able to fetch credential by name we should extend the current audit credential endpoints with getCredentialByName capability.

CB-8263 Adding getCredentialByName to the audit credential endpoints

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/StackRepoDetails.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeImageFilter.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeImageFilterTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java

Lock components from now on only means locking down components that are actually used (have their parcel activated) on the cluster, eg. by default SDX only uses CDH and if Data Hub might use Nifi parcel then lock components should lock the Nifi version also.

CB-8138 - Lock-components should only lock used parcels

---

integration-test/src/main/resources/application.yml

switch integration tests to 7.2.1 default runtime version

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/BackupRestoreSaltConfigGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/backup/DatabaseBackupHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/restore/DatabaseRestoreHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/BackupRestoreSaltConfigGeneratorTest.java
orchestrator-salt/src/main/resources/salt/pillar/postgresql/disaster_recovery.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/backup.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/restore.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Closes [CB-8207](https://jira.cloudera.com/browse/CB-8207)
* Add `aws_region` pillar value
* Add `--region` parameter to backup and restore script `aws` invocations 
* Add `aws_region` to the `BackupRestoreSaltConfigGenerator`
* Update test for `BackupRestoreSaltConfigGenerator`
* Pass in `Stack` object to `BackupRestoreSaltConfigGenerator`
Tested by:
* Running salt `state.apply postgresql.disaster_recovery.bakup` and `state.apply postgresql.disaster_recovery.restore` manually in Data Lake with external DB.
* Triggering backup + restore using the Datalake API while running with an external DB.

CB-8207: Add --region flag to aws s3 cp command for datalake backup/restore

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigView.java
freeipa/src/main/resources/freeipa-salt/salt/freeipa/init.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/replica-install.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_install.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_replica_install.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/templates/resolv.conf.j2

When installing FreeIPA replicas, do not require /etc/hosts on all
FreeIPA servers to reference all other FreeIPA servers. Instead, use
/etc/resolv.conf to bootstrap DNS. Then run ipa-client-install to
bootstrap the replica's DNS record. Then run ipa-replica-install to
replicate the DNS records via LDAP to the localhost.
This was tested by doing several repairs on a FreeIPA cluster that was
provsioned using a local instance of cloudbreak.

CB-8271: Bootstrap FreeIPA replica install without using /etc/hosts

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/DnsRecord.java
freeipa-client/src/test/java/com/sequenceiq/freeipa/client/model/DnsRecordTest.java

When FreeIPA is downscaled or repaired, the SSHFP DNS records were fix
to be removed.
This was tested with unittests and using a local deployment of
cloudbreak.

CB-8275: Fix FreeIPA downscale to remove SSHFP DNS records

---

auth-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/usermanagement/UserManagementGrpc.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/config/UmsClientConfig.java
auth-connector/src/main/proto/usermanagement.proto
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClientTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/CloudIdentitySyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UmsUsersState.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/CloudIdentitySyncServiceTest.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java

The ums client has been updated to allow listing cloud id assignments
for service principles This is used to sync the azure object ids
associated with service principles.

CDPCP-2678. Support syncing service principle cloud ids

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleServiceTest.java

Scenario: 2 nodes are deleted on AWS side, but we are trying to delete 4 nodes. It failed because 2 of 4 nodes are detached already. Solution is to remove these nodes from the request and try again.

CB-8083 autoscaling group detach can fail if some of the nodes are detached already

---

redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/action/RedbeamsProvisionActions.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/start/actions/StartDatabaseServerFailedAction.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/start/actions/StartDatabaseServerFinishedAction.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/stop/actions/StopDatabaseServerFailedAction.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/stop/actions/StopDatabaseServerFinishedAction.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/action/RedbeamsTerminationActions.java
redbeams/src/main/java/com/sequenceiq/redbeams/metrics/RedbeamsMetricService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/DBStackService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/DBStackStatusUpdater.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsStartService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsStopService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsTerminationService.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/start/actions/StartDatabaseServerFailedActionTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/start/actions/StartDatabaseServerFinishedActionTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/stop/actions/StopDatabaseServerFailedActionTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/flow/redbeams/stop/actions/StopDatabaseServerFinishedActionTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/stack/DBStackStatusUpdaterTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/stack/RedbeamsStartServiceTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/stack/RedbeamsStopServiceTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/stack/RedbeamsTerminationServiceTest.java

Problem: termination went failed because of an OptimisticLockException at delete of DBStack. Nevertheless the entry was deleted and the status could not be set during the failure handling (NPE), leading to another failure. This commit fixes setting the status and tries to fix the OptimisticLockException as well.

Missing error handling for RedbeamsTerminationActions$4

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationActions.java

Default payload converters were overriden:
`2020-07-16 11:25:05,302 [reactorDispatcher-10] convertPayload:206 ERROR c.s.f.c.AbstractAction - [type:springLog] [crn:] [name:] [flow:4f9984f2-0160-480d-bdd1-3e1bf52f158d] [requestid:] [tenant:] [userCrn:] [environment:] [traceId:cca5abf45afe607e] [spanId:cca5abf45afe607e] No payload converter found for ClusterPlatformResult{status=FAILED, statusReason='query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2', errorDetails=org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2}, payload will be null`

CB-7991 Payload converters overriden for ClusterTerminationAction

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaOperationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaTerminationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaWaitObject.java

`FreeIpaTests.testCreateStopStartFreeIpaWithTwoInstances` is failing, because of:
```
await FreeIpaTestDto[name: aws-test-fa865a9c43084e57bcf78e0a20fc1d7] for desired statuses DELETE_COMPLETED: Stack by environment [crn:cdp:environments:us-west-1:qe-aws:environment:31eb02d0-47b1-459f-b79e-9ce1dc352eaa] not found
```
```
2020-08-04 12:08:38,936 [TestNG-test=aws-e2e-tests-3] ERROR c.s.i.c.u.w.s.freeipa.FreeIpaAwait [FreeIpaTests.testCreateStopStartFreeIpaWithTwoInstances] - await [FreeIpaTestDto[name: aws-test-fa865a9c43084e57bcf78e0a20fc1d7]] is failed for statuses DELETE_COMPLETED: javax.ws.rs.NotFoundException: HTTP 404 Not Found, name: aws-test-fa865a9c43084e57bcf78e0a20fc1d7
2020-08-04 12:08:38,944 [TestNG-test=aws-e2e-tests-3] ERROR c.s.i.c.util.ErrorLogMessageProvider …
```

CB-8269 FreeIPA Termination Checker Success reporter throws 404

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/DownscaleFlowEvent.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/event/DownscaleFailureEvent.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/CollectAdditionalHostnamesHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/RemoveHostsHandler.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/RemoveHostsHandlerTest.java

The failure handlers' selector was changed to be unique for
RemoveHostsFromOrchestrationRequest and CollectAdditionalHostnamesRequest
so that both failure handlers can be executed.
This was tested by forcing an error and validadting that the failure
handler executed for both flow steps.

CB-8310: Fix failure handler for RemoveHostsFromOrchestrationRequest

---

datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeController.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeControllerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java

When the Runtime upgrade entitlement is disabled and the SDX upgrade
request does not specify the type of the upgrade we should assume
OS upgrade. In this case the request should be accepted and treated
like OS upgrade. In case the entitlement is enabled we check for both
OS and Runtime images for upgrade candidate. If the user specifies
the --runtime flag and the entitlement is disabled the request should
be rejected.
When the Runtime upgrade is disabled and the show-all or show-latest-by-runtime is invoked
it should lock the components and treat it like an OS upgrade.

CB-8325 only reject runtime requests if the entitlement is disabled

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/service/url/UrlAccessValidationService.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackImageImporter.java
cloud-openstack/src/test/java/com/sequenceiq/cloudbreak/cloud/openstack/common/OpenStackImageImageImporterTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/ManagementPackDetailsToManagementPackComponentConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v2/cli/StackRepoDetailsToStackRepoDetailsJsonConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/RepositoryConfigValidationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/PaywallCredentialService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/mpack/ManagementPackCreationValidator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/RepositoryConfigValidationServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/mpack/ManagementPackCreationValidatorTest.java

Neither on the fly validation on the UI upon entering (or changing) the
mpack URL, nor for the check upon registration did not send the basic
authorization header with the request thus getting a HTTP 401.
This had to be fixed in 2 places.

ENGESC-3405 Fix mpack validation issue for urls behind paywall

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudCredentialStatus.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsDefaultRegionSelector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsDefaultZoneProvider.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResources.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsCredentialView.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsAuthenticatorTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnectorTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsDefaultRegionSelectorTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceConnectorTest.java
environment/src/main/java/com/sequenceiq/environment/credential/service/ServiceProviderCredentialAdapter.java

Regarding CB-4915 a new mechanism has been implemented that verifies that the credential which is under creation is able to query regions. If regions could not be described using the globally set default region which is `us-east-1` then it tries to describe regions in different EC2 regions. This list of possible default is configurable, but the defaults are stored in environment service's `application.yml`. Once the describe of regions works from a region then the region is persisted on credential side as a new attribute. This means that AWS related services will picked the credential specific region as default when it is possible/necessary.
During the tests it turned out this describe region process takes some time due to a bug in AWS Java SDK: …

CB-4915 Respect region disablement policies of customer AWS accounts

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/main/resources/application.yml

Added medium duty ha entitlement capabilities and tests to SDX cluster creation logic
Implementation inspired by: https://github.com/hortonworks/cloudbreak/commit/a04709441071729e4019c2c487f2f7f0c9ee5fd9 
Flow is as follows:
1. Request comes into cloudbreak via SdxClusterRequest.java with enableMediumDutyHA attribute 
2. Logic in SdxService.java validates that the entitlement is enabled via the EntitlementService.java and that the runtime is greater or equal to 7.2.2 if enableMediumDutyHA is requested - errors out otherwise
Tests added validate the following scenarios:
- Valid request, valid runtime, valid entitlement permissions
- Valid request, valid runtime, invalid entitlement permissions
- Valid request, invalid (7.1.0) runtime, valid entitlement permissions
- Valid request, invalid …

[CB-8188] Add Medium Duty HA Entitlement enforcement

---

core/src/main/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupService.java

DefaultCDHInfo was filled out with parcels in 2.18 last time from the application.yml. Parcel configurations got removed in 2.19 but the related java code remained in the codebase. As a part of CB-7647 parcels got filled out again in the DefaultCDHInfo based on the latest greatest prewarmed image - it was necessary for the stack matrix - but the remained parcel fillup caused that cluster product components are coming from the DefaultCDHInfo. As a part of this PR I'm simply remove the DefaultCDHInfo based product fill-up as it was a dead code since 2.19.

CB-8342 Cluster product components should not come from DefaultCDHInfo

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

**Describe the change you are making here!**
CB-5949 Adds ranger authorization support for requests flowing through Knox. This only works for SDX cluster and not for DistroX clusters. This is because the logic to enable ranger authorizer checks if Ranger is installed and ranger is not installed on DistroX clusters but rather installed in SDX cluster. This PR proposes eliminating condition that checks whether ranger is installed on the cluster. By default all public cloud clusters have Ranger installed so this change will not affect any functionality.
**Testing**
This patch was locally tested (tested to see that the topology file is generated correctly)

CB-8311 - Ranger authorizer should be enabled for datahub clusters

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_install.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_replica_install.sh

Fixed the DNS forwarding to use the DNS server provided by the
original DHCP lease rather than pointing to the master which points to
the one from the cloud provider.
Use the same logic for the master too eventhough it didn't matter.
This was validated by deploying a FreeIPA HA cluster with a local
cloudbreak deployment and validating the dns forwarder settting in
LDAP.

CB-8329: Fix DNS forwarding on FreeIPA replicas

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/generate_agent_tokens.sh.j2

It can happen that salt cp.get_file command returns False, but we still create
the check file so we don't try to generate and copy again. This process is time
consuming that is why we are trying to skip it whenever we can. However, if it
returns False the copy was not successful an we need to try again.
Example output when the result is False, no agent_token_copied_to_client is created.
```
+ [[ ! -e /srv/salt/agent-tls-tokens/krisz-datalake-1-master0.krisz-en.xcu2-8y8x.wl.cloudera.site-i-08b5a305ef6dfda31/agent_token_copied_to_client ]]
++ salt krisz-datalake-1-master0.krisz-en.xcu2-8y8x.wl.cloudera.site cp.get_file salt://agent-tls-tokens/krisz-datalake-1-master0.krisz-en.xcu2-8y8x.wl.cloudera.site-i-08b5a305ef6dfda31/cmagent.token alma/etc/cloudera-scm-agent/cmagent.token
+ …
```

CB-8351 Fix the cluster installation if we can't copy the agent token

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/YcloudHybridCloudTest.java

The mock tests are extended with a new Ycloud hybrid cloud related use case, which is similar to the handled scenario and parameters of AwsYcloudHybridCloudTest e2e test. The test is executed against mock provider and validates the content of request that must include the instance groups, parcel and repository information.

CB-8243: Implement mock test related to the Ycloud hybrid cloud usecase

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java

Investigables may return null (for example when they do not have a response), so the clues should be filtered out before getting passed to ErrorLogMessageProvider.

CB-8362 Fix ErrorLogMessageProvider NPE

---

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ExistingResourceByCrnOrNameRestUrlParser.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentOpDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/EnvironmentReactorFlowManager.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/config/update/AbstractEnvStackConfigUpdatesAction.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/config/update/EnvStackConfigUpdatesActions.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/config/update/EnvStackConfigUpdatesState.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/config/update/config/EnvStackConfigUpdatesFlowConfig.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/config/update/event/EnvStackConfigUpdatesEvent.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/config/update/event/EnvStackConfigUpdatesFailedEvent.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/config/update/event/EnvStackConfigUpdatesHandlerSelectors.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/config/update/event/EnvStackConfigUpdatesStateSelectors.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/config/update/handler/StackConfigUpdatesHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/poller/StackPollerProvider.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentStackConfigUpdateService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/stack/StackPollerService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/stack/StackService.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java
environment/src/main/java/com/sequenceiq/environment/metrics/MetricType.java
environment/src/test/java/com/sequenceiq/environment/environment/poller/StackPollerProviderTest.java

This adds an API and flow to the environment service which allows for
the updating of all of an Environments Stacks pillar configs.
This is primarily needed for FreeIPA right now, when a FreeIPA DNS
server changes IP to allow all of the Clusters within an environment
to update their DNS server IP addresses.
The API added is:
POST /v1/env/crn/{crn}/update_config
These do not have authorization on them and should only ever be
called from internal to the Control Plane.  They kick off the
EnvStackConfigUpdates Flow which collects all of the stacks for
the environment and calls the Cloudbreak API and Flow created in
CB-6364.  It does not monitor these flows, it just keeps
retrying until it successfully submits a request for the pillar configs
to be updated.
If another call to update the …

CB-6363: Create an Env api and flow which updates the Envs Stacks pillar configs

---

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/BackupRestoreSaltConfigGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/RangerVirtualGroupService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/backup/DatabaseBackupHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/restore/DatabaseRestoreHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/BackupRestoreSaltConfigGeneratorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/RangerVirtualGroupServiceTest.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/runner/SaltRunner.java
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/backup.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/restore.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Here is the summary of the code changes.
1. Pass the ranger_admin_group name from  CB -> salt pillar on the datalake database backup.
2. Pass the ranger_admin_group name from CB -> salt pillar on the datalake database restore.
3. Use a configured retry attempts to get the status of datalake database backup-restore operations and also retry count on failures.
4. Changes to database backup script to replace the group name in the ranger back up with the hardcoded KEYWORD before writing to S3.
5. Changes to database restore script to replace the hardcoded KEYWORD with the group name in the ranger back up with before using to restore the database.
**Tests:**
1. Updated existing tests to cover the change that was made.
2. I created an environment with these changes in place and made sure that …

CB-8274: Re-write ranger admin group in ranger policies.

---

autoscale/src/main/java/com/sequenceiq/periscope/service/HistoryService.java

when different user tries to enable or disable autoscaling on the cluster then the creator, we throw an access denied exception even if the users added to the workspace. From now, the history will be assigned to the operation executor instead of the cluster creator

ENGESC-2921 Need cloudbreak APIs to enable autoscaling

---

orchestrator-salt/src/main/resources/salt-common/salt/filecollector/collect.sls

Came out during e2e test writing
- seems like it's not possible to concat string inside a for loop with jninja (that way how I did)
- items cannot be called on jinja list object
- `label_str` is not exists anyway, so that would throw an exception

CB-8376. Label filter is not working for diagnostics collections.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java

VM Power State can be null. User or control plane initiated operation states will appear as Provisioning States. Logged those too for clarity.

CB-8360 Handle that Azure API does not return a power state every time

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorage.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorageAccountTemplateBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorageAccoutTemplateProviderService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureStorageAccountBuilderService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/StorageAccountParameters.java
cloud-azure/src/main/resources/templates/arm-storageaccount.ftl
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorageAccountTemplateBuilderTest.java
core/src/main/resources/application.yml
freeipa/src/main/resources/application.yml

The storage account for holding images in customer subscription has a parameter "allow blob public access", the default is true. Some customers do have a policy that do not allow to create an account with such settings, so cloudbreak should also create SA with disallow blob public access.
Note: changed to master

CB-8308 [azure] image storage account public access should be false

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/RangerCloudIdentitySyncStatus.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java

This commit adds a response object to the setRangerCloudIdentityMapping API.
This change causes the swagger compatibility check to fail. We are adding
this change to the 2.27 branch and ignoring the compatibility check failure
so that compatibility checks on the 2.28 branch will pass.

CDPCP-2673. Add response to setRangerCloudIdentityMapping API

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-702.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-722.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-702.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-722.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-722.bp

1. Trash interval was set to zero, and skip trash was set to false for performance reasons consciously CB-7053.
2. This triggered a couple of warnings in CM.
3. Suppressing these because the customer can not do anything about it, and in-fact wondering what those were.
4. The change here was convoluted so will explain what is going on,
a. I did not copy the trash interval settings in the HA template in 702. That is why it is missing some configs in some templates.
b. So the suppressions were added to the config only if there would have been a warning otherwise.
5. These settings were manually modified in the CM and then the template was exported so that we know what setting to add and at which level.

ENGESC-3627 Disable thrash related warnings in DE clusters.

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/RangerCloudIdentitySyncState.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/RangerCloudIdentitySyncStatus.java
datalake/src/main/java/com/sequenceiq/datalake/cm/ClouderaManagerRangerUtil.java
datalake/src/main/java/com/sequenceiq/datalake/cm/RangerCloudIdentityService.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/cm/ClouderaManagerRangerUtilTest.java
datalake/src/test/java/com/sequenceiq/datalake/cm/RangerCloudIdentityServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/configuration/CloudIdSyncConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/CloudIdentitySyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/polling/usersync/CloudIdSyncPollerObject.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/polling/usersync/CloudIdSyncStatusListenerTask.java
freeipa/src/main/resources/application.yml
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/CloudIdentitySyncServiceTest.java

When setting cloud identity settings in ranger, the SDX service
now also returns a status object that the caller can use to
poll the status of the sync (which is just the status of the underlying
CM refresh command). The FreeIPA service polls this object to verify
that the sync is successful.
In order to simplify the design, the cloud identity sync code
has been modified to only work for single datalake per environment
and fail if there are multiple datalakes present (which we currently
don't support anyway).

CDPCP-2673. Poll status of refresh when syncing OIDs

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/start/ClusterStartActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/start/ClusterStartEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/start/ClusterStartFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/start/ClusterStartState.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/ClusterStartPillarConfigUpdateRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/ClusterStartPillarConfigUpdateResult.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterStartPillarConfigUpdateHandler.java

Co-authored-by: Brian Towles <btowles@cloudera.com>
When a datalake or datahub is started, update the pillar
configuration. This ensures that if the FreeIPA IP addresses changed
while the datalake was stopped then cloudbreak will update the FreeIPA
IP addresses when starting the stopped instances.
This was tested manually by ensuring the pillar configuration was
called on a local instance of cloudbreak.

CB-8031: Update pillar configuration when starting cluster

---

freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java

Currently we set the MDCContext before checking if a flow is running. If a flow is running we skip sync, but the code will skip MDCContext cleanup also.
This commit modifies the code to ensure cleanup is happening.

CB-8435 StackStatusCheckerJob should always cleanup MDC

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-702.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-722.bp

1. Telemetry publisher needs to have HDFS redaction enabled.
2. With these settings being false, the customer sees that the telemetry publisher does not start.
3. Since normal templates are working fine, removing the config to leave it to default.

DISTX-530 DE HA template does not work with telemetry publisher

---

core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha-722.bp
datalake/src/main/resources/runtime/7.2.2/aws/medium_duty_ha.json
datalake/src/main/resources/runtime/7.2.2/azure/medium_duty_ha.json
datalake/src/main/resources/runtime/7.2.2/yarn/medium_duty_ha.json

This updates the SDX Medium Duty templates to have hbase on the gateway node and
resizes the node instances.  This also enables 2 nodes for IdBroker as well.

CB-8377 Updating Medium Duty layout

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_healthagent_setup.sh

Fix the freeipa_healthagent_setup.sh so that it works with multiple
instances of FreeIPA.
This was tested with a local deployment of cloudbreak by deploying a
2 node FreeIPA cluster.

CB-8478: Fix freeipa_healthagent_setup.sh to work with FreeIPA HA

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CloudProviderSideTagAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/SparklessTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java
integration-test/src/main/java/com/sequenceiq/it/util/TagsUtil.java
integration-test/src/test/java/com/sequenceiq/it/util/TagsUtilTest.java

We have [CB-7706](https://jira.cloudera.com/browse/CB-7706) for E2E tag validation. The affected test case is [EnvironmentStopStartTests](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java).
However we cannot check the validation at test logs, because of the related log messages (Console and HTML) are missing. Beyond this `Owner` and `Cloudera-Creator-Resource-Name` not null validation should be extended with asserts. If these two do not contain the acting user, we need to fail the test.

CB-8497 Improve tag validation and introduce result logs

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleActions.java

Azure DL master repair failed due to missing instance metadata:
`Error during execution of com.sequenceiq.cloudbreak.core.flow2.stack.upscale.StackUpscaleActions$5
java.lang.NullPointerException: null
at com.sequenceiq.cloudbreak.converter.spi.InstanceMetaDataToCloudInstanceConverter.convert(InstanceMetaDataToCloudInstanceConverter.java:34)`
Azure did not respond with VM data for some reason:
`August 12th 2020, 08:32:40.293 | 2020-08-12 06:32:40,293 [reactorDispatcher-93] hasMissingVm:85 INFO  c.s.c.c.a.AzureVirtualMachineService - [...] Fetched VM id-s ([]) do not contain one of the following id-s: [azure-test-d79e97e7d96d4624b1f6d47c385c64090m2]`
`August 12th 2020, 08:32:40.293 | 2020-08-12 06:32:40,293 [reactorDispatcher-93] hasMissingVm:85 INFO  c.s.c.c.a.AzureVirtualMachineService - …

CB-8412 Gracefully fail if gateway metadata missing during repair

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java

FreeIpaTests.testCreateStopStartFreeIpa was removed, as it is part of the EnvironmentStopStartTests.testCreateStopStartEnvironment
FreeIpaTests.testCreateStopStartFreeIpaWithTwoInstances and testCreateThenRepairFreeIpaWithTwoInstances was combined to testCreateStopStartRepairFreeIpaWithTwoInstances
SdxRepairTests.testSDXRepairIDBRokerWithStoppedEC2Instance and testSDXRepairMasterWithStoppedEC2Instance was combined to testSDXRepairMasterAndIDBRokerWithStoppedEC2Instance

CB-7714 Combine e2e test cases

---

autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterPertainRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/HistoryRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/LoadAlertRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/PeriscopeNodeRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/ScalingPolicyRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/SecurityConfigRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/SubscriptionRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/TimeAlertRepository.java

All existing Periscope Repository interfaces should be annotated with Transactional attribute similar to CB Repository interfaces, since without that Query Results will not be pre-flushed and stale data will be returned in certain scenarios.

CB-8505-AssociatePeriscopeRepositoryWithTransaction

---

core/src/main/resources/application.yml

CB-8531 m5.xlarge missing in the instance type list

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/telemetry/TelemetryTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java

In case of failing Hybrid Cloud E2E test we have no chance to check the issue in Kibana. So we need to introduce the related Telemetry configuration steps to the Yarn Environment creation.
First of all Cloudbreak should [allow Telemetry with no Logging Object](https://github.com/hortonworks/cloudbreak/pull/8846), this is needed only for YCloud where the Cloud Storage is not available. Beyond this we should modify the related E2E test case [AwsYcloudHybridCloudTest](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java) as well.

CB-8470 Update AwsYcloudHybridCloudTest child environment with Telemetry steps

---

common/src/main/java/com/sequenceiq/cloudbreak/logger/LoggerContextKey.java
common/src/main/java/com/sequenceiq/cloudbreak/logger/MDCBuilder.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/chain/AbstractCommonChainAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/AbstractFreeIpaCleanupAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/action/AbstractDownscaleAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/repair/changeprimarygw/action/AbstractChangePrimaryGatewayAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/upscale/action/AbstractUpscaleAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/action/AbstractRebootAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/action/RebootActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java
freeipa/src/main/resources/logback.xml

Add the operation ID to the FreeIPA logs for repair.
Change the user sync to use the operationId for the operation ID
rather than the flowId.
Ensure the MDC cleanup happens if an exception is thrown.

CB-8401: Add the operation ID to the FreeIPA logs

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/NewNetworkWithNoInternetEnvironmentTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxDistroxTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxRepairWithRecipeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxImagesTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsSdxSpotInstanceTest.java

The SdxService is extended with a new functionality which checks the cloud storage parameter, except in case of mock or yarn provider. Previously this was not mandatory, but useless clusters were created without this parameter.
The corresponding unit and e2e tests are also adjusted which means that mentioned parameter is also specified for the related tests.

CB-8303: Make sure that you cannot create a DL without cloud storage

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxCreateAction.java

SdxResponse was not set in the testcontext resulting in NPE

CB-7930 during SdxCreateAction SdxResponse was not set in the testcontext

---

datalake/src/main/java/com/sequenceiq/datalake/cm/RangerCloudIdentityService.java
datalake/src/test/java/com/sequenceiq/datalake/cm/RangerCloudIdentityServiceTest.java

This ensures that we only make the CM api calls to set cloud
identity configs on CM's that are running.

CDPCP-2822. Ensure datalake is running before triggerring OID sync

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CloudProviderSideTagAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java
integration-test/src/main/java/com/sequenceiq/it/util/TagsUtil.java

We have [CB-7706](https://github.com/hortonworks/cloudbreak/pull/8534) for tag validation during E2E tests. The affected test case is [EnvironmentStopStartTests](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java). However we cannot check the validation process at test logs, because of the related log messages are missing.

CB-8497 Fix validation for cloud provider resource tags

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxCheckForUpgradeAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxUpgradeAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonClusterManagerProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxUpgradeTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxUpgradeTests.java
integration-test/src/main/resources/application.yml
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/sdx-upgrade-tests.yaml

- The test creates an SDX cluster with integrationtest.upgrade.currentRuntimeVersion runtime version
- The test upgrades the SDX cluster to the integrationtest.upgrade.targetRuntimeVersion runtime version
- The test checks that the attached volumes are the same after the upgrade

CB-6796 E2E test for SDX cluster upgrade flow

---

freeipa/src/main/resources/freeipa-salt/salt/nginx/conf/ssl-locations.d/freeipahealthcheck.conf

Forward freeipa:9443/freeipahealthcheck to freeipa:8050/.

CB-8546: Fix FreeIPA health check to work with nginx proxy

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AccountMappingSubject.java
cloud-common/src/test/java/com/sequenceiq/cloudbreak/service/identitymapping/AccountMappingSubjectTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AwsMockAccountMappingService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/AzureMockAccountMappingService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/identitymapping/AwsMockAccountMappingServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/identitymapping/AzureMockAccountMappingServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerCloudStorageServiceConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatahubConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatalakeConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerCloudStorageServiceConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatahubConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatalakeConfigProviderTest.java

* Refactor AccountMappingSubject: extract user rangerraz as the new
constant RANGER_RAZ_USER, rename DATA_ACCESS_AND_RANGER_AUDIT_USERS
to ALL_SPECIAL_USERS.
* Add S3 to ModelDescriptions.ClusterModelDescription.ENABLE_RANGER_RAZ.
* Extend cloud provider restriction with AWS in
RangerCloudStorageServiceConfigProvider,
RangerRazDatahubConfigProvider, RangerRazDatalakeConfigProvider and
SdxService.validateRazEnablement.
* Change CM version check in RangerRazDatalakeConfigProvider to use
7.2.2 for AWS and 7.2.1 for Azure.
* Add CM 7.2.2 version check to RangerRazDatahubConfigProvider (to make
it in sync with RangerRazDatalakeConfigProvider).
* Update all related unit tests and add some new cases.

CB-8053 Enable RAZ for AWS

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-722.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-722.bp

Fix for [CDPD-11918](https://jira.cloudera.com/browse/CDPD-11918)
Have tuned following tez configs in DE templates for 7.2.2 :-
tez.grouping.split-waves=1.4
tez.grouping.min-size=268435456
tez.grouping.max-size=268435456
These changes are also required for AutoScale.
Testing done:
1. Have created a DE cluster using a modified 7.2.2 template that includes above mentioned tez config changes. Cluster creation was successful on AWS using m5d.2xl instance types.
2. Ran some hive queries successfully.

Fix for CDPD-11918

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java

ClouderaManagerModificationService changes
- callUpgradeCdhCommand()
- if upgrade command is running, cb won't call a new command, but polling the current one
- if upgrade command throws exception, that the cluster is already upgraded, skip this step and continue with the following steps
- in case of patch upgrade: restartServices()
- if there is an already running Restart Services command, polling the result of that command, otherwise start a new Restart Services command and waiting its result

CB-8372 Make the upgrade CM API calls idempotent

---

freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/config/KerberosConfigRegisterService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/config/LdapConfigRegisterService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ClusterProxyService.java
freeipa/src/main/java/com/sequenceiq/freeipa/util/BalancedDnsAvailabilityChecker.java
freeipa/src/main/java/com/sequenceiq/freeipa/util/HealthCheckAvailabilityChecker.java
freeipa/src/main/resources/application.yml
freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/config/KerberosConfigRegisterServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/config/LdapConfigRegisterServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/util/BalancedDnsAvailabilityCheckerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/util/ClusterProxyServiceAvailabilityCheckerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/util/HealthCheckAvailabilityCheckerTest.java

Register the FreeIPA healthcheck with cluster proxy for new clusters.
Continue using the old login page as the status check for clusters
that were provisioned prior to the healthcheck's existence.

CB-8547: Use FreeIPA healthcheck for cluster proxy

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java

As salt state upgrade made into codebase we don't have to check if
the correct states are present on the cluster as the upgrade starts
with pushing recent states to the cluster.

CB-7040 Remove upgrade salt state presence check on GW instance

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/StackCreatorServiceTest.java

The hostgroups are sorted to follow same privateId generation pattern for a given template.
Gateway hostgroups start with privateId 0 (the hosgroup which maps to various endpoints like CM-API, HiveServer..).
If multiple hostGroups are marked gateway then they are processed alphabetically so privateId remains same and hence hostName remaing same for a given template.
Gateway hostgroups as defined in various default templates
1. DE : master
2. DE HA  : manager
3. Datamart : master
4. Flink : manager
5. FlowManagement : gateway

CB-6185-Consistent HostNames

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentBuildNumberComparator.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentBuildNumberComparatorTest.java

The UI calls the upgrade API with --show-latest-available-image-per-runtime
which does not show images with the same GBN version. Whenever I specify
--lock-components it shows those images as well. However, since we don't
want to call the upgrade API 2 times with different parameters the show
latest should show the same GBN images as well.

CB-7741 show images with same GBN without specifying --lock-components

---

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java
authorization-common/src/main/resources/legacyRights.json
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/reboot/RebootInstancesRequest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/repair/RepairInstancesRequest.java

Use environments/repairFreeIPA when checking the authorization action
for FreeIPA repair and reboot.

CDPSDX-2405: Use environments/repairFreeIPA for FreeIPA repair auth

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

HBASEJARS services in cdp-proxy-api topology needs acls just like other services defined in topology_api.xml.j2
This is a very simple change and should not have any side effects.

CB-8577 - cdp-proxy-api topology files needs ACLs for hbasejars service

---

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/TelemetryConfiguration.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigService.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigView.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/metering/MeteringConfigService.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/metering/MeteringConfigView.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/metering/MeteringConfiguration.java
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigServiceTest.java
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/metering/MeteringConfigServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecorator.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/TelemetryDecoratorTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/TelemetryApiConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverterTest.java
orchestrator-salt/src/main/resources/salt-common/pillar/fluent/init.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/init.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/databus_metering.conf.j2
orchestrator-salt/src/main/resources/salt/pillar/metering/init.sls
orchestrator-salt/src/main/resources/salt/salt/metering/settings.sls
orchestrator-salt/src/main/resources/salt/salt/metering/template/generate_heartbeats.ini.j2

details:
- adding 2 new global configs for CB - metering app and stream name (creating a new metering configuration object for those)
- the configs are passed to salt configurations (app & stream -> used by fluentd, stream also used by metering service for a check)
- added a few new fields based on the new metering version (v2), using cluster name + using tags for some specific fields (also start using the service type tag if that exists)
- old format will be still used, if: no metering_prewarmed_v2 role, no cluster name field, no stream name field, or if the stream name field is 'Metering' (as that is valid for the old format)
- metering_prewarmed_v2 will be set in cloudbreak-images project. as a snapshot version is used for metering, without versions, with that grain we can be sure we …

CB-8123. DH: Metering-related workload changes

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceConnector.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceConnectorTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureInstanceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java

Use combined stop/start operations in the FreeIPA instance reboot flow so that FreeIPA repair will wait for the AWS/Azure nodes to return to an actual running state. Currently, during a reboot operation, the AWS/Azure nodes always report a running state (this is so that the billing doesn't start billing a new session). With this fix, the reboot flow will actually finish. AWS will only bill for a minimum of 60 seconds each time a new instance is started.

CB-8248: FreeIPA reboot flow finishes before instances reboot

---

freeipa/src/main/resources/application.yml

Increase the FreeIPA operation serivice timeout from 30 minutes to 1
hour. This will allow the repair to complete without a timeout. A
repair may take more than 30 minutes if there are multiple instances
being repaired.
This was manually tested using a local cloudbreak.
I am suggesting this for 2.29 since has affected FreeIPA HA and that is planned for 2.29. Without this fix, it will likely allow only repairing a single instance of FreeIPA HA at a time without timing out.

CDPSDX-2413: Increase FreeIPA operation timeout to 1 hour

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/cloud/StackToCloudStackConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/CreateFreeIpaRequestToStackConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/InstanceMetaData.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverterTest.java

1. The hostname is reset by Google network manager https://groups.google.com/g/gce-discussion/c/fi2j7oP8bGM/m/mRYlt5OkDgAJ if the hostname is not set during creation.
2. This will break the freeipa health agent setup since it depends on the hostname of the instance having a proper domain.
3. Tested this change in the private stack to make sure Google does not reset the hostname that was set by salt.
4. Added a few more debug statements that were helpful in identifying why the hostname was null for the initial 100 seconds of GCP VM provisioning. Prior to this change, the hostname was available only in instance metadata only at the last host metadata collection step.

CB-3261 For GCP support add the hostname to the instance while bringing it up.

---

orchestrator-salt/src/main/resources/salt/salt/metering/init.sls

CB-8630. Metering OS support warning is logged even for CentOS

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeImageFilter.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeImageFilterTest.java

`1 PR 2 related changes hence the 2 commits`
Previously, we only filtered the older images by date
when you wanted to perform an OS upgrade. With this change
the older images will be filtered even if you want to perform
a runtime upgrade.
We offered images for upgrade if either the CM or the CDP version
was newer on the image. However, this is not optimal as we would
allow you to upgrade to a newer CDP where the CM is older an it would
mean a downgrade on CM. It is true the other way around as well. With
this change we are only offering images where both CM & CDP versions
are newer than before.

CB-8656 - Filter images during upgrade if they are older by date or either CM or CDP is older than before

---

freeipa/src/main/resources/freeipa-salt/salt/nginx/conf/ssl-locations.d/saltapi.conf
freeipa/src/main/resources/freeipa-salt/salt/nginx/init.sls
orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl-locations.d/saltapi.conf
orchestrator-salt/src/main/resources/salt/salt/nginx/init.sls

This commit modifies nginx configuration to access salt-api via https
if the cert is present on the node.
The cert will be present only on instance which are from a new image
configured with SSL for salt-api

CB-8414 Enable SSL on Salt-API (rest_cherrypy)

---

orchestrator-salt/src/main/resources/salt/salt/sssd/template/add_dns_record.j2

In case there are 2 subnets, say 222.a.b and 2.a.b, then the script add_dns_record tries to add IP addresses to both DNS zones which is incorrect. However, because of another error in the script an error message was produced instead of silently adding the dns record to the wrong dns zone.

CB-8646 PTR record added to another zone

---

autoscale/src/main/resources/application-test.yml
autoscale/src/main/resources/application.yml
autoscale/src/test/java/com/sequenceiq/periscope/endpointtests/DistroXAutoScaleClusterV1EndpointTest.java

1. Alert Monitors are disabled in UnitTest Context where there isn't any external service connectivity.
2. Tests should assert response of the invoked api.

CB-8643 Stabilize DistroXAutoScaleClusterV1EndpointTest

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/AbstractMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/ClusterMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/RejectedThreadMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingHandler.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/AbstractMonitorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ScalingHandlerTest.java

AS Cluster's lastEvaluated and lastScalingActivity are updated at a very high rate for every alert monitor run. Saving the entire cluster object hierarchy in this flow is inefficient and unnecessary. Hence only the required single field is updated.

DISTX-504 Optimize DB Cluster Update

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProviderTest.java
template-manager-cmtemplate/src/test/resources/output/clouderamanager-fixparam.bp
template-manager-cmtemplate/src/test/resources/output/clouderamanager-nometastore.bp
template-manager-cmtemplate/src/test/resources/output/clouderamanager-variables.bp
template-manager-cmtemplate/src/test/resources/output/clouderamanager-without-hosts.bp
template-manager-cmtemplate/src/test/resources/output/clouderamanager.bp

When the cluster is Data Lake, still set the HBase root directory to use cloud storage if the cloud storage base is configured.
In "DISTX-303 DistroX Hbase Cloud Storage", it only sets HBase root directory for workload cluster. We need to extend cloud storage for HBase to the Data Lake cluster.

CB-8211: Set HBase root directory in Datalake as S3 path

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/freeipa/FreeIpaDeletionHandler.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/MockVerification.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentChildTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentStartStopTest.java
integration-test/src/main/java/com/sequenceiq/it/util/SimpleRetryUtil.java

- Add retry logic to MockVerification by introducing SimpleRetryUtil
- Fix FreeIpa stubbing in EnvironmentStartStopTest.testCreateStopStartEnvironment
- Refactor EnvironmentChildTest.testDeleteChildAndParentEnvironment for better readability
- Make FreeIpaDeletionHandler.detachChildEnvironmentFromFreeIpa idempotent
- Add clues from EnvironmentTestDto

CB-8644 Reduce flakiness of IT

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelper.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsModifyService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsStatusLookupService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/CustomAmazonWaiterProvider.java
cloud-aws/src/main/resources/templates/aws-cf-dbstack.ftl
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelperTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsModifyServiceTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsStatusLookupServiceTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsResourceConnectorTest.java

**Solution approach:**
When the RDS is created we should enable delete protection. This makes sure that customers don't accidentally delete the database. 
While terminating the database, we need to disable the delete protection if enabled, and then terminate the database.

CB-7938: Enable delete protection for RDS to avoid accidental deletions.

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceGroupMetadataProvider.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureSetup.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/ResourceGroupUsage.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageSetupService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceServiceTest.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/azure/ResourceGroupUsage.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/parameters/dao/domain/ResourceGroupUsagePattern.java
environment/src/main/java/com/sequenceiq/environment/parameters/validation/validators/parameter/AzureParameterValidator.java
environment/src/main/resources/schema/app/20200908071723_CB-8605_single_resource_group_with_storage.sql
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverterTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/validation/validators/AzureParameterValidatorTest.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/main/resources/application.yml

This change introduces a SINGLE_WITH_DEDICATED_STORAGE_ACCOUNT option for Azure resourceGroup request which calculates the storage account and resource group names for the VHD as it used to be in the legacy "MULTIPLE" RG use-case.
The intent is to use this internally (mow-dev) to save the time and cost of many image copies.
The feature is behind entitlement CDP_AZURE_SINGLE_RESOURCE_GROUP_DEDICATED_STORAGE_ACCOUNT and also CDP_AZURE_SINGLE_RESOURCE_GROUP entitlement has to be turned on, too.

CB-8605 - New SINGLE option to use Dedicated Storage Account

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/StackCreatorServiceTest.java

So far, the condition for the separation of the base and prewarmed images have been extended with a further check on the cloud platform. In case of yCloud base image should be selected.

CB-8691: It is not possible to launch an sdx on ycloud

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UmsUsersStateProvider.java

Internal machine users are needed in user sync. This commit adds
the includeInternal flag to the listMachineUsers calls.

CDPCP-2986. Include internal machine users in user sync

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/Cluster.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/IdBroker.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/IdBrokerConverterUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ClusterV4RequestToClusterConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/GrainPropertiesService.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/IdBrokerRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/idbroker/IdBrokerService.java
core/src/main/resources/defaults/blueprints/cdp-sdx-medium-ha-722.bp
core/src/main/resources/schema/app/20200906200353_CB-8663_add_new_IdBroker_table.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/cluster/ClusterRequestToClusterConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/ClusterV4RequestToClusterConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
datalake/src/main/resources/runtime/7.2.2/aws/medium_duty_ha.json
datalake/src/main/resources/runtime/7.2.2/azure/medium_duty_ha.json
datalake/src/main/resources/runtime/7.2.2/yarn/medium_duty_ha.json
orchestrator-salt/src/main/resources/salt/pillar/idbroker/init.sls
orchestrator-salt/src/main/resources/salt/pillar/idbroker/settings.sls
orchestrator-salt/src/main/resources/salt/pillar/top.sls
orchestrator-salt/src/main/resources/salt/salt/idbroker/init.sls
orchestrator-salt/src/main/resources/salt/salt/idbroker/settings.sls
orchestrator-salt/src/main/resources/salt/salt/top.sls
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java

This change add in a new table for IdBroker's certs that will be used to
sync IdBroker nodes together.  It includes it's own master secret and
changes to the Knox IdBroker config provider.  This also includes the
necessary salt changes to have these files set and generated for just
IdBroker nodes.
Testing Done:
Brought 2 IdBroker nodes up with no issue.  If settings are incorrect
they fail to start.  Had member of IdBroker team confirm configuration
looks good and nodes respond correctly.
Brought up 1 IdBroker with no issue.
Brought up 1 IdBroker node, then upgraded to this fix and resumed it
with no issue.

CB-8663 Deploy IdBroker across multiple nodes

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurevm/action/AzureClientActions.java

On azure there is an e2e test utility listing tags bz instance id. If, however, the instance id is null, an NPE is produced, marking a test as failed, masking the real reason for failure.

CB-8711 [e2e] azure fails with NPE (Create failed)

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/polling/clusterproxy/ServiceEndpointHealthListenerTask.java

Add FreeIPA instances' status details to log error messages as well as cloudera management console UI warnings when cluster proxy service errors out during FreeIPA provisioning. Currently, if FreeIPA creation fails, the error message ("Operation timed out. Failed to check cluster proxy endpoint health.") doesn't provide much information about the underlying instances from cloud provider. With this fix, the user will be able to see the actual status of failed instances.

CB-8393: FreeIPA should provide more detailed log messages for cluster proxy errors

---

core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/dns/AllHostPublicDnsEntryService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/dns/BaseDnsEntryService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/dns/KafkaBrokerPublicDnsEntryService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/dns/NifiHostPublicDnsEntryService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/publicendpoint/dns/AllHostPublicDnsEntryServiceTest.java

**Changes**
- New service that creatse public DNS entry for all nodes within DL and DH clusters
- Parking the Nifi and Kafka borker related DNS entry services due to the new logic, but leaving them reusable when the global public DNS entry feature will be configurable on hostgroup/role level

CB-8066 create public DNS entry for all nodes within DL and DH clusters

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/provision/handler/CreateExternalDatabaseHandler.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterDetailResponse.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterResponse.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxClusterConverter.java
redbeams/build.gradle
redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsApplication.java
redbeams/src/main/java/com/sequenceiq/redbeams/configuration/CloudbreakApiConfig.java
redbeams/src/main/java/com/sequenceiq/redbeams/configuration/SdxApiConfig.java
redbeams/src/main/java/com/sequenceiq/redbeams/configuration/ServiceEndpointConfig.java
redbeams/src/main/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverter.java
redbeams/src/main/resources/application.yml
redbeams/src/test/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverterTest.java

And do the same for SDX user tags (for future compatibility). For this SDX service's SdxClusterResponse had to be extended also
as it did not return the Tags property.
Redbeams spring config was incorrect regarding Cloudbreak endpoint configuration values.
Redbeams also had to be linked to SDX service.

CB-8641 Include DistroX user tags on DistroX RDS

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/PreconditionSdxE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsDistroXSpotInstanceTest.java

The `createDefaultImageCatalog(testContext);` required for the `AwsYcloudHybridCloudTest` setup. However the setup method does not contains this.
So the missing `createDefaultImageCatalog(testContext)` step has been introduced to the `AwsYcloudHybridCloudTest` setup.

CB-8754 Introduce the createDefaultImageCatalog setup step to the AwsYcloudHybridCloudTest

---

template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/kerberos/KerberosDetailService.java

1. Datalake does not come up without this because CM keytab will be missing while starting CM.
2. I am not sure about the TODO that says remove of FreeIPA registration being ready. It should be ready already, but just trying to keep the change minimal.

CB-3255 Add GCP support in KerberosDetailService

---

mock-thunderhead/src/main/resources/application.yml

Azure Single Resource Group feature is behind an Entitlement and up until
now it was disabled. In order to enable it we had to extend the feature with
an additional 'resourceGroupUsage' type to use dedicated Storage Accounts
for the images. Without this feature each and every person would copy our images
into their personal Storage Account that would generate a lot of cost for Cloudera.
Given the above we're granting this additional Entitlement locally so everyone
would use the same SA for the images as it would be a multi RG setup. This way
all of their resources will go to the selected RG except the images which will
be stored in a common SA generated per Azure subscription.

CB-8744 enable Azure Single Resource Group feature locally (UMS mock)

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java

With the single Resource Group feature we force the customers to select
and existing RG on the UI. However, if there is a ready-only lock on the
group then the provisioning will fail and it will capture the proper error
message returned by Azure. However, there is a finally block to always gather
the created resources based on the Deployment object, but the Deployment itself
could not be created. This change fixes this problem so we can return the proper
error message to the UI/CLI.

CB-8765 fix NPE when there is a read-only lock on the Resource Group

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/AbstractE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXImagesTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXScaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/ImageValidatorE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/PreconditionSdxE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsDistroXSpotInstanceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsSdxSpotInstanceTest.java

The createDefaultImageCatalog(testContext); required for the E2E tests' setup, because of 
```
if (!resources.containsKey(key) || resources.get(key) == null) {
throw new NoSuchElementException(
String.format("Key: '%s' has been provided but it has no result in the Test Context's Resources map", key));
}
```
However some of the setup methods do not contain this.
So the missing createDefaultImageCatalog(testContext) step has been introduced to these.

CB-8754 Introduce the createDefaultImageCatalog setup step to the E2E test

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceGroupMetadataProvider.java

On azure, when requesting multiple RG usage pattern, the usage pattern itself was not passed to cloud-azure. Upon retrieval, the value was thus null and an Enum.parse resulted in an NPE. Adding default value at the location of readout.

CB-8761 [e2e] image copy failed

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java

Older clusters might have CM licenses that is not valid to access
the paywall (archive.cloudeera.com/p/). During upgrade we're downloading
both CM server and CDP runtime from the paywall thus we need a valid
license for it. Even though upgrade involves updating the Salt states
and pillars there is an extra step when we only update the CM repo
details without the paywall credential being present. This PR changes
this behavior to always include the latest credentials from UMS. The CM
server doesn't store the license so we don't need to invoke any API to
update it in the server it will just use the one that is on the disk.

CB-8776 update the CM license as part of upgrading the CM server

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterNodeNameGenerator.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterNodeNameGeneratorTest.java

Node name generation logic enhanced so that all  hostgroup's nodes start with index 0.
Testing done.
- Tested launch of new cluster with 0 based node indexes for every hostgroup.
- Tested scale up and scale down of hostgroup nodes with hostGroup based node index.
- Tested deleted on provider node and new node added with same name on repair.
- Tested manually deleted nodes and successful scale up.
- Tested scale up\down on existing clusters with privateId based names.

CB-8739 Consistent Hostnames Enhancements

---

core/src/main/resources/defaults/blueprints/cdp-opdb-722.bp
core/src/main/resources/defaults/blueprints/cdp-opdb-723.bp

CB-8773 remove yarn_nodemanager_resource_memory_mb property from opdb templates because by OPSAPS-56088 CM now autogenerate several property

CB-8773 remove yarn_nodemanager_resource_memory_mb

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/CMLicenseUtil.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/JsonCMLicense.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/main/resources/application.yml
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/ProvisionerServiceTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java

For runtime upgrade, we have to download the CM and CDP builds from paywall
(archive.cloudera.com/p/). The CM license that is configured uniquely for each
CDP account can be used to authenticate. However, it can happen that customers
do not have an updated license that can be used. In this case, it would be a
mistake to even start the upgrade process. Instead, whenever an upgrade is
requested we'll validate if we can use the configured license to access the paywall.
If it's not valid we will reject the request. Once they update the license in UMS
we will also update the license as part of the upgrade process to make sure
we can download everything. We're also NOT checking the validity of the license
when we're searching for upgrade candidates. This is because this operation happens
very …

CB-8778 validate paywall access before starting the upgrade process

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-702.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-722.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-723.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-702.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-722.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-723.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-722.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-723.bp

1. The default data engineering clusters already have memory overcommit warnings.
2. We are trying to reduce memory allocation for every service so there is no overcommit.
3. The HDFS is running there just to support services like Hive and Oozie. The customer data goes only to Cloud storage.
4. So the default 1 GiB is sufficient. If some customer has a use-case of storing the data in HDFS then the CM health check warnings are there to alert them about the issue.
Tested by suppressing the warning and exporting the template from it.

ENGESC-3627 Suppress the CM warning about minimum heap size to be 4 GiB

---

orchestrator-salt/src/main/resources/salt/salt/ambari/scripts/ambari-server-init.sh

A new extra return character is required in STDIN with Ambari 2.7.5.10 setup to confirm
Encryption algorithm.

ENGESC-4173 Ambari setup failed with Ambari 2.7.5.10 repository

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeImageFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ImageCreationBasedFilter.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeImageFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ImageCreationBasedFilterTest.java

Until now every older image has been filtered out. This led to a
situation where older image with newer version was filtered.
With this commit creation date based filtering only happens when the
versions are matching.
Also done some refactoring:
- moving out creation date based filtering
- removed private field `reason`

CB-8798 Improve creation date based image filtering for upgrade

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitService.java

e2e tests could fail if thread sleep caught interrupted exception. now it is going to be ignored in waiterservice
closes: cb-8806

CB-8806 e2e tests could fail if thread sleep caught interrupted exception

---

datalake/src/main/java/com/sequenceiq/datalake/flow/repair/handler/SdxRepairWaitHandler.java

During E2E tests I have seen multiple times SDX service timeout while
the repair finished successfully. This commit will increase the wait
time from 40 mins to 60.

CB-8800 Increase wait time for repair on SDX service side

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UserModelDescriptions.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeAllUsersRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncRequestFilter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncRequestValidator.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersStateDifference.java
freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncRequestValidatorTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncServiceTest.java

This updates the existing synchronizeAllUsers request to
allow specifying a single workload user to be deleted
from the freeipa. Currently this won't remove CM ranger
cloud identities (azure object ids). That will come in
a following commit.

CDPCP-2998. Support deleted user as part of user sync

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java

With the single Resource Group feature we force the customers to select
and existing RG on the UI. However, if there is a ready-only lock on the
group then the provisioning will fail and it will capture the proper error
message returned by Azure. However, there is a finally block to always gather
the created resources based on the Deployment object, but the Deployment itself
could not be created. This change fixes this problem so we can return the proper
error message to the UI/CLI.

CB-8875 cherry pick Azure resource group related null checks

---

mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/test/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementServiceTest.java

Contents:
* Improve `MockUserManagementService.getAccount()`:
* Grant entitlement `CDP_CM_ADMIN_CREDENTIALS`
* Set `accountId` in response (as per request)
* Set `externalAccountId` in response
* Implement `MockUserManagementService.listTerms()` (empty dummy response only)
* Update existing unit tests & add some new cases

CB-8825 MockUMS fixes for thunderhead DatalakeApi service custom DL

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/RepairInstancesService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/RepairInstancesServiceTest.java

Fix a null pointer exception that would be thrown when repairing
FreeIPA without specifying which instances to repair. This is
supposed to automatically detect which instance to repair.
This was texted manually using a local deployment of cloudbreak.

CB-8910: Fix null pointer exception when repairing FreeIPA

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/action/AbstractDownscaleAction.java

In AWS if a FreeIPA instance was deleted on the cloud provider side,
the repair operation would not properly clean up the instances. For
example, associated cloud watches were not cleaned up. Additionally, it
caused problems during the upscale since the instance group still
contained the terminated instance and so the upscale would wait until
the operation timed out.
Repair of a deleted instance was validated on AWS using a local
deployment of cloudbreak.

CB-8909: Fix FreeIPA repair of deleted instances

---

freeipa/src/main/resources/freeipa-salt/pillar/freeipa/services.sls

Add polkit service systemd salt sls restart setting in FreeIPA instances. Polkit is a component for controlling system-wide privileges in Unix-like operating systems. Currently, polkit service won't restart after it fails. With this fix, polkit service will restart after a three-second delay. This is in consistent with all other services running in FreeIpa instances.

CB-8937: FreeIPA doesn't automatically restart polkit

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls

When creating cloudera manager intermediate CA, it has a default
profile present. This has invalid settings for OCSP and CRL. In this
commit we are replacing those values with the right ones.

CB-8714 Fix OCSP and CRL URL for CM CA

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsAutoScalingService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsAutoScalingServiceTest.java

In case InsufficientInstanceCapacity is returned on an ASG request
either on launch or upscale, we need to keep waiting for the instances
to be provisioned by AWS as this failure seems recoverable, i.e. in a few
minutes AWS will likely launch the requested number of instances in the ASG.

CB-8924 AWS InsufficientInstanceCapacity fix on ASG

---

integration-test/integcb/Profile_template
integration-test/it-application.yml
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/CloudbreakTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/config/server/CloudbreakServer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MockedTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/ImageCatalogMockServerSetup.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ImageCatalogBasicTest.java
integration-test/src/main/resources/application.yml
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/controller/MockImageCatalogController.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/service/ImageCatalogMockService.java
mock-thunderhead/src/main/resources/mock-image-catalogs/catalog-with-for-upgrade.json
mock-thunderhead/src/main/resources/mock-image-catalogs/catalog-with-prewarmed.json
mock-thunderhead/src/main/resources/mock-image-catalogs/cb-catalog.json
mock-thunderhead/src/main/resources/mock-image-catalogs/freeipa-catalog.json

Moved all image catalog to mock-service so it won't take up additional spark threads.
Sadly I was not able to measure any significant reduction in execution time since there is great variance in the tests.

CB-8895 added dynamic image catalog responder for cb mock service

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/action/FreeIpaDownscaleActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/action/TerminationService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ClusterProxyService.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/termination/action/TerminationServiceTest.java

Fix FreeIPA repair so that if there is an instance stuck in the
requsted state, the repair operation is able to succeed and it clean
up as much as possible.
This was tested manully using a local instance of cloudbreak.

CB-8901: Fix FreeIPA repair with a requested instance

---

auth-internal/src/main/java/com/sequenceiq/cloudbreak/auth/security/internal/InternalCrnModifier.java
auth-internal/src/test/java/com/sequenceiq/cloudbreak/auth/security/internal/InternalCrnModifierTest.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/ReflectionUtil.java
common/src/test/java/com/sequenceiq/cloudbreak/auth/ReflectionUtilTest.java

If there is an API method which can be called with internal actor and @AccountId/@TenantAwareParam/@InitiatorUserCrn param is null, then the framework will throw an ugly NPE.
If this is occuring in PROD, the workaround is to fill in the parameter, so I opened this PR for 2.31, not for 2.29.

CB-8703 fix authz framework to handle null queryparam

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerUserSyncRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerUserSyncRoleConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java

This adds a call to get Service Principals from Thunderhead during template
preparation that will be passed into the RangerUserSyncRoleConfigProvider
to sync OID before the datalake starts up.

CB-7419 adding in Service Principals to Ranger User Sync

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementServiceTest.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/main/resources/application.yml
mock-thunderhead/src/test/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementServiceTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProviderTest.java

We should put the code change to remove HDFS from Data Lake behind entitlement. So customer can enable this feature for new SDX cluster, and existing SDX cluster upgrade does not hit this feature by accident.
The flag is committed in thunderhead at https://github.infra.cloudera.com/thunderhead/thunderhead/commit/aefabb467c204d196a3a421aa015e8895800137d#diff-78fd6bd58147c45d045cc080c7400665

CB-9055: Put NO HDFS feature under entitlement

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/FlowUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitService.java
integration-test/src/main/java/com/sequenceiq/it/util/SimpleRetryWrapper.java
integration-test/src/main/java/com/sequenceiq/it/util/cleanup/CleanupWaitUtil.java

Change the `InterruptedException` handling at the Test project. Introduced log `WARNING` instead of `throw new TestFailException` and log `ERROR`.

CB-9091 Waiting for Flow throws java.lang.InterruptedException

---

flow/src/main/java/com/sequenceiq/cloudbreak/service/ha/HeartbeatService.java
flow/src/main/java/com/sequenceiq/flow/cleanup/InMemoryCleanup.java
flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java
flow/src/test/java/com/sequenceiq/cloudbreak/service/HeartbeatServiceTest.java
flow/src/test/java/com/sequenceiq/flow/cleanup/InMemoryCleanupTest.java
flow/src/test/java/com/sequenceiq/flow/core/Flow2HandlerTest.java

The issue was caused when a failed node resumes operation but in the
meantime another node picked up the same flow.
The fix is that the resumed node does not continue progressing the
flow if the last operation is performed by another node, rather
removing the paticular flow from the inmemory store and skipping
flow continuation.

CB-9044 Flow handling race condition fix on flow redistribution

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatahubConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatahubConfigProviderTest.java

- This PR is intended to handle null pointers that corrupted cluster template generation before cluster creation. As the `ProductDetailsView` is null in case of cluster template generation.
- Also that has been validated that the `7.2.2 - Flow Management Light Duty with Apache NiFi, Apache NiFi Registry` template works at is expected and datahub clusters could be created with it.

CB-9074 handle null values of ProductDetailsView in RangerRazDatahubConfigProvider that corrupted cluster template generation

---

environment/src/main/java/com/sequenceiq/environment/network/EnvironmentNetworkService.java
environment/src/main/java/com/sequenceiq/environment/parameters/dao/domain/ResourceGroupUsagePattern.java
environment/src/test/java/com/sequenceiq/environment/network/EnvironmentNetworkServiceTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/dao/domain/ResourceGroupUsagePatternTest.java

On azure, when using single RG, then deleting the new network during environment deletion should delete the VNET resource but must not delete any resource groups (RG). With the recent introduction of resource group usage pattern USE_SINGLE_WITH_DEDICATED_STORAGE_ACCOUNT the check whether using a single RG or not was broken and was assumed that it is MULTIPLE, hence the single RG was deleted.

CB-9130 Single RG is deleted when using new network

---

orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/BootstrapParams.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/domain/Minion.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrap.java

We found an issue in e2e tests, master repair failed sometimes on azure. I was able to reproduce it, Mihaly Laszlo Molnar  and Krisztian Horvath helped me to figure out what could happen. It occurs if the master node has the same private IP address after repair as the original.
Discovered things:
salt-minion does not print anything into the log if you stop the master node, just hangs
salt-minion does not print anything into the log if you remove it's key from salt-master
salt-minion has some cache in it for master, maybe half an hour or an hour, something like this
It appears on azure because azure usually sets the same IP address for the new node as for the previous because it allocates addresses incrementally and it reuses the IP addresses.
Most of the times the e2e test is successful …

CB-9064 restart minions if master repair is happening

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterStatusService.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/status/ExtendedHostStatuses.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusServiceTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/CertExpirationState.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/cluster/ClusterV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/converter/CertExpirationStateConverter.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/Cluster.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ClusterToClusterV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/cluster/ClusterRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/resources/schema/app/20201002104732_CB-9060_alter_cluster_add_CertExpirationState.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/cluster/ClusterToClusterV4ResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJobTest.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusIntegrationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java

We are setting up clusters with autotls, which means every host has it's own certificate.
These certificates expiry every year and we must detect it and notify the customer before expiration date.
In this commit `StackStatusCheckerJob` has been enriched with checking the result from Cloudera Manager for
host certificate expiration related health info. Although these are not stored per host, they are aggregated
and if there is at least one which is expiring we are setting a new field in `Cluster` entity, `certExpirationState`
from `VALID` to `HOST_CERT_EXPIRING`.
This field is an enum to allow further expansion if we later would like to indicate eg CMCA expiration.
The value of this field is available on DistroX API in `ClusterV4Response` and on SDX API in `SdxClusterDetailResponse`.

CB-9060 Check if certificates on cluster are about to expire

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDtoBase.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java

E2E test uses the internal API to post the datalake request.
In this case, the cluster ogging feature needs to be enabled
in the request.

CB-8541 Cluster logs in AWS YCloud hybrid e2e test

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UtilV4Controller.java

UI sends in the request without workspace id, but the translation only happens via a Filter which can't be invoked in this case.
Verified locally with curl call to that endpoint.

CB-9162 we are using the workspace 0 from application code

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/service/AltusIAMService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDatabusService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDatabusServiceTest.java

- CB-8313 There is a 3rd machine user creation on our flow for CM legacy collection which was using the grpcUmsClient directly and I missed that the first and second time also

CB-8313 There is a 3rd machine user creation in our flow

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/doc/DistroXOpDescription.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/util/RenewDatalakeCertificateAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/util/RenewDistroXCertificateAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/DistroXTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/util/RenewDatalakeCertificateTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/util/RenewDistroXCertificateTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CreateDhWithDatahubCreator.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DatalakeDatahubCreateAuthTest.java

Anybody in the tenant is able to do a renew certificate process on any stack. With this change only the users with REPAIR_DATALAKE on the specific datalake or REPAIR_DATAHUB on the specific datahub are able to do cert renewal.

CB-9103 move renew certificate endpoint to datalake and distrox endpoint

---

cloud-azure/build.gradle
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorage.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageSetupService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureManagedImageService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/util/CustomVMImageNameProvider.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureManagedImageServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/util/CustomVMImageNameProviderTest.java

Some azure calls were outside of AzureClient class, and some tests were added.

CB-9110 Persist managed image status -- follow up refactorings

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/NetworkService.java
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_install.sh

1. We accept the subnet name from the user for GCP.
2. When we fetch the subnet information back from GCP, it gives the internal subnet id.
3. So make the subnet filtering logic in NetworkService similar to CloudNetworkService https://github.com/hortonworks/cloudbreak/blob/master/environment/src/main/java/com/sequenceiq/environment/network/CloudNetworkService.java#L130
4. We saw that the jinja2 template picked the next argument as the reverse zone value if the zones is an empty list, fixed that part also.
Tested in private stack
```
$ ipa dnszone-find
Zone name: 114.10.in-addr.arpa.
Active zone: TRUE
Authoritative nameserver: ipaserver0.demo5.r6zv-kv2u.dev.cldr.work.
Administrator e-mail address: hostmaster.demo5.r6zv-kv2u.dev.cldr.work.
SOA serial: 1602118320
SOA refresh: 3600
SOA retry: …
```

CB-9180 Freeipa install in GCP does not populate reverse DNS entries

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradeService.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java

We have limited the Runtime upgrade that it's only possible from version 7.1.0.
However, since we have the upgrade matrix in place we don't need this extra
check. Besides if we would allow 7.0.2 upgrade in the matrix this extra
check would still stop the process.

CB-8228 remove the base 7.1.0 version check for Runtime upgrade

---

freeipa/src/main/java/com/sequenceiq/freeipa/kerberos/KerberosConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberos/KerberosConfigService.java
freeipa/src/main/java/com/sequenceiq/freeipa/kerberos/v1/KerberosConfigV1Service.java
freeipa/src/main/java/com/sequenceiq/freeipa/ldap/LdapConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/ldap/LdapConfigService.java
freeipa/src/main/java/com/sequenceiq/freeipa/ldap/v1/LdapConfigV1Service.java

The issue is caused by a race condition while we are creating kerberos
configuration for a cluster. The process looks like the following if
the kerberos configuration doesn't exists:
1. Requests arrives
2. We check the DB for existing configuration (in this case this returns it's missing)
3. Check FreeIPA if the desired bind user exists
4. Create the bind user
5. Set the bind user password
6. Create configuration in the database
7. Return the kerberos configuration response
The main issue is step 3->5 can take up a few seconds. If there are 2
requests coming in, let's say about 2 sec difference, the first can be
in the phase to set the password, when the second will still not find
any kerberos config in the database and tries to create a new one. In
this case the first one will finish, …

CB-9251 Fix Kerberos-/LdapConfig creation race condition

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/search/CustomJUnitXMLReporter.java

Unfortunately not all the API E2E JUnit XML reports are included for Quanta uploads, because of reports with same name are going to be overwritten. So we should introduce an additional tag for XML file generation. On this way all the XML files will be present for Quanta uploads.

CB-9249 API E2E JUnit XML report names should contain the Cloud Provider as well

---

auth-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/usermanagement/UserManagementGrpc.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
auth-connector/src/main/proto/usermanagement.proto
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/ums/DefaultUmsUsersStateProvider.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/ums/DefaultUmsUsersStateProviderTest.java

This changes the flag we use when retrieving machine users. Rather than retrieving all internal machine users, most of which are not workload identities, we've added another flag to the usermanagement.proto to indicate that we want all the workload machine users.
This change is needed because we've discovered that we have an unknown and likely large number of orphaned internal machine users. Processing all internal machine users negatively impacts user sync performance. E.g., in mow-dev, we move from syncing 2500 actors to 8000+ actors.

CDPCP-3121 - Filter internal machine users for user sync

---

core/src/main/resources/defaults/blueprints/cdp-data-engineering-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-722.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-723.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-722.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-ha-723.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-710.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-720.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-721.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-722.bp
core/src/main/resources/defaults/blueprints/cdp-data-engineering-spark3-723.bp

DISTX-534 As per TSB-437, FileOutputCommitter algorithm v2 may result into
bad output data. Hence it has been advised to go back to v1 version.
This commit makes following config changes in 710, 720, 721, 722, 723
DE, DE HA & Spark3 templates so that v1 algorithm is configured ootb
in DH clusters :
fs.s3a.committer.name=directory
mapreduce.fileoutputcommitter.algorithm.version=1
spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version=1
Testing done :
Have created a DE cluster using a modified 7.2.2 template that includes above mentioned config changes. Cluster creation was successful on AWS using m5d.2xl instance types.

DISTX-534 use v1 committer for spark

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/repair.sh

The FreeIPA HA repair runbook has a rather large script that is
manually copied/pasted during a repair. This repair script is being
added to the FreeIPA instances so that it makes the repair runbook
simpler. The repair runbook is for repairing all instances from a
backup.

CB-9299: Add FreeIPA HA repair script from runbook to FreeIPA instance

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/service/AltusIAMService.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/cleanup/UMSCleanupConfig.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/cleanup/job/UMSCleanupJob.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/cleanup/service/UMSCleanupJobService.java
core/src/main/java/com/sequenceiq/cloudbreak/job/altus/CloudbreakUMSCleanupJob.java
core/src/main/java/com/sequenceiq/cloudbreak/job/altus/CloudbreakUMSCleanupJobInitializer.java
core/src/main/java/com/sequenceiq/cloudbreak/job/altus/CloudbreakUMSCleanupJobService.java
core/src/main/java/com/sequenceiq/cloudbreak/job/altus/DatahubMachineUsers.java
core/src/main/java/com/sequenceiq/cloudbreak/service/altus/AltusMachineUserService.java
core/src/test/java/com/sequenceiq/cloudbreak/job/altus/CloudbreakUMSCleanupJobTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/altus/FreeIpaUMSCleanupJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/altus/FreeIpaUMSCleanupJobInitializer.java
freeipa/src/main/java/com/sequenceiq/freeipa/altus/FreeIpaUMSCleanupJobService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/AltusMachineUserService.java
freeipa/src/test/java/com/sequenceiq/freeipa/altus/FreeIpaUMSCleanupJobTest.java

details:
We should clean up generated machine users if those were not delete during cluster destroy (no significant increase with those users, but it's useful if we will have some cleanup scripts)
that should be done for 2 components:
- freeipa service
- cloudbreak (core) service (against datalake/datahub)
machine users:
- 1 fluent user for freeipa (if cluster logs collection enabled)
- 1 fluent user for datalake (if cluster logs collection enabled)
- 1 fluent user for datahub (if cluster logs collection or metering enabled) and 1 TP user if WA enabled
(overall freeipa/datalake: max. 1-1, datahub: max 2.)
(all users have specific patterns)
-> Using quartz job scheduler to do the cleanup on every sSunday (0:00) clean users that has no attached clusters + user creation date is older than 3 …

CB-9136. Create scheduled job for machine user cleanup for FreeIPA/DL+DH

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/search/CustomJUnitXMLReporter.java

Test failures have been shown `Unknown` as Exception and Error at latest Quanta report. So I've changed the test result attribute setup at TestContext and refactored the set test name at CustomXMLReporter.

CB-9249 Stabilise JUnit XML report generation in case test failure

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterSecurityService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityServiceTest.java
common/src/main/resources/messages/messages.properties
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/FlowChainTriggers.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/RotateClusterCertificatesFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/certrotate/ClusterCertificatesRotationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/certrotate/ClusterHostCertificatesRotationHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/ssh/SshKeyService.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/OrchestratorStateParams.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/OrchestratorStateRetryParams.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/runner/SaltRunner.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/restart.sls
orchestrator-salt/src/main/resources/salt/salt/ssh/add_ssh_publickey.sls
orchestrator-salt/src/main/resources/salt/salt/ssh/remove_ssh_publickey.sls
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java

CB-9086 Enable host cert rotation on older runtimes
On clusters with older than 7.2.1 version for CM host certificates rotation root ssh access is needed.
The following changes are introduced  for this:
- Extend HostOrchestrator / SaltOrchestrator with new method for execute specific saltstates
- Introducing new salt states for ssh key adding / removal for given users on hosts
- Extend host certs rotation with adding temporary ssh access for root user during host cert rotation api call. This is only needed on clusters with older than 7.2.1 version.
CB-9297 add 755 permission for CM agent cert directory after host certs rotation on all hosts. This is needed to workaround OPSAPS-58475.

CB-9086 Enable host cert rotation on older runtimes

---

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentRequest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/DetailedEnvironmentResponse.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentBaseResponse.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/SimpleEnvironmentResponse.java
environment/src/main/java/com/sequenceiq/environment/environment/domain/Environment.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDto.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverter.java
environment/src/main/resources/schema/app/20201009154412_CB-8209_Adding_cloudbreak_version_to_environment_info.sql

The main reason for this change is to be able to retrieve the exact Cloudbreak version used during the creation of the environment, as this will help with QE purposes.
Let me know if I did all of this right, but essentially I tried to:
- Add a new column to the environment database table for the cloudbreak version
- Update the existing table to include that column
- Set the cloudbreak version when the environment is first created using the info.app.version value
- Have the cloudbreak version present in the DetailedEnvironmentResponse and the EnvironmentDto classes so that it is obtained with any describe environment calls

CB-8209: Adding the Cloudbreak version to the environment API.

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/init.sls

Install FreeIPA repair script to /opt/salt/scripts/repair.sh.
I chose to not include it in the base AMI image since this script depends on logic from the FMS codebase since it cleans up configuration that was initialized by the FMS. So it will change from time to time.

CB-9299: Install FreeIPA repair script to /opt/salt/scripts/repair.sh

---

autoscale/src/main/java/com/sequenceiq/periscope/config/DatabaseConfig.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterProxyRegistrationServiceConfig.java
common/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/DatabaseConfig.java
environment/src/main/java/com/sequenceiq/environment/configuration/DatabaseConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/configuration/DatabaseConfig.java
gradle.properties
redbeams/src/main/java/com/sequenceiq/redbeams/configuration/DatabaseConfig.java

Additionally added traceWithActiveSpanOnly=true parameter to jdbc configurations so jaeger is spammed with lonely database query spans.
Most part of cluster proxy tracing related code will go to the cluster proxy service itself.

CB-9293 - added tracing to cluster proxy from client side.

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverterTest.java

Removed the condition that – seemingly – has no additional value to the conversion but it prevents one from describing a cluster definition that is connected to a stopped environment.

CB-9227 - unable to get cluster definition on a stopped environment

---

core/src/main/resources/defaults/blueprints/7.2.2/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.3/cdp-sdx-medium-ha.bp

This sets Atlas's Solr configuration to use 2 shards and 2 replications.

CB-9300 Add support for solr collections with HA

---

core/src/main/resources/defaults/blueprints/7.2.2/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.3/cdp-sdx-medium-ha.bp
datalake/src/main/resources/duties/7.2.2/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.2/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.2/yarn/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.3/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.3/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.3/yarn/medium_duty_ha.json

This adds 2 gateway nodes and a small alpha node.  The alpha node currently
contains Atlas due to OPSAPS-57449 and will be put on the gateway node later.

CB-8960 Adding multiple gateway nodes and mini node for DL HA

---

common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/AbstractMetricService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/CheckImageAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/metrics/CloudbreakMetricService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateActionsTest.java

Prometheus was not presenting correctly the values from LongTaskTimer
type metric. CHanged the image copy metric to type Timer and now
Prometheus shows copy times correctly.

CB-9188 Change image copy metric from long task timer to timer

---

freeipa/src/main/resources/freeipa-salt/salt/logrotate/conf/krb5kdc
freeipa/src/main/resources/freeipa-salt/salt/logrotate/init.sls
freeipa/src/main/resources/freeipa-salt/salt/top.sls

By default krb5kdc log was rotated monthly. From now a 1GB limit is introduced.
After a month or 1GB in size the log will be rotated and compressed.
Max 12 files will be kept.

CB-9379 Rotate krb5kdc log by size

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ProperTerminationFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/TerminationFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/DatabaseObtainerService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/terminate/handler/TerminateExternalDatabaseHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsClientService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/DatabaseObtainerServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/terminate/handler/TerminateExternalDatabaseHandlerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsClientServiceTest.java

Move external database termination before the stack termination
flow. Previously the stack deletion completed state set another
flags (e.g. termination date) in the 'stack' entity which was not
optimal for several reasons.
During the change I found issues with Redbeams calls checking for
NotFound result. As it turned out, this exception is wrapped into
a custom one and that case needs to be handled as well.
Wrote unit tests around them.

CB-9290 Stack terminate flow chain reorder

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/CustomAmazonWaiterProvider.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/acceptor/DescribeDbInstanceForModifyFailureAcceptor.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/acceptor/DescribeDbInstanceForModifySuccessAcceptor.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/acceptor/DBInstanceStatuses.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/acceptor/DescribeDbInstanceForModifyFailureAcceptorTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/acceptor/DescribeDbInstanceForModifySuccessAcceptorTest.java

Redbeams was waiting forever on setting the termination protection
flag to 'false' in the case of stopped instances because the waiter
condition was not complete.

CB-9307 Stopped RDS is not deleted but hanging forever to timeout

---

flow/src/main/java/com/sequenceiq/flow/repository/FlowChainLogRepository.java

We can create FlowChains which are parent of other FlowChains. The
current logic checked only FlowLogs which resulted in deleting these
parent FlowChains. The SQL query has been extended with a condition to
check if a FlowChain has child FlowChain.

CB-9397 Don't purge `FlowChainLog` which has a child `FlowChain`

---

common/src/main/java/com/sequenceiq/cloudbreak/client/RestClientUtil.java
freeipa-client/build.gradle
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaHealthCheckClient.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaHealthCheckRpcListener.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/healthcheckmodel/CheckEntry.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/healthcheckmodel/CheckResult.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/healthcheckmodel/ClusterCheckResult.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/healthcheckmodel/PluginStatusEntry.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaHealthCheckClientFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaHealthCheckClusterProxyErrorRpcListener.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthDetailsService.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaChecker.java
freeipa/src/main/resources/application.yml
freeipa/src/test/java/com/sequenceiq/freeipa/client/FreeIpaHealthCheckClusterProxyErrorRpcListenerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/sync/StackStatusTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/ITResponse.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/freeipa/healthcheck/FreeIpaNodeHealthCheckHandler.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentStartStopTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/FreeIpaStartStopTest.java
mock-thunderhead/src/main/resources/application.yml

Use the new FreeIPA health checks for the instance status. This is
used for the periodic polling of the status, the on demand status for
the health API, and for the internal repair status.
Unit tests were added and this was tested manually using a local
deployment of cloudbreak.

CB-8664: Use new FreeIPA health checks for instance status

---

common/src/main/resources/messages/messages.properties
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/StackUpdaterService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/cloud/CloudConfigValidationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/cloud/config/CloudConfigValidationFlowConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCreationSetupService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/StackCreatorServiceTest.java

Changes:
- Fix the behaviour that sent a failure and successful event a the same time from `VALIDATE_CLOUD_CONFIG_STATE`
- Fix the payload of the `VALIDATE_CLOUD_CONFIG_FAILED_EVENT` that's sent from `VALIDATE_CLOUD_CONFIG_STATE`
- Clusters that's created on old `v4/../stack` APIs be marked with `LEGACY` stack type, this will result in cases where cluster "legacy" clusters could not be found on the UI as these kind of clusters won't be presented in DistroX related API calls

Cluster validation flow fix

---

freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java
freeipa/src/main/java/com/sequenceiq/freeipa/util/CookieComparator.java
freeipa/src/main/java/com/sequenceiq/freeipa/util/FreeIpaCookieStore.java
freeipa/src/test/java/com/sequenceiq/freeipa/util/CookieComparatorTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/util/FreeIpaCookieStoreTest.java

When there are multiple FreeIPA ipa_session cookies, use the last one.
This is the same behavior as FreeIPA does.
See https://github.com/freeipa/freeipa/blob/139d60d74706d2ba9855db5faefee322b23b0ba5/ipapython/cookie.py#L322-L349
for details.

CB-9374: Use last FreeIPA cookie when there are multiple

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/AbstractImageValidatorE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/BaseImageValidatorE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/PrewarmImageValidatorE2ETest.java
integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/aws-image-validation-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-image-validation-tests.yaml
integration-test/src/main/resources/testsuites/e2e/base-image-validation-tests.yaml
integration-test/src/main/resources/testsuites/e2e/prewarm-image-validation-tests.yaml
integration-test/src/main/resources/testsuites/e2e/yarn-e2e-tests.yaml

Test case for base image validation: creates an sdx cluster by using the default base image. Test is going to fail in case of any issue with the cluster creation and in case of the expected image id is not the actually used one.

CB-9037 Test case for base image validation

---

core/src/main/resources/defaults/blueprints/7.2.2/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.3/cdp-sdx-medium-ha.bp
datalake/src/main/resources/duties/7.2.2/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.2/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.2/yarn/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.3/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.3/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.3/yarn/medium_duty_ha.json

This reverts commit 22c20a6f8b9a050e7115e4d827a2bea4dedab1da.
Since we cannot deploy a intermediatary shape, we're rolling this back
and plan to use the final shape later in 7.2.4

Cb 9450 Revert back to 2 master, 1 gateway and 2 idbroker.

---

core-model/build.gradle
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/RDSConfig.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/RdsSslMode.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/converter/RdsSslModeConverter.java
core-model/src/test/java/com/sequenceiq/cloudbreak/domain/RdsSslModeTest.java
core-model/src/test/java/com/sequenceiq/cloudbreak/domain/converter/RdsSslModeConverterTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbServerConfigurer.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/RdsConfigToRdsDetailsConverter.java
core/src/main/resources/schema/app/20201020160302_CB-8789_Configure_DB_TLS_for_DL_cluster_services_and_DH_HMS.sql
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbServerConfigurerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/converter/RdsConfigToRdsDetailsConverterTest.java
gradle.properties
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/RdsDetails.java
template-manager-cmtemplate/build.gradle
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ConfigUtils.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/RdsView.java
template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/views/RdsViewTest.java

* Persist DB SSL status in `RDSConfig`
* Currently populated for external DBs only
* Return DB SSL status in `RDSDetails`
* Additions to `RdsView`:
* DB SSL status
* SSL certificate file path; empty when not using SSL
* `ConnectionURL` extended wit SSL options as necessary
* Add new compile dependency to `template-manager-cmtemplate/build.gradle`: `org.apache.commons:commons-text:1.5`
* Inject DB SSL configs for HMS and Ranger Admin
* Honor custom HMS DB settings in cluster template
* Add new unit tests and migrate existing ones to JUnit 5 & AssertJ

CB-8789 Configure DB TLS for DL cluster services & DH HMS

---

secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/SecretEngine.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/service/SecretService.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/service/VaultRetryService.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/vault/VaultKvV1Engine.java
secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/vault/VaultKvV2Engine.java
secret-engine/src/test/java/com/sequenceiq/cloudbreak/service/secret/service/SecretServiceTest.java
secret-engine/src/test/java/com/sequenceiq/cloudbreak/service/secret/vault/VaultKvV1EngineTest.java
secret-engine/src/test/java/com/sequenceiq/cloudbreak/service/secret/vault/VaultKvV2EngineTest.java

Using this optional construct to avoid tracing of lonely vault spans.
Not adding the usual tags from the MDC Context because it would be very very redundant and consume lot of memory unnecessarily.

CB-9313 - added Vault client side tracing

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/generic/DynamicModel.java

CB-9474 - cli throws unrecognised field exception for env cli command generation for response in CloudSubnet, because of the missing jackson property from the DynamicModel that has been added in this commit

CB-9474 - cli throws unrecognised field exception for env cli command generation for response in CloudSubnet

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/cloudbreak/CloudbreakTerminationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/datalake/DatalakeTerminationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/environment/EnvironmentTerminationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaTerminationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceTerminationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/redbeams/RedbeamsTerminationChecker.java

Changes:
- enforce delete yarn environment from test to be able to identify yarn environment deletion issues
- enforce TestFailException in case of DELETE_FAILED status during resource terminations

Resource deletion should break test case when a resource reaches the 'DELETE_FAILED' state

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/certrotate/ClusterCertificatesRotationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/cert/CertRotationService.java

When the cert rotation flow is started the cert expiration state will
be set to `VALID`, so on the UI the button and notification will
disappear.
In case the flow fails, the syncer will set it it to expiring again.

CB-9476 Clear the cert status when the renewal process is started

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/database/DatabaseServiceTest.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/main/resources/application.yml
mock-thunderhead/src/test/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementServiceTest.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/AllocateDatabaseServerV4Request.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/SslConfigV4Request.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/SslMode.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/responses/SslConfigV4Response.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ModelDescriptions.java
redbeams-api/src/test/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/SslModeTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverter.java
redbeams/src/test/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverterTest.java

* Apply DL external DB SSL enforcement only if entitlement `CDP_CB_DATABASE_WIRE_ENCRYPTION` has been granted.
* The presence of `CDP_CB_DATABASE_WIRE_ENCRYPTION` in `MockUserManagementService.getAccount()` is conditional, depending on the app system property `auth.mock.database.wire.encryption.enable` .
* Minor Redbeams SSL API cleanup: `SslConfigurationV4Request` renamed to `SslConfigV4Request`, `AllocateDatabaseServerV4Request.sslConfiguration` renamed to `sslConfig`, correct field / type descriptions.
* Add & enhance unit tests.

CB-9434 CB-9437 Entitlement check for DB TLS

---

cloud-aws/src/main/resources/templates/aws-cf-dbstack.ftl

CB-9362 on aws rds postgres version is 10.14 instead of 10.6

CB-9362 on aws rds postgres version is 10.14 instead of 10.6

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/DistroxService.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/DistroxServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterCreationTest.java

CB-9228 – unable to create a cluster definition for a stopped environment, since one of the DH creation validation has been placed to an inappropriate place which will be moved to the service layer, allowing one to create c.def for an existing but not necessarily available environment

CB-9228 – unable to create a cluster definition for a stopped environment

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java

CB-9506 - YCloud hybrid env test failure on teardown, so tearDown method has been removed from the test class since it has a duplicated functionality that breaks the test

CB-9506 - YCloud hybrid env test failure on teardown

---

orchestrator-salt/src/main/resources/salt/pillar/postgresql/disaster_recovery.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/backup.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/restore.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Check if a root cert exists on the instance.
* Run backup/restore with ssl-full, using the root cert if it's there.
* Fallback to default behavior if the root cert is not present.
Tested by `rsync`ing salt scripts on to a datalake master node and manually running salt backup and restore commands.
* `rsync` salt scripts
* `rsync` rds root certs to `/hadoopfs/fs1/database-cacerts/certs.pem`
* update pillar values with `ranger_admin_group` and `backup_location`
* run backup and restore:
```sh
salt $(hostname -f) state.apply postgresql.disaster_recovery.backup
salt $(hostname -f) state.apply postgresql.disaster_recovery.restore
```
Tested backup and restore when:
* Root cert present
* Root cert not present
And when `force_ssl` rds option is `0` and `1` in AWS.

CB-9154: Add ssl root cert and ssl mode to backup and restore PGSQL settings.

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterDetailResponse.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterResponse.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxClusterConverter.java
datalake/src/main/java/com/sequenceiq/datalake/entity/SdxCluster.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/main/resources/schema/app/20201019203538_CB-9224_Adding_cloudbreak_version_to_datalake_DB.sql

Jira is here: https://jira.cloudera.com/browse/CB-9224
This PR is meant to enable the following:
* Cloudbreak version used to create a datalake is saved into the datalakedb in the new column specifically for it
* The same Cloudbreak version (from the creation of the datalake) is retrieved from the datalakedb every time the datalake is "described" (i.e. is a part of the SdxClusterResponse object and is populated from the database when this is called).

CB-9224: Added cloudbreak version used to create datalake to datalake API.

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpProvisionSetup.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java

1. Google for their default centos 7 deprecated SECURE_BOOT guest os feature and started using UEFI_COMPATIBLE flag https://github.com/hashicorp/packer/issues/9353#issuecomment-640484734
2. When we import such images without this flag, then instances could not be created from that
3. Tested by importing this flag with gcloud apis and made sure that the instance booted properly.

CB-9452 Fix image import/export issue for Google cloud

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/instance/InstanceStatus.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaChecker.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/ProviderChecker.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/SyncResult.java

Integrated freeipa health check and platform instance check results to show actual instance statuses on UI. Currently instance status is incorrect on UI when the instances are unreachable because only platform instance check is used. The platform instance check doesn't check if the instance is reachable. If instances are not available, the UI will show incorrect running status. With this fix, the UI will show the instance as unreachable.

CB-9298: Instance status is incorrect on UI

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/instance/AwsInstanceTemplate.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsGroupView.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsInstanceView.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsInstanceViewTest.java
common-model/src/main/java/com/sequenceiq/common/api/placement/AwsPlacementGroupStrategy.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/AwsInstanceTemplateV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/AwsPlacementGroupV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/instancegroup/template/AwsInstanceTemplateV1Parameters.java
core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/instancegroup/template/AwsPlacementGroupV1Parameters.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverter.java

Placement Group Configuration support for AWS Clusters via Cluster Definitions. The PlacementGroup configuration for AWS is done similar to existing AvailabilitySet Configuration for Azure Clusters.
1. Tested multiple DH Cluster launches with PG strategy as NONE, SPREAD, CLUSTER, PARTITION.
2. Tested multiple DH Cluster launches without any PG Configuration.
3. Tested default DH templates launched successfully and were configured with correct PG when PG Config was added.
4. Tested successful AWS Environment\DL launches without any PG Configuration.

CB-9243 AWS PlacementGroup Support

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeServiceTest.java

CB-9208 CM license is only updated when CM itself is upgraded as well …
Solution is to turn off CM patch release upgrade check, CM will always be upgraded. In this case license will always be updated.
License update is needed because with wrong license CB doesn't allow Runtime upgrade. But if the license has changed in UMS to a good one, we need to update it on the cluster side. It is only updatable on cluster side with CM upgrade.

CB-9208 CM license is only updated when CM itself is upgraded as well

---

authorization-common/src/main/java/com/sequenceiq/authorization/service/CommonPermissionCheckingUtils.java
authorization-common/src/main/java/com/sequenceiq/authorization/service/UmsResourceAuthorizationService.java
authorization-common/src/main/java/com/sequenceiq/authorization/utils/AuthorizationMessageUtils.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/CommonPermissionCheckingUtilsTest.java
authorization-common/src/test/java/com/sequenceiq/authorization/service/UmsResourceAuthorizationServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CreateDhWithDatahubCreator.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CredentialCreateTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DatalakeDatahubCreateAuthTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvironmentCreateTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/RecipeTest.java

The error message for authz was confusing for users.
This pull request introduce a new format for this error message and unify the messages at different locations.
New format of the message:
You have insufficient rights to perform the following action(s): "environments/describeCredential" on a(n) 'credential' type resource with resource identifier: '<crn of resource>'

CB-9051 [AuthZ] Improve error pop up message for non entitled users

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/common-install.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/httpd-log-filter.sh

By default FreeIPA client requests are logged in /var/log/httpd/error_log.
Even if they are not error logs. We have extended the user_mod request to
include additional parameters so we can set the cdpHashedPassword
and CdpUnencryptedKrbPrincipalKey request time (which we don't actually
store), but we use these parameters for configuring the users' password
without them specifying it all the time. This password is stored in UMS
in SHA512 format. However, since every request is logged in error_log
we log the password hash also. To prevent this we're extending the
httpd server config to use a filter, before it writes the actual log
lines to the file. This filter is simply replacing these 2 additional
parameters so they are masked in the log file.
See detailed description in the commit …

CB-9514 filter cdp hash password and Kerberos Principal Key

---

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/TelemetryConfiguration.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/databus/AbstractDatabusStreamConfiguration.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigService.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigView.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/logcollection/ClusterLogsCollectionConfiguration.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/metering/MeteringConfiguration.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfiguration.java
common/src/test/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/TelemetryApiConverter.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/TelemetryApiConverterTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverter.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverterTest.java
orchestrator-salt/src/main/resources/salt-common/salt/fluent/settings.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/databus_monitoring.conf.j2
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/output_databus.conf.j2

details:
- Changes for dbus stream names: we now use streams named in the following format: $ENV-$CLUSTER-LogCollection. Example for the clusters in dev environment can be found here (look for LOGCOLLECTION_STREAMNAME). The existing "LogCollection" stream will continue to exist as long as there are workload clusters pushing data to it.
A- n additional logcollection related header in the fluentd config: We now expect a new header in the fluentd config with the key as @logging-app. Its value will, again, be $ENV-$CLUSTER-LogCollection. For private stacks, the value will be $ENV-$CLUSTER-$WORKSPACE-PREFIX-LogCollection. An example for the clusters in dev environment can be found here (look for LOGCOLLECTION_STREAMAPP). We will continue to accept events without the header.
See detailed …

CB-9468. LogConsumer related DataBus stream changes.

---

integration-test/scripts/swagger-check.sh

CB-9527 Ensure that we are using the latest available build, and not build - 1 for swagger compatibility check. The main problem is that if the compatibility is fixed, you need to wait that the pipeline is executed twice. 
The only catch to moving it to the 0th index is that if RE is updating the RE DB first and uploading the swagger after that then it will fail. But as we see the last step of pipeline is the RE DB update, therefore it is considered to be safe.

CB-9527 Ensure that we are using the latest available build, and not build - 1 for swagger compatibility check

---

core/src/main/resources/defaults/vm-logs.json
freeipa/src/main/resources/defaults/vm-logs.json
freeipa/src/main/resources/freeipa-salt/salt/fluent/template/input.conf.j2
orchestrator-salt/src/main/resources/salt-common/salt/fluent/cdp-logging-agent-init.sls
orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/input_vm_logs.conf.j2
orchestrator-salt/src/main/resources/salt/salt/fluent/template/input.conf.j2

details:
- in order to avoid fluentd specific config changes - use vm-logs.json (that contains label/path pairs)
- vm-logs.json will be both used by fluentd configs + diagnostics (filecollector) configs, so those will gather the same data
- for td-agent, still support the actual solution, but for cdp-logging-agent, the configs should be generated from vm-logs.json (if the telemetry related configs exist)
- add some fixes to vm-logs.json (removed duplication and removed '.' prefix from imbala definitions)
- add some new logs to vm-logs.json (that were there in td-agent config but was not there for diagnostics)

CB-9513. Start using vm-logs.json instead of input.conf.j2 files

---

core/src/main/resources/definitions/upgrade-matrix-definition.json

We have some customers who would like to upgrade from 7.0.2.
Previously this was not enabled due to the fact that it does
not work out of the box. It requires some manual pre-work on
the cluster to make the upgrade successful. Since, the upgrade
feature is behind and entitlement it will not cause any harm,
but should always ask the customer what is their upgrade plan
before we grant the entitlement.

CB-9610 extend the upgrade matrix with 7.0.2 -> 7.2.2 path

---

freeipa/src/main/java/com/sequenceiq/freeipa/util/HealthCheckAvailabilityChecker.java
freeipa/src/test/java/com/sequenceiq/freeipa/util/HealthCheckAvailabilityCheckerTest.java

Fixed the account ID because FreeIpa sync is running with the internal
user, so the current account ID was altus.
Added a test to ensure the entitlement check does not use "altus" for
the account ID.
There is thread-local storage which sets the internal actor (account ID altus). It does this for the entire quartz health check. The availability checker uses the crn service to get the account ID. The CRN service reads the thread-local storage. Every flow and every API call sets the thread-local storage to the real user's account ID. Previously in 2.32, the HealthCheckAvailbiltyChecker was only called for flows/API calls so the real account ID was used. In 2.33 (302e984637775cac69e0e6b1b706341cade5fa22 tag: 2.33.0-b15) it started to be called …

CB-9598: Use stack's account ID in the HealthCheckAvailbilityChecker

---

integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml

This reverts commit f2dc0ebff7ba915048280f8cd91ebf3128499a70.
seems like there is some config error for diagnostics tests, until im figuring it out (im not sure how much time it is), maybe better to revert it for now

Revert "CB-8861. Enable diagnostics (CM & VM based) tests for AWS"

---

mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockCrnService.java
mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/test/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementServiceTest.java

…instead of crnService.getCurrentAccountId() (which is altus in internal case)
Freeipa sync is running with internal user, so we can not use current accountId because it is 'altus' at this point.
Also this commit will ensure that mock ums getAccount call fails if we are calling it with 'altus' anywhere. This should prevent further issues with 'altus' accountId during getAccount call.

CB-9614 [thunderhead-mock] Throw exception if ums getAccount called with 'altus'

---

environment/src/main/java/com/sequenceiq/environment/environment/sync/EnvironmentStatusCheckerJob.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java
redbeams/src/main/java/com/sequenceiq/redbeams/sync/DBStackStatusSyncJob.java

`StatusCheckerJob` implementations haven't filled the request id in
`MDCContext`, and it made hard to investigate status changes during
sync.

CB-9636 add request ID to quartz sync jobs

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazBaseConfigProvider.java

Jira: https://jira.cloudera.com/browse/CB-9451
Basically just made it so RAZ should be deploying on master nodes instead of CORE nodes, this is subject to change in the future as we modify the medium duty shape.
I tested this by running the core cloudbreak service locally and setting up both a light duty and medium duty Azure RAZ datalake, ensuring that the code change was hit by placing a breakpoint on it. Both of these were set up successfully.

CB-9451: Move deployment of RAZ to the master node for better supportability with medium duty datalake setups

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/cloud/StackToCloudStackConverter.java

1. The GCS settings were missed in couple of conversion classes.
2. Without this we can not set the datalake using cloud storage.
./gradlew test

CB-9670 [GCP] Propagate the GCS logging parameters everywhere

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorage.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageSetupService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/util/CustomVMImageNameProvider.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtilsTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/util/CustomVMImageNameProviderTest.java

When extracting image name from connection string expect query paramters to follow the image name.
Related 2.9 change: https://github.com/hortonworks/cloudbreak/pull/9314

ENGESC-4921 Handle Azure custom image with SAS token

---

common/src/main/java/com/sequenceiq/cloudbreak/logger/MDCBuilder.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/GcpNetworkV4Parameters.java
core/src/main/java/com/sequenceiq/cloudbreak/service/metrics/CloudbreakMetricService.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/AllocateDatabaseServerV4Request.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/DatabaseServerV4Request.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/SslConfigV4Request.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/DatabaseServerV4StackRequest.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/NetworkV4StackBase.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/SecurityGroupV4StackRequest.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/aws/AwsNetworkV4Parameters.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/stacks/azure/AzureNetworkV4Parameters.java
redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsStartService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsStopService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsTerminationService.java

It was hard to find log messages cross-service when looking up by env-crn. This commit adds env-crn to MDC context in controller when it is present in the request body but not in request parameters.
Also, redbeams create parameters received toStrings to be logged properly.
Unrelated change: one-line log message to track azure image copy.

CB-9501 Redbeams logging: env crn was not filled in on mow-dev.

---

datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java

Currently, database backup-restore operations are using account roles instead of resource level roles. This should be changed.

CB-9748: Use resource role for database backup-restore operations.

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterStartHandler.java

Previously, we had a simple check in the upgrade flow to see if we
need to upgrade CM server itself. In case of OS upgrade, obviously
we don't need it since the versions do not change. However, we
removed this check, because we can only update the CM license as part
of this flow step. This flow step also executes the user id migration
script and for that we need to stop all the services in CM. The next
step in the upgrade flow is the CDP upgrade which we skip since the
versions do not change. The CDP upgrade flow step would start the
services once the upgrade is complete. The change image flow consists
of 3 different flows:
Stack sync
Cluster sync
Repair all instances (to replace the images)
The cluster sync flow will see that we've stopped the services in CM
and sets the cluster's status …

CB-9757 change-image does not work as part of the OS upgrade

---

datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/DatalakeUpgradeActions.java

CB-9809 - Runtime is not updated in case of failure during replace VM-s

---

common-model/src/main/java/com/sequenceiq/common/api/type/CommonStatus.java

This change solved the leaked disk issues on Azure and GCP side as we create and terminate disks/volumes with dedicated name that's created programatically.
But this is not a solution for AWS, because if a disk quota limitation occurs that means the disk identifiers could not be persisted in our side and later the termination could not be done due to the missing of disk identifiers.

CB-9222 delete volume/disk resources that's in REQUESTED state not to leak resources in case of disk quota exceeded

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java

CB-9266 storage will be removed on gcp when parameters are empty

---

datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/DatalakeDatabaseRestoreActions.java

The promotion cadence for thunderhead and data lake services are different so we should make sure that the API changes are backward compatible. 
With the recent change made to API restoreDatabaseByName is not backward compatible as the older API does not provide restoreId. This is causing issues.
Verified the change by running CB running locally.

CB-9825: Make the API change to database restore backward compatible.

---

core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering.bp

[DISTX-533](https://jira.cloudera.com/browse/DISTX-533)
An escalation ENGESC-3559 identified the problem where spark applications were filling up local disks.
The solution provided was to set fs.s3a.buffer.dir config to YARN local dir so that when spark job finishes YARN can clean those up. But if YARN LOCAL_DIRS is not set then it should fallback to something like /tmp/s3a, hence configuring following in 722, 726, 727 data engineering templates
fs.s3a.buffer.dir=${env.LOCAL_DIRS:-${hadoop.tmp.dir}}/s3a
Testing done:
Have created a DE cluster using a modified 7.2.6 template that includes above mentioned config changes. Cluster creation was successful on AWS using m5d.2xl instance types.

DISTX-533 Set S3A buffer dir to Yarn local dir

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorage.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageInfo.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageInfoService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageSetupService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureManagedImageService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/task/image/AzureManagedImageCreationCheckerContext.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/task/image/AzureManagedImageCreationCheckerTask.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/task/image/AzureManagedImageCreationPoller.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/util/CustomVMImageNameProvider.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtilsTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageInfoServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureManagedImageServiceTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/util/CustomVMImageNameProviderTest.java

With rebase another small refactoring was necessary: 
azureUtils.getImageNameFromConnectionString(image) was moved into CustomVMImageNameProvider and into AzureImageInfo.
=====
On azure, during freeipa launch, a 1) storage account is created, 2) the corresponding vhd image file is copied into the storage account, and 3) an finally azure managed image is created from the vhd file.
If an image already exists, then the whole process should be bypassed. However, if the storage account is deleted but the image exists an error is produced.
In this commit the bug is fixed by refactoring.

CB-9109 Freeipa launch crippled by missing storage account

---

freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java

During a freeipa health check, it first update instances' status and then the freeipa status. In a particular case, if the instance is deleted on provider side, the freeipa will first updates instance status to deleted. But if the environment runtime breaks ad restarts, the healthcheck will skip and won't update the freeipa status because all instances are already deleted. Therefore, after environment recovers, freeipa shows wrong stopped status. This fix will correct the freeipa status as deleted.

CB-6964: Wrong freeIpa status after instance is deleted on provider side

---

cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterProxyRegistrationClient.java

Jira: https://jira.cloudera.com/browse/CB-9848
Basically I just removed the URL from the error messages and moved its output to the logging mechanism, which I assume can only be seen by us so that we still get that information.
Let me know if you have any questions or if I need to do something differently.
Not really sure who to add for the review so please delegate this to whoever.

CB-9848: Removed internal cluster proxy URLs from error messages that are propagated to the UI so that customers don't see them.

---

cloud-aws/src/main/resources/templates/aws-cf-dbstack.ftl

When we create RDS instances for Data Lakes and Data Hubs we create a CF
template which contains the RDS username and password as input parameter.
These parameters are visible on the AWS console, however it can be masked easily
with the "NoEcho" parameter. This is an intermediate solution. The best solution
would be to store these fileds in AWS secrets and reference them in the CF template.

CB-9847 mask the RDS username and password parameters in the CF template

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/CheckImageAction.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/CheckImageActionTest.java

On azure a throttling error caused the failure of the image copy checking task. This was mainly caused by not resetting the failure number after a successful response arrived. In this way the maximum 5 errors was easily reached during the 10-minute-long copy process.
Besides the fix, the checking interval was increased from 5 to 30 seconds, to decrease the probability of a throttling error.

CB-9818 Azure image copy check failed

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/ums/EnvironmentAccessChecker.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/ums/DefaultUmsUsersStateProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/ums/EnvironmentAccessCheckerTest.java

We discovered through a failing systest that caching has been added to the hasRights call. User sync needs uncached hasRights. I tossed this change together (tested locally) because we need this fixed immediately.

CDPCP-3350. Provide user sync with an uncached hasRights implementation

---

core/src/main/resources/defaults/blueprints/7.2.7/cdp-sdx-medium-ha.bp
datalake/src/main/resources/duties/7.2.7/aws/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.7/azure/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.7/yarn/medium_duty_ha.json

For 7.2.7+, SDX HA now has 2 gateway nodes and additional 3 core node that primarily
runs Hadoop services that are dependencies of other groups.  As a result there is
reshuffling of where services are installed.  This also includes renaming master
to main.

CB-9783 update SDX HA to final shape.

---

core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering.bp

[DISTX-539](https://jira.cloudera.com/browse/DISTX-539)
Fix for OPSAPS-56088 now auto tunes lot of machine dependent configs. Hence there is no need to provide static values to some of these configs in cluster templates. Also value of some of the configs are sub-optimal.
Thus removing following configs from 7.2.2, 7.2.6, 7.2.7 DE templates:
hive.tez.container.size
mapreduce.map.memory.mb
mapreduce.reduce.memory.mb
Testing done:
Have created a DE cluster using a modified 7.2.6 template that includes above mentioned config changes. Cluster creation was successful on AWS using m5d.2xl instance types.

DISTX-539 Drop container size configs from templates

---

core/src/main/resources/defaults/blueprints/7.2.0/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.1/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-sdx.bp

This enables Ranger authorization for Solr from 7.2.0 -> 7.2.7.

CB-6028 Enable Solr Ranger Authorization.

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureNetworkLinkService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/AzureEnvironmentNetworkValidatorTest.java

This commit fixes the validation if there is already a network link in the private DNS zone in the deployment's resource group

CB-9858 - Azure environment with same network and RG cannot be created

---

core/src/main/resources/defaults/clustertemplates/7.2.2/aws/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.2/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.2/aws/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.2/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.2/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.2/azure/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.6/aws/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.6/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.6/aws/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.6/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.6/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.6/azure/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.7/aws/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.7/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.7/aws/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.7/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.7/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.7/azure/dataengineering.json

for the DE cluster shapes.
This is a workaround for OPSAPS-54928, where starting a compute group
with 0 nodes causes upscaled nodes belonging to this group to be
misconfigured, and not consume available resources (8GB for NMs).

CB-9902. Increase the default node count for the compute group to 1

---

common/src/test/java/com/sequenceiq/cloudbreak/common/anonymizer/AnonymizerUtilTest.java

Redact the FreeIPA admin password.
This was reviewed https://github.com/hortonworks/cloudbreak/pull/9476 and merged in 2.33, but it had a merge conflict so I am merging it into master with this PR. I also added a test.

CB-9852: Redact FreeIPA admin password

---

client-cm/src/main/java/com/sequenceiq/cloudbreak/cm/client/retry/ApiExceptionRetryPolicy.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/client/retry/ApiExceptionRetryPolicyTest.java

1. In the tagged escalation we saw a couple of connection reset during CM API calls does not get retried.
2. Looking at the code, there is a retry for only 5XX status codes.
3. Logs indicated that the HTTP status code was mapped to 0 when the exception is due to connection reset.

ENGESC-5493 Retry CM API call on HTTP status code 0

---

orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls

During datalake provisioning, an intermittent error of "does not have corresponding DNS A/AAAA record" happens. Currently we don't have logging for dnsrecord add operation. Only a timestamp exists in the log to show the dns add operation is done. This fix will log the added DNS record and the success return information in the add operation. This will help to confirm and debug the missing DNS a record issue.

CDPSDX-1981: missing DNS a record in ipa during datalake provisioning 

---

core/src/main/resources/defaults/blueprints/7.2.0/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.0/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.0/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.1/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.1/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.1/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering.bp

[CDPD-18761](https://jira.cloudera.com/browse/CDPD-18761)
In a customer env, split computation took longer time as FileInputFormat scanned files in single threaded mode. It has been recommended to set value of mapreduce.input.fileinputformat.list-status.num-threads to
100 OOTB. Hence setting following in DE templates for 7.2.0, 7.2.1, 7.2.2, 7.2.6, 7.2.7
mapreduce.input.fileinputformat.list-status.num-threads=100
Testing done :
Have created a DE cluster using a modified 7.2.6 template that includes above mentioned config changes. Cluster creation was successful on AWS using m5d.2xl instance types.

CDPD-18761  change OOTB value of mapreduce input list status threads count

---

datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/DatalakeDatabaseBackupActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/DatalakeDatabaseBackupFlowConfig.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/DatalakeDatabaseRestoreActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/DatalakeDatabaseRestoreFlowConfig.java

There are changes needed in both backup-restore flows to handle failures properly. There were issues in flow configurations causing the flows to be stuck in a pending state.
Below were the issues.
1. When the flows enter the DATALAKE_DATABASE_RESTORE_COULD_NOT_START_STATE and DATALAKE_DATABASE_BACKUP_COULD_NOT_START_STATE states, flows do not wait for the completion of the datalake backup.
2. When the flows enter FullBackupInProgress and FullRestoreInProgress states, database operation status was always set to SUCCESS. That need not be true.
3. Corrected the bean DATALAKE_DATABASE_RESTORE_FINISHED_STATE to DATALAKE_RESTORE_FINISHED_STATE.

CB-9927: Restore flow is in stuck state when there is a failure in performing database restore.

---

core/src/main/resources/defaults/blueprints/7.2.2/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-sdx-medium-ha.bp

This removes the setting of dfs_journalnode_edits_dir from the medium
duty blueprints along with changing the HdfsVolumeConfigProvider to
be more in line with the other configs.

CB-9925 HDFS service health warnings

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParametersConsts.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsCloudWatchService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsLaunchTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsRepairTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsCloudWatchServiceTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleServiceTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/cloud/StackToCloudStackConverter.java

Jira: https://jira.cloudera.com/browse/CB-8962
We specifically wanted to extend the FreeIPA Cloudwatch alarm feature to all AWS nodes created. In order to do this I simply rolled back the specific FreeIPA logic that added a Cloudwatch parameter to the Cloudstacks created for the instances, and removed the check for that parameter in the Cloudwatch alarm parameter.
As far as I know, removing this check will simply cause all AWS instances created by cloudbreak to create the Cloudwatch alarm by default. Please let me know if I am forgetting or overlooking something that could possibly break by removing this check.
All of the logic for automatically removing the Cloudwatch alarm when the instances are terminated, or on some failure, already exists from the FreeIPA changes made before and is …

CB-8962: Added a Cloudwatch alarm to each AWS instance created.

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePermissionProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/CmAndStackVersionFilter.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePermissionProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/CmAndStackVersionFilterTest.java

CDH and CM versions may be different from now on, so the upgrade matrix should only be used for CDH versions.

CB-9761 Do not check upgrade matrix for CM version

---

cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePremiumInstanceTest.java
core/src/main/resources/application.yml

ENGESC-5519 remove e64 instances because of the missing billing.

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/HostMetadataSetup.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java

Some of the issues that come up during Abbvie's support case at the weekend are covered by this PR.
The fix provides that:
- FQDNs be persisted in our metadata at the beginning of bootstrap phase to avoid cases when downscale/specific node termination is not able to run due to the missing FQDNs in our metadata
- Measure the request-response time of CM's deployeClientConfig command

Cb 9934 - Salt orchestrator could not execute tear down when the instances don't have FQDN in our metadata

---

autoscale/src/main/resources/application.yml
core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java
core/src/main/resources/application.yml
datalake/src/main/resources/application.yml
orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl-locations.d/clouderamanager.conf

CB-9998 set cluster proxy timeout to 120 seconds and CM client timouts to 125 seconds in our services

---

core/src/main/resources/application.yml
freeipa/src/main/resources/application.yml
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/grain/GrainUploader.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/runner/SaltCommandRunner.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/grain/GrainUploaderTest.java

In this commit I reduced significantly the polling time for grain add and remove operations in salt.
grain addition and removal should be a fast operation and we should wait hours for it.
with the new configuration, polling will fail after 5-10 minutes (in worst case).

CB-9933 - The polling of Grain append takes more than 3 hours

---

cloud-aws/src/main/resources/definitions/cdp/aws-cdp-log-policy.json

CB-10025. Remove getObject requirement from cdp logging policy (S3).

---

common-model/src/main/java/com/sequenceiq/common/api/cloudstorage/query/ConfigQueryEntries.java
core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/CloudStorageDecorator.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/CloudStorageDecoratorTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/cloudstorage/CmCloudStorageConfigProvider.java

When a DH cluster creation has triggered with an existing custom cluster definition that contains storage location with template indicators (handlebars), the cluster creation fails because CB didn't replace the template placeholders with the actual value.

CB-9174 - Creation of cluster definitions through the CLI is broken

---

freeipa/src/main/java/com/sequenceiq/freeipa/repository/RootCertRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cert/root/FreeIpaRootCertificateService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cert/root/RootCertService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/cert/root/FreeIpaRootCertificateServiceTest.java

In the previous implementation the cert was checked against
environment crn in the database. With this commit first the `Stack`
will be fetched by the environment crn, which already handles child
environments. Then stack id is used to fetch the cert from db or stack
is used to get the cert from FreeIPA.

CB-10042 Handle child environments when getting FreeIPA CA cert

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerUpgradeParcelDownloadListenerTask.java

Contains the following fixes:
- increased 2-hour timeout for parcel download
- fetch and return the download progress in case of time-out

CB-10039 - Increase the parcel download polling time in case of upgrade

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/RetryableFreeIpaClientException.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaHealthCheckClientFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthDetailsService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthServiceTest.java

Unfortunately CCM is not stable and can cause random momentary network
outage. If this happens during health check it would render FreeIPA
unreachable/unusable for 3 minutes, until the next sync.
To handle this more gracefully this commit adds `@Retryable` to the
call which invokes FreeIPA API in `FreeIpaHealthDetailsService`.
By default it will try 3 times with 1 sec delay which should be
enough for CCM to recover and fails fast enough to avoid congestion in
quartz thread pool.

CB-9981 Add retry to FreeIPA healthcheck

---

freeipa/src/main/resources/freeipa-salt/salt/ccm/init.sls
freeipa/src/main/resources/freeipa-salt/salt/ccm/scripts/socket-wait-cleanup.sh
freeipa/src/main/resources/freeipa-salt/salt/top.sls
orchestrator-salt/src/main/resources/salt/salt/ccm/init.sls
orchestrator-salt/src/main/resources/salt/salt/ccm/scripts/socket-wait-cleanup.sh
orchestrator-salt/src/main/resources/salt/salt/top.sls

There may be multiple customers affected by the file descriptor leak.

CB-9762 Scheduled cleanup of CLOSE_WAIT autossh connections

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageServiceTest.java

CB-10055 Fix base image validation: should check the image itself first in case of image id is available in the request.

---

integration-test/scripts/swagger-check.sh

CB-9896 exit with failure from swagger check when version number from release.infra is not a valid version

---

environment/src/main/java/com/sequenceiq/environment/environment/dto/AuthenticationDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/PublicKeyValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/dto/AuthenticationDtoConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/PublicKeyValidatorTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentEditTest.java

- Validating for all the supported algorithm for SSH public key and replacing the comment part with the login user name which has the default value: "cloudbreak".
- We had multiple issues with invalid public keys, one particular customer had backslashes in the comment section
which rendered the Azure ARM template invalid. This change will mitigate such errors.
The regex is based on this: https://gist.github.com/paranoiq/1932126#gistcomment-3211232

CB-10013 - added validation to ssh public key registration in environment service

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/upgrade.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/upgrade.sls

Whenever we're upgrading the CM version it can happen that the new version
was built before the current one. One example is when we're upgrading from
7.2.6 to 7.3.0 and the 7.2.6 build was created on 20th of Nov, but the 7.3.0
build was create on 6th of Nov. In this case yum will not perform the update:
Not using downloaded cloudera-manager/repomd.xml because it is older than what we have:
Current   : Fri Nov 20 09:59:52 2020
Downloaded: Fri Nov  6 02:43:27 2020
No packages marked for update
If we remove the yum caches then the update can be performed. Unfortunately, there is no
clean way of doing it from the SLS files. There are modules available which can be used
from the CLI, like:
salt '*' pkg.clean_metadata
but in SLS states this cannot be used, hece, we're going to use the cmd.run …

CB-10054 clean the yum metadata before updating the CM server and agent

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/instancegroup/InstanceGroupToInstanceGroupV4ResponseConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/instancegroup/InstanceGroupToInstanceGroupV4ResponseConverterTest.java

CB-10087 - InstanceGroup conversion does not copy the original type, so added this operation alongside with the associated test case

CB-10087 - InstanceGroup conversion does not copy the original type

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StackRequestManifesterTest.java

Jira: https://jira.cloudera.com/browse/CB-7210
Specifically this should make it so that RAZ datalakes cannot be created if they don't include the rangerraz IDBMMS role. Similarly, if they do include the role and are note trying to create a RAZ datalake, should return an error. 
Note that while we definitely want the first of these changes, we are not sure if the second is ideal. I hope these changes facilitate a discussion on this.
I also included some quick tests that kind of test this, please let me know if I need to expand on them in any way.

CB-7210: Ensure that RAZ role is included when RAZ is requested, and isn't when it is not.

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AmazonAutoscalingFailed.java

Overriding the exception's toString to leave out the class' full name

CB-9989 Remove class name from the error message presented during AmazonAutoscalingFailed

---

orchestrator-salt/src/main/resources/salt/salt/sssd/template/add_dns_record.j2

During datalake provisioning, an intermittent error of "does not have corresponding DNS A/AAAA record" happens. As we verified that dns a-record was first added and then went missing before adding service to kerbores later, we added 3 times retry with a random 10-15 seconds interval to remedy this. Also this will help to confirm how long the issue lasts and whether it comes back.

CDPSDX-1981: missing DNS a record in ipa

---

flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java

The following change broke retry feature:
https://github.com/hortonworks/cloudbreak/pull/9126
2020-12-02 14:40:02,946 [reactorDispatcher-77] lambda$handleFlowControlEvent$1:204 INFO c.s.f.c.Flow2Handler - [type:SDX] [crn:] [name:pdnd-prod-dl-1] [flow:] [requestid:ce7006b7-6f00-4e8b-a228-f88c7e4cf625] [tenant:9ad782ee-3322-4342-a3be-3a2348e0414e] [userCrn:crn:altus:iam:us-west-1:9ad782ee-3322-4342-a3be-3a2348e0414e:user:cf95a1a5-7858-488d-a69f-3b1c5b20df91] [environment:] [traceId:357a8cb5399c0674] [spanId:cb749a7f78372593] Flow 6835f9c4-a1fa-42d5-9ebb-8660e3ae5177 was handled by another node cloudbreak-datalake-55d977fb4b-hdkls, current node ID is cloudbreak-datalake-74c57b894d-64stl, abandoning.

CB-10112 fix retry feature

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/action/RebootActions.java

Fixed a regression that was introduced in
99a3d0019a986ce95cedb27c0c8459e29c8da63c. The reboot flow did not load
the FreeIPA stack metadatalist but it accessed.
This was tested by manually deploying a cluster and rebooting FreeIPA
using a local cloudbreak deployment.

CB-10032: Fix LazyInitializationException during reboot

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

**Describe the change you are making here!**
NiFi team ran into issues with a customer with large uploads. This issue is identified as a critical fix and needs to land as quick as possible (hotfix).
The changes proposed in this PR are:
- increase the socket timeout for Nifi
- set retry and failover counts to zero 
**Testing**
The patch was tested on a cluster running NiFi

CB-10160 - Increase socket timeout and update maxFailoverAttempts=0 for NiFi service

---

cloud-aws/build.gradle
integration-test/build.gradle

Checked AWS provisioning, worked fine with datalake, datahub.
Before merging in, please be sure that no other dependency was introduced for aws sdk, nobody started to use another functionality from aws sdk since this would cause compile error.
Two module that depends on are:
- cloud-aws,
- integration-test.
I checked them up until this (730d5a1bf3bf21ef4a7cdd64ce616139a45d3284) point.

CB-10106 Reduce the AWS SDK dependency size by using specific libraries

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/upgrade.sls

Unfortunately, the parcel files are large and they are even
replicated across multiple folders. Most of these folders
are used by intermediate processes like the distribution, but
they are not used after that point. Before the next upgrade we
need to clean up these folders, otherwise we run out of free space
on the root disk. Eventually, the usage of the folders should be
fixed in CM and these are just workarounds.

CB-5472 remove unused parcel files before upgrade

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/InstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxUpgradeTests.java
mock-thunderhead/src/main/resources/application.yml

CB-9580 Introduce new test cases in upgrade mock tests:
1. if embedded database is on attached disk, upgrade have to be successful
2. if embedded database is on root disk, upgrade have to fail

CB-9580 Introduce new test cases in upgrade mock tests for embedded database

---

core/src/main/resources/defaults/clustertemplates/7.2.1/aws/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.1/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.1/aws/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.1/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.1/azure/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.1/azure/dataengineering.json

Increased the default compute node count to 1 for cluster templates in 7.2.1

CB-9902: Increase the default node count for the compute group to 1 in 7.2.1 templates

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbCertificateProvider.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbCertificateProviderTest.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/start.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/root-certs.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/settings.sls
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/AbstractRdsRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/AbstractRdsRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerRoleConfigProviderTest.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObject.java
template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/views/RdsView.java
template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/TemplatePreparationObjectTest.java
template-manager-core/src/test/java/com/sequenceiq/cloudbreak/template/views/RdsViewTest.java

* Extract DB SSL root cert file name `/hadoopfs/fs1/database-cacerts/certs.pem` as the new property `cb.externaldatabase.ssl.rootcerts.path` in `core/src/main/resources/application.yml`
* Remove all other former occurrences of `/hadoopfs/fs1/database-cacerts/certs.pem` and let them be populated from the above application property (for Java) and the new pillar property `postgres_root_certs:ssl_certs_file_path` (for Salt)
* Note: `RedbeamsDbCertificateProvider.getSslCertsFilePath()` depends on neither the `Stack` nor the `Cluster` at the moment. Conditional calculation of the file path may be added later as needed.
* Introduce a new Python dict for DB SSL settings; see `orchestrator-salt/src/main/resources/salt/salt/postgresql/settings.sls`
* Add new unit tests and adapt / migrate existing …

CB-9525 DB SSL root cert file location customization

---

freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackStatusRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackStatusService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/InstanceMetaDataService.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaStatusInfoLogger.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java
freeipa/src/test/java/com/sequenceiq/freeipa/sync/StackStatusTest.java

During ENGESC-5655, we had a hard time debugging the freeipa status. Currently we only log freeipa status when there is a transition (eg. from healthy to unreachable) and it was determined that adding a log message for both freeipa status and instance status during health check would be helpful. Now we added logging for every health check.

CB-10162 Add log message every time the FreeIPA status is checked

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/init.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/init_db_remote.sh

* When the external DB server has been provisioned with SSL enforcement (#9215), DB create operations shall always mandate SSL with DB server cert and host name verification.
* Depends on #9563.

CB-9526 Use SSL with cert&host verification for Salt external DB create

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecomissionService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelDecommissionService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelManagementService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerUpgradeService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/PollingResultErrorHandler.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerSingleParcelActivationListenerTask.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecomissionServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelDecommissionServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerUpgradeServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/PollingResultErrorHandlerTest.java
core/src/main/java/com/sequenceiq/cloudbreak/cloud/model/component/ImageBasedDefaultCDHEntries.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterUpgradeHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/PreWarmParcelParser.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/locked/ParcelMatcher.java
core/src/test/java/com/sequenceiq/cloudbreak/cloud/model/component/ImageBasedDefaultCDHEntriesTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/PreWarmParcelParserTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/locked/ParcelMatcherTest.java
orchestrator-salt/src/main/resources/salt/salt/cloudera/csd/csd-downloader.sh
orchestrator-salt/src/main/resources/salt/salt/cloudera/csd/init.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/upgrade.sls

In this commit we've introduced some changes in connection with Data Hub upgrade:
- CSD downloading: To upgrade a non-CDH service may require the same version of the CSD what the new version is. By default the old CSD files are already present in the image, therefore we need to download the new ones. This process is handled by a shell script that we add to the host at the beginning of the upgrade process.
In the case of Data Lake upgrade, we don't need to download the new CSD files because we're not upgrading the non-CDH services.
- Upgrading the non-CDH services (Spark, Nifi, etc...) has a different flow than the regular CDH runtime upgrade. We need to download, distribute, and activate the new parcels, then restart the affected services. There is no upgrade command to call.
After the …

CB-9943: Extend the Data Hub CDH runtime upgrade process with upgrading the non-CDH services to a new version what we burned into the new image.

---

freeipa/src/main/java/com/sequenceiq/freeipa/sync/ProviderChecker.java
freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java

Fix the FreeIPA log message for the old instance's status.
This was manually tested with a local deployment of cloudbreak.

CB-10290: Fix the FreeIPA log message for the old instance's status

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/BaseImageValidatorE2ETest.java

This is fixing the base image one for now.
The prewarmed based test works on my machine for GCP. So this is the only fix that is needed.

CB-10299 modify BaseImageValidatorE2ETest case not to config explicitnew network for SDX internal calls

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeDistroxFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/DistroxUpgradeTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/ClusterRepairTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageChangeDto.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/UpgradeConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroxUpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeDistroxFlowEventChainFactoryTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroxUpgradeServiceTest.java

Data Hub OS upgrades are supported via cli with " --lock-components --replace-vms ENABLED"

CB-9711 - OS upgrade for datahubs should work

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/PrivateEndpointTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/ResourceGroupTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/config/PrivateEndpointProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentNetworkTestDto.java
integration-test/src/main/resources/application.yml

This commit enabled to test postgres via private endpoint on azure as well. It can be turned on for AWS and AZURE via environment variable 'integrationtest.privateendpoint.enabled'. For other platforms it is disabled for now.
For AZURE it also needs to be used together with single rg option. If it is a multiple rg deployment, then private endpoints are automatically turned off in int-test.

CB-9462 [E2E] Enable Private Link creation in CB E2E test

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthDetailsService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthServiceTest.java

Fix FreeIPA health summary status on the health API. The summary
correctly reports unreachable, stopped, available, and unhealthy now.
Fix the FreeIPA health check API's instance status when the health
check fails.
Populate the missing instance ID for the FreeIPA health check.
Tested with unit tests and also with a local instance of cloudbreak.

CB-10291 & CB-10292: Fix the FreeIPA health check API

---

core/src/main/resources/defaults/blueprints/7.0.2/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.1.0/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.0/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.1/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering-ha.bp

1. In the tagged engineering escalation we saw a scenario Hue did not follow the HDFS failover.
2. The suggested approach was to use HTTPFS role for hue_webhdfs.
3. Used this template as a custom template to create a cluster and verify that hue_webhdfs indeed points to HTTPFS role.

ENGESC-5190 Make Hue follow the HDFS failovers using WebHDFS

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationStackUtil.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsResourceConnector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/loadbalancer/AwsTargetGroup.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleServiceTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleServiceTest.java

Adds new logic to AwsDownscaleService and AwsUpscaleService. The new logic will
update the load balancer's routing rules to either remove any instances that
are being deleted from the instance groups the load balancer routes traffic to,
or add any new instances in those groups to the load balancer's targets.
Tested with unit tests, and by terminating the Knox gateway node and initiating
a repair to verify the load balancer was correctly updated.

CB-9901 Update load balancer when instances change

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProviderTest.java

RAZ is enabled on 7.2.6, but the code change for HBase feature supporting RAZ is only on 7.2.7. Therefore, only enable HBase cloud storage feature on 7.2.7+.

CB-10320: Do not enable HBase on S3 for 7.2.6 when Raz is enabled

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UmsClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxSecurityTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceWaitObject.java

CB-10327 Fixes:
* wrong deletion check in instance wait object
* we don't need to wait to the flow in case of CERT_ROTATION_IN_PROGRESS
* missing supported dto in UmsClient: UmsTestDto
missing null check at clients

CB-10327 Fixes:

---

common-model/src/main/java/com/sequenceiq/common/api/type/PublicEndpointAccessGateway.java
common/src/main/java/com/sequenceiq/cloudbreak/converter/PublicEndpointAccessGatewayConverter.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/base/EnvironmentNetworkBase.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentNetworkResponse.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/NetworkCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentResourceService.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkRequestToDtoConverter.java
environment/src/main/java/com/sequenceiq/environment/network/CloudNetworkService.java
environment/src/main/java/com/sequenceiq/environment/network/NetworkService.java
environment/src/main/java/com/sequenceiq/environment/network/dao/domain/BaseNetwork.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/EnvironmentBaseNetworkConverter.java
environment/src/main/java/com/sequenceiq/environment/network/v1/converter/EnvironmentNetworkConverter.java
environment/src/main/resources/schema/app/20201208195427_CB-10242_API_changes_for_semi-private_networks.sql
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentModificationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentResourceServiceTest.java
environment/src/test/java/com/sequenceiq/environment/network/CloudNetworkServiceTest.java
environment/src/test/java/com/sequenceiq/environment/network/NetworkServiceTest.java
environment/src/test/java/com/sequenceiq/environment/network/v1/converter/AwsEnvironmentNetworkConverterTest.java
environment/src/test/java/com/sequenceiq/environment/network/v1/converter/AzureEnvironmentNetworkConverterTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/environment/EnvironmentNetworkTestAssertion.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentNetworkTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentWithPublicEndpointAccessGatewayTests.java
integration-test/src/main/resources/testsuites/e2e/network-endpoint-access-gateway-tests.yaml
structuredevent-model/src/main/java/com/sequenceiq/environment/network/dto/NetworkDto.java

Adds new optional fields 'usePublicEndpointAccessGateway' and
'endpointGatewaySubnetIds' to the EnvironmentNetworkV1Request API object. These
fields are persisted to the EnvironmentNetwork and NetworkDto BaseNetwork
objects. Adds new columns for these fields to the environment_network table
and saves them to the database.
Tested with unit tests, and by manually setting the new fields in the IDE and
verifying they were converted/persisted in the database correctly.

CB-10242 API changes to support semi-private networks

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/clustertemplate/ClusterTemplateV4Base.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

Also, I have omitted "Template" from the messages as it is being used for Definitions.

CB-10348 Fix misleading cluster definition errors

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/InvalidFreeIpaStateException.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/mapper/FreeipaClientExceptionWrapperMapper.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/mapper/InvalidFreeIpaStateExceptionMapper.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/handler/CertRevokeHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/handler/DnsRemoveHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/handler/HostRemoveHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/handler/RoleRemoveHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/handler/UserRemoveHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/cleanup/handler/VaultRemoveHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/ServerRemoveHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactoryTest.java

Whenever the FreeIPA instance is not reachable and we know it's not reachable because the status indicates it, we're going to return 502 Bad Gateway.
According to the official explanation of the status code:
The server was acting as a gateway or proxy and received an invalid response from the upstream server.
If we don't know that the IPA server is not reachable, because we think it's available, that will remain an Internal Server Error.

CB-9972 If freeipa is in unreachable state, badgateway http status code will return instead of internal server error in the freeipa endpoint responses

---

integration-test/src/main/resources/application.yml

Modify the e2e test configuration to use CDH 7.2.6 for target version instead of CDH 7.2.7 because currently, the upgrade is not working for CDH 7.2.7

CB-10401: Modify the e2e test configuration to use CDH 7.2.6

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/task/image/AzureManagedImageCreationPoller.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageServiceTest.java

The problem: when a user wants to use a new image, it needs to be copied to its storage account and then a managed image is created from it. The first step in image creation is to persist an image resource to database with status REQUESTED. If an exception comes during image creation then a polling is done. If after the polling the image is still not present then the exception is re-thrown and the user is notified.
However, unbeknownst to the developers, the poller throws an exception on timeout - the code that would set image status to FAILED is not run any more. An image in REQUESTED state would then block the usage of that image forever, it is a trap state.
Solution: the poller after image creation does not throw an exception on any error but lets the calling code decide what to do.

CB-10029 Azure managed image creation error can potentially lock user out from using its single RG or subscription

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/backups.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/backup-log-filter.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup
freeipa/src/main/resources/freeipa-salt/salt/logrotate/conf/ipabackup
freeipa/src/main/resources/freeipa-salt/salt/logrotate/init.sls

Add FreeIPA backup debug to salt output and /var/log/ipabackup.log.
Include redaction of the x-amz-security-token.

CB-10411: Add FreeIPA backup debug to logs

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/services.sls

ipa-custodia and ipa-dnskeysyncd now will automatically restart after 60 seconds with failure exit code. We change it to 3 seconds and always to be consistent with all other services.

CB-8937: ipa-custodia and ipa-dnskeysyncd restart after 60 seconds

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaChecks.java

We started considering few group names to be reserved on CDP UMS-service. Those reserved group names also contain IPA protected groups taken from this file. Therefore, whenever IPA protected groups are updated, we need to update reserved group names in UMS as well. This commit adds a comment to track that.

Add comment related to cdpcp-2612

---

core/src/main/resources/defaults/blueprints/7.2.7/cdp-streaming-small.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-streaming.bp

By mistake, SRM (already released for 7.2.6) was left out from 7.2.7 Streams Messaging blueprints. This is to fix that.
Testing: tested manually on AWS / Azure with Light Duty / Heavy Duty.

CB-10450 Add missing SRM to 7.2.7 Streams Messaging blueprints

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpProvisionSetup.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpLabelUtil.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpLabelUtilTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/BaseImageValidatorE2ETest.java

**Changes:**
- not to create new newtork for Datalake with internal call in BaseImageValidatorE2ETest 
- limit the length of the GCP bucket name as it could not be longer than 63 characters

Cherry pick of Gcp image promoter E2E test fixes from 2.36 line

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaInstanceHealthDetailsService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaInstanceHealthDetailsServiceTest.java

Fix legacy FreeIPA health check to use the result flag in all cases.

CB-10403: Fix legacy FreeIPA health check to use the result flag

---

build.gradle
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterPreCreationApi.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/model/ServiceLocation.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/model/ServiceLocationMap.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerPreCreationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtServiceConfigLocationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtVolumePathBuilder.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/MgmtServices.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtServiceConfigLocationServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeServiceTest.java
orchestrator-salt/src/main/resources/salt/pillar/cloudera-manager/settings.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/start.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/start.sls

It's possible during upgrade different images has cloudera-scm user and group with different UID/GID.
Cloudera Manager server can use 4 directories. With this change we ensure before starting the server these directories has the right owner. As a side effect we create these directories even if CM doesn't need some of them.
The list of the directories is coming from JAVA side where we create the configuration for CM itself, this way it's ensured we'll set the owners if a new directory introduced.

CB-10363 Highstate must always correct the userid / group id

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpProvisionSetup.java

1. FreeIPA HA setup uses link-local IP address as a forwarder which does not work in GCP.
2. To make it work we need to enable MULTI_IP_SUBNET while creating the image https://cloud.google.com/vpc/docs/create-use-multiple-interfaces#i_am_having_connectivity_issues_when_using_a_netmask_that_is_not_32
3. This change will enable us to test the FreeIPA HA in GCP.

CB-8677 Fix FreeIPA HA in GCP

---

template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.2.7.json
template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.2.8.json

Version infos for SRM are missing for 7.2.7 and 7.2.8 and as a result SRM is not shown on the UI cluster creation page.
Testing: tested manually for 7.2.7

CB-10484 add SRM versions to 7.2.7 and 7.2.8 version infos

---

core/src/main/resources/defaults/blueprints/7.2.8/cdp-streaming-small.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-streaming.bp

SRM (released in 7.2.6) is missing from the 7.2.8 Streams Messaging blueprints. This PR fixes it.

CB-10468 Add missing SRM to 7.2.8 Streams Messaging blueprints

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/BackupDatalakeDatabaseFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/FlowChainTriggers.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java

Create a flow chain using the flow for updating salt and also flow for database backup.
This flow chain should first trigger the flow to update the salt pillar and sates in the nodes before triggering the flow for database backup.
This is needed because data lake nodes setup using runtime 7.1.0 and 7.2.0 might not have the necessary salt pillar and salt states needed to perform a database backup.
Tested the changes by triggering the database backup using CBD. I made sure that salt update of triggered before database backup. Additionally, i deleted some of the salt scripts needed for database backup and made sure that database backup was successful and the salt scripts are restored.

CB-10451: Perform salt update before performing datalake backup.

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/dr/BackupRestoreV4RequestValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/BackupRestoreSaltConfigGenerator.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/dr/BackupRestoreV4RequestValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/dr/BackupRestoreSaltConfigGeneratorTest.java

As runtime 7.1.0 and 7.2.0 do not support backup to object stores, we should support backup to HDFS location as well.
This is needed to support backup for data lake that are using runtime 7.1.0 and 7.20.

CB-10452: Database backup should support hdfs location as well.

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/start.sls

CM MGMT services use some directories under /hadoopfs which owners must be ensured. This has been added with a previous commit.
With this commit we won't create the directories if they don't exist to avoid some issues on ycloud and creating directories when not used.

CB-10519 Modify directories' owner only if directory exists

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/loadbalancer/LoadBalancer.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/GatewayPublicEndpointManagementService.java
core/src/main/java/com/sequenceiq/cloudbreak/util/StackUtil.java
core/src/main/resources/schema/app/20201221232206_CB-9746:_Use_new_loadbalancer_endpoints_for_DL_services.sql
core/src/test/java/com/sequenceiq/cloudbreak/service/publicendpoint/GatewayPublicEndpointManagementServiceTest.java

This PR addresses the following Jiras:
https://jira.cloudera.com/browse/CB-9746
https://jira.cloudera.com/browse/CB-10123
Specifically, I am attempting to change the endpoints assigned to all of the Datalake services from being constructed with a Knox URL to being constructed with the LoadBalancer URL.
The end-goal is for this change to be reflected across both the CDP UI and any other way of attempting to access the individual service endpoints

CB-9746: Adding LoadBalancer FQDN endpoints to the datalake services.

---

orchestrator-salt/src/main/resources/salt/salt/gateway/knox.sls

When CM introduced Knox it didn't have a way to generate the signing
keys and topologies so we used our existing Salt states to generate them.
However, at the time of generation of these files the Knox user does not
exist, because it will be created later during the template installation.
For this reason we had to make the files world readable. Since CDP 7.2.1
CM introduced a script that CB calls to make all the user and group IDs
deterministic. After the invocation of this script the Knox user and group
becomes available when we generate the Knox files.
This PR is making the Knox user as the owner of these files intead of having
a world readable permission. This is only possible from 7.2.1 onwards at
the moment. The new permissions will look like the following:
ls -la …

CB-10482 Knox signing keys should not be world readable

---

core/src/main/resources/defaults/blueprints/7.2.0/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.1/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-sdx.bp
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProviderTest.java

Closes [CB-10487](https://jira.cloudera.com/browse/CB-10487)
* Remove code that added dfs_replication to hdfs service configs
* Add `dfs_replication` values to templates:
* 7.2.0
* 7.2.1
* 7.2.2
* 7.2.6
* 7.2.7
* 7.2.7 HA
* 7.2.8
* 7.2.8 HA
Tested by setting up Data Lakes using `cbd` tool locally.

CB-10487: Manually revert CB-7306, fix dfs replication values.

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazBaseConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatahubConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/raz/RangerRazDatalakeConfigProvider.java

Jira: https://jira.cloudera.com/browse/CB-10511
Specifically just wanted to make it so that DataHubs have RAZ deployed on their Gateway nodes, while Datalakes have it deployed on the nodes with the name "master".
Have not tested yet but will do so soon.

CB-10511: Changing RAZ deployment location in DHs to the Gateway and keeping it to master nodes for DLs.

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/backup/cloud/CloudBackupFolderResolverService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/backup/cloud/GCSBackupConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/backup/cloud/GCSBackupConfigGenerator.java
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/backup/cloud/CloudBackupFolderResolverServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/backup/cloud/GCSBackupConfigGeneratorTest.java

1. Setup the FreeIPA backup config folder appropriately.
2. The backup logic got convoluted because a normal gsutil cp operation needs storage.objects.get permission if the destination is an object instead of bucket.
3. To achieve the directory structure temporarily copied the backups to a folder with the appropriate structure then perform the move to the destination.
4. Tested the script in a live cluster.

CB-8906 Add FreeIPA backup support for GCP

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/dns/DnsV1Endpoint.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/DnsV1Controller.java

DnsV1Endpoint and DnsV1Controller needed some modification to handle internal calls.
As delete operations already have environment crn as parameter it doesn't need any API change.
For adding records a new internal versions have been introduced to keep API compatibility.

CB-10545 DNSv1Endpoint should be able to handle internal calls

---

common-model/src/main/java/com/sequenceiq/common/api/telemetry/base/FeaturesBase.java
common-model/src/main/java/com/sequenceiq/common/api/telemetry/doc/TelemetryModelDescription.java
common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/Telemetry.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/TelemetryApiConverter.java
environment/src/main/java/com/sequenceiq/environment/telemetry/service/AccountTelemetryService.java
environment/src/main/java/com/sequenceiq/environment/telemetry/v1/converter/AccountTelemetryConverter.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/TelemetryApiConverterTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverter.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverterTest.java
structuredevent-model/src/main/java/com/sequenceiq/environment/environment/dto/telemetry/EnvironmentFeatures.java

details:
create a new flag on the api (in telemetry request/response) to be able to disable/enable cloud storage logging (even if s3 related details are provided in the telemetry settings)
provide this flag for account level telemetry + freeipa/datalake/datahub telemetry

CB-10504. Make cloud storage logging configurable by a flag (API)

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyServiceTest.java

For CCMV2, "cloudera-manager" service should be registered with cluster proxy.
Endpoint should be based on 9443 nginx.

CB-10541 CCMV2 Cluster Proxy Registration

---

mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
mock-thunderhead/src/main/resources/application.yml

CB-10141 Missing Experience deletion entitlement from mock-thunderhead service

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/dns/model/DnsRecordRegexpPatterns.java
freeipa-api/src/test/java/com/sequenceiq/freeipa/api/v1/dns/model/DnsRecordRegexpPatternsTest.java

With this commit A records with wildcard characters will be supported.
Wildcard only supported in the beginning and must be followed by dot and other valid characters.
Accepted:
`*.test`
`*.test.name`
Not accepted:
`*`
`*.`
`test.*.`
`*test`
`test*`
etc

CB-10555 Support wildcard hostname in requested DNS A records

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java

Added a new entitlement for the public / private load balancer to the datahubs. This is separate
entitlement than the datalake one to err on the consevative side.

CB-10096 Expand Knox load balancer to data hubs

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/conversion/FmsUserConverter.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/conversion/FmsUserConverterTest.java

If user first or last name starts or ends with spaces the sync for that user would fail on FreeIPA side.
To avoid such issues we have to trim these spaces during user sync.
Workloadusername also stripped from spaces and now checked against if it's blank isntead of empty.
Please wait for @handavid approval before merging

CB-10592 Trim user name from leading and trailing spaces before sync

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/InstanceMetaDataToCloudInstanceConverter.java

On azure, customer created a cluster with specifying a custom resource group name on the UI. In this scenario downscale did not work, it failed at downscale stack step. Reason: cloudbreak was looking for virtual machines not in the resource group specified by the customer but the one cloudbreak would have generated.

CB-10572 [2.9] downscale does not work with custom resource group name

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxImagesTests.java

CB-10553 enable pre-warmed based image test for SDX on GCP, that was disabled accidentally

---

freeipa/src/main/resources/application.yml

Now that cluster proxy has circuit breakers, allow enough time for the
FreeIPA health check (run from cluster proxy) to run again after the
inital ciruit breakers opens the cirucit. Allowing 20 attempts at 5
seconds, provides sufficient time.

CB-10634: Allow 100 seconds for initial cluster proxy health check

---

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentOpDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaOperationDescriptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java
freeipa/src/test/java/com/sequenceiq/freeipa/controller/FreeIpaV1ControllerTest.java

This commit supports the use case where an internal service needs to
list environments or list FreeIPA stacks. This follows the pattern
of the FMS describeInternal API where a parallel API is added that
includes the accountId as a query parameter. Authorization for these
APIs is limited to the internal actor only through the @InternalOnly
annotation.

CB-10536. Add internal list APIs to environments and FMS

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/service/ClouderaManagerProductsProvider.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ImageFilterParamsFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/CdhPackageLocationFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClouderaManagerPackageLocationFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/CmAndStackVersionFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/CsdLocationFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/EntitlementDrivenPackageLocationFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ImageFilterParams.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/PackageLocationFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/PreWarmParcelLocationFilter.java
core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ImageFilterParamsFactoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/CdhPackageLocationFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClouderaManagerPackageLocationFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/CsdLocationFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/EntitlementDrivenPackageLocationFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/ImageCreationBasedFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/PreWarmParcelLocationFilterTest.java

When we send an upgrade request it's important to use only the required CSD files and pre warmed parcels to filter the images.
The second part of this change is during the upgrade we need only download the required CSD files.

CB-10265: Only update the required CSDs with Data Hub upgrade

---

orchestrator-salt/src/main/resources/salt/pillar/nodes/hostattrs.sls
orchestrator-salt/src/main/resources/salt/pillar/top.sls

Using wildcard `*` char for including pillars in top file doesn't work in saltstack 2017.
To avoid the issue when the file is not present and causing issue in the top file and also
support the old saltstack version we are placing an empty version of this file in the
orchestrator-salt modul pillar directory. This will result in `hostattrs.sls` being on the
filesystem when salt states are updated but somehow the pillars are missing.

CB-10679 Place empty hostattrs.sls pillar file to support salt 2017 version

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/UserV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UserOperationDescriptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java
freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java

This is similar to my previous pull request. I identified one more API that we'll need to call internally.
An internal usersync status API is added to the FMS
to allow internal actors to retrieve status of usersync
operations.

CB-10536. Add internal API to get usersync status

---

cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterProxyError.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterProxyException.java
freeipa-client/build.gradle
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/ClusterProxyErrorRpcListener.java
freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaHealthCheckClusterProxyErrorRpcListener.java
freeipa/src/test/java/com/sequenceiq/freeipa/client/FreeIpaHealthCheckClusterProxyErrorRpcListenerTest.java

The FreeIPA management service was fix so that when a
ClusterProxyExcpetion is thrown, the HTTP response status code can be
decoded and it can be converted into a retryable exception.
This was tested on a local deployment of cloudbreak.

CB-10668: Fix retries when ClusterProxyException is thrown

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/network/AwsNetworkV4Parameters.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/loadbalancer/EndpointGatewayNetworkValidator.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/EnvironmentBaseNetworkConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/SubnetSelector.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4Converter.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/loadbalancer/EndpointGatewayNetworkValidatorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/EnvironmentBaseNetworkConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/SubnetSelectorTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/network/SubnetTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4ConverterTest.java

Adds new logic to the NetworkV1ToNetworkV4Converter to detect the public endpoint gateway
is enabled for the environment, and if so selects and adds the subnet for the endpoint to
the AWS network object. The logic for selecting a subnet has been moved out of
EnvironmentBaseNetworkConverter where it originally lived and into a separate SubnetSelector.
Support for other cloud providers will be added as this feature is extended to new cloud
providers.
Tested with unit tests and by creating data hub and verifying LB creation was successful.

CB-10617 Semi-private network: Datahub creation fails with Unable to configure load balancer

---

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl-locations.d/knox.conf
orchestrator-salt/src/main/resources/salt/salt/nginx/init.sls

CcmV2 agent currently forwards requests only to nginx on port 9443.
Control Plane requests to cluster's /resourcemanager and similar api need to be routed to knox for features like DH autoscaling to succeed.
Hence nginx on port 9443 should be configured with a new rule which routes all requests with path prefix "/knox/<clustername>" to knox running on the node. The re-route rule to knox should not include path prefix "/knox" and should only include /<clustername>.

CB-10419: [CCMv2] New route for knox from nginx on port 9443

---

autoscale/src/main/java/com/sequenceiq/periscope/domain/Cluster.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/ClusterStatusMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/LoadMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/TimeMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java

Periscope Cluster Monitors while loading clusters for evaluation load entire Cluster Object. But in Monitor Evaulation Context, only ClusterId is required. So ClusterStatusMonitor, LoadMonitor, TimeMonitor are  enhanced to initialize only ClusterId in this context.
Since these monitors are run very frequently, load on PersicopeDB is also reduced.
Also stops hibernate warnings about 500 queries in single transaction.

DISTX-556 Optimize Periscope Cluster Monitors

---

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisor.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/CloudResourceAdvisorTest.java

The autoscaling was earlier supported on version equal or above 7_2_0 and post this change it would be supported on versions equal or above 7_2_1

CB-9885:AutoScaling should only be configurable for runtime version 7.2.1 or higher

---

environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/validation/network/AzureEnvironmentNetworkValidatorTest.java

Validation during environment creation with private endpoint fails if there are no subnet with networkSecurityGroupPolicies disabled. The error message, however, was not clear enough. This commit improves the error message.

CB-10663 Azure PrivateEndpoint Subnet Selection Issue

---

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl.conf

We need to turn off ssl_verify_client in the ssl configuration, and should use localhost:9443.

CB-10358: Changes to user-data-helper script to support one way TLS between inverting proxy agent and nginx

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java

Adds new logic to load balancer creation to check if private subnets are available.
If not, then a public LB will be created instead of a private LB. The LB creation
logic was also moved from StackV4RequestToStackConverter to LoadBalancerConfigService,
and has been refactored to add more log statements about what conditions are being
evaluated, and to simplify the checks needed. New unit tests were added for the
new conditional checks.
Tested via unit tests, and by Ganesh Kumar Sankaran via applying the patch and
creating a data hub with semi-private networks enabled.

CB-10670 Datalake creation semi-private network creation fails with public subnets

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationStackUtil.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsValidatorsTest.java

Replaces the AwsLoadBalancerScheme.valueOf() conversion with a call to LoadBalancerTypeConverter.convert().

CB-10731 Load balancer type not being converted correctly in CloudFormationStackUtil

---

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/EnvironmentBaseNetworkConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/EnvironmentBaseNetworkConverterTest.java

Adds a check in EnvironmentBaseNetworkConverter to only trigger the semi-private
network logic if the feature is enabled for the environment.
Tested with a new unit test.

CB-10735 Semi-private network entitlement check incorrect

---

orchestrator-salt/src/main/resources/salt/salt/top.sls

This splits the gateway or knox logic into their own and sets the
nginx.init on the gateway instance instead of the knox instance as
DH HA has knox deployed on non gateway nodes.

CB-10699 Datahub HA template fails with missing ngninx ssl conf

---

freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java

When FreeIPA is invalid state we shouldn't throw HTTP 500.
`InvalidFreeIpaStateException` has a different mapper so we will keep this exception in case of keytab creation.

CB-10650 Don't map `InvalidFreeIpaStateException`

---

autoscale/src/main/java/com/sequenceiq/periscope/service/ha/LeaderElectionService.java

Periscope Node has a heart beat service which updates heartbeat in DB every 30 seconds indicating its aliveness.
Also there is a LeaderElectionService which polls active nodes which have updated heart beat in last 60 seconds.
Under certain scenarios when DB is slow or Node is slow and a single Leader heartBeat is delayed, Leader assumes it is not leader even though it is still leader and stops the process of allocating new DH Clusters to one of the periscope node.
Hence code is updated so that allocating new DH clusters is stopped only if active nodes are not empty.

DISTX-559 DH Autoscaling Periscope Node Allocation.

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterDetailResponse.java
datalake-api/src/test/java/com/sequenceiq/sdx/api/model/SdxClusterDetailResponseTest.java

fix for NPE when one wants to obtain the value of a tag for an empty SdxClusterDetailResponse

CB-10756 - fix for NPE when one wants to obtain the value of a tag for an empty SdxClusterDetailResponse

---

README.md
autoscale/src/main/java/com/sequenceiq/periscope/config/DatabaseConfig.java
autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/Cluster.java
autoscale/src/main/java/com/sequenceiq/periscope/model/RejectedThread.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/AbstractMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/ClusterMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/RejectedThreadMonitor.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/RejectedThreadService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ScalingService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/StackCollectorService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/security/ClusterSecurityService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/security/TlsSecurityService.java
autoscale/src/main/resources/logback.xml
autoscale/src/test/java/com/sequenceiq/periscope/monitor/AbstractMonitorTest.java

The issue was that scheduled Monitoring tasks were updating the records in
the Cluster table without real locking. This caused updates from Cloudbreak UI
to be overwritten peridically, rendering the autoscale feature practically
unusable.
The solution was updating only the lastEvaluated column in the Monitoring tasks.
Added extra logging and modified debug flag to print out Hibernate-generated SQL
and bound parameter values.

ENGESC-6221 Autoscale optimistic locking issue fix

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/CsdLocationFilter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/PreWarmParcelLocationFilter.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/CsdLocationFilterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/PreWarmParcelLocationFilterTest.java

CB-10265: Fixing the Csd and PreWarmPackage location filter when the cluster using only the CDH parcels and the stackRelated parcels are empty

CB-10265: Fixing the Csd and PreWarmPackage location filter

---

flow/src/main/java/com/sequenceiq/flow/repository/FlowLogRepository.java
flow/src/main/java/com/sequenceiq/flow/service/FlowService.java
flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java

detaails:
- Long term: provide different endpoints for diagnostics to follow progress of flows without providing the ids
- at first step, that can be done to query flows by type (only for flow logs for now, can be done for flow chains later)

CB-10788. Enhance flow service to be able to query flow state by flow type.

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudNetwork.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/dns/DnsZoneService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/NetworkService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/NetworkServiceTest.java

Current implementation doesn't filter Azure networks by resource group.
Different resource groups can have networks and subnets with the same name/id.
This could cause an issue in `NetworkService` as it tried to create a map and create multiple entry with the same key.
For a quick fix we switch to `MultiMap` so we can avoid customer issues with as little code change as possible.
The final solution requires a bigger refactor where resource group name also included in filtering.

CB-10766 Handle multiple subnet with same id in FMS NetworkService

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchServiceLoadBalancerTest.java

The error was happening because AwsLaunchService was looking for the public subet
in the "endpointGatewaySubnetId" settings, and wasn't using the "subnetId" setting
for the public load balancer even when that's what should have been used. I added
logic to fall back to "subnetId" if "endpointGatewaySubnetId" isn't set. Also added
an additional check to make sure the load balancer conversion was successful, and
added more logging around the creation.
Tested with a new unit test class.

CB-10794 Datalake creation fails on mow-dev with unable to configure load balancer

---

integration-test/src/main/java/com/sequenceiq/it/config/IntegrationTestConfiguration.java

- Excluding the JaegerAutoConfiguration did not work
- disabling Jaeger through application.yml did not work
- excluding the dependency was quite complicated through gradle
So went with creating a Bean that was missing.
https://github.com/opentracing-contrib/java-spring-jaeger/issues/20

CB-9764 resolved jaeger error message in it by adding bean for it

---

Release.md
autoscale/src/main/java/com/sequenceiq/periscope/domain/Cluster.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/ScalingHandlerUtil.java
autoscale/src/main/java/com/sequenceiq/periscope/repository/ClusterRepository.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/ScalingHandlerUtilTest.java

Similar fix to the ClusterMonitor fix earlier but this time the
scaling handler had to be modified, instead of saving the whole Cluster record
only the lastScalingActivity column is updated.

ENGESC-6221 Autoscale optimistic locking issue second fix

---

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/InstanceMetadataUpdater.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ambari/InstanceMetadataUpdaterTest.java

As part of the upgrade flow we replace the instances with new ones using
the new cloud image. This process is called change image. The images
contain different versions of certain packages which we send a
notification about that they have changed. However, there are many
packages and most of them are not relevant to customers. As part of
this PR this notification is removed.

CB-10269 remove change image notification as it is not really useful

---

authorization-common/src/main/java/com/sequenceiq/authorization/service/DefaultResourceAuthorizationProvider.java

In case of LIST_ASSIGNED_ROLES the authorizationResourceType is null (2nd param) -> LIST_ASSIGNED_ROLES("iam/listAssignedResourceRoles", null),

CB-10580 authorizeDefaultOrElseCompute throws NPE if authorizationResourceType is null

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup

Improve the error message for manual FreeIPA Azure backup. When a
user runs the Azure FreeIPA backup inside a sudo environment which
doesn't replace the keyctl session then it fails due to access
insufficient access.
This was tested with a local deployment on Azure.

CB-10849: Improve error message for manual FreeIPA Azure backup

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup

Use a consistent FreeIPA backup path on Azure.
Old path: cluster-backups/freeipa/FREEIPA_CRN/FQDN/full/backup/
ipa-full-YYYY-MM-DD-hh-mm-ss
New path: cluster-backups/freeipa/FREEIPA_CRN/FQDN/full/
ipa-full-YYYY-MM-DD-hh-mm-ss

CB-10862: Use a consistent FreeIPA backup path on Azure

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup

Add FreeIPA backup status JSON file to improve validation.
This is in addition to the existing text status file.
Tested with a local deployment of cloudbreak.

CB-10863: Add FreeIPA backup status JSON file

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/InternalSdxRepairWithRecipeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxUpgradeTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/client/GcpClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitOperationChecker.java
integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml

**Changes:**
- Enable SDXRepair test on GCP side
- Fix the validation of volumes on GCP side as only the original attached volumes needs to be re-attached and validated
- Fix several E2E test case not to use flow based polling for a cluster status causing unhandled test timeouts on E2E engine side

Gcp e2e sdx repair

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudLoadBalancer.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/TargetGroupPortPair.java
cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/model/TargetGroupPortPairTest.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationStackUtil.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/loadbalancer/AwsListener.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/loadbalancer/AwsLoadBalancer.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/loadbalancer/AwsTargetGroup.java
cloud-aws/src/main/resources/templates/aws-cf-stack.ftl
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchServiceLoadBalancerTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverterTest.java

Replaced the single port being used for load balancer config with TargetGroupPortPair.
This contains a port to direct traffic to, and a port to use for health checks.
Previous LB logic was using health the of nginx port to determine Knox instance health.
The new logic allows different ports to be used for traffic forwarding and health
checks. For the Knox LB, traffic will be forwarded to the nginx port, but health checks
will be done on the Knox port. So if Knox goes down, the LB will be able to detect it
and fail over to the second node.
Tested via unit tests and by creating a data lake and verifying LB configuration and
failover logic.

CB-10740 LB doesn't failover when Knox instance is stopped

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaInstallService.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/target/Glob.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/target/GrainTarget.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/target/HostList.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/target/RoleTarget.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/SyncAllRunner.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStates.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/SyncAllRunnerTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStatesTest.java

`saltutil.sync_all` call was a sync call which doesn't cause any issue if the size is under 200 nodes.
Over 200 nodes it takes too much time and caused timeout. Moving it to async solved the issue. It's handled similarly to highstate call.
Also measurements has been added to salt calls, so we will be able to check which salt calls are taking long time.

CB-10815 Refactor SaltStack sync all call to async

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaInstallService.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/target/Glob.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/target/GrainTarget.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/target/HostList.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/target/RoleTarget.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/SyncAllRunner.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStates.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/checker/SyncAllRunnerTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStatesTest.java

`saltutil.sync_all` call was a sync call which doesn't cause any issue if the size is under 200 nodes.
Over 200 nodes it takes too much time and caused timeout. Moving it to async solved the issue. It's handled similarly to highstate call.
Also measurements has been added to salt calls, so we will be able to check which salt calls are taking long time.

[Cherry pick] CB-10815 Refactor SaltStack sync all call to async

---

core/src/main/resources/defaults/clustertemplates/7.2.7/gcp/streaming-small.json
core/src/main/resources/defaults/clustertemplates/7.2.7/gcp/streaming.json
core/src/main/resources/defaults/clustertemplates/7.2.8/gcp/streaming-small.json
core/src/main/resources/defaults/clustertemplates/7.2.8/gcp/streaming.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

Streams Messaging templates for GCP.
Testing: tested cluster installation manually on local Cloudbreak for 7.2.7 / 7.2.8.

CSP-1216 Streams Messaging templates for GCP

---

freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java

- since permission check is custom for setPassword, other annotations are ignored

CB-10904 remove unused authz annotation from setPassword

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidator.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidatorTest.java

Fixes a case sensitivity issue in the azure object storage validation.

CB-6600 Azure msi validation fails with identity not found

---

redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/common/RedbeamsContext.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/AbstractRedbeamsTerminationAction.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/action/RedbeamsTerminationActions.java

Handle the case when the dbstack is already deleted from the database, but the termination flow has not finished.
After redbeams process restart the flow will continue its execution:
* The termination flow will handle when dbstack is not found in database during flowcontext creation.
* The termination finsished and failed action will handle if dbstack is missing from the context.

CB-10875 Redbeams termination flow fix

---

integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/listener/TestCaseTimeoutListener.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/listener/TestInvocationListener.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java

CB-10911  - In case of E2E test case timeout the created resources are persisted into a JSON file by a new TestNG listener. Increase the timeout for Environment stop/start test case. In case of timeout the test case should be marked failed.
Also some log enhancements has been added to the changes.

CB-10911 E2E test cases fails, created resources are persisted for cleanup job in case of timeout

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformParameters.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformParametersTest.java

If the VMs are placed into AvailabilitySet the maximum host count is 200
which is not adequate for some customers.

CB-10988 Disable default AvailabilitySet assignment

---

integration-test/src/main/java/com/sequenceiq/it/IntegrationTestApp.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/listener/TestCaseTimeoutListener.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/listener/TestInvocationListener.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentStopStartTests.java

E2E Environment stop/start test case is still timing out with no test failure. So the related `TestCaseTimeoutListener.class` was introduced to `xmlSuite.setListeners` application configuration as well.

CB-10911 Introduce TestCaseTimeoutListener to xmlSuite.setListeners

---

core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core-model/src/test/java/com/sequenceiq/cloudbreak/clustertemplate/ClusterTemplateTestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/clustertemplate/ClusterTemplateV4RequestToClusterTemplateConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXAuthenticationToStaAuthenticationConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXClusterToClusterConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXDatabaseRequestToStackDatabaseRequestConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXImageToImageSettingsConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4Converter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/AbstractJsonConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/clustertemplate/ClusterTemplateV4RequestToClusterTemplateConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/publicendpoint/dns/BaseDnsEntryServiceTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXAuthenticationToStaAuthenticationConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXClusterToClusterConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXDatabaseRequestToStackDatabaseRequestConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXImageToImageSettingsConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXParameterConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceGroupV1ToInstanceGroupV4ConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4ConverterTest.java
resource_names_testWhenEnvIsStoppedUnableToCreateDistroX.json

Increasing line and decision test coverage for:
- ClusterTemplateV4RequestToClusterTemplateConverter
- DistroXAuthenticationToStaAuthenticationConverter
- DistroXClusterToClusterConverter
- DistroXDatabaseRequestToStackDatabaseRequestConverter
- DistroXImageToImageSettingsConverter
- InstanceGroupV1ToInstanceGroupV4Converter
- DistroXParameterConverter
- StackV4RequestToStackConverter
- DistroXV1RequestToStackV4RequestConverter
- ClusterTemplateV4RequestToClusterTemplateConverter
- NetworkV1ToNetworkV4Converter
- TelemetryConverter

CB-10359 - increase cluster template related converter test coverage vol.1

---

orchestrator-salt/src/main/resources/salt/salt/metering/settings.sls

it only uses version 1 or 2, not any newer one, version 3 is already used from 2020 dec 16, that means newer images uses the older metering streams instead of the new ones

CB-11020. Metering heartbeat versioning is broken.

---

core/src/main/resources/schema/app/20210203155101_CB-10578_Populate_targetgroup_loadbalancer_table.sql

Copies data from the targetgroup table's id and loadbalancer_id columns into the new
targetgroup_loadbalancer table. This does not overwrite any rows already in the
targetgroup_loadbalancer table.

CB-10578 Populate new targetgroup_loadbalancer table from CB-10095

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

**Describe the change you are making here!**
This change increases the replayBufferSize value from 64 to 128 for Ranger service. This change affects topologies cdp-proxy.xml and cdp-proxy-api.xml.

CB-11025 - [Knox] Increase replayBufferSize value from 64 to 128 for Ranger service

---

common-model/src/main/java/com/sequenceiq/common/api/telemetry/doc/DiagnosticsModelDescription.java
common/src/main/java/com/sequenceiq/cloudbreak/telemetry/converter/DiagnosticsDataToParameterConverter.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/diagnostics/model/DiagnosticsCollectionRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/DiagnosticsV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/handler/DiagnosticsInitHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/DiagnosticsTriggerService.java
datalake/src/main/java/com/sequenceiq/datalake/converter/DiagnosticsParamsConverter.java
datalake/src/main/java/com/sequenceiq/datalake/flow/diagnostics/SdxDiagnosticsActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/handler/DiagnosticsInitHandler.java
orchestrator-salt/src/main/resources/salt-common/salt/filecollector/init.sls
orchestrator-salt/src/main/resources/salt-common/salt/filecollector/template/extra-dbus-headers.yaml.j2
orchestrator-salt/src/main/resources/salt-common/salt/filecollector/upload.sls

details:
- If newer cdp version is used (0.3.6) - add a new -e (extra databus header file) option to databus upload
- all the new headers will be defined in a file that is provided by that -e option
- in order to fill the required headers - although many of them are available by salt configs - we need to pass them into diagnostics params (like UUID)
- UUID: new request param (only for internal CB API - v4)
- UUID will be the flow ID (for datalake it will be the SDX flow ID, not the core one)
- remove some unused model descriptions

CB-10942. Add custom UDX headers for diagnostocs support output.

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/connector/resource/AzureDatabaseResourceServiceTest.java

Before this change, the CB checked only the existence of the resource group of the DB.
In case of single RG it's not a proper approach. In this commit I've changed the method to get the DB server from the Azure directly.

CB-9961: Fix Azure redbeams sync to work with single RG

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/common-install.sls

When pki-tomcatd@pki-tomcat starts, it always rewrites the config file
/var/lib/pki/pki-tomcat/ca/conf/CS.cfg. It even does this if the file
does not change. There is a delay of about 8 seconds between when the
service command returns and when the file is rewritten. This can cause
the file to become corrupted if any other process modifies the file
during this operation. It is recommended that the CA be shutdown
before editing this file and then the CA can be started again. This
fix was done.
This method was tested with a loop that modified the file many times
between service restarts. Without the fix, the CA failed almost every
time. With this fix, I was unable to get it to fail.

CB-11040: Fix race condition which intermittently corrupts CS.cfg

---

integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/environment-stopstart-tests.yaml
integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml

Our API E2E testing ([CB-10912](https://jira.cloudera.com/browse/CB-10912)) is struggling with timeout issues at `com.sequenceiq.it.cloudbreak.testcase.e2e.environment.EnvironmentStopStartTests`, because of this test takes at least 90 minutes with optimal circumstances. So our default 100 minutes test timeout is not appropriate for this test case.
We need to create a separate Jenkins job for this long running test with a custom test timeout.

CB-11056 Create separate test suite for EnvironmentStopStartTests

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/exception/RolledbackResourcesException.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsAttachmentResourceBuilder.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/upscale/AzureUpscaleService.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilderTest.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/CloudFailureHandler.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceService.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/PreserveResourceException.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceDeleteThread.java
common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/TemplateDecorator.java

In some cases, the managed disks were not rolled back properly in case of a failed infrastructure update. Sometimes some disks are not in "attached" state, but they are attached on Azure. In this fix, we will ask for attachment info from Azure instead of our state information. Also added a retry mechanism to managed disk deletion. Code is extended with more logs.

CB-11038 Attached disks leaked during a rollback that had been triggered by an upscale failure on Azure

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/auth/PasswordExpiredException.java

Fix error message when the password has expired.

CB-11063: Fix error message when the FreeIPA password has expired

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaHealthCheckClient.java

Add more logging when the FreeIPA health check fails.

CB-9926: Add more logging when the FreeIPA health check fails.

---

structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/CDPStructuredFlowEventToCDPOperationDetailsConverter.java
structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/EnvironmentUseCaseMapper.java
structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/CDPStructuredFlowEventToCDPOperationDetailsConverterTest.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredFlowEventToCDPOperationDetailsConverter.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredFlowEventToClusterShapeConverter.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredFlowEventToVersionDetailsConverter.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/log/cluster/ClusterRequestedLogger.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterUseCaseMapper.java
structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredFlowEventToCDPOperationDetailsConverterTest.java
structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredFlowEventToClusterShapeConverterTest.java
structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredFlowEventToVersionDetailsConverterTest.java
usage-collection/src/generated/main/java/com/cloudera/thunderhead/service/common/usage/UsageProto.java
usage-collection/src/main/proto/usage.proto

CB-11067 Support stop, start, upscale, downscale and upgrade reporting to EDH. There are some incompatible changes in the usage.proto, but since the usage.proto was not promoted to thunderhead yet, this shaould not cause any problem, but it will reduce the maintenance cost in the future. (HEAD -> edh-improve, origin/edh-improve) [Attila Kanto]
CB-11046 Provide more details about which flow step has failed. This is particularly important in case of Datahub and Datalake since they are created in flowchains and it can have multiple exists. [Attila Kanto]

Sending a more events to EDH

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSubnetIgwExplorer.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSubnetIgwExplorerTest.java

This change needs to be back-ported to 2.37 line of CB as other customers started to deal with the same issue which has been fixed by this commit. For example [ENGESC-6706](https://jira.cloudera.com/browse/ENGESC-6706).

CB-10901 Subnet should not be public by the main route table in case of a route table is associated explicitly.

---

cloud-aws/src/main/resources/definitions/aws-cb-policy.json

To put tags on the s3 buckets the PutBucketTagging permission should
be added to the user policy.

DWX-6635 CDW s3 bucket tags

---

environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentStatus.java

At `com.sequenceiq.it.cloudbreak.testcase.e2e.environment.EnvironmentStopStartTests.testCreateStopStartEnvironment` the stopped environment cannot get into `AVAILABLE` state. However test is waiting for this state even the `START_FREEIPA_FAILED` environment status draws up.
So we need to update the related failed statuses set at `EnvironmentStatus` class.

CB-11078 Environment FAILED_STATUSES set does not contains all the related EnvironmentStatus

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltService.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltConnector.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrap.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionAcceptor.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltBootstrapTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionAcceptorTest.java

After https://github.com/hortonworks/cloudbreak/pull/8408/commits/451ff5441bf2924d501af6efc7a6db168accd3f0
every minion fingerprint has to be accepted on the master for SaltStack to be functional.
This was done only for the primary gateway which caused error in multi-master setup like FreeIPA HA.
The solution is we create `SaltConnector` to all the gateways during bootstrap and iterate over them in `MinionAcceptor`
Tested with FreeIPA HA, with validating salt keys:
```
(salt_3000.5) [root@ipaserver0 ~]# salt-key -L
Accepted Keys:
ipaserver0.test.xcu2-8y8x.wl.cloudera.site
ipaserver1.test.xcu2-8y8x.wl.cloudera.site
ipaserver2.test.xcu2-8y8x.wl.cloudera.site
(salt_3000.5) [root@ipaserver1 ~]# salt-key -L
Accepted Keys:
ipaserver0.test.xcu2-8y8x.wl.cloudera.site …
```

CB-11004 Accept minion fingerprints on all master

---

freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverter.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverterTest.java

1. Found this during FreeIPA HA full repair, although it could have happened on an install too.
2. Sometimes it happens that ipaserver0 was assigned ipaserver1 hostname.
3. This breaks the replica install with this bug https://bugzilla.redhat.com/show_bug.cgi?id=1364139
4. There is no fix for the above bug in a VM install.
5. Nonetheless this is a nasty bug, that needs fixing anyway. Elsewhere in the code, there is an assumption that server 0 gets ipaserver0 hostname.

CB-10672 Fix FreeIPA HA (repair) in GCP (take 4)

---

integration-test/README.md
integration-test/scripts/fetch-secrets.sh
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ums/UmsTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/AuthUserKeys.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CreateDhWithDatahubCreator.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DataStewardTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DatalakeDatahubCreateAuthTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvStopStartWithEnvAdmin.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvironmentCreateTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/RecipeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/AbstractMockTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/AuthorizationTestUtil.java
integration-test/src/main/resources/testsuites/v4/mock/real-ums-mock-tests.yaml

CB-10710 Create Real UMS test for the DataSteward resource role
And minor refactor regarding authorization error message validation in Real UMS tests.
Testcase scenario:
- Create new environment and datalake
- Assign the Datasteward actor to the environment
- Call allowed and not allowed APIs

CB-10710 Create Real UMS test for the DataSteward resource role

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerUpdateService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java
environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentOpDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentLoadBalancerUpdateRequest.java
environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentLoadBalancerDto.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentLoadBalancerService.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java

The API changes that will be used for the new in-place upgrade for the new load balancer
and endpoint gateway features. The logic will be triggered via an API call to the
environment service. The environment service will then call the internal stack API
to update the laod balancer for each applicable stack.
As part of the request, the endpoint gateway can be enabled, and public subnets to use for the
gateway provided. Load balancers will be created based on the current entitlements (including
creating data lake load balancers if that entitlement is enabled), and whether or not the endpoint
gateway is enabled for the environment.
This change adds the new API calls and the services they trigger, and stubs out the logic that will
be implemented in subsequent PRs. This change will be broken …

CB-10612 API changes for In place enablement of semi-private networks

---

cloud-common/src/main/java/com/sequenceiq/cloudbreak/util/DeviceNameGenerator.java
cloud-common/src/test/java/com/sequenceiq/cloudbreak/util/DeviceNameGeneratorTest.java

CB creates the attached volumes and tells AWS where to mount those volumes.
However, our device name generation is incorrect as we're iterating over on
a list with multiple threads and it can happen that multiple threads get the
same device name. This will result in a conflict on AWS.
Infrastructure creation failed. Reason: Failed to create resources for instance with id: '1', message: 'com.amazonaws.services.ec2.model.AmazonEC2Exception: Invalid value '/dev/xvdk' for unixDevice. Attachment point /dev/xvdk is already in use (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: ..)'
To fix this problem I made the name generation thread safe by using an atomic counter.

CB-11138 fix Volume device name generation on AWS

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java
autoscale/src/main/java/com/sequenceiq/periscope/service/AutoScalingException.java

CB-11144 ScalingRequest.scaleup() will be executed without any error, in case if error has happened on cloudbreak side
* Check the putstack rest response from cloudbreak in ScalingRequest.scaleup() and if its statuscode is not in the SUCCESSFUL family, throws an AutoScalingException
* New entry will be created about the error in the Periscope History and notification will be sent

CB-11144 ScalingRequest.scaleup() will be executed without any error, in case if error has happened on cloudbreak side

---

autoscale/src/main/java/com/sequenceiq/periscope/service/ha/LeaderElectionService.java
autoscale/src/main/resources/application.yml
autoscale/src/test/java/com/sequenceiq/periscope/service/ha/LeaderElectionServiceTest.java

CB-11145 StackCollectorService.collectStackDetails() is expensive if there are lots of clusters in periscope
* Set the stack collection period as a configurable parameter
* Increase the default value of it to 60sec

CB-11145 StackCollectorService.collectStackDetails() is expensive if there are lots of clusters in periscope

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/model/stack/instance/InstanceGroupAdjustmentJson.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/AutoscaleController.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java

Example of new log lines:
`2021-02-15 09:40:00,304 [http-nio-9091-exec-4] putStack:70 DEBUG c.s.c.c.AutoscaleController - [owner:undefined] [type:Autoscale] [id:20] [name:undefined] [flow:] [tracking:ab1a209f-a098-4bf2-8e23-12420277b844] Autoscale requested stack update for stack id '20', with status request 'null' and adjustment: 'InstanceGroupAdjustmentJson{instanceGroup='worker', scalingAdjustment=3}'`
`2021-02-15 09:40:00,617 [http-nio-9091-exec-4] put:291 DEBUG c.s.c.s.StackCommonService - [owner:7f8b90b0-3f3a-4138-b9d5-7bbd7cae5ee9] [type:STACK] [id:20] [name:tb-292test-2] [flow:] [tracking:ab1a209f-a098-4bf2-8e23-12420277b844] Stack update has been initiated name: 'tb-292test-2' with status: 'null' and adjustment: 'InstanceGroupAdjustmentJson{instanceGroup='worker', …

CB-11144 additional logs for autoscale related update endpoint

---

autoscale/src/main/java/com/sequenceiq/periscope/config/AppConfig.java

CB-11164 Increase periscope default threadpool size to 500

CB-11164 Increase periscope default threadpool size to 500

---

integration-test/scripts/docker-compose.sh
integration-test/scripts/swagger-check.sh

Cloudbreak real UMS tests are failing, because of:
```
ERROR: for cbreak_vault_1  Cannot start service vault: endpoint with name cbreak_vault_1 already exists in network cbreak_default
```
even the `docker ps -a` shows any running containers and `docker images` shows no pulled image on the Jenkins node, the `docker network rm cbreak_default` throws error:
```
Error response from daemon: error while removing network: network cbreak_default id 790629475ad0b286dd0ce685371b65e4157e4ca0d4b466c276d1fea8ad7e4fd3 has active endpoints
```
So we should manage stuck containers for services not defined in the Compose file.

CB-11165 Remove test containers for services not defined in the IT Compose file

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java

This disables the change primary gateway flow for the Datalake since CM HA is not yet implemented.

CB-10796 Disable changing of primary gateway for SDX.

---

integration-test/.gitignore
integration-test/docker-compose_template.yml

```find / -name "*.hprof"```
takes too long at [cloudbreak-pull-request-builder-integration-test](http://ci-cloudbreak.eng.hortonworks.com/job/cloudbreak-pull-request-builder-integration-test/ws/integration-test/). So we need to specify a separate directory where Java VM dumps are created in case of out-of-memory conditions.

CB-11183 Specify directory where Java VM dumps are created on out-of-memory conditions

---

datalake/src/main/resources/application.yml

Changed to `8989` to match the one present in CBD. It is overriden in mow deployments

CB-11132 Change datalake dr service default port

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitOperationChecker.java

Fixed tests that passed when a cluster was in a failed state. The
e2e integration tests which validated the cluster was in an available
state used to pass if the cluster entered the failed state at certain
places in the polling cycle. Specifically, the early exit criteria was
met when the cluster was in the failed state. This early exit happened
right after the sleep in the poll cycle so it was more likely
to exit the polling loop without the failed check being processed.
This was fixed by removing the early exit in the case where the
cluster enters a failed state.

CB-11121: Fix tests that passed when a cluster was in a failed state

---

environment/src/main/resources/application.yml

You can establish a private connection between your VPC and Amazon RDS API
endpoints by creating an interface VPC endpoint. AWS PrivateLink enables you
to privately access Amazon RDS API operations without an internet gateway,
NAT device, VPN connection, or AWS Direct Connect connection. Instances in
your VPC don't need public IP addresses to communicate with Amazon RDS API
endpoints to launch, modify, or terminate DB instances. Your instances also
don't need public IP addresses to use any of the available RDS API operations.
Traffic between your VPC and Amazon RDS doesn't leave the Amazon network.

CB-10614 add RDS to the VPC interface endpoint list

---

datalake/src/main/resources/duties/7.2.7/gcp/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.8/gcp/medium_duty_ha.json
datalake/src/main/resources/duties/7.2.9/gcp/medium_duty_ha.json

1. This shape has been changed in the other clouds.
2. The instance types and groups are different now.
3. Updated the definitions according to AWS/Azure.

CB-10461 GCP Medium duty datalake definition updated to match AWS/Azure

---

core/src/main/resources/application.yml

CB-11227 adding Standard_E4a_v4 which comes with 4 vcores, 32 gb memory

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/upgrade/UpgradeV4Response.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterDBValidationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeService.java

If the replaceVms value is not specified in the request there is some logic to determine it.
Instead of depending the one in the request which can be null, we use the one calculated for the response.

CB-11261 Use calculated `replaceVms` value instead of the one in request

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/Cluster.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/IdBrokerConverterUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/ClusterV4RequestToClusterConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java

IDBroker was fetched in every stack get query. (with its relations like
cluster etc -> hibernate created a join query with these relations)
Explanation: It is because Stack <--> Cluster is a OneToOne relation
and Cluster <--> IdBroker is also a OneToOne relation. A OneToOne relation
can not be lazy in the case if the owner of the relation is the other entity.
In this example the Idbroker entity has the cluster id column.
Hibernate can not guess if Cluster has an IDBroker or not because this
information is in another table, so IDBroker table will be fetched.
With this fix IdBroker entity can be fetched only with it's service.
https://stackoverflow.com/questions/1444227/how-can-i-make-a-jpa-onetoone-relation-lazy
"Unconstrained (nullable) one-to-one association is the only one that
can not …

CB-11105 remove idbroker from cluster

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientExceptionUtil.java
freeipa-client/src/test/java/com/sequenceiq/freeipa/client/FreeIpaClientExceptionUtilV1Test.java

Add retries for IOExceptions in the FreeIPA client.
This was tested with unit tests and with a local deployment of
cloudbreak.

CB-11303: Add retries for IOExceptions in the FreeIPA client

---

cloud-aws/src/main/resources/definitions/aws-cb-policy.json

A ECRAccessRead policy will enable Cloudbreak client to describe repositories. CDP has a new feature which requires customers to define custom ECR repositories and Cloudbreak client will need to have rights to be able to describe repositories if the custome repo is defined on the same account.

DWX-6365 Adding ECR repo access to cloudbreak client 

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaFlowManager.java

CB-11312. Freeipa: flow should return 409 instead of 500 if a flow already exists

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceGroup.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceMetaData.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/InstanceMetaDataToCloudInstanceConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/ClusterCreationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/AbstractInstanceTerminationAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/action/StackCreationActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/stop/StackStopActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/sync/StackSyncActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/EmbeddedDatabaseService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackInstanceStatusChecker.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackViewService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderConnectorAdapter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/connector/adapter/ServiceProviderMetadataAdapter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/repair/UnhealthyInstancesFinalizer.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/InstanceMetaDataToCloudInstanceConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJobTest.java
core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusIntegrationTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackInstanceStatusCheckerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/repair/UnhealthyInstancesFinalizerTest.java

..to optimize InstanceMetaDataRepository.findNotTerminatedForStack query
findNotTerminatedForStack query has this where condition:
"WHERE i.instanceGroup.stack.id= :stackId"
Because of this condition hibernate does a fetch query for stack object.
To avoid this behavior lazy is added to stack field in InstanceGroup.
Lazy annotation added to Stack, SecurityGroup and Template for InstanceGroup.

CB-11105 use stackview for statuschecker mdc context; add lazy annotation for some instancegroup fields..

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureInstanceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/BatchInstanceActionFailedException.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtilsTest.java

- Check actual status of instances and deallocate only those that are not STOPPED
- Collect deallocation results properly
- Retry deallocation if something went wrong (exception raised)
- Improve error logging

CB-8476 Azure instance deallocation improvement

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/AutoscaleController.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java

The removed permission check only affects the cb autoscale scaling api call and only in the case when the call originated in the periscope service.

CB-11290 Auto upscale failing because of user permission issues on 2.9.2

---

ccm-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/clusterconnectivitymanagementv2/ClusterConnectivityManagementV2Grpc.java
ccm-connector/src/generated/main/java/com/cloudera/thunderhead/service/clusterconnectivitymanagementv2/ClusterConnectivityManagementV2Proto.java
ccm-connector/src/main/proto/clusterconnectivitymanagementv2.proto

With CDPAM-1289, we enhanced CCMv2 to optionally accept `environmentCrn` during agent registration. Agents registered with an `environmentCrn` would now be reused by experiences to route their requests to Kubernetes style workloads deployed inside the same environment.
This is 1 of 2 changes and would update the proto file to reflect more recent changes in thunderhead and also add the generated gRPC client.

CDPAM-1344: Cloudbreak needs to add environmentCrn to CCMv2 registration for DLs (1/2)

---

core/src/main/resources/defaults/vm-logs.json
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/generate_agent_tokens.sh.j2

With this commit if the copy fails we would only log it.
This is necessary because during downscale highstate is invoked thus agent token generation and copy is invoked.
If one of the instances is down, which doesn't have the token the downscale would.
With this change it won't block downscale anymore.
During upscale it shouldn't cause any issues, as agents without token won't start and it means the failure would still happen in the orchestration state a bit later.
The change includes turning off `set -e` during salt copy and evaluate the return code later. In some cases the `false` text is not included in the return value so we have to check the return code too.
Another change is adding the token generation log to the diagnostic bundle as if the output is too big, it won't be in the salt …

CB-11328 Agen token copy fails when a minion is unavailable

---

core/src/main/resources/defaults/vm-logs.json
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/generate_agent_tokens.sh.j2

With this commit if the copy fails we would only log it.
This is necessary because during downscale highstate is invoked thus agent token generation and copy is invoked.
If one of the instances is down, which doesn't have the token, the downscale would fail.
With this change it won't block downscale anymore.
During upscale it shouldn't cause any issues, as agents without token won't start and it means the failure would still happen in the orchestration state a bit later.
The change includes turning off `set -e` during salt copy and evaluate the return code later. In some cases the `false` text is not included in the return value so we have to check the return code too.
Another change is adding the token generation log to the diagnostic bundle as if the output is too big, it won't be in …

Cherry pick from master: CB-11328 Agen token copy fails when a minion is unavailable

---

ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/ccmv2/CcmV2ManagementClient.java
ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/ccmv2/GrpcCcmV2Client.java
ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2ParameterSupplier.java
ccm-connector/src/test/java/com/sequenceiq/cloudbreak/ccmimpl/ccmv2/CcmV2ManagementClientTest.java
ccm-connector/src/test/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2ParameterSupplierTest.java
common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/CcmV2ParameterSupplier.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/userdata/CcmUserDataService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/userdata/CcmUserDataServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/image/userdata/CcmUserDataService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/image/userdata/CcmUserDataServiceTest.java

With CDPAM-1289, we enhanced CCMv2 to optionally accept environmentCrn during agent registration. Agents registered with an environmentCrn would now be reused by experiences to route their requests to Kubernetes style workloads deployed inside the same environment.
This is 2 of 2 changes and would update the calling code to conditionally add environmentCrn during CCMv2 registration **for FreeIPA only**.

CDPAM-1344: Cloudbreak needs to add environmentCrn to CCMv2 registration for FreeIPA (2/2)

---

core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-engineering.bp

tez.runtime.pipelined.sorter.lazy-allocate.memory is set to true by default and the screenshot from tez-site.xml is :
and the CM UI having the value in tez gateway configs:

CDPD-19363:set tez.runtime.pipelined.sorter.lazy-allocate.memory to true by default in DH

---

cloud-azure/build.gradle

Add missing dependency on okhttp-urlconnection which fixes an
intermittent issue.
https://github.com/hortonworks/cloudbreak/blob/22ee0f6c7b3c77f488ee845c3f488eb8af3bef41/cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientCredentials.java#L21 okhttp3.JavaNetAuthenticator depends on okhttp-urlconnection

CB-11361: Add missing dependency on okhttp-urlconnection

---

core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/GatewayPublicEndpointManagementService.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/publicendpoint/GatewayPublicEndpointManagementServiceTest.java

Adds a new filter for LB endpoint names in GatewayPublicEndpointManagementService that will ignore
any null or empty endpoint values. Also adds a supported platform condition in LoadBalancerConfigService,
to prevent unexpeced results on platforms that haven't been fully implemented yet.

CB-11356 Handle LB with missing endpoint

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/AbstractEnvironmentAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentChangeAuthenticationAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentChangeSecurityAccessAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentDeleteAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentDeleteByNameAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentDeleteMultipleByCrnsAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentDeleteMultipleByNamesAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/CloudbreakActor.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/CloudbreakUserCache.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/RunningParameter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java

Integration tests' flow polling is failing in case of `ums-users/api-credentials.json` is present at `integration-test` project. This is a special case, when the real UMS user store has been initialised but we do not want to run UMS or AuthZ test suits. However flow polling is happening with admin user. So mistakenly UMS admin has been provided for `getAdminMicroserviceClient`.
We agreed we should introduce the needed validation for `accountId` in `getAdminByAccountId` and an additional parameter for authorisation tests only.
**_NOTES:_**
- `additional parameter for authorization tests only` was implemented different way: Instead of introducing a separate test suite parameter I applied a new `CloudbreakUserCache` class parameter as `useUmsStore`. This new parameter is going to be set when …

CB-11188 Optionally initialize real UMS users by parameter

---

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/azure/AzureEnvironmentParameters.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/azure/AzureResourceEncryptionParameters.java

CB-11152: Add keyUrl CLI param in Azure environment creation. 
This param will be used to create Disk Encryption Set which enables ServerSideEncryption with CustomerManagedKey for Azure resources. For now, SSE with CMK will be implemented for Azure Managed disks for datahub clusters.
More details are captured in CB-9920
On successful build - contents of environment json looks like -
```
"AzureEnvironmentV1Parameters" : {
"type" : "object",
"properties" : {
"resourceGroup" : {
"description" : "Azure resource group parameters.",
"$ref" : "#/definitions/AzureResourceGroupV1Parameters"
},
"resourceEncryptionParameters" : {
"description" : "Parameter: keyUrl - to encrypt Azure resources.",
"$ref" : "#/definitions/AzureResourceEncryptionV1Parameters"
}
}
},
"AzureResourceEncryptionV1Parameters" …
```

CB-11152: Add keyUrl CLI param in Azure environment creation.

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Quick fix for [CB-11327](https://jira.cloudera.com/browse/CB-11327).
Add an additional keytab to the look up chain.
Tested by running medium duty backup/restore locally.
Verified that I got successes back from the script:
```
+ doLog 'INFO Succesfully restored hive'
...
+ doLog 'INFO Succesfully restored ranger'
...
+ doLog 'INFO Completed restore.'
```
And `/var/log/dl_postgres_restore.log` confirms that restore was successful.
See also, [the second PR](https://github.com/hortonworks/cloudbreak/pull/10157), which is not a hack.

CB-11327: Add Atlas keytabs as a fallback for medium duty.

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Closes [CB-11327](https://jira.cloudera.com/browse/CB-11327).
Look for Atlas keytabs on backup and restore scripts.
This is in addition to the other keytabs that have already been checked.
Tested locally by running backup and restore using a medium duty datalake.

CB-11372: Add Atlas keytabs as a fallback for medium duty.

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudSubnet.java
cloud-aws/build.gradle
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsFirewall.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResources.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSubnetIgwExplorer.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/client/AmazonNetworkFirewallClient.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLoadBalancerLaunchService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/util/AwsPageCollector.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSubnetIgwExplorerTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchServiceLoadBalancerTest.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/NetworkCreationHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/service/network/NetworkMetadataValidationService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/network/NetworkMetadataValidationServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/network/NetworkTest.java

Adds additional pass conditions to the logic that validates the AWS subnets provided for the public endpoint
gateway load balancer. Previously a subnet could only be used if it had an attached internet gateway. Now
it can be used if it passes one of the following three conditions:
1. The subnet is tagged with "cdp-public-endpoint-gateway-lb" : "override".
2. The subnet has an internet gateway attached.
3. The subnet is routed through an AWS network firewall, and that firewall has an attached IGW.
Tested with unit tests and by enabling the feature with subnets with the override tag, and subnets routed
though a public network firewall.

CB-11070 CDP PC missing firewall for egress/ingress

---

core/src/main/resources/externaldatabase/aws/database-template.json

The size of external DB for all clouds today for Datahub clusters today is 1000GB which is too high and costly for customer since most of that is going in vacuum. In order to arrive at better defaults ,changing the External DB size to 100G. Will create a separate PR for Azure and GCP as well.
Before the change: 
Post the change:

Decrease the size of DB for DH in AWS to 100G

---

cloud-aws/src/main/resources/definitions/aws-cb-policy.json

Updating ECRAccessRead policy:
Adding missing DescribeRepositories action: to be able to describe repositories on validation
Adding Describe images action to be able to describe images and see their version matches
Adding GetAuthorizationToken to be able to obtain a temporary token

DWX-6365 Fixing ECR repository access

---

orchestrator-salt/src/main/resources/salt/salt/postgresql/init.sls

CB-11406 [sdx-upgrade][azure/AWS][710->728] unable to install 710 datahub
The fix is to use postgres unit file instead of fix postgres10 one during postgres init.

CB-11406 [sdx-upgrade][azure/AWS][710->728] unable to install 710 datahub

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionAcceptor.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionAcceptorTest.java

When a salt master in SDX is being repaired, it's old minion fingerprint is
still on the other salt master and is in a denied state.  So we delete that
to allow the new minion key to be accepted.

CB-11142 SDX HA Minion not being accepted by master

---

freeipa/src/main/java/com/sequenceiq/freeipa/converter/cloud/StackToCloudStackConverter.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/cloud/StackToCloudStackConverterTest.java

The original design was always taking instanceprofile from telemetry for freeipa so that user don't mistakenly set it in backup, because there is only one instanceprofile. Now We want to use the instanceprofile from backup if telemetry is null to include below test case.

CB-11322 Set freeipa instanceprofile using backup when telemetry is null

---

cloud-azure/src/main/resources/templates/arm-v2.ftl
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java

There was an issue with disk naming as it was calculated by concatenating
the instance's auto-increment id and the disk's auto-incrementing id
without a separator character.
This caused instance no. 1 disk 10 and instance no 11 disk id 0 having a
name collision.
The fix is to put a separator character '-' in between, but unfortunately
the clusters created with the previous unfixed template has persisted
the wrong template into the 'component' table for STACK_TYPE component type.
These clusters will need a manual data fix by replacing the template with
a fixed version.

ENGESC-7200 Azure disk naming fix

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/common-install.sls

You can send an http TRACE request to the FreeIPA server and it might
expose sensitive information. It is used mainly for debugging
purposes, but in general it should be disabled. It's fairly easy to
disable it with Apache http server.
To test you can use this command:
```
curl -kvL -X TRACE https://localhost:443
```
The response before this change is:
```
TRACE /ipa/ui HTTP/1.1
User-Agent: curl/7.29.0
Host: ipaserver0.test-env.xcu2-8y8x.wl.cloudera.site
Accept: */*
HTTP/1.1 200 OK
Date: Mon, 08 Mar 2021 09:21:48 GMT
Server: Apache/2.4.6 (CentOS) mod_auth_gssapi/1.5.1 mod_nss/1.0.14 NSS/3.28.4 mod_wsgi/3.4 Python/2.7.5
Transfer-Encoding: chunked
Content-Type: message/http
```
and after it's disabled:
```
TRACE /ipa/ui HTTP/1.1
User-Agent: curl/7.29.0
Host: …
```

CB-10259 disable http TRACE method on the IPA server

---

core/src/main/resources/externaldatabase/azure/database-template.json
core/src/main/resources/externaldatabase/gcp/database-template.json

Changes tested in Azure and the screenshots below:
Before the change with 1000GB:
post the change reduced to 100G:

CB-11385:Decrease the size of DB for Datahubs for GCP and AZURE

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

This is related to https://jira.cloudera.com/browse/CB-11437
Looks like Atlas POST requests are failing because the buffer size was exceeded. This fix will increase the buffer size and fix the issue. 
This has been tested on a local cluster in mow-int.

CB-11437 - Fix an issue with Atlas POST requests exceeding buffer size

---

core/src/main/resources/defaults/clustertemplates/7.2.10/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.10/aws/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.8/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.8/aws/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.9/aws/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.9/aws/dataengineering.json

The default disk types that are launched with cluster templates are changed to gp2. Screenshot below for the same:
The change is made for 7.2.8,7.2.9.7.2.10 for DE and DE-spark3 templates. I see the changes were already being made for DE-HA templates as part of this PR: https://github.com/hortonworks/cloudbreak/pull/10205/files

DISTX-575:Use gp2 storages for AWS

---

core/src/main/resources/defaults/clustertemplates/7.2.10/gcp/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.7/gcp/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.8/gcp/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.9/gcp/dataengineering-ha.json

1. I missed this setting during the definition creation.
2. This is already used by flow management HD template in GCP.

CB-11231 GCP : Adding external database for dataengineering ha

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

This is related to https://jira.cloudera.com/browse/CB-11368
This fix will increase the buffer size for HIVE and RANGERUI services.

CB-11368 - [Knox] Add replayBufferSize to HIVE and RANGERUI services

---

core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentLoadBalancerService.java

Jira: https://jira.cloudera.com/browse/CB-10577
This is meant to remove the check for the CDP_MEDIUM_DUTY_SDX and CDP_DATA_LAKE_LOAD_BALANCER entitlements during the datalake provisioning process if the cloud provider is AWS, it still checks for these entitlements otherwise.
Specifically, this will result in all AWS datalake provisions being set up with an accompanying loadbalancer, and globally enable medium duty setups for everyone.
I went through and added some unit tests to make sure this is working as expected.

CB-10577: Removed medium duty and loadbalancer entitlement checks for AWS.

---

integration-test/src/main/resources/testsuites/v4/mock/real-ums-mock-tests.yaml

Test ApplicationContext cannot be started at [cloudbreak-real-ums-authz-tests](http://ci-cloudbreak.eng.hortonworks.com/job/cloudbreak-real-ums-authz-tests/), because of: `Cannot find class in classpath: com.sequenceiq.it.cloudbreak.testcase.authorization.listfiltering.ImageCatalogListFiltering`.
ImageCatalogListFiltering reference is present at the test suite: [cloudbreak/integration-test/src/main/resources/testsuites/v4/mock/real-ums-mock-tests.yaml](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/resources/testsuites/v4/mock/real-ums-mock-tests.yaml). However the correct file name is [cloudbreak/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/listfiltering/ImageCatalogListFilteringTest.java](https://github.com/hortonwork …

CB-11527 Fix cannot find class listfiltering.ImageCatalogListFiltering

---

autoscale/src/main/resources/application.yml
core/src/main/resources/application.yml
datalake/src/main/resources/application.yml
environment/src/main/resources/application.yml
freeipa/src/main/resources/application.yml
redbeams/src/main/resources/application.yml

Increase spring graceful shutdown timeout from the default 30 sec to 60 sec.

CB-11491 Optimize springboot and kubernetes graceful shutdown timeouts

---

core/src/main/resources/defaults/blueprints/7.2.9/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-sdx.bp

HBase data in the datalake is stored on HDFS. However, by default
the HDFS data is readable by the world! This presents a security risk.
This change overrides the HBase umask value to 007 which sets the
HBase file permissions to rwx------ by default.

CB-11528 Set HBase umask overrides in the data lake to 007

---

autoscale-api/src/main/java/com/sequenceiq/periscope/common/MessageCode.java
autoscale-api/src/main/resources/messages/messages.properties
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandler.java
autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandlerTest.java

Autoscaling trigger failure should be made available in history events.

DISTX-585 Autoscaling trigger failure should be made available in history events.

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpCloudKMSFactory.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpComputeFactory.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpHttpClientConfig.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpIamFactory.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpSQLAdminFactory.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpStorageFactory.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/tracing/GcpTracingInterceptor.java

- changed the httptransport implementation to apache
- this way interceptors could be added to the http client
- extracting gcp api operations from stack trace - there is no other way to properly identify it
- added measurement to stack walking to see if it's too slow. it takes 0-6 ms.

CB-9030 - tracing gcp api calls.

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/common-install.sls

The default value of entry_cache_timeout is 90 mins and once a
user is cached it may not be able to SSH to the FreeIPA node with
the provided SSH key that is stored in UMS. This config is already
set to 30 seconds on the Data Lake and Data Hub clusters. As part
of this PR I'm making it consistent with the other clusters. It
should not cause any performance issues since users are not expected
to SSH to the FreeIPA instances that often. Mostly never.
After this change the sssd.conf will look like this:
```
[domain/test-env.xcu2-8y8x.wl.cloudera.site]
cache_credentials = True
entry_cache_timeout = 30
krb5_store_password_if_offline = True
ipa_domain = test-env.xcu2-8y8x.wl.cloudera.site
id_provider = ipa
auth_provider = ipa
access_provider = ipa
ipa_hostname = …
```

CB-7557 configure entry_cache_timeout for SSSD on FreeIPA

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/chain/EnvDeleteClustersFlowEventChainFactory.java

Removing the usage of Inject annotation from EnvDeleteClustersFlowEventChainFactory

CB-11561 - removing the usage of Inject annotation from EnvDeleteClustersFlowEventChainFactory

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerApiCheckerTask.java
integration-test/scripts/fetch-secrets.sh
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/StatusChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitFailedChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitOperationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitTerminationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceFailedChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceOperationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceTerminationChecker.java

While WaitService waits for a certain criteria to be met (depedning on StatusChecker implementation), it should refresh its data only once per round. This way we can not encounter an edge case where a check runs on different data then the check before it, causing changes to not handled properly.

CB-11419 Fix waiting edge cases in integration tests

---

integration-test/scripts/check-results.sh
integration-test/scripts/docker-compose.sh

We had error at starting ApplicationContext for Integration Test project, because of 
`Cannot find class in classpath: com.sequenceiq.it.cloudbreak.testcase.authorization.listfiltering.ImageCatalogListFiltering`.
So the related `artifact/integration-test` folder contains only the:
```
integcb
suites_log
```
sub folders. Beyond this the `suites_log` folder contains only the `spring.log` file with the above exception. Even the `integration-test_test_1 exited with code 1` the result was PASSED, because of:
```
./scripts/check-results.sh
Thu Mar 11 02:22:10 UTC 2021
Mar 11, 2021 2:22:12 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
[0;92m+++ Postgres traffic is below  limit.
[0;92m+++ INTEGRATION TEST SUCCESSFULLY FINISHED +++
RESULT=0
```
So we need …

CB-11626 Fix integration-test project check-results failure conditions

---

core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-engineering.bp

The setting "hiveserver2_idle_session_timeout" used to be 1 day by default for DE clusters and now the default value is changed to 4 hours and the screenshots attached for the same:
before change:
Post the change:

DISTX-571:set hive.server2.idle.session.timeout to 4h

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissionerTest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRetryService.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java

eg: customer select 3 nodes for downscale but we removed 0 nodes
It can happen because we collect nodes in the following way:
- collect nodes without FQDN (so they are not registered to CM)
- collect nodes from CM by some ordering algorithm if we don't have enough nodes from the first step
Problem: there are nodes with FQDN but not registered into CM. It can happen because we assign FQDN to them, but somehow we were not able to join them to the CM cluster.
Solution: we have to collect them also, so the downscale collection will happen in the following way:
- collect nodes without FQDN
- collect nodes with FQDN but not registered into CM
- collect nodes from CM by some ordering algorithm if we don't have enough nodes from the 1. and 2. step

CB-11621 There are cases when we remove less node than demanded node count at downscale

---

core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/clustertemplates/7.2.10/aws/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.10/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.10/gcp/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.10/yarn/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.8/aws/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.8/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.8/gcp/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.8/yarn/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.9/aws/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.9/azure/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.9/gcp/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.9/yarn/dataengineering-ha.json

1. Manager HostGroup to contain only CM.
2. Old manager HostGroup renamed to masterx.
3. Manager HostGroup made Gateway type.
4. The change is applied to 7.2.8, 7.2.9 and 7.2.10 DE HA Templates

DISTX-584 Move CM to its own hostgroup in DE HA Template

---

cloud-aws/src/main/resources/definitions/cdp/aws-cdp-bucket-access-policy.json

s3:HeadBucket is not a valid IAM action. s3:ListBucket is the IAM action
which grants access to call the HeadBucket API on S3.

CB-11667 Use ListBucket action instead of HeadBucket action in AWS IAM policy

---

core/src/main/resources/defaults/clustertemplates/7.2.10/gcp/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.10/gcp/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.10/gcp/flow-management-small.json
core/src/main/resources/defaults/clustertemplates/7.2.10/gcp/flow-management.json
core/src/main/resources/defaults/clustertemplates/7.2.10/gcp/streaming-small.json
core/src/main/resources/defaults/clustertemplates/7.2.10/gcp/streaming.json
core/src/main/resources/defaults/clustertemplates/7.2.8/gcp/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.8/gcp/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.8/gcp/flow-management-small.json
core/src/main/resources/defaults/clustertemplates/7.2.8/gcp/flow-management.json
core/src/main/resources/defaults/clustertemplates/7.2.8/gcp/streaming-small.json
core/src/main/resources/defaults/clustertemplates/7.2.8/gcp/streaming.json
core/src/main/resources/defaults/clustertemplates/7.2.9/gcp/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.9/gcp/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.9/gcp/flow-management-small.json
core/src/main/resources/defaults/clustertemplates/7.2.9/gcp/flow-management.json
core/src/main/resources/defaults/clustertemplates/7.2.9/gcp/streaming-small.json
core/src/main/resources/defaults/clustertemplates/7.2.9/gcp/streaming.json

1. Mark all the templates except for DE HA, DM and RTDM as released from 7.2.8
2. If 7.2.8 gets released before GCP is GA, customers with GCP entitlement will see this version as released before the announcement.
3. But marking it as released before, knocks out one item to track from the launch checklist.

CB-11672 GCP: Mark the existing 7.2.8 datahub templates as GA

---

core/src/main/resources/defaults/clustertemplates/7.2.10/aws/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.10/gcp/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.8/gcp/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.9/aws/dataengineering-ha.json
core/src/main/resources/defaults/clustertemplates/7.2.9/gcp/dataengineering-ha.json

GCP 7.2.8, 7.2.9, 7.2.10 template root and attached volume increased.
GCP hostgroups vm updated to 64 gb machines.
AWS 7.2.9, 7.2.10 compute hostGroup root volume increased.

DISTX-588 Rationalize DE HA Template for GCP,AWS,AZURE

---

core/src/main/resources/defaults/blueprints/7.2.0/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.1/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-engineering-spark3.bp

template.
- Moves Zookeeper over to the 'master' node.

CB-11700. Zookeeper should not be on the 'worker' nodes in the Spark3

---

redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/common/FillInMemoryStateStoreRestartAction.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/provision/RedbeamsProvisionState.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/start/RedbeamsStartState.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/stop/RedbeamsStopState.java
redbeams/src/main/java/com/sequenceiq/redbeams/flow/redbeams/termination/RedbeamsTerminationState.java

Upon restart the DBStack of running flows is not loaded into the in memory store, causing possible problems in the heartbeatService when all deleting flows are queried.
A restart action was added that fills the in memory store with currently executing flow's DBStack, if present (at the final step of the delete flow DBStack is deleted, thus after a restart at that place there is be no more DBStack).

CB-11415 Replace DefaultRestartAction for flows in redbeams service

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpCloudKMSFactory.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpComputeFactory.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpHttpClientConfig.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpIamFactory.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpSQLAdminFactory.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpServiceFactory.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/client/GcpStorageFactory.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/tracing/GcpTracingInterceptor.java

Use the original NetHttpTransport for GCP tracing. This implementation can retry with backoff and has timeout. With wrapper classes, the interceptors were added to the requests, the interceptor implementation changed to the Google HTTP API.

CB-10965 Missing retry - Read timed out for GCP

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_token.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/knox.sls

This new topology must be in synch with `cdp-proxy-api` in terms of services and gateway providers except for the authentication/federation provider they use.

CB-11694 - Added a new Knox topology called cdp-proxy-token

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeipaInternalCrnClient.java
integration-test/docker-compose_template.yml
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/FreeIpaClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/FreeIpaTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIpaSynchronizeAllUsersAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/config/server/FreeIpaServer.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaUserSyncTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/FreeIpaSyncTest.java

- removing explicit internal actor usage from integration tests
- only using internal crn client for specific actions

CB-11682 Remove internal actor from integration-test

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpNetworkConnector.java
environment/src/main/java/com/sequenceiq/environment/platformresource/v1/CredentialPlatformResourceController.java
environment/src/main/java/com/sequenceiq/environment/platformresource/v1/EnvironmentPlatformResourceController.java
environment/src/test/java/com/sequenceiq/environment/platformresource/v1/CredentialPlatformResourceControllerTest.java

**Changes:**
- validate the resource CRNs on Credential and Environment related platform resources endpoints
- handle empty network id during environment deletion as it could be empty when the deletion flow is restarted due to any reason before finalisation, but after network resource deletion

CB-11457 validate the resource CRNs on Credential and Environment related platform resources endpoints

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/repair/changeprimarygw/ChangePrimaryGatewayService.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/repair/changeprimarygw/ChangePrimaryGatewayServiceTest.java

Fix FreeIPA HA repair when master instance is stopped or doesn't
respond.
A unit test was added and it was manually tested using a local
deployment of cloudbreak.

CB-11692: Fix FreeIPA HA repair when master instance is stopped

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactoryTest.java
flow/src/main/java/com/sequenceiq/flow/core/chain/FlowChains.java
flow/src/main/java/com/sequenceiq/flow/core/chain/finalize/FlowChainFinalizeActions.java
flow/src/main/java/com/sequenceiq/flow/core/chain/finalize/config/FlowChainFinalizeEvent.java
flow/src/main/java/com/sequenceiq/flow/core/chain/finalize/config/FlowChainFinalizeFlowConfig.java
flow/src/main/java/com/sequenceiq/flow/core/chain/finalize/config/FlowChainFinalizeState.java
flow/src/main/java/com/sequenceiq/flow/core/chain/finalize/flowevents/FlowChainFinalizeFailedPayload.java
flow/src/main/java/com/sequenceiq/flow/core/chain/finalize/flowevents/FlowChainFinalizePayload.java
flow/src/main/java/com/sequenceiq/flow/core/chain/init/FlowChainInitActions.java
flow/src/main/java/com/sequenceiq/flow/core/chain/init/config/FlowChainInitEvent.java
flow/src/main/java/com/sequenceiq/flow/core/chain/init/config/FlowChainInitFlowConfig.java
flow/src/main/java/com/sequenceiq/flow/core/chain/init/config/FlowChainInitState.java
flow/src/main/java/com/sequenceiq/flow/core/chain/init/flowevents/FlowChainInitFailedPayload.java
flow/src/main/java/com/sequenceiq/flow/core/chain/init/flowevents/FlowChainInitPayload.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/log/cluster/ClusterRequestedLogger.java
structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterUseCaseMapper.java

CB-11170 EDH integration to measure how many customers used Data Hub repair
* New flows are introduced for flow chain init and flow chain finish
* To identify the repair start / finish steps, the repair flowchain is extended with these new flows
* The type of the flow chains will follow the following pattern flowchain1/flowchain2/flowchain3/flow in the flowlog table
* ClusterUseCaseMapper will make decision about the mapping based on the root flowchain
* report will be sent about repair flows
* Distrox upgrade will be reported as an upgrade report and a separated repair report

CB-11170 EDH integration to measure how many customers used Data Hub repair

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_token.xml.j2

Corrected the new topology name (it was accidentally left as `cdp-proxy-api` instead of `cdp-proxy-token`)

CB-11694 - Corrected topology name

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerRoleRefreshService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerRoleRefreshServiceTest.java

- fixing NPE issue, thus error message `New node(s) could not be added to the cluster. Reason null` will not occur again
- ensure best effort behavior and ignore CM failure

CB-11722 after Refresh Cluster CM command failure CB throws NPE

---

core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXRepairAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/CloudbreakTestDto.java

DistroXRepair test considers the repair flow's identifier at repair and remove flow identifier from test context at the end of flow polling

CB-11716 Distrox repair test fix.

---

freeipa/src/main/resources/freeipa-salt/salt/logrotate/conf/pkidebug
freeipa/src/main/resources/freeipa-salt/salt/logrotate/init.sls

Currently /pki/pki-tomcat/ca/debug doesn't have logrotate configuration. It should have similarly to ipabackup.log. We add logrotate rule to avoid the log to fill the disk space.

CB-11659 Add logrotate config for /pki/pki-tomcat/ca/debug on FreeIPA

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/certrenew/ClusterCertificateRenewState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/certrotate/ClusterCertificatesRotationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/config/update/PillarConfigUpdateState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/dr/backup/DatabaseBackupState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/dr/restore/DatabaseRestoreState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/maintenance/MaintenanceModeValidationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/update/SaltUpdateState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/start/ClusterStartState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stop/ClusterStopState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/termination/ClusterTerminationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/userpasswd/ClusterCredentialChangeState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cmdiagnostics/CmDiagnosticsCollectionState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/DiagnosticsCollectionsState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/provision/config/ExternalDatabaseCreationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/start/config/ExternalDatabaseStartState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/stop/config/ExternalDatabaseStopState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/terminate/config/ExternalDatabaseTerminationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/restart/InitializeMDCContextRestartAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/restart/WaitForSyncRestartAction.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/instance/termination/InstanceTerminationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/stop/StackStopState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/termination/StackTerminationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/cloud/config/CloudConfigValidationState.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/config/KerberosConfigValidationState.java

Replace default restartaction for flows to
- `FillInMemoryStateStoreRestartAction` if it's using `InMemoryStore` for polling
- `InitializeMDCContextRestartAction` otherwise to ensure MDCContext is set
`WaitForSyncRestartAction` will also st MDCContext

CB-11417 Replace DefaultRestartAction for flows in cb core service

---

core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-engineering.bp

the default value for "hive.blobstore.supported.schemes" is  "s3,s3a,s3n" and its updated to "s3,s3a,s3n,abfs" now. Screenshot attached below:

CDPD-23526:Add abfs and gs to hive.blobstore.supported.schemes

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientExceptionWrapper.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/RetryableFreeIpaClientException.java
freeipa-client/src/test/java/com/sequenceiq/freeipa/client/RetryableFreeIpaClientExceptionTest.java

When `exceptionForRestApi` is not set `toString` could cause exception. This is fixed by handling null gracefully.
Also `FreeIpaClientExceptionWrapper` contructor has been edited to include the message, so it won't call `toString` on the wrapped exception.

CB-11778 Fix NullPointer for `RetryableFreeIpaClientException#toString`

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/ResourceConnector.java
cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/ResourceConnectorTest.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsResourceConnector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpResourceConnector.java
cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockResourceConnector.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackResourceConnector.java
cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/OpenStackNativeResourceConnector.java
cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/LaunchStackHandler.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/ApplicationNameUtil.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnApplicationCreationService.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnMetadataCollector.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnector.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/client/model/core/Artifact.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/client/model/core/ConfigFile.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/client/model/core/Configuration.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/client/model/core/Dependency.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/client/model/core/Resource.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/client/model/core/YarnComponent.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/loadbalancer/service/component/YarnLoadBalancerComponentFactoryService.java
cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/loadbalancer/service/launch/YarnLoadBalancerLaunchService.java
cloud-yarn/src/test/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnResourceConnectorTest.java
common-model/src/main/java/com/sequenceiq/common/api/type/ResourceType.java
common-model/src/test/java/com/sequenceiq/common/api/type/ResourceTypeTest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/CreateCloudLoadBalancersHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java

Jira: https://jira.cloudera.com/browse/CB-10092
This has been tested fully, end-to-end, with additional verification that nothing has been broken for AWS/Azure LD/HA setups.
- A launchLoadBalancer() method was added to the stack creation flow within the launchStack logic
- A new class called YarnLaunchLoadBalancerService was added which handles all of the launch logic
- The gateway nodes created before the launch loadbalancer steps have their IPs retrieved
- A new docker image (which will be hosted where the default YCloud image is hosted) was created and is being pointed to by the LoadBalancer container created, this image will install the haproxy service and point it at the provided servers
- The loadbalancer container's IP is retrieved in the same way as other YCloud container IPs, but …

CB-10092: Adding an internal loadbalancer to YCloud datalake setups.

---

datalake/src/main/java/com/sequenceiq/datalake/entity/DatalakeStatusEnum.java

SDX stuck in DELETE_IN_PROGRESS when the termination failed but the flow finished.

CB-11432 Datalake cannot go to delete_failed from delete_in_progress

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/common-install.sls

As described in https://docs.google.com/document/d/1krz-82-wY9PwUcJcof2SH9EtF7KkYcPVmWGIzN2akkA/edit#, the header X-CDP-Request-ID should be logged by FreeIPA into /var/log/httpd/error_log
This can be done by adding logging of environ.get('HTTP_X_CDP_Request_ID') to the info level logs statemetns in /usr/lib/python2.7/site-packages/ipaserver/rpcserver.py
WSGIExecutioner::wsgi_execute(). Salt to distribute update this file and restart ipa.

CB-9717 FreeIPA should log X-CDP-Request-ID to /var/log/httpd/error_log

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/loadbalancer/StackLoadBalancerUpdateService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/CreateLoadBalancerEntityHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/RegisterPublicDnsHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceGroupRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceGroupService.java
environment/src/main/java/com/sequenceiq/environment/environment/service/network/NetworkMetadataValidationService.java

Fetches the instance group templates during the initial database fetch. These are required if the
cluster has an embedded database. Fixes the stack information being passed to the
"clusterHostServiceRunner.updateClusterConfigs" call, which was updated in PR #10223. And now
correctly passes the exception during failures to the UI output, so it should show up correctly.
Tested on local CB environments.

CB-11664 set-endpoint-access-gateway on existing environment fails

---

core/src/main/resources/application.yml

Jira: https://jira.cloudera.com/browse/CB-11808
Want to wait for repair with upscale/downscale to work before adding this.

CB-11808: Removed Yarn from the Load Balancer supported platforms.

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaCleanupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaCleanupServiceTest.java

FreeIPA cleanup (which runs during cluster scaling, creation, termination) in an edge case can cause missing DNS records in FreeIPA:
- create a cluster: CL1
- delete the nodes on provider (but leave it in place on the controlplane side)
- create another cluster: CL2 (some of it's nodes will get the same IP as CL1)
- delete CL1 using control plane
- this will invoke cleanup process which deletes records based on IP too, removing entries used by CL2
The fix is to remove IP based cleanup when downscaling and terminating. On the ideal path it should not cause an issue and leave residue as FQDN/name based cleanup should clean everything.
The reason we need IP based cleanup if something cause sideways during downscale/terminate cleanup as we ignore those results. In that case on …

CB-11790 FreeIPA cleanup can cause missing DNS records

---

datalake/src/main/java/com/sequenceiq/datalake/flow/cert/rotation/SdxCertRotationState.java
flow/src/main/java/com/sequenceiq/flow/core/FlowState.java
flow/src/main/java/com/sequenceiq/flow/core/chain/finalize/config/FlowChainFinalizeState.java
flow/src/main/java/com/sequenceiq/flow/core/chain/init/config/FlowChainInitState.java
flow/src/main/java/com/sequenceiq/flow/core/helloworld/config/HelloWorldState.java
flow/src/main/java/com/sequenceiq/flow/core/restart/DefaultRestartAction.java
flow/src/test/java/com/sequenceiq/flow/core/AbstractActionTest.java
flow/src/test/java/com/sequenceiq/flow/core/Flow2HandlerTest.java
flow/src/test/java/com/sequenceiq/flow/core/StateConverterAdapterTest.java
flow/src/test/java/com/sequenceiq/flow/core/config/AbstractFlowConfigurationTest.java
flow/src/test/java/com/sequenceiq/flow/core/config/TestFlowConfig.java
flow/src/test/java/com/sequenceiq/flow/service/flowlog/FlowLogDBServiceTest.java

Remove `DefaultRestartAction` from `FlowState` as default implementation for `restartAction` to enforce developers to think about it when creating new flows

CB-11418 Remove DefaultRestartAction from Flowstate as default

---

core/src/main/resources/defaults/blueprints/7.2.10/cdp-opdb.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-opdb.bp

To test this change I created Custom cluster template (called OPDB omid testv3)
I used this template to create a datahub cluster (https://console.dps.mow-dev.cloudera.com/cloud/workloads/details/richarda-opdb-omid/events)
In the first attempt I faced an issue that Omid-191 was not yet merged to cdpd-master. I pushed that change and it is in since  build number 7.2.9.0-154 so I had to specify the GBN as well.
Omid stated on the cluster and I ran some queries to test transactions. create transactional table, insert, commit, select

CDPD-16919 Phoenix 5.1 DataHub integration

---

core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionChecker.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionCheckerFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionCheckerType.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionResult.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/step/ConclusionStep.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/step/ConclusionStepResult.java
core/src/main/java/com/sequenceiq/cloudbreak/conclusion/step/SaltMinionCheckerConclusionStep.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/downscale/ClusterDownscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/upscale/ClusterUpscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/ClusterDownscaleFailedConclusionRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/ClusterUpscaleFailedConclusionRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterDownscaleFailedConclusionHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterUpscaleFailedConclusionHandler.java
core/src/test/java/com/sequenceiq/cloudbreak/conclusion/ConclusionCheckerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/conclusion/step/SaltMinionCheckerConclusionStepTest.java

If something wrong happens during flow execution (currently cluster upscale and cluster downscale), we should run some checks in order to find the root cause of the error.
Currently salt minion check is implemented.
If the conclusion checker finds something it will send an event to the UI.

CB-11680 Improve root cause detection after a complex operation fails

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/update/loadbalancer/StackLoadBalancerUpdateActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/CreateCloudLoadBalancersHandler.java

Jira: https://jira.cloudera.com/browse/CB-11646
I had to make two primary changes for this to work:
- Adding the stack creator username to the Cloud Context object created for the load balancer update flow
- We were running into null pointer exceptions because the YCloud load balancer logic requires the user name field in the Cloud Context object to be present for the creation of the load balancer and application name
- Adding a polling process for the load balancer resources to the load balancer creation logic in the update flow
- Basically when this is not present the load balancer creation will be initiated but by the time the load balancer metadata is being retrieved, the load balancer application will not have been finished
- This polling process is identical to the one present in …

CB-11646: Fixed YCloud in-place load balancer update.

---

core/src/main/resources/application.yml

Jira: https://jira.cloudera.com/browse/CB-11645
Copying extended commit message here:
This change was originally meant to track upscale/downscale support for YCloud load balancers, however as upscale and downscale operations are not supported for Yarn stacks, this just tracks the official support for YCloud load balancers. All other load balancer logic for YCloud has been implemented and tested.

CB-11645: Added Yarn to the supported load balancer cloud platform list.

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java

During datalake upgrade in the cluster sync step (part of the image change flow) the code asks CM for host statuses. CM server sometimes returns an empty response. This was not expected and an NPE was thrown.
After the NPE, even though the imafge change flow failed, the calling datalake flow proceeded and failed at the replaceVm - upscale step, as the new image was not copied.
This commit fixes the NPE itself only.

CB-11760 Datalake upgrade: NPE when CM does not send host status

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/Group.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsCloudWatchService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsTerminateService.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsCloudWatchServiceTest.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceGroup.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverterTest.java

Adds a list of deleted instances to the CloudStack object. During a stack termination, we'll send both the
running instances ids and terminated instances ids to the deleteCloudWatchAlarmsForSystemFailures. This
will allow us to delete any lingering cloudwatch alarms for instances that have been termianted on the
provider side.
Tested with unit tests and running CB locally, deleting the cloud instances, and verifying the deleted alarm
request succeeded for the deleted instances.

CB-11839 Cloudwatch alarms are not deleted in case of sdx delete

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl.conf

Only on data hubs and data lakes.
This way all ingress traffic is enabled from within the VPC towards
NGINX port 9443 if CCMv2 is enabled.
This is achieved by adding CIDR list to gateway pillar and using it
with NGINX SSL config.

CB-11711 Open NGINX for VPC CIDR with CCMv2

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ExistingResourceRestUrlParser.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java

Jira: https://jira.cloudera.com/browse/CB-11906
Changes I made:
- Added a new endpoint path for the image catalog for getting an image without a catalog name
- Needed to do this since with the previous path, not having a name would result in a malformed path that would be rejected by the validator
Tested this with the CDP CLI change I made and seems to be working correctly for the two use cases.
Let me know if there is anything we want to change for this.

CB-11906: Fixed creation of datalake with unique image ID when catalog name not present.

---

notification-sender/build.gradle
notification-sender/src/main/java/com/sequenceiq/notification/NotificationAssemblingService.java
structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/CloudbreakNotification.java

Extend CloudbreakNotification class with an optional subscriptionRequired boolean property, set based on PERSONAL_VIEW_CB_BY_RIGHT entitlement.
The flag will be used by Uluwatu to determine if notification filtering is enabled for the tenant.

CB-11379 subscriptionRequired flag for notifications

---

freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaChecker.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeipaCheckerTest.java
node-status-monitor-client/src/generated/main/java/com/cloudera/thunderhead/telemetry/nodestatus/NodeStatusProto.java
node-status-monitor-client/src/main/proto/nodestatus.proto
orchestrator-salt/src/main/resources/salt-common/salt/filecollector/init.sls
orchestrator-salt/src/main/resources/salt-common/salt/filecollector/template/cdp-doctor-commands.yaml.j2

details:
- update only models
- fix toString issue with RPCMessage during freeipa check
- skip neighbour scan for network checks
- include cloud specific network checks if the telemetry binary version is proper for that

CB-11769. Add new network checks for CDP nodestatus monitor.

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/azure/FreeIpaAzureNetworkProvider.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/gcp/FreeIpaGcpNetworkProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigView.java
freeipa/src/main/resources/freeipa-salt/salt/nginx/conf/ssl.conf
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigServiceTest.java
orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl.conf

This way all ingress traffic is enabled from within the VPC towards
NGINX port 9443 if CCMv2 is enabled.
This is achieved by adding CIDR list to gateway pillar and using it
with NGINX SSL config.
There was a missing code part which did not fill the CIDR blocks in case
of GCP and AZURE providers, this is fixed too.
To avoid null problems in the DB the ssl.conf templates were modified
accordingly.

CB-11711 Open NGINX for VPC CIDR with CCMv2 for FreeIPA

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/util/UtilV4Endpoint.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/projection/StackImageView.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/UtilV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/generator/OfflineStateGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/UsedImagesProvider.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/test/java/com/sequenceiq/cloudbreak/repository/StackRepositoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/UsedImagesProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackServiceTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/util/UtilV1Endpoint.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/UtilV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/UsedImagesProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/UsedImagesProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/StackServiceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeipaUsedImagesAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/util/UsedImagesAction.java

Deleting non-used production images will require having a waiting period of predefined days after the last stack with that image was terminated, so a thresholdInDays parameter was introduced to both CB and Freeipa endpoints.
Additionally fix the CB numberOfStacks, as the previous solution returned the number of instance groups instead of stacks.

CB-10566 Add threshold parameter to used images endpoints

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

This also enables round robining to all the hosts in the topology,
and should not affect Knox services that do not have this enabled.

CB-9745 Enabling Knox sticky sessions for ui and api requests.

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpDiskResourceBuilder.java
core/src/main/resources/defaults/clustertemplates/7.2.10/gcp/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.10/gcp/dataengineering.json
core/src/main/resources/defaults/clustertemplates/7.2.9/gcp/dataengineering-spark3.json
core/src/main/resources/defaults/clustertemplates/7.2.9/gcp/dataengineering.json

1. DISTX-557 -> To overcome memory overcommit problem in default DE template AWS and Azure was already moved to 64 GB memory, this is the GCP followup
2. DISTX-575 -> DE AWS and Azure was already handled to move to SSDs by default. The GCP DE HA template was also updated. This is just the GCP followup for other templates.
3. CB-9521 -> Moved the root volume of GCP to SSD, this should help in custom parcel handling, among other perf improvement and gets it on par with AWS and Azure.

Update GCP templates for performance

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/repair/SdxRepairActions.java
datalake/src/main/java/com/sequenceiq/datalake/flow/repair/SdxRepairEvent.java
datalake/src/main/java/com/sequenceiq/datalake/flow/repair/event/SdxRepairInProgressEvent.java
datalake/src/main/java/com/sequenceiq/datalake/flow/repair/event/SdxRepairStartRequest.java
datalake/src/main/java/com/sequenceiq/datalake/flow/repair/handler/SdxRepairStartHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/repair/handler/SdxRepairWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/start/handler/SdxStartWaitHandler.java

Before starting a repair the external database state should be validated.
Minor copy-paste naming fixes.

CB-11252 Repair puts DL in an inconsistent state if the DB is stopped

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AutoscaleV4Controller.java

DISTX-602 DH Autoscaling should use Resource Level Authorization …
DH Autoscaling should only use resource level authorization checks, since Account Level authorization has been deprecated.

DISTX-602 DH Autoscaling Resource Level Authorization

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java

Jira: https://jira.cloudera.com/browse/CB-11981
Simply added check to ensure network is not null before trying to access the internal CIDRs.

CB-11981: Fixed YCloud datalake creation NPE due to not checking if stack network is null.

---

core-api/src/main/resources/definitions/exposed-services.json

The Knox team introduced a very useful usability improvement on the Knox side to display certain elements only in the `General Proxy Information` section on the `Knox Home` page  (using pre-defined profile names) as well as we added the ability to filter topologies we display. To be able to do it on the client-side (i.e. without any server-side config), this can be achieved by adding the appropriate query parameter in the homepage's URL: `https://host:port/gateway_path/homepage/home?profile=token&topologies=cdp-proxy-token`
In this change, I added the missing query parameters into the previously created `Token Integration` link.

CB-11987 - Appending the profile and topologies query parameters into the Token Integration URL

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/doc/UserModelDescriptions.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/SynchronizeAllUsersRequest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/user/model/WorkloadCredentialsUpdateType.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/UserV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UserSyncOptions.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/poller/UserSyncPoller.java
freeipa/src/test/java/com/sequenceiq/freeipa/controller/UserV1ControllerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/WorkloadCredentialServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/poller/UserSyncPollerTest.java

Adds a flag to the SynchronizeAllUsers request that forces user sync to update
workload credentials for all users, whether or not they have changed. The flag
is a no-op when the CDP_USER_SYNC_CREDENTIALS_UPDATE_OPTIMIZATION entitlement
is not enabled.
The flag will be exposed as a '--force-workload-credentials-update' option to
the 'cdp environments sync-all-users' API. This is the backend implementation.
I added the flag to both public entry points to UserSyncService -- synchronizeUsers
and synchronizeUsersWithCustomPermissionCheck, even though callers of the former
always set it to false. It seemed inconsistent for this option to be accepted
when doing a custom permission check, but not otherwise.
I also moved the computation of UserSyncOptions up the call chain, to avoid
adding more …

CDPCP-3702 Add flag to force update of workload credentials by user sync

---

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/azure/AzureResourceEncryptionParameters.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/parameters/dao/domain/AzureParameters.java
environment/src/main/java/com/sequenceiq/environment/parameters/v1/converter/AzureEnvironmentParametersConverter.java
environment/src/main/java/com/sequenceiq/environment/parameters/validation/validators/parameter/AzureParameterValidator.java
environment/src/main/resources/schema/app/20210407150154_CB-11874_Make_DiskEncryptionSetId_available_in_environment_service_API_response.sql
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/v1/converter/AzureEnvironmentParametersConverterTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/validation/validators/AzureParameterValidatorTest.java
structuredevent-model/src/main/java/com/sequenceiq/environment/parameter/dto/AzureResourceEncryptionParametersDto.java
structuredevent-model/src/test/java/com/sequenceiq/environment/parameter/dto/AzureResourceEncryptionParametersDtoTest.java

CB-11874: Make DiskEncryptionSetId available in environment service API response.
1. AzureResourceEncryptionParameters extended with the new field diskEncryptionSetId.
2. New column `disk_encryption_set_id` and `encryption_key_url` are added to environment_parameters table.
3. To prohibit passing in the DES Resource ID in the request, validation is added.
4. Column `encryption_keyUrl` is deprecated.
Testing - Combined these changes with [CB-11872](https://github.com/hortonworks/cloudbreak/pull/10372).
1. Entries in DB are populated for `disk_encryption_set_id` and `encryption_key_url`. As expected `encryption_keyUrl` is not populated.
2. DES creation is successful, required tags are attached.

CB-11874: Make DiskEncryptionSetId available in environment service API response

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/InstanceTemplate.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/instance/AwsInstanceTemplate.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/instance/AzureInstanceTemplate.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilderTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureInstanceView.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureStackView.java
cloud-azure/src/main/resources/templates/arm-v2.ftl
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilderTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/util/AzureVirtualMachineTypeProviderTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureInstanceViewTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureStackViewTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/AwsInstanceTemplateV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/AzureEncryptionV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/AzureInstanceTemplateV4Parameters.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-api/src/test/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/AwsInstanceTemplateV4ParametersTest.java
core-api/src/test/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/AzureInstanceTemplateV4ParametersTest.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceGroupV1ToInstanceGroupV4Converter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateV1ToInstanceTemplateV4Converter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceGroupV1ToInstanceGroupV4ConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverterTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateV1ToInstanceTemplateV4ConverterTest.java

* When present in `DetailedEnvironmentResponse` (`getDiskEncryptionSetId()`), associate the provided Disk Encryption Set (DES) Resource ID with all the Managed Disks of the DH cluster being created. This applies to the OS disks as well as data (attached) disks, and will make all such disks encrypted by SSE using the customer-managed CMK linked to the DES.
* `cloud-api` receives the SSE with CMK and DES Resource ID as two new dynamic parameters in `InstanceTemplate`. The parameter name constants are defined in the new class `AzureInstanceTemplate`.
* No entitlement check (regarding `EntitlementService.isAzureDiskSSEWithCMKEnabled()`) is made; the DES Resource ID will be always used and applied to all new DH VM disks when present in `DetailedEnvironmentResponse`.
* StackV4 API has been …

CB-11154 Use DES to enable SSE with CMK during Azure DH cluster creation

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/mapper/SdkClientExceptionMapper.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/mapper/SdkClientExceptionMapperTest.java

CB-11802 Rollback of failed upscale resources due to AWS quota limit fails when there is activity still in progress on the auto scaling group

---

autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/CloudbreakCommunicator.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java
autoscale/src/test/java/com/sequenceiq/periscope/controller/AutoscaleClusterCommonServiceTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/AutoscaleV4Endpoint.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakInternalCrnClient.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AutoscaleV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackApiViewService.java

- all "internal call compatible" CB autoscale API now can be called by internal actor (TenantAwareParam annotation added to crn parameters)
- all "internal call non-compatible" API, which has old PreAuthorize annotation, got relevant authorization annotation (typically name based methods, those are not used usually by periscope anyway)
- all "internal call non-compatible" API, which has old PreAuthorize annotation, got an equivalent internal API, using accountId queryparam
- all CB autoscale APIs will be called by Periscope with internal actor
- PreAuthorize annotations removed from periscope related APIs

CB-12078 CB Scaling API that works with internal crns

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ImageFilterParamsFactory.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeService.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeServiceTest.java

CB-11996 Support Runtime upgrade without OS upgrade (image swap) for all DH clusters
* In case of distrox runtime upgrade the replaceVms parameter in the request will be overridden to false.
This means that the vm replacement will be always skipped in case of distrox runtime upgrade.
* In case of distrox os upgrade the replaceVms parameter won't be changed,
so the vm replacement can be controllable via this parameter.

CB-11996 Support Runtime upgrade without OS upgrade (image swap) for all DH clusters

---

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/azure/AzureResourceEncryptionParameters.java
environment-api/src/test/java/com/sequenceiq/environment/api/v1/environment/model/request/azure/AzureResourceEncryptionParametersTest.java

* Add new String field / API property `encryptionKeyResourceGroupName` to `AzureResourceEncryptionParameters`.
* Fix validation pattern & error message for `encryptionKeyUrl`.
* Add UT for validating `encryptionKeyUrl`.
Backend changes (converters, validation, entity) will come in a later PR as part of [CB-12118](https://jira.cloudera.com/browse/CB-12118).
See [this Azure doc page](https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates#dns-suffixes-for-base-url) for the allowed DNS suffixes in Key Vault key URLs.

CB-12101 Environment API: Add encryptionKeyResourceGroupName for Azure

---

datalake/src/main/java/com/sequenceiq/datalake/flow/create/handler/EnvWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/create/handler/RdsWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/create/handler/StorageValidationHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/handler/DatalakeChangeImageWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/handler/DatalakeUpgradeWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/handler/DatalakeVmReplaceWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/delete/handler/RdsDeletionHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/start/handler/RdsStartHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/start/handler/SdxStartWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/stop/handler/RdsStopHandler.java
datalake/src/main/java/com/sequenceiq/datalake/flow/stop/handler/SdxStopWaitHandler.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/EnvironmentService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/EnvironmentServiceTest.java

There may be a situation where a 40 min timeout is not enough. For example if something is slow on the provider side, the polling could timeout on datalake side before the flow in the core could finish, thus the stack remains in UPDATE_IN_PROGRESS state. Increasing the timeout lets CB to finish the flow. Since we have flow tracking it should not cause any problems.

CB-7972 Increase datalake start timeout to 120 min

---

common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/Crn.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/altus/CrnResourceDescriptor.java
common/src/main/java/com/sequenceiq/cloudbreak/validation/AbstractCrnValidator.java
common/src/main/java/com/sequenceiq/cloudbreak/validation/CrnCollectionValidator.java
common/src/main/java/com/sequenceiq/cloudbreak/validation/CrnValidator.java
common/src/main/java/com/sequenceiq/cloudbreak/validation/ValidCrn.java
common/src/test/java/com/sequenceiq/cloudbreak/validation/CrnCollectionValidatorTest.java
common/src/test/java/com/sequenceiq/cloudbreak/validation/CrnValidatorTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/RedbeamsDatabaseServerTest.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/requests/AllocateDatabaseServerV4Request.java

When redbeams databaseserver create endpoint is called, a clusterCrn has to be provided. Currently it is allowed to be datalake or datahub only. As a result of that services, that do not posses such CRNs are not allowed to call redbeams.
The present commit allows a databaseServer to be created with any CRN except of an environmentCrn.

CB-11514 DFX to use redbeams to create databaseServers

---

cloud-gcp/src/main/resources/definitions/gcp-prerequisites-creation-command.json

The compute.storageAdmin role is completely superseded by compute.instanceAdmin.v1 so it could be removed, but storage.admin role is neccesary for CDP related storage operations.
I think it should go into 2.42 line of CB, so master is fine for now...

CB-11754 change compute.storageAdmin role to storage.admin in the GCP credential create command

---

authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceCrnAthorizationFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/ExternalDatabaseService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsClientService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/externaldatabase/ExternalDatabaseServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsClientServiceTest.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/databaseserver/DatabaseServerV4Endpoint.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/Notes.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/OperationDescriptions.java
redbeams-api/src/main/java/com/sequenceiq/redbeams/doc/ParamDescriptions.java
redbeams/src/main/java/com/sequenceiq/redbeams/controller/v4/databaseserver/DatabaseServerV4Controller.java
redbeams/src/main/java/com/sequenceiq/redbeams/repository/DatabaseServerConfigRepository.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigService.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsCreationService.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/dbserverconfig/DatabaseServerConfigServiceTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/stack/RedbeamsCreationServiceTest.java

In case flow was stopped and then restarted just after the external
DB provision started, it might happen that upon launching a new
create request to RedBeams caused and exception. This is fixed now.

CB-11747 External database create flow is not restartable

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/DistroXService.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/DistroXServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/start/SdxStartService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/stop/SdxStopService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/start/SdxStartServiceTest.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationRetrievalTask.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/start/handler/StartFreeIpaHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/start/handler/SynchronizeUsersHandler.java
environment/src/main/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaPollerService.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationRetrievalTaskTest.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/start/handler/StartFreeIpaHandlerTest.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/start/handler/SynchronizeUsersHandlerTest.java
environment/src/test/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaPollerServiceTest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/AvailabilityStatus.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/DetailedStackStatus.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/Status.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/describe/DescribeFreeIpaResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/poller/UserSyncPoller.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/main/resources/schema/app/20210422110735_CB-12224_add_new_index_stack_detailed_status.sql
freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/poller/UserSyncPollerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/StackServiceTest.java

Provide workloads a summary of whether FreeIPA is available and able
to respond to API requests. Several checks were modified to use this
new status, since it is more accurate than the old way of checking if
FreeIPA is available.
Unit tests were updated.
The FreeIPA management service API was manually checked with a local
deployment of cloudbreak.

CB-12224: Add FreeIPA availability status

---

build.gradle

details:
- CB-11603. Upgrade package spring-messaging to version 4.3.16.RELEASE or above. (CVE-2018-1275)
- CB-11604. Upgrade package spring-messaging to version 4.3.16.RELEASE or above. (CVE-2018-1270)
(new spring-messaging version: 5.3.2 - as the spring framework version)

CDPCP-3974. Update gradle dependencies (v2 - spring messaging)

---

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/ResourceEncryptionDeleteHandler.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/ResourceEncryptionDeleteHandlerTest.java

CB-12243: DES delete flow exceptions are swallowed and do not result in flow failure
Fix the issue of swallowing of exceptions - by re-throwing the exception after logging.

CB-12243: DES delete flow exceptions are swallowed and do not result in flow failure

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeController.java
datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java
datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeControllerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java

CB-12115 Enable maintenance upgrade for every customer …
* CB-12183 Datalake maintenance upgrade validation improvement
* CB-12184 Image filtering improvement for Datalake maintenance upgrade
The maintenance upgrade will always be enabled for all the customers independently from the CDP_RUNTIME_UPGRADE entitlement.
Image filtering improvements:
* If CDP_RUNTIME_UPGRADE is enabled, filtering works as before
* If CDP_RUNTIME_UPGRADE is disabled, only patch upgrade images will be in the result.
Validation improvements:
* if CDP_RUNTIME_UPGRADE is enabled, validation works as before, otherwise:
* if runtime param is given: if no entitlement and no patch upgrades are available: candidate list will be empty, explanation is in reason param
* if imageid is given: if no entitlement and the given …

CB-12115 Enable maintenance upgrade for every customer

---

cloud-aws/src/main/resources/definitions/datahub-minimal-policy.json
cloud-aws/src/main/resources/definitions/datalake-minimal-policy.json
cloud-aws/src/main/resources/definitions/environment-minimal-policy.json
cloud-aws/src/main/resources/definitions/freeipa-minimal-policy.json
cloud-aws/src/main/resources/definitions/rds-minimal-policy.json

eipa and RDS. RDS is usable with dh or dl but others can be run as a 'standalone' policy for the role. These granulated policies support the roles to create and manage the dh, dl, env and freeipa instances on the AWS

CB-11011 minimal AWS policies for Datalake, Datahub, Environment, Fre

---

flow/src/test/java/com/sequenceiq/flow/reactor/config/EventBusConfigTest.java

The event bus is async this is why I added timeout(2000) to getLastFlowLog
method verification. The problem is sometimes the test verification thread
is faster than the async eventbus error handling thread so it can happen the
flowLogDBService method calls are not invoked when it was verified. I
hope this 1000 ms timeout can avoid the flakiness.

CB-12292 EventBusConfigTest.uncaughtErrorButFlowFound unit test is flaky

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2

Sticky sessions and noFallback were enabled for the Solr UI Knox endpoints, under the assumption that
the Solr UI requires a valid session. This prevented failover if one of the Solr instances was down.
The Solr team has since verified that the UI is stateless and there's no need for sticky sessions, and
no reason to disable fallback. Updating the topology to turn off sticky sessions and turn on falback.
Tested by manually update the topology.xml document on the data lake and verifying the Solr UI failed
over successfully.

CB-12159 Solr UI load fails - 502 Service Con Error/ HA failover disabled

---

core/src/main/resources/defaults/vm-logs.json
freeipa/src/main/resources/defaults/vm-logs.json

[CDPAM-1597](https://jira.cloudera.com/browse/CDPAM-1597):
Based on @oleewere [comment](https://jira.cloudera.com/browse/CDPAM-1597?focusedCommentId=4473163&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4473163), have added the location of CCMv2 inverting proxy agent logs that need to shipped at the time of env creation similar to how it is done for other components' logs.
Thanks

CDPAM-1597 | Ship CCMv2 inverting proxy agent logs at the time of env creation

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsLogRolePermissionValidator.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsLaunchTest.java
cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsRepairTest.java
common/src/main/java/com/sequenceiq/cloudbreak/cloud/storage/LocationHelper.java
common/src/test/java/com/sequenceiq/cloudbreak/cloud/storage/LocationHelperTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsApplication.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/s3/S3ConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/s3/S3ConfigProviderTest.java

A customer has a restriction that calls to s3 have to remain within their region (done with a policy from AWS Landing Zone). During datalake install, CM first run the task HDFS dir create failed.
Analysis revealed a connection timeout to s3. The connection, however, was made to s3 region east-us, the default s3 region in the absence of region info, to resolve the region of the bucket. Because of the barrage, however, the call was blocked.
The solution is based on a setting offered by the hadoop-aws component: adding the fs.s3.bucket.BUCKET-NAME.endpoint parameter with the regional endpoint will let hdfs know that it should use the given endpoint for the bucket (storage location base) given.

CB-12046 s3 calls should not leave the s3 region

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_replica_install.sh

If FreeIPA replica install fails, the `ipa-server-install --uninstall`
will not always clean up everthing. Add commands to force the cleanup
so that it will attempt to clean up anything that is dangling.
Also cleanup the old installation of FreeIPA from the ipaservers host
group.
This was manually tested using a local deployment of cloudbreak.

CB-12331: Force the removal of old FreeIPA server installations

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaTopologyService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaTopologyServiceTest.java

Fix deleting FreeIPA topology that has already been deleted.
Unit test added.

CB-12324: Fix deleting FreeIPA topology that has already been deleted

---

cloud-aws/src/main/resources/templates/aws-cf-stack.ftl

Reduces the AWS target group HealthyThresholdCount to the minimum value of 2 from the default of 3,
and the HealthCheckIntervalSeconds to 10s from the default of 30s. This will reduce the failover
time for the load balancer to detect an unhealthy node to ~20s.

CB-11923 Loadbalancer takes ~2.5 mins to failover requests when one of the Knox host is down

---

core/src/main/resources/application.yml
core/src/main/resources/defaults/blueprints/7.2.10/cdp-cod-edge-node.bp
core/src/main/resources/defaults/blueprints/7.2.2/cdp-cod-edge-node.bp
core/src/main/resources/defaults/blueprints/7.2.3/cdp-cod-edge-node.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-cod-edge-node.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-cod-edge-node.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-cod-edge-node.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-cod-edge-node.bp
core/src/main/resources/schema/app/20210429105927_CB-12302_make_edge_node_templates_default.sql

I add edge node templates to all of our runtimes appear to be in our code.
I tested the migration, it made the existing templates default, visible to other users as well, not just for the creator.
On mow-dev I found these edge node templates:
7.2.8 COD Edge Node
7.2.7 COD Edge Node
7.2.6 COD Edge Node
7.2.3 COD Edge Node
7.2.2 COD Edge Node
7.2.1 COD Edge Node
7.2.0 COD Edge Node
7.1.1 COD Edge Node
But we have 7.0.2, 7.1.0, 7.2.9, 7.2.10 runtimes in our code (I assume COD would create them anyway) so I add:
7.0.2 COD Edge Node
7.1.0 COD Edge Node
7.2.9 COD Edge Node
7.2.10 COD Edge Node
as well.
@lnardai @horadla23 @sodre90 @petersomogyi please correct me if some these are not needed and sure as hell that it won't break anything if I don't add them.

CB-12302 Move and migrate EdgeNode templates to CB code

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureMetadataCollector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureMetadataCollectorTest.java

Closes [CB-12229](https://jira.cloudera.com/browse/CB-12229).
* Add unit test to `AzureMetaDataCollector`, when collecting private ips.
* Fix imports for `AzureMetaDataCollectorTest`.
* Use an `Optional<String>` for LB ips instead of a `null` String.
* Use a switch/case for `AzureClient` when retrieving load balancer IPs based on the load balancer type.

CB-12229: Clean up Azure Load Balancer code

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/binduser/BindUserCreateService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaPostInstallService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/binduser/BindUserCreateServiceTest.java

Child environment lookup was missing when creating bind users.
This caused an not found exception on FMS side which prevented YCLOUD cluster creation.

CB-12345 Fix BindUsercreation for child environments

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/RemoveHostsHandler.java
freeipa/src/main/resources/freeipa-salt/salt/freeipa/init.sls
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/RemoveHostsHandlerTest.java

During FreeIPA HA repair, if the same IP address is resused, it can
break the FreeIPA installation and downscaling. The FreeIPA installion
was fixed by ensuring that the /etc/hosts file does not contain
multiple entries for the same IP address for other FreeIPA nodes.
During downscale, the selection of which nodes to delete no relies on
the IP address and hostname. In cases where the FQDN hasn't been
assinged, then only the hostname is used.
This was tested by unit tests and by repairing a cluster that repair
was failing on Azure.

CB-11936: Fix FreeIPA HA repair when an IP address is reused

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
integration-test/Makefile
integration-test/scripts/fetch-secrets.sh
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UmsClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/AssignResourceRoleGroupAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/AssignResourceRoleUserAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/DeleteUserGroupAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/ListGroupMembersAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/RemoveUserFromGroupAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/CloudbreakUserCache.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/UmsTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/RunningParameter.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ums/UmsGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ums/UmsTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/BasicEnvironmentVirtualGroupTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/L0UserKeys.java

The related test (`testAddGroupsToEnvironment`) tends to cover:
1. Group
1. test_add_group_to_env
2. test_multiple_groups
3. test_delete_group_from_env
test cases from `CB promotion L0/basic tests` ([cdpmc-qe/tests/regression/users/test_reset_password_flow.py](https://github.infra.cloudera.com/CDH/cdpmc-qe/blob/master/tests/regression/users/test_reset_password_flow.py)).

CB-12197 Introduce authorization tests regarding environment groups

---

structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToStatusDetailsConverter.java
structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredFlowEventToStatusDetailsConverterTest.java

Too long string fileds in CDPStatusDetails caused telemetry logs to exceed the maximum log size, splitting the log into several log entries and preventing the EDH pipeline to successfully collect these events.

CB-12291 Trim too long string fields in CDPStatusDetails.

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResourcesTest.java
common/src/main/java/com/sequenceiq/cloudbreak/service/Retry.java
common/src/test/java/com/sequenceiq/cloudbreak/service/RetryTest.java

* Error handling enhancements:
* `AzureEncryptionResources`:
* Key Vault permission granting is executed as a fault-tolerant logic with retries. At most 15 retries will be performed using delays of 2, 4, 8, 10, 10... sec. (Hence the raw max duration for these operations is expected to be 124 sec.) All exceptions are caught and wrapped in a `Retry.ActionFailedException` for sake of retries.
* Code quality enhancements:
* Add new constructor variants and a factory method to `Retry.ActionFailedException`.
* Testing:
* Manual verification in local CB with various combinations of permissions in the Azure credential app role.
* Added new unit tests and updated existing ones.

CB-12244 Key Vault access permission grant to DES SP may fail

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java

Currently SDX calls two API endpoints in the wrong way, which this fix should correct. It has been already tested.

CB-12382: Make image catalog APIs internally callable by SDX

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureDatabaseTemplateBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorage.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorageTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderDbTest.java

Whenever we create a Private Link on Azure we use the name of the subnet
and the name of the DB server to construct the Private Link name. However,
this name has a length limit of 85 characters. If the name of the subnet
is too long then the cluster creation will fail with the following message:
```
{
"error": {
"code": "PrivateEndpointNameTooLong",
"message": "Call to Microsoft.DBforPostgreSQL/servers failed. Error message: Private Endpoint Name may only be a maximum of 85 characters",
"details": []
}
}
```
To shorten the Private Link name we're going to use the Adler32 algorithm
to get a fix 8 characters long hash of the subnet. The same algorithm is
already used when we create the Storage Accounts.

CB-12360 Azure Private Link name has a length limit of 85 characters

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

In public cloud when HA clusters are created NN service created in Knox topology is expected to have value `hdfs://nn1` instead of `hdfs://<host>:<port>` 
Currently the log that generated topologies using salt does not take this into account. This PR fixes that. 
**Testing**
This patch was tested locally with HA cluster and non-HA cluster
Topology value for HA cluster:
```
<service>
<role>NAMENODE</role>
<url>hdfs://ns1</url>
</service>
```
Topology value for non-HA cluster:
```
<service>
<role>NAMENODE</role>
<url>hdfs://srm-azure-local-ha-dl-master0.srm-azur.xcu2-8y8x.wl.cloudera.site:8020</url>
</service>
```

CB-12352 - [KNOX] Handle the case when NN is HA in Knox topology

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/client/YarnMetricsClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/repair/changeprimarygw/ChangePrimaryGatewayService.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/action/RebootActions.java
redbeams/src/main/java/com/sequenceiq/redbeams/service/network/SubnetListerService.java

Fix String.format("{}") to use "%s" instead.

CB-12411: Fix String.format("{}") to use "%s" instead

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProviderTest.java

-From 7.2.7 Store HBase data on cloud storage for AWS at data lake when the entitlement CDP_SDX_HBASE_CLOUD_STORAGE is disabled and RAZ is disabled
-Add more test cases for this change

CB-10610: Remove CDP_SDX_HBASE_CLOUD_STORAGE entitlement at GA for AWS

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerUpgradeParcelDistributeListenerTask.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerUpgradeParcelDownloadListenerTask.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerUpgradeParcelDistributeListenerTaskTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerUpgradeParcelDownloadListenerTaskTest.java

When we perform an upgrade we need to download and distribute
parcels. This is a long process and we poll the state of these
operations. When the flow is restarted we pre-check the state
of the parcels where we have left off and some of the parcel
states were not considered causing an upgrade failure. For
example when a parcel's status is ACTIVATING that means it's
already downloaded so this state must be considered as well.
This is true for the distributing phase, when a parcel is in
ACTIVATING state that means we've already distribute it.

CB-12464 Fix parcel status polling during upgrade

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/list/ListFreeIpaResponse.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/FreeIpaToListFreeIpaResponseConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/StackToAvailabilityStatusConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverter.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/FreeIpaToListFreeIpaResponseConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/StackToAvailabiltyStatusConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/StackToDescribeFreeIpaResponseConverterTest.java

Add availability status to the FreeIPA list API.
A unit test was added. This was manually tested with a local
deploymnet of cloudbreak.

CB-12497: Add availability status to the FreeIPA list API

---

core/src/main/resources/defaults/blueprints/7.2.10/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-sdx.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-sdx.bp

[CDPD-25222](https://jira.cloudera.com/browse/CDPD-25222)
Initiator running in DL HMS adds up object store listing cost.
Hence setting following config to turn it off.
hive.compactor.initiator.on=false
Testing done:
Have created a DL using a modified sdx template that includes above mentioned config change. DL creation was successful on AWS and config change was applied.

CDPD-25222 Disable hive.compactor.initiator.on in DL HMS

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/loadbalancer/LoadBalancer.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/loadbalancer/TargetGroup.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/TargetGroupRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/TargetGroupPersistenceService.java

Removes the deprecated LoadBalancer and TargetGroup related fields and methods that were replaced
in CB-10578.

CB-10579 Clean up unused targetgroup and loadbalancer columns

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/requests/BlueprintV4Request.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/DeprecatedValidator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidDeprecated.java
core-api/src/test/java/com/sequenceiq/cloudbreak/validation/DeprecatedValidatorTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/blueprint/BlueprintTestDto.java

New error message when submitting URL for BPs
`Submitting Cluster Template by URL is not allowed anymore. Please use text based submission.
You have submitted a field that is not accepted anymore. This is usually due to deprecation or security reasons.`
Please do not MERGE until @aszegedi is finished with the Blueprint changes for the GUI tests.

CB-12511 added DeprecatedValidator to blueprint url based submission

---

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilter.java
core/src/main/resources/defaults/blueprints/7.2.10/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.6/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.7/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-sdx-medium-ha.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-sdx-medium-ha.bp
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilterTest.java

The upgrade is broken for Medium Duty with CCM. Broken means that
the repair phase of the upgrade process will fail. In the repair phase
we're re-creating all the instances with the new cloud image. Until
this bug is not fixed it is not safe to do an upgrade on this cluster
type. In the blueprint there is a field where this can be controlled
however, it's only updated when certain operations are performed like
opening the Shared resources > Cluster templates page or the
Cluster Definitions page on the Data Lake page. There are other operations
that can refresh this field in the database like launching Data Hubs or
the cache expires.

CB-12533 Disable the upgrade for the Medium duty HA template

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/VolumeSetAttributes.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsContextService.java
cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/generator/OfflineStateGenerator.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/CollectDownscaleCandidatesHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MountDisks.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java
core/src/test/java/com/sequenceiq/cloudbreak/reactor/CollectDownscaleCandidatesHandlerTest.java

Some services are sensitive to have the volumes reattached to a machine
with the same FQDN.
* Discovery FQDN now also stored in volumesets
* Discovery FQDN saved the same time as mount info
* For already running clusters, discovery FQDN ges saved at the start of repair
* During bootstraping new nodes, discovery FQDN gets read from volume sets to
set the proper hostname based on instance id

CB-11720 Tie volume sets to discovery FQDNs

---

core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering.bp

[CDPD-25038](https://jira.cloudera.com/browse/CDPD-25038)
To avoid unwanted list calls in object stores setting following config
hive.orc.splits.include.fileid=false
for 7.2.10 & 7.2.11 DE, DE-HA, DE-Spark3 templates.
Testing done:
Have created a datahub cluster using a modified DE template that includes above mentioned config change. Datahub cluster creation was successful on AWS and config change was applied.

CDPD-25038 Disable hive.orc.splits.include.fileid for object stores

---

core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering.bp

[CDPD-24463](https://jira.cloudera.com/browse/CDPD-24463)
This sets hive.hook.proto.events.clean.freq=1h
for 7.2.10 and 7.2.11 DE, DE-HA, DE-Spark3 templates, so that logs are purged
every hour and saves storage cost. This will incur few list calls to object stores every hour.
Testing done:
Have created a datahub cluster using a modified DE template that includes above mentioned config change. Datahub cluster creation was successful on AWS and config change was applied.

CDPD-24463 Hive proto logs not cleared up

---

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsClient.java

Stack update failed. Reason: Failed to create some resource on AWS for upscaled nodes, please check your quotas on AWS. Original autoscaling group state has been recovered. Exception: Cannot execute method: putMetricAlarm. Rate exceeded (Service: AmazonCloudWatch; Status Code: 400; Error Code: Throttling; Request ID: 43c0e282-da14-4c0e-aeac-7f72cf61d278; Proxy: null)

CB-12559 add default client configuration for cloudwatchclient

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaInstanceHealthDetailsService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaStackHealthDetailsService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaInstanceHealthDetailsServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaStackHealthDetailsServiceTest.java

After a FreeIPA HA repair fails, the health checks can throw NPEs. In
some cases the exception affects running the command on other
instances of FreeIPA (e.g. RuntimeException is thrown but only a
FreeIpaClientExcpetion is caught in the loop). The main cause is the
reliance on the FQDN which may be null in the cases where the repair
fails.
This was fixed and tested with unit tests and also it was validated
manually using a local deployment of cloudbreak.

CB-12627: Fix NPE after FreeIPA repair failed

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/BaseImageValidatorE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/PrewarmImageValidatorE2ETest.java

Also disable external database creation to reduce test time.

CB-12595 Fix image id retrieval in base image validation test

---

docker-autoscale/Dockerfile
docker-cloudbreak/Dockerfile
docker-datalake/Dockerfile
docker-environment/Dockerfile
docker-freeipa/Dockerfile
docker-redbeams/Dockerfile

A new Cloudera JDK 11.0.6 image was built to have the latest versions of
openssl and p11-kit to comply to findigs of security checks.

CB-11606 Update docker image parents to latest Cloudera image

---

core/build.gradle

There is a security vulnerability in jetty-util-6.1.26, a transitive dependency of google-oauth-client-jetty. This library is not in use anymore, hence its removal.

CB-11596 (CVE-2017-9735) Removed google-oauth-client-jetty, it is not used anymore

---

cloud-azure/src/main/resources/templates/arm-v2.ftl
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java

Closes [CB-12586](https://jira.cloudera.com/browse/CB-12586).
* Added conditions to check for preceding dependencies
* Use `<#sep>` to separate values in the load balancer `<#list>`
* Add test the AzureTemplateBuilderTest suite.
* Fix a string matcher that expected a leading comma in the dependencies list of the NIC.

CB-12586: Fix missing comma in NIC dependencies of arm template.

---

core/src/main/resources/defaults/clustertemplates/7.2.10/aws/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.10/azure/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.10/yarn/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.11/aws/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.11/azure/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.11/yarn/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.2/aws/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.2/azure/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.2/yarn/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.6/aws/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.6/azure/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.6/yarn/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.7/aws/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.7/azure/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.7/yarn/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.8/aws/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.8/azure/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.8/yarn/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.9/aws/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.9/azure/edgenode.json
core/src/main/resources/defaults/clustertemplates/7.2.9/yarn/edgenode.json
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java

We migrated edge node blueprints as defaults. Now the user won't see them under the Create DataHub -> Custom Tab since we only list user managed blueprints there. This change fixes this by creating default cluster templates that the user will see under the Cluster Definitions tab which is what we promised on the first place.

CB-11868 Create default edge node cluster definitions.

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeDistroxFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeDistroxFlowEventChainFactoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java

Needs to be merged after https://github.com/hortonworks/cloudbreak/pull/10711 and altered to disable the validation in case of the account has entitlement for medium duty upgrade or repair.

CB-12665 Deny repairs and downscale for HA Datahubs

---

datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/DatalakeUpgradeActions.java

Right now runtime is refreshed in datalake service after upgrade.
The experience is upgrade fails usually during image change, so datalake service contains the old runtime.
With this change it will be updated before the image change.

 CB-12538 Move runtime update before image change in datalake service 

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerModelBuilder.java
cloud-azure/src/main/resources/templates/arm-v2.ftl

Closes [CB-10402](https://jira.cloudera.com/browse/CB-10402).
* Fix arm-template issue.
* Refactor AzureLoadBalancerModelBuilder.
I messed up nesting levels of the arm template and had a template that looked like:
```
[
{ "id": "value", "id": "different_value"}
]
```
instead of:
```
[
{"id": "value"},
{"id": "different_value"}
]
```
Causing NICs to be set up belonging to only a single backend address pool, rather than both the public and private pools.
The AzureLoadBalancerModelBuilder is just reordering method definitions to match the invocation and including a javadoc comment.
Tested by creating an Azure Medium Duty DL using the `--no-use-public-ip` and forcing Cloudbreak to set up an Azure environment with the `PublicEndpointAccessGateway.ENABLED` option.
This should simulate the …

CB-10402:  Load balancer support on Azure to enable semi-private networks

---

core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-engineering-ha.bp

1. Last time by mistake added the HTTPFS role into another role.
2. This time created a 7.2.9 cluster by creating a custom template to check its validity in CM.

DISTX-642 Fix incorrect json element position for HTTPFS

---

core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering.bp

screenshot of the property added to hms safety valve:
Adding the property in hms safety valve is not reflecting as expected on beeline cli. So added it to the hive config safety valve which worked.
`0: jdbc:hive2://satyadh-master0.satyates.xcu2> set hive.metastore.try.direct.sql.ddl;
+-----------------------------------------+
|                   set                   |
+-----------------------------------------+
| hive.metastore.try.direct.sql.ddl=true  |
+-----------------------------------------+`

CDPD-25578:Set "hive.metastore.try.direct.sql.ddl" to true

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/CloudbreakCommunicator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/AutoscaleV4Endpoint.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AutoscaleV4Controller.java

Instance Ids for decommission should be part of RequestBody so that it does not cause BufferOverflowException.

CB-12443 Decommission InstanceIds Should be part of RequestBody

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/database/base/DatabaseType.java
core-api/src/main/java/com/sequenceiq/cloudbreak/cloud/VersionComparator.java
core-api/src/main/java/com/sequenceiq/cloudbreak/validation/externaldatabase/SupportedDatabaseProvider.java
core-api/src/test/java/com/sequenceiq/cloudbreak/cloud/VersionComparatorTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/KnoxGatewayServiceRdsConfigProvider.java
core/src/test/java/com/sequenceiq/cloudbreak/service/runtimes/SupportedRuntimesTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentVersionComparatorTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxServiceConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxGatewayConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxServiceConfigProviderTest.java

Tested with Sandor from Knox team we generated the token and communicated with webhdfs
Properties are setted:
knox_gateway_database_type (as of now, only PostgreSQL is supported)
knox_gateway_database_name
knox_gateway_database_host
knox_gateway_database_port
knox_gateway_database_user
knox_gateway_database_password
gateway_service_tokenstate_impl should be set to org.apache.knox.gateway.services.token.impl.JDBCTokenStateService (it's a radio button on CM UI)

CB-11674 Knox needs a DB for Token Management backend

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/repair/changeprimarygw/ChangePrimaryGatewayService.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/repair/changeprimarygw/ChangePrimaryGatewayServiceTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/target/HostAndRoleTarget.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/target/HostAndRoleTargetTest.java

In a FreeIPA HA repair, sometimes old instances are returned by salt
when the instances are checked for their roles. This was fixed by
applying a compound filter which filtered both the role name and the
current instances.
This was tested with unit tests and it was also tested using a local
cloudbreak.

CB-12549: Fix FreeIPA repair when old nodes are returned by salt

---

cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/CollectLoadBalancerMetadataHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/StackCreationFlowConfig.java

Fixes an error in the StackCreation flow so that it handles the COLLECT_LOADBALANCER_METADATA_FAILED_EVENT
correctly. Tested by running CB locally and inducing a LB metadata collection failure.

CB-10773 [HA LB] Datalake create flow timed out instead of terminating gracefully

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltConnector.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/SaltUploadWithPermission.java

FormDataMultiPart was being closed multiple times while it was still
being used. This was fixed so that it is only closed when it is done
being used.
Also some missing toString() methods were added.
This was tested manually with a local deployment of cloudbreak.

CB-12710: Fix closing FormDataMultiPart to not close it early

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/AmbariClusterUpgradeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/credential/PaywallCredentialService.java

During upgrade paywall pillar was not updated, which resulted in failed upgrades.
I've moved the "paywall" entity from paywall.sls to ambari/repo.sls because in legacy cases the top.sls is not updated even if paywall.sls is, moving "paywall" to the repo.sls solved this. 
I've still kept the paywall.sls but renamed the items in it because there could be clusters which already have been upgraded and this way I could avoid having two properties with the same name.

CB-12669 Cluster upgrade should update the paywall pillar

---

core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakApiKeyEndpoints.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakClient.java
core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakServiceCrnEndpoints.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXUpgradeAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/DistroXTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/cluster/DistroXUpgradeTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
integration-test/src/main/resources/testsuites/e2e/distrox-upgrade-tests.yaml

This test case is required to test the functionality of the DistroX cluster upgrade.
After a proper environment has created, we need to upgrade the SDX first, then we can proceed with the DistroX upgrade.
When we call the DistroX upgrade endpoint with the proper runtime version the CB should select a new image and upgrade the CM and CDH components for the new runtime version.

CB-12372: Create e2e test for distroX upgrade.

---

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/request/CustomImageCatalogV4CreateImageRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/request/CustomImageCatalogV4UpdateImageRequest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4GetImageResponse.java
core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/CustomImageCatalogV4Controller.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/CustomImageCatalogService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/CustomImageCatalogV4ControllerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/image/CustomImageCatalogServiceTest.java

In case of custom image's query operation the related source creation date is also provided.
One option was to persist the date in the database, but this value can change so it should always be updated, so only this value will be retrieved at the moment of the query and sent as part of the response.

CB-12543: sourceImageDate missing from custom images

---

template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/knox/KnoxServiceConfigProviderTest.java

Mocking methods any() and anyString() cannot be used outside of mocks.

CB-12779: Fix KnoxServiceConfigProviderTest unit test

---

environment/src/main/java/com/sequenceiq/environment/environment/validation/cloudstorage/CloudStorageLocationValidator.java
environment/src/main/java/com/sequenceiq/environment/environment/validation/cloudstorage/EnvironmentLogStorageLocationValidator.java

Currently user may use gcs://cloudbreak-dev/rdoktorics/telemetry insteand of gs:// url. We should be explicit to enforce a gs:// protocol.

CB-12098: explicit gcp backup location validation

---

integration-test/integcb/Profile_template
integration-test/scripts/docker-compose.sh
integration-test/scripts/stop-containers.sh

The [default CB communication tunnel](cloudbreak/environment/src/main/resources/application.yml) type is `DIRECT`, but on [QA Cloud Test Environment](https://qa-cloud-canary.eng.hortonworks.com) it has been changed to `CLUSTER_PROXY`. However, all of our tests still use `DIRECT` connection. So we need to change our tests' default environment creation steps to include `with Cluster Proxy`.

CB-12691 Introduce new step for default environment create method with Cluster Proxy

---

common/src/main/java/com/sequenceiq/cloudbreak/util/JaxRSUtil.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/utils/JaxRSUtilTest.java

Encountered this NPE during a failed cluster creation, this NPE during error handling prevented further logs from being collected.

 CB-12711 NPE if mediaType is null

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

Currently the default socket timeout and connection timeouts are default (120s) which appear to be low in some cases. 
It was requested [CB-12550](https://jira.cloudera.com/browse/CB-12550) to increase the timeout to bring it in line with that of other services like CM. 
This PR increases the socket timeout for Atlas and Atlas API service to 5m.

CB-12550 - [Knox] Increase sockettimeout and connection timeout values for ATLAS dispatches

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/userpasswd/ClusterCredentialChangeActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cmdiagnostics/event/CmDiagnosticsCollectionEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/event/DiagnosticsCollectionEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/ClusterCredentialChangeTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/resource/ClusterCredentialChangeRequest.java
core/src/test/java/com/sequenceiq/cloudbreak/FlowPayloadConstructorTest.java
datalake/src/test/java/com/sequenceiq/datalake/FlowPayloadConstructorTest.java
environment/src/test/java/com/sequenceiq/environment/FlowPayloadConstructorTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/FlowPayloadConstructorTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/FlowPayloadConstructorTest.java

In case of flow redistribution and restart (e.g. pod restart) the payload classes
stored in the 'flowlog' table cannot be deserialized in case of missing public
constructors.

CB-12817 Test flow event classes for public constructor

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java

Remove old salt minon keys fromr the FreeIPA primary gateway during a
repair.
This was tested manually using a local deployment of cloudbreak. Unit
tests were updated.

CB-12781: Remove old salt minion keys from FreeIPA PGW after repair

---

core/src/main/resources/defaults/vm-logs.json
freeipa/src/main/resources/defaults/vm-logs.json

The log locations to collect the info is updated based on the recent changes where we introduced two log files(access, out) for jumpgate agent in [CDPAM-1553](https://jira.cloudera.com/browse/CDPAM-1553)

CDPAM-1763 | Ship jumpgate agent logs from access and out logs at the time of env creation

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResourcesTest.java
environment/src/test/java/com/sequenceiq/environment/environment/encryption/EnvironmentEncryptionServiceTest.java

Inorder to to remove the Service principal(SP) access for Disk encryption set(DES) from key vault, following parameters are required -
1. key vault name
2. key vault resource group.
3. DES SP id.
With CB-9920(Phase 1), keyVault resource group is same as des resource group.
For phase 2, where desResourceGroup can be different from keyVaultResourceGroup, it will be taken care off as part of CB-11927.

CB-12395: DES SP access is not removed from Key Vault when deleting DES

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonClusterManagerProperties.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
integration-test/src/main/resources/application.yml

Create separate properties for distrox upgrade e2e test to set the proper runtime versions

CB-12764: Create separate properties for distrox upgrade e2e test to set the proper runtime versions

---

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverter.java
core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateV1ToInstanceTemplateV4Converter.java
core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateV1ToInstanceTemplateV4ConverterTest.java

* Handle the case when the input `InstanceTemplateV1Request` has `azure == null`; Azure disk SSE with CMK will be applied to the DH disks even in such scenarios if the environment has prescribed it so. This fixes the former broken logic of #10371 that failed to apply disk encryption for such requests.
* Testing: Manual verification in local CB; updated existing UT.

CB-12842 Azure disk SSE with CMK fix for DH request azure == null

---

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/clouderamanager-ssl-user-facing.conf

Before the change with the jdbc url `jdbc:impala://satyadh2-master0.satyates.xcu2-8y8x.dev.cldr.work:443;transportMode=http;httpPath=cliservice;ssl=1;AuthMech=3;AllowSelfSignedCerts=1;`

CB-11855:PowerBI compatibility: Setup default impala pathways for Knox

---

freeipa/src/main/java/com/sequenceiq/freeipa/kerberos/v1/KerberosConfigV1Service.java
freeipa/src/main/java/com/sequenceiq/freeipa/ldap/v1/LdapConfigV1Service.java

Sometimes bind user creation can fail with unexpected issues like timeout.
Adding `@Retryable` to provide a more stable experience during cluster provisioning.

CB-12853 Add `@Retryable` to LDAP and Kerberos bind user creation

---

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/JidInfoResponseTransformer.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStates.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/JidInfoResponseTransformerTest.java
orchestrator-salt/src/test/resources/jid_highstate_already_running_response.json

details:
- there is a use case when jid has already running, then the response format is a string in an array.
- by default it means an error, but this is a specific edge case, that needs to be handled.
- also checked some UTs, to make sure this is parsed afrer JSON based transformations (with files for UTs) updated the regex

CB-12877. Salt Failure When Creating Datalake.

---

freeipa/src/main/java/com/sequenceiq/freeipa/controller/OperationV1Controller.java

OperationV1Controller is now internal ready, but fails if no account id is specified.

 CB-12891 Fix NullPointer during fetching operation status 

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnectorTest.java

This commit adds an extra check to recreate the ARM template instead of reusing it if it is already finished (meaning its status is not ResourceStatus.IN_PROGRESS)

CB-8382 - [azure] ARM template is redeployed if it exists

---

core/src/main/java/com/sequenceiq/cloudbreak/service/image/DefaultImageCatalogService.java

The filter stream was extended with ignore case sensitive check for provider name.

CB-12903: Freeipa default image qurey not possible by using getImageFromDefaultCatalog

---

common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/JobCountMetricConfigurator.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/JobMetricsListener.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/QuartzMetricTag.java
common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/TriggerMetricsListener.java

Change metric tags in order to use different selectors for jobs and triggers in DataDog.
Fix trigger delay calculation.

CB-12449 Improve quartz metrics to monitor jobs and triggers

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/action/AzureCloudBlobClientActions.java
integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml

Minor refactor added to azure storage creator to reduce time to fail. 60 seconds should be enough.
GCP test will be skipped in first iteration

CB-12410 adding base medium duty SDX testcase to our testsuite

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/User.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/UserDisableOperation.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/UserEnableOperation.java
freeipa-client/src/test/java/com/sequenceiq/freeipa/client/operation/UserDisableOperationTest.java
freeipa-client/src/test/java/com/sequenceiq/freeipa/client/operation/UserEnableOperationTest.java

The FreeIPA User model was updated to include the nsaccountlocked field.
This field is used by FreeIPA to enable/disable users. Operations and methods
were added to the FreeIpaClient to invoke the user_enable and user_disable
APIs.

CDPCP-4714. Add FreeIPA calls to enable and disable users

---

core/src/main/java/com/sequenceiq/cloudbreak/util/StackUtil.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/model/Node.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/mount-disks.j2

When the temporaryStorage attribute (coming from an internal datahub post request) is set to EPHEMERAL_VOLUMES, instance storage should be mounted on the nodes under /hadoopfs/ephfsX.

CB-12505 Mount ephemeral volumes to different file path based on temporary storage value

---

autoscale/src/main/resources/schema/app/20210603143940_CB-12843_Make_sure_we_have_PKs_on_every_CB_table.sql
core/src/main/resources/schema/app/20210603141929_CB-12843_Make_sure_we_have_PKs_on_every_CB_table.sql
freeipa/src/main/resources/schema/app/20210603143524_CB-12843_Make_sure_we_have_PKs_on_every_CB_table.sql
redbeams/src/main/resources/schema/app/20210603144403_CB-12843_Make_sure_we_have_PKs_on_every_CB_table.sql

Public key is necessary for maintaining replica identity in postgres, in this pull request I've added pkey where it was missing.

CB-12843 Make sure we have PKs on every CB table

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResourcesTest.java

CB-12565: DES deletion and env termination fail if the RG name contains a dot
This PR fixes the regex pattern to extract resource group name from resource id, specifically for disk encryption set (DES).
As per Azure documentation, resource group name - Can include alphanumeric, underscore, parentheses, hyphen, period (except at end), and Unicode characters that match the allowed characters. 'RESOURCE_GROUP_NAME' pattern is updated to extract the name correctly.

CB-12565: DES deletion and env termination fail if the RG name contains a dot

---

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java
orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestratorTest.java

This removes old/dead salt minions that no longer exist on salt masters before bootstrapping new salt master nodes.

CB-12188 Remove old salt minions before boostrap

---

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/parameters/dao/domain/AzureParameters.java
environment/src/main/java/com/sequenceiq/environment/parameters/v1/converter/AzureEnvironmentParametersConverter.java
environment/src/main/java/com/sequenceiq/environment/parameters/validation/validators/parameter/AzureParameterValidator.java
environment/src/main/resources/schema/app/20210525113034_CB-12118_persistence_for_encryptionKeyResourceGroupName_on_Azure.sql
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/v1/converter/AzureEnvironmentParametersConverterTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/validation/validators/AzureParameterValidatorTest.java
structuredevent-model/src/main/java/com/sequenceiq/environment/parameter/dto/AzureResourceEncryptionParametersDto.java
structuredevent-model/src/test/java/com/sequenceiq/environment/parameter/dto/AzureParametersDtoTest.java
structuredevent-model/src/test/java/com/sequenceiq/environment/parameter/dto/AzureResourceEncryptionParametersDtoTest.java

CB-12118: Environment backend change: Add converters, validation and persistence for encryptionKeyResourceGroupName on Azure
Followig changes are made as part of this PR.
1. EnvironmentApiConverter, AzureResourceEncryptionParametersDto, EnvironmentResponseConverter are updated to include encryptionKeyResourceGroupName.
2. encryptionKeyResourceGroupName can only be present if the entitlement 'CDP_CB_AZURE_DISK_SSE_WITH_CMK' is true and encryptionKeyUrl is present - a validation is added.
3. encryption_keyUrl was deprecated as part of CB-11874, relating code and DB column is dropped.
4. Unit tests are updated for above changes.

CB-12118: Environment backend change: Add converters, validation and persistence for encryptionKeyResourceGroupName on Azure

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/cruisecontrol/CruiseControlRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/cruisecontrol/CruiseControlRoles.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/cruisecontrol/CruiseControlRoleConfigProviderTest.java

Created a configuration provider for Cruise Control. It sets the self healing goals and their parameters which is specific in DataHub and cannot go as defaults into the CSD.
Update:
Commit 4e03a23 resolves a merge conflict in _CMRepositoryVersionUtil.java._
Commit d4413ed adds unit tests and modifies commit message as recommended

CB-10914 Create config provider for Cruise Control

---

core/src/main/resources/definitions/upgrade-matrix-definition.json

- `.` is replaced with `\\.` so it would be escaped in Java
- `[0,1,2,3,10]` like has been replaced with `(0|1|2|3|10)`. The first mean any of these: `0` `1` `2` `3` `,`

CB-12943 Fix upgrade matrix to contain valid regex

---

freeipa/src/main/java/com/sequenceiq/freeipa/FreeIpaFlowInformation.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/FreeIpaHaApplication.java

Flows were never added as restartable, in case of a pod restart these won't be restarted.
Fixed a wrong import, which could caused invalid flows won't be canceled.

CB-12935 Add missing flows to restartable list 

---

freeipa/src/main/resources/application.yml

The FreeIPA server deletion continues to run after the FreeIPA API
returns. FreeIPA can continue processing this request for 180 seconds
for the ca topology suffix and 180 additional seconds for the domain
suffix. So the total is 360 seconds. It is unclear if the deletion of
2 servers run concurrently or not so this time allows for enough time
so that it can run consecutively. Some additional time was also added.

CB-12980: Add additional delay when waiting for FreeIPA server_del

---

integration-test/Makefile
integration-test/scripts/docker-compose.sh

Add new checks to the pull-request-builder-schema-compatibility-test. These checks will ensure that new tables without PK are not allowed anymore.

CB-12843 Make sure we have PKs on every CB table, add jenkins check

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java

TestContext's [whenException](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java#L266) was not failing in case of the expected exception has not been thrown and the doAction goes through with no error.
So we should put a related exception to the getExceptionMap() in case of the expected exception has not been thrown.

CB-12906 whenException does not throw TestFailException in case of error

---

cloud-azure/src/main/resources/definitions/azure-enabled-regions.json

Azure no longer supports southafricawest, germanynorth and norwaywest regions.

CB-12945 Remove unsupported Azure regions

---

integration-test/scripts/docker-compose.sh

Check instantly exited without error message because of "set -e".

CB-12843 Make sure we have PKs on every CB table, message fix

---

autoscale/src/main/java/com/sequenceiq/periscope/config/DatabaseConfig.java
common/src/main/java/com/sequenceiq/cloudbreak/common/database/BatchProperties.java
common/src/main/java/com/sequenceiq/cloudbreak/common/database/JpaPropertiesFacory.java
common/src/main/java/com/sequenceiq/cloudbreak/common/tx/HibernateStatementStatistics.java
core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterBuilderService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/start/ClusterStartService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartStopService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/install/FinalizeClusterInstallHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/HostMetadataSetup.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackScalingService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/HostMetadataSetupTest.java
datalake/src/main/java/com/sequenceiq/datalake/configuration/DatabaseConfig.java
environment/src/main/java/com/sequenceiq/environment/configuration/DatabaseConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/configuration/DatabaseConfig.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterUpscaleDownscaleTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/configuration/DatabaseConfig.java

Increase test node count for upscale and downscale to check large clusters.
Enable batch inserts and updates.
Run fetch and saveAll in one transaction otherwise hibernate detaches the loaded entites and it will run a select for every entity during saveAll.

CB-12852 DH couldn't be created because of n+1 query error

---

cloud-azure/src/main/resources/templates/arm-v2.ftl

Closes [CB-12631](https://jira.cloudera.com/browse/CB-12631).
Add user created tags to Load Balancers deployed in Azure.
See screenshot for example:

CB-12631: Add tags to Azure Load balancers.

---

environment/src/main/java/com/sequenceiq/environment/environment/encryption/EnvironmentEncryptionService.java
environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/ResourceEncryptionDeleteHandler.java
environment/src/main/java/com/sequenceiq/environment/resourcepersister/CloudResourceRetrieverService.java
environment/src/main/java/com/sequenceiq/environment/resourcepersister/ResourceRepository.java
environment/src/main/java/com/sequenceiq/environment/resourcepersister/ResourceService.java
environment/src/test/java/com/sequenceiq/environment/environment/encryption/EnvironmentEncryptionServiceTest.java
environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/ResourceEncryptionDeleteHandlerTest.java

CB-12325: DES resource may sometimes be left behind during environment delete
In few cases, the flow to create DES(Disk encryption set) during environment creation might result in failure after creating DES i.e; the resource is created at Azure cloud but the process itself failed to complete, leading to dangling DES in Azure cloud.
Cases where DES process can fail - Lack of adequate permissions to set DES correctly, environment service failure e.t.c
DES is created only when encryption key url is present in AzureResourceEncryptionParametersDto. Further, encryption key url can only be present in AzureResourceEncryptionParametersDto if entitlement to enable SSE with CMK is enabled for the account. So, Inorder to delete DES, checking for presence of encryption key url is sufficient.
During …

CB-12325: DES resource may sometimes be left behind during environment delete

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitFailedChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitOperationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitTerminationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/cloudbreak/CloudbreakWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceFailedChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceOperationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceTerminationChecker.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceWaitObject.java

Azure API E2E DistroXEncryptedVolumeTest/testCreateDistroXWithEncryptedVolume is does not failing even the `status=CREATE_FAILED`.
I found that the [exitWaiting method](https://github.com/hortonworks/cloudbreak/blob/CB-2.44.0/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitOperationChecker.java#L67-L70) returns only a boolean:
```
if (waitObject.isCreateFailed()) {
LOGGER.info("'{}' the polled resource entered into creation failed state. Exit waiting!", name);
return true;
}
```
However here a `throw new TestFailException` would be expected as well.

CB-13013 WaitOperationChecker exitWaiting does not throw exception in case of isCreateFailed

---

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java
auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/AbstractUmsAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/AssignResourceRoleGroupAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/AssignResourceRoleUserAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/UnassignResourceRoleAction.java

This issue has been created because of [CB-12990](https://jira.cloudera.com/browse/CB-12990): Currently we just call these GRPC UMS operations from CB but not checking for response that could lead to issues regarding resources without proper assignment.
We do not want to add `@Retryable` to `assignResourceRole` and `unassignResourceRole` at `auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java`. So I've introduced the mentioned  `Retry logic` at test project level as `com/sequenceiq/it/cloudbreak/action/ums/AbstractUmsAction.java`.

CB-13029 Introduce retry logic to resource role assignment

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/update_cnames.sh

Fix shellcheck warnings in update_cnames.sh.

CB-13046: Fix shellcheck warnings in update_cnames.sh

---

environment/src/main/resources/schema/app/20210525113034_CB-12118_persistence_for_encryptionKeyResourceGroupName_on_Azure.sql
environment/src/main/resources/schema/app/20210615104527_CB-13096_Environment_DB_encryption_keyurl_schema_bug_fix.sql

Re-adds the deprecated column `environment_parameters.encryption_keyurl` that got accidentally and prematurely removed in #10756. The column removal is now postponed to a future release to keep schema compatibility across subsequent versions.

CB-13096 Environment DB encryption_keyurl schema bug fix

---

cloud-aws-cloudformation/scripts/vertical-scaling/root-volume/README.md
cloud-aws-cloudformation/scripts/vertical-scaling/root-volume/increase-root-volume.sh
cloud-azure/scripts/vertical-scaling/root-volume/README.md
cloud-azure/scripts/vertical-scaling/root-volume/increase-root-disk-1-azure.sh
cloud-azure/scripts/vertical-scaling/root-volume/increase-root-disk-2-azure.sh

DH upgrades require more than 50GB root volume, and almost all prod clusters are at 50GB root disk. The steps to adjust the root size is manual. Given a DH with many nodes it is very cumbersome to go through each node manually and increase the root volume.
The scripts provided here for AWS and Azure help with that: they increase the root volume of provided instances. README files guide customers on how to use the scripts.

CB-12562 Script to increase root volume to 100GB

---

core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AwsEnvironmentNetworkConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/AzureEnvironmentNetworkConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/GcpEnvironmentNetworkConverterTest.java

Related to [CB-12979](https://jira.cloudera.com/browse/CB-12879).
I'm touching code in the parent class, `EnvironmentBaseNetworkConverter.java` and want to add regression tests to make sure I don't break anything.

CB-12879-1: Add tests around GcpEnvironmentNetworkConverter

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/InstanceMetadataUpdater.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateActionsTest.java

Previous CB-12684 disabled package version check during upgrade only in one part. There was another invocation of check package versions. This commit turns of checking package versions also for that other invocation

CB-13081 DL upgrade on azure: package version check still throws

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudInstance.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/generic/DynamicModel.java
cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/model/generic/DynamicModelTest.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetaDataCollectorTest.java
common/src/main/java/com/sequenceiq/cloudbreak/util/NullUtil.java
common/src/test/java/com/sequenceiq/cloudbreak/util/NullUtilTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/instancegroup/instancemetadata/InstanceMetaDataV4Response.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceMetaData.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/InstanceMetaDataToCloudInstanceConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/instancegroup/InstanceMetaDataToInstanceMetaDataV4ResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java
core/src/main/resources/schema/app/20210604170759_CB-12910_Populate_rackId_in_InstanceMetaData_core.sql
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/InstanceMetaDataToCloudInstanceConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/instance/InstanceMetaDataToInstanceMetaDataJsonConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/instancegroup/InstanceMetaDataToInstanceMetaDataV4ResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupServiceTest.java

* Changes to `InstanceMetadata` (core):
* Add `availabilityZone` and `rackId`.
* Migration for existing records:
* Populate `subnetId` if unset from `Network.attributes`.
* Populate `availabilityZone` from `Stack`.
* Populate `rackId` using `availabilityZone`, falling back to `subnetId` if `availabilityZone` is `NULL` or `''`, and set to `'default-rack'` if `subnetId` is also `NULL` or `''`.
* Populate `subnetId` and `availabilityZone` in AWS `CloudInstance` objects using dynamic parameters.
* Changes to `DynamicModel`:
* Make parameter map mutable.
* Constructor treats `null` map argument as if an empty map had been passed in.
* Eliminate unsafe casts.
* Add javadoc.
* `MetadataSetupService.saveInstanceMetaData()` (core): Populate `availabilityZone` and `rackId` from `CloudInstance`. …

CB-12910 Populate rackId in InstanceMetaData (core)

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaOperationDescriptions.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/DetailedStackStatus.java
freeipa/src/main/java/com/sequenceiq/freeipa/FreeIpaFlowInformation.java
freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/update/SaltUpdateActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/update/SaltUpdateEvent.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/update/SaltUpdateFlowConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/update/SaltUpdateState.java
freeipa/src/main/java/com/sequenceiq/freeipa/orchestrator/SaltUpdateService.java

A new flow introduced with an endpoint to enable FreeIPA salt states update. Steps:
- push down state files
- push down the pillars
- run highstate

CB-12459 Salt state update flow for FreeIPA

---

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/conversion/FmsUserConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/FmsUser.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersStateDifference.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/conversion/FmsUserConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersStateDifferenceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/ums/BaseUmsUsersStateProviderTest.java

Previous commits added the fields that represent whether an
actor is disabled to the models retrieved from the UMS and
from IPA. This commit now propagates those fields to the FMS's
internal user model for comparing users between the UMS and IPA.
The code for calculating the difference between the UMS and IPA
states was updated to not use the FmsUser.equals() method since
that method now includes the new field. The unit tests were
updated to ensure that the new calculation of users to add to
IPA works correctly.

CDPCP-4714. Add enabled state to FMS user model

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/encryption/DiskEncryptionSetCreationRequest.java
cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/model/encryption/DiskEncryptionSetCreationRequestTest.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResourcesTest.java
environment/src/main/java/com/sequenceiq/environment/environment/encryption/EnvironmentEncryptionService.java
environment/src/test/java/com/sequenceiq/environment/environment/encryption/EnvironmentEncryptionServiceTest.java

CB-12737: Update the creation/deletion of disk encryption set(DES) if encryption-key-resource-group-name is provided.
With CB-11927, `--encryption-key-resource-group-name` was introduced so that the environment resource group can be different from the key vault's resource group holding the encryption key.
This PR uses encryptionKeyResourceGroupName while creating and deleting the DES.
1. During creation, `grantKeyVaultAccessPolicyToDiskEncryptionSetServicePrincipal` uses the encryptionKeyResourceGroupName to provide necessary permissions to DES.
2. During deletion, `removeKeyVaultAccessPolicyFromDiskEncryptionSetServicePrincipal` fetches the encryptionKeyResourceGroupName from the disk encryption set's active key to remove permissions from keyVault for this DES.
In order to test, the …

CB-12737: Update the creation/deletion of disk encryption set if encryption-key-resource-group-name is provided

---

core/src/main/resources/defaults/blueprints/7.2.10/cdp-rt-data-mart.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-rt-data-mart.bp
core/src/main/resources/defaults/blueprints/7.2.8/cdp-rt-data-mart.bp
core/src/main/resources/defaults/blueprints/7.2.9/cdp-rt-data-mart.bp

The Real Time DataMart blueprints use the default Ranger service
repository name for Kudu, which is cm_kudu. Each RTDM DataHub is
supposed to have its own Ranger service repo for Kudu.
Kudu CSD recognizes the "{{GENERATED_RANGER_SERVICE_NAME}}" magic string
and uses the CM-generated unique service repo name.

CB-13227 Create separate Ranger repo for each Kudu

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/InstanceStoreMetadata.java
cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/model/InstanceStoreMetadataTest.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsAttachmentResourceBuilder.java
cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilder.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilderTest.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsPlatformParameters.java
cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/view/AwsGroupView.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilder.java
common-model/src/main/java/com/sequenceiq/common/model/AwsDiskType.java
core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/service/StackCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackStopRestrictionService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/service/StackCreationServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackStopRestrictionServiceTest.java

Instance storage/ephemeral storage should be requested always, regardless of storage type selected.

CB-12939 Always request instance storage on AWS

---

cloud-azure/src/main/resources/templates/arm-v2-freeipa.ftl
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StackRequestManifesterTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/template/InstanceTemplateRequestToTemplateConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/CreateFreeIpaRequestToStackConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProvider.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/InstanceGroupRequestToInstanceGroupConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/template/InstanceTemplateRequestToTemplateConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/converter/stack/CreateFreeIpaRequestToStackConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProviderTest.java

CB-12426: Encrypt FreeIPA, DL disks with CMK
The disk encryption set created during environment creation as part of 'ResourceEncryptionInitialization', is now used to encrypt the freeIPA and Datalake disks.
Attaching screenshots for freeIPA and datalake disks encryption with CMK.
**1. Template with DiskEncryptionSetId value set for the VM of freeIPA**
**2. FreeIPA VM disk with encryption as `SSE with CMK`.**
**3. Datalake VM disk with encryption as `SSE with CMK`.**
**4. Template with DiskEncryptionSetId value set for the VM of Datalake.**
**5. DiskEncryptionSet showing the Datalake and FreeIpa Disks as an attached resources.**
**6. Datalake nodes in cdp console**
**7. FreeIPA node in cdp console**

CB-12426: Encrypt FreeIPA, DL disks with CMK.

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/UserAddOperation.java
freeipa-client/src/test/java/com/sequenceiq/freeipa/client/operation/BatchOperationTest.java
freeipa-client/src/test/java/com/sequenceiq/freeipa/client/operation/UserAddOperationTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProvider.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersStateDifference.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProviderTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncServiceTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/user/model/UsersStateDifferenceTest.java

The UserSyncService now enables and disables users based on their state
in the UMS.
UserDisableOperations are invoked for users that exist in IPA that need to be
disabled. The UserAddOperation is updated to add disabled users to IPA. This happens
as a single operation to avoid any potential issues if user sync fails between
adding a user and disabling a user.
UserEnableOperations are invoked for users that exist in IPA that need to be enabled.
The FreeIpaUserStateProvider was fixed to correctly set the enablement state.
The state is returned as a negative flag (true indicates disabled). The previous
commit introducing this to the model had the flag reversed.

CDPCP-4714. User sync disables and enables users

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/AssignResourceRoleUserAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/UnassignResourceRoleAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ums/UmsTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/BasicEnvironmentVirtualGroupTest.java

MOW Dev API E2E test build is failing, because of testAddGroupsToEnvironment test is failing with:
```
com.sequenceiq.it.cloudbreak.exception.TestFailException: EXCEEDING UMS ACTION MAX. RETRY (11) ::: UMS action has been failed, because of: NOT_FOUND: Cannot find resource role...
```
So I'm introducing an additional step to the `UnassignResourceRoleAction` with a pre-check for resource role has already been revoked from user.

CB-13233 Prepare UnassignResourceRoleAction for NOT_FOUND case

---

cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/ComponentTestUtil.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/metadata/AwsNativeMetadataCollector.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilder.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNativeMetadataCollectorTest.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpResourceConnector.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpResourceConnectorTest.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/AbstractResourceConnector.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/CloudFailureHandler.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceService.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceCreationCallable.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/group/GroupResourceService.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/init/ResourceBuilders.java
cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/network/NetworkResourceService.java
core/build.gradle

**Changes**
- map CloudInstance to CloudResource with private id if necessary in AwsNativeMetadataCollector
- group resource connectors by Variant instead of Platform
- include `cloud-aws-native` module in `core` modul

CB-12898 AWS native metadata collector fix and group resource connectors by cloud platform vairant

---

freeipa/src/main/resources/freeipa-salt/salt/freeipa/init.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/replica-install.sls
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_promote_replica_to_master.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_replica_install.sh
freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/initdnarange.py

When a FreeIPA first instance is installed it allocates an id range with a size of 200000. The FreeIPA allocates ids from the beginning of this range when creating a user or a group.
After a replica is added to the existing FreeIPA domain it will ask for an id range when first time it needs an id, like the first time a user is added on that instance. In this case another FreeIPA master which already has an id range set, will give the upper half of it range to the one without a range. This behavior has 2 consequences:
- a FreeIPA instance/replica can exist without an id range for indefinitely long time
- with every new replica another instance can "loose" half of its range available
With this commit after replica install every replica will run a script to try to allocate ID range for …

CB-13259 FreeIPA replica DNA ID range initialization

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/deserializer/BooleanDeserializationProblemHandler.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/deserializer/ListFlatteningDeserializer.java
freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/User.java

Corrects the following error, discovered during manual testing of recovery:
Failed to create kerberos bind user: [kerberosbind-dp-re-17]com.sequenceiq.freeipa.client.RetryableFreeIpaClientException: Invoke FreeIPA failed: Cannot deserialize instance of `java.lang.Boolean` out of START_ARRAY token at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.sequenceiq.cloudbreak.client.RPCResponse["result"]->com.sequenceiq.freeipa.client.model.User["nsaccountlock"]

CB-13303 -  Failed to create kerberos bind user during recovery testing

---

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxBackupResponse.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxBackupStatusResponse.java
datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxDatabaseBackupStatusResponse.java
datalake-dr-connector/src/main/java/com/sequenceiq/cloudbreak/datalakedr/DatalakeDrClient.java
datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreService.java
flow-api/src/main/java/com/sequenceiq/flow/api/model/FlowCheckResponse.java
flow/src/main/java/com/sequenceiq/flow/service/FlowService.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxBackupAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractSdxTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/SdxBackupTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/AwsCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/AmazonS3Util.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/action/S3ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/client/S3Client.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/AzureCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/AzureCloudBlobUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/action/AzureCloudBlobClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/FlowUtil.java
integration-test/src/main/resources/testsuites/e2e/l0promotion/aws-sdx-backup-tests.yaml

A new SDX Backup test case for L0 tests.
Beyond the new test case I've introduced:
- new operations at SDX API Endpoint:
- `getBackupDatalakeStatusByName`: is needed for the `validateDatalakeBackupStatus` of `SdxBackupTest` 
- `getBackupDatalakeStatusById`: this is for clarify, because of the `backupDatalakeStatusByName` operation is actually points to the `getBackupStatusByBackupId` at the `datalakeDrClient`.
- fixed some typos
- new request at Datalake DR Client:
- `getBackupStatusByDatalakeName`: is needed for the `getBackupDatalakeStatusByName` new SDX API operation
- updated the SDX Controller and SDX Backup/Restore Service as well based on the above changes
- updated the Flow Util and Service with `getLatestFlowFinalizedAndFailed`: to stabilise the IT module wait for flow feature

CB-13252 Create new L0 test for Datalake Backup

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerModelBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/loadbalancer/AzureLoadBalancingRule.java
cloud-azure/src/main/resources/templates/arm-v2.ftl
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java
common-model/src/main/java/com/sequenceiq/common/api/type/TargetGroupType.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/kerberos/CmServiceKeytabRequestFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/FreeIPAEndpointManagementService.java
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering-ha.bp
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java
core/src/test/resources/input/de-ha.bp
orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/init.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/generate_agent_tokens.sh.j2
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/setup-autotls.sh.j2
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/oozie/OozieHAConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/oozie/OozieRoleConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/oozie/OozieHAConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/oozie/OozieRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/resources/input/de-ha.bp

1. In public cloud all the requests go through Knox, so we do not need a external load-balancer for external clients.
2. CM configuration for multiple Oozie hosts demands a load-balancer to be configured.
3. This is for Hue and Yarn to access the Oozie in HA fashion.
4. For AWS and Azure use an internal load-balancer.
5. For GCP we do not have any load-balancers, so as a workaround use the current Oozie server address for url and callbacks.
6. To make Hue to Oozie interaction work via load-balancer, Hue is moved to a new hostgroup. Since there is only one instance for GCP for manager node, Hue is also added to masterx hostgroup.
7. CM is given ability to add hosts.
8. LB reverse IP is added.
9. Knox proxy hosts are configured even if we failed to acquire Let's Encrypt certificate. …

CRB-1587 Release a first version of Oozie HA from 7.2.11

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/client/FreeipaClientTestService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/client/FreeipaClientTestServiceTest.java

Group-find with the 'all' parameter is very slow. Anecdotally, for ~7000
groups, it takes > 5 minutes while running without the 'all' parameter
only takes ~10 seconds. The 'all' parameter was removed from FreeIpaClient.groupFindAll
to improve user sync performance.
A search of the codebase revealed only two usages of the FreeIpaClient.groupFindAll
command: user sync and the freeipa client test service.
The freeipa client test service only needs to retrieve a single group at a time. This
code was updated to use group-show instead of group-find.
User sync only requires the group names when finding all the groups and does not need
the other infromation returned with the 'all' parameter.

CB-13357. Remove 'all' param from IPA group find command

---

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/error/mapper/ClouderaManagerStorageErrorMapper.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerTemplateInstallationChecker.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/error/mapper/ClouderaManagerStorageErrorMapperTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerTemplateInstallationCheckerTest.java

* `ClouderaManagerStorageErrorMapper`:
* Add null checks for several properties that could cause NPE.
* Message formatting improvements for that RAZ enabled scenario.
* `ClouderaManagerTemplateInstallationChecker`:
* `CloudStorageConfigurationFailedException` may only be thrown in case of DL.
* Fix regex that is used to determine whether to throw a `CloudStorageConfigurationFailedException`.
* Extend unit tests and add new ones.

CB-13349 CM cloud storage error mapping fixes

---

cloud-aws-cloudformation/src/main/resources/definitions/aws-datalake-backup-policy.json
cloud-aws-cloudformation/src/main/resources/definitions/aws-datalake-restore-policy.json

Closes [CB-12913](https://jira.cloudera.com/browse/CB-12913).
Check the AWS policy for Datalake backup + restore into cloudbreak so that we can refer to the policies from the public facing documentation.
I arrived at these values by creating a bucket outside of the normal permissions, and running backup restore while whittling the permissions down.
These policies are more permissive than they absolutely have to be, but they're also simpler for it.
The most restrictive/specific policies would include separate policies for Admin, Logger, and Ranger roles when restoring.
This issue is related to updating the public facing docs in [CB-12981](https://jira.cloudera.com/browse/CB-12981).

CB-12913: Add backup and restore policies for S3.

---

datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java
datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/handler/DatalakeFullRestoreWaitHandler.java
datalake/src/test/java/com/sequenceiq/datalake/flow/SdxReactorFlowManagerTest.java
datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java

Currently, backup is triggered on every upgrade if the necessary entitlement is enabled.
Instead, it should be invoked conditionally only in the use cases it is supported.

CB-13318: Automatic backup should be triggered conditionally.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/SdxBackupTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/AwsCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/AmazonS3Util.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/action/S3ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/AzureCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/AzureCloudBlobUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/action/AzureCloudBlobClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpUtil.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java

Last few API AWS and GCP E2E builds are failing, because of `SdxRepairTests.testSDXRepairMasterAndIDBRokerWithStoppedEC2Instance` test is failing with `cloud storage object has 0 bytes of content`.
So the related AWS and GCP Cloud Storage listing methods have been upgraded.

CB-13382 Fix CloudStorage Object validation

---

autoscale/build.gradle
autoscale/src/main/java/com/sequenceiq/periscope/common/AlertConstants.java
autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java
autoscale/src/main/java/com/sequenceiq/periscope/controller/DistroXAutoScaleClusterV1Controller.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/BaseAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/History.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/LoadAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/domain/TimeAlert.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java
autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java
autoscale/src/main/java/com/sequenceiq/periscope/service/UsageReportingService.java
autoscale/src/test/java/com/sequenceiq/periscope/service/UsageReportingServiceTest.java
usage-collection/src/generated/main/java/com/cloudera/thunderhead/service/common/usage/UsageProto.java
usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/LoggingUsageReporter.java
usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/UsageReporter.java
usage-collection/src/main/proto/usage.proto

Telemetry events are propogated after triggering a scaling action.
Telemetry events are propogated after autoscaling config is updated.

CB-10602 Propogate telemetry metrics from periscope.

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpDiskResourceBuilder.java

1. We need a SSD root volume. This is how AWS and Azure are setup.
2. The Disk#setKind method accepts a dummy value like compute#disks.
3. The SDK or the backend does not have any input checks. So it proceeds to create root volume with magnetic disks which are the default.
4. The right method for this setting is setType.
5. FreeIPA will perform poorly in a setup with magnetic disks.
6. Will perform a series of tests to see if the FreeIPA performs better in terms of repair resiliency and sync performance.
Tested in a seperate main class with the SDK integration.

CB-13226 Fixing the incorrect Disk class method call in GCP SDK.

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResourcesTest.java
environment/src/main/java/com/sequenceiq/environment/environment/encryption/EnvironmentEncryptionService.java
environment/src/main/java/com/sequenceiq/environment/parameters/validation/validators/parameter/AzureParameterValidator.java
environment/src/test/java/com/sequenceiq/environment/environment/encryption/EnvironmentEncryptionServiceTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/validation/validators/AzureParameterValidatorTest.java

CB-13130: Fix the creation/deletion of disk encryption set for multi-RG in Azure.
With multi-RG i.e; when `--resource-group-name` is not provided by the user, each of the resources creates its own resource group.
Following requirements should hold:
1. The RG for DES will be created.
2. User must provide ` --encryption-key-resource-group-name` - The RG where the encryption key is present.
This JIRA validates the encryption parameters for multi-RG and creates/deletes the resoure group for des by appending "-CDP_DES-" to resource group name.
Attaching a few screenshots for reference:
**1. For multi-RG, a new RG is created and DES is created within the newly created RG.** 
**2. CDP created resource group for DES and freeIPA.**
**3. `Resource` table having DES and DES's RG resource entries.**

CB-13130: Fix the creation/deletion of disk encryption set for multi-RG in Azure.

---

orchestrator-salt/src/main/resources/salt/salt/sssd/ipa.sls
orchestrator-salt/src/main/resources/salt/salt/sssd/template/add_dns_record.j2

1. There is a chance that ipa-client-install and ipa dnsrecord-add could go to different FreeIPA hosts.
2. The replication may not have been complete when the ipa dnsrecord-add was done.
3. Also the repeated addition of records could end up in similar case above and could even lead to deletion of records due to conflict.
4. The conflict can not be automatically resolved by FreeIPA because multi valued DNs are not possible to be converted to hostnames.
5. Also it is two record additions with same or different values.
6. To overcome all these obstacles in this change trying to use dnsrecord-mod instead of dnsrecord-add.
7. This way I hope the nsuniqueid is not added to the idnsname which is leading to multi valued DNs and which becomes an unresolvable conflict.
Basic bash testing done, need …

CB-13379 Ease conflict resolution problems in FreeIPA HA setup

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/model/ClusterHostAttributes.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaHostGroupAssociationBuilder.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityService.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaHostGroupAssociationBuilderTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSecurityServiceTest.java
common/src/main/java/com/sequenceiq/cloudbreak/util/URLUtils.java
common/src/test/java/com/sequenceiq/cloudbreak/util/URLUtilsTest.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/blueprint/BlueprintV4RequestToBlueprintConverter.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/clouderamanager/base/BatchResourceOperation.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/clouderamanager/base/batchapi/AbstractBatchApiHandler.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/clouderamanager/base/batchapi/BatchApiHandler.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/clouderamanager/base/batchapi/HostsResourceApiUpdateHostBatchApiHandler.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/clouderamanager/v31/controller/BatchResourceV31Controller.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java

* Set rack ID for every host in the CM cluster template when launching the cluster. Works irrespective of the stack type (DL or DH).
* `ClouderaManagerModificationService.upscaleCluster()` has been heavily refactored:
* Performance improvements: Replace linear searches in lists with set lookups. Replace nested linear searches (O(n^2)) with map lookups.
* Set rack ID for every newly added (upscaled) host during a cluster upscaling.
* Update rack ID for every outdated host of the hostgroup during a hostgroup repair (node replacement scenario).
* The former two points are realized using CM API batch operations.
* `ClouderaManagerSecurityService.createHostCertsBatchRequest()`: Add URL percent encoding around the host ID path variable. The former logic only worked because host IDs are …

CB-12911 Set rackId mapping in CM

---

template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.2.12.json
template-manager-cmtemplate/src/main/resources/cloudera-manager-template/service-definitions-minimal.json

Added Cruise Control to version files show that it appears on cluster creation page. Also fixed streaming component dependencies in _service-definitions-minimal.json_.
Testing: manual

CB-13457 Show Cruise Control icon on cluster creation page

---

environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java

As it might cause problems as of now.

Revert defaulting Tunneling to CCMv2_JUMPGATE

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/group/AbstractGcpGroupBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/group/GcpFirewallInResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/group/GcpInstanceGroupResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/GcpResourceNameService.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/group/GcpInstanceGroupResourceBuilderTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/service/GcpResourceNameServiceTest.java
common-model/src/main/java/com/sequenceiq/common/api/type/ResourceType.java

Part of the first step for GCP loadbalancers, defining instance groups to be used to define service pools
Unit testing here, more verification coming.

[CB-12976] Add Resource Builder for GCP instance Groups

---

core/src/main/resources/defaults/vm-logs.json

CB-13491. Include rotated CM server logs in diagnostics by default.

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/cruisecontrol/CruiseControlRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDatahubConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/cruisecontrol/CruiseControlRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaDatahubConfigProviderTest.java

This commit adds new custom configuration properties to both the Cruise Control and Kafka configuration providers.
These new entries are specific in DataHub and cannot go as default into the CSD.
Tested:
- Unit tests
- Manual on cluster

CB-10914 Extend Config Provider for Cruise Control and Kafka

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/init.sls

1. subject_alt_names was a new feature in config.ini from 7.4.3
2. When prior versions are upgraded to 7.4.3 the non CM nodes does not get the updated config.ini when auto-tls provisions their tokens.
3. To fix it choosing a line that existed for the entirety of Cloudera (almost) in config.ini

CB-13456 Fix Datalake upgrade to 7.4.3

---

autoscale-api/src/main/java/com/sequenceiq/periscope/api/endpoint/validator/ScalingPolicyRequestValidator.java
autoscale-api/src/main/java/com/sequenceiq/periscope/api/model/LoadAlertConfigurationRequest.java
autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java
cloud-api/src/main/java/com/sequenceiq/cloudbreak/common/ScalingHardLimitsService.java
common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/InternalCrnBuilder.java
common/src/test/java/com/sequenceiq/cloudbreak/auth/crn/InternalCrnBuilderTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java

Max node limit for loadbased-autoscaling increased to 500.

CB-13437 Max step size for autoscaling is increased to 500

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxCustomTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxTests.java

SdxRepair mocktest refactors. Splitting basic SDX test from repair use cases. Removed unnecessary env creation from testcases. Increased repair timeout to 370 seconds since its possible that we hit an unlucky sync timing.

CB-13484 SdxRepair mocktest refactors

---

environment/src/main/resources/schema/app/20210722081943_CB-13157_Remove_dummy_DB_column_environment_parameters.encryption_keyurl.sql

CB-13157: Remove dummy DB column environment_parameters.encryption_keyurl
The associated entity field got removed in CB 2.45, the unused DB column environment_parameters.encryption_keyurl (environmentdb) is removed as part of this PR.

CB-13157: Remove dummy DB column environment_parameters.encryption_keyurl

---

cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/metadata/AwsNativeMetadataCollector.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNativeMetadataCollectorApiIntegrationTest.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNativeMetadataCollectorTest.java

* `AwsNativeMetadataCollector`:
* `describeLoadBalancer()`: Fix broken logic.
* Some code refactor & log fixes.
* Make `CloudInstance` processing order deterministic (keeping the input iteration order). This may have a minor performance impact due to the usage of `LinkedHashMap` & `LinkedHashSet` vs the usual `HashMap` & `HashSet`.
* Testing:
* Manual verification in local CB (environment & DL: AWS CF, DH: AWS native).
* Updated existing UT.
* Fixed `AwsNativeMetadataCollectorTest.collectInstanceMetadataWhenOneOrMoreOfSpecifiedInstanceIdsDoNotExistAndMultipleBatchRequestsAreNecessary()`. The expectation regarding the result list size was incorrect. The right answer did not match previously due to the presence of the non-deterministic `CloudInstance` processing order mentioned above.

CB-13038 `AwsNativeMetadataCollector` bugfixes & code quality enhancements

---

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java

Datalake service will not set `admin` for user field in stackV4Request, although password is still needed for Ranger as default password.
https://github.com/hortonworks/cloudbreak/blob/master/core/src/main/resources/defaults/blueprints/7.2.12/cdp-sdx.bp#L104-L121
With this, cluster installation succeeds and Cloudbreak removes default admin user from CM:

CB-7668 Data Lake should not set a default admin password

---

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2

Profiler Manager Services has 3 main services i.e. profiler_manager_service, profiler_metrics_service and data_discovery_service. They all supports active-active HA now. 
Added enableLoadBalancing explicitly for all the services which would help in scaling. 
Tested these configs on my local cluster.

CB-13443: Enabled Load balancing using Knox for Profiler Manager Service.

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxBackupAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxRestoreAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxSyncAction.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/telemetry/TelemetryTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/SdxBackupRestoreTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/PreconditionSdxE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/action/S3ClientActions.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/FlowUtil.java

[CB-13322](https://jira.cloudera.com/browse/CB-13322) Datalake backup is failing, because of `409, Could not connect to Solr` and `ATLAS_JANUS_TABLE: HBase failure: Failed to take snapshot`
This is a workaround for `L0 SdxBackupRestoreTest`: few minutes wait before backup seems solved above API backup issues.

CB-13322 Workaround for datalake backup L0 tests

---

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleService.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsRepairTest.java
cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleServiceTest.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java
core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/service/StackCreationService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/GatewayConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/InstanceMetadataUpdater.java
core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/DiskSpaceValidationService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactoryTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/AbstractRdsConfigProviderTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/rdsconfig/RedbeamsDbServerConfigurerTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/general/GeneralClusterConfigsProvider.java

- Primary gateway change messes up the salt roles and PGW on CB side. As CM is non HA, PGW doesn't make any sense, similarly to DL.
- Fixed downscale when the instance is not returned by AWS as it's deleted long time ago. In this case no termination request is sent for the instance.
- When fetching all `GatewayConfig` only the reachables are returned to avoid connection issues. If there is no gateway instance reachable an error is raised.

CB-13493 Fix Datahub HA repair, remove primary gateway change

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterDecomissionService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecomissionService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecomissionServiceTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissionerTest.java
cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecommisionerTest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/CollectDownscaleCandidatesHandler.java

- old behaviour: during collection of downscale candidates we called listHosts in CM then we called readHost in CM for every known instance with summary view
- new behaviour: during collection of downscale candidates we call readHosts in CM with summary view

CB-13539 CollectDownscaleCandidatesHandler transaction is too long

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java

If we have 2 gateways and the primary is healthy, then CB are allowing to repair other host groups (like core host group / DL). It will fail because CB tries to communicate with the unhealthy GW node. As a quick fix we should validate if every GW group is healthy and do not let the repair request if the unhealthy GW node is not in the repair request.

CB-13554 Gateways has to be repaired first (not only primary GW)

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterStatusService.java
cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusService.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeActions.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ClusterUpgradeFailHandledRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ClusterUpgradeFailedCmSyncRequest.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterUpgradeFailedCmSyncHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ComponentConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ClouderaManagerProductTransformer.java
core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterComponentUpdater.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ImageComponentUpdaterService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/StackComponentUpdater.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/CmInstalledComponentFinderService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/CmProductChooserService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/CmServerQueryService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/CmSyncerService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/ImageReaderService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/sync/ParcelInfo.java
core/src/main/resources/application.yml
core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ClouderaManagerProductTransformerTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/StackComponentUpdaterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/CmInstalledComponentFinderServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/CmProductChooserServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/CmServerQueryServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/CmSyncerServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/sync/ImageReaderServiceTest.java

If a datalake or DH upgrade fails, versions stored in the DB itself and parcel versions on the CM may slip apart. To fix that, there should be a syncer that:
- queries the CM for activated parcels
- persists the current parcel versions, including CDH, to the component AND clusterComponent tables
This syncer is then called in the flow in the failure handler path

CB-13039 Introduce a CM version syncer

---

freeipa/src/main/java/com/sequenceiq/freeipa/converter/instance/template/InstanceTemplateRequestToTemplateConverter.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/DefaultRootVolumeTypeProvider.java
freeipa/src/main/resources/application.yml
freeipa/src/test/java/com/sequenceiq/freeipa/converter/instance/template/InstanceTemplateRequestToTemplateConverterTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/DefaultRootVolumeTypeProviderTest.java

1. The previous PR #11076 changed the root disk of datalake and datahub.
2. There is a separate code path for FreeIPA which still sets the root disk type to HDD.
3. Found during end-to-end testing.
4. Will perform the tests in parallel.

CB-13226 Making root disk to be of type SSD for FreeIPA in GCP

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java

small change to fallback to network parameters when the instance doesn't have a subnet defined yet.

CB-13597 gcp can't create instances on default subnet

---

autoscale/src/main/java/com/sequenceiq/periscope/monitor/MonitorUpdateRate.java

Currently Time-monitor is scheduled to run every 10 seconds which causes considerable load on the autoscaling service. The time precision of 10 seconds is very low considering the distributed nature of CDP  where in scale-up/scale-down takes place in minutes.
Also  this low value results in high probability of fire-ready trigger missing the trigger window (which will also be only 10 seconds) in case of server slowness and would cause missed schedules and customer escalations.
Hence Time-monitor rate is increased to 30 seconds.

CB-13610 Optimize time monitor

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/start.sls
orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/setup-autotls.sh.j2

Cloudbreak generates 2 files to set up Auto-TLS:
- /etc/cloudera-scm-server/certs/auto-tls.init.txt
- /etc/cloudera-scm-agent/cmagent.token
Both of these files have the world-readable permission and as
part of this PR it is changed to 600. The auto-tls.init.txt can be used
by the cloudera-scm user and the cmagent.token can be used by the root user.

CB-13551 fix the permission of 2 Auto-TLS related files

---

autoscale/src/main/java/com/sequenceiq/periscope/service/DateService.java
autoscale/src/test/java/com/sequenceiq/periscope/controller/validation/AlertValidatorTest.java
autoscale/src/test/java/com/sequenceiq/periscope/utils/CronTest.java

Cron Expression accepted for schedule based autoscaling should be of minimum 6 parts.
Current mechanism of autogenerating  certain parts results in user confusion and also deviates from UI input for the same which mandatorily requires minimum 6 parts.

CB-7554 Disallow 5 Part Cron Expression

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/search/KibanaSearchUrl.java

Actually Kibana links are behind one hour as the Jenkins. So we need to reduce the 2 hours offset to just 1 hour.
It is related to the [CB-8692 Cloud storage link on the test result page like Kibana link](https://jira.cloudera.com/browse/CB-8692) change.

CB-13676 Move Kibana timestamp with one hour in HTML reports

---

cloud-azure/src/main/resources/templates/arm-v2.ftl
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering-ha.bp
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java
core/src/test/resources/input/de-ha.bp
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology.xml.j2
orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2

1. Azure internal standard load-balancer is hard to work with.
2. To get internet connectivity we have to attach a NAT gateway to the customer provided subnet.
3. Instead of getting deep into the bowels of Azure network connectivity this approach simply falls back on the previous workaround.
4. This change re-arrages services in such a way that we will not need standard load-balancer or any of the complex network setup to make the services talk to each other when they are in same group.
5. Added ability for knox to load-balance between Oozie instances.

CB-13495 Make Oozie HA work with Azure basic load-balancer

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/search/KibanaSearchUrl.java

Remove time offset from Kibana search URL start and end time, because of Jenkins has already the 2 hours offset; for example:
[api-e2e-newway-aws](http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-newway-aws/) `Build #3538--2.47.0-b114-AWS (05-Aug-2021 02:50:09)` and the [DistroXEncryptedVolumeTest.testCreateDistroXWithEncryptedVolume-20210805.log](http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-newway-aws/3538/artifact/suites_log/DistroXEncryptedVolumeTest.testCreateDistroXWithEncryptedVolume-20210805.log) shows `2021-08-05 00:51:25,028` start and `2021-08-05 02:01:58,285` end time.
It is related to the [CB-8692 Cloud storage link on the test result page like Kibana link](https://jira.cloudera.com/browse/CB-8692) change.

CB-13676 Remove time offset from Kibana search URL

---

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java

Describe default image cdp cli and find default images commands returned permission denied on mow-dev due to the 'internal only' annotation, this was changed to DisableCheckPermissions.

CB-13698: Describe default image cli command returns permission denied on mow-dev

---

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/scripts/generate_agent_tokens.sh.j2

In case of base images it's possible that the scm agent is not yet installed and the directory is not present. This causes the salt cp.get_file command to fail. Since the downscale fix introduced previously ignores whether the copy is successful or not this can lead to scaleing/provision failures.

CB-13523 CM agent token copy sporadically fails for base images.

---

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientExceptionUtil.java

ACI_ERROR is returned when the FreeIPA says that we don't have permission
to make some changes.
```
Insufficient 'write' privilege to the 'userPassword' attribute of entry 'uid=ldapbind-cb246-ntp-gcp-spk3de,cn=users,cn=accounts,dc=cb246-nt,dc=s8bs-i2ta,dc=stg,dc=cldr,dc=work'.]. Failure details: [empty]
```
However, we're using a super user that has all the priviliges to make any
changes. We've only seen this error when we tried to set the password for
service users. To mitigate the problem I'm adding it to the retry list so
hopefully the `user_mod` method will succeed eventually.

CB-13700 Add ACI_ERROR(2100) error to the FreeIPA retriable list

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/InstanceGroupTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java

Issue 1: AWS Freeipa, and YARN Datalake master instance groups receive the same name, so instead of creating a new instance group for YARN, the test framework used the one that was created for AWS.
The fix was to include the cloud platform in the test dto's name, so AWS and YARN receive different names.
Issue 2: Freeipa is no longer created by environment service, so the security groups set for the environment are not automatically applied to Freeipa instances.
The fix was to set the security group directly to the Freeipa request.

CB-13672 Fix hybrid cloud test

---

core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering.bp

DISTX-678 - Set hive.metastore.try.direct.sql.ddl=true explicitly in Hive templates
As part of CDPD-25578, "hive.metastore.try.direct.sql.ddl" was explicitly set to true for "hive_service_config_safety_valve" - used by hive
This PR sets "hive.metastore.try.direct.sql.ddl" as true for "hive_metastore_config_safety_valve" to be used by hive metastore.
**Property set for "hive_metastore_config_safety_valve"**
**Property set for "hive_service_config_safety_valve" - already as part of CDPD-25578**

DISTX-678 - Set hive.metastore.try.direct.sql.ddl=true explicitly in Hive templates

---

orchestrator-salt/src/main/resources/salt/pillar/postgresql/disaster_recovery.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/backup.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/restore.sls
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh

Jira: https://jira.cloudera.com/browse/CB-13532
This change is primarily focused on extending the existing backup/restore scripts to be usable with a given database. Specifically, I have made it so the scripts take in an optional database name argument and, when the argument is _not_ provided, the default action is to backup the hive and ranger databases (the existing behavior).
Part of this change includes changes to the existing salt files in order to work correctly with the new optional argument. A side effect of this change is that the other optional argument, the log file location, can now only be used when the database name argument is given as well. We believe that this is okay as this argument is not used much in practice.
I have performed general testing of these changes, but not …

CB-13532: Modified backup-restore scripts to work on a given database.

---

freeipa/src/main/java/com/sequenceiq/freeipa/flow/chain/UpgradeFlowEventChainFactory.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/backup/full/BackupContext.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/backup/full/CreateFullBackupHandler.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/backup/full/FullBackupEvent.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/backup/full/FullBackupFlowConfig.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/backup/full/FullBackupState.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/backup/full/action/AbstractBackupAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/backup/full/action/FullBackupActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/backup/full/event/CreateFullBackupEvent.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/backup/full/event/TriggerFullBackupEvent.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/update/action/SaltUpdateActions.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/update/action/SaltUpdateFailureAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/update/action/SaltUpdateFinishedAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/salt/update/action/UpdateSaltFilesAction.java
freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/upgrade/UpgradeEvent.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/upgrade/UpgradeService.java
freeipa/src/main/resources/freeipa-salt/salt/freeipa/backup-full.sls
freeipa/src/test/java/com/sequenceiq/freeipa/flow/chain/UpgradeFlowEventChainFactoryTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/backup/full/CreateFullBackupHandlerTest.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/upgrade/UpgradeServiceTest.java
orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/OrchestratorStateParams.java

- a new flow is implemented to create full backups
- it's available only in upgrade flow chain now, no separate endpoint
- backup is added after salt update to ensure the new state is present
- backup is initiated on one node at a time, as full backup stops FreeIPA related services
- backup is only added to the flowchain if the `Stack` is configured for backup

CB-13354 FreeIPA add backup to upgrade flowchain

---

ccm-connector/src/generated/main/java/com/cloudera/thunderhead/service/clusterconnectivitymanagementv2/ClusterConnectivityManagementV2Proto.java
ccm-connector/src/main/proto/clusterconnectivitymanagementv2.proto
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/AuthenticationType.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/CcmV2Config.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClientCertificate.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterServiceConfig.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterServiceCredential.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterServiceHealthCheck.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ConfigDeleteRequest.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ConfigRegistrationRequest.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ConfigRegistrationRequestBuilder.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ConfigRegistrationResponse.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ConfigUpdateRequest.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ReadConfigEndpoint.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ReadConfigRequest.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ReadConfigResponse.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ReadConfigService.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/Tunnel.java
cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/TunnelEntry.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyService.java
core/src/test/java/com/sequenceiq/cloudbreak/clusterproxy/ClusterProxyRegistrationClientTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyServiceTest.java
environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ClusterProxyService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/ClusterProxyServiceTest.java

Updated cluster-proxy request and response objects according to the latest
image available.
Fixed typo in CCMV2 proto file.
Added fallback for CCM tunnel type.
Changed cluster proxy registration mode depending on CCMv2 or Jumpgate:
for Jumpgate, the Environment CRN must be passed but the CCMv2 config
should not, only the CCMv2 boolean flag must be set.
Old CCMv2 registration should remain the same.
Merge only after proper images are ready for FreeIPA AND base/prewarm

CB-12701 Add support for registering CCMV2 Jumpgate type clusters

---

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/service/AwsResourceNameService.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/metadata/AwsNativeLbMetadataCollector.java
cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/metadata/AwsNativeMetadataCollector.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNativeMetadataCollectorApiIntegrationTest.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNativeMetadataCollectorTest.java
cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/metadata/AwsNativeLbMetadataCollectorTest.java

Adds a new AwsNativeLbMetadataCollector to collect the AWS LB specific metadata to later
be persisted to the database.

CB-13514 - Add updated load balancer metadata collection to AwsNative classes

---

integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml

It's unstable due to Amazon(Could not launch Spot Instances. UnfulfillableCapacity - Unable to fulfill capacity due to your request configuration. Please adjust your request and try again. Launching EC2 instance failed)

CB-6830 Disabling AwsDistroXSpotInstanceTest.testDistroXOnSpotInstance

---

core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering.bp

1. This change will land in 2.48 which is after 7.2.11 release. So only updating 7.2.12 templates for full coverage in testing and enabling customers to delete and recreate clusters without change in behaviour.
2. Tested that the default is changed to SNAPPY compression after this safety valve setting by creating an external table and loading the data.

CDPD-25645 For Parquet setting SNAPPY as default compression

---

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java

Jira: https://jira.cloudera.com/browse/CB-7415
This change simply serves to modify the error message resulting when you try to repair a cluster when some instances are in a stopped state. Specifically, this adds the IDs of those stopped instances so the user knows which to restart.
Let me know if any of my logic is incorrect as I have assumed that these IDs are always available in this case.

CB-7415: Added list of stopped instanced to repair error message.

---

core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackScaleV4RequestToUpdateStackV4RequestConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/DownscaleFlowEventChainFactory.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/multiaz/MultiAzCalculatorService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java
core/src/test/java/com/sequenceiq/cloudbreak/controller/StackCreatorServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleActionsTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/multiaz/MultiAzCalculatorServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataServiceTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupServiceTest.java
environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentNetworkResponse.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/NetworkDtoToResponseConverter.java
redbeams/src/test/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverterTest.java
redbeams/src/test/java/com/sequenceiq/redbeams/service/network/NetworkParameterAdderTest.java

* Set subnet, AZ & rackId in `InstanceMetaData` (core) as early as possible.
* Applies to stack launch and stack upscale. (Repair is also implicitly covered since it involves an upscale as well.)
* Removes the former related logic in `MetadataSetupService`.
* `MultiAzCalculatorService`:
* Extract rackId generation into `determineRackId()`.
* Fix `InstanceMetaData` subnet usage statistics calculation in `collectCurrentSubnetUsage()`.
* Only consider not deleted instances. This affects instance updates (`calculateByRoundRobin()`) and subnet usage statistics calculation (`collectCurrentSubnetUsage()`).
* Code enhancements:
* Minor refactors, removal of unused methods & args, renaming improper identifiers.
* NPE elimination in several places.
* Testing:
* Manual verification in local CB: AWS …

CB-13508 Early populate subnet, AZ & rackId in `InstanceMetaData` (core)

---

orchestrator-salt/src/main/resources/salt-common/salt/filecollector/init.sls

details:
- with this change, if --update-package option will be used for collecting diagnostics, that can automatically update telemetry binary to this version (if it can be accessed from the network)

CB-13858. Update default cdp-telemetry package version.

---

core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering-ha.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering-spark3.bp
core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering.bp

DISTX-679: Turn off hive.privilege.synchronizer by default in templates
This change turns off "hive.privilege.synchronizer" by default. This property is used mainly for information schema population which users are not using actively. This can be enabled by users, in case they want to use information_schema.

DISTX-679: Turn off hive.privilege.synchronizer by default in templates

---

cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/CcmV2Config.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ClusterProxyService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/ClusterProxyServiceTest.java

Adds back `agentCrn` as an attribute in CcmV2Config. This would allow cluster-proxy to correlate a given backend id (and its health)  to the correct `agentCrn`
This reverts part of the changes done for https://github.com/hortonworks/cloudbreak/pull/11200

CDPAM-2112: Add agentCrn from CB request during registration

---

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/service/ClusterComponentConfigProvider.java
cluster-api/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterComponentViewRepository.java

CB-13711 mitigate DB cpu usage related to autosyncer and RuntimeVersionService - modify ClusterComponentConfigProvider to use ClusterComponentView based queries in methods that are related to autosync, avoiding the unwanted fetch of Cluster, Stack and SecurityConfig this way

CB-13711 mitigate DB cpu usage related to autosyncer and RuntimeVersionService

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyServiceTest.java

This fixes the bug introduced here: https://github.com/hortonworks/cloudbreak/commit/b106d4102bce00d1970850562cfb36636ce4b5d1

CB-13867 CM service config port in CP should be 9443 in case of CCMV2

---

core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/DefaultBlueprintCache.java
core/src/test/java/com/sequenceiq/cloudbreak/init/blueprint/DefaulBlueprintCacheTest.java

Blueprint upgrade options are preserved in the database and we have lots
of conditions, based on its value. Due to a bug it is not loaded properly
making all templates eligible for upgrade if the Data Hub upgrade is
enabled.

CB-13886 fix blueprint loader service not updating the upgrade options

---

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpMetadataCollector.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpBackendServiceResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpForwardingRuleResourceBuilder.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpLoadBalancerScheme.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpLoadBalancerTypeConverter.java
cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpLoadBalancingIpResourceBuilder.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/GCPLoadBalancerMetadataCollectorTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpBackendServiceResourceBuilderTest.java
cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpForwardingRuleResourceBuilderTest.java

requires other changes from CB-13426 to establish GCP loadbalancing scheme, and Forwarding Rules type.
Gathers the just IP address that has been assigned to a loadbalancer. Other details around backing instances will be a part of the CLI required changes. 
test coverage similar to AWS, Azure loadbalancer metadata collectors

[CB-13049] collect metadata for GCP loadbalancers

---

core/src/main/resources/defaults/clustertemplates/7.2.12/aws/streaming.json
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/cruisecontrol/CruiseControlRoleConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaVolumeConfigProvider.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/srm/StreamsReplicationManagerConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/cruisecontrol/CruiseControlRoleConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaVolumeConfigProviderTest.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/srm/StreamsReplicationManagerConfigProviderTest.java

This commit includes 4 minor changes.
- **StreamReplicationManagerConfigProvider** - Changed the bootstrap.servers property value calculation to only contain the core broker hosts if the core_broker hostgroup is present and CDH>=7.2.12. Because of the kafka scaling feature, having the scaleable brokers included in the bootstrap.servers causes issues when deleting nodes.
- **KafkaVolumeConfigProvider** - KAFKA_BROKER is now a shared roleType, the value of log.dirs will be calculated based on the minimum volume count.
- **CruiseControlRoleConfigProvider** - Removed the configuration that set kafka as an auth_admin, since now it is part of the CSD.
- **streaming.json** - Set the minimumNodeCount of the core_broker host group to 3.
Tested:
1. Manually on provisioned cluster
2. Unit tests

CB-13741 Change streaming config providers to fix a couple of recent issues

---

environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java
environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverter.java
environment/src/main/java/com/sequenceiq/environment/parameters/dao/domain/AwsParameters.java
environment/src/main/java/com/sequenceiq/environment/parameters/v1/converter/AwsEnvironmentParametersConverter.java
environment/src/main/java/com/sequenceiq/environment/parameters/validation/validators/parameter/AwsParameterValidator.java
environment/src/main/resources/schema/app/20210722121419_CB-13110_Add_the_encryption_Arn_parameter_passed_from_CLI_to_AWS_env_creation_in_Cloudbreak.sql
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverterTest.java
environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverterTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/v1/converter/AwsEnvironmentParametersConverterTest.java
environment/src/test/java/com/sequenceiq/environment/parameters/validation/validators/AwsParameterValidatorTest.java
structuredevent-model/src/main/java/com/sequenceiq/environment/parameter/dto/AwsDiskEncryptionParametersDto.java
structuredevent-model/src/main/java/com/sequenceiq/environment/parameter/dto/AwsParametersDto.java
structuredevent-model/src/test/java/com/sequenceiq/environment/parameter/dto/AwsDiskEncryptionParametersDtoTest.java
structuredevent-model/src/test/java/com/sequenceiq/environment/parameter/dto/AwsParametersDtoTest.java

Created a Environment with the encryption Key Arn from CLI and verified that the parameter encryption-key-arn is added to the DB:<img width="833" alt="Screenshot 2021-07-29 at 5 21 34 PM" src="https://user-images.githubusercontent.com/7271603/127487186-01bf109d-5b9d-4dd3-a7bc-9e53ebf102a8.png">

CB-13110:Add the encryption Arn parameter passed from CLI to AWS env creation in Cloudbreak

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/CloudbreakTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsDistroXSpotInstanceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsFreeIpaSpotInstanceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsSdxSpotInstanceTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/ResourceAwait.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/cloudbreak/CloudbreakWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/datalake/DatalakeWaitObject.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaWaitObject.java

Await failed when the stack failed to create, so the then validation never ran. The solution was to remove the await exception from the TestContext.

CB-13887 Fix spot tests when there is no spot capacity

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/instance/AvailabilitySetNameService.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerMetadataCollector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureMetadataCollector.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureLoadBalancerMetadataView.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerMetadataCollectorTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureMetadataCollectorTest.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/loadbalancer/AzureLoadBalancerResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/loadbalancer/AzureTargetGroupResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/loadbalancer/LoadBalancerResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/loadbalancer/TargetGroupResponse.java
core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/loadbalancer/LoadBalancerConfigDbWrapper.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/loadbalancer/TargetGroupConfigDbWrapper.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/loadbalancer/azure/AzureLoadBalancerConfigDb.java
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/loadbalancer/azure/AzureTargetGroupConfigDb.java
core/build.gradle
core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/loadbalancer/LoadBalancerToLoadBalancerResponseConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigConverter.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/loadbalancer/LoadBalancerToLoadBalancerResponseConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigConverterTest.java
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java

The Azure companion change to CB-13176. Gathers the Azure load balancer name and the availability set
name associated with each target group. That information is persisted to the database and returned
as part of the describe datalake output.

CB-13178 - Gather Azure medium duty datalake load balancer configs and return via cdp cli

---

orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/find-device-and-format.j2

Reserved storage is only valuable on the root disk. On it it enables keeps enough storage for the user to ssh into the machine even, when its full. On storage volumes it is not necessary and for a 1TB disk it reserved 50GB by default.

CB-13928 Eliminating reserved storage on storage volumes

---

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/health/HealthDetailsFreeIpaResponse.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/list/ListFreeIpaResponse.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/reboot/RebootInstancesRequest.java
freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/repair/RepairInstancesRequest.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/InstanceGroup.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/SecurityGroup.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/SecurityRule.java
freeipa/src/main/java/com/sequenceiq/freeipa/entity/Stack.java

When a FreeIPA cluster gets terminated, `SecurityGroup` is set to `null` in `InstanceGroup` and saved in a transaction while setting the `Stack` to terminated.
It looks like somehow the transaction is not respected when fetching a `Stack` with all the many to one connections.
It seems this is caused by this:
`HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@7cfa719d<rs=HikariProxyResultSet@735958073 wrapping org.postgresql.jdbc.PgResultSet@364baac2>`
To avoid this there are some possible solutions:
- switch from `Set` to `List` in relations between entities
- in `equals` and `hashCode` methods the `Set` types should be ignored
In this commit the latter is implemented.

CB-13956 Freeipa Unable to find com.sequenceiq.freeipa.entity.SecurityGroup with id

---

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/ClusterCertificatesRotationTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/ClusterRecoveryTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/ClusterUpgradeTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/DatabaseBackupTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/DatabaseRestoreTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/StackImageUpdateTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/StackSyncTriggerEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/StackEvent.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/ClusterRepairTriggerEvent.java
flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java

CB-13731 Mark datalake to cloudbreak flow trigger events as idempotent.

---

core/src/main/resources/schema/app/20210823151044_CB-13711_create_index_on_instance_metadata_for_status_and_instance_group_based_queries.sql
core/src/main/resources/schema/app/20210906145328_CB-13711_create_index_on_instancegroup_availabilityzones_by_instancegroup_id_to_mitigate_database_CPU_usage_.sql

Cherry picking the missing indices from 2.48 line of CB as it should keep the database CPU load around 10%(at least it decreased the load from 25% to 8-10% on mow-dev).

Cb 13711 mitigate high CPU load on database server due to inefficient SQL queries

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerMetadataCollector.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureLoadBalancerMetadataCollectorTest.java
core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigConverter.java
core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigConverterTest.java
template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProvider.java

Updates the load balancer metadata collection logic to use the correct stack name (the CB name instead
of the Azure stack name), and checks if the metadata is null before attempting to add it to an
immutable list.

CB-14040 Azure load balancer metadata collection failing

---

docker-autoscale/Dockerfile
docker-cloudbreak/Dockerfile

The old image seems to be outdated, and causes error during building the CB image.
Tested locally by creating a test image and using it in deployer to start CB.

Use new cloudera jdk image as default

---

datalake/src/main/java/com/sequenceiq/datalake/flow/create/SdxCreateActions.java

- during sdx creation flow, user initiated environment deletion
- during sdx deletion, sdx set status to DELETE_REQUESTED and started to terminate related RDS
- because of RDS termination, sdx creation flow failed
- during sdx creation flow failure handling, sdx tries to set status to PROVISION_FAILED but it has thrown an unhandled exception, since we cannot set status from any "delete in progress" to PROVISION_FAILED
- unhandled exception will go to general sdx failure handling, which (SdxFlowInformation) tries to set status based on current status, since it was EXTERNAL_DATABASE_DELETION_IN_PROGRESS, the failure handler will set status to DELETE_FAILED
- because of DELETE_FAILED status, environment deletion will fail also, freeipa will continue to provision ipa server and it will cause …

CB-13736 Environment deletion failed on mow-int-eu1 control plane

---

integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/azure-longrunning-e2e-tests.yaml
integration-test/src/main/resources/testsuites/e2e/gcp-longrunning-e2e-tests.yaml

CB-14099 Separate longrunning e2e test suite files by cloud provider

---

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/srm/StreamsReplicationManagerConfigProvider.java
template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/srm/StreamsReplicationManagerConfigProviderTest.java

The SRM CSD does not generate a "security.protocol" configuration anymore. Because of this, 7.2.12 streaming clusters fail to come up after start.
This commit extends the SRM configuration provider to  add "security.protocol=SASL_SSL" to the array config of SRM for CDH>=7.2.12.
Tested:
- Unit tests
- Provisioned cluster

CB-14024 SRM config provider should add security.protocol

---

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java
common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
common/src/main/resources/messages/messages.properties
core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceMetaData.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleActions.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleService.java
core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/RemoveHostsHandler.java
core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java
core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java
core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackSyncService.java
core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/CloudbreakFlowService.java
datalake/src/main/java/com/sequenceiq/datalake/service/sdx/cert/CloudbreakPoller.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitOperationChecker.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/spi/SpiDto.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/spi/SpiStoreService.java
mock-infrastructure/src/main/java/com/sequenceiq/mock/spi/controller/SpiController.java

Node can disappear at repair. It can happen if stack upscale fails at repair. In this scenario the old node is deleted, but the new node is in REQUESTED status. But requested nodes without instance id are cleaned up in many ways. For example if upscale fails, the upscale fail handling logic deletes these kind of nodes. It results the repaired node will disappear.
My solution: if a stack upscale fails, then we take back the original deleted node to DELETED_ON_PROVIDER_SIDE.
In this case the retry will not work. Reason is because retry will retry the upscale process and it would uspcale a new node next to the original node which is in DELETED_ON_PROVIDER_SIDE status. It is handled, retry (upscale) will fail if there is an another node with the same FQDN at upscale (e.g. the original node in …

CB-12707 - Put original repaired node back to DELETED_ON_PROVIDER_SIDE if repair fails if stack upscale failed

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/diagnostics/DiagnosticsTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/AwsDistroXEphemeralTemporaryStorageStopStartTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXImagesTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXRepairTests.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXScaleEdgeCasesTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXScaleTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXScaleTestParameters.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/InternalSdxSshAndCmAccessTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/SdxBackupRestoreTest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/PreconditionSdxE2ETest.java
integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/YcloudHybridCloudTest.java
integration-test/src/main/resources/testsuites/e2e/distrox-bigscale-tests.yaml

- cleanup scale test parameters class
- remove unused methods from AbstractIntegrationTest
- cleanup DistroxScaleTest
- initiate env and datalake creation at the same time in DistroxScaleTest
- create freeipa along with environment creation, not separately

CB-14023 Create weekly job for high node count scale e2e test

---

orchestrator-salt/src/main/resources/salt/salt/sssd/template/add_dns_record.j2

Fix the DNS record add script so that it retries when the following
error happens with err code 1:
ipa: ERROR: Configured time limit exceeded
Only retry when the error code is 1 and the error message is:
ipa: ERROR: no modifications to be performed
This was manually tested.

CB-14102: Fix ipa dns record errors so that it retries on more errors

---

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/PlatformParametersConsts.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureDatabaseTemplateBuilder.java
cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureDatabaseServerView.java
cloud-azure/src/main/resources/templates/arm-dbstack.ftl
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilderDbTest.java
cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/view/AzureDatabaseServerViewTest.java
redbeams/src/main/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverter.java
redbeams/src/test/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverterTest.java

CB-13745: Encryption support for Azure SQL Database instances.
Azure provides [data encryption](https://docs.microsoft.com/en-us/azure/postgresql/concepts-data-encryption-postgresql) for the SQL Databases using encryption key url and encryption key resource group name. This PR adds the required parameters in arm-template, provides "get, wrap and unwrap" permissions to key vault for the service principalId of the DB.
[Reference ](https://docs.microsoft.com/en-us/azure/postgresql/howto-data-encryption-cli#for-a-new-server)
**The screenshot shows the DB created as part of environment setup with CMK set.**
**The screenshot shows the encryption parameters in template used for launching DB instance.**

CB-13745: Encryption support for Azure SQL Database instances

---

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxRepairTests.java

CB-12707 wait for NODE_FAILURE instead of CLUSTER_AMBIGUOUS

---

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceMetaData.java
core-model/src/test/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceMetaDataTest.java
core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyService.java
core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyServiceTest.java
freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ClusterProxyService.java
freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/ClusterProxyServiceTest.java

* Up to now, Cluster Proxy registrations used either public or private IPs, depending on the source subnet, even if CCM was active. This has been changed to always pick the VM private IP when any variant of CCM is employed.
* Applies to both FreeIPA and DL / DH stacks, and all kinds of Cluster Proxy service, tunnel and CCMv2 endpoint entries.
* The former FreeIPA logic was checking for `stack.getSecurityConfig().isUsePrivateIpToTls()` to decide if the private IP was preferable. That condition is a legacy remnant from 2.9 CB and, thus, not applicable to CDP deployments (where it will always evaluate to `false`).
* `InstanceMetaData` (`core-model`): Added a helper, `getIpWrapper(boolean)`, that returns either the private IP or the result of `getPublicIpWrapper()`, depending on the `boolean` …

CB-14012 Always register private IP to Cluster Proxy when using CCM

---

datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/DatalakeRestoreActions.java

Datalake shows "datalake restore failed" status.  Although this won't block datalake operations, we want to modify it to data lake available status. The status reason is "Datalake is running, Datalake restore failed".

CDPSDX-3144: Data lake restore failed status
