hortonworks/cloudbreak

core/src/main/resources/defaults/blueprints/7.2.3/cdp-flow-management-small.bp, core/src/main/resources/defaults/blueprints/7.2.3/cdp-flow-management.bp
https://jira.cloudera.com/browse/CFM-1567
=> CFM-1567: Exclude hadoop group to fix nifiregistry startup error

environment/src/main/java/com/sequenceiq/environment/configuration/telemetry/AccountTelemetryConfig.java, environment/src/main/java/com/sequenceiq/environment/telemetry/service/AccountTelemetryService.java, environment/src/main/resources/application.yml, environment/src/test/java/com/sequenceiq/environment/telemetry/service/AccountTelemetryServiceTest.java
See detailed description in the commit message
add a default anonymization rule for cdp hashed password
=> CB-9392. Add default annymization rule for CDP hashed password & refactor default rule loading

README.md, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureSetup.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStorage.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtilsTest.java
When extracting image name from connection string expect query paramters to follow the image name. Also added Linux specific howto to readme.
=> ENGESC-4921 Handle Azure custom image with SAS token

integration-test/scripts/fetch-secrets.sh, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ums/UmsTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/AuthUserKeys.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvStopStartWithEnvAdmin.java
- secret versioning
- environment start stop test
- environment create delete test
=> CB-9475 new tests for authz based on found bugs

common/src/main/java/com/sequenceiq/cloudbreak/tracing/TracingUtil.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClient.java, freeipa-client/src/test/java/com/sequenceiq/freeipa/client/FreeIpaClientTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaClientFactory.java, freeipa/src/test/java/com/sequenceiq/freeipa/client/FreeIpaClientTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthServiceTest.java, secret-engine/src/main/java/com/sequenceiq/cloudbreak/service/secret/service/VaultRetryService.java
Additional code cleanup/refactor in VaultRetryService
=> CB-9005 - FreeIpa client tracing

README.md
=> Add java version specification to readme

integration-test/scripts/fetch-secrets.sh, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/CloudbreakUser.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/actor/CloudbreakUserCache.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/MeasuredTestContext.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvironmentLegacyAuthzGetTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/environment/EnvironmentAwait.java, integration-test/src/main/resources/testsuites/v4/mock/legacy-authz-mock-package.yaml
=> CB-9472 make authz mock tests runnable from one testsuite

cloud-azure/src/main/resources/templates/arm-dbstack.ftl, cloud-azure/src/main/resources/templates/arm-network.ftl, cloud-azure/src/main/resources/templates/arm-storageaccount.ftl, cloud-azure/src/main/resources/templates/arm-v2-freeipa.ftl, cloud-azure/src/main/resources/templates/arm-v2.ftl, cloud-azure/src/test/resources/json/arm-network.json
Upgrading ARM API versions to a more current one.
=> CB-9306 - Azure ARM templates - API version upgrade

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java, common/src/main/resources/messages/messages.properties, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/salt/update/SaltUpdateService.java
=> CB-9308 Send notification to UI when we start the Salt update process

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxAutotlsCertRotationAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/audit/AuditGrpcServiceAssertion.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/audit/DatalakeAuditGrpcServiceAssertion.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/SdxTestClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxSecurityTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxUpgradeTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java, integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
=> CB-9232 E2E test for TLS cert renewal

orchestrator-salt/src/main/resources/salt/pillar/postgresql/disaster_recovery.sls, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/backup.sls, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/restore.sls, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh
Fixes [CB-9540](https://jira.cloudera.com/browse/CB-9540).
Revert the lookup of pillar values for cacerts. Use hardcoded values instead.
=> CB-9540 Revert pillar value lookup

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseService.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/database/DatabaseServiceTest.java
do not create db if sdx is in terminated statu
=> CB-7370 proper error message if RDS is missing

integration-test/scripts/swagger-check.sh
- The list of non-API modules is a hardcoded array
- We iterate through all the changed files
- Check if their module is one of the non-API modules
- If yes, we add them to a collector array
- If in the the size of the collector array equals the number of changed files, no swagger check is needed
=> CB-9524 - Skip swagger compatibility check if there is no api change in the pull request

mock-infrastructure/build.gradle
=> CB-9551 fix main class in mock-infrastructure/gradle.build.

autoscale/src/main/java/com/sequenceiq/periscope/config/DatabaseConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/StackReferenceRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/eventbus/CloudResourcePersisterService.java, datalake/src/main/java/com/sequenceiq/datalake/configuration/DatabaseConfig.java, environment/src/main/java/com/sequenceiq/environment/configuration/DatabaseConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/configuration/DatabaseConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/configuration/DatabaseConfig.java
=> CB-9545 use JpaRepository getOne() instead of EntityManager

orchestrator-salt/src/main/resources/salt-common/salt/filecollector/init.sls
=> CB-9518. Update default cdp-telemetry version

mock-infrastructure/Dockerfile
=> CB-9551 fix ADD command in  mock-infrastructure/Dockerfile.

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/cache/UmsUserHasRightsCache.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/cache/UmsUserHasRightsForResourceCache.java
=> CDPCP-3230 add cache for hasRights

autoscale/src/main/java/com/sequenceiq/periscope/config/DatabaseConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/StackReferenceRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/eventbus/CloudResourcePersisterService.java, datalake/src/main/java/com/sequenceiq/datalake/configuration/DatabaseConfig.java, environment/src/main/java/com/sequenceiq/environment/configuration/DatabaseConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/configuration/DatabaseConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/configuration/DatabaseConfig.java
=> Merge 2.32

core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/ImageToImageDetailsConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/RdsConfigToRdsDetailsConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/converter/RdsConfigToRdsDetailsConverterTest.java, structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/ImageDetails.java, structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/RdsDetails.java, structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StackDetails.java
=> CB-9527 Clean up the sensitive details from Audit

integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
=> CB-8861. Enable diagnostics (CM & VM based) tests for AWS

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/SparklessTestContext.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentNetworkTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java, integration-test/src/main/java/com/sequenceiq/it/util/TagsUtil.java, integration-test/src/main/resources/application.yml, integration-test/src/main/resources/testsuites/e2e/gcp-distrox-baseimage-tests.yaml
=> CB-9266 distroximagetest may run on gcp

autoscale/src/main/java/com/sequenceiq/periscope/config/DatabaseConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/StackReferenceRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/eventbus/CloudResourcePersisterService.java, core/src/main/resources/definitions/upgrade-matrix-definition.json, datalake/src/main/java/com/sequenceiq/datalake/configuration/DatabaseConfig.java, environment/src/main/java/com/sequenceiq/environment/configuration/DatabaseConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/configuration/DatabaseConfig.java, integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml, redbeams/src/main/java/com/sequenceiq/redbeams/configuration/DatabaseConfig.java
=> Merge 2.33.0 to master

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/StackTags.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/AwsInstanceTemplateV4Parameters.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/template/GcpInstanceTemplateV4Parameters.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/InstanceTemplateV4RequestToTemplateConverterTest.java
=> ENGESC-5054 convert encryption data and tags from stackrequest only if it isn't null

environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/base/SecurityAccessBase.java, environment/src/main/resources/schema/app/20201004155455_CB-9595_increase_cidr_column.sql
=> CB-9595 Increase size of CIDR field on environment creation wizard

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCredentialAppCreationCommand.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCredentialConnector.java, cloud-azure/src/main/resources/templates/app-audit-creation-command.ftl, cloud-azure/src/main/resources/templates/app-creation-command.ftl, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCredentialAppCreationCommandTest.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCredentialConnectorTest.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRuntimeVersionValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/GcpMockAccountMappingService.java, core/src/main/resources/application.yml, environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentInitHandler.java, environment/src/main/java/com/sequenceiq/environment/network/NetworkService.java, environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentInitHandlerTest.java, environment/src/test/java/com/sequenceiq/environment/network/NetworkServiceTest.java
=> fixes on 2.33

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java, integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml
CB-9266 bugfix cloudprovider in image selection was wrong in case of gcp
=> CB-9266 bugfix cloudprovider in image selection was wrong

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCredentialAppCreationCommand.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCredentialConnector.java, cloud-azure/src/main/resources/templates/app-audit-creation-command.ftl, cloud-azure/src/main/resources/templates/app-creation-command.ftl, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCredentialAppCreationCommandTest.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCredentialConnectorTest.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRuntimeVersionValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/identitymapping/GcpMockAccountMappingService.java, core/src/main/resources/application.yml, core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRuntimeVersionValidatorTest.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentInitHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/sync/EnvironmentStatusCheckerJob.java, environment/src/main/java/com/sequenceiq/environment/network/NetworkService.java, environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentInitHandlerTest.java, environment/src/test/java/com/sequenceiq/environment/network/NetworkServiceTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java, redbeams/src/main/java/com/sequenceiq/redbeams/sync/DBStackStatusSyncJob.java
=> Merge 2.33

integration-test/src/main/resources/application.yml
Re-configure the upgrade tests to do a 7.2.0 -> 7.2.6 upgrade
=> CB-9642 Re-configure the upgrade tests to do a 7.2.0 -> 7.2.6 upgrade

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/cluster/CloudStorageConverter.java
1. In the last PR #9402 missed one location which was identified through private stack testing.
2. Will test this also in a private stack.
3. These are necessary conversions so would not mind sending a separate PR if this is not enough.
./gradlew test
=> CB-9670 [GCP] Propagate the GCS identity parameters everywhere

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java
=> CB-9266 bugfix better message when base images are empty

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/dns/DnsZoneService.java
When a DNS zone delete was issued for a zone which is not present in FreeIPA it generates an error which caused HTTP 500 on our end.
From now we will handle this gracefully by only having a log message that it's not present on the FreeIPA side.
=> CB-9700 DnsZone delete can cause HTTP 500 if zone is missing

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceGroupV1ToInstanceGroupV4Converter.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceGroupV1ToInstanceGroupV4ConverterTest.java
=> CB-9624 validate nodecount of instancegroup with gateway type

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/RecipeTest.java
assert was failing if there were other recipes registered in the account
=> CB-9714 Only check for missing recipe in recipe list after delete

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/environment/EnvironmentGetAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxCloudStorageTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java, integration-test/src/main/java/com/sequenceiq/it/util/TagsUtil.java, integration-test/src/main/resources/application.yml
=> CB-9266 add storage parameters to gcp test and more network attributes

core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRuntimeVersionValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/StackViewRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackViewService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/DistroxService.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRuntimeVersionValidatorTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/DistroxServiceTest.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterCreationTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterUpscaleDownscaleTest.java
=> CB-9657 DataLake runtime version is null

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/sql/GcpDatabaseServerLaunchService.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/view/GcpDatabaseNetworkView.java, redbeams/src/main/java/com/sequenceiq/redbeams/service/network/NetworkParameterAdder.java
=> CB-9267 shared vpc support in case of database creation

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CreateDhWithDatahubCreator.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvStopStartWithEnvAdmin.java
=> CB-9657 datalake should be created for authorization related dh tests

core/src/main/resources/defaults/clustertemplates/7.2.0/aws/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.0/azure/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.0/yarn/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.1/aws/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.1/azure/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.1/yarn/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.2/aws/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.2/azure/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.2/yarn/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.6/aws/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.6/azure/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.6/yarn/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.7/aws/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.7/azure/dde.json, core/src/main/resources/defaults/clustertemplates/7.2.7/yarn/dde.json
=> CDPD-19389: Set DDE feature status to released

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/ClouderaManagerProduct.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/ClouderaManagerProductBase.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/cluster/cm/product/ClouderaManagerProductV4Request.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRuntimeVersionValidator.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRuntimeVersionValidatorTest.java
=> CB-9682 Use CDH version as stack version

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosServiceTest.java, core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeService.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ClusterManagerUpgradeRequest.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterStartHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterManagerUpgradeHandler.java, core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeServiceTest.java, datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/DatalakeUpgradeActions.java
=> Merge 233 into master

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh
Closes [CB-9616](https://jira.cloudera.com/browse/CB-9616).
In Medium duty datalakes we don't have an `hdfs-NAMENODE` directory, so trying to kinit fails.  It actually doesn't matter which keytab we use, so the regular expression to look for the directory can also include `JOURNALNODE` and `DATANODE`.
This is done in both the backup and the restore script.
=> CB-9616: Have kinit code look for more HDFS node directories.

core/src/main/java/com/sequenceiq/cloudbreak/util/UsageLoggingUtil.java
1. Some datahubs are not attached to datalake CB-8084
2. This causes them to be classified as datalake in EDH.
3. Started using stack type as a way to identify a datalake.
./gradlew test
=> CB-9422 Fix datahub classification error

common/src/main/java/com/sequenceiq/cloudbreak/quartz/statuschecker/service/StatusCheckerJobService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/RescheduleStatusCheckChainFactory.java
Probably it is a CM bug and this is just a workaround.
After the repair is finished the syncer sets the status of the cluster to unhealthy because CM reports BAD health issue for a node:
2020-10-31 10:47:53,432 [quartzScheduler_Worker-6] getHostHealth:375 DEBUG c.s.c.c.ClouderaManagerClusterStatusService - [type:STACK] [crn:crn:cdp:datalake:us-west-1:qe-aws:datalake:cb0ba594-af75-4820-9d54-5d50cf6722dd] [name:aws-test-509b228843f7494f965757cc7b41d90] [flow:] [requestid:9ba14552-d47f-411c-b77b-2e01c6b36d3a] [tenant:] [userCrn:] [environment:crn:cdp:environments:us-west-1:qe-aws:environment:f29733a9-4324-4eb4-8cb2-520fb38c2880] [traceId:] [spanId:] Healthcheck result from CM: {StringType
{value='aws-test-509b228843f7494f965757cc7b41d90-idbroker0.aws-test.xcu2-8y8x.cloudera.site'}
=[class …
=> CB-9547 3 minutes delay for status checker in CB after repair was successful

common/src/main/java/com/sequenceiq/cloudbreak/logger/RestLoggerFilter.java
=> CB-9860 Limit the logged responses based on the size of the string

core/src/main/resources/application.yml, core/src/main/resources/defaults/blueprints/7.2.6/cdp-streaming-small.bp, core/src/main/resources/defaults/blueprints/7.2.6/cdp-streaming.bp, core/src/main/resources/defaults/blueprints/7.2.7/cdp-streaming-small.bp, core/src/main/resources/defaults/blueprints/7.2.7/cdp-streaming.bp, core/src/main/resources/defaults/clustertemplates/7.2.6/aws/streaming-small.json, core/src/main/resources/defaults/clustertemplates/7.2.6/aws/streaming.json, core/src/main/resources/defaults/clustertemplates/7.2.6/azure/streaming-small.json, core/src/main/resources/defaults/clustertemplates/7.2.6/azure/streaming.json, core/src/main/resources/defaults/clustertemplates/7.2.6/gcp/streaming-small.json, core/src/main/resources/defaults/clustertemplates/7.2.6/gcp/streaming.json, core/src/main/resources/defaults/clustertemplates/7.2.6/yarn/streaming-small.json, core/src/main/resources/defaults/clustertemplates/7.2.6/yarn/streaming.json, core/src/main/resources/defaults/clustertemplates/7.2.7/aws/streaming-small.json, core/src/main/resources/defaults/clustertemplates/7.2.7/aws/streaming.json, core/src/main/resources/defaults/clustertemplates/7.2.7/azure/streaming-small.json, core/src/main/resources/defaults/clustertemplates/7.2.7/azure/streaming.json, core/src/main/resources/defaults/clustertemplates/7.2.7/gcp/streaming-small.json, core/src/main/resources/defaults/clustertemplates/7.2.7/gcp/streaming.json, core/src/main/resources/defaults/clustertemplates/7.2.7/yarn/streaming-small.json, core/src/main/resources/defaults/clustertemplates/7.2.7/yarn/streaming.json, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/srm/StreamsReplicationManagerConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/srm/StreamsReplicationManagerRoles.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/srm/StreamsReplicationManagerConfigProviderTest.java
=> CB-7898: Add SRM to Streaming DataHub cluster templates

common/src/main/java/com/sequenceiq/cloudbreak/common/anonymizer/AnonymizerUtil.java, common/src/main/java/com/sequenceiq/cloudbreak/common/json/Json.java, freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_healthagent_setup.sh, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/client/SaltConnector.java
Redact the FreeIPA admin password.
=> CB-9852: Redact FreeIPA admin password

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/hybrid/AwsYcloudHybridCloudTest.java
=> CB-9750 Extend testCreateSdxOnChildEnvironment logging

integration-test/src/main/java/com/sequenceiq/it/util/TagsUtil.java
=> CB-9912 gcp test shoudl expect owner tag value sanitized

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/environment/EnvironmentNetworkTestAssertion.java
=> CB-9827 new network test checks the number of private networks

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePermissionProvider.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/CmAndStackVersionFilter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ImageFilterParams.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePermissionProviderTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/CmAndStackVersionFilterTest.java
=> CB-9715 Skip image filtering based on upgrade matrix in case of datahub upgrade

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/ImageCatalogMockServerSetup.java
Fix for Integration Test project [ImageCatalogMockServerSetup getCloudbreakUnderTestVersion](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/mock/ImageCatalogMockServerSetup.java):
Get CB version and app. name from `/cb/info` is not sufficient on Manowar environments, there `/cloud/cb/info` needed.
=> CB-8945 Fix for CB Version and AppName for MOW environments

core/src/main/resources/defaults/clustertemplates/7.2.7/aws/flow-management-small.json, core/src/main/resources/defaults/clustertemplates/7.2.7/aws/flow-management.json, core/src/main/resources/defaults/clustertemplates/7.2.7/azure/flow-management-small.json, core/src/main/resources/defaults/clustertemplates/7.2.7/azure/flow-management.json, core/src/main/resources/defaults/clustertemplates/7.2.7/gcp/flow-management-small.json, core/src/main/resources/defaults/clustertemplates/7.2.7/gcp/flow-management.json
=> CFM-1168 Add support for external databases in DataHub

core/src/main/resources/defaults/blueprints/7.2.7/cdp-flow-management-small.bp, core/src/main/resources/defaults/blueprints/7.2.7/cdp-flow-management.bp
=> CFM-1555 DataHub CSD - change authorizer default configuration

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java, auth-connector/src/main/proto/usermanagement.proto
=> Merge 2.33.0 to 2.34.0

orchestrator-salt/src/main/resources/salt-common/salt/fluent/template/databus_metering.conf.j2
=> CB-9987. Make sure metering events never dropped in DH - ENGESC-5146

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleService.java
Determine original and current values and display user-friendly error message
containing meaningful values about instance counts.
=> CB-9723 Create meaningful message on AWS failed upscale

core/src/main/resources/application.yml
=> Enable x1e.2xlarge instance type to data hub

freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/RebootService.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/start/AttemptMakerFactory.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/start/FreeIpaServiceStartService.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/start/OneFreeIpaReachableAttempt.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/start/StackStartService.java, freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/start/FreeIpaServiceStartServiceTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/start/OneFreeIpaReachableAttemptTest.java
=> CB-9443 adding freeipa health check polling to freeipa start process

environment/src/main/java/com/sequenceiq/environment/credential/v1/AuditCredentialV1Controller.java
=> CB-9955 disable credential verification in case of audit credential

template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.2.6.json, template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.2.7.json
CB-10056 Bump Schema Registry Version for 7.2.6 and 7.2.7 to match those in CDH.
=> CB-10056 Bump Schema Registry Version

common-model/src/main/java/com/sequenceiq/common/api/telemetry/validation/LoggingRequestValidator.java, common-model/src/main/java/com/sequenceiq/common/model/FileSystemType.java, common-model/src/test/java/com/sequenceiq/common/api/telemetry/validation/LoggingRequestValidatorTest.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifester.java
Reverts hortonworks/cloudbreak#9542
=> Revert "CB-8309 adding cloudstorage validation both on environment service an…"

common-model/src/main/java/com/sequenceiq/common/model/diagnostics/CmDiagnosticsParameters.java, common-model/src/main/java/com/sequenceiq/common/model/diagnostics/GcsDiagnosticsParameters.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/converter/CmDiagnosticsDataToParameterConverter.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/converter/DiagnosticsDataToParameterConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/diagnostics/DiagnosticsCollectionValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/CmDiagnosticsCollectionActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/DiagnosticsCollectionActions.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/diagnostics/DiagnosticsCollectionValidatorTest.java, datalake/src/main/java/com/sequenceiq/datalake/service/validation/diagnostics/DiagnosticsCollectionValidator.java, datalake/src/test/java/com/sequenceiq/datalake/service/validation/diagnostics/DiagnosticsCollectionValidatorTest.java, orchestrator-salt/src/main/resources/salt-common/salt/filecollector/settings.sls
=> CB-10100. Add GCS support for VM diagnostics

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java
=> CB-10104. GCS logging details are not set for DL/DH.

common-model/src/main/java/com/sequenceiq/common/api/telemetry/validation/LoggingRequestValidator.java, common-model/src/main/java/com/sequenceiq/common/model/FileSystemType.java, common-model/src/test/java/com/sequenceiq/common/api/telemetry/validation/LoggingRequestValidatorTest.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifester.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifesterTest.java
Reverts hortonworks/cloudbreak#9557
=> Revert "Revert "CB-8309 adding cloudstorage validation both on environment service an…""

core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroxUpgradeServiceTest.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxClusterRequest.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifester.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifesterTest.java
- Now request which contain whitespaces will throw BadRequestException.
I'm 90% sure buckets and azure storage accounts can't have whitespaces in them.
Note: turns out S3 folder can have whitespaces
=> CB-10063 Added validation for CloudStorage Base location. 

common/src/main/java/com/sequenceiq/cloudbreak/common/anonymizer/AnonymizerUtil.java, common/src/test/java/com/sequenceiq/cloudbreak/common/anonymizer/AnonymizerUtilTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java
Redact the MagBearerToken for FreeIPA
=> CB-10189: Redact the MagBearerToken for FreeIPA

datalake/src/main/resources/duties/7.2.7/azure/medium_duty_ha.json
=> CB-9805 Properly size Azure to match AWS instances.

core/src/main/resources/defaults/clustertemplates/7.2.1/aws/dataengineering-ha.json, core/src/main/resources/defaults/clustertemplates/7.2.1/aws/dataengineering-spark3.json, core/src/main/resources/defaults/clustertemplates/7.2.1/aws/dataengineering.json, core/src/main/resources/defaults/clustertemplates/7.2.1/azure/dataengineering-ha.json, core/src/main/resources/defaults/clustertemplates/7.2.1/azure/dataengineering-spark3.json, core/src/main/resources/defaults/clustertemplates/7.2.1/azure/dataengineering.json
Reverts hortonworks/cloudbreak#9599
Reverting to fix the commit message.
=> Revert "CB-9902: Increase the default node count for the compute group to 1 in 7.2.1 templates"

authorization-common/src/main/java/com/sequenceiq/authorization/service/CustomCheckUtil.java, datalake/src/main/java/com/sequenceiq/datalake/flow/diagnostics/SdxDiagnosticsFlowService.java, environment/src/main/java/com/sequenceiq/environment/platformresource/v1/CredentialPlatformResourceController.java, freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/PasswordService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/UserSyncService.java
=> 2.35 to master

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java
CB-10075 Upgrade image selection logic should not depend on image catalog URL
* First try to use imagecatalog by name given in the current image
* if image catalog is not found by name, use the stored imagecatalog url instead
=> CB-10075 Upgrade image selection logic should not depend on image catalog URL

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh
Code change basically gets the stripped backup location to import the metadata needed for S3guard if the location is an s3a URL. This is affecting the data lake restore on runtime 7.2.6.
=> CB-10244: Perform hadoop S3guard import on the backup location before  restore is performed.

core/src/main/resources/defaults/clustertemplates/7.2.1/aws/dataengineering-ha.json, core/src/main/resources/defaults/clustertemplates/7.2.1/aws/dataengineering-spark3.json, core/src/main/resources/defaults/clustertemplates/7.2.1/aws/dataengineering.json, core/src/main/resources/defaults/clustertemplates/7.2.1/azure/dataengineering-ha.json, core/src/main/resources/defaults/clustertemplates/7.2.1/azure/dataengineering-spark3.json, core/src/main/resources/defaults/clustertemplates/7.2.1/azure/dataengineering.json
…E cluster shapes for 7.2.1 templates"
=> CB-10239:Increase the default node count for the compute group to 1 for the DE cluster shapes for 7.2.1 template

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchService.java
This deterines based on the subnet's route tables if there is an internet
gateway attached to it making it either a private or public load balancer.
=> CB-9900 Determine if Subnet is Private or Public for Load Balancer.

cloud-azure/src/main/resources/definitions/azure-enabled-regions.json
=> CB-10284 Update Azure coordinates got from the az client

datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
Set MdcContext from the fetched SdxCluster data.
=> CB-10111 Fill MDCcontext when invoking SdxController

authorization-common/src/main/java/com/sequenceiq/authorization/service/UmsAccountAuthorizationService.java, authorization-common/src/test/java/com/sequenceiq/authorization/service/UmsAccountAuthorizationServiceTest.java
=> CB-10303 new rights was sent in legacy case

integration-test/src/main/resources/application.yml
=> CB-10270 Disable spot instances in e2e tests

authorization-common/src/main/java/com/sequenceiq/authorization/service/UmsAccountAuthorizationService.java, authorization-common/src/test/java/com/sequenceiq/authorization/service/UmsAccountAuthorizationServiceTest.java
CB-10303 new rights was sent in legacy case
=> Merge 2.35

integration-test/scripts/fetch-secrets.sh, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/AuthUserKeys.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvironmentLegacyAuthzGetTest.java
=> merge 2.35 to master

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsTaggingService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsAutoScalingService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsComputeResourceService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/encryption/EncryptedSnapshotService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilder.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/CustomAmazonWaiterProvider.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsAutoScalingServiceTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleServiceTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilderTest.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTerminationHelperService.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilder.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/upscale/AzureUpscaleService.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilderTest.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/CloudFailureContext.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/CloudFailureHandler.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceService.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceCreateThread.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerMgmtSetupService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
=> CB-9886 Nodes not killed on Cloud Provider if a scale operation fails

datalake/src/main/resources/application.yml, integration-test/src/main/resources/application.yml
=> CB-10341 Modify default Cloudera Runtime to 7.2.7

integration-test/src/main/resources/application.yml
=> Cb 10252 multi thread it

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/cluster/gateway/GatewayV4Response.java
=> CB-10370 SSOTypes enum values are missing from swagger

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/cluster/gateway/GatewayV4Request.java
=> CB-10370 SSOTypes enum values are missing from swagger (request as well)

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/cloudbreak/CloudbreakWaitObject.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/datalake/DatalakeWaitObject.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/environment/EnvironmentWaitObject.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaWaitObject.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceWaitObject.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/redbeams/RedbeamsWaitObject.java
=> CB-10388 NPE in WaitObject if the statusReason is null

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsLaunchService.java
Currently when the stackDescribe API call failing the code is ignoring the AmazonServiceException. Therefore we don't what was the error.
In this fix I've added exception logging and I extended our CloudConnectorException with the original exception as a root cause.
=> CB-10351: Improve exception logging when aws api throws exception during Rds creation

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpProvisionSetup.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpLabelUtil.java, cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpLabelUtilTest.java
=> CB-10299 limit the length of the GCP buckets as it could not be longer than 63 characters

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsPlatformResources.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSubnetIgwExplorer.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchService.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSubnetIgwExplorerTest.java
=> CB-10408 modify AwsSubnetIgwExplorer to mark subnet as public when default route table has internet gateway attached to it

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/InstanceMetadataUpdater.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ambari/InstanceMetadataUpdaterTest.java
=> ENGESC-5953 remove empty stack versions when gathering stack versions

common-model/src/main/java/com/sequenceiq/common/api/cloudstorage/old/GcsCloudStorageV1Parameters.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/base/LoggingBase.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/instance/aws/AwsInstanceTemplateParameters.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/instance/aws/AwsInstanceTemplateSpotParameters.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/create/CreateFreeIpaRequest.java
Add missing log statements for FreeIPA create request.
=> CB-10441: Add missing log statements for FreeIPA create request

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/doc/CredentialPrerequisiteModelDescription.java, common-model/src/main/java/com/sequenceiq/common/api/telemetry/doc/DiagnosticsModelDescription.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, environment-api/src/main/java/com/sequenceiq/environment/api/doc/credential/CredentialModelDescription.java, environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/CredentialPlatformResourceEndpoint.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/EnvironmentPlatformResourceEndpoint.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/PlatformResourceModelDescription.java
In EnvironmentModelDescription swagger doc there were items that were results of copy-paste.
These were corrected.
=> CB-10124 Fix descriptions

common/src/main/java/com/sequenceiq/cloudbreak/util/Benchmark.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/recipe/UploadRecipesHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/RecipeEngine.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
* measure and log the duration of the db queries
* measure the duration of the upload recipes process
* logging the uploaded recipes' length
=> CB-10446 Logging improvement during upload recipes

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialVerifier.java
=> ENGESC-5647 log simulate policy result

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialVerifier.java, common/src/main/java/com/sequenceiq/cloudbreak/util/Benchmark.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/recipe/UploadRecipesHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/RecipeEngine.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
=> Merge 235 to master

freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaClientBuilder.java
Fixed incorrect logic which treated FreeIPA is being reachable when it
was unreachable and cluster proxy was used. In this case cluster proxy
returns 502 which was incorrectly treated as a successful connection.
Although it would become unreachable for other reasons (e.g. the 3
minute health check), the health API would report incorrect results
for up to 3 minutes. There were also misleading logs which stated
FreeIPA was reachable.
This was manually tested with a local cloudbreak cluster.
=> CB-10455: Fix logic which treated unreachable FreeIPA as reachable

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
This exports just the Ranger nodes for Knox that are on the gateway nodes.
This also includes a change to Stack to persist the SDX shape and carry it
across to the Salt config.
=> CB-9744 Export Ranger on gateway for SDX HA.

build.gradle, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialVerifier.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterPreCreationApi.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/model/ServiceLocation.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/model/ServiceLocationMap.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerPreCreationService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtServiceConfigLocationService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtVolumePathBuilder.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/MgmtServices.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtServiceConfigLocationServiceTest.java, common/src/main/java/com/sequenceiq/cloudbreak/util/Benchmark.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java, core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/recipe/UploadRecipesHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/RecipeEngine.java, core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeServiceTest.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java, orchestrator-salt/src/main/resources/salt/pillar/cloudera-manager/settings.sls, orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/start.sls, orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/start.sls
=> 2.36 merge to master

common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/AbstractMetricService.java
=> CB-9751 Added field to maintain object reference to gauge values

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/AbstractImageValidatorE2ETest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/BaseImageValidatorE2ETest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/PrewarmImageValidatorE2ETest.java
=> CB-10505 Validate images by UUID instead of using the latest one.

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceGroupRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceGroupService.java
This fixes an issue where the instance groups are not fully loaded when trying to
access them.
=> CB-10512 SDX HA provisioning fails with lazyload exception.

orchestrator-salt/src/main/resources/salt/salt/gateway/knox.sls
=> Merge 2.36 to master

authorization-common/README.md
=> CB-6671 separate section about internal calls in authz readme

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/FreeIpaClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIpaSyncAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/FreeIpaTestClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaUserSyncTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/FreeIpaSyncTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaOperationWaitObject.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaUserSyncWaitObject.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaWaitObject.java
=> CB-10250 mock test for user sync

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonCloudProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/AbstractImageValidatorE2ETest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/BaseImageValidatorE2ETest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/imagevalidation/PrewarmImageValidatorE2ETest.java
=> CB-10505 Rename image parametert as it explicitly sets the image uiid to use in the test

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpCredentialConnector.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformParameters.java, cloud-gcp/src/main/resources/definitions/gcp-audit-prerequisites-creation-command.json, cloud-gcp/src/main/resources/definitions/gcp-prerequisites-creation-command.json, cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/service/CloudParameterService.java, config/checkstyle/checkstyle-suppressions.xml, environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/CredentialPlatformResourceEndpoint.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/platformresource/EnvironmentPlatformResourceEndpoint.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/securitygroup/gcp/GcpEnvironmentSecurityGroupValidator.java, environment/src/main/java/com/sequenceiq/environment/platformresource/PlatformParameterService.java, environment/src/main/java/com/sequenceiq/environment/platformresource/v1/CredentialPlatformResourceController.java, environment/src/main/java/com/sequenceiq/environment/platformresource/v1/EnvironmentPlatformResourceController.java
=> CB-10465 Create Credentials Missing Permissions for cloudsql.

autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluator.java
Fix Misplaced Log Statement Parameters
=> DISTX-496 Fix Misplaced Log Statement Parameters

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpProvisionSetup.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpLabelUtil.java, cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpLabelUtilTest.java, integration-test/build.gradle, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CloudProviderSideTagAssertion.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/yarn/YarnCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentNetworkTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxImagesTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/storage/AzureAdlsGen2Tests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudFunctionality.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazons3/client/S3Client.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/action/AzureCloudBlobClientActions.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/azurecloudblob/client/AzureCloudBlobClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpUtil.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/action/GcpClientActions.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/client/GcpClient.java, integration-test/src/main/java/com/sequenceiq/it/util/TagsUtil.java, integration-test/src/main/resources/application.yml, integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml
=> CB-10308 extend the  GCP related E2E test configuration yaml with new testcases

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ranger/RangerAdminAsSysAdminConfigProvider.java, template-manager-tag/src/main/java/com/sequenceiq/cloudbreak/tag/DefaultCostTaggingService.java, template-manager-tag/src/test/java/com/sequenceiq/cloudbreak/DefaultCostTaggingServiceAccountTagValidationTest.java, template-manager-tag/src/test/java/com/sequenceiq/cloudbreak/DefaultCostTaggingServiceTest.java
=> Ranger config modification and tag modification

environment/src/main/java/com/sequenceiq/environment/experience/WebTargetRetrier.java, environment/src/main/java/com/sequenceiq/environment/experience/common/XService.java, environment/src/main/java/com/sequenceiq/environment/experience/config/ExperienceServicesConfig.java, environment/src/main/java/com/sequenceiq/environment/experience/liftie/ExperiencesByLiftie.java, environment/src/main/java/com/sequenceiq/environment/experience/liftie/LiftieApi.java, environment/src/main/java/com/sequenceiq/environment/experience/liftie/LiftieConnector.java, environment/src/main/java/com/sequenceiq/environment/experience/liftie/responses/ClusterView.java, environment/src/test/java/com/sequenceiq/environment/experience/common/XServiceTest.java
also move config to a proper place
=> CB-10623 Refactor liftie stuff a bit

orchestrator-salt/src/main/resources/salt/salt/top.sls
This changes salt to deploy nginx configuration, ssl sites  on all gateway nodes.
=> CB-10514 Configure nginx on all gateway nodes

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpProvisionSetup.java
CB-10619 handle conflict in case of image creation on GCP during image preparation. Parallel cluster creations could create racecondition when the conflict is not handled and causing cluster creation failures
=> CB-10619 handle conflict in case of image creation on GCP during image preparation. 

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
Jira: https://jira.cloudera.com/browse/CB-10577
Simply added logic to not check for the entitlement if a medium duty datalake is being created for AWS.
Also changed required version for medium duty setups to 7.2.7
=> CB-10577: Removed CDP_SDX_MEDIUM_DUTY entitlement check for AWS and changed required version to 7.2.7

environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/experience/ExperienceDeletionRetrievalTask.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentDeletionService.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentResourceDeletionService.java, environment/src/main/java/com/sequenceiq/environment/experience/Experience.java, environment/src/main/java/com/sequenceiq/environment/experience/ExperienceConnectorService.java, environment/src/main/java/com/sequenceiq/environment/experience/RetriableWebTarget.java, environment/src/main/java/com/sequenceiq/environment/experience/common/XService.java, environment/src/main/java/com/sequenceiq/environment/experience/liftie/ExperiencesByLiftie.java, environment/src/main/java/com/sequenceiq/environment/experience/liftie/LiftieApi.java, environment/src/main/java/com/sequenceiq/environment/experience/liftie/LiftieConnector.java, environment/src/main/java/com/sequenceiq/environment/experience/liftie/responses/ClusterView.java, environment/src/main/java/com/sequenceiq/environment/experience/liftie/responses/DeleteClusterResponse.java, environment/src/main/resources/application.yml, environment/src/test/java/com/sequenceiq/environment/experience/ExperienceConnectorServiceTest.java, environment/src/test/java/com/sequenceiq/environment/experience/common/CommonExperienceValidatorTest.java, environment/src/test/java/com/sequenceiq/environment/experience/common/XServiceTest.java
And do a mass amount of refactoring.
=> CB-10254 Add delete cluster for liftie connector

environment/src/main/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaService.java, environment/src/test/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaServiceTest.java
The environment auto syncer's freeipa describe was moved to internal endpoint on freeipa. When it was rolled out to the manowar dev environment the env pods were upgraded before freeipa pods. It caused that /v1/internal/freeipa endpoint was not defined on the running freeipa pods, so it gave 404. In this case auto syncer sets the env status to "freeipa deleted on provider". With this fix it can distinguish the case when there is no internal api and the case when freeipa was deleted and freeipa give back 404 for describe.
=> CB-10669 distinguish 404 errors for freeipa calls in env sync

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsDistroXSpotInstanceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsFreeIpaSpotInstanceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/AwsSdxSpotInstanceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/SpotTestResultProvider.java
=> CB-10688 Extend spot tests with UnfulfillableCapacity case

core/src/main/java/com/sequenceiq/cloudbreak/conf/ExternalDatabaseConfig.java, core/src/main/resources/externaldatabase/gcp/database-template.json
=> CB-10713 add initial database template config for external database creation of DistroX on GCP

core/src/main/java/com/sequenceiq/cloudbreak/conf/ExternalDatabaseConfig.java, core/src/main/resources/externaldatabase/gcp/database-template.json
=> Merge 2.36.0 branch into 2.37.0

core/src/main/java/com/sequenceiq/cloudbreak/conf/ExternalDatabaseConfig.java, core/src/main/resources/externaldatabase/gcp/database-template.json
=> Merge237tomaster

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CreateDhWithDatahubCreator.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvStopStartWithEnvAdmin.java
http://ci-cloudbreak.eng.hortonworks.com/job/cloudbreak-real-ums-test/2832
=> CB-10580 EnvAdmin can perform actions on datalake, datahubs - fix tests

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/OrchestratorRecipeExecutor.java, structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/CDPStructuredFlowEventToCDPEnvironmentRequestedConverter.java, structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/CDPStructuredFlowEventToCDPEnvironmentRequestedConverterTest.java
=> 237 wolf fixes

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetaDataCollectorTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java
Improved the logic to set the load balancer type so that it's based on the "subnetId"
network parameter being passed in for stack creation. If "subnetId" is not set, the
load balancer object will not be created. Additionally, error in load balancer metadata
collection now results in a log message instead of throwing an exception.
Tested with new unit tests and by creating a data lake and data hub and verifying the
expected network values were all set, and the LB created was successfully and metadata
collected.
=> CB-10775 Missing LB metdata causing Datalake stack creation time out

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetaDataCollectorTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/OrchestratorRecipeExecutor.java, core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java, structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/CDPStructuredFlowEventToCDPEnvironmentRequestedConverter.java, structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/CDPStructuredFlowEventToCDPEnvironmentRequestedConverterTest.java
Merges the fix for CB-10775 from the CB-2.37.0 branch to master. See original PR at https://github.com/hortonworks/cloudbreak/pull/9840.
=> Merge CB-10775 into master

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl.conf
This PR fixes an issue with ssl.conf which prevented nginx from starting due to bad configuration.
=> CB-10784: Fixed an nginx conf issue that prevented nginx from starting

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/MockInfrastructureApplication.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/aspect/ResponseModifierAspect.java, mock-infrastructure/src/main/resources/logback.xml
removed unnecessary log from ApiKeyRequestFilter, fixed logback.xml for mock-infra, added log messages to mock-infra
=> CB-10708 Quarz should not start with mock-infra, 

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
Jira: https://jira.cloudera.com/browse/CB-10843
Basically rolling back the changes made for: https://github.com/hortonworks/cloudbreak/pull/9788
=> CB-10843: Rolling back to require entitlement for AWS medium duty DL setups.

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProviderTest.java
=> DWX-6485 : Disable Initiator in DataHub

autoscale/src/main/resources/application.yml, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDeployClientConfigProvider.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/model/CommandResource.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDeployClientConfigProviderTest.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerKerberosServiceTest.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java, core/src/main/resources/application.yml, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/main/resources/application.yml, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java, orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl-locations.d/clouderamanager.conf, orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl.conf
=> Merge 2.37 to master

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup, orchestrator-salt/src/main/resources/salt-common/salt/filecollector/template/cdp-doctor-commands.yaml.j2
Add FreeIPA backup permissions check to CDP doctor.
This was tested by manually running it with a local deployment of cloudbreak on
AWS.
=> CB-10846: Add FreeIPA backup permissions check to CDP doctor

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerApiCheckerTask.java
=> CB-10856 IOException should be a tolerable error for CM api calls

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigView.java, freeipa/src/main/resources/freeipa-salt/salt/nginx/conf/ssl.conf
=> CB-10784: Fixed missing freeipa pillar

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRetryService.java
Retry call was missing for CB service in case of the following events retry
SDX_STACK_CREATION_IN_PROGRESS_EVENT,
DATALAKE_UPGRADE_IN_PROGRESS_EVENT,
SDX_REPAIR_IN_PROGRESS_EVENT
=> CB-10854 Datalake upgrade/repair is not retryable

flow/src/test/java/com/sequenceiq/flow/core/Flow2HandlerTest.java
=> CB-10137 Add test coverage to the broken retry function

core/src/main/resources/defaults/blueprints/7.2.0/cdp-data-engineering-ha.bp, core/src/main/resources/defaults/blueprints/7.2.0/cdp-data-engineering.bp, core/src/main/resources/defaults/blueprints/7.2.1/cdp-data-engineering-ha.bp, core/src/main/resources/defaults/blueprints/7.2.1/cdp-data-engineering.bp, core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering-ha.bp, core/src/main/resources/defaults/blueprints/7.2.2/cdp-data-engineering.bp, core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering-ha.bp, core/src/main/resources/defaults/blueprints/7.2.6/cdp-data-engineering.bp, core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering-ha.bp, core/src/main/resources/defaults/blueprints/7.2.7/cdp-data-engineering.bp, core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering-ha.bp, core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering.bp
=> CB-10918 Add Sqoop to gateway nodes and master nodes in the templates

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/telemetry/TelemetryTestDto.java
=> CB-10853 configure telemetry for GCP related test cases

core/src/main/java/com/sequenceiq/cloudbreak/converter/StackToTemplatePreparationObjectConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v2/StackToTemplatePreparationObjectConverterTest.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProviderTest.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/model/GeneralClusterConfigs.java
Merges the fix for CB-10794 from the CB-2.37.0 branch to master. See original PR at #9890.
=> Merge CB-10794 into master

auth-connector/src/main/java/com/sequenceiq/cloudbreak/client/ApiKeyRequestFilter.java, cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockUrlFactory.java, common/src/main/java/com/sequenceiq/cloudbreak/client/CertificateTrustManager.java, common/src/main/java/com/sequenceiq/cloudbreak/client/ConfigKey.java
- ConfigKey now contains optional TrustManager
- SslContext only initialized if a new client get's created
- ConfigKey to have a Builder class.
- Removed unnecessary log message. "Message to sign"
=> CB-10708 MockUrlFactory now uses a cached JAXRS client

mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java, mock-thunderhead/src/main/resources/application.yml, mock-thunderhead/src/test/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementServiceTest.java
=> CB-10143 readd accidently removed entitlement used by mock

freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/CreateFreeIpaRequestToStackConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/StopTelemetryHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/stack/termination/handler/StopTelemetryAgentHandler.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaInstallService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/proxy/ProxyConfigService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaCreationService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/tag/AccountTagService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/tag/TagConfigService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/telemetry/AccountTelemetryService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/telemetry/TelemetryAgentService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/telemetry/TelemetryConfigService.java, freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/downscale/handler/StopTelemetryHandlerTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/TelemetryAgentServiceTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/config/FreeIpaConfigServiceTest.java
No harm was done to the code during this refactor.
Moving some methods into their own class and splitting them for easier reading.
=> CB-10733 Refactor FreeIpaInstallService

authorization-common-api/src/main/java/com/sequenceiq/authorization/info/model/RightV4.java
Added some missing account level rights to RightV4 to be used on UI
=> CB-10864 Expose additional rights

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_replica_install.sh
1. FreeIPA does not work with link-local IP addresses in 4.6.6 https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/thread/U2UKIJ424CVAITZDHP736AYNP7VPKAAH/
2. It is hard to use 4.7.0 with Centos 7. For two reasons, 4.7.0 is a bad version so there is no repository support and also it is backward incompatible with other packages installed in the system.
3. We can not move to Centos 8, where 4.8.0 is supported, as it is getting deprecated sooner than Centos 7.
4. So reverting to a bug for GCP when there is a failover scenario we can not resolve internet hostnames until the replica is rebooted.
5. This seems to be a much better compromise than not supporting HA at all for freeipa.
=> CB-8677 Fix FreeIPA HA in GCP (take 3)

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSubnetIgwExplorer.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsSubnetIgwExplorerTest.java
=> CB-10901 Subnet should not be public by the main route table in case of a route table is associated explicitly.

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/UserModOperation.java, freeipa-client/src/test/java/com/sequenceiq/freeipa/client/operation/UserModOperationTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/WorkloadCredentialService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/WorkloadCredentialServiceTest.java
=> CB-10960 ignore false error in case of freeipa user_mod operation

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hue/HueConfigProviderTest.java
The original fix for this bug revealed an older bug in the Hue config logic that had been missed
until now. This fixes that logic, by adding a template variable for knox_proxyhosts, and by
correctly setting the template config "hue-knox_proxyhosts" setting, instead of the invalid
"knox_proxyhosts" setting.
Tested with unit tests and in local CB environment.
=> CB-10839 Cannot open hue UI when Public Endpoint Access Gateway is enabled

environment/src/main/java/com/sequenceiq/environment/environment/dto/AuthenticationDtoConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentResourceService.java, environment/src/main/resources/application.yml, environment/src/test/java/com/sequenceiq/environment/environment/dto/AuthenticationDtoConverterTest.java, environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentModificationServiceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentEditTest.java
=> CB-10991 Allow to edit on Azure and GCP.

orchestrator-salt/src/main/resources/salt-common/salt/filecollector/template/cdp-doctor-commands.yaml.j2
=> CB-11009. Add disk and memory data to cdp doctor report.

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Blueprint.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/BlueprintUpgradeOption.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/converter/BlueprintUpgradeOptionConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/blueprint/BlueprintV4RequestToBlueprintConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/BlueprintLoaderService.java, core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/DefaultBlueprintCache.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ImageFilterParamsFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/BlueprintUpgradeOptionValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ImageFilterParams.java, core/src/main/resources/application.yml, core/src/main/resources/schema/app/20210202161042_CB-10656_Limit_blueprint_upgrade.sql, core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ImageFilterParamsFactoryTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePermissionProviderTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/BlueprintUpgradeOptionValidatorTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/CmAndStackVersionFilterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/CsdLocationFilterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/PreWarmParcelLocationFilterTest.java
In this commit, I've introduced a new condition to limit which type of DataHubs can be upgraded.
=> CB-10656: Limit which type of Data Hubs can be upgraded

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtServiceConfigMemoryService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/SMONMemoryWorkaroundService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/config/SMONMemoryWorkaroundServiceTest.java, core/src/main/resources/application.yml
=> SMON issues

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterDBValidationService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/UpgradeConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterDBValidationServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/UpgradeConverterTest.java
=> CB-10922 Allow Data Hub upgrade to existing clusters

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformParameters.java
=> CB-11017 Show HDD twice on the UI. I removed the duplication.

core/src/main/java/com/sequenceiq/cloudbreak/util/StackUtil.java, core/src/test/java/com/sequenceiq/cloudbreak/util/StackUtilTest.java
=> CB-10917 volume mounting logic should support cases when volume sets present in the metadata without instance reference

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformParameters.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformResources.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformParametersTest.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzurePlatformResourcesVirtualMachineFilteringTest.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/CmMgmtServiceConfigMemoryService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/config/SMONMemoryWorkaroundService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/config/SMONMemoryWorkaroundServiceTest.java, core/src/main/resources/application.yml, freeipa/src/main/resources/freeipa-salt/salt/freeipa/common-install.sls, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
=> Merge238tomaster

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/exception/RolledbackResourcesException.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsAttachmentResourceBuilder.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilder.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtils.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilder.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/upscale/AzureUpscaleService.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilderTest.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/CloudFailureHandler.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ComputeResourceService.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/PreserveResourceException.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/ResourceDeleteThread.java, common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java, common/src/main/resources/messages/messages.properties, core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/TemplateDecorator.java, core/src/main/java/com/sequenceiq/cloudbreak/util/StackUtil.java, core/src/test/java/com/sequenceiq/cloudbreak/util/StackUtilTest.java
=> Merge 2.37 into 2.38

core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering-ha.bp, core/src/main/resources/defaults/blueprints/7.2.8/cdp-data-engineering.bp
CDPD-16387 Override Tez Session Lifetime via safety valve in DE and DE-HA Template.
=> CDPD-16387 Override Tez Session Lifetime via safety valve in DE and DE-HA Template.

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh
While performing backup and restore we need to make sure that there are no updates to metadata to make sure that we have a consistent backup. Currently, it is documented but there is no way to enforce it.
This approach will make sure that HMS and Ranger's data is updated while backup-restore operations are performed on data lake.
This change basically does below
1. Limit the number of connections to the database to 0.
2. Close all the active connections to the database.
3. perform the restore operation.
4. Limit the number of connections to the database to -1 (unlimited)
=> CB-11072: Avoid the need to stop ranger and HMS services before performing restore.

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/RepositoryConfigsTests.java
=> Integration tests: Ignore repo url validation (rc-2.9)

build.gradle, freeipa-client/build.gradle, scripts/build-dev.sh, scripts/build-release.sh
- create `uploadArchives` configuration for freeipa-client
- add `:freeipa-client:uploadArchives` to the build scripts
- modify project build config to add buildinfo to freeipa-client
=> CDPSDX-2788 Upload freeipa-client jars to nexus

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/InstanceConnector.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceConnector.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceConnectorTest.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureInstanceConnector.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpInstanceConnector.java, cloud-mock/src/main/java/com/sequenceiq/cloudbreak/cloud/mock/MockInstanceConnector.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/heat/OpenStackInstanceConnector.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/OpenStackNativeInstanceConnector.java, cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/instance/RebootInstancesRequest.java, cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/RebootInstanceHandler.java, cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/testcontext/TestApplicationContext.java, cloud-yarn/src/main/java/com/sequenceiq/cloudbreak/cloud/yarn/YarnInstanceConnector.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/instance/reboot/action/RebootActions.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/BlackListedDownScaleRole.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/BlackListedUpScaleRole.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidator.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/EntitledForServiceScale.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidatorTest.java, template-manager-cmtemplate/src/test/resources/input/nifi_7_2_6.bp, template-manager-cmtemplate/src/test/resources/input/nifi_7_2_7.bp, template-manager-cmtemplate/src/test/resources/input/nifi_7_2_8.bp
=> Cfm and freeipa reboot

common/src/main/java/com/sequenceiq/cloudbreak/tracing/TracingConfiguration.java
=> CB-10824 - enable logging b3 tracing headers

core/src/main/java/com/sequenceiq/cloudbreak/converter/AmbariStackDetailsJsonToStackRepoDetailsConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/ManagementPackDetailsToManagementPackComponentConverter.java
CB-11202 extend mpack url with paywall authentication if needed when it is coming from AmbariStackDetailsJson.mpackUrl
=> CB-11202 extend mpack url with paywall authentication if needed when it is coming from AmbariStackDetailsJson.mpackUrl

orchestrator-salt/src/main/resources/salt-common/salt/filecollector/template/filecollector.yaml.j2
=> CB-11216. Include nodestatus salt-report in diagnostics logs

orchestrator-salt/src/main/resources/salt-common/salt/filecollector/template/filecollector.yaml.j2
=> CB-11221. Diagnostics - Send case number as text.

core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCreationSetupService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageService.java
CB-11202 HDF provision has failed from e2etest, mpack urls not always setup with paywall cred.
=> CB-11202 HDF provision has failed from e2etest, mpack urls not always setup with paywall cred.

common-model/src/main/java/com/sequenceiq/common/api/diagnostics/DiagnosticsCollectionStatus.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/converter/DiagnosticsDataToParameterConverter.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/converter/FlowPayloadToDiagnosticDetailsConverter.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/diagnostics/DiagnosticsV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/diagnostics/docs/DiagnosticsOperationDescriptions.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/diagnostics/docs/DiagnosticsOperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/DiagnosticsV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/service/diagnostics/DiagnosticsService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/DiagnosticsEndpoint.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/model/diagnostics/docs/DiagnosticsOperationDescriptions.java, datalake/src/main/java/com/sequenceiq/datalake/controller/diagnostics/DiagnosticsController.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/diagnostics/DiagnosticsService.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/diagnostics/DiagnosticsV1Endpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/diagnostics/docs/DiagnosticsOperationDescriptions.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/DiagnosticsV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/DiagnosticsFlowService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/diagnostics/DiagnosticsService.java
=> CB-11242. Add cancel diagnostics flow API endpoint (freeipa/dl/dh/stack)

mock-infrastructure/src/main/java/com/sequenceiq/mock/BeanConfig.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/experience/DwxController.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/experience/ExperienceStoreService.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/experience/LiftieController.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/experience/LiftieExperienceStoreService.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/experience/response/common/CpInternalCluster.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/experience/response/common/CpInternalEnvironmentResponse.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/experience/response/common/DeleteCommonExperienceWorkspaceResponse.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/experience/response/liftie/ClusterView.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/experience/response/liftie/DeleteClusterResponse.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/experience/response/liftie/ListClustersResponse.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/experience/response/liftie/PageStats.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/experience/response/liftie/StatusMessage.java, mock-infrastructure/src/main/resources/application.yml
CB-11243 - introduce experience endpoints for mock infra that needs to be done before experience deletion/handling will land on the main branch
=> CB-11243 - introduce experience endpoints for mock infra

orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls
=> CB-11208. Disable auto CM bundle creation by default.

core/src/main/resources/defaults/blueprints/7.2.0/cdp-dde.bp, core/src/main/resources/defaults/blueprints/7.2.1/cdp-dde.bp, core/src/main/resources/defaults/blueprints/7.2.2/cdp-dde.bp, core/src/main/resources/defaults/blueprints/7.2.6/cdp-dde.bp, core/src/main/resources/defaults/blueprints/7.2.7/cdp-dde.bp, core/src/main/resources/defaults/blueprints/7.2.8/cdp-dde.bp, core/src/main/resources/defaults/blueprints/7.2.9/cdp-dde.bp
=> CB-11267 Remove Knox gateway role from DDE template

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/SilentCMDecommissionHostListenerTask.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissionerTest.java, common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java, common/src/main/resources/messages/messages.properties, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXRemoveInstanceAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/DistroXTestClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDtoBase.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXScaleEdgeCasesTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/DistroxUtil.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/InstanceGroupUtil.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/SdxUtil.java
=> CB-8471 retry if lost node CM decomission is stucked

integration-test/src/main/java/com/sequenceiq/it/util/TagsUtil.java, integration-test/src/test/java/com/sequenceiq/it/util/TagsUtilTest.java
=> Merge 237 into 238

integration-test/src/main/java/com/sequenceiq/it/util/TagsUtil.java, integration-test/src/test/java/com/sequenceiq/it/util/TagsUtilTest.java
=> Merge CB-2.38.0 into master

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/progress/ProgressV4Endpoint.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/progress/ProgressV1Endpoint.java, redbeams-api/src/main/java/com/sequenceiq/redbeams/api/endpoint/v4/progress/ProgressV4Endpoint.java
=> CB-11281. Cleanup swagger nicknames for flow progress API

datalake/src/main/resources/application.yml, integration-test/src/main/resources/application.yml
=> CB-10194 set 7.2.8 as default

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/RemoveHostsHandler.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionAcceptor.java, orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionAcceptorTest.java
=> Merge 238 to 239

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/conf/AzureConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/orchestration/RemoveHostsHandler.java, environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/TagValidatorTest.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionAcceptor.java, orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionAcceptorTest.java
=> 2.39 to master

datalake/src/main/resources/duties/7.2.7/gcp/medium_duty_ha.json, datalake/src/main/resources/duties/7.2.8/gcp/medium_duty_ha.json, datalake/src/main/resources/duties/7.2.9/gcp/medium_duty_ha.json
1. Last time when I updated the sizes forgot to update the node count of gateway and core node groups.
2. Will start a private stack testing in parallel.
=> CB-10461 GCP Medium duty datalake definition updated to match AWS/Azure

cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureUtilsTest.java
=> Merge CB-2.39.0 into master

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsAttachmentResourceBuilder.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsEfsResourceBuilder.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilder.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/VolumeResourceCollector.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureAttachmentResourceBuilder.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureVolumeResourceBuilder.java, cloud-gcp/build.gradle, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpDiskResourceBuilder.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpReservedIpResourceBuilder.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpBaseResourceChecker.java, cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpBaseResourceCheckerTest.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/AbstractOpenStackResourceBuilder.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackAttachedDiskResourceBuilder.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackInstanceBuilder.java, cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/nativ/compute/OpenStackPortBuilder.java
Enhance the logging in the volume handler logic with some additional refactors that removes code duplications and a NPE weak code snippet
=> CB-11151 - Enhance the logging in the volume handler logic

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXRepairAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/DistroXTestClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXRepairTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/PreconditionSdxE2ETest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxUpgradeTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/DistroxUtil.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/InstanceUtil.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/SdxUtil.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/VolumeUtils.java, integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/distrox-repair-tests.yaml
CB-10987 [E2E] create Data Hub master repair test
=> CB-10987 [E2E] create Data Hub master repair test

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh, orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh
See [incorrectly targeted PR](https://github.com/hortonworks/cloudbreak/pull/10170) for discussion.
=> Add Atlas keytabs as a fallback for medium duty.

cloud-common/src/main/java/com/sequenceiq/cloudbreak/polling/SimpleStatusCheckerTask.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/error/mapper/ClouderaManagerStorageErrorMapper.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/exception/CloudStorageConfigurationFailedException.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerTemplateInstallationChecker.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/util/ClouderaManagerCommandApiErrorParserUtil.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerTemplateInstallationCheckerTest.java, core/src/main/resources/externaldatabase/aws/database-template.json, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java, orchestrator-salt/src/main/resources/salt/salt/postgresql/init.sls
=> Merge 239 to master

flow/src/main/java/com/sequenceiq/flow/reactor/config/EventBusConfig.java, flow/src/main/java/com/sequenceiq/flow/reactor/eventbus/ConsumerCheckerEventBus.java, flow/src/main/java/com/sequenceiq/flow/reactor/eventbus/EventCanNotBeDeliveredException.java, flow/src/main/java/com/sequenceiq/flow/reactor/handler/ConsumerNotFoundException.java, flow/src/main/java/com/sequenceiq/flow/reactor/handler/ConsumerNotFoundHandler.java, flow/src/main/java/com/sequenceiq/flow/service/FlowService.java, flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java
=> CB-11300 Put flow in failed state even if consumer is not found for an event

environment/src/main/java/com/sequenceiq/environment/experience/ExperienceConnectorService.java, environment/src/test/java/com/sequenceiq/environment/experience/ExperienceConnectorServiceTest.java
Upon environment delete, check for experiences only if Spring config flag is enabled thus the checking in the ExperienceConnectorService.getConnectedExperiences method has been expanded to check the related spring config property's value to decide whether the feature has been enabled or not
=> CB-11454 - upon environment delete, check for experiences only if Spring config flag is enabled

core/src/main/resources/schema/app/20210308110100_ENGESC-7200_Azure_Diskname_Template_Fix.sql
The SQL script now updates all existing stack's template to correct
disk naming.
=> ENGESC-7200 Azure disk naming data fix

core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java, core/src/main/java/com/sequenceiq/cloudbreak/util/StackUtil.java, core/src/test/java/com/sequenceiq/cloudbreak/util/StackUtilTest.java, orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
Merging CB 2.39.0 to master. Fixed conflicts.
=> Merge 2.39 to master

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/CsdParcelDecorator.java, core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/CsdParcelDecoratorTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeServiceTest.java
Download CSD parcels only in case of workload clusters because DataLake does not require these parcels.
=> CB-11428: Download CSD parcels only in case of workload clusters.

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/VolumeParameterConfig.java, common/src/main/java/com/sequenceiq/cloudbreak/validation/VolumeParameterConstants.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/InstanceTemplateValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackValidationV4RequestToStackValidationConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/template/InstanceTemplateValidatorTest.java
=> CB-10962 allow maximum 23 volumes per instance template on all of the cloud platforms

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/azure/AzureResourceEncryptionParameters.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverter.java, environment/src/main/java/com/sequenceiq/environment/parameters/dao/domain/AzureParameters.java, environment/src/main/java/com/sequenceiq/environment/parameters/v1/converter/AzureEnvironmentParametersConverter.java, environment/src/main/java/com/sequenceiq/environment/parameters/validation/validators/parameter/AzureParameterValidator.java, environment/src/main/resources/schema/app/20210302145523_CB-11152:_Add_keyUrl_CLI_param_in_Azure_environment_creation.sql, environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverterTest.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverterTest.java, environment/src/test/java/com/sequenceiq/environment/parameters/v1/converter/AzureEnvironmentParametersConverterTest.java, environment/src/test/java/com/sequenceiq/environment/parameters/validation/validators/AzureParameterValidatorTest.java, structuredevent-model/src/main/java/com/sequenceiq/environment/parameter/dto/AzureParametersDto.java, structuredevent-model/src/main/java/com/sequenceiq/environment/parameter/dto/AzureResourceEncryptionParametersDto.java, structuredevent-model/src/test/java/com/sequenceiq/environment/parameter/dto/AzureParametersDtoTest.java, structuredevent-model/src/test/java/com/sequenceiq/environment/parameter/dto/AzureResourceEncryptionParametersDtoTest.java
CB-11152: Add encryptionKeyUrl CLI param in Azure environment creation
This part of the code stores the encryptionKeyUrl in column 'encryption_keyUrl'.
=> CB-11152: Add encryptionKeyUrl CLI param in Azure environment creation

core/src/test/java/com/sequenceiq/cloudbreak/service/publicendpoint/GatewayPublicEndpointManagementServiceTest.java, environment/src/main/java/com/sequenceiq/environment/network/EnvironmentNetworkService.java
=> Merge 239 into master

freeipa/src/main/resources/freeipa-salt/salt/freeipa/init.sls
=> CB-9504 FreeIPA - Tomcat - Hide apache error page

core/src/main/resources/defaults/blueprints/7.2.9/cdp-opdb.bp
=> [COMPX-5169] Add QUEUEMANAGER service to ODS blueprint for 7.2.9

environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentStartDto.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/start/handler/StartDatahubHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/start/handler/StartDatalakeHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/start/handler/StartFreeIpaHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/start/handler/SynchronizeUsersHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/poller/FreeIpaPollerProvider.java, environment/src/test/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaPollerServiceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentStartStopTest.java
Reverts hortonworks/cloudbreak#10248
=> Revert "todos"

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/RdbmsDeleteHandler.java
Remove unused fields in env delete flow classes
=> CB-11558 - remove unused fields in env delete flow classes

authorization-common-api/src/main/java/com/sequenceiq/authorization/info/model/RightV4.java
Added DH and SDX describe along with DH upgrade rights to be used on UI
=> CB-11379 Extend RightV4 with additional rights

usage-collection/src/generated/main/java/com/cloudera/thunderhead/service/common/usage/UsageProto.java, usage-collection/src/main/proto/usage.proto
=> CB-11541 Make SyncEvent refactor backwards compatible with 2.39

freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Host.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/IpaServer.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Keytab.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/PasswordPolicy.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Permission.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Privilege.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Role.java, freeipa-client/src/main/java/com/sequenceiq/freeipa/client/model/Service.java, freeipa-client/src/test/java/com/sequenceiq/freeipa/client/model/ToStringTest.java
Please check if any of the fields are sensitive and should not be logged.
=> CB-8254 implement toString for all FreeIPA models

environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyUrlValidator.java, environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java, environment/src/test/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorServiceTest.java, environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyUrlValidatorTest.java
CB-11152: Add encryptionKeyUrl to create-azure-environment CLI.
This PR adds the validation for the entitlement and format of the newly added param 'encryptionKeyUrl'.
=> CB-11152: Add encryptionKeyUrl to create-azure-environment CLI. 

freeipa/src/main/java/com/sequenceiq/freeipa/kerberosmgmt/v1/KerberosMgmtRoleComponent.java, freeipa/src/test/java/com/sequenceiq/freeipa/kerberosmgmt/KerberosMgmtRoleComponentV1Test.java
Fix FreeIPA race condition when adding a role. It was possible for the
FreeIPA management service to fail to add a host if multiple hosts were added at the same time with the same role assignment.
This was manually tested in a debugger by forcing the failure
condition to occur. Both hosts were successfully added.
=> CB-11576: Fix FreeIPA race condition when adding a role

cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/CredentialVerificationHandler.java, cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/CredentialVerificationHandlerTest.java
=> Emtge 2.39 int master

datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxRepairRequest.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRepairService.java, datalake/src/main/java/com/sequenceiq/datalake/settings/SdxRepairSettings.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxRepairServiceTest.java, datalake/src/test/java/com/sequenceiq/datalake/settings/SdxRepairSettingsTest.java
=> CB-11452 Add node ids to sdx repair request

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/util/AwsCloudFormationErrorMessageProvider.java
=> CB-11632 Add logging to AwsCloudFormationErrorMessageProvider

environment/src/main/java/com/sequenceiq/environment/environment/flow/EnvironmentFillInMemoryStateStoreRestartAction.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/EnvironmentFlowInformation.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/config/update/EnvStackConfigUpdatesState.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/EnvCreationState.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/EnvClustersDeleteState.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/EnvDeleteState.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/loadbalancer/LoadBalancerUpdateState.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/start/EnvStartState.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/stop/EnvStopState.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/stop/handler/StopFreeIpaHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java, flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java, flow/src/main/java/com/sequenceiq/flow/reactor/ContextClosedEventHandler.java
=> CB-11413 make environment service states restartable with in memory state and log context re-initialisation

core/src/main/resources/defaults/clustertemplates/7.2.10/aws/dataengineering-ha.json, core/src/main/resources/defaults/clustertemplates/7.2.9/aws/dataengineering-ha.json
1. 7.2.8 is full tested in dev with both public and private subnets individually.
2. Promoting this change for all the future releases.
3. The template is still in preview state.
=> DISTX-546 Enable load-balancer for 7.2.9 and 7.2.10 by default

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityServiceTest.java
CB-10920 Only allow Data Hub upgrade to the same version as the DataLake
=> CB-10920 Only allow Data Hub upgrade to the same version as the DataLake

core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/StackCommonServiceTest.java
=> CB-11655 Not allow to delete instances from data lake clusters.

common-model/src/main/java/com/sequenceiq/common/model/diagnostics/DiagnosticParameters.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/DataBusEndpointProvider.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/converter/DiagnosticsDataToParameterConverter.java, common/src/main/java/com/sequenceiq/cloudbreak/validation/AbstractDiagnosticsCollectionValidator.java, common/src/main/java/com/sequenceiq/cloudbreak/validation/MinAppVersionChecker.java, common/src/test/java/com/sequenceiq/cloudbreak/telemetry/DataBusEndpointProviderTest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/validation/AbstractCMDiagnosticsCollectionValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/diagnostics/DiagnosticsCollectionValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/diagnostics/DiagnosticsService.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/diagnostics/DiagnosticsCollectionValidatorTest.java, datalake/src/main/java/com/sequenceiq/datalake/service/validation/diagnostics/DiagnosticsCollectionValidator.java, datalake/src/test/java/com/sequenceiq/datalake/service/validation/diagnostics/DiagnosticsCollectionValidatorTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/diagnostics/DiagnosticsCollectionValidator.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/diagnostics/DiagnosticsService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/diagnostics/DiiagnosticsCollectionValidatorTest.java, orchestrator-salt/src/main/resources/salt-common/salt/filecollector/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/filecollector/settings.sls, orchestrator-salt/src/main/resources/salt/errormessages.yaml
details:
- do not run diagnostics on stopped/requested or deleted clusters
- check dbus s3 based urls during creating support bundle
=> CB-11297. Enhance validations for diagnostics collection.

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitService.java
=> CB-11716 Handle waiting errors in checkStatus with retries

environment/src/main/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaService.java, environment/src/test/java/com/sequenceiq/environment/environment/service/freeipa/FreeIpaServiceTest.java
=> CB-11718 EnvAdmin without EnvCreator role cannot start env

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvStopStartWithEnvAdmin.java
=> CB-11718 environment start should be called by another environment admin

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvStopStartWithEnvAdmin.java
=> Merge 2.40 to master

core-model/src/main/java/com/sequenceiq/cloudbreak/dto/KerberosConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/kerberos/KerberosConfigService.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java
Reverts hortonworks/cloudbreak#10312
=> Revert "CB-11691 change the Datanode address and https address to a secure po…"

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformResources.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerRoleRefreshService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerRoleRefreshServiceTest.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXRepairAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/CloudbreakTestDto.java
=> Merge CB-2.40.0 into master

mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/controller/MockThunderheadIAMController.java
=> CB-11762 Adding listUsers and listGroups to thunderhead-mock

core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java
=> CB-11868 Create DistroX internal API for COD usecase

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/generator/OfflineStateGenerator.java, core/src/main/java/com/sequenceiq/cloudbreak/node/status/NodeStatusService.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java
=> CB-10621 Specific stack query for node status checking

mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/controller/MockThunderheadIAMController.java
These endpoints also needed to fulfill UI requests in cbd.
=> CB-11762 Adding listUsers and listMachineUsers endpoints

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/test/ClientTestV1Endpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/test/model/CheckGroupsV1Request.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/test/model/CheckUsersInGroupV1Request.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/test/model/CheckUsersV1Request.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/test/model/ClientTestBaseRequest.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/test/model/ClientTestBaseV1Response.java, freeipa-api/src/main/java/com/sequenceiq/service/api/doc/ModelDescriptions.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/ClientTestV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/client/FreeipaClientTestService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/client/FreeipaClientTestServiceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIpaFindGroupsAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIpaFindUsersAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIpaFindUsersInGroupAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/FreeIpaTestClient.java
=> CB-11799 Add API to check users and groups in ipa server

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/ClouderaManagerLicenseProvider.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/PaywallCredentialPopulator.java, auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/PaywallCredentialPopulatorTest.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/AccountAuthorizationService.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/CompositeRequestPropertyAuthorizationFactory.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/RequestPropertyAuthorizationFactory.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceAuthorizationService.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceCrnAthorizationFactory.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceCrnListAuthorizationFactory.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceNameAuthorizationFactory.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceNameListAuthorizationFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelServiceTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeServiceTest.java, datalake/src/main/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeService.java, datalake/src/test/java/com/sequenceiq/datalake/service/upgrade/SdxRuntimeUpgradeServiceTest.java
=> CB-11738 extend logging of authorization

core-model/src/main/java/com/sequenceiq/cloudbreak/dto/KerberosConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/kerberos/KerberosConfigService.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessor.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateProcessorTest.java
Root cause: https://jira.cloudera.com/browse/CDPD-24524. Potentionally many services are broken
=> Revert secure datanode

freeipa/src/main/java/com/sequenceiq/freeipa/service/operation/OperationService.java
=> CB-11860 measure user sync batch optimalisation

core/src/test/java/com/sequenceiq/cloudbreak/repository/cluster/ClusterTemplateViewRepositoryTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/template/ClusterTemplateViewServiceTest.java
=> CB-11891 - UT for the clustertemplate list by env endpoint

core/src/main/resources/application.yml
=> CB-11911 Support additional Azure E*sV3 instances

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpPlatformResources.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpBaseResourceChecker.java
=> Merge 2.40

cloud-gcp/build.gradle, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpProvisionSetup.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/polling/GcpImageAttemptMaker.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/util/GcpStackUtil.java
**Main changes:**
- enhanced logging
- polling of rewrite status, Dyngr poller as new dependency
- pre-check of bucket existence
- error handling for existing bucket name, image and rewrite call read timeout
- set the same location as the cluster for the created bucket
- increased timeout for storage related SDK calls
=> ENGESC-7596 copy image tar into bucket based on the stack location and with rewrite SDK call

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/AttachedFreeIpaRequest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/FreeIpaImageRequest.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/FreeIpaConverter.java, environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandlerTest.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/FreeIpaConverterTest.java, structuredevent-model/src/main/java/com/sequenceiq/environment/environment/dto/FreeIpaCreationDto.java
=> CB-11907 Extend environment api with freeipa image parameters

integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml
CB-11775, CB-11776 create Data Hub master repair e2etests for Azure and GCP
=> CB-11775, CB-11776 create Data Hub master repair e2etests for Azure and GCP

README.md
According to the Action Point defined in post-mortem doc: https://docs.google.com/document/d/1uO-2Pxr7vHAavPSEzF1yYP4cthZVKVkQgEENNkusCXY/edit#heading=h.qm2lo7nyfy5l
=> ENGESC-7598 - Added TOC and coding guidelines paragraphs

common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/RequestHeaderMetricFilter.java
=> CB-9195 Turn off caller id metrics, it generates too much data currently

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java
Just adds in the latest YCloud fix from Jira: https://jira.cloudera.com/browse/CB-11981
=> Merge 2.41 to master

autoscale/src/main/java/com/sequenceiq/periscope/config/AppConfig.java
Create Different Executor Thread Pool for Async Executors so that Async tasks dont interfere with critical periscope monitors.
=> Create Different Executor Thread Pool for Async Executors

freeipa/src/main/resources/freeipa-salt/salt/nginx/conf/ssl.conf
=> CB-12000 Allow localhost traffic on FreeIPA nginx in case of CCMv2

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl.conf
=> CB-12000-allow-localhost-on-dl-dx-nginx

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeDiskSpaceValidationHandler.java
=> CB-11843 Fix merge issue-rebase issue

core/src/main/resources/application.yml, datalake/src/main/resources/application.yml
=> CB-9362 creating 10.14 postgres rds in case of aws

freeipa/src/main/resources/freeipa-salt/salt/freeipa/patch-pki-tomcat.sls, freeipa/src/main/resources/freeipa-salt/salt/top.sls
=> CB-9504 Replace FreeIPA error page

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/poller/GcpDatabasePollerProvider.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/GcpComputeResourceChecker.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/GcpDatabaseResourceChecker.java, cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/GcpDatabaseResourceCheckerTest.java
=> CB-11958 Gcp database and compute resource checkers retry on socket and connect timeout exceptions

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
=> CB-11889 add Retryable annotation to host orchestrator teardown

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/requests/ImageEntryV4Request.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/responses/ImageBasicInfoV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ImageCatalogGetFromDefaultByFilterUrlParser.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ImageCatalogGetFromDefaultByIdRestUrlParser.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ImageCatalogGetImageByNameAndByIdRestUrlParser.java, core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/RestUrlParserTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/imagecatalog/ImageCatalogGetImagesByNameAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v4/imagecatalog/ImageCatalogGetImagesFromDefaultCatalogAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/mock/MockCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/imagecatalog/ImageCatalogTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ImageCatalogTest.java
Added stub impl and interface for new imagecatalog API endpoints. They are needed to be able to expose the API to CDP CLI beta. Actual implementation will follow under CB-11904.
=> CB-12095: Added stub impl and interface for new imagecatalog API

structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/CDPStructuredFlowEventToCDPOperationDetailsConverter.java, structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/EnvironmentRequestProcessingStepMapper.java, structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/EnvironmentUseCaseMapper.java, structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/CDPStructuredFlowEventToCDPOperationDetailsConverterTest.java, structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/EnvironmentRequestProcessingStepMapperTest.java, structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/EnvironmentUseCaseMapperTest.java, structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToCDPOperationDetailsConverter.java, structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterRequestProcessingStepMapper.java, structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterUseCaseMapper.java, structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToCDPOperationDetailsConverterTest.java, structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterRequestProcessingStepMapperTest.java, structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterUseCaseMapperTest.java
=> CB-11964 Track previous flow state on finished and failed messages

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/responses/ImageV4Response.java
These changes should have been added to the API as part of CB-12095
=> CB-12112: Added missing parameters

flow/src/test/java/com/sequenceiq/flow/reactor/config/EventBusConfigTest.java
=> CB-11404 Create spring integration tests for reactor fail handling

authorization-common/src/main/java/com/sequenceiq/authorization/service/ResourceNameListAuthorizationFactory.java, authorization-common/src/test/java/com/sequenceiq/authorization/service/ResourceNameListAuthorizationFactoryTest.java
=> CB-12097 [DATADOG] Cannot delete cluster template becuause of authz

environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/FreeIpaImageRequest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/FreeIpaImageResponse.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/FreeIpaResponse.java, environment/src/main/java/com/sequenceiq/environment/environment/domain/Environment.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/FreeIpaConverter.java, environment/src/main/resources/schema/app/20210414221023_CB-11907_Add_freeipa_image_catalog_and_image_id_to_environment.sql, environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/FreeIpaConverterTest.java
=> CB-11907 Persist freeipa image catalog and image id at env creation time so it can be fetched for freeipa service calls.

freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageServiceTest.java
=> CB-12140 Extend image filtering logic to match by the image uuid as well

datalake/src/main/java/com/sequenceiq/datalake/flow/stop/handler/SdxStopWaitHandler.java
=> CB-7972 Increase datalake stop timeout to 120 min

datalake/src/main/java/com/sequenceiq/datalake/flow/delete/SdxDeleteActions.java
=> CB-12099 I added/changed/improved more info about the errors

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/base/ImageCatalogV4Base.java, core-api/src/main/java/com/sequenceiq/cloudbreak/client/internal/CloudbreakApiClientConfig.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/CustomImage.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/ImageCatalog.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/VmImage.java, core/src/main/java/com/sequenceiq/cloudbreak/authorization/ImageCatalogFiltering.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/ImageCatalogRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ImageCatalogGetFromDefaultByIdRestUrlParser.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ImageCatalogGetImageByNameAndByIdRestUrlParser.java, core/src/main/resources/schema/app/20210404204500_CB-11904_custom_image_management.sql, core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/configuration/CloudbreakApiConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/configuration/ServiceEndpointConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/dto/ImageWrapper.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/image/CoreImageProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/image/FreeIpaImageProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageProvider.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageProviderFactory.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java, freeipa/src/main/resources/application.yml, freeipa/src/test/java/com/sequenceiq/freeipa/service/image/CoreImageProviderTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/image/FreeIpaImageProviderTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageProviderFactoryTest.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageServiceTest.java
Partial implementation in based on the "contract first" design philosophy - right now having the fixed API interfaces finalized and made available for other subsystems is way more important than the polished backend implementation, so implementation of those subsystems can progress without being blocked by this.
=> CB-11904 CB backend code for CRUD operations on custom catalogs

core/src/main/resources/defaults/blueprints/7.2.10/cdp-data-mart.bp, core/src/main/resources/defaults/blueprints/7.2.9/cdp-data-mart.bp
Reverts hortonworks/cloudbreak#10450
=> Revert "CB-11992:  Add zookeeper service to Datamart templates for 7.2.9 and …"

redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsApplication.java
=> CB-11822 DB states out of sync

authorization-common/src/main/java/com/sequenceiq/authorization/service/PermissionCheckService.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/model/HasRight.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/model/HasRightOnAll.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/model/HasRightOnAny.java, authorization-common/src/main/java/com/sequenceiq/authorization/utils/AuthorizationMessageUtils.java, authorization-common/src/test/java/com/sequenceiq/authorization/service/PermissionCheckServiceTest.java, authorization-common/src/test/java/com/sequenceiq/authorization/service/ResourceAuthorizationServiceTest.java, authorization-common/src/test/java/com/sequenceiq/authorization/service/model/HasRightOnAllTest.java, authorization-common/src/test/java/com/sequenceiq/authorization/service/model/HasRightOnAnyTest.java, authorization-common/src/test/java/com/sequenceiq/authorization/service/model/HasRightTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CreateDhWithDatahubCreator.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/CredentialCreateTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DataStewardTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/DatalakeDatahubCreateAuthTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvStopStartWithEnvAdmin.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/EnvironmentCreateTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/RecipeTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/AuthorizationTestUtil.java
=> CB-12178 Improve authz error messages

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchService.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/CreateLoadBalancerEntityHandler.java
When the stack network is updated during the in-place load balancer creation, persist those changes to
the database, and to the new stack object passed along during creation. Tested by calling the API on an
existing environment and verifying the database network table was updated, the new stack object had the
updated network information in subsequent steps, and the created load balancer used a public subnet
instead of a private one.
=> CB-12174 Logic to create in-place public load balancer is using private subnet

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/listfiltering/DataHubListFilteringTest.java
=> CB-12080 update datahub list filtering test

core/src/main/java/com/sequenceiq/cloudbreak/repository/ImageCatalogRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/RecipeViewRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/recipe/RecipeService.java, environment/src/main/java/com/sequenceiq/environment/environment/repository/EnvironmentRepository.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java
=> CB-12205 Fix N+1 queries in list filtering

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/view/InstanceGroupView.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceGroupViewRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceGroupService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactoryTest.java
Replace the expensive stack queries to more efficient ones.
=> CB-6227 Optimize CB queries for stack

autoscale-api/src/main/java/com/sequenceiq/periscope/common/MessageCode.java, autoscale-api/src/main/resources/messages/messages.properties, autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/CronTimeEvaluator.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluator.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandler.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingHandler.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandler.java, autoscale/src/main/java/com/sequenceiq/periscope/service/ClusterService.java, autoscale/src/main/java/com/sequenceiq/periscope/utils/LoggingUtils.java, autoscale/src/main/resources/logback.xml, autoscale/src/test/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluatorTest.java, autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandlerTest.java, autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/ScalingHandlerTest.java, autoscale/src/test/java/com/sequenceiq/periscope/monitor/handler/UpdateFailedHandlerTest.java, autoscale/src/test/java/com/sequenceiq/periscope/utils/LoggingUtilsTest.java
1. Periscope logback configuration updated to log resourceName, resourceCrn, tenant and relevant MDC Context.
2. Initialize Periscope Logger MDC Context correctly.
3. Propogate CB API Client Error Messages during Autoscaling trigger.
=> CB-12053 Improve Periscope Logging

core/src/main/resources/defaults/blueprints/7.2.10/cdp-opdb.bp
=> [COMPX-5900] Add QUEUEMANAGER service to ODS blueprint for 7.2.10

autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/CloudbreakCommunicator.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java, autoscale/src/test/java/com/sequenceiq/periscope/controller/AutoscaleClusterCommonServiceTest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakInternalCrnClient.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
=> CB-12078 Revert - CB Scaling API that works with internal crns.

environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/FreeIpaImageRequest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/FreeIpaImageResponse.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/FreeIpaResponse.java, environment/src/main/java/com/sequenceiq/environment/environment/domain/Environment.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentDtoConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/FreeIpaConverter.java, environment/src/main/resources/schema/app/20210414221023_CB-11907_Add_freeipa_image_catalog_and_image_id_to_environment.sql, environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/FreeIpaConverterTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/image/ImageServiceTest.java
=> CB-12236 Backport freeipa image catalog bugfixes from 2.42

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonCloudProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/AbstractIntegrationTest.java
=> CB-12254 Adds support to define the freeipa image explicitly.

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/AddUserToGroupAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/CreateUserGroupAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/DeleteUserGroupAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/ListGroupMembersAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/UmsTestClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ums/UmsGroupTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ums/UmsTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/request/ums/AssignResourceRequest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/request/ums/CreateUserGroupRequest.java
Need to implement following UMS Client actions:
1. Create user group
2. Delete user group
3. Add user to group
4. Remove user from group
5. List members of group
Beyond this we need a new UMS User TestDTO, Client actions and a related UMS Group Request as well.
=> CB-12247 Implement UMS User Group TestDTO and Client Actions for Integration Test module

freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaChecker.java
The FreeIPA instance IDs was added to the logging of the health
checks.
=> CB-12270: Add logging instance metadata for FreeIPA health checks

build.gradle, datalake/build.gradle, freeipa-api/build.gradle, freeipa/build.gradle, redbeams/build.gradle
=> CDPCP-3974. Make sure the same swagger version is used for every module

freeipa/src/main/resources/application.yml
=> 2.42 to master

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, autoscale/src/main/java/com/sequenceiq/periscope/controller/AutoScaleClusterCommonService.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/CloudbreakCommunicator.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java, autoscale/src/test/java/com/sequenceiq/periscope/controller/AutoscaleClusterCommonServiceTest.java, cluster-dns-connector/src/main/java/com/sequenceiq/cloudbreak/certificate/poller/CreateCertificationPoller.java, cluster-dns-connector/src/main/java/com/sequenceiq/cloudbreak/certificate/service/CertificateCreationService.java, cluster-dns-connector/src/main/java/com/sequenceiq/cloudbreak/certificate/service/DnsManagementService.java, cluster-dns-connector/src/main/java/com/sequenceiq/cloudbreak/client/GrpcClusterDnsClient.java, cluster-dns-connector/src/test/java/com/sequenceiq/cloudbreak/component/CreateCertificationTest.java, cluster-dns-connector/src/test/java/com/sequenceiq/cloudbreak/component/DnsManagementServiceTest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/client/CloudbreakInternalCrnClient.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java, core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/BasePublicEndpointManagementService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/GatewayPublicEndpointManagementService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/publicendpoint/dns/BaseDnsEntryService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/publicendpoint/GatewayPublicEndpointManagementServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/publicendpoint/dns/BaseDnsEntryServiceTest.java
=> CB-12078 autoscale and clusterdnsclient should use internal actor

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsLogRolePermissionValidator.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsLaunchTest.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsRepairTest.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpProvisionSetup.java, common/src/main/java/com/sequenceiq/cloudbreak/cloud/storage/LocationHelper.java, common/src/test/java/com/sequenceiq/cloudbreak/cloud/storage/LocationHelperTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/RedbeamsApplication.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProvider.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/s3/S3ConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/s3/S3ConfigProviderTest.java
=> Merge 2.42 to master

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java
CB-11813 Apropriate message why end-user can or cannot upgrade
=> CB-11813 Apropriate message why end-user can or cannot upgrade

mock-thunderhead/src/main/resources/application.yml
This is a quick fix for the local tests.
=> CB-11204 current GUI test only work if dynamo table is enabled. 

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTerminationHelperService.java
Trying out some smaller PRs here.
Closes [CB-12307](https://jira.cloudera.com/browse/CB-12307).
* Extract `delete*` methods from the main termination method.
* Prefer two-element Enum to boolean flag value.
* Move `if` out of `deleteLoadBalancers` method.
This is a subtask for [CB-11644](https://jira.cloudera.com/browse/CB-11644), handle Azure load balancers in upscale/downscale operations.
=> CB-12307: Extract methods, add termination operations enum.

freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
=> CB-12315 N+1 query in user sync

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/MultiHostgroupDownscaleFlowEventChainFactory.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/MultiHostgroupDownscaleFlowEventChainFactoryTest.java, structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/mapper/ClusterUseCaseMapper.java
=> CB-12291 Fix missing downscale events from usage collection logging

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/spot/SpotTestResultProvider.java
=> CB-12385 Fix spot failure reason detection

core/src/main/java/com/sequenceiq/cloudbreak/repository/ImageCatalogRepository.java, core/src/main/resources/schema/app/20210430133333_CB-12359_Allow_null_value_for_image_catalog_url.sql
=> CB-12359 Allow null value for image catalog url and allow null value for resource lookup as well.

core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/RestartClusterManagerServerHandler.java, orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java, orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/agent-cert-permission.sls, orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/restart.sls
ENGESC-8291 modifying agent cert dirs permission to 755 on all hosts in case of autotls certificate rotation
=> ENGESC-8291 modifying agent cert dirs permission to 755 on all hosts in case of autotls certificate rotation

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
=> CB-12382 imagew catalog APIs used by sdx creation with custom catalog should be internally callable

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_replica_install.sh
We have seen during cluster provisioning that ipa client install sometimes misses adding DNS records.
During cluster provision we ensure the right records exists with a custom script.
This script is slightly modified and added to replica installation to ensure more stable FreeIPA HA provisioning.
=> CB-12208 FreeIPA replica install failed with missing PTR record

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResourcesTest.java, common/src/main/java/com/sequenceiq/cloudbreak/service/Retry.java, common/src/test/java/com/sequenceiq/cloudbreak/service/RetryTest.java
=> Merge 242 to master

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureResourceConnector.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureImageFormatValidator.java, cloud-azure/src/main/resources/templates/arm-v2-freeipa.ftl, core/src/main/resources/application.yml, freeipa/src/main/resources/application.yml
This contains 2 commits:
1. switch for automatic signing of image terms
2. a new conditional statement in the ARM template for FreeIPA deployments to use Marketplace plans only for Marketplace images.
I have validated the bugfix with both a regular and a Marketplace FreeIPA deployment.
=> CB-11814 Azure image partnercenter - follow ups

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionAcceptor.java, orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/poller/join/MinionAcceptorTest.java
Checks were added to ensure that salt bootstraping API calls are only
performed if there are new unaccepted minions that need to be accepted
by the salt master. If an old node hasn't been accepted but it has
since been deleted, then the check will ensure that no API call is
made. This prevents salt from returning an error code which broke the
repair process.
This was tested with unit tests and with a local deployment of
cloudbreak.
=> CB-12474: Fix salt bootstraping for old unaccepted minions

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ambari/AmbariDecommissioner.java
Add HBASE region server decommission with condition
=> Engesc 7779

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/util/AwsEncodedAuthorizationFailureMessageDecoder.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/util/AwsEncodedAuthorizationFailureMessageDecoderTest.java
=> CB-12175 Provide better error message in case of AWS authorization error

integration-test/README.md
L0 Promotion tests (Manowar Dev API E2E) has some special Makefile target and environment variable in the test project. So a related README section would be very useful for the future.
=> CB-12486 Create a new README section (in Integration Test module) for L0 Promotion and UMS tests

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/response/AwsCredentialPrerequisites.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/response/CredentialBasePrerequisites.java, environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentExperienceDto.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/experience/EnvironmentExperienceDeletionAction.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/experience/ExperienceDeletionRetrievalTask.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/experience/ExperiencePollerObject.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentResourceDeletionService.java, environment/src/main/java/com/sequenceiq/environment/experience/Experience.java, environment/src/main/java/com/sequenceiq/environment/experience/ExperienceConnectorService.java, environment/src/main/java/com/sequenceiq/environment/experience/api/CommonExperienceApi.java, environment/src/main/java/com/sequenceiq/environment/experience/api/LiftieApi.java, environment/src/main/java/com/sequenceiq/environment/experience/common/CommonExperience.java, environment/src/main/java/com/sequenceiq/environment/experience/common/CommonExperienceConnectorService.java, environment/src/main/java/com/sequenceiq/environment/experience/common/CommonExperienceService.java, environment/src/main/java/com/sequenceiq/environment/experience/common/CommonExperienceWebTargetProvider.java, environment/src/main/java/com/sequenceiq/environment/experience/liftie/ExperiencesByLiftie.java, environment/src/main/java/com/sequenceiq/environment/experience/policy/response/ExperiencePolicyResponse.java, environment/src/main/resources/experiences-config.yml, environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/experience/ExperienceDeletionRetrievalTaskTest.java, environment/src/test/java/com/sequenceiq/environment/experience/common/CommonExperienceConnectorServiceTest.java, environment/src/test/java/com/sequenceiq/environment/experience/common/CommonExperienceWebTargetProviderTest.java
=> CB-12490 - Experience call logic

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java
=> CB-12495 Removes unused and unnecessary api methods.

authorization-common/README.md, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AuditEventV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintUtilV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/BlueprintV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ClusterTemplateV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/DatabaseV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/FileSystemV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/RecipesV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/WorkspaceAwareUtilV4Controller.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/ClusterTemplateV4ControllerTest.java
=> CB-12402 CB controllers should use workspaceid from threadlocal

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/EnvironmentBaseNetworkConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4Converter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/EnvironmentBaseNetworkConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4ConverterTest.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentLoadBalancerService.java, environment/src/main/java/com/sequenceiq/environment/environment/service/network/NetworkMetadataValidationService.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java, environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentLoadBalancerServiceTest.java, environment/src/test/java/com/sequenceiq/environment/environment/service/network/NetworkMetadataValidationServiceTest.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/EnvironmentControllerTest.java
The endpoint gateway feature is GA, so removing the entitlement checks. The entitlement itself
still exists and will be removed later.
=> CB-12444 Remove entitlement check for endpoint gateway feature

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureNetworkConnector.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureNetworkConnectorTest.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/network/aws/AwsEnvironmentNetworkValidator.java, environment/src/test/java/com/sequenceiq/environment/environment/validation/network/AwsEnvironmentNetworkValidatorTest.java
=> edh improvements

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/CustomImageCatalogV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/request/CustomImageCatalogV4CreateImageRequest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/request/CustomImageCatalogV4CreateRequest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/request/CustomImageCatalogV4UpdateImageRequest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/request/CustomImageCatalogV4VmImageRequest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4CreateImageResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4CreateResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4DeleteImageResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4DeleteResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4GetImageResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4GetResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4ListItemResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4ListResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4UpdateImageResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4VmImageResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ControllerDescription.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/Notes.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/CustomImageCatalogV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4CustomImageCatalogByNameRestUrlParser.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4CustomImageCatalogCreateImageRestUrlParser.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4CustomImageCatalogGetImageByNameAndByIdRestUrlParser.java, core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/RestUrlParserTest.java
=> CB-12438 Adds separated endpoint for custom image catalog management

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialVerifier.java, cloud-aws/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialVerifierTest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/CustomImageCatalogV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/request/CustomImageCatalogV4CreateImageRequest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/request/CustomImageCatalogV4CreateRequest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/request/CustomImageCatalogV4UpdateImageRequest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/request/CustomImageCatalogV4VmImageRequest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4CreateImageResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4CreateResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4DeleteImageResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4DeleteResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4GetImageResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4GetResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4ListItemResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4ListResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4UpdateImageResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4VmImageResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ControllerDescription.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/Notes.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/CustomImageCatalogV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4CustomImageCatalogByNameRestUrlParser.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4CustomImageCatalogCreateImageRestUrlParser.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4CustomImageCatalogGetImageByNameAndByIdRestUrlParser.java, core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/RestUrlParserTest.java
=> Merge 2.43

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/blueprint/requests/BlueprintV4Request.java, core-api/src/main/java/com/sequenceiq/cloudbreak/validation/DeprecatedValidator.java, core-api/src/main/java/com/sequenceiq/cloudbreak/validation/ValidDeprecated.java, core-api/src/test/java/com/sequenceiq/cloudbreak/validation/DeprecatedValidatorTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilter.java, core/src/main/resources/defaults/blueprints/7.2.10/cdp-sdx-medium-ha.bp, core/src/main/resources/defaults/blueprints/7.2.11/cdp-sdx-medium-ha.bp, core/src/main/resources/defaults/blueprints/7.2.6/cdp-sdx-medium-ha.bp, core/src/main/resources/defaults/blueprints/7.2.7/cdp-sdx-medium-ha.bp, core/src/main/resources/defaults/blueprints/7.2.8/cdp-sdx-medium-ha.bp, core/src/main/resources/defaults/blueprints/7.2.9/cdp-sdx-medium-ha.bp, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilterTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/blueprint/BlueprintTestDto.java
=> Merge 2.43 to master

common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/AbstractMetricService.java, common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/MetricService.java, common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/JobCountMetricConfigurator.java
=> CB-12449 Use MetricService for creating gauge metrics

datalake/src/main/resources/application.yml, integration-test/src/main/resources/application.yml
=> CB-12574 Change default runtime to 7.2.9

cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ReadConfigEndpoint.java, cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ReadConfigResponse.java, cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/ReadConfigService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/polling/clusterproxy/ServiceEndpointHealthListenerTask.java
CB-11055 Freeipa clusterproxy registration timeout errormessage improvement
=> CB-11055 Freeipa clusterproxy registration timeout errormessage improvement

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java
Error message is misleading, for example:
```
16:05:33.298 [main] ERROR c.s.i.c.u.s.action.SshJClientActions [InternalSdxRepairWithRecipeTest.testSDXMultiRepairIDBRokerAndMasterWithRecipeFile] - Create SSH client is failing on '10.112.17.110' host with user: 'null' and password: 'null'!
16:05:33.303 [main] ERROR c.s.i.cloudbreak.context.TestContext [InternalSdxRepairWithRecipeTest.testSDXMultiRepairIDBRokerAndMasterWithRecipeFile] - then [InternalSdxRepairWithRecipeTest$$Lambda$603/0x00000008009e1c40] assertion is failed:  Create SSH client is failing on '10.112.17.110' host with user: 'null' and password: 'null'! , name: aws-test-dd0a59285a
```
at [SshJClientActions.java checkFilesByNameAndPath](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/seque …
=> CB-12363 Fix the error messages with exception at SshJClientActions

datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java, datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxUpgradeController.java
=> CB-12560 crn based sdx APIs should be internally callable

core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java
tested locally by standing up stack, now uses aws elb address for CM URL
=> CB-12288 Use LB frontend even if LB is not registered with PEM

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsModelService.java
=> CB-12547 Duplication in AwsModelService.java regarding PrefixListIds calculation

common/src/main/java/com/sequenceiq/cloudbreak/util/JaxRSUtil.java, common/src/main/resources/messages/jaxrs-messages.yaml, environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationRetrievalTask.java
CB-12013 Improve error message of cluster proxy timeout
=> CB-12013 Improve error message of cluster proxy timeout

common/src/main/java/com/sequenceiq/cloudbreak/logger/format/CustomJsonLayout.java
=> CB-12661. Make sure partial id for CB JSON log event is always string

common/src/main/java/com/sequenceiq/cloudbreak/common/type/TemporaryStorage.java, common/src/main/java/com/sequenceiq/cloudbreak/converter/TemporaryStorageConverter.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/instancegroup/template/InstanceTemplateV4Request.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/instancegroup/template/InstanceTemplateV1Request.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Template.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/instancegroup/template/InstanceTemplateV4RequestToTemplateConverter.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateV1ToInstanceTemplateV4Converter.java, core/src/main/resources/schema/app/20210518125355_CB-12613_Add_TemporaryStorage_to_Template.sql
This field will controll if only ephemeral storage should be initialized for VMs
=> CB-12613 Added temporaryStorage field to InstanceTemplate in DataHub post API

core/src/main/java/com/sequenceiq/cloudbreak/service/ServiceEndpointCollector.java, core/src/test/java/com/sequenceiq/cloudbreak/service/ServiceEndpointCollectorTest.java
=> Merge242to243

cloud-aws/src/main/resources/definitions/cdp/aws-cdp-bucket-access-policy.json
Is it ok to merge it to master? @lnardai
=> CB-12498 remove s3:ListBucket for '*' resource

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/CustomImageCatalogV4Endpoint.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/CustomImageCatalogV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/CustomImageCatalogV4ControllerTest.java
=> CB-12625: Fixed access permissions to match the new rules

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/events/EventV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/client/internal/CloudbreakApiClientConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/EventV4Controller.java
=> CB-12535 cb event API should be authorized

node-status-monitor-client/src/generated/main/java/com/cloudera/thunderhead/telemetry/nodestatus/NodeStatusProto.java, node-status-monitor-client/src/main/proto/nodestatus.proto, orchestrator-salt/src/main/resources/salt-common/salt/filecollector/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/nodestatus/settings.sls
=> CB-12683. Fix typo in nodestatus.proto (statusReason of SaltMinionHealth

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateServiceTest.java
We skip and log the results of checkPackageVersions.
=> CB-12684 - Disable package version check during upgrade

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/VolumeSetAttributes.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsContextService.java, cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/config/generator/OfflineStateGenerator.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/CollectDownscaleCandidatesHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MountDisks.java, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java, core/src/test/java/com/sequenceiq/cloudbreak/reactor/CollectDownscaleCandidatesHandlerTest.java
This reverts commit c67596b952a89c99fa52fcbbf43d960b3679488d.
=> Revert "CB-11720 Tie volume sets to discovery FQDNs"

core/src/main/java/com/sequenceiq/cloudbreak/service/image/CustomImageCatalogService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/image/CustomImageCatalogServiceTest.java
=> CB-12741 Adds missing validation for custom image catalog requests.

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/event/EnvCreationEvent.java, environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/EnvCreationActionsTest.java
=> CB-12742-FreeIPA_creation_stuck_in_creating_state

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureVirtualMachineService.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureVirtualMachineServiceTest.java
in the resource group we should retry the operation and eventually fail if we can't find any machine. We found this strange behaviour during e2e testing, VMs were started, disks attached, but azure returned an empty list.
=> CB-12774 in case azure return an empty list of VMs

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/KerberosConfigValidationActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/event/PollBindUserCreationEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/handler/PollBindUserCreationHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/handler/StartBindUserCreationService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaCleanupService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaOperationCheckerTask.java, core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaOperationPollerObject.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/handler/PollBindUserCreationHandlerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/handler/StartBindUserCreationServiceTest.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/operation/OperationV1Endpoint.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/OperationV1Controller.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaOperationWaitObject.java
=> CB-12829 Datahub creation fails with Environment Admin and DH creator

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/KerberosConfigValidationActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/event/PollBindUserCreationEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/handler/PollBindUserCreationHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/handler/StartBindUserCreationService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaCleanupService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaOperationCheckerTask.java, core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaOperationPollerObject.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/handler/PollBindUserCreationHandlerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/validate/kerberosconfig/handler/StartBindUserCreationServiceTest.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/operation/OperationV1Endpoint.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/OperationV1Controller.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaOperationWaitObject.java
=> 2.43 to master

orchestrator-salt/src/main/resources/salt-common/salt/filecollector/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/filecollector/settings.sls, orchestrator-salt/src/main/resources/salt-common/salt/filecollector/upload.sls, orchestrator-salt/src/main/resources/salt-common/salt/telemetry/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/telemetry/settings.sls, orchestrator-salt/src/main/resources/salt-common/salt/telemetry/template/proxy-whitelist.txt.j2
=> CB-12762. Support no_proxy for cdp-telemetry (diagnostics) operations.

core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionCheckerType.java, core/src/main/java/com/sequenceiq/cloudbreak/conclusion/step/NetworkCheckerConclusionStep.java, core/src/test/java/com/sequenceiq/cloudbreak/conclusion/step/NetworkCheckerConclusionStepTest.java
Checks:
- cloudera.com
- CCM health check
- any neighbours accessible check
=> CB-12587 Implement network checker concluson step

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/NetworkDeleteHandler.java, environment/src/main/resources/schema/app/20210531103742_CB-11570_change_env_network_name_to_text.sql
=> CB-11570 SQL error in SDX service, because: value too long for type character varying(255)

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/DefaultImageCatalogService.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ImageCatalogGetFromDefaultByFilterWithRuntimeUrlParser.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ImageCatalogGetFromDefaultByFilterWithoutRuntimeUrlParser.java, core/src/test/java/com/sequenceiq/cloudbreak/service/image/DefaultImageCatalogServiceTest.java
=> CB-12624 Implement image lookups from default image catalogs (both cloudbreak and freeipa). They are going to be used by CDP CLI.

node-status-monitor-client/src/generated/main/java/com/cloudera/thunderhead/telemetry/nodestatus/NodeStatusProto.java, node-status-monitor-client/src/main/proto/nodestatus.proto, orchestrator-salt/src/main/resources/salt-common/salt/filecollector/init.sls
- support cdp-telemetry version in responses
- support salt-keys in salt healthcheck responses
=> CB-12841. Update nodestatus proto + latest cdp-telemetry version

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/ImageToStackImageV4ResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackToStackV4ResponseConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/StackToStackV4ResponseConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/ImageToStackImageV4ResponseConverterTest.java
=> CB-12854 Image conversions should handle missing image catalog url like the image is a custom image.

core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java
=> CB-12840 Fix cluster provision in case of custom image where the image catalog url is null

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java
=> CB-12868: Added @AccountId where it was missing

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateParameterConverter.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateV1ToInstanceTemplateV4Converter.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceTemplateV1ToInstanceTemplateV4ConverterTest.java
=> Merge 243 to master

common/src/main/java/com/sequenceiq/cloudbreak/telemetry/monitoring/MonitoringConfiguration.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/TelemetryConverter.java, core/src/main/resources/application.yml, environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/TelemetryApiConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverter.java, freeipa/src/main/resources/application.yml, freeipa/src/test/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverterTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/clouderamanager/ClouderaManagerSetupTest.java
=> CB-12054. Enable CM metrics collection by default

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
Today, if any data hubs are attached, we block deletion of data lakes.
However, there are many use cases where we want to backup, delete,
recreate and restore on to a new datalake (with the same name). We
already have a --force option. Let's use this flag to force delete
a datalake when there are datahubs attached (and are stopped).
=> CB-12675: Allow force deletion of data lake

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/request/CustomImageCatalogV4CreateImageRequest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/request/CustomImageCatalogV4UpdateImageRequest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4GetImageResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/CustomImageCatalogV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/ImageToStackImageV4ResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackToStackV4ResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/CustomImageCatalogService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/DefaultImageCatalogService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ImageCatalogGetFromDefaultByFilterWithRuntimeUrlParser.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4ImageCatalogGetFromDefaultByFilterWithoutRuntimeUrlParser.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/CustomImageCatalogV4ControllerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/StackToStackV4ResponseConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/stacks/ImageToStackImageV4ResponseConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/image/CustomImageCatalogServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/image/DefaultImageCatalogServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java
=> CB-12861: Merge cb243hotfix1 to master

core/src/main/resources/defaults/blueprints/7.1.0/cdp-flow-management-small.bp, core/src/main/resources/defaults/blueprints/7.1.0/cdp-flow-management.bp, core/src/main/resources/defaults/blueprints/7.2.0/cdp-flow-management-small.bp, core/src/main/resources/defaults/blueprints/7.2.0/cdp-flow-management.bp, core/src/main/resources/defaults/blueprints/7.2.1/cdp-flow-management-small.bp, core/src/main/resources/defaults/blueprints/7.2.1/cdp-flow-management.bp, core/src/main/resources/defaults/blueprints/7.2.10/cdp-flow-management-small.bp, core/src/main/resources/defaults/blueprints/7.2.10/cdp-flow-management.bp, core/src/main/resources/defaults/blueprints/7.2.2/cdp-flow-management-small.bp, core/src/main/resources/defaults/blueprints/7.2.2/cdp-flow-management.bp, core/src/main/resources/defaults/blueprints/7.2.6/cdp-flow-management-small.bp, core/src/main/resources/defaults/blueprints/7.2.6/cdp-flow-management.bp, core/src/main/resources/defaults/blueprints/7.2.7/cdp-flow-management-small.bp, core/src/main/resources/defaults/blueprints/7.2.7/cdp-flow-management.bp, core/src/main/resources/defaults/blueprints/7.2.8/cdp-flow-management-small.bp, core/src/main/resources/defaults/blueprints/7.2.8/cdp-flow-management.bp, core/src/main/resources/defaults/blueprints/7.2.9/cdp-flow-management-small.bp, core/src/main/resources/defaults/blueprints/7.2.9/cdp-flow-management.bp
=> CFM-2032 Set rlimit_fds = 500000 for earlier versions in CB

core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/InstanceGroupToInstanceGroupDetailsConverter.java, structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/InstanceGroupDetails.java, structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToClusterShapeConverter.java, structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToClusterShapeConverterTest.java, usage-collection/src/generated/main/java/com/cloudera/thunderhead/service/common/usage/UsageProto.java, usage-collection/src/main/proto/usage.proto
=> CB-12635 TemporalStorage feature tracking in EDH

cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNativeConnector.java
=> CB-12899 Add Aws native Validators

environment/src/main/java/com/sequenceiq/environment/credential/service/CredentialPrerequisiteService.java
=> CB-12925 fixing experience policy query, using account id

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/ums/AssignResourceRoleUserAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/BasicEnvironmentVirtualGroupTest.java
[MOW Dev API E2E Build #75-2.44.0-b47-AWS (30-May-2021 16:34:12)](http://ci-cloudbreak.eng.hortonworks.com/job/mow-api-e2e-aws/75/) E2E test build is failing, because of [testAddGroupsToEnvironment](http://ci-cloudbreak.eng.hortonworks.com/job/mow-api-e2e-aws/75/testngreports/com.sequenceiq.it.cloudbreak.testcase.e2e.l0promotion/BasicEnvironmentVirtualGroupTest/testAddGroupsToEnvironment/) test is failing with:
```
io.grpc.StatusRuntimeException: ALREADY_EXISTS: Resource role 'crn:altus:iam:us-west-1:altus:resourceRole:IamGroupAdmin' is already assigned to 'crn:altus:iam:us-west-1:f8e2f110-fc7e-4e46-ae55-381aacc6718c:machineUser:cb-qe-machine-envcreator-a/36840cef-b14c-4863-b9de-698e7b15b18c' for resource 'crn:altus:iam:us-west-1:f8e2f110-fc7e-4e46-ae55-381aacc6718c:group:testgroupa/ebc27a …
```
=> CB-12831 testAddGroupsToEnvironment test is failing AssignResourceRoleUserAction: ALREADY_EXISTS

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/filesystems/FileSystemV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/FileSystemV4Controller.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifester.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifesterTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxBlueprintLoadTests.java
=> CB-12963 Datalake blueprints are not loaded on env create

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/filesystems/FileSystemV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/EndpointConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/FileSystemV4Controller.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifester.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifesterTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxBlueprintLoadTests.java
=> 2.44 to master

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnResourceManagerRoleConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/yarn/YarnResourceManagerRoleConfigProviderTest.java
- Placement rules for AM / non-AM conrtainers being set based on CDP
version for now.
=> CB-12273. Set up YARN container placement preference rules.

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ImageComponentUpdaterService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilter.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilterTest.java
=> CB-12922 Fix cluster upgrade in case of the image catalog url is missing.

core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/RegisterPublicDnsHandler.java
When populating the instance metadata for the stack, include the metadata for all gateway instances
instead of only the primary gateway metadata. This will allow the set-endpoint-access-gateway
functionality to be run on stack with multiple gateway isstance, e.g. medium duty data lakes.
Tested by calling the set-endpoint-access-gateway API on a medium duty environment.
=> CB-12962 set-endpoint-access-gateway fails on existing Medium duty environment

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateService.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/stack/loadbalancer/handler/RegisterPublicDnsHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ImageComponentUpdaterService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilter.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterUpgradeAvailabilityServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/ClusterUpgradeImageFilterTest.java
=> Merge changes from 2.44 to master

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureVirtualMachineService.java
e.g repair both hostgroups, we should allow it to continue
=> CB-12774 its possible that a RG contains no VMs, 

cloud-azure/src/main/resources/definitions/azure-enabled-regions.json
=> CB-12945 Remove unsupported Azure regions

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsConnector.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/StackV4Request.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/DistroXV1Request.java, core/build.gradle, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java, core/src/main/resources/application.yml
=> CB-13022 Add variont to DistroX and aws-native module to core module

common/src/main/java/com/sequenceiq/cloudbreak/service/LoggerRetryListener.java, common/src/main/java/com/sequenceiq/cloudbreak/util/JaxRSUtil.java, orchestrator-salt/src/test/java/com/sequenceiq/cloudbreak/orchestrator/salt/utils/JaxRSUtilTest.java
Implement custom RetryListener and log retry related events.
=> CB-12466 Check HTTP status codes for Salt responses.

datalake/src/main/resources/schema/app/20210615082119_CB-11570_change_tag_type_to_text_in_sdxcluster_table.sql
=> CB-11570 Change sdxcluser table's tags column to text

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/ClusterUpgradeActions.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/upgrade/ClusterUpgradeInitRequest.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterUpgradeInitHandler.java
CB-10661 Download parcels before stopping services during upgrade
=> CB-10661 Download parcels before stopping services during upgrade

common-model/src/main/java/com/sequenceiq/common/api/type/Tunnel.java, common/src/test/java/com/sequenceiq/cloudbreak/converter/TunnelConverterTest.java
=> CB-12695-new-tunneltype

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/InstanceMetadataUpdater.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateActionsTest.java
=> Merge244master

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePermissionProvider.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePermissionProviderTest.java
It happened in production that a version (7.2.10) was offered as an upgrade
candidate, but the 7.2.10 version was not supported yet. This is because
the upgrade filter did not check whether a version is supported or not. It
only checks the upgrade matrix. However, there is a separate env variable
called cb.runtimes.latest that tells what is the latest supported version.
As part of this PR the upgrade filters will consider this variable also
when offering the new versions.
@lnardai @akanto this is a draft PR that we could deploy as a hotfix for 2.44.
=> CB-13080 check if the target runtime version is supported for upgrade

template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/CodHadoopTempDirConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/AbstractHbaseConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/CodHadoopTempDirConfigProviderTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hbase/HbaseCloudStorageServiceConfigProviderTest.java
Added new `hadoop.tmp.dir` setting to all COD specific blueprints.
=> ODX-684 Move hadoop.tmp.dir out of /tmp

core/build.gradle
=> CB-13128 Disable aws native in core

core/src/main/resources/defaults/blueprints/7.2.11/cdp-flink-heavy.bp, core/src/main/resources/defaults/blueprints/7.2.11/cdp-flink-light.bp
Also changed the SSB `refName`.
=> CB-13147 Add Kafka to built-in CSA blueprints

core/src/main/resources/schema/app/20210621151941_CB-6506_change_secret_paths_to_text.sql, environment/src/main/resources/schema/app/20210621111048_CB-6506_change_secret_paths_to_text.sql, freeipa/src/main/resources/schema/app/20210621121127_CB-6506_change_secret_paths_to_text.sql, redbeams/src/main/resources/schema/app/20210621103712_CB-6506_change_secret_paths_to_text.sql
=> CB-6506 Change all Vault path structure in DB (varchar(255))

core/src/main/resources/defaults/vm-logs.json
=> Fixing vm-log path pattern typos

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelper.java, cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackRequestHelperTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaUserSyncTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaTests.java
=> Merge aws cf workaround

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4GetResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/customimage/response/CustomImageCatalogV4ImageListItemResponse.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/customimage/CustomImageToCustomImageCatalogV4GetImageResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/customimage/ImageCatalogToCustomImageCatalogV4GetResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/customimage/ImageVersionsConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/customimage/CustomImageToCustomImageCatalogV4GetImageResponseConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/v4/customimage/ImageCatalogToCustomImageCatalogV4GetResponseConverterTest.java
=> CB-13169 Extend describe custom image and custom image catalog with new properties

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/instancegroup/template/InstanceTemplateV4RequestToTemplateConverter.java
=> CB-13184 Handle TemporaryStorage null value when using public API

freeipa/src/main/resources/freeipa-salt/salt/nginx/conf/ssl.conf, orchestrator-salt/src/main/resources/salt/salt/nginx/conf/clouderamanager-ssl-user-facing.conf, orchestrator-salt/src/main/resources/salt/salt/nginx/conf/ssl.conf
Add a response header in our nginx so we can check if the request reached nginx,
or failed between CB - CCM
=> CB-13210 Add custom nginx response header

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/InstanceStoreMetadata.java, cloud-api/src/test/java/com/sequenceiq/cloudbreak/cloud/model/InstanceStoreMetadataTest.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsAttachmentResourceBuilder.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilder.java, cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsVolumeResourceBuilderTest.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsPlatformParameters.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/view/AwsGroupView.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilder.java, common-model/src/main/java/com/sequenceiq/common/model/AwsDiskType.java, core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/service/StackCreationService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackStopRestrictionService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/service/StackCreationServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackStopRestrictionServiceTest.java
This commit was merged to master, however its part of a feature promised for 2.45 and technically a bugfix.
=> CB-12939 Always request instance storage on AWS

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsStackValidator.java
=> CB-12939 fix master build

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientTest.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/BlackListedUpScaleRole.java
=> CB-10915 Enable scaling for Kafka broker type nodes

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/util/CloudProviderSideTagAssertion.java
=> CB-12410 fix env tag verification for tests

freeipa/src/main/java/com/sequenceiq/freeipa/converter/cloud/StackToCloudStackConverter.java
=> CB-13186 fix NPE in StackToCloudStackConverter

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/objectstorage/AzureParameters.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/objectstorage/ObjectStorageValidateRequest.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureObjectStorageConnector.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidator.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidatorTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapperTest.java, datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidator.java
=> Merge CB-2.45.0

structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/EnvironmentDetailsToCDPEnvironmentDetailsConverter.java, structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/EnvironmentDetailsToCDPEnvironmentDetailsConverterTest.java, usage-collection/src/generated/main/java/com/cloudera/thunderhead/service/common/usage/UsageProto.java, usage-collection/src/main/proto/usage.proto
CB-11740: Integrate with Telemetry solution
Adding a new property to CDPEnvironmentAzureDetails, bool resourceEncryptionEnabled, this is set only when encryptionKeyUrl is present.
As encryptionKeyUrl is present only when "CDP_CB_AZURE_DISK_SSE_WITH_CMK" is enabled and encryptionKey is provided during environment creation, checking its presence is sufficient to know if user is using "Azure SSE with CMK".
**Thunderhead changes** - https://github.infra.cloudera.com/thunderhead/thunderhead/pull/5132
**When encryptionKeyUrl was provided :**
**When encryptionKeyUrl was NOT provided :**
=> CB-11740: Integrate with Telemetry solution.

core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionChecker.java, core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionCheckerFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionCheckerType.java, core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionStepNode.java, core/src/main/java/com/sequenceiq/cloudbreak/conclusion/ConclusionStepNodeFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/conclusion/step/VmStatusCheckerConclusionStep.java, core/src/test/java/com/sequenceiq/cloudbreak/conclusion/ConclusionCheckerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/conclusion/step/VmStatusCheckerConclusionStepTest.java
If CM is running get host statuses from CM, otherwise get status information from provider.
=> CB-13244 Check cloud provider vm statuses during conclusion checks

environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/experience/ExperienceDeletionRetrievalTask.java, environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/experience/ExperienceDeletionRetrievalTaskTest.java
=> CB-13314 raising experience delete polling timout

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MountDisks.java, orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
=> CB-13294 Pillar save should include all nodes, even unreached ones.

cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilder.java
=> CB-13285 UserData doesn't filled during aws native instance creation

environment/src/main/java/com/sequenceiq/environment/environment/validation/network/azure/AzureEnvironmentNetworkValidator.java, environment/src/test/java/com/sequenceiq/environment/environment/validation/network/AzureEnvironmentNetworkValidatorTest.java
=> CB-13323 fix typo when invalid Azure networks setup is provided

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/resource/AzureAttachmentResourceBuilder.java
=> CB-13188 Fix variable rename

environment/src/main/java/com/sequenceiq/environment/experience/ExperienceConnectorService.java
=> CB-12294 - additional logs

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentRequest.java, environment/src/main/java/com/sequenceiq/environment/environment/domain/ExperimentalFeatures.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java
=> CB-13007 - missing "ccm_version" argument for create environment

freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiKeyEndpoints.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaApiUserCrnEndpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/FreeIpaClient.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/client/internal/FreeIpaApiClientConfig.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaOperationDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/upgrade/FreeIpaUpgradeV1Endpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/upgrade/model/FreeIpaUpgradeOptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/upgrade/model/FreeIpaUpgradeRequest.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/upgrade/model/FreeIpaUpgradeResponse.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/upgrade/model/ImageInfoResponse.java, freeipa/src/main/java/com/sequenceiq/freeipa/configuration/EndpointConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaUpgradeV1Controller.java
- new endpoint
- `upgradeFreeIpa` method to initiate upgrade
- `getFreeIpaUpgradeOptions` to fetch upgrade candidate images
=> CB-12456 FreeIPA upgrade API

core/src/main/resources/schema/app/20210531123804_CB-12760_Add_index_to_resources_table.sql
=> CB-12760 Add index for stackid and resourcetype query

core/src/main/resources/defaults/blueprints/7.2.11/cdp-sdx-medium-ha.bp, core/src/main/resources/defaults/blueprints/7.2.12/cdp-sdx-medium-ha.bp
=> CB-13364 enable DL upgrade for 7.2.11 and 7.2.12

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/error/mapper/ClouderaManagerStorageErrorMapper.java
Refactors `ClouderaManagerStorageErrorMapper` as per the post-merge suggestions of #11043.
=> CB-13349 Follow-up ClouderaManagerStorageErrorMapper refactor

core/src/main/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/sharedservice/DatalakeServiceTest.java
=> CB-13358 SharedServiceConfigsView filled in every cases

mock-thunderhead/src/main/resources/application.yml
=> CB-13385 disable aws cloud storage validation for local and qa envs

freeipa/src/main/java/com/sequenceiq/freeipa/service/image/FreeIpaImageProvider.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/image/FreeIpaImageProviderTest.java
=> CB-13393 Image lookup by image uuid should not filter images by OS.

datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/handler/DatalakeUpgradeWaitHandler.java, datalake/src/main/java/com/sequenceiq/datalake/flow/repair/handler/SdxRepairWaitHandler.java
=> CB-13398 increase DL repair timeout to 120 min in DL service

freeipa/src/main/java/com/sequenceiq/freeipa/controller/OperationV1Controller.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/operation/FlowOperationService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/operation/OperationService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/operation/FlowOperationServiceTest.java
=> CB-13391. Fix freeipa circular dependency (because of flow operation service)

common-model/src/main/java/com/sequenceiq/common/model/diagnostics/DiagnosticParameters.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/converter/FlowPayloadToDiagnosticDetailsConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/DiagnosticsCollectionActions.java, freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/diagnostics/DiagnosticsCollectionActions.java
=> CB-13413. Add status reason for list diagnostics output.

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
Covering edge-case when volumes have been created but infra creation failed before volume attachment which is causing volume sets are not assigned to any instance and volume deletion fails on updating attributes of the related instance.
=> CB-12805 volume deletion not to call instnace attribute update on AWS when no instance has been assigned to volume set

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClientTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidator.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/BlackListedDownScaleRole.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/BlackListedUpScaleRole.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidator.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/EntitledForServiceScale.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidatorTest.java, template-manager-cmtemplate/src/test/resources/input/kafka-cc_7_2_12.bp, template-manager-cmtemplate/src/test/resources/input/kafka-no-cc_7_2_12.bp
=> Kafka fixes

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
=> CB-13423 fix awaitForHealthyInstances NPE

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterTerminationService.java
=> Optimize cluster telemetry cleanup on termination.

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudResource.java, cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/EIpAttributes.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsLaunchService.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleService.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/client/AmazonEc2Client.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/connector/resource/AwsElasticIpService.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/connector/resource/AwsNetworkService.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/service/AwsResourceNameService.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeEIPResourceBuilder.java, cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeEIPResourceBuilderTest.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/util/ResourceAttributeUtil.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/ResourceToCloudResourceConverter.java
=> CB-13282 Add EIP support to instances

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNetworkConnector.java, cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNetworkConnectorTest.java, environment/src/main/java/com/sequenceiq/environment/network/v1/converter/EnvironmentBaseNetworkConverter.java, environment/src/test/java/com/sequenceiq/environment/network/v1/converter/AwsEnvironmentNetworkConverterTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/image/FreeIpaImageProvider.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/image/FreeIpaImageProviderTest.java
=> Merge245to246

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNetworkConnector.java, cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNetworkConnectorTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/TerminationService.java, environment/src/main/java/com/sequenceiq/environment/network/v1/converter/EnvironmentBaseNetworkConverter.java, environment/src/test/java/com/sequenceiq/environment/network/v1/converter/AwsEnvironmentNetworkConverterTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxInternalTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/sdx/SdxTestDto.java
=> Merge246tomaster

core/src/main/resources/application.yml, core/src/main/resources/defaults/blueprints/7.2.12/cdp-streaming-small.bp, core/src/main/resources/defaults/blueprints/7.2.12/cdp-streaming.bp, core/src/main/resources/defaults/clustertemplates/7.2.12/aws/streaming-small.json, core/src/main/resources/defaults/clustertemplates/7.2.12/aws/streaming.json, core/src/main/resources/defaults/clustertemplates/7.2.12/azure/streaming-small.json, core/src/main/resources/defaults/clustertemplates/7.2.12/azure/streaming.json, core/src/main/resources/defaults/clustertemplates/7.2.12/gcp/streaming-small.json, core/src/main/resources/defaults/clustertemplates/7.2.12/gcp/streaming.json, core/src/main/resources/defaults/clustertemplates/7.2.12/yarn/streaming-small.json, core/src/main/resources/defaults/clustertemplates/7.2.12/yarn/streaming.json
Cruise Control is added to the Streams Messaging blueprints as of 7.2.12
Testing: manual
=> CB-10916 CruiseControl in Streaming blueprint for 2.7.12

cloud-aws-cloudformation/src/test/resources/application.yml, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/service/AwsResourceNameService.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/loadbalancer/AwsNativeLoadBalancerLaunchService.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/loadbalancer/AwsNativeLoadBalancerListenerResourceBuilder.java, core/src/main/resources/application.yml, environment/src/main/resources/application-test.yml, environment/src/main/resources/application.yml, freeipa/src/main/resources/application.yml, redbeams/src/main/resources/application.yml
=> Fix for native AWS loadbalancer and it's resources names and resource metadata deletion

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxBackupEndpoint.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxRestoreEndpoint.java, datalake-api/src/main/java/com/sequenceiq/sdx/client/SdxClient.java, datalake-api/src/main/java/com/sequenceiq/sdx/client/SdxServiceApiKeyEndpoints.java, datalake-api/src/main/java/com/sequenceiq/sdx/client/SdxServiceCrnEndpoints.java, datalake-api/src/main/java/com/sequenceiq/sdx/client/internal/SdxApiClientConfig.java, datalake/src/main/java/com/sequenceiq/datalake/configuration/EndpointConfig.java, datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxBackupController.java, datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java, datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxRestoreController.java, datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxBackupControllerTest.java, datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxControllerTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxBackupAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxRestoreAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/l0promotion/SdxBackupRestoreTest.java
=> CB-13405 backup and restore should have different controller

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java, authorization-common/src/main/resources/legacyRights.json, freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaUpgradeV1Controller.java
=> CB-13338 Add FreeIPA upgrade right

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java, datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
=> CB-13459 Support internal actor bulk list request for SDX DataLake API

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsDefaultZoneProvider.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsSessionCredentialClient.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/service/AwsResourceNameService.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/metadata/AwsNativeMetadataCollector.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsNativeResourceBuilderOrderConstants.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/alarm/AwsNativeCloudWatchResourceBuilder.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/alarm/AwsNativeCloudWatchService.java, cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/alarm/AwsNativeCloudWatchServiceTest.java, common-model/src/main/java/com/sequenceiq/common/api/type/ResourceType.java, common/src/main/java/com/sequenceiq/cloudbreak/telemetry/fluent/FluentConfigService.java
=> CB-13283 - Add CloudWatch alarm to the instances

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudResource.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsMetadataCollector.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationStackUtil.java, cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/AwsContextServiceTest.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureCloudResourceService.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/context/VolumeMatcher.java, cloud-template/src/test/java/com/sequenceiq/cloudbreak/cloud/template/context/VolumeMatcherTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MountDisks.java
=> CB-13434 fix volume mount for AWS and Azure

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/connector/resource/AwsLoadBalancerCommonService.java, cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/connector/resource/AwsLoadBalancerCommonServiceTest.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsNativeConnector.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsGatewaySubnetMultiAzValidator.java, cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/validator/AwsGatewaySubnetMultiAzValidatorTest.java
=> Multi-AZ support of AWS native load balancers

core/src/main/resources/schema/app/20210719141901_CB-13065_remove_datalakeresource_and_servicedescriptor.sql
=> CB-13065 remove datalakeresource and servicedescriptor tables

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/DiagnosticsFlowService.java, usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/LoggingUsageReporter.java, usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/UsageReporter.java, usage-collection/src/main/proto/usage.proto
=> CB-13501. Send preflight check (network) results to EDH.

freeipa/src/main/resources/freeipa-salt/salt/freeipa/grow-disk.sls, freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/grow_disk.sh, freeipa/src/main/resources/freeipa-salt/salt/top.sls
Tested with Azure FreeIPA:
```
[cloudbreak@ipaserver0 ~]$ lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0      2:0    1    4K  0 disk
sda      8:0    0  100G  0 disk
|-sda1   8:1    0  500M  0 part /boot
`-sda2   8:2    0 99.5G  0 part /
sdb      8:16   0  200G  0 disk
`-sdb1   8:17   0  200G  0 part /mnt/resource
sr0     11:0    1  638K  0 rom
```
=> CB-13502 - FreeIPA OS disk remains 30 GB

freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/grow_disk.sh
=> CB-13502 add missing method to grow_disk.sh

common/src/main/java/com/sequenceiq/cloudbreak/util/SecurityGroupSeparator.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceGroupV1ToInstanceGroupV4Converter.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SecurityAccessManifester.java, environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/base/SecurityAccessBase.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/SecurityAccessResponse.java, environment/src/main/java/com/sequenceiq/environment/environment/domain/Environment.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/securitygroup/aws/AwsEnvironmentSecurityGroupValidator.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/securitygroup/azure/AzureEnvironmentSecurityGroupValidator.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/securitygroup/gcp/GcpEnvironmentSecurityGroupValidator.java, environment/src/main/resources/schema/app/20210712114059_CB-13174_increase_securitygroup_length.sql, environment/src/test/java/com/sequenceiq/environment/environment/validation/securitygroup/AwsEnvironmentSecurityGroupValidatorTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/stack/AllocateDatabaseServerV4RequestToDBStackConverter.java
=> CB-13174 Allow multiple Security Group adding the list to the responses

orchestrator-salt/src/main/resources/salt-common/salt/nodestatus/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/nodestatus/settings.sls, orchestrator-salt/src/main/resources/salt-common/salt/telemetry/settings.sls
=> CB-13523. Upscale - resize failing with Orchestrator component error.

cloud-gcp/src/main/resources/definitions/gcp-audit-prerequisites-creation-command.json, cloud-gcp/src/main/resources/definitions/gcp-prerequisites-creation-command.json
=> CB-13524 GCP credential setup: hint for gcloud init

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/DownscaleFlowEventChainFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/StackDownscaleTriggerEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/AbstractStackDownscaleAction.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackScalingFlowContext.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/AbstractStackUpscaleAction.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/CollectDownscaleCandidatesHandler.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleServiceTest.java
=> CB-13434 Move fillDiscoveryFQDNForRepair to stackDownscale from clusterDownscale

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java
=> CB-13548 NullPointerException in DistroxTestDto.awaitForHostGroup method

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/StackV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/StackViewV4Response.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackToStackV4ResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/view/StackApiViewToStackViewV4ResponseConverter.java, structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToClusterDetailsConverter.java, structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToClusterDetailsConverterTest.java, usage-collection/src/main/proto/usage.proto
=> CB-13511 adding the variant to the stack response

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/DiagnosticsFlowService.java, usage-collection/src/main/proto/usage.proto
=> CB-13501. Extends network check usage data

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/distrox/AvailabilityZoneAssertion.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/EnvironmentTestClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXCustomTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/EnvironmentTest.java, integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests-for-native.yaml
=> CB-12810 add assertion to multiaz case

cloud-common/src/main/java/com/sequenceiq/cloudbreak/polling/PollingService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
=> Merge 2.45 to 2.46

mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java, mock-thunderhead/src/main/resources/application.yml
=> CB-13622 Add freeipa batch call entitlement property

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java
=> CB-13554 fix compile issue

environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentModelDescription.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/aws/AwsDiskEncryptionParameters.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/aws/AwsEnvironmentParameters.java, environment-api/src/test/java/com/sequenceiq/environment/api/v1/environment/model/request/aws/AwsDiskEncryptionParametersTest.java
=> CB-13108:Add validations for accepting CMK from create-aws-environment cli

auth-internal/src/main/java/com/sequenceiq/cloudbreak/auth/security/internal/InternalCrnModifier.java, authorization-common/src/main/java/com/sequenceiq/authorization/service/PermissionCheckService.java, common/src/main/java/com/sequenceiq/cloudbreak/logger/MDCBuilder.java
=> CB-13625 Set tenant in MDC context when user crn is internal crn.

cloud-common/src/main/java/com/sequenceiq/cloudbreak/polling/PollingService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterBootstrapper.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java, mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java, mock-thunderhead/src/main/resources/application.yml
=> Merge 246 into master

orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
=> Merge CB-2.46.0 into master

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java
Validate if repairable node list is not empty.
=> CB-11452 Make the downsize workflow in CB more robust.

core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogServiceTest.java
Custom catalog 'list' cli command also returns cloudbreak-default which unfortunately is not a custom catalog.
=> CB-13680: Custom catalog list returns the cloudbreak-default

cloud-gcp/src/main/resources/definitions/gcp-zone-coordinates.json
=> CB-13670 adding asia-southeast2 to gcp region json

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java
=> CB-6076 Put storage path location valdation into datalake creation flow.

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterStatusService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusServiceTest.java, core/src/main/java/com/sequenceiq/cloudbreak/conclusion/step/VmStatusCheckerConclusionStep.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRuntimeVersionValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/RuntimeVersionService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityService.java, core/src/test/java/com/sequenceiq/cloudbreak/conclusion/step/VmStatusCheckerConclusionStepTest.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRuntimeVersionValidatorTest.java, core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJobTest.java, core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusIntegrationTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/RuntimeVersionServiceTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityServiceTest.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
- service health check has been taken into consideration if runtime is higher than 7.2.11
- logic of getting runtime for stack moved into a dedicated service
=> CB-13723 Optimise CM service health check

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterStatusService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterStatusServiceTest.java, core/src/main/java/com/sequenceiq/cloudbreak/conclusion/step/VmStatusCheckerConclusionStep.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRuntimeVersionValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJob.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/RuntimeVersionService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityService.java, core/src/test/java/com/sequenceiq/cloudbreak/conclusion/step/VmStatusCheckerConclusionStepTest.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackRuntimeVersionValidatorTest.java, core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusCheckerJobTest.java, core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusIntegrationTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/RuntimeVersionServiceTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityServiceTest.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
=> 2.46 to master

common/src/main/java/com/sequenceiq/cloudbreak/client/RestClientUtil.java
=> CB-13687 enable GZIP in RestClientUtil

common/src/main/java/com/sequenceiq/cloudbreak/client/RestClientUtil.java
=> Cb 246 to master

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/instancegroup/DistroXInstanceGroupsBuilder.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/AwsDistroXEphemeralTemporaryStorageTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/ClouderaManagerUtil.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/clouderamanager/action/ClouderaManagerClientActions.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java, integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
=> CB-13151 E2E test for deploying cluster with ephemeral disk caching

core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/BlueprintLoaderService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderServiceTest.java
=> CB-13619 decreasing list-cluster-template operation runtime

core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/BlueprintLoaderService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderServiceTest.java
This reverts commit 1ce60f453bc67c3d041fd26b590367fae88da715.
=> Revert "CB-13619 decreasing list-cluster-template operation runtime"

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentValidationHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/service/cloudstorage/CloudStorageValidator.java, environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentValidationHandlerTest.java, environment/src/test/java/com/sequenceiq/environment/environment/validation/cloudstorage/CloudStorageValidatorTest.java
=> CB-10814 Validate FreeIPA storage paths before deployment

core/src/main/java/com/sequenceiq/cloudbreak/conf/LimitConfiguration.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/InstanceMetaDataRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/NodeCountLimitValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java, core/src/main/resources/application.yml, core/src/test/java/com/sequenceiq/cloudbreak/controller/StackCreatorServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/NodeCountLimitValidatorTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterUpscaleDownscaleTest.java
=> CB-13796 Hard limit of 500 nodes for the cluster size for CB

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyServiceTest.java
=> CB-13867 Registering 443 as ccmv2config into CP

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/catalog/ImagePackageVersion.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/image/ImageComponentVersions.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/image/ParcelInfoResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentVersionProvider.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ComponentVersionProviderTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityServiceTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeImageSelectorTest.java
Parcel info is returned on the Upgrade Endpoint:
=> CB-13836 - Upgrade endpoint should contains parcel info

cluster-proxy/src/main/java/com/sequenceiq/cloudbreak/clusterproxy/CcmV2Config.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyServiceTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ClusterProxyService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/ClusterProxyServiceTest.java
This reverts commit 377b7460c1421c265b0709d1be96e24e503e96a9.
=> Revert "CB-13867 Registering 443 as ccmv2config into CP" and cherry-pick CDPAM-2112: Add agentCrn from CB request during registration

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpForwardingRuleResourceBuilder.java, cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/loadbalancer/GcpForwardingRuleResourceBuilderTest.java
needs to be validated in mowdev to networking issues on local set up
unit tests expanded to cover multiple vpc settings
=> [CB-13876] issue with creating forwarding rule for shared vpcs

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/service/ClusterComponentConfigProvider.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterComponentViewRepository.java, core-model/src/test/java/com/sequenceiq/cloudbreak/TestUtil.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackStopRestrictionService.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/template/TemplateValidatorTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/clusterproxy/ClusterProxyServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackStopRestrictionServiceTest.java
=> 2.47 to master

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java, cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java
new unit tests covering dl master vs free ipa master
local testing found this issue initially
=> [CB-12826] fix upscale to assign to correct group

core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityService.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/upgrade/DistroXUpgradeAvailabilityServiceTest.java
DH cluster upgrade validates the parent SDX cluster being launched with RAZ.
There is an exception if the entitlement CDP_RUNTIME_UPGRADE_DATAHUB is granted, then we do not enforce this validation.
=> CB-13870 - RAZ cluster can't be upgraded

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/GroupNetwork.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/connector/resource/AwsLoadBalancerCommonService.java, cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/connector/resource/AwsLoadBalancerCommonServiceTest.java, common/src/main/java/com/sequenceiq/cloudbreak/common/network/NetworkConstants.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/parameter/instancegroup/network/aws/InstanceGroupAwsNetworkV4Parameters.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/network/aws/InstanceGroupAwsNetworkV1Parameters.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/InstanceGroupNetworkParameterConverter.java
=> Merge 2.47.0 into master

environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorService.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyArnValidator.java, environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentCreationServiceTest.java, environment/src/test/java/com/sequenceiq/environment/environment/validation/EnvironmentValidatorServiceTest.java, environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyArnValidatorTest.java
Once the PR for CB-13110 https://github.com/hortonworks/cloudbreak/pull/11106 is merged to master I will remove all those changes from this PR and just leave the validation changes in this PR
=> CB-13109:Add cloudbreak validations for Encryption Arn passed from CLI

core/src/main/resources/defaults/vm-logs.json, freeipa/src/main/resources/defaults/vm-logs.json, freeipa/src/main/resources/freeipa-salt/salt/logrotate/init.sls, orchestrator-salt/src/main/resources/salt-common/salt/logrotate/conf/salt, orchestrator-salt/src/main/resources/salt/salt/logrotate/init.sls, orchestrator-salt/src/main/resources/salt/salt/top.sls
=> CB-13859. Enable log rotation for salt logs.

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/CloudResource.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationStackUtil.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsCloudWatchService.java, cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsCloudWatchServiceTest.java
=> CB-13901 Only attempt to put recovery alarm for supported instance types

authorization-common-api/src/main/java/com/sequenceiq/authorization/resource/AuthorizationResourceAction.java, authorization-common/src/main/java/com/sequenceiq/authorization/utils/EventAuthorizationDto.java, authorization-common/src/main/java/com/sequenceiq/authorization/utils/EventAuthorizationUtils.java, authorization-common/src/main/java/com/sequenceiq/authorization/utils/LegacyResourceTypes.java, authorization-common/src/test/java/com/sequenceiq/authorization/utils/EventAuthorizationUtilsTest.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/audits/AuditEventV4Endpoint.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AuditEventV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/service/audit/AuditEventService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/V4AuditEventRestUrlParser.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/AuditEventV4ControllerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/urlparsers/RestUrlParserTest.java, structuredevent-api-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/endpoint/CDPStructuredEventV1Endpoint.java, structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/CloudbreakEventService.java, structuredevent-service-cdp/build.gradle, structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/rest/controller/CDPStructuredEventV1Controller.java, structuredevent-service-cdp/src/test/java/com/sequenceiq/cloudbreak/structuredevent/rest/controller/CDPStructuredEventV1ControllerTest.java
=> CB-12780 - Audit API and new event API should be authorized

core/src/main/resources/defaults/blueprints/7.2.12/cdp-data-engineering-ha.bp
=> DISTX-693 In DE HA Template dfs_replication should be reduced to 2

common/src/main/java/com/sequenceiq/cloudbreak/client/RPCMessage.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/image/ImageSettingsV4Request.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/Blueprint.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/StackStatus.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/cluster/Cluster.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/instance/InstanceGroup.java, structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StructuredEvent.java, structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/cdp/CDPStructuredEvent.java, structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/legacy/OperationDetails.java
=> CB-11450 Add missing toString() implementations

common-model/src/main/java/com/sequenceiq/common/model/FileSystemType.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/cloudstorage/CmCloudStorageConfigDetailsTest.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/filesystem/CloudStorageConfigDetails.java
=> CB-13960 Support paths (folders) for ABFS base location

core/src/main/java/com/sequenceiq/cloudbreak/service/events/CloudbreakEventHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java, integration-test/scripts/check-results.sh
=> CB-13996 DataLake notifications are missing

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/view/GcpLoadBalancerMetadataView.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/loadbalancer/GcpLoadBalancerResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/loadbalancer/GcpTargetGroupResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/loadbalancer/LoadBalancerResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/loadbalancer/TargetGroupResponse.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/loadbalancer/LoadBalancerConfigDbWrapper.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/loadbalancer/TargetGroupConfigDbWrapper.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/loadbalancer/gcp/GcpLoadBalancerConfigDb.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/loadbalancer/gcp/GcpLoadBalancerNamesDb.java, core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/loadbalancer/gcp/GcpTargetGroupConfigDb.java, core/build.gradle, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/loadbalancer/LoadBalancerToLoadBalancerResponseConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/stack/loadbalancer/LoadBalancerToLoadBalancerResponseConverterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigConverterTest.java
This PR contains the necessary changes to build out the responses to the CLI call 
unit testing only
still to come metadata collectors that get the required information to be packaged into the response
=> [CB-13177]Gather GCP medium duty datalake load balancer configs and return via cdp cli

core/src/main/java/com/sequenceiq/cloudbreak/service/events/CloudbreakEventHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/events/DefaultCloudbreakEventService.java, integration-test/scripts/check-results.sh
This reverts commit dc30ff034df8ed87d5bf9da4103dcab4f9b5560e.
=> Revert "CB-13996 DataLake notifications are missing"

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
Made sure the existing file is replaced instead of throwing File exists error.
=> CB-14055: Failure on database backup with failure "File exists"

datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java, datalake/src/main/java/com/sequenceiq/datalake/flow/chain/DatalakeUpgradeFlowEventChainFactory.java, datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/DatalakeUpgradeEvent.java, datalake/src/main/java/com/sequenceiq/datalake/flow/datalake/upgrade/event/DatalakeUpgradeFlowChainStartEvent.java, datalake/src/test/java/com/sequenceiq/datalake/flow/SdxReactorFlowManagerTest.java
=> CB-14022 Remove datalake upgrade chain event from datalake upgrade events

common/src/main/resources/messages/messages.properties, core/src/main/java/com/sequenceiq/cloudbreak/controller/mapper/SendNotificationExceptionMapper.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/ProvisionerService.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRepairService.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/start/SdxStartService.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/stop/SdxStopService.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/ProvisionerServiceTest.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/start/SdxStartServiceTest.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/stop/SdxStopServiceTest.java
=> CB-13701 Empty Bad Request: notification arrives on UI

core/src/main/resources/defaults/blueprints/7.2.12/cdp-dde.bp
=> DISTX-690 Change ranger audit hdfs dir param in DDE bp

datalake/src/main/java/com/sequenceiq/datalake/flow/SdxReactorFlowManager.java, datalake/src/main/java/com/sequenceiq/datalake/flow/chain/DatalakeResizeFlowEventChainFactory.java, datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachEvent.java, datalake/src/main/java/com/sequenceiq/datalake/flow/detach/event/DatalakeResizeFlowChainStartEvent.java, flow/src/main/java/com/sequenceiq/flow/core/config/Flow2Initializer.java, flow/src/test/java/com/sequenceiq/flow/core/config/Flow2InitializerTest.java
=> CB-14077 Datalake resize triggers a flow and flow chain in the beginning which results in error

orchestrator-salt/src/main/resources/salt-common/salt/logrotate/conf/salt
=> CB-13859. Increase salt log backup count

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java
=> Fw merge rdoktorics 1

mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java, mock-thunderhead/src/main/resources/application.yml
=> CB-14128 Make CDP_ENABLE_DISTROX_INSTANCE_TYPES entitlement configurable in mock environment

core/src/main/resources/application.yml, core/src/main/resources/defaults/blueprints/7.2.13/cdp-sdx-micro.bp, datalake/src/main/resources/duties/7.2.13/aws/micro_duty.json, datalake/src/main/resources/duties/7.2.13/azure/micro_duty.json, datalake/src/main/resources/duties/7.2.13/gcp/micro_duty.json, datalake/src/main/resources/duties/7.2.13/yarn/micro_duty.json
=> CB-14118 Add Micro Duty to 7.2.13

.gitignore, audit-connector/build.gradle, auth-connector/build.gradle, auth-internal-api/build.gradle, auth-internal/build.gradle, authorization-common-api/build.gradle, authorization-common/build.gradle, autoscale/build.gradle, build.gradle, ccm-connector/build.gradle, cloud-common/build.gradle, cluster-dns-connector/build.gradle, cluster-proxy/build.gradle, core/build.gradle, databus-connector/build.gradle, datalake-dr-connector/build.gradle, datalake/build.gradle, environment/build.gradle, freeipa/build.gradle, grpc-common/build.gradle, idbmms-connector/build.gradle, integration-test/build.gradle, mock-infrastructure/build.gradle, mock-thunderhead/build.gradle, node-status-monitor-client/build.gradle, redbeams/build.gradle, usage-collection/build.gradle, workspace/build.gradle
=> CB-14141 Remove jcenter() as it is not working (403) and is already obsoleted

cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/GcpMetadataCollector.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/view/GcpLoadBalancerMetadataView.java, cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/GCPLoadBalancerMetadataCollectorTest.java
continuation of CB-13177. makes the calls to GCP to collect needed info for CLI reporting only
=> [CB-13177] collect information from GCP

core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java
=> CB-13989 Add number nodes added/removed in the metrics message

cloud-api/src/main/java/com/sequenceiq/cloudbreak/cloud/model/objectstorage/ObjectStorageValidateRequest.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsObjectStorageConnector.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/validator/AwsIDBrokerObjectStorageValidator.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureObjectStorageConnector.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidator.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureIDBrokerObjectStorageValidatorTest.java, datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidator.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentCloudStorageValidationRequest.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentValidationHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/service/cloudstorage/CloudStorageValidator.java, environment/src/test/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentValidationHandlerTest.java, mock-thunderhead/src/main/resources/application.yml
Adds validation to the backup cloud storage.
Switches on the aws cloud storage validation for local development.
=> CB-14109 Backup location base should be validated

datalake/src/main/java/com/sequenceiq/datalake/service/sdx/StackRequestManifester.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/StackRequestManifesterTest.java
Encrypting the datalake disks with GCP CMEK passed during gcp environment creation.
=> CB-13692: Encrypt datalake disks with CMEK based on encryption key parameter set in create-gcp-environment call

environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/FreeIpaConverter.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverterTest.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/FreeIpaConverterTest.java
=> CB-14204 disable force multiaz in case of aws entitlement.

core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXRepairV1RequestToClusterRepairV4RequestConverter.java
=> CB-14222 NPE in DistroXRepairV1RequestToClusterRepairV4RequestConverter

environment/src/main/resources/definitions/default-internal-tags.json, template-manager-tag/src/main/java/com/sequenceiq/cloudbreak/tag/TagTemplateProcessor.java, template-manager-tag/src/test/java/com/sequenceiq/cloudbreak/tag/TagTemplateProcessorTest.java
=> CB-14054 Extract username from email for {{{userName}}} tag value

ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2JumpgateParameterSupplier.java, ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2ParameterSupplier.java, ccm-connector/src/main/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/InvertingProxyAndAgent.java, ccm-connector/src/test/java/com/sequenceiq/cloudbreak/ccmimpl/cloudinit/DefaultCcmV2JumpgateParameterSupplierTest.java, common-model/src/main/java/com/sequenceiq/common/api/type/CcmV2TlsType.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/CcmV2ParameterConstants.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultCcmV2JumpgateParameters.java, common/src/main/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultCcmV2Parameters.java, common/src/test/java/com/sequenceiq/cloudbreak/ccm/cloudinit/DefaultCcmV2JumpgateParametersTest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/request/EnvironmentRequest.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/DetailedEnvironmentResponse.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentBaseResponse.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/SimpleEnvironmentResponse.java, environment/src/main/java/com/sequenceiq/environment/environment/domain/ExperimentalFeatures.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverter.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverter.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentApiConverterTest.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/converter/EnvironmentResponseConverterTest.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/image/userdata/UserDataBuilder.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/image/userdata/UserDataService.java, freeipa/src/main/resources/init/init.ftl, freeipa/src/test/java/com/sequenceiq/freeipa/service/image/userdata/UserDataBuilderTest.java, freeipa/src/test/resources/azure-ccm-v2-jumpgate-onewaytls-init.sh, freeipa/src/test/resources/azure-ccm-v2-jumpgate-twowaytls-init.sh
2 commits, the one is just nit fixes from a previous, already merged PR. 
Please check the 2 commits separately. Thanks.
=> CB-14185 Add entitlement and override checking for CCMv2 TLS mode

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/BlueprintFile.java, core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/BlueprintLoaderService.java, core/src/main/java/com/sequenceiq/cloudbreak/init/blueprint/DefaultBlueprintCache.java, core/src/test/java/com/sequenceiq/cloudbreak/init/blueprint/DefaulBlueprintCacheTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderServiceTest.java, integration-test/src/main/resources/testsuites/v4/mock/multithread.yaml
=> CB-13619 eliminating deep copy in BlueprintCache and using immutable objects instead

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/backup_db.sh
When the backup is performed with input not to close DB connections, we should not only avoid closing existing connections we should also avoid blocking new connections as well.
=> CB-14272: Avoid limiting the incoming connection while performing backup.

orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/mount-disks.j2
=> CB-13971 Mounting ephemeral storage disk to /hadoopfs/ephfs on Azure

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java, core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaConfigProvider.java, core/src/test/java/com/sequenceiq/cloudbreak/service/freeipa/FreeIpaConfigProviderTest.java
- moved the logic separate class
- refoctored logic to use separate streams
- added unit test
=> CB-14294 Fix reused stream

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/StopRestrictionReason.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackStopRestrictionService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePreconditionService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/StackStopRestrictionServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/UpgradePreconditionServiceTest.java
=> CB-14130 Fix stop restriction logic for AWS clusters

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsLaunchTemplateUpdateService.java
=> CB-12461 Fix of LaunchTemplateVersionRequest creation

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
CDPD-29553: Accessing Spark History server REST API through Apache Knox
Creating an endpoint on cdp-proxy-api for users trying to connect to Spark History Server via rest API.
Successful curl cmds- 
- For Spark3
```
juhig@MacBook-Pro ~ % curl -i  -u juhig -k -X GET --header 'Accept: application/json' "https://10.112.5.65/cdpd2spark3/cdp-proxy-api/spark3history/api/v1/applications/application_1632917528652_0004"
Enter host password for user 'juhig':
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 29 Sep 2021 12:25:04 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 380
Connection: keep-alive
Set-Cookie: KNOXSESSIONID=node01kcuhciwqzosv6c6vjx30cfgh3.node0; Path=/cdpd2spark3/cdp-proxy-api; Secure; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; …
```
=> CDPD-29553: Accessing Spark History server REST API through Apache Knox

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/request/InstanceGroupAdjustmentV4Request.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/autoscales/request/UpdateStackV4Request.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/StackScaleV4Request.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/network/NetworkScaleV4Request.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/ModelDescriptions.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/DistroXScaleV1Request.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/network/NetworkScaleV1Request.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/network/MultiAzValidator.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackScaleV4RequestToUpdateStackV4RequestConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/StackRepairFlowEventChainFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpscaleFlowEventChainFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/dto/NetworkScaleDetails.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/StackAndClusterUpscaleTriggerEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/StackScaleTriggerEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackScalingFlowContext.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/AbstractStackUpscaleAction.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleActions.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/recover/DatalakeRecoverySetupNewInstancesHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/multiaz/MultiAzCalculatorService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXScaleV1RequestToStackScaleV4RequestConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/upscale/StackUpscaleActionsTest.java, core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/recover/DatalakeRecoverySetupNewInstancesHandlerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/StackCommonServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/multiaz/MultiAzCalculatorServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/InstanceMetaDataServiceTest.java
At scaling the user could decide which availability zones should be preferred by control plane at instance provisioning.
=> CB-13673 support of preferred availability zones for datahub scaling.

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/ChangeImageCatalogV4Request.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxChangeImageCatalogRequest.java, datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/FreeIpaV1Endpoint.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/doc/FreeIpaOperationDescriptions.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/imagecatalog/ChangeImageCatalogRequest.java, freeipa/src/main/java/com/sequenceiq/freeipa/controller/FreeIpaV1Controller.java
Adds dummy implementations so we can work in parallel on the real implementation and on the related CLI changes.
=> CB-14307 Extend FreeIPA, DataLake and DataHub interfaces with change image catalog.

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentValidationHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/EnvironmentFlowValidatorService.java, environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyArnValidator.java, environment/src/test/java/com/sequenceiq/environment/environment/validation/validators/EncryptionKeyArnValidatorTest.java
Verified he change with invalid (correct format but wrong ARN(the ARN of the key which is not present on AWS on the specified region)) and the env creation failed as below<img width="864" alt="Screenshot 2021-09-14 at 1 42 51 PM" src="https://user-images.githubusercontent.com/7271603/133223673-07ac5b5f-412e-408c-948a-970f048540f9.png">
Also validated the successful env creation with valid key.
=> CB-13464:Add validation to check if the mentioned Key exists in AWS

.github/CODEOWNERS
=> CB-14371 Add relevant Wolf entires to CB CODEOWNERS

common/src/main/java/com/sequenceiq/cloudbreak/common/json/Json.java, freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/upgrade/model/FreeIpaUpgradeResponse.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/image/ImageService.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/FreeIpaClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIpaUpgradeAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/FreeIpaTestClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/AbstractCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CloudProviderProxy.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/FreeIpaProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/azure/AzureProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpCloudProvider.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/gcp/GcpProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractFreeIpaTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaOperationStatusTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaUserSyncTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/freeipa/FreeIpaOperationWaitObject.java, integration-test/src/main/resources/application.yml, integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/azure-longrunning-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/gcp-longrunning-e2e-tests.yaml
=> CB-13339 E2E test for FreeIPA upgrade

orchestrator-salt/src/main/resources/salt/salt/nginx/conf/clouderamanager-ssl-user-facing.conf
=> CB-14353 disable direct CM UI debug path in NGiNX configuration.

cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/metadata/AwsNativeMetadataCollector.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilder.java
=> CB-14340 native rollback fix

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java, datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
=> CB-14697. Fix query param validation for fetching instance groups.

datalake/src/main/java/com/sequenceiq/datalake/job/SdxClusterStatusCheckerJob.java, datalake/src/test/java/com/sequenceiq/datalake/job/SdxClusterStatusCheckerJobTest.java
- added short circuit for SdxClusterStatusCheckerJob when there is a running flow for that Datalake to prevent adhoc status changes
- it was causing sideeffect for SDX status WAITING_FOr_EXTERNAL_DATABASE_STOP would be switched to STOP making EnvService saying stop complete
=> CB-14721 added short circuit for SdxClusterStatusCheckerJob

common-model/src/main/java/com/sequenceiq/common/api/type/Tunnel.java, common-model/src/test/java/com/sequenceiq/common/api/type/TunnelTest.java, environment-api/src/main/java/com/sequenceiq/environment/api/doc/environment/EnvironmentOpDescription.java, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/endpoint/EnvironmentEndpoint.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/EnvironmentReactorFlowManager.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentUpgradeCcmService.java, environment/src/main/java/com/sequenceiq/environment/environment/v1/EnvironmentController.java, environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentUpgradeCcmServiceTest.java, environment/src/test/java/com/sequenceiq/environment/environment/v1/EnvironmentControllerTest.java
=> CB-14566 New Environment endpoint to trigger CCM upgrade workflow

core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java
=> CB-14694 Unintentionally the @ValidCrn was added to a name endpoint

datalake/src/main/java/com/sequenceiq/datalake/flow/create/handler/RdsWaitHandler.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/database/DatabaseService.java
=> CB-14754 raising polling duration on database creation from 60 to 80

orchestrator-salt/src/main/resources/salt/salt/cloudera/agent/upgrade.sls, orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/upgrade.sls, orchestrator-salt/src/main/resources/salt/salt/cloudera/scripts/check_cm_repo_url.sh.j2
CB-14206 CM upgrade related states are not failing if yum repo is not available
Was tested:
* valid repository
* invalid /etc/hosts
* invalid proxy password
=> CB-14206 CM upgrade related states are not failing if yum repo is not available

common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java, common/src/main/resources/messages/messages.properties, core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/resource/DecommissionResult.java, core/src/test/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandlerTest.java
=> CB-14751 Force delete and downscale should work when CM decommission fails

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilder.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsLaunchService.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/view/AwsRdsInstanceView.java, cloud-aws-cloudformation/src/main/resources/templates/aws-cf-dbstack.ftl, cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationTemplateBuilderDBTest.java, redbeams/src/main/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverter.java, redbeams/src/test/java/com/sequenceiq/redbeams/converter/spi/DBStackToDatabaseStackConverterTest.java
Environment created from cli with --encryption-key-arn and external rds encrypted with the kms key arn passed from environment :<img width="1042" alt="Screenshot 2021-11-02 at 5 56 28 PM" src="https://user-images.githubusercontent.com/7271603/139847312-aef11925-044d-41f8-a2d5-563811e0050e.png">
=> CB-14516:Encrypt External RDS with Custom Kms key id

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsSetup.java
=> CB-12148 added null check for availability zones in aws validateRegionAndZone

core/src/main/resources/schema/app/20211104142425_CB-14617_remove_idbroker_for_cluster_templates.sql
=> CB-14617 remove idbroker for cluster templates

core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCommonService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/InstanceGroupService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidator.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidator.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidatorTest.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/validation/BlueprintValidator.java
=> CB-14752 Validate Node Manager role count before downscale

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/service/AwsResourceNameService.java, cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilderTest.java, cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilder.java, cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpInstanceResourceBuilderTest.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/context/ResourceBuilderContext.java, cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/group/GroupResourceService.java, common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java, common/src/main/resources/messages/messages.properties, core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/resource/DecommissionResult.java, core/src/main/resources/schema/app/20211105113320_CB-14758_update_AWS_security_group_resources_to_have_instance_group_name_reference_based_on_resource_name.sql, core/src/test/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandlerTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/DistroXCreateAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/v1/distrox/FetchPreferredSubnetForInstanceNetworkIfMultiAzEnabledAction.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/distrox/AvailabilityZoneAssertion.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/client/DistroXTestClient.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDtoBase.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXRepairTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java, integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests-for-native.yaml, structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToClusterShapeConverter.java, structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToStatusDetailsConverter.java, structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToClusterShapeConverterTest.java, structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToStatusDetailsConverterTest.java
=> Mergecb249intomaster

datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/DatalakeBackupActions.java
When the backup operation fails, extract the message from the associated exception and include
it in the status message in the CDP UI. Also updates the status reason during a failure from
"Datalake backup failed, Datalake is running" (which makes it sound like the DL running is the
failure reason), to "Backup failed, returning datalake to running state."
Tested by inducing a backup failure locally and verifying the expected message appeared in the
UI's status reason field.
=> CB-14605 Datalake MD Upgrade Fails at "backup" with no meaningful information

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AwsEnvironmentWithCustomerManagedKeyTests.java, integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml
Tested the successful run of the e2e file with AWS CMK in environment creation.
=> CB-13203:Add nightly e2e tests for Environment creation with AWS CMK

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/imagecatalog/ImageCatalogV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/ImageCatalogV4Controller.java, datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java, datalake/src/main/java/com/sequenceiq/datalake/service/imagecatalog/ImageCatalogService.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java, datalake/src/test/java/com/sequenceiq/datalake/service/imagecatalog/ImageCatalogServiceTest.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxServiceTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/authorization/ChangeImageCatalogTest.java
=> CB-14783 Image catalog permission check while changing DataLake image catalog.

cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsAutoScalingService.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleService.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/CustomAmazonWaiterProvider.java, cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/scheduler/StackCancellationCheck.java, cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleServiceTest.java
=> CB-14607 Throw more usefull message for auto scaling failure than default aws waiter's message.

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/imagecatalog/GenerateImageCatalogV4Response.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/StackV4ControllerTest.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java, datalake-api/src/main/java/com/sequenceiq/sdx/api/model/SdxGenerateImageCatalogResponse.java, datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxImageCatalogService.java, datalake/src/test/java/com/sequenceiq/datalake/controller/sdx/SdxControllerTest.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxImageCatalogServiceTest.java
=> CB-14459 Generate image catalog based on the image used by SDX cluster

authorization-common/src/main/java/com/sequenceiq/authorization/service/RequestPropertyAuthorizationFactory.java, authorization-common/src/test/java/com/sequenceiq/authorization/service/RequestPropertyAuthorizationFactoryTest.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/DistroXV1Request.java
=> CB-14667 Change authorization error to bad request if the request doesn't contain required property.

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyServiceTest.java
And leave CCMv2.x endpoint configs on port 9443 with `/knox` pathprefix.
=> CB-14816 register Knox endpoint in ClusterProxy to port 443 in case of direct ClusterProxy or CCMv1 as tunnel type again

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AwsEnvironmentWithCustomerManagedKeyTests.java
=> CB-14832:Fix AWS KMS CMK format error

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/ssh/action/SshJClientActions.java, integration-test/src/main/resources/application.yml
Set a supported instance type for AWS tests
Azure test should use private ips when public ips are not available
=> CB-13974 Ephemeral storage e2e fixes

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/aws/AwsProperties.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/AwsEnvironmentWithCustomerManagedKeyTests.java, integration-test/src/main/resources/application.yml
=> CB-14832:[e2e] AWS KMS CMK format error

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerParcelActivationListenerTask.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerParcelActivationListenerTaskTest.java, core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterUpscaleService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyService.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/UpscaleClusterManagerHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterUpgradeHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/upgrade/ClusterUpgradeInitHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpgradeServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterUpscaleServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/provision/service/ClusterProxyServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/ClouderaManagerClusterCreationSetupServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelServiceTest.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/clouderamanager/CommandId.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/clouderamanager/base/ParcelResourceOperation.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/clouderamanager/v31/controller/ParcelResourceV31Controller.java
=> Merge CB-2.49.0 into master

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/AuthorizationClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/PersonalResourceViewClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/config/UmsClientConfig.java, autoscale/src/main/resources/application.yml, core/src/main/resources/application.yml, datalake/src/main/resources/application.yml, environment/src/main/resources/application.yml, freeipa/src/main/resources/application.yml, grpc-common/src/main/java/com/sequenceiq/cloudbreak/grpc/altus/CallingServiceNameInterceptor.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UmsClient.java, redbeams/src/main/resources/application.yml
=> CB-14482 Set the callingServiceName GRPC context for UMS calls

cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsResourceConnector.java, cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/service/DefaultCostTaggingService.java, cloud-common/src/main/java/com/sequenceiq/cloudbreak/common/type/DefaultApplicationTag.java, cloud-common/src/test/java/com/sequenceiq/cloudbreak/common/service/DefaultCostTaggingServiceTest.java
=> CB-14054 Extract username from email for owner tag

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/common/DetailedStackStatus.java
=> CB-14945 - Remove invalid upgrade failure statuses

orchestrator-salt/src/main/resources/salt/salt/unbound/init.sls
=> CB-14656 Skip unbound fix if the file is missing

integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests-for-native.yaml
=> CB-14951 ignore datahub repair in AWS native E2E test

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/start/StackStartStopService.java, flow/src/main/java/com/sequenceiq/flow/core/Flow2Handler.java
=> CB-14918 Add logs to Flow2Handler

datalake/src/main/java/com/sequenceiq/datalake/flow/chain/DatalakeResizeFlowEventChainFactory.java, datalake/src/main/java/com/sequenceiq/datalake/flow/datahub/StartDatahubActions.java, datalake/src/main/java/com/sequenceiq/datalake/flow/datahub/StartDatahubFlowConfig.java, datalake/src/main/java/com/sequenceiq/datalake/flow/datahub/StartDatahubFlowEvent.java, datalake/src/main/java/com/sequenceiq/datalake/flow/datahub/StartDatahubFlowState.java, datalake/src/main/java/com/sequenceiq/datalake/flow/datahub/event/StartDatahubFailedEvent.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/DistroxService.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/start/SdxStartService.java, datalake/src/test/java/com/sequenceiq/datalake/flow/chain/DatalakeResizeFlowEventChainTest.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/start/SdxStartServiceTest.java
Created a new flow within datalake to just call the proess to start
datahubs, and wait for the success of them becoming available. includes
a few service additions to support this process. tested with unit test
and a manual local test to confirm desired behavior
=> [CB-13626] Start datahub automatically after resize

integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml
=> CB-14421 add distroxscaletest to qa suite with small scale targets

cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureTemplateBuilder.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/loadbalancer/README.md
Closes [CB-14882](https://jira.cloudera.com/browse/CB-14882).
=> CB-14882: Add docs for Azure Load Balancer.

structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToImageDetailsConverter.java, structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToImageDetailsConverterTest.java, usage-collection/src/main/proto/usage.proto
=> CB-14943 Report the image catalog url and the os type to EDH.

auth-internal/src/main/java/com/sequenceiq/cloudbreak/auth/security/internal/InternalCrnModifier.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/UnboundRestartPatchService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/UnboundRestartPatchServiceTest.java
In prod the salt updates initiated by UnboundRestartPatchService failed with the following error: "Could not get SAML metadata file to set up IdP in KNOXSSO: NOT_FOUND: No account found with id: altus".
This could be reproduced locally by using dev UMS instead of mock, and setting the property distrox.gateway.ssotype to SSO_PROVIDER_FROM_UMS.
The fix includes calling the salt update with an internal user that is added to the account of the stack, and small improvements to logging.
=> CB-15104 Fix unbound restart stack patcher service

orchestrator-salt/src/main/resources/salt/salt/disks/service/scripts/mount-instance-storage.j2
Added a check to skip the script, of all volumes are mounted already.
=> CB-14883 mount-instance-storage service no longer mounts volumes twice

integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml
Reverts hortonworks/cloudbreak#11787
=> Revert "CB-14421 add distroxscaletest to qa suite with small scale targets"

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/README.md
Please let me know if I need to explain myself more, or if you'd like to see additional comments/docs in the Java side of things.
=> CB-14928: Add docs for DL backup/restore salt scripts.

auth-internal/src/main/java/com/sequenceiq/cloudbreak/auth/security/internal/InternalCrnModifier.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResourcesTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/UnboundRestartPatchService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/UnboundRestartPatchServiceTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverterTest.java
=> Merge 2.49.0 to 2.50.0

auth-internal/src/main/java/com/sequenceiq/cloudbreak/auth/security/internal/InternalCrnModifier.java, cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResources.java, cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java, cloud-azure/src/test/java/com/sequenceiq/cloudbreak/cloud/azure/AzureEncryptionResourcesTest.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/AbstractClouderaManagerCommandCheckerTask.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stackpatch/UnboundRestartPatchService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stackpatch/UnboundRestartPatchServiceTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/converter/DistroXV1RequestToStackV4RequestConverterTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRecoveryTests.java
=> Merge2.50tomaster

core/src/main/java/com/sequenceiq/cloudbreak/repository/HostGroupRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterCommonService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/hostgroup/HostGroupService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/UpdateNodeCountValidator.java, core/src/test/java/com/sequenceiq/cloudbreak/service/StackCommonServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidator.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidatorTest.java, template-manager-core/src/main/java/com/sequenceiq/cloudbreak/template/validation/BlueprintValidator.java
=> CB-14782 Add role count validation to scaling and remove instances.

cloud-gcp/src/main/resources/definitions/gcp-zone-coordinates.json
=> CB-15268 adding the missing regions to GCP

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java, orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/mount-disks.j2, orchestrator-salt/src/main/resources/salt/salt/disks/service/scripts/mount-instance-storage.j2
=> Merge250tomaster

core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java, orchestrator-salt/src/main/resources/salt/salt/unbound/init.sls
=> CB-15121 Unbound config should be removed after upgrade - fix pillar

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelDecommissionService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelDecommissionServiceTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelServiceTest.java
=> Merge249to250

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupServiceTest.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CMRepositoryVersionUtil.java
=> CB-15276 Add no-proxy hosts to CM proxy settings

README.md
=> CB-15321 Update README with the mock-infrastructure property

core/src/main/java/com/sequenceiq/cloudbreak/service/image/CsdParcelNameMatcher.java, core/src/main/java/com/sequenceiq/cloudbreak/service/image/PreWarmParcelParser.java
=> CB-15332 CsdParcelNameMatcher should log on TRACE level

cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterApi.java, cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/api/ClusterModificationService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelDecommissionService.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerParcelDecommissionServiceTest.java, core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelServiceTest.java
=> Merge250tomaster2

core/src/main/resources/defaults/vm-logs.json
=> CB-15308 Add mount-instance-storage.log to log collection

cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/alarm/AwsNativeCloudWatchService.java, common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java, common/src/main/resources/messages/messages.properties, environment-api/src/main/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentStatus.java, environment-api/src/test/java/com/sequenceiq/environment/api/v1/environment/model/response/EnvironmentStatusTest.java, environment/src/main/java/com/sequenceiq/environment/environment/EnvironmentStatus.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/EnvironmentFlowInformation.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/EnvironmentReactorFlowManager.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/EnvClustersDeleteActions.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/AbstractUpgradeCcmAction.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/UpgradeCcmActions.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/UpgradeCcmState.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/config/UpgradeCcmFlowConfig.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/event/UpgradeCcmEvent.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/event/UpgradeCcmFailedEvent.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/event/UpgradeCcmHandlerSelectors.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/event/UpgradeCcmStateSelectors.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/handler/UpgradeCcmOnDatahubHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/handler/UpgradeCcmOnDatalakeHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/handler/UpgradeCcmOnFreeIpaHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/handler/ValidateUpgradeCcmHandler.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentUpgradeCcmService.java, environment/src/main/java/com/sequenceiq/environment/environment/sync/EnvironmentSyncService.java, environment/src/main/java/com/sequenceiq/environment/metrics/MetricType.java, environment/src/test/java/com/sequenceiq/environment/environment/flow/upgrade/ccm/UpgradeCcmActionsTest.java, environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentUpgradeCcmServiceTest.java
=> CB-14568 CCM upgrade flow skeleton in Environment service

datalake/src/main/java/com/sequenceiq/datalake/flow/detach/SdxDetachActions.java
I verified the changes in the local development environment.
=> CB-15354:  Re-sizing data lake with internal database will fail.

core-api/src/main/resources/definitions/exposed-services.json, core-api/src/test/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollectorTest.java, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_token.xml.j2
=> [CB-15333] Add SSB-SSE-API

datalake/src/main/java/com/sequenceiq/datalake/flow/chain/DatalakeResizeFlowEventChainFactory.java, datalake/src/main/java/com/sequenceiq/datalake/flow/create/SdxCreateActions.java, datalake/src/main/java/com/sequenceiq/datalake/flow/dr/event/DatalakeDatabaseDrStartBaseEvent.java, datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/DatalakeRestoreActions.java, datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/event/DatalakeRestoreFailedEvent.java, datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/event/DatalakeTriggerRestoreEvent.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreService.java, datalake/src/test/java/com/sequenceiq/datalake/flow/dr/restore/DatalakeRestoreActionsTest.java
add check to override sdxId for restore based on sdxName
=> [CDPSDX-3237] restore fails on resize

freeipa/src/test/java/com/sequenceiq/freeipa/flow/stack/termination/action/TerminationServiceTest.java
=> CB-14348 Fixing build caused by 2 conflicting merge

common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/AbstractMetricService.java, common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/MetricService.java, common/src/main/java/com/sequenceiq/cloudbreak/common/metrics/type/MetricType.java, common/src/main/java/com/sequenceiq/cloudbreak/common/service/TransactionMetricsService.java
CB-14957 Introduce metrics for db transactions
CB-14958 Introduce metrics for tx count
=> CB-14957, CB-14958 Introduce metrics for db transactions

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRepairTests.java
=> CB-15422 add wait for CLUSTER_UNREACHABLE state

core/build.gradle, integration-test/build.gradle
=> CB-15044 json-smart to 2.4.5

environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/freeipa/FreeIpaCreationHandler.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java
depends on: https://github.com/hortonworks/cloudbreak/pull/11889
=> CB-15369 E2E smoke test for FreeIPA HA upgrade

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java
=> CB-15466 ignore failing freeipa HA upgrade test on QA

build.gradle, mock-infrastructure/build.gradle, mock-thunderhead/build.gradle, structuredevent-service-cdp/build.gradle
I got NoSuchMethodErrors, but it is resolved in my environment with these modifications. Hopefully it will help others too.
=> CB-15435 force protobuf-java version to run services in Intellij Idea smoothly

flow-api/src/main/java/com/sequenceiq/flow/api/model/operation/OperationProgressStatus.java, flow/src/main/java/com/sequenceiq/flow/converter/OperationDetailsPopulator.java
=> CB-15352. Make sure operation status is always 100% if the flow is completed.

core/src/main/java/com/sequenceiq/cloudbreak/service/diagnostics/DiagnosticsService.java, datalake/src/main/java/com/sequenceiq/datalake/service/sdx/diagnostics/DiagnosticsService.java, flow/src/main/java/com/sequenceiq/flow/repository/FlowLogRepository.java, flow/src/main/java/com/sequenceiq/flow/service/FlowService.java, flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowLogDBService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/diagnostics/DiagnosticsService.java
=> CB-15335. Addendum: use ClassValue class for every flow log db query.

core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/CsdLocationFilter.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/PreWarmParcelLocationFilter.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/CsdLocationFilterTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/image/PreWarmParcelLocationFilterTest.java
=> Merge250tomaster3

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java
After the upgrade is initiated, and while it's in `RUNNING` state, this test will try to create then delete the same A and CNAME records.
This is introduced for both single and HA test.
=> CB-15298 Register/delete DNS A/PTR/CNAME records

integration-test/README.md
=> Update README about remote UMS setup

integration-test/scripts/check-results.sh, integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/azure-longrunning-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/gcp-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/gcp-longrunning-e2e-tests.yaml
=> CB-15495 revert timed out tests checking script and moved sdx repairs tests

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/freeipa/FreeIpaSynchronizeAllUsersAction.java
=> CB-15520 freeipa test fails with conflicting user syncs

datalake/src/main/java/com/sequenceiq/datalake/flow/dr/backup/event/DatalakeDatabaseBackupStartEvent.java, datalake/src/main/java/com/sequenceiq/datalake/flow/dr/event/DatalakeDatabaseDrStartBaseEvent.java, datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/DatalakeRestoreActions.java, datalake/src/main/java/com/sequenceiq/datalake/flow/dr/restore/event/DatalakeDatabaseRestoreStartEvent.java, datalake/src/test/java/com/sequenceiq/datalake/flow/dr/restore/DatalakeRestoreActionsTest.java
changes to unit testing to ensure that the correct SDXID is
passed on to other parts if the flow. Loal testing done to show that a
restore takes place
=> [CDPSDX-3237] to changes need to restore correctly in the context of a resize

core-api/src/main/java/com/sequenceiq/cloudbreak/doc/Notes.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/doc/DistroXOpDescription.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXV1Endpoint.java, core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/StackOperations.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXV1Controller.java, core/src/test/java/com/sequenceiq/cloudbreak/service/StackCommonServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java
1. Internal and dev only API.
2. End to end test pending.
=> CB-15162 API to reset the state of a cluster/cancel a flow

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/FlowUtil.java
=> CB-15561 FlowUtil misleading message in case of flow wait timeout

environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/ClusterDefinitionDeleteHandlerTest.java, environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/NetworkDeleteHandlerTest.java, environment/src/test/java/com/sequenceiq/environment/environment/flow/deletion/handler/RdbmsDeleteHandlerTest.java
=> CB-11559 adding unit test for some env classes

cloudwatch-connector/build.gradle
=> CB-15566. Remove unneeded kudu-client (get there from a copy/paste)

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java
CB-15301 FreeIpa Add/delete/list dns zones tests
=> CB-15301 FreeIpa Add/delete/list dns zones tests

common/src/main/java/com/sequenceiq/cloudbreak/converter/TemporaryStorageConverter.java, common/src/test/java/com/sequenceiq/cloudbreak/converter/TemporaryStorageConverterTest.java, core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/instancegroup/template/InstanceTemplateV4RequestToTemplateConverter.java, core/src/test/java/com/sequenceiq/cloudbreak/converter/InstanceTemplateV4RequestToTemplateConverterTest.java
The commit adds the missing unit test covering temporaryStorage being null
=> CB-14968 - Handle null temporaryStorage in template

orchestrator-salt/src/main/resources/salt/salt/unbound/init.sls
Tested on 4 cluster, master node was repaired in 20 mins on all of them.
=> CB-15588 set cache-max-ttl to 30 sec for unbound

docker-autoscale/Dockerfile, docker-cloudbreak/Dockerfile, docker-datalake/Dockerfile, docker-environment/Dockerfile, docker-freeipa/Dockerfile, docker-redbeams/Dockerfile, integration-test/scripts/compress-results.sh, integration-test/scripts/docker-compose.sh, integration-test/test-image/Dockerfile, mock-infrastructure/Dockerfile, mock-thunderhead/Dockerfile, scripts/build-dev.sh
=> CB-15437 update the extremely old base image for java applications

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/VolumeBuilderUtil.java, cloud-aws-common/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/VolumeBuilderUtilTest.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilder.java, cloud-aws-native/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeInstanceResourceBuilderTest.java, integration-test/src/main/resources/testsuites/e2e/azure-longrunning-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/l0promotion/azure-ephemeral-tests.yaml
=> Merge CB-2.51.0 into master

template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.2.13.json
=> CB-15624 Bump flink and ssb version in 7.2.13 template

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/base/InstanceGroupV4Base.java
=> CB-15600 Maximum DH nodecount should be reflected in api description

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/flow/FreeIpaFlowManager.java
- measure how long did it take to accept (or not accept) an event
- print statistics to log every time a flow is going to be triggered
=> CB-15311 Add flow threadpool statistics to FreeIPA

orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2
=> [CB-15655] Fix SSB-SSE port in topoligy_api

orchestrator-salt/src/main/resources/salt/salt/disks/service/scripts/mount-instance-storage.j2
=> Merge 2.51.0 into master

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java
=> CB-15428 handle concurrent update modification on stack

orchestrator-salt/src/main/resources/salt/salt/postgresql/disaster_recovery/scripts/restore_db.sh
This is an issue introduced with the recent changes done to support backup/restore of profiler databases.
Backup taken on light duty DL can be used to restore a medium-duty datalake. This is a widely used use case. When this is performed database restore fails as the light-duty datalake does not profiler services as the backup location would not have the backups for profiler_agent and profiler_metric databases.
=> CB-15631: Restore-datalake fails during resize-datalake.

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/DistroXClusterUpscaleDownscaleTest.java
This is a correction of my previous commit. Apparently the upscale node count was too high and was rejected by cloudbreak, making the test a fail.
Scaling node count is adjusted to be between the current maximum and the minimum for workers. A micro-refactoring was done to increase readability of node count adjustments.
=> CB-14961 Have a mock test for a large cluster - part 2.

core-api/src/main/resources/definitions/exposed-services.json, core-api/src/test/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollectorTest.java, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_api.xml.j2, orchestrator-salt/src/main/resources/salt/salt/gateway/config/cm/topology_token.xml.j2
Need to revert this to unblock release.
We need to merge this forward for master branch which will make changes disappear there. I would vouch for submitting the whole PR with all the fixes in one commit to master later on.
=> [CB-15333] Revert ssb sse api

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/request/ClusterRepairV4Request.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/DistroXRepairV1Request.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeDistroxFlowEventChainFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/ClusterRepairTriggerEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/service/StackCommonService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/ReactorFlowManagerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/ClusterRepairFlowEventChainFactoryTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeDistroxFlowEventChainFactoryTest.java, core/src/test/java/com/sequenceiq/cloudbreak/job/StackStatusIntegrationTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/ClusterRepairServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterOperationServiceTest.java
=> CB-15571 Disable removeOnly flag for datahub repair

autoscale/src/main/java/com/sequenceiq/periscope/config/DatabaseConfig.java, core/src/main/java/com/sequenceiq/cloudbreak/conf/DatabaseConfig.java, datalake/src/main/java/com/sequenceiq/datalake/configuration/DatabaseConfig.java, environment/src/main/java/com/sequenceiq/environment/configuration/DatabaseConfig.java, freeipa/src/main/java/com/sequenceiq/freeipa/configuration/DatabaseConfig.java, redbeams/src/main/java/com/sequenceiq/redbeams/configuration/DatabaseConfig.java
=> CB-15683 Modify databaseconfig to accept cert bundle

environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentModificationService.java, environment/src/test/java/com/sequenceiq/environment/environment/service/EnvironmentModificationServiceTest.java
CB-15504: Validate the update-azure-encryption-resources request based on key provided
Following changes are made as part of this commit -
- If user tries to update the encryption key for an existing environment -
1. If key doesn't exists - Update the encryption resources after validating the key.
2. If same key already exists - Log info message and return the encryption resources without any error.
3. If some key already exists - throw an error as only adding the key to existing environments is allowed and not modifying the key.
=> CB-15504: Validate the update-azure-encryption-resources request based on key provided

core-model/src/main/java/com/sequenceiq/cloudbreak/domain/view/StackView.java
=> 251 merge to master

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupService.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/MetadataSetupServiceTest.java
tested with a local dev stack using UMS and mov-dev DNS
when a resize happens the CM URL remains the same as the previous light
duty CM URL
=> [CB-13231] support resize for light duty with no loadbalancer

freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/freeipa/cleanup/CleanupServiceTest.java
Ignore DNS zone during DNS record cleanup which gets deleted between the listing of DNS zones and listing records in the zone.
Discovered during FreeIPA upgrade e2e tests.
=> CB-15701 Handle DNS zone is deleted during downscale

cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartUpscaleStartInstancesHandler.java, cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartUpscaleStartInstancesHandlerTest.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerHostHealthyStatusChecker.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerHostHealthyStatusCheckerTest.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartds/StopStartDownscaleFlowService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartus/StopStartUpscaleActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/StopStartUpscaleTriggerEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/cluster/StopStartUpscaleCommissionViaCMRequest.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/api/event/orchestration/StopStartUpscaleCommissionViaCMResult.java, core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/StopStartUpscaleCommissionViaCMHandler.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartus/StopStartUpscaleActionsTest.java, core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/StopStartUpscaleCommissionViaCMHandlerTest.java
=> CB-15444. Add unit tests for scale-up via instance start.

datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEventEndpoint.java, datalake/src/main/java/com/sequenceiq/datalake/controller/SdxEventController.java, datalake/src/main/java/com/sequenceiq/datalake/service/SdxEventsService.java, datalake/src/test/java/com/sequenceiq/datalake/controller/SdxEventControllerTest.java, datalake/src/test/java/com/sequenceiq/datalake/service/sdx/SdxEventsServiceTests.java, structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/repository/CDPStructuredEventRepository.java, structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/CDPStructuredEventService.java, structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/db/CDPStructuredEventDBService.java
=>  CB-15671: Create getAuditEventsZipForResource endpoint in SDX events.

cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupService.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/ClouderaManagerPollingServiceProvider.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/polling/task/ClouderaManagerHostStatusChecker.java, cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerSetupServiceTest.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ClusterServiceRunner.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunner.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/GrainPropertiesService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/HostAttributeDecorator.java, core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/TargetedUpscaleCache.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/TargetedUpscaleSupportService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java, core/src/main/java/com/sequenceiq/cloudbreak/util/StackUtil.java, core/src/main/resources/application.yml, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/ClusterHostServiceRunnerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/GrainPropertiesServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/HostAttributeDecoratorTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/cluster/ClusterManagerUpscaleServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/TargetedUpscaleSupportServiceTest.java, core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationServiceTest.java, mock-infrastructure/src/main/java/com/sequenceiq/mock/salt/response/FileExistsSaltResponse.java, orchestrator-api/src/main/java/com/sequenceiq/cloudbreak/orchestrator/host/HostOrchestrator.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java, orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStates.java
=> CB-14421 Implement targeted salt highstate during upscale (with fixed medium duty repair and upgrade)

build.gradle, docker-autoscale/Dockerfile, docker-autoscale/bootstrap/start_autoscale_app.sh, docker-cloudbreak/Dockerfile, docker-cloudbreak/bootstrap/start_cloudbreak_app.sh, docker-datalake/Dockerfile, docker-datalake/bootstrap/start_datalake_app.sh, docker-environment/Dockerfile, docker-environment/bootstrap/start_environment_app.sh, docker-freeipa/Dockerfile, docker-freeipa/bootstrap/start_freeipa_app.sh, docker-redbeams/Dockerfile, docker-redbeams/bootstrap/start_redbeams_app.sh, integration-test/integcb/Profile_template, integration-test/scripts/docker-compose.sh, integration-test/test-image/Dockerfile, mock-infrastructure/Dockerfile, mock-thunderhead/Dockerfile
=> CB-15647 CB-15648 CB-15649 CB-15650 CB-15654 ubi as base image

cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/AwsNativeResourceBuilderOrderConstants.java, cloud-aws-native/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/resource/instance/AwsNativeEIPResourceBuilder.java, freeipa/src/main/java/com/sequenceiq/freeipa/converter/cloud/ResourceToCloudResourceConverter.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/resource/ResourceAttributeUtil.java
=> CB-15765 fix the deletion of EIPs of FreeIPA on AWS_NATIVE variant

autoscale/src/main/java/com/sequenceiq/periscope/monitor/AbstractMonitor.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/EvaluatorExecutor.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/load/YarnLoadEvaluator.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandler.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerCommissioner.java, cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/AutoscaleV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/StopStartDownscaleFlowEventChainFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/StopStartUpscaleFlowEventChainFactory.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartds/StopStartDownscaleActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartds/StopStartDownscaleContext.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartus/StopStartUpscaleActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartus/StopStartUpscaleContext.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/StopStartDownscaleTriggerEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/event/StopStartUpscaleTriggerEvent.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/service/ReactorFlowManager.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/StackOperationService.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartds/StopStartDownscaleActionsTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/stopstartus/StopStartUpscaleActionsTest.java
- Also removes some unused parameters related to
primaryInstanceGateway, servicesToStart.
=> CB-15156. General cleanup of logging, some TODOs for stop-start branch.

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/CloudFunctionality.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/AwsCloudFunctionality.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/azure/AzureCloudFunctionality.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/gcp/GcpCloudFunctionality.java, integration-test/src/main/resources/testsuites/e2e/aws-distrox-tests.yaml, integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests-for-native.yaml, integration-test/src/main/resources/testsuites/e2e/aws-e2e-tests.yaml, integration-test/src/main/resources/testsuites/e2e/azure-e2e-tests.yaml
Introduce new E2E test case for Azure Disk Encryption with Single Resource Group.
=> CB-15688 Introduce new Single Resource Group E2E test case for Azure Customer Managed Key

common/src/main/java/com/sequenceiq/cloudbreak/auth/crn/Crn.java
Previous pull where this new region was added: https://github.com/hortonworks/cloudbreak/pull/12077/files
=> [CB-15786] Rename CDP partition: cdp-gov to cdp-us-gov

structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/CDPFlowStructuredEventHandler.java
=> CB-15802 Add log to structured event transition

common/src/main/java/com/sequenceiq/cloudbreak/common/event/PayloadContext.java, core/src/main/java/com/sequenceiq/cloudbreak/repository/StackRepository.java, core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackService.java, environment/src/main/java/com/sequenceiq/environment/environment/repository/EnvironmentRepository.java, environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentService.java, freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/FreeIpaService.java, freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/StackService.java
=> CB-15806 Query only the necessary columns for flow stat's PayloadContext

autoscale-api/src/main/java/com/sequenceiq/periscope/common/MessageCode.java, autoscale-api/src/main/resources/messages/messages.properties, autoscale/src/main/java/com/sequenceiq/periscope/controller/DistroXAutoScaleClusterV1Controller.java, autoscale/src/main/java/com/sequenceiq/periscope/controller/validation/AlertValidator.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/evaluator/EvaluatorExecutor.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/CloudbreakCommunicator.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ClusterStatusSyncHandler.java, autoscale/src/main/java/com/sequenceiq/periscope/monitor/handler/ScalingRequest.java, autoscale/src/test/java/com/sequenceiq/periscope/controller/validation/AlertValidatorTest.java, mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
- AlertValidator will check for the entitlement if StopStart mechanism is to be used.
- Added new entitlements to mockUMS for local testing.
=> CB-15673 Entitlement validation checks for StopStart scaling

common/src/main/java/com/sequenceiq/cloudbreak/common/anonymizer/AnonymizerUtil.java, datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidator.java, datalake/src/test/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidatorTest.java
=> CB-15804 Cloud secret key logged to Kibana

common/src/main/java/com/sequenceiq/cloudbreak/common/anonymizer/AnonymizerUtil.java, datalake/src/main/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidator.java, datalake/src/test/java/com/sequenceiq/datalake/service/validation/cloudstorage/CloudStorageValidatorTest.java
=> 2.51 to master

core/src/main/java/com/sequenceiq/cloudbreak/service/image/ImageCatalogService.java
Extend image not found error message with runtime and image catalog name parameters
=> CB-15739 Extend image not found error message

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxResizeTests.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/SdxUtil.java
E2E test for datalake resize functionality.
=> CB-13414: Add e2e tests for re-sizing of the datalake.

core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java, core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/response/upgrade/StackCcmUpgradeV4Response.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/endpoint/DistroXUpgradeV1Endpoint.java, core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/upgrade/DistroXCcmUpgradeV1Response.java, core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java, core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ccm/StackCcmUpgradeService.java, core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXUpgradeV1Controller.java, core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/StackV4ControllerTest.java, core/src/test/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXUpgradeV1ControllerTest.java
=> CB-14577 add CCM upgrade endpoint to distrox and core service

orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/find-device-and-format.j2, orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/mount-disks.j2
=> CB-13489 Mount and format scripts will handle no attached or local disks

cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/mapper/SdkClientExceptionMapper.java
=> CB-15402 Fix NPE if message from AWS or methodName is null.

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/CustomConfigurationsV4Controller.java
=> CB-15908: Removing InternalOnly annotation to make endpoint available for the UI

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java
Get keytab for host
https://jira.cloudera.com/browse/CB-15294
=> CB-15294 Generate hostkeytab

core/src/main/java/com/sequenceiq/cloudbreak/service/stack/TargetedUpscaleSupportService.java
=> CB-14421 logging should be fixed regarding unbound entitlement check

freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ChildEnvironmentService.java, freeipa/src/test/java/com/sequenceiq/freeipa/service/stack/ChildEnvironmentServiceTest.java
=> CB-15904 Catch optimistic locking exception when detaching child env

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/context/TestContext.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractSdxTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/AbstractTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/CloudbreakTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/blueprint/BlueprintTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/clustertemplate/ClusterTemplateTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/credential/CredentialTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/customconfigs/CustomConfigurationsTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/distrox/DistroXTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/environment/EnvironmentTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/freeipa/FreeIpaTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/imagecatalog/ImageCatalogTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/kerberos/KerberosTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/ldap/LdapTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/recipe/RecipeTestDto.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/stack/StackTestDto.java
=> CB-15907 Multiple Raw use of parameterized class in integ test module

core/scripts/mount-ephemeral-recipe.sh, orchestrator-salt/src/main/resources/salt/bootstrapnodes/mount-disks.sh, orchestrator-salt/src/main/resources/salt/salt/disks/mount/scripts/mount-disks.j2, orchestrator-salt/src/main/resources/salt/salt/disks/service/scripts/mount-instance-storage.j2
=> CB-15724 Set directory permission on volumes to 1777

freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/ChildEnvironmentService.java
=> CB-15904 Add exception to log message

core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/StackV4RequestToStackConverter.java, core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverter.java, structuredevent-model/src/main/java/com/sequenceiq/cloudbreak/structuredevent/event/StackDetails.java, structuredevent-service-legacy/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToCDPClusterDetailsConverter.java, structuredevent-service-legacy/src/test/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/StructuredEventToCDPClusterDetailsConverterTest.java, template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProvider.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/CentralCmTemplateUpdaterTest.java, template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProviderTest.java, template-manager-cmtemplate/src/test/resources/input/core-settings-empty.bp, template-manager-cmtemplate/src/test/resources/input/core-settings.bp, template-manager-cmtemplate/src/test/resources/output/core-settings-empty.bp, template-manager-cmtemplate/src/test/resources/output/core-settings.bp
=> CB-15896 , CB-15917 Fixing solr issue and edh

core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/StackStatusFinalizer.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/config/update/PillarConfigUpdateService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/downscale/StackDownscaleService.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateActions.java, core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/stack/provision/service/StackCreationService.java, core/src/main/java/com/sequenceiq/cloudbreak/service/StackUpdater.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/StackStatusFinalizerTest.java, core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/stack/image/update/StackImageUpdateActionsTest.java
=> CB-15867 Cluster and stack status reason are not filled in EDH

datalake/src/main/java/com/sequenceiq/datalake/controller/SdxEventController.java
=> CB-15944 quick fix for authz of SDX event API

core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/CustomConfigurationsV4Controller.java
=> CB-15908 Removing InternalOnly annotation to make endpoint available for UI

datalake/src/main/java/com/sequenceiq/datalake/service/SdxEventsService.java
=> 2.52 to master

core/src/main/java/com/sequenceiq/cloudbreak/service/decorator/TemplateDecorator.java, core/src/test/java/com/sequenceiq/cloudbreak/service/decorator/TemplateDecoratorTest.java
Eliminate GetPlatformVMTypes request if it does not need. If we send the volume count and size in the request we can skip the VMTypes fetching"
This reverts commit 6b4c57552af22105507451c95d10a79484f91c46.
=> Revert "CB-15919 Eliminate GetPlatformVMTypes request if it does not need.

datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxController.java
=> [CB-13940] require new resize right in order to perform a restore

integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxRecoveryTests.java
=> CB-16005 Add new build repo mirrors to recovery test

freeipa/src/main/resources/schema/app/20220215144919_CB-16132_create_operationId_index_for_operation.sql
=> CB-16132 create operationId index for operation

auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/AuthorizationClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/PersonalResourceViewClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java, auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/config/UmsClientConfig.java, auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/GrpcUmsClientTest.java, grpc-common/src/main/java/com/sequenceiq/cloudbreak/grpc/util/GrpcUtil.java, integration-test/src/main/java/com/sequenceiq/it/cloudbreak/UmsClient.java
=> CB-16138 add ums grpc timeout
